/******************************************************************************
 * COPYRIGHT CRAY INC. ar_bte_descs_h.h
 * FILE: ar_bte_descs_h.h
 * Created by v2h.c on Wed Oct  8 14:38:58 2014
 ******************************************************************************/

#ifndef _AR_BTE_DESCS_H_H_
#define _AR_BTE_DESCS_H_H_

#ifndef _GENERIC_DESCD_T_
#define _GENERIC_DESCD_T_
typedef struct {
	char* _name;		/* Field's name */
	uint32_t _bpos;		/* Field's bit postion in quad word */
	uint64_t _mask;		/* Field's bit mask in quad word */
	int _index;		/* Field's quad word index */
} generic_descd_t;
#endif

#ifndef _GENERIC_DESC_T_
#define _GENERIC_DESC_T_
typedef struct {
	char* _name;		/* Descriptor name */
	uint64_t _addr;		/* Descriptor address */
	int _size;		/* Size in bytes of Descriptor */
	int _depth;		/* Number of Descriptor instances */
	const generic_descd_t *_info;	/* Descriptor detail */
} generic_desc_t;
#endif

/*
 *  AR BTE DESCRIPTOR DETAIL DECLARATIONS
 */
static const generic_descd_t _ar_nic_bte_cfg_tbl_desc_detail[] = {
    { "DEST_USER_DATA", AR_NIC_BTE_CFG_TBL_DESC_DEST_USER_DATA_BP, AR_NIC_BTE_CFG_TBL_DESC_DEST_USER_DATA_MASK, 4 },
    { "RESERVED_255", AR_NIC_BTE_CFG_TBL_DESC_RESERVED_255_BP, AR_NIC_BTE_CFG_TBL_DESC_RESERVED_255_MASK, 3 },
    { "WC", AR_NIC_BTE_CFG_TBL_DESC_WC_BP, AR_NIC_BTE_CFG_TBL_DESC_WC_MASK, 3 },
    { "TX_STS", AR_NIC_BTE_CFG_TBL_DESC_TX_STS_BP, AR_NIC_BTE_CFG_TBL_DESC_TX_STS_MASK, 3 },
    { "TIMEOUT_ERR", AR_NIC_BTE_CFG_TBL_DESC_TIMEOUT_ERR_BP, AR_NIC_BTE_CFG_TBL_DESC_TIMEOUT_ERR_MASK, 3 },
    { "BTE_COMPLETE", AR_NIC_BTE_CFG_TBL_DESC_BTE_COMPLETE_BP, AR_NIC_BTE_CFG_TBL_DESC_BTE_COMPLETE_MASK, 3 },
    { "FMAL", AR_NIC_BTE_CFG_TBL_DESC_FMAL_BP, AR_NIC_BTE_CFG_TBL_DESC_FMAL_MASK, 3 },
    { "RC", AR_NIC_BTE_CFG_TBL_DESC_RC_BP, AR_NIC_BTE_CFG_TBL_DESC_RC_MASK, 3 },
    { "RD_RO", AR_NIC_BTE_CFG_TBL_DESC_RD_RO_BP, AR_NIC_BTE_CFG_TBL_DESC_RD_RO_MASK, 3 },
    { "RD_NO_SNOOP", AR_NIC_BTE_CFG_TBL_DESC_RD_NO_SNOOP_BP, AR_NIC_BTE_CFG_TBL_DESC_RD_NO_SNOOP_MASK, 3 },
    { "SRC_CQ_DATA", AR_NIC_BTE_CFG_TBL_DESC_SRC_CQ_DATA_BP, AR_NIC_BTE_CFG_TBL_DESC_SRC_CQ_DATA_MASK, 3 },
    { "DELAYED_IRQ_EN", AR_NIC_BTE_CFG_TBL_DESC_DELAYED_IRQ_EN_BP, AR_NIC_BTE_CFG_TBL_DESC_DELAYED_IRQ_EN_MASK, 2 },
    { "IRQ_MODE", AR_NIC_BTE_CFG_TBL_DESC_IRQ_MODE_BP, AR_NIC_BTE_CFG_TBL_DESC_IRQ_MODE_MASK, 2 },
    { "BTE_FENCE", AR_NIC_BTE_CFG_TBL_DESC_BTE_FENCE_BP, AR_NIC_BTE_CFG_TBL_DESC_BTE_FENCE_MASK, 2 },
    { "BTE_IMMEDIATE", AR_NIC_BTE_CFG_TBL_DESC_BTE_IMMEDIATE_BP, AR_NIC_BTE_CFG_TBL_DESC_BTE_IMMEDIATE_MASK, 2 },
    { "TX_CONCATENATE", AR_NIC_BTE_CFG_TBL_DESC_TX_CONCATENATE_BP, AR_NIC_BTE_CFG_TBL_DESC_TX_CONCATENATE_MASK, 2 },
    { "LOC_PTAG", AR_NIC_BTE_CFG_TBL_DESC_LOC_PTAG_BP, AR_NIC_BTE_CFG_TBL_DESC_LOC_PTAG_MASK, 2 },
    { "REM_PTAG", AR_NIC_BTE_CFG_TBL_DESC_REM_PTAG_BP, AR_NIC_BTE_CFG_TBL_DESC_REM_PTAG_MASK, 2 },
    { "SRC_CQH", AR_NIC_BTE_CFG_TBL_DESC_SRC_CQH_BP, AR_NIC_BTE_CFG_TBL_DESC_SRC_CQH_MASK, 2 },
    { "XFER_LEN", AR_NIC_BTE_CFG_TBL_DESC_XFER_LEN_BP, AR_NIC_BTE_CFG_TBL_DESC_XFER_LEN_MASK, 2 },
    { "REM_MDH", AR_NIC_BTE_CFG_TBL_DESC_REM_MDH_BP, AR_NIC_BTE_CFG_TBL_DESC_REM_MDH_MASK, 1 },
    { "LOC_MDH", AR_NIC_BTE_CFG_TBL_DESC_LOC_MDH_BP, AR_NIC_BTE_CFG_TBL_DESC_LOC_MDH_MASK, 1 },
    { "LOC_PHYS_ADDR", AR_NIC_BTE_CFG_TBL_DESC_LOC_PHYS_ADDR_BP, AR_NIC_BTE_CFG_TBL_DESC_LOC_PHYS_ADDR_MASK, 1 },
    { "LOC_MEM_OFFSET", AR_NIC_BTE_CFG_TBL_DESC_LOC_MEM_OFFSET_BP, AR_NIC_BTE_CFG_TBL_DESC_LOC_MEM_OFFSET_MASK, 1 },
    { "NTT_EN", AR_NIC_BTE_CFG_TBL_DESC_NTT_EN_BP, AR_NIC_BTE_CFG_TBL_DESC_NTT_EN_MASK, 0 },
    { "NAT_EN", AR_NIC_BTE_CFG_TBL_DESC_NAT_EN_BP, AR_NIC_BTE_CFG_TBL_DESC_NAT_EN_MASK, 0 },
    { "SRC_SSID_CQ_EN", AR_NIC_BTE_CFG_TBL_DESC_SRC_SSID_CQ_EN_BP, AR_NIC_BTE_CFG_TBL_DESC_SRC_SSID_CQ_EN_MASK, 0 },
    { "SRC_BTE_CQ_EN", AR_NIC_BTE_CFG_TBL_DESC_SRC_BTE_CQ_EN_BP, AR_NIC_BTE_CFG_TBL_DESC_SRC_BTE_CQ_EN_MASK, 0 },
    { "BTE_OP", AR_NIC_BTE_CFG_TBL_DESC_BTE_OP_BP, AR_NIC_BTE_CFG_TBL_DESC_BTE_OP_MASK, 0 },
    { "DEST_ENDPOINT", AR_NIC_BTE_CFG_TBL_DESC_DEST_ENDPOINT_BP, AR_NIC_BTE_CFG_TBL_DESC_DEST_ENDPOINT_MASK, 0 },
    { "REM_MEM_OFFSET", AR_NIC_BTE_CFG_TBL_DESC_REM_MEM_OFFSET_BP, AR_NIC_BTE_CFG_TBL_DESC_REM_MEM_OFFSET_MASK, 0 },
    { NULL, 0, 0, 0 }
};
static const generic_descd_t _ar_nic_bte_cfg_chan_desc_detail[] = {
    { "SSIDS_IN_USE_CLR", AR_NIC_BTE_CFG_CHAN_DESC_SSIDS_IN_USE_CLR_BP, AR_NIC_BTE_CFG_CHAN_DESC_SSIDS_IN_USE_CLR_MASK, 5 },
    { "FMA_ALLOW_NON_PRIV", AR_NIC_BTE_CFG_CHAN_DESC_FMA_ALLOW_NON_PRIV_BP, AR_NIC_BTE_CFG_CHAN_DESC_FMA_ALLOW_NON_PRIV_MASK, 4 },
    { "TX_WR_IDX", AR_NIC_BTE_CFG_CHAN_DESC_TX_WR_IDX_BP, AR_NIC_BTE_CFG_CHAN_DESC_TX_WR_IDX_MASK, 3 },
    { "RD_TPH", AR_NIC_BTE_CFG_CHAN_DESC_RD_TPH_BP, AR_NIC_BTE_CFG_CHAN_DESC_RD_TPH_MASK, 2 },
    { "WR_TPH", AR_NIC_BTE_CFG_CHAN_DESC_WR_TPH_BP, AR_NIC_BTE_CFG_CHAN_DESC_WR_TPH_MASK, 2 },
    { "RD_TC", AR_NIC_BTE_CFG_CHAN_DESC_RD_TC_BP, AR_NIC_BTE_CFG_CHAN_DESC_RD_TC_MASK, 2 },
    { "WR_TC", AR_NIC_BTE_CFG_CHAN_DESC_WR_TC_BP, AR_NIC_BTE_CFG_CHAN_DESC_WR_TC_MASK, 2 },
    { "PI_TAIL_TIMEOUT_VAL", AR_NIC_BTE_CFG_CHAN_DESC_PI_TAIL_TIMEOUT_VAL_BP, AR_NIC_BTE_CFG_CHAN_DESC_PI_TAIL_TIMEOUT_VAL_MASK, 2 },
    { "SSIDS_IN_USE_CLR_EN", AR_NIC_BTE_CFG_CHAN_DESC_SSIDS_IN_USE_CLR_EN_BP, AR_NIC_BTE_CFG_CHAN_DESC_SSIDS_IN_USE_CLR_EN_MASK, 2 },
    { "TX_RD_IDX", AR_NIC_BTE_CFG_CHAN_DESC_TX_RD_IDX_BP, AR_NIC_BTE_CFG_CHAN_DESC_TX_RD_IDX_MASK, 2 },
    { "MAX_NUM_SSIDS", AR_NIC_BTE_CFG_CHAN_DESC_MAX_NUM_SSIDS_BP, AR_NIC_BTE_CFG_CHAN_DESC_MAX_NUM_SSIDS_MASK, 1 },
    { "FMA_ANP_HW_CLR_EN", AR_NIC_BTE_CFG_CHAN_DESC_FMA_ANP_HW_CLR_EN_BP, AR_NIC_BTE_CFG_CHAN_DESC_FMA_ANP_HW_CLR_EN_MASK, 1 },
    { "FMA_EN", AR_NIC_BTE_CFG_CHAN_DESC_FMA_EN_BP, AR_NIC_BTE_CFG_CHAN_DESC_FMA_EN_MASK, 1 },
    { "FMA_NO_BTE_SEND", AR_NIC_BTE_CFG_CHAN_DESC_FMA_NO_BTE_SEND_BP, AR_NIC_BTE_CFG_CHAN_DESC_FMA_NO_BTE_SEND_MASK, 1 },
    { "TX_IRQ_EN", AR_NIC_BTE_CFG_CHAN_DESC_TX_IRQ_EN_BP, AR_NIC_BTE_CFG_CHAN_DESC_TX_IRQ_EN_MASK, 1 },
    { "TX_EN", AR_NIC_BTE_CFG_CHAN_DESC_TX_EN_BP, AR_NIC_BTE_CFG_CHAN_DESC_TX_EN_MASK, 1 },
    { "TX_RST", AR_NIC_BTE_CFG_CHAN_DESC_TX_RST_BP, AR_NIC_BTE_CFG_CHAN_DESC_TX_RST_MASK, 1 },
    { "TX_DBG", AR_NIC_BTE_CFG_CHAN_DESC_TX_DBG_BP, AR_NIC_BTE_CFG_CHAN_DESC_TX_DBG_MASK, 1 },
    { "CPU_TX_BASE_ADDR", AR_NIC_BTE_CFG_CHAN_DESC_CPU_TX_BASE_ADDR_BP, AR_NIC_BTE_CFG_CHAN_DESC_CPU_TX_BASE_ADDR_MASK, 1 },
    { "FMA_MAX_XFER_LEN", AR_NIC_BTE_CFG_CHAN_DESC_FMA_MAX_XFER_LEN_BP, AR_NIC_BTE_CFG_CHAN_DESC_FMA_MAX_XFER_LEN_MASK, 0 },
    { "TX_TIMEOUT_VAL", AR_NIC_BTE_CFG_CHAN_DESC_TX_TIMEOUT_VAL_BP, AR_NIC_BTE_CFG_CHAN_DESC_TX_TIMEOUT_VAL_MASK, 0 },
    { "IRQ_IDX", AR_NIC_BTE_CFG_CHAN_DESC_IRQ_IDX_BP, AR_NIC_BTE_CFG_CHAN_DESC_IRQ_IDX_MASK, 0 },
    { "TX_IDV", AR_NIC_BTE_CFG_CHAN_DESC_TX_IDV_BP, AR_NIC_BTE_CFG_CHAN_DESC_TX_IDV_MASK, 0 },
    { NULL, 0, 0, 0 }
};

/*
 *  AR BTE DESCRIPTOR DECLARATIONS
 */
static const generic_desc_t _ar_nic_bte_cfg_tbl_desc = {
    "AR_NIC_BTE_CFG_TBL_DESC", AR_NIC_BTE_CFG_TBL_DESC, AR_NIC_BTE_CFG_TBL_DESC_DESC_INCR, AR_NIC_BTE_CFG_TBL_DESC_N_ENTRY, _ar_nic_bte_cfg_tbl_desc_detail
};
static const generic_desc_t _ar_nic_bte_cfg_chan_desc = {
    "AR_NIC_BTE_CFG_CHAN_DESC", AR_NIC_BTE_CFG_CHAN_DESC, AR_NIC_BTE_CFG_CHAN_DESC_DESC_INCR, AR_NIC_BTE_CFG_CHAN_DESC_N_ENTRY, _ar_nic_bte_cfg_chan_desc_detail
};

/*
 *  INSTALL AR BTE DESCRIPTORS
 */
static const generic_desc_t* _ar_bte_descs[] = {
    &_ar_nic_bte_cfg_tbl_desc,
    &_ar_nic_bte_cfg_chan_desc,
    NULL
};

#endif
