/******************************************************************************
 * COPYRIGHT CRAY INC. ar_cq_mmrs_h.h
 * FILE: ar_cq_mmrs_h.h
 * Created by v2h.c on Wed Oct  8 14:38:58 2014
 ******************************************************************************/

#ifndef _AR_CQ_MMRS_H_H_
#define _AR_CQ_MMRS_H_H_

#ifdef __GNUC__
#define _unused __attribute__((unused))
#else
#define _unused
#endif

#ifndef _GENERIC_MMRD_T_
#define _GENERIC_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint64_t _mask;		/* Field bit mask */
} generic_mmrd_t;
#endif

#ifndef _ERRCAT_MMRD_T_
#define _ERRCAT_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint32_t _ec;		/* Field error category */
} errcat_mmrd_t;
#endif

#ifndef _GENERIC_MMR_T_
#define _GENERIC_MMR_T_
typedef struct {
	char* _name;		/* MMR name */
	uint64_t _addr;		/* MMR address */
	int _size;		/* Size in bytes of MMR */
	int _depth;		/* Number of MMR instances */
	const generic_mmrd_t *_info;	/* MMR detail */
} generic_mmr_t;
#endif

static const generic_mmr_t* _ar_cq_mmrs[] _unused;	/* CQ Array */

/*
 *  AR CQ MMR DETAIL DECLARATIONS
 */
static const generic_mmrd_t _ar_nic_cq_mmr_ring_0_hi_cq_detail[] = {
    { "UNUSED_145_116", AR_NIC_CQ_MMR_RING_0_HI_CQ_UNUSED_145_116_BP, AR_NIC_CQ_MMR_RING_0_HI_CQ_UNUSED_145_116_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_mmr_ring_0_mid_cq_detail[] = {
    { "UNUSED_127_116", AR_NIC_CQ_MMR_RING_0_MID_CQ_UNUSED_127_116_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_UNUSED_127_116_MASK },
    { "CNTR_TRANS_CMP_Q_PARITY_ERR", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_TRANS_CMP_Q_PARITY_ERR_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_TRANS_CMP_Q_PARITY_ERR_MASK },
    { "CNTR_SSID_INPUT_EVENT_DATA_PARITY_ERR", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_SSID_INPUT_EVENT_DATA_PARITY_ERR_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_SSID_INPUT_EVENT_DATA_PARITY_ERR_MASK },
    { "CNTR_BTE_INPUT_EVENT_DATA_PARITY_ERR", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_BTE_INPUT_EVENT_DATA_PARITY_ERR_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_BTE_INPUT_EVENT_DATA_PARITY_ERR_MASK },
    { "CNTR_DLA_INPUT_EVENT_DATA_PARITY_ERR", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DLA_INPUT_EVENT_DATA_PARITY_ERR_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DLA_INPUT_EVENT_DATA_PARITY_ERR_MASK },
    { "CNTR_RMT_INPUT_EVENT_DATA_PARITY_ERR", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_RMT_INPUT_EVENT_DATA_PARITY_ERR_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_RMT_INPUT_EVENT_DATA_PARITY_ERR_MASK },
    { "CNTR_RMT_INPUT_RMT_DATA_PARITY_ERR", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_RMT_INPUT_RMT_DATA_PARITY_ERR_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_RMT_INPUT_RMT_DATA_PARITY_ERR_MASK },
    { "CNTR_DESC_TBL_MBE3", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DESC_TBL_MBE3_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DESC_TBL_MBE3_MASK },
    { "CNTR_DESC_TBL_MBE2", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DESC_TBL_MBE2_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DESC_TBL_MBE2_MASK },
    { "CNTR_DESC_TBL_MBE1", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DESC_TBL_MBE1_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DESC_TBL_MBE1_MASK },
    { "CNTR_DESC_TBL_MBE0", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DESC_TBL_MBE0_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DESC_TBL_MBE0_MASK },
    { "CNTR_DESC_TBL_SBE3", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DESC_TBL_SBE3_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DESC_TBL_SBE3_MASK },
    { "CNTR_DESC_TBL_SBE2", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DESC_TBL_SBE2_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DESC_TBL_SBE2_MASK },
    { "CNTR_DESC_TBL_SBE1", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DESC_TBL_SBE1_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DESC_TBL_SBE1_MASK },
    { "CNTR_DESC_TBL_SBE0", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DESC_TBL_SBE0_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DESC_TBL_SBE0_MASK },
    { "CNTR_NPT_STALLED", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_NPT_STALLED_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_NPT_STALLED_MASK },
    { "CNTR_NPT_FLIT", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_NPT_FLIT_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_NPT_FLIT_MASK },
    { "CNTR_NPT_PKT", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_NPT_PKT_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_NPT_PKT_MASK },
    { "CNTR_RMT_DROPPED", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_RMT_DROPPED_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_RMT_DROPPED_MASK },
    { "CNTR_DLA_DROPPED", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DLA_DROPPED_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DLA_DROPPED_MASK },
    { "CNTR_BTE_DROPPED", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_BTE_DROPPED_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_BTE_DROPPED_MASK },
    { "CNTR_SSID_DROPPED", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_SSID_DROPPED_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_SSID_DROPPED_MASK },
    { "CNTR_RMT_BLOCKED", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_RMT_BLOCKED_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_RMT_BLOCKED_MASK },
    { "CNTR_DLA_BLOCKED", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DLA_BLOCKED_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DLA_BLOCKED_MASK },
    { "CNTR_BTE_BLOCKED", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_BTE_BLOCKED_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_BTE_BLOCKED_MASK },
    { "CNTR_SSID_BLOCKED", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_SSID_BLOCKED_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_SSID_BLOCKED_MASK },
    { "CNTR_RMT_STALLED", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_RMT_STALLED_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_RMT_STALLED_MASK },
    { "CNTR_DLA_STALLED", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DLA_STALLED_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DLA_STALLED_MASK },
    { "CNTR_BTE_STALLED", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_BTE_STALLED_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_BTE_STALLED_MASK },
    { "CNTR_SSID_STALLED", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_SSID_STALLED_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_SSID_STALLED_MASK },
    { "CNTR_FMA", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_FMA_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_FMA_MASK },
    { "CNTR_RMT", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_RMT_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_RMT_MASK },
    { "CNTR_DLA", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DLA_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_DLA_MASK },
    { "CNTR_BTE", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_BTE_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_BTE_MASK },
    { "CNTR_SSID", AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_SSID_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_CNTR_SSID_MASK },
    { "UNUSED_81_35", AR_NIC_CQ_MMR_RING_0_MID_CQ_UNUSED_81_35_BP, AR_NIC_CQ_MMR_RING_0_MID_CQ_UNUSED_81_35_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_mmr_ring_0_lo_cq_detail[] = {
    { "UNUSED_81_35", AR_NIC_CQ_MMR_RING_0_LO_CQ_UNUSED_81_35_BP, AR_NIC_CQ_MMR_RING_0_LO_CQ_UNUSED_81_35_MASK },
    { "R_Q_CQ_LB_OS_IRQ", AR_NIC_CQ_MMR_RING_0_LO_CQ_R_Q_CQ_LB_OS_IRQ_BP, AR_NIC_CQ_MMR_RING_0_LO_CQ_R_Q_CQ_LB_OS_IRQ_MASK },
    { "R_Q_CQ_LB_HSS_IRQ", AR_NIC_CQ_MMR_RING_0_LO_CQ_R_Q_CQ_LB_HSS_IRQ_BP, AR_NIC_CQ_MMR_RING_0_LO_CQ_R_Q_CQ_LB_HSS_IRQ_MASK },
    { "R_Q_CQ_LB_WR_ACK", AR_NIC_CQ_MMR_RING_0_LO_CQ_R_Q_CQ_LB_WR_ACK_BP, AR_NIC_CQ_MMR_RING_0_LO_CQ_R_Q_CQ_LB_WR_ACK_MASK },
    { "R_Q_CQ_LB_RSP_15_0", AR_NIC_CQ_MMR_RING_0_LO_CQ_R_Q_CQ_LB_RSP_15_0_BP, AR_NIC_CQ_MMR_RING_0_LO_CQ_R_Q_CQ_LB_RSP_15_0_MASK },
    { "I_LB_CQ_REQ_15_0", AR_NIC_CQ_MMR_RING_0_LO_CQ_I_LB_CQ_REQ_15_0_BP, AR_NIC_CQ_MMR_RING_0_LO_CQ_I_LB_CQ_REQ_15_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_err_flg_1_hi_cq_detail[] = {
    { "UNUSED_145_86", AR_NIC_CQ_ERR_FLG_1_HI_CQ_UNUSED_145_86_BP, AR_NIC_CQ_ERR_FLG_1_HI_CQ_UNUSED_145_86_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_err_flg_1_mid_cq_detail[] = {
    { "UNUSED_127_86", AR_NIC_CQ_ERR_FLG_1_MID_CQ_UNUSED_127_86_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_UNUSED_127_86_MASK },
    { "CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR", AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR_MASK },
    { "CQ_LCL_PARITY_ERR", AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_LCL_PARITY_ERR_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_LCL_PARITY_ERR_MASK },
    { "CQ_LCL_DROPPED_EVENT", AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_LCL_DROPPED_EVENT_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_LCL_DROPPED_EVENT_MASK },
    { "CQ_LCL_IDX_BOUNDS", AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_LCL_IDX_BOUNDS_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_LCL_IDX_BOUNDS_MASK },
    { "CQ_LCL_NAT_ERR", AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_LCL_NAT_ERR_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_LCL_NAT_ERR_MASK },
    { "CQ_LCL_OVERRUN_EVENT", AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_LCL_OVERRUN_EVENT_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_LCL_OVERRUN_EVENT_MASK },
    { "CQ_LCL_DISABLED_CQ", AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_LCL_DISABLED_CQ_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_LCL_DISABLED_CQ_MASK },
    { "CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR", AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR_MASK },
    { "CQ_RMT_PARITY_ERR", AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_RMT_PARITY_ERR_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_RMT_PARITY_ERR_MASK },
    { "CQ_RMT_DROPPED_EVENT", AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_RMT_DROPPED_EVENT_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_RMT_DROPPED_EVENT_MASK },
    { "CQ_RMT_IDX_BOUNDS", AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_RMT_IDX_BOUNDS_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_RMT_IDX_BOUNDS_MASK },
    { "CQ_RMT_NAT_ERR", AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_RMT_NAT_ERR_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_RMT_NAT_ERR_MASK },
    { "CQ_RMT_OVERRUN_EVENT", AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_RMT_OVERRUN_EVENT_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_RMT_OVERRUN_EVENT_MASK },
    { "CQ_RMT_DISABLED_CQ", AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_RMT_DISABLED_CQ_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_RMT_DISABLED_CQ_MASK },
    { "CQ_DESC_TBL_SBE", AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_DESC_TBL_SBE_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_DESC_TBL_SBE_MASK },
    { "CQ_DESC_TBL_MBE", AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_DESC_TBL_MBE_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_CQ_DESC_TBL_MBE_MASK },
    { "FMA_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FLG_1_MID_CQ_FMA_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_FMA_CQ_INPUT_Q_OVERRUN_MASK },
    { "SSID_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FLG_1_MID_CQ_SSID_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_SSID_CQ_INPUT_Q_OVERRUN_MASK },
    { "RMT_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FLG_1_MID_CQ_RMT_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_RMT_CQ_INPUT_Q_OVERRUN_MASK },
    { "DLA_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FLG_1_MID_CQ_DLA_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_DLA_CQ_INPUT_Q_OVERRUN_MASK },
    { "BTE_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FLG_1_MID_CQ_BTE_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_BTE_CQ_INPUT_Q_OVERRUN_MASK },
    { "DIAG_ONLY", AR_NIC_CQ_ERR_FLG_1_MID_CQ_DIAG_ONLY_BP, AR_NIC_CQ_ERR_FLG_1_MID_CQ_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_err_flg_1_lo_cq_detail[] = {
    { "UNUSED_63_22", AR_NIC_CQ_ERR_FLG_1_LO_CQ_UNUSED_63_22_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_UNUSED_63_22_MASK },
    { "I_CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR", AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR_MASK },
    { "I_CQ_LCL_PARITY_ERR", AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_LCL_PARITY_ERR_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_LCL_PARITY_ERR_MASK },
    { "I_CQ_LCL_DROPPED_EVENT", AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_LCL_DROPPED_EVENT_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_LCL_DROPPED_EVENT_MASK },
    { "I_CQ_LCL_IDX_BOUNDS", AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_LCL_IDX_BOUNDS_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_LCL_IDX_BOUNDS_MASK },
    { "I_CQ_LCL_NAT_ERR", AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_LCL_NAT_ERR_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_LCL_NAT_ERR_MASK },
    { "I_CQ_LCL_OVERRUN_EVENT", AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_LCL_OVERRUN_EVENT_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_LCL_OVERRUN_EVENT_MASK },
    { "I_CQ_LCL_DISABLED_CQ", AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_LCL_DISABLED_CQ_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_LCL_DISABLED_CQ_MASK },
    { "I_CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR", AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR_MASK },
    { "I_CQ_RMT_PARITY_ERR", AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_RMT_PARITY_ERR_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_RMT_PARITY_ERR_MASK },
    { "I_CQ_RMT_DROPPED_EVENT", AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_RMT_DROPPED_EVENT_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_RMT_DROPPED_EVENT_MASK },
    { "I_CQ_RMT_IDX_BOUNDS", AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_RMT_IDX_BOUNDS_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_RMT_IDX_BOUNDS_MASK },
    { "I_CQ_RMT_NAT_ERR", AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_RMT_NAT_ERR_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_RMT_NAT_ERR_MASK },
    { "I_CQ_RMT_OVERRUN_EVENT", AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_RMT_OVERRUN_EVENT_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_RMT_OVERRUN_EVENT_MASK },
    { "I_CQ_RMT_DISABLED_CQ", AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_RMT_DISABLED_CQ_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_RMT_DISABLED_CQ_MASK },
    { "I_CQ_DESC_TBL_SBE", AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_DESC_TBL_SBE_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_DESC_TBL_SBE_MASK },
    { "I_CQ_DESC_TBL_MBE", AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_DESC_TBL_MBE_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_CQ_DESC_TBL_MBE_MASK },
    { "I_FMA_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_FMA_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_FMA_CQ_INPUT_Q_OVERRUN_MASK },
    { "I_SSID_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_SSID_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_SSID_CQ_INPUT_Q_OVERRUN_MASK },
    { "I_RMT_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_RMT_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_RMT_CQ_INPUT_Q_OVERRUN_MASK },
    { "I_DLA_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_DLA_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_DLA_CQ_INPUT_Q_OVERRUN_MASK },
    { "I_BTE_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_BTE_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_I_BTE_CQ_INPUT_Q_OVERRUN_MASK },
    { "UNUSED_0", AR_NIC_CQ_ERR_FLG_1_LO_CQ_UNUSED_0_BP, AR_NIC_CQ_ERR_FLG_1_LO_CQ_UNUSED_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_cq_npt_flit_2_hi_cq_detail[] = {
    { "R_Q_CQ_NPT_REQ_SB", AR_NIC_CQ_CQ_NPT_FLIT_2_HI_CQ_R_Q_CQ_NPT_REQ_SB_BP, AR_NIC_CQ_CQ_NPT_FLIT_2_HI_CQ_R_Q_CQ_NPT_REQ_SB_MASK },
    { "R_Q_CQ_NPT_REQ_FLIT", AR_NIC_CQ_CQ_NPT_FLIT_2_HI_CQ_R_Q_CQ_NPT_REQ_FLIT_BP, AR_NIC_CQ_CQ_NPT_FLIT_2_HI_CQ_R_Q_CQ_NPT_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_cq_npt_flit_2_mid_cq_detail[] = {
    { "R_Q_CQ_NPT_REQ_FLIT", AR_NIC_CQ_CQ_NPT_FLIT_2_MID_CQ_R_Q_CQ_NPT_REQ_FLIT_BP, AR_NIC_CQ_CQ_NPT_FLIT_2_MID_CQ_R_Q_CQ_NPT_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_cq_npt_flit_2_lo_cq_detail[] = {
    { "R_Q_CQ_NPT_REQ_FLIT", AR_NIC_CQ_CQ_NPT_FLIT_2_LO_CQ_R_Q_CQ_NPT_REQ_FLIT_BP, AR_NIC_CQ_CQ_NPT_FLIT_2_LO_CQ_R_Q_CQ_NPT_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_cq_nat_request_3_hi_cq_detail[] = {
    { "UNUSED_145_56", AR_NIC_CQ_CQ_NAT_REQUEST_3_HI_CQ_UNUSED_145_56_BP, AR_NIC_CQ_CQ_NAT_REQUEST_3_HI_CQ_UNUSED_145_56_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_cq_nat_request_3_mid_cq_detail[] = {
    { "UNUSED_145_56", AR_NIC_CQ_CQ_NAT_REQUEST_3_MID_CQ_UNUSED_145_56_BP, AR_NIC_CQ_CQ_NAT_REQUEST_3_MID_CQ_UNUSED_145_56_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_cq_nat_request_3_lo_cq_detail[] = {
    { "UNUSED_145_56", AR_NIC_CQ_CQ_NAT_REQUEST_3_LO_CQ_UNUSED_145_56_BP, AR_NIC_CQ_CQ_NAT_REQUEST_3_LO_CQ_UNUSED_145_56_MASK },
    { "R_Q_CQ_NAT_VALID", AR_NIC_CQ_CQ_NAT_REQUEST_3_LO_CQ_R_Q_CQ_NAT_VALID_BP, AR_NIC_CQ_CQ_NAT_REQUEST_3_LO_CQ_R_Q_CQ_NAT_VALID_MASK },
    { "R_Q_CQ_NAT_TFIELDS_47_0", AR_NIC_CQ_CQ_NAT_REQUEST_3_LO_CQ_R_Q_CQ_NAT_TFIELDS_47_0_BP, AR_NIC_CQ_CQ_NAT_REQUEST_3_LO_CQ_R_Q_CQ_NAT_TFIELDS_47_0_MASK },
    { "R_Q_CQ_NAT_TID_5_0", AR_NIC_CQ_CQ_NAT_REQUEST_3_LO_CQ_R_Q_CQ_NAT_TID_5_0_BP, AR_NIC_CQ_CQ_NAT_REQUEST_3_LO_CQ_R_Q_CQ_NAT_TID_5_0_MASK },
    { "R_Q_CQ_NAT_MDD_EN", AR_NIC_CQ_CQ_NAT_REQUEST_3_LO_CQ_R_Q_CQ_NAT_MDD_EN_BP, AR_NIC_CQ_CQ_NAT_REQUEST_3_LO_CQ_R_Q_CQ_NAT_MDD_EN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_cq_acks_4_hi_cq_detail[] = {
    { "UNUSED_145_6", AR_NIC_CQ_CQ_ACKS_4_HI_CQ_UNUSED_145_6_BP, AR_NIC_CQ_CQ_ACKS_4_HI_CQ_UNUSED_145_6_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_cq_acks_4_mid_cq_detail[] = {
    { "UNUSED_145_6", AR_NIC_CQ_CQ_ACKS_4_MID_CQ_UNUSED_145_6_BP, AR_NIC_CQ_CQ_ACKS_4_MID_CQ_UNUSED_145_6_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_cq_acks_4_lo_cq_detail[] = {
    { "UNUSED_145_6", AR_NIC_CQ_CQ_ACKS_4_LO_CQ_UNUSED_145_6_BP, AR_NIC_CQ_CQ_ACKS_4_LO_CQ_UNUSED_145_6_MASK },
    { "R_Q_CQ_FMA_ACK", AR_NIC_CQ_CQ_ACKS_4_LO_CQ_R_Q_CQ_FMA_ACK_BP, AR_NIC_CQ_CQ_ACKS_4_LO_CQ_R_Q_CQ_FMA_ACK_MASK },
    { "R_Q_CQ_DLA_ACK", AR_NIC_CQ_CQ_ACKS_4_LO_CQ_R_Q_CQ_DLA_ACK_BP, AR_NIC_CQ_CQ_ACKS_4_LO_CQ_R_Q_CQ_DLA_ACK_MASK },
    { "R_Q_CQ_RMT_ACK", AR_NIC_CQ_CQ_ACKS_4_LO_CQ_R_Q_CQ_RMT_ACK_BP, AR_NIC_CQ_CQ_ACKS_4_LO_CQ_R_Q_CQ_RMT_ACK_MASK },
    { "R_Q_CQ_SSID_ACK", AR_NIC_CQ_CQ_ACKS_4_LO_CQ_R_Q_CQ_SSID_ACK_BP, AR_NIC_CQ_CQ_ACKS_4_LO_CQ_R_Q_CQ_SSID_ACK_MASK },
    { "R_Q_CQ_BTE_ACK", AR_NIC_CQ_CQ_ACKS_4_LO_CQ_R_Q_CQ_BTE_ACK_BP, AR_NIC_CQ_CQ_ACKS_4_LO_CQ_R_Q_CQ_BTE_ACK_MASK },
    { "R_Q_CQ_IOMMU_COMP_WAIT_ACK", AR_NIC_CQ_CQ_ACKS_4_LO_CQ_R_Q_CQ_IOMMU_COMP_WAIT_ACK_BP, AR_NIC_CQ_CQ_ACKS_4_LO_CQ_R_Q_CQ_IOMMU_COMP_WAIT_ACK_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_cq_debug_5_hi_cq_detail[] = {
    { "UNUSED_145_64", AR_NIC_CQ_CQ_DEBUG_5_HI_CQ_UNUSED_145_64_BP, AR_NIC_CQ_CQ_DEBUG_5_HI_CQ_UNUSED_145_64_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_cq_debug_5_mid_cq_detail[] = {
    { "UNUSED_145_64", AR_NIC_CQ_CQ_DEBUG_5_MID_CQ_UNUSED_145_64_BP, AR_NIC_CQ_CQ_DEBUG_5_MID_CQ_UNUSED_145_64_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_cq_debug_5_lo_cq_detail[] = {
    { "CQ_IOMMU_COMP_WAIT_ACK_PENDING", AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_CQ_IOMMU_COMP_WAIT_ACK_PENDING_BP, AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_CQ_IOMMU_COMP_WAIT_ACK_PENDING_MASK },
    { "CQ_IOMMU_EPOCH", AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_CQ_IOMMU_EPOCH_BP, AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_CQ_IOMMU_EPOCH_MASK },
    { "CQ_IOMMU_EPOCH_CNT_1", AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_CQ_IOMMU_EPOCH_CNT_1_BP, AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_CQ_IOMMU_EPOCH_CNT_1_MASK },
    { "CQ_IOMMU_EPOCH_CNT_0", AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_CQ_IOMMU_EPOCH_CNT_0_BP, AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_CQ_IOMMU_EPOCH_CNT_0_MASK },
    { "CQ_NPT_STATE", AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_CQ_NPT_STATE_BP, AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_CQ_NPT_STATE_MASK },
    { "CQ_DESC_FIFO_CNT", AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_CQ_DESC_FIFO_CNT_BP, AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_CQ_DESC_FIFO_CNT_MASK },
    { "FMA_CQ_Q_CNT", AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_FMA_CQ_Q_CNT_BP, AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_FMA_CQ_Q_CNT_MASK },
    { "DLA_CQ_TRQ_CNT", AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_DLA_CQ_TRQ_CNT_BP, AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_DLA_CQ_TRQ_CNT_MASK },
    { "DLA_CQ_TRDR_CNT", AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_DLA_CQ_TRDR_CNT_BP, AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_DLA_CQ_TRDR_CNT_MASK },
    { "RMT_CQ_TRQ_CNT", AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_RMT_CQ_TRQ_CNT_BP, AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_RMT_CQ_TRQ_CNT_MASK },
    { "RMT_CQ_TRDR_CNT", AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_RMT_CQ_TRDR_CNT_BP, AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_RMT_CQ_TRDR_CNT_MASK },
    { "SSID_CQ_TRQ_CNT", AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_SSID_CQ_TRQ_CNT_BP, AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_SSID_CQ_TRQ_CNT_MASK },
    { "SSID_CQ_TRDR_CNT", AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_SSID_CQ_TRDR_CNT_BP, AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_SSID_CQ_TRDR_CNT_MASK },
    { "BTE_CQ_TRQ_CNT", AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_BTE_CQ_TRQ_CNT_BP, AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_BTE_CQ_TRQ_CNT_MASK },
    { "BTE_CQ_TRDR_CNT", AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_BTE_CQ_TRDR_CNT_BP, AR_NIC_CQ_CQ_DEBUG_5_LO_CQ_BTE_CQ_TRDR_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_cfg_npt_credits_detail[] = {
    { "NPT_CRDTS_USED", AR_NIC_CQ_CFG_NPT_CREDITS_NPT_CRDTS_USED_BP, AR_NIC_CQ_CFG_NPT_CREDITS_NPT_CRDTS_USED_MASK },
    { "NPT_CRDTS_USED_MAX", AR_NIC_CQ_CFG_NPT_CREDITS_NPT_CRDTS_USED_MAX_BP, AR_NIC_CQ_CFG_NPT_CREDITS_NPT_CRDTS_USED_MAX_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_cfg_cam_credits_detail[] = {
    { "CAM_CRDTS_USED", AR_NIC_CQ_CFG_CAM_CREDITS_CAM_CRDTS_USED_BP, AR_NIC_CQ_CFG_CAM_CREDITS_CAM_CRDTS_USED_MASK },
    { "CAM_CRDTS_USED_MAX", AR_NIC_CQ_CFG_CAM_CREDITS_CAM_CRDTS_USED_MAX_BP, AR_NIC_CQ_CFG_CAM_CREDITS_CAM_CRDTS_USED_MAX_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_cfg_cache_revisit_rate_detail[] = {
    { "CACHE_REVISIT_RATE", AR_NIC_CQ_CFG_CACHE_REVISIT_RATE_CACHE_REVISIT_RATE_BP, AR_NIC_CQ_CFG_CACHE_REVISIT_RATE_CACHE_REVISIT_RATE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_cfg_nat_response_timeout_detail[] = {
    { "NAT_TIMEOUT_EN", AR_NIC_CQ_CFG_NAT_RESPONSE_TIMEOUT_NAT_TIMEOUT_EN_BP, AR_NIC_CQ_CFG_NAT_RESPONSE_TIMEOUT_NAT_TIMEOUT_EN_MASK },
    { "NAT_TIMEOUT_CNT", AR_NIC_CQ_CFG_NAT_RESPONSE_TIMEOUT_NAT_TIMEOUT_CNT_BP, AR_NIC_CQ_CFG_NAT_RESPONSE_TIMEOUT_NAT_TIMEOUT_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_err_flg_detail[] = {
    { "CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR", AR_NIC_CQ_ERR_FLG_CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR_BP, AR_NIC_CQ_ERR_FLG_CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR_MASK },
    { "CQ_LCL_PARITY_ERR", AR_NIC_CQ_ERR_FLG_CQ_LCL_PARITY_ERR_BP, AR_NIC_CQ_ERR_FLG_CQ_LCL_PARITY_ERR_MASK },
    { "CQ_LCL_DROPPED_EVENT", AR_NIC_CQ_ERR_FLG_CQ_LCL_DROPPED_EVENT_BP, AR_NIC_CQ_ERR_FLG_CQ_LCL_DROPPED_EVENT_MASK },
    { "CQ_LCL_IDX_BOUNDS", AR_NIC_CQ_ERR_FLG_CQ_LCL_IDX_BOUNDS_BP, AR_NIC_CQ_ERR_FLG_CQ_LCL_IDX_BOUNDS_MASK },
    { "CQ_LCL_NAT_ERR", AR_NIC_CQ_ERR_FLG_CQ_LCL_NAT_ERR_BP, AR_NIC_CQ_ERR_FLG_CQ_LCL_NAT_ERR_MASK },
    { "CQ_LCL_OVERRUN_EVENT", AR_NIC_CQ_ERR_FLG_CQ_LCL_OVERRUN_EVENT_BP, AR_NIC_CQ_ERR_FLG_CQ_LCL_OVERRUN_EVENT_MASK },
    { "CQ_LCL_DISABLED_CQ", AR_NIC_CQ_ERR_FLG_CQ_LCL_DISABLED_CQ_BP, AR_NIC_CQ_ERR_FLG_CQ_LCL_DISABLED_CQ_MASK },
    { "CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR", AR_NIC_CQ_ERR_FLG_CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR_BP, AR_NIC_CQ_ERR_FLG_CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR_MASK },
    { "CQ_RMT_PARITY_ERR", AR_NIC_CQ_ERR_FLG_CQ_RMT_PARITY_ERR_BP, AR_NIC_CQ_ERR_FLG_CQ_RMT_PARITY_ERR_MASK },
    { "CQ_RMT_DROPPED_EVENT", AR_NIC_CQ_ERR_FLG_CQ_RMT_DROPPED_EVENT_BP, AR_NIC_CQ_ERR_FLG_CQ_RMT_DROPPED_EVENT_MASK },
    { "CQ_RMT_IDX_BOUNDS", AR_NIC_CQ_ERR_FLG_CQ_RMT_IDX_BOUNDS_BP, AR_NIC_CQ_ERR_FLG_CQ_RMT_IDX_BOUNDS_MASK },
    { "CQ_RMT_NAT_ERR", AR_NIC_CQ_ERR_FLG_CQ_RMT_NAT_ERR_BP, AR_NIC_CQ_ERR_FLG_CQ_RMT_NAT_ERR_MASK },
    { "CQ_RMT_OVERRUN_EVENT", AR_NIC_CQ_ERR_FLG_CQ_RMT_OVERRUN_EVENT_BP, AR_NIC_CQ_ERR_FLG_CQ_RMT_OVERRUN_EVENT_MASK },
    { "CQ_RMT_DISABLED_CQ", AR_NIC_CQ_ERR_FLG_CQ_RMT_DISABLED_CQ_BP, AR_NIC_CQ_ERR_FLG_CQ_RMT_DISABLED_CQ_MASK },
    { "CQ_DESC_TBL_SBE", AR_NIC_CQ_ERR_FLG_CQ_DESC_TBL_SBE_BP, AR_NIC_CQ_ERR_FLG_CQ_DESC_TBL_SBE_MASK },
    { "CQ_DESC_TBL_MBE", AR_NIC_CQ_ERR_FLG_CQ_DESC_TBL_MBE_BP, AR_NIC_CQ_ERR_FLG_CQ_DESC_TBL_MBE_MASK },
    { "FMA_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FLG_FMA_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FLG_FMA_CQ_INPUT_Q_OVERRUN_MASK },
    { "SSID_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FLG_SSID_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FLG_SSID_CQ_INPUT_Q_OVERRUN_MASK },
    { "RMT_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FLG_RMT_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FLG_RMT_CQ_INPUT_Q_OVERRUN_MASK },
    { "DLA_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FLG_DLA_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FLG_DLA_CQ_INPUT_Q_OVERRUN_MASK },
    { "BTE_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FLG_BTE_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FLG_BTE_CQ_INPUT_Q_OVERRUN_MASK },
    { "DIAG_ONLY", AR_NIC_CQ_ERR_FLG_DIAG_ONLY_BP, AR_NIC_CQ_ERR_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
#ifdef EXCEPTIONS_DEFS
static const errcat_mmrd_t _ar_nic_cq_err_flg_errcat[] = {
    { "CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR", AR_NIC_CQ_ERR_FLG_CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR_BP, AR_NIC_CQ_ERR_FLG_CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR_EC },
    { "CQ_LCL_PARITY_ERR", AR_NIC_CQ_ERR_FLG_CQ_LCL_PARITY_ERR_BP, AR_NIC_CQ_ERR_FLG_CQ_LCL_PARITY_ERR_EC },
    { "CQ_LCL_DROPPED_EVENT", AR_NIC_CQ_ERR_FLG_CQ_LCL_DROPPED_EVENT_BP, AR_NIC_CQ_ERR_FLG_CQ_LCL_DROPPED_EVENT_EC },
    { "CQ_LCL_IDX_BOUNDS", AR_NIC_CQ_ERR_FLG_CQ_LCL_IDX_BOUNDS_BP, AR_NIC_CQ_ERR_FLG_CQ_LCL_IDX_BOUNDS_EC },
    { "CQ_LCL_NAT_ERR", AR_NIC_CQ_ERR_FLG_CQ_LCL_NAT_ERR_BP, AR_NIC_CQ_ERR_FLG_CQ_LCL_NAT_ERR_EC },
    { "CQ_LCL_OVERRUN_EVENT", AR_NIC_CQ_ERR_FLG_CQ_LCL_OVERRUN_EVENT_BP, AR_NIC_CQ_ERR_FLG_CQ_LCL_OVERRUN_EVENT_EC },
    { "CQ_LCL_DISABLED_CQ", AR_NIC_CQ_ERR_FLG_CQ_LCL_DISABLED_CQ_BP, AR_NIC_CQ_ERR_FLG_CQ_LCL_DISABLED_CQ_EC },
    { "CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR", AR_NIC_CQ_ERR_FLG_CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR_BP, AR_NIC_CQ_ERR_FLG_CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR_EC },
    { "CQ_RMT_PARITY_ERR", AR_NIC_CQ_ERR_FLG_CQ_RMT_PARITY_ERR_BP, AR_NIC_CQ_ERR_FLG_CQ_RMT_PARITY_ERR_EC },
    { "CQ_RMT_DROPPED_EVENT", AR_NIC_CQ_ERR_FLG_CQ_RMT_DROPPED_EVENT_BP, AR_NIC_CQ_ERR_FLG_CQ_RMT_DROPPED_EVENT_EC },
    { "CQ_RMT_IDX_BOUNDS", AR_NIC_CQ_ERR_FLG_CQ_RMT_IDX_BOUNDS_BP, AR_NIC_CQ_ERR_FLG_CQ_RMT_IDX_BOUNDS_EC },
    { "CQ_RMT_NAT_ERR", AR_NIC_CQ_ERR_FLG_CQ_RMT_NAT_ERR_BP, AR_NIC_CQ_ERR_FLG_CQ_RMT_NAT_ERR_EC },
    { "CQ_RMT_OVERRUN_EVENT", AR_NIC_CQ_ERR_FLG_CQ_RMT_OVERRUN_EVENT_BP, AR_NIC_CQ_ERR_FLG_CQ_RMT_OVERRUN_EVENT_EC },
    { "CQ_RMT_DISABLED_CQ", AR_NIC_CQ_ERR_FLG_CQ_RMT_DISABLED_CQ_BP, AR_NIC_CQ_ERR_FLG_CQ_RMT_DISABLED_CQ_EC },
    { "CQ_DESC_TBL_SBE", AR_NIC_CQ_ERR_FLG_CQ_DESC_TBL_SBE_BP, AR_NIC_CQ_ERR_FLG_CQ_DESC_TBL_SBE_EC },
    { "CQ_DESC_TBL_MBE", AR_NIC_CQ_ERR_FLG_CQ_DESC_TBL_MBE_BP, AR_NIC_CQ_ERR_FLG_CQ_DESC_TBL_MBE_EC },
    { "FMA_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FLG_FMA_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FLG_FMA_CQ_INPUT_Q_OVERRUN_EC },
    { "SSID_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FLG_SSID_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FLG_SSID_CQ_INPUT_Q_OVERRUN_EC },
    { "RMT_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FLG_RMT_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FLG_RMT_CQ_INPUT_Q_OVERRUN_EC },
    { "DLA_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FLG_DLA_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FLG_DLA_CQ_INPUT_Q_OVERRUN_EC },
    { "BTE_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FLG_BTE_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FLG_BTE_CQ_INPUT_Q_OVERRUN_EC },
    { "DIAG_ONLY", AR_NIC_CQ_ERR_FLG_DIAG_ONLY_BP, AR_NIC_CQ_ERR_FLG_DIAG_ONLY_EC },
    { NULL, 0, 0 }
};
#endif
static const generic_mmrd_t _ar_nic_cq_err_clr_detail[] = {
    { "CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR", AR_NIC_CQ_ERR_CLR_CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR_BP, AR_NIC_CQ_ERR_CLR_CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR_MASK },
    { "CQ_LCL_PARITY_ERR", AR_NIC_CQ_ERR_CLR_CQ_LCL_PARITY_ERR_BP, AR_NIC_CQ_ERR_CLR_CQ_LCL_PARITY_ERR_MASK },
    { "CQ_LCL_DROPPED_EVENT", AR_NIC_CQ_ERR_CLR_CQ_LCL_DROPPED_EVENT_BP, AR_NIC_CQ_ERR_CLR_CQ_LCL_DROPPED_EVENT_MASK },
    { "CQ_LCL_IDX_BOUNDS", AR_NIC_CQ_ERR_CLR_CQ_LCL_IDX_BOUNDS_BP, AR_NIC_CQ_ERR_CLR_CQ_LCL_IDX_BOUNDS_MASK },
    { "CQ_LCL_NAT_ERR", AR_NIC_CQ_ERR_CLR_CQ_LCL_NAT_ERR_BP, AR_NIC_CQ_ERR_CLR_CQ_LCL_NAT_ERR_MASK },
    { "CQ_LCL_OVERRUN_EVENT", AR_NIC_CQ_ERR_CLR_CQ_LCL_OVERRUN_EVENT_BP, AR_NIC_CQ_ERR_CLR_CQ_LCL_OVERRUN_EVENT_MASK },
    { "CQ_LCL_DISABLED_CQ", AR_NIC_CQ_ERR_CLR_CQ_LCL_DISABLED_CQ_BP, AR_NIC_CQ_ERR_CLR_CQ_LCL_DISABLED_CQ_MASK },
    { "CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR", AR_NIC_CQ_ERR_CLR_CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR_BP, AR_NIC_CQ_ERR_CLR_CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR_MASK },
    { "CQ_RMT_PARITY_ERR", AR_NIC_CQ_ERR_CLR_CQ_RMT_PARITY_ERR_BP, AR_NIC_CQ_ERR_CLR_CQ_RMT_PARITY_ERR_MASK },
    { "CQ_RMT_DROPPED_EVENT", AR_NIC_CQ_ERR_CLR_CQ_RMT_DROPPED_EVENT_BP, AR_NIC_CQ_ERR_CLR_CQ_RMT_DROPPED_EVENT_MASK },
    { "CQ_RMT_IDX_BOUNDS", AR_NIC_CQ_ERR_CLR_CQ_RMT_IDX_BOUNDS_BP, AR_NIC_CQ_ERR_CLR_CQ_RMT_IDX_BOUNDS_MASK },
    { "CQ_RMT_NAT_ERR", AR_NIC_CQ_ERR_CLR_CQ_RMT_NAT_ERR_BP, AR_NIC_CQ_ERR_CLR_CQ_RMT_NAT_ERR_MASK },
    { "CQ_RMT_OVERRUN_EVENT", AR_NIC_CQ_ERR_CLR_CQ_RMT_OVERRUN_EVENT_BP, AR_NIC_CQ_ERR_CLR_CQ_RMT_OVERRUN_EVENT_MASK },
    { "CQ_RMT_DISABLED_CQ", AR_NIC_CQ_ERR_CLR_CQ_RMT_DISABLED_CQ_BP, AR_NIC_CQ_ERR_CLR_CQ_RMT_DISABLED_CQ_MASK },
    { "CQ_DESC_TBL_SBE", AR_NIC_CQ_ERR_CLR_CQ_DESC_TBL_SBE_BP, AR_NIC_CQ_ERR_CLR_CQ_DESC_TBL_SBE_MASK },
    { "CQ_DESC_TBL_MBE", AR_NIC_CQ_ERR_CLR_CQ_DESC_TBL_MBE_BP, AR_NIC_CQ_ERR_CLR_CQ_DESC_TBL_MBE_MASK },
    { "FMA_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_CLR_FMA_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_CLR_FMA_CQ_INPUT_Q_OVERRUN_MASK },
    { "SSID_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_CLR_SSID_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_CLR_SSID_CQ_INPUT_Q_OVERRUN_MASK },
    { "RMT_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_CLR_RMT_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_CLR_RMT_CQ_INPUT_Q_OVERRUN_MASK },
    { "DLA_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_CLR_DLA_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_CLR_DLA_CQ_INPUT_Q_OVERRUN_MASK },
    { "BTE_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_CLR_BTE_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_CLR_BTE_CQ_INPUT_Q_OVERRUN_MASK },
    { "DIAG_ONLY", AR_NIC_CQ_ERR_CLR_DIAG_ONLY_BP, AR_NIC_CQ_ERR_CLR_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_err_hss_msk_detail[] = {
    { "CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR", AR_NIC_CQ_ERR_HSS_MSK_CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR_BP, AR_NIC_CQ_ERR_HSS_MSK_CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR_MASK },
    { "CQ_LCL_PARITY_ERR", AR_NIC_CQ_ERR_HSS_MSK_CQ_LCL_PARITY_ERR_BP, AR_NIC_CQ_ERR_HSS_MSK_CQ_LCL_PARITY_ERR_MASK },
    { "CQ_LCL_DROPPED_EVENT", AR_NIC_CQ_ERR_HSS_MSK_CQ_LCL_DROPPED_EVENT_BP, AR_NIC_CQ_ERR_HSS_MSK_CQ_LCL_DROPPED_EVENT_MASK },
    { "CQ_LCL_IDX_BOUNDS", AR_NIC_CQ_ERR_HSS_MSK_CQ_LCL_IDX_BOUNDS_BP, AR_NIC_CQ_ERR_HSS_MSK_CQ_LCL_IDX_BOUNDS_MASK },
    { "CQ_LCL_NAT_ERR", AR_NIC_CQ_ERR_HSS_MSK_CQ_LCL_NAT_ERR_BP, AR_NIC_CQ_ERR_HSS_MSK_CQ_LCL_NAT_ERR_MASK },
    { "CQ_LCL_OVERRUN_EVENT", AR_NIC_CQ_ERR_HSS_MSK_CQ_LCL_OVERRUN_EVENT_BP, AR_NIC_CQ_ERR_HSS_MSK_CQ_LCL_OVERRUN_EVENT_MASK },
    { "CQ_LCL_DISABLED_CQ", AR_NIC_CQ_ERR_HSS_MSK_CQ_LCL_DISABLED_CQ_BP, AR_NIC_CQ_ERR_HSS_MSK_CQ_LCL_DISABLED_CQ_MASK },
    { "CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR", AR_NIC_CQ_ERR_HSS_MSK_CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR_BP, AR_NIC_CQ_ERR_HSS_MSK_CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR_MASK },
    { "CQ_RMT_PARITY_ERR", AR_NIC_CQ_ERR_HSS_MSK_CQ_RMT_PARITY_ERR_BP, AR_NIC_CQ_ERR_HSS_MSK_CQ_RMT_PARITY_ERR_MASK },
    { "CQ_RMT_DROPPED_EVENT", AR_NIC_CQ_ERR_HSS_MSK_CQ_RMT_DROPPED_EVENT_BP, AR_NIC_CQ_ERR_HSS_MSK_CQ_RMT_DROPPED_EVENT_MASK },
    { "CQ_RMT_IDX_BOUNDS", AR_NIC_CQ_ERR_HSS_MSK_CQ_RMT_IDX_BOUNDS_BP, AR_NIC_CQ_ERR_HSS_MSK_CQ_RMT_IDX_BOUNDS_MASK },
    { "CQ_RMT_NAT_ERR", AR_NIC_CQ_ERR_HSS_MSK_CQ_RMT_NAT_ERR_BP, AR_NIC_CQ_ERR_HSS_MSK_CQ_RMT_NAT_ERR_MASK },
    { "CQ_RMT_OVERRUN_EVENT", AR_NIC_CQ_ERR_HSS_MSK_CQ_RMT_OVERRUN_EVENT_BP, AR_NIC_CQ_ERR_HSS_MSK_CQ_RMT_OVERRUN_EVENT_MASK },
    { "CQ_RMT_DISABLED_CQ", AR_NIC_CQ_ERR_HSS_MSK_CQ_RMT_DISABLED_CQ_BP, AR_NIC_CQ_ERR_HSS_MSK_CQ_RMT_DISABLED_CQ_MASK },
    { "CQ_DESC_TBL_SBE", AR_NIC_CQ_ERR_HSS_MSK_CQ_DESC_TBL_SBE_BP, AR_NIC_CQ_ERR_HSS_MSK_CQ_DESC_TBL_SBE_MASK },
    { "CQ_DESC_TBL_MBE", AR_NIC_CQ_ERR_HSS_MSK_CQ_DESC_TBL_MBE_BP, AR_NIC_CQ_ERR_HSS_MSK_CQ_DESC_TBL_MBE_MASK },
    { "FMA_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_HSS_MSK_FMA_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_HSS_MSK_FMA_CQ_INPUT_Q_OVERRUN_MASK },
    { "SSID_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_HSS_MSK_SSID_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_HSS_MSK_SSID_CQ_INPUT_Q_OVERRUN_MASK },
    { "RMT_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_HSS_MSK_RMT_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_HSS_MSK_RMT_CQ_INPUT_Q_OVERRUN_MASK },
    { "DLA_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_HSS_MSK_DLA_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_HSS_MSK_DLA_CQ_INPUT_Q_OVERRUN_MASK },
    { "BTE_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_HSS_MSK_BTE_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_HSS_MSK_BTE_CQ_INPUT_Q_OVERRUN_MASK },
    { "DIAG_ONLY", AR_NIC_CQ_ERR_HSS_MSK_DIAG_ONLY_BP, AR_NIC_CQ_ERR_HSS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_err_os_msk_detail[] = {
    { "CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR", AR_NIC_CQ_ERR_OS_MSK_CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR_BP, AR_NIC_CQ_ERR_OS_MSK_CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR_MASK },
    { "CQ_LCL_PARITY_ERR", AR_NIC_CQ_ERR_OS_MSK_CQ_LCL_PARITY_ERR_BP, AR_NIC_CQ_ERR_OS_MSK_CQ_LCL_PARITY_ERR_MASK },
    { "CQ_LCL_DROPPED_EVENT", AR_NIC_CQ_ERR_OS_MSK_CQ_LCL_DROPPED_EVENT_BP, AR_NIC_CQ_ERR_OS_MSK_CQ_LCL_DROPPED_EVENT_MASK },
    { "CQ_LCL_IDX_BOUNDS", AR_NIC_CQ_ERR_OS_MSK_CQ_LCL_IDX_BOUNDS_BP, AR_NIC_CQ_ERR_OS_MSK_CQ_LCL_IDX_BOUNDS_MASK },
    { "CQ_LCL_NAT_ERR", AR_NIC_CQ_ERR_OS_MSK_CQ_LCL_NAT_ERR_BP, AR_NIC_CQ_ERR_OS_MSK_CQ_LCL_NAT_ERR_MASK },
    { "CQ_LCL_OVERRUN_EVENT", AR_NIC_CQ_ERR_OS_MSK_CQ_LCL_OVERRUN_EVENT_BP, AR_NIC_CQ_ERR_OS_MSK_CQ_LCL_OVERRUN_EVENT_MASK },
    { "CQ_LCL_DISABLED_CQ", AR_NIC_CQ_ERR_OS_MSK_CQ_LCL_DISABLED_CQ_BP, AR_NIC_CQ_ERR_OS_MSK_CQ_LCL_DISABLED_CQ_MASK },
    { "CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR", AR_NIC_CQ_ERR_OS_MSK_CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR_BP, AR_NIC_CQ_ERR_OS_MSK_CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR_MASK },
    { "CQ_RMT_PARITY_ERR", AR_NIC_CQ_ERR_OS_MSK_CQ_RMT_PARITY_ERR_BP, AR_NIC_CQ_ERR_OS_MSK_CQ_RMT_PARITY_ERR_MASK },
    { "CQ_RMT_DROPPED_EVENT", AR_NIC_CQ_ERR_OS_MSK_CQ_RMT_DROPPED_EVENT_BP, AR_NIC_CQ_ERR_OS_MSK_CQ_RMT_DROPPED_EVENT_MASK },
    { "CQ_RMT_IDX_BOUNDS", AR_NIC_CQ_ERR_OS_MSK_CQ_RMT_IDX_BOUNDS_BP, AR_NIC_CQ_ERR_OS_MSK_CQ_RMT_IDX_BOUNDS_MASK },
    { "CQ_RMT_NAT_ERR", AR_NIC_CQ_ERR_OS_MSK_CQ_RMT_NAT_ERR_BP, AR_NIC_CQ_ERR_OS_MSK_CQ_RMT_NAT_ERR_MASK },
    { "CQ_RMT_OVERRUN_EVENT", AR_NIC_CQ_ERR_OS_MSK_CQ_RMT_OVERRUN_EVENT_BP, AR_NIC_CQ_ERR_OS_MSK_CQ_RMT_OVERRUN_EVENT_MASK },
    { "CQ_RMT_DISABLED_CQ", AR_NIC_CQ_ERR_OS_MSK_CQ_RMT_DISABLED_CQ_BP, AR_NIC_CQ_ERR_OS_MSK_CQ_RMT_DISABLED_CQ_MASK },
    { "CQ_DESC_TBL_SBE", AR_NIC_CQ_ERR_OS_MSK_CQ_DESC_TBL_SBE_BP, AR_NIC_CQ_ERR_OS_MSK_CQ_DESC_TBL_SBE_MASK },
    { "CQ_DESC_TBL_MBE", AR_NIC_CQ_ERR_OS_MSK_CQ_DESC_TBL_MBE_BP, AR_NIC_CQ_ERR_OS_MSK_CQ_DESC_TBL_MBE_MASK },
    { "FMA_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_OS_MSK_FMA_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_OS_MSK_FMA_CQ_INPUT_Q_OVERRUN_MASK },
    { "SSID_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_OS_MSK_SSID_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_OS_MSK_SSID_CQ_INPUT_Q_OVERRUN_MASK },
    { "RMT_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_OS_MSK_RMT_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_OS_MSK_RMT_CQ_INPUT_Q_OVERRUN_MASK },
    { "DLA_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_OS_MSK_DLA_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_OS_MSK_DLA_CQ_INPUT_Q_OVERRUN_MASK },
    { "BTE_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_OS_MSK_BTE_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_OS_MSK_BTE_CQ_INPUT_Q_OVERRUN_MASK },
    { "DIAG_ONLY", AR_NIC_CQ_ERR_OS_MSK_DIAG_ONLY_BP, AR_NIC_CQ_ERR_OS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_err_first_flg_detail[] = {
    { "CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR", AR_NIC_CQ_ERR_FIRST_FLG_CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR_BP, AR_NIC_CQ_ERR_FIRST_FLG_CQ_LCL_NAT_RESPONSE_TIMEOUT_ERR_MASK },
    { "CQ_LCL_PARITY_ERR", AR_NIC_CQ_ERR_FIRST_FLG_CQ_LCL_PARITY_ERR_BP, AR_NIC_CQ_ERR_FIRST_FLG_CQ_LCL_PARITY_ERR_MASK },
    { "CQ_LCL_DROPPED_EVENT", AR_NIC_CQ_ERR_FIRST_FLG_CQ_LCL_DROPPED_EVENT_BP, AR_NIC_CQ_ERR_FIRST_FLG_CQ_LCL_DROPPED_EVENT_MASK },
    { "CQ_LCL_IDX_BOUNDS", AR_NIC_CQ_ERR_FIRST_FLG_CQ_LCL_IDX_BOUNDS_BP, AR_NIC_CQ_ERR_FIRST_FLG_CQ_LCL_IDX_BOUNDS_MASK },
    { "CQ_LCL_NAT_ERR", AR_NIC_CQ_ERR_FIRST_FLG_CQ_LCL_NAT_ERR_BP, AR_NIC_CQ_ERR_FIRST_FLG_CQ_LCL_NAT_ERR_MASK },
    { "CQ_LCL_OVERRUN_EVENT", AR_NIC_CQ_ERR_FIRST_FLG_CQ_LCL_OVERRUN_EVENT_BP, AR_NIC_CQ_ERR_FIRST_FLG_CQ_LCL_OVERRUN_EVENT_MASK },
    { "CQ_LCL_DISABLED_CQ", AR_NIC_CQ_ERR_FIRST_FLG_CQ_LCL_DISABLED_CQ_BP, AR_NIC_CQ_ERR_FIRST_FLG_CQ_LCL_DISABLED_CQ_MASK },
    { "CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR", AR_NIC_CQ_ERR_FIRST_FLG_CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR_BP, AR_NIC_CQ_ERR_FIRST_FLG_CQ_RMT_NAT_RESPONSE_TIMEOUT_ERR_MASK },
    { "CQ_RMT_PARITY_ERR", AR_NIC_CQ_ERR_FIRST_FLG_CQ_RMT_PARITY_ERR_BP, AR_NIC_CQ_ERR_FIRST_FLG_CQ_RMT_PARITY_ERR_MASK },
    { "CQ_RMT_DROPPED_EVENT", AR_NIC_CQ_ERR_FIRST_FLG_CQ_RMT_DROPPED_EVENT_BP, AR_NIC_CQ_ERR_FIRST_FLG_CQ_RMT_DROPPED_EVENT_MASK },
    { "CQ_RMT_IDX_BOUNDS", AR_NIC_CQ_ERR_FIRST_FLG_CQ_RMT_IDX_BOUNDS_BP, AR_NIC_CQ_ERR_FIRST_FLG_CQ_RMT_IDX_BOUNDS_MASK },
    { "CQ_RMT_NAT_ERR", AR_NIC_CQ_ERR_FIRST_FLG_CQ_RMT_NAT_ERR_BP, AR_NIC_CQ_ERR_FIRST_FLG_CQ_RMT_NAT_ERR_MASK },
    { "CQ_RMT_OVERRUN_EVENT", AR_NIC_CQ_ERR_FIRST_FLG_CQ_RMT_OVERRUN_EVENT_BP, AR_NIC_CQ_ERR_FIRST_FLG_CQ_RMT_OVERRUN_EVENT_MASK },
    { "CQ_RMT_DISABLED_CQ", AR_NIC_CQ_ERR_FIRST_FLG_CQ_RMT_DISABLED_CQ_BP, AR_NIC_CQ_ERR_FIRST_FLG_CQ_RMT_DISABLED_CQ_MASK },
    { "CQ_DESC_TBL_SBE", AR_NIC_CQ_ERR_FIRST_FLG_CQ_DESC_TBL_SBE_BP, AR_NIC_CQ_ERR_FIRST_FLG_CQ_DESC_TBL_SBE_MASK },
    { "CQ_DESC_TBL_MBE", AR_NIC_CQ_ERR_FIRST_FLG_CQ_DESC_TBL_MBE_BP, AR_NIC_CQ_ERR_FIRST_FLG_CQ_DESC_TBL_MBE_MASK },
    { "FMA_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FIRST_FLG_FMA_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FIRST_FLG_FMA_CQ_INPUT_Q_OVERRUN_MASK },
    { "SSID_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FIRST_FLG_SSID_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FIRST_FLG_SSID_CQ_INPUT_Q_OVERRUN_MASK },
    { "RMT_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FIRST_FLG_RMT_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FIRST_FLG_RMT_CQ_INPUT_Q_OVERRUN_MASK },
    { "DLA_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FIRST_FLG_DLA_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FIRST_FLG_DLA_CQ_INPUT_Q_OVERRUN_MASK },
    { "BTE_CQ_INPUT_Q_OVERRUN", AR_NIC_CQ_ERR_FIRST_FLG_BTE_CQ_INPUT_Q_OVERRUN_BP, AR_NIC_CQ_ERR_FIRST_FLG_BTE_CQ_INPUT_Q_OVERRUN_MASK },
    { "DIAG_ONLY", AR_NIC_CQ_ERR_FIRST_FLG_DIAG_ONLY_BP, AR_NIC_CQ_ERR_FIRST_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_err_info_desc_tbl_sbe_mbe_detail[] = {
    { "SBE_SRC", AR_NIC_CQ_ERR_INFO_DESC_TBL_SBE_MBE_SBE_SRC_BP, AR_NIC_CQ_ERR_INFO_DESC_TBL_SBE_MBE_SBE_SRC_MASK },
    { "SBE_REGION", AR_NIC_CQ_ERR_INFO_DESC_TBL_SBE_MBE_SBE_REGION_BP, AR_NIC_CQ_ERR_INFO_DESC_TBL_SBE_MBE_SBE_REGION_MASK },
    { "SBE_SYNDROME", AR_NIC_CQ_ERR_INFO_DESC_TBL_SBE_MBE_SBE_SYNDROME_BP, AR_NIC_CQ_ERR_INFO_DESC_TBL_SBE_MBE_SBE_SYNDROME_MASK },
    { "SBE_ADDR", AR_NIC_CQ_ERR_INFO_DESC_TBL_SBE_MBE_SBE_ADDR_BP, AR_NIC_CQ_ERR_INFO_DESC_TBL_SBE_MBE_SBE_ADDR_MASK },
    { "MBE_SRC", AR_NIC_CQ_ERR_INFO_DESC_TBL_SBE_MBE_MBE_SRC_BP, AR_NIC_CQ_ERR_INFO_DESC_TBL_SBE_MBE_MBE_SRC_MASK },
    { "MBE_REGION", AR_NIC_CQ_ERR_INFO_DESC_TBL_SBE_MBE_MBE_REGION_BP, AR_NIC_CQ_ERR_INFO_DESC_TBL_SBE_MBE_MBE_REGION_MASK },
    { "MBE_SYNDROME", AR_NIC_CQ_ERR_INFO_DESC_TBL_SBE_MBE_MBE_SYNDROME_BP, AR_NIC_CQ_ERR_INFO_DESC_TBL_SBE_MBE_MBE_SYNDROME_MASK },
    { "MBE_ADDR", AR_NIC_CQ_ERR_INFO_DESC_TBL_SBE_MBE_MBE_ADDR_BP, AR_NIC_CQ_ERR_INFO_DESC_TBL_SBE_MBE_MBE_ADDR_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_err_info_rmt_disabled_cq_detail[] = {
    { "SOURCE", AR_NIC_CQ_ERR_INFO_RMT_DISABLED_CQ_SOURCE_BP, AR_NIC_CQ_ERR_INFO_RMT_DISABLED_CQ_SOURCE_MASK },
    { "CQH", AR_NIC_CQ_ERR_INFO_RMT_DISABLED_CQ_CQH_BP, AR_NIC_CQ_ERR_INFO_RMT_DISABLED_CQ_CQH_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_err_info_rmt_nat_err_detail[] = {
    { "NAT_ERR", AR_NIC_CQ_ERR_INFO_RMT_NAT_ERR_NAT_ERR_BP, AR_NIC_CQ_ERR_INFO_RMT_NAT_ERR_NAT_ERR_MASK },
    { "SOURCE", AR_NIC_CQ_ERR_INFO_RMT_NAT_ERR_SOURCE_BP, AR_NIC_CQ_ERR_INFO_RMT_NAT_ERR_SOURCE_MASK },
    { "CQH", AR_NIC_CQ_ERR_INFO_RMT_NAT_ERR_CQH_BP, AR_NIC_CQ_ERR_INFO_RMT_NAT_ERR_CQH_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_err_info_rmt_idx_bounds_detail[] = {
    { "SOURCE", AR_NIC_CQ_ERR_INFO_RMT_IDX_BOUNDS_SOURCE_BP, AR_NIC_CQ_ERR_INFO_RMT_IDX_BOUNDS_SOURCE_MASK },
    { "CQH", AR_NIC_CQ_ERR_INFO_RMT_IDX_BOUNDS_CQH_BP, AR_NIC_CQ_ERR_INFO_RMT_IDX_BOUNDS_CQH_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_err_info_rmt_dropped_event_detail[] = {
    { "INPUT_RMT_PARITY_ERR", AR_NIC_CQ_ERR_INFO_RMT_DROPPED_EVENT_INPUT_RMT_PARITY_ERR_BP, AR_NIC_CQ_ERR_INFO_RMT_DROPPED_EVENT_INPUT_RMT_PARITY_ERR_MASK },
    { "INPUT_EVENT_PARITY_ERR", AR_NIC_CQ_ERR_INFO_RMT_DROPPED_EVENT_INPUT_EVENT_PARITY_ERR_BP, AR_NIC_CQ_ERR_INFO_RMT_DROPPED_EVENT_INPUT_EVENT_PARITY_ERR_MASK },
    { "TCQ_PARITY_ERR", AR_NIC_CQ_ERR_INFO_RMT_DROPPED_EVENT_TCQ_PARITY_ERR_BP, AR_NIC_CQ_ERR_INFO_RMT_DROPPED_EVENT_TCQ_PARITY_ERR_MASK },
    { "TCQ_STATUS", AR_NIC_CQ_ERR_INFO_RMT_DROPPED_EVENT_TCQ_STATUS_BP, AR_NIC_CQ_ERR_INFO_RMT_DROPPED_EVENT_TCQ_STATUS_MASK },
    { "SOURCE", AR_NIC_CQ_ERR_INFO_RMT_DROPPED_EVENT_SOURCE_BP, AR_NIC_CQ_ERR_INFO_RMT_DROPPED_EVENT_SOURCE_MASK },
    { "CQH", AR_NIC_CQ_ERR_INFO_RMT_DROPPED_EVENT_CQH_BP, AR_NIC_CQ_ERR_INFO_RMT_DROPPED_EVENT_CQH_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_err_info_rmt_nat_response_timeout_detail[] = {
    { "SOURCE", AR_NIC_CQ_ERR_INFO_RMT_NAT_RESPONSE_TIMEOUT_SOURCE_BP, AR_NIC_CQ_ERR_INFO_RMT_NAT_RESPONSE_TIMEOUT_SOURCE_MASK },
    { "CQH", AR_NIC_CQ_ERR_INFO_RMT_NAT_RESPONSE_TIMEOUT_CQH_BP, AR_NIC_CQ_ERR_INFO_RMT_NAT_RESPONSE_TIMEOUT_CQH_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_err_info_lcl_disabled_cq_detail[] = {
    { "SOURCE", AR_NIC_CQ_ERR_INFO_LCL_DISABLED_CQ_SOURCE_BP, AR_NIC_CQ_ERR_INFO_LCL_DISABLED_CQ_SOURCE_MASK },
    { "CQH", AR_NIC_CQ_ERR_INFO_LCL_DISABLED_CQ_CQH_BP, AR_NIC_CQ_ERR_INFO_LCL_DISABLED_CQ_CQH_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_err_info_lcl_nat_err_detail[] = {
    { "NAT_ERR", AR_NIC_CQ_ERR_INFO_LCL_NAT_ERR_NAT_ERR_BP, AR_NIC_CQ_ERR_INFO_LCL_NAT_ERR_NAT_ERR_MASK },
    { "SOURCE", AR_NIC_CQ_ERR_INFO_LCL_NAT_ERR_SOURCE_BP, AR_NIC_CQ_ERR_INFO_LCL_NAT_ERR_SOURCE_MASK },
    { "CQH", AR_NIC_CQ_ERR_INFO_LCL_NAT_ERR_CQH_BP, AR_NIC_CQ_ERR_INFO_LCL_NAT_ERR_CQH_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_err_info_lcl_idx_bounds_detail[] = {
    { "SOURCE", AR_NIC_CQ_ERR_INFO_LCL_IDX_BOUNDS_SOURCE_BP, AR_NIC_CQ_ERR_INFO_LCL_IDX_BOUNDS_SOURCE_MASK },
    { "CQH", AR_NIC_CQ_ERR_INFO_LCL_IDX_BOUNDS_CQH_BP, AR_NIC_CQ_ERR_INFO_LCL_IDX_BOUNDS_CQH_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_err_info_lcl_dropped_event_detail[] = {
    { "INPUT_EVENT_PARITY_ERR", AR_NIC_CQ_ERR_INFO_LCL_DROPPED_EVENT_INPUT_EVENT_PARITY_ERR_BP, AR_NIC_CQ_ERR_INFO_LCL_DROPPED_EVENT_INPUT_EVENT_PARITY_ERR_MASK },
    { "TCQ_PARITY_ERR", AR_NIC_CQ_ERR_INFO_LCL_DROPPED_EVENT_TCQ_PARITY_ERR_BP, AR_NIC_CQ_ERR_INFO_LCL_DROPPED_EVENT_TCQ_PARITY_ERR_MASK },
    { "TCQ_STATUS", AR_NIC_CQ_ERR_INFO_LCL_DROPPED_EVENT_TCQ_STATUS_BP, AR_NIC_CQ_ERR_INFO_LCL_DROPPED_EVENT_TCQ_STATUS_MASK },
    { "SOURCE", AR_NIC_CQ_ERR_INFO_LCL_DROPPED_EVENT_SOURCE_BP, AR_NIC_CQ_ERR_INFO_LCL_DROPPED_EVENT_SOURCE_MASK },
    { "CQH", AR_NIC_CQ_ERR_INFO_LCL_DROPPED_EVENT_CQH_BP, AR_NIC_CQ_ERR_INFO_LCL_DROPPED_EVENT_CQH_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_err_info_lcl_nat_response_timeout_detail[] = {
    { "SOURCE", AR_NIC_CQ_ERR_INFO_LCL_NAT_RESPONSE_TIMEOUT_SOURCE_BP, AR_NIC_CQ_ERR_INFO_LCL_NAT_RESPONSE_TIMEOUT_SOURCE_MASK },
    { "CQH", AR_NIC_CQ_ERR_INFO_LCL_NAT_RESPONSE_TIMEOUT_CQH_BP, AR_NIC_CQ_ERR_INFO_LCL_NAT_RESPONSE_TIMEOUT_CQH_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_dbg_errinj_desc_tbl_detail[] = {
    { "ADDRESS", AR_NIC_CQ_DBG_ERRINJ_DESC_TBL_ADDRESS_BP, AR_NIC_CQ_DBG_ERRINJ_DESC_TBL_ADDRESS_MASK },
    { "CHECKBITS", AR_NIC_CQ_DBG_ERRINJ_DESC_TBL_CHECKBITS_BP, AR_NIC_CQ_DBG_ERRINJ_DESC_TBL_CHECKBITS_MASK },
    { "SELECT", AR_NIC_CQ_DBG_ERRINJ_DESC_TBL_SELECT_BP, AR_NIC_CQ_DBG_ERRINJ_DESC_TBL_SELECT_MASK },
    { "TRIGGERED", AR_NIC_CQ_DBG_ERRINJ_DESC_TBL_TRIGGERED_BP, AR_NIC_CQ_DBG_ERRINJ_DESC_TBL_TRIGGERED_MASK },
    { "MODE", AR_NIC_CQ_DBG_ERRINJ_DESC_TBL_MODE_BP, AR_NIC_CQ_DBG_ERRINJ_DESC_TBL_MODE_MASK },
    { "ENABLE", AR_NIC_CQ_DBG_ERRINJ_DESC_TBL_ENABLE_BP, AR_NIC_CQ_DBG_ERRINJ_DESC_TBL_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_dbg_errinj_parity_detail[] = {
    { "TRANS_COMPL_Q", AR_NIC_CQ_DBG_ERRINJ_PARITY_TRANS_COMPL_Q_BP, AR_NIC_CQ_DBG_ERRINJ_PARITY_TRANS_COMPL_Q_MASK },
    { "RMT_INPUT_RMT_DATA", AR_NIC_CQ_DBG_ERRINJ_PARITY_RMT_INPUT_RMT_DATA_BP, AR_NIC_CQ_DBG_ERRINJ_PARITY_RMT_INPUT_RMT_DATA_MASK },
    { "RMT_INPUT_EVENT_DATA", AR_NIC_CQ_DBG_ERRINJ_PARITY_RMT_INPUT_EVENT_DATA_BP, AR_NIC_CQ_DBG_ERRINJ_PARITY_RMT_INPUT_EVENT_DATA_MASK },
    { "SSID_INPUT_EVENT_DATA", AR_NIC_CQ_DBG_ERRINJ_PARITY_SSID_INPUT_EVENT_DATA_BP, AR_NIC_CQ_DBG_ERRINJ_PARITY_SSID_INPUT_EVENT_DATA_MASK },
    { "DLA_INPUT_EVENT_DATA", AR_NIC_CQ_DBG_ERRINJ_PARITY_DLA_INPUT_EVENT_DATA_BP, AR_NIC_CQ_DBG_ERRINJ_PARITY_DLA_INPUT_EVENT_DATA_MASK },
    { "BTE_INPUT_EVENT_DATA", AR_NIC_CQ_DBG_ERRINJ_PARITY_BTE_INPUT_EVENT_DATA_BP, AR_NIC_CQ_DBG_ERRINJ_PARITY_BTE_INPUT_EVENT_DATA_MASK },
    { "TRIGGERED", AR_NIC_CQ_DBG_ERRINJ_PARITY_TRIGGERED_BP, AR_NIC_CQ_DBG_ERRINJ_PARITY_TRIGGERED_MASK },
    { "MODE0", AR_NIC_CQ_DBG_ERRINJ_PARITY_MODE0_BP, AR_NIC_CQ_DBG_ERRINJ_PARITY_MODE0_MASK },
    { "ENABLE", AR_NIC_CQ_DBG_ERRINJ_PARITY_ENABLE_BP, AR_NIC_CQ_DBG_ERRINJ_PARITY_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_dbg_iommu_status_detail[] = {
    { "CQ_IOMMU_EPOCH", AR_NIC_CQ_DBG_IOMMU_STATUS_CQ_IOMMU_EPOCH_BP, AR_NIC_CQ_DBG_IOMMU_STATUS_CQ_IOMMU_EPOCH_MASK },
    { "CQ_IOMMU_EPOCH_CNT_1", AR_NIC_CQ_DBG_IOMMU_STATUS_CQ_IOMMU_EPOCH_CNT_1_BP, AR_NIC_CQ_DBG_IOMMU_STATUS_CQ_IOMMU_EPOCH_CNT_1_MASK },
    { "CQ_IOMMU_EPOCH_CNT_0", AR_NIC_CQ_DBG_IOMMU_STATUS_CQ_IOMMU_EPOCH_CNT_0_BP, AR_NIC_CQ_DBG_IOMMU_STATUS_CQ_IOMMU_EPOCH_CNT_0_MASK },
    { "CQ_IOMMU_COMP_WAIT_ACK_PENDING", AR_NIC_CQ_DBG_IOMMU_STATUS_CQ_IOMMU_COMP_WAIT_ACK_PENDING_BP, AR_NIC_CQ_DBG_IOMMU_STATUS_CQ_IOMMU_COMP_WAIT_ACK_PENDING_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_cq_dbg_state_detail[] = {
    { "CQ_NPT_STATE", AR_NIC_CQ_DBG_STATE_CQ_NPT_STATE_BP, AR_NIC_CQ_DBG_STATE_CQ_NPT_STATE_MASK },
    { "CQ_DESC_FIFO_CNT", AR_NIC_CQ_DBG_STATE_CQ_DESC_FIFO_CNT_BP, AR_NIC_CQ_DBG_STATE_CQ_DESC_FIFO_CNT_MASK },
    { "FMA_CQ_Q_CNT", AR_NIC_CQ_DBG_STATE_FMA_CQ_Q_CNT_BP, AR_NIC_CQ_DBG_STATE_FMA_CQ_Q_CNT_MASK },
    { "DLA_CQ_TRQ_CNT", AR_NIC_CQ_DBG_STATE_DLA_CQ_TRQ_CNT_BP, AR_NIC_CQ_DBG_STATE_DLA_CQ_TRQ_CNT_MASK },
    { "DLA_CQ_TRDR_CNT", AR_NIC_CQ_DBG_STATE_DLA_CQ_TRDR_CNT_BP, AR_NIC_CQ_DBG_STATE_DLA_CQ_TRDR_CNT_MASK },
    { "RMT_CQ_TRQ_CNT", AR_NIC_CQ_DBG_STATE_RMT_CQ_TRQ_CNT_BP, AR_NIC_CQ_DBG_STATE_RMT_CQ_TRQ_CNT_MASK },
    { "RMT_CQ_TRDR_CNT", AR_NIC_CQ_DBG_STATE_RMT_CQ_TRDR_CNT_BP, AR_NIC_CQ_DBG_STATE_RMT_CQ_TRDR_CNT_MASK },
    { "SSID_CQ_TRQ_CNT", AR_NIC_CQ_DBG_STATE_SSID_CQ_TRQ_CNT_BP, AR_NIC_CQ_DBG_STATE_SSID_CQ_TRQ_CNT_MASK },
    { "SSID_CQ_TRDR_CNT", AR_NIC_CQ_DBG_STATE_SSID_CQ_TRDR_CNT_BP, AR_NIC_CQ_DBG_STATE_SSID_CQ_TRDR_CNT_MASK },
    { "BTE_CQ_TRQ_CNT", AR_NIC_CQ_DBG_STATE_BTE_CQ_TRQ_CNT_BP, AR_NIC_CQ_DBG_STATE_BTE_CQ_TRQ_CNT_MASK },
    { "BTE_CQ_TRDR_CNT", AR_NIC_CQ_DBG_STATE_BTE_CQ_TRDR_CNT_BP, AR_NIC_CQ_DBG_STATE_BTE_CQ_TRDR_CNT_MASK },
    { NULL, 0, 0 }
};

/*
 *  AR CQ MMR DECLARATIONS
 */
static const generic_mmr_t _ar_nic_cq_mmr_ring_0_hi_cq = {
    "AR_NIC_CQ_MMR_RING_0_HI_CQ", AR_NIC_CQ_MMR_RING_0_HI_CQ, 8, 1, _ar_nic_cq_mmr_ring_0_hi_cq_detail
};
static const generic_mmr_t _ar_nic_cq_mmr_ring_0_mid_cq = {
    "AR_NIC_CQ_MMR_RING_0_MID_CQ", AR_NIC_CQ_MMR_RING_0_MID_CQ, 8, 1, _ar_nic_cq_mmr_ring_0_mid_cq_detail
};
static const generic_mmr_t _ar_nic_cq_mmr_ring_0_lo_cq = {
    "AR_NIC_CQ_MMR_RING_0_LO_CQ", AR_NIC_CQ_MMR_RING_0_LO_CQ, 8, 1, _ar_nic_cq_mmr_ring_0_lo_cq_detail
};
static const generic_mmr_t _ar_nic_cq_err_flg_1_hi_cq = {
    "AR_NIC_CQ_ERR_FLG_1_HI_CQ", AR_NIC_CQ_ERR_FLG_1_HI_CQ, 8, 1, _ar_nic_cq_err_flg_1_hi_cq_detail
};
static const generic_mmr_t _ar_nic_cq_err_flg_1_mid_cq = {
    "AR_NIC_CQ_ERR_FLG_1_MID_CQ", AR_NIC_CQ_ERR_FLG_1_MID_CQ, 8, 1, _ar_nic_cq_err_flg_1_mid_cq_detail
};
static const generic_mmr_t _ar_nic_cq_err_flg_1_lo_cq = {
    "AR_NIC_CQ_ERR_FLG_1_LO_CQ", AR_NIC_CQ_ERR_FLG_1_LO_CQ, 8, 1, _ar_nic_cq_err_flg_1_lo_cq_detail
};
static const generic_mmr_t _ar_nic_cq_cq_npt_flit_2_hi_cq = {
    "AR_NIC_CQ_CQ_NPT_FLIT_2_HI_CQ", AR_NIC_CQ_CQ_NPT_FLIT_2_HI_CQ, 8, 1, _ar_nic_cq_cq_npt_flit_2_hi_cq_detail
};
static const generic_mmr_t _ar_nic_cq_cq_npt_flit_2_mid_cq = {
    "AR_NIC_CQ_CQ_NPT_FLIT_2_MID_CQ", AR_NIC_CQ_CQ_NPT_FLIT_2_MID_CQ, 8, 1, _ar_nic_cq_cq_npt_flit_2_mid_cq_detail
};
static const generic_mmr_t _ar_nic_cq_cq_npt_flit_2_lo_cq = {
    "AR_NIC_CQ_CQ_NPT_FLIT_2_LO_CQ", AR_NIC_CQ_CQ_NPT_FLIT_2_LO_CQ, 8, 1, _ar_nic_cq_cq_npt_flit_2_lo_cq_detail
};
static const generic_mmr_t _ar_nic_cq_cq_nat_request_3_hi_cq = {
    "AR_NIC_CQ_CQ_NAT_REQUEST_3_HI_CQ", AR_NIC_CQ_CQ_NAT_REQUEST_3_HI_CQ, 8, 1, _ar_nic_cq_cq_nat_request_3_hi_cq_detail
};
static const generic_mmr_t _ar_nic_cq_cq_nat_request_3_mid_cq = {
    "AR_NIC_CQ_CQ_NAT_REQUEST_3_MID_CQ", AR_NIC_CQ_CQ_NAT_REQUEST_3_MID_CQ, 8, 1, _ar_nic_cq_cq_nat_request_3_mid_cq_detail
};
static const generic_mmr_t _ar_nic_cq_cq_nat_request_3_lo_cq = {
    "AR_NIC_CQ_CQ_NAT_REQUEST_3_LO_CQ", AR_NIC_CQ_CQ_NAT_REQUEST_3_LO_CQ, 8, 1, _ar_nic_cq_cq_nat_request_3_lo_cq_detail
};
static const generic_mmr_t _ar_nic_cq_cq_acks_4_hi_cq = {
    "AR_NIC_CQ_CQ_ACKS_4_HI_CQ", AR_NIC_CQ_CQ_ACKS_4_HI_CQ, 8, 1, _ar_nic_cq_cq_acks_4_hi_cq_detail
};
static const generic_mmr_t _ar_nic_cq_cq_acks_4_mid_cq = {
    "AR_NIC_CQ_CQ_ACKS_4_MID_CQ", AR_NIC_CQ_CQ_ACKS_4_MID_CQ, 8, 1, _ar_nic_cq_cq_acks_4_mid_cq_detail
};
static const generic_mmr_t _ar_nic_cq_cq_acks_4_lo_cq = {
    "AR_NIC_CQ_CQ_ACKS_4_LO_CQ", AR_NIC_CQ_CQ_ACKS_4_LO_CQ, 8, 1, _ar_nic_cq_cq_acks_4_lo_cq_detail
};
static const generic_mmr_t _ar_nic_cq_cq_debug_5_hi_cq = {
    "AR_NIC_CQ_CQ_DEBUG_5_HI_CQ", AR_NIC_CQ_CQ_DEBUG_5_HI_CQ, 8, 1, _ar_nic_cq_cq_debug_5_hi_cq_detail
};
static const generic_mmr_t _ar_nic_cq_cq_debug_5_mid_cq = {
    "AR_NIC_CQ_CQ_DEBUG_5_MID_CQ", AR_NIC_CQ_CQ_DEBUG_5_MID_CQ, 8, 1, _ar_nic_cq_cq_debug_5_mid_cq_detail
};
static const generic_mmr_t _ar_nic_cq_cq_debug_5_lo_cq = {
    "AR_NIC_CQ_CQ_DEBUG_5_LO_CQ", AR_NIC_CQ_CQ_DEBUG_5_LO_CQ, 8, 1, _ar_nic_cq_cq_debug_5_lo_cq_detail
};
static const generic_mmr_t _ar_nic_cq_cfg_npt_credits = {
    "AR_NIC_CQ_CFG_NPT_CREDITS", AR_NIC_CQ_CFG_NPT_CREDITS, 8, 1, _ar_nic_cq_cfg_npt_credits_detail
};
static const generic_mmr_t _ar_nic_cq_cfg_cam_credits = {
    "AR_NIC_CQ_CFG_CAM_CREDITS", AR_NIC_CQ_CFG_CAM_CREDITS, 8, 1, _ar_nic_cq_cfg_cam_credits_detail
};
static const generic_mmr_t _ar_nic_cq_cfg_cache_revisit_rate = {
    "AR_NIC_CQ_CFG_CACHE_REVISIT_RATE", AR_NIC_CQ_CFG_CACHE_REVISIT_RATE, 8, 1, _ar_nic_cq_cfg_cache_revisit_rate_detail
};
static const generic_mmr_t _ar_nic_cq_cfg_nat_response_timeout = {
    "AR_NIC_CQ_CFG_NAT_RESPONSE_TIMEOUT", AR_NIC_CQ_CFG_NAT_RESPONSE_TIMEOUT, 8, 1, _ar_nic_cq_cfg_nat_response_timeout_detail
};
static const generic_mmr_t _ar_nic_cq_err_flg = {
    "AR_NIC_CQ_ERR_FLG", AR_NIC_CQ_ERR_FLG, 8, 1, _ar_nic_cq_err_flg_detail
};
static const generic_mmr_t _ar_nic_cq_err_clr = {
    "AR_NIC_CQ_ERR_CLR", AR_NIC_CQ_ERR_CLR, 8, 1, _ar_nic_cq_err_clr_detail
};
static const generic_mmr_t _ar_nic_cq_err_hss_msk = {
    "AR_NIC_CQ_ERR_HSS_MSK", AR_NIC_CQ_ERR_HSS_MSK, 8, 1, _ar_nic_cq_err_hss_msk_detail
};
static const generic_mmr_t _ar_nic_cq_err_os_msk = {
    "AR_NIC_CQ_ERR_OS_MSK", AR_NIC_CQ_ERR_OS_MSK, 8, 1, _ar_nic_cq_err_os_msk_detail
};
static const generic_mmr_t _ar_nic_cq_err_first_flg = {
    "AR_NIC_CQ_ERR_FIRST_FLG", AR_NIC_CQ_ERR_FIRST_FLG, 8, 1, _ar_nic_cq_err_first_flg_detail
};
static const generic_mmr_t _ar_nic_cq_err_info_desc_tbl_sbe_mbe = {
    "AR_NIC_CQ_ERR_INFO_DESC_TBL_SBE_MBE", AR_NIC_CQ_ERR_INFO_DESC_TBL_SBE_MBE, 8, 1, _ar_nic_cq_err_info_desc_tbl_sbe_mbe_detail
};
static const generic_mmr_t _ar_nic_cq_err_info_rmt_disabled_cq = {
    "AR_NIC_CQ_ERR_INFO_RMT_DISABLED_CQ", AR_NIC_CQ_ERR_INFO_RMT_DISABLED_CQ, 8, 1, _ar_nic_cq_err_info_rmt_disabled_cq_detail
};
static const generic_mmr_t _ar_nic_cq_err_info_rmt_nat_err = {
    "AR_NIC_CQ_ERR_INFO_RMT_NAT_ERR", AR_NIC_CQ_ERR_INFO_RMT_NAT_ERR, 8, 1, _ar_nic_cq_err_info_rmt_nat_err_detail
};
static const generic_mmr_t _ar_nic_cq_err_info_rmt_idx_bounds = {
    "AR_NIC_CQ_ERR_INFO_RMT_IDX_BOUNDS", AR_NIC_CQ_ERR_INFO_RMT_IDX_BOUNDS, 8, 1, _ar_nic_cq_err_info_rmt_idx_bounds_detail
};
static const generic_mmr_t _ar_nic_cq_err_info_rmt_dropped_event = {
    "AR_NIC_CQ_ERR_INFO_RMT_DROPPED_EVENT", AR_NIC_CQ_ERR_INFO_RMT_DROPPED_EVENT, 8, 1, _ar_nic_cq_err_info_rmt_dropped_event_detail
};
static const generic_mmr_t _ar_nic_cq_err_info_rmt_nat_response_timeout = {
    "AR_NIC_CQ_ERR_INFO_RMT_NAT_RESPONSE_TIMEOUT", AR_NIC_CQ_ERR_INFO_RMT_NAT_RESPONSE_TIMEOUT, 8, 1, _ar_nic_cq_err_info_rmt_nat_response_timeout_detail
};
static const generic_mmr_t _ar_nic_cq_err_info_lcl_disabled_cq = {
    "AR_NIC_CQ_ERR_INFO_LCL_DISABLED_CQ", AR_NIC_CQ_ERR_INFO_LCL_DISABLED_CQ, 8, 1, _ar_nic_cq_err_info_lcl_disabled_cq_detail
};
static const generic_mmr_t _ar_nic_cq_err_info_lcl_nat_err = {
    "AR_NIC_CQ_ERR_INFO_LCL_NAT_ERR", AR_NIC_CQ_ERR_INFO_LCL_NAT_ERR, 8, 1, _ar_nic_cq_err_info_lcl_nat_err_detail
};
static const generic_mmr_t _ar_nic_cq_err_info_lcl_idx_bounds = {
    "AR_NIC_CQ_ERR_INFO_LCL_IDX_BOUNDS", AR_NIC_CQ_ERR_INFO_LCL_IDX_BOUNDS, 8, 1, _ar_nic_cq_err_info_lcl_idx_bounds_detail
};
static const generic_mmr_t _ar_nic_cq_err_info_lcl_dropped_event = {
    "AR_NIC_CQ_ERR_INFO_LCL_DROPPED_EVENT", AR_NIC_CQ_ERR_INFO_LCL_DROPPED_EVENT, 8, 1, _ar_nic_cq_err_info_lcl_dropped_event_detail
};
static const generic_mmr_t _ar_nic_cq_err_info_lcl_nat_response_timeout = {
    "AR_NIC_CQ_ERR_INFO_LCL_NAT_RESPONSE_TIMEOUT", AR_NIC_CQ_ERR_INFO_LCL_NAT_RESPONSE_TIMEOUT, 8, 1, _ar_nic_cq_err_info_lcl_nat_response_timeout_detail
};
static const generic_mmr_t _ar_nic_cq_dbg_errinj_desc_tbl = {
    "AR_NIC_CQ_DBG_ERRINJ_DESC_TBL", AR_NIC_CQ_DBG_ERRINJ_DESC_TBL, 8, 1, _ar_nic_cq_dbg_errinj_desc_tbl_detail
};
static const generic_mmr_t _ar_nic_cq_dbg_errinj_parity = {
    "AR_NIC_CQ_DBG_ERRINJ_PARITY", AR_NIC_CQ_DBG_ERRINJ_PARITY, 8, 1, _ar_nic_cq_dbg_errinj_parity_detail
};
static const generic_mmr_t _ar_nic_cq_dbg_iommu_status = {
    "AR_NIC_CQ_DBG_IOMMU_STATUS", AR_NIC_CQ_DBG_IOMMU_STATUS, 8, 1, _ar_nic_cq_dbg_iommu_status_detail
};
static const generic_mmr_t _ar_nic_cq_dbg_state = {
    "AR_NIC_CQ_DBG_STATE", AR_NIC_CQ_DBG_STATE, 8, 1, _ar_nic_cq_dbg_state_detail
};

/*
 *  INSTALL AR CQ MMRS
 */
static const generic_mmr_t* _ar_cq_mmrs[] _unused = {
    &_ar_nic_cq_mmr_ring_0_hi_cq,
    &_ar_nic_cq_mmr_ring_0_mid_cq,
    &_ar_nic_cq_mmr_ring_0_lo_cq,
    &_ar_nic_cq_err_flg_1_hi_cq,
    &_ar_nic_cq_err_flg_1_mid_cq,
    &_ar_nic_cq_err_flg_1_lo_cq,
    &_ar_nic_cq_cq_npt_flit_2_hi_cq,
    &_ar_nic_cq_cq_npt_flit_2_mid_cq,
    &_ar_nic_cq_cq_npt_flit_2_lo_cq,
    &_ar_nic_cq_cq_nat_request_3_hi_cq,
    &_ar_nic_cq_cq_nat_request_3_mid_cq,
    &_ar_nic_cq_cq_nat_request_3_lo_cq,
    &_ar_nic_cq_cq_acks_4_hi_cq,
    &_ar_nic_cq_cq_acks_4_mid_cq,
    &_ar_nic_cq_cq_acks_4_lo_cq,
    &_ar_nic_cq_cq_debug_5_hi_cq,
    &_ar_nic_cq_cq_debug_5_mid_cq,
    &_ar_nic_cq_cq_debug_5_lo_cq,
    &_ar_nic_cq_cfg_npt_credits,
    &_ar_nic_cq_cfg_cam_credits,
    &_ar_nic_cq_cfg_cache_revisit_rate,
    &_ar_nic_cq_cfg_nat_response_timeout,
    &_ar_nic_cq_err_flg,
    &_ar_nic_cq_err_clr,
    &_ar_nic_cq_err_hss_msk,
    &_ar_nic_cq_err_os_msk,
    &_ar_nic_cq_err_first_flg,
    &_ar_nic_cq_err_info_desc_tbl_sbe_mbe,
    &_ar_nic_cq_err_info_rmt_disabled_cq,
    &_ar_nic_cq_err_info_rmt_nat_err,
    &_ar_nic_cq_err_info_rmt_idx_bounds,
    &_ar_nic_cq_err_info_rmt_dropped_event,
    &_ar_nic_cq_err_info_rmt_nat_response_timeout,
    &_ar_nic_cq_err_info_lcl_disabled_cq,
    &_ar_nic_cq_err_info_lcl_nat_err,
    &_ar_nic_cq_err_info_lcl_idx_bounds,
    &_ar_nic_cq_err_info_lcl_dropped_event,
    &_ar_nic_cq_err_info_lcl_nat_response_timeout,
    &_ar_nic_cq_dbg_errinj_desc_tbl,
    &_ar_nic_cq_dbg_errinj_parity,
    &_ar_nic_cq_dbg_iommu_status,
    &_ar_nic_cq_dbg_state,
    NULL
};

#endif
