/******************************************************************************
 * COPYRIGHT CRAY INC. ar_ce_mmrs_h.h
 * FILE: ar_ce_mmrs_h.h
 * Created by v2h.c on Wed Oct  8 14:38:58 2014
 ******************************************************************************/

#ifndef _AR_CE_MMRS_H_H_
#define _AR_CE_MMRS_H_H_

#ifdef __GNUC__
#define _unused __attribute__((unused))
#else
#define _unused
#endif

#ifndef _GENERIC_MMRD_T_
#define _GENERIC_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint64_t _mask;		/* Field bit mask */
} generic_mmrd_t;
#endif

#ifndef _ERRCAT_MMRD_T_
#define _ERRCAT_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint32_t _ec;		/* Field error category */
} errcat_mmrd_t;
#endif

#ifndef _GENERIC_MMR_T_
#define _GENERIC_MMR_T_
typedef struct {
	char* _name;		/* MMR name */
	uint64_t _addr;		/* MMR address */
	int _size;		/* Size in bytes of MMR */
	int _depth;		/* Number of MMR instances */
	const generic_mmrd_t *_info;	/* MMR detail */
} generic_mmr_t;
#endif

static const generic_mmr_t* _ar_ce_mmrs[] _unused;	/* CE Array */

/*
 *  AR CE MMR DETAIL DECLARATIONS
 */
static const generic_mmrd_t _ar_nic_ce_cfg_in_base_detail[] = {
    { "PKEY", AR_NIC_CE_CFG_IN_BASE_PKEY_BP, AR_NIC_CE_CFG_IN_BASE_PKEY_MASK },
    { "FP_ROUNDING_MODE", AR_NIC_CE_CFG_IN_BASE_FP_ROUNDING_MODE_BP, AR_NIC_CE_CFG_IN_BASE_FP_ROUNDING_MODE_MASK },
    { "NUMBER_OF_CHILDREN", AR_NIC_CE_CFG_IN_BASE_NUMBER_OF_CHILDREN_BP, AR_NIC_CE_CFG_IN_BASE_NUMBER_OF_CHILDREN_MASK },
    { "VC_RESET", AR_NIC_CE_CFG_IN_BASE_VC_RESET_BP, AR_NIC_CE_CFG_IN_BASE_VC_RESET_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_mmr_ring_cclk_0_hi_ce_detail[] = {
    { "N85B0_61", AR_NIC_CE_MMR_RING_CCLK_0_HI_CE_N85B0_61_BP, AR_NIC_CE_MMR_RING_CCLK_0_HI_CE_N85B0_61_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_mmr_ring_cclk_0_mid_ce_detail[] = {
    { "UNUSED_127_92", AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_UNUSED_127_92_BP, AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_UNUSED_127_92_MASK },
    { "CNTR_BAD_REQS", AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_CNTR_BAD_REQS_BP, AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_CNTR_BAD_REQS_MASK },
    { "CNTR_HEADER_PC", AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_CNTR_HEADER_PC_BP, AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_CNTR_HEADER_PC_MASK },
    { "CNTR_CONFIG_MBE", AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_CNTR_CONFIG_MBE_BP, AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_CNTR_CONFIG_MBE_MASK },
    { "CNTR_CONFIG_SBE", AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_CNTR_CONFIG_SBE_BP, AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_CNTR_CONFIG_SBE_MASK },
    { "CNTR_DFLIT_MBE", AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_CNTR_DFLIT_MBE_BP, AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_CNTR_DFLIT_MBE_MASK },
    { "CNTR_DFLIT_SBE", AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_CNTR_DFLIT_SBE_BP, AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_CNTR_DFLIT_SBE_MASK },
    { "CNTR_REDUCT_SCAT3", AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_CNTR_REDUCT_SCAT3_BP, AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_CNTR_REDUCT_SCAT3_MASK },
    { "CNTR_REDUCT_SCAT2", AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_CNTR_REDUCT_SCAT2_BP, AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_CNTR_REDUCT_SCAT2_MASK },
    { "CNTR_REDUCT_SCAT1", AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_CNTR_REDUCT_SCAT1_BP, AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_CNTR_REDUCT_SCAT1_MASK },
    { "CNTR_REDUCT_SCAT0", AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_CNTR_REDUCT_SCAT0_BP, AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_CNTR_REDUCT_SCAT0_MASK },
    { "UNUSED_81_64", AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_UNUSED_81_64_BP, AR_NIC_CE_MMR_RING_CCLK_0_MID_CE_UNUSED_81_64_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_mmr_ring_cclk_0_lo_ce_detail[] = {
    { "N85B0_61", AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_N85B0_61_BP, AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_N85B0_61_MASK },
    { "ANOTHER_RAT_ACK", AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_ANOTHER_RAT_ACK_BP, AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_ANOTHER_RAT_ACK_MASK },
    { "Q_NPT_FCNT", AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_Q_NPT_FCNT_BP, AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_Q_NPT_FCNT_MASK },
    { "STALL_NPT", AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_STALL_NPT_BP, AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_STALL_NPT_MASK },
    { "I_VC_RESET", AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_I_VC_RESET_BP, AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_I_VC_RESET_MASK },
    { "Q_FIRST_RED", AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_Q_FIRST_RED_BP, AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_Q_FIRST_RED_MASK },
    { "R_Q_MIN_MAX", AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_R_Q_MIN_MAX_BP, AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_R_Q_MIN_MAX_MASK },
    { "R_Q_DBLOP", AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_R_Q_DBLOP_BP, AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_R_Q_DBLOP_MASK },
    { "R_Q_VC_D2", AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_R_Q_VC_D2_BP, AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_R_Q_VC_D2_MASK },
    { "MMRR_Q_OS_IRQ", AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_MMRR_Q_OS_IRQ_BP, AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_MMRR_Q_OS_IRQ_MASK },
    { "MMRR_Q_HSS_IRQ", AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_MMRR_Q_HSS_IRQ_BP, AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_MMRR_Q_HSS_IRQ_MASK },
    { "R_Q_CE_NETMON_RING_WRACK", AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_R_Q_CE_NETMON_RING_WRACK_BP, AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_R_Q_CE_NETMON_RING_WRACK_MASK },
    { "R_Q_CE_NETMON_RING_15_0", AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_R_Q_CE_NETMON_RING_15_0_BP, AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_R_Q_CE_NETMON_RING_15_0_MASK },
    { "I_NETMON_CE_RING_15_0", AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_I_NETMON_CE_RING_15_0_BP, AR_NIC_CE_MMR_RING_CCLK_0_LO_CE_I_NETMON_CE_RING_15_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_err_flg_1_hi_ce_detail[] = {
    { "N1B0_145", AR_NIC_CE_ERR_FLG_1_HI_CE_N1B0_145_BP, AR_NIC_CE_ERR_FLG_1_HI_CE_N1B0_145_MASK },
    { "Q_SCATTER_IP", AR_NIC_CE_ERR_FLG_1_HI_CE_Q_SCATTER_IP_BP, AR_NIC_CE_ERR_FLG_1_HI_CE_Q_SCATTER_IP_MASK },
    { "Q_WAIT4RED", AR_NIC_CE_ERR_FLG_1_HI_CE_Q_WAIT4RED_BP, AR_NIC_CE_ERR_FLG_1_HI_CE_Q_WAIT4RED_MASK },
    { "Q_WAIT4SCATT", AR_NIC_CE_ERR_FLG_1_HI_CE_Q_WAIT4SCATT_BP, AR_NIC_CE_ERR_FLG_1_HI_CE_Q_WAIT4SCATT_MASK },
    { "Q_SCATTER_CMD_SG6", AR_NIC_CE_ERR_FLG_1_HI_CE_Q_SCATTER_CMD_SG6_BP, AR_NIC_CE_ERR_FLG_1_HI_CE_Q_SCATTER_CMD_SG6_MASK },
    { "I_RED_DONE", AR_NIC_CE_ERR_FLG_1_HI_CE_I_RED_DONE_BP, AR_NIC_CE_ERR_FLG_1_HI_CE_I_RED_DONE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_err_flg_1_mid_ce_detail[] = {
    { "UNUSED_127", AR_NIC_CE_ERR_FLG_1_MID_CE_UNUSED_127_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_UNUSED_127_MASK },
    { "REDENGN_OVRFLO", AR_NIC_CE_ERR_FLG_1_MID_CE_REDENGN_OVRFLO_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_REDENGN_OVRFLO_MASK },
    { "RAT_FIFO_OVRFLO", AR_NIC_CE_ERR_FLG_1_MID_CE_RAT_FIFO_OVRFLO_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_RAT_FIFO_OVRFLO_MASK },
    { "ADDRESS_ERR", AR_NIC_CE_ERR_FLG_1_MID_CE_ADDRESS_ERR_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_ADDRESS_ERR_MASK },
    { "MMR_REG_SBE", AR_NIC_CE_ERR_FLG_1_MID_CE_MMR_REG_SBE_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_MMR_REG_SBE_MASK },
    { "MMR_REG_MBE", AR_NIC_CE_ERR_FLG_1_MID_CE_MMR_REG_MBE_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_MMR_REG_MBE_MASK },
    { "OPERATION_DISABLED", AR_NIC_CE_ERR_FLG_1_MID_CE_OPERATION_DISABLED_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_OPERATION_DISABLED_MASK },
    { "HEADER_PC", AR_NIC_CE_ERR_FLG_1_MID_CE_HEADER_PC_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_HEADER_PC_MASK },
    { "HEADER_LSTATUS", AR_NIC_CE_ERR_FLG_1_MID_CE_HEADER_LSTATUS_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_HEADER_LSTATUS_MASK },
    { "HEADER_WITH_TAIL", AR_NIC_CE_ERR_FLG_1_MID_CE_HEADER_WITH_TAIL_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_HEADER_WITH_TAIL_MASK },
    { "INV_CE_CMD", AR_NIC_CE_ERR_FLG_1_MID_CE_INV_CE_CMD_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_INV_CE_CMD_MASK },
    { "INV_ALU_OP", AR_NIC_CE_ERR_FLG_1_MID_CE_INV_ALU_OP_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_INV_ALU_OP_MASK },
    { "INV_CNT_BM", AR_NIC_CE_ERR_FLG_1_MID_CE_INV_CNT_BM_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_INV_CNT_BM_MASK },
    { "BAD_OPERANDS", AR_NIC_CE_ERR_FLG_1_MID_CE_BAD_OPERANDS_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_BAD_OPERANDS_MASK },
    { "UNEXPECTED_SCATTER", AR_NIC_CE_ERR_FLG_1_MID_CE_UNEXPECTED_SCATTER_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_UNEXPECTED_SCATTER_MASK },
    { "DFLIT_SBE", AR_NIC_CE_ERR_FLG_1_MID_CE_DFLIT_SBE_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_DFLIT_SBE_MASK },
    { "DFLIT_MBE", AR_NIC_CE_ERR_FLG_1_MID_CE_DFLIT_MBE_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_DFLIT_MBE_MASK },
    { "PROTECTION_VIOLATION", AR_NIC_CE_ERR_FLG_1_MID_CE_PROTECTION_VIOLATION_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_PROTECTION_VIOLATION_MASK },
    { "UNEXPECTED_JOIN", AR_NIC_CE_ERR_FLG_1_MID_CE_UNEXPECTED_JOIN_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_UNEXPECTED_JOIN_MASK },
    { "DUPLICATE_JOIN", AR_NIC_CE_ERR_FLG_1_MID_CE_DUPLICATE_JOIN_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_DUPLICATE_JOIN_MASK },
    { "FIRST_OP_NOT_MATCH", AR_NIC_CE_ERR_FLG_1_MID_CE_FIRST_OP_NOT_MATCH_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_FIRST_OP_NOT_MATCH_MASK },
    { "FIRST_CNT_NOT_MATCH", AR_NIC_CE_ERR_FLG_1_MID_CE_FIRST_CNT_NOT_MATCH_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_FIRST_CNT_NOT_MATCH_MASK },
    { "MISMATCH_ERR", AR_NIC_CE_ERR_FLG_1_MID_CE_MISMATCH_ERR_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_MISMATCH_ERR_MASK },
    { "OP_INDX_REG_PC", AR_NIC_CE_ERR_FLG_1_MID_CE_OP_INDX_REG_PC_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_OP_INDX_REG_PC_MASK },
    { "JL_REG_PC", AR_NIC_CE_ERR_FLG_1_MID_CE_JL_REG_PC_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_JL_REG_PC_MASK },
    { "DIAG_ONLY", AR_NIC_CE_ERR_FLG_1_MID_CE_DIAG_ONLY_BP, AR_NIC_CE_ERR_FLG_1_MID_CE_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_err_flg_1_lo_ce_detail[] = {
    { "UNUSED_63", AR_NIC_CE_ERR_FLG_1_LO_CE_UNUSED_63_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_UNUSED_63_MASK },
    { "I_REDENGN_OVRFLO", AR_NIC_CE_ERR_FLG_1_LO_CE_I_REDENGN_OVRFLO_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_REDENGN_OVRFLO_MASK },
    { "I_RAT_FIFO_OVRFLO", AR_NIC_CE_ERR_FLG_1_LO_CE_I_RAT_FIFO_OVRFLO_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_RAT_FIFO_OVRFLO_MASK },
    { "I_ADDRESS_ERR", AR_NIC_CE_ERR_FLG_1_LO_CE_I_ADDRESS_ERR_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_ADDRESS_ERR_MASK },
    { "I_MMR_REG_SBE", AR_NIC_CE_ERR_FLG_1_LO_CE_I_MMR_REG_SBE_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_MMR_REG_SBE_MASK },
    { "I_MMR_REG_MBE", AR_NIC_CE_ERR_FLG_1_LO_CE_I_MMR_REG_MBE_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_MMR_REG_MBE_MASK },
    { "I_OPERATION_DISABLED", AR_NIC_CE_ERR_FLG_1_LO_CE_I_OPERATION_DISABLED_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_OPERATION_DISABLED_MASK },
    { "I_HEADER_PC", AR_NIC_CE_ERR_FLG_1_LO_CE_I_HEADER_PC_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_HEADER_PC_MASK },
    { "I_HEADER_LSTATUS", AR_NIC_CE_ERR_FLG_1_LO_CE_I_HEADER_LSTATUS_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_HEADER_LSTATUS_MASK },
    { "I_HEADER_WITH_TAIL", AR_NIC_CE_ERR_FLG_1_LO_CE_I_HEADER_WITH_TAIL_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_HEADER_WITH_TAIL_MASK },
    { "I_INV_CE_CMD", AR_NIC_CE_ERR_FLG_1_LO_CE_I_INV_CE_CMD_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_INV_CE_CMD_MASK },
    { "I_INV_ALU_OP", AR_NIC_CE_ERR_FLG_1_LO_CE_I_INV_ALU_OP_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_INV_ALU_OP_MASK },
    { "I_INV_CNT_BM", AR_NIC_CE_ERR_FLG_1_LO_CE_I_INV_CNT_BM_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_INV_CNT_BM_MASK },
    { "I_BAD_OPERANDS", AR_NIC_CE_ERR_FLG_1_LO_CE_I_BAD_OPERANDS_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_BAD_OPERANDS_MASK },
    { "I_UNEXPECTED_SCATTER", AR_NIC_CE_ERR_FLG_1_LO_CE_I_UNEXPECTED_SCATTER_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_UNEXPECTED_SCATTER_MASK },
    { "I_DFLIT_SBE", AR_NIC_CE_ERR_FLG_1_LO_CE_I_DFLIT_SBE_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_DFLIT_SBE_MASK },
    { "I_DFLIT_MBE", AR_NIC_CE_ERR_FLG_1_LO_CE_I_DFLIT_MBE_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_DFLIT_MBE_MASK },
    { "I_PROTECTION_VIOLATION", AR_NIC_CE_ERR_FLG_1_LO_CE_I_PROTECTION_VIOLATION_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_PROTECTION_VIOLATION_MASK },
    { "I_UNEXPECTED_JOIN", AR_NIC_CE_ERR_FLG_1_LO_CE_I_UNEXPECTED_JOIN_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_UNEXPECTED_JOIN_MASK },
    { "I_DUPLICATE_JOIN", AR_NIC_CE_ERR_FLG_1_LO_CE_I_DUPLICATE_JOIN_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_DUPLICATE_JOIN_MASK },
    { "I_FIRST_OP_NOT_MATCH", AR_NIC_CE_ERR_FLG_1_LO_CE_I_FIRST_OP_NOT_MATCH_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_FIRST_OP_NOT_MATCH_MASK },
    { "I_FIRST_CNT_NOT_MATCH", AR_NIC_CE_ERR_FLG_1_LO_CE_I_FIRST_CNT_NOT_MATCH_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_FIRST_CNT_NOT_MATCH_MASK },
    { "I_MISMATCH_ERR", AR_NIC_CE_ERR_FLG_1_LO_CE_I_MISMATCH_ERR_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_MISMATCH_ERR_MASK },
    { "I_OP_INDX_REG_PC", AR_NIC_CE_ERR_FLG_1_LO_CE_I_OP_INDX_REG_PC_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_OP_INDX_REG_PC_MASK },
    { "I_JL_REG_PC", AR_NIC_CE_ERR_FLG_1_LO_CE_I_JL_REG_PC_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_I_JL_REG_PC_MASK },
    { "UNUSED_0", AR_NIC_CE_ERR_FLG_1_LO_CE_UNUSED_0_BP, AR_NIC_CE_ERR_FLG_1_LO_CE_UNUSED_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_input_data2_cclk_2_hi_ce_detail[] = {
    { "Q_ANOTHER_CE_NPT_SB", AR_NIC_CE_CE_INPUT_DATA2_CCLK_2_HI_CE_Q_ANOTHER_CE_NPT_SB_BP, AR_NIC_CE_CE_INPUT_DATA2_CCLK_2_HI_CE_Q_ANOTHER_CE_NPT_SB_MASK },
    { "Q_ANOTHER_CE_NPT", AR_NIC_CE_CE_INPUT_DATA2_CCLK_2_HI_CE_Q_ANOTHER_CE_NPT_BP, AR_NIC_CE_CE_INPUT_DATA2_CCLK_2_HI_CE_Q_ANOTHER_CE_NPT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_input_data2_cclk_2_mid_ce_detail[] = {
    { "Q_ANOTHER_CE_NPT", AR_NIC_CE_CE_INPUT_DATA2_CCLK_2_MID_CE_Q_ANOTHER_CE_NPT_BP, AR_NIC_CE_CE_INPUT_DATA2_CCLK_2_MID_CE_Q_ANOTHER_CE_NPT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_input_data2_cclk_2_lo_ce_detail[] = {
    { "Q_ANOTHER_CE_NPT", AR_NIC_CE_CE_INPUT_DATA2_CCLK_2_LO_CE_Q_ANOTHER_CE_NPT_BP, AR_NIC_CE_CE_INPUT_DATA2_CCLK_2_LO_CE_Q_ANOTHER_CE_NPT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_input_data3_cclk_3_hi_ce_detail[] = {
    { "Q_SB_SG2", AR_NIC_CE_CE_INPUT_DATA3_CCLK_3_HI_CE_Q_SB_SG2_BP, AR_NIC_CE_CE_INPUT_DATA3_CCLK_3_HI_CE_Q_SB_SG2_MASK },
    { "Q_FLIT_SG2", AR_NIC_CE_CE_INPUT_DATA3_CCLK_3_HI_CE_Q_FLIT_SG2_BP, AR_NIC_CE_CE_INPUT_DATA3_CCLK_3_HI_CE_Q_FLIT_SG2_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_input_data3_cclk_3_mid_ce_detail[] = {
    { "Q_FLIT_SG2", AR_NIC_CE_CE_INPUT_DATA3_CCLK_3_MID_CE_Q_FLIT_SG2_BP, AR_NIC_CE_CE_INPUT_DATA3_CCLK_3_MID_CE_Q_FLIT_SG2_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_input_data3_cclk_3_lo_ce_detail[] = {
    { "Q_FLIT_SG2", AR_NIC_CE_CE_INPUT_DATA3_CCLK_3_LO_CE_Q_FLIT_SG2_BP, AR_NIC_CE_CE_INPUT_DATA3_CCLK_3_LO_CE_Q_FLIT_SG2_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_input_data4_cclk_4_hi_ce_detail[] = {
    { "N9B0_137", AR_NIC_CE_CE_INPUT_DATA4_CCLK_4_HI_CE_N9B0_137_BP, AR_NIC_CE_CE_INPUT_DATA4_CCLK_4_HI_CE_N9B0_137_MASK },
    { "R_Q_FLIT4REDENGN_134_72", AR_NIC_CE_CE_INPUT_DATA4_CCLK_4_HI_CE_R_Q_FLIT4REDENGN_134_72_BP, AR_NIC_CE_CE_INPUT_DATA4_CCLK_4_HI_CE_R_Q_FLIT4REDENGN_134_72_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_input_data4_cclk_4_mid_ce_detail[] = {
    { "R_Q_FLIT4REDENGN_134_72", AR_NIC_CE_CE_INPUT_DATA4_CCLK_4_MID_CE_R_Q_FLIT4REDENGN_134_72_BP, AR_NIC_CE_CE_INPUT_DATA4_CCLK_4_MID_CE_R_Q_FLIT4REDENGN_134_72_MASK },
    { "R_Q_FLIT4REDENGN_61_0", AR_NIC_CE_CE_INPUT_DATA4_CCLK_4_MID_CE_R_Q_FLIT4REDENGN_61_0_BP, AR_NIC_CE_CE_INPUT_DATA4_CCLK_4_MID_CE_R_Q_FLIT4REDENGN_61_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_input_data4_cclk_4_lo_ce_detail[] = {
    { "R_Q_FLIT4REDENGN_61_0", AR_NIC_CE_CE_INPUT_DATA4_CCLK_4_LO_CE_R_Q_FLIT4REDENGN_61_0_BP, AR_NIC_CE_CE_INPUT_DATA4_CCLK_4_LO_CE_R_Q_FLIT4REDENGN_61_0_MASK },
    { "R_Q_HD_VAL", AR_NIC_CE_CE_INPUT_DATA4_CCLK_4_LO_CE_R_Q_HD_VAL_BP, AR_NIC_CE_CE_INPUT_DATA4_CCLK_4_LO_CE_R_Q_HD_VAL_MASK },
    { "R_Q_HD_CNT", AR_NIC_CE_CE_INPUT_DATA4_CCLK_4_LO_CE_R_Q_HD_CNT_BP, AR_NIC_CE_CE_INPUT_DATA4_CCLK_4_LO_CE_R_Q_HD_CNT_MASK },
    { "R_Q_ADV_SCAT_CNT", AR_NIC_CE_CE_INPUT_DATA4_CCLK_4_LO_CE_R_Q_ADV_SCAT_CNT_BP, AR_NIC_CE_CE_INPUT_DATA4_CCLK_4_LO_CE_R_Q_ADV_SCAT_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_input_data5_cclk_5_hi_ce_detail[] = {
    { "N18B0_128", AR_NIC_CE_CE_INPUT_DATA5_CCLK_5_HI_CE_N18B0_128_BP, AR_NIC_CE_CE_INPUT_DATA5_CCLK_5_HI_CE_N18B0_128_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_input_data5_cclk_5_mid_ce_detail[] = {
    { "Q_VC3_WHOS_IN", AR_NIC_CE_CE_INPUT_DATA5_CCLK_5_MID_CE_Q_VC3_WHOS_IN_BP, AR_NIC_CE_CE_INPUT_DATA5_CCLK_5_MID_CE_Q_VC3_WHOS_IN_MASK },
    { "Q_VC2_WHOS_IN", AR_NIC_CE_CE_INPUT_DATA5_CCLK_5_MID_CE_Q_VC2_WHOS_IN_BP, AR_NIC_CE_CE_INPUT_DATA5_CCLK_5_MID_CE_Q_VC2_WHOS_IN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_input_data5_cclk_5_lo_ce_detail[] = {
    { "Q_VC1_WHOS_IN", AR_NIC_CE_CE_INPUT_DATA5_CCLK_5_LO_CE_Q_VC1_WHOS_IN_BP, AR_NIC_CE_CE_INPUT_DATA5_CCLK_5_LO_CE_Q_VC1_WHOS_IN_MASK },
    { "Q_VC0_WHOS_IN", AR_NIC_CE_CE_INPUT_DATA5_CCLK_5_LO_CE_Q_VC0_WHOS_IN_BP, AR_NIC_CE_CE_INPUT_DATA5_CCLK_5_LO_CE_Q_VC0_WHOS_IN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_input_data6_cclk_6_hi_ce_detail[] = {
    { "N46B0_100", AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_HI_CE_N46B0_100_BP, AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_HI_CE_N46B0_100_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_input_data6_cclk_6_mid_ce_detail[] = {
    { "N46B0_100", AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_MID_CE_N46B0_100_BP, AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_MID_CE_N46B0_100_MASK },
    { "Q_VC0_FIRST_RED_ID", AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_MID_CE_Q_VC0_FIRST_RED_ID_BP, AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_MID_CE_Q_VC0_FIRST_RED_ID_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_input_data6_cclk_6_lo_ce_detail[] = {
    { "Q_VC0_FIRST_RED_ID", AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_LO_CE_Q_VC0_FIRST_RED_ID_BP, AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_LO_CE_Q_VC0_FIRST_RED_ID_MASK },
    { "R_Q_VC0_FIRST_OP", AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_LO_CE_R_Q_VC0_FIRST_OP_BP, AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_LO_CE_R_Q_VC0_FIRST_OP_MASK },
    { "N1B0_53", AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_LO_CE_N1B0_53_BP, AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_LO_CE_N1B0_53_MASK },
    { "R_Q_VC0_FIRST_CNT", AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_LO_CE_R_Q_VC0_FIRST_CNT_BP, AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_LO_CE_R_Q_VC0_FIRST_CNT_MASK },
    { "Q_VC1_FIRST_RED_ID", AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_LO_CE_Q_VC1_FIRST_RED_ID_BP, AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_LO_CE_Q_VC1_FIRST_RED_ID_MASK },
    { "R_Q_VC1_FIRST_OP", AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_LO_CE_R_Q_VC1_FIRST_OP_BP, AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_LO_CE_R_Q_VC1_FIRST_OP_MASK },
    { "N1B0_3", AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_LO_CE_N1B0_3_BP, AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_LO_CE_N1B0_3_MASK },
    { "R_Q_VC1_FIRST_CNT", AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_LO_CE_R_Q_VC1_FIRST_CNT_BP, AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_LO_CE_R_Q_VC1_FIRST_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_input_data7_cclk_7_hi_ce_detail[] = {
    { "N46B0_100", AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_HI_CE_N46B0_100_BP, AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_HI_CE_N46B0_100_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_input_data7_cclk_7_mid_ce_detail[] = {
    { "N46B0_100", AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_MID_CE_N46B0_100_BP, AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_MID_CE_N46B0_100_MASK },
    { "Q_VC2_FIRST_RED_ID", AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_MID_CE_Q_VC2_FIRST_RED_ID_BP, AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_MID_CE_Q_VC2_FIRST_RED_ID_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_input_data7_cclk_7_lo_ce_detail[] = {
    { "Q_VC2_FIRST_RED_ID", AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_LO_CE_Q_VC2_FIRST_RED_ID_BP, AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_LO_CE_Q_VC2_FIRST_RED_ID_MASK },
    { "R_Q_VC2_FIRST_OP", AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_LO_CE_R_Q_VC2_FIRST_OP_BP, AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_LO_CE_R_Q_VC2_FIRST_OP_MASK },
    { "N1B0_53", AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_LO_CE_N1B0_53_BP, AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_LO_CE_N1B0_53_MASK },
    { "R_Q_VC2_FIRST_CNT", AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_LO_CE_R_Q_VC2_FIRST_CNT_BP, AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_LO_CE_R_Q_VC2_FIRST_CNT_MASK },
    { "Q_VC3_FIRST_RED_ID", AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_LO_CE_Q_VC3_FIRST_RED_ID_BP, AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_LO_CE_Q_VC3_FIRST_RED_ID_MASK },
    { "R_Q_VC3_FIRST_OP", AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_LO_CE_R_Q_VC3_FIRST_OP_BP, AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_LO_CE_R_Q_VC3_FIRST_OP_MASK },
    { "N1B0_3", AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_LO_CE_N1B0_3_BP, AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_LO_CE_N1B0_3_MASK },
    { "R_Q_VC3_FIRST_CNT", AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_LO_CE_R_Q_VC3_FIRST_CNT_BP, AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_LO_CE_R_Q_VC3_FIRST_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_redengn_data7_cclk_8_hi_ce_detail[] = {
    { "INDEXB1", AR_NIC_CE_CE_REDENGN_DATA7_CCLK_8_HI_CE_INDEXB1_BP, AR_NIC_CE_CE_REDENGN_DATA7_CCLK_8_HI_CE_INDEXB1_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_redengn_data7_cclk_8_mid_ce_detail[] = {
    { "INDEXB1", AR_NIC_CE_CE_REDENGN_DATA7_CCLK_8_MID_CE_INDEXB1_BP, AR_NIC_CE_CE_REDENGN_DATA7_CCLK_8_MID_CE_INDEXB1_MASK },
    { "Q_INDEXB2", AR_NIC_CE_CE_REDENGN_DATA7_CCLK_8_MID_CE_Q_INDEXB2_BP, AR_NIC_CE_CE_REDENGN_DATA7_CCLK_8_MID_CE_Q_INDEXB2_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_redengn_data7_cclk_8_lo_ce_detail[] = {
    { "Q_INDEXB2", AR_NIC_CE_CE_REDENGN_DATA7_CCLK_8_LO_CE_Q_INDEXB2_BP, AR_NIC_CE_CE_REDENGN_DATA7_CCLK_8_LO_CE_Q_INDEXB2_MASK },
    { "Q_DBL_SFT_RR", AR_NIC_CE_CE_REDENGN_DATA7_CCLK_8_LO_CE_Q_DBL_SFT_RR_BP, AR_NIC_CE_CE_REDENGN_DATA7_CCLK_8_LO_CE_Q_DBL_SFT_RR_MASK },
    { "R_FP_EXCPT", AR_NIC_CE_CE_REDENGN_DATA7_CCLK_8_LO_CE_R_FP_EXCPT_BP, AR_NIC_CE_CE_REDENGN_DATA7_CCLK_8_LO_CE_R_FP_EXCPT_MASK },
    { "Q_VC2_JRD_ADDR", AR_NIC_CE_CE_REDENGN_DATA7_CCLK_8_LO_CE_Q_VC2_JRD_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA7_CCLK_8_LO_CE_Q_VC2_JRD_ADDR_MASK },
    { "Q_VC3_JRD_ADDR", AR_NIC_CE_CE_REDENGN_DATA7_CCLK_8_LO_CE_Q_VC3_JRD_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA7_CCLK_8_LO_CE_Q_VC3_JRD_ADDR_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_redengn_data6_cclk_9_hi_ce_detail[] = {
    { "Q_OSFT_RR0", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_HI_CE_Q_OSFT_RR0_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_HI_CE_Q_OSFT_RR0_MASK },
    { "Q_ISFT_RR0", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_HI_CE_Q_ISFT_RR0_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_HI_CE_Q_ISFT_RR0_MASK },
    { "Q_OPN_RBN", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_HI_CE_Q_OPN_RBN_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_HI_CE_Q_OPN_RBN_MASK },
    { "Q_IDX_RBN", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_HI_CE_Q_IDX_RBN_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_HI_CE_Q_IDX_RBN_MASK },
    { "Q_VC0_OPND_CNT", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_HI_CE_Q_VC0_OPND_CNT_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_HI_CE_Q_VC0_OPND_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_redengn_data6_cclk_9_mid_ce_detail[] = {
    { "Q_VC0_OPND_CNT", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_Q_VC0_OPND_CNT_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_Q_VC0_OPND_CNT_MASK },
    { "Q_VC1_OPND_CNT", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_Q_VC1_OPND_CNT_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_Q_VC1_OPND_CNT_MASK },
    { "Q_VC2_OPND_CNT", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_Q_VC2_OPND_CNT_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_Q_VC2_OPND_CNT_MASK },
    { "Q_VC3_OPND_CNT", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_Q_VC3_OPND_CNT_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_Q_VC3_OPND_CNT_MASK },
    { "Q_LOJC", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_Q_LOJC_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_Q_LOJC_MASK },
    { "Q_LIJC", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_Q_LIJC_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_Q_LIJC_MASK },
    { "R_Q_VC0_JOIN_CNT", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_VC0_JOIN_CNT_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_VC0_JOIN_CNT_MASK },
    { "R_Q_VC1_JOIN_CNT", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_VC1_JOIN_CNT_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_VC1_JOIN_CNT_MASK },
    { "R_Q_VC2_JOIN_CNT", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_VC2_JOIN_CNT_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_VC2_JOIN_CNT_MASK },
    { "R_Q_VC3_JOIN_CNT", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_VC3_JOIN_CNT_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_VC3_JOIN_CNT_MASK },
    { "R_Q_ODONE0", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_ODONE0_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_ODONE0_MASK },
    { "R_Q_ODONE1", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_ODONE1_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_ODONE1_MASK },
    { "R_Q_ODONE2", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_ODONE2_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_ODONE2_MASK },
    { "R_Q_ODONE3", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_ODONE3_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_ODONE3_MASK },
    { "R_Q_IDONE0", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_IDONE0_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_IDONE0_MASK },
    { "R_Q_IDONE1", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_IDONE1_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_IDONE1_MASK },
    { "R_Q_IDONE2", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_IDONE2_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_IDONE2_MASK },
    { "R_Q_IDONE3", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_IDONE3_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_R_Q_IDONE3_MASK },
    { "ALU_RESULT", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_ALU_RESULT_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE_ALU_RESULT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_redengn_data6_cclk_9_lo_ce_detail[] = {
    { "ALU_RESULT", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_LO_CE_ALU_RESULT_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_LO_CE_ALU_RESULT_MASK },
    { "SEL_INDX1", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_LO_CE_SEL_INDX1_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_LO_CE_SEL_INDX1_MASK },
    { "SEL_EQ", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_LO_CE_SEL_EQ_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_LO_CE_SEL_EQ_MASK },
    { "Q_INDX1GTR2", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_LO_CE_Q_INDX1GTR2_BP, AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_LO_CE_Q_INDX1GTR2_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_redengn_data5_cclk_a_hi_ce_detail[] = {
    { "Q_ALU_OPRND_1", AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_HI_CE_Q_ALU_OPRND_1_BP, AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_HI_CE_Q_ALU_OPRND_1_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_redengn_data5_cclk_a_mid_ce_detail[] = {
    { "Q_ALU_OPRND_1", AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_MID_CE_Q_ALU_OPRND_1_BP, AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_MID_CE_Q_ALU_OPRND_1_MASK },
    { "Q_ALU_OPRND_2", AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_MID_CE_Q_ALU_OPRND_2_BP, AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_MID_CE_Q_ALU_OPRND_2_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_redengn_data5_cclk_a_lo_ce_detail[] = {
    { "Q_ALU_OPRND_2", AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_LO_CE_Q_ALU_OPRND_2_BP, AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_LO_CE_Q_ALU_OPRND_2_MASK },
    { "Q_ALU_CMD", AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_LO_CE_Q_ALU_CMD_BP, AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_LO_CE_Q_ALU_CMD_MASK },
    { "Q_MODE32", AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_LO_CE_Q_MODE32_BP, AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_LO_CE_Q_MODE32_MASK },
    { "Q_RND_MODE", AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_LO_CE_Q_RND_MODE_BP, AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_LO_CE_Q_RND_MODE_MASK },
    { "Q_MM_MOD_0", AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_LO_CE_Q_MM_MOD_0_BP, AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_LO_CE_Q_MM_MOD_0_MASK },
    { "Q_SELO1_RBN", AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_LO_CE_Q_SELO1_RBN_BP, AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_LO_CE_Q_SELO1_RBN_MASK },
    { "N1B0_6", AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_LO_CE_N1B0_6_BP, AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_LO_CE_N1B0_6_MASK },
    { "Q_SELI1_RBN", AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_LO_CE_Q_SELI1_RBN_BP, AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_LO_CE_Q_SELI1_RBN_MASK },
    { "Q_RES_IDX_SEL1", AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_LO_CE_Q_RES_IDX_SEL1_BP, AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_LO_CE_Q_RES_IDX_SEL1_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_redengn_data0_cclk_b_hi_ce_detail[] = {
    { "Q_OPND_WE", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_HI_CE_Q_OPND_WE_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_HI_CE_Q_OPND_WE_MASK },
    { "Q_HDR_CNT", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_HI_CE_Q_HDR_CNT_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_HI_CE_Q_HDR_CNT_MASK },
    { "Q_INDX_WE", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_HI_CE_Q_INDX_WE_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_HI_CE_Q_INDX_WE_MASK },
    { "Q_VC0_JWR_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_HI_CE_Q_VC0_JWR_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_HI_CE_Q_VC0_JWR_ADDR_MASK },
    { "Q_VC1_JWR_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_HI_CE_Q_VC1_JWR_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_HI_CE_Q_VC1_JWR_ADDR_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_redengn_data0_cclk_b_mid_ce_detail[] = {
    { "Q_VC1_JWR_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_VC1_JWR_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_VC1_JWR_ADDR_MASK },
    { "Q_VC2_JWR_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_VC2_JWR_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_VC2_JWR_ADDR_MASK },
    { "Q_VC3_JWR_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_VC3_JWR_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_VC3_JWR_ADDR_MASK },
    { "Q_VC0_OWR_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_VC0_OWR_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_VC0_OWR_ADDR_MASK },
    { "Q_VC1_OWR_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_VC1_OWR_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_VC1_OWR_ADDR_MASK },
    { "Q_VC2_OWR_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_VC2_OWR_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_VC2_OWR_ADDR_MASK },
    { "Q_VC3_OWR_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_VC3_OWR_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_VC3_OWR_ADDR_MASK },
    { "Q_VC0_IWR_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_VC0_IWR_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_VC0_IWR_ADDR_MASK },
    { "Q_VC1_IWR_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_VC1_IWR_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_VC1_IWR_ADDR_MASK },
    { "Q_VC2_IWR_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_VC2_IWR_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_VC2_IWR_ADDR_MASK },
    { "Q_VC3_IWR_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_VC3_IWR_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_VC3_IWR_ADDR_MASK },
    { "Q_OWIAT4JOINC", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_OWIAT4JOINC_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_OWIAT4JOINC_MASK },
    { "Q_IWAIT4JOINC", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_IWAIT4JOINC_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_IWAIT4JOINC_MASK },
    { "Q_INIT_OPND", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_INIT_OPND_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE_Q_INIT_OPND_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_redengn_data0_cclk_b_lo_ce_detail[] = {
    { "Q_INIT_OPND", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_INIT_OPND_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_INIT_OPND_MASK },
    { "Q_OPND_VAL", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_OPND_VAL_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_OPND_VAL_MASK },
    { "Q_INIT_INDX", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_INIT_INDX_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_INIT_INDX_MASK },
    { "Q_INDX_VAL", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_INDX_VAL_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_INDX_VAL_MASK },
    { "Q_VC0_ORD_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_VC0_ORD_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_VC0_ORD_ADDR_MASK },
    { "Q_VC1_ORD_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_VC1_ORD_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_VC1_ORD_ADDR_MASK },
    { "Q_VC2_ORD_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_VC2_ORD_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_VC2_ORD_ADDR_MASK },
    { "Q_VC3_ORD_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_VC3_ORD_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_VC3_ORD_ADDR_MASK },
    { "Q_VC0_IRD_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_VC0_IRD_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_VC0_IRD_ADDR_MASK },
    { "Q_VC1_IRD_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_VC1_IRD_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_VC1_IRD_ADDR_MASK },
    { "Q_VC2_IRD_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_VC2_IRD_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_VC2_IRD_ADDR_MASK },
    { "Q_VC3_IRD_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_VC3_IRD_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_VC3_IRD_ADDR_MASK },
    { "Q_VC0_JRD_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_VC0_JRD_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_VC0_JRD_ADDR_MASK },
    { "Q_VC1_JRD_ADDR", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_VC1_JRD_ADDR_BP, AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE_Q_VC1_JRD_ADDR_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_req_data19_cclk_c_hi_ce_detail[] = {
    { "N36B0_110", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_HI_CE_N36B0_110_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_HI_CE_N36B0_110_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_req_data19_cclk_c_mid_ce_detail[] = {
    { "N36B0_110", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_N36B0_110_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_N36B0_110_MASK },
    { "Q_HD_VAL", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_Q_HD_VAL_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_Q_HD_VAL_MASK },
    { "Q_SCAT_INITD2", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_Q_SCAT_INITD2_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_Q_SCAT_INITD2_MASK },
    { "Q_PART_DONE", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_Q_PART_DONE_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_Q_PART_DONE_MASK },
    { "Q_RED_DONE", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_Q_RED_DONE_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_Q_RED_DONE_MASK },
    { "R_Q_ROOT_INIT", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_R_Q_ROOT_INIT_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_R_Q_ROOT_INIT_MASK },
    { "Q_SD_VAL", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_Q_SD_VAL_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_Q_SD_VAL_MASK },
    { "Q_DFLIT_WE_DLY", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_Q_DFLIT_WE_DLY_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_Q_DFLIT_WE_DLY_MASK },
    { "Q_HFLIT_WE_DLY", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_Q_HFLIT_WE_DLY_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_Q_HFLIT_WE_DLY_MASK },
    { "Q_FLIT_CNT", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_Q_FLIT_CNT_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_Q_FLIT_CNT_MASK },
    { "Q_VC0_SCAT_CNT", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_Q_VC0_SCAT_CNT_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_Q_VC0_SCAT_CNT_MASK },
    { "Q_VC1_SCAT_CNT", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_Q_VC1_SCAT_CNT_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_Q_VC1_SCAT_CNT_MASK },
    { "Q_VC2_SCAT_CNT", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_Q_VC2_SCAT_CNT_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE_Q_VC2_SCAT_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_req_data19_cclk_c_lo_ce_detail[] = {
    { "Q_VC2_SCAT_CNT", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC2_SCAT_CNT_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC2_SCAT_CNT_MASK },
    { "Q_VC3_SCAT_CNT", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC3_SCAT_CNT_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC3_SCAT_CNT_MASK },
    { "Q_VC0_SCAT_END", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC0_SCAT_END_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC0_SCAT_END_MASK },
    { "Q_VC1_SCAT_END", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC1_SCAT_END_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC1_SCAT_END_MASK },
    { "Q_VC2_SCAT_END", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC2_SCAT_END_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC2_SCAT_END_MASK },
    { "Q_VC3_SCAT_END", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC3_SCAT_END_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC3_SCAT_END_MASK },
    { "Q_VC0_CMPLT", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC0_CMPLT_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC0_CMPLT_MASK },
    { "Q_VC1_CMPLT", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC1_CMPLT_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC1_CMPLT_MASK },
    { "Q_VC2_CMPLT", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC2_CMPLT_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC2_CMPLT_MASK },
    { "Q_VC3_CMPLT", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC3_CMPLT_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC3_CMPLT_MASK },
    { "Q_VC0_SCAT_IP", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC0_SCAT_IP_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC0_SCAT_IP_MASK },
    { "Q_VC1_SCAT_IP", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC1_SCAT_IP_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC1_SCAT_IP_MASK },
    { "Q_VC2_SCAT_IP", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC2_SCAT_IP_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC2_SCAT_IP_MASK },
    { "Q_VC3_SCAT_IP", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC3_SCAT_IP_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC3_SCAT_IP_MASK },
    { "Q_VC0_SCAT_INPROC", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC0_SCAT_INPROC_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC0_SCAT_INPROC_MASK },
    { "Q_VC1_SCAT_INPROC", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC1_SCAT_INPROC_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC1_SCAT_INPROC_MASK },
    { "Q_VC2_SCAT_INPROC", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC2_SCAT_INPROC_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC2_SCAT_INPROC_MASK },
    { "Q_VC3_SCAT_INPROC", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC3_SCAT_INPROC_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC3_SCAT_INPROC_MASK },
    { "R_Q_SCAT_DONE", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_R_Q_SCAT_DONE_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_R_Q_SCAT_DONE_MASK },
    { "Q_VC0_FIRST_REQ", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC0_FIRST_REQ_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC0_FIRST_REQ_MASK },
    { "Q_VC1_FIRST_REQ", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC1_FIRST_REQ_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC1_FIRST_REQ_MASK },
    { "Q_VC2_FIRST_REQ", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC2_FIRST_REQ_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC2_FIRST_REQ_MASK },
    { "Q_VC3_FIRST_REQ", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC3_FIRST_REQ_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_VC3_FIRST_REQ_MASK },
    { "Q_LPN", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_LPN_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_LPN_MASK },
    { "Q_RND_RBN", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_RND_RBN_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_RND_RBN_MASK },
    { "Q_SEL2_1", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_SEL2_1_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_SEL2_1_MASK },
    { "Q_SEL2_2", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_SEL2_2_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_SEL2_2_MASK },
    { "D2_SEL", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_D2_SEL_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_D2_SEL_MASK },
    { "Q_STALL4FLIT", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_STALL4FLIT_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_STALL4FLIT_MASK },
    { "Q_SEL1_1", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_SEL1_1_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_SEL1_1_MASK },
    { "Q_SEL1_2", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_SEL1_2_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_SEL1_2_MASK },
    { "Q_SEL21", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_SEL21_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_SEL21_MASK },
    { "Q_SEL_SYNCCMPLT", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_SEL_SYNCCMPLT_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_SEL_SYNCCMPLT_MASK },
    { "Q_SEL_SYNCCMPLTD", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_SEL_SYNCCMPLTD_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_SEL_SYNCCMPLTD_MASK },
    { "Q_HFLIT_WE", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_HFLIT_WE_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_HFLIT_WE_MASK },
    { "Q_DFLIT_WE", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_DFLIT_WE_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_DFLIT_WE_MASK },
    { "Q_HDR_SEL", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_HDR_SEL_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_HDR_SEL_MASK },
    { "Q_SEL0", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_SEL0_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_SEL0_MASK },
    { "Q_DAT_SEL", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_DAT_SEL_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_DAT_SEL_MASK },
    { "Q_TAILON1", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_TAILON1_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_TAILON1_MASK },
    { "Q_TAILON2", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_TAILON2_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_TAILON2_MASK },
    { "Q_TAIL", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_TAIL_BP, AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE_Q_TAIL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_req_data18_cclk_d_hi_ce_detail[] = {
    { "N6B0_140", AR_NIC_CE_CE_REQ_DATA18_CCLK_D_HI_CE_N6B0_140_BP, AR_NIC_CE_CE_REQ_DATA18_CCLK_D_HI_CE_N6B0_140_MASK },
    { "Q_DAT4PGEN", AR_NIC_CE_CE_REQ_DATA18_CCLK_D_HI_CE_Q_DAT4PGEN_BP, AR_NIC_CE_CE_REQ_DATA18_CCLK_D_HI_CE_Q_DAT4PGEN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_req_data18_cclk_d_mid_ce_detail[] = {
    { "Q_DAT4PGEN", AR_NIC_CE_CE_REQ_DATA18_CCLK_D_MID_CE_Q_DAT4PGEN_BP, AR_NIC_CE_CE_REQ_DATA18_CCLK_D_MID_CE_Q_DAT4PGEN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_req_data18_cclk_d_lo_ce_detail[] = {
    { "Q_DAT4PGEN", AR_NIC_CE_CE_REQ_DATA18_CCLK_D_LO_CE_Q_DAT4PGEN_BP, AR_NIC_CE_CE_REQ_DATA18_CCLK_D_LO_CE_Q_DAT4PGEN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_req_data17_cclk_e_hi_ce_detail[] = {
    { "Q_TARB_SB_RELAY", AR_NIC_CE_CE_REQ_DATA17_CCLK_E_HI_CE_Q_TARB_SB_RELAY_BP, AR_NIC_CE_CE_REQ_DATA17_CCLK_E_HI_CE_Q_TARB_SB_RELAY_MASK },
    { "Q_TARB_FLIT_RELAY", AR_NIC_CE_CE_REQ_DATA17_CCLK_E_HI_CE_Q_TARB_FLIT_RELAY_BP, AR_NIC_CE_CE_REQ_DATA17_CCLK_E_HI_CE_Q_TARB_FLIT_RELAY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_req_data17_cclk_e_mid_ce_detail[] = {
    { "Q_TARB_FLIT_RELAY", AR_NIC_CE_CE_REQ_DATA17_CCLK_E_MID_CE_Q_TARB_FLIT_RELAY_BP, AR_NIC_CE_CE_REQ_DATA17_CCLK_E_MID_CE_Q_TARB_FLIT_RELAY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_req_data17_cclk_e_lo_ce_detail[] = {
    { "Q_TARB_FLIT_RELAY", AR_NIC_CE_CE_REQ_DATA17_CCLK_E_LO_CE_Q_TARB_FLIT_RELAY_BP, AR_NIC_CE_CE_REQ_DATA17_CCLK_E_LO_CE_Q_TARB_FLIT_RELAY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_req_data2_cclk_f_hi_ce_detail[] = {
    { "N14B0_132", AR_NIC_CE_CE_REQ_DATA2_CCLK_F_HI_CE_N14B0_132_BP, AR_NIC_CE_CE_REQ_DATA2_CCLK_F_HI_CE_N14B0_132_MASK },
    { "Q_SCAT_INIT", AR_NIC_CE_CE_REQ_DATA2_CCLK_F_HI_CE_Q_SCAT_INIT_BP, AR_NIC_CE_CE_REQ_DATA2_CCLK_F_HI_CE_Q_SCAT_INIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_req_data2_cclk_f_mid_ce_detail[] = {
    { "Q_VC2_CCW", AR_NIC_CE_CE_REQ_DATA2_CCLK_F_MID_CE_Q_VC2_CCW_BP, AR_NIC_CE_CE_REQ_DATA2_CCLK_F_MID_CE_Q_VC2_CCW_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_req_data2_cclk_f_lo_ce_detail[] = {
    { "Q_VC3_CCW", AR_NIC_CE_CE_REQ_DATA2_CCLK_F_LO_CE_Q_VC3_CCW_BP, AR_NIC_CE_CE_REQ_DATA2_CCLK_F_LO_CE_Q_VC3_CCW_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_req_data0_cclk_10_hi_ce_detail[] = {
    { "N18B0_128", AR_NIC_CE_CE_REQ_DATA0_CCLK_10_HI_CE_N18B0_128_BP, AR_NIC_CE_CE_REQ_DATA0_CCLK_10_HI_CE_N18B0_128_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_req_data0_cclk_10_mid_ce_detail[] = {
    { "Q_VC0_CCW", AR_NIC_CE_CE_REQ_DATA0_CCLK_10_MID_CE_Q_VC0_CCW_BP, AR_NIC_CE_CE_REQ_DATA0_CCLK_10_MID_CE_Q_VC0_CCW_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_ce_req_data0_cclk_10_lo_ce_detail[] = {
    { "Q_VC1_CCW", AR_NIC_CE_CE_REQ_DATA0_CCLK_10_LO_CE_Q_VC1_CCW_BP, AR_NIC_CE_CE_REQ_DATA0_CCLK_10_LO_CE_Q_VC1_CCW_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_cfg_out_base_detail[] = {
    { "IS_ROOT", AR_NIC_CE_CFG_OUT_BASE_IS_ROOT_BP, AR_NIC_CE_CFG_OUT_BASE_IS_ROOT_MASK },
    { "PTAG", AR_NIC_CE_CFG_OUT_BASE_PTAG_BP, AR_NIC_CE_CFG_OUT_BASE_PTAG_MASK },
    { "DST", AR_NIC_CE_CFG_OUT_BASE_DST_BP, AR_NIC_CE_CFG_OUT_BASE_DST_MASK },
    { "DSTID", AR_NIC_CE_CFG_OUT_BASE_DSTID_BP, AR_NIC_CE_CFG_OUT_BASE_DSTID_MASK },
    { "NTT", AR_NIC_CE_CFG_OUT_BASE_NTT_BP, AR_NIC_CE_CFG_OUT_BASE_NTT_MASK },
    { "SSID_LCQH", AR_NIC_CE_CFG_OUT_BASE_SSID_LCQH_BP, AR_NIC_CE_CFG_OUT_BASE_SSID_LCQH_MASK },
    { "SSID_NSRC", AR_NIC_CE_CFG_OUT_BASE_SSID_NSRC_BP, AR_NIC_CE_CFG_OUT_BASE_SSID_NSRC_MASK },
    { "RC_2_0", AR_NIC_CE_CFG_OUT_BASE_RC_2_0_BP, AR_NIC_CE_CFG_OUT_BASE_RC_2_0_MASK },
    { "CE_ID", AR_NIC_CE_CFG_OUT_BASE_CE_ID_BP, AR_NIC_CE_CFG_OUT_BASE_CE_ID_MASK },
    { "CHILD_ID", AR_NIC_CE_CFG_OUT_BASE_CHILD_ID_BP, AR_NIC_CE_CFG_OUT_BASE_CHILD_ID_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_err_flg_detail[] = {
    { "REDENGN_OVRFLO", AR_NIC_CE_ERR_FLG_REDENGN_OVRFLO_BP, AR_NIC_CE_ERR_FLG_REDENGN_OVRFLO_MASK },
    { "RAT_FIFO_OVRFLO", AR_NIC_CE_ERR_FLG_RAT_FIFO_OVRFLO_BP, AR_NIC_CE_ERR_FLG_RAT_FIFO_OVRFLO_MASK },
    { "ADDRESS_ERR", AR_NIC_CE_ERR_FLG_ADDRESS_ERR_BP, AR_NIC_CE_ERR_FLG_ADDRESS_ERR_MASK },
    { "MMR_REG_SBE", AR_NIC_CE_ERR_FLG_MMR_REG_SBE_BP, AR_NIC_CE_ERR_FLG_MMR_REG_SBE_MASK },
    { "MMR_REG_MBE", AR_NIC_CE_ERR_FLG_MMR_REG_MBE_BP, AR_NIC_CE_ERR_FLG_MMR_REG_MBE_MASK },
    { "OPERATION_DISABLED", AR_NIC_CE_ERR_FLG_OPERATION_DISABLED_BP, AR_NIC_CE_ERR_FLG_OPERATION_DISABLED_MASK },
    { "HEADER_PC", AR_NIC_CE_ERR_FLG_HEADER_PC_BP, AR_NIC_CE_ERR_FLG_HEADER_PC_MASK },
    { "HEADER_LSTATUS", AR_NIC_CE_ERR_FLG_HEADER_LSTATUS_BP, AR_NIC_CE_ERR_FLG_HEADER_LSTATUS_MASK },
    { "HEADER_WITH_TAIL", AR_NIC_CE_ERR_FLG_HEADER_WITH_TAIL_BP, AR_NIC_CE_ERR_FLG_HEADER_WITH_TAIL_MASK },
    { "INV_CE_CMD", AR_NIC_CE_ERR_FLG_INV_CE_CMD_BP, AR_NIC_CE_ERR_FLG_INV_CE_CMD_MASK },
    { "INV_ALU_OP", AR_NIC_CE_ERR_FLG_INV_ALU_OP_BP, AR_NIC_CE_ERR_FLG_INV_ALU_OP_MASK },
    { "INV_CNT_BM", AR_NIC_CE_ERR_FLG_INV_CNT_BM_BP, AR_NIC_CE_ERR_FLG_INV_CNT_BM_MASK },
    { "BAD_OPERANDS", AR_NIC_CE_ERR_FLG_BAD_OPERANDS_BP, AR_NIC_CE_ERR_FLG_BAD_OPERANDS_MASK },
    { "UNEXPECTED_SCATTER", AR_NIC_CE_ERR_FLG_UNEXPECTED_SCATTER_BP, AR_NIC_CE_ERR_FLG_UNEXPECTED_SCATTER_MASK },
    { "DFLIT_SBE", AR_NIC_CE_ERR_FLG_DFLIT_SBE_BP, AR_NIC_CE_ERR_FLG_DFLIT_SBE_MASK },
    { "DFLIT_MBE", AR_NIC_CE_ERR_FLG_DFLIT_MBE_BP, AR_NIC_CE_ERR_FLG_DFLIT_MBE_MASK },
    { "PROTECTION_VIOLATION", AR_NIC_CE_ERR_FLG_PROTECTION_VIOLATION_BP, AR_NIC_CE_ERR_FLG_PROTECTION_VIOLATION_MASK },
    { "UNEXPECTED_JOIN", AR_NIC_CE_ERR_FLG_UNEXPECTED_JOIN_BP, AR_NIC_CE_ERR_FLG_UNEXPECTED_JOIN_MASK },
    { "DUPLICATE_JOIN", AR_NIC_CE_ERR_FLG_DUPLICATE_JOIN_BP, AR_NIC_CE_ERR_FLG_DUPLICATE_JOIN_MASK },
    { "FIRST_OP_NOT_MATCH", AR_NIC_CE_ERR_FLG_FIRST_OP_NOT_MATCH_BP, AR_NIC_CE_ERR_FLG_FIRST_OP_NOT_MATCH_MASK },
    { "FIRST_CNT_NOT_MATCH", AR_NIC_CE_ERR_FLG_FIRST_CNT_NOT_MATCH_BP, AR_NIC_CE_ERR_FLG_FIRST_CNT_NOT_MATCH_MASK },
    { "MISMATCH_ERR", AR_NIC_CE_ERR_FLG_MISMATCH_ERR_BP, AR_NIC_CE_ERR_FLG_MISMATCH_ERR_MASK },
    { "OP_INDX_REG_PC", AR_NIC_CE_ERR_FLG_OP_INDX_REG_PC_BP, AR_NIC_CE_ERR_FLG_OP_INDX_REG_PC_MASK },
    { "JL_REG_PC", AR_NIC_CE_ERR_FLG_JL_REG_PC_BP, AR_NIC_CE_ERR_FLG_JL_REG_PC_MASK },
    { "DIAG_ONLY", AR_NIC_CE_ERR_FLG_DIAG_ONLY_BP, AR_NIC_CE_ERR_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
#ifdef EXCEPTIONS_DEFS
static const errcat_mmrd_t _ar_nic_ce_err_flg_errcat[] = {
    { "REDENGN_OVRFLO", AR_NIC_CE_ERR_FLG_REDENGN_OVRFLO_BP, AR_NIC_CE_ERR_FLG_REDENGN_OVRFLO_EC },
    { "RAT_FIFO_OVRFLO", AR_NIC_CE_ERR_FLG_RAT_FIFO_OVRFLO_BP, AR_NIC_CE_ERR_FLG_RAT_FIFO_OVRFLO_EC },
    { "ADDRESS_ERR", AR_NIC_CE_ERR_FLG_ADDRESS_ERR_BP, AR_NIC_CE_ERR_FLG_ADDRESS_ERR_EC },
    { "MMR_REG_SBE", AR_NIC_CE_ERR_FLG_MMR_REG_SBE_BP, AR_NIC_CE_ERR_FLG_MMR_REG_SBE_EC },
    { "MMR_REG_MBE", AR_NIC_CE_ERR_FLG_MMR_REG_MBE_BP, AR_NIC_CE_ERR_FLG_MMR_REG_MBE_EC },
    { "OPERATION_DISABLED", AR_NIC_CE_ERR_FLG_OPERATION_DISABLED_BP, AR_NIC_CE_ERR_FLG_OPERATION_DISABLED_EC },
    { "HEADER_PC", AR_NIC_CE_ERR_FLG_HEADER_PC_BP, AR_NIC_CE_ERR_FLG_HEADER_PC_EC },
    { "HEADER_LSTATUS", AR_NIC_CE_ERR_FLG_HEADER_LSTATUS_BP, AR_NIC_CE_ERR_FLG_HEADER_LSTATUS_EC },
    { "HEADER_WITH_TAIL", AR_NIC_CE_ERR_FLG_HEADER_WITH_TAIL_BP, AR_NIC_CE_ERR_FLG_HEADER_WITH_TAIL_EC },
    { "INV_CE_CMD", AR_NIC_CE_ERR_FLG_INV_CE_CMD_BP, AR_NIC_CE_ERR_FLG_INV_CE_CMD_EC },
    { "INV_ALU_OP", AR_NIC_CE_ERR_FLG_INV_ALU_OP_BP, AR_NIC_CE_ERR_FLG_INV_ALU_OP_EC },
    { "INV_CNT_BM", AR_NIC_CE_ERR_FLG_INV_CNT_BM_BP, AR_NIC_CE_ERR_FLG_INV_CNT_BM_EC },
    { "BAD_OPERANDS", AR_NIC_CE_ERR_FLG_BAD_OPERANDS_BP, AR_NIC_CE_ERR_FLG_BAD_OPERANDS_EC },
    { "UNEXPECTED_SCATTER", AR_NIC_CE_ERR_FLG_UNEXPECTED_SCATTER_BP, AR_NIC_CE_ERR_FLG_UNEXPECTED_SCATTER_EC },
    { "DFLIT_SBE", AR_NIC_CE_ERR_FLG_DFLIT_SBE_BP, AR_NIC_CE_ERR_FLG_DFLIT_SBE_EC },
    { "DFLIT_MBE", AR_NIC_CE_ERR_FLG_DFLIT_MBE_BP, AR_NIC_CE_ERR_FLG_DFLIT_MBE_EC },
    { "PROTECTION_VIOLATION", AR_NIC_CE_ERR_FLG_PROTECTION_VIOLATION_BP, AR_NIC_CE_ERR_FLG_PROTECTION_VIOLATION_EC },
    { "UNEXPECTED_JOIN", AR_NIC_CE_ERR_FLG_UNEXPECTED_JOIN_BP, AR_NIC_CE_ERR_FLG_UNEXPECTED_JOIN_EC },
    { "DUPLICATE_JOIN", AR_NIC_CE_ERR_FLG_DUPLICATE_JOIN_BP, AR_NIC_CE_ERR_FLG_DUPLICATE_JOIN_EC },
    { "FIRST_OP_NOT_MATCH", AR_NIC_CE_ERR_FLG_FIRST_OP_NOT_MATCH_BP, AR_NIC_CE_ERR_FLG_FIRST_OP_NOT_MATCH_EC },
    { "FIRST_CNT_NOT_MATCH", AR_NIC_CE_ERR_FLG_FIRST_CNT_NOT_MATCH_BP, AR_NIC_CE_ERR_FLG_FIRST_CNT_NOT_MATCH_EC },
    { "MISMATCH_ERR", AR_NIC_CE_ERR_FLG_MISMATCH_ERR_BP, AR_NIC_CE_ERR_FLG_MISMATCH_ERR_EC },
    { "OP_INDX_REG_PC", AR_NIC_CE_ERR_FLG_OP_INDX_REG_PC_BP, AR_NIC_CE_ERR_FLG_OP_INDX_REG_PC_EC },
    { "JL_REG_PC", AR_NIC_CE_ERR_FLG_JL_REG_PC_BP, AR_NIC_CE_ERR_FLG_JL_REG_PC_EC },
    { "DIAG_ONLY", AR_NIC_CE_ERR_FLG_DIAG_ONLY_BP, AR_NIC_CE_ERR_FLG_DIAG_ONLY_EC },
    { NULL, 0, 0 }
};
#endif
static const generic_mmrd_t _ar_nic_ce_err_clr_detail[] = {
    { "REDENGN_OVRFLO", AR_NIC_CE_ERR_CLR_REDENGN_OVRFLO_BP, AR_NIC_CE_ERR_CLR_REDENGN_OVRFLO_MASK },
    { "RAT_FIFO_OVRFLO", AR_NIC_CE_ERR_CLR_RAT_FIFO_OVRFLO_BP, AR_NIC_CE_ERR_CLR_RAT_FIFO_OVRFLO_MASK },
    { "ADDRESS_ERR", AR_NIC_CE_ERR_CLR_ADDRESS_ERR_BP, AR_NIC_CE_ERR_CLR_ADDRESS_ERR_MASK },
    { "MMR_REG_SBE", AR_NIC_CE_ERR_CLR_MMR_REG_SBE_BP, AR_NIC_CE_ERR_CLR_MMR_REG_SBE_MASK },
    { "MMR_REG_MBE", AR_NIC_CE_ERR_CLR_MMR_REG_MBE_BP, AR_NIC_CE_ERR_CLR_MMR_REG_MBE_MASK },
    { "OPERATION_DISABLED", AR_NIC_CE_ERR_CLR_OPERATION_DISABLED_BP, AR_NIC_CE_ERR_CLR_OPERATION_DISABLED_MASK },
    { "HEADER_PC", AR_NIC_CE_ERR_CLR_HEADER_PC_BP, AR_NIC_CE_ERR_CLR_HEADER_PC_MASK },
    { "HEADER_LSTATUS", AR_NIC_CE_ERR_CLR_HEADER_LSTATUS_BP, AR_NIC_CE_ERR_CLR_HEADER_LSTATUS_MASK },
    { "HEADER_WITH_TAIL", AR_NIC_CE_ERR_CLR_HEADER_WITH_TAIL_BP, AR_NIC_CE_ERR_CLR_HEADER_WITH_TAIL_MASK },
    { "INV_CE_CMD", AR_NIC_CE_ERR_CLR_INV_CE_CMD_BP, AR_NIC_CE_ERR_CLR_INV_CE_CMD_MASK },
    { "INV_ALU_OP", AR_NIC_CE_ERR_CLR_INV_ALU_OP_BP, AR_NIC_CE_ERR_CLR_INV_ALU_OP_MASK },
    { "INV_CNT_BM", AR_NIC_CE_ERR_CLR_INV_CNT_BM_BP, AR_NIC_CE_ERR_CLR_INV_CNT_BM_MASK },
    { "BAD_OPERANDS", AR_NIC_CE_ERR_CLR_BAD_OPERANDS_BP, AR_NIC_CE_ERR_CLR_BAD_OPERANDS_MASK },
    { "UNEXPECTED_SCATTER", AR_NIC_CE_ERR_CLR_UNEXPECTED_SCATTER_BP, AR_NIC_CE_ERR_CLR_UNEXPECTED_SCATTER_MASK },
    { "DFLIT_SBE", AR_NIC_CE_ERR_CLR_DFLIT_SBE_BP, AR_NIC_CE_ERR_CLR_DFLIT_SBE_MASK },
    { "DFLIT_MBE", AR_NIC_CE_ERR_CLR_DFLIT_MBE_BP, AR_NIC_CE_ERR_CLR_DFLIT_MBE_MASK },
    { "PROTECTION_VIOLATION", AR_NIC_CE_ERR_CLR_PROTECTION_VIOLATION_BP, AR_NIC_CE_ERR_CLR_PROTECTION_VIOLATION_MASK },
    { "UNEXPECTED_JOIN", AR_NIC_CE_ERR_CLR_UNEXPECTED_JOIN_BP, AR_NIC_CE_ERR_CLR_UNEXPECTED_JOIN_MASK },
    { "DUPLICATE_JOIN", AR_NIC_CE_ERR_CLR_DUPLICATE_JOIN_BP, AR_NIC_CE_ERR_CLR_DUPLICATE_JOIN_MASK },
    { "FIRST_OP_NOT_MATCH", AR_NIC_CE_ERR_CLR_FIRST_OP_NOT_MATCH_BP, AR_NIC_CE_ERR_CLR_FIRST_OP_NOT_MATCH_MASK },
    { "FIRST_CNT_NOT_MATCH", AR_NIC_CE_ERR_CLR_FIRST_CNT_NOT_MATCH_BP, AR_NIC_CE_ERR_CLR_FIRST_CNT_NOT_MATCH_MASK },
    { "MISMATCH_ERR", AR_NIC_CE_ERR_CLR_MISMATCH_ERR_BP, AR_NIC_CE_ERR_CLR_MISMATCH_ERR_MASK },
    { "OP_INDX_REG_PC", AR_NIC_CE_ERR_CLR_OP_INDX_REG_PC_BP, AR_NIC_CE_ERR_CLR_OP_INDX_REG_PC_MASK },
    { "JL_REG_PC", AR_NIC_CE_ERR_CLR_JL_REG_PC_BP, AR_NIC_CE_ERR_CLR_JL_REG_PC_MASK },
    { "DIAG_ONLY", AR_NIC_CE_ERR_CLR_DIAG_ONLY_BP, AR_NIC_CE_ERR_CLR_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_err_hss_msk_detail[] = {
    { "REDENGN_OVRFLO", AR_NIC_CE_ERR_HSS_MSK_REDENGN_OVRFLO_BP, AR_NIC_CE_ERR_HSS_MSK_REDENGN_OVRFLO_MASK },
    { "RAT_FIFO_OVRFLO", AR_NIC_CE_ERR_HSS_MSK_RAT_FIFO_OVRFLO_BP, AR_NIC_CE_ERR_HSS_MSK_RAT_FIFO_OVRFLO_MASK },
    { "ADDRESS_ERR", AR_NIC_CE_ERR_HSS_MSK_ADDRESS_ERR_BP, AR_NIC_CE_ERR_HSS_MSK_ADDRESS_ERR_MASK },
    { "MMR_REG_SBE", AR_NIC_CE_ERR_HSS_MSK_MMR_REG_SBE_BP, AR_NIC_CE_ERR_HSS_MSK_MMR_REG_SBE_MASK },
    { "MMR_REG_MBE", AR_NIC_CE_ERR_HSS_MSK_MMR_REG_MBE_BP, AR_NIC_CE_ERR_HSS_MSK_MMR_REG_MBE_MASK },
    { "OPERATION_DISABLED", AR_NIC_CE_ERR_HSS_MSK_OPERATION_DISABLED_BP, AR_NIC_CE_ERR_HSS_MSK_OPERATION_DISABLED_MASK },
    { "HEADER_PC", AR_NIC_CE_ERR_HSS_MSK_HEADER_PC_BP, AR_NIC_CE_ERR_HSS_MSK_HEADER_PC_MASK },
    { "HEADER_LSTATUS", AR_NIC_CE_ERR_HSS_MSK_HEADER_LSTATUS_BP, AR_NIC_CE_ERR_HSS_MSK_HEADER_LSTATUS_MASK },
    { "HEADER_WITH_TAIL", AR_NIC_CE_ERR_HSS_MSK_HEADER_WITH_TAIL_BP, AR_NIC_CE_ERR_HSS_MSK_HEADER_WITH_TAIL_MASK },
    { "INV_CE_CMD", AR_NIC_CE_ERR_HSS_MSK_INV_CE_CMD_BP, AR_NIC_CE_ERR_HSS_MSK_INV_CE_CMD_MASK },
    { "INV_ALU_OP", AR_NIC_CE_ERR_HSS_MSK_INV_ALU_OP_BP, AR_NIC_CE_ERR_HSS_MSK_INV_ALU_OP_MASK },
    { "INV_CNT_BM", AR_NIC_CE_ERR_HSS_MSK_INV_CNT_BM_BP, AR_NIC_CE_ERR_HSS_MSK_INV_CNT_BM_MASK },
    { "BAD_OPERANDS", AR_NIC_CE_ERR_HSS_MSK_BAD_OPERANDS_BP, AR_NIC_CE_ERR_HSS_MSK_BAD_OPERANDS_MASK },
    { "UNEXPECTED_SCATTER", AR_NIC_CE_ERR_HSS_MSK_UNEXPECTED_SCATTER_BP, AR_NIC_CE_ERR_HSS_MSK_UNEXPECTED_SCATTER_MASK },
    { "DFLIT_SBE", AR_NIC_CE_ERR_HSS_MSK_DFLIT_SBE_BP, AR_NIC_CE_ERR_HSS_MSK_DFLIT_SBE_MASK },
    { "DFLIT_MBE", AR_NIC_CE_ERR_HSS_MSK_DFLIT_MBE_BP, AR_NIC_CE_ERR_HSS_MSK_DFLIT_MBE_MASK },
    { "PROTECTION_VIOLATION", AR_NIC_CE_ERR_HSS_MSK_PROTECTION_VIOLATION_BP, AR_NIC_CE_ERR_HSS_MSK_PROTECTION_VIOLATION_MASK },
    { "UNEXPECTED_JOIN", AR_NIC_CE_ERR_HSS_MSK_UNEXPECTED_JOIN_BP, AR_NIC_CE_ERR_HSS_MSK_UNEXPECTED_JOIN_MASK },
    { "DUPLICATE_JOIN", AR_NIC_CE_ERR_HSS_MSK_DUPLICATE_JOIN_BP, AR_NIC_CE_ERR_HSS_MSK_DUPLICATE_JOIN_MASK },
    { "FIRST_OP_NOT_MATCH", AR_NIC_CE_ERR_HSS_MSK_FIRST_OP_NOT_MATCH_BP, AR_NIC_CE_ERR_HSS_MSK_FIRST_OP_NOT_MATCH_MASK },
    { "FIRST_CNT_NOT_MATCH", AR_NIC_CE_ERR_HSS_MSK_FIRST_CNT_NOT_MATCH_BP, AR_NIC_CE_ERR_HSS_MSK_FIRST_CNT_NOT_MATCH_MASK },
    { "MISMATCH_ERR", AR_NIC_CE_ERR_HSS_MSK_MISMATCH_ERR_BP, AR_NIC_CE_ERR_HSS_MSK_MISMATCH_ERR_MASK },
    { "OP_INDX_REG_PC", AR_NIC_CE_ERR_HSS_MSK_OP_INDX_REG_PC_BP, AR_NIC_CE_ERR_HSS_MSK_OP_INDX_REG_PC_MASK },
    { "JL_REG_PC", AR_NIC_CE_ERR_HSS_MSK_JL_REG_PC_BP, AR_NIC_CE_ERR_HSS_MSK_JL_REG_PC_MASK },
    { "DIAG_ONLY", AR_NIC_CE_ERR_HSS_MSK_DIAG_ONLY_BP, AR_NIC_CE_ERR_HSS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_err_os_msk_detail[] = {
    { "REDENGN_OVRFLO", AR_NIC_CE_ERR_OS_MSK_REDENGN_OVRFLO_BP, AR_NIC_CE_ERR_OS_MSK_REDENGN_OVRFLO_MASK },
    { "RAT_FIFO_OVRFLO", AR_NIC_CE_ERR_OS_MSK_RAT_FIFO_OVRFLO_BP, AR_NIC_CE_ERR_OS_MSK_RAT_FIFO_OVRFLO_MASK },
    { "ADDRESS_ERR", AR_NIC_CE_ERR_OS_MSK_ADDRESS_ERR_BP, AR_NIC_CE_ERR_OS_MSK_ADDRESS_ERR_MASK },
    { "MMR_REG_SBE", AR_NIC_CE_ERR_OS_MSK_MMR_REG_SBE_BP, AR_NIC_CE_ERR_OS_MSK_MMR_REG_SBE_MASK },
    { "MMR_REG_MBE", AR_NIC_CE_ERR_OS_MSK_MMR_REG_MBE_BP, AR_NIC_CE_ERR_OS_MSK_MMR_REG_MBE_MASK },
    { "OPERATION_DISABLED", AR_NIC_CE_ERR_OS_MSK_OPERATION_DISABLED_BP, AR_NIC_CE_ERR_OS_MSK_OPERATION_DISABLED_MASK },
    { "HEADER_PC", AR_NIC_CE_ERR_OS_MSK_HEADER_PC_BP, AR_NIC_CE_ERR_OS_MSK_HEADER_PC_MASK },
    { "HEADER_LSTATUS", AR_NIC_CE_ERR_OS_MSK_HEADER_LSTATUS_BP, AR_NIC_CE_ERR_OS_MSK_HEADER_LSTATUS_MASK },
    { "HEADER_WITH_TAIL", AR_NIC_CE_ERR_OS_MSK_HEADER_WITH_TAIL_BP, AR_NIC_CE_ERR_OS_MSK_HEADER_WITH_TAIL_MASK },
    { "INV_CE_CMD", AR_NIC_CE_ERR_OS_MSK_INV_CE_CMD_BP, AR_NIC_CE_ERR_OS_MSK_INV_CE_CMD_MASK },
    { "INV_ALU_OP", AR_NIC_CE_ERR_OS_MSK_INV_ALU_OP_BP, AR_NIC_CE_ERR_OS_MSK_INV_ALU_OP_MASK },
    { "INV_CNT_BM", AR_NIC_CE_ERR_OS_MSK_INV_CNT_BM_BP, AR_NIC_CE_ERR_OS_MSK_INV_CNT_BM_MASK },
    { "BAD_OPERANDS", AR_NIC_CE_ERR_OS_MSK_BAD_OPERANDS_BP, AR_NIC_CE_ERR_OS_MSK_BAD_OPERANDS_MASK },
    { "UNEXPECTED_SCATTER", AR_NIC_CE_ERR_OS_MSK_UNEXPECTED_SCATTER_BP, AR_NIC_CE_ERR_OS_MSK_UNEXPECTED_SCATTER_MASK },
    { "DFLIT_SBE", AR_NIC_CE_ERR_OS_MSK_DFLIT_SBE_BP, AR_NIC_CE_ERR_OS_MSK_DFLIT_SBE_MASK },
    { "DFLIT_MBE", AR_NIC_CE_ERR_OS_MSK_DFLIT_MBE_BP, AR_NIC_CE_ERR_OS_MSK_DFLIT_MBE_MASK },
    { "PROTECTION_VIOLATION", AR_NIC_CE_ERR_OS_MSK_PROTECTION_VIOLATION_BP, AR_NIC_CE_ERR_OS_MSK_PROTECTION_VIOLATION_MASK },
    { "UNEXPECTED_JOIN", AR_NIC_CE_ERR_OS_MSK_UNEXPECTED_JOIN_BP, AR_NIC_CE_ERR_OS_MSK_UNEXPECTED_JOIN_MASK },
    { "DUPLICATE_JOIN", AR_NIC_CE_ERR_OS_MSK_DUPLICATE_JOIN_BP, AR_NIC_CE_ERR_OS_MSK_DUPLICATE_JOIN_MASK },
    { "FIRST_OP_NOT_MATCH", AR_NIC_CE_ERR_OS_MSK_FIRST_OP_NOT_MATCH_BP, AR_NIC_CE_ERR_OS_MSK_FIRST_OP_NOT_MATCH_MASK },
    { "FIRST_CNT_NOT_MATCH", AR_NIC_CE_ERR_OS_MSK_FIRST_CNT_NOT_MATCH_BP, AR_NIC_CE_ERR_OS_MSK_FIRST_CNT_NOT_MATCH_MASK },
    { "MISMATCH_ERR", AR_NIC_CE_ERR_OS_MSK_MISMATCH_ERR_BP, AR_NIC_CE_ERR_OS_MSK_MISMATCH_ERR_MASK },
    { "OP_INDX_REG_PC", AR_NIC_CE_ERR_OS_MSK_OP_INDX_REG_PC_BP, AR_NIC_CE_ERR_OS_MSK_OP_INDX_REG_PC_MASK },
    { "JL_REG_PC", AR_NIC_CE_ERR_OS_MSK_JL_REG_PC_BP, AR_NIC_CE_ERR_OS_MSK_JL_REG_PC_MASK },
    { "DIAG_ONLY", AR_NIC_CE_ERR_OS_MSK_DIAG_ONLY_BP, AR_NIC_CE_ERR_OS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_err_first_flg_detail[] = {
    { "REDENGN_OVRFLO", AR_NIC_CE_ERR_FIRST_FLG_REDENGN_OVRFLO_BP, AR_NIC_CE_ERR_FIRST_FLG_REDENGN_OVRFLO_MASK },
    { "RAT_FIFO_OVRFLO", AR_NIC_CE_ERR_FIRST_FLG_RAT_FIFO_OVRFLO_BP, AR_NIC_CE_ERR_FIRST_FLG_RAT_FIFO_OVRFLO_MASK },
    { "ADDRESS_ERR", AR_NIC_CE_ERR_FIRST_FLG_ADDRESS_ERR_BP, AR_NIC_CE_ERR_FIRST_FLG_ADDRESS_ERR_MASK },
    { "MMR_REG_SBE", AR_NIC_CE_ERR_FIRST_FLG_MMR_REG_SBE_BP, AR_NIC_CE_ERR_FIRST_FLG_MMR_REG_SBE_MASK },
    { "MMR_REG_MBE", AR_NIC_CE_ERR_FIRST_FLG_MMR_REG_MBE_BP, AR_NIC_CE_ERR_FIRST_FLG_MMR_REG_MBE_MASK },
    { "OPERATION_DISABLED", AR_NIC_CE_ERR_FIRST_FLG_OPERATION_DISABLED_BP, AR_NIC_CE_ERR_FIRST_FLG_OPERATION_DISABLED_MASK },
    { "HEADER_PC", AR_NIC_CE_ERR_FIRST_FLG_HEADER_PC_BP, AR_NIC_CE_ERR_FIRST_FLG_HEADER_PC_MASK },
    { "HEADER_LSTATUS", AR_NIC_CE_ERR_FIRST_FLG_HEADER_LSTATUS_BP, AR_NIC_CE_ERR_FIRST_FLG_HEADER_LSTATUS_MASK },
    { "HEADER_WITH_TAIL", AR_NIC_CE_ERR_FIRST_FLG_HEADER_WITH_TAIL_BP, AR_NIC_CE_ERR_FIRST_FLG_HEADER_WITH_TAIL_MASK },
    { "INV_CE_CMD", AR_NIC_CE_ERR_FIRST_FLG_INV_CE_CMD_BP, AR_NIC_CE_ERR_FIRST_FLG_INV_CE_CMD_MASK },
    { "INV_ALU_OP", AR_NIC_CE_ERR_FIRST_FLG_INV_ALU_OP_BP, AR_NIC_CE_ERR_FIRST_FLG_INV_ALU_OP_MASK },
    { "INV_CNT_BM", AR_NIC_CE_ERR_FIRST_FLG_INV_CNT_BM_BP, AR_NIC_CE_ERR_FIRST_FLG_INV_CNT_BM_MASK },
    { "BAD_OPERANDS", AR_NIC_CE_ERR_FIRST_FLG_BAD_OPERANDS_BP, AR_NIC_CE_ERR_FIRST_FLG_BAD_OPERANDS_MASK },
    { "UNEXPECTED_SCATTER", AR_NIC_CE_ERR_FIRST_FLG_UNEXPECTED_SCATTER_BP, AR_NIC_CE_ERR_FIRST_FLG_UNEXPECTED_SCATTER_MASK },
    { "DFLIT_SBE", AR_NIC_CE_ERR_FIRST_FLG_DFLIT_SBE_BP, AR_NIC_CE_ERR_FIRST_FLG_DFLIT_SBE_MASK },
    { "DFLIT_MBE", AR_NIC_CE_ERR_FIRST_FLG_DFLIT_MBE_BP, AR_NIC_CE_ERR_FIRST_FLG_DFLIT_MBE_MASK },
    { "PROTECTION_VIOLATION", AR_NIC_CE_ERR_FIRST_FLG_PROTECTION_VIOLATION_BP, AR_NIC_CE_ERR_FIRST_FLG_PROTECTION_VIOLATION_MASK },
    { "UNEXPECTED_JOIN", AR_NIC_CE_ERR_FIRST_FLG_UNEXPECTED_JOIN_BP, AR_NIC_CE_ERR_FIRST_FLG_UNEXPECTED_JOIN_MASK },
    { "DUPLICATE_JOIN", AR_NIC_CE_ERR_FIRST_FLG_DUPLICATE_JOIN_BP, AR_NIC_CE_ERR_FIRST_FLG_DUPLICATE_JOIN_MASK },
    { "FIRST_OP_NOT_MATCH", AR_NIC_CE_ERR_FIRST_FLG_FIRST_OP_NOT_MATCH_BP, AR_NIC_CE_ERR_FIRST_FLG_FIRST_OP_NOT_MATCH_MASK },
    { "FIRST_CNT_NOT_MATCH", AR_NIC_CE_ERR_FIRST_FLG_FIRST_CNT_NOT_MATCH_BP, AR_NIC_CE_ERR_FIRST_FLG_FIRST_CNT_NOT_MATCH_MASK },
    { "MISMATCH_ERR", AR_NIC_CE_ERR_FIRST_FLG_MISMATCH_ERR_BP, AR_NIC_CE_ERR_FIRST_FLG_MISMATCH_ERR_MASK },
    { "OP_INDX_REG_PC", AR_NIC_CE_ERR_FIRST_FLG_OP_INDX_REG_PC_BP, AR_NIC_CE_ERR_FIRST_FLG_OP_INDX_REG_PC_MASK },
    { "JL_REG_PC", AR_NIC_CE_ERR_FIRST_FLG_JL_REG_PC_BP, AR_NIC_CE_ERR_FIRST_FLG_JL_REG_PC_MASK },
    { "DIAG_ONLY", AR_NIC_CE_ERR_FIRST_FLG_DIAG_ONLY_BP, AR_NIC_CE_ERR_FIRST_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_err_req_info_detail[] = {
    { "MBE_SYNDROME", AR_NIC_CE_ERR_REQ_INFO_MBE_SYNDROME_BP, AR_NIC_CE_ERR_REQ_INFO_MBE_SYNDROME_MASK },
    { "MBE_SOURCE", AR_NIC_CE_ERR_REQ_INFO_MBE_SOURCE_BP, AR_NIC_CE_ERR_REQ_INFO_MBE_SOURCE_MASK },
    { "SBE_SYNDROME", AR_NIC_CE_ERR_REQ_INFO_SBE_SYNDROME_BP, AR_NIC_CE_ERR_REQ_INFO_SBE_SYNDROME_MASK },
    { "SBE_SOURCE", AR_NIC_CE_ERR_REQ_INFO_SBE_SOURCE_BP, AR_NIC_CE_ERR_REQ_INFO_SBE_SOURCE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_err_op_info_detail[] = {
    { "UNXPCT_SCAT_SOURCE", AR_NIC_CE_ERR_OP_INFO_UNXPCT_SCAT_SOURCE_BP, AR_NIC_CE_ERR_OP_INFO_UNXPCT_SCAT_SOURCE_MASK },
    { "BAD_OP_SOURCE", AR_NIC_CE_ERR_OP_INFO_BAD_OP_SOURCE_BP, AR_NIC_CE_ERR_OP_INFO_BAD_OP_SOURCE_MASK },
    { "OP_DISABLE_SOURCE", AR_NIC_CE_ERR_OP_INFO_OP_DISABLE_SOURCE_BP, AR_NIC_CE_ERR_OP_INFO_OP_DISABLE_SOURCE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_err_inv_info_detail[] = {
    { "INV_CNT_SOURCE", AR_NIC_CE_ERR_INV_INFO_INV_CNT_SOURCE_BP, AR_NIC_CE_ERR_INV_INFO_INV_CNT_SOURCE_MASK },
    { "INV_ALU_SOURCE", AR_NIC_CE_ERR_INV_INFO_INV_ALU_SOURCE_BP, AR_NIC_CE_ERR_INV_INFO_INV_ALU_SOURCE_MASK },
    { "INV_CMD_SOURCE", AR_NIC_CE_ERR_INV_INFO_INV_CMD_SOURCE_BP, AR_NIC_CE_ERR_INV_INFO_INV_CMD_SOURCE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_err_reject_info_detail[] = {
    { "BAD_PKEY_SOURCE", AR_NIC_CE_ERR_REJECT_INFO_BAD_PKEY_SOURCE_BP, AR_NIC_CE_ERR_REJECT_INFO_BAD_PKEY_SOURCE_MASK },
    { "UNEXPCT_JOIN_SOURCE", AR_NIC_CE_ERR_REJECT_INFO_UNEXPCT_JOIN_SOURCE_BP, AR_NIC_CE_ERR_REJECT_INFO_UNEXPCT_JOIN_SOURCE_MASK },
    { "DUP_JOIN_SOURCE", AR_NIC_CE_ERR_REJECT_INFO_DUP_JOIN_SOURCE_BP, AR_NIC_CE_ERR_REJECT_INFO_DUP_JOIN_SOURCE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_err_match_info_detail[] = {
    { "CMD_MIS_SOURCE", AR_NIC_CE_ERR_MATCH_INFO_CMD_MIS_SOURCE_BP, AR_NIC_CE_ERR_MATCH_INFO_CMD_MIS_SOURCE_MASK },
    { "CNT_MIS_SOURCE", AR_NIC_CE_ERR_MATCH_INFO_CNT_MIS_SOURCE_BP, AR_NIC_CE_ERR_MATCH_INFO_CNT_MIS_SOURCE_MASK },
    { "REDID_MIS_SOURCE", AR_NIC_CE_ERR_MATCH_INFO_REDID_MIS_SOURCE_BP, AR_NIC_CE_ERR_MATCH_INFO_REDID_MIS_SOURCE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_err_chk_info_detail[] = {
    { "SBE_DISCPTOR_SYNDROME", AR_NIC_CE_ERR_CHK_INFO_SBE_DISCPTOR_SYNDROME_BP, AR_NIC_CE_ERR_CHK_INFO_SBE_DISCPTOR_SYNDROME_MASK },
    { "SBE_DISCPTOR_ADDR", AR_NIC_CE_ERR_CHK_INFO_SBE_DISCPTOR_ADDR_BP, AR_NIC_CE_ERR_CHK_INFO_SBE_DISCPTOR_ADDR_MASK },
    { "MBE_DISCPTOR_SYNDROME", AR_NIC_CE_ERR_CHK_INFO_MBE_DISCPTOR_SYNDROME_BP, AR_NIC_CE_ERR_CHK_INFO_MBE_DISCPTOR_SYNDROME_MASK },
    { "MBE_DISCPTOR_ADDR", AR_NIC_CE_ERR_CHK_INFO_MBE_DISCPTOR_ADDR_BP, AR_NIC_CE_ERR_CHK_INFO_MBE_DISCPTOR_ADDR_MASK },
    { "LSTATUS_SOURCE", AR_NIC_CE_ERR_CHK_INFO_LSTATUS_SOURCE_BP, AR_NIC_CE_ERR_CHK_INFO_LSTATUS_SOURCE_MASK },
    { "HDR_WTAIL_SOURCE", AR_NIC_CE_ERR_CHK_INFO_HDR_WTAIL_SOURCE_BP, AR_NIC_CE_ERR_CHK_INFO_HDR_WTAIL_SOURCE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_err_adderr_info_detail[] = {
    { "REDENGN_OVRFLO_SOURCE", AR_NIC_CE_ERR_ADDERR_INFO_REDENGN_OVRFLO_SOURCE_BP, AR_NIC_CE_ERR_ADDERR_INFO_REDENGN_OVRFLO_SOURCE_MASK },
    { "ADDRESS_ERR_SOURCE", AR_NIC_CE_ERR_ADDERR_INFO_ADDRESS_ERR_SOURCE_BP, AR_NIC_CE_ERR_ADDERR_INFO_ADDRESS_ERR_SOURCE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_sts_chnl_0_info_detail[] = {
    { "WHOS_IN", AR_NIC_CE_STS_CHNL_0_INFO_WHOS_IN_BP, AR_NIC_CE_STS_CHNL_0_INFO_WHOS_IN_MASK },
    { "JOIN_COUNT", AR_NIC_CE_STS_CHNL_0_INFO_JOIN_COUNT_BP, AR_NIC_CE_STS_CHNL_0_INFO_JOIN_COUNT_MASK },
    { "WAIT4SCATTER", AR_NIC_CE_STS_CHNL_0_INFO_WAIT4SCATTER_BP, AR_NIC_CE_STS_CHNL_0_INFO_WAIT4SCATTER_MASK },
    { "WAIT4REDUCTION", AR_NIC_CE_STS_CHNL_0_INFO_WAIT4REDUCTION_BP, AR_NIC_CE_STS_CHNL_0_INFO_WAIT4REDUCTION_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_sts_chnl_1_info_detail[] = {
    { "WHOS_IN", AR_NIC_CE_STS_CHNL_1_INFO_WHOS_IN_BP, AR_NIC_CE_STS_CHNL_1_INFO_WHOS_IN_MASK },
    { "JOIN_COUNT", AR_NIC_CE_STS_CHNL_1_INFO_JOIN_COUNT_BP, AR_NIC_CE_STS_CHNL_1_INFO_JOIN_COUNT_MASK },
    { "WAIT4SCATTER", AR_NIC_CE_STS_CHNL_1_INFO_WAIT4SCATTER_BP, AR_NIC_CE_STS_CHNL_1_INFO_WAIT4SCATTER_MASK },
    { "WAIT4REDUCTION", AR_NIC_CE_STS_CHNL_1_INFO_WAIT4REDUCTION_BP, AR_NIC_CE_STS_CHNL_1_INFO_WAIT4REDUCTION_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_sts_chnl_2_info_detail[] = {
    { "WHOS_IN", AR_NIC_CE_STS_CHNL_2_INFO_WHOS_IN_BP, AR_NIC_CE_STS_CHNL_2_INFO_WHOS_IN_MASK },
    { "JOIN_COUNT", AR_NIC_CE_STS_CHNL_2_INFO_JOIN_COUNT_BP, AR_NIC_CE_STS_CHNL_2_INFO_JOIN_COUNT_MASK },
    { "WAIT4SCATTER", AR_NIC_CE_STS_CHNL_2_INFO_WAIT4SCATTER_BP, AR_NIC_CE_STS_CHNL_2_INFO_WAIT4SCATTER_MASK },
    { "WAIT4REDUCTION", AR_NIC_CE_STS_CHNL_2_INFO_WAIT4REDUCTION_BP, AR_NIC_CE_STS_CHNL_2_INFO_WAIT4REDUCTION_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_sts_chnl_3_info_detail[] = {
    { "WHOS_IN", AR_NIC_CE_STS_CHNL_3_INFO_WHOS_IN_BP, AR_NIC_CE_STS_CHNL_3_INFO_WHOS_IN_MASK },
    { "JOIN_COUNT", AR_NIC_CE_STS_CHNL_3_INFO_JOIN_COUNT_BP, AR_NIC_CE_STS_CHNL_3_INFO_JOIN_COUNT_MASK },
    { "WAIT4SCATTER", AR_NIC_CE_STS_CHNL_3_INFO_WAIT4SCATTER_BP, AR_NIC_CE_STS_CHNL_3_INFO_WAIT4SCATTER_MASK },
    { "WAIT4REDUCTION", AR_NIC_CE_STS_CHNL_3_INFO_WAIT4REDUCTION_BP, AR_NIC_CE_STS_CHNL_3_INFO_WAIT4REDUCTION_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_dbg_errinj_input_detail[] = {
    { "CHECKBYTEUP", AR_NIC_CE_DBG_ERRINJ_INPUT_CHECKBYTEUP_BP, AR_NIC_CE_DBG_ERRINJ_INPUT_CHECKBYTEUP_MASK },
    { "CHECKBYTELO", AR_NIC_CE_DBG_ERRINJ_INPUT_CHECKBYTELO_BP, AR_NIC_CE_DBG_ERRINJ_INPUT_CHECKBYTELO_MASK },
    { "PARITY", AR_NIC_CE_DBG_ERRINJ_INPUT_PARITY_BP, AR_NIC_CE_DBG_ERRINJ_INPUT_PARITY_MASK },
    { "TAIL", AR_NIC_CE_DBG_ERRINJ_INPUT_TAIL_BP, AR_NIC_CE_DBG_ERRINJ_INPUT_TAIL_MASK },
    { "COUNT", AR_NIC_CE_DBG_ERRINJ_INPUT_COUNT_BP, AR_NIC_CE_DBG_ERRINJ_INPUT_COUNT_MASK },
    { "TRIGGERED", AR_NIC_CE_DBG_ERRINJ_INPUT_TRIGGERED_BP, AR_NIC_CE_DBG_ERRINJ_INPUT_TRIGGERED_MASK },
    { "MODE", AR_NIC_CE_DBG_ERRINJ_INPUT_MODE_BP, AR_NIC_CE_DBG_ERRINJ_INPUT_MODE_MASK },
    { "ENABLE", AR_NIC_CE_DBG_ERRINJ_INPUT_ENABLE_BP, AR_NIC_CE_DBG_ERRINJ_INPUT_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_dbg_errinj_redengn_detail[] = {
    { "IX_CHECKBYTE", AR_NIC_CE_DBG_ERRINJ_REDENGN_IX_CHECKBYTE_BP, AR_NIC_CE_DBG_ERRINJ_REDENGN_IX_CHECKBYTE_MASK },
    { "OP_CHECKBYTE", AR_NIC_CE_DBG_ERRINJ_REDENGN_OP_CHECKBYTE_BP, AR_NIC_CE_DBG_ERRINJ_REDENGN_OP_CHECKBYTE_MASK },
    { "JL_CHECKBYTE", AR_NIC_CE_DBG_ERRINJ_REDENGN_JL_CHECKBYTE_BP, AR_NIC_CE_DBG_ERRINJ_REDENGN_JL_CHECKBYTE_MASK },
    { "REGSELECT", AR_NIC_CE_DBG_ERRINJ_REDENGN_REGSELECT_BP, AR_NIC_CE_DBG_ERRINJ_REDENGN_REGSELECT_MASK },
    { "VIRTUAL_CE_REG", AR_NIC_CE_DBG_ERRINJ_REDENGN_VIRTUAL_CE_REG_BP, AR_NIC_CE_DBG_ERRINJ_REDENGN_VIRTUAL_CE_REG_MASK },
    { "TRIGGERED", AR_NIC_CE_DBG_ERRINJ_REDENGN_TRIGGERED_BP, AR_NIC_CE_DBG_ERRINJ_REDENGN_TRIGGERED_MASK },
    { "MODE", AR_NIC_CE_DBG_ERRINJ_REDENGN_MODE_BP, AR_NIC_CE_DBG_ERRINJ_REDENGN_MODE_MASK },
    { "ENABLE", AR_NIC_CE_DBG_ERRINJ_REDENGN_ENABLE_BP, AR_NIC_CE_DBG_ERRINJ_REDENGN_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_dbg_errinj_child_cfg_detail[] = {
    { "ADDRESS", AR_NIC_CE_DBG_ERRINJ_CHILD_CFG_ADDRESS_BP, AR_NIC_CE_DBG_ERRINJ_CHILD_CFG_ADDRESS_MASK },
    { "CHECKBYTE", AR_NIC_CE_DBG_ERRINJ_CHILD_CFG_CHECKBYTE_BP, AR_NIC_CE_DBG_ERRINJ_CHILD_CFG_CHECKBYTE_MASK },
    { "REGSELECT", AR_NIC_CE_DBG_ERRINJ_CHILD_CFG_REGSELECT_BP, AR_NIC_CE_DBG_ERRINJ_CHILD_CFG_REGSELECT_MASK },
    { "TRIGGERED", AR_NIC_CE_DBG_ERRINJ_CHILD_CFG_TRIGGERED_BP, AR_NIC_CE_DBG_ERRINJ_CHILD_CFG_TRIGGERED_MASK },
    { "MODE", AR_NIC_CE_DBG_ERRINJ_CHILD_CFG_MODE_BP, AR_NIC_CE_DBG_ERRINJ_CHILD_CFG_MODE_MASK },
    { "ENABLE", AR_NIC_CE_DBG_ERRINJ_CHILD_CFG_ENABLE_BP, AR_NIC_CE_DBG_ERRINJ_CHILD_CFG_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_dbg_crdts_detail[] = {
    { "MAX_TARB_CREDITS", AR_NIC_CE_DBG_CRDTS_MAX_TARB_CREDITS_BP, AR_NIC_CE_DBG_CRDTS_MAX_TARB_CREDITS_MASK },
    { "MAX_NPT_CRDTS", AR_NIC_CE_DBG_CRDTS_MAX_NPT_CRDTS_BP, AR_NIC_CE_DBG_CRDTS_MAX_NPT_CRDTS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_ce_sts_crdts_detail[] = {
    { "TARB_FCNT", AR_NIC_CE_STS_CRDTS_TARB_FCNT_BP, AR_NIC_CE_STS_CRDTS_TARB_FCNT_MASK },
    { "NPT_FCNT", AR_NIC_CE_STS_CRDTS_NPT_FCNT_BP, AR_NIC_CE_STS_CRDTS_NPT_FCNT_MASK },
    { NULL, 0, 0 }
};

/*
 *  AR CE MMR DECLARATIONS
 */
static const generic_mmr_t _ar_nic_ce_cfg_in_base_0 = {
    "AR_NIC_CE_CFG_IN_BASE_0", AR_NIC_CE_CFG_IN_BASE + 0x0ull, 8, 1, _ar_nic_ce_cfg_in_base_detail
};
static const generic_mmr_t _ar_nic_ce_cfg_in_base_1 = {
    "AR_NIC_CE_CFG_IN_BASE_1", AR_NIC_CE_CFG_IN_BASE + 0x8ull, 8, 1, _ar_nic_ce_cfg_in_base_detail
};
static const generic_mmr_t _ar_nic_ce_cfg_in_base_2 = {
    "AR_NIC_CE_CFG_IN_BASE_2", AR_NIC_CE_CFG_IN_BASE + 0x10ull, 8, 1, _ar_nic_ce_cfg_in_base_detail
};
static const generic_mmr_t _ar_nic_ce_cfg_in_base_3 = {
    "AR_NIC_CE_CFG_IN_BASE_3", AR_NIC_CE_CFG_IN_BASE + 0x18ull, 8, 1, _ar_nic_ce_cfg_in_base_detail
};
static const generic_mmr_t _ar_nic_ce_mmr_ring_cclk_0_hi_ce = {
    "AR_NIC_CE_MMR_RING_CCLK_0_HI_CE", AR_NIC_CE_MMR_RING_CCLK_0_HI_CE, 8, 1, _ar_nic_ce_mmr_ring_cclk_0_hi_ce_detail
};
static const generic_mmr_t _ar_nic_ce_mmr_ring_cclk_0_mid_ce = {
    "AR_NIC_CE_MMR_RING_CCLK_0_MID_CE", AR_NIC_CE_MMR_RING_CCLK_0_MID_CE, 8, 1, _ar_nic_ce_mmr_ring_cclk_0_mid_ce_detail
};
static const generic_mmr_t _ar_nic_ce_mmr_ring_cclk_0_lo_ce = {
    "AR_NIC_CE_MMR_RING_CCLK_0_LO_CE", AR_NIC_CE_MMR_RING_CCLK_0_LO_CE, 8, 1, _ar_nic_ce_mmr_ring_cclk_0_lo_ce_detail
};
static const generic_mmr_t _ar_nic_ce_err_flg_1_hi_ce = {
    "AR_NIC_CE_ERR_FLG_1_HI_CE", AR_NIC_CE_ERR_FLG_1_HI_CE, 8, 1, _ar_nic_ce_err_flg_1_hi_ce_detail
};
static const generic_mmr_t _ar_nic_ce_err_flg_1_mid_ce = {
    "AR_NIC_CE_ERR_FLG_1_MID_CE", AR_NIC_CE_ERR_FLG_1_MID_CE, 8, 1, _ar_nic_ce_err_flg_1_mid_ce_detail
};
static const generic_mmr_t _ar_nic_ce_err_flg_1_lo_ce = {
    "AR_NIC_CE_ERR_FLG_1_LO_CE", AR_NIC_CE_ERR_FLG_1_LO_CE, 8, 1, _ar_nic_ce_err_flg_1_lo_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_input_data2_cclk_2_hi_ce = {
    "AR_NIC_CE_CE_INPUT_DATA2_CCLK_2_HI_CE", AR_NIC_CE_CE_INPUT_DATA2_CCLK_2_HI_CE, 8, 1, _ar_nic_ce_ce_input_data2_cclk_2_hi_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_input_data2_cclk_2_mid_ce = {
    "AR_NIC_CE_CE_INPUT_DATA2_CCLK_2_MID_CE", AR_NIC_CE_CE_INPUT_DATA2_CCLK_2_MID_CE, 8, 1, _ar_nic_ce_ce_input_data2_cclk_2_mid_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_input_data2_cclk_2_lo_ce = {
    "AR_NIC_CE_CE_INPUT_DATA2_CCLK_2_LO_CE", AR_NIC_CE_CE_INPUT_DATA2_CCLK_2_LO_CE, 8, 1, _ar_nic_ce_ce_input_data2_cclk_2_lo_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_input_data3_cclk_3_hi_ce = {
    "AR_NIC_CE_CE_INPUT_DATA3_CCLK_3_HI_CE", AR_NIC_CE_CE_INPUT_DATA3_CCLK_3_HI_CE, 8, 1, _ar_nic_ce_ce_input_data3_cclk_3_hi_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_input_data3_cclk_3_mid_ce = {
    "AR_NIC_CE_CE_INPUT_DATA3_CCLK_3_MID_CE", AR_NIC_CE_CE_INPUT_DATA3_CCLK_3_MID_CE, 8, 1, _ar_nic_ce_ce_input_data3_cclk_3_mid_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_input_data3_cclk_3_lo_ce = {
    "AR_NIC_CE_CE_INPUT_DATA3_CCLK_3_LO_CE", AR_NIC_CE_CE_INPUT_DATA3_CCLK_3_LO_CE, 8, 1, _ar_nic_ce_ce_input_data3_cclk_3_lo_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_input_data4_cclk_4_hi_ce = {
    "AR_NIC_CE_CE_INPUT_DATA4_CCLK_4_HI_CE", AR_NIC_CE_CE_INPUT_DATA4_CCLK_4_HI_CE, 8, 1, _ar_nic_ce_ce_input_data4_cclk_4_hi_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_input_data4_cclk_4_mid_ce = {
    "AR_NIC_CE_CE_INPUT_DATA4_CCLK_4_MID_CE", AR_NIC_CE_CE_INPUT_DATA4_CCLK_4_MID_CE, 8, 1, _ar_nic_ce_ce_input_data4_cclk_4_mid_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_input_data4_cclk_4_lo_ce = {
    "AR_NIC_CE_CE_INPUT_DATA4_CCLK_4_LO_CE", AR_NIC_CE_CE_INPUT_DATA4_CCLK_4_LO_CE, 8, 1, _ar_nic_ce_ce_input_data4_cclk_4_lo_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_input_data5_cclk_5_hi_ce = {
    "AR_NIC_CE_CE_INPUT_DATA5_CCLK_5_HI_CE", AR_NIC_CE_CE_INPUT_DATA5_CCLK_5_HI_CE, 8, 1, _ar_nic_ce_ce_input_data5_cclk_5_hi_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_input_data5_cclk_5_mid_ce = {
    "AR_NIC_CE_CE_INPUT_DATA5_CCLK_5_MID_CE", AR_NIC_CE_CE_INPUT_DATA5_CCLK_5_MID_CE, 8, 1, _ar_nic_ce_ce_input_data5_cclk_5_mid_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_input_data5_cclk_5_lo_ce = {
    "AR_NIC_CE_CE_INPUT_DATA5_CCLK_5_LO_CE", AR_NIC_CE_CE_INPUT_DATA5_CCLK_5_LO_CE, 8, 1, _ar_nic_ce_ce_input_data5_cclk_5_lo_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_input_data6_cclk_6_hi_ce = {
    "AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_HI_CE", AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_HI_CE, 8, 1, _ar_nic_ce_ce_input_data6_cclk_6_hi_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_input_data6_cclk_6_mid_ce = {
    "AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_MID_CE", AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_MID_CE, 8, 1, _ar_nic_ce_ce_input_data6_cclk_6_mid_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_input_data6_cclk_6_lo_ce = {
    "AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_LO_CE", AR_NIC_CE_CE_INPUT_DATA6_CCLK_6_LO_CE, 8, 1, _ar_nic_ce_ce_input_data6_cclk_6_lo_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_input_data7_cclk_7_hi_ce = {
    "AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_HI_CE", AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_HI_CE, 8, 1, _ar_nic_ce_ce_input_data7_cclk_7_hi_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_input_data7_cclk_7_mid_ce = {
    "AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_MID_CE", AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_MID_CE, 8, 1, _ar_nic_ce_ce_input_data7_cclk_7_mid_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_input_data7_cclk_7_lo_ce = {
    "AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_LO_CE", AR_NIC_CE_CE_INPUT_DATA7_CCLK_7_LO_CE, 8, 1, _ar_nic_ce_ce_input_data7_cclk_7_lo_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_redengn_data7_cclk_8_hi_ce = {
    "AR_NIC_CE_CE_REDENGN_DATA7_CCLK_8_HI_CE", AR_NIC_CE_CE_REDENGN_DATA7_CCLK_8_HI_CE, 8, 1, _ar_nic_ce_ce_redengn_data7_cclk_8_hi_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_redengn_data7_cclk_8_mid_ce = {
    "AR_NIC_CE_CE_REDENGN_DATA7_CCLK_8_MID_CE", AR_NIC_CE_CE_REDENGN_DATA7_CCLK_8_MID_CE, 8, 1, _ar_nic_ce_ce_redengn_data7_cclk_8_mid_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_redengn_data7_cclk_8_lo_ce = {
    "AR_NIC_CE_CE_REDENGN_DATA7_CCLK_8_LO_CE", AR_NIC_CE_CE_REDENGN_DATA7_CCLK_8_LO_CE, 8, 1, _ar_nic_ce_ce_redengn_data7_cclk_8_lo_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_redengn_data6_cclk_9_hi_ce = {
    "AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_HI_CE", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_HI_CE, 8, 1, _ar_nic_ce_ce_redengn_data6_cclk_9_hi_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_redengn_data6_cclk_9_mid_ce = {
    "AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_MID_CE, 8, 1, _ar_nic_ce_ce_redengn_data6_cclk_9_mid_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_redengn_data6_cclk_9_lo_ce = {
    "AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_LO_CE", AR_NIC_CE_CE_REDENGN_DATA6_CCLK_9_LO_CE, 8, 1, _ar_nic_ce_ce_redengn_data6_cclk_9_lo_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_redengn_data5_cclk_a_hi_ce = {
    "AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_HI_CE", AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_HI_CE, 8, 1, _ar_nic_ce_ce_redengn_data5_cclk_a_hi_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_redengn_data5_cclk_a_mid_ce = {
    "AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_MID_CE", AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_MID_CE, 8, 1, _ar_nic_ce_ce_redengn_data5_cclk_a_mid_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_redengn_data5_cclk_a_lo_ce = {
    "AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_LO_CE", AR_NIC_CE_CE_REDENGN_DATA5_CCLK_A_LO_CE, 8, 1, _ar_nic_ce_ce_redengn_data5_cclk_a_lo_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_redengn_data0_cclk_b_hi_ce = {
    "AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_HI_CE", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_HI_CE, 8, 1, _ar_nic_ce_ce_redengn_data0_cclk_b_hi_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_redengn_data0_cclk_b_mid_ce = {
    "AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_MID_CE, 8, 1, _ar_nic_ce_ce_redengn_data0_cclk_b_mid_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_redengn_data0_cclk_b_lo_ce = {
    "AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE", AR_NIC_CE_CE_REDENGN_DATA0_CCLK_B_LO_CE, 8, 1, _ar_nic_ce_ce_redengn_data0_cclk_b_lo_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_req_data19_cclk_c_hi_ce = {
    "AR_NIC_CE_CE_REQ_DATA19_CCLK_C_HI_CE", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_HI_CE, 8, 1, _ar_nic_ce_ce_req_data19_cclk_c_hi_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_req_data19_cclk_c_mid_ce = {
    "AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_MID_CE, 8, 1, _ar_nic_ce_ce_req_data19_cclk_c_mid_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_req_data19_cclk_c_lo_ce = {
    "AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE", AR_NIC_CE_CE_REQ_DATA19_CCLK_C_LO_CE, 8, 1, _ar_nic_ce_ce_req_data19_cclk_c_lo_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_req_data18_cclk_d_hi_ce = {
    "AR_NIC_CE_CE_REQ_DATA18_CCLK_D_HI_CE", AR_NIC_CE_CE_REQ_DATA18_CCLK_D_HI_CE, 8, 1, _ar_nic_ce_ce_req_data18_cclk_d_hi_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_req_data18_cclk_d_mid_ce = {
    "AR_NIC_CE_CE_REQ_DATA18_CCLK_D_MID_CE", AR_NIC_CE_CE_REQ_DATA18_CCLK_D_MID_CE, 8, 1, _ar_nic_ce_ce_req_data18_cclk_d_mid_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_req_data18_cclk_d_lo_ce = {
    "AR_NIC_CE_CE_REQ_DATA18_CCLK_D_LO_CE", AR_NIC_CE_CE_REQ_DATA18_CCLK_D_LO_CE, 8, 1, _ar_nic_ce_ce_req_data18_cclk_d_lo_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_req_data17_cclk_e_hi_ce = {
    "AR_NIC_CE_CE_REQ_DATA17_CCLK_E_HI_CE", AR_NIC_CE_CE_REQ_DATA17_CCLK_E_HI_CE, 8, 1, _ar_nic_ce_ce_req_data17_cclk_e_hi_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_req_data17_cclk_e_mid_ce = {
    "AR_NIC_CE_CE_REQ_DATA17_CCLK_E_MID_CE", AR_NIC_CE_CE_REQ_DATA17_CCLK_E_MID_CE, 8, 1, _ar_nic_ce_ce_req_data17_cclk_e_mid_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_req_data17_cclk_e_lo_ce = {
    "AR_NIC_CE_CE_REQ_DATA17_CCLK_E_LO_CE", AR_NIC_CE_CE_REQ_DATA17_CCLK_E_LO_CE, 8, 1, _ar_nic_ce_ce_req_data17_cclk_e_lo_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_req_data2_cclk_f_hi_ce = {
    "AR_NIC_CE_CE_REQ_DATA2_CCLK_F_HI_CE", AR_NIC_CE_CE_REQ_DATA2_CCLK_F_HI_CE, 8, 1, _ar_nic_ce_ce_req_data2_cclk_f_hi_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_req_data2_cclk_f_mid_ce = {
    "AR_NIC_CE_CE_REQ_DATA2_CCLK_F_MID_CE", AR_NIC_CE_CE_REQ_DATA2_CCLK_F_MID_CE, 8, 1, _ar_nic_ce_ce_req_data2_cclk_f_mid_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_req_data2_cclk_f_lo_ce = {
    "AR_NIC_CE_CE_REQ_DATA2_CCLK_F_LO_CE", AR_NIC_CE_CE_REQ_DATA2_CCLK_F_LO_CE, 8, 1, _ar_nic_ce_ce_req_data2_cclk_f_lo_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_req_data0_cclk_10_hi_ce = {
    "AR_NIC_CE_CE_REQ_DATA0_CCLK_10_HI_CE", AR_NIC_CE_CE_REQ_DATA0_CCLK_10_HI_CE, 8, 1, _ar_nic_ce_ce_req_data0_cclk_10_hi_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_req_data0_cclk_10_mid_ce = {
    "AR_NIC_CE_CE_REQ_DATA0_CCLK_10_MID_CE", AR_NIC_CE_CE_REQ_DATA0_CCLK_10_MID_CE, 8, 1, _ar_nic_ce_ce_req_data0_cclk_10_mid_ce_detail
};
static const generic_mmr_t _ar_nic_ce_ce_req_data0_cclk_10_lo_ce = {
    "AR_NIC_CE_CE_REQ_DATA0_CCLK_10_LO_CE", AR_NIC_CE_CE_REQ_DATA0_CCLK_10_LO_CE, 8, 1, _ar_nic_ce_ce_req_data0_cclk_10_lo_ce_detail
};
static const generic_mmr_t _ar_nic_ce_cfg_out_base_0 = {
    "AR_NIC_CE_CFG_OUT_BASE_0", AR_NIC_CE_CFG_OUT_BASE + 0x0ull, 8, 1, _ar_nic_ce_cfg_out_base_detail
};
static const generic_mmr_t _ar_nic_ce_cfg_out_base_1 = {
    "AR_NIC_CE_CFG_OUT_BASE_1", AR_NIC_CE_CFG_OUT_BASE + 0x8ull, 8, 1, _ar_nic_ce_cfg_out_base_detail
};
static const generic_mmr_t _ar_nic_ce_cfg_out_base_2 = {
    "AR_NIC_CE_CFG_OUT_BASE_2", AR_NIC_CE_CFG_OUT_BASE + 0x10ull, 8, 1, _ar_nic_ce_cfg_out_base_detail
};
static const generic_mmr_t _ar_nic_ce_cfg_out_base_3 = {
    "AR_NIC_CE_CFG_OUT_BASE_3", AR_NIC_CE_CFG_OUT_BASE + 0x18ull, 8, 1, _ar_nic_ce_cfg_out_base_detail
};
static const generic_mmr_t _ar_nic_ce_err_flg = {
    "AR_NIC_CE_ERR_FLG", AR_NIC_CE_ERR_FLG, 8, 1, _ar_nic_ce_err_flg_detail
};
static const generic_mmr_t _ar_nic_ce_err_clr = {
    "AR_NIC_CE_ERR_CLR", AR_NIC_CE_ERR_CLR, 8, 1, _ar_nic_ce_err_clr_detail
};
static const generic_mmr_t _ar_nic_ce_err_hss_msk = {
    "AR_NIC_CE_ERR_HSS_MSK", AR_NIC_CE_ERR_HSS_MSK, 8, 1, _ar_nic_ce_err_hss_msk_detail
};
static const generic_mmr_t _ar_nic_ce_err_os_msk = {
    "AR_NIC_CE_ERR_OS_MSK", AR_NIC_CE_ERR_OS_MSK, 8, 1, _ar_nic_ce_err_os_msk_detail
};
static const generic_mmr_t _ar_nic_ce_err_first_flg = {
    "AR_NIC_CE_ERR_FIRST_FLG", AR_NIC_CE_ERR_FIRST_FLG, 8, 1, _ar_nic_ce_err_first_flg_detail
};
static const generic_mmr_t _ar_nic_ce_err_req_info = {
    "AR_NIC_CE_ERR_REQ_INFO", AR_NIC_CE_ERR_REQ_INFO, 8, 1, _ar_nic_ce_err_req_info_detail
};
static const generic_mmr_t _ar_nic_ce_err_op_info = {
    "AR_NIC_CE_ERR_OP_INFO", AR_NIC_CE_ERR_OP_INFO, 8, 1, _ar_nic_ce_err_op_info_detail
};
static const generic_mmr_t _ar_nic_ce_err_inv_info = {
    "AR_NIC_CE_ERR_INV_INFO", AR_NIC_CE_ERR_INV_INFO, 8, 1, _ar_nic_ce_err_inv_info_detail
};
static const generic_mmr_t _ar_nic_ce_err_reject_info = {
    "AR_NIC_CE_ERR_REJECT_INFO", AR_NIC_CE_ERR_REJECT_INFO, 8, 1, _ar_nic_ce_err_reject_info_detail
};
static const generic_mmr_t _ar_nic_ce_err_match_info = {
    "AR_NIC_CE_ERR_MATCH_INFO", AR_NIC_CE_ERR_MATCH_INFO, 8, 1, _ar_nic_ce_err_match_info_detail
};
static const generic_mmr_t _ar_nic_ce_err_chk_info = {
    "AR_NIC_CE_ERR_CHK_INFO", AR_NIC_CE_ERR_CHK_INFO, 8, 1, _ar_nic_ce_err_chk_info_detail
};
static const generic_mmr_t _ar_nic_ce_err_adderr_info = {
    "AR_NIC_CE_ERR_ADDERR_INFO", AR_NIC_CE_ERR_ADDERR_INFO, 8, 1, _ar_nic_ce_err_adderr_info_detail
};
static const generic_mmr_t _ar_nic_ce_sts_chnl_0_info = {
    "AR_NIC_CE_STS_CHNL_0_INFO", AR_NIC_CE_STS_CHNL_0_INFO, 8, 1, _ar_nic_ce_sts_chnl_0_info_detail
};
static const generic_mmr_t _ar_nic_ce_sts_chnl_1_info = {
    "AR_NIC_CE_STS_CHNL_1_INFO", AR_NIC_CE_STS_CHNL_1_INFO, 8, 1, _ar_nic_ce_sts_chnl_1_info_detail
};
static const generic_mmr_t _ar_nic_ce_sts_chnl_2_info = {
    "AR_NIC_CE_STS_CHNL_2_INFO", AR_NIC_CE_STS_CHNL_2_INFO, 8, 1, _ar_nic_ce_sts_chnl_2_info_detail
};
static const generic_mmr_t _ar_nic_ce_sts_chnl_3_info = {
    "AR_NIC_CE_STS_CHNL_3_INFO", AR_NIC_CE_STS_CHNL_3_INFO, 8, 1, _ar_nic_ce_sts_chnl_3_info_detail
};
static const generic_mmr_t _ar_nic_ce_dbg_errinj_input = {
    "AR_NIC_CE_DBG_ERRINJ_INPUT", AR_NIC_CE_DBG_ERRINJ_INPUT, 8, 1, _ar_nic_ce_dbg_errinj_input_detail
};
static const generic_mmr_t _ar_nic_ce_dbg_errinj_redengn = {
    "AR_NIC_CE_DBG_ERRINJ_REDENGN", AR_NIC_CE_DBG_ERRINJ_REDENGN, 8, 1, _ar_nic_ce_dbg_errinj_redengn_detail
};
static const generic_mmr_t _ar_nic_ce_dbg_errinj_child_cfg = {
    "AR_NIC_CE_DBG_ERRINJ_CHILD_CFG", AR_NIC_CE_DBG_ERRINJ_CHILD_CFG, 8, 1, _ar_nic_ce_dbg_errinj_child_cfg_detail
};
static const generic_mmr_t _ar_nic_ce_dbg_crdts = {
    "AR_NIC_CE_DBG_CRDTS", AR_NIC_CE_DBG_CRDTS, 8, 1, _ar_nic_ce_dbg_crdts_detail
};
static const generic_mmr_t _ar_nic_ce_sts_crdts = {
    "AR_NIC_CE_STS_CRDTS", AR_NIC_CE_STS_CRDTS, 8, 1, _ar_nic_ce_sts_crdts_detail
};

/*
 *  INSTALL AR CE MMRS
 */
static const generic_mmr_t* _ar_ce_mmrs[] _unused = {
    &_ar_nic_ce_cfg_in_base_0,
    &_ar_nic_ce_cfg_in_base_1,
    &_ar_nic_ce_cfg_in_base_2,
    &_ar_nic_ce_cfg_in_base_3,
    &_ar_nic_ce_mmr_ring_cclk_0_hi_ce,
    &_ar_nic_ce_mmr_ring_cclk_0_mid_ce,
    &_ar_nic_ce_mmr_ring_cclk_0_lo_ce,
    &_ar_nic_ce_err_flg_1_hi_ce,
    &_ar_nic_ce_err_flg_1_mid_ce,
    &_ar_nic_ce_err_flg_1_lo_ce,
    &_ar_nic_ce_ce_input_data2_cclk_2_hi_ce,
    &_ar_nic_ce_ce_input_data2_cclk_2_mid_ce,
    &_ar_nic_ce_ce_input_data2_cclk_2_lo_ce,
    &_ar_nic_ce_ce_input_data3_cclk_3_hi_ce,
    &_ar_nic_ce_ce_input_data3_cclk_3_mid_ce,
    &_ar_nic_ce_ce_input_data3_cclk_3_lo_ce,
    &_ar_nic_ce_ce_input_data4_cclk_4_hi_ce,
    &_ar_nic_ce_ce_input_data4_cclk_4_mid_ce,
    &_ar_nic_ce_ce_input_data4_cclk_4_lo_ce,
    &_ar_nic_ce_ce_input_data5_cclk_5_hi_ce,
    &_ar_nic_ce_ce_input_data5_cclk_5_mid_ce,
    &_ar_nic_ce_ce_input_data5_cclk_5_lo_ce,
    &_ar_nic_ce_ce_input_data6_cclk_6_hi_ce,
    &_ar_nic_ce_ce_input_data6_cclk_6_mid_ce,
    &_ar_nic_ce_ce_input_data6_cclk_6_lo_ce,
    &_ar_nic_ce_ce_input_data7_cclk_7_hi_ce,
    &_ar_nic_ce_ce_input_data7_cclk_7_mid_ce,
    &_ar_nic_ce_ce_input_data7_cclk_7_lo_ce,
    &_ar_nic_ce_ce_redengn_data7_cclk_8_hi_ce,
    &_ar_nic_ce_ce_redengn_data7_cclk_8_mid_ce,
    &_ar_nic_ce_ce_redengn_data7_cclk_8_lo_ce,
    &_ar_nic_ce_ce_redengn_data6_cclk_9_hi_ce,
    &_ar_nic_ce_ce_redengn_data6_cclk_9_mid_ce,
    &_ar_nic_ce_ce_redengn_data6_cclk_9_lo_ce,
    &_ar_nic_ce_ce_redengn_data5_cclk_a_hi_ce,
    &_ar_nic_ce_ce_redengn_data5_cclk_a_mid_ce,
    &_ar_nic_ce_ce_redengn_data5_cclk_a_lo_ce,
    &_ar_nic_ce_ce_redengn_data0_cclk_b_hi_ce,
    &_ar_nic_ce_ce_redengn_data0_cclk_b_mid_ce,
    &_ar_nic_ce_ce_redengn_data0_cclk_b_lo_ce,
    &_ar_nic_ce_ce_req_data19_cclk_c_hi_ce,
    &_ar_nic_ce_ce_req_data19_cclk_c_mid_ce,
    &_ar_nic_ce_ce_req_data19_cclk_c_lo_ce,
    &_ar_nic_ce_ce_req_data18_cclk_d_hi_ce,
    &_ar_nic_ce_ce_req_data18_cclk_d_mid_ce,
    &_ar_nic_ce_ce_req_data18_cclk_d_lo_ce,
    &_ar_nic_ce_ce_req_data17_cclk_e_hi_ce,
    &_ar_nic_ce_ce_req_data17_cclk_e_mid_ce,
    &_ar_nic_ce_ce_req_data17_cclk_e_lo_ce,
    &_ar_nic_ce_ce_req_data2_cclk_f_hi_ce,
    &_ar_nic_ce_ce_req_data2_cclk_f_mid_ce,
    &_ar_nic_ce_ce_req_data2_cclk_f_lo_ce,
    &_ar_nic_ce_ce_req_data0_cclk_10_hi_ce,
    &_ar_nic_ce_ce_req_data0_cclk_10_mid_ce,
    &_ar_nic_ce_ce_req_data0_cclk_10_lo_ce,
    &_ar_nic_ce_cfg_out_base_0,
    &_ar_nic_ce_cfg_out_base_1,
    &_ar_nic_ce_cfg_out_base_2,
    &_ar_nic_ce_cfg_out_base_3,
    &_ar_nic_ce_err_flg,
    &_ar_nic_ce_err_clr,
    &_ar_nic_ce_err_hss_msk,
    &_ar_nic_ce_err_os_msk,
    &_ar_nic_ce_err_first_flg,
    &_ar_nic_ce_err_req_info,
    &_ar_nic_ce_err_op_info,
    &_ar_nic_ce_err_inv_info,
    &_ar_nic_ce_err_reject_info,
    &_ar_nic_ce_err_match_info,
    &_ar_nic_ce_err_chk_info,
    &_ar_nic_ce_err_adderr_info,
    &_ar_nic_ce_sts_chnl_0_info,
    &_ar_nic_ce_sts_chnl_1_info,
    &_ar_nic_ce_sts_chnl_2_info,
    &_ar_nic_ce_sts_chnl_3_info,
    &_ar_nic_ce_dbg_errinj_input,
    &_ar_nic_ce_dbg_errinj_redengn,
    &_ar_nic_ce_dbg_errinj_child_cfg,
    &_ar_nic_ce_dbg_crdts,
    &_ar_nic_ce_sts_crdts,
    NULL
};

#endif
