/******************************************************************************
 * COPYRIGHT CRAY INC. ar_nl_enum_h.h
 * FILE: ar_nl_enum_h.h
 * Created by v2h.c on Wed Oct  8 14:39:01 2014
 ******************************************************************************/

#ifndef _AR_NL_ENUM_H_H_
#define _AR_NL_ENUM_H_H_

#define AR_NL_PRF_PTILE_0_REQ_TO_NIC_0                              	0x0ull
#define AR_NL_PRF_PTILE_0_REQ_TO_NIC_1                              	0x1ull
#define AR_NL_PRF_PTILE_0_REQ_TO_NIC_0_STALLED                      	0x2ull
#define AR_NL_PRF_PTILE_0_REQ_TO_NIC_1_STALLED                      	0x3ull
#define AR_NL_PRF_PTILE_0_REQ_IN_NW_FLITS                           	0x4ull
#define AR_NL_PRF_PTILE_0_REQ_IN_NW_PKTS                            	0x5ull
#define AR_NL_PRF_PTILE_1_REQ_TO_NIC_0                              	0x6ull
#define AR_NL_PRF_PTILE_1_REQ_TO_NIC_1                              	0x7ull
#define AR_NL_PRF_PTILE_1_REQ_TO_NIC_0_STALLED                      	0x8ull
#define AR_NL_PRF_PTILE_1_REQ_TO_NIC_1_STALLED                      	0x9ull
#define AR_NL_PRF_PTILE_1_REQ_IN_NW_FLITS                           	0xaull
#define AR_NL_PRF_PTILE_1_REQ_IN_NW_PKTS                            	0xbull
#define AR_NL_PRF_PTILE_2_REQ_TO_NIC_0                              	0xcull
#define AR_NL_PRF_PTILE_2_REQ_TO_NIC_1                              	0xdull
#define AR_NL_PRF_PTILE_2_REQ_TO_NIC_0_STALLED                      	0xeull
#define AR_NL_PRF_PTILE_2_REQ_TO_NIC_1_STALLED                      	0xfull
#define AR_NL_PRF_PTILE_2_REQ_IN_NW_FLITS                           	0x10ull
#define AR_NL_PRF_PTILE_2_REQ_IN_NW_PKTS                            	0x11ull
#define AR_NL_PRF_PTILE_3_REQ_TO_NIC_0                              	0x12ull
#define AR_NL_PRF_PTILE_3_REQ_TO_NIC_1                              	0x13ull
#define AR_NL_PRF_PTILE_3_REQ_TO_NIC_0_STALLED                      	0x14ull
#define AR_NL_PRF_PTILE_3_REQ_TO_NIC_1_STALLED                      	0x15ull
#define AR_NL_PRF_PTILE_3_REQ_IN_NW_FLITS                           	0x16ull
#define AR_NL_PRF_PTILE_3_REQ_IN_NW_PKTS                            	0x17ull
#define AR_NL_PRF_PTILE_4_REQ_TO_NIC_2                              	0x18ull
#define AR_NL_PRF_PTILE_4_REQ_TO_NIC_3                              	0x19ull
#define AR_NL_PRF_PTILE_4_REQ_TO_NIC_2_STALLED                      	0x1aull
#define AR_NL_PRF_PTILE_4_REQ_TO_NIC_3_STALLED                      	0x1bull
#define AR_NL_PRF_PTILE_4_REQ_IN_NW_FLITS                           	0x1cull
#define AR_NL_PRF_PTILE_4_REQ_IN_NW_PKTS                            	0x1dull
#define AR_NL_PRF_PTILE_5_REQ_TO_NIC_2                              	0x1eull
#define AR_NL_PRF_PTILE_5_REQ_TO_NIC_3                              	0x1full
#define AR_NL_PRF_PTILE_5_REQ_TO_NIC_2_STALLED                      	0x20ull
#define AR_NL_PRF_PTILE_5_REQ_TO_NIC_3_STALLED                      	0x21ull
#define AR_NL_PRF_PTILE_5_REQ_IN_NW_FLITS                           	0x22ull
#define AR_NL_PRF_PTILE_5_REQ_IN_NW_PKTS                            	0x23ull
#define AR_NL_PRF_PTILE_6_REQ_TO_NIC_2                              	0x24ull
#define AR_NL_PRF_PTILE_6_REQ_TO_NIC_3                              	0x25ull
#define AR_NL_PRF_PTILE_6_REQ_TO_NIC_2_STALLED                      	0x26ull
#define AR_NL_PRF_PTILE_6_REQ_TO_NIC_3_STALLED                      	0x27ull
#define AR_NL_PRF_PTILE_6_REQ_IN_NW_FLITS                           	0x28ull
#define AR_NL_PRF_PTILE_6_REQ_IN_NW_PKTS                            	0x29ull
#define AR_NL_PRF_PTILE_7_REQ_TO_NIC_2                              	0x2aull
#define AR_NL_PRF_PTILE_7_REQ_TO_NIC_3                              	0x2bull
#define AR_NL_PRF_PTILE_7_REQ_TO_NIC_2_STALLED                      	0x2cull
#define AR_NL_PRF_PTILE_7_REQ_TO_NIC_3_STALLED                      	0x2dull
#define AR_NL_PRF_PTILE_7_REQ_IN_NW_FLITS                           	0x2eull
#define AR_NL_PRF_PTILE_7_REQ_IN_NW_PKTS                            	0x2full
#define AR_NL_PRF_PTILE_0_RSP_TO_NIC_0                              	0x30ull
#define AR_NL_PRF_PTILE_0_RSP_TO_NIC_1                              	0x31ull
#define AR_NL_PRF_PTILE_0_RSP_TO_NIC_0_STALLED                      	0x32ull
#define AR_NL_PRF_PTILE_0_RSP_TO_NIC_1_STALLED                      	0x33ull
#define AR_NL_PRF_PTILE_0_RSP_IN_NW_FLITS                           	0x34ull
#define AR_NL_PRF_PTILE_0_RSP_IN_NW_PKTS                            	0x35ull
#define AR_NL_PRF_PTILE_1_RSP_TO_NIC_0                              	0x36ull
#define AR_NL_PRF_PTILE_1_RSP_TO_NIC_1                              	0x37ull
#define AR_NL_PRF_PTILE_1_RSP_TO_NIC_0_STALLED                      	0x38ull
#define AR_NL_PRF_PTILE_1_RSP_TO_NIC_1_STALLED                      	0x39ull
#define AR_NL_PRF_PTILE_1_RSP_IN_NW_FLITS                           	0x3aull
#define AR_NL_PRF_PTILE_1_RSP_IN_NW_PKTS                            	0x3bull
#define AR_NL_PRF_PTILE_2_RSP_TO_NIC_0                              	0x3cull
#define AR_NL_PRF_PTILE_2_RSP_TO_NIC_1                              	0x3dull
#define AR_NL_PRF_PTILE_2_RSP_TO_NIC_0_STALLED                      	0x3eull
#define AR_NL_PRF_PTILE_2_RSP_TO_NIC_1_STALLED                      	0x3full
#define AR_NL_PRF_PTILE_2_RSP_IN_NW_FLITS                           	0x40ull
#define AR_NL_PRF_PTILE_2_RSP_IN_NW_PKTS                            	0x41ull
#define AR_NL_PRF_PTILE_3_RSP_TO_NIC_0                              	0x42ull
#define AR_NL_PRF_PTILE_3_RSP_TO_NIC_1                              	0x43ull
#define AR_NL_PRF_PTILE_3_RSP_TO_NIC_0_STALLED                      	0x44ull
#define AR_NL_PRF_PTILE_3_RSP_TO_NIC_1_STALLED                      	0x45ull
#define AR_NL_PRF_PTILE_3_RSP_IN_NW_FLITS                           	0x46ull
#define AR_NL_PRF_PTILE_3_RSP_IN_NW_PKTS                            	0x47ull
#define AR_NL_PRF_PTILE_4_RSP_TO_NIC_2                              	0x48ull
#define AR_NL_PRF_PTILE_4_RSP_TO_NIC_3                              	0x49ull
#define AR_NL_PRF_PTILE_4_RSP_TO_NIC_2_STALLED                      	0x4aull
#define AR_NL_PRF_PTILE_4_RSP_TO_NIC_3_STALLED                      	0x4bull
#define AR_NL_PRF_PTILE_4_RSP_IN_NW_FLITS                           	0x4cull
#define AR_NL_PRF_PTILE_4_RSP_IN_NW_PKTS                            	0x4dull
#define AR_NL_PRF_PTILE_5_RSP_TO_NIC_2                              	0x4eull
#define AR_NL_PRF_PTILE_5_RSP_TO_NIC_3                              	0x4full
#define AR_NL_PRF_PTILE_5_RSP_TO_NIC_2_STALLED                      	0x50ull
#define AR_NL_PRF_PTILE_5_RSP_TO_NIC_3_STALLED                      	0x51ull
#define AR_NL_PRF_PTILE_5_RSP_IN_NW_FLITS                           	0x52ull
#define AR_NL_PRF_PTILE_5_RSP_IN_NW_PKTS                            	0x53ull
#define AR_NL_PRF_PTILE_6_RSP_TO_NIC_2                              	0x54ull
#define AR_NL_PRF_PTILE_6_RSP_TO_NIC_3                              	0x55ull
#define AR_NL_PRF_PTILE_6_RSP_TO_NIC_2_STALLED                      	0x56ull
#define AR_NL_PRF_PTILE_6_RSP_TO_NIC_3_STALLED                      	0x57ull
#define AR_NL_PRF_PTILE_6_RSP_IN_NW_FLITS                           	0x58ull
#define AR_NL_PRF_PTILE_6_RSP_IN_NW_PKTS                            	0x59ull
#define AR_NL_PRF_PTILE_7_RSP_TO_NIC_2                              	0x5aull
#define AR_NL_PRF_PTILE_7_RSP_TO_NIC_3                              	0x5bull
#define AR_NL_PRF_PTILE_7_RSP_TO_NIC_2_STALLED                      	0x5cull
#define AR_NL_PRF_PTILE_7_RSP_TO_NIC_3_STALLED                      	0x5dull
#define AR_NL_PRF_PTILE_7_RSP_IN_NW_FLITS                           	0x5eull
#define AR_NL_PRF_PTILE_7_RSP_IN_NW_PKTS                            	0x5full
#define AR_NL_PRF_REQ_PTILES_TO_NIC_0_FLITS                         	0x60ull
#define AR_NL_PRF_REQ_PTILES_TO_NIC_0_PKTS                          	0x61ull
#define AR_NL_PRF_REQ_PTILES_TO_NIC_0_STALLED                       	0x62ull
#define AR_NL_PRF_REQ_PTILES_TO_NIC_1_FLITS                         	0x63ull
#define AR_NL_PRF_REQ_PTILES_TO_NIC_1_PKTS                          	0x64ull
#define AR_NL_PRF_REQ_PTILES_TO_NIC_1_STALLED                       	0x65ull
#define AR_NL_PRF_REQ_PTILES_TO_NIC_2_FLITS                         	0x66ull
#define AR_NL_PRF_REQ_PTILES_TO_NIC_2_PKTS                          	0x67ull
#define AR_NL_PRF_REQ_PTILES_TO_NIC_2_STALLED                       	0x68ull
#define AR_NL_PRF_REQ_PTILES_TO_NIC_3_FLITS                         	0x69ull
#define AR_NL_PRF_REQ_PTILES_TO_NIC_3_PKTS                          	0x6aull
#define AR_NL_PRF_REQ_PTILES_TO_NIC_3_STALLED                       	0x6bull
#define AR_NL_PRF_RSP_PTILES_TO_NIC_0_FLITS                         	0x6cull
#define AR_NL_PRF_RSP_PTILES_TO_NIC_0_PKTS                          	0x6dull
#define AR_NL_PRF_RSP_PTILES_TO_NIC_0_STALLED                       	0x6eull
#define AR_NL_PRF_RSP_PTILES_TO_NIC_1_FLITS                         	0x6full
#define AR_NL_PRF_RSP_PTILES_TO_NIC_1_PKTS                          	0x70ull
#define AR_NL_PRF_RSP_PTILES_TO_NIC_1_STALLED                       	0x71ull
#define AR_NL_PRF_RSP_PTILES_TO_NIC_2_FLITS                         	0x72ull
#define AR_NL_PRF_RSP_PTILES_TO_NIC_2_PKTS                          	0x73ull
#define AR_NL_PRF_RSP_PTILES_TO_NIC_2_STALLED                       	0x74ull
#define AR_NL_PRF_RSP_PTILES_TO_NIC_3_FLITS                         	0x75ull
#define AR_NL_PRF_RSP_PTILES_TO_NIC_3_PKTS                          	0x76ull
#define AR_NL_PRF_RSP_PTILES_TO_NIC_3_STALLED                       	0x77ull
#define AR_NL_PRF_SCRATCH_0_RANGE                                   	0x7full
#define AR_NL_PRF_NIC_0_REQ_TO_PTILE_0                              	0x80ull
#define AR_NL_PRF_NIC_1_REQ_TO_PTILE_0                              	0x81ull
#define AR_NL_PRF_NIC_0_REQ_TO_PTILE_0_STALLED                      	0x82ull
#define AR_NL_PRF_NIC_1_REQ_TO_PTILE_0_STALLED                      	0x83ull
#define AR_NL_PRF_PTILE_0_REQ_OUT_NW_FLITS                          	0x84ull
#define AR_NL_PRF_PTILE_0_REQ_OUT_NW_PKTS                           	0x85ull
#define AR_NL_PRF_NIC_0_REQ_TO_PTILE_1                              	0x86ull
#define AR_NL_PRF_NIC_1_REQ_TO_PTILE_1                              	0x87ull
#define AR_NL_PRF_NIC_0_REQ_TO_PTILE_1_STALLED                      	0x88ull
#define AR_NL_PRF_NIC_1_REQ_TO_PTILE_1_STALLED                      	0x89ull
#define AR_NL_PRF_PTILE_1_REQ_OUT_NW_FLITS                          	0x8aull
#define AR_NL_PRF_PTILE_1_REQ_OUT_NW_PKTS                           	0x8bull
#define AR_NL_PRF_NIC_0_REQ_TO_PTILE_2                              	0x8cull
#define AR_NL_PRF_NIC_1_REQ_TO_PTILE_2                              	0x8dull
#define AR_NL_PRF_NIC_0_REQ_TO_PTILE_2_STALLED                      	0x8eull
#define AR_NL_PRF_NIC_1_REQ_TO_PTILE_2_STALLED                      	0x8full
#define AR_NL_PRF_PTILE_2_REQ_OUT_NW_FLITS                          	0x90ull
#define AR_NL_PRF_PTILE_2_REQ_OUT_NW_PKTS                           	0x91ull
#define AR_NL_PRF_NIC_0_REQ_TO_PTILE_3                              	0x92ull
#define AR_NL_PRF_NIC_1_REQ_TO_PTILE_3                              	0x93ull
#define AR_NL_PRF_NIC_0_REQ_TO_PTILE_3_STALLED                      	0x94ull
#define AR_NL_PRF_NIC_1_REQ_TO_PTILE_3_STALLED                      	0x95ull
#define AR_NL_PRF_PTILE_3_REQ_OUT_NW_FLITS                          	0x96ull
#define AR_NL_PRF_PTILE_3_REQ_OUT_NW_PKTS                           	0x97ull
#define AR_NL_PRF_NIC_2_REQ_TO_PTILE_4                              	0x98ull
#define AR_NL_PRF_NIC_3_REQ_TO_PTILE_4                              	0x99ull
#define AR_NL_PRF_NIC_2_REQ_TO_PTILE_4_STALLED                      	0x9aull
#define AR_NL_PRF_NIC_3_REQ_TO_PTILE_4_STALLED                      	0x9bull
#define AR_NL_PRF_PTILE_4_REQ_OUT_NW_FLITS                          	0x9cull
#define AR_NL_PRF_PTILE_4_REQ_OUT_NW_PKTS                           	0x9dull
#define AR_NL_PRF_NIC_2_REQ_TO_PTILE_5                              	0x9eull
#define AR_NL_PRF_NIC_3_REQ_TO_PTILE_5                              	0x9full
#define AR_NL_PRF_NIC_2_REQ_TO_PTILE_5_STALLED                      	0xa0ull
#define AR_NL_PRF_NIC_3_REQ_TO_PTILE_5_STALLED                      	0xa1ull
#define AR_NL_PRF_PTILE_5_REQ_OUT_NW_PKTS                           	0xa2ull
#define AR_NL_PRF_PTILE_5_REQ_OUT_NW_FLITS                          	0xa3ull
#define AR_NL_PRF_NIC_2_REQ_TO_PTILE_6                              	0xa4ull
#define AR_NL_PRF_NIC_3_REQ_TO_PTILE_6                              	0xa5ull
#define AR_NL_PRF_NIC_2_REQ_TO_PTILE_6_STALLED                      	0xa6ull
#define AR_NL_PRF_NIC_3_REQ_TO_PTILE_6_STALLED                      	0xa7ull
#define AR_NL_PRF_PTILE_6_REQ_OUT_NW_FLITS                          	0xa8ull
#define AR_NL_PRF_PTILE_6_REQ_OUT_NW_PKTS                           	0xa9ull
#define AR_NL_PRF_NIC_2_REQ_TO_PTILE_7                              	0xaaull
#define AR_NL_PRF_NIC_3_REQ_TO_PTILE_7                              	0xabull
#define AR_NL_PRF_NIC_2_REQ_TO_PTILE_7_STALLED                      	0xacull
#define AR_NL_PRF_NIC_3_REQ_TO_PTILE_7_STALLED                      	0xadull
#define AR_NL_PRF_PTILE_7_REQ_OUT_NW_FLITS                          	0xaeull
#define AR_NL_PRF_PTILE_7_REQ_OUT_NW_PKTS                           	0xafull
#define AR_NL_PRF_NIC_0_RSP_TO_PTILE_0                              	0xb0ull
#define AR_NL_PRF_NIC_1_RSP_TO_PTILE_0                              	0xb1ull
#define AR_NL_PRF_NIC_0_RSP_TO_PTILE_0_STALLED                      	0xb2ull
#define AR_NL_PRF_NIC_1_RSP_TO_PTILE_0_STALLED                      	0xb3ull
#define AR_NL_PRF_PTILE_0_RSP_OUT_NW_FLITS                          	0xb4ull
#define AR_NL_PRF_PTILE_0_RSP_OUT_NW_PKTS                           	0xb5ull
#define AR_NL_PRF_NIC_0_RSP_TO_PTILE_1                              	0xb6ull
#define AR_NL_PRF_NIC_1_RSP_TO_PTILE_1                              	0xb7ull
#define AR_NL_PRF_NIC_0_RSP_TO_PTILE_1_STALLED                      	0xb8ull
#define AR_NL_PRF_NIC_1_RSP_TO_PTILE_1_STALLED                      	0xb9ull
#define AR_NL_PRF_PTILE_1_RSP_OUT_NW_FLITS                          	0xbaull
#define AR_NL_PRF_PTILE_1_RSP_OUT_NW_PKTS                           	0xbbull
#define AR_NL_PRF_NIC_0_RSP_TO_PTILE_2                              	0xbcull
#define AR_NL_PRF_NIC_1_RSP_TO_PTILE_2                              	0xbdull
#define AR_NL_PRF_NIC_0_RSP_TO_PTILE_2_STALLED                      	0xbeull
#define AR_NL_PRF_NIC_1_RSP_TO_PTILE_2_STALLED                      	0xbfull
#define AR_NL_PRF_PTILE_2_RSP_OUT_NW_FLITS                          	0xc0ull
#define AR_NL_PRF_PTILE_2_RSP_OUT_NW_PKTS                           	0xc1ull
#define AR_NL_PRF_NIC_0_RSP_TO_PTILE_3                              	0xc2ull
#define AR_NL_PRF_NIC_1_RSP_TO_PTILE_3                              	0xc3ull
#define AR_NL_PRF_NIC_0_RSP_TO_PTILE_3_STALLED                      	0xc4ull
#define AR_NL_PRF_NIC_1_RSP_TO_PTILE_3_STALLED                      	0xc5ull
#define AR_NL_PRF_PTILE_3_RSP_OUT_NW_FLITS                          	0xc6ull
#define AR_NL_PRF_PTILE_3_RSP_OUT_NW_PKTS                           	0xc7ull
#define AR_NL_PRF_NIC_2_RSP_TO_PTILE_4                              	0xc8ull
#define AR_NL_PRF_NIC_3_RSP_TO_PTILE_4                              	0xc9ull
#define AR_NL_PRF_NIC_2_RSP_TO_PTILE_4_STALLED                      	0xcaull
#define AR_NL_PRF_NIC_3_RSP_TO_PTILE_4_STALLED                      	0xcbull
#define AR_NL_PRF_PTILE_4_RSP_OUT_NW_FLITS                          	0xccull
#define AR_NL_PRF_PTILE_4_RSP_OUT_NW_PKTS                           	0xcdull
#define AR_NL_PRF_NIC_2_RSP_TO_PTILE_5                              	0xceull
#define AR_NL_PRF_NIC_3_RSP_TO_PTILE_5                              	0xcfull
#define AR_NL_PRF_NIC_2_RSP_TO_PTILE_5_STALLED                      	0xd0ull
#define AR_NL_PRF_NIC_3_RSP_TO_PTILE_5_STALLED                      	0xd1ull
#define AR_NL_PRF_PTILE_5_RSP_OUT_NW_FLITS                          	0xd2ull
#define AR_NL_PRF_PTILE_5_RSP_OUT_NW_PKTS                           	0xd3ull
#define AR_NL_PRF_NIC_2_RSP_TO_PTILE_6                              	0xd4ull
#define AR_NL_PRF_NIC_3_RSP_TO_PTILE_6                              	0xd5ull
#define AR_NL_PRF_NIC_2_RSP_TO_PTILE_6_STALLED                      	0xd6ull
#define AR_NL_PRF_NIC_3_RSP_TO_PTILE_6_STALLED                      	0xd7ull
#define AR_NL_PRF_PTILE_6_RSP_OUT_NW_FLITS                          	0xd8ull
#define AR_NL_PRF_PTILE_6_RSP_OUT_NW_PKTS                           	0xd9ull
#define AR_NL_PRF_NIC_2_RSP_TO_PTILE_7                              	0xdaull
#define AR_NL_PRF_NIC_3_RSP_TO_PTILE_7                              	0xdbull
#define AR_NL_PRF_NIC_2_RSP_TO_PTILE_7_STALLED                      	0xdcull
#define AR_NL_PRF_NIC_3_RSP_TO_PTILE_7_STALLED                      	0xddull
#define AR_NL_PRF_PTILE_7_RSP_OUT_NW_FLITS                          	0xdeull
#define AR_NL_PRF_PTILE_7_RSP_OUT_NW_PKTS                           	0xdfull
#define AR_NL_PRF_REQ_NIC_0_TO_PTILES_FLITS                         	0xe0ull
#define AR_NL_PRF_REQ_NIC_0_TO_PTILES_PKTS                          	0xe1ull
#define AR_NL_PRF_REQ_NIC_0_TO_PTILES_STALLED                       	0xe2ull
#define AR_NL_PRF_REQ_NIC_1_TO_PTILES_FLITS                         	0xe3ull
#define AR_NL_PRF_REQ_NIC_1_TO_PTILES_PKTS                          	0xe4ull
#define AR_NL_PRF_REQ_NIC_1_TO_PTILES_STALLED                       	0xe5ull
#define AR_NL_PRF_REQ_NIC_2_TO_PTILES_FLITS                         	0xe6ull
#define AR_NL_PRF_REQ_NIC_2_TO_PTILES_PKTS                          	0xe7ull
#define AR_NL_PRF_REQ_NIC_2_TO_PTILES_STALLED                       	0xe8ull
#define AR_NL_PRF_REQ_NIC_3_TO_PTILES_FLITS                         	0xe9ull
#define AR_NL_PRF_REQ_NIC_3_TO_PTILES_PKTS                          	0xeaull
#define AR_NL_PRF_REQ_NIC_3_TO_PTILES_STALLED                       	0xebull
#define AR_NL_PRF_RSP_NIC_0_TO_PTILES_FLITS                         	0xecull
#define AR_NL_PRF_RSP_NIC_0_TO_PTILES_PKTS                          	0xedull
#define AR_NL_PRF_RSP_NIC_0_TO_PTILES_STALLED                       	0xeeull
#define AR_NL_PRF_RSP_NIC_1_TO_PTILES_FLITS                         	0xefull
#define AR_NL_PRF_RSP_NIC_1_TO_PTILES_PKTS                          	0xf0ull
#define AR_NL_PRF_RSP_NIC_1_TO_PTILES_STALLED                       	0xf1ull
#define AR_NL_PRF_RSP_NIC_2_TO_PTILES_FLITS                         	0xf2ull
#define AR_NL_PRF_RSP_NIC_2_TO_PTILES_PKTS                          	0xf3ull
#define AR_NL_PRF_RSP_NIC_2_TO_PTILES_STALLED                       	0xf4ull
#define AR_NL_PRF_RSP_NIC_3_TO_PTILES_FLITS                         	0xf5ull
#define AR_NL_PRF_RSP_NIC_3_TO_PTILES_PKTS                          	0xf6ull
#define AR_NL_PRF_RSP_NIC_3_TO_PTILES_STALLED                       	0xf7ull
#define AR_NL_PRF_SCRATCH_1_RANGE                                   	0xffull

#endif
