/******************************************************************************
 * COPYRIGHT CRAY INC. ar_npt_mmrs_h.h
 * FILE: ar_npt_mmrs_h.h
 * Created by v2h.c on Wed Oct  8 14:39:01 2014
 ******************************************************************************/

#ifndef _AR_NPT_MMRS_H_H_
#define _AR_NPT_MMRS_H_H_

#ifdef __GNUC__
#define _unused __attribute__((unused))
#else
#define _unused
#endif

#ifndef _GENERIC_MMRD_T_
#define _GENERIC_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint64_t _mask;		/* Field bit mask */
} generic_mmrd_t;
#endif

#ifndef _ERRCAT_MMRD_T_
#define _ERRCAT_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint32_t _ec;		/* Field error category */
} errcat_mmrd_t;
#endif

#ifndef _GENERIC_MMR_T_
#define _GENERIC_MMR_T_
typedef struct {
	char* _name;		/* MMR name */
	uint64_t _addr;		/* MMR address */
	int _size;		/* Size in bytes of MMR */
	int _depth;		/* Number of MMR instances */
	const generic_mmrd_t *_info;	/* MMR detail */
} generic_mmr_t;
#endif

static const generic_mmr_t* _ar_npt_mmrs[] _unused;	/* NPT Array */

/*
 *  AR NPT MMR DETAIL DECLARATIONS
 */
static const generic_mmrd_t _ar_nic_npt_cfg_params_detail[] = {
    { "ALL_INTEGRITY_ERRS", AR_NIC_NPT_CFG_PARAMS_ALL_INTEGRITY_ERRS_BP, AR_NIC_NPT_CFG_PARAMS_ALL_INTEGRITY_ERRS_MASK },
    { "SF_CE", AR_NIC_NPT_CFG_PARAMS_SF_CE_BP, AR_NIC_NPT_CFG_PARAMS_SF_CE_MASK },
    { "SF_P", AR_NIC_NPT_CFG_PARAMS_SF_P_BP, AR_NIC_NPT_CFG_PARAMS_SF_P_MASK },
    { "SF_RMT", AR_NIC_NPT_CFG_PARAMS_SF_RMT_BP, AR_NIC_NPT_CFG_PARAMS_SF_RMT_MASK },
    { "SF_CQ", AR_NIC_NPT_CFG_PARAMS_SF_CQ_BP, AR_NIC_NPT_CFG_PARAMS_SF_CQ_MASK },
    { "TIMEOUT_ENABLE", AR_NIC_NPT_CFG_PARAMS_TIMEOUT_ENABLE_BP, AR_NIC_NPT_CFG_PARAMS_TIMEOUT_ENABLE_MASK },
    { "ENTRY_TIMEOUT_PERIOD", AR_NIC_NPT_CFG_PARAMS_ENTRY_TIMEOUT_PERIOD_BP, AR_NIC_NPT_CFG_PARAMS_ENTRY_TIMEOUT_PERIOD_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_npt_mmr_ring_0_hi_npt_detail[] = {
    { "UNUSED_145_75", AR_NIC_NPT_NPT_MMR_RING_0_HI_NPT_UNUSED_145_75_BP, AR_NIC_NPT_NPT_MMR_RING_0_HI_NPT_UNUSED_145_75_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_npt_mmr_ring_0_mid_npt_detail[] = {
    { "UNUSED_127_112", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_UNUSED_127_112_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_UNUSED_127_112_MASK },
    { "CNTR_RSP_MBE", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_RSP_MBE_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_RSP_MBE_MASK },
    { "CNTR_RSP_SBE", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_RSP_SBE_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_RSP_SBE_MASK },
    { "CNTR_RSP_PE", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_RSP_PE_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_RSP_PE_MASK },
    { "CNTR_REQ_PE", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_REQ_PE_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_REQ_PE_MASK },
    { "CNTR_ERR_MBE", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_ERR_MBE_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_ERR_MBE_MASK },
    { "CNTR_ERR_SBE", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_ERR_SBE_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_ERR_SBE_MASK },
    { "CNTR_PKT_CW", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_PKT_CW_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_PKT_CW_MASK },
    { "CNTR_PKT_DROP", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_PKT_DROP_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_PKT_DROP_MASK },
    { "CNTR_PKT_IGNORE", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_PKT_IGNORE_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_PKT_IGNORE_MASK },
    { "CNTR_RSP_FLIT", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_RSP_FLIT_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_RSP_FLIT_MASK },
    { "CNTR_RSP_PKT", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_RSP_PKT_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_RSP_PKT_MASK },
    { "CNTR_NL_STALLED", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_NL_STALLED_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_NL_STALLED_MASK },
    { "CNTR_NL_FLITS", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_NL_FLITS_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_NL_FLITS_MASK },
    { "CNTR_NL_PKTS", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_NL_PKTS_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_NL_PKTS_MASK },
    { "CNTR_CE_BLOCKED", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_CE_BLOCKED_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_CE_BLOCKED_MASK },
    { "CNTR_CE_PKTS", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_CE_PKTS_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_CE_PKTS_MASK },
    { "CNTR_P_BLOCKED", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_P_BLOCKED_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_P_BLOCKED_MASK },
    { "CNTR_P_PKTS", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_P_PKTS_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_P_PKTS_MASK },
    { "CNTR_NP_BLOCKED", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_NP_BLOCKED_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_NP_BLOCKED_MASK },
    { "CNTR_NP_FLITS", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_NP_FLITS_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_NP_FLITS_MASK },
    { "CNTR_NP_PKTS", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_NP_PKTS_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_NP_PKTS_MASK },
    { "CNTR_INPUT_STALLED", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_INPUT_STALLED_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_INPUT_STALLED_MASK },
    { "CNTR_INPUT_FLITS", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_INPUT_FLITS_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_INPUT_FLITS_MASK },
    { "CNTR_INPUT_PKTS", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_INPUT_PKTS_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_INPUT_PKTS_MASK },
    { "CNTR_RMT_BLOCKED", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_RMT_BLOCKED_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_RMT_BLOCKED_MASK },
    { "CNTR_RMT_FLITS", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_RMT_FLITS_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_RMT_FLITS_MASK },
    { "CNTR_RMT_PKTS", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_RMT_PKTS_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_RMT_PKTS_MASK },
    { "CNTR_CQ_BLOCKED", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_CQ_BLOCKED_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_CQ_BLOCKED_MASK },
    { "CNTR_CQ_FLITS", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_CQ_FLITS_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_CQ_FLITS_MASK },
    { "CNTR_CQ_PKTS", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_CQ_PKTS_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_CNTR_CQ_PKTS_MASK },
    { "UNUSED_81_75", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_UNUSED_81_75_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_UNUSED_81_75_MASK },
    { "DBG_CQ_RMT_RDY", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_DBG_CQ_RMT_RDY_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_DBG_CQ_RMT_RDY_MASK },
    { "DBG_REQPKT", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_DBG_REQPKT_BP, AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT_DBG_REQPKT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_npt_mmr_ring_0_lo_npt_detail[] = {
    { "DBG_REQPKT", AR_NIC_NPT_NPT_MMR_RING_0_LO_NPT_DBG_REQPKT_BP, AR_NIC_NPT_NPT_MMR_RING_0_LO_NPT_DBG_REQPKT_MASK },
    { "R_Q_NPT_PI_OS_IRQ", AR_NIC_NPT_NPT_MMR_RING_0_LO_NPT_R_Q_NPT_PI_OS_IRQ_BP, AR_NIC_NPT_NPT_MMR_RING_0_LO_NPT_R_Q_NPT_PI_OS_IRQ_MASK },
    { "R_Q_NPT_LB_HSS_IRQ", AR_NIC_NPT_NPT_MMR_RING_0_LO_NPT_R_Q_NPT_LB_HSS_IRQ_BP, AR_NIC_NPT_NPT_MMR_RING_0_LO_NPT_R_Q_NPT_LB_HSS_IRQ_MASK },
    { "R_Q_NPT_RSPMON_RING_WRACK", AR_NIC_NPT_NPT_MMR_RING_0_LO_NPT_R_Q_NPT_RSPMON_RING_WRACK_BP, AR_NIC_NPT_NPT_MMR_RING_0_LO_NPT_R_Q_NPT_RSPMON_RING_WRACK_MASK },
    { "R_Q_NPT_RSPMON_RING_15_0", AR_NIC_NPT_NPT_MMR_RING_0_LO_NPT_R_Q_NPT_RSPMON_RING_15_0_BP, AR_NIC_NPT_NPT_MMR_RING_0_LO_NPT_R_Q_NPT_RSPMON_RING_15_0_MASK },
    { "I_RSPMON_NPT_RING_15_0", AR_NIC_NPT_NPT_MMR_RING_0_LO_NPT_I_RSPMON_NPT_RING_15_0_BP, AR_NIC_NPT_NPT_MMR_RING_0_LO_NPT_I_RSPMON_NPT_RING_15_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_err_flg_1_hi_npt_detail[] = {
    { "UNUSED_145_128", AR_NIC_NPT_ERR_FLG_1_HI_NPT_UNUSED_145_128_BP, AR_NIC_NPT_ERR_FLG_1_HI_NPT_UNUSED_145_128_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_err_flg_1_mid_npt_detail[] = {
    { "UNUSED_127_88", AR_NIC_NPT_ERR_FLG_1_MID_NPT_UNUSED_127_88_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_UNUSED_127_88_MASK },
    { "NL_CRDT_UNFLW", AR_NIC_NPT_ERR_FLG_1_MID_NPT_NL_CRDT_UNFLW_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_NL_CRDT_UNFLW_MASK },
    { "CW_DROP", AR_NIC_NPT_ERR_FLG_1_MID_NPT_CW_DROP_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_CW_DROP_MASK },
    { "RSP_FLIT_MBE", AR_NIC_NPT_ERR_FLG_1_MID_NPT_RSP_FLIT_MBE_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_RSP_FLIT_MBE_MASK },
    { "RSP_FLIT_SBE", AR_NIC_NPT_ERR_FLG_1_MID_NPT_RSP_FLIT_SBE_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_RSP_FLIT_SBE_MASK },
    { "RSP_FLIT_PE", AR_NIC_NPT_ERR_FLG_1_MID_NPT_RSP_FLIT_PE_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_RSP_FLIT_PE_MASK },
    { "REQ_FLIT_PE", AR_NIC_NPT_ERR_FLG_1_MID_NPT_REQ_FLIT_PE_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_REQ_FLIT_PE_MASK },
    { "CMD_MISMATCH", AR_NIC_NPT_ERR_FLG_1_MID_NPT_CMD_MISMATCH_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_CMD_MISMATCH_MASK },
    { "UNSOLICITED_RSP", AR_NIC_NPT_ERR_FLG_1_MID_NPT_UNSOLICITED_RSP_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_UNSOLICITED_RSP_MASK },
    { "TIMEOUT", AR_NIC_NPT_ERR_FLG_1_MID_NPT_TIMEOUT_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_TIMEOUT_MASK },
    { "NPT_RAM_SBE", AR_NIC_NPT_ERR_FLG_1_MID_NPT_NPT_RAM_SBE_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_NPT_RAM_SBE_MASK },
    { "NPT_RAM_MBE", AR_NIC_NPT_ERR_FLG_1_MID_NPT_NPT_RAM_MBE_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_NPT_RAM_MBE_MASK },
    { "CE_UFLW", AR_NIC_NPT_ERR_FLG_1_MID_NPT_CE_UFLW_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_CE_UFLW_MASK },
    { "P_UFLW", AR_NIC_NPT_ERR_FLG_1_MID_NPT_P_UFLW_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_P_UFLW_MASK },
    { "NP_PAYLD_UFLW", AR_NIC_NPT_ERR_FLG_1_MID_NPT_NP_PAYLD_UFLW_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_NP_PAYLD_UFLW_MASK },
    { "NP_HDR_UFLW", AR_NIC_NPT_ERR_FLG_1_MID_NPT_NP_HDR_UFLW_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_NP_HDR_UFLW_MASK },
    { "RMT_UFLW", AR_NIC_NPT_ERR_FLG_1_MID_NPT_RMT_UFLW_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_RMT_UFLW_MASK },
    { "CQ_UFLW", AR_NIC_NPT_ERR_FLG_1_MID_NPT_CQ_UFLW_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_CQ_UFLW_MASK },
    { "CE_OFLW", AR_NIC_NPT_ERR_FLG_1_MID_NPT_CE_OFLW_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_CE_OFLW_MASK },
    { "P_OFLW", AR_NIC_NPT_ERR_FLG_1_MID_NPT_P_OFLW_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_P_OFLW_MASK },
    { "NP_PAYLD_OFLW", AR_NIC_NPT_ERR_FLG_1_MID_NPT_NP_PAYLD_OFLW_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_NP_PAYLD_OFLW_MASK },
    { "NP_HDR_OFLW", AR_NIC_NPT_ERR_FLG_1_MID_NPT_NP_HDR_OFLW_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_NP_HDR_OFLW_MASK },
    { "RMT_OFLW", AR_NIC_NPT_ERR_FLG_1_MID_NPT_RMT_OFLW_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_RMT_OFLW_MASK },
    { "CQ_OFLW", AR_NIC_NPT_ERR_FLG_1_MID_NPT_CQ_OFLW_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_CQ_OFLW_MASK },
    { "DIAG_ONLY", AR_NIC_NPT_ERR_FLG_1_MID_NPT_DIAG_ONLY_BP, AR_NIC_NPT_ERR_FLG_1_MID_NPT_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_err_flg_1_lo_npt_detail[] = {
    { "UNUSED_63_24", AR_NIC_NPT_ERR_FLG_1_LO_NPT_UNUSED_63_24_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_UNUSED_63_24_MASK },
    { "I_NL_CRDT_UNFLW", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_NL_CRDT_UNFLW_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_NL_CRDT_UNFLW_MASK },
    { "I_CW_DROP", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_CW_DROP_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_CW_DROP_MASK },
    { "I_RSP_FLIT_MBE", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_RSP_FLIT_MBE_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_RSP_FLIT_MBE_MASK },
    { "I_RSP_FLIT_SBE", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_RSP_FLIT_SBE_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_RSP_FLIT_SBE_MASK },
    { "I_RSP_FLIT_PE", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_RSP_FLIT_PE_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_RSP_FLIT_PE_MASK },
    { "I_REQ_FLIT_PE", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_REQ_FLIT_PE_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_REQ_FLIT_PE_MASK },
    { "I_CMD_MISMATCH", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_CMD_MISMATCH_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_CMD_MISMATCH_MASK },
    { "I_UNSOLICITED_RSP", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_UNSOLICITED_RSP_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_UNSOLICITED_RSP_MASK },
    { "I_TIMEOUT", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_TIMEOUT_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_TIMEOUT_MASK },
    { "I_NPT_RAM_SBE", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_NPT_RAM_SBE_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_NPT_RAM_SBE_MASK },
    { "I_NPT_RAM_MBE", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_NPT_RAM_MBE_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_NPT_RAM_MBE_MASK },
    { "I_CE_UFLW", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_CE_UFLW_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_CE_UFLW_MASK },
    { "I_P_UFLW", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_P_UFLW_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_P_UFLW_MASK },
    { "I_NP_PAYLD_UFLW", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_NP_PAYLD_UFLW_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_NP_PAYLD_UFLW_MASK },
    { "I_NP_HDR_UFLW", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_NP_HDR_UFLW_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_NP_HDR_UFLW_MASK },
    { "I_RMT_UFLW", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_RMT_UFLW_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_RMT_UFLW_MASK },
    { "I_CQ_UFLW", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_CQ_UFLW_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_CQ_UFLW_MASK },
    { "I_CE_OFLW", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_CE_OFLW_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_CE_OFLW_MASK },
    { "I_P_OFLW", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_P_OFLW_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_P_OFLW_MASK },
    { "I_NP_PAYLD_OFLW", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_NP_PAYLD_OFLW_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_NP_PAYLD_OFLW_MASK },
    { "I_NP_HDR_OFLW", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_NP_HDR_OFLW_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_NP_HDR_OFLW_MASK },
    { "I_RMT_OFLW", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_RMT_OFLW_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_RMT_OFLW_MASK },
    { "I_CQ_OFLW", AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_CQ_OFLW_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_I_CQ_OFLW_MASK },
    { "UNUSED_0", AR_NIC_NPT_ERR_FLG_1_LO_NPT_UNUSED_0_BP, AR_NIC_NPT_ERR_FLG_1_LO_NPT_UNUSED_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_amo_npt_rsp_flit_2_hi_npt_detail[] = {
    { "I_AMO_NPT_RSP_SB", AR_NIC_NPT_AMO_NPT_RSP_FLIT_2_HI_NPT_I_AMO_NPT_RSP_SB_BP, AR_NIC_NPT_AMO_NPT_RSP_FLIT_2_HI_NPT_I_AMO_NPT_RSP_SB_MASK },
    { "I_AMO_NPT_RSP_FLIT", AR_NIC_NPT_AMO_NPT_RSP_FLIT_2_HI_NPT_I_AMO_NPT_RSP_FLIT_BP, AR_NIC_NPT_AMO_NPT_RSP_FLIT_2_HI_NPT_I_AMO_NPT_RSP_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_amo_npt_rsp_flit_2_mid_npt_detail[] = {
    { "I_AMO_NPT_RSP_FLIT", AR_NIC_NPT_AMO_NPT_RSP_FLIT_2_MID_NPT_I_AMO_NPT_RSP_FLIT_BP, AR_NIC_NPT_AMO_NPT_RSP_FLIT_2_MID_NPT_I_AMO_NPT_RSP_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_amo_npt_rsp_flit_2_lo_npt_detail[] = {
    { "I_AMO_NPT_RSP_FLIT", AR_NIC_NPT_AMO_NPT_RSP_FLIT_2_LO_NPT_I_AMO_NPT_RSP_FLIT_BP, AR_NIC_NPT_AMO_NPT_RSP_FLIT_2_LO_NPT_I_AMO_NPT_RSP_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_nic_nl_rsp_flit_3_hi_npt_detail[] = {
    { "R_Q_NIC_NL_RSP_SB", AR_NIC_NPT_NIC_NL_RSP_FLIT_3_HI_NPT_R_Q_NIC_NL_RSP_SB_BP, AR_NIC_NPT_NIC_NL_RSP_FLIT_3_HI_NPT_R_Q_NIC_NL_RSP_SB_MASK },
    { "R_Q_NIC_NL_RSP_FLIT", AR_NIC_NPT_NIC_NL_RSP_FLIT_3_HI_NPT_R_Q_NIC_NL_RSP_FLIT_BP, AR_NIC_NPT_NIC_NL_RSP_FLIT_3_HI_NPT_R_Q_NIC_NL_RSP_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_nic_nl_rsp_flit_3_mid_npt_detail[] = {
    { "R_Q_NIC_NL_RSP_FLIT", AR_NIC_NPT_NIC_NL_RSP_FLIT_3_MID_NPT_R_Q_NIC_NL_RSP_FLIT_BP, AR_NIC_NPT_NIC_NL_RSP_FLIT_3_MID_NPT_R_Q_NIC_NL_RSP_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_nic_nl_rsp_flit_3_lo_npt_detail[] = {
    { "R_Q_NIC_NL_RSP_FLIT", AR_NIC_NPT_NIC_NL_RSP_FLIT_3_LO_NPT_R_Q_NIC_NL_RSP_FLIT_BP, AR_NIC_NPT_NIC_NL_RSP_FLIT_3_LO_NPT_R_Q_NIC_NL_RSP_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_npt_amo_req_flit_4_hi_npt_detail[] = {
    { "R_Q_NPT_AMO_REQ_SB", AR_NIC_NPT_NPT_AMO_REQ_FLIT_4_HI_NPT_R_Q_NPT_AMO_REQ_SB_BP, AR_NIC_NPT_NPT_AMO_REQ_FLIT_4_HI_NPT_R_Q_NPT_AMO_REQ_SB_MASK },
    { "R_Q_NPT_AMO_REQ_FLIT", AR_NIC_NPT_NPT_AMO_REQ_FLIT_4_HI_NPT_R_Q_NPT_AMO_REQ_FLIT_BP, AR_NIC_NPT_NPT_AMO_REQ_FLIT_4_HI_NPT_R_Q_NPT_AMO_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_npt_amo_req_flit_4_mid_npt_detail[] = {
    { "R_Q_NPT_AMO_REQ_FLIT", AR_NIC_NPT_NPT_AMO_REQ_FLIT_4_MID_NPT_R_Q_NPT_AMO_REQ_FLIT_BP, AR_NIC_NPT_NPT_AMO_REQ_FLIT_4_MID_NPT_R_Q_NPT_AMO_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_npt_amo_req_flit_4_lo_npt_detail[] = {
    { "R_Q_NPT_AMO_REQ_FLIT", AR_NIC_NPT_NPT_AMO_REQ_FLIT_4_LO_NPT_R_Q_NPT_AMO_REQ_FLIT_BP, AR_NIC_NPT_NPT_AMO_REQ_FLIT_4_LO_NPT_R_Q_NPT_AMO_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_npt_free_vld_vecs_5_hi_npt_detail[] = {
    { "UNUSED_145_128", AR_NIC_NPT_NPT_FREE_VLD_VECS_5_HI_NPT_UNUSED_145_128_BP, AR_NIC_NPT_NPT_FREE_VLD_VECS_5_HI_NPT_UNUSED_145_128_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_npt_free_vld_vecs_5_mid_npt_detail[] = {
    { "FREE_VEC", AR_NIC_NPT_NPT_FREE_VLD_VECS_5_MID_NPT_FREE_VEC_BP, AR_NIC_NPT_NPT_FREE_VLD_VECS_5_MID_NPT_FREE_VEC_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_npt_free_vld_vecs_5_lo_npt_detail[] = {
    { "VLD_VEC", AR_NIC_NPT_NPT_FREE_VLD_VECS_5_LO_NPT_VLD_VEC_BP, AR_NIC_NPT_NPT_FREE_VLD_VECS_5_LO_NPT_VLD_VEC_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_npt_power_down_ff_hi_npt_detail[] = {
    { "POWER_DOWN", AR_NIC_NPT_NPT_POWER_DOWN_FF_HI_NPT_POWER_DOWN_BP, AR_NIC_NPT_NPT_POWER_DOWN_FF_HI_NPT_POWER_DOWN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_npt_power_down_ff_mid_npt_detail[] = {
    { "POWER_DOWN", AR_NIC_NPT_NPT_POWER_DOWN_FF_MID_NPT_POWER_DOWN_BP, AR_NIC_NPT_NPT_POWER_DOWN_FF_MID_NPT_POWER_DOWN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_npt_power_down_ff_lo_npt_detail[] = {
    { "POWER_DOWN", AR_NIC_NPT_NPT_POWER_DOWN_FF_LO_NPT_POWER_DOWN_BP, AR_NIC_NPT_NPT_POWER_DOWN_FF_LO_NPT_POWER_DOWN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_cfg_crdts_detail[] = {
    { "MAX_PKT_SIZE", AR_NIC_NPT_CFG_CRDTS_MAX_PKT_SIZE_BP, AR_NIC_NPT_CFG_CRDTS_MAX_PKT_SIZE_MASK },
    { "P_CRDTS_MAX", AR_NIC_NPT_CFG_CRDTS_P_CRDTS_MAX_BP, AR_NIC_NPT_CFG_CRDTS_P_CRDTS_MAX_MASK },
    { "AMO_CRDTS_MAX", AR_NIC_NPT_CFG_CRDTS_AMO_CRDTS_MAX_BP, AR_NIC_NPT_CFG_CRDTS_AMO_CRDTS_MAX_MASK },
    { "NL_CRDTS_MAX", AR_NIC_NPT_CFG_CRDTS_NL_CRDTS_MAX_BP, AR_NIC_NPT_CFG_CRDTS_NL_CRDTS_MAX_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_cfg_avail_tags_detail[] = {
    { "EN", AR_NIC_NPT_CFG_AVAIL_TAGS_EN_BP, AR_NIC_NPT_CFG_AVAIL_TAGS_EN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_err_flg_detail[] = {
    { "NL_CRDT_UNFLW", AR_NIC_NPT_ERR_FLG_NL_CRDT_UNFLW_BP, AR_NIC_NPT_ERR_FLG_NL_CRDT_UNFLW_MASK },
    { "CW_DROP", AR_NIC_NPT_ERR_FLG_CW_DROP_BP, AR_NIC_NPT_ERR_FLG_CW_DROP_MASK },
    { "RSP_FLIT_MBE", AR_NIC_NPT_ERR_FLG_RSP_FLIT_MBE_BP, AR_NIC_NPT_ERR_FLG_RSP_FLIT_MBE_MASK },
    { "RSP_FLIT_SBE", AR_NIC_NPT_ERR_FLG_RSP_FLIT_SBE_BP, AR_NIC_NPT_ERR_FLG_RSP_FLIT_SBE_MASK },
    { "RSP_FLIT_PE", AR_NIC_NPT_ERR_FLG_RSP_FLIT_PE_BP, AR_NIC_NPT_ERR_FLG_RSP_FLIT_PE_MASK },
    { "REQ_FLIT_PE", AR_NIC_NPT_ERR_FLG_REQ_FLIT_PE_BP, AR_NIC_NPT_ERR_FLG_REQ_FLIT_PE_MASK },
    { "CMD_MISMATCH", AR_NIC_NPT_ERR_FLG_CMD_MISMATCH_BP, AR_NIC_NPT_ERR_FLG_CMD_MISMATCH_MASK },
    { "UNSOLICITED_RSP", AR_NIC_NPT_ERR_FLG_UNSOLICITED_RSP_BP, AR_NIC_NPT_ERR_FLG_UNSOLICITED_RSP_MASK },
    { "TIMEOUT", AR_NIC_NPT_ERR_FLG_TIMEOUT_BP, AR_NIC_NPT_ERR_FLG_TIMEOUT_MASK },
    { "NPT_RAM_SBE", AR_NIC_NPT_ERR_FLG_NPT_RAM_SBE_BP, AR_NIC_NPT_ERR_FLG_NPT_RAM_SBE_MASK },
    { "NPT_RAM_MBE", AR_NIC_NPT_ERR_FLG_NPT_RAM_MBE_BP, AR_NIC_NPT_ERR_FLG_NPT_RAM_MBE_MASK },
    { "CE_UFLW", AR_NIC_NPT_ERR_FLG_CE_UFLW_BP, AR_NIC_NPT_ERR_FLG_CE_UFLW_MASK },
    { "P_UFLW", AR_NIC_NPT_ERR_FLG_P_UFLW_BP, AR_NIC_NPT_ERR_FLG_P_UFLW_MASK },
    { "NP_PAYLD_UFLW", AR_NIC_NPT_ERR_FLG_NP_PAYLD_UFLW_BP, AR_NIC_NPT_ERR_FLG_NP_PAYLD_UFLW_MASK },
    { "NP_HDR_UFLW", AR_NIC_NPT_ERR_FLG_NP_HDR_UFLW_BP, AR_NIC_NPT_ERR_FLG_NP_HDR_UFLW_MASK },
    { "RMT_UFLW", AR_NIC_NPT_ERR_FLG_RMT_UFLW_BP, AR_NIC_NPT_ERR_FLG_RMT_UFLW_MASK },
    { "CQ_UFLW", AR_NIC_NPT_ERR_FLG_CQ_UFLW_BP, AR_NIC_NPT_ERR_FLG_CQ_UFLW_MASK },
    { "CE_OFLW", AR_NIC_NPT_ERR_FLG_CE_OFLW_BP, AR_NIC_NPT_ERR_FLG_CE_OFLW_MASK },
    { "P_OFLW", AR_NIC_NPT_ERR_FLG_P_OFLW_BP, AR_NIC_NPT_ERR_FLG_P_OFLW_MASK },
    { "NP_PAYLD_OFLW", AR_NIC_NPT_ERR_FLG_NP_PAYLD_OFLW_BP, AR_NIC_NPT_ERR_FLG_NP_PAYLD_OFLW_MASK },
    { "NP_HDR_OFLW", AR_NIC_NPT_ERR_FLG_NP_HDR_OFLW_BP, AR_NIC_NPT_ERR_FLG_NP_HDR_OFLW_MASK },
    { "RMT_OFLW", AR_NIC_NPT_ERR_FLG_RMT_OFLW_BP, AR_NIC_NPT_ERR_FLG_RMT_OFLW_MASK },
    { "CQ_OFLW", AR_NIC_NPT_ERR_FLG_CQ_OFLW_BP, AR_NIC_NPT_ERR_FLG_CQ_OFLW_MASK },
    { "DIAG_ONLY", AR_NIC_NPT_ERR_FLG_DIAG_ONLY_BP, AR_NIC_NPT_ERR_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
#ifdef EXCEPTIONS_DEFS
static const errcat_mmrd_t _ar_nic_npt_err_flg_errcat[] = {
    { "NL_CRDT_UNFLW", AR_NIC_NPT_ERR_FLG_NL_CRDT_UNFLW_BP, AR_NIC_NPT_ERR_FLG_NL_CRDT_UNFLW_EC },
    { "CW_DROP", AR_NIC_NPT_ERR_FLG_CW_DROP_BP, AR_NIC_NPT_ERR_FLG_CW_DROP_EC },
    { "RSP_FLIT_MBE", AR_NIC_NPT_ERR_FLG_RSP_FLIT_MBE_BP, AR_NIC_NPT_ERR_FLG_RSP_FLIT_MBE_EC },
    { "RSP_FLIT_SBE", AR_NIC_NPT_ERR_FLG_RSP_FLIT_SBE_BP, AR_NIC_NPT_ERR_FLG_RSP_FLIT_SBE_EC },
    { "RSP_FLIT_PE", AR_NIC_NPT_ERR_FLG_RSP_FLIT_PE_BP, AR_NIC_NPT_ERR_FLG_RSP_FLIT_PE_EC },
    { "REQ_FLIT_PE", AR_NIC_NPT_ERR_FLG_REQ_FLIT_PE_BP, AR_NIC_NPT_ERR_FLG_REQ_FLIT_PE_EC },
    { "CMD_MISMATCH", AR_NIC_NPT_ERR_FLG_CMD_MISMATCH_BP, AR_NIC_NPT_ERR_FLG_CMD_MISMATCH_EC },
    { "UNSOLICITED_RSP", AR_NIC_NPT_ERR_FLG_UNSOLICITED_RSP_BP, AR_NIC_NPT_ERR_FLG_UNSOLICITED_RSP_EC },
    { "TIMEOUT", AR_NIC_NPT_ERR_FLG_TIMEOUT_BP, AR_NIC_NPT_ERR_FLG_TIMEOUT_EC },
    { "NPT_RAM_SBE", AR_NIC_NPT_ERR_FLG_NPT_RAM_SBE_BP, AR_NIC_NPT_ERR_FLG_NPT_RAM_SBE_EC },
    { "NPT_RAM_MBE", AR_NIC_NPT_ERR_FLG_NPT_RAM_MBE_BP, AR_NIC_NPT_ERR_FLG_NPT_RAM_MBE_EC },
    { "CE_UFLW", AR_NIC_NPT_ERR_FLG_CE_UFLW_BP, AR_NIC_NPT_ERR_FLG_CE_UFLW_EC },
    { "P_UFLW", AR_NIC_NPT_ERR_FLG_P_UFLW_BP, AR_NIC_NPT_ERR_FLG_P_UFLW_EC },
    { "NP_PAYLD_UFLW", AR_NIC_NPT_ERR_FLG_NP_PAYLD_UFLW_BP, AR_NIC_NPT_ERR_FLG_NP_PAYLD_UFLW_EC },
    { "NP_HDR_UFLW", AR_NIC_NPT_ERR_FLG_NP_HDR_UFLW_BP, AR_NIC_NPT_ERR_FLG_NP_HDR_UFLW_EC },
    { "RMT_UFLW", AR_NIC_NPT_ERR_FLG_RMT_UFLW_BP, AR_NIC_NPT_ERR_FLG_RMT_UFLW_EC },
    { "CQ_UFLW", AR_NIC_NPT_ERR_FLG_CQ_UFLW_BP, AR_NIC_NPT_ERR_FLG_CQ_UFLW_EC },
    { "CE_OFLW", AR_NIC_NPT_ERR_FLG_CE_OFLW_BP, AR_NIC_NPT_ERR_FLG_CE_OFLW_EC },
    { "P_OFLW", AR_NIC_NPT_ERR_FLG_P_OFLW_BP, AR_NIC_NPT_ERR_FLG_P_OFLW_EC },
    { "NP_PAYLD_OFLW", AR_NIC_NPT_ERR_FLG_NP_PAYLD_OFLW_BP, AR_NIC_NPT_ERR_FLG_NP_PAYLD_OFLW_EC },
    { "NP_HDR_OFLW", AR_NIC_NPT_ERR_FLG_NP_HDR_OFLW_BP, AR_NIC_NPT_ERR_FLG_NP_HDR_OFLW_EC },
    { "RMT_OFLW", AR_NIC_NPT_ERR_FLG_RMT_OFLW_BP, AR_NIC_NPT_ERR_FLG_RMT_OFLW_EC },
    { "CQ_OFLW", AR_NIC_NPT_ERR_FLG_CQ_OFLW_BP, AR_NIC_NPT_ERR_FLG_CQ_OFLW_EC },
    { "DIAG_ONLY", AR_NIC_NPT_ERR_FLG_DIAG_ONLY_BP, AR_NIC_NPT_ERR_FLG_DIAG_ONLY_EC },
    { NULL, 0, 0 }
};
#endif
static const generic_mmrd_t _ar_nic_npt_err_clr_detail[] = {
    { "NL_CRDT_UNFLW", AR_NIC_NPT_ERR_CLR_NL_CRDT_UNFLW_BP, AR_NIC_NPT_ERR_CLR_NL_CRDT_UNFLW_MASK },
    { "CW_DROP", AR_NIC_NPT_ERR_CLR_CW_DROP_BP, AR_NIC_NPT_ERR_CLR_CW_DROP_MASK },
    { "RSP_FLIT_MBE", AR_NIC_NPT_ERR_CLR_RSP_FLIT_MBE_BP, AR_NIC_NPT_ERR_CLR_RSP_FLIT_MBE_MASK },
    { "RSP_FLIT_SBE", AR_NIC_NPT_ERR_CLR_RSP_FLIT_SBE_BP, AR_NIC_NPT_ERR_CLR_RSP_FLIT_SBE_MASK },
    { "RSP_FLIT_PE", AR_NIC_NPT_ERR_CLR_RSP_FLIT_PE_BP, AR_NIC_NPT_ERR_CLR_RSP_FLIT_PE_MASK },
    { "REQ_FLIT_PE", AR_NIC_NPT_ERR_CLR_REQ_FLIT_PE_BP, AR_NIC_NPT_ERR_CLR_REQ_FLIT_PE_MASK },
    { "CMD_MISMATCH", AR_NIC_NPT_ERR_CLR_CMD_MISMATCH_BP, AR_NIC_NPT_ERR_CLR_CMD_MISMATCH_MASK },
    { "UNSOLICITED_RSP", AR_NIC_NPT_ERR_CLR_UNSOLICITED_RSP_BP, AR_NIC_NPT_ERR_CLR_UNSOLICITED_RSP_MASK },
    { "TIMEOUT", AR_NIC_NPT_ERR_CLR_TIMEOUT_BP, AR_NIC_NPT_ERR_CLR_TIMEOUT_MASK },
    { "NPT_RAM_SBE", AR_NIC_NPT_ERR_CLR_NPT_RAM_SBE_BP, AR_NIC_NPT_ERR_CLR_NPT_RAM_SBE_MASK },
    { "NPT_RAM_MBE", AR_NIC_NPT_ERR_CLR_NPT_RAM_MBE_BP, AR_NIC_NPT_ERR_CLR_NPT_RAM_MBE_MASK },
    { "CE_UFLW", AR_NIC_NPT_ERR_CLR_CE_UFLW_BP, AR_NIC_NPT_ERR_CLR_CE_UFLW_MASK },
    { "P_UFLW", AR_NIC_NPT_ERR_CLR_P_UFLW_BP, AR_NIC_NPT_ERR_CLR_P_UFLW_MASK },
    { "NP_PAYLD_UFLW", AR_NIC_NPT_ERR_CLR_NP_PAYLD_UFLW_BP, AR_NIC_NPT_ERR_CLR_NP_PAYLD_UFLW_MASK },
    { "NP_HDR_UFLW", AR_NIC_NPT_ERR_CLR_NP_HDR_UFLW_BP, AR_NIC_NPT_ERR_CLR_NP_HDR_UFLW_MASK },
    { "RMT_UFLW", AR_NIC_NPT_ERR_CLR_RMT_UFLW_BP, AR_NIC_NPT_ERR_CLR_RMT_UFLW_MASK },
    { "CQ_UFLW", AR_NIC_NPT_ERR_CLR_CQ_UFLW_BP, AR_NIC_NPT_ERR_CLR_CQ_UFLW_MASK },
    { "CE_OFLW", AR_NIC_NPT_ERR_CLR_CE_OFLW_BP, AR_NIC_NPT_ERR_CLR_CE_OFLW_MASK },
    { "P_OFLW", AR_NIC_NPT_ERR_CLR_P_OFLW_BP, AR_NIC_NPT_ERR_CLR_P_OFLW_MASK },
    { "NP_PAYLD_OFLW", AR_NIC_NPT_ERR_CLR_NP_PAYLD_OFLW_BP, AR_NIC_NPT_ERR_CLR_NP_PAYLD_OFLW_MASK },
    { "NP_HDR_OFLW", AR_NIC_NPT_ERR_CLR_NP_HDR_OFLW_BP, AR_NIC_NPT_ERR_CLR_NP_HDR_OFLW_MASK },
    { "RMT_OFLW", AR_NIC_NPT_ERR_CLR_RMT_OFLW_BP, AR_NIC_NPT_ERR_CLR_RMT_OFLW_MASK },
    { "CQ_OFLW", AR_NIC_NPT_ERR_CLR_CQ_OFLW_BP, AR_NIC_NPT_ERR_CLR_CQ_OFLW_MASK },
    { "DIAG_ONLY", AR_NIC_NPT_ERR_CLR_DIAG_ONLY_BP, AR_NIC_NPT_ERR_CLR_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_err_hss_msk_detail[] = {
    { "NL_CRDT_UNFLW", AR_NIC_NPT_ERR_HSS_MSK_NL_CRDT_UNFLW_BP, AR_NIC_NPT_ERR_HSS_MSK_NL_CRDT_UNFLW_MASK },
    { "CW_DROP", AR_NIC_NPT_ERR_HSS_MSK_CW_DROP_BP, AR_NIC_NPT_ERR_HSS_MSK_CW_DROP_MASK },
    { "RSP_FLIT_MBE", AR_NIC_NPT_ERR_HSS_MSK_RSP_FLIT_MBE_BP, AR_NIC_NPT_ERR_HSS_MSK_RSP_FLIT_MBE_MASK },
    { "RSP_FLIT_SBE", AR_NIC_NPT_ERR_HSS_MSK_RSP_FLIT_SBE_BP, AR_NIC_NPT_ERR_HSS_MSK_RSP_FLIT_SBE_MASK },
    { "RSP_FLIT_PE", AR_NIC_NPT_ERR_HSS_MSK_RSP_FLIT_PE_BP, AR_NIC_NPT_ERR_HSS_MSK_RSP_FLIT_PE_MASK },
    { "REQ_FLIT_PE", AR_NIC_NPT_ERR_HSS_MSK_REQ_FLIT_PE_BP, AR_NIC_NPT_ERR_HSS_MSK_REQ_FLIT_PE_MASK },
    { "CMD_MISMATCH", AR_NIC_NPT_ERR_HSS_MSK_CMD_MISMATCH_BP, AR_NIC_NPT_ERR_HSS_MSK_CMD_MISMATCH_MASK },
    { "UNSOLICITED_RSP", AR_NIC_NPT_ERR_HSS_MSK_UNSOLICITED_RSP_BP, AR_NIC_NPT_ERR_HSS_MSK_UNSOLICITED_RSP_MASK },
    { "TIMEOUT", AR_NIC_NPT_ERR_HSS_MSK_TIMEOUT_BP, AR_NIC_NPT_ERR_HSS_MSK_TIMEOUT_MASK },
    { "NPT_RAM_SBE", AR_NIC_NPT_ERR_HSS_MSK_NPT_RAM_SBE_BP, AR_NIC_NPT_ERR_HSS_MSK_NPT_RAM_SBE_MASK },
    { "NPT_RAM_MBE", AR_NIC_NPT_ERR_HSS_MSK_NPT_RAM_MBE_BP, AR_NIC_NPT_ERR_HSS_MSK_NPT_RAM_MBE_MASK },
    { "CE_UFLW", AR_NIC_NPT_ERR_HSS_MSK_CE_UFLW_BP, AR_NIC_NPT_ERR_HSS_MSK_CE_UFLW_MASK },
    { "P_UFLW", AR_NIC_NPT_ERR_HSS_MSK_P_UFLW_BP, AR_NIC_NPT_ERR_HSS_MSK_P_UFLW_MASK },
    { "NP_PAYLD_UFLW", AR_NIC_NPT_ERR_HSS_MSK_NP_PAYLD_UFLW_BP, AR_NIC_NPT_ERR_HSS_MSK_NP_PAYLD_UFLW_MASK },
    { "NP_HDR_UFLW", AR_NIC_NPT_ERR_HSS_MSK_NP_HDR_UFLW_BP, AR_NIC_NPT_ERR_HSS_MSK_NP_HDR_UFLW_MASK },
    { "RMT_UFLW", AR_NIC_NPT_ERR_HSS_MSK_RMT_UFLW_BP, AR_NIC_NPT_ERR_HSS_MSK_RMT_UFLW_MASK },
    { "CQ_UFLW", AR_NIC_NPT_ERR_HSS_MSK_CQ_UFLW_BP, AR_NIC_NPT_ERR_HSS_MSK_CQ_UFLW_MASK },
    { "CE_OFLW", AR_NIC_NPT_ERR_HSS_MSK_CE_OFLW_BP, AR_NIC_NPT_ERR_HSS_MSK_CE_OFLW_MASK },
    { "P_OFLW", AR_NIC_NPT_ERR_HSS_MSK_P_OFLW_BP, AR_NIC_NPT_ERR_HSS_MSK_P_OFLW_MASK },
    { "NP_PAYLD_OFLW", AR_NIC_NPT_ERR_HSS_MSK_NP_PAYLD_OFLW_BP, AR_NIC_NPT_ERR_HSS_MSK_NP_PAYLD_OFLW_MASK },
    { "NP_HDR_OFLW", AR_NIC_NPT_ERR_HSS_MSK_NP_HDR_OFLW_BP, AR_NIC_NPT_ERR_HSS_MSK_NP_HDR_OFLW_MASK },
    { "RMT_OFLW", AR_NIC_NPT_ERR_HSS_MSK_RMT_OFLW_BP, AR_NIC_NPT_ERR_HSS_MSK_RMT_OFLW_MASK },
    { "CQ_OFLW", AR_NIC_NPT_ERR_HSS_MSK_CQ_OFLW_BP, AR_NIC_NPT_ERR_HSS_MSK_CQ_OFLW_MASK },
    { "DIAG_ONLY", AR_NIC_NPT_ERR_HSS_MSK_DIAG_ONLY_BP, AR_NIC_NPT_ERR_HSS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_err_os_msk_detail[] = {
    { "NL_CRDT_UNFLW", AR_NIC_NPT_ERR_OS_MSK_NL_CRDT_UNFLW_BP, AR_NIC_NPT_ERR_OS_MSK_NL_CRDT_UNFLW_MASK },
    { "CW_DROP", AR_NIC_NPT_ERR_OS_MSK_CW_DROP_BP, AR_NIC_NPT_ERR_OS_MSK_CW_DROP_MASK },
    { "RSP_FLIT_MBE", AR_NIC_NPT_ERR_OS_MSK_RSP_FLIT_MBE_BP, AR_NIC_NPT_ERR_OS_MSK_RSP_FLIT_MBE_MASK },
    { "RSP_FLIT_SBE", AR_NIC_NPT_ERR_OS_MSK_RSP_FLIT_SBE_BP, AR_NIC_NPT_ERR_OS_MSK_RSP_FLIT_SBE_MASK },
    { "RSP_FLIT_PE", AR_NIC_NPT_ERR_OS_MSK_RSP_FLIT_PE_BP, AR_NIC_NPT_ERR_OS_MSK_RSP_FLIT_PE_MASK },
    { "REQ_FLIT_PE", AR_NIC_NPT_ERR_OS_MSK_REQ_FLIT_PE_BP, AR_NIC_NPT_ERR_OS_MSK_REQ_FLIT_PE_MASK },
    { "CMD_MISMATCH", AR_NIC_NPT_ERR_OS_MSK_CMD_MISMATCH_BP, AR_NIC_NPT_ERR_OS_MSK_CMD_MISMATCH_MASK },
    { "UNSOLICITED_RSP", AR_NIC_NPT_ERR_OS_MSK_UNSOLICITED_RSP_BP, AR_NIC_NPT_ERR_OS_MSK_UNSOLICITED_RSP_MASK },
    { "TIMEOUT", AR_NIC_NPT_ERR_OS_MSK_TIMEOUT_BP, AR_NIC_NPT_ERR_OS_MSK_TIMEOUT_MASK },
    { "NPT_RAM_SBE", AR_NIC_NPT_ERR_OS_MSK_NPT_RAM_SBE_BP, AR_NIC_NPT_ERR_OS_MSK_NPT_RAM_SBE_MASK },
    { "NPT_RAM_MBE", AR_NIC_NPT_ERR_OS_MSK_NPT_RAM_MBE_BP, AR_NIC_NPT_ERR_OS_MSK_NPT_RAM_MBE_MASK },
    { "CE_UFLW", AR_NIC_NPT_ERR_OS_MSK_CE_UFLW_BP, AR_NIC_NPT_ERR_OS_MSK_CE_UFLW_MASK },
    { "P_UFLW", AR_NIC_NPT_ERR_OS_MSK_P_UFLW_BP, AR_NIC_NPT_ERR_OS_MSK_P_UFLW_MASK },
    { "NP_PAYLD_UFLW", AR_NIC_NPT_ERR_OS_MSK_NP_PAYLD_UFLW_BP, AR_NIC_NPT_ERR_OS_MSK_NP_PAYLD_UFLW_MASK },
    { "NP_HDR_UFLW", AR_NIC_NPT_ERR_OS_MSK_NP_HDR_UFLW_BP, AR_NIC_NPT_ERR_OS_MSK_NP_HDR_UFLW_MASK },
    { "RMT_UFLW", AR_NIC_NPT_ERR_OS_MSK_RMT_UFLW_BP, AR_NIC_NPT_ERR_OS_MSK_RMT_UFLW_MASK },
    { "CQ_UFLW", AR_NIC_NPT_ERR_OS_MSK_CQ_UFLW_BP, AR_NIC_NPT_ERR_OS_MSK_CQ_UFLW_MASK },
    { "CE_OFLW", AR_NIC_NPT_ERR_OS_MSK_CE_OFLW_BP, AR_NIC_NPT_ERR_OS_MSK_CE_OFLW_MASK },
    { "P_OFLW", AR_NIC_NPT_ERR_OS_MSK_P_OFLW_BP, AR_NIC_NPT_ERR_OS_MSK_P_OFLW_MASK },
    { "NP_PAYLD_OFLW", AR_NIC_NPT_ERR_OS_MSK_NP_PAYLD_OFLW_BP, AR_NIC_NPT_ERR_OS_MSK_NP_PAYLD_OFLW_MASK },
    { "NP_HDR_OFLW", AR_NIC_NPT_ERR_OS_MSK_NP_HDR_OFLW_BP, AR_NIC_NPT_ERR_OS_MSK_NP_HDR_OFLW_MASK },
    { "RMT_OFLW", AR_NIC_NPT_ERR_OS_MSK_RMT_OFLW_BP, AR_NIC_NPT_ERR_OS_MSK_RMT_OFLW_MASK },
    { "CQ_OFLW", AR_NIC_NPT_ERR_OS_MSK_CQ_OFLW_BP, AR_NIC_NPT_ERR_OS_MSK_CQ_OFLW_MASK },
    { "DIAG_ONLY", AR_NIC_NPT_ERR_OS_MSK_DIAG_ONLY_BP, AR_NIC_NPT_ERR_OS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_err_first_flg_detail[] = {
    { "NL_CRDT_UNFLW", AR_NIC_NPT_ERR_FIRST_FLG_NL_CRDT_UNFLW_BP, AR_NIC_NPT_ERR_FIRST_FLG_NL_CRDT_UNFLW_MASK },
    { "CW_DROP", AR_NIC_NPT_ERR_FIRST_FLG_CW_DROP_BP, AR_NIC_NPT_ERR_FIRST_FLG_CW_DROP_MASK },
    { "RSP_FLIT_MBE", AR_NIC_NPT_ERR_FIRST_FLG_RSP_FLIT_MBE_BP, AR_NIC_NPT_ERR_FIRST_FLG_RSP_FLIT_MBE_MASK },
    { "RSP_FLIT_SBE", AR_NIC_NPT_ERR_FIRST_FLG_RSP_FLIT_SBE_BP, AR_NIC_NPT_ERR_FIRST_FLG_RSP_FLIT_SBE_MASK },
    { "RSP_FLIT_PE", AR_NIC_NPT_ERR_FIRST_FLG_RSP_FLIT_PE_BP, AR_NIC_NPT_ERR_FIRST_FLG_RSP_FLIT_PE_MASK },
    { "REQ_FLIT_PE", AR_NIC_NPT_ERR_FIRST_FLG_REQ_FLIT_PE_BP, AR_NIC_NPT_ERR_FIRST_FLG_REQ_FLIT_PE_MASK },
    { "CMD_MISMATCH", AR_NIC_NPT_ERR_FIRST_FLG_CMD_MISMATCH_BP, AR_NIC_NPT_ERR_FIRST_FLG_CMD_MISMATCH_MASK },
    { "UNSOLICITED_RSP", AR_NIC_NPT_ERR_FIRST_FLG_UNSOLICITED_RSP_BP, AR_NIC_NPT_ERR_FIRST_FLG_UNSOLICITED_RSP_MASK },
    { "TIMEOUT", AR_NIC_NPT_ERR_FIRST_FLG_TIMEOUT_BP, AR_NIC_NPT_ERR_FIRST_FLG_TIMEOUT_MASK },
    { "NPT_RAM_SBE", AR_NIC_NPT_ERR_FIRST_FLG_NPT_RAM_SBE_BP, AR_NIC_NPT_ERR_FIRST_FLG_NPT_RAM_SBE_MASK },
    { "NPT_RAM_MBE", AR_NIC_NPT_ERR_FIRST_FLG_NPT_RAM_MBE_BP, AR_NIC_NPT_ERR_FIRST_FLG_NPT_RAM_MBE_MASK },
    { "CE_UFLW", AR_NIC_NPT_ERR_FIRST_FLG_CE_UFLW_BP, AR_NIC_NPT_ERR_FIRST_FLG_CE_UFLW_MASK },
    { "P_UFLW", AR_NIC_NPT_ERR_FIRST_FLG_P_UFLW_BP, AR_NIC_NPT_ERR_FIRST_FLG_P_UFLW_MASK },
    { "NP_PAYLD_UFLW", AR_NIC_NPT_ERR_FIRST_FLG_NP_PAYLD_UFLW_BP, AR_NIC_NPT_ERR_FIRST_FLG_NP_PAYLD_UFLW_MASK },
    { "NP_HDR_UFLW", AR_NIC_NPT_ERR_FIRST_FLG_NP_HDR_UFLW_BP, AR_NIC_NPT_ERR_FIRST_FLG_NP_HDR_UFLW_MASK },
    { "RMT_UFLW", AR_NIC_NPT_ERR_FIRST_FLG_RMT_UFLW_BP, AR_NIC_NPT_ERR_FIRST_FLG_RMT_UFLW_MASK },
    { "CQ_UFLW", AR_NIC_NPT_ERR_FIRST_FLG_CQ_UFLW_BP, AR_NIC_NPT_ERR_FIRST_FLG_CQ_UFLW_MASK },
    { "CE_OFLW", AR_NIC_NPT_ERR_FIRST_FLG_CE_OFLW_BP, AR_NIC_NPT_ERR_FIRST_FLG_CE_OFLW_MASK },
    { "P_OFLW", AR_NIC_NPT_ERR_FIRST_FLG_P_OFLW_BP, AR_NIC_NPT_ERR_FIRST_FLG_P_OFLW_MASK },
    { "NP_PAYLD_OFLW", AR_NIC_NPT_ERR_FIRST_FLG_NP_PAYLD_OFLW_BP, AR_NIC_NPT_ERR_FIRST_FLG_NP_PAYLD_OFLW_MASK },
    { "NP_HDR_OFLW", AR_NIC_NPT_ERR_FIRST_FLG_NP_HDR_OFLW_BP, AR_NIC_NPT_ERR_FIRST_FLG_NP_HDR_OFLW_MASK },
    { "RMT_OFLW", AR_NIC_NPT_ERR_FIRST_FLG_RMT_OFLW_BP, AR_NIC_NPT_ERR_FIRST_FLG_RMT_OFLW_MASK },
    { "CQ_OFLW", AR_NIC_NPT_ERR_FIRST_FLG_CQ_OFLW_BP, AR_NIC_NPT_ERR_FIRST_FLG_CQ_OFLW_MASK },
    { "DIAG_ONLY", AR_NIC_NPT_ERR_FIRST_FLG_DIAG_ONLY_BP, AR_NIC_NPT_ERR_FIRST_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_err_info_ram_detail[] = {
    { "MBE_ADDRESS", AR_NIC_NPT_ERR_INFO_RAM_MBE_ADDRESS_BP, AR_NIC_NPT_ERR_INFO_RAM_MBE_ADDRESS_MASK },
    { "MBE_SYNDROME", AR_NIC_NPT_ERR_INFO_RAM_MBE_SYNDROME_BP, AR_NIC_NPT_ERR_INFO_RAM_MBE_SYNDROME_MASK },
    { "SBE_ADDRESS", AR_NIC_NPT_ERR_INFO_RAM_SBE_ADDRESS_BP, AR_NIC_NPT_ERR_INFO_RAM_SBE_ADDRESS_MASK },
    { "SBE_SYNDROME", AR_NIC_NPT_ERR_INFO_RAM_SBE_SYNDROME_BP, AR_NIC_NPT_ERR_INFO_RAM_SBE_SYNDROME_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_err_info_timeout_detail[] = {
    { "ENTRIES", AR_NIC_NPT_ERR_INFO_TIMEOUT_ENTRIES_BP, AR_NIC_NPT_ERR_INFO_TIMEOUT_ENTRIES_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_err_info_unsolicited_rsp_detail[] = {
    { "REQUEST_TAG", AR_NIC_NPT_ERR_INFO_UNSOLICITED_RSP_REQUEST_TAG_BP, AR_NIC_NPT_ERR_INFO_UNSOLICITED_RSP_REQUEST_TAG_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_err_info_cmd_mismatch_detail[] = {
    { "EXP_NET_CMD", AR_NIC_NPT_ERR_INFO_CMD_MISMATCH_EXP_NET_CMD_BP, AR_NIC_NPT_ERR_INFO_CMD_MISMATCH_EXP_NET_CMD_MASK },
    { "TYPE", AR_NIC_NPT_ERR_INFO_CMD_MISMATCH_TYPE_BP, AR_NIC_NPT_ERR_INFO_CMD_MISMATCH_TYPE_MASK },
    { "RCV_CMD", AR_NIC_NPT_ERR_INFO_CMD_MISMATCH_RCV_CMD_BP, AR_NIC_NPT_ERR_INFO_CMD_MISMATCH_RCV_CMD_MASK },
    { "REQUEST_TAG", AR_NIC_NPT_ERR_INFO_CMD_MISMATCH_REQUEST_TAG_BP, AR_NIC_NPT_ERR_INFO_CMD_MISMATCH_REQUEST_TAG_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_err_info_cw_drop_detail[] = {
    { "RSTATUS", AR_NIC_NPT_ERR_INFO_CW_DROP_RSTATUS_BP, AR_NIC_NPT_ERR_INFO_CW_DROP_RSTATUS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_dbg_errinj_ram_detail[] = {
    { "ADDRESS", AR_NIC_NPT_DBG_ERRINJ_RAM_ADDRESS_BP, AR_NIC_NPT_DBG_ERRINJ_RAM_ADDRESS_MASK },
    { "CHECKBYTE", AR_NIC_NPT_DBG_ERRINJ_RAM_CHECKBYTE_BP, AR_NIC_NPT_DBG_ERRINJ_RAM_CHECKBYTE_MASK },
    { "TRIGGERED", AR_NIC_NPT_DBG_ERRINJ_RAM_TRIGGERED_BP, AR_NIC_NPT_DBG_ERRINJ_RAM_TRIGGERED_MASK },
    { "MODE", AR_NIC_NPT_DBG_ERRINJ_RAM_MODE_BP, AR_NIC_NPT_DBG_ERRINJ_RAM_MODE_MASK },
    { "ENABLE", AR_NIC_NPT_DBG_ERRINJ_RAM_ENABLE_BP, AR_NIC_NPT_DBG_ERRINJ_RAM_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_dbg_errinj_rsp_bus_detail[] = {
    { "TRIGGERED_3", AR_NIC_NPT_DBG_ERRINJ_RSP_BUS_TRIGGERED_3_BP, AR_NIC_NPT_DBG_ERRINJ_RSP_BUS_TRIGGERED_3_MASK },
    { "TRIGGERED_2", AR_NIC_NPT_DBG_ERRINJ_RSP_BUS_TRIGGERED_2_BP, AR_NIC_NPT_DBG_ERRINJ_RSP_BUS_TRIGGERED_2_MASK },
    { "TRIGGERED_1", AR_NIC_NPT_DBG_ERRINJ_RSP_BUS_TRIGGERED_1_BP, AR_NIC_NPT_DBG_ERRINJ_RSP_BUS_TRIGGERED_1_MASK },
    { "TRIGGERED_0", AR_NIC_NPT_DBG_ERRINJ_RSP_BUS_TRIGGERED_0_BP, AR_NIC_NPT_DBG_ERRINJ_RSP_BUS_TRIGGERED_0_MASK },
    { "TAIL", AR_NIC_NPT_DBG_ERRINJ_RSP_BUS_TAIL_BP, AR_NIC_NPT_DBG_ERRINJ_RSP_BUS_TAIL_MASK },
    { "PARITY", AR_NIC_NPT_DBG_ERRINJ_RSP_BUS_PARITY_BP, AR_NIC_NPT_DBG_ERRINJ_RSP_BUS_PARITY_MASK },
    { "ECC1", AR_NIC_NPT_DBG_ERRINJ_RSP_BUS_ECC1_BP, AR_NIC_NPT_DBG_ERRINJ_RSP_BUS_ECC1_MASK },
    { "ECC0", AR_NIC_NPT_DBG_ERRINJ_RSP_BUS_ECC0_BP, AR_NIC_NPT_DBG_ERRINJ_RSP_BUS_ECC0_MASK },
    { "MODE", AR_NIC_NPT_DBG_ERRINJ_RSP_BUS_MODE_BP, AR_NIC_NPT_DBG_ERRINJ_RSP_BUS_MODE_MASK },
    { "COUNT", AR_NIC_NPT_DBG_ERRINJ_RSP_BUS_COUNT_BP, AR_NIC_NPT_DBG_ERRINJ_RSP_BUS_COUNT_MASK },
    { "EN", AR_NIC_NPT_DBG_ERRINJ_RSP_BUS_EN_BP, AR_NIC_NPT_DBG_ERRINJ_RSP_BUS_EN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_dbg_crdts_detail[] = {
    { "NL_CRDTS", AR_NIC_NPT_DBG_CRDTS_NL_CRDTS_BP, AR_NIC_NPT_DBG_CRDTS_NL_CRDTS_MASK },
    { "AMO_CRDTS", AR_NIC_NPT_DBG_CRDTS_AMO_CRDTS_BP, AR_NIC_NPT_DBG_CRDTS_AMO_CRDTS_MASK },
    { "P_CRDTS", AR_NIC_NPT_DBG_CRDTS_P_CRDTS_BP, AR_NIC_NPT_DBG_CRDTS_P_CRDTS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_sts_comp_wait_detail[] = {
    { "STATE", AR_NIC_NPT_STS_COMP_WAIT_STATE_BP, AR_NIC_NPT_STS_COMP_WAIT_STATE_MASK },
    { "RESET", AR_NIC_NPT_STS_COMP_WAIT_RESET_BP, AR_NIC_NPT_STS_COMP_WAIT_RESET_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_prf_en_detail[] = {
    { "PRF_STALL_EN", AR_NIC_NPT_PRF_EN_PRF_STALL_EN_BP, AR_NIC_NPT_PRF_EN_PRF_STALL_EN_MASK },
    { "PRF_FULL_EN", AR_NIC_NPT_PRF_EN_PRF_FULL_EN_BP, AR_NIC_NPT_PRF_EN_PRF_FULL_EN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_prf_full_duration_detail[] = {
    { "MAX", AR_NIC_NPT_PRF_FULL_DURATION_MAX_BP, AR_NIC_NPT_PRF_FULL_DURATION_MAX_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_npt_prf_nl_stall_duration_detail[] = {
    { "MAX", AR_NIC_NPT_PRF_NL_STALL_DURATION_MAX_BP, AR_NIC_NPT_PRF_NL_STALL_DURATION_MAX_MASK },
    { NULL, 0, 0 }
};

/*
 *  AR NPT MMR DECLARATIONS
 */
static const generic_mmr_t _ar_nic_npt_cfg_params = {
    "AR_NIC_NPT_CFG_PARAMS", AR_NIC_NPT_CFG_PARAMS, 8, 1, _ar_nic_npt_cfg_params_detail
};
static const generic_mmr_t _ar_nic_npt_npt_mmr_ring_0_hi_npt = {
    "AR_NIC_NPT_NPT_MMR_RING_0_HI_NPT", AR_NIC_NPT_NPT_MMR_RING_0_HI_NPT, 8, 1, _ar_nic_npt_npt_mmr_ring_0_hi_npt_detail
};
static const generic_mmr_t _ar_nic_npt_npt_mmr_ring_0_mid_npt = {
    "AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT", AR_NIC_NPT_NPT_MMR_RING_0_MID_NPT, 8, 1, _ar_nic_npt_npt_mmr_ring_0_mid_npt_detail
};
static const generic_mmr_t _ar_nic_npt_npt_mmr_ring_0_lo_npt = {
    "AR_NIC_NPT_NPT_MMR_RING_0_LO_NPT", AR_NIC_NPT_NPT_MMR_RING_0_LO_NPT, 8, 1, _ar_nic_npt_npt_mmr_ring_0_lo_npt_detail
};
static const generic_mmr_t _ar_nic_npt_err_flg_1_hi_npt = {
    "AR_NIC_NPT_ERR_FLG_1_HI_NPT", AR_NIC_NPT_ERR_FLG_1_HI_NPT, 8, 1, _ar_nic_npt_err_flg_1_hi_npt_detail
};
static const generic_mmr_t _ar_nic_npt_err_flg_1_mid_npt = {
    "AR_NIC_NPT_ERR_FLG_1_MID_NPT", AR_NIC_NPT_ERR_FLG_1_MID_NPT, 8, 1, _ar_nic_npt_err_flg_1_mid_npt_detail
};
static const generic_mmr_t _ar_nic_npt_err_flg_1_lo_npt = {
    "AR_NIC_NPT_ERR_FLG_1_LO_NPT", AR_NIC_NPT_ERR_FLG_1_LO_NPT, 8, 1, _ar_nic_npt_err_flg_1_lo_npt_detail
};
static const generic_mmr_t _ar_nic_npt_amo_npt_rsp_flit_2_hi_npt = {
    "AR_NIC_NPT_AMO_NPT_RSP_FLIT_2_HI_NPT", AR_NIC_NPT_AMO_NPT_RSP_FLIT_2_HI_NPT, 8, 1, _ar_nic_npt_amo_npt_rsp_flit_2_hi_npt_detail
};
static const generic_mmr_t _ar_nic_npt_amo_npt_rsp_flit_2_mid_npt = {
    "AR_NIC_NPT_AMO_NPT_RSP_FLIT_2_MID_NPT", AR_NIC_NPT_AMO_NPT_RSP_FLIT_2_MID_NPT, 8, 1, _ar_nic_npt_amo_npt_rsp_flit_2_mid_npt_detail
};
static const generic_mmr_t _ar_nic_npt_amo_npt_rsp_flit_2_lo_npt = {
    "AR_NIC_NPT_AMO_NPT_RSP_FLIT_2_LO_NPT", AR_NIC_NPT_AMO_NPT_RSP_FLIT_2_LO_NPT, 8, 1, _ar_nic_npt_amo_npt_rsp_flit_2_lo_npt_detail
};
static const generic_mmr_t _ar_nic_npt_nic_nl_rsp_flit_3_hi_npt = {
    "AR_NIC_NPT_NIC_NL_RSP_FLIT_3_HI_NPT", AR_NIC_NPT_NIC_NL_RSP_FLIT_3_HI_NPT, 8, 1, _ar_nic_npt_nic_nl_rsp_flit_3_hi_npt_detail
};
static const generic_mmr_t _ar_nic_npt_nic_nl_rsp_flit_3_mid_npt = {
    "AR_NIC_NPT_NIC_NL_RSP_FLIT_3_MID_NPT", AR_NIC_NPT_NIC_NL_RSP_FLIT_3_MID_NPT, 8, 1, _ar_nic_npt_nic_nl_rsp_flit_3_mid_npt_detail
};
static const generic_mmr_t _ar_nic_npt_nic_nl_rsp_flit_3_lo_npt = {
    "AR_NIC_NPT_NIC_NL_RSP_FLIT_3_LO_NPT", AR_NIC_NPT_NIC_NL_RSP_FLIT_3_LO_NPT, 8, 1, _ar_nic_npt_nic_nl_rsp_flit_3_lo_npt_detail
};
static const generic_mmr_t _ar_nic_npt_npt_amo_req_flit_4_hi_npt = {
    "AR_NIC_NPT_NPT_AMO_REQ_FLIT_4_HI_NPT", AR_NIC_NPT_NPT_AMO_REQ_FLIT_4_HI_NPT, 8, 1, _ar_nic_npt_npt_amo_req_flit_4_hi_npt_detail
};
static const generic_mmr_t _ar_nic_npt_npt_amo_req_flit_4_mid_npt = {
    "AR_NIC_NPT_NPT_AMO_REQ_FLIT_4_MID_NPT", AR_NIC_NPT_NPT_AMO_REQ_FLIT_4_MID_NPT, 8, 1, _ar_nic_npt_npt_amo_req_flit_4_mid_npt_detail
};
static const generic_mmr_t _ar_nic_npt_npt_amo_req_flit_4_lo_npt = {
    "AR_NIC_NPT_NPT_AMO_REQ_FLIT_4_LO_NPT", AR_NIC_NPT_NPT_AMO_REQ_FLIT_4_LO_NPT, 8, 1, _ar_nic_npt_npt_amo_req_flit_4_lo_npt_detail
};
static const generic_mmr_t _ar_nic_npt_npt_free_vld_vecs_5_hi_npt = {
    "AR_NIC_NPT_NPT_FREE_VLD_VECS_5_HI_NPT", AR_NIC_NPT_NPT_FREE_VLD_VECS_5_HI_NPT, 8, 1, _ar_nic_npt_npt_free_vld_vecs_5_hi_npt_detail
};
static const generic_mmr_t _ar_nic_npt_npt_free_vld_vecs_5_mid_npt = {
    "AR_NIC_NPT_NPT_FREE_VLD_VECS_5_MID_NPT", AR_NIC_NPT_NPT_FREE_VLD_VECS_5_MID_NPT, 8, 1, _ar_nic_npt_npt_free_vld_vecs_5_mid_npt_detail
};
static const generic_mmr_t _ar_nic_npt_npt_free_vld_vecs_5_lo_npt = {
    "AR_NIC_NPT_NPT_FREE_VLD_VECS_5_LO_NPT", AR_NIC_NPT_NPT_FREE_VLD_VECS_5_LO_NPT, 8, 1, _ar_nic_npt_npt_free_vld_vecs_5_lo_npt_detail
};
static const generic_mmr_t _ar_nic_npt_npt_power_down_ff_hi_npt = {
    "AR_NIC_NPT_NPT_POWER_DOWN_FF_HI_NPT", AR_NIC_NPT_NPT_POWER_DOWN_FF_HI_NPT, 8, 1, _ar_nic_npt_npt_power_down_ff_hi_npt_detail
};
static const generic_mmr_t _ar_nic_npt_npt_power_down_ff_mid_npt = {
    "AR_NIC_NPT_NPT_POWER_DOWN_FF_MID_NPT", AR_NIC_NPT_NPT_POWER_DOWN_FF_MID_NPT, 8, 1, _ar_nic_npt_npt_power_down_ff_mid_npt_detail
};
static const generic_mmr_t _ar_nic_npt_npt_power_down_ff_lo_npt = {
    "AR_NIC_NPT_NPT_POWER_DOWN_FF_LO_NPT", AR_NIC_NPT_NPT_POWER_DOWN_FF_LO_NPT, 8, 1, _ar_nic_npt_npt_power_down_ff_lo_npt_detail
};
static const generic_mmr_t _ar_nic_npt_cfg_crdts = {
    "AR_NIC_NPT_CFG_CRDTS", AR_NIC_NPT_CFG_CRDTS, 8, 1, _ar_nic_npt_cfg_crdts_detail
};
static const generic_mmr_t _ar_nic_npt_cfg_avail_tags = {
    "AR_NIC_NPT_CFG_AVAIL_TAGS", AR_NIC_NPT_CFG_AVAIL_TAGS, 8, 1, _ar_nic_npt_cfg_avail_tags_detail
};
static const generic_mmr_t _ar_nic_npt_err_flg = {
    "AR_NIC_NPT_ERR_FLG", AR_NIC_NPT_ERR_FLG, 8, 1, _ar_nic_npt_err_flg_detail
};
static const generic_mmr_t _ar_nic_npt_err_clr = {
    "AR_NIC_NPT_ERR_CLR", AR_NIC_NPT_ERR_CLR, 8, 1, _ar_nic_npt_err_clr_detail
};
static const generic_mmr_t _ar_nic_npt_err_hss_msk = {
    "AR_NIC_NPT_ERR_HSS_MSK", AR_NIC_NPT_ERR_HSS_MSK, 8, 1, _ar_nic_npt_err_hss_msk_detail
};
static const generic_mmr_t _ar_nic_npt_err_os_msk = {
    "AR_NIC_NPT_ERR_OS_MSK", AR_NIC_NPT_ERR_OS_MSK, 8, 1, _ar_nic_npt_err_os_msk_detail
};
static const generic_mmr_t _ar_nic_npt_err_first_flg = {
    "AR_NIC_NPT_ERR_FIRST_FLG", AR_NIC_NPT_ERR_FIRST_FLG, 8, 1, _ar_nic_npt_err_first_flg_detail
};
static const generic_mmr_t _ar_nic_npt_err_info_ram = {
    "AR_NIC_NPT_ERR_INFO_RAM", AR_NIC_NPT_ERR_INFO_RAM, 8, 1, _ar_nic_npt_err_info_ram_detail
};
static const generic_mmr_t _ar_nic_npt_err_info_timeout = {
    "AR_NIC_NPT_ERR_INFO_TIMEOUT", AR_NIC_NPT_ERR_INFO_TIMEOUT, 8, 1, _ar_nic_npt_err_info_timeout_detail
};
static const generic_mmr_t _ar_nic_npt_err_info_unsolicited_rsp = {
    "AR_NIC_NPT_ERR_INFO_UNSOLICITED_RSP", AR_NIC_NPT_ERR_INFO_UNSOLICITED_RSP, 8, 1, _ar_nic_npt_err_info_unsolicited_rsp_detail
};
static const generic_mmr_t _ar_nic_npt_err_info_cmd_mismatch = {
    "AR_NIC_NPT_ERR_INFO_CMD_MISMATCH", AR_NIC_NPT_ERR_INFO_CMD_MISMATCH, 8, 1, _ar_nic_npt_err_info_cmd_mismatch_detail
};
static const generic_mmr_t _ar_nic_npt_err_info_cw_drop = {
    "AR_NIC_NPT_ERR_INFO_CW_DROP", AR_NIC_NPT_ERR_INFO_CW_DROP, 8, 1, _ar_nic_npt_err_info_cw_drop_detail
};
static const generic_mmr_t _ar_nic_npt_dbg_errinj_ram = {
    "AR_NIC_NPT_DBG_ERRINJ_RAM", AR_NIC_NPT_DBG_ERRINJ_RAM, 8, 1, _ar_nic_npt_dbg_errinj_ram_detail
};
static const generic_mmr_t _ar_nic_npt_dbg_errinj_rsp_bus = {
    "AR_NIC_NPT_DBG_ERRINJ_RSP_BUS", AR_NIC_NPT_DBG_ERRINJ_RSP_BUS, 8, 1, _ar_nic_npt_dbg_errinj_rsp_bus_detail
};
static const generic_mmr_t _ar_nic_npt_dbg_crdts = {
    "AR_NIC_NPT_DBG_CRDTS", AR_NIC_NPT_DBG_CRDTS, 8, 1, _ar_nic_npt_dbg_crdts_detail
};
static const generic_mmr_t _ar_nic_npt_sts_comp_wait = {
    "AR_NIC_NPT_STS_COMP_WAIT", AR_NIC_NPT_STS_COMP_WAIT, 8, 1, _ar_nic_npt_sts_comp_wait_detail
};
static const generic_mmr_t _ar_nic_npt_prf_en = {
    "AR_NIC_NPT_PRF_EN", AR_NIC_NPT_PRF_EN, 8, 1, _ar_nic_npt_prf_en_detail
};
static const generic_mmr_t _ar_nic_npt_prf_full_duration = {
    "AR_NIC_NPT_PRF_FULL_DURATION", AR_NIC_NPT_PRF_FULL_DURATION, 8, 1, _ar_nic_npt_prf_full_duration_detail
};
static const generic_mmr_t _ar_nic_npt_prf_nl_stall_duration = {
    "AR_NIC_NPT_PRF_NL_STALL_DURATION", AR_NIC_NPT_PRF_NL_STALL_DURATION, 8, 1, _ar_nic_npt_prf_nl_stall_duration_detail
};

/*
 *  INSTALL AR NPT MMRS
 */
static const generic_mmr_t* _ar_npt_mmrs[] _unused = {
    &_ar_nic_npt_cfg_params,
    &_ar_nic_npt_npt_mmr_ring_0_hi_npt,
    &_ar_nic_npt_npt_mmr_ring_0_mid_npt,
    &_ar_nic_npt_npt_mmr_ring_0_lo_npt,
    &_ar_nic_npt_err_flg_1_hi_npt,
    &_ar_nic_npt_err_flg_1_mid_npt,
    &_ar_nic_npt_err_flg_1_lo_npt,
    &_ar_nic_npt_amo_npt_rsp_flit_2_hi_npt,
    &_ar_nic_npt_amo_npt_rsp_flit_2_mid_npt,
    &_ar_nic_npt_amo_npt_rsp_flit_2_lo_npt,
    &_ar_nic_npt_nic_nl_rsp_flit_3_hi_npt,
    &_ar_nic_npt_nic_nl_rsp_flit_3_mid_npt,
    &_ar_nic_npt_nic_nl_rsp_flit_3_lo_npt,
    &_ar_nic_npt_npt_amo_req_flit_4_hi_npt,
    &_ar_nic_npt_npt_amo_req_flit_4_mid_npt,
    &_ar_nic_npt_npt_amo_req_flit_4_lo_npt,
    &_ar_nic_npt_npt_free_vld_vecs_5_hi_npt,
    &_ar_nic_npt_npt_free_vld_vecs_5_mid_npt,
    &_ar_nic_npt_npt_free_vld_vecs_5_lo_npt,
    &_ar_nic_npt_npt_power_down_ff_hi_npt,
    &_ar_nic_npt_npt_power_down_ff_mid_npt,
    &_ar_nic_npt_npt_power_down_ff_lo_npt,
    &_ar_nic_npt_cfg_crdts,
    &_ar_nic_npt_cfg_avail_tags,
    &_ar_nic_npt_err_flg,
    &_ar_nic_npt_err_clr,
    &_ar_nic_npt_err_hss_msk,
    &_ar_nic_npt_err_os_msk,
    &_ar_nic_npt_err_first_flg,
    &_ar_nic_npt_err_info_ram,
    &_ar_nic_npt_err_info_timeout,
    &_ar_nic_npt_err_info_unsolicited_rsp,
    &_ar_nic_npt_err_info_cmd_mismatch,
    &_ar_nic_npt_err_info_cw_drop,
    &_ar_nic_npt_dbg_errinj_ram,
    &_ar_nic_npt_dbg_errinj_rsp_bus,
    &_ar_nic_npt_dbg_crdts,
    &_ar_nic_npt_sts_comp_wait,
    &_ar_nic_npt_prf_en,
    &_ar_nic_npt_prf_full_duration,
    &_ar_nic_npt_prf_nl_stall_duration,
    NULL
};

#endif
