/******************************************************************************
 * COPYRIGHT CRAY INC. ar_nslm_enum_h.h
 * FILE: ar_nslm_enum_h.h
 * Created by v2h.c on Wed Oct  8 14:39:02 2014
 ******************************************************************************/

#ifndef _AR_NSLM_ENUM_H_H_
#define _AR_NSLM_ENUM_H_H_

#define AR_NIC_NSLM_RESET_FLIT_COUNT_DELAY                          	0x7ull
#define AR_NIC_NETMON_LM_BLK_SEL                                    	0x0ull
#define AR_NIC_NAT_LM_BLK_SEL                                       	0x1ull
#define AR_NIC_CE_LM_BLK_SEL                                        	0x2ull
#define AR_NIC_SSID_LM_BLK_SEL                                      	0x3ull
#define AR_NIC_ORB_LM_BLK_SEL                                       	0x4ull
#define AR_NIC_RAT_LM_BLK_SEL                                       	0x5ull
#define AR_NIC_TARB_LM_BLK_SEL                                      	0x6ull
#define AR_NIC_WC_LM_BLK_SEL                                        	0x7ull
#define AR_NIC_REQMON_LM_BLK_SEL                                    	0x0ull
#define AR_NIC_BTE_LM_BLK_SEL                                       	0x1ull
#define AR_NIC_FMA_LM_BLK_SEL                                       	0x2ull
#define AR_NIC_DLA_LM_BLK_SEL                                       	0x3ull
#define AR_NIC_RSPMON_LM_BLK_SEL                                    	0x0ull
#define AR_NIC_CQ_LM_BLK_SEL                                        	0x1ull
#define AR_NIC_RMT_LM_BLK_SEL                                       	0x2ull
#define AR_NIC_IOMMU_LM_BLK_SEL                                     	0x3ull
#define AR_NIC_PARB_LM_BLK_SEL                                      	0x4ull
#define AR_NIC_NPT_LM_BLK_SEL                                       	0x5ull
#define AR_NIC_AMO_LM_BLK_SEL                                       	0x6ull
#define AR_NIC_NET_SUBCHIP_ID                                       	0x0ull
#define AR_NIC_REQ_SUBCHIP_ID                                       	0x1ull
#define AR_NIC_RSP_SUBCHIP_ID                                       	0x2ull
#define AR_NIC_NETMON_EVENT_CNTR_NETMON                             	0x0ull
#define AR_NIC_NETMON_EVENT_CNTR_NAT                                	0x10ull
#define AR_NIC_NETMON_EVENT_CNTR_CE                                 	0x90ull
#define AR_NIC_NETMON_EVENT_CNTR_SSID                               	0xe0ull
#define AR_NIC_NETMON_EVENT_CNTR_ORB                                	0x1c8ull
#define AR_NIC_NETMON_EVENT_CNTR_RAT                                	0x2a8ull
#define AR_NIC_NETMON_EVENT_CNTR_TARB                               	0x380ull
#define AR_NIC_NETMON_EVENT_CNTR_SCRATCH                            	0x3e0ull
#define AR_NIC_NETMON_NETMON_EVENT_CNTR_TRIGGER0                    	0x0ull
#define AR_NIC_NETMON_NETMON_EVENT_CNTR_TRIGGER1                    	0x1ull
#define AR_NIC_NETMON_NAT_EVENT_CNTR_RAT_TRANSLATIONS               	0x0ull
#define AR_NIC_NETMON_NAT_EVENT_CNTR_RAT_STALLED                    	0x1ull
#define AR_NIC_NETMON_NAT_EVENT_CNTR_RAT_BLOCKED                    	0x2ull
#define AR_NIC_NETMON_NAT_EVENT_CNTR_CQ_TRANSLATIONS                	0x3ull
#define AR_NIC_NETMON_NAT_EVENT_CNTR_CQ_STALLED                     	0x4ull
#define AR_NIC_NETMON_NAT_EVENT_CNTR_CQ_BLOCKED                     	0x5ull
#define AR_NIC_NETMON_NAT_EVENT_CNTR_BTE_TRANSLATIONS               	0x6ull
#define AR_NIC_NETMON_NAT_EVENT_CNTR_BTE_STALLED                    	0x7ull
#define AR_NIC_NETMON_NAT_EVENT_CNTR_BTE_BLOCKED                    	0x8ull
#define AR_NIC_NETMON_NAT_EVENT_CNTR_PIPELINE_STALLED               	0x9ull
#define AR_NIC_NETMON_NAT_EVENT_CNTR_MDDT0_SBE                      	0xaull
#define AR_NIC_NETMON_NAT_EVENT_CNTR_MDDT0_MBE                      	0xbull
#define AR_NIC_NETMON_NAT_EVENT_CNTR_MDDT1_SBE                      	0xcull
#define AR_NIC_NETMON_NAT_EVENT_CNTR_MDDT1_MBE                      	0xdull
#define AR_NIC_NETMON_NAT_EVENT_CNTR_PTT_SBE                        	0xeull
#define AR_NIC_NETMON_NAT_EVENT_CNTR_PTT_MBE                        	0xfull
#define AR_NIC_NETMON_CE_EVENT_CNTR_REDUCT_SCAT0                    	0x0ull
#define AR_NIC_NETMON_CE_EVENT_CNTR_REDUCT_SCAT1                    	0x1ull
#define AR_NIC_NETMON_CE_EVENT_CNTR_REDUCT_SCAT2                    	0x2ull
#define AR_NIC_NETMON_CE_EVENT_CNTR_REDUCT_SCAT3                    	0x3ull
#define AR_NIC_NETMON_CE_EVENT_CNTR_DFLIT_SBE                       	0x4ull
#define AR_NIC_NETMON_CE_EVENT_CNTR_DFLIT_MBE                       	0x5ull
#define AR_NIC_NETMON_CE_EVENT_CNTR_CONFIG_SBE                      	0x6ull
#define AR_NIC_NETMON_CE_EVENT_CNTR_CONFIG_MBE                      	0x7ull
#define AR_NIC_NETMON_CE_EVENT_CNTR_HEADER_PC                       	0x8ull
#define AR_NIC_NETMON_CE_EVENT_CNTR_BAD_REQS                        	0x9ull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_ALLOCATIONS                   	0x0ull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_NO_SSID                       	0x1ull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_NO_SSID_DURATN                	0x2ull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_REQ_STALLED_DURATN            	0x3ull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_DSMN_OPTIMAL                  	0x4ull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_DSMN_SUBOPTIMAL               	0x5ull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_BTESEND_SUCCESSFUL            	0x6ull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_BTESEND_UNSUCCESSFUL          	0x7ull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_NO_DEST_NOTIFY                	0x8ull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_LATE_FIRST_REQRSP             	0x9ull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_INTENTIONAL_TIMEOUT           	0xaull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_LREQ_ERR_HSS                  	0xbull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_LREQ_ERR_OS                   	0xcull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_RREQ_HSS                      	0xdull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_RREQ_OS                       	0xeull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_RSP_HSS                       	0xfull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_RSP_OS                        	0x10ull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_STALE_SSID                    	0x11ull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_SEQ_ERR_HSS                   	0x12ull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_SEQ_ERR_OS                    	0x13ull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_UNEXPTD_RSP                   	0x14ull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_MEM_ERR_CORR                  	0x15ull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_MEM_ERR_UNCORR                	0x16ull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_CORRUPT_REQ_HD                	0x17ull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_CORR_REQ_PAYLD_ERR            	0x18ull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_UNCORR_REQ_PAYLD_ERR          	0x19ull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_REQ_LEN_ERR                   	0x1aull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_CORRUPT_RSP                   	0x1bull
#define AR_NIC_NETMON_SSID_EVENT_CNTR_BYPASSED_REQ                  	0x1cull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_REQ_FLITS                      	0x0ull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_REQ_PKTS                       	0x1ull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_REQ_STALLED                    	0x2ull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_RSP_NET_TRACK                  	0x3ull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_RSP_FLITS                      	0x4ull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_RSP_PKTS                       	0x5ull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_RSP_STALLED                    	0x6ull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_RSP_BLOCKED                    	0x7ull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_RSP_BLOCKED_PKT_GEN            	0x8ull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_ORD_RAM_READ                   	0x9ull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_NTT_SBE                        	0xaull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_NTT_MBE                        	0xbull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_PTT_SBE                        	0xcull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_PTT_MBE                        	0xdull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_REQ_FIFO_SBE                   	0xeull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_REQ_FIFO_MBE                   	0xfull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_REQ_FIFO_PE                    	0x10ull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_RSP_FIFO_SBE                   	0x11ull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_RSP_FIFO_MBE                   	0x12ull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_RSP_FIFO_PE                    	0x13ull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_RSP_FIFO_SPKT                  	0x14ull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_ORD_SBE                        	0x15ull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_ORD_MBE                        	0x16ull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_SCRUB_CNT                      	0x17ull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_NO_ENTRY                       	0x18ull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_CMD_MISMATCH                   	0x19ull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_ILLEGAL_PKTID                  	0x1aull
#define AR_NIC_NETMON_ORB_EVENT_CNTR_ILLEGAL_LSTATUS                	0x1bull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_NL_PKTS                        	0x0ull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_NL_FLITS                       	0x1ull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_NL_BLOCKED                     	0x2ull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_IOMMU_PKTS                     	0x3ull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_IOMMU_FLITS                    	0x4ull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_IOMMU_BLOCKED                  	0x5ull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_REQ_STALLED                    	0x6ull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_ORB_PKTS                       	0x7ull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_ORB_FLITS                      	0x8ull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_RSP_STALLED                    	0x9ull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_REQ_PARITY_INPUT               	0xaull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_RSP_PARITY_INPUT               	0xbull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_REQ_PARITY_OUTPUT              	0xcull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_RSP_PARITY_OUTPUT              	0xdull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_REQ_XLAT_ERR                   	0xeull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_REQ_PAYLD_ERR                  	0xfull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_RSP_XLAT_ERR                   	0x10ull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_RSP_PAYLD_ERR                  	0x11ull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_IOMMU_PARITY_INPUT             	0x12ull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_IOMMU_DROP_INPUT               	0x13ull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_IOMMU_PAYLD_ERR                	0x14ull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_REQ_MALFORMED                  	0x15ull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_REQ_INV_CMD                    	0x16ull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_RSP_MALFORMED                  	0x17ull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_RSP_INV_CMD                    	0x18ull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_REQ_FLIT                       	0x19ull
#define AR_NIC_NETMON_RAT_EVENT_CNTR_RSP_FLIT                       	0x1aull
#define AR_NIC_NETMON_TARB_EVENT_CNTR_CE_FLITS                      	0x0ull
#define AR_NIC_NETMON_TARB_EVENT_CNTR_CE_PKTS                       	0x1ull
#define AR_NIC_NETMON_TARB_EVENT_CNTR_CE_BLOCKED                    	0x2ull
#define AR_NIC_NETMON_TARB_EVENT_CNTR_BTE_FLITS                     	0x3ull
#define AR_NIC_NETMON_TARB_EVENT_CNTR_BTE_PKTS                      	0x4ull
#define AR_NIC_NETMON_TARB_EVENT_CNTR_BTE_BLOCKED                   	0x5ull
#define AR_NIC_NETMON_TARB_EVENT_CNTR_DLA_FLITS                     	0x6ull
#define AR_NIC_NETMON_TARB_EVENT_CNTR_DLA_PKTS                      	0x7ull
#define AR_NIC_NETMON_TARB_EVENT_CNTR_DLA_BLOCKED                   	0x8ull
#define AR_NIC_NETMON_TARB_EVENT_CNTR_SSID_FLITS                    	0x9ull
#define AR_NIC_NETMON_TARB_EVENT_CNTR_SSID_PKTS                     	0xaull
#define AR_NIC_NETMON_TARB_EVENT_CNTR_SSID_STALLED                  	0xbull
#define AR_NIC_NETMON_RESERVED_EVENT_CNTR_SCRATCH0                  	0x0ull
#define AR_NIC_NETMON_RESERVED_EVENT_CNTR_SCRATCH1                  	0x1ull
#define AR_NIC_NETMON_RESERVED_EVENT_CNTR_SCRATCH2                  	0x2ull
#define AR_NIC_NETMON_RESERVED_EVENT_CNTR_SCRATCH3                  	0x3ull
#define AR_NIC_REQMON_EVENT_CNTR_REQMON                             	0x0ull
#define AR_NIC_REQMON_EVENT_CNTR_BTE                                	0x10ull
#define AR_NIC_REQMON_EVENT_CNTR_FMA                                	0x180ull
#define AR_NIC_REQMON_EVENT_CNTR_DLA                                	0x200ull
#define AR_NIC_REQMON_EVENT_CNTR_AMO                                	0x280ull
#define AR_NIC_REQMON_EVENT_CNTR_WC                                 	0x380ull
#define AR_NIC_REQMON_REQMON_EVENT_CNTR_TRIGGER0                    	0x0ull
#define AR_NIC_REQMON_REQMON_EVENT_CNTR_TRIGGER1                    	0x1ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_NET_PKT0                       	0x0ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_NET_PKT1                       	0x1ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_NET_PKT2                       	0x2ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_NET_PKT3                       	0x3ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_DESC0                          	0x4ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_DESC1                          	0x5ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_DESC2                          	0x6ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_DESC3                          	0x7ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_PROC_TIME0                     	0x8ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_PROC_TIME1                     	0x9ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_PROC_TIME2                     	0xaull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_PROC_TIME3                     	0xbull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_TARB_FLT_BLK                   	0xcull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_TARB_PKT_BLK                   	0xdull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_PARB_WR_FLT_BLK                	0xeull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_PARB_RD_FLT_BLK                	0xfull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_PARB_RD_PKT_BLK                	0x10ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_RD_REQ0                        	0x11ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_RD_REQ1                        	0x12ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_RD_REQ2                        	0x13ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_RD_REQ3                        	0x14ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_RD_RSP0                        	0x15ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_RD_RSP1                        	0x16ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_RD_RSP2                        	0x17ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_RD_RSP3                        	0x18ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_PI_RD_RSP_ERR0                 	0x19ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_PI_RD_RSP_ERR1                 	0x1aull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_PI_RD_RSP_ERR2                 	0x1bull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_PI_RD_RSP_ERR3                 	0x1cull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_NAT_ERR0                       	0x1dull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_NAT_ERR1                       	0x1eull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_NAT_ERR2                       	0x1full
#define AR_NIC_REQMON_BTE_EVENT_CNTR_NAT_ERR3                       	0x20ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_TIMEOUT_ERR0                   	0x21ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_TIMEOUT_ERR1                   	0x22ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_TIMEOUT_ERR2                   	0x23ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_TIMEOUT_ERR3                   	0x24ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_UNCORRECTABLE_ERR0             	0x25ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_UNCORRECTABLE_ERR1             	0x26ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_UNCORRECTABLE_ERR2             	0x27ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_UNCORRECTABLE_ERR3             	0x28ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_INV_CMD0                       	0x29ull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_INV_CMD1                       	0x2aull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_INV_CMD2                       	0x2bull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_INV_CMD3                       	0x2cull
#define AR_NIC_REQMON_BTE_EVENT_CNTR_AGGREGATED_CQE                 	0x2dull
#define AR_NIC_REQMON_FMA_EVENT_CNTR_PKT                            	0x0ull
#define AR_NIC_REQMON_FMA_EVENT_CNTR_FLIT                           	0x1ull
#define AR_NIC_REQMON_FMA_EVENT_CNTR_TARB_STALLED                   	0x2ull
#define AR_NIC_REQMON_FMA_EVENT_CNTR_PI_PKT                         	0x3ull
#define AR_NIC_REQMON_FMA_EVENT_CNTR_PI_FLIT                        	0x4ull
#define AR_NIC_REQMON_FMA_EVENT_CNTR_CQ                             	0x5ull
#define AR_NIC_REQMON_FMA_EVENT_CNTR_CQ_STALL                       	0x6ull
#define AR_NIC_REQMON_FMA_EVENT_CNTR_GET_REQ                        	0x7ull
#define AR_NIC_REQMON_FMA_EVENT_CNTR_FAMO_REQ                       	0x8ull
#define AR_NIC_REQMON_FMA_EVENT_CNTR_PUT_REQ                        	0x9ull
#define AR_NIC_REQMON_FMA_EVENT_CNTR_NFAMO_REQ                      	0xaull
#define AR_NIC_REQMON_FMA_EVENT_CNTR_HDR_PERR                       	0xbull
#define AR_NIC_REQMON_FMA_EVENT_CNTR_DATA_MBE                       	0xcull
#define AR_NIC_REQMON_FMA_EVENT_CNTR_DESC_MBE                       	0xdull
#define AR_NIC_REQMON_FMA_EVENT_CNTR_INV_CMD                        	0xeull
#define AR_NIC_REQMON_FMA_EVENT_CNTR_TDATA_SBE                      	0xfull
#define AR_NIC_REQMON_DLA_EVENT_CNTR_LO_CD_ALLOC_PASS               	0x0ull
#define AR_NIC_REQMON_DLA_EVENT_CNTR_LO_CD_ALLOC_FAIL               	0x1ull
#define AR_NIC_REQMON_DLA_EVENT_CNTR_HI_CD_ALLOC_PASS               	0x2ull
#define AR_NIC_REQMON_DLA_EVENT_CNTR_HI_CD_ALLOC_FAIL               	0x3ull
#define AR_NIC_REQMON_DLA_EVENT_CNTR_PR_ALLOC_PASS                  	0x4ull
#define AR_NIC_REQMON_DLA_EVENT_CNTR_PR_ALLOC_FAIL                  	0x5ull
#define AR_NIC_REQMON_DLA_EVENT_CNTR_HDR_PERR                       	0x6ull
#define AR_NIC_REQMON_DLA_EVENT_CNTR_DATA_MBE                       	0x7ull
#define AR_NIC_REQMON_DLA_EVENT_CNTR_FIFO_HDR_MBE                   	0x8ull
#define AR_NIC_REQMON_DLA_EVENT_CNTR_FIFO_ENQ_PKT                   	0x9ull
#define AR_NIC_REQMON_DLA_EVENT_CNTR_LO_CD_ENQ                      	0xaull
#define AR_NIC_REQMON_DLA_EVENT_CNTR_HI_CD_ENQ                      	0xbull
#define AR_NIC_REQMON_DLA_EVENT_CNTR_PR_ENQ                         	0xcull
#define AR_NIC_REQMON_DLA_EVENT_CNTR_FMA_PKT_ERR                    	0xdull
#define AR_NIC_REQMON_DLA_EVENT_CNTR_TARB_STALLED                   	0xeull
#define AR_NIC_REQMON_DLA_EVENT_CNTR_RESERVED15                     	0xfull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_REQ0_PKT                       	0x0ull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_REQ0_FLIT                      	0x1ull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_REQ0_STALL                     	0x2ull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_REQ0_BLOCK                     	0x3ull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_REQ1_PKT                       	0x4ull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_REQ1_STALL                     	0x5ull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_REQ1_BLOCK                     	0x6ull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_RSP0_PKT                       	0x7ull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_RSP0_FLIT                      	0x8ull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_RSP0_BLOCK                     	0x9ull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_RSP1_PKT                       	0xaull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_RSP1_FLIT                      	0xbull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_RSP1_BLOCK                     	0xcull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_AMO_DONE                       	0xdull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_AMO_HIT                        	0xeull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_AMO_MISS                       	0xfull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_STALL_MATCH                    	0x10ull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_STALL_FLUSH                    	0x11ull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_STALL_FULL                     	0x12ull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_STALL_ORDERED                  	0x13ull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_FILL_RSP                       	0x14ull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_INVALIDATE                     	0x15ull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_ERR_REQ_PARITY                 	0x16ull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_ERR_REQ_SBE                    	0x17ull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_ERR_REQ_MBE                    	0x18ull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_ERR_RSP_PARITY                 	0x19ull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_ERR_RSP_SBE                    	0x1aull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_DATASTORE_WR_POISON            	0x1bull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_DATASTORE_RD_POISON            	0x1cull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_ERR_REQLIST_SBE                	0x1dull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_ERR_REQLIST_MBE                	0x1eull
#define AR_NIC_REQMON_AMO_EVENT_CNTR_TIMEOUT_ARM                    	0x1full
#define AR_NIC_REQMON_WC_EVENT_CNTR_RAT_GETRESP                     	0x0ull
#define AR_NIC_REQMON_WC_EVENT_CNTR_PARB_PUT                        	0x1ull
#define AR_NIC_REQMON_WC_EVENT_CNTR_WC_IN                           	0x2ull
#define AR_NIC_REQMON_WC_EVENT_CNTR_WC_OUT                          	0x3ull
#define AR_NIC_REQMON_WC_EVENT_CNTR_BUF0_ALLOCATION                 	0x4ull
#define AR_NIC_REQMON_WC_EVENT_CNTR_BUF0_COMBINE                    	0x5ull
#define AR_NIC_REQMON_WC_EVENT_CNTR_BUF0_EVICTION                   	0x6ull
#define AR_NIC_REQMON_WC_EVENT_CNTR_BUF1_ALLOCATION                 	0x7ull
#define AR_NIC_REQMON_WC_EVENT_CNTR_BUF1_COMBINE                    	0x8ull
#define AR_NIC_REQMON_WC_EVENT_CNTR_BUF1_EVICTION                   	0x9ull
#define AR_NIC_REQMON_WC_EVENT_CNTR_RESERVED10                      	0xaull
#define AR_NIC_REQMON_WC_EVENT_CNTR_TAG_PBE                         	0xbull
#define AR_NIC_REQMON_WC_EVENT_CNTR_NTWK_RSP_HDR_PBE                	0xcull
#define AR_NIC_REQMON_WC_EVENT_CNTR_RSPIN0_HDR_PBE                  	0xdull
#define AR_NIC_REQMON_WC_EVENT_CNTR_RSPIN1_HDR_PBE                  	0xeull
#define AR_NIC_REQMON_WC_EVENT_CNTR_BUFFER_TIMEOUT                  	0xfull
#define AR_NIC_RSPMON_EVENT_CNTR_RSPMON                             	0x0ull
#define AR_NIC_RSPMON_EVENT_CNTR_CQ                                 	0x10ull
#define AR_NIC_RSPMON_EVENT_CNTR_RMT                                	0x120ull
#define AR_NIC_RSPMON_EVENT_CNTR_IOMMU                              	0x1d0ull
#define AR_NIC_RSPMON_EVENT_CNTR_PARB                               	0x250ull
#define AR_NIC_RSPMON_EVENT_CNTR_NPT                                	0x310ull
#define AR_NIC_RSPMON_RSPMON_EVENT_CNTR_TRIGGER0                    	0x0ull
#define AR_NIC_RSPMON_RSPMON_EVENT_CNTR_TRIGGER1                    	0x1ull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_SSID                            	0x0ull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_BTE                             	0x1ull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_DLA                             	0x2ull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_RMT                             	0x3ull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_FMA                             	0x4ull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_SSID_STALLED                    	0x5ull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_BTE_STALLED                     	0x6ull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_DLA_STALLED                     	0x7ull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_RMT_STALLED                     	0x8ull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_SSID_BLOCKED                    	0x9ull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_BTE_BLOCKED                     	0xaull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_DLA_BLOCKED                     	0xbull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_RMT_BLOCKED                     	0xcull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_SSID_DROPPED                    	0xdull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_BTE_DROPPED                     	0xeull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_DLA_DROPPED                     	0xfull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_RMT_DROPPED                     	0x10ull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_NPT_PKT                         	0x11ull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_NPT_FLIT                        	0x12ull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_NPT_STALLED                     	0x13ull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_DESC_TBL_SBE0                   	0x14ull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_DESC_TBL_SBE1                   	0x15ull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_DESC_TBL_SBE2                   	0x16ull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_DESC_TBL_SBE3                   	0x17ull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_DESC_TBL_MBE0                   	0x18ull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_DESC_TBL_MBE1                   	0x19ull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_DESC_TBL_MBE2                   	0x1aull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_DESC_TBL_MBE3                   	0x1bull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_RMT_INPUT_RMT_DATA_PARITY_ERR   	0x1cull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_RMT_INPUT_EVENT_DATA_PARITY_ERR 	0x1dull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_DLA_INPUT_EVENT_DATA_PARITY_ERR 	0x1eull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_BTE_INPUT_EVENT_DATA_PARITY_ERR 	0x1full
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_SSID_INPUT_EVENT_DATA_PARITY_ERR	0x20ull
#define AR_NIC_RSPMON_CQ_EVENT_CNTR_TRANS_CMP_Q_PARITY_ERR          	0x21ull
#define AR_NIC_RSPMON_RMT_EVENT_CNTR_INQ_PARITY                     	0x0ull
#define AR_NIC_RSPMON_RMT_EVENT_CNTR_PAYLOAD_SBE                    	0x1ull
#define AR_NIC_RSPMON_RMT_EVENT_CNTR_PAYLOAD_MBE                    	0x2ull
#define AR_NIC_RSPMON_RMT_EVENT_CNTR_SEQ_TBL_SBE                    	0x3ull
#define AR_NIC_RSPMON_RMT_EVENT_CNTR_SEQ_TBL_MBE                    	0x4ull
#define AR_NIC_RSPMON_RMT_EVENT_CNTR_DESC_TBL_SBE                   	0x5ull
#define AR_NIC_RSPMON_RMT_EVENT_CNTR_DESC_TBL_MBE                   	0x6ull
#define AR_NIC_RSPMON_RMT_EVENT_CNTR_UNDELIVERABLE_CQE              	0x7ull
#define AR_NIC_RSPMON_RMT_EVENT_CNTR_PUT_CAM_FILLS                  	0x8ull
#define AR_NIC_RSPMON_RMT_EVENT_CNTR_PUT_CAM_MISSES                 	0x9ull
#define AR_NIC_RSPMON_RMT_EVENT_CNTR_PUT_CAM_EVICTS                 	0xaull
#define AR_NIC_RSPMON_RMT_EVENT_CNTR_PUT_CAM_HITS                   	0xbull
#define AR_NIC_RSPMON_RMT_EVENT_CNTR_PUT_MBE_EVICTS                 	0xcull
#define AR_NIC_RSPMON_RMT_EVENT_CNTR_PUT_TIMEOUTS                   	0xdull
#define AR_NIC_RSPMON_RMT_EVENT_CNTR_RCV_COMPLETES                  	0xeull
#define AR_NIC_RSPMON_RMT_EVENT_CNTR_SEND_CAM_FILLS                 	0xfull
#define AR_NIC_RSPMON_RMT_EVENT_CNTR_SEND_CAM_MISSES                	0x10ull
#define AR_NIC_RSPMON_RMT_EVENT_CNTR_SEND_CAM_EVICTS                	0x11ull
#define AR_NIC_RSPMON_RMT_EVENT_CNTR_SEND_CAM_HITS                  	0x12ull
#define AR_NIC_RSPMON_RMT_EVENT_CNTR_SEND_MBE_EVICTS                	0x13ull
#define AR_NIC_RSPMON_RMT_EVENT_CNTR_SEND_TIMEOUTS                  	0x14ull
#define AR_NIC_RSPMON_RMT_EVENT_CNTR_ABORTS                         	0x15ull
#define AR_NIC_RSPMON_IOMMU_EVENT_CNTR_IDLE                         	0x0ull
#define AR_NIC_RSPMON_IOMMU_EVENT_CNTR_TR_RCVD                      	0x1ull
#define AR_NIC_RSPMON_IOMMU_EVENT_CNTR_TR_1LVL_RSP                  	0x2ull
#define AR_NIC_RSPMON_IOMMU_EVENT_CNTR_TR_2LVL_RSP                  	0x3ull
#define AR_NIC_RSPMON_IOMMU_EVENT_CNTR_IOPF_PTE                     	0x4ull
#define AR_NIC_RSPMON_IOMMU_EVENT_CNTR_IOPF_TC                      	0x5ull
#define AR_NIC_RSPMON_IOMMU_EVENT_CNTR_IOPF_ACCESS                  	0x6ull
#define AR_NIC_RSPMON_IOMMU_EVENT_CNTR_PTEC_HIT                     	0x7ull
#define AR_NIC_RSPMON_IOMMU_EVENT_CNTR_PTEC_MISS                    	0x8ull
#define AR_NIC_RSPMON_IOMMU_EVENT_CNTR_PTEC_EVICT                   	0x9ull
#define AR_NIC_RSPMON_IOMMU_EVENT_CNTR_PTEC_INVAL                   	0xaull
#define AR_NIC_RSPMON_IOMMU_EVENT_CNTR_STALL_PTEC_CA                	0xbull
#define AR_NIC_RSPMON_IOMMU_EVENT_CNTR_OFB_CA                       	0xcull
#define AR_NIC_RSPMON_IOMMU_EVENT_CNTR_PTE_RF                       	0xdull
#define AR_NIC_RSPMON_IOMMU_EVENT_CNTR_PTE_INV                      	0xeull
#define AR_NIC_RSPMON_IOMMU_EVENT_CNTR_EVENTS                       	0xfull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_BTE_RD_PKTS                   	0x0ull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_BTE_RD_FLITS                  	0x1ull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_BTE_RD_BLOCKED                	0x2ull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_BTE_WR_PKTS                   	0x3ull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_BTE_WR_FLITS                  	0x4ull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_BTE_WR_BLOCKED                	0x5ull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_AMO_PKTS                      	0x6ull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_AMO_FLITS                     	0x7ull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_AMO_BLOCKED                   	0x8ull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_WC_PKTS                       	0x9ull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_WC_FLITS                      	0xaull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_WC_BLOCKED                    	0xbull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_IOMMU_PKTS                    	0xcull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_IOMMU_FLITS                   	0xdull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_IOMMU_BLOCKED                 	0xeull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_DLA_PKTS                      	0xfull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_DLA_FLITS                     	0x10ull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_DLA_BLOCKED                   	0x11ull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_MAINT_PKTS                    	0x12ull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_MAINT_FLITS                   	0x13ull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_MAINT_BLOCKED                 	0x14ull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_PI_PKTS                       	0x15ull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_PI_FLITS                      	0x16ull
#define AR_NIC_RSPMON_PARB_EVENT_CNTR_PI_STALLED                    	0x17ull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_CQ_PKTS                        	0x0ull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_CQ_FLITS                       	0x1ull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_CQ_BLOCKED                     	0x2ull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_RMT_PKTS                       	0x3ull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_RMT_FLITS                      	0x4ull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_RMT_BLOCKED                    	0x5ull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_INPUT_PKTS                     	0x6ull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_INPUT_FLITS                    	0x7ull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_INPUT_STALLED                  	0x8ull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_NP_PKTS                        	0x9ull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_NP_FLITS                       	0xaull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_NP_BLOCKED                     	0xbull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_P_PKTS                         	0xcull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_P_BLOCKED                      	0xdull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_CE_PKTS                        	0xeull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_CE_BLOCKED                     	0xfull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_NL_PKTS                        	0x10ull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_NL_FLITS                       	0x11ull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_NL_STALLED                     	0x12ull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_RSP_PKT                        	0x13ull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_RSP_FLIT                       	0x14ull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_PKT_IGNORE                     	0x15ull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_PKT_DROP                       	0x16ull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_PKT_CW                         	0x17ull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_ERR_SBE                        	0x18ull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_ERR_MBE                        	0x19ull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_REQ_PE                         	0x1aull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_RSP_PE                         	0x1bull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_RSP_SBE                        	0x1cull
#define AR_NIC_RSPMON_NPT_EVENT_CNTR_RSP_MBE                        	0x1dull

#endif
