/******************************************************************************
 * COPYRIGHT CRAY INC. ar_nt_mmrs_h.h
 * FILE: ar_nt_mmrs_h.h
 * Created by v2h.c on Wed Oct  8 14:39:04 2014
 ******************************************************************************/

#ifndef _AR_NT_MMRS_H_H_
#define _AR_NT_MMRS_H_H_

#ifdef __GNUC__
#define _unused __attribute__((unused))
#else
#define _unused
#endif

#ifndef _GENERIC_MMRD_T_
#define _GENERIC_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint64_t _mask;		/* Field bit mask */
} generic_mmrd_t;
#endif

#ifndef _ERRCAT_MMRD_T_
#define _ERRCAT_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint32_t _ec;		/* Field error category */
} errcat_mmrd_t;
#endif

#ifndef _GENERIC_MMR_T_
#define _GENERIC_MMR_T_
typedef struct {
	char* _name;		/* MMR name */
	uint64_t _addr;		/* MMR address */
	int _size;		/* Size in bytes of MMR */
	int _depth;		/* Number of MMR instances */
	const generic_mmrd_t *_info;	/* MMR detail */
} generic_mmr_t;
#endif

static const generic_mmr_t* _ar_nt_mmrs[] _unused;	/* NT Array */

/*
 *  AR NT MMR DETAIL DECLARATIONS
 */
static const generic_mmrd_t _ar_rtr_inq_cfg_degrade_diag_detail[] = {
    { "LMON_SUBSWITCH_SEL", AR_RTR_INQ_CFG_DEGRADE_DIAG_LMON_SUBSWITCH_SEL_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_LMON_SUBSWITCH_SEL_MASK },
    { "LMON_COLBUF_SEL", AR_RTR_INQ_CFG_DEGRADE_DIAG_LMON_COLBUF_SEL_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_LMON_COLBUF_SEL_MASK },
    { "LMON_INQ_SEL", AR_RTR_INQ_CFG_DEGRADE_DIAG_LMON_INQ_SEL_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_LMON_INQ_SEL_MASK },
    { "LMON_EN", AR_RTR_INQ_CFG_DEGRADE_DIAG_LMON_EN_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_LMON_EN_MASK },
    { "LMON_SEL", AR_RTR_INQ_CFG_DEGRADE_DIAG_LMON_SEL_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_LMON_SEL_MASK },
    { "COLBUF_CRDT_RESET", AR_RTR_INQ_CFG_DEGRADE_DIAG_COLBUF_CRDT_RESET_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_COLBUF_CRDT_RESET_MASK },
    { "COLBUF_GC_MODE", AR_RTR_INQ_CFG_DEGRADE_DIAG_COLBUF_GC_MODE_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_COLBUF_GC_MODE_MASK },
    { "START_LINK_ALIVE_DISCOVERY", AR_RTR_INQ_CFG_DEGRADE_DIAG_START_LINK_ALIVE_DISCOVERY_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_START_LINK_ALIVE_DISCOVERY_MASK },
    { "DISABLE_LINK_ALIVE_DISCOVERY", AR_RTR_INQ_CFG_DEGRADE_DIAG_DISABLE_LINK_ALIVE_DISCOVERY_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_DISABLE_LINK_ALIVE_DISCOVERY_MASK },
    { "LINK_ALIVE_DISC_CH_CNT", AR_RTR_INQ_CFG_DEGRADE_DIAG_LINK_ALIVE_DISC_CH_CNT_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_LINK_ALIVE_DISC_CH_CNT_MASK },
    { "ENABLE_VC_SIGNATURE", AR_RTR_INQ_CFG_DEGRADE_DIAG_ENABLE_VC_SIGNATURE_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_ENABLE_VC_SIGNATURE_MASK },
    { "DISABLE_BYPASS", AR_RTR_INQ_CFG_DEGRADE_DIAG_DISABLE_BYPASS_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_DISABLE_BYPASS_MASK },
    { "ANY_VC_UNDER_TEST", AR_RTR_INQ_CFG_DEGRADE_DIAG_ANY_VC_UNDER_TEST_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_ANY_VC_UNDER_TEST_MASK },
    { "VC_UNDER_TEST", AR_RTR_INQ_CFG_DEGRADE_DIAG_VC_UNDER_TEST_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_VC_UNDER_TEST_MASK },
    { "SINGLE_STEP_DFIFO_MODE", AR_RTR_INQ_CFG_DEGRADE_DIAG_SINGLE_STEP_DFIFO_MODE_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_SINGLE_STEP_DFIFO_MODE_MASK },
    { "SINGLE_STEP_DFIFO_A_FLIT", AR_RTR_INQ_CFG_DEGRADE_DIAG_SINGLE_STEP_DFIFO_A_FLIT_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_SINGLE_STEP_DFIFO_A_FLIT_MASK },
    { "SINGLE_STEP_DFIFO_ABSORB", AR_RTR_INQ_CFG_DEGRADE_DIAG_SINGLE_STEP_DFIFO_ABSORB_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_SINGLE_STEP_DFIFO_ABSORB_MASK },
    { "FIRST_FLIT_RELEASE_DAMQ", AR_RTR_INQ_CFG_DEGRADE_DIAG_FIRST_FLIT_RELEASE_DAMQ_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_FIRST_FLIT_RELEASE_DAMQ_MASK },
    { "STOP_DAMQ_SEND", AR_RTR_INQ_CFG_DEGRADE_DIAG_STOP_DAMQ_SEND_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_STOP_DAMQ_SEND_MASK },
    { "STOP_DAMQ_ACCEPT", AR_RTR_INQ_CFG_DEGRADE_DIAG_STOP_DAMQ_ACCEPT_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_STOP_DAMQ_ACCEPT_MASK },
    { "RESET_INQ", AR_RTR_INQ_CFG_DEGRADE_DIAG_RESET_INQ_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_RESET_INQ_MASK },
    { "STATIC_LINK_LIST_MODE", AR_RTR_INQ_CFG_DEGRADE_DIAG_STATIC_LINK_LIST_MODE_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_STATIC_LINK_LIST_MODE_MASK },
    { "INQ_ERROR_PAUSE_DAMQ", AR_RTR_INQ_CFG_DEGRADE_DIAG_INQ_ERROR_PAUSE_DAMQ_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_INQ_ERROR_PAUSE_DAMQ_MASK },
    { "CHECKBYTE", AR_RTR_INQ_CFG_DEGRADE_DIAG_CHECKBYTE_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_CHECKBYTE_MASK },
    { "TRIGGERED", AR_RTR_INQ_CFG_DEGRADE_DIAG_TRIGGERED_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_TRIGGERED_MASK },
    { "ERR_INJ_MODE", AR_RTR_INQ_CFG_DEGRADE_DIAG_ERR_INJ_MODE_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_ERR_INJ_MODE_MASK },
    { "ERR_INJ_ENABLE", AR_RTR_INQ_CFG_DEGRADE_DIAG_ERR_INJ_ENABLE_BP, AR_RTR_INQ_CFG_DEGRADE_DIAG_ERR_INJ_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_cfg_fifo_rowbuf_crdt_limit_detail[] = {
    { "DFIFO_CRDT_LIMIT", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_DFIFO_CRDT_LIMIT_BP, AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_DFIFO_CRDT_LIMIT_MASK },
    { "OFIFO_CRDT_LIMIT", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_OFIFO_CRDT_LIMIT_BP, AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_OFIFO_CRDT_LIMIT_MASK },
    { "RFIFO_CRDT_LIMIT", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_RFIFO_CRDT_LIMIT_BP, AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_RFIFO_CRDT_LIMIT_MASK },
    { "ROWBUF_VC7_CRDT_LIMIT", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_ROWBUF_VC7_CRDT_LIMIT_BP, AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_ROWBUF_VC7_CRDT_LIMIT_MASK },
    { "ROWBUF_VC6_CRDT_LIMIT", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_ROWBUF_VC6_CRDT_LIMIT_BP, AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_ROWBUF_VC6_CRDT_LIMIT_MASK },
    { "ROWBUF_VC5_CRDT_LIMIT", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_ROWBUF_VC5_CRDT_LIMIT_BP, AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_ROWBUF_VC5_CRDT_LIMIT_MASK },
    { "ROWBUF_VC4_CRDT_LIMIT", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_ROWBUF_VC4_CRDT_LIMIT_BP, AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_ROWBUF_VC4_CRDT_LIMIT_MASK },
    { "ROWBUF_VC3_CRDT_LIMIT", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_ROWBUF_VC3_CRDT_LIMIT_BP, AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_ROWBUF_VC3_CRDT_LIMIT_MASK },
    { "ROWBUF_VC2_CRDT_LIMIT", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_ROWBUF_VC2_CRDT_LIMIT_BP, AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_ROWBUF_VC2_CRDT_LIMIT_MASK },
    { "ROWBUF_VC1_CRDT_LIMIT", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_ROWBUF_VC1_CRDT_LIMIT_BP, AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_ROWBUF_VC1_CRDT_LIMIT_MASK },
    { "ROWBUF_VC0_CRDT_LIMIT", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_ROWBUF_VC0_CRDT_LIMIT_BP, AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_ROWBUF_VC0_CRDT_LIMIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_cfg_fifo_rowbuf_crdts_detail[] = {
    { "DFIFO_CRDTS", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS_DFIFO_CRDTS_BP, AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS_DFIFO_CRDTS_MASK },
    { "OFIFO_CRDTS", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS_OFIFO_CRDTS_BP, AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS_OFIFO_CRDTS_MASK },
    { "RFIFO_CRDTS", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS_RFIFO_CRDTS_BP, AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS_RFIFO_CRDTS_MASK },
    { "ROWBUF_VC7_CRDTS", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS_ROWBUF_VC7_CRDTS_BP, AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS_ROWBUF_VC7_CRDTS_MASK },
    { "ROWBUF_VC6_CRDTS", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS_ROWBUF_VC6_CRDTS_BP, AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS_ROWBUF_VC6_CRDTS_MASK },
    { "ROWBUF_VC5_CRDTS", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS_ROWBUF_VC5_CRDTS_BP, AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS_ROWBUF_VC5_CRDTS_MASK },
    { "ROWBUF_VC4_CRDTS", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS_ROWBUF_VC4_CRDTS_BP, AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS_ROWBUF_VC4_CRDTS_MASK },
    { "ROWBUF_VC3_CRDTS", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS_ROWBUF_VC3_CRDTS_BP, AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS_ROWBUF_VC3_CRDTS_MASK },
    { "ROWBUF_VC2_CRDTS", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS_ROWBUF_VC2_CRDTS_BP, AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS_ROWBUF_VC2_CRDTS_MASK },
    { "ROWBUF_VC1_CRDTS", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS_ROWBUF_VC1_CRDTS_BP, AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS_ROWBUF_VC1_CRDTS_MASK },
    { "ROWBUF_VC0_CRDTS", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS_ROWBUF_VC0_CRDTS_BP, AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS_ROWBUF_VC0_CRDTS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_cfg_damq_vc04_detail[] = {
    { "FLIT_IDX_PAR_VC4", AR_RTR_INQ_CFG_DAMQ_VC04_FLIT_IDX_PAR_VC4_BP, AR_RTR_INQ_CFG_DAMQ_VC04_FLIT_IDX_PAR_VC4_MASK },
    { "FLIT_IDX_PAR_VC0", AR_RTR_INQ_CFG_DAMQ_VC04_FLIT_IDX_PAR_VC0_BP, AR_RTR_INQ_CFG_DAMQ_VC04_FLIT_IDX_PAR_VC0_MASK },
    { "VALID_BLK_CNT_PAR_VC4", AR_RTR_INQ_CFG_DAMQ_VC04_VALID_BLK_CNT_PAR_VC4_BP, AR_RTR_INQ_CFG_DAMQ_VC04_VALID_BLK_CNT_PAR_VC4_MASK },
    { "VALID_BLK_CNT_PAR_VC0", AR_RTR_INQ_CFG_DAMQ_VC04_VALID_BLK_CNT_PAR_VC0_BP, AR_RTR_INQ_CFG_DAMQ_VC04_VALID_BLK_CNT_PAR_VC0_MASK },
    { "TAIL_BLK_PTR_PAR_VC4", AR_RTR_INQ_CFG_DAMQ_VC04_TAIL_BLK_PTR_PAR_VC4_BP, AR_RTR_INQ_CFG_DAMQ_VC04_TAIL_BLK_PTR_PAR_VC4_MASK },
    { "TAIL_BLK_PTR_PAR_VC0", AR_RTR_INQ_CFG_DAMQ_VC04_TAIL_BLK_PTR_PAR_VC0_BP, AR_RTR_INQ_CFG_DAMQ_VC04_TAIL_BLK_PTR_PAR_VC0_MASK },
    { "HEAD_BLK_PTR_PAR_VC4", AR_RTR_INQ_CFG_DAMQ_VC04_HEAD_BLK_PTR_PAR_VC4_BP, AR_RTR_INQ_CFG_DAMQ_VC04_HEAD_BLK_PTR_PAR_VC4_MASK },
    { "HEAD_BLK_PTR_PAR_VC0", AR_RTR_INQ_CFG_DAMQ_VC04_HEAD_BLK_PTR_PAR_VC0_BP, AR_RTR_INQ_CFG_DAMQ_VC04_HEAD_BLK_PTR_PAR_VC0_MASK },
    { "TAIL_FLIT_IDX_VC4", AR_RTR_INQ_CFG_DAMQ_VC04_TAIL_FLIT_IDX_VC4_BP, AR_RTR_INQ_CFG_DAMQ_VC04_TAIL_FLIT_IDX_VC4_MASK },
    { "TAIL_FLIT_IDX_VC0", AR_RTR_INQ_CFG_DAMQ_VC04_TAIL_FLIT_IDX_VC0_BP, AR_RTR_INQ_CFG_DAMQ_VC04_TAIL_FLIT_IDX_VC0_MASK },
    { "HEAD_FLIT_IDX_VC4", AR_RTR_INQ_CFG_DAMQ_VC04_HEAD_FLIT_IDX_VC4_BP, AR_RTR_INQ_CFG_DAMQ_VC04_HEAD_FLIT_IDX_VC4_MASK },
    { "HEAD_FLIT_IDX_VC0", AR_RTR_INQ_CFG_DAMQ_VC04_HEAD_FLIT_IDX_VC0_BP, AR_RTR_INQ_CFG_DAMQ_VC04_HEAD_FLIT_IDX_VC0_MASK },
    { "VALID_BLK_CNT_VC4", AR_RTR_INQ_CFG_DAMQ_VC04_VALID_BLK_CNT_VC4_BP, AR_RTR_INQ_CFG_DAMQ_VC04_VALID_BLK_CNT_VC4_MASK },
    { "VALID_BLK_CNT_VC0", AR_RTR_INQ_CFG_DAMQ_VC04_VALID_BLK_CNT_VC0_BP, AR_RTR_INQ_CFG_DAMQ_VC04_VALID_BLK_CNT_VC0_MASK },
    { "TAIL_BLK_PTR_VC4", AR_RTR_INQ_CFG_DAMQ_VC04_TAIL_BLK_PTR_VC4_BP, AR_RTR_INQ_CFG_DAMQ_VC04_TAIL_BLK_PTR_VC4_MASK },
    { "TAIL_BLK_PTR_VC0", AR_RTR_INQ_CFG_DAMQ_VC04_TAIL_BLK_PTR_VC0_BP, AR_RTR_INQ_CFG_DAMQ_VC04_TAIL_BLK_PTR_VC0_MASK },
    { "HEAD_BLK_PTR_VC4", AR_RTR_INQ_CFG_DAMQ_VC04_HEAD_BLK_PTR_VC4_BP, AR_RTR_INQ_CFG_DAMQ_VC04_HEAD_BLK_PTR_VC4_MASK },
    { "HEAD_BLK_PTR_VC0", AR_RTR_INQ_CFG_DAMQ_VC04_HEAD_BLK_PTR_VC0_BP, AR_RTR_INQ_CFG_DAMQ_VC04_HEAD_BLK_PTR_VC0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_cfg_damq_vc15_detail[] = {
    { "FLIT_IDX_PAR_VC5", AR_RTR_INQ_CFG_DAMQ_VC15_FLIT_IDX_PAR_VC5_BP, AR_RTR_INQ_CFG_DAMQ_VC15_FLIT_IDX_PAR_VC5_MASK },
    { "FLIT_IDX_PAR_VC1", AR_RTR_INQ_CFG_DAMQ_VC15_FLIT_IDX_PAR_VC1_BP, AR_RTR_INQ_CFG_DAMQ_VC15_FLIT_IDX_PAR_VC1_MASK },
    { "VALID_BLK_CNT_PAR_VC5", AR_RTR_INQ_CFG_DAMQ_VC15_VALID_BLK_CNT_PAR_VC5_BP, AR_RTR_INQ_CFG_DAMQ_VC15_VALID_BLK_CNT_PAR_VC5_MASK },
    { "VALID_BLK_CNT_PAR_VC1", AR_RTR_INQ_CFG_DAMQ_VC15_VALID_BLK_CNT_PAR_VC1_BP, AR_RTR_INQ_CFG_DAMQ_VC15_VALID_BLK_CNT_PAR_VC1_MASK },
    { "TAIL_BLK_PTR_PAR_VC5", AR_RTR_INQ_CFG_DAMQ_VC15_TAIL_BLK_PTR_PAR_VC5_BP, AR_RTR_INQ_CFG_DAMQ_VC15_TAIL_BLK_PTR_PAR_VC5_MASK },
    { "TAIL_BLK_PTR_PAR_VC1", AR_RTR_INQ_CFG_DAMQ_VC15_TAIL_BLK_PTR_PAR_VC1_BP, AR_RTR_INQ_CFG_DAMQ_VC15_TAIL_BLK_PTR_PAR_VC1_MASK },
    { "HEAD_BLK_PTR_PAR_VC5", AR_RTR_INQ_CFG_DAMQ_VC15_HEAD_BLK_PTR_PAR_VC5_BP, AR_RTR_INQ_CFG_DAMQ_VC15_HEAD_BLK_PTR_PAR_VC5_MASK },
    { "HEAD_BLK_PTR_PAR_VC1", AR_RTR_INQ_CFG_DAMQ_VC15_HEAD_BLK_PTR_PAR_VC1_BP, AR_RTR_INQ_CFG_DAMQ_VC15_HEAD_BLK_PTR_PAR_VC1_MASK },
    { "TAIL_FLIT_IDX_VC5", AR_RTR_INQ_CFG_DAMQ_VC15_TAIL_FLIT_IDX_VC5_BP, AR_RTR_INQ_CFG_DAMQ_VC15_TAIL_FLIT_IDX_VC5_MASK },
    { "TAIL_FLIT_IDX_VC1", AR_RTR_INQ_CFG_DAMQ_VC15_TAIL_FLIT_IDX_VC1_BP, AR_RTR_INQ_CFG_DAMQ_VC15_TAIL_FLIT_IDX_VC1_MASK },
    { "HEAD_FLIT_IDX_VC5", AR_RTR_INQ_CFG_DAMQ_VC15_HEAD_FLIT_IDX_VC5_BP, AR_RTR_INQ_CFG_DAMQ_VC15_HEAD_FLIT_IDX_VC5_MASK },
    { "HEAD_FLIT_IDX_VC1", AR_RTR_INQ_CFG_DAMQ_VC15_HEAD_FLIT_IDX_VC1_BP, AR_RTR_INQ_CFG_DAMQ_VC15_HEAD_FLIT_IDX_VC1_MASK },
    { "VALID_BLK_CNT_VC5", AR_RTR_INQ_CFG_DAMQ_VC15_VALID_BLK_CNT_VC5_BP, AR_RTR_INQ_CFG_DAMQ_VC15_VALID_BLK_CNT_VC5_MASK },
    { "VALID_BLK_CNT_VC1", AR_RTR_INQ_CFG_DAMQ_VC15_VALID_BLK_CNT_VC1_BP, AR_RTR_INQ_CFG_DAMQ_VC15_VALID_BLK_CNT_VC1_MASK },
    { "TAIL_BLK_PTR_VC5", AR_RTR_INQ_CFG_DAMQ_VC15_TAIL_BLK_PTR_VC5_BP, AR_RTR_INQ_CFG_DAMQ_VC15_TAIL_BLK_PTR_VC5_MASK },
    { "TAIL_BLK_PTR_VC1", AR_RTR_INQ_CFG_DAMQ_VC15_TAIL_BLK_PTR_VC1_BP, AR_RTR_INQ_CFG_DAMQ_VC15_TAIL_BLK_PTR_VC1_MASK },
    { "HEAD_BLK_PTR_VC5", AR_RTR_INQ_CFG_DAMQ_VC15_HEAD_BLK_PTR_VC5_BP, AR_RTR_INQ_CFG_DAMQ_VC15_HEAD_BLK_PTR_VC5_MASK },
    { "HEAD_BLK_PTR_VC1", AR_RTR_INQ_CFG_DAMQ_VC15_HEAD_BLK_PTR_VC1_BP, AR_RTR_INQ_CFG_DAMQ_VC15_HEAD_BLK_PTR_VC1_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_cfg_damq_vc26_detail[] = {
    { "FLIT_IDX_PAR_VC6", AR_RTR_INQ_CFG_DAMQ_VC26_FLIT_IDX_PAR_VC6_BP, AR_RTR_INQ_CFG_DAMQ_VC26_FLIT_IDX_PAR_VC6_MASK },
    { "FLIT_IDX_PAR_VC2", AR_RTR_INQ_CFG_DAMQ_VC26_FLIT_IDX_PAR_VC2_BP, AR_RTR_INQ_CFG_DAMQ_VC26_FLIT_IDX_PAR_VC2_MASK },
    { "VALID_BLK_CNT_PAR_VC6", AR_RTR_INQ_CFG_DAMQ_VC26_VALID_BLK_CNT_PAR_VC6_BP, AR_RTR_INQ_CFG_DAMQ_VC26_VALID_BLK_CNT_PAR_VC6_MASK },
    { "VALID_BLK_CNT_PAR_VC2", AR_RTR_INQ_CFG_DAMQ_VC26_VALID_BLK_CNT_PAR_VC2_BP, AR_RTR_INQ_CFG_DAMQ_VC26_VALID_BLK_CNT_PAR_VC2_MASK },
    { "TAIL_BLK_PTR_PAR_VC6", AR_RTR_INQ_CFG_DAMQ_VC26_TAIL_BLK_PTR_PAR_VC6_BP, AR_RTR_INQ_CFG_DAMQ_VC26_TAIL_BLK_PTR_PAR_VC6_MASK },
    { "TAIL_BLK_PTR_PAR_VC2", AR_RTR_INQ_CFG_DAMQ_VC26_TAIL_BLK_PTR_PAR_VC2_BP, AR_RTR_INQ_CFG_DAMQ_VC26_TAIL_BLK_PTR_PAR_VC2_MASK },
    { "HEAD_BLK_PTR_PAR_VC6", AR_RTR_INQ_CFG_DAMQ_VC26_HEAD_BLK_PTR_PAR_VC6_BP, AR_RTR_INQ_CFG_DAMQ_VC26_HEAD_BLK_PTR_PAR_VC6_MASK },
    { "HEAD_BLK_PTR_PAR_VC2", AR_RTR_INQ_CFG_DAMQ_VC26_HEAD_BLK_PTR_PAR_VC2_BP, AR_RTR_INQ_CFG_DAMQ_VC26_HEAD_BLK_PTR_PAR_VC2_MASK },
    { "TAIL_FLIT_IDX_VC6", AR_RTR_INQ_CFG_DAMQ_VC26_TAIL_FLIT_IDX_VC6_BP, AR_RTR_INQ_CFG_DAMQ_VC26_TAIL_FLIT_IDX_VC6_MASK },
    { "TAIL_FLIT_IDX_VC2", AR_RTR_INQ_CFG_DAMQ_VC26_TAIL_FLIT_IDX_VC2_BP, AR_RTR_INQ_CFG_DAMQ_VC26_TAIL_FLIT_IDX_VC2_MASK },
    { "HEAD_FLIT_IDX_VC6", AR_RTR_INQ_CFG_DAMQ_VC26_HEAD_FLIT_IDX_VC6_BP, AR_RTR_INQ_CFG_DAMQ_VC26_HEAD_FLIT_IDX_VC6_MASK },
    { "HEAD_FLIT_IDX_VC2", AR_RTR_INQ_CFG_DAMQ_VC26_HEAD_FLIT_IDX_VC2_BP, AR_RTR_INQ_CFG_DAMQ_VC26_HEAD_FLIT_IDX_VC2_MASK },
    { "VALID_BLK_CNT_VC6", AR_RTR_INQ_CFG_DAMQ_VC26_VALID_BLK_CNT_VC6_BP, AR_RTR_INQ_CFG_DAMQ_VC26_VALID_BLK_CNT_VC6_MASK },
    { "VALID_BLK_CNT_VC2", AR_RTR_INQ_CFG_DAMQ_VC26_VALID_BLK_CNT_VC2_BP, AR_RTR_INQ_CFG_DAMQ_VC26_VALID_BLK_CNT_VC2_MASK },
    { "TAIL_BLK_PTR_VC6", AR_RTR_INQ_CFG_DAMQ_VC26_TAIL_BLK_PTR_VC6_BP, AR_RTR_INQ_CFG_DAMQ_VC26_TAIL_BLK_PTR_VC6_MASK },
    { "TAIL_BLK_PTR_VC2", AR_RTR_INQ_CFG_DAMQ_VC26_TAIL_BLK_PTR_VC2_BP, AR_RTR_INQ_CFG_DAMQ_VC26_TAIL_BLK_PTR_VC2_MASK },
    { "HEAD_BLK_PTR_VC6", AR_RTR_INQ_CFG_DAMQ_VC26_HEAD_BLK_PTR_VC6_BP, AR_RTR_INQ_CFG_DAMQ_VC26_HEAD_BLK_PTR_VC6_MASK },
    { "HEAD_BLK_PTR_VC2", AR_RTR_INQ_CFG_DAMQ_VC26_HEAD_BLK_PTR_VC2_BP, AR_RTR_INQ_CFG_DAMQ_VC26_HEAD_BLK_PTR_VC2_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_cfg_damq_vc37_detail[] = {
    { "FLIT_IDX_PAR_VC7", AR_RTR_INQ_CFG_DAMQ_VC37_FLIT_IDX_PAR_VC7_BP, AR_RTR_INQ_CFG_DAMQ_VC37_FLIT_IDX_PAR_VC7_MASK },
    { "FLIT_IDX_PAR_VC3", AR_RTR_INQ_CFG_DAMQ_VC37_FLIT_IDX_PAR_VC3_BP, AR_RTR_INQ_CFG_DAMQ_VC37_FLIT_IDX_PAR_VC3_MASK },
    { "VALID_BLK_CNT_PAR_VC7", AR_RTR_INQ_CFG_DAMQ_VC37_VALID_BLK_CNT_PAR_VC7_BP, AR_RTR_INQ_CFG_DAMQ_VC37_VALID_BLK_CNT_PAR_VC7_MASK },
    { "VALID_BLK_CNT_PAR_VC3", AR_RTR_INQ_CFG_DAMQ_VC37_VALID_BLK_CNT_PAR_VC3_BP, AR_RTR_INQ_CFG_DAMQ_VC37_VALID_BLK_CNT_PAR_VC3_MASK },
    { "TAIL_BLK_PTR_PAR_VC7", AR_RTR_INQ_CFG_DAMQ_VC37_TAIL_BLK_PTR_PAR_VC7_BP, AR_RTR_INQ_CFG_DAMQ_VC37_TAIL_BLK_PTR_PAR_VC7_MASK },
    { "TAIL_BLK_PTR_PAR_VC3", AR_RTR_INQ_CFG_DAMQ_VC37_TAIL_BLK_PTR_PAR_VC3_BP, AR_RTR_INQ_CFG_DAMQ_VC37_TAIL_BLK_PTR_PAR_VC3_MASK },
    { "HEAD_BLK_PTR_PAR_VC7", AR_RTR_INQ_CFG_DAMQ_VC37_HEAD_BLK_PTR_PAR_VC7_BP, AR_RTR_INQ_CFG_DAMQ_VC37_HEAD_BLK_PTR_PAR_VC7_MASK },
    { "HEAD_BLK_PTR_PAR_VC3", AR_RTR_INQ_CFG_DAMQ_VC37_HEAD_BLK_PTR_PAR_VC3_BP, AR_RTR_INQ_CFG_DAMQ_VC37_HEAD_BLK_PTR_PAR_VC3_MASK },
    { "TAIL_FLIT_IDX_VC7", AR_RTR_INQ_CFG_DAMQ_VC37_TAIL_FLIT_IDX_VC7_BP, AR_RTR_INQ_CFG_DAMQ_VC37_TAIL_FLIT_IDX_VC7_MASK },
    { "TAIL_FLIT_IDX_VC3", AR_RTR_INQ_CFG_DAMQ_VC37_TAIL_FLIT_IDX_VC3_BP, AR_RTR_INQ_CFG_DAMQ_VC37_TAIL_FLIT_IDX_VC3_MASK },
    { "HEAD_FLIT_IDX_VC7", AR_RTR_INQ_CFG_DAMQ_VC37_HEAD_FLIT_IDX_VC7_BP, AR_RTR_INQ_CFG_DAMQ_VC37_HEAD_FLIT_IDX_VC7_MASK },
    { "HEAD_FLIT_IDX_VC3", AR_RTR_INQ_CFG_DAMQ_VC37_HEAD_FLIT_IDX_VC3_BP, AR_RTR_INQ_CFG_DAMQ_VC37_HEAD_FLIT_IDX_VC3_MASK },
    { "VALID_BLK_CNT_VC7", AR_RTR_INQ_CFG_DAMQ_VC37_VALID_BLK_CNT_VC7_BP, AR_RTR_INQ_CFG_DAMQ_VC37_VALID_BLK_CNT_VC7_MASK },
    { "VALID_BLK_CNT_VC3", AR_RTR_INQ_CFG_DAMQ_VC37_VALID_BLK_CNT_VC3_BP, AR_RTR_INQ_CFG_DAMQ_VC37_VALID_BLK_CNT_VC3_MASK },
    { "TAIL_BLK_PTR_VC7", AR_RTR_INQ_CFG_DAMQ_VC37_TAIL_BLK_PTR_VC7_BP, AR_RTR_INQ_CFG_DAMQ_VC37_TAIL_BLK_PTR_VC7_MASK },
    { "TAIL_BLK_PTR_VC3", AR_RTR_INQ_CFG_DAMQ_VC37_TAIL_BLK_PTR_VC3_BP, AR_RTR_INQ_CFG_DAMQ_VC37_TAIL_BLK_PTR_VC3_MASK },
    { "HEAD_BLK_PTR_VC7", AR_RTR_INQ_CFG_DAMQ_VC37_HEAD_BLK_PTR_VC7_BP, AR_RTR_INQ_CFG_DAMQ_VC37_HEAD_BLK_PTR_VC7_MASK },
    { "HEAD_BLK_PTR_VC3", AR_RTR_INQ_CFG_DAMQ_VC37_HEAD_BLK_PTR_VC3_BP, AR_RTR_INQ_CFG_DAMQ_VC37_HEAD_BLK_PTR_VC3_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_cfg_damq_free_detail[] = {
    { "VALID_BLK_CNT_PAR_FREE", AR_RTR_INQ_CFG_DAMQ_FREE_VALID_BLK_CNT_PAR_FREE_BP, AR_RTR_INQ_CFG_DAMQ_FREE_VALID_BLK_CNT_PAR_FREE_MASK },
    { "TAIL_BLK_PTR_PAR_FREE", AR_RTR_INQ_CFG_DAMQ_FREE_TAIL_BLK_PTR_PAR_FREE_BP, AR_RTR_INQ_CFG_DAMQ_FREE_TAIL_BLK_PTR_PAR_FREE_MASK },
    { "HEAD_BLK_PTR_PAR_FREE", AR_RTR_INQ_CFG_DAMQ_FREE_HEAD_BLK_PTR_PAR_FREE_BP, AR_RTR_INQ_CFG_DAMQ_FREE_HEAD_BLK_PTR_PAR_FREE_MASK },
    { "VALID_BLK_CNT_FREE", AR_RTR_INQ_CFG_DAMQ_FREE_VALID_BLK_CNT_FREE_BP, AR_RTR_INQ_CFG_DAMQ_FREE_VALID_BLK_CNT_FREE_MASK },
    { "TAIL_BLK_PTR_FREE", AR_RTR_INQ_CFG_DAMQ_FREE_TAIL_BLK_PTR_FREE_BP, AR_RTR_INQ_CFG_DAMQ_FREE_TAIL_BLK_PTR_FREE_MASK },
    { "HEAD_BLK_PTR_FREE", AR_RTR_INQ_CFG_DAMQ_FREE_HEAD_BLK_PTR_FREE_BP, AR_RTR_INQ_CFG_DAMQ_FREE_HEAD_BLK_PTR_FREE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_cfg_damq_next_detail[] = {
    { "NXT_BLK_PTR_RD_WR", AR_RTR_INQ_CFG_DAMQ_NEXT_NXT_BLK_PTR_RD_WR_BP, AR_RTR_INQ_CFG_DAMQ_NEXT_NXT_BLK_PTR_RD_WR_MASK },
    { "NXT_BLK_PTR_PAR", AR_RTR_INQ_CFG_DAMQ_NEXT_NXT_BLK_PTR_PAR_BP, AR_RTR_INQ_CFG_DAMQ_NEXT_NXT_BLK_PTR_PAR_MASK },
    { "NXT_BLK_PTR_DATA", AR_RTR_INQ_CFG_DAMQ_NEXT_NXT_BLK_PTR_DATA_BP, AR_RTR_INQ_CFG_DAMQ_NEXT_NXT_BLK_PTR_DATA_MASK },
    { "NXT_BLK_PTR_ADDR", AR_RTR_INQ_CFG_DAMQ_NEXT_NXT_BLK_PTR_ADDR_BP, AR_RTR_INQ_CFG_DAMQ_NEXT_NXT_BLK_PTR_ADDR_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_cfg_damq_blk_in_used0_detail[] = {
    { "IN_USED", AR_RTR_INQ_CFG_DAMQ_BLK_IN_USED0_IN_USED_BP, AR_RTR_INQ_CFG_DAMQ_BLK_IN_USED0_IN_USED_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_cfg_damq_blk_in_used1_detail[] = {
    { "IN_USED", AR_RTR_INQ_CFG_DAMQ_BLK_IN_USED1_IN_USED_BP, AR_RTR_INQ_CFG_DAMQ_BLK_IN_USED1_IN_USED_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_cfg_dfifo_data_detail[] = {
    { "SINGLE_STEP_DFIFO_DATA", AR_RTR_INQ_CFG_DFIFO_DATA_SINGLE_STEP_DFIFO_DATA_BP, AR_RTR_INQ_CFG_DFIFO_DATA_SINGLE_STEP_DFIFO_DATA_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_cfg_route_pipe_detail[] = {
    { "RESET_LFSR", AR_RTR_INQ_CFG_ROUTE_PIPE_RESET_LFSR_BP, AR_RTR_INQ_CFG_ROUTE_PIPE_RESET_LFSR_MASK },
    { "READ_ALL_RTABLES", AR_RTR_INQ_CFG_ROUTE_PIPE_READ_ALL_RTABLES_BP, AR_RTR_INQ_CFG_ROUTE_PIPE_READ_ALL_RTABLES_MASK },
    { "ROUTE_ERR_TYPE_ENABLE", AR_RTR_INQ_CFG_ROUTE_PIPE_ROUTE_ERR_TYPE_ENABLE_BP, AR_RTR_INQ_CFG_ROUTE_PIPE_ROUTE_ERR_TYPE_ENABLE_MASK },
    { "GROUP_NUMBER", AR_RTR_INQ_CFG_ROUTE_PIPE_GROUP_NUMBER_BP, AR_RTR_INQ_CFG_ROUTE_PIPE_GROUP_NUMBER_MASK },
    { "ARIES_NUMBER", AR_RTR_INQ_CFG_ROUTE_PIPE_ARIES_NUMBER_BP, AR_RTR_INQ_CFG_ROUTE_PIPE_ARIES_NUMBER_MASK },
    { "INCR_INCOMING_VC", AR_RTR_INQ_CFG_ROUTE_PIPE_INCR_INCOMING_VC_BP, AR_RTR_INQ_CFG_ROUTE_PIPE_INCR_INCOMING_VC_MASK },
    { "AT_A_BLUE_TILE", AR_RTR_INQ_CFG_ROUTE_PIPE_AT_A_BLUE_TILE_BP, AR_RTR_INQ_CFG_ROUTE_PIPE_AT_A_BLUE_TILE_MASK },
    { "AT_A_PTILE", AR_RTR_INQ_CFG_ROUTE_PIPE_AT_A_PTILE_BP, AR_RTR_INQ_CFG_ROUTE_PIPE_AT_A_PTILE_MASK },
    { "HASH_ID", AR_RTR_INQ_CFG_ROUTE_PIPE_HASH_ID_BP, AR_RTR_INQ_CFG_ROUTE_PIPE_HASH_ID_MASK },
    { "LMIN_TBL_ADDR_SHIFT", AR_RTR_INQ_CFG_ROUTE_PIPE_LMIN_TBL_ADDR_SHIFT_BP, AR_RTR_INQ_CFG_ROUTE_PIPE_LMIN_TBL_ADDR_SHIFT_MASK },
    { "GMIN_TBL_ADDR_SHIFT", AR_RTR_INQ_CFG_ROUTE_PIPE_GMIN_TBL_ADDR_SHIFT_BP, AR_RTR_INQ_CFG_ROUTE_PIPE_GMIN_TBL_ADDR_SHIFT_MASK },
    { "DISABLE_CONGESTION", AR_RTR_INQ_CFG_ROUTE_PIPE_DISABLE_CONGESTION_BP, AR_RTR_INQ_CFG_ROUTE_PIPE_DISABLE_CONGESTION_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_cfg_vc_table_detail[] = {
    { "TRGT_VC7_PAR", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC7_PAR_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC7_PAR_MASK },
    { "TRGT_VC7_ROOT", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC7_ROOT_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC7_ROOT_MASK },
    { "TRGT_VC7", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC7_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC7_MASK },
    { "TRGT_VC6_PAR", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC6_PAR_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC6_PAR_MASK },
    { "TRGT_VC6_ROOT", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC6_ROOT_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC6_ROOT_MASK },
    { "TRGT_VC6", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC6_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC6_MASK },
    { "TRGT_VC5_PAR", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC5_PAR_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC5_PAR_MASK },
    { "TRGT_VC5_ROOT", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC5_ROOT_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC5_ROOT_MASK },
    { "TRGT_VC5", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC5_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC5_MASK },
    { "TRGT_VC4_PAR", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC4_PAR_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC4_PAR_MASK },
    { "TRGT_VC4_ROOT", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC4_ROOT_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC4_ROOT_MASK },
    { "TRGT_VC4", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC4_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC4_MASK },
    { "TRGT_VC3_PAR", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC3_PAR_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC3_PAR_MASK },
    { "TRGT_VC3_ROOT", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC3_ROOT_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC3_ROOT_MASK },
    { "TRGT_VC3", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC3_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC3_MASK },
    { "TRGT_VC2_PAR", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC2_PAR_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC2_PAR_MASK },
    { "TRGT_VC2_ROOT", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC2_ROOT_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC2_ROOT_MASK },
    { "TRGT_VC2", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC2_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC2_MASK },
    { "TRGT_VC1_PAR", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC1_PAR_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC1_PAR_MASK },
    { "TRGT_VC1_ROOT", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC1_ROOT_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC1_ROOT_MASK },
    { "TRGT_VC1", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC1_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC1_MASK },
    { "TRGT_VC0_PAR", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC0_PAR_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC0_PAR_MASK },
    { "TRGT_VC0_ROOT", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC0_ROOT_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC0_ROOT_MASK },
    { "TRGT_VC0", AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC0_BP, AR_RTR_INQ_CFG_VC_TABLE_TRGT_VC0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_cfg_link_alive_bits_detail[] = {
    { "LINK_ALIVE", AR_RTR_INQ_CFG_LINK_ALIVE_BITS_LINK_ALIVE_BP, AR_RTR_INQ_CFG_LINK_ALIVE_BITS_LINK_ALIVE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_cfg_congest_ctrl_detail[] = {
    { "ADAPT3_NONMIN_CONGEST_ADD", AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT3_NONMIN_CONGEST_ADD_BP, AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT3_NONMIN_CONGEST_ADD_MASK },
    { "ADAPT3_NONMIN_CONGEST_SHIFT", AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT3_NONMIN_CONGEST_SHIFT_BP, AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT3_NONMIN_CONGEST_SHIFT_MASK },
    { "ADAPT3_MIN_CONGEST_ADD", AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT3_MIN_CONGEST_ADD_BP, AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT3_MIN_CONGEST_ADD_MASK },
    { "ADAPT3_MIN_CONGEST_SHIFT", AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT3_MIN_CONGEST_SHIFT_BP, AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT3_MIN_CONGEST_SHIFT_MASK },
    { "ADAPT2_NONMIN_CONGEST_ADD", AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT2_NONMIN_CONGEST_ADD_BP, AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT2_NONMIN_CONGEST_ADD_MASK },
    { "ADAPT2_NONMIN_CONGEST_SHIFT", AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT2_NONMIN_CONGEST_SHIFT_BP, AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT2_NONMIN_CONGEST_SHIFT_MASK },
    { "ADAPT2_MIN_CONGEST_ADD", AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT2_MIN_CONGEST_ADD_BP, AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT2_MIN_CONGEST_ADD_MASK },
    { "ADAPT2_MIN_CONGEST_SHIFT", AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT2_MIN_CONGEST_SHIFT_BP, AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT2_MIN_CONGEST_SHIFT_MASK },
    { "ADAPT1_NONMIN_CONGEST_ADD", AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT1_NONMIN_CONGEST_ADD_BP, AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT1_NONMIN_CONGEST_ADD_MASK },
    { "ADAPT1_NONMIN_CONGEST_SHIFT", AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT1_NONMIN_CONGEST_SHIFT_BP, AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT1_NONMIN_CONGEST_SHIFT_MASK },
    { "ADAPT1_MIN_CONGEST_ADD", AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT1_MIN_CONGEST_ADD_BP, AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT1_MIN_CONGEST_ADD_MASK },
    { "ADAPT1_MIN_CONGEST_SHIFT", AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT1_MIN_CONGEST_SHIFT_BP, AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT1_MIN_CONGEST_SHIFT_MASK },
    { "ADAPT0_NONMIN_CONGEST_ADD", AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT0_NONMIN_CONGEST_ADD_BP, AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT0_NONMIN_CONGEST_ADD_MASK },
    { "ADAPT0_NONMIN_CONGEST_SHIFT", AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT0_NONMIN_CONGEST_SHIFT_BP, AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT0_NONMIN_CONGEST_SHIFT_MASK },
    { "ADAPT0_MIN_CONGEST_ADD", AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT0_MIN_CONGEST_ADD_BP, AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT0_MIN_CONGEST_ADD_MASK },
    { "ADAPT0_MIN_CONGEST_SHIFT", AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT0_MIN_CONGEST_SHIFT_BP, AR_RTR_INQ_CFG_CONGEST_CTRL_ADAPT0_MIN_CONGEST_SHIFT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_err_flg_detail[] = {
    { "LCB_ERR", AR_RTR_INQ_ERR_FLG_LCB_ERR_BP, AR_RTR_INQ_ERR_FLG_LCB_ERR_MASK },
    { "COLBUF_FPT_VC7", AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC7_BP, AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC7_MASK },
    { "COLBUF_FPT_VC6", AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC6_BP, AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC6_MASK },
    { "COLBUF_FPT_VC5", AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC5_BP, AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC5_MASK },
    { "COLBUF_FPT_VC4", AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC4_BP, AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC4_MASK },
    { "COLBUF_FPT_VC3", AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC3_BP, AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC3_MASK },
    { "COLBUF_FPT_VC2", AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC2_BP, AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC2_MASK },
    { "COLBUF_FPT_VC1", AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC1_BP, AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC1_MASK },
    { "COLBUF_FPT_VC0", AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC0_BP, AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC0_MASK },
    { "COLBUF_MBE_ERR", AR_RTR_INQ_ERR_FLG_COLBUF_MBE_ERR_BP, AR_RTR_INQ_ERR_FLG_COLBUF_MBE_ERR_MASK },
    { "COLBUF_SBE_ON_TAIL", AR_RTR_INQ_ERR_FLG_COLBUF_SBE_ON_TAIL_BP, AR_RTR_INQ_ERR_FLG_COLBUF_SBE_ON_TAIL_MASK },
    { "COLBUF_SBE_ERR", AR_RTR_INQ_ERR_FLG_COLBUF_SBE_ERR_BP, AR_RTR_INQ_ERR_FLG_COLBUF_SBE_ERR_MASK },
    { "COLBUF_CRC_ERR", AR_RTR_INQ_ERR_FLG_COLBUF_CRC_ERR_BP, AR_RTR_INQ_ERR_FLG_COLBUF_CRC_ERR_MASK },
    { "COLBUF_MAX_PKT_ERR", AR_RTR_INQ_ERR_FLG_COLBUF_MAX_PKT_ERR_BP, AR_RTR_INQ_ERR_FLG_COLBUF_MAX_PKT_ERR_MASK },
    { "COLBUF_UFLW_ERR", AR_RTR_INQ_ERR_FLG_COLBUF_UFLW_ERR_BP, AR_RTR_INQ_ERR_FLG_COLBUF_UFLW_ERR_MASK },
    { "COLBUF_OFLW_ERR", AR_RTR_INQ_ERR_FLG_COLBUF_OFLW_ERR_BP, AR_RTR_INQ_ERR_FLG_COLBUF_OFLW_ERR_MASK },
    { "SUBSWITCH_ERR", AR_RTR_INQ_ERR_FLG_SUBSWITCH_ERR_BP, AR_RTR_INQ_ERR_FLG_SUBSWITCH_ERR_MASK },
    { "LINK_ALIVE_TIMEOUT_ERR", AR_RTR_INQ_ERR_FLG_LINK_ALIVE_TIMEOUT_ERR_BP, AR_RTR_INQ_ERR_FLG_LINK_ALIVE_TIMEOUT_ERR_MASK },
    { "LINK_ALIVE_CHANNEL_ERR", AR_RTR_INQ_ERR_FLG_LINK_ALIVE_CHANNEL_ERR_BP, AR_RTR_INQ_ERR_FLG_LINK_ALIVE_CHANNEL_ERR_MASK },
    { "PRF_CNT_ROLLOVR_ERR", AR_RTR_INQ_ERR_FLG_PRF_CNT_ROLLOVR_ERR_BP, AR_RTR_INQ_ERR_FLG_PRF_CNT_ROLLOVR_ERR_MASK },
    { "MBE_RTABLE", AR_RTR_INQ_ERR_FLG_MBE_RTABLE_BP, AR_RTR_INQ_ERR_FLG_MBE_RTABLE_MASK },
    { "SBE_RTABLE", AR_RTR_INQ_ERR_FLG_SBE_RTABLE_BP, AR_RTR_INQ_ERR_FLG_SBE_RTABLE_MASK },
    { "ROUTE_ERROR", AR_RTR_INQ_ERR_FLG_ROUTE_ERROR_BP, AR_RTR_INQ_ERR_FLG_ROUTE_ERROR_MASK },
    { "PBE_VC_TABLE", AR_RTR_INQ_ERR_FLG_PBE_VC_TABLE_BP, AR_RTR_INQ_ERR_FLG_PBE_VC_TABLE_MASK },
    { "PBE_RFIFO_DATA", AR_RTR_INQ_ERR_FLG_PBE_RFIFO_DATA_BP, AR_RTR_INQ_ERR_FLG_PBE_RFIFO_DATA_MASK },
    { "PBE_RFIFO_COUNT", AR_RTR_INQ_ERR_FLG_PBE_RFIFO_COUNT_BP, AR_RTR_INQ_ERR_FLG_PBE_RFIFO_COUNT_MASK },
    { "PBE_OFIFO_COUNT", AR_RTR_INQ_ERR_FLG_PBE_OFIFO_COUNT_BP, AR_RTR_INQ_ERR_FLG_PBE_OFIFO_COUNT_MASK },
    { "PBE_DFIFO_COUNT", AR_RTR_INQ_ERR_FLG_PBE_DFIFO_COUNT_BP, AR_RTR_INQ_ERR_FLG_PBE_DFIFO_COUNT_MASK },
    { "INCORRECT_ACCESS_DFIFO", AR_RTR_INQ_ERR_FLG_INCORRECT_ACCESS_DFIFO_BP, AR_RTR_INQ_ERR_FLG_INCORRECT_ACCESS_DFIFO_MASK },
    { "UFLW_ERR_RFIFO", AR_RTR_INQ_ERR_FLG_UFLW_ERR_RFIFO_BP, AR_RTR_INQ_ERR_FLG_UFLW_ERR_RFIFO_MASK },
    { "UFLW_ERR_OFIFO", AR_RTR_INQ_ERR_FLG_UFLW_ERR_OFIFO_BP, AR_RTR_INQ_ERR_FLG_UFLW_ERR_OFIFO_MASK },
    { "UFLW_ERR_DFIFO", AR_RTR_INQ_ERR_FLG_UFLW_ERR_DFIFO_BP, AR_RTR_INQ_ERR_FLG_UFLW_ERR_DFIFO_MASK },
    { "OFLW_ERR_RFIFO", AR_RTR_INQ_ERR_FLG_OFLW_ERR_RFIFO_BP, AR_RTR_INQ_ERR_FLG_OFLW_ERR_RFIFO_MASK },
    { "OFLW_ERR_OFIFO", AR_RTR_INQ_ERR_FLG_OFLW_ERR_OFIFO_BP, AR_RTR_INQ_ERR_FLG_OFLW_ERR_OFIFO_MASK },
    { "OFLW_ERR_DFIFO", AR_RTR_INQ_ERR_FLG_OFLW_ERR_DFIFO_BP, AR_RTR_INQ_ERR_FLG_OFLW_ERR_DFIFO_MASK },
    { "ERR_RD_WRONG_VC_BLK_DAMQ", AR_RTR_INQ_ERR_FLG_ERR_RD_WRONG_VC_BLK_DAMQ_BP, AR_RTR_INQ_ERR_FLG_ERR_RD_WRONG_VC_BLK_DAMQ_MASK },
    { "ERR_DEALLOC_IDLE_BLK_DAMQ", AR_RTR_INQ_ERR_FLG_ERR_DEALLOC_IDLE_BLK_DAMQ_BP, AR_RTR_INQ_ERR_FLG_ERR_DEALLOC_IDLE_BLK_DAMQ_MASK },
    { "ERR_ALLOC_INUSE_BLK_DAMQ", AR_RTR_INQ_ERR_FLG_ERR_ALLOC_INUSE_BLK_DAMQ_BP, AR_RTR_INQ_ERR_FLG_ERR_ALLOC_INUSE_BLK_DAMQ_MASK },
    { "ERR_WR_NON_ALLOC_BLK_DAMQ", AR_RTR_INQ_ERR_FLG_ERR_WR_NON_ALLOC_BLK_DAMQ_BP, AR_RTR_INQ_ERR_FLG_ERR_WR_NON_ALLOC_BLK_DAMQ_MASK },
    { "ERR_RD_NON_ALLOC_BLK_DAMQ", AR_RTR_INQ_ERR_FLG_ERR_RD_NON_ALLOC_BLK_DAMQ_BP, AR_RTR_INQ_ERR_FLG_ERR_RD_NON_ALLOC_BLK_DAMQ_MASK },
    { "PBE_CNT_DAMQ", AR_RTR_INQ_ERR_FLG_PBE_CNT_DAMQ_BP, AR_RTR_INQ_ERR_FLG_PBE_CNT_DAMQ_MASK },
    { "PBE_PTR_DAMQ", AR_RTR_INQ_ERR_FLG_PBE_PTR_DAMQ_BP, AR_RTR_INQ_ERR_FLG_PBE_PTR_DAMQ_MASK },
    { "MBE_DAMQ", AR_RTR_INQ_ERR_FLG_MBE_DAMQ_BP, AR_RTR_INQ_ERR_FLG_MBE_DAMQ_MASK },
    { "SBE_DAMQ", AR_RTR_INQ_ERR_FLG_SBE_DAMQ_BP, AR_RTR_INQ_ERR_FLG_SBE_DAMQ_MASK },
    { "UFLW_ERR_DAMQ", AR_RTR_INQ_ERR_FLG_UFLW_ERR_DAMQ_BP, AR_RTR_INQ_ERR_FLG_UFLW_ERR_DAMQ_MASK },
    { "OFLW_ERR_DAMQ", AR_RTR_INQ_ERR_FLG_OFLW_ERR_DAMQ_BP, AR_RTR_INQ_ERR_FLG_OFLW_ERR_DAMQ_MASK },
    { "DIAG_ONLY", AR_RTR_INQ_ERR_FLG_DIAG_ONLY_BP, AR_RTR_INQ_ERR_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
#ifdef EXCEPTIONS_DEFS
static const errcat_mmrd_t _ar_rtr_inq_err_flg_errcat[] = {
    { "LCB_ERR", AR_RTR_INQ_ERR_FLG_LCB_ERR_BP, AR_RTR_INQ_ERR_FLG_LCB_ERR_EC },
    { "COLBUF_FPT_VC7", AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC7_BP, AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC7_EC },
    { "COLBUF_FPT_VC6", AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC6_BP, AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC6_EC },
    { "COLBUF_FPT_VC5", AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC5_BP, AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC5_EC },
    { "COLBUF_FPT_VC4", AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC4_BP, AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC4_EC },
    { "COLBUF_FPT_VC3", AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC3_BP, AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC3_EC },
    { "COLBUF_FPT_VC2", AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC2_BP, AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC2_EC },
    { "COLBUF_FPT_VC1", AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC1_BP, AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC1_EC },
    { "COLBUF_FPT_VC0", AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC0_BP, AR_RTR_INQ_ERR_FLG_COLBUF_FPT_VC0_EC },
    { "COLBUF_MBE_ERR", AR_RTR_INQ_ERR_FLG_COLBUF_MBE_ERR_BP, AR_RTR_INQ_ERR_FLG_COLBUF_MBE_ERR_EC },
    { "COLBUF_SBE_ON_TAIL", AR_RTR_INQ_ERR_FLG_COLBUF_SBE_ON_TAIL_BP, AR_RTR_INQ_ERR_FLG_COLBUF_SBE_ON_TAIL_EC },
    { "COLBUF_SBE_ERR", AR_RTR_INQ_ERR_FLG_COLBUF_SBE_ERR_BP, AR_RTR_INQ_ERR_FLG_COLBUF_SBE_ERR_EC },
    { "COLBUF_CRC_ERR", AR_RTR_INQ_ERR_FLG_COLBUF_CRC_ERR_BP, AR_RTR_INQ_ERR_FLG_COLBUF_CRC_ERR_EC },
    { "COLBUF_MAX_PKT_ERR", AR_RTR_INQ_ERR_FLG_COLBUF_MAX_PKT_ERR_BP, AR_RTR_INQ_ERR_FLG_COLBUF_MAX_PKT_ERR_EC },
    { "COLBUF_UFLW_ERR", AR_RTR_INQ_ERR_FLG_COLBUF_UFLW_ERR_BP, AR_RTR_INQ_ERR_FLG_COLBUF_UFLW_ERR_EC },
    { "COLBUF_OFLW_ERR", AR_RTR_INQ_ERR_FLG_COLBUF_OFLW_ERR_BP, AR_RTR_INQ_ERR_FLG_COLBUF_OFLW_ERR_EC },
    { "SUBSWITCH_ERR", AR_RTR_INQ_ERR_FLG_SUBSWITCH_ERR_BP, AR_RTR_INQ_ERR_FLG_SUBSWITCH_ERR_EC },
    { "LINK_ALIVE_TIMEOUT_ERR", AR_RTR_INQ_ERR_FLG_LINK_ALIVE_TIMEOUT_ERR_BP, AR_RTR_INQ_ERR_FLG_LINK_ALIVE_TIMEOUT_ERR_EC },
    { "LINK_ALIVE_CHANNEL_ERR", AR_RTR_INQ_ERR_FLG_LINK_ALIVE_CHANNEL_ERR_BP, AR_RTR_INQ_ERR_FLG_LINK_ALIVE_CHANNEL_ERR_EC },
    { "PRF_CNT_ROLLOVR_ERR", AR_RTR_INQ_ERR_FLG_PRF_CNT_ROLLOVR_ERR_BP, AR_RTR_INQ_ERR_FLG_PRF_CNT_ROLLOVR_ERR_EC },
    { "MBE_RTABLE", AR_RTR_INQ_ERR_FLG_MBE_RTABLE_BP, AR_RTR_INQ_ERR_FLG_MBE_RTABLE_EC },
    { "SBE_RTABLE", AR_RTR_INQ_ERR_FLG_SBE_RTABLE_BP, AR_RTR_INQ_ERR_FLG_SBE_RTABLE_EC },
    { "ROUTE_ERROR", AR_RTR_INQ_ERR_FLG_ROUTE_ERROR_BP, AR_RTR_INQ_ERR_FLG_ROUTE_ERROR_EC },
    { "PBE_VC_TABLE", AR_RTR_INQ_ERR_FLG_PBE_VC_TABLE_BP, AR_RTR_INQ_ERR_FLG_PBE_VC_TABLE_EC },
    { "PBE_RFIFO_DATA", AR_RTR_INQ_ERR_FLG_PBE_RFIFO_DATA_BP, AR_RTR_INQ_ERR_FLG_PBE_RFIFO_DATA_EC },
    { "PBE_RFIFO_COUNT", AR_RTR_INQ_ERR_FLG_PBE_RFIFO_COUNT_BP, AR_RTR_INQ_ERR_FLG_PBE_RFIFO_COUNT_EC },
    { "PBE_OFIFO_COUNT", AR_RTR_INQ_ERR_FLG_PBE_OFIFO_COUNT_BP, AR_RTR_INQ_ERR_FLG_PBE_OFIFO_COUNT_EC },
    { "PBE_DFIFO_COUNT", AR_RTR_INQ_ERR_FLG_PBE_DFIFO_COUNT_BP, AR_RTR_INQ_ERR_FLG_PBE_DFIFO_COUNT_EC },
    { "INCORRECT_ACCESS_DFIFO", AR_RTR_INQ_ERR_FLG_INCORRECT_ACCESS_DFIFO_BP, AR_RTR_INQ_ERR_FLG_INCORRECT_ACCESS_DFIFO_EC },
    { "UFLW_ERR_RFIFO", AR_RTR_INQ_ERR_FLG_UFLW_ERR_RFIFO_BP, AR_RTR_INQ_ERR_FLG_UFLW_ERR_RFIFO_EC },
    { "UFLW_ERR_OFIFO", AR_RTR_INQ_ERR_FLG_UFLW_ERR_OFIFO_BP, AR_RTR_INQ_ERR_FLG_UFLW_ERR_OFIFO_EC },
    { "UFLW_ERR_DFIFO", AR_RTR_INQ_ERR_FLG_UFLW_ERR_DFIFO_BP, AR_RTR_INQ_ERR_FLG_UFLW_ERR_DFIFO_EC },
    { "OFLW_ERR_RFIFO", AR_RTR_INQ_ERR_FLG_OFLW_ERR_RFIFO_BP, AR_RTR_INQ_ERR_FLG_OFLW_ERR_RFIFO_EC },
    { "OFLW_ERR_OFIFO", AR_RTR_INQ_ERR_FLG_OFLW_ERR_OFIFO_BP, AR_RTR_INQ_ERR_FLG_OFLW_ERR_OFIFO_EC },
    { "OFLW_ERR_DFIFO", AR_RTR_INQ_ERR_FLG_OFLW_ERR_DFIFO_BP, AR_RTR_INQ_ERR_FLG_OFLW_ERR_DFIFO_EC },
    { "ERR_RD_WRONG_VC_BLK_DAMQ", AR_RTR_INQ_ERR_FLG_ERR_RD_WRONG_VC_BLK_DAMQ_BP, AR_RTR_INQ_ERR_FLG_ERR_RD_WRONG_VC_BLK_DAMQ_EC },
    { "ERR_DEALLOC_IDLE_BLK_DAMQ", AR_RTR_INQ_ERR_FLG_ERR_DEALLOC_IDLE_BLK_DAMQ_BP, AR_RTR_INQ_ERR_FLG_ERR_DEALLOC_IDLE_BLK_DAMQ_EC },
    { "ERR_ALLOC_INUSE_BLK_DAMQ", AR_RTR_INQ_ERR_FLG_ERR_ALLOC_INUSE_BLK_DAMQ_BP, AR_RTR_INQ_ERR_FLG_ERR_ALLOC_INUSE_BLK_DAMQ_EC },
    { "ERR_WR_NON_ALLOC_BLK_DAMQ", AR_RTR_INQ_ERR_FLG_ERR_WR_NON_ALLOC_BLK_DAMQ_BP, AR_RTR_INQ_ERR_FLG_ERR_WR_NON_ALLOC_BLK_DAMQ_EC },
    { "ERR_RD_NON_ALLOC_BLK_DAMQ", AR_RTR_INQ_ERR_FLG_ERR_RD_NON_ALLOC_BLK_DAMQ_BP, AR_RTR_INQ_ERR_FLG_ERR_RD_NON_ALLOC_BLK_DAMQ_EC },
    { "PBE_CNT_DAMQ", AR_RTR_INQ_ERR_FLG_PBE_CNT_DAMQ_BP, AR_RTR_INQ_ERR_FLG_PBE_CNT_DAMQ_EC },
    { "PBE_PTR_DAMQ", AR_RTR_INQ_ERR_FLG_PBE_PTR_DAMQ_BP, AR_RTR_INQ_ERR_FLG_PBE_PTR_DAMQ_EC },
    { "MBE_DAMQ", AR_RTR_INQ_ERR_FLG_MBE_DAMQ_BP, AR_RTR_INQ_ERR_FLG_MBE_DAMQ_EC },
    { "SBE_DAMQ", AR_RTR_INQ_ERR_FLG_SBE_DAMQ_BP, AR_RTR_INQ_ERR_FLG_SBE_DAMQ_EC },
    { "UFLW_ERR_DAMQ", AR_RTR_INQ_ERR_FLG_UFLW_ERR_DAMQ_BP, AR_RTR_INQ_ERR_FLG_UFLW_ERR_DAMQ_EC },
    { "OFLW_ERR_DAMQ", AR_RTR_INQ_ERR_FLG_OFLW_ERR_DAMQ_BP, AR_RTR_INQ_ERR_FLG_OFLW_ERR_DAMQ_EC },
    { "DIAG_ONLY", AR_RTR_INQ_ERR_FLG_DIAG_ONLY_BP, AR_RTR_INQ_ERR_FLG_DIAG_ONLY_EC },
    { NULL, 0, 0 }
};
#endif
static const generic_mmrd_t _ar_rtr_inq_err_clr_detail[] = {
    { "LCB_ERR", AR_RTR_INQ_ERR_CLR_LCB_ERR_BP, AR_RTR_INQ_ERR_CLR_LCB_ERR_MASK },
    { "COLBUF_FPT_VC7", AR_RTR_INQ_ERR_CLR_COLBUF_FPT_VC7_BP, AR_RTR_INQ_ERR_CLR_COLBUF_FPT_VC7_MASK },
    { "COLBUF_FPT_VC6", AR_RTR_INQ_ERR_CLR_COLBUF_FPT_VC6_BP, AR_RTR_INQ_ERR_CLR_COLBUF_FPT_VC6_MASK },
    { "COLBUF_FPT_VC5", AR_RTR_INQ_ERR_CLR_COLBUF_FPT_VC5_BP, AR_RTR_INQ_ERR_CLR_COLBUF_FPT_VC5_MASK },
    { "COLBUF_FPT_VC4", AR_RTR_INQ_ERR_CLR_COLBUF_FPT_VC4_BP, AR_RTR_INQ_ERR_CLR_COLBUF_FPT_VC4_MASK },
    { "COLBUF_FPT_VC3", AR_RTR_INQ_ERR_CLR_COLBUF_FPT_VC3_BP, AR_RTR_INQ_ERR_CLR_COLBUF_FPT_VC3_MASK },
    { "COLBUF_FPT_VC2", AR_RTR_INQ_ERR_CLR_COLBUF_FPT_VC2_BP, AR_RTR_INQ_ERR_CLR_COLBUF_FPT_VC2_MASK },
    { "COLBUF_FPT_VC1", AR_RTR_INQ_ERR_CLR_COLBUF_FPT_VC1_BP, AR_RTR_INQ_ERR_CLR_COLBUF_FPT_VC1_MASK },
    { "COLBUF_FPT_VC0", AR_RTR_INQ_ERR_CLR_COLBUF_FPT_VC0_BP, AR_RTR_INQ_ERR_CLR_COLBUF_FPT_VC0_MASK },
    { "COLBUF_MBE_ERR", AR_RTR_INQ_ERR_CLR_COLBUF_MBE_ERR_BP, AR_RTR_INQ_ERR_CLR_COLBUF_MBE_ERR_MASK },
    { "COLBUF_SBE_ON_TAIL", AR_RTR_INQ_ERR_CLR_COLBUF_SBE_ON_TAIL_BP, AR_RTR_INQ_ERR_CLR_COLBUF_SBE_ON_TAIL_MASK },
    { "COLBUF_SBE_ERR", AR_RTR_INQ_ERR_CLR_COLBUF_SBE_ERR_BP, AR_RTR_INQ_ERR_CLR_COLBUF_SBE_ERR_MASK },
    { "COLBUF_CRC_ERR", AR_RTR_INQ_ERR_CLR_COLBUF_CRC_ERR_BP, AR_RTR_INQ_ERR_CLR_COLBUF_CRC_ERR_MASK },
    { "COLBUF_MAX_PKT_ERR", AR_RTR_INQ_ERR_CLR_COLBUF_MAX_PKT_ERR_BP, AR_RTR_INQ_ERR_CLR_COLBUF_MAX_PKT_ERR_MASK },
    { "COLBUF_UFLW_ERR", AR_RTR_INQ_ERR_CLR_COLBUF_UFLW_ERR_BP, AR_RTR_INQ_ERR_CLR_COLBUF_UFLW_ERR_MASK },
    { "COLBUF_OFLW_ERR", AR_RTR_INQ_ERR_CLR_COLBUF_OFLW_ERR_BP, AR_RTR_INQ_ERR_CLR_COLBUF_OFLW_ERR_MASK },
    { "SUBSWITCH_ERR", AR_RTR_INQ_ERR_CLR_SUBSWITCH_ERR_BP, AR_RTR_INQ_ERR_CLR_SUBSWITCH_ERR_MASK },
    { "LINK_ALIVE_TIMEOUT_ERR", AR_RTR_INQ_ERR_CLR_LINK_ALIVE_TIMEOUT_ERR_BP, AR_RTR_INQ_ERR_CLR_LINK_ALIVE_TIMEOUT_ERR_MASK },
    { "LINK_ALIVE_CHANNEL_ERR", AR_RTR_INQ_ERR_CLR_LINK_ALIVE_CHANNEL_ERR_BP, AR_RTR_INQ_ERR_CLR_LINK_ALIVE_CHANNEL_ERR_MASK },
    { "PRF_CNT_ROLLOVR_ERR", AR_RTR_INQ_ERR_CLR_PRF_CNT_ROLLOVR_ERR_BP, AR_RTR_INQ_ERR_CLR_PRF_CNT_ROLLOVR_ERR_MASK },
    { "MBE_RTABLE", AR_RTR_INQ_ERR_CLR_MBE_RTABLE_BP, AR_RTR_INQ_ERR_CLR_MBE_RTABLE_MASK },
    { "SBE_RTABLE", AR_RTR_INQ_ERR_CLR_SBE_RTABLE_BP, AR_RTR_INQ_ERR_CLR_SBE_RTABLE_MASK },
    { "ROUTE_ERROR", AR_RTR_INQ_ERR_CLR_ROUTE_ERROR_BP, AR_RTR_INQ_ERR_CLR_ROUTE_ERROR_MASK },
    { "PBE_VC_TABLE", AR_RTR_INQ_ERR_CLR_PBE_VC_TABLE_BP, AR_RTR_INQ_ERR_CLR_PBE_VC_TABLE_MASK },
    { "PBE_RFIFO_DATA", AR_RTR_INQ_ERR_CLR_PBE_RFIFO_DATA_BP, AR_RTR_INQ_ERR_CLR_PBE_RFIFO_DATA_MASK },
    { "PBE_RFIFO_COUNT", AR_RTR_INQ_ERR_CLR_PBE_RFIFO_COUNT_BP, AR_RTR_INQ_ERR_CLR_PBE_RFIFO_COUNT_MASK },
    { "PBE_OFIFO_COUNT", AR_RTR_INQ_ERR_CLR_PBE_OFIFO_COUNT_BP, AR_RTR_INQ_ERR_CLR_PBE_OFIFO_COUNT_MASK },
    { "PBE_DFIFO_COUNT", AR_RTR_INQ_ERR_CLR_PBE_DFIFO_COUNT_BP, AR_RTR_INQ_ERR_CLR_PBE_DFIFO_COUNT_MASK },
    { "INCORRECT_ACCESS_DFIFO", AR_RTR_INQ_ERR_CLR_INCORRECT_ACCESS_DFIFO_BP, AR_RTR_INQ_ERR_CLR_INCORRECT_ACCESS_DFIFO_MASK },
    { "UFLW_ERR_RFIFO", AR_RTR_INQ_ERR_CLR_UFLW_ERR_RFIFO_BP, AR_RTR_INQ_ERR_CLR_UFLW_ERR_RFIFO_MASK },
    { "UFLW_ERR_OFIFO", AR_RTR_INQ_ERR_CLR_UFLW_ERR_OFIFO_BP, AR_RTR_INQ_ERR_CLR_UFLW_ERR_OFIFO_MASK },
    { "UFLW_ERR_DFIFO", AR_RTR_INQ_ERR_CLR_UFLW_ERR_DFIFO_BP, AR_RTR_INQ_ERR_CLR_UFLW_ERR_DFIFO_MASK },
    { "OFLW_ERR_RFIFO", AR_RTR_INQ_ERR_CLR_OFLW_ERR_RFIFO_BP, AR_RTR_INQ_ERR_CLR_OFLW_ERR_RFIFO_MASK },
    { "OFLW_ERR_OFIFO", AR_RTR_INQ_ERR_CLR_OFLW_ERR_OFIFO_BP, AR_RTR_INQ_ERR_CLR_OFLW_ERR_OFIFO_MASK },
    { "OFLW_ERR_DFIFO", AR_RTR_INQ_ERR_CLR_OFLW_ERR_DFIFO_BP, AR_RTR_INQ_ERR_CLR_OFLW_ERR_DFIFO_MASK },
    { "ERR_RD_WRONG_VC_BLK_DAMQ", AR_RTR_INQ_ERR_CLR_ERR_RD_WRONG_VC_BLK_DAMQ_BP, AR_RTR_INQ_ERR_CLR_ERR_RD_WRONG_VC_BLK_DAMQ_MASK },
    { "ERR_DEALLOC_IDLE_BLK_DAMQ", AR_RTR_INQ_ERR_CLR_ERR_DEALLOC_IDLE_BLK_DAMQ_BP, AR_RTR_INQ_ERR_CLR_ERR_DEALLOC_IDLE_BLK_DAMQ_MASK },
    { "ERR_ALLOC_INUSE_BLK_DAMQ", AR_RTR_INQ_ERR_CLR_ERR_ALLOC_INUSE_BLK_DAMQ_BP, AR_RTR_INQ_ERR_CLR_ERR_ALLOC_INUSE_BLK_DAMQ_MASK },
    { "ERR_WR_NON_ALLOC_BLK_DAMQ", AR_RTR_INQ_ERR_CLR_ERR_WR_NON_ALLOC_BLK_DAMQ_BP, AR_RTR_INQ_ERR_CLR_ERR_WR_NON_ALLOC_BLK_DAMQ_MASK },
    { "ERR_RD_NON_ALLOC_BLK_DAMQ", AR_RTR_INQ_ERR_CLR_ERR_RD_NON_ALLOC_BLK_DAMQ_BP, AR_RTR_INQ_ERR_CLR_ERR_RD_NON_ALLOC_BLK_DAMQ_MASK },
    { "PBE_CNT_DAMQ", AR_RTR_INQ_ERR_CLR_PBE_CNT_DAMQ_BP, AR_RTR_INQ_ERR_CLR_PBE_CNT_DAMQ_MASK },
    { "PBE_PTR_DAMQ", AR_RTR_INQ_ERR_CLR_PBE_PTR_DAMQ_BP, AR_RTR_INQ_ERR_CLR_PBE_PTR_DAMQ_MASK },
    { "MBE_DAMQ", AR_RTR_INQ_ERR_CLR_MBE_DAMQ_BP, AR_RTR_INQ_ERR_CLR_MBE_DAMQ_MASK },
    { "SBE_DAMQ", AR_RTR_INQ_ERR_CLR_SBE_DAMQ_BP, AR_RTR_INQ_ERR_CLR_SBE_DAMQ_MASK },
    { "UFLW_ERR_DAMQ", AR_RTR_INQ_ERR_CLR_UFLW_ERR_DAMQ_BP, AR_RTR_INQ_ERR_CLR_UFLW_ERR_DAMQ_MASK },
    { "OFLW_ERR_DAMQ", AR_RTR_INQ_ERR_CLR_OFLW_ERR_DAMQ_BP, AR_RTR_INQ_ERR_CLR_OFLW_ERR_DAMQ_MASK },
    { "DIAG_ONLY", AR_RTR_INQ_ERR_CLR_DIAG_ONLY_BP, AR_RTR_INQ_ERR_CLR_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_err_hss_msk_detail[] = {
    { "LCB_ERR", AR_RTR_INQ_ERR_HSS_MSK_LCB_ERR_BP, AR_RTR_INQ_ERR_HSS_MSK_LCB_ERR_MASK },
    { "COLBUF_FPT_VC7", AR_RTR_INQ_ERR_HSS_MSK_COLBUF_FPT_VC7_BP, AR_RTR_INQ_ERR_HSS_MSK_COLBUF_FPT_VC7_MASK },
    { "COLBUF_FPT_VC6", AR_RTR_INQ_ERR_HSS_MSK_COLBUF_FPT_VC6_BP, AR_RTR_INQ_ERR_HSS_MSK_COLBUF_FPT_VC6_MASK },
    { "COLBUF_FPT_VC5", AR_RTR_INQ_ERR_HSS_MSK_COLBUF_FPT_VC5_BP, AR_RTR_INQ_ERR_HSS_MSK_COLBUF_FPT_VC5_MASK },
    { "COLBUF_FPT_VC4", AR_RTR_INQ_ERR_HSS_MSK_COLBUF_FPT_VC4_BP, AR_RTR_INQ_ERR_HSS_MSK_COLBUF_FPT_VC4_MASK },
    { "COLBUF_FPT_VC3", AR_RTR_INQ_ERR_HSS_MSK_COLBUF_FPT_VC3_BP, AR_RTR_INQ_ERR_HSS_MSK_COLBUF_FPT_VC3_MASK },
    { "COLBUF_FPT_VC2", AR_RTR_INQ_ERR_HSS_MSK_COLBUF_FPT_VC2_BP, AR_RTR_INQ_ERR_HSS_MSK_COLBUF_FPT_VC2_MASK },
    { "COLBUF_FPT_VC1", AR_RTR_INQ_ERR_HSS_MSK_COLBUF_FPT_VC1_BP, AR_RTR_INQ_ERR_HSS_MSK_COLBUF_FPT_VC1_MASK },
    { "COLBUF_FPT_VC0", AR_RTR_INQ_ERR_HSS_MSK_COLBUF_FPT_VC0_BP, AR_RTR_INQ_ERR_HSS_MSK_COLBUF_FPT_VC0_MASK },
    { "COLBUF_MBE_ERR", AR_RTR_INQ_ERR_HSS_MSK_COLBUF_MBE_ERR_BP, AR_RTR_INQ_ERR_HSS_MSK_COLBUF_MBE_ERR_MASK },
    { "COLBUF_SBE_ON_TAIL", AR_RTR_INQ_ERR_HSS_MSK_COLBUF_SBE_ON_TAIL_BP, AR_RTR_INQ_ERR_HSS_MSK_COLBUF_SBE_ON_TAIL_MASK },
    { "COLBUF_SBE_ERR", AR_RTR_INQ_ERR_HSS_MSK_COLBUF_SBE_ERR_BP, AR_RTR_INQ_ERR_HSS_MSK_COLBUF_SBE_ERR_MASK },
    { "COLBUF_CRC_ERR", AR_RTR_INQ_ERR_HSS_MSK_COLBUF_CRC_ERR_BP, AR_RTR_INQ_ERR_HSS_MSK_COLBUF_CRC_ERR_MASK },
    { "COLBUF_MAX_PKT_ERR", AR_RTR_INQ_ERR_HSS_MSK_COLBUF_MAX_PKT_ERR_BP, AR_RTR_INQ_ERR_HSS_MSK_COLBUF_MAX_PKT_ERR_MASK },
    { "COLBUF_UFLW_ERR", AR_RTR_INQ_ERR_HSS_MSK_COLBUF_UFLW_ERR_BP, AR_RTR_INQ_ERR_HSS_MSK_COLBUF_UFLW_ERR_MASK },
    { "COLBUF_OFLW_ERR", AR_RTR_INQ_ERR_HSS_MSK_COLBUF_OFLW_ERR_BP, AR_RTR_INQ_ERR_HSS_MSK_COLBUF_OFLW_ERR_MASK },
    { "SUBSWITCH_ERR", AR_RTR_INQ_ERR_HSS_MSK_SUBSWITCH_ERR_BP, AR_RTR_INQ_ERR_HSS_MSK_SUBSWITCH_ERR_MASK },
    { "LINK_ALIVE_TIMEOUT_ERR", AR_RTR_INQ_ERR_HSS_MSK_LINK_ALIVE_TIMEOUT_ERR_BP, AR_RTR_INQ_ERR_HSS_MSK_LINK_ALIVE_TIMEOUT_ERR_MASK },
    { "LINK_ALIVE_CHANNEL_ERR", AR_RTR_INQ_ERR_HSS_MSK_LINK_ALIVE_CHANNEL_ERR_BP, AR_RTR_INQ_ERR_HSS_MSK_LINK_ALIVE_CHANNEL_ERR_MASK },
    { "PRF_CNT_ROLLOVR_ERR", AR_RTR_INQ_ERR_HSS_MSK_PRF_CNT_ROLLOVR_ERR_BP, AR_RTR_INQ_ERR_HSS_MSK_PRF_CNT_ROLLOVR_ERR_MASK },
    { "MBE_RTABLE", AR_RTR_INQ_ERR_HSS_MSK_MBE_RTABLE_BP, AR_RTR_INQ_ERR_HSS_MSK_MBE_RTABLE_MASK },
    { "SBE_RTABLE", AR_RTR_INQ_ERR_HSS_MSK_SBE_RTABLE_BP, AR_RTR_INQ_ERR_HSS_MSK_SBE_RTABLE_MASK },
    { "ROUTE_ERROR", AR_RTR_INQ_ERR_HSS_MSK_ROUTE_ERROR_BP, AR_RTR_INQ_ERR_HSS_MSK_ROUTE_ERROR_MASK },
    { "PBE_VC_TABLE", AR_RTR_INQ_ERR_HSS_MSK_PBE_VC_TABLE_BP, AR_RTR_INQ_ERR_HSS_MSK_PBE_VC_TABLE_MASK },
    { "PBE_RFIFO_DATA", AR_RTR_INQ_ERR_HSS_MSK_PBE_RFIFO_DATA_BP, AR_RTR_INQ_ERR_HSS_MSK_PBE_RFIFO_DATA_MASK },
    { "PBE_RFIFO_COUNT", AR_RTR_INQ_ERR_HSS_MSK_PBE_RFIFO_COUNT_BP, AR_RTR_INQ_ERR_HSS_MSK_PBE_RFIFO_COUNT_MASK },
    { "PBE_OFIFO_COUNT", AR_RTR_INQ_ERR_HSS_MSK_PBE_OFIFO_COUNT_BP, AR_RTR_INQ_ERR_HSS_MSK_PBE_OFIFO_COUNT_MASK },
    { "PBE_DFIFO_COUNT", AR_RTR_INQ_ERR_HSS_MSK_PBE_DFIFO_COUNT_BP, AR_RTR_INQ_ERR_HSS_MSK_PBE_DFIFO_COUNT_MASK },
    { "INCORRECT_ACCESS_DFIFO", AR_RTR_INQ_ERR_HSS_MSK_INCORRECT_ACCESS_DFIFO_BP, AR_RTR_INQ_ERR_HSS_MSK_INCORRECT_ACCESS_DFIFO_MASK },
    { "UFLW_ERR_RFIFO", AR_RTR_INQ_ERR_HSS_MSK_UFLW_ERR_RFIFO_BP, AR_RTR_INQ_ERR_HSS_MSK_UFLW_ERR_RFIFO_MASK },
    { "UFLW_ERR_OFIFO", AR_RTR_INQ_ERR_HSS_MSK_UFLW_ERR_OFIFO_BP, AR_RTR_INQ_ERR_HSS_MSK_UFLW_ERR_OFIFO_MASK },
    { "UFLW_ERR_DFIFO", AR_RTR_INQ_ERR_HSS_MSK_UFLW_ERR_DFIFO_BP, AR_RTR_INQ_ERR_HSS_MSK_UFLW_ERR_DFIFO_MASK },
    { "OFLW_ERR_RFIFO", AR_RTR_INQ_ERR_HSS_MSK_OFLW_ERR_RFIFO_BP, AR_RTR_INQ_ERR_HSS_MSK_OFLW_ERR_RFIFO_MASK },
    { "OFLW_ERR_OFIFO", AR_RTR_INQ_ERR_HSS_MSK_OFLW_ERR_OFIFO_BP, AR_RTR_INQ_ERR_HSS_MSK_OFLW_ERR_OFIFO_MASK },
    { "OFLW_ERR_DFIFO", AR_RTR_INQ_ERR_HSS_MSK_OFLW_ERR_DFIFO_BP, AR_RTR_INQ_ERR_HSS_MSK_OFLW_ERR_DFIFO_MASK },
    { "ERR_RD_WRONG_VC_BLK_DAMQ", AR_RTR_INQ_ERR_HSS_MSK_ERR_RD_WRONG_VC_BLK_DAMQ_BP, AR_RTR_INQ_ERR_HSS_MSK_ERR_RD_WRONG_VC_BLK_DAMQ_MASK },
    { "ERR_DEALLOC_IDLE_BLK_DAMQ", AR_RTR_INQ_ERR_HSS_MSK_ERR_DEALLOC_IDLE_BLK_DAMQ_BP, AR_RTR_INQ_ERR_HSS_MSK_ERR_DEALLOC_IDLE_BLK_DAMQ_MASK },
    { "ERR_ALLOC_INUSE_BLK_DAMQ", AR_RTR_INQ_ERR_HSS_MSK_ERR_ALLOC_INUSE_BLK_DAMQ_BP, AR_RTR_INQ_ERR_HSS_MSK_ERR_ALLOC_INUSE_BLK_DAMQ_MASK },
    { "ERR_WR_NON_ALLOC_BLK_DAMQ", AR_RTR_INQ_ERR_HSS_MSK_ERR_WR_NON_ALLOC_BLK_DAMQ_BP, AR_RTR_INQ_ERR_HSS_MSK_ERR_WR_NON_ALLOC_BLK_DAMQ_MASK },
    { "ERR_RD_NON_ALLOC_BLK_DAMQ", AR_RTR_INQ_ERR_HSS_MSK_ERR_RD_NON_ALLOC_BLK_DAMQ_BP, AR_RTR_INQ_ERR_HSS_MSK_ERR_RD_NON_ALLOC_BLK_DAMQ_MASK },
    { "PBE_CNT_DAMQ", AR_RTR_INQ_ERR_HSS_MSK_PBE_CNT_DAMQ_BP, AR_RTR_INQ_ERR_HSS_MSK_PBE_CNT_DAMQ_MASK },
    { "PBE_PTR_DAMQ", AR_RTR_INQ_ERR_HSS_MSK_PBE_PTR_DAMQ_BP, AR_RTR_INQ_ERR_HSS_MSK_PBE_PTR_DAMQ_MASK },
    { "MBE_DAMQ", AR_RTR_INQ_ERR_HSS_MSK_MBE_DAMQ_BP, AR_RTR_INQ_ERR_HSS_MSK_MBE_DAMQ_MASK },
    { "SBE_DAMQ", AR_RTR_INQ_ERR_HSS_MSK_SBE_DAMQ_BP, AR_RTR_INQ_ERR_HSS_MSK_SBE_DAMQ_MASK },
    { "UFLW_ERR_DAMQ", AR_RTR_INQ_ERR_HSS_MSK_UFLW_ERR_DAMQ_BP, AR_RTR_INQ_ERR_HSS_MSK_UFLW_ERR_DAMQ_MASK },
    { "OFLW_ERR_DAMQ", AR_RTR_INQ_ERR_HSS_MSK_OFLW_ERR_DAMQ_BP, AR_RTR_INQ_ERR_HSS_MSK_OFLW_ERR_DAMQ_MASK },
    { "DIAG_ONLY", AR_RTR_INQ_ERR_HSS_MSK_DIAG_ONLY_BP, AR_RTR_INQ_ERR_HSS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_err_first_flg_detail[] = {
    { "LCB_ERR", AR_RTR_INQ_ERR_FIRST_FLG_LCB_ERR_BP, AR_RTR_INQ_ERR_FIRST_FLG_LCB_ERR_MASK },
    { "COLBUF_FPT_VC7", AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_FPT_VC7_BP, AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_FPT_VC7_MASK },
    { "COLBUF_FPT_VC6", AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_FPT_VC6_BP, AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_FPT_VC6_MASK },
    { "COLBUF_FPT_VC5", AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_FPT_VC5_BP, AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_FPT_VC5_MASK },
    { "COLBUF_FPT_VC4", AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_FPT_VC4_BP, AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_FPT_VC4_MASK },
    { "COLBUF_FPT_VC3", AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_FPT_VC3_BP, AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_FPT_VC3_MASK },
    { "COLBUF_FPT_VC2", AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_FPT_VC2_BP, AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_FPT_VC2_MASK },
    { "COLBUF_FPT_VC1", AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_FPT_VC1_BP, AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_FPT_VC1_MASK },
    { "COLBUF_FPT_VC0", AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_FPT_VC0_BP, AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_FPT_VC0_MASK },
    { "COLBUF_MBE_ERR", AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_MBE_ERR_BP, AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_MBE_ERR_MASK },
    { "COLBUF_SBE_ON_TAIL", AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_SBE_ON_TAIL_BP, AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_SBE_ON_TAIL_MASK },
    { "COLBUF_SBE_ERR", AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_SBE_ERR_BP, AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_SBE_ERR_MASK },
    { "COLBUF_CRC_ERR", AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_CRC_ERR_BP, AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_CRC_ERR_MASK },
    { "COLBUF_MAX_PKT_ERR", AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_MAX_PKT_ERR_BP, AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_MAX_PKT_ERR_MASK },
    { "COLBUF_UFLW_ERR", AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_UFLW_ERR_BP, AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_UFLW_ERR_MASK },
    { "COLBUF_OFLW_ERR", AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_OFLW_ERR_BP, AR_RTR_INQ_ERR_FIRST_FLG_COLBUF_OFLW_ERR_MASK },
    { "SUBSWITCH_ERR", AR_RTR_INQ_ERR_FIRST_FLG_SUBSWITCH_ERR_BP, AR_RTR_INQ_ERR_FIRST_FLG_SUBSWITCH_ERR_MASK },
    { "LINK_ALIVE_TIMEOUT_ERR", AR_RTR_INQ_ERR_FIRST_FLG_LINK_ALIVE_TIMEOUT_ERR_BP, AR_RTR_INQ_ERR_FIRST_FLG_LINK_ALIVE_TIMEOUT_ERR_MASK },
    { "LINK_ALIVE_CHANNEL_ERR", AR_RTR_INQ_ERR_FIRST_FLG_LINK_ALIVE_CHANNEL_ERR_BP, AR_RTR_INQ_ERR_FIRST_FLG_LINK_ALIVE_CHANNEL_ERR_MASK },
    { "PRF_CNT_ROLLOVR_ERR", AR_RTR_INQ_ERR_FIRST_FLG_PRF_CNT_ROLLOVR_ERR_BP, AR_RTR_INQ_ERR_FIRST_FLG_PRF_CNT_ROLLOVR_ERR_MASK },
    { "MBE_RTABLE", AR_RTR_INQ_ERR_FIRST_FLG_MBE_RTABLE_BP, AR_RTR_INQ_ERR_FIRST_FLG_MBE_RTABLE_MASK },
    { "SBE_RTABLE", AR_RTR_INQ_ERR_FIRST_FLG_SBE_RTABLE_BP, AR_RTR_INQ_ERR_FIRST_FLG_SBE_RTABLE_MASK },
    { "ROUTE_ERROR", AR_RTR_INQ_ERR_FIRST_FLG_ROUTE_ERROR_BP, AR_RTR_INQ_ERR_FIRST_FLG_ROUTE_ERROR_MASK },
    { "PBE_VC_TABLE", AR_RTR_INQ_ERR_FIRST_FLG_PBE_VC_TABLE_BP, AR_RTR_INQ_ERR_FIRST_FLG_PBE_VC_TABLE_MASK },
    { "PBE_RFIFO_DATA", AR_RTR_INQ_ERR_FIRST_FLG_PBE_RFIFO_DATA_BP, AR_RTR_INQ_ERR_FIRST_FLG_PBE_RFIFO_DATA_MASK },
    { "PBE_RFIFO_COUNT", AR_RTR_INQ_ERR_FIRST_FLG_PBE_RFIFO_COUNT_BP, AR_RTR_INQ_ERR_FIRST_FLG_PBE_RFIFO_COUNT_MASK },
    { "PBE_OFIFO_COUNT", AR_RTR_INQ_ERR_FIRST_FLG_PBE_OFIFO_COUNT_BP, AR_RTR_INQ_ERR_FIRST_FLG_PBE_OFIFO_COUNT_MASK },
    { "PBE_DFIFO_COUNT", AR_RTR_INQ_ERR_FIRST_FLG_PBE_DFIFO_COUNT_BP, AR_RTR_INQ_ERR_FIRST_FLG_PBE_DFIFO_COUNT_MASK },
    { "INCORRECT_ACCESS_DFIFO", AR_RTR_INQ_ERR_FIRST_FLG_INCORRECT_ACCESS_DFIFO_BP, AR_RTR_INQ_ERR_FIRST_FLG_INCORRECT_ACCESS_DFIFO_MASK },
    { "UFLW_ERR_RFIFO", AR_RTR_INQ_ERR_FIRST_FLG_UFLW_ERR_RFIFO_BP, AR_RTR_INQ_ERR_FIRST_FLG_UFLW_ERR_RFIFO_MASK },
    { "UFLW_ERR_OFIFO", AR_RTR_INQ_ERR_FIRST_FLG_UFLW_ERR_OFIFO_BP, AR_RTR_INQ_ERR_FIRST_FLG_UFLW_ERR_OFIFO_MASK },
    { "UFLW_ERR_DFIFO", AR_RTR_INQ_ERR_FIRST_FLG_UFLW_ERR_DFIFO_BP, AR_RTR_INQ_ERR_FIRST_FLG_UFLW_ERR_DFIFO_MASK },
    { "OFLW_ERR_RFIFO", AR_RTR_INQ_ERR_FIRST_FLG_OFLW_ERR_RFIFO_BP, AR_RTR_INQ_ERR_FIRST_FLG_OFLW_ERR_RFIFO_MASK },
    { "OFLW_ERR_OFIFO", AR_RTR_INQ_ERR_FIRST_FLG_OFLW_ERR_OFIFO_BP, AR_RTR_INQ_ERR_FIRST_FLG_OFLW_ERR_OFIFO_MASK },
    { "OFLW_ERR_DFIFO", AR_RTR_INQ_ERR_FIRST_FLG_OFLW_ERR_DFIFO_BP, AR_RTR_INQ_ERR_FIRST_FLG_OFLW_ERR_DFIFO_MASK },
    { "ERR_RD_WRONG_VC_BLK_DAMQ", AR_RTR_INQ_ERR_FIRST_FLG_ERR_RD_WRONG_VC_BLK_DAMQ_BP, AR_RTR_INQ_ERR_FIRST_FLG_ERR_RD_WRONG_VC_BLK_DAMQ_MASK },
    { "ERR_DEALLOC_IDLE_BLK_DAMQ", AR_RTR_INQ_ERR_FIRST_FLG_ERR_DEALLOC_IDLE_BLK_DAMQ_BP, AR_RTR_INQ_ERR_FIRST_FLG_ERR_DEALLOC_IDLE_BLK_DAMQ_MASK },
    { "ERR_ALLOC_INUSE_BLK_DAMQ", AR_RTR_INQ_ERR_FIRST_FLG_ERR_ALLOC_INUSE_BLK_DAMQ_BP, AR_RTR_INQ_ERR_FIRST_FLG_ERR_ALLOC_INUSE_BLK_DAMQ_MASK },
    { "ERR_WR_NON_ALLOC_BLK_DAMQ", AR_RTR_INQ_ERR_FIRST_FLG_ERR_WR_NON_ALLOC_BLK_DAMQ_BP, AR_RTR_INQ_ERR_FIRST_FLG_ERR_WR_NON_ALLOC_BLK_DAMQ_MASK },
    { "ERR_RD_NON_ALLOC_BLK_DAMQ", AR_RTR_INQ_ERR_FIRST_FLG_ERR_RD_NON_ALLOC_BLK_DAMQ_BP, AR_RTR_INQ_ERR_FIRST_FLG_ERR_RD_NON_ALLOC_BLK_DAMQ_MASK },
    { "PBE_CNT_DAMQ", AR_RTR_INQ_ERR_FIRST_FLG_PBE_CNT_DAMQ_BP, AR_RTR_INQ_ERR_FIRST_FLG_PBE_CNT_DAMQ_MASK },
    { "PBE_PTR_DAMQ", AR_RTR_INQ_ERR_FIRST_FLG_PBE_PTR_DAMQ_BP, AR_RTR_INQ_ERR_FIRST_FLG_PBE_PTR_DAMQ_MASK },
    { "MBE_DAMQ", AR_RTR_INQ_ERR_FIRST_FLG_MBE_DAMQ_BP, AR_RTR_INQ_ERR_FIRST_FLG_MBE_DAMQ_MASK },
    { "SBE_DAMQ", AR_RTR_INQ_ERR_FIRST_FLG_SBE_DAMQ_BP, AR_RTR_INQ_ERR_FIRST_FLG_SBE_DAMQ_MASK },
    { "UFLW_ERR_DAMQ", AR_RTR_INQ_ERR_FIRST_FLG_UFLW_ERR_DAMQ_BP, AR_RTR_INQ_ERR_FIRST_FLG_UFLW_ERR_DAMQ_MASK },
    { "OFLW_ERR_DAMQ", AR_RTR_INQ_ERR_FIRST_FLG_OFLW_ERR_DAMQ_BP, AR_RTR_INQ_ERR_FIRST_FLG_OFLW_ERR_DAMQ_MASK },
    { "DIAG_ONLY", AR_RTR_INQ_ERR_FIRST_FLG_DIAG_ONLY_BP, AR_RTR_INQ_ERR_FIRST_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_dbg_errinj_rtable_detail[] = {
    { "ADDRESS", AR_RTR_INQ_DBG_ERRINJ_RTABLE_ADDRESS_BP, AR_RTR_INQ_DBG_ERRINJ_RTABLE_ADDRESS_MASK },
    { "CHECKBYTE", AR_RTR_INQ_DBG_ERRINJ_RTABLE_CHECKBYTE_BP, AR_RTR_INQ_DBG_ERRINJ_RTABLE_CHECKBYTE_MASK },
    { "RAMSELECT", AR_RTR_INQ_DBG_ERRINJ_RTABLE_RAMSELECT_BP, AR_RTR_INQ_DBG_ERRINJ_RTABLE_RAMSELECT_MASK },
    { "TRIGGERED", AR_RTR_INQ_DBG_ERRINJ_RTABLE_TRIGGERED_BP, AR_RTR_INQ_DBG_ERRINJ_RTABLE_TRIGGERED_MASK },
    { "MODE", AR_RTR_INQ_DBG_ERRINJ_RTABLE_MODE_BP, AR_RTR_INQ_DBG_ERRINJ_RTABLE_MODE_MASK },
    { "ENABLE", AR_RTR_INQ_DBG_ERRINJ_RTABLE_ENABLE_BP, AR_RTR_INQ_DBG_ERRINJ_RTABLE_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_err_info_rtable_detail[] = {
    { "MBE_RAM_NUM", AR_RTR_INQ_ERR_INFO_RTABLE_MBE_RAM_NUM_BP, AR_RTR_INQ_ERR_INFO_RTABLE_MBE_RAM_NUM_MASK },
    { "MBE_ADDRESS", AR_RTR_INQ_ERR_INFO_RTABLE_MBE_ADDRESS_BP, AR_RTR_INQ_ERR_INFO_RTABLE_MBE_ADDRESS_MASK },
    { "MBE_SYNDROME", AR_RTR_INQ_ERR_INFO_RTABLE_MBE_SYNDROME_BP, AR_RTR_INQ_ERR_INFO_RTABLE_MBE_SYNDROME_MASK },
    { "SBE_RAM_NUM", AR_RTR_INQ_ERR_INFO_RTABLE_SBE_RAM_NUM_BP, AR_RTR_INQ_ERR_INFO_RTABLE_SBE_RAM_NUM_MASK },
    { "SBE_ADDRESS", AR_RTR_INQ_ERR_INFO_RTABLE_SBE_ADDRESS_BP, AR_RTR_INQ_ERR_INFO_RTABLE_SBE_ADDRESS_MASK },
    { "SBE_SYNDROME", AR_RTR_INQ_ERR_INFO_RTABLE_SBE_SYNDROME_BP, AR_RTR_INQ_ERR_INFO_RTABLE_SBE_SYNDROME_MASK },
    { "MMR_DETECTED_MBE", AR_RTR_INQ_ERR_INFO_RTABLE_MMR_DETECTED_MBE_BP, AR_RTR_INQ_ERR_INFO_RTABLE_MMR_DETECTED_MBE_MASK },
    { "MMR_DETECTED_SBE", AR_RTR_INQ_ERR_INFO_RTABLE_MMR_DETECTED_SBE_BP, AR_RTR_INQ_ERR_INFO_RTABLE_MMR_DETECTED_SBE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_err_info_cnt_sbe_rtable_detail[] = {
    { "SBE_COUNT", AR_RTR_INQ_ERR_INFO_CNT_SBE_RTABLE_SBE_COUNT_BP, AR_RTR_INQ_ERR_INFO_CNT_SBE_RTABLE_SBE_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_err_info_cnt_mbe_rtable_detail[] = {
    { "MBE_COUNT", AR_RTR_INQ_ERR_INFO_CNT_MBE_RTABLE_MBE_COUNT_BP, AR_RTR_INQ_ERR_INFO_CNT_MBE_RTABLE_MBE_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_err_info_routing_detail[] = {
    { "ROUTE_ERR_TYPE", AR_RTR_INQ_ERR_INFO_ROUTING_ROUTE_ERR_TYPE_BP, AR_RTR_INQ_ERR_INFO_ROUTING_ROUTE_ERR_TYPE_MASK },
    { "RTABLE_ADDRESS", AR_RTR_INQ_ERR_INFO_ROUTING_RTABLE_ADDRESS_BP, AR_RTR_INQ_ERR_INFO_ROUTING_RTABLE_ADDRESS_MASK },
    { "ROUTE_TABLE", AR_RTR_INQ_ERR_INFO_ROUTING_ROUTE_TABLE_BP, AR_RTR_INQ_ERR_INFO_ROUTING_ROUTE_TABLE_MASK },
    { "ROUTE_HEAD", AR_RTR_INQ_ERR_INFO_ROUTING_ROUTE_HEAD_BP, AR_RTR_INQ_ERR_INFO_ROUTING_ROUTE_HEAD_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_err_info_damq_detail[] = {
    { "VC_WITH_ERR", AR_RTR_INQ_ERR_INFO_DAMQ_VC_WITH_ERR_BP, AR_RTR_INQ_ERR_INFO_DAMQ_VC_WITH_ERR_MASK },
    { "HEADER_MBE", AR_RTR_INQ_ERR_INFO_DAMQ_HEADER_MBE_BP, AR_RTR_INQ_ERR_INFO_DAMQ_HEADER_MBE_MASK },
    { "MBE_VC", AR_RTR_INQ_ERR_INFO_DAMQ_MBE_VC_BP, AR_RTR_INQ_ERR_INFO_DAMQ_MBE_VC_MASK },
    { "SBE_VC", AR_RTR_INQ_ERR_INFO_DAMQ_SBE_VC_BP, AR_RTR_INQ_ERR_INFO_DAMQ_SBE_VC_MASK },
    { "MBE_RAM_NUM", AR_RTR_INQ_ERR_INFO_DAMQ_MBE_RAM_NUM_BP, AR_RTR_INQ_ERR_INFO_DAMQ_MBE_RAM_NUM_MASK },
    { "MBE_ADDRESS", AR_RTR_INQ_ERR_INFO_DAMQ_MBE_ADDRESS_BP, AR_RTR_INQ_ERR_INFO_DAMQ_MBE_ADDRESS_MASK },
    { "MBE_SYNDROME", AR_RTR_INQ_ERR_INFO_DAMQ_MBE_SYNDROME_BP, AR_RTR_INQ_ERR_INFO_DAMQ_MBE_SYNDROME_MASK },
    { "SBE_RAM_NUM", AR_RTR_INQ_ERR_INFO_DAMQ_SBE_RAM_NUM_BP, AR_RTR_INQ_ERR_INFO_DAMQ_SBE_RAM_NUM_MASK },
    { "SBE_ADDRESS", AR_RTR_INQ_ERR_INFO_DAMQ_SBE_ADDRESS_BP, AR_RTR_INQ_ERR_INFO_DAMQ_SBE_ADDRESS_MASK },
    { "SBE_SYNDROME", AR_RTR_INQ_ERR_INFO_DAMQ_SBE_SYNDROME_BP, AR_RTR_INQ_ERR_INFO_DAMQ_SBE_SYNDROME_MASK },
    { "MMR_DETECTED_MBE", AR_RTR_INQ_ERR_INFO_DAMQ_MMR_DETECTED_MBE_BP, AR_RTR_INQ_ERR_INFO_DAMQ_MMR_DETECTED_MBE_MASK },
    { "MMR_DETECTED_SBE", AR_RTR_INQ_ERR_INFO_DAMQ_MMR_DETECTED_SBE_BP, AR_RTR_INQ_ERR_INFO_DAMQ_MMR_DETECTED_SBE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_err_info_cnt_sbe_damq_detail[] = {
    { "SBE_COUNT", AR_RTR_INQ_ERR_INFO_CNT_SBE_DAMQ_SBE_COUNT_BP, AR_RTR_INQ_ERR_INFO_CNT_SBE_DAMQ_SBE_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_err_info_cnt_mbe_damq_detail[] = {
    { "MBE_COUNT", AR_RTR_INQ_ERR_INFO_CNT_MBE_DAMQ_MBE_COUNT_BP, AR_RTR_INQ_ERR_INFO_CNT_MBE_DAMQ_MBE_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_incoming_flit_vc0_detail[] = {
    { "COUNT", AR_RTR_INQ_PRF_INCOMING_FLIT_VC0_COUNT_BP, AR_RTR_INQ_PRF_INCOMING_FLIT_VC0_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_incoming_flit_vc1_detail[] = {
    { "COUNT", AR_RTR_INQ_PRF_INCOMING_FLIT_VC1_COUNT_BP, AR_RTR_INQ_PRF_INCOMING_FLIT_VC1_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_incoming_flit_vc2_detail[] = {
    { "COUNT", AR_RTR_INQ_PRF_INCOMING_FLIT_VC2_COUNT_BP, AR_RTR_INQ_PRF_INCOMING_FLIT_VC2_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_incoming_flit_vc3_detail[] = {
    { "COUNT", AR_RTR_INQ_PRF_INCOMING_FLIT_VC3_COUNT_BP, AR_RTR_INQ_PRF_INCOMING_FLIT_VC3_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_incoming_flit_vc4_detail[] = {
    { "COUNT", AR_RTR_INQ_PRF_INCOMING_FLIT_VC4_COUNT_BP, AR_RTR_INQ_PRF_INCOMING_FLIT_VC4_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_incoming_flit_vc5_detail[] = {
    { "COUNT", AR_RTR_INQ_PRF_INCOMING_FLIT_VC5_COUNT_BP, AR_RTR_INQ_PRF_INCOMING_FLIT_VC5_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_incoming_flit_vc6_detail[] = {
    { "COUNT", AR_RTR_INQ_PRF_INCOMING_FLIT_VC6_COUNT_BP, AR_RTR_INQ_PRF_INCOMING_FLIT_VC6_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_incoming_flit_vc7_detail[] = {
    { "COUNT", AR_RTR_INQ_PRF_INCOMING_FLIT_VC7_COUNT_BP, AR_RTR_INQ_PRF_INCOMING_FLIT_VC7_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_flit0_filtering_setup_detail[] = {
    { "ENABLE", AR_RTR_INQ_PRF_FLIT0_FILTERING_SETUP_ENABLE_BP, AR_RTR_INQ_PRF_FLIT0_FILTERING_SETUP_ENABLE_MASK },
    { "FLIT_PTR", AR_RTR_INQ_PRF_FLIT0_FILTERING_SETUP_FLIT_PTR_BP, AR_RTR_INQ_PRF_FLIT0_FILTERING_SETUP_FLIT_PTR_MASK },
    { "COMPARE_PATTERN", AR_RTR_INQ_PRF_FLIT0_FILTERING_SETUP_COMPARE_PATTERN_BP, AR_RTR_INQ_PRF_FLIT0_FILTERING_SETUP_COMPARE_PATTERN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_flit0_filtering_mask_detail[] = {
    { "MASK", AR_RTR_INQ_PRF_FLIT0_FILTERING_MASK_MASK_BP, AR_RTR_INQ_PRF_FLIT0_FILTERING_MASK_MASK_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_flit1_filtering_setup_detail[] = {
    { "ENABLE", AR_RTR_INQ_PRF_FLIT1_FILTERING_SETUP_ENABLE_BP, AR_RTR_INQ_PRF_FLIT1_FILTERING_SETUP_ENABLE_MASK },
    { "FLIT_PTR", AR_RTR_INQ_PRF_FLIT1_FILTERING_SETUP_FLIT_PTR_BP, AR_RTR_INQ_PRF_FLIT1_FILTERING_SETUP_FLIT_PTR_MASK },
    { "COMPARE_PATTERN", AR_RTR_INQ_PRF_FLIT1_FILTERING_SETUP_COMPARE_PATTERN_BP, AR_RTR_INQ_PRF_FLIT1_FILTERING_SETUP_COMPARE_PATTERN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_flit1_filtering_mask_detail[] = {
    { "MASK", AR_RTR_INQ_PRF_FLIT1_FILTERING_MASK_MASK_BP, AR_RTR_INQ_PRF_FLIT1_FILTERING_MASK_MASK_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_flit2_filtering_setup_detail[] = {
    { "ENABLE", AR_RTR_INQ_PRF_FLIT2_FILTERING_SETUP_ENABLE_BP, AR_RTR_INQ_PRF_FLIT2_FILTERING_SETUP_ENABLE_MASK },
    { "FLIT_PTR", AR_RTR_INQ_PRF_FLIT2_FILTERING_SETUP_FLIT_PTR_BP, AR_RTR_INQ_PRF_FLIT2_FILTERING_SETUP_FLIT_PTR_MASK },
    { "COMPARE_PATTERN", AR_RTR_INQ_PRF_FLIT2_FILTERING_SETUP_COMPARE_PATTERN_BP, AR_RTR_INQ_PRF_FLIT2_FILTERING_SETUP_COMPARE_PATTERN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_flit2_filtering_mask_detail[] = {
    { "MASK", AR_RTR_INQ_PRF_FLIT2_FILTERING_MASK_MASK_BP, AR_RTR_INQ_PRF_FLIT2_FILTERING_MASK_MASK_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_flit3_filtering_setup_detail[] = {
    { "ENABLE", AR_RTR_INQ_PRF_FLIT3_FILTERING_SETUP_ENABLE_BP, AR_RTR_INQ_PRF_FLIT3_FILTERING_SETUP_ENABLE_MASK },
    { "FLIT_PTR", AR_RTR_INQ_PRF_FLIT3_FILTERING_SETUP_FLIT_PTR_BP, AR_RTR_INQ_PRF_FLIT3_FILTERING_SETUP_FLIT_PTR_MASK },
    { "COMPARE_PATTERN", AR_RTR_INQ_PRF_FLIT3_FILTERING_SETUP_COMPARE_PATTERN_BP, AR_RTR_INQ_PRF_FLIT3_FILTERING_SETUP_COMPARE_PATTERN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_flit3_filtering_mask_detail[] = {
    { "MASK", AR_RTR_INQ_PRF_FLIT3_FILTERING_MASK_MASK_BP, AR_RTR_INQ_PRF_FLIT3_FILTERING_MASK_MASK_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_flit4_filtering_setup_detail[] = {
    { "ENABLE", AR_RTR_INQ_PRF_FLIT4_FILTERING_SETUP_ENABLE_BP, AR_RTR_INQ_PRF_FLIT4_FILTERING_SETUP_ENABLE_MASK },
    { "FLIT_PTR", AR_RTR_INQ_PRF_FLIT4_FILTERING_SETUP_FLIT_PTR_BP, AR_RTR_INQ_PRF_FLIT4_FILTERING_SETUP_FLIT_PTR_MASK },
    { "COMPARE_PATTERN", AR_RTR_INQ_PRF_FLIT4_FILTERING_SETUP_COMPARE_PATTERN_BP, AR_RTR_INQ_PRF_FLIT4_FILTERING_SETUP_COMPARE_PATTERN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_flit4_filtering_mask_detail[] = {
    { "MASK", AR_RTR_INQ_PRF_FLIT4_FILTERING_MASK_MASK_BP, AR_RTR_INQ_PRF_FLIT4_FILTERING_MASK_MASK_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_flit5_filtering_setup_detail[] = {
    { "ENABLE", AR_RTR_INQ_PRF_FLIT5_FILTERING_SETUP_ENABLE_BP, AR_RTR_INQ_PRF_FLIT5_FILTERING_SETUP_ENABLE_MASK },
    { "FLIT_PTR", AR_RTR_INQ_PRF_FLIT5_FILTERING_SETUP_FLIT_PTR_BP, AR_RTR_INQ_PRF_FLIT5_FILTERING_SETUP_FLIT_PTR_MASK },
    { "COMPARE_PATTERN", AR_RTR_INQ_PRF_FLIT5_FILTERING_SETUP_COMPARE_PATTERN_BP, AR_RTR_INQ_PRF_FLIT5_FILTERING_SETUP_COMPARE_PATTERN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_flit5_filtering_mask_detail[] = {
    { "MASK", AR_RTR_INQ_PRF_FLIT5_FILTERING_MASK_MASK_BP, AR_RTR_INQ_PRF_FLIT5_FILTERING_MASK_MASK_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_flit6_filtering_setup_detail[] = {
    { "ENABLE", AR_RTR_INQ_PRF_FLIT6_FILTERING_SETUP_ENABLE_BP, AR_RTR_INQ_PRF_FLIT6_FILTERING_SETUP_ENABLE_MASK },
    { "FLIT_PTR", AR_RTR_INQ_PRF_FLIT6_FILTERING_SETUP_FLIT_PTR_BP, AR_RTR_INQ_PRF_FLIT6_FILTERING_SETUP_FLIT_PTR_MASK },
    { "COMPARE_PATTERN", AR_RTR_INQ_PRF_FLIT6_FILTERING_SETUP_COMPARE_PATTERN_BP, AR_RTR_INQ_PRF_FLIT6_FILTERING_SETUP_COMPARE_PATTERN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_flit6_filtering_mask_detail[] = {
    { "MASK", AR_RTR_INQ_PRF_FLIT6_FILTERING_MASK_MASK_BP, AR_RTR_INQ_PRF_FLIT6_FILTERING_MASK_MASK_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_flit7_filtering_setup_detail[] = {
    { "ENABLE", AR_RTR_INQ_PRF_FLIT7_FILTERING_SETUP_ENABLE_BP, AR_RTR_INQ_PRF_FLIT7_FILTERING_SETUP_ENABLE_MASK },
    { "FLIT_PTR", AR_RTR_INQ_PRF_FLIT7_FILTERING_SETUP_FLIT_PTR_BP, AR_RTR_INQ_PRF_FLIT7_FILTERING_SETUP_FLIT_PTR_MASK },
    { "COMPARE_PATTERN", AR_RTR_INQ_PRF_FLIT7_FILTERING_SETUP_COMPARE_PATTERN_BP, AR_RTR_INQ_PRF_FLIT7_FILTERING_SETUP_COMPARE_PATTERN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_flit7_filtering_mask_detail[] = {
    { "MASK", AR_RTR_INQ_PRF_FLIT7_FILTERING_MASK_MASK_BP, AR_RTR_INQ_PRF_FLIT7_FILTERING_MASK_MASK_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_incoming_pkt_vc0_filter_flit0_cnt_detail[] = {
    { "COUNT", AR_RTR_INQ_PRF_INCOMING_PKT_VC0_FILTER_FLIT0_CNT_COUNT_BP, AR_RTR_INQ_PRF_INCOMING_PKT_VC0_FILTER_FLIT0_CNT_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_incoming_pkt_vc1_filter_flit1_cnt_detail[] = {
    { "COUNT", AR_RTR_INQ_PRF_INCOMING_PKT_VC1_FILTER_FLIT1_CNT_COUNT_BP, AR_RTR_INQ_PRF_INCOMING_PKT_VC1_FILTER_FLIT1_CNT_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_incoming_pkt_vc2_filter_flit2_cnt_detail[] = {
    { "COUNT", AR_RTR_INQ_PRF_INCOMING_PKT_VC2_FILTER_FLIT2_CNT_COUNT_BP, AR_RTR_INQ_PRF_INCOMING_PKT_VC2_FILTER_FLIT2_CNT_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_incoming_pkt_vc3_filter_flit3_cnt_detail[] = {
    { "COUNT", AR_RTR_INQ_PRF_INCOMING_PKT_VC3_FILTER_FLIT3_CNT_COUNT_BP, AR_RTR_INQ_PRF_INCOMING_PKT_VC3_FILTER_FLIT3_CNT_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_incoming_pkt_vc4_filter_flit4_cnt_detail[] = {
    { "COUNT", AR_RTR_INQ_PRF_INCOMING_PKT_VC4_FILTER_FLIT4_CNT_COUNT_BP, AR_RTR_INQ_PRF_INCOMING_PKT_VC4_FILTER_FLIT4_CNT_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_incoming_pkt_vc5_filter_flit5_cnt_detail[] = {
    { "COUNT", AR_RTR_INQ_PRF_INCOMING_PKT_VC5_FILTER_FLIT5_CNT_COUNT_BP, AR_RTR_INQ_PRF_INCOMING_PKT_VC5_FILTER_FLIT5_CNT_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_incoming_pkt_vc6_filter_flit6_cnt_detail[] = {
    { "COUNT", AR_RTR_INQ_PRF_INCOMING_PKT_VC6_FILTER_FLIT6_CNT_COUNT_BP, AR_RTR_INQ_PRF_INCOMING_PKT_VC6_FILTER_FLIT6_CNT_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_incoming_pkt_vc7_filter_flit7_cnt_detail[] = {
    { "COUNT", AR_RTR_INQ_PRF_INCOMING_PKT_VC7_FILTER_FLIT7_CNT_COUNT_BP, AR_RTR_INQ_PRF_INCOMING_PKT_VC7_FILTER_FLIT7_CNT_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_match_flit_3_to_0_filtering_cnt_detail[] = {
    { "FLIT_CNT", AR_RTR_INQ_PRF_MATCH_FLIT_3_TO_0_FILTERING_CNT_FLIT_CNT_BP, AR_RTR_INQ_PRF_MATCH_FLIT_3_TO_0_FILTERING_CNT_FLIT_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_match_flit_7_to_4_filtering_cnt_detail[] = {
    { "FLIT_CNT", AR_RTR_INQ_PRF_MATCH_FLIT_7_TO_4_FILTERING_CNT_FLIT_CNT_BP, AR_RTR_INQ_PRF_MATCH_FLIT_7_TO_4_FILTERING_CNT_FLIT_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_rowbus_stall_cnt_detail[] = {
    { "ROWBUS_STALL_CNT", AR_RTR_INQ_PRF_ROWBUS_STALL_CNT_ROWBUS_STALL_CNT_BP, AR_RTR_INQ_PRF_ROWBUS_STALL_CNT_ROWBUS_STALL_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_rowbus_2x_usage_cnt_detail[] = {
    { "ROWBUS_2X_USAGE_CNT", AR_RTR_INQ_PRF_ROWBUS_2X_USAGE_CNT_ROWBUS_2X_USAGE_CNT_BP, AR_RTR_INQ_PRF_ROWBUS_2X_USAGE_CNT_ROWBUS_2X_USAGE_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_inq_prf_pkt_to_dead_link_cnt_detail[] = {
    { "PKT_TO_DEAD_LINK_CNT", AR_RTR_INQ_PRF_PKT_TO_DEAD_LINK_CNT_PKT_TO_DEAD_LINK_CNT_BP, AR_RTR_INQ_PRF_PKT_TO_DEAD_LINK_CNT_PKT_TO_DEAD_LINK_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_subswitch_cfg_colbuf_crdts_detail[] = {
    { "RD_CRDT_USED_CNT_VC7", AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC7_BP, AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC7_MASK },
    { "RD_CRDT_USED_CNT_VC6", AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC6_BP, AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC6_MASK },
    { "RD_CRDT_USED_CNT_VC5", AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC5_BP, AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC5_MASK },
    { "RD_CRDT_USED_CNT_VC4", AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC4_BP, AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC4_MASK },
    { "RD_CRDT_USED_CNT_VC3", AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC3_BP, AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC3_MASK },
    { "RD_CRDT_USED_CNT_VC2", AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC2_BP, AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC2_MASK },
    { "RD_CRDT_USED_CNT_VC1", AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC1_BP, AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC1_MASK },
    { "RD_CRDT_USED_CNT_VC0", AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC0_BP, AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC0_MASK },
    { "WR_MAX_FLIT_CREDITS_EN", AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_WR_MAX_FLIT_CREDITS_EN_BP, AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_WR_MAX_FLIT_CREDITS_EN_MASK },
    { "WR_MAX_FLIT_CREDITS", AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_WR_MAX_FLIT_CREDITS_BP, AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_WR_MAX_FLIT_CREDITS_MASK },
    { "VC_NUMBER", AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_VC_NUMBER_BP, AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_VC_NUMBER_MASK },
    { "COLUMN_NUMBER", AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_COLUMN_NUMBER_BP, AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS_COLUMN_NUMBER_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_subswitch_err_info_detail[] = {
    { "ERR_MULTIPLE_SECT7", AR_RTR_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT7_BP, AR_RTR_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT7_MASK },
    { "ERR_TYPE_SECT7", AR_RTR_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT7_BP, AR_RTR_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT7_MASK },
    { "VC_SECT7", AR_RTR_SUBSWITCH_ERR_INFO_VC_SECT7_BP, AR_RTR_SUBSWITCH_ERR_INFO_VC_SECT7_MASK },
    { "ERR_MULTIPLE_SECT6", AR_RTR_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT6_BP, AR_RTR_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT6_MASK },
    { "ERR_TYPE_SECT6", AR_RTR_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT6_BP, AR_RTR_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT6_MASK },
    { "VC_SECT6", AR_RTR_SUBSWITCH_ERR_INFO_VC_SECT6_BP, AR_RTR_SUBSWITCH_ERR_INFO_VC_SECT6_MASK },
    { "ERR_MULTIPLE_SECT5", AR_RTR_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT5_BP, AR_RTR_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT5_MASK },
    { "ERR_TYPE_SECT5", AR_RTR_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT5_BP, AR_RTR_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT5_MASK },
    { "VC_SECT5", AR_RTR_SUBSWITCH_ERR_INFO_VC_SECT5_BP, AR_RTR_SUBSWITCH_ERR_INFO_VC_SECT5_MASK },
    { "ERR_MULTIPLE_SECT4", AR_RTR_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT4_BP, AR_RTR_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT4_MASK },
    { "ERR_TYPE_SECT4", AR_RTR_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT4_BP, AR_RTR_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT4_MASK },
    { "VC_SECT4", AR_RTR_SUBSWITCH_ERR_INFO_VC_SECT4_BP, AR_RTR_SUBSWITCH_ERR_INFO_VC_SECT4_MASK },
    { "ERR_MULTIPLE_SECT3", AR_RTR_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT3_BP, AR_RTR_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT3_MASK },
    { "ERR_TYPE_SECT3", AR_RTR_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT3_BP, AR_RTR_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT3_MASK },
    { "VC_SECT3", AR_RTR_SUBSWITCH_ERR_INFO_VC_SECT3_BP, AR_RTR_SUBSWITCH_ERR_INFO_VC_SECT3_MASK },
    { "ERR_MULTIPLE_SECT2", AR_RTR_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT2_BP, AR_RTR_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT2_MASK },
    { "ERR_TYPE_SECT2", AR_RTR_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT2_BP, AR_RTR_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT2_MASK },
    { "VC_SECT2", AR_RTR_SUBSWITCH_ERR_INFO_VC_SECT2_BP, AR_RTR_SUBSWITCH_ERR_INFO_VC_SECT2_MASK },
    { "ERR_MULTIPLE_SECT1", AR_RTR_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT1_BP, AR_RTR_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT1_MASK },
    { "ERR_TYPE_SECT1", AR_RTR_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT1_BP, AR_RTR_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT1_MASK },
    { "VC_SECT1", AR_RTR_SUBSWITCH_ERR_INFO_VC_SECT1_BP, AR_RTR_SUBSWITCH_ERR_INFO_VC_SECT1_MASK },
    { "ERR_MULTIPLE_SECT0", AR_RTR_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT0_BP, AR_RTR_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT0_MASK },
    { "ERR_TYPE_SECT0", AR_RTR_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT0_BP, AR_RTR_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT0_MASK },
    { "VC_SECT0", AR_RTR_SUBSWITCH_ERR_INFO_VC_SECT0_BP, AR_RTR_SUBSWITCH_ERR_INFO_VC_SECT0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_subswitch_err_mask_detail[] = {
    { "MASK_CREDIT_UFLOW", AR_RTR_SUBSWITCH_ERR_MASK_MASK_CREDIT_UFLOW_BP, AR_RTR_SUBSWITCH_ERR_MASK_MASK_CREDIT_UFLOW_MASK },
    { "MASK_BUFFER_UFLOW", AR_RTR_SUBSWITCH_ERR_MASK_MASK_BUFFER_UFLOW_BP, AR_RTR_SUBSWITCH_ERR_MASK_MASK_BUFFER_UFLOW_MASK },
    { "MASK_BUFFER_OFLOW", AR_RTR_SUBSWITCH_ERR_MASK_MASK_BUFFER_OFLOW_BP, AR_RTR_SUBSWITCH_ERR_MASK_MASK_BUFFER_OFLOW_MASK },
    { "MASK_BAD_TVC_PT_ERR", AR_RTR_SUBSWITCH_ERR_MASK_MASK_BAD_TVC_PT_ERR_BP, AR_RTR_SUBSWITCH_ERR_MASK_MASK_BAD_TVC_PT_ERR_MASK },
    { "MASK_BAD_TVC_ERR", AR_RTR_SUBSWITCH_ERR_MASK_MASK_BAD_TVC_ERR_BP, AR_RTR_SUBSWITCH_ERR_MASK_MASK_BAD_TVC_ERR_MASK },
    { "MASK_EMPTY_ROUTE_ERR", AR_RTR_SUBSWITCH_ERR_MASK_MASK_EMPTY_ROUTE_ERR_BP, AR_RTR_SUBSWITCH_ERR_MASK_MASK_EMPTY_ROUTE_ERR_MASK },
    { "MASK_INVALID_ROUTE_ERR", AR_RTR_SUBSWITCH_ERR_MASK_MASK_INVALID_ROUTE_ERR_BP, AR_RTR_SUBSWITCH_ERR_MASK_MASK_INVALID_ROUTE_ERR_MASK },
    { "MASK_FLIT_ROUTE_HEAD_PARITY_ERR", AR_RTR_SUBSWITCH_ERR_MASK_MASK_FLIT_ROUTE_HEAD_PARITY_ERR_BP, AR_RTR_SUBSWITCH_ERR_MASK_MASK_FLIT_ROUTE_HEAD_PARITY_ERR_MASK },
    { "MASK_FLIT_ROUTE_IN_PARITY_ERR", AR_RTR_SUBSWITCH_ERR_MASK_MASK_FLIT_ROUTE_IN_PARITY_ERR_BP, AR_RTR_SUBSWITCH_ERR_MASK_MASK_FLIT_ROUTE_IN_PARITY_ERR_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_colbuf_cfg_crdts_channel_detail[] = {
    { "MAX_PACKET_SZ", AR_RTR_COLBUF_CFG_CRDTS_CHANNEL_MAX_PACKET_SZ_BP, AR_RTR_COLBUF_CFG_CRDTS_CHANNEL_MAX_PACKET_SZ_MASK },
    { "LCB_CRDT_LIMIT", AR_RTR_COLBUF_CFG_CRDTS_CHANNEL_LCB_CRDT_LIMIT_BP, AR_RTR_COLBUF_CFG_CRDTS_CHANNEL_LCB_CRDT_LIMIT_MASK },
    { "UPDATE_CRDT_LIMIT", AR_RTR_COLBUF_CFG_CRDTS_CHANNEL_UPDATE_CRDT_LIMIT_BP, AR_RTR_COLBUF_CFG_CRDTS_CHANNEL_UPDATE_CRDT_LIMIT_MASK },
    { "VC_PTR", AR_RTR_COLBUF_CFG_CRDTS_CHANNEL_VC_PTR_BP, AR_RTR_COLBUF_CFG_CRDTS_CHANNEL_VC_PTR_MASK },
    { "FLITS_SENT", AR_RTR_COLBUF_CFG_CRDTS_CHANNEL_FLITS_SENT_BP, AR_RTR_COLBUF_CFG_CRDTS_CHANNEL_FLITS_SENT_MASK },
    { "ALLOCATED_TO_SHARED_USED", AR_RTR_COLBUF_CFG_CRDTS_CHANNEL_ALLOCATED_TO_SHARED_USED_BP, AR_RTR_COLBUF_CFG_CRDTS_CHANNEL_ALLOCATED_TO_SHARED_USED_MASK },
    { "SHARED_BLKS_USED", AR_RTR_COLBUF_CFG_CRDTS_CHANNEL_SHARED_BLKS_USED_BP, AR_RTR_COLBUF_CFG_CRDTS_CHANNEL_SHARED_BLKS_USED_MASK },
    { "PRIVATE_BLKS_USED", AR_RTR_COLBUF_CFG_CRDTS_CHANNEL_PRIVATE_BLKS_USED_BP, AR_RTR_COLBUF_CFG_CRDTS_CHANNEL_PRIVATE_BLKS_USED_MASK },
    { "ALLOC_TO_SHARED_CRDT_LIMIT", AR_RTR_COLBUF_CFG_CRDTS_CHANNEL_ALLOC_TO_SHARED_CRDT_LIMIT_BP, AR_RTR_COLBUF_CFG_CRDTS_CHANNEL_ALLOC_TO_SHARED_CRDT_LIMIT_MASK },
    { "SHARED_CRDT_LIMIT", AR_RTR_COLBUF_CFG_CRDTS_CHANNEL_SHARED_CRDT_LIMIT_BP, AR_RTR_COLBUF_CFG_CRDTS_CHANNEL_SHARED_CRDT_LIMIT_MASK },
    { "PRIVATE_CRDT_LIMIT", AR_RTR_COLBUF_CFG_CRDTS_CHANNEL_PRIVATE_CRDT_LIMIT_BP, AR_RTR_COLBUF_CFG_CRDTS_CHANNEL_PRIVATE_CRDT_LIMIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_colbuf_cfg_fpt_detail[] = {
    { "FPT_CNTRL", AR_RTR_COLBUF_CFG_FPT_FPT_CNTRL_BP, AR_RTR_COLBUF_CFG_FPT_FPT_CNTRL_MASK },
    { "FPT_TIMER", AR_RTR_COLBUF_CFG_FPT_FPT_TIMER_BP, AR_RTR_COLBUF_CFG_FPT_FPT_TIMER_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_colbuf_cfg_congest_cntl_detail[] = {
    { "DIAG_MODE", AR_RTR_COLBUF_CFG_CONGEST_CNTL_DIAG_MODE_BP, AR_RTR_COLBUF_CFG_CONGEST_CNTL_DIAG_MODE_MASK },
    { "STEP_FAR_END_LINK_DELAY", AR_RTR_COLBUF_CFG_CONGEST_CNTL_STEP_FAR_END_LINK_DELAY_BP, AR_RTR_COLBUF_CFG_CONGEST_CNTL_STEP_FAR_END_LINK_DELAY_MASK },
    { "DELAY_PIPE_TAP", AR_RTR_COLBUF_CFG_CONGEST_CNTL_DELAY_PIPE_TAP_BP, AR_RTR_COLBUF_CFG_CONGEST_CNTL_DELAY_PIPE_TAP_MASK },
    { "DELAY_PIPE_SHIFT", AR_RTR_COLBUF_CFG_CONGEST_CNTL_DELAY_PIPE_SHIFT_BP, AR_RTR_COLBUF_CFG_CONGEST_CNTL_DELAY_PIPE_SHIFT_MASK },
    { "UPPER_THRESHOLD", AR_RTR_COLBUF_CFG_CONGEST_CNTL_UPPER_THRESHOLD_BP, AR_RTR_COLBUF_CFG_CONGEST_CNTL_UPPER_THRESHOLD_MASK },
    { "MIDDLE_THRESHOLD", AR_RTR_COLBUF_CFG_CONGEST_CNTL_MIDDLE_THRESHOLD_BP, AR_RTR_COLBUF_CFG_CONGEST_CNTL_MIDDLE_THRESHOLD_MASK },
    { "LOWER_THRESHOLD", AR_RTR_COLBUF_CFG_CONGEST_CNTL_LOWER_THRESHOLD_BP, AR_RTR_COLBUF_CFG_CONGEST_CNTL_LOWER_THRESHOLD_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_colbuf_cfg_congest_port_en_detail[] = {
    { "CONGEST_PORT_EN", AR_RTR_COLBUF_CFG_CONGEST_PORT_EN_CONGEST_PORT_EN_BP, AR_RTR_COLBUF_CFG_CONGEST_PORT_EN_CONGEST_PORT_EN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_colbuf_cfg_congest_far_table_detail[] = {
    { "FAR_TABLE", AR_RTR_COLBUF_CFG_CONGEST_FAR_TABLE_FAR_TABLE_BP, AR_RTR_COLBUF_CFG_CONGEST_FAR_TABLE_FAR_TABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_colbuf_cfg_congest_near_table_detail[] = {
    { "NEAR_TABLE", AR_RTR_COLBUF_CFG_CONGEST_NEAR_TABLE_NEAR_TABLE_BP, AR_RTR_COLBUF_CFG_CONGEST_NEAR_TABLE_NEAR_TABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_colbuf_cfg_congest_dnstrm_table_detail[] = {
    { "DNSTRM_TABLE", AR_RTR_COLBUF_CFG_CONGEST_DNSTRM_TABLE_DNSTRM_TABLE_BP, AR_RTR_COLBUF_CFG_CONGEST_DNSTRM_TABLE_DNSTRM_TABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_colbuf_dbg_errinj_detail[] = {
    { "CHECKBITS", AR_RTR_COLBUF_DBG_ERRINJ_CHECKBITS_BP, AR_RTR_COLBUF_DBG_ERRINJ_CHECKBITS_MASK },
    { "COUNT", AR_RTR_COLBUF_DBG_ERRINJ_COUNT_BP, AR_RTR_COLBUF_DBG_ERRINJ_COUNT_MASK },
    { "TRIGGERED", AR_RTR_COLBUF_DBG_ERRINJ_TRIGGERED_BP, AR_RTR_COLBUF_DBG_ERRINJ_TRIGGERED_MASK },
    { "MODE", AR_RTR_COLBUF_DBG_ERRINJ_MODE_BP, AR_RTR_COLBUF_DBG_ERRINJ_MODE_MASK },
    { "ENABLE", AR_RTR_COLBUF_DBG_ERRINJ_ENABLE_BP, AR_RTR_COLBUF_DBG_ERRINJ_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_colbuf_err_info_detail[] = {
    { "MBE_SYNDROME", AR_RTR_COLBUF_ERR_INFO_MBE_SYNDROME_BP, AR_RTR_COLBUF_ERR_INFO_MBE_SYNDROME_MASK },
    { "MBE_HEAD_FLIT", AR_RTR_COLBUF_ERR_INFO_MBE_HEAD_FLIT_BP, AR_RTR_COLBUF_ERR_INFO_MBE_HEAD_FLIT_MASK },
    { "MBE_TAIL_FLIT", AR_RTR_COLBUF_ERR_INFO_MBE_TAIL_FLIT_BP, AR_RTR_COLBUF_ERR_INFO_MBE_TAIL_FLIT_MASK },
    { "MBE_SRC_PORT", AR_RTR_COLBUF_ERR_INFO_MBE_SRC_PORT_BP, AR_RTR_COLBUF_ERR_INFO_MBE_SRC_PORT_MASK },
    { "MBE_SRC_VC", AR_RTR_COLBUF_ERR_INFO_MBE_SRC_VC_BP, AR_RTR_COLBUF_ERR_INFO_MBE_SRC_VC_MASK },
    { "SBE_SYNDROME", AR_RTR_COLBUF_ERR_INFO_SBE_SYNDROME_BP, AR_RTR_COLBUF_ERR_INFO_SBE_SYNDROME_MASK },
    { "PKT_LENGTH", AR_RTR_COLBUF_ERR_INFO_PKT_LENGTH_BP, AR_RTR_COLBUF_ERR_INFO_PKT_LENGTH_MASK },
    { "VC", AR_RTR_COLBUF_ERR_INFO_VC_BP, AR_RTR_COLBUF_ERR_INFO_VC_MASK },
    { "SRC_PORT_IN", AR_RTR_COLBUF_ERR_INFO_SRC_PORT_IN_BP, AR_RTR_COLBUF_ERR_INFO_SRC_PORT_IN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_colbuf_err_info_cnt_mbe_detail[] = {
    { "MBE_COUNT", AR_RTR_COLBUF_ERR_INFO_CNT_MBE_MBE_COUNT_BP, AR_RTR_COLBUF_ERR_INFO_CNT_MBE_MBE_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_colbuf_err_info_cnt_sbe_detail[] = {
    { "SBE_COUNT", AR_RTR_COLBUF_ERR_INFO_CNT_SBE_SBE_COUNT_BP, AR_RTR_COLBUF_ERR_INFO_CNT_SBE_SBE_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_colbuf_perf_stall_rq_detail[] = {
    { "VC_PTR", AR_RTR_COLBUF_PERF_STALL_RQ_VC_PTR_BP, AR_RTR_COLBUF_PERF_STALL_RQ_VC_PTR_MASK },
    { "COL_BUF_PERF_STALL_RQ", AR_RTR_COLBUF_PERF_STALL_RQ_COL_BUF_PERF_STALL_RQ_BP, AR_RTR_COLBUF_PERF_STALL_RQ_COL_BUF_PERF_STALL_RQ_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_colbuf_perf_stall_rs_detail[] = {
    { "VC_PTR", AR_RTR_COLBUF_PERF_STALL_RS_VC_PTR_BP, AR_RTR_COLBUF_PERF_STALL_RS_VC_PTR_MASK },
    { "COL_BUF_PERF_STALL_RS", AR_RTR_COLBUF_PERF_STALL_RS_COL_BUF_PERF_STALL_RS_BP, AR_RTR_COLBUF_PERF_STALL_RS_COL_BUF_PERF_STALL_RS_MASK },
    { NULL, 0, 0 }
};

/*
 *  AR NT MMR DECLARATIONS
 */
static const generic_mmr_t _ar_rtr_inq_cfg_degrade_diag = {
    "AR_RTR_INQ_CFG_DEGRADE_DIAG", AR_RTR_INQ_CFG_DEGRADE_DIAG, 8, 1, _ar_rtr_inq_cfg_degrade_diag_detail
};
static const generic_mmr_t _ar_rtr_inq_cfg_fifo_rowbuf_crdt_limit = {
    "AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT, 8, 1, _ar_rtr_inq_cfg_fifo_rowbuf_crdt_limit_detail
};
static const generic_mmr_t _ar_rtr_inq_cfg_fifo_rowbuf_crdts = {
    "AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS", AR_RTR_INQ_CFG_FIFO_ROWBUF_CRDTS, 8, 1, _ar_rtr_inq_cfg_fifo_rowbuf_crdts_detail
};
static const generic_mmr_t _ar_rtr_inq_cfg_damq_vc04 = {
    "AR_RTR_INQ_CFG_DAMQ_VC04", AR_RTR_INQ_CFG_DAMQ_VC04, 8, 1, _ar_rtr_inq_cfg_damq_vc04_detail
};
static const generic_mmr_t _ar_rtr_inq_cfg_damq_vc15 = {
    "AR_RTR_INQ_CFG_DAMQ_VC15", AR_RTR_INQ_CFG_DAMQ_VC15, 8, 1, _ar_rtr_inq_cfg_damq_vc15_detail
};
static const generic_mmr_t _ar_rtr_inq_cfg_damq_vc26 = {
    "AR_RTR_INQ_CFG_DAMQ_VC26", AR_RTR_INQ_CFG_DAMQ_VC26, 8, 1, _ar_rtr_inq_cfg_damq_vc26_detail
};
static const generic_mmr_t _ar_rtr_inq_cfg_damq_vc37 = {
    "AR_RTR_INQ_CFG_DAMQ_VC37", AR_RTR_INQ_CFG_DAMQ_VC37, 8, 1, _ar_rtr_inq_cfg_damq_vc37_detail
};
static const generic_mmr_t _ar_rtr_inq_cfg_damq_free = {
    "AR_RTR_INQ_CFG_DAMQ_FREE", AR_RTR_INQ_CFG_DAMQ_FREE, 8, 1, _ar_rtr_inq_cfg_damq_free_detail
};
static const generic_mmr_t _ar_rtr_inq_cfg_damq_next = {
    "AR_RTR_INQ_CFG_DAMQ_NEXT", AR_RTR_INQ_CFG_DAMQ_NEXT, 8, 1, _ar_rtr_inq_cfg_damq_next_detail
};
static const generic_mmr_t _ar_rtr_inq_cfg_damq_blk_in_used0 = {
    "AR_RTR_INQ_CFG_DAMQ_BLK_IN_USED0", AR_RTR_INQ_CFG_DAMQ_BLK_IN_USED0, 8, 1, _ar_rtr_inq_cfg_damq_blk_in_used0_detail
};
static const generic_mmr_t _ar_rtr_inq_cfg_damq_blk_in_used1 = {
    "AR_RTR_INQ_CFG_DAMQ_BLK_IN_USED1", AR_RTR_INQ_CFG_DAMQ_BLK_IN_USED1, 8, 1, _ar_rtr_inq_cfg_damq_blk_in_used1_detail
};
static const generic_mmr_t _ar_rtr_inq_cfg_dfifo_data = {
    "AR_RTR_INQ_CFG_DFIFO_DATA", AR_RTR_INQ_CFG_DFIFO_DATA, 8, 1, _ar_rtr_inq_cfg_dfifo_data_detail
};
static const generic_mmr_t _ar_rtr_inq_cfg_route_pipe = {
    "AR_RTR_INQ_CFG_ROUTE_PIPE", AR_RTR_INQ_CFG_ROUTE_PIPE, 8, 1, _ar_rtr_inq_cfg_route_pipe_detail
};
static const generic_mmr_t _ar_rtr_inq_cfg_vc_table = {
    "AR_RTR_INQ_CFG_VC_TABLE", AR_RTR_INQ_CFG_VC_TABLE, 8, 1, _ar_rtr_inq_cfg_vc_table_detail
};
static const generic_mmr_t _ar_rtr_inq_cfg_link_alive_bits = {
    "AR_RTR_INQ_CFG_LINK_ALIVE_BITS", AR_RTR_INQ_CFG_LINK_ALIVE_BITS, 8, 1, _ar_rtr_inq_cfg_link_alive_bits_detail
};
static const generic_mmr_t _ar_rtr_inq_cfg_congest_ctrl = {
    "AR_RTR_INQ_CFG_CONGEST_CTRL", AR_RTR_INQ_CFG_CONGEST_CTRL, 8, 1, _ar_rtr_inq_cfg_congest_ctrl_detail
};
static const generic_mmr_t _ar_rtr_inq_err_flg = {
    "AR_RTR_INQ_ERR_FLG", AR_RTR_INQ_ERR_FLG, 8, 1, _ar_rtr_inq_err_flg_detail
};
static const generic_mmr_t _ar_rtr_inq_err_clr = {
    "AR_RTR_INQ_ERR_CLR", AR_RTR_INQ_ERR_CLR, 8, 1, _ar_rtr_inq_err_clr_detail
};
static const generic_mmr_t _ar_rtr_inq_err_hss_msk = {
    "AR_RTR_INQ_ERR_HSS_MSK", AR_RTR_INQ_ERR_HSS_MSK, 8, 1, _ar_rtr_inq_err_hss_msk_detail
};
static const generic_mmr_t _ar_rtr_inq_err_first_flg = {
    "AR_RTR_INQ_ERR_FIRST_FLG", AR_RTR_INQ_ERR_FIRST_FLG, 8, 1, _ar_rtr_inq_err_first_flg_detail
};
static const generic_mmr_t _ar_rtr_inq_dbg_errinj_rtable = {
    "AR_RTR_INQ_DBG_ERRINJ_RTABLE", AR_RTR_INQ_DBG_ERRINJ_RTABLE, 8, 1, _ar_rtr_inq_dbg_errinj_rtable_detail
};
static const generic_mmr_t _ar_rtr_inq_err_info_rtable = {
    "AR_RTR_INQ_ERR_INFO_RTABLE", AR_RTR_INQ_ERR_INFO_RTABLE, 8, 1, _ar_rtr_inq_err_info_rtable_detail
};
static const generic_mmr_t _ar_rtr_inq_err_info_cnt_sbe_rtable = {
    "AR_RTR_INQ_ERR_INFO_CNT_SBE_RTABLE", AR_RTR_INQ_ERR_INFO_CNT_SBE_RTABLE, 8, 1, _ar_rtr_inq_err_info_cnt_sbe_rtable_detail
};
static const generic_mmr_t _ar_rtr_inq_err_info_cnt_mbe_rtable = {
    "AR_RTR_INQ_ERR_INFO_CNT_MBE_RTABLE", AR_RTR_INQ_ERR_INFO_CNT_MBE_RTABLE, 8, 1, _ar_rtr_inq_err_info_cnt_mbe_rtable_detail
};
static const generic_mmr_t _ar_rtr_inq_err_info_routing = {
    "AR_RTR_INQ_ERR_INFO_ROUTING", AR_RTR_INQ_ERR_INFO_ROUTING, 8, 1, _ar_rtr_inq_err_info_routing_detail
};
static const generic_mmr_t _ar_rtr_inq_err_info_damq = {
    "AR_RTR_INQ_ERR_INFO_DAMQ", AR_RTR_INQ_ERR_INFO_DAMQ, 8, 1, _ar_rtr_inq_err_info_damq_detail
};
static const generic_mmr_t _ar_rtr_inq_err_info_cnt_sbe_damq = {
    "AR_RTR_INQ_ERR_INFO_CNT_SBE_DAMQ", AR_RTR_INQ_ERR_INFO_CNT_SBE_DAMQ, 8, 1, _ar_rtr_inq_err_info_cnt_sbe_damq_detail
};
static const generic_mmr_t _ar_rtr_inq_err_info_cnt_mbe_damq = {
    "AR_RTR_INQ_ERR_INFO_CNT_MBE_DAMQ", AR_RTR_INQ_ERR_INFO_CNT_MBE_DAMQ, 8, 1, _ar_rtr_inq_err_info_cnt_mbe_damq_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_incoming_flit_vc0 = {
    "AR_RTR_INQ_PRF_INCOMING_FLIT_VC0", AR_RTR_INQ_PRF_INCOMING_FLIT_VC0, 8, 1, _ar_rtr_inq_prf_incoming_flit_vc0_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_incoming_flit_vc1 = {
    "AR_RTR_INQ_PRF_INCOMING_FLIT_VC1", AR_RTR_INQ_PRF_INCOMING_FLIT_VC1, 8, 1, _ar_rtr_inq_prf_incoming_flit_vc1_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_incoming_flit_vc2 = {
    "AR_RTR_INQ_PRF_INCOMING_FLIT_VC2", AR_RTR_INQ_PRF_INCOMING_FLIT_VC2, 8, 1, _ar_rtr_inq_prf_incoming_flit_vc2_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_incoming_flit_vc3 = {
    "AR_RTR_INQ_PRF_INCOMING_FLIT_VC3", AR_RTR_INQ_PRF_INCOMING_FLIT_VC3, 8, 1, _ar_rtr_inq_prf_incoming_flit_vc3_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_incoming_flit_vc4 = {
    "AR_RTR_INQ_PRF_INCOMING_FLIT_VC4", AR_RTR_INQ_PRF_INCOMING_FLIT_VC4, 8, 1, _ar_rtr_inq_prf_incoming_flit_vc4_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_incoming_flit_vc5 = {
    "AR_RTR_INQ_PRF_INCOMING_FLIT_VC5", AR_RTR_INQ_PRF_INCOMING_FLIT_VC5, 8, 1, _ar_rtr_inq_prf_incoming_flit_vc5_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_incoming_flit_vc6 = {
    "AR_RTR_INQ_PRF_INCOMING_FLIT_VC6", AR_RTR_INQ_PRF_INCOMING_FLIT_VC6, 8, 1, _ar_rtr_inq_prf_incoming_flit_vc6_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_incoming_flit_vc7 = {
    "AR_RTR_INQ_PRF_INCOMING_FLIT_VC7", AR_RTR_INQ_PRF_INCOMING_FLIT_VC7, 8, 1, _ar_rtr_inq_prf_incoming_flit_vc7_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_flit0_filtering_setup = {
    "AR_RTR_INQ_PRF_FLIT0_FILTERING_SETUP", AR_RTR_INQ_PRF_FLIT0_FILTERING_SETUP, 8, 1, _ar_rtr_inq_prf_flit0_filtering_setup_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_flit0_filtering_mask = {
    "AR_RTR_INQ_PRF_FLIT0_FILTERING_MASK", AR_RTR_INQ_PRF_FLIT0_FILTERING_MASK, 8, 1, _ar_rtr_inq_prf_flit0_filtering_mask_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_flit1_filtering_setup = {
    "AR_RTR_INQ_PRF_FLIT1_FILTERING_SETUP", AR_RTR_INQ_PRF_FLIT1_FILTERING_SETUP, 8, 1, _ar_rtr_inq_prf_flit1_filtering_setup_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_flit1_filtering_mask = {
    "AR_RTR_INQ_PRF_FLIT1_FILTERING_MASK", AR_RTR_INQ_PRF_FLIT1_FILTERING_MASK, 8, 1, _ar_rtr_inq_prf_flit1_filtering_mask_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_flit2_filtering_setup = {
    "AR_RTR_INQ_PRF_FLIT2_FILTERING_SETUP", AR_RTR_INQ_PRF_FLIT2_FILTERING_SETUP, 8, 1, _ar_rtr_inq_prf_flit2_filtering_setup_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_flit2_filtering_mask = {
    "AR_RTR_INQ_PRF_FLIT2_FILTERING_MASK", AR_RTR_INQ_PRF_FLIT2_FILTERING_MASK, 8, 1, _ar_rtr_inq_prf_flit2_filtering_mask_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_flit3_filtering_setup = {
    "AR_RTR_INQ_PRF_FLIT3_FILTERING_SETUP", AR_RTR_INQ_PRF_FLIT3_FILTERING_SETUP, 8, 1, _ar_rtr_inq_prf_flit3_filtering_setup_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_flit3_filtering_mask = {
    "AR_RTR_INQ_PRF_FLIT3_FILTERING_MASK", AR_RTR_INQ_PRF_FLIT3_FILTERING_MASK, 8, 1, _ar_rtr_inq_prf_flit3_filtering_mask_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_flit4_filtering_setup = {
    "AR_RTR_INQ_PRF_FLIT4_FILTERING_SETUP", AR_RTR_INQ_PRF_FLIT4_FILTERING_SETUP, 8, 1, _ar_rtr_inq_prf_flit4_filtering_setup_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_flit4_filtering_mask = {
    "AR_RTR_INQ_PRF_FLIT4_FILTERING_MASK", AR_RTR_INQ_PRF_FLIT4_FILTERING_MASK, 8, 1, _ar_rtr_inq_prf_flit4_filtering_mask_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_flit5_filtering_setup = {
    "AR_RTR_INQ_PRF_FLIT5_FILTERING_SETUP", AR_RTR_INQ_PRF_FLIT5_FILTERING_SETUP, 8, 1, _ar_rtr_inq_prf_flit5_filtering_setup_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_flit5_filtering_mask = {
    "AR_RTR_INQ_PRF_FLIT5_FILTERING_MASK", AR_RTR_INQ_PRF_FLIT5_FILTERING_MASK, 8, 1, _ar_rtr_inq_prf_flit5_filtering_mask_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_flit6_filtering_setup = {
    "AR_RTR_INQ_PRF_FLIT6_FILTERING_SETUP", AR_RTR_INQ_PRF_FLIT6_FILTERING_SETUP, 8, 1, _ar_rtr_inq_prf_flit6_filtering_setup_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_flit6_filtering_mask = {
    "AR_RTR_INQ_PRF_FLIT6_FILTERING_MASK", AR_RTR_INQ_PRF_FLIT6_FILTERING_MASK, 8, 1, _ar_rtr_inq_prf_flit6_filtering_mask_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_flit7_filtering_setup = {
    "AR_RTR_INQ_PRF_FLIT7_FILTERING_SETUP", AR_RTR_INQ_PRF_FLIT7_FILTERING_SETUP, 8, 1, _ar_rtr_inq_prf_flit7_filtering_setup_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_flit7_filtering_mask = {
    "AR_RTR_INQ_PRF_FLIT7_FILTERING_MASK", AR_RTR_INQ_PRF_FLIT7_FILTERING_MASK, 8, 1, _ar_rtr_inq_prf_flit7_filtering_mask_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_incoming_pkt_vc0_filter_flit0_cnt = {
    "AR_RTR_INQ_PRF_INCOMING_PKT_VC0_FILTER_FLIT0_CNT", AR_RTR_INQ_PRF_INCOMING_PKT_VC0_FILTER_FLIT0_CNT, 8, 1, _ar_rtr_inq_prf_incoming_pkt_vc0_filter_flit0_cnt_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_incoming_pkt_vc1_filter_flit1_cnt = {
    "AR_RTR_INQ_PRF_INCOMING_PKT_VC1_FILTER_FLIT1_CNT", AR_RTR_INQ_PRF_INCOMING_PKT_VC1_FILTER_FLIT1_CNT, 8, 1, _ar_rtr_inq_prf_incoming_pkt_vc1_filter_flit1_cnt_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_incoming_pkt_vc2_filter_flit2_cnt = {
    "AR_RTR_INQ_PRF_INCOMING_PKT_VC2_FILTER_FLIT2_CNT", AR_RTR_INQ_PRF_INCOMING_PKT_VC2_FILTER_FLIT2_CNT, 8, 1, _ar_rtr_inq_prf_incoming_pkt_vc2_filter_flit2_cnt_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_incoming_pkt_vc3_filter_flit3_cnt = {
    "AR_RTR_INQ_PRF_INCOMING_PKT_VC3_FILTER_FLIT3_CNT", AR_RTR_INQ_PRF_INCOMING_PKT_VC3_FILTER_FLIT3_CNT, 8, 1, _ar_rtr_inq_prf_incoming_pkt_vc3_filter_flit3_cnt_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_incoming_pkt_vc4_filter_flit4_cnt = {
    "AR_RTR_INQ_PRF_INCOMING_PKT_VC4_FILTER_FLIT4_CNT", AR_RTR_INQ_PRF_INCOMING_PKT_VC4_FILTER_FLIT4_CNT, 8, 1, _ar_rtr_inq_prf_incoming_pkt_vc4_filter_flit4_cnt_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_incoming_pkt_vc5_filter_flit5_cnt = {
    "AR_RTR_INQ_PRF_INCOMING_PKT_VC5_FILTER_FLIT5_CNT", AR_RTR_INQ_PRF_INCOMING_PKT_VC5_FILTER_FLIT5_CNT, 8, 1, _ar_rtr_inq_prf_incoming_pkt_vc5_filter_flit5_cnt_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_incoming_pkt_vc6_filter_flit6_cnt = {
    "AR_RTR_INQ_PRF_INCOMING_PKT_VC6_FILTER_FLIT6_CNT", AR_RTR_INQ_PRF_INCOMING_PKT_VC6_FILTER_FLIT6_CNT, 8, 1, _ar_rtr_inq_prf_incoming_pkt_vc6_filter_flit6_cnt_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_incoming_pkt_vc7_filter_flit7_cnt = {
    "AR_RTR_INQ_PRF_INCOMING_PKT_VC7_FILTER_FLIT7_CNT", AR_RTR_INQ_PRF_INCOMING_PKT_VC7_FILTER_FLIT7_CNT, 8, 1, _ar_rtr_inq_prf_incoming_pkt_vc7_filter_flit7_cnt_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_match_flit_3_to_0_filtering_cnt = {
    "AR_RTR_INQ_PRF_MATCH_FLIT_3_TO_0_FILTERING_CNT", AR_RTR_INQ_PRF_MATCH_FLIT_3_TO_0_FILTERING_CNT, 8, 1, _ar_rtr_inq_prf_match_flit_3_to_0_filtering_cnt_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_match_flit_7_to_4_filtering_cnt = {
    "AR_RTR_INQ_PRF_MATCH_FLIT_7_TO_4_FILTERING_CNT", AR_RTR_INQ_PRF_MATCH_FLIT_7_TO_4_FILTERING_CNT, 8, 1, _ar_rtr_inq_prf_match_flit_7_to_4_filtering_cnt_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_rowbus_stall_cnt = {
    "AR_RTR_INQ_PRF_ROWBUS_STALL_CNT", AR_RTR_INQ_PRF_ROWBUS_STALL_CNT, 8, 1, _ar_rtr_inq_prf_rowbus_stall_cnt_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_rowbus_2x_usage_cnt = {
    "AR_RTR_INQ_PRF_ROWBUS_2X_USAGE_CNT", AR_RTR_INQ_PRF_ROWBUS_2X_USAGE_CNT, 8, 1, _ar_rtr_inq_prf_rowbus_2x_usage_cnt_detail
};
static const generic_mmr_t _ar_rtr_inq_prf_pkt_to_dead_link_cnt = {
    "AR_RTR_INQ_PRF_PKT_TO_DEAD_LINK_CNT", AR_RTR_INQ_PRF_PKT_TO_DEAD_LINK_CNT, 8, 1, _ar_rtr_inq_prf_pkt_to_dead_link_cnt_detail
};
static const generic_mmr_t _ar_rtr_subswitch_cfg_colbuf_crdts = {
    "AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS", AR_RTR_SUBSWITCH_CFG_COLBUF_CRDTS, 8, 1, _ar_rtr_subswitch_cfg_colbuf_crdts_detail
};
static const generic_mmr_t _ar_rtr_subswitch_err_info = {
    "AR_RTR_SUBSWITCH_ERR_INFO", AR_RTR_SUBSWITCH_ERR_INFO, 8, 1, _ar_rtr_subswitch_err_info_detail
};
static const generic_mmr_t _ar_rtr_subswitch_err_mask = {
    "AR_RTR_SUBSWITCH_ERR_MASK", AR_RTR_SUBSWITCH_ERR_MASK, 8, 1, _ar_rtr_subswitch_err_mask_detail
};
static const generic_mmr_t _ar_rtr_colbuf_cfg_crdts_channel = {
    "AR_RTR_COLBUF_CFG_CRDTS_CHANNEL", AR_RTR_COLBUF_CFG_CRDTS_CHANNEL, 8, 1, _ar_rtr_colbuf_cfg_crdts_channel_detail
};
static const generic_mmr_t _ar_rtr_colbuf_cfg_fpt = {
    "AR_RTR_COLBUF_CFG_FPT", AR_RTR_COLBUF_CFG_FPT, 8, 1, _ar_rtr_colbuf_cfg_fpt_detail
};
static const generic_mmr_t _ar_rtr_colbuf_cfg_congest_cntl = {
    "AR_RTR_COLBUF_CFG_CONGEST_CNTL", AR_RTR_COLBUF_CFG_CONGEST_CNTL, 8, 1, _ar_rtr_colbuf_cfg_congest_cntl_detail
};
static const generic_mmr_t _ar_rtr_colbuf_cfg_congest_port_en = {
    "AR_RTR_COLBUF_CFG_CONGEST_PORT_EN", AR_RTR_COLBUF_CFG_CONGEST_PORT_EN, 8, 1, _ar_rtr_colbuf_cfg_congest_port_en_detail
};
static const generic_mmr_t _ar_rtr_colbuf_cfg_congest_far_table = {
    "AR_RTR_COLBUF_CFG_CONGEST_FAR_TABLE", AR_RTR_COLBUF_CFG_CONGEST_FAR_TABLE, 8, 1, _ar_rtr_colbuf_cfg_congest_far_table_detail
};
static const generic_mmr_t _ar_rtr_colbuf_cfg_congest_near_table = {
    "AR_RTR_COLBUF_CFG_CONGEST_NEAR_TABLE", AR_RTR_COLBUF_CFG_CONGEST_NEAR_TABLE, 8, 1, _ar_rtr_colbuf_cfg_congest_near_table_detail
};
static const generic_mmr_t _ar_rtr_colbuf_cfg_congest_dnstrm_table = {
    "AR_RTR_COLBUF_CFG_CONGEST_DNSTRM_TABLE", AR_RTR_COLBUF_CFG_CONGEST_DNSTRM_TABLE, 8, 1, _ar_rtr_colbuf_cfg_congest_dnstrm_table_detail
};
static const generic_mmr_t _ar_rtr_colbuf_dbg_errinj = {
    "AR_RTR_COLBUF_DBG_ERRINJ", AR_RTR_COLBUF_DBG_ERRINJ, 8, 1, _ar_rtr_colbuf_dbg_errinj_detail
};
static const generic_mmr_t _ar_rtr_colbuf_err_info = {
    "AR_RTR_COLBUF_ERR_INFO", AR_RTR_COLBUF_ERR_INFO, 8, 1, _ar_rtr_colbuf_err_info_detail
};
static const generic_mmr_t _ar_rtr_colbuf_err_info_cnt_mbe = {
    "AR_RTR_COLBUF_ERR_INFO_CNT_MBE", AR_RTR_COLBUF_ERR_INFO_CNT_MBE, 8, 1, _ar_rtr_colbuf_err_info_cnt_mbe_detail
};
static const generic_mmr_t _ar_rtr_colbuf_err_info_cnt_sbe = {
    "AR_RTR_COLBUF_ERR_INFO_CNT_SBE", AR_RTR_COLBUF_ERR_INFO_CNT_SBE, 8, 1, _ar_rtr_colbuf_err_info_cnt_sbe_detail
};
static const generic_mmr_t _ar_rtr_colbuf_perf_stall_rq = {
    "AR_RTR_COLBUF_PERF_STALL_RQ", AR_RTR_COLBUF_PERF_STALL_RQ, 8, 1, _ar_rtr_colbuf_perf_stall_rq_detail
};
static const generic_mmr_t _ar_rtr_colbuf_perf_stall_rs = {
    "AR_RTR_COLBUF_PERF_STALL_RS", AR_RTR_COLBUF_PERF_STALL_RS, 8, 1, _ar_rtr_colbuf_perf_stall_rs_detail
};

/*
 *  INSTALL AR NT MMRS
 */
static const generic_mmr_t* _ar_nt_mmrs[] _unused = {
    &_ar_rtr_inq_cfg_degrade_diag,
    &_ar_rtr_inq_cfg_fifo_rowbuf_crdt_limit,
    &_ar_rtr_inq_cfg_fifo_rowbuf_crdts,
    &_ar_rtr_inq_cfg_damq_vc04,
    &_ar_rtr_inq_cfg_damq_vc15,
    &_ar_rtr_inq_cfg_damq_vc26,
    &_ar_rtr_inq_cfg_damq_vc37,
    &_ar_rtr_inq_cfg_damq_free,
    &_ar_rtr_inq_cfg_damq_next,
    &_ar_rtr_inq_cfg_damq_blk_in_used0,
    &_ar_rtr_inq_cfg_damq_blk_in_used1,
    &_ar_rtr_inq_cfg_dfifo_data,
    &_ar_rtr_inq_cfg_route_pipe,
    &_ar_rtr_inq_cfg_vc_table,
    &_ar_rtr_inq_cfg_link_alive_bits,
    &_ar_rtr_inq_cfg_congest_ctrl,
    &_ar_rtr_inq_err_flg,
    &_ar_rtr_inq_err_clr,
    &_ar_rtr_inq_err_hss_msk,
    &_ar_rtr_inq_err_first_flg,
    &_ar_rtr_inq_dbg_errinj_rtable,
    &_ar_rtr_inq_err_info_rtable,
    &_ar_rtr_inq_err_info_cnt_sbe_rtable,
    &_ar_rtr_inq_err_info_cnt_mbe_rtable,
    &_ar_rtr_inq_err_info_routing,
    &_ar_rtr_inq_err_info_damq,
    &_ar_rtr_inq_err_info_cnt_sbe_damq,
    &_ar_rtr_inq_err_info_cnt_mbe_damq,
    &_ar_rtr_inq_prf_incoming_flit_vc0,
    &_ar_rtr_inq_prf_incoming_flit_vc1,
    &_ar_rtr_inq_prf_incoming_flit_vc2,
    &_ar_rtr_inq_prf_incoming_flit_vc3,
    &_ar_rtr_inq_prf_incoming_flit_vc4,
    &_ar_rtr_inq_prf_incoming_flit_vc5,
    &_ar_rtr_inq_prf_incoming_flit_vc6,
    &_ar_rtr_inq_prf_incoming_flit_vc7,
    &_ar_rtr_inq_prf_flit0_filtering_setup,
    &_ar_rtr_inq_prf_flit0_filtering_mask,
    &_ar_rtr_inq_prf_flit1_filtering_setup,
    &_ar_rtr_inq_prf_flit1_filtering_mask,
    &_ar_rtr_inq_prf_flit2_filtering_setup,
    &_ar_rtr_inq_prf_flit2_filtering_mask,
    &_ar_rtr_inq_prf_flit3_filtering_setup,
    &_ar_rtr_inq_prf_flit3_filtering_mask,
    &_ar_rtr_inq_prf_flit4_filtering_setup,
    &_ar_rtr_inq_prf_flit4_filtering_mask,
    &_ar_rtr_inq_prf_flit5_filtering_setup,
    &_ar_rtr_inq_prf_flit5_filtering_mask,
    &_ar_rtr_inq_prf_flit6_filtering_setup,
    &_ar_rtr_inq_prf_flit6_filtering_mask,
    &_ar_rtr_inq_prf_flit7_filtering_setup,
    &_ar_rtr_inq_prf_flit7_filtering_mask,
    &_ar_rtr_inq_prf_incoming_pkt_vc0_filter_flit0_cnt,
    &_ar_rtr_inq_prf_incoming_pkt_vc1_filter_flit1_cnt,
    &_ar_rtr_inq_prf_incoming_pkt_vc2_filter_flit2_cnt,
    &_ar_rtr_inq_prf_incoming_pkt_vc3_filter_flit3_cnt,
    &_ar_rtr_inq_prf_incoming_pkt_vc4_filter_flit4_cnt,
    &_ar_rtr_inq_prf_incoming_pkt_vc5_filter_flit5_cnt,
    &_ar_rtr_inq_prf_incoming_pkt_vc6_filter_flit6_cnt,
    &_ar_rtr_inq_prf_incoming_pkt_vc7_filter_flit7_cnt,
    &_ar_rtr_inq_prf_match_flit_3_to_0_filtering_cnt,
    &_ar_rtr_inq_prf_match_flit_7_to_4_filtering_cnt,
    &_ar_rtr_inq_prf_rowbus_stall_cnt,
    &_ar_rtr_inq_prf_rowbus_2x_usage_cnt,
    &_ar_rtr_inq_prf_pkt_to_dead_link_cnt,
    &_ar_rtr_subswitch_cfg_colbuf_crdts,
    &_ar_rtr_subswitch_err_info,
    &_ar_rtr_subswitch_err_mask,
    &_ar_rtr_colbuf_cfg_crdts_channel,
    &_ar_rtr_colbuf_cfg_fpt,
    &_ar_rtr_colbuf_cfg_congest_cntl,
    &_ar_rtr_colbuf_cfg_congest_port_en,
    &_ar_rtr_colbuf_cfg_congest_far_table,
    &_ar_rtr_colbuf_cfg_congest_near_table,
    &_ar_rtr_colbuf_cfg_congest_dnstrm_table,
    &_ar_rtr_colbuf_dbg_errinj,
    &_ar_rtr_colbuf_err_info,
    &_ar_rtr_colbuf_err_info_cnt_mbe,
    &_ar_rtr_colbuf_err_info_cnt_sbe,
    &_ar_rtr_colbuf_perf_stall_rq,
    &_ar_rtr_colbuf_perf_stall_rs,
    NULL
};

#endif
