/******************************************************************************
 * COPYRIGHT CRAY INC. ar_niclm_mmrs_h.h
 * FILE: ar_niclm_mmrs_h.h
 * Created by v2h.c on Wed Oct  8 14:39:01 2014
 ******************************************************************************/

#ifndef _AR_NICLM_MMRS_H_H_
#define _AR_NICLM_MMRS_H_H_

#ifdef __GNUC__
#define _unused __attribute__((unused))
#else
#define _unused
#endif

#ifndef _GENERIC_MMRD_T_
#define _GENERIC_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint64_t _mask;		/* Field bit mask */
} generic_mmrd_t;
#endif

#ifndef _ERRCAT_MMRD_T_
#define _ERRCAT_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint32_t _ec;		/* Field error category */
} errcat_mmrd_t;
#endif

#ifndef _GENERIC_MMR_T_
#define _GENERIC_MMR_T_
typedef struct {
	char* _name;		/* MMR name */
	uint64_t _addr;		/* MMR address */
	int _size;		/* Size in bytes of MMR */
	int _depth;		/* Number of MMR instances */
	const generic_mmrd_t *_info;	/* MMR detail */
} generic_mmr_t;
#endif

static const generic_mmr_t* _ar_niclm_mmrs[] _unused;	/* NICLM Array */

/*
 *  AR NICLM MMR DETAIL DECLARATIONS
 */
static const generic_mmrd_t _ar_nic_niclm_dbg_lm0_ctl_detail[] = {
    { "LM_RST", AR_NIC_NICLM_DBG_LM0_CTL_LM_RST_BP, AR_NIC_NICLM_DBG_LM0_CTL_LM_RST_MASK },
    { "LM_TRIG_STATE", AR_NIC_NICLM_DBG_LM0_CTL_LM_TRIG_STATE_BP, AR_NIC_NICLM_DBG_LM0_CTL_LM_TRIG_STATE_MASK },
    { "LM_CAP_STATE", AR_NIC_NICLM_DBG_LM0_CTL_LM_CAP_STATE_BP, AR_NIC_NICLM_DBG_LM0_CTL_LM_CAP_STATE_MASK },
    { "LM_CTL_T0_CNT", AR_NIC_NICLM_DBG_LM0_CTL_LM_CTL_T0_CNT_BP, AR_NIC_NICLM_DBG_LM0_CTL_LM_CTL_T0_CNT_MASK },
    { "LM_CTL_T1_CNT", AR_NIC_NICLM_DBG_LM0_CTL_LM_CTL_T1_CNT_BP, AR_NIC_NICLM_DBG_LM0_CTL_LM_CTL_T1_CNT_MASK },
    { "LM_TRIG_EN", AR_NIC_NICLM_DBG_LM0_CTL_LM_TRIG_EN_BP, AR_NIC_NICLM_DBG_LM0_CTL_LM_TRIG_EN_MASK },
    { "LM_CTL_MODE", AR_NIC_NICLM_DBG_LM0_CTL_LM_CTL_MODE_BP, AR_NIC_NICLM_DBG_LM0_CTL_LM_CTL_MODE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_dbg_lm0_ptrs_detail[] = {
    { "LM_REC_ACT", AR_NIC_NICLM_DBG_LM0_PTRS_LM_REC_ACT_BP, AR_NIC_NICLM_DBG_LM0_PTRS_LM_REC_ACT_MASK },
    { "LM_REC_DONE", AR_NIC_NICLM_DBG_LM0_PTRS_LM_REC_DONE_BP, AR_NIC_NICLM_DBG_LM0_PTRS_LM_REC_DONE_MASK },
    { "LM_MULT_EVENT", AR_NIC_NICLM_DBG_LM0_PTRS_LM_MULT_EVENT_BP, AR_NIC_NICLM_DBG_LM0_PTRS_LM_MULT_EVENT_MASK },
    { "LM_WR_AD_WRAP", AR_NIC_NICLM_DBG_LM0_PTRS_LM_WR_AD_WRAP_BP, AR_NIC_NICLM_DBG_LM0_PTRS_LM_WR_AD_WRAP_MASK },
    { "LM_RD_PTR", AR_NIC_NICLM_DBG_LM0_PTRS_LM_RD_PTR_BP, AR_NIC_NICLM_DBG_LM0_PTRS_LM_RD_PTR_MASK },
    { "LM_WR_PTR", AR_NIC_NICLM_DBG_LM0_PTRS_LM_WR_PTR_BP, AR_NIC_NICLM_DBG_LM0_PTRS_LM_WR_PTR_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_dbg_lm0_read_lo_detail[] = {
    { "DATA", AR_NIC_NICLM_DBG_LM0_READ_LO_DATA_BP, AR_NIC_NICLM_DBG_LM0_READ_LO_DATA_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_dbg_lm0_read_mid_detail[] = {
    { "DATA", AR_NIC_NICLM_DBG_LM0_READ_MID_DATA_BP, AR_NIC_NICLM_DBG_LM0_READ_MID_DATA_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_dbg_lm0_read_hi_detail[] = {
    { "DATA", AR_NIC_NICLM_DBG_LM0_READ_HI_DATA_BP, AR_NIC_NICLM_DBG_LM0_READ_HI_DATA_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_dbg_lm0_snap_sel_detail[] = {
    { "SEL", AR_NIC_NICLM_DBG_LM0_SNAP_SEL_SEL_BP, AR_NIC_NICLM_DBG_LM0_SNAP_SEL_SEL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_dbg_lm0_snap_dlo_detail[] = {
    { "DATA", AR_NIC_NICLM_DBG_LM0_SNAP_DLO_DATA_BP, AR_NIC_NICLM_DBG_LM0_SNAP_DLO_DATA_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_dbg_lm0_snap_dmid_detail[] = {
    { "DATA", AR_NIC_NICLM_DBG_LM0_SNAP_DMID_DATA_BP, AR_NIC_NICLM_DBG_LM0_SNAP_DMID_DATA_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_dbg_lm0_snap_dhi_detail[] = {
    { "DATA", AR_NIC_NICLM_DBG_LM0_SNAP_DHI_DATA_BP, AR_NIC_NICLM_DBG_LM0_SNAP_DHI_DATA_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_dbg_lm1_ctl_detail[] = {
    { "LM_RST", AR_NIC_NICLM_DBG_LM1_CTL_LM_RST_BP, AR_NIC_NICLM_DBG_LM1_CTL_LM_RST_MASK },
    { "LM_TRIG_STATE", AR_NIC_NICLM_DBG_LM1_CTL_LM_TRIG_STATE_BP, AR_NIC_NICLM_DBG_LM1_CTL_LM_TRIG_STATE_MASK },
    { "LM_CAP_STATE", AR_NIC_NICLM_DBG_LM1_CTL_LM_CAP_STATE_BP, AR_NIC_NICLM_DBG_LM1_CTL_LM_CAP_STATE_MASK },
    { "LM_CTL_T0_CNT", AR_NIC_NICLM_DBG_LM1_CTL_LM_CTL_T0_CNT_BP, AR_NIC_NICLM_DBG_LM1_CTL_LM_CTL_T0_CNT_MASK },
    { "LM_CTL_T1_CNT", AR_NIC_NICLM_DBG_LM1_CTL_LM_CTL_T1_CNT_BP, AR_NIC_NICLM_DBG_LM1_CTL_LM_CTL_T1_CNT_MASK },
    { "LM_TRIG_EN", AR_NIC_NICLM_DBG_LM1_CTL_LM_TRIG_EN_BP, AR_NIC_NICLM_DBG_LM1_CTL_LM_TRIG_EN_MASK },
    { "LM_CTL_MODE", AR_NIC_NICLM_DBG_LM1_CTL_LM_CTL_MODE_BP, AR_NIC_NICLM_DBG_LM1_CTL_LM_CTL_MODE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_dbg_lm1_ptrs_detail[] = {
    { "LM_REC_ACT", AR_NIC_NICLM_DBG_LM1_PTRS_LM_REC_ACT_BP, AR_NIC_NICLM_DBG_LM1_PTRS_LM_REC_ACT_MASK },
    { "LM_REC_DONE", AR_NIC_NICLM_DBG_LM1_PTRS_LM_REC_DONE_BP, AR_NIC_NICLM_DBG_LM1_PTRS_LM_REC_DONE_MASK },
    { "LM_MULT_EVENT", AR_NIC_NICLM_DBG_LM1_PTRS_LM_MULT_EVENT_BP, AR_NIC_NICLM_DBG_LM1_PTRS_LM_MULT_EVENT_MASK },
    { "LM_WR_AD_WRAP", AR_NIC_NICLM_DBG_LM1_PTRS_LM_WR_AD_WRAP_BP, AR_NIC_NICLM_DBG_LM1_PTRS_LM_WR_AD_WRAP_MASK },
    { "LM_RD_PTR", AR_NIC_NICLM_DBG_LM1_PTRS_LM_RD_PTR_BP, AR_NIC_NICLM_DBG_LM1_PTRS_LM_RD_PTR_MASK },
    { "LM_WR_PTR", AR_NIC_NICLM_DBG_LM1_PTRS_LM_WR_PTR_BP, AR_NIC_NICLM_DBG_LM1_PTRS_LM_WR_PTR_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_dbg_lm1_read_lo_detail[] = {
    { "DATA", AR_NIC_NICLM_DBG_LM1_READ_LO_DATA_BP, AR_NIC_NICLM_DBG_LM1_READ_LO_DATA_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_dbg_lm1_read_mid_detail[] = {
    { "DATA", AR_NIC_NICLM_DBG_LM1_READ_MID_DATA_BP, AR_NIC_NICLM_DBG_LM1_READ_MID_DATA_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_dbg_lm1_read_hi_detail[] = {
    { "DATA", AR_NIC_NICLM_DBG_LM1_READ_HI_DATA_BP, AR_NIC_NICLM_DBG_LM1_READ_HI_DATA_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_dbg_lm1_snap_sel_detail[] = {
    { "SEL", AR_NIC_NICLM_DBG_LM1_SNAP_SEL_SEL_BP, AR_NIC_NICLM_DBG_LM1_SNAP_SEL_SEL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_dbg_lm1_snap_dlo_detail[] = {
    { "DATA", AR_NIC_NICLM_DBG_LM1_SNAP_DLO_DATA_BP, AR_NIC_NICLM_DBG_LM1_SNAP_DLO_DATA_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_dbg_lm1_snap_dmid_detail[] = {
    { "DATA", AR_NIC_NICLM_DBG_LM1_SNAP_DMID_DATA_BP, AR_NIC_NICLM_DBG_LM1_SNAP_DMID_DATA_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_dbg_lm1_snap_dhi_detail[] = {
    { "DATA", AR_NIC_NICLM_DBG_LM1_SNAP_DHI_DATA_BP, AR_NIC_NICLM_DBG_LM1_SNAP_DHI_DATA_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_dbg_rem_trig_detail[] = {
    { "NL_PROP_TO_PI", AR_NIC_NICLM_DBG_REM_TRIG_NL_PROP_TO_PI_BP, AR_NIC_NICLM_DBG_REM_TRIG_NL_PROP_TO_PI_MASK },
    { "PI_PROP_TO_NL", AR_NIC_NICLM_DBG_REM_TRIG_PI_PROP_TO_NL_BP, AR_NIC_NICLM_DBG_REM_TRIG_PI_PROP_TO_NL_MASK },
    { "LM1_PROP_TO_NL", AR_NIC_NICLM_DBG_REM_TRIG_LM1_PROP_TO_NL_BP, AR_NIC_NICLM_DBG_REM_TRIG_LM1_PROP_TO_NL_MASK },
    { "LM0_PROP_TO_NL", AR_NIC_NICLM_DBG_REM_TRIG_LM0_PROP_TO_NL_BP, AR_NIC_NICLM_DBG_REM_TRIG_LM0_PROP_TO_NL_MASK },
    { "LM1_PROP_TO_PI", AR_NIC_NICLM_DBG_REM_TRIG_LM1_PROP_TO_PI_BP, AR_NIC_NICLM_DBG_REM_TRIG_LM1_PROP_TO_PI_MASK },
    { "LM0_PROP_TO_PI", AR_NIC_NICLM_DBG_REM_TRIG_LM0_PROP_TO_PI_BP, AR_NIC_NICLM_DBG_REM_TRIG_LM0_PROP_TO_PI_MASK },
    { "LM1_ENABLE_NIC_RSP_HSS_IRQ", AR_NIC_NICLM_DBG_REM_TRIG_LM1_ENABLE_NIC_RSP_HSS_IRQ_BP, AR_NIC_NICLM_DBG_REM_TRIG_LM1_ENABLE_NIC_RSP_HSS_IRQ_MASK },
    { "LM1_ENABLE_NIC_REQ_HSS_IRQ", AR_NIC_NICLM_DBG_REM_TRIG_LM1_ENABLE_NIC_REQ_HSS_IRQ_BP, AR_NIC_NICLM_DBG_REM_TRIG_LM1_ENABLE_NIC_REQ_HSS_IRQ_MASK },
    { "LM1_ENABLE_NIC_NET_HSS_IRQ", AR_NIC_NICLM_DBG_REM_TRIG_LM1_ENABLE_NIC_NET_HSS_IRQ_BP, AR_NIC_NICLM_DBG_REM_TRIG_LM1_ENABLE_NIC_NET_HSS_IRQ_MASK },
    { "LM0_ENABLE_NIC_RSP_HSS_IRQ", AR_NIC_NICLM_DBG_REM_TRIG_LM0_ENABLE_NIC_RSP_HSS_IRQ_BP, AR_NIC_NICLM_DBG_REM_TRIG_LM0_ENABLE_NIC_RSP_HSS_IRQ_MASK },
    { "LM0_ENABLE_NIC_REQ_HSS_IRQ", AR_NIC_NICLM_DBG_REM_TRIG_LM0_ENABLE_NIC_REQ_HSS_IRQ_BP, AR_NIC_NICLM_DBG_REM_TRIG_LM0_ENABLE_NIC_REQ_HSS_IRQ_MASK },
    { "LM0_ENABLE_NIC_NET_HSS_IRQ", AR_NIC_NICLM_DBG_REM_TRIG_LM0_ENABLE_NIC_NET_HSS_IRQ_BP, AR_NIC_NICLM_DBG_REM_TRIG_LM0_ENABLE_NIC_NET_HSS_IRQ_MASK },
    { "LM1_ENABLE_NIC_HSS_IRQ", AR_NIC_NICLM_DBG_REM_TRIG_LM1_ENABLE_NIC_HSS_IRQ_BP, AR_NIC_NICLM_DBG_REM_TRIG_LM1_ENABLE_NIC_HSS_IRQ_MASK },
    { "LM0_ENABLE_NIC_HSS_IRQ", AR_NIC_NICLM_DBG_REM_TRIG_LM0_ENABLE_NIC_HSS_IRQ_BP, AR_NIC_NICLM_DBG_REM_TRIG_LM0_ENABLE_NIC_HSS_IRQ_MASK },
    { "LM1_ENABLE_FROM_NL", AR_NIC_NICLM_DBG_REM_TRIG_LM1_ENABLE_FROM_NL_BP, AR_NIC_NICLM_DBG_REM_TRIG_LM1_ENABLE_FROM_NL_MASK },
    { "LM0_ENABLE_FROM_NL", AR_NIC_NICLM_DBG_REM_TRIG_LM0_ENABLE_FROM_NL_BP, AR_NIC_NICLM_DBG_REM_TRIG_LM0_ENABLE_FROM_NL_MASK },
    { "LM1_ENABLE_FROM_PI", AR_NIC_NICLM_DBG_REM_TRIG_LM1_ENABLE_FROM_PI_BP, AR_NIC_NICLM_DBG_REM_TRIG_LM1_ENABLE_FROM_PI_MASK },
    { "LM0_ENABLE_FROM_PI", AR_NIC_NICLM_DBG_REM_TRIG_LM0_ENABLE_FROM_PI_BP, AR_NIC_NICLM_DBG_REM_TRIG_LM0_ENABLE_FROM_PI_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_dbg_trig_sts_detail[] = {
    { "LM1_REM_TRIG1_RCV_LAST", AR_NIC_NICLM_DBG_TRIG_STS_LM1_REM_TRIG1_RCV_LAST_BP, AR_NIC_NICLM_DBG_TRIG_STS_LM1_REM_TRIG1_RCV_LAST_MASK },
    { "LM1_REM_TRIG0_RCV_LAST", AR_NIC_NICLM_DBG_TRIG_STS_LM1_REM_TRIG0_RCV_LAST_BP, AR_NIC_NICLM_DBG_TRIG_STS_LM1_REM_TRIG0_RCV_LAST_MASK },
    { "LM1_REM_TRIG1_RCV_FIRST", AR_NIC_NICLM_DBG_TRIG_STS_LM1_REM_TRIG1_RCV_FIRST_BP, AR_NIC_NICLM_DBG_TRIG_STS_LM1_REM_TRIG1_RCV_FIRST_MASK },
    { "LM1_REM_TRIG0_RCV_FIRST", AR_NIC_NICLM_DBG_TRIG_STS_LM1_REM_TRIG0_RCV_FIRST_BP, AR_NIC_NICLM_DBG_TRIG_STS_LM1_REM_TRIG0_RCV_FIRST_MASK },
    { "LM1_REM_TRIG1_RCV", AR_NIC_NICLM_DBG_TRIG_STS_LM1_REM_TRIG1_RCV_BP, AR_NIC_NICLM_DBG_TRIG_STS_LM1_REM_TRIG1_RCV_MASK },
    { "LM1_REM_TRIG0_RCV", AR_NIC_NICLM_DBG_TRIG_STS_LM1_REM_TRIG0_RCV_BP, AR_NIC_NICLM_DBG_TRIG_STS_LM1_REM_TRIG0_RCV_MASK },
    { "LM1_LCL_TRIG1_RCV", AR_NIC_NICLM_DBG_TRIG_STS_LM1_LCL_TRIG1_RCV_BP, AR_NIC_NICLM_DBG_TRIG_STS_LM1_LCL_TRIG1_RCV_MASK },
    { "LM1_LCL_TRIG0_RCV", AR_NIC_NICLM_DBG_TRIG_STS_LM1_LCL_TRIG0_RCV_BP, AR_NIC_NICLM_DBG_TRIG_STS_LM1_LCL_TRIG0_RCV_MASK },
    { "LM0_REM_TRIG1_RCV_LAST", AR_NIC_NICLM_DBG_TRIG_STS_LM0_REM_TRIG1_RCV_LAST_BP, AR_NIC_NICLM_DBG_TRIG_STS_LM0_REM_TRIG1_RCV_LAST_MASK },
    { "LM0_REM_TRIG0_RCV_LAST", AR_NIC_NICLM_DBG_TRIG_STS_LM0_REM_TRIG0_RCV_LAST_BP, AR_NIC_NICLM_DBG_TRIG_STS_LM0_REM_TRIG0_RCV_LAST_MASK },
    { "LM0_REM_TRIG1_RCV_FIRST", AR_NIC_NICLM_DBG_TRIG_STS_LM0_REM_TRIG1_RCV_FIRST_BP, AR_NIC_NICLM_DBG_TRIG_STS_LM0_REM_TRIG1_RCV_FIRST_MASK },
    { "LM0_REM_TRIG0_RCV_FIRST", AR_NIC_NICLM_DBG_TRIG_STS_LM0_REM_TRIG0_RCV_FIRST_BP, AR_NIC_NICLM_DBG_TRIG_STS_LM0_REM_TRIG0_RCV_FIRST_MASK },
    { "LM0_REM_TRIG1_RCV", AR_NIC_NICLM_DBG_TRIG_STS_LM0_REM_TRIG1_RCV_BP, AR_NIC_NICLM_DBG_TRIG_STS_LM0_REM_TRIG1_RCV_MASK },
    { "LM0_REM_TRIG0_RCV", AR_NIC_NICLM_DBG_TRIG_STS_LM0_REM_TRIG0_RCV_BP, AR_NIC_NICLM_DBG_TRIG_STS_LM0_REM_TRIG0_RCV_MASK },
    { "LM0_LCL_TRIG1_RCV", AR_NIC_NICLM_DBG_TRIG_STS_LM0_LCL_TRIG1_RCV_BP, AR_NIC_NICLM_DBG_TRIG_STS_LM0_LCL_TRIG1_RCV_MASK },
    { "LM0_LCL_TRIG0_RCV", AR_NIC_NICLM_DBG_TRIG_STS_LM0_LCL_TRIG0_RCV_BP, AR_NIC_NICLM_DBG_TRIG_STS_LM0_LCL_TRIG0_RCV_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_err_flg_detail[] = {
    { "PI_TRIGGER1", AR_NIC_NICLM_ERR_FLG_PI_TRIGGER1_BP, AR_NIC_NICLM_ERR_FLG_PI_TRIGGER1_MASK },
    { "PI_TRIGGER0", AR_NIC_NICLM_ERR_FLG_PI_TRIGGER0_BP, AR_NIC_NICLM_ERR_FLG_PI_TRIGGER0_MASK },
    { "NL_TRIGGER1", AR_NIC_NICLM_ERR_FLG_NL_TRIGGER1_BP, AR_NIC_NICLM_ERR_FLG_NL_TRIGGER1_MASK },
    { "NL_TRIGGER0", AR_NIC_NICLM_ERR_FLG_NL_TRIGGER0_BP, AR_NIC_NICLM_ERR_FLG_NL_TRIGGER0_MASK },
    { "RSPMON_TRIGGER1", AR_NIC_NICLM_ERR_FLG_RSPMON_TRIGGER1_BP, AR_NIC_NICLM_ERR_FLG_RSPMON_TRIGGER1_MASK },
    { "RSPMON_TRIGGER0", AR_NIC_NICLM_ERR_FLG_RSPMON_TRIGGER0_BP, AR_NIC_NICLM_ERR_FLG_RSPMON_TRIGGER0_MASK },
    { "REQMON_TRIGGER1", AR_NIC_NICLM_ERR_FLG_REQMON_TRIGGER1_BP, AR_NIC_NICLM_ERR_FLG_REQMON_TRIGGER1_MASK },
    { "REQMON_TRIGGER0", AR_NIC_NICLM_ERR_FLG_REQMON_TRIGGER0_BP, AR_NIC_NICLM_ERR_FLG_REQMON_TRIGGER0_MASK },
    { "NETMON_TRIGGER1", AR_NIC_NICLM_ERR_FLG_NETMON_TRIGGER1_BP, AR_NIC_NICLM_ERR_FLG_NETMON_TRIGGER1_MASK },
    { "NETMON_TRIGGER0", AR_NIC_NICLM_ERR_FLG_NETMON_TRIGGER0_BP, AR_NIC_NICLM_ERR_FLG_NETMON_TRIGGER0_MASK },
    { "LM1_RAM_PARITY", AR_NIC_NICLM_ERR_FLG_LM1_RAM_PARITY_BP, AR_NIC_NICLM_ERR_FLG_LM1_RAM_PARITY_MASK },
    { "LM0_RAM_PARITY", AR_NIC_NICLM_ERR_FLG_LM0_RAM_PARITY_BP, AR_NIC_NICLM_ERR_FLG_LM0_RAM_PARITY_MASK },
    { "DIAG_ONLY", AR_NIC_NICLM_ERR_FLG_DIAG_ONLY_BP, AR_NIC_NICLM_ERR_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
#ifdef EXCEPTIONS_DEFS
static const errcat_mmrd_t _ar_nic_niclm_err_flg_errcat[] = {
    { "PI_TRIGGER1", AR_NIC_NICLM_ERR_FLG_PI_TRIGGER1_BP, AR_NIC_NICLM_ERR_FLG_PI_TRIGGER1_EC },
    { "PI_TRIGGER0", AR_NIC_NICLM_ERR_FLG_PI_TRIGGER0_BP, AR_NIC_NICLM_ERR_FLG_PI_TRIGGER0_EC },
    { "NL_TRIGGER1", AR_NIC_NICLM_ERR_FLG_NL_TRIGGER1_BP, AR_NIC_NICLM_ERR_FLG_NL_TRIGGER1_EC },
    { "NL_TRIGGER0", AR_NIC_NICLM_ERR_FLG_NL_TRIGGER0_BP, AR_NIC_NICLM_ERR_FLG_NL_TRIGGER0_EC },
    { "RSPMON_TRIGGER1", AR_NIC_NICLM_ERR_FLG_RSPMON_TRIGGER1_BP, AR_NIC_NICLM_ERR_FLG_RSPMON_TRIGGER1_EC },
    { "RSPMON_TRIGGER0", AR_NIC_NICLM_ERR_FLG_RSPMON_TRIGGER0_BP, AR_NIC_NICLM_ERR_FLG_RSPMON_TRIGGER0_EC },
    { "REQMON_TRIGGER1", AR_NIC_NICLM_ERR_FLG_REQMON_TRIGGER1_BP, AR_NIC_NICLM_ERR_FLG_REQMON_TRIGGER1_EC },
    { "REQMON_TRIGGER0", AR_NIC_NICLM_ERR_FLG_REQMON_TRIGGER0_BP, AR_NIC_NICLM_ERR_FLG_REQMON_TRIGGER0_EC },
    { "NETMON_TRIGGER1", AR_NIC_NICLM_ERR_FLG_NETMON_TRIGGER1_BP, AR_NIC_NICLM_ERR_FLG_NETMON_TRIGGER1_EC },
    { "NETMON_TRIGGER0", AR_NIC_NICLM_ERR_FLG_NETMON_TRIGGER0_BP, AR_NIC_NICLM_ERR_FLG_NETMON_TRIGGER0_EC },
    { "LM1_RAM_PARITY", AR_NIC_NICLM_ERR_FLG_LM1_RAM_PARITY_BP, AR_NIC_NICLM_ERR_FLG_LM1_RAM_PARITY_EC },
    { "LM0_RAM_PARITY", AR_NIC_NICLM_ERR_FLG_LM0_RAM_PARITY_BP, AR_NIC_NICLM_ERR_FLG_LM0_RAM_PARITY_EC },
    { "DIAG_ONLY", AR_NIC_NICLM_ERR_FLG_DIAG_ONLY_BP, AR_NIC_NICLM_ERR_FLG_DIAG_ONLY_EC },
    { NULL, 0, 0 }
};
#endif
static const generic_mmrd_t _ar_nic_niclm_err_clr_detail[] = {
    { "PI_TRIGGER1", AR_NIC_NICLM_ERR_CLR_PI_TRIGGER1_BP, AR_NIC_NICLM_ERR_CLR_PI_TRIGGER1_MASK },
    { "PI_TRIGGER0", AR_NIC_NICLM_ERR_CLR_PI_TRIGGER0_BP, AR_NIC_NICLM_ERR_CLR_PI_TRIGGER0_MASK },
    { "NL_TRIGGER1", AR_NIC_NICLM_ERR_CLR_NL_TRIGGER1_BP, AR_NIC_NICLM_ERR_CLR_NL_TRIGGER1_MASK },
    { "NL_TRIGGER0", AR_NIC_NICLM_ERR_CLR_NL_TRIGGER0_BP, AR_NIC_NICLM_ERR_CLR_NL_TRIGGER0_MASK },
    { "RSPMON_TRIGGER1", AR_NIC_NICLM_ERR_CLR_RSPMON_TRIGGER1_BP, AR_NIC_NICLM_ERR_CLR_RSPMON_TRIGGER1_MASK },
    { "RSPMON_TRIGGER0", AR_NIC_NICLM_ERR_CLR_RSPMON_TRIGGER0_BP, AR_NIC_NICLM_ERR_CLR_RSPMON_TRIGGER0_MASK },
    { "REQMON_TRIGGER1", AR_NIC_NICLM_ERR_CLR_REQMON_TRIGGER1_BP, AR_NIC_NICLM_ERR_CLR_REQMON_TRIGGER1_MASK },
    { "REQMON_TRIGGER0", AR_NIC_NICLM_ERR_CLR_REQMON_TRIGGER0_BP, AR_NIC_NICLM_ERR_CLR_REQMON_TRIGGER0_MASK },
    { "NETMON_TRIGGER1", AR_NIC_NICLM_ERR_CLR_NETMON_TRIGGER1_BP, AR_NIC_NICLM_ERR_CLR_NETMON_TRIGGER1_MASK },
    { "NETMON_TRIGGER0", AR_NIC_NICLM_ERR_CLR_NETMON_TRIGGER0_BP, AR_NIC_NICLM_ERR_CLR_NETMON_TRIGGER0_MASK },
    { "LM1_RAM_PARITY", AR_NIC_NICLM_ERR_CLR_LM1_RAM_PARITY_BP, AR_NIC_NICLM_ERR_CLR_LM1_RAM_PARITY_MASK },
    { "LM0_RAM_PARITY", AR_NIC_NICLM_ERR_CLR_LM0_RAM_PARITY_BP, AR_NIC_NICLM_ERR_CLR_LM0_RAM_PARITY_MASK },
    { "DIAG_ONLY", AR_NIC_NICLM_ERR_CLR_DIAG_ONLY_BP, AR_NIC_NICLM_ERR_CLR_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_err_hss_msk_detail[] = {
    { "PI_TRIGGER1", AR_NIC_NICLM_ERR_HSS_MSK_PI_TRIGGER1_BP, AR_NIC_NICLM_ERR_HSS_MSK_PI_TRIGGER1_MASK },
    { "PI_TRIGGER0", AR_NIC_NICLM_ERR_HSS_MSK_PI_TRIGGER0_BP, AR_NIC_NICLM_ERR_HSS_MSK_PI_TRIGGER0_MASK },
    { "NL_TRIGGER1", AR_NIC_NICLM_ERR_HSS_MSK_NL_TRIGGER1_BP, AR_NIC_NICLM_ERR_HSS_MSK_NL_TRIGGER1_MASK },
    { "NL_TRIGGER0", AR_NIC_NICLM_ERR_HSS_MSK_NL_TRIGGER0_BP, AR_NIC_NICLM_ERR_HSS_MSK_NL_TRIGGER0_MASK },
    { "RSPMON_TRIGGER1", AR_NIC_NICLM_ERR_HSS_MSK_RSPMON_TRIGGER1_BP, AR_NIC_NICLM_ERR_HSS_MSK_RSPMON_TRIGGER1_MASK },
    { "RSPMON_TRIGGER0", AR_NIC_NICLM_ERR_HSS_MSK_RSPMON_TRIGGER0_BP, AR_NIC_NICLM_ERR_HSS_MSK_RSPMON_TRIGGER0_MASK },
    { "REQMON_TRIGGER1", AR_NIC_NICLM_ERR_HSS_MSK_REQMON_TRIGGER1_BP, AR_NIC_NICLM_ERR_HSS_MSK_REQMON_TRIGGER1_MASK },
    { "REQMON_TRIGGER0", AR_NIC_NICLM_ERR_HSS_MSK_REQMON_TRIGGER0_BP, AR_NIC_NICLM_ERR_HSS_MSK_REQMON_TRIGGER0_MASK },
    { "NETMON_TRIGGER1", AR_NIC_NICLM_ERR_HSS_MSK_NETMON_TRIGGER1_BP, AR_NIC_NICLM_ERR_HSS_MSK_NETMON_TRIGGER1_MASK },
    { "NETMON_TRIGGER0", AR_NIC_NICLM_ERR_HSS_MSK_NETMON_TRIGGER0_BP, AR_NIC_NICLM_ERR_HSS_MSK_NETMON_TRIGGER0_MASK },
    { "LM1_RAM_PARITY", AR_NIC_NICLM_ERR_HSS_MSK_LM1_RAM_PARITY_BP, AR_NIC_NICLM_ERR_HSS_MSK_LM1_RAM_PARITY_MASK },
    { "LM0_RAM_PARITY", AR_NIC_NICLM_ERR_HSS_MSK_LM0_RAM_PARITY_BP, AR_NIC_NICLM_ERR_HSS_MSK_LM0_RAM_PARITY_MASK },
    { "DIAG_ONLY", AR_NIC_NICLM_ERR_HSS_MSK_DIAG_ONLY_BP, AR_NIC_NICLM_ERR_HSS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_err_os_msk_detail[] = {
    { "PI_TRIGGER1", AR_NIC_NICLM_ERR_OS_MSK_PI_TRIGGER1_BP, AR_NIC_NICLM_ERR_OS_MSK_PI_TRIGGER1_MASK },
    { "PI_TRIGGER0", AR_NIC_NICLM_ERR_OS_MSK_PI_TRIGGER0_BP, AR_NIC_NICLM_ERR_OS_MSK_PI_TRIGGER0_MASK },
    { "NL_TRIGGER1", AR_NIC_NICLM_ERR_OS_MSK_NL_TRIGGER1_BP, AR_NIC_NICLM_ERR_OS_MSK_NL_TRIGGER1_MASK },
    { "NL_TRIGGER0", AR_NIC_NICLM_ERR_OS_MSK_NL_TRIGGER0_BP, AR_NIC_NICLM_ERR_OS_MSK_NL_TRIGGER0_MASK },
    { "RSPMON_TRIGGER1", AR_NIC_NICLM_ERR_OS_MSK_RSPMON_TRIGGER1_BP, AR_NIC_NICLM_ERR_OS_MSK_RSPMON_TRIGGER1_MASK },
    { "RSPMON_TRIGGER0", AR_NIC_NICLM_ERR_OS_MSK_RSPMON_TRIGGER0_BP, AR_NIC_NICLM_ERR_OS_MSK_RSPMON_TRIGGER0_MASK },
    { "REQMON_TRIGGER1", AR_NIC_NICLM_ERR_OS_MSK_REQMON_TRIGGER1_BP, AR_NIC_NICLM_ERR_OS_MSK_REQMON_TRIGGER1_MASK },
    { "REQMON_TRIGGER0", AR_NIC_NICLM_ERR_OS_MSK_REQMON_TRIGGER0_BP, AR_NIC_NICLM_ERR_OS_MSK_REQMON_TRIGGER0_MASK },
    { "NETMON_TRIGGER1", AR_NIC_NICLM_ERR_OS_MSK_NETMON_TRIGGER1_BP, AR_NIC_NICLM_ERR_OS_MSK_NETMON_TRIGGER1_MASK },
    { "NETMON_TRIGGER0", AR_NIC_NICLM_ERR_OS_MSK_NETMON_TRIGGER0_BP, AR_NIC_NICLM_ERR_OS_MSK_NETMON_TRIGGER0_MASK },
    { "LM1_RAM_PARITY", AR_NIC_NICLM_ERR_OS_MSK_LM1_RAM_PARITY_BP, AR_NIC_NICLM_ERR_OS_MSK_LM1_RAM_PARITY_MASK },
    { "LM0_RAM_PARITY", AR_NIC_NICLM_ERR_OS_MSK_LM0_RAM_PARITY_BP, AR_NIC_NICLM_ERR_OS_MSK_LM0_RAM_PARITY_MASK },
    { "DIAG_ONLY", AR_NIC_NICLM_ERR_OS_MSK_DIAG_ONLY_BP, AR_NIC_NICLM_ERR_OS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_err_first_flg_detail[] = {
    { "PI_TRIGGER1", AR_NIC_NICLM_ERR_FIRST_FLG_PI_TRIGGER1_BP, AR_NIC_NICLM_ERR_FIRST_FLG_PI_TRIGGER1_MASK },
    { "PI_TRIGGER0", AR_NIC_NICLM_ERR_FIRST_FLG_PI_TRIGGER0_BP, AR_NIC_NICLM_ERR_FIRST_FLG_PI_TRIGGER0_MASK },
    { "NL_TRIGGER1", AR_NIC_NICLM_ERR_FIRST_FLG_NL_TRIGGER1_BP, AR_NIC_NICLM_ERR_FIRST_FLG_NL_TRIGGER1_MASK },
    { "NL_TRIGGER0", AR_NIC_NICLM_ERR_FIRST_FLG_NL_TRIGGER0_BP, AR_NIC_NICLM_ERR_FIRST_FLG_NL_TRIGGER0_MASK },
    { "RSPMON_TRIGGER1", AR_NIC_NICLM_ERR_FIRST_FLG_RSPMON_TRIGGER1_BP, AR_NIC_NICLM_ERR_FIRST_FLG_RSPMON_TRIGGER1_MASK },
    { "RSPMON_TRIGGER0", AR_NIC_NICLM_ERR_FIRST_FLG_RSPMON_TRIGGER0_BP, AR_NIC_NICLM_ERR_FIRST_FLG_RSPMON_TRIGGER0_MASK },
    { "REQMON_TRIGGER1", AR_NIC_NICLM_ERR_FIRST_FLG_REQMON_TRIGGER1_BP, AR_NIC_NICLM_ERR_FIRST_FLG_REQMON_TRIGGER1_MASK },
    { "REQMON_TRIGGER0", AR_NIC_NICLM_ERR_FIRST_FLG_REQMON_TRIGGER0_BP, AR_NIC_NICLM_ERR_FIRST_FLG_REQMON_TRIGGER0_MASK },
    { "NETMON_TRIGGER1", AR_NIC_NICLM_ERR_FIRST_FLG_NETMON_TRIGGER1_BP, AR_NIC_NICLM_ERR_FIRST_FLG_NETMON_TRIGGER1_MASK },
    { "NETMON_TRIGGER0", AR_NIC_NICLM_ERR_FIRST_FLG_NETMON_TRIGGER0_BP, AR_NIC_NICLM_ERR_FIRST_FLG_NETMON_TRIGGER0_MASK },
    { "LM1_RAM_PARITY", AR_NIC_NICLM_ERR_FIRST_FLG_LM1_RAM_PARITY_BP, AR_NIC_NICLM_ERR_FIRST_FLG_LM1_RAM_PARITY_MASK },
    { "LM0_RAM_PARITY", AR_NIC_NICLM_ERR_FIRST_FLG_LM0_RAM_PARITY_BP, AR_NIC_NICLM_ERR_FIRST_FLG_LM0_RAM_PARITY_MASK },
    { "DIAG_ONLY", AR_NIC_NICLM_ERR_FIRST_FLG_DIAG_ONLY_BP, AR_NIC_NICLM_ERR_FIRST_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_dbg_errinj_perr_detail[] = {
    { "ADDRESS", AR_NIC_NICLM_DBG_ERRINJ_PERR_ADDRESS_BP, AR_NIC_NICLM_DBG_ERRINJ_PERR_ADDRESS_MASK },
    { "CHECKBITS", AR_NIC_NICLM_DBG_ERRINJ_PERR_CHECKBITS_BP, AR_NIC_NICLM_DBG_ERRINJ_PERR_CHECKBITS_MASK },
    { "LM1_TRIGGERED", AR_NIC_NICLM_DBG_ERRINJ_PERR_LM1_TRIGGERED_BP, AR_NIC_NICLM_DBG_ERRINJ_PERR_LM1_TRIGGERED_MASK },
    { "LM0_TRIGGERED", AR_NIC_NICLM_DBG_ERRINJ_PERR_LM0_TRIGGERED_BP, AR_NIC_NICLM_DBG_ERRINJ_PERR_LM0_TRIGGERED_MASK },
    { "RAM_SELECT", AR_NIC_NICLM_DBG_ERRINJ_PERR_RAM_SELECT_BP, AR_NIC_NICLM_DBG_ERRINJ_PERR_RAM_SELECT_MASK },
    { "MODE", AR_NIC_NICLM_DBG_ERRINJ_PERR_MODE_BP, AR_NIC_NICLM_DBG_ERRINJ_PERR_MODE_MASK },
    { "ENABLE", AR_NIC_NICLM_DBG_ERRINJ_PERR_ENABLE_BP, AR_NIC_NICLM_DBG_ERRINJ_PERR_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_err_info_perr_detail[] = {
    { "LM1_ADDRESS", AR_NIC_NICLM_ERR_INFO_PERR_LM1_ADDRESS_BP, AR_NIC_NICLM_ERR_INFO_PERR_LM1_ADDRESS_MASK },
    { "LM0_ADDRESS", AR_NIC_NICLM_ERR_INFO_PERR_LM0_ADDRESS_BP, AR_NIC_NICLM_ERR_INFO_PERR_LM0_ADDRESS_MASK },
    { "LM1_MMR_DETECTED_PERR", AR_NIC_NICLM_ERR_INFO_PERR_LM1_MMR_DETECTED_PERR_BP, AR_NIC_NICLM_ERR_INFO_PERR_LM1_MMR_DETECTED_PERR_MASK },
    { "LM0_MMR_DETECTED_PERR", AR_NIC_NICLM_ERR_INFO_PERR_LM0_MMR_DETECTED_PERR_BP, AR_NIC_NICLM_ERR_INFO_PERR_LM0_MMR_DETECTED_PERR_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_err_info_lm0_perr_cnt_detail[] = {
    { "CNT", AR_NIC_NICLM_ERR_INFO_LM0_PERR_CNT_CNT_BP, AR_NIC_NICLM_ERR_INFO_LM0_PERR_CNT_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_err_info_lm1_perr_cnt_detail[] = {
    { "CNT", AR_NIC_NICLM_ERR_INFO_LM1_PERR_CNT_CNT_BP, AR_NIC_NICLM_ERR_INFO_LM1_PERR_CNT_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_niclm_err_frc_hss_irq_detail[] = {
    { NULL, 0, 0 }
};

/*
 *  AR NICLM MMR DECLARATIONS
 */
static const generic_mmr_t _ar_nic_niclm_dbg_lm0_ctl = {
    "AR_NIC_NICLM_DBG_LM0_CTL", AR_NIC_NICLM_DBG_LM0_CTL, 8, 1, _ar_nic_niclm_dbg_lm0_ctl_detail
};
static const generic_mmr_t _ar_nic_niclm_dbg_lm0_ptrs = {
    "AR_NIC_NICLM_DBG_LM0_PTRS", AR_NIC_NICLM_DBG_LM0_PTRS, 8, 1, _ar_nic_niclm_dbg_lm0_ptrs_detail
};
static const generic_mmr_t _ar_nic_niclm_dbg_lm0_read_lo = {
    "AR_NIC_NICLM_DBG_LM0_READ_LO", AR_NIC_NICLM_DBG_LM0_READ_LO, 8, 1, _ar_nic_niclm_dbg_lm0_read_lo_detail
};
static const generic_mmr_t _ar_nic_niclm_dbg_lm0_read_mid = {
    "AR_NIC_NICLM_DBG_LM0_READ_MID", AR_NIC_NICLM_DBG_LM0_READ_MID, 8, 1, _ar_nic_niclm_dbg_lm0_read_mid_detail
};
static const generic_mmr_t _ar_nic_niclm_dbg_lm0_read_hi = {
    "AR_NIC_NICLM_DBG_LM0_READ_HI", AR_NIC_NICLM_DBG_LM0_READ_HI, 8, 1, _ar_nic_niclm_dbg_lm0_read_hi_detail
};
static const generic_mmr_t _ar_nic_niclm_dbg_lm0_snap_sel = {
    "AR_NIC_NICLM_DBG_LM0_SNAP_SEL", AR_NIC_NICLM_DBG_LM0_SNAP_SEL, 8, 1, _ar_nic_niclm_dbg_lm0_snap_sel_detail
};
static const generic_mmr_t _ar_nic_niclm_dbg_lm0_snap_dlo = {
    "AR_NIC_NICLM_DBG_LM0_SNAP_DLO", AR_NIC_NICLM_DBG_LM0_SNAP_DLO, 8, 1, _ar_nic_niclm_dbg_lm0_snap_dlo_detail
};
static const generic_mmr_t _ar_nic_niclm_dbg_lm0_snap_dmid = {
    "AR_NIC_NICLM_DBG_LM0_SNAP_DMID", AR_NIC_NICLM_DBG_LM0_SNAP_DMID, 8, 1, _ar_nic_niclm_dbg_lm0_snap_dmid_detail
};
static const generic_mmr_t _ar_nic_niclm_dbg_lm0_snap_dhi = {
    "AR_NIC_NICLM_DBG_LM0_SNAP_DHI", AR_NIC_NICLM_DBG_LM0_SNAP_DHI, 8, 1, _ar_nic_niclm_dbg_lm0_snap_dhi_detail
};
static const generic_mmr_t _ar_nic_niclm_dbg_lm1_ctl = {
    "AR_NIC_NICLM_DBG_LM1_CTL", AR_NIC_NICLM_DBG_LM1_CTL, 8, 1, _ar_nic_niclm_dbg_lm1_ctl_detail
};
static const generic_mmr_t _ar_nic_niclm_dbg_lm1_ptrs = {
    "AR_NIC_NICLM_DBG_LM1_PTRS", AR_NIC_NICLM_DBG_LM1_PTRS, 8, 1, _ar_nic_niclm_dbg_lm1_ptrs_detail
};
static const generic_mmr_t _ar_nic_niclm_dbg_lm1_read_lo = {
    "AR_NIC_NICLM_DBG_LM1_READ_LO", AR_NIC_NICLM_DBG_LM1_READ_LO, 8, 1, _ar_nic_niclm_dbg_lm1_read_lo_detail
};
static const generic_mmr_t _ar_nic_niclm_dbg_lm1_read_mid = {
    "AR_NIC_NICLM_DBG_LM1_READ_MID", AR_NIC_NICLM_DBG_LM1_READ_MID, 8, 1, _ar_nic_niclm_dbg_lm1_read_mid_detail
};
static const generic_mmr_t _ar_nic_niclm_dbg_lm1_read_hi = {
    "AR_NIC_NICLM_DBG_LM1_READ_HI", AR_NIC_NICLM_DBG_LM1_READ_HI, 8, 1, _ar_nic_niclm_dbg_lm1_read_hi_detail
};
static const generic_mmr_t _ar_nic_niclm_dbg_lm1_snap_sel = {
    "AR_NIC_NICLM_DBG_LM1_SNAP_SEL", AR_NIC_NICLM_DBG_LM1_SNAP_SEL, 8, 1, _ar_nic_niclm_dbg_lm1_snap_sel_detail
};
static const generic_mmr_t _ar_nic_niclm_dbg_lm1_snap_dlo = {
    "AR_NIC_NICLM_DBG_LM1_SNAP_DLO", AR_NIC_NICLM_DBG_LM1_SNAP_DLO, 8, 1, _ar_nic_niclm_dbg_lm1_snap_dlo_detail
};
static const generic_mmr_t _ar_nic_niclm_dbg_lm1_snap_dmid = {
    "AR_NIC_NICLM_DBG_LM1_SNAP_DMID", AR_NIC_NICLM_DBG_LM1_SNAP_DMID, 8, 1, _ar_nic_niclm_dbg_lm1_snap_dmid_detail
};
static const generic_mmr_t _ar_nic_niclm_dbg_lm1_snap_dhi = {
    "AR_NIC_NICLM_DBG_LM1_SNAP_DHI", AR_NIC_NICLM_DBG_LM1_SNAP_DHI, 8, 1, _ar_nic_niclm_dbg_lm1_snap_dhi_detail
};
static const generic_mmr_t _ar_nic_niclm_dbg_rem_trig = {
    "AR_NIC_NICLM_DBG_REM_TRIG", AR_NIC_NICLM_DBG_REM_TRIG, 8, 1, _ar_nic_niclm_dbg_rem_trig_detail
};
static const generic_mmr_t _ar_nic_niclm_dbg_trig_sts = {
    "AR_NIC_NICLM_DBG_TRIG_STS", AR_NIC_NICLM_DBG_TRIG_STS, 8, 1, _ar_nic_niclm_dbg_trig_sts_detail
};
static const generic_mmr_t _ar_nic_niclm_err_flg = {
    "AR_NIC_NICLM_ERR_FLG", AR_NIC_NICLM_ERR_FLG, 8, 1, _ar_nic_niclm_err_flg_detail
};
static const generic_mmr_t _ar_nic_niclm_err_clr = {
    "AR_NIC_NICLM_ERR_CLR", AR_NIC_NICLM_ERR_CLR, 8, 1, _ar_nic_niclm_err_clr_detail
};
static const generic_mmr_t _ar_nic_niclm_err_hss_msk = {
    "AR_NIC_NICLM_ERR_HSS_MSK", AR_NIC_NICLM_ERR_HSS_MSK, 8, 1, _ar_nic_niclm_err_hss_msk_detail
};
static const generic_mmr_t _ar_nic_niclm_err_os_msk = {
    "AR_NIC_NICLM_ERR_OS_MSK", AR_NIC_NICLM_ERR_OS_MSK, 8, 1, _ar_nic_niclm_err_os_msk_detail
};
static const generic_mmr_t _ar_nic_niclm_err_first_flg = {
    "AR_NIC_NICLM_ERR_FIRST_FLG", AR_NIC_NICLM_ERR_FIRST_FLG, 8, 1, _ar_nic_niclm_err_first_flg_detail
};
static const generic_mmr_t _ar_nic_niclm_dbg_errinj_perr = {
    "AR_NIC_NICLM_DBG_ERRINJ_PERR", AR_NIC_NICLM_DBG_ERRINJ_PERR, 8, 1, _ar_nic_niclm_dbg_errinj_perr_detail
};
static const generic_mmr_t _ar_nic_niclm_err_info_perr = {
    "AR_NIC_NICLM_ERR_INFO_PERR", AR_NIC_NICLM_ERR_INFO_PERR, 8, 1, _ar_nic_niclm_err_info_perr_detail
};
static const generic_mmr_t _ar_nic_niclm_err_info_lm0_perr_cnt = {
    "AR_NIC_NICLM_ERR_INFO_LM0_PERR_CNT", AR_NIC_NICLM_ERR_INFO_LM0_PERR_CNT, 8, 1, _ar_nic_niclm_err_info_lm0_perr_cnt_detail
};
static const generic_mmr_t _ar_nic_niclm_err_info_lm1_perr_cnt = {
    "AR_NIC_NICLM_ERR_INFO_LM1_PERR_CNT", AR_NIC_NICLM_ERR_INFO_LM1_PERR_CNT, 8, 1, _ar_nic_niclm_err_info_lm1_perr_cnt_detail
};
static const generic_mmr_t _ar_nic_niclm_err_frc_hss_irq = {
    "AR_NIC_NICLM_ERR_FRC_HSS_IRQ", AR_NIC_NICLM_ERR_FRC_HSS_IRQ, 8, 1, _ar_nic_niclm_err_frc_hss_irq_detail
};

/*
 *  INSTALL AR NICLM MMRS
 */
static const generic_mmr_t* _ar_niclm_mmrs[] _unused = {
    &_ar_nic_niclm_dbg_lm0_ctl,
    &_ar_nic_niclm_dbg_lm0_ptrs,
    &_ar_nic_niclm_dbg_lm0_read_lo,
    &_ar_nic_niclm_dbg_lm0_read_mid,
    &_ar_nic_niclm_dbg_lm0_read_hi,
    &_ar_nic_niclm_dbg_lm0_snap_sel,
    &_ar_nic_niclm_dbg_lm0_snap_dlo,
    &_ar_nic_niclm_dbg_lm0_snap_dmid,
    &_ar_nic_niclm_dbg_lm0_snap_dhi,
    &_ar_nic_niclm_dbg_lm1_ctl,
    &_ar_nic_niclm_dbg_lm1_ptrs,
    &_ar_nic_niclm_dbg_lm1_read_lo,
    &_ar_nic_niclm_dbg_lm1_read_mid,
    &_ar_nic_niclm_dbg_lm1_read_hi,
    &_ar_nic_niclm_dbg_lm1_snap_sel,
    &_ar_nic_niclm_dbg_lm1_snap_dlo,
    &_ar_nic_niclm_dbg_lm1_snap_dmid,
    &_ar_nic_niclm_dbg_lm1_snap_dhi,
    &_ar_nic_niclm_dbg_rem_trig,
    &_ar_nic_niclm_dbg_trig_sts,
    &_ar_nic_niclm_err_flg,
    &_ar_nic_niclm_err_clr,
    &_ar_nic_niclm_err_hss_msk,
    &_ar_nic_niclm_err_os_msk,
    &_ar_nic_niclm_err_first_flg,
    &_ar_nic_niclm_dbg_errinj_perr,
    &_ar_nic_niclm_err_info_perr,
    &_ar_nic_niclm_err_info_lm0_perr_cnt,
    &_ar_nic_niclm_err_info_lm1_perr_cnt,
    &_ar_nic_niclm_err_frc_hss_irq,
    NULL
};

#endif
