/******************************************************************************
 * COPYRIGHT CRAY INC. ar_parb_mmrs_h.h
 * FILE: ar_parb_mmrs_h.h
 * Created by v2h.c on Wed Oct  8 14:39:02 2014
 ******************************************************************************/

#ifndef _AR_PARB_MMRS_H_H_
#define _AR_PARB_MMRS_H_H_

#ifdef __GNUC__
#define _unused __attribute__((unused))
#else
#define _unused
#endif

#ifndef _GENERIC_MMRD_T_
#define _GENERIC_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint64_t _mask;		/* Field bit mask */
} generic_mmrd_t;
#endif

#ifndef _ERRCAT_MMRD_T_
#define _ERRCAT_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint32_t _ec;		/* Field error category */
} errcat_mmrd_t;
#endif

#ifndef _GENERIC_MMR_T_
#define _GENERIC_MMR_T_
typedef struct {
	char* _name;		/* MMR name */
	uint64_t _addr;		/* MMR address */
	int _size;		/* Size in bytes of MMR */
	int _depth;		/* Number of MMR instances */
	const generic_mmrd_t *_info;	/* MMR detail */
} generic_mmr_t;
#endif

static const generic_mmr_t* _ar_parb_mmrs[] _unused;	/* PARB Array */

/*
 *  AR PARB MMR DETAIL DECLARATIONS
 */
static const generic_mmrd_t _ar_nic_parb_cfg_params_detail[] = {
    { "MAX_PKT_SIZE", AR_NIC_PARB_CFG_PARAMS_MAX_PKT_SIZE_BP, AR_NIC_PARB_CFG_PARAMS_MAX_PKT_SIZE_MASK },
    { "SF_BTE_RD", AR_NIC_PARB_CFG_PARAMS_SF_BTE_RD_BP, AR_NIC_PARB_CFG_PARAMS_SF_BTE_RD_MASK },
    { "SF_BTE_WR", AR_NIC_PARB_CFG_PARAMS_SF_BTE_WR_BP, AR_NIC_PARB_CFG_PARAMS_SF_BTE_WR_MASK },
    { "SF_AMO", AR_NIC_PARB_CFG_PARAMS_SF_AMO_BP, AR_NIC_PARB_CFG_PARAMS_SF_AMO_MASK },
    { "SF_WC", AR_NIC_PARB_CFG_PARAMS_SF_WC_BP, AR_NIC_PARB_CFG_PARAMS_SF_WC_MASK },
    { "SF_IOMMU", AR_NIC_PARB_CFG_PARAMS_SF_IOMMU_BP, AR_NIC_PARB_CFG_PARAMS_SF_IOMMU_MASK },
    { "SF_DLA", AR_NIC_PARB_CFG_PARAMS_SF_DLA_BP, AR_NIC_PARB_CFG_PARAMS_SF_DLA_MASK },
    { "BTE_RD_VC", AR_NIC_PARB_CFG_PARAMS_BTE_RD_VC_BP, AR_NIC_PARB_CFG_PARAMS_BTE_RD_VC_MASK },
    { "BTE_WR_VC", AR_NIC_PARB_CFG_PARAMS_BTE_WR_VC_BP, AR_NIC_PARB_CFG_PARAMS_BTE_WR_VC_MASK },
    { "AMO_VC", AR_NIC_PARB_CFG_PARAMS_AMO_VC_BP, AR_NIC_PARB_CFG_PARAMS_AMO_VC_MASK },
    { "WC_VC", AR_NIC_PARB_CFG_PARAMS_WC_VC_BP, AR_NIC_PARB_CFG_PARAMS_WC_VC_MASK },
    { "IOMMU_VC", AR_NIC_PARB_CFG_PARAMS_IOMMU_VC_BP, AR_NIC_PARB_CFG_PARAMS_IOMMU_VC_MASK },
    { "DLA_VC", AR_NIC_PARB_CFG_PARAMS_DLA_VC_BP, AR_NIC_PARB_CFG_PARAMS_DLA_VC_MASK },
    { "USE_SHARED_CRDTS", AR_NIC_PARB_CFG_PARAMS_USE_SHARED_CRDTS_BP, AR_NIC_PARB_CFG_PARAMS_USE_SHARED_CRDTS_MASK },
    { "PI_POOL_CRDTS", AR_NIC_PARB_CFG_PARAMS_PI_POOL_CRDTS_BP, AR_NIC_PARB_CFG_PARAMS_PI_POOL_CRDTS_MASK },
    { "PI_VC2_CRDTS", AR_NIC_PARB_CFG_PARAMS_PI_VC2_CRDTS_BP, AR_NIC_PARB_CFG_PARAMS_PI_VC2_CRDTS_MASK },
    { "PI_VC1_CRDTS", AR_NIC_PARB_CFG_PARAMS_PI_VC1_CRDTS_BP, AR_NIC_PARB_CFG_PARAMS_PI_VC1_CRDTS_MASK },
    { "PI_VC0_CRDTS", AR_NIC_PARB_CFG_PARAMS_PI_VC0_CRDTS_BP, AR_NIC_PARB_CFG_PARAMS_PI_VC0_CRDTS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_parb_mmr_ring_0_hi_parb_detail[] = {
    { "UNUSED_145_56", AR_NIC_PARB_PARB_MMR_RING_0_HI_PARB_UNUSED_145_56_BP, AR_NIC_PARB_PARB_MMR_RING_0_HI_PARB_UNUSED_145_56_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_parb_mmr_ring_0_mid_parb_detail[] = {
    { "UNUSED_127_106", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_UNUSED_127_106_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_UNUSED_127_106_MASK },
    { "CNTR_PI_STALLED", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_PI_STALLED_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_PI_STALLED_MASK },
    { "CNTR_PI_FLITS", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_PI_FLITS_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_PI_FLITS_MASK },
    { "CNTR_PI_PKTS", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_PI_PKTS_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_PI_PKTS_MASK },
    { "CNTR_MAINT_BLOCKED", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_MAINT_BLOCKED_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_MAINT_BLOCKED_MASK },
    { "CNTR_MAINT_FLITS", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_MAINT_FLITS_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_MAINT_FLITS_MASK },
    { "CNTR_MAINT_PKTS", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_MAINT_PKTS_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_MAINT_PKTS_MASK },
    { "CNTR_DLA_BLOCKED", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_DLA_BLOCKED_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_DLA_BLOCKED_MASK },
    { "CNTR_DLA_FLITS", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_DLA_FLITS_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_DLA_FLITS_MASK },
    { "CNTR_DLA_PKTS", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_DLA_PKTS_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_DLA_PKTS_MASK },
    { "CNTR_IOMMU_BLOCKED", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_IOMMU_BLOCKED_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_IOMMU_BLOCKED_MASK },
    { "CNTR_IOMMU_FLITS", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_IOMMU_FLITS_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_IOMMU_FLITS_MASK },
    { "CNTR_IOMMU_PKTS", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_IOMMU_PKTS_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_IOMMU_PKTS_MASK },
    { "CNTR_WC_BLOCKED", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_WC_BLOCKED_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_WC_BLOCKED_MASK },
    { "CNTR_WC_FLITS", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_WC_FLITS_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_WC_FLITS_MASK },
    { "CNTR_WC_PKTS", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_WC_PKTS_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_WC_PKTS_MASK },
    { "CNTR_AMO_BLOCKED", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_AMO_BLOCKED_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_AMO_BLOCKED_MASK },
    { "CNTR_AMO_FLITS", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_AMO_FLITS_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_AMO_FLITS_MASK },
    { "CNTR_AMO_PKTS", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_AMO_PKTS_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_AMO_PKTS_MASK },
    { "CNTR_BTE_WR_BLOCKED", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_BTE_WR_BLOCKED_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_BTE_WR_BLOCKED_MASK },
    { "CNTR_BTE_WR_FLITS", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_BTE_WR_FLITS_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_BTE_WR_FLITS_MASK },
    { "CNTR_BTE_WR_PKTS", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_BTE_WR_PKTS_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_BTE_WR_PKTS_MASK },
    { "CNTR_BTE_RD_BLOCKED", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_BTE_RD_BLOCKED_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_BTE_RD_BLOCKED_MASK },
    { "CNTR_BTE_RD_FLITS", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_BTE_RD_FLITS_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_BTE_RD_FLITS_MASK },
    { "CNTR_BTE_RD_PKTS", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_BTE_RD_PKTS_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_CNTR_BTE_RD_PKTS_MASK },
    { "UNUSED_81_64", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_UNUSED_81_64_BP, AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB_UNUSED_81_64_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_parb_mmr_ring_0_lo_parb_detail[] = {
    { "UNUSED_145_56", AR_NIC_PARB_PARB_MMR_RING_0_LO_PARB_UNUSED_145_56_BP, AR_NIC_PARB_PARB_MMR_RING_0_LO_PARB_UNUSED_145_56_MASK },
    { "ARB_REQ", AR_NIC_PARB_PARB_MMR_RING_0_LO_PARB_ARB_REQ_BP, AR_NIC_PARB_PARB_MMR_RING_0_LO_PARB_ARB_REQ_MASK },
    { "ARB_GNT", AR_NIC_PARB_PARB_MMR_RING_0_LO_PARB_ARB_GNT_BP, AR_NIC_PARB_PARB_MMR_RING_0_LO_PARB_ARB_GNT_MASK },
    { "ARB_ACK", AR_NIC_PARB_PARB_MMR_RING_0_LO_PARB_ARB_ACK_BP, AR_NIC_PARB_PARB_MMR_RING_0_LO_PARB_ARB_ACK_MASK },
    { "R_Q_PARB_PI_OS_IRQ", AR_NIC_PARB_PARB_MMR_RING_0_LO_PARB_R_Q_PARB_PI_OS_IRQ_BP, AR_NIC_PARB_PARB_MMR_RING_0_LO_PARB_R_Q_PARB_PI_OS_IRQ_MASK },
    { "R_Q_PARB_LB_HSS_IRQ", AR_NIC_PARB_PARB_MMR_RING_0_LO_PARB_R_Q_PARB_LB_HSS_IRQ_BP, AR_NIC_PARB_PARB_MMR_RING_0_LO_PARB_R_Q_PARB_LB_HSS_IRQ_MASK },
    { "R_Q_PARB_RSPMON_RING_WRACK", AR_NIC_PARB_PARB_MMR_RING_0_LO_PARB_R_Q_PARB_RSPMON_RING_WRACK_BP, AR_NIC_PARB_PARB_MMR_RING_0_LO_PARB_R_Q_PARB_RSPMON_RING_WRACK_MASK },
    { "R_Q_PARB_RSPMON_RING_15_0", AR_NIC_PARB_PARB_MMR_RING_0_LO_PARB_R_Q_PARB_RSPMON_RING_15_0_BP, AR_NIC_PARB_PARB_MMR_RING_0_LO_PARB_R_Q_PARB_RSPMON_RING_15_0_MASK },
    { "I_RSPMON_PARB_RING_15_0", AR_NIC_PARB_PARB_MMR_RING_0_LO_PARB_I_RSPMON_PARB_RING_15_0_BP, AR_NIC_PARB_PARB_MMR_RING_0_LO_PARB_I_RSPMON_PARB_RING_15_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_err_flg_1_hi_parb_detail[] = {
    { "UNUSED_145_130", AR_NIC_PARB_ERR_FLG_1_HI_PARB_UNUSED_145_130_BP, AR_NIC_PARB_ERR_FLG_1_HI_PARB_UNUSED_145_130_MASK },
    { "DBG_AMO_WC_RDY", AR_NIC_PARB_ERR_FLG_1_HI_PARB_DBG_AMO_WC_RDY_BP, AR_NIC_PARB_ERR_FLG_1_HI_PARB_DBG_AMO_WC_RDY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_err_flg_1_mid_parb_detail[] = {
    { "UNUSED_127_88", AR_NIC_PARB_ERR_FLG_1_MID_PARB_UNUSED_127_88_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_UNUSED_127_88_MASK },
    { "MAINT_BAD_PAYLD_CNT", AR_NIC_PARB_ERR_FLG_1_MID_PARB_MAINT_BAD_PAYLD_CNT_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_MAINT_BAD_PAYLD_CNT_MASK },
    { "MAINT_RSP_DROP", AR_NIC_PARB_ERR_FLG_1_MID_PARB_MAINT_RSP_DROP_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_MAINT_RSP_DROP_MASK },
    { "MAINT_ILLEGAL_RD", AR_NIC_PARB_ERR_FLG_1_MID_PARB_MAINT_ILLEGAL_RD_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_MAINT_ILLEGAL_RD_MASK },
    { "MAINT_ILLEGAL_WR", AR_NIC_PARB_ERR_FLG_1_MID_PARB_MAINT_ILLEGAL_WR_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_MAINT_ILLEGAL_WR_MASK },
    { "MAINT_LFIFO_MBE", AR_NIC_PARB_ERR_FLG_1_MID_PARB_MAINT_LFIFO_MBE_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_MAINT_LFIFO_MBE_MASK },
    { "MAINT_LFIFO_SBE", AR_NIC_PARB_ERR_FLG_1_MID_PARB_MAINT_LFIFO_SBE_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_MAINT_LFIFO_SBE_MASK },
    { "MAINT_RSP_MBE", AR_NIC_PARB_ERR_FLG_1_MID_PARB_MAINT_RSP_MBE_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_MAINT_RSP_MBE_MASK },
    { "MAINT_RSP_SBE", AR_NIC_PARB_ERR_FLG_1_MID_PARB_MAINT_RSP_SBE_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_MAINT_RSP_SBE_MASK },
    { "MAINT_RSP_PE", AR_NIC_PARB_ERR_FLG_1_MID_PARB_MAINT_RSP_PE_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_MAINT_RSP_PE_MASK },
    { "MAINT_SFIFO_OVFLW", AR_NIC_PARB_ERR_FLG_1_MID_PARB_MAINT_SFIFO_OVFLW_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_MAINT_SFIFO_OVFLW_MASK },
    { "MAINT_LFIFO_OVFLW", AR_NIC_PARB_ERR_FLG_1_MID_PARB_MAINT_LFIFO_OVFLW_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_MAINT_LFIFO_OVFLW_MASK },
    { "BTE_RD_UFLW", AR_NIC_PARB_ERR_FLG_1_MID_PARB_BTE_RD_UFLW_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_BTE_RD_UFLW_MASK },
    { "BTE_WR_UFLW", AR_NIC_PARB_ERR_FLG_1_MID_PARB_BTE_WR_UFLW_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_BTE_WR_UFLW_MASK },
    { "AMO_UFLW", AR_NIC_PARB_ERR_FLG_1_MID_PARB_AMO_UFLW_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_AMO_UFLW_MASK },
    { "WC_UFLW", AR_NIC_PARB_ERR_FLG_1_MID_PARB_WC_UFLW_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_WC_UFLW_MASK },
    { "IOMMU_UFLW", AR_NIC_PARB_ERR_FLG_1_MID_PARB_IOMMU_UFLW_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_IOMMU_UFLW_MASK },
    { "DLA_UFLW", AR_NIC_PARB_ERR_FLG_1_MID_PARB_DLA_UFLW_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_DLA_UFLW_MASK },
    { "BTE_RD_OFLW", AR_NIC_PARB_ERR_FLG_1_MID_PARB_BTE_RD_OFLW_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_BTE_RD_OFLW_MASK },
    { "BTE_WR_OFLW", AR_NIC_PARB_ERR_FLG_1_MID_PARB_BTE_WR_OFLW_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_BTE_WR_OFLW_MASK },
    { "AMO_OFLW", AR_NIC_PARB_ERR_FLG_1_MID_PARB_AMO_OFLW_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_AMO_OFLW_MASK },
    { "WC_OFLW", AR_NIC_PARB_ERR_FLG_1_MID_PARB_WC_OFLW_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_WC_OFLW_MASK },
    { "IOMMU_OFLW", AR_NIC_PARB_ERR_FLG_1_MID_PARB_IOMMU_OFLW_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_IOMMU_OFLW_MASK },
    { "DLA_OFLW", AR_NIC_PARB_ERR_FLG_1_MID_PARB_DLA_OFLW_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_DLA_OFLW_MASK },
    { "DIAG_ONLY", AR_NIC_PARB_ERR_FLG_1_MID_PARB_DIAG_ONLY_BP, AR_NIC_PARB_ERR_FLG_1_MID_PARB_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_err_flg_1_lo_parb_detail[] = {
    { "UNUSED_63_24", AR_NIC_PARB_ERR_FLG_1_LO_PARB_UNUSED_63_24_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_UNUSED_63_24_MASK },
    { "I_MAINT_BAD_PAYLD_CNT", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_MAINT_BAD_PAYLD_CNT_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_MAINT_BAD_PAYLD_CNT_MASK },
    { "I_MAINT_RSP_DROP", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_MAINT_RSP_DROP_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_MAINT_RSP_DROP_MASK },
    { "I_MAINT_ILLEGAL_RD", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_MAINT_ILLEGAL_RD_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_MAINT_ILLEGAL_RD_MASK },
    { "I_MAINT_ILLEGAL_WR", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_MAINT_ILLEGAL_WR_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_MAINT_ILLEGAL_WR_MASK },
    { "I_MAINT_LFIFO_MBE", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_MAINT_LFIFO_MBE_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_MAINT_LFIFO_MBE_MASK },
    { "I_MAINT_LFIFO_SBE", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_MAINT_LFIFO_SBE_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_MAINT_LFIFO_SBE_MASK },
    { "I_MAINT_RSP_MBE", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_MAINT_RSP_MBE_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_MAINT_RSP_MBE_MASK },
    { "I_MAINT_RSP_SBE", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_MAINT_RSP_SBE_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_MAINT_RSP_SBE_MASK },
    { "I_MAINT_RSP_PE", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_MAINT_RSP_PE_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_MAINT_RSP_PE_MASK },
    { "I_MAINT_SFIFO_OVFLW", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_MAINT_SFIFO_OVFLW_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_MAINT_SFIFO_OVFLW_MASK },
    { "I_MAINT_LFIFO_OVFLW", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_MAINT_LFIFO_OVFLW_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_MAINT_LFIFO_OVFLW_MASK },
    { "I_BTE_RD_UFLW", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_BTE_RD_UFLW_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_BTE_RD_UFLW_MASK },
    { "I_BTE_WR_UFLW", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_BTE_WR_UFLW_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_BTE_WR_UFLW_MASK },
    { "I_AMO_UFLW", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_AMO_UFLW_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_AMO_UFLW_MASK },
    { "I_WC_UFLW", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_WC_UFLW_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_WC_UFLW_MASK },
    { "I_IOMMU_UFLW", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_IOMMU_UFLW_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_IOMMU_UFLW_MASK },
    { "I_DLA_UFLW", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_DLA_UFLW_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_DLA_UFLW_MASK },
    { "I_BTE_RD_OFLW", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_BTE_RD_OFLW_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_BTE_RD_OFLW_MASK },
    { "I_BTE_WR_OFLW", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_BTE_WR_OFLW_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_BTE_WR_OFLW_MASK },
    { "I_AMO_OFLW", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_AMO_OFLW_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_AMO_OFLW_MASK },
    { "I_WC_OFLW", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_WC_OFLW_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_WC_OFLW_MASK },
    { "I_IOMMU_OFLW", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_IOMMU_OFLW_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_IOMMU_OFLW_MASK },
    { "I_DLA_OFLW", AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_DLA_OFLW_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_I_DLA_OFLW_MASK },
    { "UNUSED_0", AR_NIC_PARB_ERR_FLG_1_LO_PARB_UNUSED_0_BP, AR_NIC_PARB_ERR_FLG_1_LO_PARB_UNUSED_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_nic_pi_req_flit_2_hi_parb_detail[] = {
    { "R_Q_NIC_PI_REQ_SB", AR_NIC_PARB_NIC_PI_REQ_FLIT_2_HI_PARB_R_Q_NIC_PI_REQ_SB_BP, AR_NIC_PARB_NIC_PI_REQ_FLIT_2_HI_PARB_R_Q_NIC_PI_REQ_SB_MASK },
    { "R_Q_NIC_PI_REQ_FLIT", AR_NIC_PARB_NIC_PI_REQ_FLIT_2_HI_PARB_R_Q_NIC_PI_REQ_FLIT_BP, AR_NIC_PARB_NIC_PI_REQ_FLIT_2_HI_PARB_R_Q_NIC_PI_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_nic_pi_req_flit_2_mid_parb_detail[] = {
    { "R_Q_NIC_PI_REQ_FLIT", AR_NIC_PARB_NIC_PI_REQ_FLIT_2_MID_PARB_R_Q_NIC_PI_REQ_FLIT_BP, AR_NIC_PARB_NIC_PI_REQ_FLIT_2_MID_PARB_R_Q_NIC_PI_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_nic_pi_req_flit_2_lo_parb_detail[] = {
    { "R_Q_NIC_PI_REQ_FLIT", AR_NIC_PARB_NIC_PI_REQ_FLIT_2_LO_PARB_R_Q_NIC_PI_REQ_FLIT_BP, AR_NIC_PARB_NIC_PI_REQ_FLIT_2_LO_PARB_R_Q_NIC_PI_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_parb_power_down_ff_hi_parb_detail[] = {
    { "POWER_DOWN", AR_NIC_PARB_PARB_POWER_DOWN_FF_HI_PARB_POWER_DOWN_BP, AR_NIC_PARB_PARB_POWER_DOWN_FF_HI_PARB_POWER_DOWN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_parb_power_down_ff_mid_parb_detail[] = {
    { "POWER_DOWN", AR_NIC_PARB_PARB_POWER_DOWN_FF_MID_PARB_POWER_DOWN_BP, AR_NIC_PARB_PARB_POWER_DOWN_FF_MID_PARB_POWER_DOWN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_parb_power_down_ff_lo_parb_detail[] = {
    { "POWER_DOWN", AR_NIC_PARB_PARB_POWER_DOWN_FF_LO_PARB_POWER_DOWN_BP, AR_NIC_PARB_PARB_POWER_DOWN_FF_LO_PARB_POWER_DOWN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_err_flg_detail[] = {
    { "MAINT_BAD_PAYLD_CNT", AR_NIC_PARB_ERR_FLG_MAINT_BAD_PAYLD_CNT_BP, AR_NIC_PARB_ERR_FLG_MAINT_BAD_PAYLD_CNT_MASK },
    { "MAINT_RSP_DROP", AR_NIC_PARB_ERR_FLG_MAINT_RSP_DROP_BP, AR_NIC_PARB_ERR_FLG_MAINT_RSP_DROP_MASK },
    { "MAINT_ILLEGAL_RD", AR_NIC_PARB_ERR_FLG_MAINT_ILLEGAL_RD_BP, AR_NIC_PARB_ERR_FLG_MAINT_ILLEGAL_RD_MASK },
    { "MAINT_ILLEGAL_WR", AR_NIC_PARB_ERR_FLG_MAINT_ILLEGAL_WR_BP, AR_NIC_PARB_ERR_FLG_MAINT_ILLEGAL_WR_MASK },
    { "MAINT_LFIFO_MBE", AR_NIC_PARB_ERR_FLG_MAINT_LFIFO_MBE_BP, AR_NIC_PARB_ERR_FLG_MAINT_LFIFO_MBE_MASK },
    { "MAINT_LFIFO_SBE", AR_NIC_PARB_ERR_FLG_MAINT_LFIFO_SBE_BP, AR_NIC_PARB_ERR_FLG_MAINT_LFIFO_SBE_MASK },
    { "MAINT_RSP_MBE", AR_NIC_PARB_ERR_FLG_MAINT_RSP_MBE_BP, AR_NIC_PARB_ERR_FLG_MAINT_RSP_MBE_MASK },
    { "MAINT_RSP_SBE", AR_NIC_PARB_ERR_FLG_MAINT_RSP_SBE_BP, AR_NIC_PARB_ERR_FLG_MAINT_RSP_SBE_MASK },
    { "MAINT_RSP_PE", AR_NIC_PARB_ERR_FLG_MAINT_RSP_PE_BP, AR_NIC_PARB_ERR_FLG_MAINT_RSP_PE_MASK },
    { "MAINT_SFIFO_OVFLW", AR_NIC_PARB_ERR_FLG_MAINT_SFIFO_OVFLW_BP, AR_NIC_PARB_ERR_FLG_MAINT_SFIFO_OVFLW_MASK },
    { "MAINT_LFIFO_OVFLW", AR_NIC_PARB_ERR_FLG_MAINT_LFIFO_OVFLW_BP, AR_NIC_PARB_ERR_FLG_MAINT_LFIFO_OVFLW_MASK },
    { "BTE_RD_UFLW", AR_NIC_PARB_ERR_FLG_BTE_RD_UFLW_BP, AR_NIC_PARB_ERR_FLG_BTE_RD_UFLW_MASK },
    { "BTE_WR_UFLW", AR_NIC_PARB_ERR_FLG_BTE_WR_UFLW_BP, AR_NIC_PARB_ERR_FLG_BTE_WR_UFLW_MASK },
    { "AMO_UFLW", AR_NIC_PARB_ERR_FLG_AMO_UFLW_BP, AR_NIC_PARB_ERR_FLG_AMO_UFLW_MASK },
    { "WC_UFLW", AR_NIC_PARB_ERR_FLG_WC_UFLW_BP, AR_NIC_PARB_ERR_FLG_WC_UFLW_MASK },
    { "IOMMU_UFLW", AR_NIC_PARB_ERR_FLG_IOMMU_UFLW_BP, AR_NIC_PARB_ERR_FLG_IOMMU_UFLW_MASK },
    { "DLA_UFLW", AR_NIC_PARB_ERR_FLG_DLA_UFLW_BP, AR_NIC_PARB_ERR_FLG_DLA_UFLW_MASK },
    { "BTE_RD_OFLW", AR_NIC_PARB_ERR_FLG_BTE_RD_OFLW_BP, AR_NIC_PARB_ERR_FLG_BTE_RD_OFLW_MASK },
    { "BTE_WR_OFLW", AR_NIC_PARB_ERR_FLG_BTE_WR_OFLW_BP, AR_NIC_PARB_ERR_FLG_BTE_WR_OFLW_MASK },
    { "AMO_OFLW", AR_NIC_PARB_ERR_FLG_AMO_OFLW_BP, AR_NIC_PARB_ERR_FLG_AMO_OFLW_MASK },
    { "WC_OFLW", AR_NIC_PARB_ERR_FLG_WC_OFLW_BP, AR_NIC_PARB_ERR_FLG_WC_OFLW_MASK },
    { "IOMMU_OFLW", AR_NIC_PARB_ERR_FLG_IOMMU_OFLW_BP, AR_NIC_PARB_ERR_FLG_IOMMU_OFLW_MASK },
    { "DLA_OFLW", AR_NIC_PARB_ERR_FLG_DLA_OFLW_BP, AR_NIC_PARB_ERR_FLG_DLA_OFLW_MASK },
    { "DIAG_ONLY", AR_NIC_PARB_ERR_FLG_DIAG_ONLY_BP, AR_NIC_PARB_ERR_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
#ifdef EXCEPTIONS_DEFS
static const errcat_mmrd_t _ar_nic_parb_err_flg_errcat[] = {
    { "MAINT_BAD_PAYLD_CNT", AR_NIC_PARB_ERR_FLG_MAINT_BAD_PAYLD_CNT_BP, AR_NIC_PARB_ERR_FLG_MAINT_BAD_PAYLD_CNT_EC },
    { "MAINT_RSP_DROP", AR_NIC_PARB_ERR_FLG_MAINT_RSP_DROP_BP, AR_NIC_PARB_ERR_FLG_MAINT_RSP_DROP_EC },
    { "MAINT_ILLEGAL_RD", AR_NIC_PARB_ERR_FLG_MAINT_ILLEGAL_RD_BP, AR_NIC_PARB_ERR_FLG_MAINT_ILLEGAL_RD_EC },
    { "MAINT_ILLEGAL_WR", AR_NIC_PARB_ERR_FLG_MAINT_ILLEGAL_WR_BP, AR_NIC_PARB_ERR_FLG_MAINT_ILLEGAL_WR_EC },
    { "MAINT_LFIFO_MBE", AR_NIC_PARB_ERR_FLG_MAINT_LFIFO_MBE_BP, AR_NIC_PARB_ERR_FLG_MAINT_LFIFO_MBE_EC },
    { "MAINT_LFIFO_SBE", AR_NIC_PARB_ERR_FLG_MAINT_LFIFO_SBE_BP, AR_NIC_PARB_ERR_FLG_MAINT_LFIFO_SBE_EC },
    { "MAINT_RSP_MBE", AR_NIC_PARB_ERR_FLG_MAINT_RSP_MBE_BP, AR_NIC_PARB_ERR_FLG_MAINT_RSP_MBE_EC },
    { "MAINT_RSP_SBE", AR_NIC_PARB_ERR_FLG_MAINT_RSP_SBE_BP, AR_NIC_PARB_ERR_FLG_MAINT_RSP_SBE_EC },
    { "MAINT_RSP_PE", AR_NIC_PARB_ERR_FLG_MAINT_RSP_PE_BP, AR_NIC_PARB_ERR_FLG_MAINT_RSP_PE_EC },
    { "MAINT_SFIFO_OVFLW", AR_NIC_PARB_ERR_FLG_MAINT_SFIFO_OVFLW_BP, AR_NIC_PARB_ERR_FLG_MAINT_SFIFO_OVFLW_EC },
    { "MAINT_LFIFO_OVFLW", AR_NIC_PARB_ERR_FLG_MAINT_LFIFO_OVFLW_BP, AR_NIC_PARB_ERR_FLG_MAINT_LFIFO_OVFLW_EC },
    { "BTE_RD_UFLW", AR_NIC_PARB_ERR_FLG_BTE_RD_UFLW_BP, AR_NIC_PARB_ERR_FLG_BTE_RD_UFLW_EC },
    { "BTE_WR_UFLW", AR_NIC_PARB_ERR_FLG_BTE_WR_UFLW_BP, AR_NIC_PARB_ERR_FLG_BTE_WR_UFLW_EC },
    { "AMO_UFLW", AR_NIC_PARB_ERR_FLG_AMO_UFLW_BP, AR_NIC_PARB_ERR_FLG_AMO_UFLW_EC },
    { "WC_UFLW", AR_NIC_PARB_ERR_FLG_WC_UFLW_BP, AR_NIC_PARB_ERR_FLG_WC_UFLW_EC },
    { "IOMMU_UFLW", AR_NIC_PARB_ERR_FLG_IOMMU_UFLW_BP, AR_NIC_PARB_ERR_FLG_IOMMU_UFLW_EC },
    { "DLA_UFLW", AR_NIC_PARB_ERR_FLG_DLA_UFLW_BP, AR_NIC_PARB_ERR_FLG_DLA_UFLW_EC },
    { "BTE_RD_OFLW", AR_NIC_PARB_ERR_FLG_BTE_RD_OFLW_BP, AR_NIC_PARB_ERR_FLG_BTE_RD_OFLW_EC },
    { "BTE_WR_OFLW", AR_NIC_PARB_ERR_FLG_BTE_WR_OFLW_BP, AR_NIC_PARB_ERR_FLG_BTE_WR_OFLW_EC },
    { "AMO_OFLW", AR_NIC_PARB_ERR_FLG_AMO_OFLW_BP, AR_NIC_PARB_ERR_FLG_AMO_OFLW_EC },
    { "WC_OFLW", AR_NIC_PARB_ERR_FLG_WC_OFLW_BP, AR_NIC_PARB_ERR_FLG_WC_OFLW_EC },
    { "IOMMU_OFLW", AR_NIC_PARB_ERR_FLG_IOMMU_OFLW_BP, AR_NIC_PARB_ERR_FLG_IOMMU_OFLW_EC },
    { "DLA_OFLW", AR_NIC_PARB_ERR_FLG_DLA_OFLW_BP, AR_NIC_PARB_ERR_FLG_DLA_OFLW_EC },
    { "DIAG_ONLY", AR_NIC_PARB_ERR_FLG_DIAG_ONLY_BP, AR_NIC_PARB_ERR_FLG_DIAG_ONLY_EC },
    { NULL, 0, 0 }
};
#endif
static const generic_mmrd_t _ar_nic_parb_err_clr_detail[] = {
    { "MAINT_BAD_PAYLD_CNT", AR_NIC_PARB_ERR_CLR_MAINT_BAD_PAYLD_CNT_BP, AR_NIC_PARB_ERR_CLR_MAINT_BAD_PAYLD_CNT_MASK },
    { "MAINT_RSP_DROP", AR_NIC_PARB_ERR_CLR_MAINT_RSP_DROP_BP, AR_NIC_PARB_ERR_CLR_MAINT_RSP_DROP_MASK },
    { "MAINT_ILLEGAL_RD", AR_NIC_PARB_ERR_CLR_MAINT_ILLEGAL_RD_BP, AR_NIC_PARB_ERR_CLR_MAINT_ILLEGAL_RD_MASK },
    { "MAINT_ILLEGAL_WR", AR_NIC_PARB_ERR_CLR_MAINT_ILLEGAL_WR_BP, AR_NIC_PARB_ERR_CLR_MAINT_ILLEGAL_WR_MASK },
    { "MAINT_LFIFO_MBE", AR_NIC_PARB_ERR_CLR_MAINT_LFIFO_MBE_BP, AR_NIC_PARB_ERR_CLR_MAINT_LFIFO_MBE_MASK },
    { "MAINT_LFIFO_SBE", AR_NIC_PARB_ERR_CLR_MAINT_LFIFO_SBE_BP, AR_NIC_PARB_ERR_CLR_MAINT_LFIFO_SBE_MASK },
    { "MAINT_RSP_MBE", AR_NIC_PARB_ERR_CLR_MAINT_RSP_MBE_BP, AR_NIC_PARB_ERR_CLR_MAINT_RSP_MBE_MASK },
    { "MAINT_RSP_SBE", AR_NIC_PARB_ERR_CLR_MAINT_RSP_SBE_BP, AR_NIC_PARB_ERR_CLR_MAINT_RSP_SBE_MASK },
    { "MAINT_RSP_PE", AR_NIC_PARB_ERR_CLR_MAINT_RSP_PE_BP, AR_NIC_PARB_ERR_CLR_MAINT_RSP_PE_MASK },
    { "MAINT_SFIFO_OVFLW", AR_NIC_PARB_ERR_CLR_MAINT_SFIFO_OVFLW_BP, AR_NIC_PARB_ERR_CLR_MAINT_SFIFO_OVFLW_MASK },
    { "MAINT_LFIFO_OVFLW", AR_NIC_PARB_ERR_CLR_MAINT_LFIFO_OVFLW_BP, AR_NIC_PARB_ERR_CLR_MAINT_LFIFO_OVFLW_MASK },
    { "BTE_RD_UFLW", AR_NIC_PARB_ERR_CLR_BTE_RD_UFLW_BP, AR_NIC_PARB_ERR_CLR_BTE_RD_UFLW_MASK },
    { "BTE_WR_UFLW", AR_NIC_PARB_ERR_CLR_BTE_WR_UFLW_BP, AR_NIC_PARB_ERR_CLR_BTE_WR_UFLW_MASK },
    { "AMO_UFLW", AR_NIC_PARB_ERR_CLR_AMO_UFLW_BP, AR_NIC_PARB_ERR_CLR_AMO_UFLW_MASK },
    { "WC_UFLW", AR_NIC_PARB_ERR_CLR_WC_UFLW_BP, AR_NIC_PARB_ERR_CLR_WC_UFLW_MASK },
    { "IOMMU_UFLW", AR_NIC_PARB_ERR_CLR_IOMMU_UFLW_BP, AR_NIC_PARB_ERR_CLR_IOMMU_UFLW_MASK },
    { "DLA_UFLW", AR_NIC_PARB_ERR_CLR_DLA_UFLW_BP, AR_NIC_PARB_ERR_CLR_DLA_UFLW_MASK },
    { "BTE_RD_OFLW", AR_NIC_PARB_ERR_CLR_BTE_RD_OFLW_BP, AR_NIC_PARB_ERR_CLR_BTE_RD_OFLW_MASK },
    { "BTE_WR_OFLW", AR_NIC_PARB_ERR_CLR_BTE_WR_OFLW_BP, AR_NIC_PARB_ERR_CLR_BTE_WR_OFLW_MASK },
    { "AMO_OFLW", AR_NIC_PARB_ERR_CLR_AMO_OFLW_BP, AR_NIC_PARB_ERR_CLR_AMO_OFLW_MASK },
    { "WC_OFLW", AR_NIC_PARB_ERR_CLR_WC_OFLW_BP, AR_NIC_PARB_ERR_CLR_WC_OFLW_MASK },
    { "IOMMU_OFLW", AR_NIC_PARB_ERR_CLR_IOMMU_OFLW_BP, AR_NIC_PARB_ERR_CLR_IOMMU_OFLW_MASK },
    { "DLA_OFLW", AR_NIC_PARB_ERR_CLR_DLA_OFLW_BP, AR_NIC_PARB_ERR_CLR_DLA_OFLW_MASK },
    { "DIAG_ONLY", AR_NIC_PARB_ERR_CLR_DIAG_ONLY_BP, AR_NIC_PARB_ERR_CLR_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_err_hss_msk_detail[] = {
    { "MAINT_BAD_PAYLD_CNT", AR_NIC_PARB_ERR_HSS_MSK_MAINT_BAD_PAYLD_CNT_BP, AR_NIC_PARB_ERR_HSS_MSK_MAINT_BAD_PAYLD_CNT_MASK },
    { "MAINT_RSP_DROP", AR_NIC_PARB_ERR_HSS_MSK_MAINT_RSP_DROP_BP, AR_NIC_PARB_ERR_HSS_MSK_MAINT_RSP_DROP_MASK },
    { "MAINT_ILLEGAL_RD", AR_NIC_PARB_ERR_HSS_MSK_MAINT_ILLEGAL_RD_BP, AR_NIC_PARB_ERR_HSS_MSK_MAINT_ILLEGAL_RD_MASK },
    { "MAINT_ILLEGAL_WR", AR_NIC_PARB_ERR_HSS_MSK_MAINT_ILLEGAL_WR_BP, AR_NIC_PARB_ERR_HSS_MSK_MAINT_ILLEGAL_WR_MASK },
    { "MAINT_LFIFO_MBE", AR_NIC_PARB_ERR_HSS_MSK_MAINT_LFIFO_MBE_BP, AR_NIC_PARB_ERR_HSS_MSK_MAINT_LFIFO_MBE_MASK },
    { "MAINT_LFIFO_SBE", AR_NIC_PARB_ERR_HSS_MSK_MAINT_LFIFO_SBE_BP, AR_NIC_PARB_ERR_HSS_MSK_MAINT_LFIFO_SBE_MASK },
    { "MAINT_RSP_MBE", AR_NIC_PARB_ERR_HSS_MSK_MAINT_RSP_MBE_BP, AR_NIC_PARB_ERR_HSS_MSK_MAINT_RSP_MBE_MASK },
    { "MAINT_RSP_SBE", AR_NIC_PARB_ERR_HSS_MSK_MAINT_RSP_SBE_BP, AR_NIC_PARB_ERR_HSS_MSK_MAINT_RSP_SBE_MASK },
    { "MAINT_RSP_PE", AR_NIC_PARB_ERR_HSS_MSK_MAINT_RSP_PE_BP, AR_NIC_PARB_ERR_HSS_MSK_MAINT_RSP_PE_MASK },
    { "MAINT_SFIFO_OVFLW", AR_NIC_PARB_ERR_HSS_MSK_MAINT_SFIFO_OVFLW_BP, AR_NIC_PARB_ERR_HSS_MSK_MAINT_SFIFO_OVFLW_MASK },
    { "MAINT_LFIFO_OVFLW", AR_NIC_PARB_ERR_HSS_MSK_MAINT_LFIFO_OVFLW_BP, AR_NIC_PARB_ERR_HSS_MSK_MAINT_LFIFO_OVFLW_MASK },
    { "BTE_RD_UFLW", AR_NIC_PARB_ERR_HSS_MSK_BTE_RD_UFLW_BP, AR_NIC_PARB_ERR_HSS_MSK_BTE_RD_UFLW_MASK },
    { "BTE_WR_UFLW", AR_NIC_PARB_ERR_HSS_MSK_BTE_WR_UFLW_BP, AR_NIC_PARB_ERR_HSS_MSK_BTE_WR_UFLW_MASK },
    { "AMO_UFLW", AR_NIC_PARB_ERR_HSS_MSK_AMO_UFLW_BP, AR_NIC_PARB_ERR_HSS_MSK_AMO_UFLW_MASK },
    { "WC_UFLW", AR_NIC_PARB_ERR_HSS_MSK_WC_UFLW_BP, AR_NIC_PARB_ERR_HSS_MSK_WC_UFLW_MASK },
    { "IOMMU_UFLW", AR_NIC_PARB_ERR_HSS_MSK_IOMMU_UFLW_BP, AR_NIC_PARB_ERR_HSS_MSK_IOMMU_UFLW_MASK },
    { "DLA_UFLW", AR_NIC_PARB_ERR_HSS_MSK_DLA_UFLW_BP, AR_NIC_PARB_ERR_HSS_MSK_DLA_UFLW_MASK },
    { "BTE_RD_OFLW", AR_NIC_PARB_ERR_HSS_MSK_BTE_RD_OFLW_BP, AR_NIC_PARB_ERR_HSS_MSK_BTE_RD_OFLW_MASK },
    { "BTE_WR_OFLW", AR_NIC_PARB_ERR_HSS_MSK_BTE_WR_OFLW_BP, AR_NIC_PARB_ERR_HSS_MSK_BTE_WR_OFLW_MASK },
    { "AMO_OFLW", AR_NIC_PARB_ERR_HSS_MSK_AMO_OFLW_BP, AR_NIC_PARB_ERR_HSS_MSK_AMO_OFLW_MASK },
    { "WC_OFLW", AR_NIC_PARB_ERR_HSS_MSK_WC_OFLW_BP, AR_NIC_PARB_ERR_HSS_MSK_WC_OFLW_MASK },
    { "IOMMU_OFLW", AR_NIC_PARB_ERR_HSS_MSK_IOMMU_OFLW_BP, AR_NIC_PARB_ERR_HSS_MSK_IOMMU_OFLW_MASK },
    { "DLA_OFLW", AR_NIC_PARB_ERR_HSS_MSK_DLA_OFLW_BP, AR_NIC_PARB_ERR_HSS_MSK_DLA_OFLW_MASK },
    { "DIAG_ONLY", AR_NIC_PARB_ERR_HSS_MSK_DIAG_ONLY_BP, AR_NIC_PARB_ERR_HSS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_err_os_msk_detail[] = {
    { "MAINT_BAD_PAYLD_CNT", AR_NIC_PARB_ERR_OS_MSK_MAINT_BAD_PAYLD_CNT_BP, AR_NIC_PARB_ERR_OS_MSK_MAINT_BAD_PAYLD_CNT_MASK },
    { "MAINT_RSP_DROP", AR_NIC_PARB_ERR_OS_MSK_MAINT_RSP_DROP_BP, AR_NIC_PARB_ERR_OS_MSK_MAINT_RSP_DROP_MASK },
    { "MAINT_ILLEGAL_RD", AR_NIC_PARB_ERR_OS_MSK_MAINT_ILLEGAL_RD_BP, AR_NIC_PARB_ERR_OS_MSK_MAINT_ILLEGAL_RD_MASK },
    { "MAINT_ILLEGAL_WR", AR_NIC_PARB_ERR_OS_MSK_MAINT_ILLEGAL_WR_BP, AR_NIC_PARB_ERR_OS_MSK_MAINT_ILLEGAL_WR_MASK },
    { "MAINT_LFIFO_MBE", AR_NIC_PARB_ERR_OS_MSK_MAINT_LFIFO_MBE_BP, AR_NIC_PARB_ERR_OS_MSK_MAINT_LFIFO_MBE_MASK },
    { "MAINT_LFIFO_SBE", AR_NIC_PARB_ERR_OS_MSK_MAINT_LFIFO_SBE_BP, AR_NIC_PARB_ERR_OS_MSK_MAINT_LFIFO_SBE_MASK },
    { "MAINT_RSP_MBE", AR_NIC_PARB_ERR_OS_MSK_MAINT_RSP_MBE_BP, AR_NIC_PARB_ERR_OS_MSK_MAINT_RSP_MBE_MASK },
    { "MAINT_RSP_SBE", AR_NIC_PARB_ERR_OS_MSK_MAINT_RSP_SBE_BP, AR_NIC_PARB_ERR_OS_MSK_MAINT_RSP_SBE_MASK },
    { "MAINT_RSP_PE", AR_NIC_PARB_ERR_OS_MSK_MAINT_RSP_PE_BP, AR_NIC_PARB_ERR_OS_MSK_MAINT_RSP_PE_MASK },
    { "MAINT_SFIFO_OVFLW", AR_NIC_PARB_ERR_OS_MSK_MAINT_SFIFO_OVFLW_BP, AR_NIC_PARB_ERR_OS_MSK_MAINT_SFIFO_OVFLW_MASK },
    { "MAINT_LFIFO_OVFLW", AR_NIC_PARB_ERR_OS_MSK_MAINT_LFIFO_OVFLW_BP, AR_NIC_PARB_ERR_OS_MSK_MAINT_LFIFO_OVFLW_MASK },
    { "BTE_RD_UFLW", AR_NIC_PARB_ERR_OS_MSK_BTE_RD_UFLW_BP, AR_NIC_PARB_ERR_OS_MSK_BTE_RD_UFLW_MASK },
    { "BTE_WR_UFLW", AR_NIC_PARB_ERR_OS_MSK_BTE_WR_UFLW_BP, AR_NIC_PARB_ERR_OS_MSK_BTE_WR_UFLW_MASK },
    { "AMO_UFLW", AR_NIC_PARB_ERR_OS_MSK_AMO_UFLW_BP, AR_NIC_PARB_ERR_OS_MSK_AMO_UFLW_MASK },
    { "WC_UFLW", AR_NIC_PARB_ERR_OS_MSK_WC_UFLW_BP, AR_NIC_PARB_ERR_OS_MSK_WC_UFLW_MASK },
    { "IOMMU_UFLW", AR_NIC_PARB_ERR_OS_MSK_IOMMU_UFLW_BP, AR_NIC_PARB_ERR_OS_MSK_IOMMU_UFLW_MASK },
    { "DLA_UFLW", AR_NIC_PARB_ERR_OS_MSK_DLA_UFLW_BP, AR_NIC_PARB_ERR_OS_MSK_DLA_UFLW_MASK },
    { "BTE_RD_OFLW", AR_NIC_PARB_ERR_OS_MSK_BTE_RD_OFLW_BP, AR_NIC_PARB_ERR_OS_MSK_BTE_RD_OFLW_MASK },
    { "BTE_WR_OFLW", AR_NIC_PARB_ERR_OS_MSK_BTE_WR_OFLW_BP, AR_NIC_PARB_ERR_OS_MSK_BTE_WR_OFLW_MASK },
    { "AMO_OFLW", AR_NIC_PARB_ERR_OS_MSK_AMO_OFLW_BP, AR_NIC_PARB_ERR_OS_MSK_AMO_OFLW_MASK },
    { "WC_OFLW", AR_NIC_PARB_ERR_OS_MSK_WC_OFLW_BP, AR_NIC_PARB_ERR_OS_MSK_WC_OFLW_MASK },
    { "IOMMU_OFLW", AR_NIC_PARB_ERR_OS_MSK_IOMMU_OFLW_BP, AR_NIC_PARB_ERR_OS_MSK_IOMMU_OFLW_MASK },
    { "DLA_OFLW", AR_NIC_PARB_ERR_OS_MSK_DLA_OFLW_BP, AR_NIC_PARB_ERR_OS_MSK_DLA_OFLW_MASK },
    { "DIAG_ONLY", AR_NIC_PARB_ERR_OS_MSK_DIAG_ONLY_BP, AR_NIC_PARB_ERR_OS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_err_first_flg_detail[] = {
    { "MAINT_BAD_PAYLD_CNT", AR_NIC_PARB_ERR_FIRST_FLG_MAINT_BAD_PAYLD_CNT_BP, AR_NIC_PARB_ERR_FIRST_FLG_MAINT_BAD_PAYLD_CNT_MASK },
    { "MAINT_RSP_DROP", AR_NIC_PARB_ERR_FIRST_FLG_MAINT_RSP_DROP_BP, AR_NIC_PARB_ERR_FIRST_FLG_MAINT_RSP_DROP_MASK },
    { "MAINT_ILLEGAL_RD", AR_NIC_PARB_ERR_FIRST_FLG_MAINT_ILLEGAL_RD_BP, AR_NIC_PARB_ERR_FIRST_FLG_MAINT_ILLEGAL_RD_MASK },
    { "MAINT_ILLEGAL_WR", AR_NIC_PARB_ERR_FIRST_FLG_MAINT_ILLEGAL_WR_BP, AR_NIC_PARB_ERR_FIRST_FLG_MAINT_ILLEGAL_WR_MASK },
    { "MAINT_LFIFO_MBE", AR_NIC_PARB_ERR_FIRST_FLG_MAINT_LFIFO_MBE_BP, AR_NIC_PARB_ERR_FIRST_FLG_MAINT_LFIFO_MBE_MASK },
    { "MAINT_LFIFO_SBE", AR_NIC_PARB_ERR_FIRST_FLG_MAINT_LFIFO_SBE_BP, AR_NIC_PARB_ERR_FIRST_FLG_MAINT_LFIFO_SBE_MASK },
    { "MAINT_RSP_MBE", AR_NIC_PARB_ERR_FIRST_FLG_MAINT_RSP_MBE_BP, AR_NIC_PARB_ERR_FIRST_FLG_MAINT_RSP_MBE_MASK },
    { "MAINT_RSP_SBE", AR_NIC_PARB_ERR_FIRST_FLG_MAINT_RSP_SBE_BP, AR_NIC_PARB_ERR_FIRST_FLG_MAINT_RSP_SBE_MASK },
    { "MAINT_RSP_PE", AR_NIC_PARB_ERR_FIRST_FLG_MAINT_RSP_PE_BP, AR_NIC_PARB_ERR_FIRST_FLG_MAINT_RSP_PE_MASK },
    { "MAINT_SFIFO_OVFLW", AR_NIC_PARB_ERR_FIRST_FLG_MAINT_SFIFO_OVFLW_BP, AR_NIC_PARB_ERR_FIRST_FLG_MAINT_SFIFO_OVFLW_MASK },
    { "MAINT_LFIFO_OVFLW", AR_NIC_PARB_ERR_FIRST_FLG_MAINT_LFIFO_OVFLW_BP, AR_NIC_PARB_ERR_FIRST_FLG_MAINT_LFIFO_OVFLW_MASK },
    { "BTE_RD_UFLW", AR_NIC_PARB_ERR_FIRST_FLG_BTE_RD_UFLW_BP, AR_NIC_PARB_ERR_FIRST_FLG_BTE_RD_UFLW_MASK },
    { "BTE_WR_UFLW", AR_NIC_PARB_ERR_FIRST_FLG_BTE_WR_UFLW_BP, AR_NIC_PARB_ERR_FIRST_FLG_BTE_WR_UFLW_MASK },
    { "AMO_UFLW", AR_NIC_PARB_ERR_FIRST_FLG_AMO_UFLW_BP, AR_NIC_PARB_ERR_FIRST_FLG_AMO_UFLW_MASK },
    { "WC_UFLW", AR_NIC_PARB_ERR_FIRST_FLG_WC_UFLW_BP, AR_NIC_PARB_ERR_FIRST_FLG_WC_UFLW_MASK },
    { "IOMMU_UFLW", AR_NIC_PARB_ERR_FIRST_FLG_IOMMU_UFLW_BP, AR_NIC_PARB_ERR_FIRST_FLG_IOMMU_UFLW_MASK },
    { "DLA_UFLW", AR_NIC_PARB_ERR_FIRST_FLG_DLA_UFLW_BP, AR_NIC_PARB_ERR_FIRST_FLG_DLA_UFLW_MASK },
    { "BTE_RD_OFLW", AR_NIC_PARB_ERR_FIRST_FLG_BTE_RD_OFLW_BP, AR_NIC_PARB_ERR_FIRST_FLG_BTE_RD_OFLW_MASK },
    { "BTE_WR_OFLW", AR_NIC_PARB_ERR_FIRST_FLG_BTE_WR_OFLW_BP, AR_NIC_PARB_ERR_FIRST_FLG_BTE_WR_OFLW_MASK },
    { "AMO_OFLW", AR_NIC_PARB_ERR_FIRST_FLG_AMO_OFLW_BP, AR_NIC_PARB_ERR_FIRST_FLG_AMO_OFLW_MASK },
    { "WC_OFLW", AR_NIC_PARB_ERR_FIRST_FLG_WC_OFLW_BP, AR_NIC_PARB_ERR_FIRST_FLG_WC_OFLW_MASK },
    { "IOMMU_OFLW", AR_NIC_PARB_ERR_FIRST_FLG_IOMMU_OFLW_BP, AR_NIC_PARB_ERR_FIRST_FLG_IOMMU_OFLW_MASK },
    { "DLA_OFLW", AR_NIC_PARB_ERR_FIRST_FLG_DLA_OFLW_BP, AR_NIC_PARB_ERR_FIRST_FLG_DLA_OFLW_MASK },
    { "DIAG_ONLY", AR_NIC_PARB_ERR_FIRST_FLG_DIAG_ONLY_BP, AR_NIC_PARB_ERR_FIRST_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_dbg_state_detail[] = {
    { "AMO_RDY", AR_NIC_PARB_DBG_STATE_AMO_RDY_BP, AR_NIC_PARB_DBG_STATE_AMO_RDY_MASK },
    { "WC_RDY", AR_NIC_PARB_DBG_STATE_WC_RDY_BP, AR_NIC_PARB_DBG_STATE_WC_RDY_MASK },
    { "POOL_CRDTS", AR_NIC_PARB_DBG_STATE_POOL_CRDTS_BP, AR_NIC_PARB_DBG_STATE_POOL_CRDTS_MASK },
    { "VC2_CRDTS", AR_NIC_PARB_DBG_STATE_VC2_CRDTS_BP, AR_NIC_PARB_DBG_STATE_VC2_CRDTS_MASK },
    { "VC1_CRDTS", AR_NIC_PARB_DBG_STATE_VC1_CRDTS_BP, AR_NIC_PARB_DBG_STATE_VC1_CRDTS_MASK },
    { "VC0_CRDTS", AR_NIC_PARB_DBG_STATE_VC0_CRDTS_BP, AR_NIC_PARB_DBG_STATE_VC0_CRDTS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_prf_en_detail[] = {
    { "PRF_VC2_EN", AR_NIC_PARB_PRF_EN_PRF_VC2_EN_BP, AR_NIC_PARB_PRF_EN_PRF_VC2_EN_MASK },
    { "PRF_VC1_EN", AR_NIC_PARB_PRF_EN_PRF_VC1_EN_BP, AR_NIC_PARB_PRF_EN_PRF_VC1_EN_MASK },
    { "PRF_VC0_EN", AR_NIC_PARB_PRF_EN_PRF_VC0_EN_BP, AR_NIC_PARB_PRF_EN_PRF_VC0_EN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_prf_stall_duration_vc0_detail[] = {
    { "MAX", AR_NIC_PARB_PRF_STALL_DURATION_VC0_MAX_BP, AR_NIC_PARB_PRF_STALL_DURATION_VC0_MAX_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_prf_stall_duration_vc1_detail[] = {
    { "MAX", AR_NIC_PARB_PRF_STALL_DURATION_VC1_MAX_BP, AR_NIC_PARB_PRF_STALL_DURATION_VC1_MAX_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_prf_stall_duration_vc2_detail[] = {
    { "MAX", AR_NIC_PARB_PRF_STALL_DURATION_VC2_MAX_BP, AR_NIC_PARB_PRF_STALL_DURATION_VC2_MAX_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_cfg_maint_queue_params_detail[] = {
    { "MAX_FLITS", AR_NIC_PARB_CFG_MAINT_QUEUE_PARAMS_MAX_FLITS_BP, AR_NIC_PARB_CFG_MAINT_QUEUE_PARAMS_MAX_FLITS_MASK },
    { "SFIFO_CRDTS", AR_NIC_PARB_CFG_MAINT_QUEUE_PARAMS_SFIFO_CRDTS_BP, AR_NIC_PARB_CFG_MAINT_QUEUE_PARAMS_SFIFO_CRDTS_MASK },
    { "MAINT_VC", AR_NIC_PARB_CFG_MAINT_QUEUE_PARAMS_MAINT_VC_BP, AR_NIC_PARB_CFG_MAINT_QUEUE_PARAMS_MAINT_VC_MASK },
    { "BLOCK_ID", AR_NIC_PARB_CFG_MAINT_QUEUE_PARAMS_BLOCK_ID_BP, AR_NIC_PARB_CFG_MAINT_QUEUE_PARAMS_BLOCK_ID_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_cfg_maint_queue_go_detail[] = {
    { "GO", AR_NIC_PARB_CFG_MAINT_QUEUE_GO_GO_BP, AR_NIC_PARB_CFG_MAINT_QUEUE_GO_GO_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_cfg_maint_queue_reset_detail[] = {
    { "RESET", AR_NIC_PARB_CFG_MAINT_QUEUE_RESET_RESET_BP, AR_NIC_PARB_CFG_MAINT_QUEUE_RESET_RESET_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_parb_sts_maint_queue_detail[] = {
    { "QUEUE_STATE", AR_NIC_PARB_STS_MAINT_QUEUE_QUEUE_STATE_BP, AR_NIC_PARB_STS_MAINT_QUEUE_QUEUE_STATE_MASK },
    { "LFIFO_CNTR", AR_NIC_PARB_STS_MAINT_QUEUE_LFIFO_CNTR_BP, AR_NIC_PARB_STS_MAINT_QUEUE_LFIFO_CNTR_MASK },
    { "SFIFO_CNTR", AR_NIC_PARB_STS_MAINT_QUEUE_SFIFO_CNTR_BP, AR_NIC_PARB_STS_MAINT_QUEUE_SFIFO_CNTR_MASK },
    { "RSP_FLIT_CNTR", AR_NIC_PARB_STS_MAINT_QUEUE_RSP_FLIT_CNTR_BP, AR_NIC_PARB_STS_MAINT_QUEUE_RSP_FLIT_CNTR_MASK },
    { "REQ_FLIT_CNTR", AR_NIC_PARB_STS_MAINT_QUEUE_REQ_FLIT_CNTR_BP, AR_NIC_PARB_STS_MAINT_QUEUE_REQ_FLIT_CNTR_MASK },
    { NULL, 0, 0 }
};

/*
 *  AR PARB MMR DECLARATIONS
 */
static const generic_mmr_t _ar_nic_parb_cfg_params = {
    "AR_NIC_PARB_CFG_PARAMS", AR_NIC_PARB_CFG_PARAMS, 8, 1, _ar_nic_parb_cfg_params_detail
};
static const generic_mmr_t _ar_nic_parb_parb_mmr_ring_0_hi_parb = {
    "AR_NIC_PARB_PARB_MMR_RING_0_HI_PARB", AR_NIC_PARB_PARB_MMR_RING_0_HI_PARB, 8, 1, _ar_nic_parb_parb_mmr_ring_0_hi_parb_detail
};
static const generic_mmr_t _ar_nic_parb_parb_mmr_ring_0_mid_parb = {
    "AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB", AR_NIC_PARB_PARB_MMR_RING_0_MID_PARB, 8, 1, _ar_nic_parb_parb_mmr_ring_0_mid_parb_detail
};
static const generic_mmr_t _ar_nic_parb_parb_mmr_ring_0_lo_parb = {
    "AR_NIC_PARB_PARB_MMR_RING_0_LO_PARB", AR_NIC_PARB_PARB_MMR_RING_0_LO_PARB, 8, 1, _ar_nic_parb_parb_mmr_ring_0_lo_parb_detail
};
static const generic_mmr_t _ar_nic_parb_err_flg_1_hi_parb = {
    "AR_NIC_PARB_ERR_FLG_1_HI_PARB", AR_NIC_PARB_ERR_FLG_1_HI_PARB, 8, 1, _ar_nic_parb_err_flg_1_hi_parb_detail
};
static const generic_mmr_t _ar_nic_parb_err_flg_1_mid_parb = {
    "AR_NIC_PARB_ERR_FLG_1_MID_PARB", AR_NIC_PARB_ERR_FLG_1_MID_PARB, 8, 1, _ar_nic_parb_err_flg_1_mid_parb_detail
};
static const generic_mmr_t _ar_nic_parb_err_flg_1_lo_parb = {
    "AR_NIC_PARB_ERR_FLG_1_LO_PARB", AR_NIC_PARB_ERR_FLG_1_LO_PARB, 8, 1, _ar_nic_parb_err_flg_1_lo_parb_detail
};
static const generic_mmr_t _ar_nic_parb_nic_pi_req_flit_2_hi_parb = {
    "AR_NIC_PARB_NIC_PI_REQ_FLIT_2_HI_PARB", AR_NIC_PARB_NIC_PI_REQ_FLIT_2_HI_PARB, 8, 1, _ar_nic_parb_nic_pi_req_flit_2_hi_parb_detail
};
static const generic_mmr_t _ar_nic_parb_nic_pi_req_flit_2_mid_parb = {
    "AR_NIC_PARB_NIC_PI_REQ_FLIT_2_MID_PARB", AR_NIC_PARB_NIC_PI_REQ_FLIT_2_MID_PARB, 8, 1, _ar_nic_parb_nic_pi_req_flit_2_mid_parb_detail
};
static const generic_mmr_t _ar_nic_parb_nic_pi_req_flit_2_lo_parb = {
    "AR_NIC_PARB_NIC_PI_REQ_FLIT_2_LO_PARB", AR_NIC_PARB_NIC_PI_REQ_FLIT_2_LO_PARB, 8, 1, _ar_nic_parb_nic_pi_req_flit_2_lo_parb_detail
};
static const generic_mmr_t _ar_nic_parb_parb_power_down_ff_hi_parb = {
    "AR_NIC_PARB_PARB_POWER_DOWN_FF_HI_PARB", AR_NIC_PARB_PARB_POWER_DOWN_FF_HI_PARB, 8, 1, _ar_nic_parb_parb_power_down_ff_hi_parb_detail
};
static const generic_mmr_t _ar_nic_parb_parb_power_down_ff_mid_parb = {
    "AR_NIC_PARB_PARB_POWER_DOWN_FF_MID_PARB", AR_NIC_PARB_PARB_POWER_DOWN_FF_MID_PARB, 8, 1, _ar_nic_parb_parb_power_down_ff_mid_parb_detail
};
static const generic_mmr_t _ar_nic_parb_parb_power_down_ff_lo_parb = {
    "AR_NIC_PARB_PARB_POWER_DOWN_FF_LO_PARB", AR_NIC_PARB_PARB_POWER_DOWN_FF_LO_PARB, 8, 1, _ar_nic_parb_parb_power_down_ff_lo_parb_detail
};
static const generic_mmr_t _ar_nic_parb_err_flg = {
    "AR_NIC_PARB_ERR_FLG", AR_NIC_PARB_ERR_FLG, 8, 1, _ar_nic_parb_err_flg_detail
};
static const generic_mmr_t _ar_nic_parb_err_clr = {
    "AR_NIC_PARB_ERR_CLR", AR_NIC_PARB_ERR_CLR, 8, 1, _ar_nic_parb_err_clr_detail
};
static const generic_mmr_t _ar_nic_parb_err_hss_msk = {
    "AR_NIC_PARB_ERR_HSS_MSK", AR_NIC_PARB_ERR_HSS_MSK, 8, 1, _ar_nic_parb_err_hss_msk_detail
};
static const generic_mmr_t _ar_nic_parb_err_os_msk = {
    "AR_NIC_PARB_ERR_OS_MSK", AR_NIC_PARB_ERR_OS_MSK, 8, 1, _ar_nic_parb_err_os_msk_detail
};
static const generic_mmr_t _ar_nic_parb_err_first_flg = {
    "AR_NIC_PARB_ERR_FIRST_FLG", AR_NIC_PARB_ERR_FIRST_FLG, 8, 1, _ar_nic_parb_err_first_flg_detail
};
static const generic_mmr_t _ar_nic_parb_dbg_state = {
    "AR_NIC_PARB_DBG_STATE", AR_NIC_PARB_DBG_STATE, 8, 1, _ar_nic_parb_dbg_state_detail
};
static const generic_mmr_t _ar_nic_parb_prf_en = {
    "AR_NIC_PARB_PRF_EN", AR_NIC_PARB_PRF_EN, 8, 1, _ar_nic_parb_prf_en_detail
};
static const generic_mmr_t _ar_nic_parb_prf_stall_duration_vc0 = {
    "AR_NIC_PARB_PRF_STALL_DURATION_VC0", AR_NIC_PARB_PRF_STALL_DURATION_VC0, 8, 1, _ar_nic_parb_prf_stall_duration_vc0_detail
};
static const generic_mmr_t _ar_nic_parb_prf_stall_duration_vc1 = {
    "AR_NIC_PARB_PRF_STALL_DURATION_VC1", AR_NIC_PARB_PRF_STALL_DURATION_VC1, 8, 1, _ar_nic_parb_prf_stall_duration_vc1_detail
};
static const generic_mmr_t _ar_nic_parb_prf_stall_duration_vc2 = {
    "AR_NIC_PARB_PRF_STALL_DURATION_VC2", AR_NIC_PARB_PRF_STALL_DURATION_VC2, 8, 1, _ar_nic_parb_prf_stall_duration_vc2_detail
};
static const generic_mmr_t _ar_nic_parb_cfg_maint_queue_params = {
    "AR_NIC_PARB_CFG_MAINT_QUEUE_PARAMS", AR_NIC_PARB_CFG_MAINT_QUEUE_PARAMS, 8, 1, _ar_nic_parb_cfg_maint_queue_params_detail
};
static const generic_mmr_t _ar_nic_parb_cfg_maint_queue_go = {
    "AR_NIC_PARB_CFG_MAINT_QUEUE_GO", AR_NIC_PARB_CFG_MAINT_QUEUE_GO, 8, 1, _ar_nic_parb_cfg_maint_queue_go_detail
};
static const generic_mmr_t _ar_nic_parb_cfg_maint_queue_reset = {
    "AR_NIC_PARB_CFG_MAINT_QUEUE_RESET", AR_NIC_PARB_CFG_MAINT_QUEUE_RESET, 8, 1, _ar_nic_parb_cfg_maint_queue_reset_detail
};
static const generic_mmr_t _ar_nic_parb_sts_maint_queue = {
    "AR_NIC_PARB_STS_MAINT_QUEUE", AR_NIC_PARB_STS_MAINT_QUEUE, 8, 1, _ar_nic_parb_sts_maint_queue_detail
};

/*
 *  INSTALL AR PARB MMRS
 */
static const generic_mmr_t* _ar_parb_mmrs[] _unused = {
    &_ar_nic_parb_cfg_params,
    &_ar_nic_parb_parb_mmr_ring_0_hi_parb,
    &_ar_nic_parb_parb_mmr_ring_0_mid_parb,
    &_ar_nic_parb_parb_mmr_ring_0_lo_parb,
    &_ar_nic_parb_err_flg_1_hi_parb,
    &_ar_nic_parb_err_flg_1_mid_parb,
    &_ar_nic_parb_err_flg_1_lo_parb,
    &_ar_nic_parb_nic_pi_req_flit_2_hi_parb,
    &_ar_nic_parb_nic_pi_req_flit_2_mid_parb,
    &_ar_nic_parb_nic_pi_req_flit_2_lo_parb,
    &_ar_nic_parb_parb_power_down_ff_hi_parb,
    &_ar_nic_parb_parb_power_down_ff_mid_parb,
    &_ar_nic_parb_parb_power_down_ff_lo_parb,
    &_ar_nic_parb_err_flg,
    &_ar_nic_parb_err_clr,
    &_ar_nic_parb_err_hss_msk,
    &_ar_nic_parb_err_os_msk,
    &_ar_nic_parb_err_first_flg,
    &_ar_nic_parb_dbg_state,
    &_ar_nic_parb_prf_en,
    &_ar_nic_parb_prf_stall_duration_vc0,
    &_ar_nic_parb_prf_stall_duration_vc1,
    &_ar_nic_parb_prf_stall_duration_vc2,
    &_ar_nic_parb_cfg_maint_queue_params,
    &_ar_nic_parb_cfg_maint_queue_go,
    &_ar_nic_parb_cfg_maint_queue_reset,
    &_ar_nic_parb_sts_maint_queue,
    NULL
};

#endif
