/******************************************************************************
 * COPYRIGHT CRAY INC. ar_pt_mmrs_h.h
 * FILE: ar_pt_mmrs_h.h
 * Created by v2h.c on Wed Oct  8 14:39:04 2014
 ******************************************************************************/

#ifndef _AR_PT_MMRS_H_H_
#define _AR_PT_MMRS_H_H_

#ifdef __GNUC__
#define _unused __attribute__((unused))
#else
#define _unused
#endif

#ifndef _GENERIC_MMRD_T_
#define _GENERIC_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint64_t _mask;		/* Field bit mask */
} generic_mmrd_t;
#endif

#ifndef _ERRCAT_MMRD_T_
#define _ERRCAT_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint32_t _ec;		/* Field error category */
} errcat_mmrd_t;
#endif

#ifndef _GENERIC_MMR_T_
#define _GENERIC_MMR_T_
typedef struct {
	char* _name;		/* MMR name */
	uint64_t _addr;		/* MMR address */
	int _size;		/* Size in bytes of MMR */
	int _depth;		/* Number of MMR instances */
	const generic_mmrd_t *_info;	/* MMR detail */
} generic_mmr_t;
#endif

static const generic_mmr_t* _ar_pt_mmrs[] _unused;	/* PT Array */

/*
 *  AR PT MMR DETAIL DECLARATIONS
 */
static const generic_mmrd_t _ar_rtr_pt_inq_cfg_degrade_diag_detail[] = {
    { "LMON_SUBSWITCH_SEL", AR_RTR_PT_INQ_CFG_DEGRADE_DIAG_LMON_SUBSWITCH_SEL_BP, AR_RTR_PT_INQ_CFG_DEGRADE_DIAG_LMON_SUBSWITCH_SEL_MASK },
    { "LMON_COLBUF_SEL", AR_RTR_PT_INQ_CFG_DEGRADE_DIAG_LMON_COLBUF_SEL_BP, AR_RTR_PT_INQ_CFG_DEGRADE_DIAG_LMON_COLBUF_SEL_MASK },
    { "LMON_INQ_SEL", AR_RTR_PT_INQ_CFG_DEGRADE_DIAG_LMON_INQ_SEL_BP, AR_RTR_PT_INQ_CFG_DEGRADE_DIAG_LMON_INQ_SEL_MASK },
    { "LMON_EN", AR_RTR_PT_INQ_CFG_DEGRADE_DIAG_LMON_EN_BP, AR_RTR_PT_INQ_CFG_DEGRADE_DIAG_LMON_EN_MASK },
    { "LMON_SEL", AR_RTR_PT_INQ_CFG_DEGRADE_DIAG_LMON_SEL_BP, AR_RTR_PT_INQ_CFG_DEGRADE_DIAG_LMON_SEL_MASK },
    { "COLBUF_GC_MODE", AR_RTR_PT_INQ_CFG_DEGRADE_DIAG_COLBUF_GC_MODE_BP, AR_RTR_PT_INQ_CFG_DEGRADE_DIAG_COLBUF_GC_MODE_MASK },
    { "DISABLE_LINK_ALIVE_DISCOVERY", AR_RTR_PT_INQ_CFG_DEGRADE_DIAG_DISABLE_LINK_ALIVE_DISCOVERY_BP, AR_RTR_PT_INQ_CFG_DEGRADE_DIAG_DISABLE_LINK_ALIVE_DISCOVERY_MASK },
    { "VC_UNDER_TEST", AR_RTR_PT_INQ_CFG_DEGRADE_DIAG_VC_UNDER_TEST_BP, AR_RTR_PT_INQ_CFG_DEGRADE_DIAG_VC_UNDER_TEST_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_cfg_fifo_rowbuf_crdt_limit_detail[] = {
    { "OFIFO_RSP_CRDT_LIMIT", AR_RTR_PT_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_OFIFO_RSP_CRDT_LIMIT_BP, AR_RTR_PT_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_OFIFO_RSP_CRDT_LIMIT_MASK },
    { "OFIFO_REQ_CRDT_LIMIT", AR_RTR_PT_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_OFIFO_REQ_CRDT_LIMIT_BP, AR_RTR_PT_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_OFIFO_REQ_CRDT_LIMIT_MASK },
    { "ROWBUF_RSP_CRDT_LIMIT", AR_RTR_PT_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_ROWBUF_RSP_CRDT_LIMIT_BP, AR_RTR_PT_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_ROWBUF_RSP_CRDT_LIMIT_MASK },
    { "ROWBUF_REQ_CRDT_LIMIT", AR_RTR_PT_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_ROWBUF_REQ_CRDT_LIMIT_BP, AR_RTR_PT_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT_ROWBUF_REQ_CRDT_LIMIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_cfg_fifo_rowbuf_crdts_detail[] = {
    { "OFIFO_RSP_CRDTS", AR_RTR_PT_INQ_CFG_FIFO_ROWBUF_CRDTS_OFIFO_RSP_CRDTS_BP, AR_RTR_PT_INQ_CFG_FIFO_ROWBUF_CRDTS_OFIFO_RSP_CRDTS_MASK },
    { "OFIFO_REQ_CRDTS", AR_RTR_PT_INQ_CFG_FIFO_ROWBUF_CRDTS_OFIFO_REQ_CRDTS_BP, AR_RTR_PT_INQ_CFG_FIFO_ROWBUF_CRDTS_OFIFO_REQ_CRDTS_MASK },
    { "ROWBUF_RSP_CRDTS", AR_RTR_PT_INQ_CFG_FIFO_ROWBUF_CRDTS_ROWBUF_RSP_CRDTS_BP, AR_RTR_PT_INQ_CFG_FIFO_ROWBUF_CRDTS_ROWBUF_RSP_CRDTS_MASK },
    { "ROWBUF_REQ_CRDTS", AR_RTR_PT_INQ_CFG_FIFO_ROWBUF_CRDTS_ROWBUF_REQ_CRDTS_BP, AR_RTR_PT_INQ_CFG_FIFO_ROWBUF_CRDTS_ROWBUF_REQ_CRDTS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_cfg_route_pipe_detail[] = {
    { "RESET_LFSR", AR_RTR_PT_INQ_CFG_ROUTE_PIPE_RESET_LFSR_BP, AR_RTR_PT_INQ_CFG_ROUTE_PIPE_RESET_LFSR_MASK },
    { "READ_ALL_RTABLES", AR_RTR_PT_INQ_CFG_ROUTE_PIPE_READ_ALL_RTABLES_BP, AR_RTR_PT_INQ_CFG_ROUTE_PIPE_READ_ALL_RTABLES_MASK },
    { "ROUTE_ERR_TYPE_ENABLE", AR_RTR_PT_INQ_CFG_ROUTE_PIPE_ROUTE_ERR_TYPE_ENABLE_BP, AR_RTR_PT_INQ_CFG_ROUTE_PIPE_ROUTE_ERR_TYPE_ENABLE_MASK },
    { "GROUP_NUMBER", AR_RTR_PT_INQ_CFG_ROUTE_PIPE_GROUP_NUMBER_BP, AR_RTR_PT_INQ_CFG_ROUTE_PIPE_GROUP_NUMBER_MASK },
    { "ARIES_NUMBER", AR_RTR_PT_INQ_CFG_ROUTE_PIPE_ARIES_NUMBER_BP, AR_RTR_PT_INQ_CFG_ROUTE_PIPE_ARIES_NUMBER_MASK },
    { "INCR_INCOMING_VC", AR_RTR_PT_INQ_CFG_ROUTE_PIPE_INCR_INCOMING_VC_BP, AR_RTR_PT_INQ_CFG_ROUTE_PIPE_INCR_INCOMING_VC_MASK },
    { "AT_A_BLUE_TILE", AR_RTR_PT_INQ_CFG_ROUTE_PIPE_AT_A_BLUE_TILE_BP, AR_RTR_PT_INQ_CFG_ROUTE_PIPE_AT_A_BLUE_TILE_MASK },
    { "AT_A_PTILE", AR_RTR_PT_INQ_CFG_ROUTE_PIPE_AT_A_PTILE_BP, AR_RTR_PT_INQ_CFG_ROUTE_PIPE_AT_A_PTILE_MASK },
    { "HASH_ID", AR_RTR_PT_INQ_CFG_ROUTE_PIPE_HASH_ID_BP, AR_RTR_PT_INQ_CFG_ROUTE_PIPE_HASH_ID_MASK },
    { "LMIN_TBL_ADDR_SHIFT", AR_RTR_PT_INQ_CFG_ROUTE_PIPE_LMIN_TBL_ADDR_SHIFT_BP, AR_RTR_PT_INQ_CFG_ROUTE_PIPE_LMIN_TBL_ADDR_SHIFT_MASK },
    { "GMIN_TBL_ADDR_SHIFT", AR_RTR_PT_INQ_CFG_ROUTE_PIPE_GMIN_TBL_ADDR_SHIFT_BP, AR_RTR_PT_INQ_CFG_ROUTE_PIPE_GMIN_TBL_ADDR_SHIFT_MASK },
    { "DISABLE_CONGESTION", AR_RTR_PT_INQ_CFG_ROUTE_PIPE_DISABLE_CONGESTION_BP, AR_RTR_PT_INQ_CFG_ROUTE_PIPE_DISABLE_CONGESTION_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_cfg_vc_table_detail[] = {
    { "TRGT_VC7_PAR", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC7_PAR_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC7_PAR_MASK },
    { "TRGT_VC7_ROOT", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC7_ROOT_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC7_ROOT_MASK },
    { "TRGT_VC7", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC7_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC7_MASK },
    { "TRGT_VC6_PAR", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC6_PAR_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC6_PAR_MASK },
    { "TRGT_VC6_ROOT", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC6_ROOT_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC6_ROOT_MASK },
    { "TRGT_VC6", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC6_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC6_MASK },
    { "TRGT_VC5_PAR", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC5_PAR_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC5_PAR_MASK },
    { "TRGT_VC5_ROOT", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC5_ROOT_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC5_ROOT_MASK },
    { "TRGT_VC5", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC5_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC5_MASK },
    { "TRGT_VC4_PAR", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC4_PAR_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC4_PAR_MASK },
    { "TRGT_VC4_ROOT", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC4_ROOT_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC4_ROOT_MASK },
    { "TRGT_VC4", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC4_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC4_MASK },
    { "TRGT_VC3_PAR", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC3_PAR_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC3_PAR_MASK },
    { "TRGT_VC3_ROOT", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC3_ROOT_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC3_ROOT_MASK },
    { "TRGT_VC3", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC3_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC3_MASK },
    { "TRGT_VC2_PAR", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC2_PAR_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC2_PAR_MASK },
    { "TRGT_VC2_ROOT", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC2_ROOT_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC2_ROOT_MASK },
    { "TRGT_VC2", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC2_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC2_MASK },
    { "TRGT_VC1_PAR", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC1_PAR_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC1_PAR_MASK },
    { "TRGT_VC1_ROOT", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC1_ROOT_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC1_ROOT_MASK },
    { "TRGT_VC1", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC1_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC1_MASK },
    { "TRGT_VC0_PAR", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC0_PAR_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC0_PAR_MASK },
    { "TRGT_VC0_ROOT", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC0_ROOT_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC0_ROOT_MASK },
    { "TRGT_VC0", AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC0_BP, AR_RTR_PT_INQ_CFG_VC_TABLE_TRGT_VC0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_cfg_link_alive_bits_detail[] = {
    { "LINK_ALIVE", AR_RTR_PT_INQ_CFG_LINK_ALIVE_BITS_LINK_ALIVE_BP, AR_RTR_PT_INQ_CFG_LINK_ALIVE_BITS_LINK_ALIVE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_cfg_congest_ctrl_detail[] = {
    { "ADAPT3_NONMIN_CONGEST_ADD", AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT3_NONMIN_CONGEST_ADD_BP, AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT3_NONMIN_CONGEST_ADD_MASK },
    { "ADAPT3_NONMIN_CONGEST_SHIFT", AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT3_NONMIN_CONGEST_SHIFT_BP, AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT3_NONMIN_CONGEST_SHIFT_MASK },
    { "ADAPT3_MIN_CONGEST_ADD", AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT3_MIN_CONGEST_ADD_BP, AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT3_MIN_CONGEST_ADD_MASK },
    { "ADAPT3_MIN_CONGEST_SHIFT", AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT3_MIN_CONGEST_SHIFT_BP, AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT3_MIN_CONGEST_SHIFT_MASK },
    { "ADAPT2_NONMIN_CONGEST_ADD", AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT2_NONMIN_CONGEST_ADD_BP, AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT2_NONMIN_CONGEST_ADD_MASK },
    { "ADAPT2_NONMIN_CONGEST_SHIFT", AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT2_NONMIN_CONGEST_SHIFT_BP, AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT2_NONMIN_CONGEST_SHIFT_MASK },
    { "ADAPT2_MIN_CONGEST_ADD", AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT2_MIN_CONGEST_ADD_BP, AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT2_MIN_CONGEST_ADD_MASK },
    { "ADAPT2_MIN_CONGEST_SHIFT", AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT2_MIN_CONGEST_SHIFT_BP, AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT2_MIN_CONGEST_SHIFT_MASK },
    { "ADAPT1_NONMIN_CONGEST_ADD", AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT1_NONMIN_CONGEST_ADD_BP, AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT1_NONMIN_CONGEST_ADD_MASK },
    { "ADAPT1_NONMIN_CONGEST_SHIFT", AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT1_NONMIN_CONGEST_SHIFT_BP, AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT1_NONMIN_CONGEST_SHIFT_MASK },
    { "ADAPT1_MIN_CONGEST_ADD", AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT1_MIN_CONGEST_ADD_BP, AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT1_MIN_CONGEST_ADD_MASK },
    { "ADAPT1_MIN_CONGEST_SHIFT", AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT1_MIN_CONGEST_SHIFT_BP, AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT1_MIN_CONGEST_SHIFT_MASK },
    { "ADAPT0_NONMIN_CONGEST_ADD", AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT0_NONMIN_CONGEST_ADD_BP, AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT0_NONMIN_CONGEST_ADD_MASK },
    { "ADAPT0_NONMIN_CONGEST_SHIFT", AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT0_NONMIN_CONGEST_SHIFT_BP, AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT0_NONMIN_CONGEST_SHIFT_MASK },
    { "ADAPT0_MIN_CONGEST_ADD", AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT0_MIN_CONGEST_ADD_BP, AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT0_MIN_CONGEST_ADD_MASK },
    { "ADAPT0_MIN_CONGEST_SHIFT", AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT0_MIN_CONGEST_SHIFT_BP, AR_RTR_PT_INQ_CFG_CONGEST_CTRL_ADAPT0_MIN_CONGEST_SHIFT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_cfg_init_vc_inject_detail[] = {
    { "OUTGRP_RSP_VC_ADAPTIVE3", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_RSP_VC_ADAPTIVE3_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_RSP_VC_ADAPTIVE3_MASK },
    { "OUTGRP_RSP_VC_ADAPTIVE2", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_RSP_VC_ADAPTIVE2_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_RSP_VC_ADAPTIVE2_MASK },
    { "OUTGRP_RSP_VC_ADAPTIVE1", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_RSP_VC_ADAPTIVE1_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_RSP_VC_ADAPTIVE1_MASK },
    { "OUTGRP_RSP_VC_ADAPTIVE0", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_RSP_VC_ADAPTIVE0_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_RSP_VC_ADAPTIVE0_MASK },
    { "OUTGRP_RSP_VC_MIN_NON_HASHED", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_RSP_VC_MIN_NON_HASHED_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_RSP_VC_MIN_NON_HASHED_MASK },
    { "RESERVED_53_52", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_RESERVED_53_52_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_RESERVED_53_52_MASK },
    { "OUTGRP_RSP_VC_MIN_HASHED", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_RSP_VC_MIN_HASHED_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_RSP_VC_MIN_HASHED_MASK },
    { "OUTGRP_RSP_VC_NON_MIN_HASHED", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_RSP_VC_NON_MIN_HASHED_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_RSP_VC_NON_MIN_HASHED_MASK },
    { "INGRP_RSP_VC_ADAPTIVE3", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_RSP_VC_ADAPTIVE3_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_RSP_VC_ADAPTIVE3_MASK },
    { "INGRP_RSP_VC_ADAPTIVE2", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_RSP_VC_ADAPTIVE2_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_RSP_VC_ADAPTIVE2_MASK },
    { "INGRP_RSP_VC_ADAPTIVE1", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_RSP_VC_ADAPTIVE1_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_RSP_VC_ADAPTIVE1_MASK },
    { "INGRP_RSP_VC_ADAPTIVE0", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_RSP_VC_ADAPTIVE0_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_RSP_VC_ADAPTIVE0_MASK },
    { "INGRP_RSP_VC_MIN_NON_HASHED", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_RSP_VC_MIN_NON_HASHED_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_RSP_VC_MIN_NON_HASHED_MASK },
    { "RESERVED_37_36", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_RESERVED_37_36_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_RESERVED_37_36_MASK },
    { "INGRP_RSP_VC_MIN_HASHED", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_RSP_VC_MIN_HASHED_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_RSP_VC_MIN_HASHED_MASK },
    { "INGRP_RSP_VC_NON_MIN_HASHED", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_RSP_VC_NON_MIN_HASHED_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_RSP_VC_NON_MIN_HASHED_MASK },
    { "OUTGRP_REQ_VC_ADAPTIVE3", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_REQ_VC_ADAPTIVE3_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_REQ_VC_ADAPTIVE3_MASK },
    { "OUTGRP_REQ_VC_ADAPTIVE2", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_REQ_VC_ADAPTIVE2_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_REQ_VC_ADAPTIVE2_MASK },
    { "OUTGRP_REQ_VC_ADAPTIVE1", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_REQ_VC_ADAPTIVE1_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_REQ_VC_ADAPTIVE1_MASK },
    { "OUTGRP_REQ_VC_ADAPTIVE0", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_REQ_VC_ADAPTIVE0_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_REQ_VC_ADAPTIVE0_MASK },
    { "OUTGRP_REQ_VC_MIN_NON_HASHED", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_REQ_VC_MIN_NON_HASHED_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_REQ_VC_MIN_NON_HASHED_MASK },
    { "RESERVED_21_20", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_RESERVED_21_20_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_RESERVED_21_20_MASK },
    { "OUTGRP_REQ_VC_MIN_HASHED", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_REQ_VC_MIN_HASHED_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_REQ_VC_MIN_HASHED_MASK },
    { "OUTGRP_REQ_VC_NON_MIN_HASHED", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_REQ_VC_NON_MIN_HASHED_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_OUTGRP_REQ_VC_NON_MIN_HASHED_MASK },
    { "INGRP_REQ_VC_ADAPTIVE3", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_REQ_VC_ADAPTIVE3_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_REQ_VC_ADAPTIVE3_MASK },
    { "INGRP_REQ_VC_ADAPTIVE2", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_REQ_VC_ADAPTIVE2_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_REQ_VC_ADAPTIVE2_MASK },
    { "INGRP_REQ_VC_ADAPTIVE1", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_REQ_VC_ADAPTIVE1_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_REQ_VC_ADAPTIVE1_MASK },
    { "INGRP_REQ_VC_ADAPTIVE0", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_REQ_VC_ADAPTIVE0_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_REQ_VC_ADAPTIVE0_MASK },
    { "INGRP_REQ_VC_MIN_NON_HASHED", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_REQ_VC_MIN_NON_HASHED_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_REQ_VC_MIN_NON_HASHED_MASK },
    { "RESERVED_5_4", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_RESERVED_5_4_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_RESERVED_5_4_MASK },
    { "INGRP_REQ_VC_MIN_HASHED", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_REQ_VC_MIN_HASHED_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_REQ_VC_MIN_HASHED_MASK },
    { "INGRP_REQ_VC_NON_MIN_HASHED", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_REQ_VC_NON_MIN_HASHED_BP, AR_RTR_PT_INQ_CFG_INIT_VC_INJECT_INGRP_REQ_VC_NON_MIN_HASHED_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_err_flg_detail[] = {
    { "COLBUF_MAX_PKT_ERR", AR_RTR_PT_INQ_ERR_FLG_COLBUF_MAX_PKT_ERR_BP, AR_RTR_PT_INQ_ERR_FLG_COLBUF_MAX_PKT_ERR_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT5", AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT5_BP, AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT5_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT4", AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT4_BP, AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT4_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT3", AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT3_BP, AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT3_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT2", AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT2_BP, AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT2_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT1", AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT1_BP, AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT1_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT0", AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT0_BP, AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT0_MASK },
    { "SUBSWITCH_ERR", AR_RTR_PT_INQ_ERR_FLG_SUBSWITCH_ERR_BP, AR_RTR_PT_INQ_ERR_FLG_SUBSWITCH_ERR_MASK },
    { "LINK_ALIVE_TIMEOUT_ERR", AR_RTR_PT_INQ_ERR_FLG_LINK_ALIVE_TIMEOUT_ERR_BP, AR_RTR_PT_INQ_ERR_FLG_LINK_ALIVE_TIMEOUT_ERR_MASK },
    { "LINK_ALIVE_CHANNEL_ERR", AR_RTR_PT_INQ_ERR_FLG_LINK_ALIVE_CHANNEL_ERR_BP, AR_RTR_PT_INQ_ERR_FLG_LINK_ALIVE_CHANNEL_ERR_MASK },
    { "PRF_CNT_ROLLOVR_ERR", AR_RTR_PT_INQ_ERR_FLG_PRF_CNT_ROLLOVR_ERR_BP, AR_RTR_PT_INQ_ERR_FLG_PRF_CNT_ROLLOVR_ERR_MASK },
    { "MBE_RTABLE", AR_RTR_PT_INQ_ERR_FLG_MBE_RTABLE_BP, AR_RTR_PT_INQ_ERR_FLG_MBE_RTABLE_MASK },
    { "SBE_RTABLE", AR_RTR_PT_INQ_ERR_FLG_SBE_RTABLE_BP, AR_RTR_PT_INQ_ERR_FLG_SBE_RTABLE_MASK },
    { "ROUTE_ERROR", AR_RTR_PT_INQ_ERR_FLG_ROUTE_ERROR_BP, AR_RTR_PT_INQ_ERR_FLG_ROUTE_ERROR_MASK },
    { "PBE_VC_TABLE", AR_RTR_PT_INQ_ERR_FLG_PBE_VC_TABLE_BP, AR_RTR_PT_INQ_ERR_FLG_PBE_VC_TABLE_MASK },
    { "PBE_RFIFO_RS", AR_RTR_PT_INQ_ERR_FLG_PBE_RFIFO_RS_BP, AR_RTR_PT_INQ_ERR_FLG_PBE_RFIFO_RS_MASK },
    { "PBE_RFIFO_RQ", AR_RTR_PT_INQ_ERR_FLG_PBE_RFIFO_RQ_BP, AR_RTR_PT_INQ_ERR_FLG_PBE_RFIFO_RQ_MASK },
    { "UFLW_ERR_RS_RFIFO", AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RS_RFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RS_RFIFO_MASK },
    { "UFLW_ERR_RQ_RFIFO", AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RQ_RFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RQ_RFIFO_MASK },
    { "UFLW_ERR_RS_OFIFO", AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RS_OFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RS_OFIFO_MASK },
    { "UFLW_ERR_RQ_OFIFO", AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RQ_OFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RQ_OFIFO_MASK },
    { "UFLW_ERR_RS_DFIFO", AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RS_DFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RS_DFIFO_MASK },
    { "UFLW_ERR_RQ_DFIFO", AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RQ_DFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RQ_DFIFO_MASK },
    { "OFLW_ERR_RS_RFIFO", AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RS_RFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RS_RFIFO_MASK },
    { "OFLW_ERR_RQ_RFIFO", AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RQ_RFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RQ_RFIFO_MASK },
    { "OFLW_ERR_RS_OFIFO", AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RS_OFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RS_OFIFO_MASK },
    { "OFLW_ERR_RQ_OFIFO", AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RQ_OFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RQ_OFIFO_MASK },
    { "OFLW_ERR_RS_DFIFO", AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RS_DFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RS_DFIFO_MASK },
    { "OFLW_ERR_RQ_DFIFO", AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RQ_DFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RQ_DFIFO_MASK },
    { "MBE_RS_DFIFO", AR_RTR_PT_INQ_ERR_FLG_MBE_RS_DFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_MBE_RS_DFIFO_MASK },
    { "SBE_RS_DFIFO", AR_RTR_PT_INQ_ERR_FLG_SBE_RS_DFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_SBE_RS_DFIFO_MASK },
    { "MBE_RQ_DFIFO", AR_RTR_PT_INQ_ERR_FLG_MBE_RQ_DFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_MBE_RQ_DFIFO_MASK },
    { "SBE_RQ_DFIFO", AR_RTR_PT_INQ_ERR_FLG_SBE_RQ_DFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_SBE_RQ_DFIFO_MASK },
    { "DIAG_ONLY", AR_RTR_PT_INQ_ERR_FLG_DIAG_ONLY_BP, AR_RTR_PT_INQ_ERR_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
#ifdef EXCEPTIONS_DEFS
static const errcat_mmrd_t _ar_rtr_pt_inq_err_flg_errcat[] = {
    { "COLBUF_MAX_PKT_ERR", AR_RTR_PT_INQ_ERR_FLG_COLBUF_MAX_PKT_ERR_BP, AR_RTR_PT_INQ_ERR_FLG_COLBUF_MAX_PKT_ERR_EC },
    { "COLBUF_OFLW_UFLW_ERR_INPUT5", AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT5_BP, AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT5_EC },
    { "COLBUF_OFLW_UFLW_ERR_INPUT4", AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT4_BP, AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT4_EC },
    { "COLBUF_OFLW_UFLW_ERR_INPUT3", AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT3_BP, AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT3_EC },
    { "COLBUF_OFLW_UFLW_ERR_INPUT2", AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT2_BP, AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT2_EC },
    { "COLBUF_OFLW_UFLW_ERR_INPUT1", AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT1_BP, AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT1_EC },
    { "COLBUF_OFLW_UFLW_ERR_INPUT0", AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT0_BP, AR_RTR_PT_INQ_ERR_FLG_COLBUF_OFLW_UFLW_ERR_INPUT0_EC },
    { "SUBSWITCH_ERR", AR_RTR_PT_INQ_ERR_FLG_SUBSWITCH_ERR_BP, AR_RTR_PT_INQ_ERR_FLG_SUBSWITCH_ERR_EC },
    { "LINK_ALIVE_TIMEOUT_ERR", AR_RTR_PT_INQ_ERR_FLG_LINK_ALIVE_TIMEOUT_ERR_BP, AR_RTR_PT_INQ_ERR_FLG_LINK_ALIVE_TIMEOUT_ERR_EC },
    { "LINK_ALIVE_CHANNEL_ERR", AR_RTR_PT_INQ_ERR_FLG_LINK_ALIVE_CHANNEL_ERR_BP, AR_RTR_PT_INQ_ERR_FLG_LINK_ALIVE_CHANNEL_ERR_EC },
    { "PRF_CNT_ROLLOVR_ERR", AR_RTR_PT_INQ_ERR_FLG_PRF_CNT_ROLLOVR_ERR_BP, AR_RTR_PT_INQ_ERR_FLG_PRF_CNT_ROLLOVR_ERR_EC },
    { "MBE_RTABLE", AR_RTR_PT_INQ_ERR_FLG_MBE_RTABLE_BP, AR_RTR_PT_INQ_ERR_FLG_MBE_RTABLE_EC },
    { "SBE_RTABLE", AR_RTR_PT_INQ_ERR_FLG_SBE_RTABLE_BP, AR_RTR_PT_INQ_ERR_FLG_SBE_RTABLE_EC },
    { "ROUTE_ERROR", AR_RTR_PT_INQ_ERR_FLG_ROUTE_ERROR_BP, AR_RTR_PT_INQ_ERR_FLG_ROUTE_ERROR_EC },
    { "PBE_VC_TABLE", AR_RTR_PT_INQ_ERR_FLG_PBE_VC_TABLE_BP, AR_RTR_PT_INQ_ERR_FLG_PBE_VC_TABLE_EC },
    { "PBE_RFIFO_RS", AR_RTR_PT_INQ_ERR_FLG_PBE_RFIFO_RS_BP, AR_RTR_PT_INQ_ERR_FLG_PBE_RFIFO_RS_EC },
    { "PBE_RFIFO_RQ", AR_RTR_PT_INQ_ERR_FLG_PBE_RFIFO_RQ_BP, AR_RTR_PT_INQ_ERR_FLG_PBE_RFIFO_RQ_EC },
    { "UFLW_ERR_RS_RFIFO", AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RS_RFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RS_RFIFO_EC },
    { "UFLW_ERR_RQ_RFIFO", AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RQ_RFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RQ_RFIFO_EC },
    { "UFLW_ERR_RS_OFIFO", AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RS_OFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RS_OFIFO_EC },
    { "UFLW_ERR_RQ_OFIFO", AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RQ_OFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RQ_OFIFO_EC },
    { "UFLW_ERR_RS_DFIFO", AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RS_DFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RS_DFIFO_EC },
    { "UFLW_ERR_RQ_DFIFO", AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RQ_DFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_UFLW_ERR_RQ_DFIFO_EC },
    { "OFLW_ERR_RS_RFIFO", AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RS_RFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RS_RFIFO_EC },
    { "OFLW_ERR_RQ_RFIFO", AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RQ_RFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RQ_RFIFO_EC },
    { "OFLW_ERR_RS_OFIFO", AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RS_OFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RS_OFIFO_EC },
    { "OFLW_ERR_RQ_OFIFO", AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RQ_OFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RQ_OFIFO_EC },
    { "OFLW_ERR_RS_DFIFO", AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RS_DFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RS_DFIFO_EC },
    { "OFLW_ERR_RQ_DFIFO", AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RQ_DFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_OFLW_ERR_RQ_DFIFO_EC },
    { "MBE_RS_DFIFO", AR_RTR_PT_INQ_ERR_FLG_MBE_RS_DFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_MBE_RS_DFIFO_EC },
    { "SBE_RS_DFIFO", AR_RTR_PT_INQ_ERR_FLG_SBE_RS_DFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_SBE_RS_DFIFO_EC },
    { "MBE_RQ_DFIFO", AR_RTR_PT_INQ_ERR_FLG_MBE_RQ_DFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_MBE_RQ_DFIFO_EC },
    { "SBE_RQ_DFIFO", AR_RTR_PT_INQ_ERR_FLG_SBE_RQ_DFIFO_BP, AR_RTR_PT_INQ_ERR_FLG_SBE_RQ_DFIFO_EC },
    { "DIAG_ONLY", AR_RTR_PT_INQ_ERR_FLG_DIAG_ONLY_BP, AR_RTR_PT_INQ_ERR_FLG_DIAG_ONLY_EC },
    { NULL, 0, 0 }
};
#endif
static const generic_mmrd_t _ar_rtr_pt_inq_err_clr_detail[] = {
    { "COLBUF_MAX_PKT_ERR", AR_RTR_PT_INQ_ERR_CLR_COLBUF_MAX_PKT_ERR_BP, AR_RTR_PT_INQ_ERR_CLR_COLBUF_MAX_PKT_ERR_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT5", AR_RTR_PT_INQ_ERR_CLR_COLBUF_OFLW_UFLW_ERR_INPUT5_BP, AR_RTR_PT_INQ_ERR_CLR_COLBUF_OFLW_UFLW_ERR_INPUT5_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT4", AR_RTR_PT_INQ_ERR_CLR_COLBUF_OFLW_UFLW_ERR_INPUT4_BP, AR_RTR_PT_INQ_ERR_CLR_COLBUF_OFLW_UFLW_ERR_INPUT4_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT3", AR_RTR_PT_INQ_ERR_CLR_COLBUF_OFLW_UFLW_ERR_INPUT3_BP, AR_RTR_PT_INQ_ERR_CLR_COLBUF_OFLW_UFLW_ERR_INPUT3_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT2", AR_RTR_PT_INQ_ERR_CLR_COLBUF_OFLW_UFLW_ERR_INPUT2_BP, AR_RTR_PT_INQ_ERR_CLR_COLBUF_OFLW_UFLW_ERR_INPUT2_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT1", AR_RTR_PT_INQ_ERR_CLR_COLBUF_OFLW_UFLW_ERR_INPUT1_BP, AR_RTR_PT_INQ_ERR_CLR_COLBUF_OFLW_UFLW_ERR_INPUT1_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT0", AR_RTR_PT_INQ_ERR_CLR_COLBUF_OFLW_UFLW_ERR_INPUT0_BP, AR_RTR_PT_INQ_ERR_CLR_COLBUF_OFLW_UFLW_ERR_INPUT0_MASK },
    { "SUBSWITCH_ERR", AR_RTR_PT_INQ_ERR_CLR_SUBSWITCH_ERR_BP, AR_RTR_PT_INQ_ERR_CLR_SUBSWITCH_ERR_MASK },
    { "LINK_ALIVE_TIMEOUT_ERR", AR_RTR_PT_INQ_ERR_CLR_LINK_ALIVE_TIMEOUT_ERR_BP, AR_RTR_PT_INQ_ERR_CLR_LINK_ALIVE_TIMEOUT_ERR_MASK },
    { "LINK_ALIVE_CHANNEL_ERR", AR_RTR_PT_INQ_ERR_CLR_LINK_ALIVE_CHANNEL_ERR_BP, AR_RTR_PT_INQ_ERR_CLR_LINK_ALIVE_CHANNEL_ERR_MASK },
    { "PRF_CNT_ROLLOVR_ERR", AR_RTR_PT_INQ_ERR_CLR_PRF_CNT_ROLLOVR_ERR_BP, AR_RTR_PT_INQ_ERR_CLR_PRF_CNT_ROLLOVR_ERR_MASK },
    { "MBE_RTABLE", AR_RTR_PT_INQ_ERR_CLR_MBE_RTABLE_BP, AR_RTR_PT_INQ_ERR_CLR_MBE_RTABLE_MASK },
    { "SBE_RTABLE", AR_RTR_PT_INQ_ERR_CLR_SBE_RTABLE_BP, AR_RTR_PT_INQ_ERR_CLR_SBE_RTABLE_MASK },
    { "ROUTE_ERROR", AR_RTR_PT_INQ_ERR_CLR_ROUTE_ERROR_BP, AR_RTR_PT_INQ_ERR_CLR_ROUTE_ERROR_MASK },
    { "PBE_VC_TABLE", AR_RTR_PT_INQ_ERR_CLR_PBE_VC_TABLE_BP, AR_RTR_PT_INQ_ERR_CLR_PBE_VC_TABLE_MASK },
    { "PBE_RFIFO_RS", AR_RTR_PT_INQ_ERR_CLR_PBE_RFIFO_RS_BP, AR_RTR_PT_INQ_ERR_CLR_PBE_RFIFO_RS_MASK },
    { "PBE_RFIFO_RQ", AR_RTR_PT_INQ_ERR_CLR_PBE_RFIFO_RQ_BP, AR_RTR_PT_INQ_ERR_CLR_PBE_RFIFO_RQ_MASK },
    { "UFLW_ERR_RS_RFIFO", AR_RTR_PT_INQ_ERR_CLR_UFLW_ERR_RS_RFIFO_BP, AR_RTR_PT_INQ_ERR_CLR_UFLW_ERR_RS_RFIFO_MASK },
    { "UFLW_ERR_RQ_RFIFO", AR_RTR_PT_INQ_ERR_CLR_UFLW_ERR_RQ_RFIFO_BP, AR_RTR_PT_INQ_ERR_CLR_UFLW_ERR_RQ_RFIFO_MASK },
    { "UFLW_ERR_RS_OFIFO", AR_RTR_PT_INQ_ERR_CLR_UFLW_ERR_RS_OFIFO_BP, AR_RTR_PT_INQ_ERR_CLR_UFLW_ERR_RS_OFIFO_MASK },
    { "UFLW_ERR_RQ_OFIFO", AR_RTR_PT_INQ_ERR_CLR_UFLW_ERR_RQ_OFIFO_BP, AR_RTR_PT_INQ_ERR_CLR_UFLW_ERR_RQ_OFIFO_MASK },
    { "UFLW_ERR_RS_DFIFO", AR_RTR_PT_INQ_ERR_CLR_UFLW_ERR_RS_DFIFO_BP, AR_RTR_PT_INQ_ERR_CLR_UFLW_ERR_RS_DFIFO_MASK },
    { "UFLW_ERR_RQ_DFIFO", AR_RTR_PT_INQ_ERR_CLR_UFLW_ERR_RQ_DFIFO_BP, AR_RTR_PT_INQ_ERR_CLR_UFLW_ERR_RQ_DFIFO_MASK },
    { "OFLW_ERR_RS_RFIFO", AR_RTR_PT_INQ_ERR_CLR_OFLW_ERR_RS_RFIFO_BP, AR_RTR_PT_INQ_ERR_CLR_OFLW_ERR_RS_RFIFO_MASK },
    { "OFLW_ERR_RQ_RFIFO", AR_RTR_PT_INQ_ERR_CLR_OFLW_ERR_RQ_RFIFO_BP, AR_RTR_PT_INQ_ERR_CLR_OFLW_ERR_RQ_RFIFO_MASK },
    { "OFLW_ERR_RS_OFIFO", AR_RTR_PT_INQ_ERR_CLR_OFLW_ERR_RS_OFIFO_BP, AR_RTR_PT_INQ_ERR_CLR_OFLW_ERR_RS_OFIFO_MASK },
    { "OFLW_ERR_RQ_OFIFO", AR_RTR_PT_INQ_ERR_CLR_OFLW_ERR_RQ_OFIFO_BP, AR_RTR_PT_INQ_ERR_CLR_OFLW_ERR_RQ_OFIFO_MASK },
    { "OFLW_ERR_RS_DFIFO", AR_RTR_PT_INQ_ERR_CLR_OFLW_ERR_RS_DFIFO_BP, AR_RTR_PT_INQ_ERR_CLR_OFLW_ERR_RS_DFIFO_MASK },
    { "OFLW_ERR_RQ_DFIFO", AR_RTR_PT_INQ_ERR_CLR_OFLW_ERR_RQ_DFIFO_BP, AR_RTR_PT_INQ_ERR_CLR_OFLW_ERR_RQ_DFIFO_MASK },
    { "MBE_RS_DFIFO", AR_RTR_PT_INQ_ERR_CLR_MBE_RS_DFIFO_BP, AR_RTR_PT_INQ_ERR_CLR_MBE_RS_DFIFO_MASK },
    { "SBE_RS_DFIFO", AR_RTR_PT_INQ_ERR_CLR_SBE_RS_DFIFO_BP, AR_RTR_PT_INQ_ERR_CLR_SBE_RS_DFIFO_MASK },
    { "MBE_RQ_DFIFO", AR_RTR_PT_INQ_ERR_CLR_MBE_RQ_DFIFO_BP, AR_RTR_PT_INQ_ERR_CLR_MBE_RQ_DFIFO_MASK },
    { "SBE_RQ_DFIFO", AR_RTR_PT_INQ_ERR_CLR_SBE_RQ_DFIFO_BP, AR_RTR_PT_INQ_ERR_CLR_SBE_RQ_DFIFO_MASK },
    { "DIAG_ONLY", AR_RTR_PT_INQ_ERR_CLR_DIAG_ONLY_BP, AR_RTR_PT_INQ_ERR_CLR_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_err_hss_msk_detail[] = {
    { "COLBUF_MAX_PKT_ERR", AR_RTR_PT_INQ_ERR_HSS_MSK_COLBUF_MAX_PKT_ERR_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_COLBUF_MAX_PKT_ERR_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT5", AR_RTR_PT_INQ_ERR_HSS_MSK_COLBUF_OFLW_UFLW_ERR_INPUT5_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_COLBUF_OFLW_UFLW_ERR_INPUT5_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT4", AR_RTR_PT_INQ_ERR_HSS_MSK_COLBUF_OFLW_UFLW_ERR_INPUT4_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_COLBUF_OFLW_UFLW_ERR_INPUT4_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT3", AR_RTR_PT_INQ_ERR_HSS_MSK_COLBUF_OFLW_UFLW_ERR_INPUT3_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_COLBUF_OFLW_UFLW_ERR_INPUT3_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT2", AR_RTR_PT_INQ_ERR_HSS_MSK_COLBUF_OFLW_UFLW_ERR_INPUT2_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_COLBUF_OFLW_UFLW_ERR_INPUT2_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT1", AR_RTR_PT_INQ_ERR_HSS_MSK_COLBUF_OFLW_UFLW_ERR_INPUT1_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_COLBUF_OFLW_UFLW_ERR_INPUT1_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT0", AR_RTR_PT_INQ_ERR_HSS_MSK_COLBUF_OFLW_UFLW_ERR_INPUT0_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_COLBUF_OFLW_UFLW_ERR_INPUT0_MASK },
    { "SUBSWITCH_ERR", AR_RTR_PT_INQ_ERR_HSS_MSK_SUBSWITCH_ERR_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_SUBSWITCH_ERR_MASK },
    { "LINK_ALIVE_TIMEOUT_ERR", AR_RTR_PT_INQ_ERR_HSS_MSK_LINK_ALIVE_TIMEOUT_ERR_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_LINK_ALIVE_TIMEOUT_ERR_MASK },
    { "LINK_ALIVE_CHANNEL_ERR", AR_RTR_PT_INQ_ERR_HSS_MSK_LINK_ALIVE_CHANNEL_ERR_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_LINK_ALIVE_CHANNEL_ERR_MASK },
    { "PRF_CNT_ROLLOVR_ERR", AR_RTR_PT_INQ_ERR_HSS_MSK_PRF_CNT_ROLLOVR_ERR_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_PRF_CNT_ROLLOVR_ERR_MASK },
    { "MBE_RTABLE", AR_RTR_PT_INQ_ERR_HSS_MSK_MBE_RTABLE_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_MBE_RTABLE_MASK },
    { "SBE_RTABLE", AR_RTR_PT_INQ_ERR_HSS_MSK_SBE_RTABLE_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_SBE_RTABLE_MASK },
    { "ROUTE_ERROR", AR_RTR_PT_INQ_ERR_HSS_MSK_ROUTE_ERROR_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_ROUTE_ERROR_MASK },
    { "PBE_VC_TABLE", AR_RTR_PT_INQ_ERR_HSS_MSK_PBE_VC_TABLE_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_PBE_VC_TABLE_MASK },
    { "PBE_RFIFO_RS", AR_RTR_PT_INQ_ERR_HSS_MSK_PBE_RFIFO_RS_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_PBE_RFIFO_RS_MASK },
    { "PBE_RFIFO_RQ", AR_RTR_PT_INQ_ERR_HSS_MSK_PBE_RFIFO_RQ_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_PBE_RFIFO_RQ_MASK },
    { "UFLW_ERR_RS_RFIFO", AR_RTR_PT_INQ_ERR_HSS_MSK_UFLW_ERR_RS_RFIFO_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_UFLW_ERR_RS_RFIFO_MASK },
    { "UFLW_ERR_RQ_RFIFO", AR_RTR_PT_INQ_ERR_HSS_MSK_UFLW_ERR_RQ_RFIFO_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_UFLW_ERR_RQ_RFIFO_MASK },
    { "UFLW_ERR_RS_OFIFO", AR_RTR_PT_INQ_ERR_HSS_MSK_UFLW_ERR_RS_OFIFO_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_UFLW_ERR_RS_OFIFO_MASK },
    { "UFLW_ERR_RQ_OFIFO", AR_RTR_PT_INQ_ERR_HSS_MSK_UFLW_ERR_RQ_OFIFO_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_UFLW_ERR_RQ_OFIFO_MASK },
    { "UFLW_ERR_RS_DFIFO", AR_RTR_PT_INQ_ERR_HSS_MSK_UFLW_ERR_RS_DFIFO_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_UFLW_ERR_RS_DFIFO_MASK },
    { "UFLW_ERR_RQ_DFIFO", AR_RTR_PT_INQ_ERR_HSS_MSK_UFLW_ERR_RQ_DFIFO_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_UFLW_ERR_RQ_DFIFO_MASK },
    { "OFLW_ERR_RS_RFIFO", AR_RTR_PT_INQ_ERR_HSS_MSK_OFLW_ERR_RS_RFIFO_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_OFLW_ERR_RS_RFIFO_MASK },
    { "OFLW_ERR_RQ_RFIFO", AR_RTR_PT_INQ_ERR_HSS_MSK_OFLW_ERR_RQ_RFIFO_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_OFLW_ERR_RQ_RFIFO_MASK },
    { "OFLW_ERR_RS_OFIFO", AR_RTR_PT_INQ_ERR_HSS_MSK_OFLW_ERR_RS_OFIFO_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_OFLW_ERR_RS_OFIFO_MASK },
    { "OFLW_ERR_RQ_OFIFO", AR_RTR_PT_INQ_ERR_HSS_MSK_OFLW_ERR_RQ_OFIFO_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_OFLW_ERR_RQ_OFIFO_MASK },
    { "OFLW_ERR_RS_DFIFO", AR_RTR_PT_INQ_ERR_HSS_MSK_OFLW_ERR_RS_DFIFO_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_OFLW_ERR_RS_DFIFO_MASK },
    { "OFLW_ERR_RQ_DFIFO", AR_RTR_PT_INQ_ERR_HSS_MSK_OFLW_ERR_RQ_DFIFO_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_OFLW_ERR_RQ_DFIFO_MASK },
    { "MBE_RS_DFIFO", AR_RTR_PT_INQ_ERR_HSS_MSK_MBE_RS_DFIFO_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_MBE_RS_DFIFO_MASK },
    { "SBE_RS_DFIFO", AR_RTR_PT_INQ_ERR_HSS_MSK_SBE_RS_DFIFO_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_SBE_RS_DFIFO_MASK },
    { "MBE_RQ_DFIFO", AR_RTR_PT_INQ_ERR_HSS_MSK_MBE_RQ_DFIFO_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_MBE_RQ_DFIFO_MASK },
    { "SBE_RQ_DFIFO", AR_RTR_PT_INQ_ERR_HSS_MSK_SBE_RQ_DFIFO_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_SBE_RQ_DFIFO_MASK },
    { "DIAG_ONLY", AR_RTR_PT_INQ_ERR_HSS_MSK_DIAG_ONLY_BP, AR_RTR_PT_INQ_ERR_HSS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_err_first_flg_detail[] = {
    { "COLBUF_MAX_PKT_ERR", AR_RTR_PT_INQ_ERR_FIRST_FLG_COLBUF_MAX_PKT_ERR_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_COLBUF_MAX_PKT_ERR_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT5", AR_RTR_PT_INQ_ERR_FIRST_FLG_COLBUF_OFLW_UFLW_ERR_INPUT5_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_COLBUF_OFLW_UFLW_ERR_INPUT5_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT4", AR_RTR_PT_INQ_ERR_FIRST_FLG_COLBUF_OFLW_UFLW_ERR_INPUT4_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_COLBUF_OFLW_UFLW_ERR_INPUT4_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT3", AR_RTR_PT_INQ_ERR_FIRST_FLG_COLBUF_OFLW_UFLW_ERR_INPUT3_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_COLBUF_OFLW_UFLW_ERR_INPUT3_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT2", AR_RTR_PT_INQ_ERR_FIRST_FLG_COLBUF_OFLW_UFLW_ERR_INPUT2_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_COLBUF_OFLW_UFLW_ERR_INPUT2_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT1", AR_RTR_PT_INQ_ERR_FIRST_FLG_COLBUF_OFLW_UFLW_ERR_INPUT1_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_COLBUF_OFLW_UFLW_ERR_INPUT1_MASK },
    { "COLBUF_OFLW_UFLW_ERR_INPUT0", AR_RTR_PT_INQ_ERR_FIRST_FLG_COLBUF_OFLW_UFLW_ERR_INPUT0_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_COLBUF_OFLW_UFLW_ERR_INPUT0_MASK },
    { "SUBSWITCH_ERR", AR_RTR_PT_INQ_ERR_FIRST_FLG_SUBSWITCH_ERR_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_SUBSWITCH_ERR_MASK },
    { "LINK_ALIVE_TIMEOUT_ERR", AR_RTR_PT_INQ_ERR_FIRST_FLG_LINK_ALIVE_TIMEOUT_ERR_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_LINK_ALIVE_TIMEOUT_ERR_MASK },
    { "LINK_ALIVE_CHANNEL_ERR", AR_RTR_PT_INQ_ERR_FIRST_FLG_LINK_ALIVE_CHANNEL_ERR_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_LINK_ALIVE_CHANNEL_ERR_MASK },
    { "PRF_CNT_ROLLOVR_ERR", AR_RTR_PT_INQ_ERR_FIRST_FLG_PRF_CNT_ROLLOVR_ERR_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_PRF_CNT_ROLLOVR_ERR_MASK },
    { "MBE_RTABLE", AR_RTR_PT_INQ_ERR_FIRST_FLG_MBE_RTABLE_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_MBE_RTABLE_MASK },
    { "SBE_RTABLE", AR_RTR_PT_INQ_ERR_FIRST_FLG_SBE_RTABLE_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_SBE_RTABLE_MASK },
    { "ROUTE_ERROR", AR_RTR_PT_INQ_ERR_FIRST_FLG_ROUTE_ERROR_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_ROUTE_ERROR_MASK },
    { "PBE_VC_TABLE", AR_RTR_PT_INQ_ERR_FIRST_FLG_PBE_VC_TABLE_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_PBE_VC_TABLE_MASK },
    { "PBE_RFIFO_RS", AR_RTR_PT_INQ_ERR_FIRST_FLG_PBE_RFIFO_RS_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_PBE_RFIFO_RS_MASK },
    { "PBE_RFIFO_RQ", AR_RTR_PT_INQ_ERR_FIRST_FLG_PBE_RFIFO_RQ_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_PBE_RFIFO_RQ_MASK },
    { "UFLW_ERR_RS_RFIFO", AR_RTR_PT_INQ_ERR_FIRST_FLG_UFLW_ERR_RS_RFIFO_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_UFLW_ERR_RS_RFIFO_MASK },
    { "UFLW_ERR_RQ_RFIFO", AR_RTR_PT_INQ_ERR_FIRST_FLG_UFLW_ERR_RQ_RFIFO_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_UFLW_ERR_RQ_RFIFO_MASK },
    { "UFLW_ERR_RS_OFIFO", AR_RTR_PT_INQ_ERR_FIRST_FLG_UFLW_ERR_RS_OFIFO_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_UFLW_ERR_RS_OFIFO_MASK },
    { "UFLW_ERR_RQ_OFIFO", AR_RTR_PT_INQ_ERR_FIRST_FLG_UFLW_ERR_RQ_OFIFO_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_UFLW_ERR_RQ_OFIFO_MASK },
    { "UFLW_ERR_RS_DFIFO", AR_RTR_PT_INQ_ERR_FIRST_FLG_UFLW_ERR_RS_DFIFO_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_UFLW_ERR_RS_DFIFO_MASK },
    { "UFLW_ERR_RQ_DFIFO", AR_RTR_PT_INQ_ERR_FIRST_FLG_UFLW_ERR_RQ_DFIFO_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_UFLW_ERR_RQ_DFIFO_MASK },
    { "OFLW_ERR_RS_RFIFO", AR_RTR_PT_INQ_ERR_FIRST_FLG_OFLW_ERR_RS_RFIFO_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_OFLW_ERR_RS_RFIFO_MASK },
    { "OFLW_ERR_RQ_RFIFO", AR_RTR_PT_INQ_ERR_FIRST_FLG_OFLW_ERR_RQ_RFIFO_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_OFLW_ERR_RQ_RFIFO_MASK },
    { "OFLW_ERR_RS_OFIFO", AR_RTR_PT_INQ_ERR_FIRST_FLG_OFLW_ERR_RS_OFIFO_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_OFLW_ERR_RS_OFIFO_MASK },
    { "OFLW_ERR_RQ_OFIFO", AR_RTR_PT_INQ_ERR_FIRST_FLG_OFLW_ERR_RQ_OFIFO_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_OFLW_ERR_RQ_OFIFO_MASK },
    { "OFLW_ERR_RS_DFIFO", AR_RTR_PT_INQ_ERR_FIRST_FLG_OFLW_ERR_RS_DFIFO_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_OFLW_ERR_RS_DFIFO_MASK },
    { "OFLW_ERR_RQ_DFIFO", AR_RTR_PT_INQ_ERR_FIRST_FLG_OFLW_ERR_RQ_DFIFO_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_OFLW_ERR_RQ_DFIFO_MASK },
    { "MBE_RS_DFIFO", AR_RTR_PT_INQ_ERR_FIRST_FLG_MBE_RS_DFIFO_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_MBE_RS_DFIFO_MASK },
    { "SBE_RS_DFIFO", AR_RTR_PT_INQ_ERR_FIRST_FLG_SBE_RS_DFIFO_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_SBE_RS_DFIFO_MASK },
    { "MBE_RQ_DFIFO", AR_RTR_PT_INQ_ERR_FIRST_FLG_MBE_RQ_DFIFO_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_MBE_RQ_DFIFO_MASK },
    { "SBE_RQ_DFIFO", AR_RTR_PT_INQ_ERR_FIRST_FLG_SBE_RQ_DFIFO_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_SBE_RQ_DFIFO_MASK },
    { "DIAG_ONLY", AR_RTR_PT_INQ_ERR_FIRST_FLG_DIAG_ONLY_BP, AR_RTR_PT_INQ_ERR_FIRST_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_dbg_errinj_rtable_detail[] = {
    { "ADDRESS", AR_RTR_PT_INQ_DBG_ERRINJ_RTABLE_ADDRESS_BP, AR_RTR_PT_INQ_DBG_ERRINJ_RTABLE_ADDRESS_MASK },
    { "CHECKBYTE", AR_RTR_PT_INQ_DBG_ERRINJ_RTABLE_CHECKBYTE_BP, AR_RTR_PT_INQ_DBG_ERRINJ_RTABLE_CHECKBYTE_MASK },
    { "RAMSELECT", AR_RTR_PT_INQ_DBG_ERRINJ_RTABLE_RAMSELECT_BP, AR_RTR_PT_INQ_DBG_ERRINJ_RTABLE_RAMSELECT_MASK },
    { "TRIGGERED", AR_RTR_PT_INQ_DBG_ERRINJ_RTABLE_TRIGGERED_BP, AR_RTR_PT_INQ_DBG_ERRINJ_RTABLE_TRIGGERED_MASK },
    { "MODE", AR_RTR_PT_INQ_DBG_ERRINJ_RTABLE_MODE_BP, AR_RTR_PT_INQ_DBG_ERRINJ_RTABLE_MODE_MASK },
    { "ENABLE", AR_RTR_PT_INQ_DBG_ERRINJ_RTABLE_ENABLE_BP, AR_RTR_PT_INQ_DBG_ERRINJ_RTABLE_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_err_info_rtable_detail[] = {
    { "MBE_RAM_NUM", AR_RTR_PT_INQ_ERR_INFO_RTABLE_MBE_RAM_NUM_BP, AR_RTR_PT_INQ_ERR_INFO_RTABLE_MBE_RAM_NUM_MASK },
    { "MBE_ADDRESS", AR_RTR_PT_INQ_ERR_INFO_RTABLE_MBE_ADDRESS_BP, AR_RTR_PT_INQ_ERR_INFO_RTABLE_MBE_ADDRESS_MASK },
    { "MBE_SYNDROME", AR_RTR_PT_INQ_ERR_INFO_RTABLE_MBE_SYNDROME_BP, AR_RTR_PT_INQ_ERR_INFO_RTABLE_MBE_SYNDROME_MASK },
    { "SBE_RAM_NUM", AR_RTR_PT_INQ_ERR_INFO_RTABLE_SBE_RAM_NUM_BP, AR_RTR_PT_INQ_ERR_INFO_RTABLE_SBE_RAM_NUM_MASK },
    { "SBE_ADDRESS", AR_RTR_PT_INQ_ERR_INFO_RTABLE_SBE_ADDRESS_BP, AR_RTR_PT_INQ_ERR_INFO_RTABLE_SBE_ADDRESS_MASK },
    { "SBE_SYNDROME", AR_RTR_PT_INQ_ERR_INFO_RTABLE_SBE_SYNDROME_BP, AR_RTR_PT_INQ_ERR_INFO_RTABLE_SBE_SYNDROME_MASK },
    { "MMR_DETECTED_MBE", AR_RTR_PT_INQ_ERR_INFO_RTABLE_MMR_DETECTED_MBE_BP, AR_RTR_PT_INQ_ERR_INFO_RTABLE_MMR_DETECTED_MBE_MASK },
    { "MMR_DETECTED_SBE", AR_RTR_PT_INQ_ERR_INFO_RTABLE_MMR_DETECTED_SBE_BP, AR_RTR_PT_INQ_ERR_INFO_RTABLE_MMR_DETECTED_SBE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_err_info_cnt_sbe_rtable_detail[] = {
    { "SBE_COUNT", AR_RTR_PT_INQ_ERR_INFO_CNT_SBE_RTABLE_SBE_COUNT_BP, AR_RTR_PT_INQ_ERR_INFO_CNT_SBE_RTABLE_SBE_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_err_info_cnt_mbe_rtable_detail[] = {
    { "MBE_COUNT", AR_RTR_PT_INQ_ERR_INFO_CNT_MBE_RTABLE_MBE_COUNT_BP, AR_RTR_PT_INQ_ERR_INFO_CNT_MBE_RTABLE_MBE_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_err_info_routing_detail[] = {
    { "ROUTE_ERR_TYPE", AR_RTR_PT_INQ_ERR_INFO_ROUTING_ROUTE_ERR_TYPE_BP, AR_RTR_PT_INQ_ERR_INFO_ROUTING_ROUTE_ERR_TYPE_MASK },
    { "RTABLE_ADDRESS", AR_RTR_PT_INQ_ERR_INFO_ROUTING_RTABLE_ADDRESS_BP, AR_RTR_PT_INQ_ERR_INFO_ROUTING_RTABLE_ADDRESS_MASK },
    { "ROUTE_TABLE", AR_RTR_PT_INQ_ERR_INFO_ROUTING_ROUTE_TABLE_BP, AR_RTR_PT_INQ_ERR_INFO_ROUTING_ROUTE_TABLE_MASK },
    { "ROUTE_HEAD", AR_RTR_PT_INQ_ERR_INFO_ROUTING_ROUTE_HEAD_BP, AR_RTR_PT_INQ_ERR_INFO_ROUTING_ROUTE_HEAD_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_dbg_errinj_req_rsp_detail[] = {
    { "CHECKBYTE", AR_RTR_PT_INQ_DBG_ERRINJ_REQ_RSP_CHECKBYTE_BP, AR_RTR_PT_INQ_DBG_ERRINJ_REQ_RSP_CHECKBYTE_MASK },
    { "PATH", AR_RTR_PT_INQ_DBG_ERRINJ_REQ_RSP_PATH_BP, AR_RTR_PT_INQ_DBG_ERRINJ_REQ_RSP_PATH_MASK },
    { "COUNT", AR_RTR_PT_INQ_DBG_ERRINJ_REQ_RSP_COUNT_BP, AR_RTR_PT_INQ_DBG_ERRINJ_REQ_RSP_COUNT_MASK },
    { "TRIGGERED", AR_RTR_PT_INQ_DBG_ERRINJ_REQ_RSP_TRIGGERED_BP, AR_RTR_PT_INQ_DBG_ERRINJ_REQ_RSP_TRIGGERED_MASK },
    { "MODE", AR_RTR_PT_INQ_DBG_ERRINJ_REQ_RSP_MODE_BP, AR_RTR_PT_INQ_DBG_ERRINJ_REQ_RSP_MODE_MASK },
    { "ENABLE", AR_RTR_PT_INQ_DBG_ERRINJ_REQ_RSP_ENABLE_BP, AR_RTR_PT_INQ_DBG_ERRINJ_REQ_RSP_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_err_info_cnt_sbe_req_detail[] = {
    { "SBE_COUNT", AR_RTR_PT_INQ_ERR_INFO_CNT_SBE_REQ_SBE_COUNT_BP, AR_RTR_PT_INQ_ERR_INFO_CNT_SBE_REQ_SBE_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_err_info_cnt_mbe_req_detail[] = {
    { "MBE_COUNT", AR_RTR_PT_INQ_ERR_INFO_CNT_MBE_REQ_MBE_COUNT_BP, AR_RTR_PT_INQ_ERR_INFO_CNT_MBE_REQ_MBE_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_err_info_cnt_sbe_rsp_detail[] = {
    { "SBE_COUNT", AR_RTR_PT_INQ_ERR_INFO_CNT_SBE_RSP_SBE_COUNT_BP, AR_RTR_PT_INQ_ERR_INFO_CNT_SBE_RSP_SBE_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_err_info_cnt_mbe_rsp_detail[] = {
    { "MBE_COUNT", AR_RTR_PT_INQ_ERR_INFO_CNT_MBE_RSP_MBE_COUNT_BP, AR_RTR_PT_INQ_ERR_INFO_CNT_MBE_RSP_MBE_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_incoming_flit_vc0_detail[] = {
    { "COUNT", AR_RTR_PT_INQ_PRF_INCOMING_FLIT_VC0_COUNT_BP, AR_RTR_PT_INQ_PRF_INCOMING_FLIT_VC0_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_incoming_flit_vc4_detail[] = {
    { "COUNT", AR_RTR_PT_INQ_PRF_INCOMING_FLIT_VC4_COUNT_BP, AR_RTR_PT_INQ_PRF_INCOMING_FLIT_VC4_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_flit0_filtering_setup_detail[] = {
    { "ENABLE", AR_RTR_PT_INQ_PRF_FLIT0_FILTERING_SETUP_ENABLE_BP, AR_RTR_PT_INQ_PRF_FLIT0_FILTERING_SETUP_ENABLE_MASK },
    { "FLIT_PTR", AR_RTR_PT_INQ_PRF_FLIT0_FILTERING_SETUP_FLIT_PTR_BP, AR_RTR_PT_INQ_PRF_FLIT0_FILTERING_SETUP_FLIT_PTR_MASK },
    { "COMPARE_PATTERN", AR_RTR_PT_INQ_PRF_FLIT0_FILTERING_SETUP_COMPARE_PATTERN_BP, AR_RTR_PT_INQ_PRF_FLIT0_FILTERING_SETUP_COMPARE_PATTERN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_flit0_filtering_mask_detail[] = {
    { "MASK", AR_RTR_PT_INQ_PRF_FLIT0_FILTERING_MASK_MASK_BP, AR_RTR_PT_INQ_PRF_FLIT0_FILTERING_MASK_MASK_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_flit1_filtering_setup_detail[] = {
    { "ENABLE", AR_RTR_PT_INQ_PRF_FLIT1_FILTERING_SETUP_ENABLE_BP, AR_RTR_PT_INQ_PRF_FLIT1_FILTERING_SETUP_ENABLE_MASK },
    { "FLIT_PTR", AR_RTR_PT_INQ_PRF_FLIT1_FILTERING_SETUP_FLIT_PTR_BP, AR_RTR_PT_INQ_PRF_FLIT1_FILTERING_SETUP_FLIT_PTR_MASK },
    { "COMPARE_PATTERN", AR_RTR_PT_INQ_PRF_FLIT1_FILTERING_SETUP_COMPARE_PATTERN_BP, AR_RTR_PT_INQ_PRF_FLIT1_FILTERING_SETUP_COMPARE_PATTERN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_flit1_filtering_mask_detail[] = {
    { "MASK", AR_RTR_PT_INQ_PRF_FLIT1_FILTERING_MASK_MASK_BP, AR_RTR_PT_INQ_PRF_FLIT1_FILTERING_MASK_MASK_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_flit2_filtering_setup_detail[] = {
    { "ENABLE", AR_RTR_PT_INQ_PRF_FLIT2_FILTERING_SETUP_ENABLE_BP, AR_RTR_PT_INQ_PRF_FLIT2_FILTERING_SETUP_ENABLE_MASK },
    { "FLIT_PTR", AR_RTR_PT_INQ_PRF_FLIT2_FILTERING_SETUP_FLIT_PTR_BP, AR_RTR_PT_INQ_PRF_FLIT2_FILTERING_SETUP_FLIT_PTR_MASK },
    { "COMPARE_PATTERN", AR_RTR_PT_INQ_PRF_FLIT2_FILTERING_SETUP_COMPARE_PATTERN_BP, AR_RTR_PT_INQ_PRF_FLIT2_FILTERING_SETUP_COMPARE_PATTERN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_flit2_filtering_mask_detail[] = {
    { "MASK", AR_RTR_PT_INQ_PRF_FLIT2_FILTERING_MASK_MASK_BP, AR_RTR_PT_INQ_PRF_FLIT2_FILTERING_MASK_MASK_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_flit3_filtering_setup_detail[] = {
    { "ENABLE", AR_RTR_PT_INQ_PRF_FLIT3_FILTERING_SETUP_ENABLE_BP, AR_RTR_PT_INQ_PRF_FLIT3_FILTERING_SETUP_ENABLE_MASK },
    { "FLIT_PTR", AR_RTR_PT_INQ_PRF_FLIT3_FILTERING_SETUP_FLIT_PTR_BP, AR_RTR_PT_INQ_PRF_FLIT3_FILTERING_SETUP_FLIT_PTR_MASK },
    { "COMPARE_PATTERN", AR_RTR_PT_INQ_PRF_FLIT3_FILTERING_SETUP_COMPARE_PATTERN_BP, AR_RTR_PT_INQ_PRF_FLIT3_FILTERING_SETUP_COMPARE_PATTERN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_flit3_filtering_mask_detail[] = {
    { "MASK", AR_RTR_PT_INQ_PRF_FLIT3_FILTERING_MASK_MASK_BP, AR_RTR_PT_INQ_PRF_FLIT3_FILTERING_MASK_MASK_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_flit4_filtering_setup_detail[] = {
    { "ENABLE", AR_RTR_PT_INQ_PRF_FLIT4_FILTERING_SETUP_ENABLE_BP, AR_RTR_PT_INQ_PRF_FLIT4_FILTERING_SETUP_ENABLE_MASK },
    { "FLIT_PTR", AR_RTR_PT_INQ_PRF_FLIT4_FILTERING_SETUP_FLIT_PTR_BP, AR_RTR_PT_INQ_PRF_FLIT4_FILTERING_SETUP_FLIT_PTR_MASK },
    { "COMPARE_PATTERN", AR_RTR_PT_INQ_PRF_FLIT4_FILTERING_SETUP_COMPARE_PATTERN_BP, AR_RTR_PT_INQ_PRF_FLIT4_FILTERING_SETUP_COMPARE_PATTERN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_flit4_filtering_mask_detail[] = {
    { "MASK", AR_RTR_PT_INQ_PRF_FLIT4_FILTERING_MASK_MASK_BP, AR_RTR_PT_INQ_PRF_FLIT4_FILTERING_MASK_MASK_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_flit5_filtering_setup_detail[] = {
    { "ENABLE", AR_RTR_PT_INQ_PRF_FLIT5_FILTERING_SETUP_ENABLE_BP, AR_RTR_PT_INQ_PRF_FLIT5_FILTERING_SETUP_ENABLE_MASK },
    { "FLIT_PTR", AR_RTR_PT_INQ_PRF_FLIT5_FILTERING_SETUP_FLIT_PTR_BP, AR_RTR_PT_INQ_PRF_FLIT5_FILTERING_SETUP_FLIT_PTR_MASK },
    { "COMPARE_PATTERN", AR_RTR_PT_INQ_PRF_FLIT5_FILTERING_SETUP_COMPARE_PATTERN_BP, AR_RTR_PT_INQ_PRF_FLIT5_FILTERING_SETUP_COMPARE_PATTERN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_flit5_filtering_mask_detail[] = {
    { "MASK", AR_RTR_PT_INQ_PRF_FLIT5_FILTERING_MASK_MASK_BP, AR_RTR_PT_INQ_PRF_FLIT5_FILTERING_MASK_MASK_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_flit6_filtering_setup_detail[] = {
    { "ENABLE", AR_RTR_PT_INQ_PRF_FLIT6_FILTERING_SETUP_ENABLE_BP, AR_RTR_PT_INQ_PRF_FLIT6_FILTERING_SETUP_ENABLE_MASK },
    { "FLIT_PTR", AR_RTR_PT_INQ_PRF_FLIT6_FILTERING_SETUP_FLIT_PTR_BP, AR_RTR_PT_INQ_PRF_FLIT6_FILTERING_SETUP_FLIT_PTR_MASK },
    { "COMPARE_PATTERN", AR_RTR_PT_INQ_PRF_FLIT6_FILTERING_SETUP_COMPARE_PATTERN_BP, AR_RTR_PT_INQ_PRF_FLIT6_FILTERING_SETUP_COMPARE_PATTERN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_flit6_filtering_mask_detail[] = {
    { "MASK", AR_RTR_PT_INQ_PRF_FLIT6_FILTERING_MASK_MASK_BP, AR_RTR_PT_INQ_PRF_FLIT6_FILTERING_MASK_MASK_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_flit7_filtering_setup_detail[] = {
    { "ENABLE", AR_RTR_PT_INQ_PRF_FLIT7_FILTERING_SETUP_ENABLE_BP, AR_RTR_PT_INQ_PRF_FLIT7_FILTERING_SETUP_ENABLE_MASK },
    { "FLIT_PTR", AR_RTR_PT_INQ_PRF_FLIT7_FILTERING_SETUP_FLIT_PTR_BP, AR_RTR_PT_INQ_PRF_FLIT7_FILTERING_SETUP_FLIT_PTR_MASK },
    { "COMPARE_PATTERN", AR_RTR_PT_INQ_PRF_FLIT7_FILTERING_SETUP_COMPARE_PATTERN_BP, AR_RTR_PT_INQ_PRF_FLIT7_FILTERING_SETUP_COMPARE_PATTERN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_flit7_filtering_mask_detail[] = {
    { "MASK", AR_RTR_PT_INQ_PRF_FLIT7_FILTERING_MASK_MASK_BP, AR_RTR_PT_INQ_PRF_FLIT7_FILTERING_MASK_MASK_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_incoming_pkt_vc0_filter_flit0_cnt_detail[] = {
    { "COUNT", AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC0_FILTER_FLIT0_CNT_COUNT_BP, AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC0_FILTER_FLIT0_CNT_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_incoming_pkt_vc1_filter_flit1_cnt_detail[] = {
    { "COUNT", AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC1_FILTER_FLIT1_CNT_COUNT_BP, AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC1_FILTER_FLIT1_CNT_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_incoming_pkt_vc2_filter_flit2_cnt_detail[] = {
    { "COUNT", AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC2_FILTER_FLIT2_CNT_COUNT_BP, AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC2_FILTER_FLIT2_CNT_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_incoming_pkt_vc3_filter_flit3_cnt_detail[] = {
    { "COUNT", AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC3_FILTER_FLIT3_CNT_COUNT_BP, AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC3_FILTER_FLIT3_CNT_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_incoming_pkt_vc4_filter_flit4_cnt_detail[] = {
    { "COUNT", AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC4_FILTER_FLIT4_CNT_COUNT_BP, AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC4_FILTER_FLIT4_CNT_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_incoming_pkt_vc5_filter_flit5_cnt_detail[] = {
    { "COUNT", AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC5_FILTER_FLIT5_CNT_COUNT_BP, AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC5_FILTER_FLIT5_CNT_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_incoming_pkt_vc6_filter_flit6_cnt_detail[] = {
    { "COUNT", AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC6_FILTER_FLIT6_CNT_COUNT_BP, AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC6_FILTER_FLIT6_CNT_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_incoming_pkt_vc7_filter_flit7_cnt_detail[] = {
    { "COUNT", AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC7_FILTER_FLIT7_CNT_COUNT_BP, AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC7_FILTER_FLIT7_CNT_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_match_flit_3_to_0_filtering_cnt_detail[] = {
    { "FLIT_CNT", AR_RTR_PT_INQ_PRF_MATCH_FLIT_3_TO_0_FILTERING_CNT_FLIT_CNT_BP, AR_RTR_PT_INQ_PRF_MATCH_FLIT_3_TO_0_FILTERING_CNT_FLIT_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_match_flit_7_to_4_filtering_cnt_detail[] = {
    { "FLIT_CNT", AR_RTR_PT_INQ_PRF_MATCH_FLIT_7_TO_4_FILTERING_CNT_FLIT_CNT_BP, AR_RTR_PT_INQ_PRF_MATCH_FLIT_7_TO_4_FILTERING_CNT_FLIT_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_req_rowbus_stall_cnt_detail[] = {
    { "COUNT", AR_RTR_PT_INQ_PRF_REQ_ROWBUS_STALL_CNT_COUNT_BP, AR_RTR_PT_INQ_PRF_REQ_ROWBUS_STALL_CNT_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_rsp_rowbus_stall_cnt_detail[] = {
    { "COUNT", AR_RTR_PT_INQ_PRF_RSP_ROWBUS_STALL_CNT_COUNT_BP, AR_RTR_PT_INQ_PRF_RSP_ROWBUS_STALL_CNT_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_rowbus_2x_usage_cnt_detail[] = {
    { "ROWBUS_2X_USAGE_CNT", AR_RTR_PT_INQ_PRF_ROWBUS_2X_USAGE_CNT_ROWBUS_2X_USAGE_CNT_BP, AR_RTR_PT_INQ_PRF_ROWBUS_2X_USAGE_CNT_ROWBUS_2X_USAGE_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_inq_prf_pkt_to_dead_link_cnt_detail[] = {
    { "PKT_TO_DEAD_LINK_CNT", AR_RTR_PT_INQ_PRF_PKT_TO_DEAD_LINK_CNT_PKT_TO_DEAD_LINK_CNT_BP, AR_RTR_PT_INQ_PRF_PKT_TO_DEAD_LINK_CNT_PKT_TO_DEAD_LINK_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_subswitch_cfg_colbuf_crdts_detail[] = {
    { "RD_CRDT_USED_CNT_VC7", AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC7_BP, AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC7_MASK },
    { "RD_CRDT_USED_CNT_VC6", AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC6_BP, AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC6_MASK },
    { "RD_CRDT_USED_CNT_VC5", AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC5_BP, AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC5_MASK },
    { "RD_CRDT_USED_CNT_VC4", AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC4_BP, AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC4_MASK },
    { "RD_CRDT_USED_CNT_VC3", AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC3_BP, AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC3_MASK },
    { "RD_CRDT_USED_CNT_VC2", AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC2_BP, AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC2_MASK },
    { "RD_CRDT_USED_CNT_VC1", AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC1_BP, AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC1_MASK },
    { "RD_CRDT_USED_CNT_VC0", AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC0_BP, AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_RD_CRDT_USED_CNT_VC0_MASK },
    { "WR_MAX_FLIT_CREDITS_EN", AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_WR_MAX_FLIT_CREDITS_EN_BP, AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_WR_MAX_FLIT_CREDITS_EN_MASK },
    { "WR_MAX_FLIT_CREDITS", AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_WR_MAX_FLIT_CREDITS_BP, AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_WR_MAX_FLIT_CREDITS_MASK },
    { "VC_NUMBER", AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_VC_NUMBER_BP, AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_VC_NUMBER_MASK },
    { "COLUMN_NUMBER", AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_COLUMN_NUMBER_BP, AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS_COLUMN_NUMBER_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_subswitch_err_info_detail[] = {
    { "ERR_MULTIPLE_SECT7", AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT7_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT7_MASK },
    { "ERR_TYPE_SECT7", AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT7_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT7_MASK },
    { "VC_SECT7", AR_RTR_PT_SUBSWITCH_ERR_INFO_VC_SECT7_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_VC_SECT7_MASK },
    { "ERR_MULTIPLE_SECT6", AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT6_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT6_MASK },
    { "ERR_TYPE_SECT6", AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT6_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT6_MASK },
    { "VC_SECT6", AR_RTR_PT_SUBSWITCH_ERR_INFO_VC_SECT6_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_VC_SECT6_MASK },
    { "ERR_MULTIPLE_SECT5", AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT5_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT5_MASK },
    { "ERR_TYPE_SECT5", AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT5_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT5_MASK },
    { "VC_SECT5", AR_RTR_PT_SUBSWITCH_ERR_INFO_VC_SECT5_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_VC_SECT5_MASK },
    { "ERR_MULTIPLE_SECT4", AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT4_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT4_MASK },
    { "ERR_TYPE_SECT4", AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT4_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT4_MASK },
    { "VC_SECT4", AR_RTR_PT_SUBSWITCH_ERR_INFO_VC_SECT4_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_VC_SECT4_MASK },
    { "ERR_MULTIPLE_SECT3", AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT3_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT3_MASK },
    { "ERR_TYPE_SECT3", AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT3_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT3_MASK },
    { "VC_SECT3", AR_RTR_PT_SUBSWITCH_ERR_INFO_VC_SECT3_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_VC_SECT3_MASK },
    { "ERR_MULTIPLE_SECT2", AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT2_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT2_MASK },
    { "ERR_TYPE_SECT2", AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT2_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT2_MASK },
    { "VC_SECT2", AR_RTR_PT_SUBSWITCH_ERR_INFO_VC_SECT2_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_VC_SECT2_MASK },
    { "ERR_MULTIPLE_SECT1", AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT1_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT1_MASK },
    { "ERR_TYPE_SECT1", AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT1_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT1_MASK },
    { "VC_SECT1", AR_RTR_PT_SUBSWITCH_ERR_INFO_VC_SECT1_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_VC_SECT1_MASK },
    { "ERR_MULTIPLE_SECT0", AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT0_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_MULTIPLE_SECT0_MASK },
    { "ERR_TYPE_SECT0", AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT0_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_ERR_TYPE_SECT0_MASK },
    { "VC_SECT0", AR_RTR_PT_SUBSWITCH_ERR_INFO_VC_SECT0_BP, AR_RTR_PT_SUBSWITCH_ERR_INFO_VC_SECT0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_subswitch_err_mask_detail[] = {
    { "MASK_CREDIT_UFLOW", AR_RTR_PT_SUBSWITCH_ERR_MASK_MASK_CREDIT_UFLOW_BP, AR_RTR_PT_SUBSWITCH_ERR_MASK_MASK_CREDIT_UFLOW_MASK },
    { "MASK_BUFFER_UFLOW", AR_RTR_PT_SUBSWITCH_ERR_MASK_MASK_BUFFER_UFLOW_BP, AR_RTR_PT_SUBSWITCH_ERR_MASK_MASK_BUFFER_UFLOW_MASK },
    { "MASK_BUFFER_OFLOW", AR_RTR_PT_SUBSWITCH_ERR_MASK_MASK_BUFFER_OFLOW_BP, AR_RTR_PT_SUBSWITCH_ERR_MASK_MASK_BUFFER_OFLOW_MASK },
    { "MASK_BAD_TVC_PT_ERR", AR_RTR_PT_SUBSWITCH_ERR_MASK_MASK_BAD_TVC_PT_ERR_BP, AR_RTR_PT_SUBSWITCH_ERR_MASK_MASK_BAD_TVC_PT_ERR_MASK },
    { "MASK_BAD_TVC_ERR", AR_RTR_PT_SUBSWITCH_ERR_MASK_MASK_BAD_TVC_ERR_BP, AR_RTR_PT_SUBSWITCH_ERR_MASK_MASK_BAD_TVC_ERR_MASK },
    { "MASK_EMPTY_ROUTE_ERR", AR_RTR_PT_SUBSWITCH_ERR_MASK_MASK_EMPTY_ROUTE_ERR_BP, AR_RTR_PT_SUBSWITCH_ERR_MASK_MASK_EMPTY_ROUTE_ERR_MASK },
    { "MASK_INVALID_ROUTE_ERR", AR_RTR_PT_SUBSWITCH_ERR_MASK_MASK_INVALID_ROUTE_ERR_BP, AR_RTR_PT_SUBSWITCH_ERR_MASK_MASK_INVALID_ROUTE_ERR_MASK },
    { "MASK_FLIT_ROUTE_HEAD_PARITY_ERR", AR_RTR_PT_SUBSWITCH_ERR_MASK_MASK_FLIT_ROUTE_HEAD_PARITY_ERR_BP, AR_RTR_PT_SUBSWITCH_ERR_MASK_MASK_FLIT_ROUTE_HEAD_PARITY_ERR_MASK },
    { "MASK_FLIT_ROUTE_IN_PARITY_ERR", AR_RTR_PT_SUBSWITCH_ERR_MASK_MASK_FLIT_ROUTE_IN_PARITY_ERR_BP, AR_RTR_PT_SUBSWITCH_ERR_MASK_MASK_FLIT_ROUTE_IN_PARITY_ERR_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_colbuf_cfg_crdts_channel_detail[] = {
    { "RSP_MAX_PKT_LENGTH", AR_RTR_PT_COLBUF_CFG_CRDTS_CHANNEL_RSP_MAX_PKT_LENGTH_BP, AR_RTR_PT_COLBUF_CFG_CRDTS_CHANNEL_RSP_MAX_PKT_LENGTH_MASK },
    { "REQ_MAX_PKT_LENGTH", AR_RTR_PT_COLBUF_CFG_CRDTS_CHANNEL_REQ_MAX_PKT_LENGTH_BP, AR_RTR_PT_COLBUF_CFG_CRDTS_CHANNEL_REQ_MAX_PKT_LENGTH_MASK },
    { "RSP_CRDT_LIMIT", AR_RTR_PT_COLBUF_CFG_CRDTS_CHANNEL_RSP_CRDT_LIMIT_BP, AR_RTR_PT_COLBUF_CFG_CRDTS_CHANNEL_RSP_CRDT_LIMIT_MASK },
    { "REQ_CRDT_LIMIT", AR_RTR_PT_COLBUF_CFG_CRDTS_CHANNEL_REQ_CRDT_LIMIT_BP, AR_RTR_PT_COLBUF_CFG_CRDTS_CHANNEL_REQ_CRDT_LIMIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_colbuf_err_info_detail[] = {
    { "SUPER_PACKET_RSP", AR_RTR_PT_COLBUF_ERR_INFO_SUPER_PACKET_RSP_BP, AR_RTR_PT_COLBUF_ERR_INFO_SUPER_PACKET_RSP_MASK },
    { "SUPER_PACKET_REQ", AR_RTR_PT_COLBUF_ERR_INFO_SUPER_PACKET_REQ_BP, AR_RTR_PT_COLBUF_ERR_INFO_SUPER_PACKET_REQ_MASK },
    { "SUPER_PACKET_FLIT_CNT", AR_RTR_PT_COLBUF_ERR_INFO_SUPER_PACKET_FLIT_CNT_BP, AR_RTR_PT_COLBUF_ERR_INFO_SUPER_PACKET_FLIT_CNT_MASK },
    { "UNDERFLOW_INPUT5", AR_RTR_PT_COLBUF_ERR_INFO_UNDERFLOW_INPUT5_BP, AR_RTR_PT_COLBUF_ERR_INFO_UNDERFLOW_INPUT5_MASK },
    { "OVERFLOW_INPUT5", AR_RTR_PT_COLBUF_ERR_INFO_OVERFLOW_INPUT5_BP, AR_RTR_PT_COLBUF_ERR_INFO_OVERFLOW_INPUT5_MASK },
    { "INPUT5_VC_PTR", AR_RTR_PT_COLBUF_ERR_INFO_INPUT5_VC_PTR_BP, AR_RTR_PT_COLBUF_ERR_INFO_INPUT5_VC_PTR_MASK },
    { "UNDERFLOW_INPUT4", AR_RTR_PT_COLBUF_ERR_INFO_UNDERFLOW_INPUT4_BP, AR_RTR_PT_COLBUF_ERR_INFO_UNDERFLOW_INPUT4_MASK },
    { "OVERFLOW_INPUT4", AR_RTR_PT_COLBUF_ERR_INFO_OVERFLOW_INPUT4_BP, AR_RTR_PT_COLBUF_ERR_INFO_OVERFLOW_INPUT4_MASK },
    { "INPUT4_VC_PTR", AR_RTR_PT_COLBUF_ERR_INFO_INPUT4_VC_PTR_BP, AR_RTR_PT_COLBUF_ERR_INFO_INPUT4_VC_PTR_MASK },
    { "UNDERFLOW_INPUT3", AR_RTR_PT_COLBUF_ERR_INFO_UNDERFLOW_INPUT3_BP, AR_RTR_PT_COLBUF_ERR_INFO_UNDERFLOW_INPUT3_MASK },
    { "OVERFLOW_INPUT3", AR_RTR_PT_COLBUF_ERR_INFO_OVERFLOW_INPUT3_BP, AR_RTR_PT_COLBUF_ERR_INFO_OVERFLOW_INPUT3_MASK },
    { "INPUT3_VC_PTR", AR_RTR_PT_COLBUF_ERR_INFO_INPUT3_VC_PTR_BP, AR_RTR_PT_COLBUF_ERR_INFO_INPUT3_VC_PTR_MASK },
    { "UNDERFLOW_INPUT2", AR_RTR_PT_COLBUF_ERR_INFO_UNDERFLOW_INPUT2_BP, AR_RTR_PT_COLBUF_ERR_INFO_UNDERFLOW_INPUT2_MASK },
    { "OVERFLOW_INPUT2", AR_RTR_PT_COLBUF_ERR_INFO_OVERFLOW_INPUT2_BP, AR_RTR_PT_COLBUF_ERR_INFO_OVERFLOW_INPUT2_MASK },
    { "INPUT2_VC_PTR", AR_RTR_PT_COLBUF_ERR_INFO_INPUT2_VC_PTR_BP, AR_RTR_PT_COLBUF_ERR_INFO_INPUT2_VC_PTR_MASK },
    { "UNDERFLOW_INPUT1", AR_RTR_PT_COLBUF_ERR_INFO_UNDERFLOW_INPUT1_BP, AR_RTR_PT_COLBUF_ERR_INFO_UNDERFLOW_INPUT1_MASK },
    { "OVERFLOW_INPUT1", AR_RTR_PT_COLBUF_ERR_INFO_OVERFLOW_INPUT1_BP, AR_RTR_PT_COLBUF_ERR_INFO_OVERFLOW_INPUT1_MASK },
    { "INPUT1_VC_PTR", AR_RTR_PT_COLBUF_ERR_INFO_INPUT1_VC_PTR_BP, AR_RTR_PT_COLBUF_ERR_INFO_INPUT1_VC_PTR_MASK },
    { "UNDERFLOW_INPUT0", AR_RTR_PT_COLBUF_ERR_INFO_UNDERFLOW_INPUT0_BP, AR_RTR_PT_COLBUF_ERR_INFO_UNDERFLOW_INPUT0_MASK },
    { "OVERFLOW_INPUT0", AR_RTR_PT_COLBUF_ERR_INFO_OVERFLOW_INPUT0_BP, AR_RTR_PT_COLBUF_ERR_INFO_OVERFLOW_INPUT0_MASK },
    { "INPUT0_VC_PTR", AR_RTR_PT_COLBUF_ERR_INFO_INPUT0_VC_PTR_BP, AR_RTR_PT_COLBUF_ERR_INFO_INPUT0_VC_PTR_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_colbuf_perf_stall_rq_detail[] = {
    { "COL_BUF_PERF_STALL_RQ", AR_RTR_PT_COLBUF_PERF_STALL_RQ_COL_BUF_PERF_STALL_RQ_BP, AR_RTR_PT_COLBUF_PERF_STALL_RQ_COL_BUF_PERF_STALL_RQ_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_rtr_pt_colbuf_perf_stall_rs_detail[] = {
    { "COL_BUF_PERF_STALL_RS", AR_RTR_PT_COLBUF_PERF_STALL_RS_COL_BUF_PERF_STALL_RS_BP, AR_RTR_PT_COLBUF_PERF_STALL_RS_COL_BUF_PERF_STALL_RS_MASK },
    { NULL, 0, 0 }
};

/*
 *  AR PT MMR DECLARATIONS
 */
static const generic_mmr_t _ar_rtr_pt_inq_cfg_degrade_diag = {
    "AR_RTR_PT_INQ_CFG_DEGRADE_DIAG", AR_RTR_PT_INQ_CFG_DEGRADE_DIAG, 8, 1, _ar_rtr_pt_inq_cfg_degrade_diag_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_cfg_fifo_rowbuf_crdt_limit = {
    "AR_RTR_PT_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT", AR_RTR_PT_INQ_CFG_FIFO_ROWBUF_CRDT_LIMIT, 8, 1, _ar_rtr_pt_inq_cfg_fifo_rowbuf_crdt_limit_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_cfg_fifo_rowbuf_crdts = {
    "AR_RTR_PT_INQ_CFG_FIFO_ROWBUF_CRDTS", AR_RTR_PT_INQ_CFG_FIFO_ROWBUF_CRDTS, 8, 1, _ar_rtr_pt_inq_cfg_fifo_rowbuf_crdts_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_cfg_route_pipe = {
    "AR_RTR_PT_INQ_CFG_ROUTE_PIPE", AR_RTR_PT_INQ_CFG_ROUTE_PIPE, 8, 1, _ar_rtr_pt_inq_cfg_route_pipe_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_cfg_vc_table = {
    "AR_RTR_PT_INQ_CFG_VC_TABLE", AR_RTR_PT_INQ_CFG_VC_TABLE, 8, 1, _ar_rtr_pt_inq_cfg_vc_table_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_cfg_link_alive_bits = {
    "AR_RTR_PT_INQ_CFG_LINK_ALIVE_BITS", AR_RTR_PT_INQ_CFG_LINK_ALIVE_BITS, 8, 1, _ar_rtr_pt_inq_cfg_link_alive_bits_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_cfg_congest_ctrl = {
    "AR_RTR_PT_INQ_CFG_CONGEST_CTRL", AR_RTR_PT_INQ_CFG_CONGEST_CTRL, 8, 1, _ar_rtr_pt_inq_cfg_congest_ctrl_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_cfg_init_vc_inject = {
    "AR_RTR_PT_INQ_CFG_INIT_VC_INJECT", AR_RTR_PT_INQ_CFG_INIT_VC_INJECT, 8, 1, _ar_rtr_pt_inq_cfg_init_vc_inject_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_err_flg = {
    "AR_RTR_PT_INQ_ERR_FLG", AR_RTR_PT_INQ_ERR_FLG, 8, 1, _ar_rtr_pt_inq_err_flg_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_err_clr = {
    "AR_RTR_PT_INQ_ERR_CLR", AR_RTR_PT_INQ_ERR_CLR, 8, 1, _ar_rtr_pt_inq_err_clr_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_err_hss_msk = {
    "AR_RTR_PT_INQ_ERR_HSS_MSK", AR_RTR_PT_INQ_ERR_HSS_MSK, 8, 1, _ar_rtr_pt_inq_err_hss_msk_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_err_first_flg = {
    "AR_RTR_PT_INQ_ERR_FIRST_FLG", AR_RTR_PT_INQ_ERR_FIRST_FLG, 8, 1, _ar_rtr_pt_inq_err_first_flg_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_dbg_errinj_rtable = {
    "AR_RTR_PT_INQ_DBG_ERRINJ_RTABLE", AR_RTR_PT_INQ_DBG_ERRINJ_RTABLE, 8, 1, _ar_rtr_pt_inq_dbg_errinj_rtable_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_err_info_rtable = {
    "AR_RTR_PT_INQ_ERR_INFO_RTABLE", AR_RTR_PT_INQ_ERR_INFO_RTABLE, 8, 1, _ar_rtr_pt_inq_err_info_rtable_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_err_info_cnt_sbe_rtable = {
    "AR_RTR_PT_INQ_ERR_INFO_CNT_SBE_RTABLE", AR_RTR_PT_INQ_ERR_INFO_CNT_SBE_RTABLE, 8, 1, _ar_rtr_pt_inq_err_info_cnt_sbe_rtable_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_err_info_cnt_mbe_rtable = {
    "AR_RTR_PT_INQ_ERR_INFO_CNT_MBE_RTABLE", AR_RTR_PT_INQ_ERR_INFO_CNT_MBE_RTABLE, 8, 1, _ar_rtr_pt_inq_err_info_cnt_mbe_rtable_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_err_info_routing = {
    "AR_RTR_PT_INQ_ERR_INFO_ROUTING", AR_RTR_PT_INQ_ERR_INFO_ROUTING, 8, 1, _ar_rtr_pt_inq_err_info_routing_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_dbg_errinj_req_rsp = {
    "AR_RTR_PT_INQ_DBG_ERRINJ_REQ_RSP", AR_RTR_PT_INQ_DBG_ERRINJ_REQ_RSP, 8, 1, _ar_rtr_pt_inq_dbg_errinj_req_rsp_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_err_info_cnt_sbe_req = {
    "AR_RTR_PT_INQ_ERR_INFO_CNT_SBE_REQ", AR_RTR_PT_INQ_ERR_INFO_CNT_SBE_REQ, 8, 1, _ar_rtr_pt_inq_err_info_cnt_sbe_req_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_err_info_cnt_mbe_req = {
    "AR_RTR_PT_INQ_ERR_INFO_CNT_MBE_REQ", AR_RTR_PT_INQ_ERR_INFO_CNT_MBE_REQ, 8, 1, _ar_rtr_pt_inq_err_info_cnt_mbe_req_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_err_info_cnt_sbe_rsp = {
    "AR_RTR_PT_INQ_ERR_INFO_CNT_SBE_RSP", AR_RTR_PT_INQ_ERR_INFO_CNT_SBE_RSP, 8, 1, _ar_rtr_pt_inq_err_info_cnt_sbe_rsp_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_err_info_cnt_mbe_rsp = {
    "AR_RTR_PT_INQ_ERR_INFO_CNT_MBE_RSP", AR_RTR_PT_INQ_ERR_INFO_CNT_MBE_RSP, 8, 1, _ar_rtr_pt_inq_err_info_cnt_mbe_rsp_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_incoming_flit_vc0 = {
    "AR_RTR_PT_INQ_PRF_INCOMING_FLIT_VC0", AR_RTR_PT_INQ_PRF_INCOMING_FLIT_VC0, 8, 1, _ar_rtr_pt_inq_prf_incoming_flit_vc0_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_incoming_flit_vc4 = {
    "AR_RTR_PT_INQ_PRF_INCOMING_FLIT_VC4", AR_RTR_PT_INQ_PRF_INCOMING_FLIT_VC4, 8, 1, _ar_rtr_pt_inq_prf_incoming_flit_vc4_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_flit0_filtering_setup = {
    "AR_RTR_PT_INQ_PRF_FLIT0_FILTERING_SETUP", AR_RTR_PT_INQ_PRF_FLIT0_FILTERING_SETUP, 8, 1, _ar_rtr_pt_inq_prf_flit0_filtering_setup_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_flit0_filtering_mask = {
    "AR_RTR_PT_INQ_PRF_FLIT0_FILTERING_MASK", AR_RTR_PT_INQ_PRF_FLIT0_FILTERING_MASK, 8, 1, _ar_rtr_pt_inq_prf_flit0_filtering_mask_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_flit1_filtering_setup = {
    "AR_RTR_PT_INQ_PRF_FLIT1_FILTERING_SETUP", AR_RTR_PT_INQ_PRF_FLIT1_FILTERING_SETUP, 8, 1, _ar_rtr_pt_inq_prf_flit1_filtering_setup_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_flit1_filtering_mask = {
    "AR_RTR_PT_INQ_PRF_FLIT1_FILTERING_MASK", AR_RTR_PT_INQ_PRF_FLIT1_FILTERING_MASK, 8, 1, _ar_rtr_pt_inq_prf_flit1_filtering_mask_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_flit2_filtering_setup = {
    "AR_RTR_PT_INQ_PRF_FLIT2_FILTERING_SETUP", AR_RTR_PT_INQ_PRF_FLIT2_FILTERING_SETUP, 8, 1, _ar_rtr_pt_inq_prf_flit2_filtering_setup_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_flit2_filtering_mask = {
    "AR_RTR_PT_INQ_PRF_FLIT2_FILTERING_MASK", AR_RTR_PT_INQ_PRF_FLIT2_FILTERING_MASK, 8, 1, _ar_rtr_pt_inq_prf_flit2_filtering_mask_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_flit3_filtering_setup = {
    "AR_RTR_PT_INQ_PRF_FLIT3_FILTERING_SETUP", AR_RTR_PT_INQ_PRF_FLIT3_FILTERING_SETUP, 8, 1, _ar_rtr_pt_inq_prf_flit3_filtering_setup_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_flit3_filtering_mask = {
    "AR_RTR_PT_INQ_PRF_FLIT3_FILTERING_MASK", AR_RTR_PT_INQ_PRF_FLIT3_FILTERING_MASK, 8, 1, _ar_rtr_pt_inq_prf_flit3_filtering_mask_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_flit4_filtering_setup = {
    "AR_RTR_PT_INQ_PRF_FLIT4_FILTERING_SETUP", AR_RTR_PT_INQ_PRF_FLIT4_FILTERING_SETUP, 8, 1, _ar_rtr_pt_inq_prf_flit4_filtering_setup_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_flit4_filtering_mask = {
    "AR_RTR_PT_INQ_PRF_FLIT4_FILTERING_MASK", AR_RTR_PT_INQ_PRF_FLIT4_FILTERING_MASK, 8, 1, _ar_rtr_pt_inq_prf_flit4_filtering_mask_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_flit5_filtering_setup = {
    "AR_RTR_PT_INQ_PRF_FLIT5_FILTERING_SETUP", AR_RTR_PT_INQ_PRF_FLIT5_FILTERING_SETUP, 8, 1, _ar_rtr_pt_inq_prf_flit5_filtering_setup_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_flit5_filtering_mask = {
    "AR_RTR_PT_INQ_PRF_FLIT5_FILTERING_MASK", AR_RTR_PT_INQ_PRF_FLIT5_FILTERING_MASK, 8, 1, _ar_rtr_pt_inq_prf_flit5_filtering_mask_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_flit6_filtering_setup = {
    "AR_RTR_PT_INQ_PRF_FLIT6_FILTERING_SETUP", AR_RTR_PT_INQ_PRF_FLIT6_FILTERING_SETUP, 8, 1, _ar_rtr_pt_inq_prf_flit6_filtering_setup_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_flit6_filtering_mask = {
    "AR_RTR_PT_INQ_PRF_FLIT6_FILTERING_MASK", AR_RTR_PT_INQ_PRF_FLIT6_FILTERING_MASK, 8, 1, _ar_rtr_pt_inq_prf_flit6_filtering_mask_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_flit7_filtering_setup = {
    "AR_RTR_PT_INQ_PRF_FLIT7_FILTERING_SETUP", AR_RTR_PT_INQ_PRF_FLIT7_FILTERING_SETUP, 8, 1, _ar_rtr_pt_inq_prf_flit7_filtering_setup_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_flit7_filtering_mask = {
    "AR_RTR_PT_INQ_PRF_FLIT7_FILTERING_MASK", AR_RTR_PT_INQ_PRF_FLIT7_FILTERING_MASK, 8, 1, _ar_rtr_pt_inq_prf_flit7_filtering_mask_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_incoming_pkt_vc0_filter_flit0_cnt = {
    "AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC0_FILTER_FLIT0_CNT", AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC0_FILTER_FLIT0_CNT, 8, 1, _ar_rtr_pt_inq_prf_incoming_pkt_vc0_filter_flit0_cnt_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_incoming_pkt_vc1_filter_flit1_cnt = {
    "AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC1_FILTER_FLIT1_CNT", AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC1_FILTER_FLIT1_CNT, 8, 1, _ar_rtr_pt_inq_prf_incoming_pkt_vc1_filter_flit1_cnt_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_incoming_pkt_vc2_filter_flit2_cnt = {
    "AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC2_FILTER_FLIT2_CNT", AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC2_FILTER_FLIT2_CNT, 8, 1, _ar_rtr_pt_inq_prf_incoming_pkt_vc2_filter_flit2_cnt_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_incoming_pkt_vc3_filter_flit3_cnt = {
    "AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC3_FILTER_FLIT3_CNT", AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC3_FILTER_FLIT3_CNT, 8, 1, _ar_rtr_pt_inq_prf_incoming_pkt_vc3_filter_flit3_cnt_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_incoming_pkt_vc4_filter_flit4_cnt = {
    "AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC4_FILTER_FLIT4_CNT", AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC4_FILTER_FLIT4_CNT, 8, 1, _ar_rtr_pt_inq_prf_incoming_pkt_vc4_filter_flit4_cnt_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_incoming_pkt_vc5_filter_flit5_cnt = {
    "AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC5_FILTER_FLIT5_CNT", AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC5_FILTER_FLIT5_CNT, 8, 1, _ar_rtr_pt_inq_prf_incoming_pkt_vc5_filter_flit5_cnt_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_incoming_pkt_vc6_filter_flit6_cnt = {
    "AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC6_FILTER_FLIT6_CNT", AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC6_FILTER_FLIT6_CNT, 8, 1, _ar_rtr_pt_inq_prf_incoming_pkt_vc6_filter_flit6_cnt_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_incoming_pkt_vc7_filter_flit7_cnt = {
    "AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC7_FILTER_FLIT7_CNT", AR_RTR_PT_INQ_PRF_INCOMING_PKT_VC7_FILTER_FLIT7_CNT, 8, 1, _ar_rtr_pt_inq_prf_incoming_pkt_vc7_filter_flit7_cnt_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_match_flit_3_to_0_filtering_cnt = {
    "AR_RTR_PT_INQ_PRF_MATCH_FLIT_3_TO_0_FILTERING_CNT", AR_RTR_PT_INQ_PRF_MATCH_FLIT_3_TO_0_FILTERING_CNT, 8, 1, _ar_rtr_pt_inq_prf_match_flit_3_to_0_filtering_cnt_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_match_flit_7_to_4_filtering_cnt = {
    "AR_RTR_PT_INQ_PRF_MATCH_FLIT_7_TO_4_FILTERING_CNT", AR_RTR_PT_INQ_PRF_MATCH_FLIT_7_TO_4_FILTERING_CNT, 8, 1, _ar_rtr_pt_inq_prf_match_flit_7_to_4_filtering_cnt_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_req_rowbus_stall_cnt = {
    "AR_RTR_PT_INQ_PRF_REQ_ROWBUS_STALL_CNT", AR_RTR_PT_INQ_PRF_REQ_ROWBUS_STALL_CNT, 8, 1, _ar_rtr_pt_inq_prf_req_rowbus_stall_cnt_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_rsp_rowbus_stall_cnt = {
    "AR_RTR_PT_INQ_PRF_RSP_ROWBUS_STALL_CNT", AR_RTR_PT_INQ_PRF_RSP_ROWBUS_STALL_CNT, 8, 1, _ar_rtr_pt_inq_prf_rsp_rowbus_stall_cnt_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_rowbus_2x_usage_cnt = {
    "AR_RTR_PT_INQ_PRF_ROWBUS_2X_USAGE_CNT", AR_RTR_PT_INQ_PRF_ROWBUS_2X_USAGE_CNT, 8, 1, _ar_rtr_pt_inq_prf_rowbus_2x_usage_cnt_detail
};
static const generic_mmr_t _ar_rtr_pt_inq_prf_pkt_to_dead_link_cnt = {
    "AR_RTR_PT_INQ_PRF_PKT_TO_DEAD_LINK_CNT", AR_RTR_PT_INQ_PRF_PKT_TO_DEAD_LINK_CNT, 8, 1, _ar_rtr_pt_inq_prf_pkt_to_dead_link_cnt_detail
};
static const generic_mmr_t _ar_rtr_pt_subswitch_cfg_colbuf_crdts = {
    "AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS", AR_RTR_PT_SUBSWITCH_CFG_COLBUF_CRDTS, 8, 1, _ar_rtr_pt_subswitch_cfg_colbuf_crdts_detail
};
static const generic_mmr_t _ar_rtr_pt_subswitch_err_info = {
    "AR_RTR_PT_SUBSWITCH_ERR_INFO", AR_RTR_PT_SUBSWITCH_ERR_INFO, 8, 1, _ar_rtr_pt_subswitch_err_info_detail
};
static const generic_mmr_t _ar_rtr_pt_subswitch_err_mask = {
    "AR_RTR_PT_SUBSWITCH_ERR_MASK", AR_RTR_PT_SUBSWITCH_ERR_MASK, 8, 1, _ar_rtr_pt_subswitch_err_mask_detail
};
static const generic_mmr_t _ar_rtr_pt_colbuf_cfg_crdts_channel = {
    "AR_RTR_PT_COLBUF_CFG_CRDTS_CHANNEL", AR_RTR_PT_COLBUF_CFG_CRDTS_CHANNEL, 8, 1, _ar_rtr_pt_colbuf_cfg_crdts_channel_detail
};
static const generic_mmr_t _ar_rtr_pt_colbuf_err_info = {
    "AR_RTR_PT_COLBUF_ERR_INFO", AR_RTR_PT_COLBUF_ERR_INFO, 8, 1, _ar_rtr_pt_colbuf_err_info_detail
};
static const generic_mmr_t _ar_rtr_pt_colbuf_perf_stall_rq = {
    "AR_RTR_PT_COLBUF_PERF_STALL_RQ", AR_RTR_PT_COLBUF_PERF_STALL_RQ, 8, 1, _ar_rtr_pt_colbuf_perf_stall_rq_detail
};
static const generic_mmr_t _ar_rtr_pt_colbuf_perf_stall_rs = {
    "AR_RTR_PT_COLBUF_PERF_STALL_RS", AR_RTR_PT_COLBUF_PERF_STALL_RS, 8, 1, _ar_rtr_pt_colbuf_perf_stall_rs_detail
};

/*
 *  INSTALL AR PT MMRS
 */
static const generic_mmr_t* _ar_pt_mmrs[] _unused = {
    &_ar_rtr_pt_inq_cfg_degrade_diag,
    &_ar_rtr_pt_inq_cfg_fifo_rowbuf_crdt_limit,
    &_ar_rtr_pt_inq_cfg_fifo_rowbuf_crdts,
    &_ar_rtr_pt_inq_cfg_route_pipe,
    &_ar_rtr_pt_inq_cfg_vc_table,
    &_ar_rtr_pt_inq_cfg_link_alive_bits,
    &_ar_rtr_pt_inq_cfg_congest_ctrl,
    &_ar_rtr_pt_inq_cfg_init_vc_inject,
    &_ar_rtr_pt_inq_err_flg,
    &_ar_rtr_pt_inq_err_clr,
    &_ar_rtr_pt_inq_err_hss_msk,
    &_ar_rtr_pt_inq_err_first_flg,
    &_ar_rtr_pt_inq_dbg_errinj_rtable,
    &_ar_rtr_pt_inq_err_info_rtable,
    &_ar_rtr_pt_inq_err_info_cnt_sbe_rtable,
    &_ar_rtr_pt_inq_err_info_cnt_mbe_rtable,
    &_ar_rtr_pt_inq_err_info_routing,
    &_ar_rtr_pt_inq_dbg_errinj_req_rsp,
    &_ar_rtr_pt_inq_err_info_cnt_sbe_req,
    &_ar_rtr_pt_inq_err_info_cnt_mbe_req,
    &_ar_rtr_pt_inq_err_info_cnt_sbe_rsp,
    &_ar_rtr_pt_inq_err_info_cnt_mbe_rsp,
    &_ar_rtr_pt_inq_prf_incoming_flit_vc0,
    &_ar_rtr_pt_inq_prf_incoming_flit_vc4,
    &_ar_rtr_pt_inq_prf_flit0_filtering_setup,
    &_ar_rtr_pt_inq_prf_flit0_filtering_mask,
    &_ar_rtr_pt_inq_prf_flit1_filtering_setup,
    &_ar_rtr_pt_inq_prf_flit1_filtering_mask,
    &_ar_rtr_pt_inq_prf_flit2_filtering_setup,
    &_ar_rtr_pt_inq_prf_flit2_filtering_mask,
    &_ar_rtr_pt_inq_prf_flit3_filtering_setup,
    &_ar_rtr_pt_inq_prf_flit3_filtering_mask,
    &_ar_rtr_pt_inq_prf_flit4_filtering_setup,
    &_ar_rtr_pt_inq_prf_flit4_filtering_mask,
    &_ar_rtr_pt_inq_prf_flit5_filtering_setup,
    &_ar_rtr_pt_inq_prf_flit5_filtering_mask,
    &_ar_rtr_pt_inq_prf_flit6_filtering_setup,
    &_ar_rtr_pt_inq_prf_flit6_filtering_mask,
    &_ar_rtr_pt_inq_prf_flit7_filtering_setup,
    &_ar_rtr_pt_inq_prf_flit7_filtering_mask,
    &_ar_rtr_pt_inq_prf_incoming_pkt_vc0_filter_flit0_cnt,
    &_ar_rtr_pt_inq_prf_incoming_pkt_vc1_filter_flit1_cnt,
    &_ar_rtr_pt_inq_prf_incoming_pkt_vc2_filter_flit2_cnt,
    &_ar_rtr_pt_inq_prf_incoming_pkt_vc3_filter_flit3_cnt,
    &_ar_rtr_pt_inq_prf_incoming_pkt_vc4_filter_flit4_cnt,
    &_ar_rtr_pt_inq_prf_incoming_pkt_vc5_filter_flit5_cnt,
    &_ar_rtr_pt_inq_prf_incoming_pkt_vc6_filter_flit6_cnt,
    &_ar_rtr_pt_inq_prf_incoming_pkt_vc7_filter_flit7_cnt,
    &_ar_rtr_pt_inq_prf_match_flit_3_to_0_filtering_cnt,
    &_ar_rtr_pt_inq_prf_match_flit_7_to_4_filtering_cnt,
    &_ar_rtr_pt_inq_prf_req_rowbus_stall_cnt,
    &_ar_rtr_pt_inq_prf_rsp_rowbus_stall_cnt,
    &_ar_rtr_pt_inq_prf_rowbus_2x_usage_cnt,
    &_ar_rtr_pt_inq_prf_pkt_to_dead_link_cnt,
    &_ar_rtr_pt_subswitch_cfg_colbuf_crdts,
    &_ar_rtr_pt_subswitch_err_info,
    &_ar_rtr_pt_subswitch_err_mask,
    &_ar_rtr_pt_colbuf_cfg_crdts_channel,
    &_ar_rtr_pt_colbuf_err_info,
    &_ar_rtr_pt_colbuf_perf_stall_rq,
    &_ar_rtr_pt_colbuf_perf_stall_rs,
    NULL
};

#endif
