/******************************************************************************
 * COPYRIGHT CRAY INC. ar_rmt_mmrs_h.h
 * FILE: ar_rmt_mmrs_h.h
 * Created by v2h.c on Wed Oct  8 14:39:03 2014
 ******************************************************************************/

#ifndef _AR_RMT_MMRS_H_H_
#define _AR_RMT_MMRS_H_H_

#ifdef __GNUC__
#define _unused __attribute__((unused))
#else
#define _unused
#endif

#ifndef _GENERIC_MMRD_T_
#define _GENERIC_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint64_t _mask;		/* Field bit mask */
} generic_mmrd_t;
#endif

#ifndef _ERRCAT_MMRD_T_
#define _ERRCAT_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint32_t _ec;		/* Field error category */
} errcat_mmrd_t;
#endif

#ifndef _GENERIC_MMR_T_
#define _GENERIC_MMR_T_
typedef struct {
	char* _name;		/* MMR name */
	uint64_t _addr;		/* MMR address */
	int _size;		/* Size in bytes of MMR */
	int _depth;		/* Number of MMR instances */
	const generic_mmrd_t *_info;	/* MMR detail */
} generic_mmr_t;
#endif

static const generic_mmr_t* _ar_rmt_mmrs[] _unused;	/* RMT Array */

/*
 *  AR RMT MMR DETAIL DECLARATIONS
 */
static const generic_mmrd_t _ar_nic_rmt_rmt_mmr_ring_0_hi_rmt_detail[] = {
    { "UNUSED_145_35", AR_NIC_RMT_RMT_MMR_RING_0_HI_RMT_UNUSED_145_35_BP, AR_NIC_RMT_RMT_MMR_RING_0_HI_RMT_UNUSED_145_35_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_rmt_mmr_ring_0_mid_rmt_detail[] = {
    { "UNUSED_127_104", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_UNUSED_127_104_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_UNUSED_127_104_MASK },
    { "CNTR_ABORTS", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_ABORTS_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_ABORTS_MASK },
    { "CNTR_SEND_TIMEOUTS", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_SEND_TIMEOUTS_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_SEND_TIMEOUTS_MASK },
    { "CNTR_SEND_MBE_EVICTS", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_SEND_MBE_EVICTS_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_SEND_MBE_EVICTS_MASK },
    { "CNTR_SEND_CAM_HITS", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_SEND_CAM_HITS_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_SEND_CAM_HITS_MASK },
    { "CNTR_SEND_CAM_EVICTS", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_SEND_CAM_EVICTS_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_SEND_CAM_EVICTS_MASK },
    { "CNTR_SEND_CAM_MISSES", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_SEND_CAM_MISSES_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_SEND_CAM_MISSES_MASK },
    { "CNTR_SEND_CAM_FILLS", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_SEND_CAM_FILLS_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_SEND_CAM_FILLS_MASK },
    { "CNTR_RCV_COMPLETES", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_RCV_COMPLETES_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_RCV_COMPLETES_MASK },
    { "CNTR_PUT_TIMEOUTS", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_PUT_TIMEOUTS_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_PUT_TIMEOUTS_MASK },
    { "CNTR_PUT_MBE_EVICTS", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_PUT_MBE_EVICTS_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_PUT_MBE_EVICTS_MASK },
    { "CNTR_PUT_CAM_HITS", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_PUT_CAM_HITS_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_PUT_CAM_HITS_MASK },
    { "CNTR_PUT_CAM_EVICTS", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_PUT_CAM_EVICTS_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_PUT_CAM_EVICTS_MASK },
    { "CNTR_PUT_CAM_MISSES", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_PUT_CAM_MISSES_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_PUT_CAM_MISSES_MASK },
    { "CNTR_PUT_CAM_FILLS", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_PUT_CAM_FILLS_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_PUT_CAM_FILLS_MASK },
    { "CNTR_UNDELIVERABLE_CQE", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_UNDELIVERABLE_CQE_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_UNDELIVERABLE_CQE_MASK },
    { "CNTR_DESC_TBL_MBE", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_DESC_TBL_MBE_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_DESC_TBL_MBE_MASK },
    { "CNTR_DESC_TBL_SBE", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_DESC_TBL_SBE_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_DESC_TBL_SBE_MASK },
    { "CNTR_SEQ_TBL_MBE", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_SEQ_TBL_MBE_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_SEQ_TBL_MBE_MASK },
    { "CNTR_SEQ_TBL_SBE", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_SEQ_TBL_SBE_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_SEQ_TBL_SBE_MASK },
    { "CNTR_PAYLOAD_MBE", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_PAYLOAD_MBE_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_PAYLOAD_MBE_MASK },
    { "CNTR_PAYLOAD_SBE", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_PAYLOAD_SBE_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_PAYLOAD_SBE_MASK },
    { "CNTR_INQ_PARITY", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_INQ_PARITY_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_CNTR_INQ_PARITY_MASK },
    { "UNUSED_81_64", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_UNUSED_81_64_BP, AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT_UNUSED_81_64_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_rmt_mmr_ring_0_lo_rmt_detail[] = {
    { "UNUSED_145_35", AR_NIC_RMT_RMT_MMR_RING_0_LO_RMT_UNUSED_145_35_BP, AR_NIC_RMT_RMT_MMR_RING_0_LO_RMT_UNUSED_145_35_MASK },
    { "OS_IRQ", AR_NIC_RMT_RMT_MMR_RING_0_LO_RMT_OS_IRQ_BP, AR_NIC_RMT_RMT_MMR_RING_0_LO_RMT_OS_IRQ_MASK },
    { "HSS_IRQ", AR_NIC_RMT_RMT_MMR_RING_0_LO_RMT_HSS_IRQ_BP, AR_NIC_RMT_RMT_MMR_RING_0_LO_RMT_HSS_IRQ_MASK },
    { "R_Q_LB_WR_ACK", AR_NIC_RMT_RMT_MMR_RING_0_LO_RMT_R_Q_LB_WR_ACK_BP, AR_NIC_RMT_RMT_MMR_RING_0_LO_RMT_R_Q_LB_WR_ACK_MASK },
    { "R_Q_LB_RSP", AR_NIC_RMT_RMT_MMR_RING_0_LO_RMT_R_Q_LB_RSP_BP, AR_NIC_RMT_RMT_MMR_RING_0_LO_RMT_R_Q_LB_RSP_MASK },
    { "I_LB_REQ", AR_NIC_RMT_RMT_MMR_RING_0_LO_RMT_I_LB_REQ_BP, AR_NIC_RMT_RMT_MMR_RING_0_LO_RMT_I_LB_REQ_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_err_flg_1_hi_rmt_detail[] = {
    { "UNUSED_145_128", AR_NIC_RMT_ERR_FLG_1_HI_RMT_UNUSED_145_128_BP, AR_NIC_RMT_ERR_FLG_1_HI_RMT_UNUSED_145_128_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_err_flg_1_mid_rmt_detail[] = {
    { "UNUSED_127_93", AR_NIC_RMT_ERR_FLG_1_MID_RMT_UNUSED_127_93_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_UNUSED_127_93_MASK },
    { "STALL_DROPPED", AR_NIC_RMT_ERR_FLG_1_MID_RMT_STALL_DROPPED_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_STALL_DROPPED_MASK },
    { "BTECH3_NO_DESC", AR_NIC_RMT_ERR_FLG_1_MID_RMT_BTECH3_NO_DESC_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_BTECH3_NO_DESC_MASK },
    { "BTECH3_LAST_DESC", AR_NIC_RMT_ERR_FLG_1_MID_RMT_BTECH3_LAST_DESC_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_BTECH3_LAST_DESC_MASK },
    { "BTECH2_NO_DESC", AR_NIC_RMT_ERR_FLG_1_MID_RMT_BTECH2_NO_DESC_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_BTECH2_NO_DESC_MASK },
    { "BTECH2_LAST_DESC", AR_NIC_RMT_ERR_FLG_1_MID_RMT_BTECH2_LAST_DESC_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_BTECH2_LAST_DESC_MASK },
    { "BTECH1_NO_DESC", AR_NIC_RMT_ERR_FLG_1_MID_RMT_BTECH1_NO_DESC_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_BTECH1_NO_DESC_MASK },
    { "BTECH1_LAST_DESC", AR_NIC_RMT_ERR_FLG_1_MID_RMT_BTECH1_LAST_DESC_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_BTECH1_LAST_DESC_MASK },
    { "BTECH0_NO_DESC", AR_NIC_RMT_ERR_FLG_1_MID_RMT_BTECH0_NO_DESC_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_BTECH0_NO_DESC_MASK },
    { "BTECH0_LAST_DESC", AR_NIC_RMT_ERR_FLG_1_MID_RMT_BTECH0_LAST_DESC_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_BTECH0_LAST_DESC_MASK },
    { "DSMN_CAM_PARITY", AR_NIC_RMT_ERR_FLG_1_MID_RMT_DSMN_CAM_PARITY_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_DSMN_CAM_PARITY_MASK },
    { "SEND_CAM_PARITY", AR_NIC_RMT_ERR_FLG_1_MID_RMT_SEND_CAM_PARITY_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_SEND_CAM_PARITY_MASK },
    { "DSMN_TIMEOUT", AR_NIC_RMT_ERR_FLG_1_MID_RMT_DSMN_TIMEOUT_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_DSMN_TIMEOUT_MASK },
    { "SEND_TIMEOUT", AR_NIC_RMT_ERR_FLG_1_MID_RMT_SEND_TIMEOUT_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_SEND_TIMEOUT_MASK },
    { "RX_OVERRUN", AR_NIC_RMT_ERR_FLG_1_MID_RMT_RX_OVERRUN_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_RX_OVERRUN_MASK },
    { "RX_SEND_CAM_MISS", AR_NIC_RMT_ERR_FLG_1_MID_RMT_RX_SEND_CAM_MISS_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_RX_SEND_CAM_MISS_MASK },
    { "RX_BTECH_UNAVAILABLE", AR_NIC_RMT_ERR_FLG_1_MID_RMT_RX_BTECH_UNAVAILABLE_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_RX_BTECH_UNAVAILABLE_MASK },
    { "RX_DESC_BTECH_INV", AR_NIC_RMT_ERR_FLG_1_MID_RMT_RX_DESC_BTECH_INV_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_RX_DESC_BTECH_INV_MASK },
    { "UNDELIVERABLE_CQE", AR_NIC_RMT_ERR_FLG_1_MID_RMT_UNDELIVERABLE_CQE_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_UNDELIVERABLE_CQE_MASK },
    { "MALFORMED_PKT", AR_NIC_RMT_ERR_FLG_1_MID_RMT_MALFORMED_PKT_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_MALFORMED_PKT_MASK },
    { "DESC_TBL_MBE", AR_NIC_RMT_ERR_FLG_1_MID_RMT_DESC_TBL_MBE_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_DESC_TBL_MBE_MASK },
    { "DESC_TBL_SBE", AR_NIC_RMT_ERR_FLG_1_MID_RMT_DESC_TBL_SBE_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_DESC_TBL_SBE_MASK },
    { "SEQ_TBL_MBE", AR_NIC_RMT_ERR_FLG_1_MID_RMT_SEQ_TBL_MBE_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_SEQ_TBL_MBE_MASK },
    { "SEQ_TBL_SBE", AR_NIC_RMT_ERR_FLG_1_MID_RMT_SEQ_TBL_SBE_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_SEQ_TBL_SBE_MASK },
    { "PROTOCOL_ERR", AR_NIC_RMT_ERR_FLG_1_MID_RMT_PROTOCOL_ERR_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_PROTOCOL_ERR_MASK },
    { "PAYLOAD_MBE_DROP", AR_NIC_RMT_ERR_FLG_1_MID_RMT_PAYLOAD_MBE_DROP_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_PAYLOAD_MBE_DROP_MASK },
    { "PAYLOAD_MBE", AR_NIC_RMT_ERR_FLG_1_MID_RMT_PAYLOAD_MBE_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_PAYLOAD_MBE_MASK },
    { "PAYLOAD_SBE", AR_NIC_RMT_ERR_FLG_1_MID_RMT_PAYLOAD_SBE_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_PAYLOAD_SBE_MASK },
    { "INQ_PARITY", AR_NIC_RMT_ERR_FLG_1_MID_RMT_INQ_PARITY_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_INQ_PARITY_MASK },
    { "DIAG_ONLY", AR_NIC_RMT_ERR_FLG_1_MID_RMT_DIAG_ONLY_BP, AR_NIC_RMT_ERR_FLG_1_MID_RMT_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_err_flg_1_lo_rmt_detail[] = {
    { "UNUSED_63_29", AR_NIC_RMT_ERR_FLG_1_LO_RMT_UNUSED_63_29_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_UNUSED_63_29_MASK },
    { "I_STALL_DROPPED", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_STALL_DROPPED_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_STALL_DROPPED_MASK },
    { "I_BTECH3_NO_DESC", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_BTECH3_NO_DESC_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_BTECH3_NO_DESC_MASK },
    { "I_BTECH3_LAST_DESC", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_BTECH3_LAST_DESC_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_BTECH3_LAST_DESC_MASK },
    { "I_BTECH2_NO_DESC", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_BTECH2_NO_DESC_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_BTECH2_NO_DESC_MASK },
    { "I_BTECH2_LAST_DESC", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_BTECH2_LAST_DESC_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_BTECH2_LAST_DESC_MASK },
    { "I_BTECH1_NO_DESC", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_BTECH1_NO_DESC_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_BTECH1_NO_DESC_MASK },
    { "I_BTECH1_LAST_DESC", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_BTECH1_LAST_DESC_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_BTECH1_LAST_DESC_MASK },
    { "I_BTECH0_NO_DESC", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_BTECH0_NO_DESC_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_BTECH0_NO_DESC_MASK },
    { "I_BTECH0_LAST_DESC", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_BTECH0_LAST_DESC_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_BTECH0_LAST_DESC_MASK },
    { "I_DSMN_CAM_PARITY", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_DSMN_CAM_PARITY_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_DSMN_CAM_PARITY_MASK },
    { "I_SEND_CAM_PARITY", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_SEND_CAM_PARITY_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_SEND_CAM_PARITY_MASK },
    { "I_DSMN_TIMEOUT", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_DSMN_TIMEOUT_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_DSMN_TIMEOUT_MASK },
    { "I_SEND_TIMEOUT", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_SEND_TIMEOUT_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_SEND_TIMEOUT_MASK },
    { "I_RX_OVERRUN", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_RX_OVERRUN_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_RX_OVERRUN_MASK },
    { "I_RX_SEND_CAM_MISS", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_RX_SEND_CAM_MISS_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_RX_SEND_CAM_MISS_MASK },
    { "I_RX_BTECH_UNAVAILABLE", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_RX_BTECH_UNAVAILABLE_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_RX_BTECH_UNAVAILABLE_MASK },
    { "I_RX_DESC_BTECH_INV", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_RX_DESC_BTECH_INV_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_RX_DESC_BTECH_INV_MASK },
    { "I_UNDELIVERABLE_CQE", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_UNDELIVERABLE_CQE_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_UNDELIVERABLE_CQE_MASK },
    { "I_MALFORMED_PKT", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_MALFORMED_PKT_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_MALFORMED_PKT_MASK },
    { "I_DESC_TBL_MBE", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_DESC_TBL_MBE_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_DESC_TBL_MBE_MASK },
    { "I_DESC_TBL_SBE", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_DESC_TBL_SBE_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_DESC_TBL_SBE_MASK },
    { "I_SEQ_TBL_MBE", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_SEQ_TBL_MBE_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_SEQ_TBL_MBE_MASK },
    { "I_SEQ_TBL_SBE", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_SEQ_TBL_SBE_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_SEQ_TBL_SBE_MASK },
    { "I_PROTOCOL_ERR", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_PROTOCOL_ERR_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_PROTOCOL_ERR_MASK },
    { "I_PAYLOAD_MBE_DROP", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_PAYLOAD_MBE_DROP_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_PAYLOAD_MBE_DROP_MASK },
    { "I_PAYLOAD_MBE", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_PAYLOAD_MBE_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_PAYLOAD_MBE_MASK },
    { "I_PAYLOAD_SBE", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_PAYLOAD_SBE_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_PAYLOAD_SBE_MASK },
    { "I_INQ_PARITY", AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_INQ_PARITY_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_I_INQ_PARITY_MASK },
    { "UNUSED_0", AR_NIC_RMT_ERR_FLG_1_LO_RMT_UNUSED_0_BP, AR_NIC_RMT_ERR_FLG_1_LO_RMT_UNUSED_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_rmt_cam_2_hi_rmt_detail[] = {
    { "I_RAT_ACK", AR_NIC_RMT_RMT_CAM_2_HI_RMT_I_RAT_ACK_BP, AR_NIC_RMT_RMT_CAM_2_HI_RMT_I_RAT_ACK_MASK },
    { "I_TAGS_26_0", AR_NIC_RMT_RMT_CAM_2_HI_RMT_I_TAGS_26_0_BP, AR_NIC_RMT_RMT_CAM_2_HI_RMT_I_TAGS_26_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_rmt_cam_2_mid_rmt_detail[] = {
    { "I_TAGS_26_0", AR_NIC_RMT_RMT_CAM_2_MID_RMT_I_TAGS_26_0_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_I_TAGS_26_0_MASK },
    { "I_LSTATUS", AR_NIC_RMT_RMT_CAM_2_MID_RMT_I_LSTATUS_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_I_LSTATUS_MASK },
    { "I_INPUT_Q_COUNT_UNDERFLOW", AR_NIC_RMT_RMT_CAM_2_MID_RMT_I_INPUT_Q_COUNT_UNDERFLOW_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_I_INPUT_Q_COUNT_UNDERFLOW_MASK },
    { "I_INPUT_Q_COUNT_OVERFLOW", AR_NIC_RMT_RMT_CAM_2_MID_RMT_I_INPUT_Q_COUNT_OVERFLOW_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_I_INPUT_Q_COUNT_OVERFLOW_MASK },
    { "I_FLIT_CREDITS_USED_UNDERFLOW", AR_NIC_RMT_RMT_CAM_2_MID_RMT_I_FLIT_CREDITS_USED_UNDERFLOW_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_I_FLIT_CREDITS_USED_UNDERFLOW_MASK },
    { "I_FLIT_CREDITS_USED_OVERFLOW", AR_NIC_RMT_RMT_CAM_2_MID_RMT_I_FLIT_CREDITS_USED_OVERFLOW_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_I_FLIT_CREDITS_USED_OVERFLOW_MASK },
    { "I_EVICT_INDEX", AR_NIC_RMT_RMT_CAM_2_MID_RMT_I_EVICT_INDEX_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_I_EVICT_INDEX_MASK },
    { "I_EVICT_EN", AR_NIC_RMT_RMT_CAM_2_MID_RMT_I_EVICT_EN_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_I_EVICT_EN_MASK },
    { "PUT_C", AR_NIC_RMT_RMT_CAM_2_MID_RMT_PUT_C_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_PUT_C_MASK },
    { "SEND_C", AR_NIC_RMT_RMT_CAM_2_MID_RMT_SEND_C_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_SEND_C_MASK },
    { "MSG_SENDCMP", AR_NIC_RMT_RMT_CAM_2_MID_RMT_MSG_SENDCMP_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_MSG_SENDCMP_MASK },
    { "MSG_RCVCMP", AR_NIC_RMT_RMT_CAM_2_MID_RMT_MSG_RCVCMP_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_MSG_RCVCMP_MASK },
    { "MSG_ABORT", AR_NIC_RMT_RMT_CAM_2_MID_RMT_MSG_ABORT_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_MSG_ABORT_MASK },
    { "BTE_SENDCMP", AR_NIC_RMT_RMT_CAM_2_MID_RMT_BTE_SENDCMP_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_BTE_SENDCMP_MASK },
    { "CHECK_VALID_HIT", AR_NIC_RMT_RMT_CAM_2_MID_RMT_CHECK_VALID_HIT_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_CHECK_VALID_HIT_MASK },
    { "USE_RMT", AR_NIC_RMT_RMT_CAM_2_MID_RMT_USE_RMT_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_USE_RMT_MASK },
    { "CHECK_INDEX", AR_NIC_RMT_RMT_CAM_2_MID_RMT_CHECK_INDEX_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_CHECK_INDEX_MASK },
    { "CAM_EN_C", AR_NIC_RMT_RMT_CAM_2_MID_RMT_CAM_EN_C_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_CAM_EN_C_MASK },
    { "HEADER_C", AR_NIC_RMT_RMT_CAM_2_MID_RMT_HEADER_C_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_HEADER_C_MASK },
    { "FULL_C", AR_NIC_RMT_RMT_CAM_2_MID_RMT_FULL_C_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_FULL_C_MASK },
    { "STALL_Q_EN_C", AR_NIC_RMT_RMT_CAM_2_MID_RMT_STALL_Q_EN_C_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_STALL_Q_EN_C_MASK },
    { "STALL_OR_SCRUB_INDEX", AR_NIC_RMT_RMT_CAM_2_MID_RMT_STALL_OR_SCRUB_INDEX_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_STALL_OR_SCRUB_INDEX_MASK },
    { "CAM_READ_EN_C", AR_NIC_RMT_RMT_CAM_2_MID_RMT_CAM_READ_EN_C_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_CAM_READ_EN_C_MASK },
    { "CAM_FILL_EN_C", AR_NIC_RMT_RMT_CAM_2_MID_RMT_CAM_FILL_EN_C_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_CAM_FILL_EN_C_MASK },
    { "R_Q_FILL", AR_NIC_RMT_RMT_CAM_2_MID_RMT_R_Q_FILL_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_R_Q_FILL_MASK },
    { "R_Q_MISS", AR_NIC_RMT_RMT_CAM_2_MID_RMT_R_Q_MISS_BP, AR_NIC_RMT_RMT_CAM_2_MID_RMT_R_Q_MISS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_rmt_cam_2_lo_rmt_detail[] = {
    { "R_Q_FIRST", AR_NIC_RMT_RMT_CAM_2_LO_RMT_R_Q_FIRST_BP, AR_NIC_RMT_RMT_CAM_2_LO_RMT_R_Q_FIRST_MASK },
    { "R_Q_UPDATE_EN", AR_NIC_RMT_RMT_CAM_2_LO_RMT_R_Q_UPDATE_EN_BP, AR_NIC_RMT_RMT_CAM_2_LO_RMT_R_Q_UPDATE_EN_MASK },
    { "R_Q_DESC_EN", AR_NIC_RMT_RMT_CAM_2_LO_RMT_R_Q_DESC_EN_BP, AR_NIC_RMT_RMT_CAM_2_LO_RMT_R_Q_DESC_EN_MASK },
    { "Q_COUNT", AR_NIC_RMT_RMT_CAM_2_LO_RMT_Q_COUNT_BP, AR_NIC_RMT_RMT_CAM_2_LO_RMT_Q_COUNT_MASK },
    { "R_Q_EPOCH_INCR", AR_NIC_RMT_RMT_CAM_2_LO_RMT_R_Q_EPOCH_INCR_BP, AR_NIC_RMT_RMT_CAM_2_LO_RMT_R_Q_EPOCH_INCR_MASK },
    { "SEND_RESERVE_REACHED_C", AR_NIC_RMT_RMT_CAM_2_LO_RMT_SEND_RESERVE_REACHED_C_BP, AR_NIC_RMT_RMT_CAM_2_LO_RMT_SEND_RESERVE_REACHED_C_MASK },
    { "SEND_COUNT_UNDERFLOW", AR_NIC_RMT_RMT_CAM_2_LO_RMT_SEND_COUNT_UNDERFLOW_BP, AR_NIC_RMT_RMT_CAM_2_LO_RMT_SEND_COUNT_UNDERFLOW_MASK },
    { "SEND_COUNT_OVERFLOW", AR_NIC_RMT_RMT_CAM_2_LO_RMT_SEND_COUNT_OVERFLOW_BP, AR_NIC_RMT_RMT_CAM_2_LO_RMT_SEND_COUNT_OVERFLOW_MASK },
    { "CAM_COUNT_UNDERFLOW", AR_NIC_RMT_RMT_CAM_2_LO_RMT_CAM_COUNT_UNDERFLOW_BP, AR_NIC_RMT_RMT_CAM_2_LO_RMT_CAM_COUNT_UNDERFLOW_MASK },
    { "CAM_COUNT_OVERFLOW", AR_NIC_RMT_RMT_CAM_2_LO_RMT_CAM_COUNT_OVERFLOW_BP, AR_NIC_RMT_RMT_CAM_2_LO_RMT_CAM_COUNT_OVERFLOW_MASK },
    { "SEND_COUNT", AR_NIC_RMT_RMT_CAM_2_LO_RMT_SEND_COUNT_BP, AR_NIC_RMT_RMT_CAM_2_LO_RMT_SEND_COUNT_MASK },
    { "LAST_NEW_EVICT", AR_NIC_RMT_RMT_CAM_2_LO_RMT_LAST_NEW_EVICT_BP, AR_NIC_RMT_RMT_CAM_2_LO_RMT_LAST_NEW_EVICT_MASK },
    { "LAST_UPD_EVICT", AR_NIC_RMT_RMT_CAM_2_LO_RMT_LAST_UPD_EVICT_BP, AR_NIC_RMT_RMT_CAM_2_LO_RMT_LAST_UPD_EVICT_MASK },
    { "R_Q_MMR_READ_ACK", AR_NIC_RMT_RMT_CAM_2_LO_RMT_R_Q_MMR_READ_ACK_BP, AR_NIC_RMT_RMT_CAM_2_LO_RMT_R_Q_MMR_READ_ACK_MASK },
    { "MMR_STATE", AR_NIC_RMT_RMT_CAM_2_LO_RMT_MMR_STATE_BP, AR_NIC_RMT_RMT_CAM_2_LO_RMT_MMR_STATE_MASK },
    { "MMR_RW", AR_NIC_RMT_RMT_CAM_2_LO_RMT_MMR_RW_BP, AR_NIC_RMT_RMT_CAM_2_LO_RMT_MMR_RW_MASK },
    { "MMR_INDEX", AR_NIC_RMT_RMT_CAM_2_LO_RMT_MMR_INDEX_BP, AR_NIC_RMT_RMT_CAM_2_LO_RMT_MMR_INDEX_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_rmt_seq_table_3_hi_rmt_detail[] = {
    { "UNUSED_145_140", AR_NIC_RMT_RMT_SEQ_TABLE_3_HI_RMT_UNUSED_145_140_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_HI_RMT_UNUSED_145_140_MASK },
    { "R_Q_SEQTBL_READ_ACK", AR_NIC_RMT_RMT_SEQ_TABLE_3_HI_RMT_R_Q_SEQTBL_READ_ACK_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_HI_RMT_R_Q_SEQTBL_READ_ACK_MASK },
    { "R_Q_SEQTBL_READ_SBE", AR_NIC_RMT_RMT_SEQ_TABLE_3_HI_RMT_R_Q_SEQTBL_READ_SBE_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_HI_RMT_R_Q_SEQTBL_READ_SBE_MASK },
    { "R_Q_SEQTBL_READ_MBE", AR_NIC_RMT_RMT_SEQ_TABLE_3_HI_RMT_R_Q_SEQTBL_READ_MBE_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_HI_RMT_R_Q_SEQTBL_READ_MBE_MASK },
    { "ERRINJ_SEQ_TBL_ENABLE", AR_NIC_RMT_RMT_SEQ_TABLE_3_HI_RMT_ERRINJ_SEQ_TBL_ENABLE_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_HI_RMT_ERRINJ_SEQ_TBL_ENABLE_MASK },
    { "ERRINJ_SEQ_TBL_ARMED", AR_NIC_RMT_RMT_SEQ_TABLE_3_HI_RMT_ERRINJ_SEQ_TBL_ARMED_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_HI_RMT_ERRINJ_SEQ_TBL_ARMED_MASK },
    { "R_Q_SBE", AR_NIC_RMT_RMT_SEQ_TABLE_3_HI_RMT_R_Q_SBE_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_HI_RMT_R_Q_SBE_MASK },
    { "R_Q_MBE", AR_NIC_RMT_RMT_SEQ_TABLE_3_HI_RMT_R_Q_MBE_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_HI_RMT_R_Q_MBE_MASK },
    { "R_Q_BTE_SEND", AR_NIC_RMT_RMT_SEQ_TABLE_3_HI_RMT_R_Q_BTE_SEND_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_HI_RMT_R_Q_BTE_SEND_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_rmt_seq_table_3_mid_rmt_detail[] = {
    { "R_Q_EPOCH_EN", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_EPOCH_EN_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_EPOCH_EN_MASK },
    { "R_Q_EPOCH_TIME_7_0", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_EPOCH_TIME_7_0_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_EPOCH_TIME_7_0_MASK },
    { "R_Q_MSGCMP_RX", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_MSGCMP_RX_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_MSGCMP_RX_MASK },
    { "R_Q_FLAG_OP", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_FLAG_OP_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_FLAG_OP_MASK },
    { "R_Q_RX_STATUS", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_RX_STATUS_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_RX_STATUS_MASK },
    { "R_Q_CQ_ERRLOC", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_CQ_ERRLOC_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_CQ_ERRLOC_MASK },
    { "UNUSED_106_101", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_UNUSED_106_101_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_UNUSED_106_101_MASK },
    { "R_Q_RX_OVERRUN", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_RX_OVERRUN_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_RX_OVERRUN_MASK },
    { "R_Q_RX_IMM_EN", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_RX_IMM_EN_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_RX_IMM_EN_MASK },
    { "R_Q_RX_BTECH", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_RX_BTECH_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_RX_BTECH_MASK },
    { "R_Q_PI_HINTS", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_PI_HINTS_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_PI_HINTS_MASK },
    { "R_Q_RX_IRQ_MODE", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_RX_IRQ_MODE_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_RX_IRQ_MODE_MASK },
    { "R_Q_RX_DELAY_IRQ_EN", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_RX_DELAY_IRQ_EN_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_RX_DELAY_IRQ_EN_MASK },
    { "UNUSED_91_90", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_UNUSED_91_90_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_UNUSED_91_90_MASK },
    { "WEN_7", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_WEN_7_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_WEN_7_MASK },
    { "WEN_6", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_WEN_6_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_WEN_6_MASK },
    { "I_WE_1", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_I_WE_1_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_I_WE_1_MASK },
    { "MMR_STATE", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_MMR_STATE_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_MMR_STATE_MASK },
    { "RADDR_2_9", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_RADDR_2_9_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_RADDR_2_9_MASK },
    { "RADDR_1_9", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_RADDR_1_9_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_RADDR_1_9_MASK },
    { "RADDR_0", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_RADDR_0_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_RADDR_0_MASK },
    { "R_Q_RX_COMPLETE", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_RX_COMPLETE_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_RX_COMPLETE_MASK },
    { "R_Q_RX_EVICTED", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_RX_EVICTED_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_RX_EVICTED_MASK },
    { "R_Q_PKT_COUNT", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_PKT_COUNT_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT_R_Q_PKT_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_rmt_seq_table_3_lo_rmt_detail[] = {
    { "R_Q_PKT_COUNT", AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT_R_Q_PKT_COUNT_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT_R_Q_PKT_COUNT_MASK },
    { "R_Q_PKT_PID", AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT_R_Q_PKT_PID_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT_R_Q_PKT_PID_MASK },
    { "R_Q_PKT_FLUSH", AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT_R_Q_PKT_FLUSH_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT_R_Q_PKT_FLUSH_MASK },
    { "R_Q_STALL_OR_SCRUB_SRCID", AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT_R_Q_STALL_OR_SCRUB_SRCID_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT_R_Q_STALL_OR_SCRUB_SRCID_MASK },
    { "R_Q_STALL_OR_SCRUB_SOURCE", AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT_R_Q_STALL_OR_SCRUB_SOURCE_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT_R_Q_STALL_OR_SCRUB_SOURCE_MASK },
    { "R_Q_GOT_FIRST", AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT_R_Q_GOT_FIRST_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT_R_Q_GOT_FIRST_MASK },
    { "INIT_SEQ_TABLE_WREN_P6", AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT_INIT_SEQ_TABLE_WREN_P6_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT_INIT_SEQ_TABLE_WREN_P6_MASK },
    { "INIT_SEQ_TABLE_COMPLETE", AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT_INIT_SEQ_TABLE_COMPLETE_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT_INIT_SEQ_TABLE_COMPLETE_MASK },
    { "ADDR", AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT_ADDR_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT_ADDR_MASK },
    { "WADDR_6", AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT_WADDR_6_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT_WADDR_6_MASK },
    { "MMR_WRITE_ENABLE_P6", AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT_MMR_WRITE_ENABLE_P6_BP, AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT_MMR_WRITE_ENABLE_P6_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_rmt_pkt_update_4_hi_rmt_detail[] = {
    { "UNUSED_145_143", AR_NIC_RMT_RMT_PKT_UPDATE_4_HI_RMT_UNUSED_145_143_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_HI_RMT_UNUSED_145_143_MASK },
    { "R_Q_PKT_UPD_FLIT_ACK", AR_NIC_RMT_RMT_PKT_UPDATE_4_HI_RMT_R_Q_PKT_UPD_FLIT_ACK_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_HI_RMT_R_Q_PKT_UPD_FLIT_ACK_MASK },
    { "R_Q_PKT_UPD_CQ_ACK", AR_NIC_RMT_RMT_PKT_UPDATE_4_HI_RMT_R_Q_PKT_UPD_CQ_ACK_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_HI_RMT_R_Q_PKT_UPD_CQ_ACK_MASK },
    { "R_Q_STALL_Q_REQ", AR_NIC_RMT_RMT_PKT_UPDATE_4_HI_RMT_R_Q_STALL_Q_REQ_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_HI_RMT_R_Q_STALL_Q_REQ_MASK },
    { "R_Q_STALL_Q_INDEX", AR_NIC_RMT_RMT_PKT_UPDATE_4_HI_RMT_R_Q_STALL_Q_INDEX_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_HI_RMT_R_Q_STALL_Q_INDEX_MASK },
    { "R_Q_PI_HINTS", AR_NIC_RMT_RMT_PKT_UPDATE_4_HI_RMT_R_Q_PI_HINTS_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_HI_RMT_R_Q_PI_HINTS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_rmt_pkt_update_4_mid_rmt_detail[] = {
    { "R_Q_PI_HINTS", AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_PI_HINTS_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_PI_HINTS_MASK },
    { "R_Q_WADDR", AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_WADDR_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_WADDR_MASK },
    { "R_Q_EVICT_INDEX", AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_EVICT_INDEX_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_EVICT_INDEX_MASK },
    { "R_Q_WE_0", AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_WE_0_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_WE_0_MASK },
    { "R_Q_EVICT_EN", AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_EVICT_EN_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_EVICT_EN_MASK },
    { "R_Q_EVICT_SEND", AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_EVICT_SEND_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_EVICT_SEND_MASK },
    { "R_Q_CQ_VALID", AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_CQ_VALID_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_CQ_VALID_MASK },
    { "R_Q_CQ_HIT", AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_CQ_HIT_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_CQ_HIT_MASK },
    { "R_Q_CQ_NS", AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_CQ_NS_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_CQ_NS_MASK },
    { "R_Q_CQ_SRC_ID", AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_CQ_SRC_ID_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_CQ_SRC_ID_MASK },
    { "R_Q_CQ_FLUSH", AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_CQ_FLUSH_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_CQ_FLUSH_MASK },
    { "R_Q_CQ_HANDLE", AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_CQ_HANDLE_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_CQ_HANDLE_MASK },
    { "R_Q_CQ_SOURCE", AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_CQ_SOURCE_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_CQ_SOURCE_MASK },
    { "R_Q_CQ_PKT_ID", AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_CQ_PKT_ID_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT_R_Q_CQ_PKT_ID_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_rmt_pkt_update_4_lo_rmt_detail[] = {
    { "R_Q_CQ_PKT_ID", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_R_Q_CQ_PKT_ID_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_R_Q_CQ_PKT_ID_MASK },
    { "R_Q_IRQ_BUBBLE_REQ", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_R_Q_IRQ_BUBBLE_REQ_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_R_Q_IRQ_BUBBLE_REQ_MASK },
    { "STALL_DROPPED", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_STALL_DROPPED_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_STALL_DROPPED_MASK },
    { "BTECH3_NO_DESC", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_BTECH3_NO_DESC_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_BTECH3_NO_DESC_MASK },
    { "BTECH3_LAST_DESC", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_BTECH3_LAST_DESC_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_BTECH3_LAST_DESC_MASK },
    { "BTECH2_NO_DESC", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_BTECH2_NO_DESC_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_BTECH2_NO_DESC_MASK },
    { "BTECH2_LAST_DESC", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_BTECH2_LAST_DESC_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_BTECH2_LAST_DESC_MASK },
    { "BTECH1_NO_DESC", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_BTECH1_NO_DESC_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_BTECH1_NO_DESC_MASK },
    { "BTECH1_LAST_DESC", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_BTECH1_LAST_DESC_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_BTECH1_LAST_DESC_MASK },
    { "BTECH0_NO_DESC", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_BTECH0_NO_DESC_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_BTECH0_NO_DESC_MASK },
    { "BTECH0_LAST_DESC", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_BTECH0_LAST_DESC_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_BTECH0_LAST_DESC_MASK },
    { "DSMN_CAM_PARITY", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_DSMN_CAM_PARITY_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_DSMN_CAM_PARITY_MASK },
    { "SEND_CAM_PARITY", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_SEND_CAM_PARITY_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_SEND_CAM_PARITY_MASK },
    { "DSMN_TIMEOUT", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_DSMN_TIMEOUT_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_DSMN_TIMEOUT_MASK },
    { "SEND_TIMEOUT", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_SEND_TIMEOUT_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_SEND_TIMEOUT_MASK },
    { "RX_OVERRUN", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_RX_OVERRUN_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_RX_OVERRUN_MASK },
    { "RX_SEND_CAM_MISS", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_RX_SEND_CAM_MISS_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_RX_SEND_CAM_MISS_MASK },
    { "RX_BTECH_UNAVAILABLE", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_RX_BTECH_UNAVAILABLE_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_RX_BTECH_UNAVAILABLE_MASK },
    { "RX_DESC_BTECH_INV", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_RX_DESC_BTECH_INV_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_RX_DESC_BTECH_INV_MASK },
    { "UNDELIVERABLE_CQE", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_UNDELIVERABLE_CQE_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_UNDELIVERABLE_CQE_MASK },
    { "MALFORMED_PKT", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_MALFORMED_PKT_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_MALFORMED_PKT_MASK },
    { "DESC_TBL_MBE", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_DESC_TBL_MBE_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_DESC_TBL_MBE_MASK },
    { "DESC_TBL_SBE", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_DESC_TBL_SBE_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_DESC_TBL_SBE_MASK },
    { "SEQ_TBL_MBE", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_SEQ_TBL_MBE_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_SEQ_TBL_MBE_MASK },
    { "SEQ_TBL_SBE", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_SEQ_TBL_SBE_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_SEQ_TBL_SBE_MASK },
    { "PROTOCOL_ERR", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_PROTOCOL_ERR_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_PROTOCOL_ERR_MASK },
    { "PAYLOAD_MBE_DROP", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_PAYLOAD_MBE_DROP_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_PAYLOAD_MBE_DROP_MASK },
    { "UNUSED_30_29", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_UNUSED_30_29_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_UNUSED_30_29_MASK },
    { "RXRESET", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_RXRESET_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_RXRESET_MASK },
    { "IDV_TIMER", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_IDV_TIMER_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_IDV_TIMER_MASK },
    { "IDV_TERM", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_IDV_TERM_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_IDV_TERM_MASK },
    { "IS_HEAD", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_IS_HEAD_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_IS_HEAD_MASK },
    { "MSGCMP_FLIT_COUNT", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_MSGCMP_FLIT_COUNT_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_MSGCMP_FLIT_COUNT_MASK },
    { "MSGCMP_FLAG_EN", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_MSGCMP_FLAG_EN_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_MSGCMP_FLAG_EN_MASK },
    { "MSGCMP_FLAG_ERR", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_MSGCMP_FLAG_ERR_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_MSGCMP_FLAG_ERR_MASK },
    { "EOM_CACHE_COUNT", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_EOM_CACHE_COUNT_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_EOM_CACHE_COUNT_MASK },
    { "STALL_Q_COUNT", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_STALL_Q_COUNT_BP, AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT_STALL_Q_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_rmt_cq_5_hi_rmt_detail[] = {
    { "UNUSED_145_105", AR_NIC_RMT_RMT_CQ_5_HI_RMT_UNUSED_145_105_BP, AR_NIC_RMT_RMT_CQ_5_HI_RMT_UNUSED_145_105_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_rmt_cq_5_mid_rmt_detail[] = {
    { "UNUSED_145_105", AR_NIC_RMT_RMT_CQ_5_MID_RMT_UNUSED_145_105_BP, AR_NIC_RMT_RMT_CQ_5_MID_RMT_UNUSED_145_105_MASK },
    { "R_Q_RMT_CQ_VALID", AR_NIC_RMT_RMT_CQ_5_MID_RMT_R_Q_RMT_CQ_VALID_BP, AR_NIC_RMT_RMT_CQ_5_MID_RMT_R_Q_RMT_CQ_VALID_MASK },
    { "R_Q_RMT_CQ_HIT", AR_NIC_RMT_RMT_CQ_5_MID_RMT_R_Q_RMT_CQ_HIT_BP, AR_NIC_RMT_RMT_CQ_5_MID_RMT_R_Q_RMT_CQ_HIT_MASK },
    { "R_Q_RMT_CQ_NS", AR_NIC_RMT_RMT_CQ_5_MID_RMT_R_Q_RMT_CQ_NS_BP, AR_NIC_RMT_RMT_CQ_5_MID_RMT_R_Q_RMT_CQ_NS_MASK },
    { "R_Q_RMT_CQ_SRC_ID", AR_NIC_RMT_RMT_CQ_5_MID_RMT_R_Q_RMT_CQ_SRC_ID_BP, AR_NIC_RMT_RMT_CQ_5_MID_RMT_R_Q_RMT_CQ_SRC_ID_MASK },
    { "R_Q_RMT_CQ_FLUSH", AR_NIC_RMT_RMT_CQ_5_MID_RMT_R_Q_RMT_CQ_FLUSH_BP, AR_NIC_RMT_RMT_CQ_5_MID_RMT_R_Q_RMT_CQ_FLUSH_MASK },
    { "R_Q_RMT_CQ_HANDLE", AR_NIC_RMT_RMT_CQ_5_MID_RMT_R_Q_RMT_CQ_HANDLE_BP, AR_NIC_RMT_RMT_CQ_5_MID_RMT_R_Q_RMT_CQ_HANDLE_MASK },
    { "R_Q_RMT_CQ_SOURCE", AR_NIC_RMT_RMT_CQ_5_MID_RMT_R_Q_RMT_CQ_SOURCE_BP, AR_NIC_RMT_RMT_CQ_5_MID_RMT_R_Q_RMT_CQ_SOURCE_MASK },
    { "R_Q_RMT_CQ_PKT_ID", AR_NIC_RMT_RMT_CQ_5_MID_RMT_R_Q_RMT_CQ_PKT_ID_BP, AR_NIC_RMT_RMT_CQ_5_MID_RMT_R_Q_RMT_CQ_PKT_ID_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_rmt_cq_5_lo_rmt_detail[] = {
    { "R_Q_RMT_CQ_PKT_ID", AR_NIC_RMT_RMT_CQ_5_LO_RMT_R_Q_RMT_CQ_PKT_ID_BP, AR_NIC_RMT_RMT_CQ_5_LO_RMT_R_Q_RMT_CQ_PKT_ID_MASK },
    { "R_Q_RMT_CQ_DATA", AR_NIC_RMT_RMT_CQ_5_LO_RMT_R_Q_RMT_CQ_DATA_BP, AR_NIC_RMT_RMT_CQ_5_LO_RMT_R_Q_RMT_CQ_DATA_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_rat_rmt_flit_6_hi_rmt_detail[] = {
    { "PKT_SB", AR_NIC_RMT_RAT_RMT_FLIT_6_HI_RMT_PKT_SB_BP, AR_NIC_RMT_RAT_RMT_FLIT_6_HI_RMT_PKT_SB_MASK },
    { "PKT_FLIT", AR_NIC_RMT_RAT_RMT_FLIT_6_HI_RMT_PKT_FLIT_BP, AR_NIC_RMT_RAT_RMT_FLIT_6_HI_RMT_PKT_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_rat_rmt_flit_6_mid_rmt_detail[] = {
    { "PKT_FLIT", AR_NIC_RMT_RAT_RMT_FLIT_6_MID_RMT_PKT_FLIT_BP, AR_NIC_RMT_RAT_RMT_FLIT_6_MID_RMT_PKT_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_rat_rmt_flit_6_lo_rmt_detail[] = {
    { "PKT_FLIT", AR_NIC_RMT_RAT_RMT_FLIT_6_LO_RMT_PKT_FLIT_BP, AR_NIC_RMT_RAT_RMT_FLIT_6_LO_RMT_PKT_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_rmt_npt_flit_7_hi_rmt_detail[] = {
    { "R_Q_RMT_NPT_REQ_SB", AR_NIC_RMT_RMT_NPT_FLIT_7_HI_RMT_R_Q_RMT_NPT_REQ_SB_BP, AR_NIC_RMT_RMT_NPT_FLIT_7_HI_RMT_R_Q_RMT_NPT_REQ_SB_MASK },
    { "R_Q_RMT_NPT_REQ_FLIT", AR_NIC_RMT_RMT_NPT_FLIT_7_HI_RMT_R_Q_RMT_NPT_REQ_FLIT_BP, AR_NIC_RMT_RMT_NPT_FLIT_7_HI_RMT_R_Q_RMT_NPT_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_rmt_npt_flit_7_mid_rmt_detail[] = {
    { "R_Q_RMT_NPT_REQ_FLIT", AR_NIC_RMT_RMT_NPT_FLIT_7_MID_RMT_R_Q_RMT_NPT_REQ_FLIT_BP, AR_NIC_RMT_RMT_NPT_FLIT_7_MID_RMT_R_Q_RMT_NPT_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_rmt_npt_flit_7_lo_rmt_detail[] = {
    { "R_Q_RMT_NPT_REQ_FLIT", AR_NIC_RMT_RMT_NPT_FLIT_7_LO_RMT_R_Q_RMT_NPT_REQ_FLIT_BP, AR_NIC_RMT_RMT_NPT_FLIT_7_LO_RMT_R_Q_RMT_NPT_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_cfg_timer_control_detail[] = {
    { "SCRUB_INTERVAL", AR_NIC_RMT_CFG_TIMER_CONTROL_SCRUB_INTERVAL_BP, AR_NIC_RMT_CFG_TIMER_CONTROL_SCRUB_INTERVAL_MASK },
    { "IDV_INTERVAL", AR_NIC_RMT_CFG_TIMER_CONTROL_IDV_INTERVAL_BP, AR_NIC_RMT_CFG_TIMER_CONTROL_IDV_INTERVAL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_cfg_cam_params0_detail[] = {
    { "RMT_EN", AR_NIC_RMT_CFG_CAM_PARAMS0_RMT_EN_BP, AR_NIC_RMT_CFG_CAM_PARAMS0_RMT_EN_MASK },
    { "CQ_CREDITS", AR_NIC_RMT_CFG_CAM_PARAMS0_CQ_CREDITS_BP, AR_NIC_RMT_CFG_CAM_PARAMS0_CQ_CREDITS_MASK },
    { "NPT_CREDITS", AR_NIC_RMT_CFG_CAM_PARAMS0_NPT_CREDITS_BP, AR_NIC_RMT_CFG_CAM_PARAMS0_NPT_CREDITS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_cfg_cam_params1_detail[] = {
    { "DSMN_TIMEOUT_MODE", AR_NIC_RMT_CFG_CAM_PARAMS1_DSMN_TIMEOUT_MODE_BP, AR_NIC_RMT_CFG_CAM_PARAMS1_DSMN_TIMEOUT_MODE_MASK },
    { "SEND_TIMEOUT_MODE", AR_NIC_RMT_CFG_CAM_PARAMS1_SEND_TIMEOUT_MODE_BP, AR_NIC_RMT_CFG_CAM_PARAMS1_SEND_TIMEOUT_MODE_MASK },
    { "DSMN_TIMEOUT_VALUE", AR_NIC_RMT_CFG_CAM_PARAMS1_DSMN_TIMEOUT_VALUE_BP, AR_NIC_RMT_CFG_CAM_PARAMS1_DSMN_TIMEOUT_VALUE_MASK },
    { "SEND_TIMEOUT_VALUE", AR_NIC_RMT_CFG_CAM_PARAMS1_SEND_TIMEOUT_VALUE_BP, AR_NIC_RMT_CFG_CAM_PARAMS1_SEND_TIMEOUT_VALUE_MASK },
    { "MAX_CAM_ENTRIES", AR_NIC_RMT_CFG_CAM_PARAMS1_MAX_CAM_ENTRIES_BP, AR_NIC_RMT_CFG_CAM_PARAMS1_MAX_CAM_ENTRIES_MASK },
    { "EVICT_THRESHOLD", AR_NIC_RMT_CFG_CAM_PARAMS1_EVICT_THRESHOLD_BP, AR_NIC_RMT_CFG_CAM_PARAMS1_EVICT_THRESHOLD_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_cfg_rx_desc_btech_base_idx_detail[] = {
    { "BTECH3", AR_NIC_RMT_CFG_RX_DESC_BTECH_BASE_IDX_BTECH3_BP, AR_NIC_RMT_CFG_RX_DESC_BTECH_BASE_IDX_BTECH3_MASK },
    { "BTECH2", AR_NIC_RMT_CFG_RX_DESC_BTECH_BASE_IDX_BTECH2_BP, AR_NIC_RMT_CFG_RX_DESC_BTECH_BASE_IDX_BTECH2_MASK },
    { "BTECH1", AR_NIC_RMT_CFG_RX_DESC_BTECH_BASE_IDX_BTECH1_BP, AR_NIC_RMT_CFG_RX_DESC_BTECH_BASE_IDX_BTECH1_MASK },
    { "BTECH0", AR_NIC_RMT_CFG_RX_DESC_BTECH_BASE_IDX_BTECH0_BP, AR_NIC_RMT_CFG_RX_DESC_BTECH_BASE_IDX_BTECH0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_cfg_rx_desc_btech_cnt_detail[] = {
    { "BTECH3", AR_NIC_RMT_CFG_RX_DESC_BTECH_CNT_BTECH3_BP, AR_NIC_RMT_CFG_RX_DESC_BTECH_CNT_BTECH3_MASK },
    { "BTECH2", AR_NIC_RMT_CFG_RX_DESC_BTECH_CNT_BTECH2_BP, AR_NIC_RMT_CFG_RX_DESC_BTECH_CNT_BTECH2_MASK },
    { "BTECH1", AR_NIC_RMT_CFG_RX_DESC_BTECH_CNT_BTECH1_BP, AR_NIC_RMT_CFG_RX_DESC_BTECH_CNT_BTECH1_MASK },
    { "BTECH0", AR_NIC_RMT_CFG_RX_DESC_BTECH_CNT_BTECH0_BP, AR_NIC_RMT_CFG_RX_DESC_BTECH_CNT_BTECH0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_err_flg_detail[] = {
    { "STALL_DROPPED", AR_NIC_RMT_ERR_FLG_STALL_DROPPED_BP, AR_NIC_RMT_ERR_FLG_STALL_DROPPED_MASK },
    { "BTECH3_NO_DESC", AR_NIC_RMT_ERR_FLG_BTECH3_NO_DESC_BP, AR_NIC_RMT_ERR_FLG_BTECH3_NO_DESC_MASK },
    { "BTECH3_LAST_DESC", AR_NIC_RMT_ERR_FLG_BTECH3_LAST_DESC_BP, AR_NIC_RMT_ERR_FLG_BTECH3_LAST_DESC_MASK },
    { "BTECH2_NO_DESC", AR_NIC_RMT_ERR_FLG_BTECH2_NO_DESC_BP, AR_NIC_RMT_ERR_FLG_BTECH2_NO_DESC_MASK },
    { "BTECH2_LAST_DESC", AR_NIC_RMT_ERR_FLG_BTECH2_LAST_DESC_BP, AR_NIC_RMT_ERR_FLG_BTECH2_LAST_DESC_MASK },
    { "BTECH1_NO_DESC", AR_NIC_RMT_ERR_FLG_BTECH1_NO_DESC_BP, AR_NIC_RMT_ERR_FLG_BTECH1_NO_DESC_MASK },
    { "BTECH1_LAST_DESC", AR_NIC_RMT_ERR_FLG_BTECH1_LAST_DESC_BP, AR_NIC_RMT_ERR_FLG_BTECH1_LAST_DESC_MASK },
    { "BTECH0_NO_DESC", AR_NIC_RMT_ERR_FLG_BTECH0_NO_DESC_BP, AR_NIC_RMT_ERR_FLG_BTECH0_NO_DESC_MASK },
    { "BTECH0_LAST_DESC", AR_NIC_RMT_ERR_FLG_BTECH0_LAST_DESC_BP, AR_NIC_RMT_ERR_FLG_BTECH0_LAST_DESC_MASK },
    { "DSMN_CAM_PARITY", AR_NIC_RMT_ERR_FLG_DSMN_CAM_PARITY_BP, AR_NIC_RMT_ERR_FLG_DSMN_CAM_PARITY_MASK },
    { "SEND_CAM_PARITY", AR_NIC_RMT_ERR_FLG_SEND_CAM_PARITY_BP, AR_NIC_RMT_ERR_FLG_SEND_CAM_PARITY_MASK },
    { "DSMN_TIMEOUT", AR_NIC_RMT_ERR_FLG_DSMN_TIMEOUT_BP, AR_NIC_RMT_ERR_FLG_DSMN_TIMEOUT_MASK },
    { "SEND_TIMEOUT", AR_NIC_RMT_ERR_FLG_SEND_TIMEOUT_BP, AR_NIC_RMT_ERR_FLG_SEND_TIMEOUT_MASK },
    { "RX_OVERRUN", AR_NIC_RMT_ERR_FLG_RX_OVERRUN_BP, AR_NIC_RMT_ERR_FLG_RX_OVERRUN_MASK },
    { "RX_SEND_CAM_MISS", AR_NIC_RMT_ERR_FLG_RX_SEND_CAM_MISS_BP, AR_NIC_RMT_ERR_FLG_RX_SEND_CAM_MISS_MASK },
    { "RX_BTECH_UNAVAILABLE", AR_NIC_RMT_ERR_FLG_RX_BTECH_UNAVAILABLE_BP, AR_NIC_RMT_ERR_FLG_RX_BTECH_UNAVAILABLE_MASK },
    { "RX_DESC_BTECH_INV", AR_NIC_RMT_ERR_FLG_RX_DESC_BTECH_INV_BP, AR_NIC_RMT_ERR_FLG_RX_DESC_BTECH_INV_MASK },
    { "UNDELIVERABLE_CQE", AR_NIC_RMT_ERR_FLG_UNDELIVERABLE_CQE_BP, AR_NIC_RMT_ERR_FLG_UNDELIVERABLE_CQE_MASK },
    { "MALFORMED_PKT", AR_NIC_RMT_ERR_FLG_MALFORMED_PKT_BP, AR_NIC_RMT_ERR_FLG_MALFORMED_PKT_MASK },
    { "DESC_TBL_MBE", AR_NIC_RMT_ERR_FLG_DESC_TBL_MBE_BP, AR_NIC_RMT_ERR_FLG_DESC_TBL_MBE_MASK },
    { "DESC_TBL_SBE", AR_NIC_RMT_ERR_FLG_DESC_TBL_SBE_BP, AR_NIC_RMT_ERR_FLG_DESC_TBL_SBE_MASK },
    { "SEQ_TBL_MBE", AR_NIC_RMT_ERR_FLG_SEQ_TBL_MBE_BP, AR_NIC_RMT_ERR_FLG_SEQ_TBL_MBE_MASK },
    { "SEQ_TBL_SBE", AR_NIC_RMT_ERR_FLG_SEQ_TBL_SBE_BP, AR_NIC_RMT_ERR_FLG_SEQ_TBL_SBE_MASK },
    { "PROTOCOL_ERR", AR_NIC_RMT_ERR_FLG_PROTOCOL_ERR_BP, AR_NIC_RMT_ERR_FLG_PROTOCOL_ERR_MASK },
    { "PAYLOAD_MBE_DROP", AR_NIC_RMT_ERR_FLG_PAYLOAD_MBE_DROP_BP, AR_NIC_RMT_ERR_FLG_PAYLOAD_MBE_DROP_MASK },
    { "PAYLOAD_MBE", AR_NIC_RMT_ERR_FLG_PAYLOAD_MBE_BP, AR_NIC_RMT_ERR_FLG_PAYLOAD_MBE_MASK },
    { "PAYLOAD_SBE", AR_NIC_RMT_ERR_FLG_PAYLOAD_SBE_BP, AR_NIC_RMT_ERR_FLG_PAYLOAD_SBE_MASK },
    { "INQ_PARITY", AR_NIC_RMT_ERR_FLG_INQ_PARITY_BP, AR_NIC_RMT_ERR_FLG_INQ_PARITY_MASK },
    { "DIAG_ONLY", AR_NIC_RMT_ERR_FLG_DIAG_ONLY_BP, AR_NIC_RMT_ERR_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
#ifdef EXCEPTIONS_DEFS
static const errcat_mmrd_t _ar_nic_rmt_err_flg_errcat[] = {
    { "STALL_DROPPED", AR_NIC_RMT_ERR_FLG_STALL_DROPPED_BP, AR_NIC_RMT_ERR_FLG_STALL_DROPPED_EC },
    { "BTECH3_NO_DESC", AR_NIC_RMT_ERR_FLG_BTECH3_NO_DESC_BP, AR_NIC_RMT_ERR_FLG_BTECH3_NO_DESC_EC },
    { "BTECH3_LAST_DESC", AR_NIC_RMT_ERR_FLG_BTECH3_LAST_DESC_BP, AR_NIC_RMT_ERR_FLG_BTECH3_LAST_DESC_EC },
    { "BTECH2_NO_DESC", AR_NIC_RMT_ERR_FLG_BTECH2_NO_DESC_BP, AR_NIC_RMT_ERR_FLG_BTECH2_NO_DESC_EC },
    { "BTECH2_LAST_DESC", AR_NIC_RMT_ERR_FLG_BTECH2_LAST_DESC_BP, AR_NIC_RMT_ERR_FLG_BTECH2_LAST_DESC_EC },
    { "BTECH1_NO_DESC", AR_NIC_RMT_ERR_FLG_BTECH1_NO_DESC_BP, AR_NIC_RMT_ERR_FLG_BTECH1_NO_DESC_EC },
    { "BTECH1_LAST_DESC", AR_NIC_RMT_ERR_FLG_BTECH1_LAST_DESC_BP, AR_NIC_RMT_ERR_FLG_BTECH1_LAST_DESC_EC },
    { "BTECH0_NO_DESC", AR_NIC_RMT_ERR_FLG_BTECH0_NO_DESC_BP, AR_NIC_RMT_ERR_FLG_BTECH0_NO_DESC_EC },
    { "BTECH0_LAST_DESC", AR_NIC_RMT_ERR_FLG_BTECH0_LAST_DESC_BP, AR_NIC_RMT_ERR_FLG_BTECH0_LAST_DESC_EC },
    { "DSMN_CAM_PARITY", AR_NIC_RMT_ERR_FLG_DSMN_CAM_PARITY_BP, AR_NIC_RMT_ERR_FLG_DSMN_CAM_PARITY_EC },
    { "SEND_CAM_PARITY", AR_NIC_RMT_ERR_FLG_SEND_CAM_PARITY_BP, AR_NIC_RMT_ERR_FLG_SEND_CAM_PARITY_EC },
    { "DSMN_TIMEOUT", AR_NIC_RMT_ERR_FLG_DSMN_TIMEOUT_BP, AR_NIC_RMT_ERR_FLG_DSMN_TIMEOUT_EC },
    { "SEND_TIMEOUT", AR_NIC_RMT_ERR_FLG_SEND_TIMEOUT_BP, AR_NIC_RMT_ERR_FLG_SEND_TIMEOUT_EC },
    { "RX_OVERRUN", AR_NIC_RMT_ERR_FLG_RX_OVERRUN_BP, AR_NIC_RMT_ERR_FLG_RX_OVERRUN_EC },
    { "RX_SEND_CAM_MISS", AR_NIC_RMT_ERR_FLG_RX_SEND_CAM_MISS_BP, AR_NIC_RMT_ERR_FLG_RX_SEND_CAM_MISS_EC },
    { "RX_BTECH_UNAVAILABLE", AR_NIC_RMT_ERR_FLG_RX_BTECH_UNAVAILABLE_BP, AR_NIC_RMT_ERR_FLG_RX_BTECH_UNAVAILABLE_EC },
    { "RX_DESC_BTECH_INV", AR_NIC_RMT_ERR_FLG_RX_DESC_BTECH_INV_BP, AR_NIC_RMT_ERR_FLG_RX_DESC_BTECH_INV_EC },
    { "UNDELIVERABLE_CQE", AR_NIC_RMT_ERR_FLG_UNDELIVERABLE_CQE_BP, AR_NIC_RMT_ERR_FLG_UNDELIVERABLE_CQE_EC },
    { "MALFORMED_PKT", AR_NIC_RMT_ERR_FLG_MALFORMED_PKT_BP, AR_NIC_RMT_ERR_FLG_MALFORMED_PKT_EC },
    { "DESC_TBL_MBE", AR_NIC_RMT_ERR_FLG_DESC_TBL_MBE_BP, AR_NIC_RMT_ERR_FLG_DESC_TBL_MBE_EC },
    { "DESC_TBL_SBE", AR_NIC_RMT_ERR_FLG_DESC_TBL_SBE_BP, AR_NIC_RMT_ERR_FLG_DESC_TBL_SBE_EC },
    { "SEQ_TBL_MBE", AR_NIC_RMT_ERR_FLG_SEQ_TBL_MBE_BP, AR_NIC_RMT_ERR_FLG_SEQ_TBL_MBE_EC },
    { "SEQ_TBL_SBE", AR_NIC_RMT_ERR_FLG_SEQ_TBL_SBE_BP, AR_NIC_RMT_ERR_FLG_SEQ_TBL_SBE_EC },
    { "PROTOCOL_ERR", AR_NIC_RMT_ERR_FLG_PROTOCOL_ERR_BP, AR_NIC_RMT_ERR_FLG_PROTOCOL_ERR_EC },
    { "PAYLOAD_MBE_DROP", AR_NIC_RMT_ERR_FLG_PAYLOAD_MBE_DROP_BP, AR_NIC_RMT_ERR_FLG_PAYLOAD_MBE_DROP_EC },
    { "PAYLOAD_MBE", AR_NIC_RMT_ERR_FLG_PAYLOAD_MBE_BP, AR_NIC_RMT_ERR_FLG_PAYLOAD_MBE_EC },
    { "PAYLOAD_SBE", AR_NIC_RMT_ERR_FLG_PAYLOAD_SBE_BP, AR_NIC_RMT_ERR_FLG_PAYLOAD_SBE_EC },
    { "INQ_PARITY", AR_NIC_RMT_ERR_FLG_INQ_PARITY_BP, AR_NIC_RMT_ERR_FLG_INQ_PARITY_EC },
    { "DIAG_ONLY", AR_NIC_RMT_ERR_FLG_DIAG_ONLY_BP, AR_NIC_RMT_ERR_FLG_DIAG_ONLY_EC },
    { NULL, 0, 0 }
};
#endif
static const generic_mmrd_t _ar_nic_rmt_err_clr_detail[] = {
    { "STALL_DROPPED", AR_NIC_RMT_ERR_CLR_STALL_DROPPED_BP, AR_NIC_RMT_ERR_CLR_STALL_DROPPED_MASK },
    { "BTECH3_NO_DESC", AR_NIC_RMT_ERR_CLR_BTECH3_NO_DESC_BP, AR_NIC_RMT_ERR_CLR_BTECH3_NO_DESC_MASK },
    { "BTECH3_LAST_DESC", AR_NIC_RMT_ERR_CLR_BTECH3_LAST_DESC_BP, AR_NIC_RMT_ERR_CLR_BTECH3_LAST_DESC_MASK },
    { "BTECH2_NO_DESC", AR_NIC_RMT_ERR_CLR_BTECH2_NO_DESC_BP, AR_NIC_RMT_ERR_CLR_BTECH2_NO_DESC_MASK },
    { "BTECH2_LAST_DESC", AR_NIC_RMT_ERR_CLR_BTECH2_LAST_DESC_BP, AR_NIC_RMT_ERR_CLR_BTECH2_LAST_DESC_MASK },
    { "BTECH1_NO_DESC", AR_NIC_RMT_ERR_CLR_BTECH1_NO_DESC_BP, AR_NIC_RMT_ERR_CLR_BTECH1_NO_DESC_MASK },
    { "BTECH1_LAST_DESC", AR_NIC_RMT_ERR_CLR_BTECH1_LAST_DESC_BP, AR_NIC_RMT_ERR_CLR_BTECH1_LAST_DESC_MASK },
    { "BTECH0_NO_DESC", AR_NIC_RMT_ERR_CLR_BTECH0_NO_DESC_BP, AR_NIC_RMT_ERR_CLR_BTECH0_NO_DESC_MASK },
    { "BTECH0_LAST_DESC", AR_NIC_RMT_ERR_CLR_BTECH0_LAST_DESC_BP, AR_NIC_RMT_ERR_CLR_BTECH0_LAST_DESC_MASK },
    { "DSMN_CAM_PARITY", AR_NIC_RMT_ERR_CLR_DSMN_CAM_PARITY_BP, AR_NIC_RMT_ERR_CLR_DSMN_CAM_PARITY_MASK },
    { "SEND_CAM_PARITY", AR_NIC_RMT_ERR_CLR_SEND_CAM_PARITY_BP, AR_NIC_RMT_ERR_CLR_SEND_CAM_PARITY_MASK },
    { "DSMN_TIMEOUT", AR_NIC_RMT_ERR_CLR_DSMN_TIMEOUT_BP, AR_NIC_RMT_ERR_CLR_DSMN_TIMEOUT_MASK },
    { "SEND_TIMEOUT", AR_NIC_RMT_ERR_CLR_SEND_TIMEOUT_BP, AR_NIC_RMT_ERR_CLR_SEND_TIMEOUT_MASK },
    { "RX_OVERRUN", AR_NIC_RMT_ERR_CLR_RX_OVERRUN_BP, AR_NIC_RMT_ERR_CLR_RX_OVERRUN_MASK },
    { "RX_SEND_CAM_MISS", AR_NIC_RMT_ERR_CLR_RX_SEND_CAM_MISS_BP, AR_NIC_RMT_ERR_CLR_RX_SEND_CAM_MISS_MASK },
    { "RX_BTECH_UNAVAILABLE", AR_NIC_RMT_ERR_CLR_RX_BTECH_UNAVAILABLE_BP, AR_NIC_RMT_ERR_CLR_RX_BTECH_UNAVAILABLE_MASK },
    { "RX_DESC_BTECH_INV", AR_NIC_RMT_ERR_CLR_RX_DESC_BTECH_INV_BP, AR_NIC_RMT_ERR_CLR_RX_DESC_BTECH_INV_MASK },
    { "UNDELIVERABLE_CQE", AR_NIC_RMT_ERR_CLR_UNDELIVERABLE_CQE_BP, AR_NIC_RMT_ERR_CLR_UNDELIVERABLE_CQE_MASK },
    { "MALFORMED_PKT", AR_NIC_RMT_ERR_CLR_MALFORMED_PKT_BP, AR_NIC_RMT_ERR_CLR_MALFORMED_PKT_MASK },
    { "DESC_TBL_MBE", AR_NIC_RMT_ERR_CLR_DESC_TBL_MBE_BP, AR_NIC_RMT_ERR_CLR_DESC_TBL_MBE_MASK },
    { "DESC_TBL_SBE", AR_NIC_RMT_ERR_CLR_DESC_TBL_SBE_BP, AR_NIC_RMT_ERR_CLR_DESC_TBL_SBE_MASK },
    { "SEQ_TBL_MBE", AR_NIC_RMT_ERR_CLR_SEQ_TBL_MBE_BP, AR_NIC_RMT_ERR_CLR_SEQ_TBL_MBE_MASK },
    { "SEQ_TBL_SBE", AR_NIC_RMT_ERR_CLR_SEQ_TBL_SBE_BP, AR_NIC_RMT_ERR_CLR_SEQ_TBL_SBE_MASK },
    { "PROTOCOL_ERR", AR_NIC_RMT_ERR_CLR_PROTOCOL_ERR_BP, AR_NIC_RMT_ERR_CLR_PROTOCOL_ERR_MASK },
    { "PAYLOAD_MBE_DROP", AR_NIC_RMT_ERR_CLR_PAYLOAD_MBE_DROP_BP, AR_NIC_RMT_ERR_CLR_PAYLOAD_MBE_DROP_MASK },
    { "PAYLOAD_MBE", AR_NIC_RMT_ERR_CLR_PAYLOAD_MBE_BP, AR_NIC_RMT_ERR_CLR_PAYLOAD_MBE_MASK },
    { "PAYLOAD_SBE", AR_NIC_RMT_ERR_CLR_PAYLOAD_SBE_BP, AR_NIC_RMT_ERR_CLR_PAYLOAD_SBE_MASK },
    { "INQ_PARITY", AR_NIC_RMT_ERR_CLR_INQ_PARITY_BP, AR_NIC_RMT_ERR_CLR_INQ_PARITY_MASK },
    { "DIAG_ONLY", AR_NIC_RMT_ERR_CLR_DIAG_ONLY_BP, AR_NIC_RMT_ERR_CLR_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_err_hss_msk_detail[] = {
    { "STALL_DROPPED", AR_NIC_RMT_ERR_HSS_MSK_STALL_DROPPED_BP, AR_NIC_RMT_ERR_HSS_MSK_STALL_DROPPED_MASK },
    { "BTECH3_NO_DESC", AR_NIC_RMT_ERR_HSS_MSK_BTECH3_NO_DESC_BP, AR_NIC_RMT_ERR_HSS_MSK_BTECH3_NO_DESC_MASK },
    { "BTECH3_LAST_DESC", AR_NIC_RMT_ERR_HSS_MSK_BTECH3_LAST_DESC_BP, AR_NIC_RMT_ERR_HSS_MSK_BTECH3_LAST_DESC_MASK },
    { "BTECH2_NO_DESC", AR_NIC_RMT_ERR_HSS_MSK_BTECH2_NO_DESC_BP, AR_NIC_RMT_ERR_HSS_MSK_BTECH2_NO_DESC_MASK },
    { "BTECH2_LAST_DESC", AR_NIC_RMT_ERR_HSS_MSK_BTECH2_LAST_DESC_BP, AR_NIC_RMT_ERR_HSS_MSK_BTECH2_LAST_DESC_MASK },
    { "BTECH1_NO_DESC", AR_NIC_RMT_ERR_HSS_MSK_BTECH1_NO_DESC_BP, AR_NIC_RMT_ERR_HSS_MSK_BTECH1_NO_DESC_MASK },
    { "BTECH1_LAST_DESC", AR_NIC_RMT_ERR_HSS_MSK_BTECH1_LAST_DESC_BP, AR_NIC_RMT_ERR_HSS_MSK_BTECH1_LAST_DESC_MASK },
    { "BTECH0_NO_DESC", AR_NIC_RMT_ERR_HSS_MSK_BTECH0_NO_DESC_BP, AR_NIC_RMT_ERR_HSS_MSK_BTECH0_NO_DESC_MASK },
    { "BTECH0_LAST_DESC", AR_NIC_RMT_ERR_HSS_MSK_BTECH0_LAST_DESC_BP, AR_NIC_RMT_ERR_HSS_MSK_BTECH0_LAST_DESC_MASK },
    { "DSMN_CAM_PARITY", AR_NIC_RMT_ERR_HSS_MSK_DSMN_CAM_PARITY_BP, AR_NIC_RMT_ERR_HSS_MSK_DSMN_CAM_PARITY_MASK },
    { "SEND_CAM_PARITY", AR_NIC_RMT_ERR_HSS_MSK_SEND_CAM_PARITY_BP, AR_NIC_RMT_ERR_HSS_MSK_SEND_CAM_PARITY_MASK },
    { "DSMN_TIMEOUT", AR_NIC_RMT_ERR_HSS_MSK_DSMN_TIMEOUT_BP, AR_NIC_RMT_ERR_HSS_MSK_DSMN_TIMEOUT_MASK },
    { "SEND_TIMEOUT", AR_NIC_RMT_ERR_HSS_MSK_SEND_TIMEOUT_BP, AR_NIC_RMT_ERR_HSS_MSK_SEND_TIMEOUT_MASK },
    { "RX_OVERRUN", AR_NIC_RMT_ERR_HSS_MSK_RX_OVERRUN_BP, AR_NIC_RMT_ERR_HSS_MSK_RX_OVERRUN_MASK },
    { "RX_SEND_CAM_MISS", AR_NIC_RMT_ERR_HSS_MSK_RX_SEND_CAM_MISS_BP, AR_NIC_RMT_ERR_HSS_MSK_RX_SEND_CAM_MISS_MASK },
    { "RX_BTECH_UNAVAILABLE", AR_NIC_RMT_ERR_HSS_MSK_RX_BTECH_UNAVAILABLE_BP, AR_NIC_RMT_ERR_HSS_MSK_RX_BTECH_UNAVAILABLE_MASK },
    { "RX_DESC_BTECH_INV", AR_NIC_RMT_ERR_HSS_MSK_RX_DESC_BTECH_INV_BP, AR_NIC_RMT_ERR_HSS_MSK_RX_DESC_BTECH_INV_MASK },
    { "UNDELIVERABLE_CQE", AR_NIC_RMT_ERR_HSS_MSK_UNDELIVERABLE_CQE_BP, AR_NIC_RMT_ERR_HSS_MSK_UNDELIVERABLE_CQE_MASK },
    { "MALFORMED_PKT", AR_NIC_RMT_ERR_HSS_MSK_MALFORMED_PKT_BP, AR_NIC_RMT_ERR_HSS_MSK_MALFORMED_PKT_MASK },
    { "DESC_TBL_MBE", AR_NIC_RMT_ERR_HSS_MSK_DESC_TBL_MBE_BP, AR_NIC_RMT_ERR_HSS_MSK_DESC_TBL_MBE_MASK },
    { "DESC_TBL_SBE", AR_NIC_RMT_ERR_HSS_MSK_DESC_TBL_SBE_BP, AR_NIC_RMT_ERR_HSS_MSK_DESC_TBL_SBE_MASK },
    { "SEQ_TBL_MBE", AR_NIC_RMT_ERR_HSS_MSK_SEQ_TBL_MBE_BP, AR_NIC_RMT_ERR_HSS_MSK_SEQ_TBL_MBE_MASK },
    { "SEQ_TBL_SBE", AR_NIC_RMT_ERR_HSS_MSK_SEQ_TBL_SBE_BP, AR_NIC_RMT_ERR_HSS_MSK_SEQ_TBL_SBE_MASK },
    { "PROTOCOL_ERR", AR_NIC_RMT_ERR_HSS_MSK_PROTOCOL_ERR_BP, AR_NIC_RMT_ERR_HSS_MSK_PROTOCOL_ERR_MASK },
    { "PAYLOAD_MBE_DROP", AR_NIC_RMT_ERR_HSS_MSK_PAYLOAD_MBE_DROP_BP, AR_NIC_RMT_ERR_HSS_MSK_PAYLOAD_MBE_DROP_MASK },
    { "PAYLOAD_MBE", AR_NIC_RMT_ERR_HSS_MSK_PAYLOAD_MBE_BP, AR_NIC_RMT_ERR_HSS_MSK_PAYLOAD_MBE_MASK },
    { "PAYLOAD_SBE", AR_NIC_RMT_ERR_HSS_MSK_PAYLOAD_SBE_BP, AR_NIC_RMT_ERR_HSS_MSK_PAYLOAD_SBE_MASK },
    { "INQ_PARITY", AR_NIC_RMT_ERR_HSS_MSK_INQ_PARITY_BP, AR_NIC_RMT_ERR_HSS_MSK_INQ_PARITY_MASK },
    { "DIAG_ONLY", AR_NIC_RMT_ERR_HSS_MSK_DIAG_ONLY_BP, AR_NIC_RMT_ERR_HSS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_err_os_msk_detail[] = {
    { "STALL_DROPPED", AR_NIC_RMT_ERR_OS_MSK_STALL_DROPPED_BP, AR_NIC_RMT_ERR_OS_MSK_STALL_DROPPED_MASK },
    { "BTECH3_NO_DESC", AR_NIC_RMT_ERR_OS_MSK_BTECH3_NO_DESC_BP, AR_NIC_RMT_ERR_OS_MSK_BTECH3_NO_DESC_MASK },
    { "BTECH3_LAST_DESC", AR_NIC_RMT_ERR_OS_MSK_BTECH3_LAST_DESC_BP, AR_NIC_RMT_ERR_OS_MSK_BTECH3_LAST_DESC_MASK },
    { "BTECH2_NO_DESC", AR_NIC_RMT_ERR_OS_MSK_BTECH2_NO_DESC_BP, AR_NIC_RMT_ERR_OS_MSK_BTECH2_NO_DESC_MASK },
    { "BTECH2_LAST_DESC", AR_NIC_RMT_ERR_OS_MSK_BTECH2_LAST_DESC_BP, AR_NIC_RMT_ERR_OS_MSK_BTECH2_LAST_DESC_MASK },
    { "BTECH1_NO_DESC", AR_NIC_RMT_ERR_OS_MSK_BTECH1_NO_DESC_BP, AR_NIC_RMT_ERR_OS_MSK_BTECH1_NO_DESC_MASK },
    { "BTECH1_LAST_DESC", AR_NIC_RMT_ERR_OS_MSK_BTECH1_LAST_DESC_BP, AR_NIC_RMT_ERR_OS_MSK_BTECH1_LAST_DESC_MASK },
    { "BTECH0_NO_DESC", AR_NIC_RMT_ERR_OS_MSK_BTECH0_NO_DESC_BP, AR_NIC_RMT_ERR_OS_MSK_BTECH0_NO_DESC_MASK },
    { "BTECH0_LAST_DESC", AR_NIC_RMT_ERR_OS_MSK_BTECH0_LAST_DESC_BP, AR_NIC_RMT_ERR_OS_MSK_BTECH0_LAST_DESC_MASK },
    { "DSMN_CAM_PARITY", AR_NIC_RMT_ERR_OS_MSK_DSMN_CAM_PARITY_BP, AR_NIC_RMT_ERR_OS_MSK_DSMN_CAM_PARITY_MASK },
    { "SEND_CAM_PARITY", AR_NIC_RMT_ERR_OS_MSK_SEND_CAM_PARITY_BP, AR_NIC_RMT_ERR_OS_MSK_SEND_CAM_PARITY_MASK },
    { "DSMN_TIMEOUT", AR_NIC_RMT_ERR_OS_MSK_DSMN_TIMEOUT_BP, AR_NIC_RMT_ERR_OS_MSK_DSMN_TIMEOUT_MASK },
    { "SEND_TIMEOUT", AR_NIC_RMT_ERR_OS_MSK_SEND_TIMEOUT_BP, AR_NIC_RMT_ERR_OS_MSK_SEND_TIMEOUT_MASK },
    { "RX_OVERRUN", AR_NIC_RMT_ERR_OS_MSK_RX_OVERRUN_BP, AR_NIC_RMT_ERR_OS_MSK_RX_OVERRUN_MASK },
    { "RX_SEND_CAM_MISS", AR_NIC_RMT_ERR_OS_MSK_RX_SEND_CAM_MISS_BP, AR_NIC_RMT_ERR_OS_MSK_RX_SEND_CAM_MISS_MASK },
    { "RX_BTECH_UNAVAILABLE", AR_NIC_RMT_ERR_OS_MSK_RX_BTECH_UNAVAILABLE_BP, AR_NIC_RMT_ERR_OS_MSK_RX_BTECH_UNAVAILABLE_MASK },
    { "RX_DESC_BTECH_INV", AR_NIC_RMT_ERR_OS_MSK_RX_DESC_BTECH_INV_BP, AR_NIC_RMT_ERR_OS_MSK_RX_DESC_BTECH_INV_MASK },
    { "UNDELIVERABLE_CQE", AR_NIC_RMT_ERR_OS_MSK_UNDELIVERABLE_CQE_BP, AR_NIC_RMT_ERR_OS_MSK_UNDELIVERABLE_CQE_MASK },
    { "MALFORMED_PKT", AR_NIC_RMT_ERR_OS_MSK_MALFORMED_PKT_BP, AR_NIC_RMT_ERR_OS_MSK_MALFORMED_PKT_MASK },
    { "DESC_TBL_MBE", AR_NIC_RMT_ERR_OS_MSK_DESC_TBL_MBE_BP, AR_NIC_RMT_ERR_OS_MSK_DESC_TBL_MBE_MASK },
    { "DESC_TBL_SBE", AR_NIC_RMT_ERR_OS_MSK_DESC_TBL_SBE_BP, AR_NIC_RMT_ERR_OS_MSK_DESC_TBL_SBE_MASK },
    { "SEQ_TBL_MBE", AR_NIC_RMT_ERR_OS_MSK_SEQ_TBL_MBE_BP, AR_NIC_RMT_ERR_OS_MSK_SEQ_TBL_MBE_MASK },
    { "SEQ_TBL_SBE", AR_NIC_RMT_ERR_OS_MSK_SEQ_TBL_SBE_BP, AR_NIC_RMT_ERR_OS_MSK_SEQ_TBL_SBE_MASK },
    { "PROTOCOL_ERR", AR_NIC_RMT_ERR_OS_MSK_PROTOCOL_ERR_BP, AR_NIC_RMT_ERR_OS_MSK_PROTOCOL_ERR_MASK },
    { "PAYLOAD_MBE_DROP", AR_NIC_RMT_ERR_OS_MSK_PAYLOAD_MBE_DROP_BP, AR_NIC_RMT_ERR_OS_MSK_PAYLOAD_MBE_DROP_MASK },
    { "PAYLOAD_MBE", AR_NIC_RMT_ERR_OS_MSK_PAYLOAD_MBE_BP, AR_NIC_RMT_ERR_OS_MSK_PAYLOAD_MBE_MASK },
    { "PAYLOAD_SBE", AR_NIC_RMT_ERR_OS_MSK_PAYLOAD_SBE_BP, AR_NIC_RMT_ERR_OS_MSK_PAYLOAD_SBE_MASK },
    { "INQ_PARITY", AR_NIC_RMT_ERR_OS_MSK_INQ_PARITY_BP, AR_NIC_RMT_ERR_OS_MSK_INQ_PARITY_MASK },
    { "DIAG_ONLY", AR_NIC_RMT_ERR_OS_MSK_DIAG_ONLY_BP, AR_NIC_RMT_ERR_OS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_err_first_flg_detail[] = {
    { "STALL_DROPPED", AR_NIC_RMT_ERR_FIRST_FLG_STALL_DROPPED_BP, AR_NIC_RMT_ERR_FIRST_FLG_STALL_DROPPED_MASK },
    { "BTECH3_NO_DESC", AR_NIC_RMT_ERR_FIRST_FLG_BTECH3_NO_DESC_BP, AR_NIC_RMT_ERR_FIRST_FLG_BTECH3_NO_DESC_MASK },
    { "BTECH3_LAST_DESC", AR_NIC_RMT_ERR_FIRST_FLG_BTECH3_LAST_DESC_BP, AR_NIC_RMT_ERR_FIRST_FLG_BTECH3_LAST_DESC_MASK },
    { "BTECH2_NO_DESC", AR_NIC_RMT_ERR_FIRST_FLG_BTECH2_NO_DESC_BP, AR_NIC_RMT_ERR_FIRST_FLG_BTECH2_NO_DESC_MASK },
    { "BTECH2_LAST_DESC", AR_NIC_RMT_ERR_FIRST_FLG_BTECH2_LAST_DESC_BP, AR_NIC_RMT_ERR_FIRST_FLG_BTECH2_LAST_DESC_MASK },
    { "BTECH1_NO_DESC", AR_NIC_RMT_ERR_FIRST_FLG_BTECH1_NO_DESC_BP, AR_NIC_RMT_ERR_FIRST_FLG_BTECH1_NO_DESC_MASK },
    { "BTECH1_LAST_DESC", AR_NIC_RMT_ERR_FIRST_FLG_BTECH1_LAST_DESC_BP, AR_NIC_RMT_ERR_FIRST_FLG_BTECH1_LAST_DESC_MASK },
    { "BTECH0_NO_DESC", AR_NIC_RMT_ERR_FIRST_FLG_BTECH0_NO_DESC_BP, AR_NIC_RMT_ERR_FIRST_FLG_BTECH0_NO_DESC_MASK },
    { "BTECH0_LAST_DESC", AR_NIC_RMT_ERR_FIRST_FLG_BTECH0_LAST_DESC_BP, AR_NIC_RMT_ERR_FIRST_FLG_BTECH0_LAST_DESC_MASK },
    { "DSMN_CAM_PARITY", AR_NIC_RMT_ERR_FIRST_FLG_DSMN_CAM_PARITY_BP, AR_NIC_RMT_ERR_FIRST_FLG_DSMN_CAM_PARITY_MASK },
    { "SEND_CAM_PARITY", AR_NIC_RMT_ERR_FIRST_FLG_SEND_CAM_PARITY_BP, AR_NIC_RMT_ERR_FIRST_FLG_SEND_CAM_PARITY_MASK },
    { "DSMN_TIMEOUT", AR_NIC_RMT_ERR_FIRST_FLG_DSMN_TIMEOUT_BP, AR_NIC_RMT_ERR_FIRST_FLG_DSMN_TIMEOUT_MASK },
    { "SEND_TIMEOUT", AR_NIC_RMT_ERR_FIRST_FLG_SEND_TIMEOUT_BP, AR_NIC_RMT_ERR_FIRST_FLG_SEND_TIMEOUT_MASK },
    { "RX_OVERRUN", AR_NIC_RMT_ERR_FIRST_FLG_RX_OVERRUN_BP, AR_NIC_RMT_ERR_FIRST_FLG_RX_OVERRUN_MASK },
    { "RX_SEND_CAM_MISS", AR_NIC_RMT_ERR_FIRST_FLG_RX_SEND_CAM_MISS_BP, AR_NIC_RMT_ERR_FIRST_FLG_RX_SEND_CAM_MISS_MASK },
    { "RX_BTECH_UNAVAILABLE", AR_NIC_RMT_ERR_FIRST_FLG_RX_BTECH_UNAVAILABLE_BP, AR_NIC_RMT_ERR_FIRST_FLG_RX_BTECH_UNAVAILABLE_MASK },
    { "RX_DESC_BTECH_INV", AR_NIC_RMT_ERR_FIRST_FLG_RX_DESC_BTECH_INV_BP, AR_NIC_RMT_ERR_FIRST_FLG_RX_DESC_BTECH_INV_MASK },
    { "UNDELIVERABLE_CQE", AR_NIC_RMT_ERR_FIRST_FLG_UNDELIVERABLE_CQE_BP, AR_NIC_RMT_ERR_FIRST_FLG_UNDELIVERABLE_CQE_MASK },
    { "MALFORMED_PKT", AR_NIC_RMT_ERR_FIRST_FLG_MALFORMED_PKT_BP, AR_NIC_RMT_ERR_FIRST_FLG_MALFORMED_PKT_MASK },
    { "DESC_TBL_MBE", AR_NIC_RMT_ERR_FIRST_FLG_DESC_TBL_MBE_BP, AR_NIC_RMT_ERR_FIRST_FLG_DESC_TBL_MBE_MASK },
    { "DESC_TBL_SBE", AR_NIC_RMT_ERR_FIRST_FLG_DESC_TBL_SBE_BP, AR_NIC_RMT_ERR_FIRST_FLG_DESC_TBL_SBE_MASK },
    { "SEQ_TBL_MBE", AR_NIC_RMT_ERR_FIRST_FLG_SEQ_TBL_MBE_BP, AR_NIC_RMT_ERR_FIRST_FLG_SEQ_TBL_MBE_MASK },
    { "SEQ_TBL_SBE", AR_NIC_RMT_ERR_FIRST_FLG_SEQ_TBL_SBE_BP, AR_NIC_RMT_ERR_FIRST_FLG_SEQ_TBL_SBE_MASK },
    { "PROTOCOL_ERR", AR_NIC_RMT_ERR_FIRST_FLG_PROTOCOL_ERR_BP, AR_NIC_RMT_ERR_FIRST_FLG_PROTOCOL_ERR_MASK },
    { "PAYLOAD_MBE_DROP", AR_NIC_RMT_ERR_FIRST_FLG_PAYLOAD_MBE_DROP_BP, AR_NIC_RMT_ERR_FIRST_FLG_PAYLOAD_MBE_DROP_MASK },
    { "PAYLOAD_MBE", AR_NIC_RMT_ERR_FIRST_FLG_PAYLOAD_MBE_BP, AR_NIC_RMT_ERR_FIRST_FLG_PAYLOAD_MBE_MASK },
    { "PAYLOAD_SBE", AR_NIC_RMT_ERR_FIRST_FLG_PAYLOAD_SBE_BP, AR_NIC_RMT_ERR_FIRST_FLG_PAYLOAD_SBE_MASK },
    { "INQ_PARITY", AR_NIC_RMT_ERR_FIRST_FLG_INQ_PARITY_BP, AR_NIC_RMT_ERR_FIRST_FLG_INQ_PARITY_MASK },
    { "DIAG_ONLY", AR_NIC_RMT_ERR_FIRST_FLG_DIAG_ONLY_BP, AR_NIC_RMT_ERR_FIRST_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_err_info_hss_msk_detail[] = {
    { "MSK", AR_NIC_RMT_ERR_INFO_HSS_MSK_MSK_BP, AR_NIC_RMT_ERR_INFO_HSS_MSK_MSK_MASK },
    { "DIAG_ONLY", AR_NIC_RMT_ERR_INFO_HSS_MSK_DIAG_ONLY_BP, AR_NIC_RMT_ERR_INFO_HSS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_err_info_os_msk_detail[] = {
    { "MSK", AR_NIC_RMT_ERR_INFO_OS_MSK_MSK_BP, AR_NIC_RMT_ERR_INFO_OS_MSK_MSK_MASK },
    { "DIAG_ONLY", AR_NIC_RMT_ERR_INFO_OS_MSK_DIAG_ONLY_BP, AR_NIC_RMT_ERR_INFO_OS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_err_info_desc_tbl_ecc_detail[] = {
    { "MBE_ADDRESS", AR_NIC_RMT_ERR_INFO_DESC_TBL_ECC_MBE_ADDRESS_BP, AR_NIC_RMT_ERR_INFO_DESC_TBL_ECC_MBE_ADDRESS_MASK },
    { "MBE_SYNDROME", AR_NIC_RMT_ERR_INFO_DESC_TBL_ECC_MBE_SYNDROME_BP, AR_NIC_RMT_ERR_INFO_DESC_TBL_ECC_MBE_SYNDROME_MASK },
    { "SBE_ADDRESS", AR_NIC_RMT_ERR_INFO_DESC_TBL_ECC_SBE_ADDRESS_BP, AR_NIC_RMT_ERR_INFO_DESC_TBL_ECC_SBE_ADDRESS_MASK },
    { "SBE_SYNDROME", AR_NIC_RMT_ERR_INFO_DESC_TBL_ECC_SBE_SYNDROME_BP, AR_NIC_RMT_ERR_INFO_DESC_TBL_ECC_SBE_SYNDROME_MASK },
    { "MMR_DETECTED_MBE", AR_NIC_RMT_ERR_INFO_DESC_TBL_ECC_MMR_DETECTED_MBE_BP, AR_NIC_RMT_ERR_INFO_DESC_TBL_ECC_MMR_DETECTED_MBE_MASK },
    { "MMR_DETECTED_SBE", AR_NIC_RMT_ERR_INFO_DESC_TBL_ECC_MMR_DETECTED_SBE_BP, AR_NIC_RMT_ERR_INFO_DESC_TBL_ECC_MMR_DETECTED_SBE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_err_info_seq_tbl_ecc_detail[] = {
    { "MBE_RAM_MSK", AR_NIC_RMT_ERR_INFO_SEQ_TBL_ECC_MBE_RAM_MSK_BP, AR_NIC_RMT_ERR_INFO_SEQ_TBL_ECC_MBE_RAM_MSK_MASK },
    { "MBE_ADDRESS", AR_NIC_RMT_ERR_INFO_SEQ_TBL_ECC_MBE_ADDRESS_BP, AR_NIC_RMT_ERR_INFO_SEQ_TBL_ECC_MBE_ADDRESS_MASK },
    { "MBE_SYNDROME", AR_NIC_RMT_ERR_INFO_SEQ_TBL_ECC_MBE_SYNDROME_BP, AR_NIC_RMT_ERR_INFO_SEQ_TBL_ECC_MBE_SYNDROME_MASK },
    { "SBE_RAM_MSK", AR_NIC_RMT_ERR_INFO_SEQ_TBL_ECC_SBE_RAM_MSK_BP, AR_NIC_RMT_ERR_INFO_SEQ_TBL_ECC_SBE_RAM_MSK_MASK },
    { "SBE_ADDRESS", AR_NIC_RMT_ERR_INFO_SEQ_TBL_ECC_SBE_ADDRESS_BP, AR_NIC_RMT_ERR_INFO_SEQ_TBL_ECC_SBE_ADDRESS_MASK },
    { "SBE_SYNDROME", AR_NIC_RMT_ERR_INFO_SEQ_TBL_ECC_SBE_SYNDROME_BP, AR_NIC_RMT_ERR_INFO_SEQ_TBL_ECC_SBE_SYNDROME_MASK },
    { "MMR_DETECTED_MBE", AR_NIC_RMT_ERR_INFO_SEQ_TBL_ECC_MMR_DETECTED_MBE_BP, AR_NIC_RMT_ERR_INFO_SEQ_TBL_ECC_MMR_DETECTED_MBE_MASK },
    { "MMR_DETECTED_SBE", AR_NIC_RMT_ERR_INFO_SEQ_TBL_ECC_MMR_DETECTED_SBE_BP, AR_NIC_RMT_ERR_INFO_SEQ_TBL_ECC_MMR_DETECTED_SBE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_err_info_inq_parity_detail[] = {
    { "MSK", AR_NIC_RMT_ERR_INFO_INQ_PARITY_MSK_BP, AR_NIC_RMT_ERR_INFO_INQ_PARITY_MSK_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_err_info_payload_ecc_detail[] = {
    { "MBE_MSK", AR_NIC_RMT_ERR_INFO_PAYLOAD_ECC_MBE_MSK_BP, AR_NIC_RMT_ERR_INFO_PAYLOAD_ECC_MBE_MSK_MASK },
    { "MBE_SYNDROME", AR_NIC_RMT_ERR_INFO_PAYLOAD_ECC_MBE_SYNDROME_BP, AR_NIC_RMT_ERR_INFO_PAYLOAD_ECC_MBE_SYNDROME_MASK },
    { "SBE_MSK", AR_NIC_RMT_ERR_INFO_PAYLOAD_ECC_SBE_MSK_BP, AR_NIC_RMT_ERR_INFO_PAYLOAD_ECC_SBE_MSK_MASK },
    { "SBE_SYNDROME", AR_NIC_RMT_ERR_INFO_PAYLOAD_ECC_SBE_SYNDROME_BP, AR_NIC_RMT_ERR_INFO_PAYLOAD_ECC_SBE_SYNDROME_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_err_info_hss_pkt_detail[] = {
    { "ERR_FLG_NUM", AR_NIC_RMT_ERR_INFO_HSS_PKT_ERR_FLG_NUM_BP, AR_NIC_RMT_ERR_INFO_HSS_PKT_ERR_FLG_NUM_MASK },
    { "CAM_HIT", AR_NIC_RMT_ERR_INFO_HSS_PKT_CAM_HIT_BP, AR_NIC_RMT_ERR_INFO_HSS_PKT_CAM_HIT_MASK },
    { "CAM_FILL", AR_NIC_RMT_ERR_INFO_HSS_PKT_CAM_FILL_BP, AR_NIC_RMT_ERR_INFO_HSS_PKT_CAM_FILL_MASK },
    { "CAM_IDX", AR_NIC_RMT_ERR_INFO_HSS_PKT_CAM_IDX_BP, AR_NIC_RMT_ERR_INFO_HSS_PKT_CAM_IDX_MASK },
    { "PKTID", AR_NIC_RMT_ERR_INFO_HSS_PKT_PKTID_BP, AR_NIC_RMT_ERR_INFO_HSS_PKT_PKTID_MASK },
    { "REQCMD", AR_NIC_RMT_ERR_INFO_HSS_PKT_REQCMD_BP, AR_NIC_RMT_ERR_INFO_HSS_PKT_REQCMD_MASK },
    { "SOURCE", AR_NIC_RMT_ERR_INFO_HSS_PKT_SOURCE_BP, AR_NIC_RMT_ERR_INFO_HSS_PKT_SOURCE_MASK },
    { "SRCID", AR_NIC_RMT_ERR_INFO_HSS_PKT_SRCID_BP, AR_NIC_RMT_ERR_INFO_HSS_PKT_SRCID_MASK },
    { "SSID", AR_NIC_RMT_ERR_INFO_HSS_PKT_SSID_BP, AR_NIC_RMT_ERR_INFO_HSS_PKT_SSID_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_err_info_os_pkt_detail[] = {
    { "ERR_FLG_NUM", AR_NIC_RMT_ERR_INFO_OS_PKT_ERR_FLG_NUM_BP, AR_NIC_RMT_ERR_INFO_OS_PKT_ERR_FLG_NUM_MASK },
    { "CAM_HIT", AR_NIC_RMT_ERR_INFO_OS_PKT_CAM_HIT_BP, AR_NIC_RMT_ERR_INFO_OS_PKT_CAM_HIT_MASK },
    { "CAM_FILL", AR_NIC_RMT_ERR_INFO_OS_PKT_CAM_FILL_BP, AR_NIC_RMT_ERR_INFO_OS_PKT_CAM_FILL_MASK },
    { "CAM_IDX", AR_NIC_RMT_ERR_INFO_OS_PKT_CAM_IDX_BP, AR_NIC_RMT_ERR_INFO_OS_PKT_CAM_IDX_MASK },
    { "PKTID", AR_NIC_RMT_ERR_INFO_OS_PKT_PKTID_BP, AR_NIC_RMT_ERR_INFO_OS_PKT_PKTID_MASK },
    { "REQCMD", AR_NIC_RMT_ERR_INFO_OS_PKT_REQCMD_BP, AR_NIC_RMT_ERR_INFO_OS_PKT_REQCMD_MASK },
    { "SOURCE", AR_NIC_RMT_ERR_INFO_OS_PKT_SOURCE_BP, AR_NIC_RMT_ERR_INFO_OS_PKT_SOURCE_MASK },
    { "SRCID", AR_NIC_RMT_ERR_INFO_OS_PKT_SRCID_BP, AR_NIC_RMT_ERR_INFO_OS_PKT_SRCID_MASK },
    { "SSID", AR_NIC_RMT_ERR_INFO_OS_PKT_SSID_BP, AR_NIC_RMT_ERR_INFO_OS_PKT_SSID_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_dbg_errinj_desc_tbl_detail[] = {
    { "ADDRESS", AR_NIC_RMT_DBG_ERRINJ_DESC_TBL_ADDRESS_BP, AR_NIC_RMT_DBG_ERRINJ_DESC_TBL_ADDRESS_MASK },
    { "CHECKBITS", AR_NIC_RMT_DBG_ERRINJ_DESC_TBL_CHECKBITS_BP, AR_NIC_RMT_DBG_ERRINJ_DESC_TBL_CHECKBITS_MASK },
    { "TRIGGERED", AR_NIC_RMT_DBG_ERRINJ_DESC_TBL_TRIGGERED_BP, AR_NIC_RMT_DBG_ERRINJ_DESC_TBL_TRIGGERED_MASK },
    { "MODE", AR_NIC_RMT_DBG_ERRINJ_DESC_TBL_MODE_BP, AR_NIC_RMT_DBG_ERRINJ_DESC_TBL_MODE_MASK },
    { "ENABLE", AR_NIC_RMT_DBG_ERRINJ_DESC_TBL_ENABLE_BP, AR_NIC_RMT_DBG_ERRINJ_DESC_TBL_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_dbg_errinj_seq_tbl_detail[] = {
    { "ADDRESS", AR_NIC_RMT_DBG_ERRINJ_SEQ_TBL_ADDRESS_BP, AR_NIC_RMT_DBG_ERRINJ_SEQ_TBL_ADDRESS_MASK },
    { "CHECKBITS", AR_NIC_RMT_DBG_ERRINJ_SEQ_TBL_CHECKBITS_BP, AR_NIC_RMT_DBG_ERRINJ_SEQ_TBL_CHECKBITS_MASK },
    { "MSK", AR_NIC_RMT_DBG_ERRINJ_SEQ_TBL_MSK_BP, AR_NIC_RMT_DBG_ERRINJ_SEQ_TBL_MSK_MASK },
    { "TRIGGERED", AR_NIC_RMT_DBG_ERRINJ_SEQ_TBL_TRIGGERED_BP, AR_NIC_RMT_DBG_ERRINJ_SEQ_TBL_TRIGGERED_MASK },
    { "MODE", AR_NIC_RMT_DBG_ERRINJ_SEQ_TBL_MODE_BP, AR_NIC_RMT_DBG_ERRINJ_SEQ_TBL_MODE_MASK },
    { "ENABLE", AR_NIC_RMT_DBG_ERRINJ_SEQ_TBL_ENABLE_BP, AR_NIC_RMT_DBG_ERRINJ_SEQ_TBL_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_dbg_errinj_inq_detail[] = {
    { "CHECKBITSUP", AR_NIC_RMT_DBG_ERRINJ_INQ_CHECKBITSUP_BP, AR_NIC_RMT_DBG_ERRINJ_INQ_CHECKBITSUP_MASK },
    { "CHECKBITSLO", AR_NIC_RMT_DBG_ERRINJ_INQ_CHECKBITSLO_BP, AR_NIC_RMT_DBG_ERRINJ_INQ_CHECKBITSLO_MASK },
    { "PARITY", AR_NIC_RMT_DBG_ERRINJ_INQ_PARITY_BP, AR_NIC_RMT_DBG_ERRINJ_INQ_PARITY_MASK },
    { "TAIL", AR_NIC_RMT_DBG_ERRINJ_INQ_TAIL_BP, AR_NIC_RMT_DBG_ERRINJ_INQ_TAIL_MASK },
    { "COUNT", AR_NIC_RMT_DBG_ERRINJ_INQ_COUNT_BP, AR_NIC_RMT_DBG_ERRINJ_INQ_COUNT_MASK },
    { "TRIGGERED", AR_NIC_RMT_DBG_ERRINJ_INQ_TRIGGERED_BP, AR_NIC_RMT_DBG_ERRINJ_INQ_TRIGGERED_MASK },
    { "MODE", AR_NIC_RMT_DBG_ERRINJ_INQ_MODE_BP, AR_NIC_RMT_DBG_ERRINJ_INQ_MODE_MASK },
    { "ENABLE", AR_NIC_RMT_DBG_ERRINJ_INQ_ENABLE_BP, AR_NIC_RMT_DBG_ERRINJ_INQ_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_dbg_errinj_cam_detail[] = {
    { "ADDRESS", AR_NIC_RMT_DBG_ERRINJ_CAM_ADDRESS_BP, AR_NIC_RMT_DBG_ERRINJ_CAM_ADDRESS_MASK },
    { "TRIGGERED", AR_NIC_RMT_DBG_ERRINJ_CAM_TRIGGERED_BP, AR_NIC_RMT_DBG_ERRINJ_CAM_TRIGGERED_MASK },
    { "MODE", AR_NIC_RMT_DBG_ERRINJ_CAM_MODE_BP, AR_NIC_RMT_DBG_ERRINJ_CAM_MODE_MASK },
    { "ENABLE", AR_NIC_RMT_DBG_ERRINJ_CAM_ENABLE_BP, AR_NIC_RMT_DBG_ERRINJ_CAM_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_prf_put_bytes_rx_detail[] = {
    { "CNT", AR_NIC_RMT_PRF_PUT_BYTES_RX_CNT_BP, AR_NIC_RMT_PRF_PUT_BYTES_RX_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rmt_prf_send_bytes_rx_detail[] = {
    { "CNT", AR_NIC_RMT_PRF_SEND_BYTES_RX_CNT_BP, AR_NIC_RMT_PRF_SEND_BYTES_RX_CNT_MASK },
    { NULL, 0, 0 }
};

/*
 *  AR RMT MMR DECLARATIONS
 */
static const generic_mmr_t _ar_nic_rmt_rmt_mmr_ring_0_hi_rmt = {
    "AR_NIC_RMT_RMT_MMR_RING_0_HI_RMT", AR_NIC_RMT_RMT_MMR_RING_0_HI_RMT, 8, 1, _ar_nic_rmt_rmt_mmr_ring_0_hi_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_rmt_mmr_ring_0_mid_rmt = {
    "AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT", AR_NIC_RMT_RMT_MMR_RING_0_MID_RMT, 8, 1, _ar_nic_rmt_rmt_mmr_ring_0_mid_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_rmt_mmr_ring_0_lo_rmt = {
    "AR_NIC_RMT_RMT_MMR_RING_0_LO_RMT", AR_NIC_RMT_RMT_MMR_RING_0_LO_RMT, 8, 1, _ar_nic_rmt_rmt_mmr_ring_0_lo_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_err_flg_1_hi_rmt = {
    "AR_NIC_RMT_ERR_FLG_1_HI_RMT", AR_NIC_RMT_ERR_FLG_1_HI_RMT, 8, 1, _ar_nic_rmt_err_flg_1_hi_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_err_flg_1_mid_rmt = {
    "AR_NIC_RMT_ERR_FLG_1_MID_RMT", AR_NIC_RMT_ERR_FLG_1_MID_RMT, 8, 1, _ar_nic_rmt_err_flg_1_mid_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_err_flg_1_lo_rmt = {
    "AR_NIC_RMT_ERR_FLG_1_LO_RMT", AR_NIC_RMT_ERR_FLG_1_LO_RMT, 8, 1, _ar_nic_rmt_err_flg_1_lo_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_rmt_cam_2_hi_rmt = {
    "AR_NIC_RMT_RMT_CAM_2_HI_RMT", AR_NIC_RMT_RMT_CAM_2_HI_RMT, 8, 1, _ar_nic_rmt_rmt_cam_2_hi_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_rmt_cam_2_mid_rmt = {
    "AR_NIC_RMT_RMT_CAM_2_MID_RMT", AR_NIC_RMT_RMT_CAM_2_MID_RMT, 8, 1, _ar_nic_rmt_rmt_cam_2_mid_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_rmt_cam_2_lo_rmt = {
    "AR_NIC_RMT_RMT_CAM_2_LO_RMT", AR_NIC_RMT_RMT_CAM_2_LO_RMT, 8, 1, _ar_nic_rmt_rmt_cam_2_lo_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_rmt_seq_table_3_hi_rmt = {
    "AR_NIC_RMT_RMT_SEQ_TABLE_3_HI_RMT", AR_NIC_RMT_RMT_SEQ_TABLE_3_HI_RMT, 8, 1, _ar_nic_rmt_rmt_seq_table_3_hi_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_rmt_seq_table_3_mid_rmt = {
    "AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT", AR_NIC_RMT_RMT_SEQ_TABLE_3_MID_RMT, 8, 1, _ar_nic_rmt_rmt_seq_table_3_mid_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_rmt_seq_table_3_lo_rmt = {
    "AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT", AR_NIC_RMT_RMT_SEQ_TABLE_3_LO_RMT, 8, 1, _ar_nic_rmt_rmt_seq_table_3_lo_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_rmt_pkt_update_4_hi_rmt = {
    "AR_NIC_RMT_RMT_PKT_UPDATE_4_HI_RMT", AR_NIC_RMT_RMT_PKT_UPDATE_4_HI_RMT, 8, 1, _ar_nic_rmt_rmt_pkt_update_4_hi_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_rmt_pkt_update_4_mid_rmt = {
    "AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT", AR_NIC_RMT_RMT_PKT_UPDATE_4_MID_RMT, 8, 1, _ar_nic_rmt_rmt_pkt_update_4_mid_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_rmt_pkt_update_4_lo_rmt = {
    "AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT", AR_NIC_RMT_RMT_PKT_UPDATE_4_LO_RMT, 8, 1, _ar_nic_rmt_rmt_pkt_update_4_lo_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_rmt_cq_5_hi_rmt = {
    "AR_NIC_RMT_RMT_CQ_5_HI_RMT", AR_NIC_RMT_RMT_CQ_5_HI_RMT, 8, 1, _ar_nic_rmt_rmt_cq_5_hi_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_rmt_cq_5_mid_rmt = {
    "AR_NIC_RMT_RMT_CQ_5_MID_RMT", AR_NIC_RMT_RMT_CQ_5_MID_RMT, 8, 1, _ar_nic_rmt_rmt_cq_5_mid_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_rmt_cq_5_lo_rmt = {
    "AR_NIC_RMT_RMT_CQ_5_LO_RMT", AR_NIC_RMT_RMT_CQ_5_LO_RMT, 8, 1, _ar_nic_rmt_rmt_cq_5_lo_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_rat_rmt_flit_6_hi_rmt = {
    "AR_NIC_RMT_RAT_RMT_FLIT_6_HI_RMT", AR_NIC_RMT_RAT_RMT_FLIT_6_HI_RMT, 8, 1, _ar_nic_rmt_rat_rmt_flit_6_hi_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_rat_rmt_flit_6_mid_rmt = {
    "AR_NIC_RMT_RAT_RMT_FLIT_6_MID_RMT", AR_NIC_RMT_RAT_RMT_FLIT_6_MID_RMT, 8, 1, _ar_nic_rmt_rat_rmt_flit_6_mid_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_rat_rmt_flit_6_lo_rmt = {
    "AR_NIC_RMT_RAT_RMT_FLIT_6_LO_RMT", AR_NIC_RMT_RAT_RMT_FLIT_6_LO_RMT, 8, 1, _ar_nic_rmt_rat_rmt_flit_6_lo_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_rmt_npt_flit_7_hi_rmt = {
    "AR_NIC_RMT_RMT_NPT_FLIT_7_HI_RMT", AR_NIC_RMT_RMT_NPT_FLIT_7_HI_RMT, 8, 1, _ar_nic_rmt_rmt_npt_flit_7_hi_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_rmt_npt_flit_7_mid_rmt = {
    "AR_NIC_RMT_RMT_NPT_FLIT_7_MID_RMT", AR_NIC_RMT_RMT_NPT_FLIT_7_MID_RMT, 8, 1, _ar_nic_rmt_rmt_npt_flit_7_mid_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_rmt_npt_flit_7_lo_rmt = {
    "AR_NIC_RMT_RMT_NPT_FLIT_7_LO_RMT", AR_NIC_RMT_RMT_NPT_FLIT_7_LO_RMT, 8, 1, _ar_nic_rmt_rmt_npt_flit_7_lo_rmt_detail
};
static const generic_mmr_t _ar_nic_rmt_cfg_timer_control = {
    "AR_NIC_RMT_CFG_TIMER_CONTROL", AR_NIC_RMT_CFG_TIMER_CONTROL, 8, 1, _ar_nic_rmt_cfg_timer_control_detail
};
static const generic_mmr_t _ar_nic_rmt_cfg_cam_params0 = {
    "AR_NIC_RMT_CFG_CAM_PARAMS0", AR_NIC_RMT_CFG_CAM_PARAMS0, 8, 1, _ar_nic_rmt_cfg_cam_params0_detail
};
static const generic_mmr_t _ar_nic_rmt_cfg_cam_params1 = {
    "AR_NIC_RMT_CFG_CAM_PARAMS1", AR_NIC_RMT_CFG_CAM_PARAMS1, 8, 1, _ar_nic_rmt_cfg_cam_params1_detail
};
static const generic_mmr_t _ar_nic_rmt_cfg_rx_desc_btech_base_idx = {
    "AR_NIC_RMT_CFG_RX_DESC_BTECH_BASE_IDX", AR_NIC_RMT_CFG_RX_DESC_BTECH_BASE_IDX, 8, 1, _ar_nic_rmt_cfg_rx_desc_btech_base_idx_detail
};
static const generic_mmr_t _ar_nic_rmt_cfg_rx_desc_btech_cnt = {
    "AR_NIC_RMT_CFG_RX_DESC_BTECH_CNT", AR_NIC_RMT_CFG_RX_DESC_BTECH_CNT, 8, 1, _ar_nic_rmt_cfg_rx_desc_btech_cnt_detail
};
static const generic_mmr_t _ar_nic_rmt_err_flg = {
    "AR_NIC_RMT_ERR_FLG", AR_NIC_RMT_ERR_FLG, 8, 1, _ar_nic_rmt_err_flg_detail
};
static const generic_mmr_t _ar_nic_rmt_err_clr = {
    "AR_NIC_RMT_ERR_CLR", AR_NIC_RMT_ERR_CLR, 8, 1, _ar_nic_rmt_err_clr_detail
};
static const generic_mmr_t _ar_nic_rmt_err_hss_msk = {
    "AR_NIC_RMT_ERR_HSS_MSK", AR_NIC_RMT_ERR_HSS_MSK, 8, 1, _ar_nic_rmt_err_hss_msk_detail
};
static const generic_mmr_t _ar_nic_rmt_err_os_msk = {
    "AR_NIC_RMT_ERR_OS_MSK", AR_NIC_RMT_ERR_OS_MSK, 8, 1, _ar_nic_rmt_err_os_msk_detail
};
static const generic_mmr_t _ar_nic_rmt_err_first_flg = {
    "AR_NIC_RMT_ERR_FIRST_FLG", AR_NIC_RMT_ERR_FIRST_FLG, 8, 1, _ar_nic_rmt_err_first_flg_detail
};
static const generic_mmr_t _ar_nic_rmt_err_info_hss_msk = {
    "AR_NIC_RMT_ERR_INFO_HSS_MSK", AR_NIC_RMT_ERR_INFO_HSS_MSK, 8, 1, _ar_nic_rmt_err_info_hss_msk_detail
};
static const generic_mmr_t _ar_nic_rmt_err_info_os_msk = {
    "AR_NIC_RMT_ERR_INFO_OS_MSK", AR_NIC_RMT_ERR_INFO_OS_MSK, 8, 1, _ar_nic_rmt_err_info_os_msk_detail
};
static const generic_mmr_t _ar_nic_rmt_err_info_desc_tbl_ecc = {
    "AR_NIC_RMT_ERR_INFO_DESC_TBL_ECC", AR_NIC_RMT_ERR_INFO_DESC_TBL_ECC, 8, 1, _ar_nic_rmt_err_info_desc_tbl_ecc_detail
};
static const generic_mmr_t _ar_nic_rmt_err_info_seq_tbl_ecc = {
    "AR_NIC_RMT_ERR_INFO_SEQ_TBL_ECC", AR_NIC_RMT_ERR_INFO_SEQ_TBL_ECC, 8, 1, _ar_nic_rmt_err_info_seq_tbl_ecc_detail
};
static const generic_mmr_t _ar_nic_rmt_err_info_inq_parity = {
    "AR_NIC_RMT_ERR_INFO_INQ_PARITY", AR_NIC_RMT_ERR_INFO_INQ_PARITY, 8, 1, _ar_nic_rmt_err_info_inq_parity_detail
};
static const generic_mmr_t _ar_nic_rmt_err_info_payload_ecc = {
    "AR_NIC_RMT_ERR_INFO_PAYLOAD_ECC", AR_NIC_RMT_ERR_INFO_PAYLOAD_ECC, 8, 1, _ar_nic_rmt_err_info_payload_ecc_detail
};
static const generic_mmr_t _ar_nic_rmt_err_info_hss_pkt = {
    "AR_NIC_RMT_ERR_INFO_HSS_PKT", AR_NIC_RMT_ERR_INFO_HSS_PKT, 8, 1, _ar_nic_rmt_err_info_hss_pkt_detail
};
static const generic_mmr_t _ar_nic_rmt_err_info_os_pkt = {
    "AR_NIC_RMT_ERR_INFO_OS_PKT", AR_NIC_RMT_ERR_INFO_OS_PKT, 8, 1, _ar_nic_rmt_err_info_os_pkt_detail
};
static const generic_mmr_t _ar_nic_rmt_dbg_errinj_desc_tbl = {
    "AR_NIC_RMT_DBG_ERRINJ_DESC_TBL", AR_NIC_RMT_DBG_ERRINJ_DESC_TBL, 8, 1, _ar_nic_rmt_dbg_errinj_desc_tbl_detail
};
static const generic_mmr_t _ar_nic_rmt_dbg_errinj_seq_tbl = {
    "AR_NIC_RMT_DBG_ERRINJ_SEQ_TBL", AR_NIC_RMT_DBG_ERRINJ_SEQ_TBL, 8, 1, _ar_nic_rmt_dbg_errinj_seq_tbl_detail
};
static const generic_mmr_t _ar_nic_rmt_dbg_errinj_inq = {
    "AR_NIC_RMT_DBG_ERRINJ_INQ", AR_NIC_RMT_DBG_ERRINJ_INQ, 8, 1, _ar_nic_rmt_dbg_errinj_inq_detail
};
static const generic_mmr_t _ar_nic_rmt_dbg_errinj_cam = {
    "AR_NIC_RMT_DBG_ERRINJ_CAM", AR_NIC_RMT_DBG_ERRINJ_CAM, 8, 1, _ar_nic_rmt_dbg_errinj_cam_detail
};
static const generic_mmr_t _ar_nic_rmt_prf_put_bytes_rx = {
    "AR_NIC_RMT_PRF_PUT_BYTES_RX", AR_NIC_RMT_PRF_PUT_BYTES_RX, 8, 1, _ar_nic_rmt_prf_put_bytes_rx_detail
};
static const generic_mmr_t _ar_nic_rmt_prf_send_bytes_rx = {
    "AR_NIC_RMT_PRF_SEND_BYTES_RX", AR_NIC_RMT_PRF_SEND_BYTES_RX, 8, 1, _ar_nic_rmt_prf_send_bytes_rx_detail
};

/*
 *  INSTALL AR RMT MMRS
 */
static const generic_mmr_t* _ar_rmt_mmrs[] _unused = {
    &_ar_nic_rmt_rmt_mmr_ring_0_hi_rmt,
    &_ar_nic_rmt_rmt_mmr_ring_0_mid_rmt,
    &_ar_nic_rmt_rmt_mmr_ring_0_lo_rmt,
    &_ar_nic_rmt_err_flg_1_hi_rmt,
    &_ar_nic_rmt_err_flg_1_mid_rmt,
    &_ar_nic_rmt_err_flg_1_lo_rmt,
    &_ar_nic_rmt_rmt_cam_2_hi_rmt,
    &_ar_nic_rmt_rmt_cam_2_mid_rmt,
    &_ar_nic_rmt_rmt_cam_2_lo_rmt,
    &_ar_nic_rmt_rmt_seq_table_3_hi_rmt,
    &_ar_nic_rmt_rmt_seq_table_3_mid_rmt,
    &_ar_nic_rmt_rmt_seq_table_3_lo_rmt,
    &_ar_nic_rmt_rmt_pkt_update_4_hi_rmt,
    &_ar_nic_rmt_rmt_pkt_update_4_mid_rmt,
    &_ar_nic_rmt_rmt_pkt_update_4_lo_rmt,
    &_ar_nic_rmt_rmt_cq_5_hi_rmt,
    &_ar_nic_rmt_rmt_cq_5_mid_rmt,
    &_ar_nic_rmt_rmt_cq_5_lo_rmt,
    &_ar_nic_rmt_rat_rmt_flit_6_hi_rmt,
    &_ar_nic_rmt_rat_rmt_flit_6_mid_rmt,
    &_ar_nic_rmt_rat_rmt_flit_6_lo_rmt,
    &_ar_nic_rmt_rmt_npt_flit_7_hi_rmt,
    &_ar_nic_rmt_rmt_npt_flit_7_mid_rmt,
    &_ar_nic_rmt_rmt_npt_flit_7_lo_rmt,
    &_ar_nic_rmt_cfg_timer_control,
    &_ar_nic_rmt_cfg_cam_params0,
    &_ar_nic_rmt_cfg_cam_params1,
    &_ar_nic_rmt_cfg_rx_desc_btech_base_idx,
    &_ar_nic_rmt_cfg_rx_desc_btech_cnt,
    &_ar_nic_rmt_err_flg,
    &_ar_nic_rmt_err_clr,
    &_ar_nic_rmt_err_hss_msk,
    &_ar_nic_rmt_err_os_msk,
    &_ar_nic_rmt_err_first_flg,
    &_ar_nic_rmt_err_info_hss_msk,
    &_ar_nic_rmt_err_info_os_msk,
    &_ar_nic_rmt_err_info_desc_tbl_ecc,
    &_ar_nic_rmt_err_info_seq_tbl_ecc,
    &_ar_nic_rmt_err_info_inq_parity,
    &_ar_nic_rmt_err_info_payload_ecc,
    &_ar_nic_rmt_err_info_hss_pkt,
    &_ar_nic_rmt_err_info_os_pkt,
    &_ar_nic_rmt_dbg_errinj_desc_tbl,
    &_ar_nic_rmt_dbg_errinj_seq_tbl,
    &_ar_nic_rmt_dbg_errinj_inq,
    &_ar_nic_rmt_dbg_errinj_cam,
    &_ar_nic_rmt_prf_put_bytes_rx,
    &_ar_nic_rmt_prf_send_bytes_rx,
    NULL
};

#endif
