/******************************************************************************
 * COPYRIGHT CRAY INC. ar_sbus_mmrs_h.h
 * FILE: ar_sbus_mmrs_h.h
 * Created by v2h.c on Wed Oct  8 14:39:04 2014
 ******************************************************************************/

#ifndef _AR_SBUS_MMRS_H_H_
#define _AR_SBUS_MMRS_H_H_

#ifdef __GNUC__
#define _unused __attribute__((unused))
#else
#define _unused
#endif

#ifndef _GENERIC_MMRD_T_
#define _GENERIC_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint64_t _mask;		/* Field bit mask */
} generic_mmrd_t;
#endif

#ifndef _ERRCAT_MMRD_T_
#define _ERRCAT_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint32_t _ec;		/* Field error category */
} errcat_mmrd_t;
#endif

#ifndef _GENERIC_MMR_T_
#define _GENERIC_MMR_T_
typedef struct {
	char* _name;		/* MMR name */
	uint64_t _addr;		/* MMR address */
	int _size;		/* Size in bytes of MMR */
	int _depth;		/* Number of MMR instances */
	const generic_mmrd_t *_info;	/* MMR detail */
} generic_mmr_t;
#endif

static const generic_mmr_t* _ar_sbus_mmrs[] _unused;	/* SBUS Array */

/*
 *  AR SBUS MMR DETAIL DECLARATIONS
 */
static const generic_mmrd_t _ar_serdes_sbus_00_detail[] = {
    { "RESERVED_31_15", AR_SERDES_SBUS_00_RESERVED_31_15_BP, AR_SERDES_SBUS_00_RESERVED_31_15_MASK },
    { "TX_PHASE_SLIP_CNTL", AR_SERDES_SBUS_00_TX_PHASE_SLIP_CNTL_BP, AR_SERDES_SBUS_00_TX_PHASE_SLIP_CNTL_MASK },
    { "TX_PHASE_CAL_EN_CNTL", AR_SERDES_SBUS_00_TX_PHASE_CAL_EN_CNTL_BP, AR_SERDES_SBUS_00_TX_PHASE_CAL_EN_CNTL_MASK },
    { "TX_PHASE_MASTER_CNTL", AR_SERDES_SBUS_00_TX_PHASE_MASTER_CNTL_BP, AR_SERDES_SBUS_00_TX_PHASE_MASTER_CNTL_MASK },
    { "REF_SEL_CNTL", AR_SERDES_SBUS_00_REF_SEL_CNTL_BP, AR_SERDES_SBUS_00_REF_SEL_CNTL_MASK },
    { "PLL_RECAL_EN_CNTL", AR_SERDES_SBUS_00_PLL_RECAL_EN_CNTL_BP, AR_SERDES_SBUS_00_PLL_RECAL_EN_CNTL_MASK },
    { "RX_EN_CNTL", AR_SERDES_SBUS_00_RX_EN_CNTL_BP, AR_SERDES_SBUS_00_RX_EN_CNTL_MASK },
    { "TX_EN_CNTL", AR_SERDES_SBUS_00_TX_EN_CNTL_BP, AR_SERDES_SBUS_00_TX_EN_CNTL_MASK },
    { "SBUS_CLK_GATE", AR_SERDES_SBUS_00_SBUS_CLK_GATE_BP, AR_SERDES_SBUS_00_SBUS_CLK_GATE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_01_detail[] = {
    { "RESERVED_31_25", AR_SERDES_SBUS_01_RESERVED_31_25_BP, AR_SERDES_SBUS_01_RESERVED_31_25_MASK },
    { "RX_RATE_SEL_CNTL", AR_SERDES_SBUS_01_RX_RATE_SEL_CNTL_BP, AR_SERDES_SBUS_01_RX_RATE_SEL_CNTL_MASK },
    { "RESERVED_15_9", AR_SERDES_SBUS_01_RESERVED_15_9_BP, AR_SERDES_SBUS_01_RESERVED_15_9_MASK },
    { "TX_RATE_SEL_CNTL", AR_SERDES_SBUS_01_TX_RATE_SEL_CNTL_BP, AR_SERDES_SBUS_01_TX_RATE_SEL_CNTL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_02_detail[] = {
    { "RESERVED_31_3", AR_SERDES_SBUS_02_RESERVED_31_3_BP, AR_SERDES_SBUS_02_RESERVED_31_3_MASK },
    { "RX_RDY_OBS", AR_SERDES_SBUS_02_RX_RDY_OBS_BP, AR_SERDES_SBUS_02_RX_RDY_OBS_MASK },
    { "TX_RDY_OBS", AR_SERDES_SBUS_02_TX_RDY_OBS_BP, AR_SERDES_SBUS_02_TX_RDY_OBS_MASK },
    { "RESERVED_0", AR_SERDES_SBUS_02_RESERVED_0_BP, AR_SERDES_SBUS_02_RESERVED_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_03_detail[] = {
    { "RESERVED_31_4", AR_SERDES_SBUS_03_RESERVED_31_4_BP, AR_SERDES_SBUS_03_RESERVED_31_4_MASK },
    { "RX_WIDTH_MODE_CNTL", AR_SERDES_SBUS_03_RX_WIDTH_MODE_CNTL_BP, AR_SERDES_SBUS_03_RX_WIDTH_MODE_CNTL_MASK },
    { "TX_WIDTH_MODE_CNTL", AR_SERDES_SBUS_03_TX_WIDTH_MODE_CNTL_BP, AR_SERDES_SBUS_03_TX_WIDTH_MODE_CNTL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_05_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_05_RESERVED_31_8_BP, AR_SERDES_SBUS_05_RESERVED_31_8_MASK },
    { "TX_PHASE_OUT_OBS", AR_SERDES_SBUS_05_TX_PHASE_OUT_OBS_BP, AR_SERDES_SBUS_05_TX_PHASE_OUT_OBS_MASK },
    { "RESERVED_2_0", AR_SERDES_SBUS_05_RESERVED_2_0_BP, AR_SERDES_SBUS_05_RESERVED_2_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_06_detail[] = {
    { "RESERVED_31_6", AR_SERDES_SBUS_06_RESERVED_31_6_BP, AR_SERDES_SBUS_06_RESERVED_31_6_MASK },
    { "TX_PHASE_IN_CNTL", AR_SERDES_SBUS_06_TX_PHASE_IN_CNTL_BP, AR_SERDES_SBUS_06_TX_PHASE_IN_CNTL_MASK },
    { "TX_PHASE_IN_GATE", AR_SERDES_SBUS_06_TX_PHASE_IN_GATE_BP, AR_SERDES_SBUS_06_TX_PHASE_IN_GATE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_07_detail[] = {
    { "RESERVED_31_13", AR_SERDES_SBUS_07_RESERVED_31_13_BP, AR_SERDES_SBUS_07_RESERVED_31_13_MASK },
    { "HALT_CNTL", AR_SERDES_SBUS_07_HALT_CNTL_BP, AR_SERDES_SBUS_07_HALT_CNTL_MASK },
    { "ALLOW_CORE_HALT_CNTL", AR_SERDES_SBUS_07_ALLOW_CORE_HALT_CNTL_BP, AR_SERDES_SBUS_07_ALLOW_CORE_HALT_CNTL_MASK },
    { "RESERVED_3_0", AR_SERDES_SBUS_07_RESERVED_3_0_BP, AR_SERDES_SBUS_07_RESERVED_3_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_0b_detail[] = {
    { "RESERVED_31_3", AR_SERDES_SBUS_0B_RESERVED_31_3_BP, AR_SERDES_SBUS_0B_RESERVED_31_3_MASK },
    { "TX_REFCLK_SYNC_CTRL", AR_SERDES_SBUS_0B_TX_REFCLK_SYNC_CTRL_BP, AR_SERDES_SBUS_0B_TX_REFCLK_SYNC_CTRL_MASK },
    { "TX_REFCLK_SYNC_GATE", AR_SERDES_SBUS_0B_TX_REFCLK_SYNC_GATE_BP, AR_SERDES_SBUS_0B_TX_REFCLK_SYNC_GATE_MASK },
    { "RESERVED_0", AR_SERDES_SBUS_0B_RESERVED_0_BP, AR_SERDES_SBUS_0B_RESERVED_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_3c_detail[] = {
    { "RESERVED_31_13", AR_SERDES_SBUS_3C_RESERVED_31_13_BP, AR_SERDES_SBUS_3C_RESERVED_31_13_MASK },
    { "TX_OUTPUT_EQ_POST_CNTL", AR_SERDES_SBUS_3C_TX_OUTPUT_EQ_POST_CNTL_BP, AR_SERDES_SBUS_3C_TX_OUTPUT_EQ_POST_CNTL_MASK },
    { "TX_OUTPUT_EQ_PRE_CNTL", AR_SERDES_SBUS_3C_TX_OUTPUT_EQ_PRE_CNTL_BP, AR_SERDES_SBUS_3C_TX_OUTPUT_EQ_PRE_CNTL_MASK },
    { "TX_OUTPUT_EQ_GATE", AR_SERDES_SBUS_3C_TX_OUTPUT_EQ_GATE_BP, AR_SERDES_SBUS_3C_TX_OUTPUT_EQ_GATE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_3d_detail[] = {
    { "RESERVED_31_15", AR_SERDES_SBUS_3D_RESERVED_31_15_BP, AR_SERDES_SBUS_3D_RESERVED_31_15_MASK },
    { "TX_IMPEDANCE_GATE", AR_SERDES_SBUS_3D_TX_IMPEDANCE_GATE_BP, AR_SERDES_SBUS_3D_TX_IMPEDANCE_GATE_MASK },
    { "TX_IMPEDANCE_CNTL", AR_SERDES_SBUS_3D_TX_IMPEDANCE_CNTL_BP, AR_SERDES_SBUS_3D_TX_IMPEDANCE_CNTL_MASK },
    { "TX_OUTPUT_ATTENUATION_CNTL", AR_SERDES_SBUS_3D_TX_OUTPUT_ATTENUATION_CNTL_BP, AR_SERDES_SBUS_3D_TX_OUTPUT_ATTENUATION_CNTL_MASK },
    { "TX_LND_DISABLE_CNTL", AR_SERDES_SBUS_3D_TX_LND_DISABLE_CNTL_BP, AR_SERDES_SBUS_3D_TX_LND_DISABLE_CNTL_MASK },
    { "TX_OUTPUT_SLEW_CNTL", AR_SERDES_SBUS_3D_TX_OUTPUT_SLEW_CNTL_BP, AR_SERDES_SBUS_3D_TX_OUTPUT_SLEW_CNTL_MASK },
    { "TX_ATTENUATION_GATE", AR_SERDES_SBUS_3D_TX_ATTENUATION_GATE_BP, AR_SERDES_SBUS_3D_TX_ATTENUATION_GATE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_3e_detail[] = {
    { "RESERVED_31_3", AR_SERDES_SBUS_3E_RESERVED_31_3_BP, AR_SERDES_SBUS_3E_RESERVED_31_3_MASK },
    { "NEAR_LOOPBACK_EN_CNTL", AR_SERDES_SBUS_3E_NEAR_LOOPBACK_EN_CNTL_BP, AR_SERDES_SBUS_3E_NEAR_LOOPBACK_EN_CNTL_MASK },
    { "TX_OUTPUT_EN_CNTL", AR_SERDES_SBUS_3E_TX_OUTPUT_EN_CNTL_BP, AR_SERDES_SBUS_3E_TX_OUTPUT_EN_CNTL_MASK },
    { "TX_OUTPUT_GATE", AR_SERDES_SBUS_3E_TX_OUTPUT_GATE_BP, AR_SERDES_SBUS_3E_TX_OUTPUT_GATE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_3f_detail[] = {
    { "RESERVED_31_13", AR_SERDES_SBUS_3F_RESERVED_31_13_BP, AR_SERDES_SBUS_3F_RESERVED_31_13_MASK },
    { "TX_ALT_PATTERN_EN_CNTL", AR_SERDES_SBUS_3F_TX_ALT_PATTERN_EN_CNTL_BP, AR_SERDES_SBUS_3F_TX_ALT_PATTERN_EN_CNTL_MASK },
    { "TX_ELEC_IDLE_CNTL", AR_SERDES_SBUS_3F_TX_ELEC_IDLE_CNTL_BP, AR_SERDES_SBUS_3F_TX_ELEC_IDLE_CNTL_MASK },
    { "TX_POLARITY_INV_EN_CNTL", AR_SERDES_SBUS_3F_TX_POLARITY_INV_EN_CNTL_BP, AR_SERDES_SBUS_3F_TX_POLARITY_INV_EN_CNTL_MASK },
    { "TX_INVERT_ONE_WORD_CNTL", AR_SERDES_SBUS_3F_TX_INVERT_ONE_WORD_CNTL_BP, AR_SERDES_SBUS_3F_TX_INVERT_ONE_WORD_CNTL_MASK },
    { "TX_SEL_CORE_DATA_CNTL", AR_SERDES_SBUS_3F_TX_SEL_CORE_DATA_CNTL_BP, AR_SERDES_SBUS_3F_TX_SEL_CORE_DATA_CNTL_MASK },
    { "TX_PATTERN_GEN_EN_CNTL", AR_SERDES_SBUS_3F_TX_PATTERN_GEN_EN_CNTL_BP, AR_SERDES_SBUS_3F_TX_PATTERN_GEN_EN_CNTL_MASK },
    { "TX_PATTERN_GEN_SEL_CNTL", AR_SERDES_SBUS_3F_TX_PATTERN_GEN_SEL_CNTL_BP, AR_SERDES_SBUS_3F_TX_PATTERN_GEN_SEL_CNTL_MASK },
    { "TX_PATTERN_GEN_CTL_CNTL", AR_SERDES_SBUS_3F_TX_PATTERN_GEN_CTL_CNTL_BP, AR_SERDES_SBUS_3F_TX_PATTERN_GEN_CTL_CNTL_MASK },
    { "TX_DATA_SEL_CNTL", AR_SERDES_SBUS_3F_TX_DATA_SEL_CNTL_BP, AR_SERDES_SBUS_3F_TX_DATA_SEL_CNTL_MASK },
    { "TX_DATA_GATE", AR_SERDES_SBUS_3F_TX_DATA_GATE_BP, AR_SERDES_SBUS_3F_TX_DATA_GATE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_40_detail[] = {
    { "RESERVED_31_20", AR_SERDES_SBUS_40_RESERVED_31_20_BP, AR_SERDES_SBUS_40_RESERVED_31_20_MASK },
    { "TX_USER_REG_CNTL", AR_SERDES_SBUS_40_TX_USER_REG_CNTL_BP, AR_SERDES_SBUS_40_TX_USER_REG_CNTL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_41_detail[] = {
    { "RESERVED_31_1", AR_SERDES_SBUS_41_RESERVED_31_1_BP, AR_SERDES_SBUS_41_RESERVED_31_1_MASK },
    { "RX_K30_7_ERR_EN_CNTL", AR_SERDES_SBUS_41_RX_K30_7_ERR_EN_CNTL_BP, AR_SERDES_SBUS_41_RX_K30_7_ERR_EN_CNTL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_50_detail[] = {
    { "RESERVED_31_21", AR_SERDES_SBUS_50_RESERVED_31_21_BP, AR_SERDES_SBUS_50_RESERVED_31_21_MASK },
    { "RX_OFFSET_DATA_SEL_CNTL", AR_SERDES_SBUS_50_RX_OFFSET_DATA_SEL_CNTL_BP, AR_SERDES_SBUS_50_RX_OFFSET_DATA_SEL_CNTL_MASK },
    { "RESERVED_19_18", AR_SERDES_SBUS_50_RESERVED_19_18_BP, AR_SERDES_SBUS_50_RESERVED_19_18_MASK },
    { "SIG_STRENGTH_STRONG_EN_CNTL", AR_SERDES_SBUS_50_SIG_STRENGTH_STRONG_EN_CNTL_BP, AR_SERDES_SBUS_50_SIG_STRENGTH_STRONG_EN_CNTL_MASK },
    { "RX_SIG_STRENGTH_EN_CNTL", AR_SERDES_SBUS_50_RX_SIG_STRENGTH_EN_CNTL_BP, AR_SERDES_SBUS_50_RX_SIG_STRENGTH_EN_CNTL_MASK },
    { "RX_DROPOUT_CHAR_EN_CNTL", AR_SERDES_SBUS_50_RX_DROPOUT_CHAR_EN_CNTL_BP, AR_SERDES_SBUS_50_RX_DROPOUT_CHAR_EN_CNTL_MASK },
    { "RX_INVERT_ONE_WORD_CNTL", AR_SERDES_SBUS_50_RX_INVERT_ONE_WORD_CNTL_BP, AR_SERDES_SBUS_50_RX_INVERT_ONE_WORD_CNTL_MASK },
    { "RX_PATTERN_CMP_EN_CNTL", AR_SERDES_SBUS_50_RX_PATTERN_CMP_EN_CNTL_BP, AR_SERDES_SBUS_50_RX_PATTERN_CMP_EN_CNTL_MASK },
    { "RX_PATTERN_CMP_SEL_CNTL", AR_SERDES_SBUS_50_RX_PATTERN_CMP_SEL_CNTL_BP, AR_SERDES_SBUS_50_RX_PATTERN_CMP_SEL_CNTL_MASK },
    { "RX_PATTERN_CTL_CNTL", AR_SERDES_SBUS_50_RX_PATTERN_CTL_CNTL_BP, AR_SERDES_SBUS_50_RX_PATTERN_CTL_CNTL_MASK },
    { "RX_SEL_CNTL", AR_SERDES_SBUS_50_RX_SEL_CNTL_BP, AR_SERDES_SBUS_50_RX_SEL_CNTL_MASK },
    { "RX_K28_7_COMMA_DET_EN_CNTL", AR_SERDES_SBUS_50_RX_K28_7_COMMA_DET_EN_CNTL_BP, AR_SERDES_SBUS_50_RX_K28_7_COMMA_DET_EN_CNTL_MASK },
    { "RX_DATA_HALT_LOAD_CNTL", AR_SERDES_SBUS_50_RX_DATA_HALT_LOAD_CNTL_BP, AR_SERDES_SBUS_50_RX_DATA_HALT_LOAD_CNTL_MASK },
    { "RX_POLARITY_INV_EN_CNTL", AR_SERDES_SBUS_50_RX_POLARITY_INV_EN_CNTL_BP, AR_SERDES_SBUS_50_RX_POLARITY_INV_EN_CNTL_MASK },
    { "RX_BIT_SLIP_CNTL", AR_SERDES_SBUS_50_RX_BIT_SLIP_CNTL_BP, AR_SERDES_SBUS_50_RX_BIT_SLIP_CNTL_MASK },
    { "RX_8B10B_ALIGN_EN_CNTL", AR_SERDES_SBUS_50_RX_8B10B_ALIGN_EN_CNTL_BP, AR_SERDES_SBUS_50_RX_8B10B_ALIGN_EN_CNTL_MASK },
    { "RX_DATA_GATE", AR_SERDES_SBUS_50_RX_DATA_GATE_BP, AR_SERDES_SBUS_50_RX_DATA_GATE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_51_detail[] = {
    { "RESERVED_31_3", AR_SERDES_SBUS_51_RESERVED_31_3_BP, AR_SERDES_SBUS_51_RESERVED_31_3_MASK },
    { "RX_ALT_PATTERN_EN_CNTL", AR_SERDES_SBUS_51_RX_ALT_PATTERN_EN_CNTL_BP, AR_SERDES_SBUS_51_RX_ALT_PATTERN_EN_CNTL_MASK },
    { "RESERVED_1_0", AR_SERDES_SBUS_51_RESERVED_1_0_BP, AR_SERDES_SBUS_51_RESERVED_1_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_52_detail[] = {
    { "RESERVED_31_20", AR_SERDES_SBUS_52_RESERVED_31_20_BP, AR_SERDES_SBUS_52_RESERVED_31_20_MASK },
    { "RX_USER_REG_CNTL", AR_SERDES_SBUS_52_RX_USER_REG_CNTL_BP, AR_SERDES_SBUS_52_RX_USER_REG_CNTL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_53_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_53_RESERVED_31_8_BP, AR_SERDES_SBUS_53_RESERVED_31_8_MASK },
    { "RX_ERROR_MONITOR_EN_CNTL", AR_SERDES_SBUS_53_RX_ERROR_MONITOR_EN_CNTL_BP, AR_SERDES_SBUS_53_RX_ERROR_MONITOR_EN_CNTL_MASK },
    { "RX_ERROR_MONITOR_RESET_CNTL", AR_SERDES_SBUS_53_RX_ERROR_MONITOR_RESET_CNTL_BP, AR_SERDES_SBUS_53_RX_ERROR_MONITOR_RESET_CNTL_MASK },
    { "RX_ERROR_EDGE_DETECT_CNTL", AR_SERDES_SBUS_53_RX_ERROR_EDGE_DETECT_CNTL_BP, AR_SERDES_SBUS_53_RX_ERROR_EDGE_DETECT_CNTL_MASK },
    { "RX_ERROR_MONITOR_SEL_CNTL", AR_SERDES_SBUS_53_RX_ERROR_MONITOR_SEL_CNTL_BP, AR_SERDES_SBUS_53_RX_ERROR_MONITOR_SEL_CNTL_MASK },
    { "RX_ERROR_MONITOR_GATE", AR_SERDES_SBUS_53_RX_ERROR_MONITOR_GATE_BP, AR_SERDES_SBUS_53_RX_ERROR_MONITOR_GATE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_54_detail[] = {
    { "RESERVED_31_9", AR_SERDES_SBUS_54_RESERVED_31_9_BP, AR_SERDES_SBUS_54_RESERVED_31_9_MASK },
    { "RX_8B10B_ALIGNED_COMMA_DET_MSB", AR_SERDES_SBUS_54_RX_8B10B_ALIGNED_COMMA_DET_MSB_BP, AR_SERDES_SBUS_54_RX_8B10B_ALIGNED_COMMA_DET_MSB_MASK },
    { "RX_8B10B_ALIGNED_COMMA_DET_LSB", AR_SERDES_SBUS_54_RX_8B10B_ALIGNED_COMMA_DET_LSB_BP, AR_SERDES_SBUS_54_RX_8B10B_ALIGNED_COMMA_DET_LSB_MASK },
    { "RX_PATTERN_CMP_PASS", AR_SERDES_SBUS_54_RX_PATTERN_CMP_PASS_BP, AR_SERDES_SBUS_54_RX_PATTERN_CMP_PASS_MASK },
    { "RX_8B10B_COMMA_DET_MSB", AR_SERDES_SBUS_54_RX_8B10B_COMMA_DET_MSB_BP, AR_SERDES_SBUS_54_RX_8B10B_COMMA_DET_MSB_MASK },
    { "RX_8B10B_COMMA_DET_LSB", AR_SERDES_SBUS_54_RX_8B10B_COMMA_DET_LSB_BP, AR_SERDES_SBUS_54_RX_8B10B_COMMA_DET_LSB_MASK },
    { "RX_8B10B_SLIP_IN_PROGRESS_DET", AR_SERDES_SBUS_54_RX_8B10B_SLIP_IN_PROGRESS_DET_BP, AR_SERDES_SBUS_54_RX_8B10B_SLIP_IN_PROGRESS_DET_MASK },
    { "RESERVED_2", AR_SERDES_SBUS_54_RESERVED_2_BP, AR_SERDES_SBUS_54_RESERVED_2_MASK },
    { "RX_PRBS_FAILURE", AR_SERDES_SBUS_54_RX_PRBS_FAILURE_BP, AR_SERDES_SBUS_54_RX_PRBS_FAILURE_MASK },
    { "RX_ERROR_OCCURED", AR_SERDES_SBUS_54_RX_ERROR_OCCURED_BP, AR_SERDES_SBUS_54_RX_ERROR_OCCURED_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_55_detail[] = {
    { "RX_ERROR_COUNT_OBS", AR_SERDES_SBUS_55_RX_ERROR_COUNT_OBS_BP, AR_SERDES_SBUS_55_RX_ERROR_COUNT_OBS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_56_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_56_RESERVED_31_8_BP, AR_SERDES_SBUS_56_RESERVED_31_8_MASK },
    { "RX_PRBS_DATA_MSB_OBS_39_32", AR_SERDES_SBUS_56_RX_PRBS_DATA_MSB_OBS_39_32_BP, AR_SERDES_SBUS_56_RX_PRBS_DATA_MSB_OBS_39_32_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_57_detail[] = {
    { "RX_PRBS_DATA_MSB_OBS_31_0", AR_SERDES_SBUS_57_RX_PRBS_DATA_MSB_OBS_31_0_BP, AR_SERDES_SBUS_57_RX_PRBS_DATA_MSB_OBS_31_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_58_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_58_RESERVED_31_8_BP, AR_SERDES_SBUS_58_RESERVED_31_8_MASK },
    { "RX_PRBS_DATA_LSB_OBS_39_32", AR_SERDES_SBUS_58_RX_PRBS_DATA_LSB_OBS_39_32_BP, AR_SERDES_SBUS_58_RX_PRBS_DATA_LSB_OBS_39_32_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_59_detail[] = {
    { "RX_PRBS_DATA_LSB_OBS_31_0", AR_SERDES_SBUS_59_RX_PRBS_DATA_LSB_OBS_31_0_BP, AR_SERDES_SBUS_59_RX_PRBS_DATA_LSB_OBS_31_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_5a_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_5A_RESERVED_31_8_BP, AR_SERDES_SBUS_5A_RESERVED_31_8_MASK },
    { "RX_SIG_STRENGTH_OBS", AR_SERDES_SBUS_5A_RX_SIG_STRENGTH_OBS_BP, AR_SERDES_SBUS_5A_RX_SIG_STRENGTH_OBS_MASK },
    { "RESERVED_5_0", AR_SERDES_SBUS_5A_RESERVED_5_0_BP, AR_SERDES_SBUS_5A_RESERVED_5_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_5b_detail[] = {
    { "RESERVED_31_2", AR_SERDES_SBUS_5B_RESERVED_31_2_BP, AR_SERDES_SBUS_5B_RESERVED_31_2_MASK },
    { "RX_FAR_LOOPBACK_EN_CNTL", AR_SERDES_SBUS_5B_RX_FAR_LOOPBACK_EN_CNTL_BP, AR_SERDES_SBUS_5B_RX_FAR_LOOPBACK_EN_CNTL_MASK },
    { "RX_FAR_LOOPBACK_GATE", AR_SERDES_SBUS_5B_RX_FAR_LOOPBACK_GATE_BP, AR_SERDES_SBUS_5B_RX_FAR_LOOPBACK_GATE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_64_detail[] = {
    { "RESERVED_31_9", AR_SERDES_SBUS_64_RESERVED_31_9_BP, AR_SERDES_SBUS_64_RESERVED_31_9_MASK },
    { "RX_DFE_B_DATA_PD_CNTL", AR_SERDES_SBUS_64_RX_DFE_B_DATA_PD_CNTL_BP, AR_SERDES_SBUS_64_RX_DFE_B_DATA_PD_CNTL_MASK },
    { "RX_DFE_B_OFFSET_PD_CNTL", AR_SERDES_SBUS_64_RX_DFE_B_OFFSET_PD_CNTL_BP, AR_SERDES_SBUS_64_RX_DFE_B_OFFSET_PD_CNTL_MASK },
    { "RX_DFE_A_DATA_PD_CNTL", AR_SERDES_SBUS_64_RX_DFE_A_DATA_PD_CNTL_BP, AR_SERDES_SBUS_64_RX_DFE_A_DATA_PD_CNTL_MASK },
    { "RX_DFE_A_OFFSET_PD_CNTL", AR_SERDES_SBUS_64_RX_DFE_A_OFFSET_PD_CNTL_BP, AR_SERDES_SBUS_64_RX_DFE_A_OFFSET_PD_CNTL_MASK },
    { "RX_SEL_DFE_A_DATA_CNTL", AR_SERDES_SBUS_64_RX_SEL_DFE_A_DATA_CNTL_BP, AR_SERDES_SBUS_64_RX_SEL_DFE_A_DATA_CNTL_MASK },
    { "RX_SEL_DFE_A_OFFSET_CNTL", AR_SERDES_SBUS_64_RX_SEL_DFE_A_OFFSET_CNTL_BP, AR_SERDES_SBUS_64_RX_SEL_DFE_A_OFFSET_CNTL_MASK },
    { "RX_PHASE_INTERPOLATOR_GATE", AR_SERDES_SBUS_64_RX_PHASE_INTERPOLATOR_GATE_BP, AR_SERDES_SBUS_64_RX_PHASE_INTERPOLATOR_GATE_MASK },
    { "RX_DFE_PD_GATE", AR_SERDES_SBUS_64_RX_DFE_PD_GATE_BP, AR_SERDES_SBUS_64_RX_DFE_PD_GATE_MASK },
    { "RX_DFE_GATE", AR_SERDES_SBUS_64_RX_DFE_GATE_BP, AR_SERDES_SBUS_64_RX_DFE_GATE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_65_detail[] = {
    { "RESERVED_31_7", AR_SERDES_SBUS_65_RESERVED_31_7_BP, AR_SERDES_SBUS_65_RESERVED_31_7_MASK },
    { "RX_PHASE_INTERPOLATOR_CNTL", AR_SERDES_SBUS_65_RX_PHASE_INTERPOLATOR_CNTL_BP, AR_SERDES_SBUS_65_RX_PHASE_INTERPOLATOR_CNTL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_67_detail[] = {
    { "RESERVED_31_30", AR_SERDES_SBUS_67_RESERVED_31_30_BP, AR_SERDES_SBUS_67_RESERVED_31_30_MASK },
    { "RX_DFE_A_CNTL_29_0_", AR_SERDES_SBUS_67_RX_DFE_A_CNTL_29_0__BP, AR_SERDES_SBUS_67_RX_DFE_A_CNTL_29_0__MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_68_detail[] = {
    { "RESERVED_31_10", AR_SERDES_SBUS_68_RESERVED_31_10_BP, AR_SERDES_SBUS_68_RESERVED_31_10_MASK },
    { "RX_DFE_A_CNTL_39_30_", AR_SERDES_SBUS_68_RX_DFE_A_CNTL_39_30__BP, AR_SERDES_SBUS_68_RX_DFE_A_CNTL_39_30__MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_69_detail[] = {
    { "RESERVED_31_30", AR_SERDES_SBUS_69_RESERVED_31_30_BP, AR_SERDES_SBUS_69_RESERVED_31_30_MASK },
    { "RX_DFE_B_CNTL_29_0_", AR_SERDES_SBUS_69_RX_DFE_B_CNTL_29_0__BP, AR_SERDES_SBUS_69_RX_DFE_B_CNTL_29_0__MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_6a_detail[] = {
    { "RESERVED_31_10", AR_SERDES_SBUS_6A_RESERVED_31_10_BP, AR_SERDES_SBUS_6A_RESERVED_31_10_MASK },
    { "RX_DFE_B_CNTL_39_30_", AR_SERDES_SBUS_6A_RX_DFE_B_CNTL_39_30__BP, AR_SERDES_SBUS_6A_RX_DFE_B_CNTL_39_30__MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_6b_detail[] = {
    { "RESERVED_31_24", AR_SERDES_SBUS_6B_RESERVED_31_24_BP, AR_SERDES_SBUS_6B_RESERVED_31_24_MASK },
    { "RX_DFE_B_EBERT_DAC_CNTL", AR_SERDES_SBUS_6B_RX_DFE_B_EBERT_DAC_CNTL_BP, AR_SERDES_SBUS_6B_RX_DFE_B_EBERT_DAC_CNTL_MASK },
    { "RESERVED_15_8", AR_SERDES_SBUS_6B_RESERVED_15_8_BP, AR_SERDES_SBUS_6B_RESERVED_15_8_MASK },
    { "RX_DFE_A_EBERT_DAC_CNTL", AR_SERDES_SBUS_6B_RX_DFE_A_EBERT_DAC_CNTL_BP, AR_SERDES_SBUS_6B_RX_DFE_A_EBERT_DAC_CNTL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_81_detail[] = {
    { "RESERVED_31_16", AR_SERDES_SBUS_81_RESERVED_31_16_BP, AR_SERDES_SBUS_81_RESERVED_31_16_MASK },
    { "DFE_SCRATCH_PAD_CNTL", AR_SERDES_SBUS_81_DFE_SCRATCH_PAD_CNTL_BP, AR_SERDES_SBUS_81_DFE_SCRATCH_PAD_CNTL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_82_detail[] = {
    { "RESERVED_31_16", AR_SERDES_SBUS_82_RESERVED_31_16_BP, AR_SERDES_SBUS_82_RESERVED_31_16_MASK },
    { "DFE_USER_CONFIG", AR_SERDES_SBUS_82_DFE_USER_CONFIG_BP, AR_SERDES_SBUS_82_DFE_USER_CONFIG_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_8c_detail[] = {
    { "RESERVED_31", AR_SERDES_SBUS_8C_RESERVED_31_BP, AR_SERDES_SBUS_8C_RESERVED_31_MASK },
    { "TX_OVERRIDE_IN_OBS", AR_SERDES_SBUS_8C_TX_OVERRIDE_IN_OBS_BP, AR_SERDES_SBUS_8C_TX_OVERRIDE_IN_OBS_MASK },
    { "TX_OVERRIDE_EN_OBS", AR_SERDES_SBUS_8C_TX_OVERRIDE_EN_OBS_BP, AR_SERDES_SBUS_8C_TX_OVERRIDE_EN_OBS_MASK },
    { "RESERVED_28_0", AR_SERDES_SBUS_8C_RESERVED_28_0_BP, AR_SERDES_SBUS_8C_RESERVED_28_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_8e_detail[] = {
    { "RESERVED_31_20", AR_SERDES_SBUS_8E_RESERVED_31_20_BP, AR_SERDES_SBUS_8E_RESERVED_31_20_MASK },
    { "SBUS_OVERRIDE_CORE_TO_ANLG_CNTL", AR_SERDES_SBUS_8E_SBUS_OVERRIDE_CORE_TO_ANLG_CNTL_BP, AR_SERDES_SBUS_8E_SBUS_OVERRIDE_CORE_TO_ANLG_CNTL_MASK },
    { "RESERVED_3_1", AR_SERDES_SBUS_8E_RESERVED_3_1_BP, AR_SERDES_SBUS_8E_RESERVED_3_1_MASK },
    { "SBUS_OVERRIDE_CORE_TO_ANLG_GATE", AR_SERDES_SBUS_8E_SBUS_OVERRIDE_CORE_TO_ANLG_GATE_BP, AR_SERDES_SBUS_8E_SBUS_OVERRIDE_CORE_TO_ANLG_GATE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_8f_detail[] = {
    { "RESERVED_31_20", AR_SERDES_SBUS_8F_RESERVED_31_20_BP, AR_SERDES_SBUS_8F_RESERVED_31_20_MASK },
    { "SBUS_OVERRIDE_ANLG_TO_CORE_CNTL", AR_SERDES_SBUS_8F_SBUS_OVERRIDE_ANLG_TO_CORE_CNTL_BP, AR_SERDES_SBUS_8F_SBUS_OVERRIDE_ANLG_TO_CORE_CNTL_MASK },
    { "RESERVED_3_1", AR_SERDES_SBUS_8F_RESERVED_3_1_BP, AR_SERDES_SBUS_8F_RESERVED_3_1_MASK },
    { "SBUS_OVERRIDE_ANLG_TO_CORE_GATE", AR_SERDES_SBUS_8F_SBUS_OVERRIDE_ANLG_TO_CORE_GATE_BP, AR_SERDES_SBUS_8F_SBUS_OVERRIDE_ANLG_TO_CORE_GATE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_90_detail[] = {
    { "LINK_LOOPBACK_EN_CNTL", AR_SERDES_SBUS_90_LINK_LOOPBACK_EN_CNTL_BP, AR_SERDES_SBUS_90_LINK_LOOPBACK_EN_CNTL_MASK },
    { "RESERVED_30_0", AR_SERDES_SBUS_90_RESERVED_30_0_BP, AR_SERDES_SBUS_90_RESERVED_30_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_92_detail[] = {
    { "RESERVED_31_9", AR_SERDES_SBUS_92_RESERVED_31_9_BP, AR_SERDES_SBUS_92_RESERVED_31_9_MASK },
    { "PCIE_RX_POWER_DOWN_CNTL", AR_SERDES_SBUS_92_PCIE_RX_POWER_DOWN_CNTL_BP, AR_SERDES_SBUS_92_PCIE_RX_POWER_DOWN_CNTL_MASK },
    { "PCIE_TX_POWER_DOWN_CNTL", AR_SERDES_SBUS_92_PCIE_TX_POWER_DOWN_CNTL_BP, AR_SERDES_SBUS_92_PCIE_TX_POWER_DOWN_CNTL_MASK },
    { "PCIE_TX_DETECT_RX_CNTL", AR_SERDES_SBUS_92_PCIE_TX_DETECT_RX_CNTL_BP, AR_SERDES_SBUS_92_PCIE_TX_DETECT_RX_CNTL_MASK },
    { "PCIE_RX_ELEC_IDLE_THRESHOLD_CNTL", AR_SERDES_SBUS_92_PCIE_RX_ELEC_IDLE_THRESHOLD_CNTL_BP, AR_SERDES_SBUS_92_PCIE_RX_ELEC_IDLE_THRESHOLD_CNTL_MASK },
    { "PCIE_GATE", AR_SERDES_SBUS_92_PCIE_GATE_BP, AR_SERDES_SBUS_92_PCIE_GATE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_93_detail[] = {
    { "RESERVED_31_2", AR_SERDES_SBUS_93_RESERVED_31_2_BP, AR_SERDES_SBUS_93_RESERVED_31_2_MASK },
    { "PCIE_RX_ELEC_IDLE_DETECT_CNTL", AR_SERDES_SBUS_93_PCIE_RX_ELEC_IDLE_DETECT_CNTL_BP, AR_SERDES_SBUS_93_PCIE_RX_ELEC_IDLE_DETECT_CNTL_MASK },
    { "PCIE_RX_ELEC_IDLE_DETECT_GATE", AR_SERDES_SBUS_93_PCIE_RX_ELEC_IDLE_DETECT_GATE_BP, AR_SERDES_SBUS_93_PCIE_RX_ELEC_IDLE_DETECT_GATE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_95_detail[] = {
    { "RESERVED_31_23", AR_SERDES_SBUS_95_RESERVED_31_23_BP, AR_SERDES_SBUS_95_RESERVED_31_23_MASK },
    { "SIG_OK_PFD_COUNTER_CNTL", AR_SERDES_SBUS_95_SIG_OK_PFD_COUNTER_CNTL_BP, AR_SERDES_SBUS_95_SIG_OK_PFD_COUNTER_CNTL_MASK },
    { "SIG_OK_USE_SEL_PFD_CNTL", AR_SERDES_SBUS_95_SIG_OK_USE_SEL_PFD_CNTL_BP, AR_SERDES_SBUS_95_SIG_OK_USE_SEL_PFD_CNTL_MASK },
    { "SIG_OK_COMMA_COUNT_LIMIT_CNTL", AR_SERDES_SBUS_95_SIG_OK_COMMA_COUNT_LIMIT_CNTL_BP, AR_SERDES_SBUS_95_SIG_OK_COMMA_COUNT_LIMIT_CNTL_MASK },
    { "SIG_OK_USE_KR_CNTL", AR_SERDES_SBUS_95_SIG_OK_USE_KR_CNTL_BP, AR_SERDES_SBUS_95_SIG_OK_USE_KR_CNTL_MASK },
    { "PROGRAMMABLE_SIG_OK_OBS", AR_SERDES_SBUS_95_PROGRAMMABLE_SIG_OK_OBS_BP, AR_SERDES_SBUS_95_PROGRAMMABLE_SIG_OK_OBS_MASK },
    { "SIG_OK_OBS", AR_SERDES_SBUS_95_SIG_OK_OBS_BP, AR_SERDES_SBUS_95_SIG_OK_OBS_MASK },
    { "SIG_OK_OUTPUT_CNTL", AR_SERDES_SBUS_95_SIG_OK_OUTPUT_CNTL_BP, AR_SERDES_SBUS_95_SIG_OK_OUTPUT_CNTL_MASK },
    { "SIG_OK_FFL_COUNTER_BIT3_EN_CNTL", AR_SERDES_SBUS_95_SIG_OK_FFL_COUNTER_BIT3_EN_CNTL_BP, AR_SERDES_SBUS_95_SIG_OK_FFL_COUNTER_BIT3_EN_CNTL_MASK },
    { "SIG_OK_FFL_COUNTER_BIT2_EN_CNTL", AR_SERDES_SBUS_95_SIG_OK_FFL_COUNTER_BIT2_EN_CNTL_BP, AR_SERDES_SBUS_95_SIG_OK_FFL_COUNTER_BIT2_EN_CNTL_MASK },
    { "SIG_OK_USE_FINE_FLOCK_CNTR_CNTL", AR_SERDES_SBUS_95_SIG_OK_USE_FINE_FLOCK_CNTR_CNTL_BP, AR_SERDES_SBUS_95_SIG_OK_USE_FINE_FLOCK_CNTR_CNTL_MASK },
    { "SIG_OK_USE_SLIP_IN_PROGRESS_CNTL", AR_SERDES_SBUS_95_SIG_OK_USE_SLIP_IN_PROGRESS_CNTL_BP, AR_SERDES_SBUS_95_SIG_OK_USE_SLIP_IN_PROGRESS_CNTL_MASK },
    { "SIG_OK_USE_RX_RDY_CNTL", AR_SERDES_SBUS_95_SIG_OK_USE_RX_RDY_CNTL_BP, AR_SERDES_SBUS_95_SIG_OK_USE_RX_RDY_CNTL_MASK },
    { "SIG_OK_USE_COMMA_DET_CNTL", AR_SERDES_SBUS_95_SIG_OK_USE_COMMA_DET_CNTL_BP, AR_SERDES_SBUS_95_SIG_OK_USE_COMMA_DET_CNTL_MASK },
    { "SIG_OK_USE_SIGNAL_STRENGTH_CNTL", AR_SERDES_SBUS_95_SIG_OK_USE_SIGNAL_STRENGTH_CNTL_BP, AR_SERDES_SBUS_95_SIG_OK_USE_SIGNAL_STRENGTH_CNTL_MASK },
    { "SIG_OK_USE_ELEC_IDLE_CNTL", AR_SERDES_SBUS_95_SIG_OK_USE_ELEC_IDLE_CNTL_BP, AR_SERDES_SBUS_95_SIG_OK_USE_ELEC_IDLE_CNTL_MASK },
    { "SIG_OK_USE_RX_FINE_FLOCK_CNT", AR_SERDES_SBUS_95_SIG_OK_USE_RX_FINE_FLOCK_CNT_BP, AR_SERDES_SBUS_95_SIG_OK_USE_RX_FINE_FLOCK_CNT_MASK },
    { "SIG_OK_EN_PRGRMBLE_INPUTS_GATE", AR_SERDES_SBUS_95_SIG_OK_EN_PRGRMBLE_INPUTS_GATE_BP, AR_SERDES_SBUS_95_SIG_OK_EN_PRGRMBLE_INPUTS_GATE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ad_detail[] = {
    { "RESERVED_31_2", AR_SERDES_SBUS_AD_RESERVED_31_2_BP, AR_SERDES_SBUS_AD_RESERVED_31_2_MASK },
    { "KR_TRAINING_EN", AR_SERDES_SBUS_AD_KR_TRAINING_EN_BP, AR_SERDES_SBUS_AD_KR_TRAINING_EN_MASK },
    { "KR_TRAINING_EN_GATE", AR_SERDES_SBUS_AD_KR_TRAINING_EN_GATE_BP, AR_SERDES_SBUS_AD_KR_TRAINING_EN_GATE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ae_detail[] = {
    { "RESERVED_31_2", AR_SERDES_SBUS_AE_RESERVED_31_2_BP, AR_SERDES_SBUS_AE_RESERVED_31_2_MASK },
    { "KR_RESTART_TRAINING", AR_SERDES_SBUS_AE_KR_RESTART_TRAINING_BP, AR_SERDES_SBUS_AE_KR_RESTART_TRAINING_MASK },
    { "KR_RESTART_TRAINING_GATE", AR_SERDES_SBUS_AE_KR_RESTART_TRAINING_GATE_BP, AR_SERDES_SBUS_AE_KR_RESTART_TRAINING_GATE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_af_detail[] = {
    { "RESERVED_31_19", AR_SERDES_SBUS_AF_RESERVED_31_19_BP, AR_SERDES_SBUS_AF_RESERVED_31_19_MASK },
    { "KR_TRAINING_STATE", AR_SERDES_SBUS_AF_KR_TRAINING_STATE_BP, AR_SERDES_SBUS_AF_KR_TRAINING_STATE_MASK },
    { "RESERVED_15_9", AR_SERDES_SBUS_AF_RESERVED_15_9_BP, AR_SERDES_SBUS_AF_RESERVED_15_9_MASK },
    { "KR_TRAINING", AR_SERDES_SBUS_AF_KR_TRAINING_BP, AR_SERDES_SBUS_AF_KR_TRAINING_MASK },
    { "KR_FRAME_LOCK", AR_SERDES_SBUS_AF_KR_FRAME_LOCK_BP, AR_SERDES_SBUS_AF_KR_FRAME_LOCK_MASK },
    { "KR_RX_FAULT", AR_SERDES_SBUS_AF_KR_RX_FAULT_BP, AR_SERDES_SBUS_AF_KR_RX_FAULT_MASK },
    { "KR_TX_FAULT", AR_SERDES_SBUS_AF_KR_TX_FAULT_BP, AR_SERDES_SBUS_AF_KR_TX_FAULT_MASK },
    { "KR_PMD_FAULT", AR_SERDES_SBUS_AF_KR_PMD_FAULT_BP, AR_SERDES_SBUS_AF_KR_PMD_FAULT_MASK },
    { "KR_SIGNAL_DETECT", AR_SERDES_SBUS_AF_KR_SIGNAL_DETECT_BP, AR_SERDES_SBUS_AF_KR_SIGNAL_DETECT_MASK },
    { "KR_TRAINING_FAILURE", AR_SERDES_SBUS_AF_KR_TRAINING_FAILURE_BP, AR_SERDES_SBUS_AF_KR_TRAINING_FAILURE_MASK },
    { "KR_RX_TRAINED", AR_SERDES_SBUS_AF_KR_RX_TRAINED_BP, AR_SERDES_SBUS_AF_KR_RX_TRAINED_MASK },
    { "KR_RX_TRAINED_GATE", AR_SERDES_SBUS_AF_KR_RX_TRAINED_GATE_BP, AR_SERDES_SBUS_AF_KR_RX_TRAINED_GATE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_b3_detail[] = {
    { "RESERVED_31_2", AR_SERDES_SBUS_B3_RESERVED_31_2_BP, AR_SERDES_SBUS_B3_RESERVED_31_2_MASK },
    { "KR_REMOTE_RX_RDY", AR_SERDES_SBUS_B3_KR_REMOTE_RX_RDY_BP, AR_SERDES_SBUS_B3_KR_REMOTE_RX_RDY_MASK },
    { "KR_REMOTE_RX_RDY_GATE", AR_SERDES_SBUS_B3_KR_REMOTE_RX_RDY_GATE_BP, AR_SERDES_SBUS_B3_KR_REMOTE_RX_RDY_GATE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_fc_detail[] = {
    { "RESERVED_31_24", AR_SERDES_SBUS_FC_RESERVED_31_24_BP, AR_SERDES_SBUS_FC_RESERVED_31_24_MASK },
    { "BROADCAST_INV_2_CNTL", AR_SERDES_SBUS_FC_BROADCAST_INV_2_CNTL_BP, AR_SERDES_SBUS_FC_BROADCAST_INV_2_CNTL_MASK },
    { "RESERVED_15_12", AR_SERDES_SBUS_FC_RESERVED_15_12_BP, AR_SERDES_SBUS_FC_RESERVED_15_12_MASK },
    { "BROADCAST_INV_CNT", AR_SERDES_SBUS_FC_BROADCAST_INV_CNT_BP, AR_SERDES_SBUS_FC_BROADCAST_INV_CNT_MASK },
    { "RESERVED_3_1", AR_SERDES_SBUS_FC_RESERVED_3_1_BP, AR_SERDES_SBUS_FC_RESERVED_3_1_MASK },
    { "IGNORE_BROADCAST_CNTL", AR_SERDES_SBUS_FC_IGNORE_BROADCAST_CNTL_BP, AR_SERDES_SBUS_FC_IGNORE_BROADCAST_CNTL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_fd_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_FD_RESERVED_31_8_BP, AR_SERDES_SBUS_FD_RESERVED_31_8_MASK },
    { "SERDES_SBUS_TEST_READ_WRITE", AR_SERDES_SBUS_FD_SERDES_SBUS_TEST_READ_WRITE_BP, AR_SERDES_SBUS_FD_SERDES_SBUS_TEST_READ_WRITE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_fe_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_FE_RESERVED_31_8_BP, AR_SERDES_SBUS_FE_RESERVED_31_8_MASK },
    { "SERDES_VARIANT_IDCODE_OBS", AR_SERDES_SBUS_FE_SERDES_VARIANT_IDCODE_OBS_BP, AR_SERDES_SBUS_FE_SERDES_VARIANT_IDCODE_OBS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ff_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_FF_RESERVED_31_8_BP, AR_SERDES_SBUS_FF_RESERVED_31_8_MASK },
    { "IDCODE", AR_SERDES_SBUS_FF_IDCODE_BP, AR_SERDES_SBUS_FF_IDCODE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_pmro_ctrl_detail[] = {
    { "RESERVED_31_8", AR_SERDES_PMRO_CTRL_RESERVED_31_8_BP, AR_SERDES_PMRO_CTRL_RESERVED_31_8_MASK },
    { "OSC_RUN_DELAY", AR_SERDES_PMRO_CTRL_OSC_RUN_DELAY_BP, AR_SERDES_PMRO_CTRL_OSC_RUN_DELAY_MASK },
    { "PMRO_ACTIVE_DELAY", AR_SERDES_PMRO_CTRL_PMRO_ACTIVE_DELAY_BP, AR_SERDES_PMRO_CTRL_PMRO_ACTIVE_DELAY_MASK },
    { "PMRO_ACTIVE", AR_SERDES_PMRO_CTRL_PMRO_ACTIVE_BP, AR_SERDES_PMRO_CTRL_PMRO_ACTIVE_MASK },
    { "STATE_BIT_3", AR_SERDES_PMRO_CTRL_STATE_BIT_3_BP, AR_SERDES_PMRO_CTRL_STATE_BIT_3_MASK },
    { "STATE_BIT_2", AR_SERDES_PMRO_CTRL_STATE_BIT_2_BP, AR_SERDES_PMRO_CTRL_STATE_BIT_2_MASK },
    { "STATE_BIT_1", AR_SERDES_PMRO_CTRL_STATE_BIT_1_BP, AR_SERDES_PMRO_CTRL_STATE_BIT_1_MASK },
    { "STATE_BIT_0", AR_SERDES_PMRO_CTRL_STATE_BIT_0_BP, AR_SERDES_PMRO_CTRL_STATE_BIT_0_MASK },
    { "OSC_RUN", AR_SERDES_PMRO_CTRL_OSC_RUN_BP, AR_SERDES_PMRO_CTRL_OSC_RUN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_pmro_std_vt_config_detail[] = {
    { "RESERVED_31_16", AR_SERDES_PMRO_STD_VT_CONFIG_RESERVED_31_16_BP, AR_SERDES_PMRO_STD_VT_CONFIG_RESERVED_31_16_MASK },
    { "BUFFER", AR_SERDES_PMRO_STD_VT_CONFIG_BUFFER_BP, AR_SERDES_PMRO_STD_VT_CONFIG_BUFFER_MASK },
    { "AOI221_SLOW_IN_SLOW_AND", AR_SERDES_PMRO_STD_VT_CONFIG_AOI221_SLOW_IN_SLOW_AND_BP, AR_SERDES_PMRO_STD_VT_CONFIG_AOI221_SLOW_IN_SLOW_AND_MASK },
    { "AOI221_FAST_IN_SLOW_AND", AR_SERDES_PMRO_STD_VT_CONFIG_AOI221_FAST_IN_SLOW_AND_BP, AR_SERDES_PMRO_STD_VT_CONFIG_AOI221_FAST_IN_SLOW_AND_MASK },
    { "AOI221_SLOW_IN_FAST_AND", AR_SERDES_PMRO_STD_VT_CONFIG_AOI221_SLOW_IN_FAST_AND_BP, AR_SERDES_PMRO_STD_VT_CONFIG_AOI221_SLOW_IN_FAST_AND_MASK },
    { "AOI221_FAST_IN_FAST_AND", AR_SERDES_PMRO_STD_VT_CONFIG_AOI221_FAST_IN_FAST_AND_BP, AR_SERDES_PMRO_STD_VT_CONFIG_AOI221_FAST_IN_FAST_AND_MASK },
    { "NOR_THREE_SLOW_IN", AR_SERDES_PMRO_STD_VT_CONFIG_NOR_THREE_SLOW_IN_BP, AR_SERDES_PMRO_STD_VT_CONFIG_NOR_THREE_SLOW_IN_MASK },
    { "NAND_THREE_SLOW_IN", AR_SERDES_PMRO_STD_VT_CONFIG_NAND_THREE_SLOW_IN_BP, AR_SERDES_PMRO_STD_VT_CONFIG_NAND_THREE_SLOW_IN_MASK },
    { "XOR_TWO_SLOW_IN_NIM", AR_SERDES_PMRO_STD_VT_CONFIG_XOR_TWO_SLOW_IN_NIM_BP, AR_SERDES_PMRO_STD_VT_CONFIG_XOR_TWO_SLOW_IN_NIM_MASK },
    { "XOR_TWO_FAST_IN_NIM", AR_SERDES_PMRO_STD_VT_CONFIG_XOR_TWO_FAST_IN_NIM_BP, AR_SERDES_PMRO_STD_VT_CONFIG_XOR_TWO_FAST_IN_NIM_MASK },
    { "XOR_TWO_SLOW_IN_IM", AR_SERDES_PMRO_STD_VT_CONFIG_XOR_TWO_SLOW_IN_IM_BP, AR_SERDES_PMRO_STD_VT_CONFIG_XOR_TWO_SLOW_IN_IM_MASK },
    { "XOR_TWO_FAST_IN_IM", AR_SERDES_PMRO_STD_VT_CONFIG_XOR_TWO_FAST_IN_IM_BP, AR_SERDES_PMRO_STD_VT_CONFIG_XOR_TWO_FAST_IN_IM_MASK },
    { "NOR_TWO_SLOW_IN", AR_SERDES_PMRO_STD_VT_CONFIG_NOR_TWO_SLOW_IN_BP, AR_SERDES_PMRO_STD_VT_CONFIG_NOR_TWO_SLOW_IN_MASK },
    { "NOR_TWO_FAST_IN", AR_SERDES_PMRO_STD_VT_CONFIG_NOR_TWO_FAST_IN_BP, AR_SERDES_PMRO_STD_VT_CONFIG_NOR_TWO_FAST_IN_MASK },
    { "NAND_TWO_SLOW_IN", AR_SERDES_PMRO_STD_VT_CONFIG_NAND_TWO_SLOW_IN_BP, AR_SERDES_PMRO_STD_VT_CONFIG_NAND_TWO_SLOW_IN_MASK },
    { "NAND_TWO_FAST_IN", AR_SERDES_PMRO_STD_VT_CONFIG_NAND_TWO_FAST_IN_BP, AR_SERDES_PMRO_STD_VT_CONFIG_NAND_TWO_FAST_IN_MASK },
    { "INVERTER", AR_SERDES_PMRO_STD_VT_CONFIG_INVERTER_BP, AR_SERDES_PMRO_STD_VT_CONFIG_INVERTER_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_pmro_hi_vt_config_detail[] = {
    { "RESERVED_31_16", AR_SERDES_PMRO_HI_VT_CONFIG_RESERVED_31_16_BP, AR_SERDES_PMRO_HI_VT_CONFIG_RESERVED_31_16_MASK },
    { "BUFFER", AR_SERDES_PMRO_HI_VT_CONFIG_BUFFER_BP, AR_SERDES_PMRO_HI_VT_CONFIG_BUFFER_MASK },
    { "AOI221_SLOW_IN_SLOW_AND", AR_SERDES_PMRO_HI_VT_CONFIG_AOI221_SLOW_IN_SLOW_AND_BP, AR_SERDES_PMRO_HI_VT_CONFIG_AOI221_SLOW_IN_SLOW_AND_MASK },
    { "AOI221_FAST_IN_SLOW_AND", AR_SERDES_PMRO_HI_VT_CONFIG_AOI221_FAST_IN_SLOW_AND_BP, AR_SERDES_PMRO_HI_VT_CONFIG_AOI221_FAST_IN_SLOW_AND_MASK },
    { "AOI221_SLOW_IN_FAST_AND", AR_SERDES_PMRO_HI_VT_CONFIG_AOI221_SLOW_IN_FAST_AND_BP, AR_SERDES_PMRO_HI_VT_CONFIG_AOI221_SLOW_IN_FAST_AND_MASK },
    { "AOI221_FAST_IN_FAST_AND", AR_SERDES_PMRO_HI_VT_CONFIG_AOI221_FAST_IN_FAST_AND_BP, AR_SERDES_PMRO_HI_VT_CONFIG_AOI221_FAST_IN_FAST_AND_MASK },
    { "NOR_THREE_SLOW_IN", AR_SERDES_PMRO_HI_VT_CONFIG_NOR_THREE_SLOW_IN_BP, AR_SERDES_PMRO_HI_VT_CONFIG_NOR_THREE_SLOW_IN_MASK },
    { "NAND_THREE_SLOW_IN", AR_SERDES_PMRO_HI_VT_CONFIG_NAND_THREE_SLOW_IN_BP, AR_SERDES_PMRO_HI_VT_CONFIG_NAND_THREE_SLOW_IN_MASK },
    { "XOR_TWO_SLOW_IN_NIM", AR_SERDES_PMRO_HI_VT_CONFIG_XOR_TWO_SLOW_IN_NIM_BP, AR_SERDES_PMRO_HI_VT_CONFIG_XOR_TWO_SLOW_IN_NIM_MASK },
    { "XOR_TWO_FAST_IN_NIM", AR_SERDES_PMRO_HI_VT_CONFIG_XOR_TWO_FAST_IN_NIM_BP, AR_SERDES_PMRO_HI_VT_CONFIG_XOR_TWO_FAST_IN_NIM_MASK },
    { "XOR_TWO_SLOW_IN_IM", AR_SERDES_PMRO_HI_VT_CONFIG_XOR_TWO_SLOW_IN_IM_BP, AR_SERDES_PMRO_HI_VT_CONFIG_XOR_TWO_SLOW_IN_IM_MASK },
    { "XOR_TWO_FAST_IN_IM", AR_SERDES_PMRO_HI_VT_CONFIG_XOR_TWO_FAST_IN_IM_BP, AR_SERDES_PMRO_HI_VT_CONFIG_XOR_TWO_FAST_IN_IM_MASK },
    { "NOR_TWO_SLOW_IN", AR_SERDES_PMRO_HI_VT_CONFIG_NOR_TWO_SLOW_IN_BP, AR_SERDES_PMRO_HI_VT_CONFIG_NOR_TWO_SLOW_IN_MASK },
    { "NOR_TWO_FAST_IN", AR_SERDES_PMRO_HI_VT_CONFIG_NOR_TWO_FAST_IN_BP, AR_SERDES_PMRO_HI_VT_CONFIG_NOR_TWO_FAST_IN_MASK },
    { "NAND_TWO_SLOW_IN", AR_SERDES_PMRO_HI_VT_CONFIG_NAND_TWO_SLOW_IN_BP, AR_SERDES_PMRO_HI_VT_CONFIG_NAND_TWO_SLOW_IN_MASK },
    { "NAND_TWO_FAST_IN", AR_SERDES_PMRO_HI_VT_CONFIG_NAND_TWO_FAST_IN_BP, AR_SERDES_PMRO_HI_VT_CONFIG_NAND_TWO_FAST_IN_MASK },
    { "INVERTER", AR_SERDES_PMRO_HI_VT_CONFIG_INVERTER_BP, AR_SERDES_PMRO_HI_VT_CONFIG_INVERTER_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_pmro_lo_vt_config_detail[] = {
    { "RESERVED_31_16", AR_SERDES_PMRO_LO_VT_CONFIG_RESERVED_31_16_BP, AR_SERDES_PMRO_LO_VT_CONFIG_RESERVED_31_16_MASK },
    { "BUFFER", AR_SERDES_PMRO_LO_VT_CONFIG_BUFFER_BP, AR_SERDES_PMRO_LO_VT_CONFIG_BUFFER_MASK },
    { "AOI221_SLOW_IN_SLOW_AND", AR_SERDES_PMRO_LO_VT_CONFIG_AOI221_SLOW_IN_SLOW_AND_BP, AR_SERDES_PMRO_LO_VT_CONFIG_AOI221_SLOW_IN_SLOW_AND_MASK },
    { "AOI221_FAST_IN_SLOW_AND", AR_SERDES_PMRO_LO_VT_CONFIG_AOI221_FAST_IN_SLOW_AND_BP, AR_SERDES_PMRO_LO_VT_CONFIG_AOI221_FAST_IN_SLOW_AND_MASK },
    { "AOI221_SLOW_IN_FAST_AND", AR_SERDES_PMRO_LO_VT_CONFIG_AOI221_SLOW_IN_FAST_AND_BP, AR_SERDES_PMRO_LO_VT_CONFIG_AOI221_SLOW_IN_FAST_AND_MASK },
    { "AOI221_FAST_IN_FAST_AND", AR_SERDES_PMRO_LO_VT_CONFIG_AOI221_FAST_IN_FAST_AND_BP, AR_SERDES_PMRO_LO_VT_CONFIG_AOI221_FAST_IN_FAST_AND_MASK },
    { "NOR_THREE_SLOW_IN", AR_SERDES_PMRO_LO_VT_CONFIG_NOR_THREE_SLOW_IN_BP, AR_SERDES_PMRO_LO_VT_CONFIG_NOR_THREE_SLOW_IN_MASK },
    { "NAND_THREE_SLOW_IN", AR_SERDES_PMRO_LO_VT_CONFIG_NAND_THREE_SLOW_IN_BP, AR_SERDES_PMRO_LO_VT_CONFIG_NAND_THREE_SLOW_IN_MASK },
    { "XOR_TWO_SLOW_IN_NIM", AR_SERDES_PMRO_LO_VT_CONFIG_XOR_TWO_SLOW_IN_NIM_BP, AR_SERDES_PMRO_LO_VT_CONFIG_XOR_TWO_SLOW_IN_NIM_MASK },
    { "XOR_TWO_FAST_IN_NIM", AR_SERDES_PMRO_LO_VT_CONFIG_XOR_TWO_FAST_IN_NIM_BP, AR_SERDES_PMRO_LO_VT_CONFIG_XOR_TWO_FAST_IN_NIM_MASK },
    { "XOR_TWO_SLOW_IN_IM", AR_SERDES_PMRO_LO_VT_CONFIG_XOR_TWO_SLOW_IN_IM_BP, AR_SERDES_PMRO_LO_VT_CONFIG_XOR_TWO_SLOW_IN_IM_MASK },
    { "XOR_TWO_FAST_IN_IM", AR_SERDES_PMRO_LO_VT_CONFIG_XOR_TWO_FAST_IN_IM_BP, AR_SERDES_PMRO_LO_VT_CONFIG_XOR_TWO_FAST_IN_IM_MASK },
    { "NOR_TWO_SLOW_IN", AR_SERDES_PMRO_LO_VT_CONFIG_NOR_TWO_SLOW_IN_BP, AR_SERDES_PMRO_LO_VT_CONFIG_NOR_TWO_SLOW_IN_MASK },
    { "NOR_TWO_FAST_IN", AR_SERDES_PMRO_LO_VT_CONFIG_NOR_TWO_FAST_IN_BP, AR_SERDES_PMRO_LO_VT_CONFIG_NOR_TWO_FAST_IN_MASK },
    { "NAND_TWO_SLOW_IN", AR_SERDES_PMRO_LO_VT_CONFIG_NAND_TWO_SLOW_IN_BP, AR_SERDES_PMRO_LO_VT_CONFIG_NAND_TWO_SLOW_IN_MASK },
    { "NAND_TWO_FAST_IN", AR_SERDES_PMRO_LO_VT_CONFIG_NAND_TWO_FAST_IN_BP, AR_SERDES_PMRO_LO_VT_CONFIG_NAND_TWO_FAST_IN_MASK },
    { "INVERTER", AR_SERDES_PMRO_LO_VT_CONFIG_INVERTER_BP, AR_SERDES_PMRO_LO_VT_CONFIG_INVERTER_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_pmro_ref_clk_cntr_detail[] = {
    { "RESERVED_31_16", AR_SERDES_PMRO_REF_CLK_CNTR_RESERVED_31_16_BP, AR_SERDES_PMRO_REF_CLK_CNTR_RESERVED_31_16_MASK },
    { "COUNTER_VALUE", AR_SERDES_PMRO_REF_CLK_CNTR_COUNTER_VALUE_BP, AR_SERDES_PMRO_REF_CLK_CNTR_COUNTER_VALUE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_pmro_osc_cntr_detail[] = {
    { "RESERVED_31_16", AR_SERDES_PMRO_OSC_CNTR_RESERVED_31_16_BP, AR_SERDES_PMRO_OSC_CNTR_RESERVED_31_16_MASK },
    { "OSC_COUNT", AR_SERDES_PMRO_OSC_CNTR_OSC_COUNT_BP, AR_SERDES_PMRO_OSC_CNTR_OSC_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_pmro_unimplemented_detail[] = {
    { "RESERVED_31_0", AR_SERDES_PMRO_UNIMPLEMENTED_RESERVED_31_0_BP, AR_SERDES_PMRO_UNIMPLEMENTED_RESERVED_31_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_pmro_sbus_id_detail[] = {
    { "RESERVED_31_8", AR_SERDES_PMRO_SBUS_ID_RESERVED_31_8_BP, AR_SERDES_PMRO_SBUS_ID_RESERVED_31_8_MASK },
    { "SBUS_ID", AR_SERDES_PMRO_SBUS_ID_SBUS_ID_BP, AR_SERDES_PMRO_SBUS_ID_SBUS_ID_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_00_detail[] = {
    { "RESERVED_31_2", AR_SERDES_SBUS_CTRL_00_RESERVED_31_2_BP, AR_SERDES_SBUS_CTRL_00_RESERVED_31_2_MASK },
    { "CISM_LOOP", AR_SERDES_SBUS_CTRL_00_CISM_LOOP_BP, AR_SERDES_SBUS_CTRL_00_CISM_LOOP_MASK },
    { "CISM_START", AR_SERDES_SBUS_CTRL_00_CISM_START_BP, AR_SERDES_SBUS_CTRL_00_CISM_START_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_01_detail[] = {
    { "RESERVED_31_5", AR_SERDES_SBUS_CTRL_01_RESERVED_31_5_BP, AR_SERDES_SBUS_CTRL_01_RESERVED_31_5_MASK },
    { "CISM_TIMER_VALUE", AR_SERDES_SBUS_CTRL_01_CISM_TIMER_VALUE_BP, AR_SERDES_SBUS_CTRL_01_CISM_TIMER_VALUE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_02_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_CTRL_02_RESERVED_31_8_BP, AR_SERDES_SBUS_CTRL_02_RESERVED_31_8_MASK },
    { "LAST_SBUS_ADDRESS", AR_SERDES_SBUS_CTRL_02_LAST_SBUS_ADDRESS_BP, AR_SERDES_SBUS_CTRL_02_LAST_SBUS_ADDRESS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_0a_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_CTRL_0A_RESERVED_31_8_BP, AR_SERDES_SBUS_CTRL_0A_RESERVED_31_8_MASK },
    { "CLOCK_DIVIDER_SETTING0", AR_SERDES_SBUS_CTRL_0A_CLOCK_DIVIDER_SETTING0_BP, AR_SERDES_SBUS_CTRL_0A_CLOCK_DIVIDER_SETTING0_MASK },
    { "CLOCK_DIVIDER_SETTING1", AR_SERDES_SBUS_CTRL_0A_CLOCK_DIVIDER_SETTING1_BP, AR_SERDES_SBUS_CTRL_0A_CLOCK_DIVIDER_SETTING1_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_0b_detail[] = {
    { "RESERVED_31_12", AR_SERDES_SBUS_CTRL_0B_RESERVED_31_12_BP, AR_SERDES_SBUS_CTRL_0B_RESERVED_31_12_MASK },
    { "CLOCK_DIVIDER_RESET_VALUE", AR_SERDES_SBUS_CTRL_0B_CLOCK_DIVIDER_RESET_VALUE_BP, AR_SERDES_SBUS_CTRL_0B_CLOCK_DIVIDER_RESET_VALUE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_0c_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_CTRL_0C_RESERVED_31_8_BP, AR_SERDES_SBUS_CTRL_0C_RESERVED_31_8_MASK },
    { "CISM_LOOP", AR_SERDES_SBUS_CTRL_0C_CISM_LOOP_BP, AR_SERDES_SBUS_CTRL_0C_CISM_LOOP_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_0d_detail[] = {
    { "RESERVED_31_4", AR_SERDES_SBUS_CTRL_0D_RESERVED_31_4_BP, AR_SERDES_SBUS_CTRL_0D_RESERVED_31_4_MASK },
    { "CLOCK_DIVIDER_RESET_VALUE_PAGE1", AR_SERDES_SBUS_CTRL_0D_CLOCK_DIVIDER_RESET_VALUE_PAGE1_BP, AR_SERDES_SBUS_CTRL_0D_CLOCK_DIVIDER_RESET_VALUE_PAGE1_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_10_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_CTRL_10_RESERVED_31_8_BP, AR_SERDES_SBUS_CTRL_10_RESERVED_31_8_MASK },
    { "CISM_SBUS_RX_ADDRESS", AR_SERDES_SBUS_CTRL_10_CISM_SBUS_RX_ADDRESS_BP, AR_SERDES_SBUS_CTRL_10_CISM_SBUS_RX_ADDRESS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_11_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_CTRL_11_RESERVED_31_8_BP, AR_SERDES_SBUS_CTRL_11_RESERVED_31_8_MASK },
    { "CISM_COMMAND_1", AR_SERDES_SBUS_CTRL_11_CISM_COMMAND_1_BP, AR_SERDES_SBUS_CTRL_11_CISM_COMMAND_1_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_12_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_CTRL_12_RESERVED_31_8_BP, AR_SERDES_SBUS_CTRL_12_RESERVED_31_8_MASK },
    { "CISM_DATA_ADDRESS_1", AR_SERDES_SBUS_CTRL_12_CISM_DATA_ADDRESS_1_BP, AR_SERDES_SBUS_CTRL_12_CISM_DATA_ADDRESS_1_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_13_detail[] = {
    { "CISM_DATA_WORD_1", AR_SERDES_SBUS_CTRL_13_CISM_DATA_WORD_1_BP, AR_SERDES_SBUS_CTRL_13_CISM_DATA_WORD_1_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_14_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_CTRL_14_RESERVED_31_8_BP, AR_SERDES_SBUS_CTRL_14_RESERVED_31_8_MASK },
    { "CISM_COMMAND_2", AR_SERDES_SBUS_CTRL_14_CISM_COMMAND_2_BP, AR_SERDES_SBUS_CTRL_14_CISM_COMMAND_2_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_15_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_CTRL_15_RESERVED_31_8_BP, AR_SERDES_SBUS_CTRL_15_RESERVED_31_8_MASK },
    { "CISM_DATA_ADDRESS_2", AR_SERDES_SBUS_CTRL_15_CISM_DATA_ADDRESS_2_BP, AR_SERDES_SBUS_CTRL_15_CISM_DATA_ADDRESS_2_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_16_detail[] = {
    { "CISM_DATA_WORD_2", AR_SERDES_SBUS_CTRL_16_CISM_DATA_WORD_2_BP, AR_SERDES_SBUS_CTRL_16_CISM_DATA_WORD_2_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_20_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_CTRL_20_RESERVED_31_8_BP, AR_SERDES_SBUS_CTRL_20_RESERVED_31_8_MASK },
    { "BSB_SELECT", AR_SERDES_SBUS_CTRL_20_BSB_SELECT_BP, AR_SERDES_SBUS_CTRL_20_BSB_SELECT_MASK },
    { "BSB_CONTROL", AR_SERDES_SBUS_CTRL_20_BSB_CONTROL_BP, AR_SERDES_SBUS_CTRL_20_BSB_CONTROL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_80_detail[] = {
    { "GENERIC_WRITE", AR_SERDES_SBUS_CTRL_80_GENERIC_WRITE_BP, AR_SERDES_SBUS_CTRL_80_GENERIC_WRITE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_81_detail[] = {
    { "RESERVED_31_0", AR_SERDES_SBUS_CTRL_81_RESERVED_31_0_BP, AR_SERDES_SBUS_CTRL_81_RESERVED_31_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_82_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_CTRL_82_RESERVED_31_8_BP, AR_SERDES_SBUS_CTRL_82_RESERVED_31_8_MASK },
    { "GENERIC_WRITE_PAGE0", AR_SERDES_SBUS_CTRL_82_GENERIC_WRITE_PAGE0_BP, AR_SERDES_SBUS_CTRL_82_GENERIC_WRITE_PAGE0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_83_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_CTRL_83_RESERVED_31_8_BP, AR_SERDES_SBUS_CTRL_83_RESERVED_31_8_MASK },
    { "GENERIC_WRITE_PAGE1", AR_SERDES_SBUS_CTRL_83_GENERIC_WRITE_PAGE1_BP, AR_SERDES_SBUS_CTRL_83_GENERIC_WRITE_PAGE1_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_84_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_CTRL_84_RESERVED_31_8_BP, AR_SERDES_SBUS_CTRL_84_RESERVED_31_8_MASK },
    { "GENERIC_WRITE_PAGE2", AR_SERDES_SBUS_CTRL_84_GENERIC_WRITE_PAGE2_BP, AR_SERDES_SBUS_CTRL_84_GENERIC_WRITE_PAGE2_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_85_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_CTRL_85_RESERVED_31_8_BP, AR_SERDES_SBUS_CTRL_85_RESERVED_31_8_MASK },
    { "GENERIC_WRITE_PAGE3", AR_SERDES_SBUS_CTRL_85_GENERIC_WRITE_PAGE3_BP, AR_SERDES_SBUS_CTRL_85_GENERIC_WRITE_PAGE3_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_86_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_CTRL_86_RESERVED_31_8_BP, AR_SERDES_SBUS_CTRL_86_RESERVED_31_8_MASK },
    { "GENERIC_READ_PAGE0", AR_SERDES_SBUS_CTRL_86_GENERIC_READ_PAGE0_BP, AR_SERDES_SBUS_CTRL_86_GENERIC_READ_PAGE0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_87_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_CTRL_87_RESERVED_31_8_BP, AR_SERDES_SBUS_CTRL_87_RESERVED_31_8_MASK },
    { "GENERIC_READ_PAGE1", AR_SERDES_SBUS_CTRL_87_GENERIC_READ_PAGE1_BP, AR_SERDES_SBUS_CTRL_87_GENERIC_READ_PAGE1_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_88_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_CTRL_88_RESERVED_31_8_BP, AR_SERDES_SBUS_CTRL_88_RESERVED_31_8_MASK },
    { "GENERIC_READ_PAGE2", AR_SERDES_SBUS_CTRL_88_GENERIC_READ_PAGE2_BP, AR_SERDES_SBUS_CTRL_88_GENERIC_READ_PAGE2_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_89_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_CTRL_89_RESERVED_31_8_BP, AR_SERDES_SBUS_CTRL_89_RESERVED_31_8_MASK },
    { "GENERIC_READ_PAGE3", AR_SERDES_SBUS_CTRL_89_GENERIC_READ_PAGE3_BP, AR_SERDES_SBUS_CTRL_89_GENERIC_READ_PAGE3_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_fe_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_CTRL_FE_RESERVED_31_8_BP, AR_SERDES_SBUS_CTRL_FE_RESERVED_31_8_MASK },
    { "SBUS_ID", AR_SERDES_SBUS_CTRL_FE_SBUS_ID_BP, AR_SERDES_SBUS_CTRL_FE_SBUS_ID_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_serdes_sbus_ctrl_ff_detail[] = {
    { "RESERVED_31_8", AR_SERDES_SBUS_CTRL_FF_RESERVED_31_8_BP, AR_SERDES_SBUS_CTRL_FF_RESERVED_31_8_MASK },
    { "IP_IDCODE", AR_SERDES_SBUS_CTRL_FF_IP_IDCODE_BP, AR_SERDES_SBUS_CTRL_FF_IP_IDCODE_MASK },
    { NULL, 0, 0 }
};

/*
 *  AR SBUS MMR DECLARATIONS
 */
static const generic_mmr_t _ar_serdes_sbus_00 = {
    "AR_SERDES_SBUS_00", AR_SERDES_SBUS_00, 8, 1, _ar_serdes_sbus_00_detail
};
static const generic_mmr_t _ar_serdes_sbus_01 = {
    "AR_SERDES_SBUS_01", AR_SERDES_SBUS_01, 8, 1, _ar_serdes_sbus_01_detail
};
static const generic_mmr_t _ar_serdes_sbus_02 = {
    "AR_SERDES_SBUS_02", AR_SERDES_SBUS_02, 8, 1, _ar_serdes_sbus_02_detail
};
static const generic_mmr_t _ar_serdes_sbus_03 = {
    "AR_SERDES_SBUS_03", AR_SERDES_SBUS_03, 8, 1, _ar_serdes_sbus_03_detail
};
static const generic_mmr_t _ar_serdes_sbus_05 = {
    "AR_SERDES_SBUS_05", AR_SERDES_SBUS_05, 8, 1, _ar_serdes_sbus_05_detail
};
static const generic_mmr_t _ar_serdes_sbus_06 = {
    "AR_SERDES_SBUS_06", AR_SERDES_SBUS_06, 8, 1, _ar_serdes_sbus_06_detail
};
static const generic_mmr_t _ar_serdes_sbus_07 = {
    "AR_SERDES_SBUS_07", AR_SERDES_SBUS_07, 8, 1, _ar_serdes_sbus_07_detail
};
static const generic_mmr_t _ar_serdes_sbus_0b = {
    "AR_SERDES_SBUS_0B", AR_SERDES_SBUS_0B, 8, 1, _ar_serdes_sbus_0b_detail
};
static const generic_mmr_t _ar_serdes_sbus_3c = {
    "AR_SERDES_SBUS_3C", AR_SERDES_SBUS_3C, 8, 1, _ar_serdes_sbus_3c_detail
};
static const generic_mmr_t _ar_serdes_sbus_3d = {
    "AR_SERDES_SBUS_3D", AR_SERDES_SBUS_3D, 8, 1, _ar_serdes_sbus_3d_detail
};
static const generic_mmr_t _ar_serdes_sbus_3e = {
    "AR_SERDES_SBUS_3E", AR_SERDES_SBUS_3E, 8, 1, _ar_serdes_sbus_3e_detail
};
static const generic_mmr_t _ar_serdes_sbus_3f = {
    "AR_SERDES_SBUS_3F", AR_SERDES_SBUS_3F, 8, 1, _ar_serdes_sbus_3f_detail
};
static const generic_mmr_t _ar_serdes_sbus_40 = {
    "AR_SERDES_SBUS_40", AR_SERDES_SBUS_40, 8, 1, _ar_serdes_sbus_40_detail
};
static const generic_mmr_t _ar_serdes_sbus_41 = {
    "AR_SERDES_SBUS_41", AR_SERDES_SBUS_41, 8, 1, _ar_serdes_sbus_41_detail
};
static const generic_mmr_t _ar_serdes_sbus_50 = {
    "AR_SERDES_SBUS_50", AR_SERDES_SBUS_50, 8, 1, _ar_serdes_sbus_50_detail
};
static const generic_mmr_t _ar_serdes_sbus_51 = {
    "AR_SERDES_SBUS_51", AR_SERDES_SBUS_51, 8, 1, _ar_serdes_sbus_51_detail
};
static const generic_mmr_t _ar_serdes_sbus_52 = {
    "AR_SERDES_SBUS_52", AR_SERDES_SBUS_52, 8, 1, _ar_serdes_sbus_52_detail
};
static const generic_mmr_t _ar_serdes_sbus_53 = {
    "AR_SERDES_SBUS_53", AR_SERDES_SBUS_53, 8, 1, _ar_serdes_sbus_53_detail
};
static const generic_mmr_t _ar_serdes_sbus_54 = {
    "AR_SERDES_SBUS_54", AR_SERDES_SBUS_54, 8, 1, _ar_serdes_sbus_54_detail
};
static const generic_mmr_t _ar_serdes_sbus_55 = {
    "AR_SERDES_SBUS_55", AR_SERDES_SBUS_55, 8, 1, _ar_serdes_sbus_55_detail
};
static const generic_mmr_t _ar_serdes_sbus_56 = {
    "AR_SERDES_SBUS_56", AR_SERDES_SBUS_56, 8, 1, _ar_serdes_sbus_56_detail
};
static const generic_mmr_t _ar_serdes_sbus_57 = {
    "AR_SERDES_SBUS_57", AR_SERDES_SBUS_57, 8, 1, _ar_serdes_sbus_57_detail
};
static const generic_mmr_t _ar_serdes_sbus_58 = {
    "AR_SERDES_SBUS_58", AR_SERDES_SBUS_58, 8, 1, _ar_serdes_sbus_58_detail
};
static const generic_mmr_t _ar_serdes_sbus_59 = {
    "AR_SERDES_SBUS_59", AR_SERDES_SBUS_59, 8, 1, _ar_serdes_sbus_59_detail
};
static const generic_mmr_t _ar_serdes_sbus_5a = {
    "AR_SERDES_SBUS_5A", AR_SERDES_SBUS_5A, 8, 1, _ar_serdes_sbus_5a_detail
};
static const generic_mmr_t _ar_serdes_sbus_5b = {
    "AR_SERDES_SBUS_5B", AR_SERDES_SBUS_5B, 8, 1, _ar_serdes_sbus_5b_detail
};
static const generic_mmr_t _ar_serdes_sbus_64 = {
    "AR_SERDES_SBUS_64", AR_SERDES_SBUS_64, 8, 1, _ar_serdes_sbus_64_detail
};
static const generic_mmr_t _ar_serdes_sbus_65 = {
    "AR_SERDES_SBUS_65", AR_SERDES_SBUS_65, 8, 1, _ar_serdes_sbus_65_detail
};
static const generic_mmr_t _ar_serdes_sbus_67 = {
    "AR_SERDES_SBUS_67", AR_SERDES_SBUS_67, 8, 1, _ar_serdes_sbus_67_detail
};
static const generic_mmr_t _ar_serdes_sbus_68 = {
    "AR_SERDES_SBUS_68", AR_SERDES_SBUS_68, 8, 1, _ar_serdes_sbus_68_detail
};
static const generic_mmr_t _ar_serdes_sbus_69 = {
    "AR_SERDES_SBUS_69", AR_SERDES_SBUS_69, 8, 1, _ar_serdes_sbus_69_detail
};
static const generic_mmr_t _ar_serdes_sbus_6a = {
    "AR_SERDES_SBUS_6A", AR_SERDES_SBUS_6A, 8, 1, _ar_serdes_sbus_6a_detail
};
static const generic_mmr_t _ar_serdes_sbus_6b = {
    "AR_SERDES_SBUS_6B", AR_SERDES_SBUS_6B, 8, 1, _ar_serdes_sbus_6b_detail
};
static const generic_mmr_t _ar_serdes_sbus_81 = {
    "AR_SERDES_SBUS_81", AR_SERDES_SBUS_81, 8, 1, _ar_serdes_sbus_81_detail
};
static const generic_mmr_t _ar_serdes_sbus_82 = {
    "AR_SERDES_SBUS_82", AR_SERDES_SBUS_82, 8, 1, _ar_serdes_sbus_82_detail
};
static const generic_mmr_t _ar_serdes_sbus_8c = {
    "AR_SERDES_SBUS_8C", AR_SERDES_SBUS_8C, 8, 1, _ar_serdes_sbus_8c_detail
};
static const generic_mmr_t _ar_serdes_sbus_8e = {
    "AR_SERDES_SBUS_8E", AR_SERDES_SBUS_8E, 8, 1, _ar_serdes_sbus_8e_detail
};
static const generic_mmr_t _ar_serdes_sbus_8f = {
    "AR_SERDES_SBUS_8F", AR_SERDES_SBUS_8F, 8, 1, _ar_serdes_sbus_8f_detail
};
static const generic_mmr_t _ar_serdes_sbus_90 = {
    "AR_SERDES_SBUS_90", AR_SERDES_SBUS_90, 8, 1, _ar_serdes_sbus_90_detail
};
static const generic_mmr_t _ar_serdes_sbus_92 = {
    "AR_SERDES_SBUS_92", AR_SERDES_SBUS_92, 8, 1, _ar_serdes_sbus_92_detail
};
static const generic_mmr_t _ar_serdes_sbus_93 = {
    "AR_SERDES_SBUS_93", AR_SERDES_SBUS_93, 8, 1, _ar_serdes_sbus_93_detail
};
static const generic_mmr_t _ar_serdes_sbus_95 = {
    "AR_SERDES_SBUS_95", AR_SERDES_SBUS_95, 8, 1, _ar_serdes_sbus_95_detail
};
static const generic_mmr_t _ar_serdes_sbus_ad = {
    "AR_SERDES_SBUS_AD", AR_SERDES_SBUS_AD, 8, 1, _ar_serdes_sbus_ad_detail
};
static const generic_mmr_t _ar_serdes_sbus_ae = {
    "AR_SERDES_SBUS_AE", AR_SERDES_SBUS_AE, 8, 1, _ar_serdes_sbus_ae_detail
};
static const generic_mmr_t _ar_serdes_sbus_af = {
    "AR_SERDES_SBUS_AF", AR_SERDES_SBUS_AF, 8, 1, _ar_serdes_sbus_af_detail
};
static const generic_mmr_t _ar_serdes_sbus_b3 = {
    "AR_SERDES_SBUS_B3", AR_SERDES_SBUS_B3, 8, 1, _ar_serdes_sbus_b3_detail
};
static const generic_mmr_t _ar_serdes_sbus_fc = {
    "AR_SERDES_SBUS_FC", AR_SERDES_SBUS_FC, 8, 1, _ar_serdes_sbus_fc_detail
};
static const generic_mmr_t _ar_serdes_sbus_fd = {
    "AR_SERDES_SBUS_FD", AR_SERDES_SBUS_FD, 8, 1, _ar_serdes_sbus_fd_detail
};
static const generic_mmr_t _ar_serdes_sbus_fe = {
    "AR_SERDES_SBUS_FE", AR_SERDES_SBUS_FE, 8, 1, _ar_serdes_sbus_fe_detail
};
static const generic_mmr_t _ar_serdes_sbus_ff = {
    "AR_SERDES_SBUS_FF", AR_SERDES_SBUS_FF, 8, 1, _ar_serdes_sbus_ff_detail
};
static const generic_mmr_t _ar_serdes_pmro_ctrl = {
    "AR_SERDES_PMRO_CTRL", AR_SERDES_PMRO_CTRL, 8, 1, _ar_serdes_pmro_ctrl_detail
};
static const generic_mmr_t _ar_serdes_pmro_std_vt_config = {
    "AR_SERDES_PMRO_STD_VT_CONFIG", AR_SERDES_PMRO_STD_VT_CONFIG, 8, 1, _ar_serdes_pmro_std_vt_config_detail
};
static const generic_mmr_t _ar_serdes_pmro_hi_vt_config = {
    "AR_SERDES_PMRO_HI_VT_CONFIG", AR_SERDES_PMRO_HI_VT_CONFIG, 8, 1, _ar_serdes_pmro_hi_vt_config_detail
};
static const generic_mmr_t _ar_serdes_pmro_lo_vt_config = {
    "AR_SERDES_PMRO_LO_VT_CONFIG", AR_SERDES_PMRO_LO_VT_CONFIG, 8, 1, _ar_serdes_pmro_lo_vt_config_detail
};
static const generic_mmr_t _ar_serdes_pmro_ref_clk_cntr = {
    "AR_SERDES_PMRO_REF_CLK_CNTR", AR_SERDES_PMRO_REF_CLK_CNTR, 8, 1, _ar_serdes_pmro_ref_clk_cntr_detail
};
static const generic_mmr_t _ar_serdes_pmro_osc_cntr = {
    "AR_SERDES_PMRO_OSC_CNTR", AR_SERDES_PMRO_OSC_CNTR, 8, 1, _ar_serdes_pmro_osc_cntr_detail
};
static const generic_mmr_t _ar_serdes_pmro_unimplemented = {
    "AR_SERDES_PMRO_UNIMPLEMENTED", AR_SERDES_PMRO_UNIMPLEMENTED, 8, 1, _ar_serdes_pmro_unimplemented_detail
};
static const generic_mmr_t _ar_serdes_pmro_sbus_id = {
    "AR_SERDES_PMRO_SBUS_ID", AR_SERDES_PMRO_SBUS_ID, 8, 1, _ar_serdes_pmro_sbus_id_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_00 = {
    "AR_SERDES_SBUS_CTRL_00", AR_SERDES_SBUS_CTRL_00, 8, 1, _ar_serdes_sbus_ctrl_00_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_01 = {
    "AR_SERDES_SBUS_CTRL_01", AR_SERDES_SBUS_CTRL_01, 8, 1, _ar_serdes_sbus_ctrl_01_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_02 = {
    "AR_SERDES_SBUS_CTRL_02", AR_SERDES_SBUS_CTRL_02, 8, 1, _ar_serdes_sbus_ctrl_02_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_0a = {
    "AR_SERDES_SBUS_CTRL_0A", AR_SERDES_SBUS_CTRL_0A, 8, 1, _ar_serdes_sbus_ctrl_0a_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_0b = {
    "AR_SERDES_SBUS_CTRL_0B", AR_SERDES_SBUS_CTRL_0B, 8, 1, _ar_serdes_sbus_ctrl_0b_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_0c = {
    "AR_SERDES_SBUS_CTRL_0C", AR_SERDES_SBUS_CTRL_0C, 8, 1, _ar_serdes_sbus_ctrl_0c_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_0d = {
    "AR_SERDES_SBUS_CTRL_0D", AR_SERDES_SBUS_CTRL_0D, 8, 1, _ar_serdes_sbus_ctrl_0d_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_10 = {
    "AR_SERDES_SBUS_CTRL_10", AR_SERDES_SBUS_CTRL_10, 8, 1, _ar_serdes_sbus_ctrl_10_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_11 = {
    "AR_SERDES_SBUS_CTRL_11", AR_SERDES_SBUS_CTRL_11, 8, 1, _ar_serdes_sbus_ctrl_11_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_12 = {
    "AR_SERDES_SBUS_CTRL_12", AR_SERDES_SBUS_CTRL_12, 8, 1, _ar_serdes_sbus_ctrl_12_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_13 = {
    "AR_SERDES_SBUS_CTRL_13", AR_SERDES_SBUS_CTRL_13, 8, 1, _ar_serdes_sbus_ctrl_13_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_14 = {
    "AR_SERDES_SBUS_CTRL_14", AR_SERDES_SBUS_CTRL_14, 8, 1, _ar_serdes_sbus_ctrl_14_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_15 = {
    "AR_SERDES_SBUS_CTRL_15", AR_SERDES_SBUS_CTRL_15, 8, 1, _ar_serdes_sbus_ctrl_15_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_16 = {
    "AR_SERDES_SBUS_CTRL_16", AR_SERDES_SBUS_CTRL_16, 8, 1, _ar_serdes_sbus_ctrl_16_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_20 = {
    "AR_SERDES_SBUS_CTRL_20", AR_SERDES_SBUS_CTRL_20, 8, 1, _ar_serdes_sbus_ctrl_20_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_80 = {
    "AR_SERDES_SBUS_CTRL_80", AR_SERDES_SBUS_CTRL_80, 8, 1, _ar_serdes_sbus_ctrl_80_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_81 = {
    "AR_SERDES_SBUS_CTRL_81", AR_SERDES_SBUS_CTRL_81, 8, 1, _ar_serdes_sbus_ctrl_81_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_82 = {
    "AR_SERDES_SBUS_CTRL_82", AR_SERDES_SBUS_CTRL_82, 8, 1, _ar_serdes_sbus_ctrl_82_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_83 = {
    "AR_SERDES_SBUS_CTRL_83", AR_SERDES_SBUS_CTRL_83, 8, 1, _ar_serdes_sbus_ctrl_83_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_84 = {
    "AR_SERDES_SBUS_CTRL_84", AR_SERDES_SBUS_CTRL_84, 8, 1, _ar_serdes_sbus_ctrl_84_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_85 = {
    "AR_SERDES_SBUS_CTRL_85", AR_SERDES_SBUS_CTRL_85, 8, 1, _ar_serdes_sbus_ctrl_85_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_86 = {
    "AR_SERDES_SBUS_CTRL_86", AR_SERDES_SBUS_CTRL_86, 8, 1, _ar_serdes_sbus_ctrl_86_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_87 = {
    "AR_SERDES_SBUS_CTRL_87", AR_SERDES_SBUS_CTRL_87, 8, 1, _ar_serdes_sbus_ctrl_87_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_88 = {
    "AR_SERDES_SBUS_CTRL_88", AR_SERDES_SBUS_CTRL_88, 8, 1, _ar_serdes_sbus_ctrl_88_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_89 = {
    "AR_SERDES_SBUS_CTRL_89", AR_SERDES_SBUS_CTRL_89, 8, 1, _ar_serdes_sbus_ctrl_89_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_fe = {
    "AR_SERDES_SBUS_CTRL_FE", AR_SERDES_SBUS_CTRL_FE, 8, 1, _ar_serdes_sbus_ctrl_fe_detail
};
static const generic_mmr_t _ar_serdes_sbus_ctrl_ff = {
    "AR_SERDES_SBUS_CTRL_FF", AR_SERDES_SBUS_CTRL_FF, 8, 1, _ar_serdes_sbus_ctrl_ff_detail
};

/*
 *  INSTALL AR SBUS MMRS
 */
static const generic_mmr_t* _ar_sbus_mmrs[] _unused = {
    &_ar_serdes_sbus_00,
    &_ar_serdes_sbus_01,
    &_ar_serdes_sbus_02,
    &_ar_serdes_sbus_03,
    &_ar_serdes_sbus_05,
    &_ar_serdes_sbus_06,
    &_ar_serdes_sbus_07,
    &_ar_serdes_sbus_0b,
    &_ar_serdes_sbus_3c,
    &_ar_serdes_sbus_3d,
    &_ar_serdes_sbus_3e,
    &_ar_serdes_sbus_3f,
    &_ar_serdes_sbus_40,
    &_ar_serdes_sbus_41,
    &_ar_serdes_sbus_50,
    &_ar_serdes_sbus_51,
    &_ar_serdes_sbus_52,
    &_ar_serdes_sbus_53,
    &_ar_serdes_sbus_54,
    &_ar_serdes_sbus_55,
    &_ar_serdes_sbus_56,
    &_ar_serdes_sbus_57,
    &_ar_serdes_sbus_58,
    &_ar_serdes_sbus_59,
    &_ar_serdes_sbus_5a,
    &_ar_serdes_sbus_5b,
    &_ar_serdes_sbus_64,
    &_ar_serdes_sbus_65,
    &_ar_serdes_sbus_67,
    &_ar_serdes_sbus_68,
    &_ar_serdes_sbus_69,
    &_ar_serdes_sbus_6a,
    &_ar_serdes_sbus_6b,
    &_ar_serdes_sbus_81,
    &_ar_serdes_sbus_82,
    &_ar_serdes_sbus_8c,
    &_ar_serdes_sbus_8e,
    &_ar_serdes_sbus_8f,
    &_ar_serdes_sbus_90,
    &_ar_serdes_sbus_92,
    &_ar_serdes_sbus_93,
    &_ar_serdes_sbus_95,
    &_ar_serdes_sbus_ad,
    &_ar_serdes_sbus_ae,
    &_ar_serdes_sbus_af,
    &_ar_serdes_sbus_b3,
    &_ar_serdes_sbus_fc,
    &_ar_serdes_sbus_fd,
    &_ar_serdes_sbus_fe,
    &_ar_serdes_sbus_ff,
    &_ar_serdes_pmro_ctrl,
    &_ar_serdes_pmro_std_vt_config,
    &_ar_serdes_pmro_hi_vt_config,
    &_ar_serdes_pmro_lo_vt_config,
    &_ar_serdes_pmro_ref_clk_cntr,
    &_ar_serdes_pmro_osc_cntr,
    &_ar_serdes_pmro_unimplemented,
    &_ar_serdes_pmro_sbus_id,
    &_ar_serdes_sbus_ctrl_00,
    &_ar_serdes_sbus_ctrl_01,
    &_ar_serdes_sbus_ctrl_02,
    &_ar_serdes_sbus_ctrl_0a,
    &_ar_serdes_sbus_ctrl_0b,
    &_ar_serdes_sbus_ctrl_0c,
    &_ar_serdes_sbus_ctrl_0d,
    &_ar_serdes_sbus_ctrl_10,
    &_ar_serdes_sbus_ctrl_11,
    &_ar_serdes_sbus_ctrl_12,
    &_ar_serdes_sbus_ctrl_13,
    &_ar_serdes_sbus_ctrl_14,
    &_ar_serdes_sbus_ctrl_15,
    &_ar_serdes_sbus_ctrl_16,
    &_ar_serdes_sbus_ctrl_20,
    &_ar_serdes_sbus_ctrl_80,
    &_ar_serdes_sbus_ctrl_81,
    &_ar_serdes_sbus_ctrl_82,
    &_ar_serdes_sbus_ctrl_83,
    &_ar_serdes_sbus_ctrl_84,
    &_ar_serdes_sbus_ctrl_85,
    &_ar_serdes_sbus_ctrl_86,
    &_ar_serdes_sbus_ctrl_87,
    &_ar_serdes_sbus_ctrl_88,
    &_ar_serdes_sbus_ctrl_89,
    &_ar_serdes_sbus_ctrl_fe,
    &_ar_serdes_sbus_ctrl_ff,
    NULL
};

#endif
