/******************************************************************************
 * COPYRIGHT CRAY INC. ar_amo_mmrs_h.h
 * FILE: ar_amo_mmrs_h.h
 * Created by v2h.c on Wed Oct  8 14:38:57 2014
 ******************************************************************************/

#ifndef _AR_AMO_MMRS_H_H_
#define _AR_AMO_MMRS_H_H_

#ifdef __GNUC__
#define _unused __attribute__((unused))
#else
#define _unused
#endif

#ifndef _GENERIC_MMRD_T_
#define _GENERIC_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint64_t _mask;		/* Field bit mask */
} generic_mmrd_t;
#endif

#ifndef _ERRCAT_MMRD_T_
#define _ERRCAT_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint32_t _ec;		/* Field error category */
} errcat_mmrd_t;
#endif

#ifndef _GENERIC_MMR_T_
#define _GENERIC_MMR_T_
typedef struct {
	char* _name;		/* MMR name */
	uint64_t _addr;		/* MMR address */
	int _size;		/* Size in bytes of MMR */
	int _depth;		/* Number of MMR instances */
	const generic_mmrd_t *_info;	/* MMR detail */
} generic_mmr_t;
#endif

static const generic_mmr_t* _ar_amo_mmrs[] _unused;	/* AMO Array */

/*
 *  AR AMO MMR DETAIL DECLARATIONS
 */
static const generic_mmrd_t _ar_nic_amo_cfg_cache_inv_detail[] = {
    { "INV", AR_NIC_AMO_CFG_CACHE_INV_INV_BP, AR_NIC_AMO_CFG_CACHE_INV_INV_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_amo_mmr_ring_0_hi_amo_detail[] = {
    { "UNUSED_145_39", AR_NIC_AMO_AMO_MMR_RING_0_HI_AMO_UNUSED_145_39_BP, AR_NIC_AMO_AMO_MMR_RING_0_HI_AMO_UNUSED_145_39_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_amo_mmr_ring_0_mid_amo_detail[] = {
    { "UNUSED_127_114", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_UNUSED_127_114_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_UNUSED_127_114_MASK },
    { "CNTR_TIMEOUT_ARM", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_TIMEOUT_ARM_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_TIMEOUT_ARM_MASK },
    { "CNTR_ERR_REQLIST_MBE", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_ERR_REQLIST_MBE_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_ERR_REQLIST_MBE_MASK },
    { "CNTR_ERR_REQLIST_SBE", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_ERR_REQLIST_SBE_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_ERR_REQLIST_SBE_MASK },
    { "CNTR_DATASTORE_RD_POISON", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_DATASTORE_RD_POISON_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_DATASTORE_RD_POISON_MASK },
    { "CNTR_DATASTORE_WR_POISON", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_DATASTORE_WR_POISON_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_DATASTORE_WR_POISON_MASK },
    { "CNTR_ERR_RSP_SBE", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_ERR_RSP_SBE_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_ERR_RSP_SBE_MASK },
    { "CNTR_ERR_RSP_PARITY", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_ERR_RSP_PARITY_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_ERR_RSP_PARITY_MASK },
    { "CNTR_ERR_REQ_MBE", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_ERR_REQ_MBE_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_ERR_REQ_MBE_MASK },
    { "CNTR_ERR_REQ_SBE", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_ERR_REQ_SBE_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_ERR_REQ_SBE_MASK },
    { "CNTR_ERR_REQ_PARITY", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_ERR_REQ_PARITY_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_ERR_REQ_PARITY_MASK },
    { "CNTR_INVALIDATE", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_INVALIDATE_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_INVALIDATE_MASK },
    { "CNTR_FILL_RSP", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_FILL_RSP_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_FILL_RSP_MASK },
    { "CNTR_STALL_ORDERED", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_STALL_ORDERED_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_STALL_ORDERED_MASK },
    { "CNTR_STALL_FULL", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_STALL_FULL_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_STALL_FULL_MASK },
    { "CNTR_STALL_FLUSH", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_STALL_FLUSH_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_STALL_FLUSH_MASK },
    { "CNTR_STALL_MATCH", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_STALL_MATCH_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_STALL_MATCH_MASK },
    { "CNTR_AMO_MISS", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_AMO_MISS_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_AMO_MISS_MASK },
    { "CNTR_AMO_HIT", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_AMO_HIT_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_AMO_HIT_MASK },
    { "CNTR_AMO_DONE", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_AMO_DONE_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_AMO_DONE_MASK },
    { "CNTR_RSP1_BLOCK", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_RSP1_BLOCK_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_RSP1_BLOCK_MASK },
    { "CNTR_RSP1_FLIT", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_RSP1_FLIT_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_RSP1_FLIT_MASK },
    { "CNTR_RSP1_PKT", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_RSP1_PKT_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_RSP1_PKT_MASK },
    { "CNTR_RSP0_BLOCK", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_RSP0_BLOCK_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_RSP0_BLOCK_MASK },
    { "CNTR_RSP0_FLIT", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_RSP0_FLIT_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_RSP0_FLIT_MASK },
    { "CNTR_RSP0_PKT", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_RSP0_PKT_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_RSP0_PKT_MASK },
    { "CNTR_REQ1_BLOCK", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_REQ1_BLOCK_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_REQ1_BLOCK_MASK },
    { "CNTR_REQ1_STALL", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_REQ1_STALL_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_REQ1_STALL_MASK },
    { "CNTR_REQ1_PKT", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_REQ1_PKT_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_REQ1_PKT_MASK },
    { "CNTR_REQ0_BLOCK", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_REQ0_BLOCK_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_REQ0_BLOCK_MASK },
    { "CNTR_REQ0_STALL", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_REQ0_STALL_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_REQ0_STALL_MASK },
    { "CNTR_REQ0_FLIT", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_REQ0_FLIT_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_REQ0_FLIT_MASK },
    { "CNTR_REQ0_PKT", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_REQ0_PKT_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_CNTR_REQ0_PKT_MASK },
    { "UNUSED_81_64", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_UNUSED_81_64_BP, AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO_UNUSED_81_64_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_amo_mmr_ring_0_lo_amo_detail[] = {
    { "UNUSED_145_39", AR_NIC_AMO_AMO_MMR_RING_0_LO_AMO_UNUSED_145_39_BP, AR_NIC_AMO_AMO_MMR_RING_0_LO_AMO_UNUSED_145_39_MASK },
    { "DBG_REQ_RDY", AR_NIC_AMO_AMO_MMR_RING_0_LO_AMO_DBG_REQ_RDY_BP, AR_NIC_AMO_AMO_MMR_RING_0_LO_AMO_DBG_REQ_RDY_MASK },
    { "DBG_RSP_RDY", AR_NIC_AMO_AMO_MMR_RING_0_LO_AMO_DBG_RSP_RDY_BP, AR_NIC_AMO_AMO_MMR_RING_0_LO_AMO_DBG_RSP_RDY_MASK },
    { "R_Q_AMO_PI_OS_IRQ", AR_NIC_AMO_AMO_MMR_RING_0_LO_AMO_R_Q_AMO_PI_OS_IRQ_BP, AR_NIC_AMO_AMO_MMR_RING_0_LO_AMO_R_Q_AMO_PI_OS_IRQ_MASK },
    { "R_Q_AMO_LB_HSS_IRQ", AR_NIC_AMO_AMO_MMR_RING_0_LO_AMO_R_Q_AMO_LB_HSS_IRQ_BP, AR_NIC_AMO_AMO_MMR_RING_0_LO_AMO_R_Q_AMO_LB_HSS_IRQ_MASK },
    { "R_Q_AMO_RSPMON_RING_WRACK", AR_NIC_AMO_AMO_MMR_RING_0_LO_AMO_R_Q_AMO_RSPMON_RING_WRACK_BP, AR_NIC_AMO_AMO_MMR_RING_0_LO_AMO_R_Q_AMO_RSPMON_RING_WRACK_MASK },
    { "R_Q_AMO_RSPMON_RING_15_0", AR_NIC_AMO_AMO_MMR_RING_0_LO_AMO_R_Q_AMO_RSPMON_RING_15_0_BP, AR_NIC_AMO_AMO_MMR_RING_0_LO_AMO_R_Q_AMO_RSPMON_RING_15_0_MASK },
    { "I_RSPMON_AMO_RING_15_0", AR_NIC_AMO_AMO_MMR_RING_0_LO_AMO_I_RSPMON_AMO_RING_15_0_BP, AR_NIC_AMO_AMO_MMR_RING_0_LO_AMO_I_RSPMON_AMO_RING_15_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_err_flg_1_hi_amo_detail[] = {
    { "UNUSED_145_143", AR_NIC_AMO_ERR_FLG_1_HI_AMO_UNUSED_145_143_BP, AR_NIC_AMO_ERR_FLG_1_HI_AMO_UNUSED_145_143_MASK },
    { "DBG_REQLIST_CNTR", AR_NIC_AMO_ERR_FLG_1_HI_AMO_DBG_REQLIST_CNTR_BP, AR_NIC_AMO_ERR_FLG_1_HI_AMO_DBG_REQLIST_CNTR_MASK },
    { "DBG_LFSR_VAL", AR_NIC_AMO_ERR_FLG_1_HI_AMO_DBG_LFSR_VAL_BP, AR_NIC_AMO_ERR_FLG_1_HI_AMO_DBG_LFSR_VAL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_err_flg_1_mid_amo_detail[] = {
    { "UNUSED_127_91", AR_NIC_AMO_ERR_FLG_1_MID_AMO_UNUSED_127_91_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_UNUSED_127_91_MASK },
    { "TIMEOUT", AR_NIC_AMO_ERR_FLG_1_MID_AMO_TIMEOUT_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_TIMEOUT_MASK },
    { "FP_UNDERFLOW", AR_NIC_AMO_ERR_FLG_1_MID_AMO_FP_UNDERFLOW_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_FP_UNDERFLOW_MASK },
    { "FP_OVERFLOW", AR_NIC_AMO_ERR_FLG_1_MID_AMO_FP_OVERFLOW_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_FP_OVERFLOW_MASK },
    { "FP_INVALID", AR_NIC_AMO_ERR_FLG_1_MID_AMO_FP_INVALID_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_FP_INVALID_MASK },
    { "FP_INEXACT", AR_NIC_AMO_ERR_FLG_1_MID_AMO_FP_INEXACT_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_FP_INEXACT_MASK },
    { "REQLIST_MBE", AR_NIC_AMO_ERR_FLG_1_MID_AMO_REQLIST_MBE_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_REQLIST_MBE_MASK },
    { "REQLIST_SBE", AR_NIC_AMO_ERR_FLG_1_MID_AMO_REQLIST_SBE_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_REQLIST_SBE_MASK },
    { "DATASTORE_WR_POISON", AR_NIC_AMO_ERR_FLG_1_MID_AMO_DATASTORE_WR_POISON_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_DATASTORE_WR_POISON_MASK },
    { "DATASTORE_RD_POISON", AR_NIC_AMO_ERR_FLG_1_MID_AMO_DATASTORE_RD_POISON_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_DATASTORE_RD_POISON_MASK },
    { "RSP_MBE", AR_NIC_AMO_ERR_FLG_1_MID_AMO_RSP_MBE_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_RSP_MBE_MASK },
    { "RSP_SBE", AR_NIC_AMO_ERR_FLG_1_MID_AMO_RSP_SBE_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_RSP_SBE_MASK },
    { "RSP_UNSOLICITED", AR_NIC_AMO_ERR_FLG_1_MID_AMO_RSP_UNSOLICITED_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_RSP_UNSOLICITED_MASK },
    { "RSP_PARITY", AR_NIC_AMO_ERR_FLG_1_MID_AMO_RSP_PARITY_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_RSP_PARITY_MASK },
    { "REQ_MBE", AR_NIC_AMO_ERR_FLG_1_MID_AMO_REQ_MBE_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_REQ_MBE_MASK },
    { "REQ_SBE", AR_NIC_AMO_ERR_FLG_1_MID_AMO_REQ_SBE_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_REQ_SBE_MASK },
    { "REQ_PARITY", AR_NIC_AMO_ERR_FLG_1_MID_AMO_REQ_PARITY_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_REQ_PARITY_MASK },
    { "RSP1_FIFO_UNFLW", AR_NIC_AMO_ERR_FLG_1_MID_AMO_RSP1_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_RSP1_FIFO_UNFLW_MASK },
    { "RSP0_FIFO_UNFLW", AR_NIC_AMO_ERR_FLG_1_MID_AMO_RSP0_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_RSP0_FIFO_UNFLW_MASK },
    { "REQ1_FIFO_UNFLW", AR_NIC_AMO_ERR_FLG_1_MID_AMO_REQ1_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_REQ1_FIFO_UNFLW_MASK },
    { "REQ0_FIFO_UNFLW", AR_NIC_AMO_ERR_FLG_1_MID_AMO_REQ0_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_REQ0_FIFO_UNFLW_MASK },
    { "INPUT_FIFO_UNFLW", AR_NIC_AMO_ERR_FLG_1_MID_AMO_INPUT_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_INPUT_FIFO_UNFLW_MASK },
    { "RSP1_FIFO_OVFLW", AR_NIC_AMO_ERR_FLG_1_MID_AMO_RSP1_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_RSP1_FIFO_OVFLW_MASK },
    { "RSP0_FIFO_OVFLW", AR_NIC_AMO_ERR_FLG_1_MID_AMO_RSP0_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_RSP0_FIFO_OVFLW_MASK },
    { "REQ1_FIFO_OVFLW", AR_NIC_AMO_ERR_FLG_1_MID_AMO_REQ1_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_REQ1_FIFO_OVFLW_MASK },
    { "REQ0_FIFO_OVFLW", AR_NIC_AMO_ERR_FLG_1_MID_AMO_REQ0_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_REQ0_FIFO_OVFLW_MASK },
    { "INPUT_FIFO_OVFLW", AR_NIC_AMO_ERR_FLG_1_MID_AMO_INPUT_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_INPUT_FIFO_OVFLW_MASK },
    { "DIAG_ONLY", AR_NIC_AMO_ERR_FLG_1_MID_AMO_DIAG_ONLY_BP, AR_NIC_AMO_ERR_FLG_1_MID_AMO_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_err_flg_1_lo_amo_detail[] = {
    { "UNUSED_63_27", AR_NIC_AMO_ERR_FLG_1_LO_AMO_UNUSED_63_27_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_UNUSED_63_27_MASK },
    { "I_TIMEOUT", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_TIMEOUT_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_TIMEOUT_MASK },
    { "I_FP_UNDERFLOW", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_FP_UNDERFLOW_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_FP_UNDERFLOW_MASK },
    { "I_FP_OVERFLOW", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_FP_OVERFLOW_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_FP_OVERFLOW_MASK },
    { "I_FP_INVALID", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_FP_INVALID_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_FP_INVALID_MASK },
    { "I_FP_INEXACT", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_FP_INEXACT_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_FP_INEXACT_MASK },
    { "I_REQLIST_MBE", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_REQLIST_MBE_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_REQLIST_MBE_MASK },
    { "I_REQLIST_SBE", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_REQLIST_SBE_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_REQLIST_SBE_MASK },
    { "I_DATASTORE_WR_POISON", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_DATASTORE_WR_POISON_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_DATASTORE_WR_POISON_MASK },
    { "I_DATASTORE_RD_POISON", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_DATASTORE_RD_POISON_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_DATASTORE_RD_POISON_MASK },
    { "I_RSP_MBE", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_RSP_MBE_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_RSP_MBE_MASK },
    { "I_RSP_SBE", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_RSP_SBE_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_RSP_SBE_MASK },
    { "I_RSP_UNSOLICITED", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_RSP_UNSOLICITED_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_RSP_UNSOLICITED_MASK },
    { "I_RSP_PARITY", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_RSP_PARITY_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_RSP_PARITY_MASK },
    { "I_REQ_MBE", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_REQ_MBE_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_REQ_MBE_MASK },
    { "I_REQ_SBE", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_REQ_SBE_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_REQ_SBE_MASK },
    { "I_REQ_PARITY", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_REQ_PARITY_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_REQ_PARITY_MASK },
    { "I_RSP1_FIFO_UNFLW", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_RSP1_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_RSP1_FIFO_UNFLW_MASK },
    { "I_RSP0_FIFO_UNFLW", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_RSP0_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_RSP0_FIFO_UNFLW_MASK },
    { "I_REQ1_FIFO_UNFLW", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_REQ1_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_REQ1_FIFO_UNFLW_MASK },
    { "I_REQ0_FIFO_UNFLW", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_REQ0_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_REQ0_FIFO_UNFLW_MASK },
    { "I_INPUT_FIFO_UNFLW", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_INPUT_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_INPUT_FIFO_UNFLW_MASK },
    { "I_RSP1_FIFO_OVFLW", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_RSP1_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_RSP1_FIFO_OVFLW_MASK },
    { "I_RSP0_FIFO_OVFLW", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_RSP0_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_RSP0_FIFO_OVFLW_MASK },
    { "I_REQ1_FIFO_OVFLW", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_REQ1_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_REQ1_FIFO_OVFLW_MASK },
    { "I_REQ0_FIFO_OVFLW", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_REQ0_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_REQ0_FIFO_OVFLW_MASK },
    { "I_INPUT_FIFO_OVFLW", AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_INPUT_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_I_INPUT_FIFO_OVFLW_MASK },
    { "UNUSED_0", AR_NIC_AMO_ERR_FLG_1_LO_AMO_UNUSED_0_BP, AR_NIC_AMO_ERR_FLG_1_LO_AMO_UNUSED_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_amo_tagstore_active_2_hi_amo_detail[] = {
    { "UNUSED_145_144", AR_NIC_AMO_AMO_TAGSTORE_ACTIVE_2_HI_AMO_UNUSED_145_144_BP, AR_NIC_AMO_AMO_TAGSTORE_ACTIVE_2_HI_AMO_UNUSED_145_144_MASK },
    { "DBG_PARB_CRDTS", AR_NIC_AMO_AMO_TAGSTORE_ACTIVE_2_HI_AMO_DBG_PARB_CRDTS_BP, AR_NIC_AMO_AMO_TAGSTORE_ACTIVE_2_HI_AMO_DBG_PARB_CRDTS_MASK },
    { "DBG_INPUT_CRDTS", AR_NIC_AMO_AMO_TAGSTORE_ACTIVE_2_HI_AMO_DBG_INPUT_CRDTS_BP, AR_NIC_AMO_AMO_TAGSTORE_ACTIVE_2_HI_AMO_DBG_INPUT_CRDTS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_amo_tagstore_active_2_mid_amo_detail[] = {
    { "STS_TAGSTORE_ACTIVE", AR_NIC_AMO_AMO_TAGSTORE_ACTIVE_2_MID_AMO_STS_TAGSTORE_ACTIVE_BP, AR_NIC_AMO_AMO_TAGSTORE_ACTIVE_2_MID_AMO_STS_TAGSTORE_ACTIVE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_amo_tagstore_active_2_lo_amo_detail[] = {
    { "STS_TAGSTORE_VLD", AR_NIC_AMO_AMO_TAGSTORE_ACTIVE_2_LO_AMO_STS_TAGSTORE_VLD_BP, AR_NIC_AMO_AMO_TAGSTORE_ACTIVE_2_LO_AMO_STS_TAGSTORE_VLD_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_amo_tagstore_pending_3_hi_amo_detail[] = {
    { "TIMEOUT_VLD", AR_NIC_AMO_AMO_TAGSTORE_PENDING_3_HI_AMO_TIMEOUT_VLD_BP, AR_NIC_AMO_AMO_TAGSTORE_PENDING_3_HI_AMO_TIMEOUT_VLD_MASK },
    { "TIMEOUT_ARM", AR_NIC_AMO_AMO_TAGSTORE_PENDING_3_HI_AMO_TIMEOUT_ARM_BP, AR_NIC_AMO_AMO_TAGSTORE_PENDING_3_HI_AMO_TIMEOUT_ARM_MASK },
    { "OLDEST_REQID", AR_NIC_AMO_AMO_TAGSTORE_PENDING_3_HI_AMO_OLDEST_REQID_BP, AR_NIC_AMO_AMO_TAGSTORE_PENDING_3_HI_AMO_OLDEST_REQID_MASK },
    { "OLDEST_STALL", AR_NIC_AMO_AMO_TAGSTORE_PENDING_3_HI_AMO_OLDEST_STALL_BP, AR_NIC_AMO_AMO_TAGSTORE_PENDING_3_HI_AMO_OLDEST_STALL_MASK },
    { "UNUSED_136_128", AR_NIC_AMO_AMO_TAGSTORE_PENDING_3_HI_AMO_UNUSED_136_128_BP, AR_NIC_AMO_AMO_TAGSTORE_PENDING_3_HI_AMO_UNUSED_136_128_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_amo_tagstore_pending_3_mid_amo_detail[] = {
    { "STS_TAGSTORE_PENDING", AR_NIC_AMO_AMO_TAGSTORE_PENDING_3_MID_AMO_STS_TAGSTORE_PENDING_BP, AR_NIC_AMO_AMO_TAGSTORE_PENDING_3_MID_AMO_STS_TAGSTORE_PENDING_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_amo_tagstore_pending_3_lo_amo_detail[] = {
    { "STS_TAGSTORE_VLD", AR_NIC_AMO_AMO_TAGSTORE_PENDING_3_LO_AMO_STS_TAGSTORE_VLD_BP, AR_NIC_AMO_AMO_TAGSTORE_PENDING_3_LO_AMO_STS_TAGSTORE_VLD_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_amo_reqlist_rdy_4_hi_amo_detail[] = {
    { "UNUSED_145_144", AR_NIC_AMO_AMO_REQLIST_RDY_4_HI_AMO_UNUSED_145_144_BP, AR_NIC_AMO_AMO_REQLIST_RDY_4_HI_AMO_UNUSED_145_144_MASK },
    { "DBG_REQ_CRDTS", AR_NIC_AMO_AMO_REQLIST_RDY_4_HI_AMO_DBG_REQ_CRDTS_BP, AR_NIC_AMO_AMO_REQLIST_RDY_4_HI_AMO_DBG_REQ_CRDTS_MASK },
    { "DBG_RSP_CRDTS", AR_NIC_AMO_AMO_REQLIST_RDY_4_HI_AMO_DBG_RSP_CRDTS_BP, AR_NIC_AMO_AMO_REQLIST_RDY_4_HI_AMO_DBG_RSP_CRDTS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_amo_reqlist_rdy_4_mid_amo_detail[] = {
    { "STS_REQLIST_VLD", AR_NIC_AMO_AMO_REQLIST_RDY_4_MID_AMO_STS_REQLIST_VLD_BP, AR_NIC_AMO_AMO_REQLIST_RDY_4_MID_AMO_STS_REQLIST_VLD_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_amo_reqlist_rdy_4_lo_amo_detail[] = {
    { "STS_REQLIST_RDY", AR_NIC_AMO_AMO_REQLIST_RDY_4_LO_AMO_STS_REQLIST_RDY_BP, AR_NIC_AMO_AMO_REQLIST_RDY_4_LO_AMO_STS_REQLIST_RDY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_amo_parb_req_flit_5_hi_amo_detail[] = {
    { "R_Q_AMO_PARB_REQ_SB", AR_NIC_AMO_AMO_PARB_REQ_FLIT_5_HI_AMO_R_Q_AMO_PARB_REQ_SB_BP, AR_NIC_AMO_AMO_PARB_REQ_FLIT_5_HI_AMO_R_Q_AMO_PARB_REQ_SB_MASK },
    { "R_Q_AMO_PARB_REQ_FLIT", AR_NIC_AMO_AMO_PARB_REQ_FLIT_5_HI_AMO_R_Q_AMO_PARB_REQ_FLIT_BP, AR_NIC_AMO_AMO_PARB_REQ_FLIT_5_HI_AMO_R_Q_AMO_PARB_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_amo_parb_req_flit_5_mid_amo_detail[] = {
    { "R_Q_AMO_PARB_REQ_FLIT", AR_NIC_AMO_AMO_PARB_REQ_FLIT_5_MID_AMO_R_Q_AMO_PARB_REQ_FLIT_BP, AR_NIC_AMO_AMO_PARB_REQ_FLIT_5_MID_AMO_R_Q_AMO_PARB_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_amo_parb_req_flit_5_lo_amo_detail[] = {
    { "R_Q_AMO_PARB_REQ_FLIT", AR_NIC_AMO_AMO_PARB_REQ_FLIT_5_LO_AMO_R_Q_AMO_PARB_REQ_FLIT_BP, AR_NIC_AMO_AMO_PARB_REQ_FLIT_5_LO_AMO_R_Q_AMO_PARB_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_pi_nic_rsp_flit_6_hi_amo_detail[] = {
    { "I_PI_NIC_RSP_SB", AR_NIC_AMO_PI_NIC_RSP_FLIT_6_HI_AMO_I_PI_NIC_RSP_SB_BP, AR_NIC_AMO_PI_NIC_RSP_FLIT_6_HI_AMO_I_PI_NIC_RSP_SB_MASK },
    { "I_PI_NIC_RSP_FLIT", AR_NIC_AMO_PI_NIC_RSP_FLIT_6_HI_AMO_I_PI_NIC_RSP_FLIT_BP, AR_NIC_AMO_PI_NIC_RSP_FLIT_6_HI_AMO_I_PI_NIC_RSP_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_pi_nic_rsp_flit_6_mid_amo_detail[] = {
    { "I_PI_NIC_RSP_FLIT", AR_NIC_AMO_PI_NIC_RSP_FLIT_6_MID_AMO_I_PI_NIC_RSP_FLIT_BP, AR_NIC_AMO_PI_NIC_RSP_FLIT_6_MID_AMO_I_PI_NIC_RSP_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_pi_nic_rsp_flit_6_lo_amo_detail[] = {
    { "I_PI_NIC_RSP_FLIT", AR_NIC_AMO_PI_NIC_RSP_FLIT_6_LO_AMO_I_PI_NIC_RSP_FLIT_BP, AR_NIC_AMO_PI_NIC_RSP_FLIT_6_LO_AMO_I_PI_NIC_RSP_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_amo_acp_out_7_hi_amo_detail[] = {
    { "VLD", AR_NIC_AMO_AMO_ACP_OUT_7_HI_AMO_VLD_BP, AR_NIC_AMO_AMO_ACP_OUT_7_HI_AMO_VLD_MASK },
    { "DONE_WRITEBACK", AR_NIC_AMO_AMO_ACP_OUT_7_HI_AMO_DONE_WRITEBACK_BP, AR_NIC_AMO_AMO_ACP_OUT_7_HI_AMO_DONE_WRITEBACK_MASK },
    { "WRITEBACK", AR_NIC_AMO_AMO_ACP_OUT_7_HI_AMO_WRITEBACK_BP, AR_NIC_AMO_AMO_ACP_OUT_7_HI_AMO_WRITEBACK_MASK },
    { "RESPONSE", AR_NIC_AMO_AMO_ACP_OUT_7_HI_AMO_RESPONSE_BP, AR_NIC_AMO_AMO_ACP_OUT_7_HI_AMO_RESPONSE_MASK },
    { "DIRTY", AR_NIC_AMO_AMO_ACP_OUT_7_HI_AMO_DIRTY_BP, AR_NIC_AMO_AMO_ACP_OUT_7_HI_AMO_DIRTY_MASK },
    { "FETCHING", AR_NIC_AMO_AMO_ACP_OUT_7_HI_AMO_FETCHING_BP, AR_NIC_AMO_AMO_ACP_OUT_7_HI_AMO_FETCHING_MASK },
    { "W", AR_NIC_AMO_AMO_ACP_OUT_7_HI_AMO_W_BP, AR_NIC_AMO_AMO_ACP_OUT_7_HI_AMO_W_MASK },
    { "IDX", AR_NIC_AMO_AMO_ACP_OUT_7_HI_AMO_IDX_BP, AR_NIC_AMO_AMO_ACP_OUT_7_HI_AMO_IDX_MASK },
    { "REQID", AR_NIC_AMO_AMO_ACP_OUT_7_HI_AMO_REQID_BP, AR_NIC_AMO_AMO_ACP_OUT_7_HI_AMO_REQID_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_amo_acp_out_7_mid_amo_detail[] = {
    { "REQID", AR_NIC_AMO_AMO_ACP_OUT_7_MID_AMO_REQID_BP, AR_NIC_AMO_AMO_ACP_OUT_7_MID_AMO_REQID_MASK },
    { "PI_HINTS", AR_NIC_AMO_AMO_ACP_OUT_7_MID_AMO_PI_HINTS_BP, AR_NIC_AMO_AMO_ACP_OUT_7_MID_AMO_PI_HINTS_MASK },
    { "PI_ID", AR_NIC_AMO_AMO_ACP_OUT_7_MID_AMO_PI_ID_BP, AR_NIC_AMO_AMO_ACP_OUT_7_MID_AMO_PI_ID_MASK },
    { "POISON", AR_NIC_AMO_AMO_ACP_OUT_7_MID_AMO_POISON_BP, AR_NIC_AMO_AMO_ACP_OUT_7_MID_AMO_POISON_MASK },
    { "ADDR_47_2", AR_NIC_AMO_AMO_ACP_OUT_7_MID_AMO_ADDR_47_2_BP, AR_NIC_AMO_AMO_ACP_OUT_7_MID_AMO_ADDR_47_2_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_amo_acp_out_7_lo_amo_detail[] = {
    { "RESULT", AR_NIC_AMO_AMO_ACP_OUT_7_LO_AMO_RESULT_BP, AR_NIC_AMO_AMO_ACP_OUT_7_LO_AMO_RESULT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_amo_power_down_ff_hi_amo_detail[] = {
    { "POWER_DOWN", AR_NIC_AMO_AMO_POWER_DOWN_FF_HI_AMO_POWER_DOWN_BP, AR_NIC_AMO_AMO_POWER_DOWN_FF_HI_AMO_POWER_DOWN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_amo_power_down_ff_mid_amo_detail[] = {
    { "POWER_DOWN", AR_NIC_AMO_AMO_POWER_DOWN_FF_MID_AMO_POWER_DOWN_BP, AR_NIC_AMO_AMO_POWER_DOWN_FF_MID_AMO_POWER_DOWN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_amo_power_down_ff_lo_amo_detail[] = {
    { "POWER_DOWN", AR_NIC_AMO_AMO_POWER_DOWN_FF_LO_AMO_POWER_DOWN_BP, AR_NIC_AMO_AMO_POWER_DOWN_FF_LO_AMO_POWER_DOWN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_cfg_rounding_mode_detail[] = {
    { "ROUNDING_MODE", AR_NIC_AMO_CFG_ROUNDING_MODE_ROUNDING_MODE_BP, AR_NIC_AMO_CFG_ROUNDING_MODE_ROUNDING_MODE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_cfg_params_detail[] = {
    { "TIMEOUT_THRESHOLD", AR_NIC_AMO_CFG_PARAMS_TIMEOUT_THRESHOLD_BP, AR_NIC_AMO_CFG_PARAMS_TIMEOUT_THRESHOLD_MASK },
    { "TIMEOUT_EN", AR_NIC_AMO_CFG_PARAMS_TIMEOUT_EN_BP, AR_NIC_AMO_CFG_PARAMS_TIMEOUT_EN_MASK },
    { "CLEAR_RO", AR_NIC_AMO_CFG_PARAMS_CLEAR_RO_BP, AR_NIC_AMO_CFG_PARAMS_CLEAR_RO_MASK },
    { "IGNORE_DIRTY", AR_NIC_AMO_CFG_PARAMS_IGNORE_DIRTY_BP, AR_NIC_AMO_CFG_PARAMS_IGNORE_DIRTY_MASK },
    { "ORDERED_WAIT", AR_NIC_AMO_CFG_PARAMS_ORDERED_WAIT_BP, AR_NIC_AMO_CFG_PARAMS_ORDERED_WAIT_MASK },
    { "FORCE_CA_VAL", AR_NIC_AMO_CFG_PARAMS_FORCE_CA_VAL_BP, AR_NIC_AMO_CFG_PARAMS_FORCE_CA_VAL_MASK },
    { "FORCE_CA_EN", AR_NIC_AMO_CFG_PARAMS_FORCE_CA_EN_BP, AR_NIC_AMO_CFG_PARAMS_FORCE_CA_EN_MASK },
    { "REQLIST_MAX", AR_NIC_AMO_CFG_PARAMS_REQLIST_MAX_BP, AR_NIC_AMO_CFG_PARAMS_REQLIST_MAX_MASK },
    { "SF_RSP", AR_NIC_AMO_CFG_PARAMS_SF_RSP_BP, AR_NIC_AMO_CFG_PARAMS_SF_RSP_MASK },
    { "SF_REQ", AR_NIC_AMO_CFG_PARAMS_SF_REQ_BP, AR_NIC_AMO_CFG_PARAMS_SF_REQ_MASK },
    { "SF_INPUT", AR_NIC_AMO_CFG_PARAMS_SF_INPUT_BP, AR_NIC_AMO_CFG_PARAMS_SF_INPUT_MASK },
    { "LFSR_EN", AR_NIC_AMO_CFG_PARAMS_LFSR_EN_BP, AR_NIC_AMO_CFG_PARAMS_LFSR_EN_MASK },
    { "LFSR_SEED", AR_NIC_AMO_CFG_PARAMS_LFSR_SEED_BP, AR_NIC_AMO_CFG_PARAMS_LFSR_SEED_MASK },
    { "LFSR_THRESHOLD", AR_NIC_AMO_CFG_PARAMS_LFSR_THRESHOLD_BP, AR_NIC_AMO_CFG_PARAMS_LFSR_THRESHOLD_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_cfg_crdts_detail[] = {
    { "RSP_ARBITRATION", AR_NIC_AMO_CFG_CRDTS_RSP_ARBITRATION_BP, AR_NIC_AMO_CFG_CRDTS_RSP_ARBITRATION_MASK },
    { "MAX_PKT_SIZE", AR_NIC_AMO_CFG_CRDTS_MAX_PKT_SIZE_BP, AR_NIC_AMO_CFG_CRDTS_MAX_PKT_SIZE_MASK },
    { "REQ_CRDTS_MAX", AR_NIC_AMO_CFG_CRDTS_REQ_CRDTS_MAX_BP, AR_NIC_AMO_CFG_CRDTS_REQ_CRDTS_MAX_MASK },
    { "RSP_CRDTS_MAX", AR_NIC_AMO_CFG_CRDTS_RSP_CRDTS_MAX_BP, AR_NIC_AMO_CFG_CRDTS_RSP_CRDTS_MAX_MASK },
    { "PARB_CRDTS_MAX", AR_NIC_AMO_CFG_CRDTS_PARB_CRDTS_MAX_BP, AR_NIC_AMO_CFG_CRDTS_PARB_CRDTS_MAX_MASK },
    { "INPUT_CRDTS_MAX", AR_NIC_AMO_CFG_CRDTS_INPUT_CRDTS_MAX_BP, AR_NIC_AMO_CFG_CRDTS_INPUT_CRDTS_MAX_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_cfg_offld_detail[] = {
    { "CACHEABLE", AR_NIC_AMO_CFG_OFFLD_CACHEABLE_BP, AR_NIC_AMO_CFG_OFFLD_CACHEABLE_MASK },
    { "UNCACHEABLE", AR_NIC_AMO_CFG_OFFLD_UNCACHEABLE_BP, AR_NIC_AMO_CFG_OFFLD_UNCACHEABLE_MASK },
    { "WORD64", AR_NIC_AMO_CFG_OFFLD_WORD64_BP, AR_NIC_AMO_CFG_OFFLD_WORD64_MASK },
    { "WORD32", AR_NIC_AMO_CFG_OFFLD_WORD32_BP, AR_NIC_AMO_CFG_OFFLD_WORD32_MASK },
    { "FETCH", AR_NIC_AMO_CFG_OFFLD_FETCH_BP, AR_NIC_AMO_CFG_OFFLD_FETCH_MASK },
    { "NONFETCH", AR_NIC_AMO_CFG_OFFLD_NONFETCH_BP, AR_NIC_AMO_CFG_OFFLD_NONFETCH_MASK },
    { "OP_OFFLOAD", AR_NIC_AMO_CFG_OFFLD_OP_OFFLOAD_BP, AR_NIC_AMO_CFG_OFFLD_OP_OFFLOAD_MASK },
    { "OP_FLUSH", AR_NIC_AMO_CFG_OFFLD_OP_FLUSH_BP, AR_NIC_AMO_CFG_OFFLD_OP_FLUSH_MASK },
    { "OP_DISABLE", AR_NIC_AMO_CFG_OFFLD_OP_DISABLE_BP, AR_NIC_AMO_CFG_OFFLD_OP_DISABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_err_flg_detail[] = {
    { "TIMEOUT", AR_NIC_AMO_ERR_FLG_TIMEOUT_BP, AR_NIC_AMO_ERR_FLG_TIMEOUT_MASK },
    { "FP_UNDERFLOW", AR_NIC_AMO_ERR_FLG_FP_UNDERFLOW_BP, AR_NIC_AMO_ERR_FLG_FP_UNDERFLOW_MASK },
    { "FP_OVERFLOW", AR_NIC_AMO_ERR_FLG_FP_OVERFLOW_BP, AR_NIC_AMO_ERR_FLG_FP_OVERFLOW_MASK },
    { "FP_INVALID", AR_NIC_AMO_ERR_FLG_FP_INVALID_BP, AR_NIC_AMO_ERR_FLG_FP_INVALID_MASK },
    { "FP_INEXACT", AR_NIC_AMO_ERR_FLG_FP_INEXACT_BP, AR_NIC_AMO_ERR_FLG_FP_INEXACT_MASK },
    { "REQLIST_MBE", AR_NIC_AMO_ERR_FLG_REQLIST_MBE_BP, AR_NIC_AMO_ERR_FLG_REQLIST_MBE_MASK },
    { "REQLIST_SBE", AR_NIC_AMO_ERR_FLG_REQLIST_SBE_BP, AR_NIC_AMO_ERR_FLG_REQLIST_SBE_MASK },
    { "DATASTORE_WR_POISON", AR_NIC_AMO_ERR_FLG_DATASTORE_WR_POISON_BP, AR_NIC_AMO_ERR_FLG_DATASTORE_WR_POISON_MASK },
    { "DATASTORE_RD_POISON", AR_NIC_AMO_ERR_FLG_DATASTORE_RD_POISON_BP, AR_NIC_AMO_ERR_FLG_DATASTORE_RD_POISON_MASK },
    { "RSP_MBE", AR_NIC_AMO_ERR_FLG_RSP_MBE_BP, AR_NIC_AMO_ERR_FLG_RSP_MBE_MASK },
    { "RSP_SBE", AR_NIC_AMO_ERR_FLG_RSP_SBE_BP, AR_NIC_AMO_ERR_FLG_RSP_SBE_MASK },
    { "RSP_UNSOLICITED", AR_NIC_AMO_ERR_FLG_RSP_UNSOLICITED_BP, AR_NIC_AMO_ERR_FLG_RSP_UNSOLICITED_MASK },
    { "RSP_PARITY", AR_NIC_AMO_ERR_FLG_RSP_PARITY_BP, AR_NIC_AMO_ERR_FLG_RSP_PARITY_MASK },
    { "REQ_MBE", AR_NIC_AMO_ERR_FLG_REQ_MBE_BP, AR_NIC_AMO_ERR_FLG_REQ_MBE_MASK },
    { "REQ_SBE", AR_NIC_AMO_ERR_FLG_REQ_SBE_BP, AR_NIC_AMO_ERR_FLG_REQ_SBE_MASK },
    { "REQ_PARITY", AR_NIC_AMO_ERR_FLG_REQ_PARITY_BP, AR_NIC_AMO_ERR_FLG_REQ_PARITY_MASK },
    { "RSP1_FIFO_UNFLW", AR_NIC_AMO_ERR_FLG_RSP1_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FLG_RSP1_FIFO_UNFLW_MASK },
    { "RSP0_FIFO_UNFLW", AR_NIC_AMO_ERR_FLG_RSP0_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FLG_RSP0_FIFO_UNFLW_MASK },
    { "REQ1_FIFO_UNFLW", AR_NIC_AMO_ERR_FLG_REQ1_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FLG_REQ1_FIFO_UNFLW_MASK },
    { "REQ0_FIFO_UNFLW", AR_NIC_AMO_ERR_FLG_REQ0_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FLG_REQ0_FIFO_UNFLW_MASK },
    { "INPUT_FIFO_UNFLW", AR_NIC_AMO_ERR_FLG_INPUT_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FLG_INPUT_FIFO_UNFLW_MASK },
    { "RSP1_FIFO_OVFLW", AR_NIC_AMO_ERR_FLG_RSP1_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FLG_RSP1_FIFO_OVFLW_MASK },
    { "RSP0_FIFO_OVFLW", AR_NIC_AMO_ERR_FLG_RSP0_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FLG_RSP0_FIFO_OVFLW_MASK },
    { "REQ1_FIFO_OVFLW", AR_NIC_AMO_ERR_FLG_REQ1_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FLG_REQ1_FIFO_OVFLW_MASK },
    { "REQ0_FIFO_OVFLW", AR_NIC_AMO_ERR_FLG_REQ0_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FLG_REQ0_FIFO_OVFLW_MASK },
    { "INPUT_FIFO_OVFLW", AR_NIC_AMO_ERR_FLG_INPUT_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FLG_INPUT_FIFO_OVFLW_MASK },
    { "DIAG_ONLY", AR_NIC_AMO_ERR_FLG_DIAG_ONLY_BP, AR_NIC_AMO_ERR_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
#ifdef EXCEPTIONS_DEFS
static const errcat_mmrd_t _ar_nic_amo_err_flg_errcat[] = {
    { "TIMEOUT", AR_NIC_AMO_ERR_FLG_TIMEOUT_BP, AR_NIC_AMO_ERR_FLG_TIMEOUT_EC },
    { "FP_UNDERFLOW", AR_NIC_AMO_ERR_FLG_FP_UNDERFLOW_BP, AR_NIC_AMO_ERR_FLG_FP_UNDERFLOW_EC },
    { "FP_OVERFLOW", AR_NIC_AMO_ERR_FLG_FP_OVERFLOW_BP, AR_NIC_AMO_ERR_FLG_FP_OVERFLOW_EC },
    { "FP_INVALID", AR_NIC_AMO_ERR_FLG_FP_INVALID_BP, AR_NIC_AMO_ERR_FLG_FP_INVALID_EC },
    { "FP_INEXACT", AR_NIC_AMO_ERR_FLG_FP_INEXACT_BP, AR_NIC_AMO_ERR_FLG_FP_INEXACT_EC },
    { "REQLIST_MBE", AR_NIC_AMO_ERR_FLG_REQLIST_MBE_BP, AR_NIC_AMO_ERR_FLG_REQLIST_MBE_EC },
    { "REQLIST_SBE", AR_NIC_AMO_ERR_FLG_REQLIST_SBE_BP, AR_NIC_AMO_ERR_FLG_REQLIST_SBE_EC },
    { "DATASTORE_WR_POISON", AR_NIC_AMO_ERR_FLG_DATASTORE_WR_POISON_BP, AR_NIC_AMO_ERR_FLG_DATASTORE_WR_POISON_EC },
    { "DATASTORE_RD_POISON", AR_NIC_AMO_ERR_FLG_DATASTORE_RD_POISON_BP, AR_NIC_AMO_ERR_FLG_DATASTORE_RD_POISON_EC },
    { "RSP_MBE", AR_NIC_AMO_ERR_FLG_RSP_MBE_BP, AR_NIC_AMO_ERR_FLG_RSP_MBE_EC },
    { "RSP_SBE", AR_NIC_AMO_ERR_FLG_RSP_SBE_BP, AR_NIC_AMO_ERR_FLG_RSP_SBE_EC },
    { "RSP_UNSOLICITED", AR_NIC_AMO_ERR_FLG_RSP_UNSOLICITED_BP, AR_NIC_AMO_ERR_FLG_RSP_UNSOLICITED_EC },
    { "RSP_PARITY", AR_NIC_AMO_ERR_FLG_RSP_PARITY_BP, AR_NIC_AMO_ERR_FLG_RSP_PARITY_EC },
    { "REQ_MBE", AR_NIC_AMO_ERR_FLG_REQ_MBE_BP, AR_NIC_AMO_ERR_FLG_REQ_MBE_EC },
    { "REQ_SBE", AR_NIC_AMO_ERR_FLG_REQ_SBE_BP, AR_NIC_AMO_ERR_FLG_REQ_SBE_EC },
    { "REQ_PARITY", AR_NIC_AMO_ERR_FLG_REQ_PARITY_BP, AR_NIC_AMO_ERR_FLG_REQ_PARITY_EC },
    { "RSP1_FIFO_UNFLW", AR_NIC_AMO_ERR_FLG_RSP1_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FLG_RSP1_FIFO_UNFLW_EC },
    { "RSP0_FIFO_UNFLW", AR_NIC_AMO_ERR_FLG_RSP0_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FLG_RSP0_FIFO_UNFLW_EC },
    { "REQ1_FIFO_UNFLW", AR_NIC_AMO_ERR_FLG_REQ1_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FLG_REQ1_FIFO_UNFLW_EC },
    { "REQ0_FIFO_UNFLW", AR_NIC_AMO_ERR_FLG_REQ0_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FLG_REQ0_FIFO_UNFLW_EC },
    { "INPUT_FIFO_UNFLW", AR_NIC_AMO_ERR_FLG_INPUT_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FLG_INPUT_FIFO_UNFLW_EC },
    { "RSP1_FIFO_OVFLW", AR_NIC_AMO_ERR_FLG_RSP1_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FLG_RSP1_FIFO_OVFLW_EC },
    { "RSP0_FIFO_OVFLW", AR_NIC_AMO_ERR_FLG_RSP0_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FLG_RSP0_FIFO_OVFLW_EC },
    { "REQ1_FIFO_OVFLW", AR_NIC_AMO_ERR_FLG_REQ1_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FLG_REQ1_FIFO_OVFLW_EC },
    { "REQ0_FIFO_OVFLW", AR_NIC_AMO_ERR_FLG_REQ0_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FLG_REQ0_FIFO_OVFLW_EC },
    { "INPUT_FIFO_OVFLW", AR_NIC_AMO_ERR_FLG_INPUT_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FLG_INPUT_FIFO_OVFLW_EC },
    { "DIAG_ONLY", AR_NIC_AMO_ERR_FLG_DIAG_ONLY_BP, AR_NIC_AMO_ERR_FLG_DIAG_ONLY_EC },
    { NULL, 0, 0 }
};
#endif
static const generic_mmrd_t _ar_nic_amo_err_clr_detail[] = {
    { "TIMEOUT", AR_NIC_AMO_ERR_CLR_TIMEOUT_BP, AR_NIC_AMO_ERR_CLR_TIMEOUT_MASK },
    { "FP_UNDERFLOW", AR_NIC_AMO_ERR_CLR_FP_UNDERFLOW_BP, AR_NIC_AMO_ERR_CLR_FP_UNDERFLOW_MASK },
    { "FP_OVERFLOW", AR_NIC_AMO_ERR_CLR_FP_OVERFLOW_BP, AR_NIC_AMO_ERR_CLR_FP_OVERFLOW_MASK },
    { "FP_INVALID", AR_NIC_AMO_ERR_CLR_FP_INVALID_BP, AR_NIC_AMO_ERR_CLR_FP_INVALID_MASK },
    { "FP_INEXACT", AR_NIC_AMO_ERR_CLR_FP_INEXACT_BP, AR_NIC_AMO_ERR_CLR_FP_INEXACT_MASK },
    { "REQLIST_MBE", AR_NIC_AMO_ERR_CLR_REQLIST_MBE_BP, AR_NIC_AMO_ERR_CLR_REQLIST_MBE_MASK },
    { "REQLIST_SBE", AR_NIC_AMO_ERR_CLR_REQLIST_SBE_BP, AR_NIC_AMO_ERR_CLR_REQLIST_SBE_MASK },
    { "DATASTORE_WR_POISON", AR_NIC_AMO_ERR_CLR_DATASTORE_WR_POISON_BP, AR_NIC_AMO_ERR_CLR_DATASTORE_WR_POISON_MASK },
    { "DATASTORE_RD_POISON", AR_NIC_AMO_ERR_CLR_DATASTORE_RD_POISON_BP, AR_NIC_AMO_ERR_CLR_DATASTORE_RD_POISON_MASK },
    { "RSP_MBE", AR_NIC_AMO_ERR_CLR_RSP_MBE_BP, AR_NIC_AMO_ERR_CLR_RSP_MBE_MASK },
    { "RSP_SBE", AR_NIC_AMO_ERR_CLR_RSP_SBE_BP, AR_NIC_AMO_ERR_CLR_RSP_SBE_MASK },
    { "RSP_UNSOLICITED", AR_NIC_AMO_ERR_CLR_RSP_UNSOLICITED_BP, AR_NIC_AMO_ERR_CLR_RSP_UNSOLICITED_MASK },
    { "RSP_PARITY", AR_NIC_AMO_ERR_CLR_RSP_PARITY_BP, AR_NIC_AMO_ERR_CLR_RSP_PARITY_MASK },
    { "REQ_MBE", AR_NIC_AMO_ERR_CLR_REQ_MBE_BP, AR_NIC_AMO_ERR_CLR_REQ_MBE_MASK },
    { "REQ_SBE", AR_NIC_AMO_ERR_CLR_REQ_SBE_BP, AR_NIC_AMO_ERR_CLR_REQ_SBE_MASK },
    { "REQ_PARITY", AR_NIC_AMO_ERR_CLR_REQ_PARITY_BP, AR_NIC_AMO_ERR_CLR_REQ_PARITY_MASK },
    { "RSP1_FIFO_UNFLW", AR_NIC_AMO_ERR_CLR_RSP1_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_CLR_RSP1_FIFO_UNFLW_MASK },
    { "RSP0_FIFO_UNFLW", AR_NIC_AMO_ERR_CLR_RSP0_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_CLR_RSP0_FIFO_UNFLW_MASK },
    { "REQ1_FIFO_UNFLW", AR_NIC_AMO_ERR_CLR_REQ1_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_CLR_REQ1_FIFO_UNFLW_MASK },
    { "REQ0_FIFO_UNFLW", AR_NIC_AMO_ERR_CLR_REQ0_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_CLR_REQ0_FIFO_UNFLW_MASK },
    { "INPUT_FIFO_UNFLW", AR_NIC_AMO_ERR_CLR_INPUT_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_CLR_INPUT_FIFO_UNFLW_MASK },
    { "RSP1_FIFO_OVFLW", AR_NIC_AMO_ERR_CLR_RSP1_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_CLR_RSP1_FIFO_OVFLW_MASK },
    { "RSP0_FIFO_OVFLW", AR_NIC_AMO_ERR_CLR_RSP0_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_CLR_RSP0_FIFO_OVFLW_MASK },
    { "REQ1_FIFO_OVFLW", AR_NIC_AMO_ERR_CLR_REQ1_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_CLR_REQ1_FIFO_OVFLW_MASK },
    { "REQ0_FIFO_OVFLW", AR_NIC_AMO_ERR_CLR_REQ0_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_CLR_REQ0_FIFO_OVFLW_MASK },
    { "INPUT_FIFO_OVFLW", AR_NIC_AMO_ERR_CLR_INPUT_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_CLR_INPUT_FIFO_OVFLW_MASK },
    { "DIAG_ONLY", AR_NIC_AMO_ERR_CLR_DIAG_ONLY_BP, AR_NIC_AMO_ERR_CLR_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_err_hss_msk_detail[] = {
    { "TIMEOUT", AR_NIC_AMO_ERR_HSS_MSK_TIMEOUT_BP, AR_NIC_AMO_ERR_HSS_MSK_TIMEOUT_MASK },
    { "FP_UNDERFLOW", AR_NIC_AMO_ERR_HSS_MSK_FP_UNDERFLOW_BP, AR_NIC_AMO_ERR_HSS_MSK_FP_UNDERFLOW_MASK },
    { "FP_OVERFLOW", AR_NIC_AMO_ERR_HSS_MSK_FP_OVERFLOW_BP, AR_NIC_AMO_ERR_HSS_MSK_FP_OVERFLOW_MASK },
    { "FP_INVALID", AR_NIC_AMO_ERR_HSS_MSK_FP_INVALID_BP, AR_NIC_AMO_ERR_HSS_MSK_FP_INVALID_MASK },
    { "FP_INEXACT", AR_NIC_AMO_ERR_HSS_MSK_FP_INEXACT_BP, AR_NIC_AMO_ERR_HSS_MSK_FP_INEXACT_MASK },
    { "REQLIST_MBE", AR_NIC_AMO_ERR_HSS_MSK_REQLIST_MBE_BP, AR_NIC_AMO_ERR_HSS_MSK_REQLIST_MBE_MASK },
    { "REQLIST_SBE", AR_NIC_AMO_ERR_HSS_MSK_REQLIST_SBE_BP, AR_NIC_AMO_ERR_HSS_MSK_REQLIST_SBE_MASK },
    { "DATASTORE_WR_POISON", AR_NIC_AMO_ERR_HSS_MSK_DATASTORE_WR_POISON_BP, AR_NIC_AMO_ERR_HSS_MSK_DATASTORE_WR_POISON_MASK },
    { "DATASTORE_RD_POISON", AR_NIC_AMO_ERR_HSS_MSK_DATASTORE_RD_POISON_BP, AR_NIC_AMO_ERR_HSS_MSK_DATASTORE_RD_POISON_MASK },
    { "RSP_MBE", AR_NIC_AMO_ERR_HSS_MSK_RSP_MBE_BP, AR_NIC_AMO_ERR_HSS_MSK_RSP_MBE_MASK },
    { "RSP_SBE", AR_NIC_AMO_ERR_HSS_MSK_RSP_SBE_BP, AR_NIC_AMO_ERR_HSS_MSK_RSP_SBE_MASK },
    { "RSP_UNSOLICITED", AR_NIC_AMO_ERR_HSS_MSK_RSP_UNSOLICITED_BP, AR_NIC_AMO_ERR_HSS_MSK_RSP_UNSOLICITED_MASK },
    { "RSP_PARITY", AR_NIC_AMO_ERR_HSS_MSK_RSP_PARITY_BP, AR_NIC_AMO_ERR_HSS_MSK_RSP_PARITY_MASK },
    { "REQ_MBE", AR_NIC_AMO_ERR_HSS_MSK_REQ_MBE_BP, AR_NIC_AMO_ERR_HSS_MSK_REQ_MBE_MASK },
    { "REQ_SBE", AR_NIC_AMO_ERR_HSS_MSK_REQ_SBE_BP, AR_NIC_AMO_ERR_HSS_MSK_REQ_SBE_MASK },
    { "REQ_PARITY", AR_NIC_AMO_ERR_HSS_MSK_REQ_PARITY_BP, AR_NIC_AMO_ERR_HSS_MSK_REQ_PARITY_MASK },
    { "RSP1_FIFO_UNFLW", AR_NIC_AMO_ERR_HSS_MSK_RSP1_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_HSS_MSK_RSP1_FIFO_UNFLW_MASK },
    { "RSP0_FIFO_UNFLW", AR_NIC_AMO_ERR_HSS_MSK_RSP0_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_HSS_MSK_RSP0_FIFO_UNFLW_MASK },
    { "REQ1_FIFO_UNFLW", AR_NIC_AMO_ERR_HSS_MSK_REQ1_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_HSS_MSK_REQ1_FIFO_UNFLW_MASK },
    { "REQ0_FIFO_UNFLW", AR_NIC_AMO_ERR_HSS_MSK_REQ0_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_HSS_MSK_REQ0_FIFO_UNFLW_MASK },
    { "INPUT_FIFO_UNFLW", AR_NIC_AMO_ERR_HSS_MSK_INPUT_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_HSS_MSK_INPUT_FIFO_UNFLW_MASK },
    { "RSP1_FIFO_OVFLW", AR_NIC_AMO_ERR_HSS_MSK_RSP1_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_HSS_MSK_RSP1_FIFO_OVFLW_MASK },
    { "RSP0_FIFO_OVFLW", AR_NIC_AMO_ERR_HSS_MSK_RSP0_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_HSS_MSK_RSP0_FIFO_OVFLW_MASK },
    { "REQ1_FIFO_OVFLW", AR_NIC_AMO_ERR_HSS_MSK_REQ1_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_HSS_MSK_REQ1_FIFO_OVFLW_MASK },
    { "REQ0_FIFO_OVFLW", AR_NIC_AMO_ERR_HSS_MSK_REQ0_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_HSS_MSK_REQ0_FIFO_OVFLW_MASK },
    { "INPUT_FIFO_OVFLW", AR_NIC_AMO_ERR_HSS_MSK_INPUT_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_HSS_MSK_INPUT_FIFO_OVFLW_MASK },
    { "DIAG_ONLY", AR_NIC_AMO_ERR_HSS_MSK_DIAG_ONLY_BP, AR_NIC_AMO_ERR_HSS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_err_os_msk_detail[] = {
    { "TIMEOUT", AR_NIC_AMO_ERR_OS_MSK_TIMEOUT_BP, AR_NIC_AMO_ERR_OS_MSK_TIMEOUT_MASK },
    { "FP_UNDERFLOW", AR_NIC_AMO_ERR_OS_MSK_FP_UNDERFLOW_BP, AR_NIC_AMO_ERR_OS_MSK_FP_UNDERFLOW_MASK },
    { "FP_OVERFLOW", AR_NIC_AMO_ERR_OS_MSK_FP_OVERFLOW_BP, AR_NIC_AMO_ERR_OS_MSK_FP_OVERFLOW_MASK },
    { "FP_INVALID", AR_NIC_AMO_ERR_OS_MSK_FP_INVALID_BP, AR_NIC_AMO_ERR_OS_MSK_FP_INVALID_MASK },
    { "FP_INEXACT", AR_NIC_AMO_ERR_OS_MSK_FP_INEXACT_BP, AR_NIC_AMO_ERR_OS_MSK_FP_INEXACT_MASK },
    { "REQLIST_MBE", AR_NIC_AMO_ERR_OS_MSK_REQLIST_MBE_BP, AR_NIC_AMO_ERR_OS_MSK_REQLIST_MBE_MASK },
    { "REQLIST_SBE", AR_NIC_AMO_ERR_OS_MSK_REQLIST_SBE_BP, AR_NIC_AMO_ERR_OS_MSK_REQLIST_SBE_MASK },
    { "DATASTORE_WR_POISON", AR_NIC_AMO_ERR_OS_MSK_DATASTORE_WR_POISON_BP, AR_NIC_AMO_ERR_OS_MSK_DATASTORE_WR_POISON_MASK },
    { "DATASTORE_RD_POISON", AR_NIC_AMO_ERR_OS_MSK_DATASTORE_RD_POISON_BP, AR_NIC_AMO_ERR_OS_MSK_DATASTORE_RD_POISON_MASK },
    { "RSP_MBE", AR_NIC_AMO_ERR_OS_MSK_RSP_MBE_BP, AR_NIC_AMO_ERR_OS_MSK_RSP_MBE_MASK },
    { "RSP_SBE", AR_NIC_AMO_ERR_OS_MSK_RSP_SBE_BP, AR_NIC_AMO_ERR_OS_MSK_RSP_SBE_MASK },
    { "RSP_UNSOLICITED", AR_NIC_AMO_ERR_OS_MSK_RSP_UNSOLICITED_BP, AR_NIC_AMO_ERR_OS_MSK_RSP_UNSOLICITED_MASK },
    { "RSP_PARITY", AR_NIC_AMO_ERR_OS_MSK_RSP_PARITY_BP, AR_NIC_AMO_ERR_OS_MSK_RSP_PARITY_MASK },
    { "REQ_MBE", AR_NIC_AMO_ERR_OS_MSK_REQ_MBE_BP, AR_NIC_AMO_ERR_OS_MSK_REQ_MBE_MASK },
    { "REQ_SBE", AR_NIC_AMO_ERR_OS_MSK_REQ_SBE_BP, AR_NIC_AMO_ERR_OS_MSK_REQ_SBE_MASK },
    { "REQ_PARITY", AR_NIC_AMO_ERR_OS_MSK_REQ_PARITY_BP, AR_NIC_AMO_ERR_OS_MSK_REQ_PARITY_MASK },
    { "RSP1_FIFO_UNFLW", AR_NIC_AMO_ERR_OS_MSK_RSP1_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_OS_MSK_RSP1_FIFO_UNFLW_MASK },
    { "RSP0_FIFO_UNFLW", AR_NIC_AMO_ERR_OS_MSK_RSP0_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_OS_MSK_RSP0_FIFO_UNFLW_MASK },
    { "REQ1_FIFO_UNFLW", AR_NIC_AMO_ERR_OS_MSK_REQ1_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_OS_MSK_REQ1_FIFO_UNFLW_MASK },
    { "REQ0_FIFO_UNFLW", AR_NIC_AMO_ERR_OS_MSK_REQ0_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_OS_MSK_REQ0_FIFO_UNFLW_MASK },
    { "INPUT_FIFO_UNFLW", AR_NIC_AMO_ERR_OS_MSK_INPUT_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_OS_MSK_INPUT_FIFO_UNFLW_MASK },
    { "RSP1_FIFO_OVFLW", AR_NIC_AMO_ERR_OS_MSK_RSP1_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_OS_MSK_RSP1_FIFO_OVFLW_MASK },
    { "RSP0_FIFO_OVFLW", AR_NIC_AMO_ERR_OS_MSK_RSP0_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_OS_MSK_RSP0_FIFO_OVFLW_MASK },
    { "REQ1_FIFO_OVFLW", AR_NIC_AMO_ERR_OS_MSK_REQ1_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_OS_MSK_REQ1_FIFO_OVFLW_MASK },
    { "REQ0_FIFO_OVFLW", AR_NIC_AMO_ERR_OS_MSK_REQ0_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_OS_MSK_REQ0_FIFO_OVFLW_MASK },
    { "INPUT_FIFO_OVFLW", AR_NIC_AMO_ERR_OS_MSK_INPUT_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_OS_MSK_INPUT_FIFO_OVFLW_MASK },
    { "DIAG_ONLY", AR_NIC_AMO_ERR_OS_MSK_DIAG_ONLY_BP, AR_NIC_AMO_ERR_OS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_err_first_flg_detail[] = {
    { "TIMEOUT", AR_NIC_AMO_ERR_FIRST_FLG_TIMEOUT_BP, AR_NIC_AMO_ERR_FIRST_FLG_TIMEOUT_MASK },
    { "FP_UNDERFLOW", AR_NIC_AMO_ERR_FIRST_FLG_FP_UNDERFLOW_BP, AR_NIC_AMO_ERR_FIRST_FLG_FP_UNDERFLOW_MASK },
    { "FP_OVERFLOW", AR_NIC_AMO_ERR_FIRST_FLG_FP_OVERFLOW_BP, AR_NIC_AMO_ERR_FIRST_FLG_FP_OVERFLOW_MASK },
    { "FP_INVALID", AR_NIC_AMO_ERR_FIRST_FLG_FP_INVALID_BP, AR_NIC_AMO_ERR_FIRST_FLG_FP_INVALID_MASK },
    { "FP_INEXACT", AR_NIC_AMO_ERR_FIRST_FLG_FP_INEXACT_BP, AR_NIC_AMO_ERR_FIRST_FLG_FP_INEXACT_MASK },
    { "REQLIST_MBE", AR_NIC_AMO_ERR_FIRST_FLG_REQLIST_MBE_BP, AR_NIC_AMO_ERR_FIRST_FLG_REQLIST_MBE_MASK },
    { "REQLIST_SBE", AR_NIC_AMO_ERR_FIRST_FLG_REQLIST_SBE_BP, AR_NIC_AMO_ERR_FIRST_FLG_REQLIST_SBE_MASK },
    { "DATASTORE_WR_POISON", AR_NIC_AMO_ERR_FIRST_FLG_DATASTORE_WR_POISON_BP, AR_NIC_AMO_ERR_FIRST_FLG_DATASTORE_WR_POISON_MASK },
    { "DATASTORE_RD_POISON", AR_NIC_AMO_ERR_FIRST_FLG_DATASTORE_RD_POISON_BP, AR_NIC_AMO_ERR_FIRST_FLG_DATASTORE_RD_POISON_MASK },
    { "RSP_MBE", AR_NIC_AMO_ERR_FIRST_FLG_RSP_MBE_BP, AR_NIC_AMO_ERR_FIRST_FLG_RSP_MBE_MASK },
    { "RSP_SBE", AR_NIC_AMO_ERR_FIRST_FLG_RSP_SBE_BP, AR_NIC_AMO_ERR_FIRST_FLG_RSP_SBE_MASK },
    { "RSP_UNSOLICITED", AR_NIC_AMO_ERR_FIRST_FLG_RSP_UNSOLICITED_BP, AR_NIC_AMO_ERR_FIRST_FLG_RSP_UNSOLICITED_MASK },
    { "RSP_PARITY", AR_NIC_AMO_ERR_FIRST_FLG_RSP_PARITY_BP, AR_NIC_AMO_ERR_FIRST_FLG_RSP_PARITY_MASK },
    { "REQ_MBE", AR_NIC_AMO_ERR_FIRST_FLG_REQ_MBE_BP, AR_NIC_AMO_ERR_FIRST_FLG_REQ_MBE_MASK },
    { "REQ_SBE", AR_NIC_AMO_ERR_FIRST_FLG_REQ_SBE_BP, AR_NIC_AMO_ERR_FIRST_FLG_REQ_SBE_MASK },
    { "REQ_PARITY", AR_NIC_AMO_ERR_FIRST_FLG_REQ_PARITY_BP, AR_NIC_AMO_ERR_FIRST_FLG_REQ_PARITY_MASK },
    { "RSP1_FIFO_UNFLW", AR_NIC_AMO_ERR_FIRST_FLG_RSP1_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FIRST_FLG_RSP1_FIFO_UNFLW_MASK },
    { "RSP0_FIFO_UNFLW", AR_NIC_AMO_ERR_FIRST_FLG_RSP0_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FIRST_FLG_RSP0_FIFO_UNFLW_MASK },
    { "REQ1_FIFO_UNFLW", AR_NIC_AMO_ERR_FIRST_FLG_REQ1_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FIRST_FLG_REQ1_FIFO_UNFLW_MASK },
    { "REQ0_FIFO_UNFLW", AR_NIC_AMO_ERR_FIRST_FLG_REQ0_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FIRST_FLG_REQ0_FIFO_UNFLW_MASK },
    { "INPUT_FIFO_UNFLW", AR_NIC_AMO_ERR_FIRST_FLG_INPUT_FIFO_UNFLW_BP, AR_NIC_AMO_ERR_FIRST_FLG_INPUT_FIFO_UNFLW_MASK },
    { "RSP1_FIFO_OVFLW", AR_NIC_AMO_ERR_FIRST_FLG_RSP1_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FIRST_FLG_RSP1_FIFO_OVFLW_MASK },
    { "RSP0_FIFO_OVFLW", AR_NIC_AMO_ERR_FIRST_FLG_RSP0_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FIRST_FLG_RSP0_FIFO_OVFLW_MASK },
    { "REQ1_FIFO_OVFLW", AR_NIC_AMO_ERR_FIRST_FLG_REQ1_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FIRST_FLG_REQ1_FIFO_OVFLW_MASK },
    { "REQ0_FIFO_OVFLW", AR_NIC_AMO_ERR_FIRST_FLG_REQ0_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FIRST_FLG_REQ0_FIFO_OVFLW_MASK },
    { "INPUT_FIFO_OVFLW", AR_NIC_AMO_ERR_FIRST_FLG_INPUT_FIFO_OVFLW_BP, AR_NIC_AMO_ERR_FIRST_FLG_INPUT_FIFO_OVFLW_MASK },
    { "DIAG_ONLY", AR_NIC_AMO_ERR_FIRST_FLG_DIAG_ONLY_BP, AR_NIC_AMO_ERR_FIRST_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_err_info_reqlist_ram_detail[] = {
    { "MBE_ADDRESS", AR_NIC_AMO_ERR_INFO_REQLIST_RAM_MBE_ADDRESS_BP, AR_NIC_AMO_ERR_INFO_REQLIST_RAM_MBE_ADDRESS_MASK },
    { "MBE_SYNDROME", AR_NIC_AMO_ERR_INFO_REQLIST_RAM_MBE_SYNDROME_BP, AR_NIC_AMO_ERR_INFO_REQLIST_RAM_MBE_SYNDROME_MASK },
    { "SBE_ADDRESS", AR_NIC_AMO_ERR_INFO_REQLIST_RAM_SBE_ADDRESS_BP, AR_NIC_AMO_ERR_INFO_REQLIST_RAM_SBE_ADDRESS_MASK },
    { "SBE_SYNDROME", AR_NIC_AMO_ERR_INFO_REQLIST_RAM_SBE_SYNDROME_BP, AR_NIC_AMO_ERR_INFO_REQLIST_RAM_SBE_SYNDROME_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_err_info_fp_inexact_detail[] = {
    { "WORD_SIZE", AR_NIC_AMO_ERR_INFO_FP_INEXACT_WORD_SIZE_BP, AR_NIC_AMO_ERR_INFO_FP_INEXACT_WORD_SIZE_MASK },
    { "TC", AR_NIC_AMO_ERR_INFO_FP_INEXACT_TC_BP, AR_NIC_AMO_ERR_INFO_FP_INEXACT_TC_MASK },
    { "ADDR_47_2", AR_NIC_AMO_ERR_INFO_FP_INEXACT_ADDR_47_2_BP, AR_NIC_AMO_ERR_INFO_FP_INEXACT_ADDR_47_2_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_err_info_fp_invalid_detail[] = {
    { "WORD_SIZE", AR_NIC_AMO_ERR_INFO_FP_INVALID_WORD_SIZE_BP, AR_NIC_AMO_ERR_INFO_FP_INVALID_WORD_SIZE_MASK },
    { "TC", AR_NIC_AMO_ERR_INFO_FP_INVALID_TC_BP, AR_NIC_AMO_ERR_INFO_FP_INVALID_TC_MASK },
    { "ADDR_47_2", AR_NIC_AMO_ERR_INFO_FP_INVALID_ADDR_47_2_BP, AR_NIC_AMO_ERR_INFO_FP_INVALID_ADDR_47_2_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_err_info_fp_overflow_detail[] = {
    { "WORD_SIZE", AR_NIC_AMO_ERR_INFO_FP_OVERFLOW_WORD_SIZE_BP, AR_NIC_AMO_ERR_INFO_FP_OVERFLOW_WORD_SIZE_MASK },
    { "TC", AR_NIC_AMO_ERR_INFO_FP_OVERFLOW_TC_BP, AR_NIC_AMO_ERR_INFO_FP_OVERFLOW_TC_MASK },
    { "ADDR_47_2", AR_NIC_AMO_ERR_INFO_FP_OVERFLOW_ADDR_47_2_BP, AR_NIC_AMO_ERR_INFO_FP_OVERFLOW_ADDR_47_2_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_err_info_fp_underflow_detail[] = {
    { "WORD_SIZE", AR_NIC_AMO_ERR_INFO_FP_UNDERFLOW_WORD_SIZE_BP, AR_NIC_AMO_ERR_INFO_FP_UNDERFLOW_WORD_SIZE_MASK },
    { "TC", AR_NIC_AMO_ERR_INFO_FP_UNDERFLOW_TC_BP, AR_NIC_AMO_ERR_INFO_FP_UNDERFLOW_TC_MASK },
    { "ADDR_47_2", AR_NIC_AMO_ERR_INFO_FP_UNDERFLOW_ADDR_47_2_BP, AR_NIC_AMO_ERR_INFO_FP_UNDERFLOW_ADDR_47_2_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_err_info_req_bus_detail[] = {
    { "SYNDROME1_MBE", AR_NIC_AMO_ERR_INFO_REQ_BUS_SYNDROME1_MBE_BP, AR_NIC_AMO_ERR_INFO_REQ_BUS_SYNDROME1_MBE_MASK },
    { "SYNDROME0_MBE", AR_NIC_AMO_ERR_INFO_REQ_BUS_SYNDROME0_MBE_BP, AR_NIC_AMO_ERR_INFO_REQ_BUS_SYNDROME0_MBE_MASK },
    { "SYNDROME1_SBE", AR_NIC_AMO_ERR_INFO_REQ_BUS_SYNDROME1_SBE_BP, AR_NIC_AMO_ERR_INFO_REQ_BUS_SYNDROME1_SBE_MASK },
    { "SYNDROME0_SBE", AR_NIC_AMO_ERR_INFO_REQ_BUS_SYNDROME0_SBE_BP, AR_NIC_AMO_ERR_INFO_REQ_BUS_SYNDROME0_SBE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_err_info_rsp_bus_detail[] = {
    { "SYNDROME_MBE", AR_NIC_AMO_ERR_INFO_RSP_BUS_SYNDROME_MBE_BP, AR_NIC_AMO_ERR_INFO_RSP_BUS_SYNDROME_MBE_MASK },
    { "SYNDROME_SBE", AR_NIC_AMO_ERR_INFO_RSP_BUS_SYNDROME_SBE_BP, AR_NIC_AMO_ERR_INFO_RSP_BUS_SYNDROME_SBE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_dbg_state_detail[] = {
    { "CACHE_PEND", AR_NIC_AMO_DBG_STATE_CACHE_PEND_BP, AR_NIC_AMO_DBG_STATE_CACHE_PEND_MASK },
    { "CACHE_VLD", AR_NIC_AMO_DBG_STATE_CACHE_VLD_BP, AR_NIC_AMO_DBG_STATE_CACHE_VLD_MASK },
    { "LFSR_VAL", AR_NIC_AMO_DBG_STATE_LFSR_VAL_BP, AR_NIC_AMO_DBG_STATE_LFSR_VAL_MASK },
    { "REQLIST_CNTR", AR_NIC_AMO_DBG_STATE_REQLIST_CNTR_BP, AR_NIC_AMO_DBG_STATE_REQLIST_CNTR_MASK },
    { "RSP1_RDY", AR_NIC_AMO_DBG_STATE_RSP1_RDY_BP, AR_NIC_AMO_DBG_STATE_RSP1_RDY_MASK },
    { "RSP0_RDY", AR_NIC_AMO_DBG_STATE_RSP0_RDY_BP, AR_NIC_AMO_DBG_STATE_RSP0_RDY_MASK },
    { "REQ1_RDY", AR_NIC_AMO_DBG_STATE_REQ1_RDY_BP, AR_NIC_AMO_DBG_STATE_REQ1_RDY_MASK },
    { "REQ0_RDY", AR_NIC_AMO_DBG_STATE_REQ0_RDY_BP, AR_NIC_AMO_DBG_STATE_REQ0_RDY_MASK },
    { "REQ_CRDTS", AR_NIC_AMO_DBG_STATE_REQ_CRDTS_BP, AR_NIC_AMO_DBG_STATE_REQ_CRDTS_MASK },
    { "RSP_CRDTS", AR_NIC_AMO_DBG_STATE_RSP_CRDTS_BP, AR_NIC_AMO_DBG_STATE_RSP_CRDTS_MASK },
    { "PARB_CRDTS", AR_NIC_AMO_DBG_STATE_PARB_CRDTS_BP, AR_NIC_AMO_DBG_STATE_PARB_CRDTS_MASK },
    { "INPUT_CRDTS", AR_NIC_AMO_DBG_STATE_INPUT_CRDTS_BP, AR_NIC_AMO_DBG_STATE_INPUT_CRDTS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_dbg_errinj_reqlist_detail[] = {
    { "ADDRESS", AR_NIC_AMO_DBG_ERRINJ_REQLIST_ADDRESS_BP, AR_NIC_AMO_DBG_ERRINJ_REQLIST_ADDRESS_MASK },
    { "CHECKBYTE", AR_NIC_AMO_DBG_ERRINJ_REQLIST_CHECKBYTE_BP, AR_NIC_AMO_DBG_ERRINJ_REQLIST_CHECKBYTE_MASK },
    { "TRIGGERED", AR_NIC_AMO_DBG_ERRINJ_REQLIST_TRIGGERED_BP, AR_NIC_AMO_DBG_ERRINJ_REQLIST_TRIGGERED_MASK },
    { "MODE", AR_NIC_AMO_DBG_ERRINJ_REQLIST_MODE_BP, AR_NIC_AMO_DBG_ERRINJ_REQLIST_MODE_MASK },
    { "ENABLE", AR_NIC_AMO_DBG_ERRINJ_REQLIST_ENABLE_BP, AR_NIC_AMO_DBG_ERRINJ_REQLIST_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_dbg_errinj_datastore_detail[] = {
    { "ADDRESS", AR_NIC_AMO_DBG_ERRINJ_DATASTORE_ADDRESS_BP, AR_NIC_AMO_DBG_ERRINJ_DATASTORE_ADDRESS_MASK },
    { "TRIGGERED", AR_NIC_AMO_DBG_ERRINJ_DATASTORE_TRIGGERED_BP, AR_NIC_AMO_DBG_ERRINJ_DATASTORE_TRIGGERED_MASK },
    { "MODE", AR_NIC_AMO_DBG_ERRINJ_DATASTORE_MODE_BP, AR_NIC_AMO_DBG_ERRINJ_DATASTORE_MODE_MASK },
    { "ENABLE", AR_NIC_AMO_DBG_ERRINJ_DATASTORE_ENABLE_BP, AR_NIC_AMO_DBG_ERRINJ_DATASTORE_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_dbg_errinj_req_bus_detail[] = {
    { "PARITY", AR_NIC_AMO_DBG_ERRINJ_REQ_BUS_PARITY_BP, AR_NIC_AMO_DBG_ERRINJ_REQ_BUS_PARITY_MASK },
    { "ECC1", AR_NIC_AMO_DBG_ERRINJ_REQ_BUS_ECC1_BP, AR_NIC_AMO_DBG_ERRINJ_REQ_BUS_ECC1_MASK },
    { "ECC0", AR_NIC_AMO_DBG_ERRINJ_REQ_BUS_ECC0_BP, AR_NIC_AMO_DBG_ERRINJ_REQ_BUS_ECC0_MASK },
    { "TRIGGERED", AR_NIC_AMO_DBG_ERRINJ_REQ_BUS_TRIGGERED_BP, AR_NIC_AMO_DBG_ERRINJ_REQ_BUS_TRIGGERED_MASK },
    { "TAIL", AR_NIC_AMO_DBG_ERRINJ_REQ_BUS_TAIL_BP, AR_NIC_AMO_DBG_ERRINJ_REQ_BUS_TAIL_MASK },
    { "COUNT", AR_NIC_AMO_DBG_ERRINJ_REQ_BUS_COUNT_BP, AR_NIC_AMO_DBG_ERRINJ_REQ_BUS_COUNT_MASK },
    { "MODE", AR_NIC_AMO_DBG_ERRINJ_REQ_BUS_MODE_BP, AR_NIC_AMO_DBG_ERRINJ_REQ_BUS_MODE_MASK },
    { "EN", AR_NIC_AMO_DBG_ERRINJ_REQ_BUS_EN_BP, AR_NIC_AMO_DBG_ERRINJ_REQ_BUS_EN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_dbg_errinj_rsp_bus_detail[] = {
    { "PKT_ERR", AR_NIC_AMO_DBG_ERRINJ_RSP_BUS_PKT_ERR_BP, AR_NIC_AMO_DBG_ERRINJ_RSP_BUS_PKT_ERR_MASK },
    { "ECC0", AR_NIC_AMO_DBG_ERRINJ_RSP_BUS_ECC0_BP, AR_NIC_AMO_DBG_ERRINJ_RSP_BUS_ECC0_MASK },
    { "PARITY", AR_NIC_AMO_DBG_ERRINJ_RSP_BUS_PARITY_BP, AR_NIC_AMO_DBG_ERRINJ_RSP_BUS_PARITY_MASK },
    { "TRIGGERED", AR_NIC_AMO_DBG_ERRINJ_RSP_BUS_TRIGGERED_BP, AR_NIC_AMO_DBG_ERRINJ_RSP_BUS_TRIGGERED_MASK },
    { "MODE", AR_NIC_AMO_DBG_ERRINJ_RSP_BUS_MODE_BP, AR_NIC_AMO_DBG_ERRINJ_RSP_BUS_MODE_MASK },
    { "EN", AR_NIC_AMO_DBG_ERRINJ_RSP_BUS_EN_BP, AR_NIC_AMO_DBG_ERRINJ_RSP_BUS_EN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_prf_en_detail[] = {
    { "PRF_ORDERED_EN", AR_NIC_AMO_PRF_EN_PRF_ORDERED_EN_BP, AR_NIC_AMO_PRF_EN_PRF_ORDERED_EN_MASK },
    { "PRF_FULL_EN", AR_NIC_AMO_PRF_EN_PRF_FULL_EN_BP, AR_NIC_AMO_PRF_EN_PRF_FULL_EN_MASK },
    { "PRF_FLUSH_EN", AR_NIC_AMO_PRF_EN_PRF_FLUSH_EN_BP, AR_NIC_AMO_PRF_EN_PRF_FLUSH_EN_MASK },
    { "PRF_MATCH_EN", AR_NIC_AMO_PRF_EN_PRF_MATCH_EN_BP, AR_NIC_AMO_PRF_EN_PRF_MATCH_EN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_prf_stall_duration_match_detail[] = {
    { "MAX", AR_NIC_AMO_PRF_STALL_DURATION_MATCH_MAX_BP, AR_NIC_AMO_PRF_STALL_DURATION_MATCH_MAX_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_prf_stall_duration_flush_detail[] = {
    { "MAX", AR_NIC_AMO_PRF_STALL_DURATION_FLUSH_MAX_BP, AR_NIC_AMO_PRF_STALL_DURATION_FLUSH_MAX_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_prf_stall_duration_full_detail[] = {
    { "MAX", AR_NIC_AMO_PRF_STALL_DURATION_FULL_MAX_BP, AR_NIC_AMO_PRF_STALL_DURATION_FULL_MAX_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_amo_prf_stall_duration_ordered_detail[] = {
    { "MAX", AR_NIC_AMO_PRF_STALL_DURATION_ORDERED_MAX_BP, AR_NIC_AMO_PRF_STALL_DURATION_ORDERED_MAX_MASK },
    { NULL, 0, 0 }
};

/*
 *  AR AMO MMR DECLARATIONS
 */
static const generic_mmr_t _ar_nic_amo_cfg_cache_inv = {
    "AR_NIC_AMO_CFG_CACHE_INV", AR_NIC_AMO_CFG_CACHE_INV, 8, 1, _ar_nic_amo_cfg_cache_inv_detail
};
static const generic_mmr_t _ar_nic_amo_amo_mmr_ring_0_hi_amo = {
    "AR_NIC_AMO_AMO_MMR_RING_0_HI_AMO", AR_NIC_AMO_AMO_MMR_RING_0_HI_AMO, 8, 1, _ar_nic_amo_amo_mmr_ring_0_hi_amo_detail
};
static const generic_mmr_t _ar_nic_amo_amo_mmr_ring_0_mid_amo = {
    "AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO", AR_NIC_AMO_AMO_MMR_RING_0_MID_AMO, 8, 1, _ar_nic_amo_amo_mmr_ring_0_mid_amo_detail
};
static const generic_mmr_t _ar_nic_amo_amo_mmr_ring_0_lo_amo = {
    "AR_NIC_AMO_AMO_MMR_RING_0_LO_AMO", AR_NIC_AMO_AMO_MMR_RING_0_LO_AMO, 8, 1, _ar_nic_amo_amo_mmr_ring_0_lo_amo_detail
};
static const generic_mmr_t _ar_nic_amo_err_flg_1_hi_amo = {
    "AR_NIC_AMO_ERR_FLG_1_HI_AMO", AR_NIC_AMO_ERR_FLG_1_HI_AMO, 8, 1, _ar_nic_amo_err_flg_1_hi_amo_detail
};
static const generic_mmr_t _ar_nic_amo_err_flg_1_mid_amo = {
    "AR_NIC_AMO_ERR_FLG_1_MID_AMO", AR_NIC_AMO_ERR_FLG_1_MID_AMO, 8, 1, _ar_nic_amo_err_flg_1_mid_amo_detail
};
static const generic_mmr_t _ar_nic_amo_err_flg_1_lo_amo = {
    "AR_NIC_AMO_ERR_FLG_1_LO_AMO", AR_NIC_AMO_ERR_FLG_1_LO_AMO, 8, 1, _ar_nic_amo_err_flg_1_lo_amo_detail
};
static const generic_mmr_t _ar_nic_amo_amo_tagstore_active_2_hi_amo = {
    "AR_NIC_AMO_AMO_TAGSTORE_ACTIVE_2_HI_AMO", AR_NIC_AMO_AMO_TAGSTORE_ACTIVE_2_HI_AMO, 8, 1, _ar_nic_amo_amo_tagstore_active_2_hi_amo_detail
};
static const generic_mmr_t _ar_nic_amo_amo_tagstore_active_2_mid_amo = {
    "AR_NIC_AMO_AMO_TAGSTORE_ACTIVE_2_MID_AMO", AR_NIC_AMO_AMO_TAGSTORE_ACTIVE_2_MID_AMO, 8, 1, _ar_nic_amo_amo_tagstore_active_2_mid_amo_detail
};
static const generic_mmr_t _ar_nic_amo_amo_tagstore_active_2_lo_amo = {
    "AR_NIC_AMO_AMO_TAGSTORE_ACTIVE_2_LO_AMO", AR_NIC_AMO_AMO_TAGSTORE_ACTIVE_2_LO_AMO, 8, 1, _ar_nic_amo_amo_tagstore_active_2_lo_amo_detail
};
static const generic_mmr_t _ar_nic_amo_amo_tagstore_pending_3_hi_amo = {
    "AR_NIC_AMO_AMO_TAGSTORE_PENDING_3_HI_AMO", AR_NIC_AMO_AMO_TAGSTORE_PENDING_3_HI_AMO, 8, 1, _ar_nic_amo_amo_tagstore_pending_3_hi_amo_detail
};
static const generic_mmr_t _ar_nic_amo_amo_tagstore_pending_3_mid_amo = {
    "AR_NIC_AMO_AMO_TAGSTORE_PENDING_3_MID_AMO", AR_NIC_AMO_AMO_TAGSTORE_PENDING_3_MID_AMO, 8, 1, _ar_nic_amo_amo_tagstore_pending_3_mid_amo_detail
};
static const generic_mmr_t _ar_nic_amo_amo_tagstore_pending_3_lo_amo = {
    "AR_NIC_AMO_AMO_TAGSTORE_PENDING_3_LO_AMO", AR_NIC_AMO_AMO_TAGSTORE_PENDING_3_LO_AMO, 8, 1, _ar_nic_amo_amo_tagstore_pending_3_lo_amo_detail
};
static const generic_mmr_t _ar_nic_amo_amo_reqlist_rdy_4_hi_amo = {
    "AR_NIC_AMO_AMO_REQLIST_RDY_4_HI_AMO", AR_NIC_AMO_AMO_REQLIST_RDY_4_HI_AMO, 8, 1, _ar_nic_amo_amo_reqlist_rdy_4_hi_amo_detail
};
static const generic_mmr_t _ar_nic_amo_amo_reqlist_rdy_4_mid_amo = {
    "AR_NIC_AMO_AMO_REQLIST_RDY_4_MID_AMO", AR_NIC_AMO_AMO_REQLIST_RDY_4_MID_AMO, 8, 1, _ar_nic_amo_amo_reqlist_rdy_4_mid_amo_detail
};
static const generic_mmr_t _ar_nic_amo_amo_reqlist_rdy_4_lo_amo = {
    "AR_NIC_AMO_AMO_REQLIST_RDY_4_LO_AMO", AR_NIC_AMO_AMO_REQLIST_RDY_4_LO_AMO, 8, 1, _ar_nic_amo_amo_reqlist_rdy_4_lo_amo_detail
};
static const generic_mmr_t _ar_nic_amo_amo_parb_req_flit_5_hi_amo = {
    "AR_NIC_AMO_AMO_PARB_REQ_FLIT_5_HI_AMO", AR_NIC_AMO_AMO_PARB_REQ_FLIT_5_HI_AMO, 8, 1, _ar_nic_amo_amo_parb_req_flit_5_hi_amo_detail
};
static const generic_mmr_t _ar_nic_amo_amo_parb_req_flit_5_mid_amo = {
    "AR_NIC_AMO_AMO_PARB_REQ_FLIT_5_MID_AMO", AR_NIC_AMO_AMO_PARB_REQ_FLIT_5_MID_AMO, 8, 1, _ar_nic_amo_amo_parb_req_flit_5_mid_amo_detail
};
static const generic_mmr_t _ar_nic_amo_amo_parb_req_flit_5_lo_amo = {
    "AR_NIC_AMO_AMO_PARB_REQ_FLIT_5_LO_AMO", AR_NIC_AMO_AMO_PARB_REQ_FLIT_5_LO_AMO, 8, 1, _ar_nic_amo_amo_parb_req_flit_5_lo_amo_detail
};
static const generic_mmr_t _ar_nic_amo_pi_nic_rsp_flit_6_hi_amo = {
    "AR_NIC_AMO_PI_NIC_RSP_FLIT_6_HI_AMO", AR_NIC_AMO_PI_NIC_RSP_FLIT_6_HI_AMO, 8, 1, _ar_nic_amo_pi_nic_rsp_flit_6_hi_amo_detail
};
static const generic_mmr_t _ar_nic_amo_pi_nic_rsp_flit_6_mid_amo = {
    "AR_NIC_AMO_PI_NIC_RSP_FLIT_6_MID_AMO", AR_NIC_AMO_PI_NIC_RSP_FLIT_6_MID_AMO, 8, 1, _ar_nic_amo_pi_nic_rsp_flit_6_mid_amo_detail
};
static const generic_mmr_t _ar_nic_amo_pi_nic_rsp_flit_6_lo_amo = {
    "AR_NIC_AMO_PI_NIC_RSP_FLIT_6_LO_AMO", AR_NIC_AMO_PI_NIC_RSP_FLIT_6_LO_AMO, 8, 1, _ar_nic_amo_pi_nic_rsp_flit_6_lo_amo_detail
};
static const generic_mmr_t _ar_nic_amo_amo_acp_out_7_hi_amo = {
    "AR_NIC_AMO_AMO_ACP_OUT_7_HI_AMO", AR_NIC_AMO_AMO_ACP_OUT_7_HI_AMO, 8, 1, _ar_nic_amo_amo_acp_out_7_hi_amo_detail
};
static const generic_mmr_t _ar_nic_amo_amo_acp_out_7_mid_amo = {
    "AR_NIC_AMO_AMO_ACP_OUT_7_MID_AMO", AR_NIC_AMO_AMO_ACP_OUT_7_MID_AMO, 8, 1, _ar_nic_amo_amo_acp_out_7_mid_amo_detail
};
static const generic_mmr_t _ar_nic_amo_amo_acp_out_7_lo_amo = {
    "AR_NIC_AMO_AMO_ACP_OUT_7_LO_AMO", AR_NIC_AMO_AMO_ACP_OUT_7_LO_AMO, 8, 1, _ar_nic_amo_amo_acp_out_7_lo_amo_detail
};
static const generic_mmr_t _ar_nic_amo_amo_power_down_ff_hi_amo = {
    "AR_NIC_AMO_AMO_POWER_DOWN_FF_HI_AMO", AR_NIC_AMO_AMO_POWER_DOWN_FF_HI_AMO, 8, 1, _ar_nic_amo_amo_power_down_ff_hi_amo_detail
};
static const generic_mmr_t _ar_nic_amo_amo_power_down_ff_mid_amo = {
    "AR_NIC_AMO_AMO_POWER_DOWN_FF_MID_AMO", AR_NIC_AMO_AMO_POWER_DOWN_FF_MID_AMO, 8, 1, _ar_nic_amo_amo_power_down_ff_mid_amo_detail
};
static const generic_mmr_t _ar_nic_amo_amo_power_down_ff_lo_amo = {
    "AR_NIC_AMO_AMO_POWER_DOWN_FF_LO_AMO", AR_NIC_AMO_AMO_POWER_DOWN_FF_LO_AMO, 8, 1, _ar_nic_amo_amo_power_down_ff_lo_amo_detail
};
static const generic_mmr_t _ar_nic_amo_cfg_rounding_mode = {
    "AR_NIC_AMO_CFG_ROUNDING_MODE", AR_NIC_AMO_CFG_ROUNDING_MODE, 8, 1, _ar_nic_amo_cfg_rounding_mode_detail
};
static const generic_mmr_t _ar_nic_amo_cfg_params = {
    "AR_NIC_AMO_CFG_PARAMS", AR_NIC_AMO_CFG_PARAMS, 8, 1, _ar_nic_amo_cfg_params_detail
};
static const generic_mmr_t _ar_nic_amo_cfg_crdts = {
    "AR_NIC_AMO_CFG_CRDTS", AR_NIC_AMO_CFG_CRDTS, 8, 1, _ar_nic_amo_cfg_crdts_detail
};
static const generic_mmr_t _ar_nic_amo_cfg_offld = {
    "AR_NIC_AMO_CFG_OFFLD", AR_NIC_AMO_CFG_OFFLD, 8, 1, _ar_nic_amo_cfg_offld_detail
};
static const generic_mmr_t _ar_nic_amo_err_flg = {
    "AR_NIC_AMO_ERR_FLG", AR_NIC_AMO_ERR_FLG, 8, 1, _ar_nic_amo_err_flg_detail
};
static const generic_mmr_t _ar_nic_amo_err_clr = {
    "AR_NIC_AMO_ERR_CLR", AR_NIC_AMO_ERR_CLR, 8, 1, _ar_nic_amo_err_clr_detail
};
static const generic_mmr_t _ar_nic_amo_err_hss_msk = {
    "AR_NIC_AMO_ERR_HSS_MSK", AR_NIC_AMO_ERR_HSS_MSK, 8, 1, _ar_nic_amo_err_hss_msk_detail
};
static const generic_mmr_t _ar_nic_amo_err_os_msk = {
    "AR_NIC_AMO_ERR_OS_MSK", AR_NIC_AMO_ERR_OS_MSK, 8, 1, _ar_nic_amo_err_os_msk_detail
};
static const generic_mmr_t _ar_nic_amo_err_first_flg = {
    "AR_NIC_AMO_ERR_FIRST_FLG", AR_NIC_AMO_ERR_FIRST_FLG, 8, 1, _ar_nic_amo_err_first_flg_detail
};
static const generic_mmr_t _ar_nic_amo_err_info_reqlist_ram = {
    "AR_NIC_AMO_ERR_INFO_REQLIST_RAM", AR_NIC_AMO_ERR_INFO_REQLIST_RAM, 8, 1, _ar_nic_amo_err_info_reqlist_ram_detail
};
static const generic_mmr_t _ar_nic_amo_err_info_fp_inexact = {
    "AR_NIC_AMO_ERR_INFO_FP_INEXACT", AR_NIC_AMO_ERR_INFO_FP_INEXACT, 8, 1, _ar_nic_amo_err_info_fp_inexact_detail
};
static const generic_mmr_t _ar_nic_amo_err_info_fp_invalid = {
    "AR_NIC_AMO_ERR_INFO_FP_INVALID", AR_NIC_AMO_ERR_INFO_FP_INVALID, 8, 1, _ar_nic_amo_err_info_fp_invalid_detail
};
static const generic_mmr_t _ar_nic_amo_err_info_fp_overflow = {
    "AR_NIC_AMO_ERR_INFO_FP_OVERFLOW", AR_NIC_AMO_ERR_INFO_FP_OVERFLOW, 8, 1, _ar_nic_amo_err_info_fp_overflow_detail
};
static const generic_mmr_t _ar_nic_amo_err_info_fp_underflow = {
    "AR_NIC_AMO_ERR_INFO_FP_UNDERFLOW", AR_NIC_AMO_ERR_INFO_FP_UNDERFLOW, 8, 1, _ar_nic_amo_err_info_fp_underflow_detail
};
static const generic_mmr_t _ar_nic_amo_err_info_req_bus = {
    "AR_NIC_AMO_ERR_INFO_REQ_BUS", AR_NIC_AMO_ERR_INFO_REQ_BUS, 8, 1, _ar_nic_amo_err_info_req_bus_detail
};
static const generic_mmr_t _ar_nic_amo_err_info_rsp_bus = {
    "AR_NIC_AMO_ERR_INFO_RSP_BUS", AR_NIC_AMO_ERR_INFO_RSP_BUS, 8, 1, _ar_nic_amo_err_info_rsp_bus_detail
};
static const generic_mmr_t _ar_nic_amo_dbg_state = {
    "AR_NIC_AMO_DBG_STATE", AR_NIC_AMO_DBG_STATE, 8, 1, _ar_nic_amo_dbg_state_detail
};
static const generic_mmr_t _ar_nic_amo_dbg_errinj_reqlist = {
    "AR_NIC_AMO_DBG_ERRINJ_REQLIST", AR_NIC_AMO_DBG_ERRINJ_REQLIST, 8, 1, _ar_nic_amo_dbg_errinj_reqlist_detail
};
static const generic_mmr_t _ar_nic_amo_dbg_errinj_datastore = {
    "AR_NIC_AMO_DBG_ERRINJ_DATASTORE", AR_NIC_AMO_DBG_ERRINJ_DATASTORE, 8, 1, _ar_nic_amo_dbg_errinj_datastore_detail
};
static const generic_mmr_t _ar_nic_amo_dbg_errinj_req_bus = {
    "AR_NIC_AMO_DBG_ERRINJ_REQ_BUS", AR_NIC_AMO_DBG_ERRINJ_REQ_BUS, 8, 1, _ar_nic_amo_dbg_errinj_req_bus_detail
};
static const generic_mmr_t _ar_nic_amo_dbg_errinj_rsp_bus = {
    "AR_NIC_AMO_DBG_ERRINJ_RSP_BUS", AR_NIC_AMO_DBG_ERRINJ_RSP_BUS, 8, 1, _ar_nic_amo_dbg_errinj_rsp_bus_detail
};
static const generic_mmr_t _ar_nic_amo_prf_en = {
    "AR_NIC_AMO_PRF_EN", AR_NIC_AMO_PRF_EN, 8, 1, _ar_nic_amo_prf_en_detail
};
static const generic_mmr_t _ar_nic_amo_prf_stall_duration_match = {
    "AR_NIC_AMO_PRF_STALL_DURATION_MATCH", AR_NIC_AMO_PRF_STALL_DURATION_MATCH, 8, 1, _ar_nic_amo_prf_stall_duration_match_detail
};
static const generic_mmr_t _ar_nic_amo_prf_stall_duration_flush = {
    "AR_NIC_AMO_PRF_STALL_DURATION_FLUSH", AR_NIC_AMO_PRF_STALL_DURATION_FLUSH, 8, 1, _ar_nic_amo_prf_stall_duration_flush_detail
};
static const generic_mmr_t _ar_nic_amo_prf_stall_duration_full = {
    "AR_NIC_AMO_PRF_STALL_DURATION_FULL", AR_NIC_AMO_PRF_STALL_DURATION_FULL, 8, 1, _ar_nic_amo_prf_stall_duration_full_detail
};
static const generic_mmr_t _ar_nic_amo_prf_stall_duration_ordered = {
    "AR_NIC_AMO_PRF_STALL_DURATION_ORDERED", AR_NIC_AMO_PRF_STALL_DURATION_ORDERED, 8, 1, _ar_nic_amo_prf_stall_duration_ordered_detail
};

/*
 *  INSTALL AR AMO MMRS
 */
static const generic_mmr_t* _ar_amo_mmrs[] _unused = {
    &_ar_nic_amo_cfg_cache_inv,
    &_ar_nic_amo_amo_mmr_ring_0_hi_amo,
    &_ar_nic_amo_amo_mmr_ring_0_mid_amo,
    &_ar_nic_amo_amo_mmr_ring_0_lo_amo,
    &_ar_nic_amo_err_flg_1_hi_amo,
    &_ar_nic_amo_err_flg_1_mid_amo,
    &_ar_nic_amo_err_flg_1_lo_amo,
    &_ar_nic_amo_amo_tagstore_active_2_hi_amo,
    &_ar_nic_amo_amo_tagstore_active_2_mid_amo,
    &_ar_nic_amo_amo_tagstore_active_2_lo_amo,
    &_ar_nic_amo_amo_tagstore_pending_3_hi_amo,
    &_ar_nic_amo_amo_tagstore_pending_3_mid_amo,
    &_ar_nic_amo_amo_tagstore_pending_3_lo_amo,
    &_ar_nic_amo_amo_reqlist_rdy_4_hi_amo,
    &_ar_nic_amo_amo_reqlist_rdy_4_mid_amo,
    &_ar_nic_amo_amo_reqlist_rdy_4_lo_amo,
    &_ar_nic_amo_amo_parb_req_flit_5_hi_amo,
    &_ar_nic_amo_amo_parb_req_flit_5_mid_amo,
    &_ar_nic_amo_amo_parb_req_flit_5_lo_amo,
    &_ar_nic_amo_pi_nic_rsp_flit_6_hi_amo,
    &_ar_nic_amo_pi_nic_rsp_flit_6_mid_amo,
    &_ar_nic_amo_pi_nic_rsp_flit_6_lo_amo,
    &_ar_nic_amo_amo_acp_out_7_hi_amo,
    &_ar_nic_amo_amo_acp_out_7_mid_amo,
    &_ar_nic_amo_amo_acp_out_7_lo_amo,
    &_ar_nic_amo_amo_power_down_ff_hi_amo,
    &_ar_nic_amo_amo_power_down_ff_mid_amo,
    &_ar_nic_amo_amo_power_down_ff_lo_amo,
    &_ar_nic_amo_cfg_rounding_mode,
    &_ar_nic_amo_cfg_params,
    &_ar_nic_amo_cfg_crdts,
    &_ar_nic_amo_cfg_offld,
    &_ar_nic_amo_err_flg,
    &_ar_nic_amo_err_clr,
    &_ar_nic_amo_err_hss_msk,
    &_ar_nic_amo_err_os_msk,
    &_ar_nic_amo_err_first_flg,
    &_ar_nic_amo_err_info_reqlist_ram,
    &_ar_nic_amo_err_info_fp_inexact,
    &_ar_nic_amo_err_info_fp_invalid,
    &_ar_nic_amo_err_info_fp_overflow,
    &_ar_nic_amo_err_info_fp_underflow,
    &_ar_nic_amo_err_info_req_bus,
    &_ar_nic_amo_err_info_rsp_bus,
    &_ar_nic_amo_dbg_state,
    &_ar_nic_amo_dbg_errinj_reqlist,
    &_ar_nic_amo_dbg_errinj_datastore,
    &_ar_nic_amo_dbg_errinj_req_bus,
    &_ar_nic_amo_dbg_errinj_rsp_bus,
    &_ar_nic_amo_prf_en,
    &_ar_nic_amo_prf_stall_duration_match,
    &_ar_nic_amo_prf_stall_duration_flush,
    &_ar_nic_amo_prf_stall_duration_full,
    &_ar_nic_amo_prf_stall_duration_ordered,
    NULL
};

#endif
