/******************************************************************************
 * COPYRIGHT CRAY INC. ar_cbus_defs.h
 * FILE: ar_cbus_defs.h
 * Created by v2h.c on Wed Oct  8 14:39:04 2014
 ******************************************************************************/

#ifndef _AR_CBUS_DEFS_H_
#define _AR_CBUS_DEFS_H_

#define AR_CBUS_N_MMRS                                         	9
#define AR_CBUS_N_DESCS                                        	0

/*
 *  AR CBUS MMR TABLE ADDRESS DEFINES
 */

/*
 *  AR CBUS MMR ADDRESS DEFINES
 */
#define AR_SERDES_CBUS_PATTERN                                 	(AR_CBUS_BASE+0x0000000000ull)
#define AR_SERDES_CBUS_PATTERN_SIZE                            	0x0000000008ull
#define AR_SERDES_CBUS_PATTERN_LIMIT                           	AR_SERDES_CBUS_PATTERN+AR_SERDES_CBUS_PATTERN_SIZE-1
#define AR_SERDES_CBUS_PATDET                                  	(AR_CBUS_BASE+0x0000000001ull)
#define AR_SERDES_CBUS_PATDET_SIZE                             	0x0000000008ull
#define AR_SERDES_CBUS_PATDET_LIMIT                            	AR_SERDES_CBUS_PATDET+AR_SERDES_CBUS_PATDET_SIZE-1
#define AR_SERDES_CBUS_REVPOL                                  	(AR_CBUS_BASE+0x0000000002ull)
#define AR_SERDES_CBUS_REVPOL_SIZE                             	0x0000000008ull
#define AR_SERDES_CBUS_REVPOL_LIMIT                            	AR_SERDES_CBUS_REVPOL+AR_SERDES_CBUS_REVPOL_SIZE-1
#define AR_SERDES_CBUS_TX_PAT                                  	(AR_CBUS_BASE+0x0000000003ull)
#define AR_SERDES_CBUS_TX_PAT_SIZE                             	0x0000000008ull
#define AR_SERDES_CBUS_TX_PAT_LIMIT                            	AR_SERDES_CBUS_TX_PAT+AR_SERDES_CBUS_TX_PAT_SIZE-1
#define AR_SERDES_CBUS_RX_PAT                                  	(AR_CBUS_BASE+0x0000000004ull)
#define AR_SERDES_CBUS_RX_PAT_SIZE                             	0x0000000008ull
#define AR_SERDES_CBUS_RX_PAT_LIMIT                            	AR_SERDES_CBUS_RX_PAT+AR_SERDES_CBUS_RX_PAT_SIZE-1
#define AR_SERDES_CBUS_RX_MASK                                 	(AR_CBUS_BASE+0x0000000005ull)
#define AR_SERDES_CBUS_RX_MASK_SIZE                            	0x0000000008ull
#define AR_SERDES_CBUS_RX_MASK_LIMIT                           	AR_SERDES_CBUS_RX_MASK+AR_SERDES_CBUS_RX_MASK_SIZE-1
#define AR_SERDES_CBUS_ENPOLCNT                                	(AR_CBUS_BASE+0x0000000006ull)
#define AR_SERDES_CBUS_ENPOLCNT_SIZE                           	0x0000000008ull
#define AR_SERDES_CBUS_ENPOLCNT_LIMIT                          	AR_SERDES_CBUS_ENPOLCNT+AR_SERDES_CBUS_ENPOLCNT_SIZE-1
#define AR_SERDES_CBUS_TXI_EN_PROC_RESET                       	(AR_CBUS_BASE+0x0000000007ull)
#define AR_SERDES_CBUS_TXI_EN_PROC_RESET_SIZE                  	0x0000000008ull
#define AR_SERDES_CBUS_TXI_EN_PROC_RESET_LIMIT                 	AR_SERDES_CBUS_TXI_EN_PROC_RESET+AR_SERDES_CBUS_TXI_EN_PROC_RESET_SIZE-1
#define AR_SERDES_CBUS_ELEC_IDLE_EN_SEL                        	(AR_CBUS_BASE+0x0000000008ull)
#define AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_SIZE                   	0x0000000008ull
#define AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_LIMIT                  	AR_SERDES_CBUS_ELEC_IDLE_EN_SEL+AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_SIZE-1

/*
 *  AR_SERDES_CBUS_PATTERN DEFINES
 */
#define AR_SERDES_CBUS_PATTERN_Q_PATTERN_MASK                           	0x00000000000000ffull
#define AR_SERDES_CBUS_PATTERN_Q_PATTERN_BP                             	0
#define AR_SERDES_CBUS_PATTERN_Q_PATTERN_QW                             	0
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_SERDES_CBUS_PATDET DEFINES
 */
#define AR_SERDES_CBUS_PATDET_Q_PATDET_MASK                             	0x00000000000000ffull
#define AR_SERDES_CBUS_PATDET_Q_PATDET_BP                               	0
#define AR_SERDES_CBUS_PATDET_Q_PATDET_QW                               	0
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_SERDES_CBUS_REVPOL DEFINES
 */
#define AR_SERDES_CBUS_REVPOL_REVPOL_MASK                               	0x00000000000000ffull
#define AR_SERDES_CBUS_REVPOL_REVPOL_BP                                 	0
#define AR_SERDES_CBUS_REVPOL_REVPOL_QW                                 	0
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_SERDES_CBUS_TX_PAT DEFINES
 */
#define AR_SERDES_CBUS_TX_PAT_Q_TX_PAT_MASK                             	0x00000000000000ffull
#define AR_SERDES_CBUS_TX_PAT_Q_TX_PAT_BP                               	0
#define AR_SERDES_CBUS_TX_PAT_Q_TX_PAT_QW                               	0
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_SERDES_CBUS_RX_PAT DEFINES
 */
#define AR_SERDES_CBUS_RX_PAT_Q_RX_PAT_MASK                             	0x00000000000000ffull
#define AR_SERDES_CBUS_RX_PAT_Q_RX_PAT_BP                               	0
#define AR_SERDES_CBUS_RX_PAT_Q_RX_PAT_QW                               	0
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_SERDES_CBUS_RX_MASK DEFINES
 */
#define AR_SERDES_CBUS_RX_MASK_Q_RX_MASK_MASK                           	0x00000000000000ffull
#define AR_SERDES_CBUS_RX_MASK_Q_RX_MASK_BP                             	0
#define AR_SERDES_CBUS_RX_MASK_Q_RX_MASK_QW                             	0
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_SERDES_CBUS_ENPOLCNT DEFINES
 */
#define AR_SERDES_CBUS_ENPOLCNT_RESERVED_7_1_MASK                       	0x00000000000000feull
#define AR_SERDES_CBUS_ENPOLCNT_Q_ENPOLCNT_MASK                         	0x0000000000000001ull
#define AR_SERDES_CBUS_ENPOLCNT_RESERVED_7_1_BP                         	1
#define AR_SERDES_CBUS_ENPOLCNT_Q_ENPOLCNT_BP                           	0
#define AR_SERDES_CBUS_ENPOLCNT_RESERVED_7_1_QW                         	0
#define AR_SERDES_CBUS_ENPOLCNT_Q_ENPOLCNT_QW                           	0
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_SERDES_CBUS_TXI_EN_PROC_RESET DEFINES
 */
#define AR_SERDES_CBUS_TXI_EN_PROC_RESET_RESERVED_7_2_MASK              	0x00000000000000fcull
#define AR_SERDES_CBUS_TXI_EN_PROC_RESET_Q_TXI_EN_MASK                  	0x0000000000000002ull
#define AR_SERDES_CBUS_TXI_EN_PROC_RESET_Q_PROC_RESET_MASK              	0x0000000000000001ull
#define AR_SERDES_CBUS_TXI_EN_PROC_RESET_RESERVED_7_2_BP                	2
#define AR_SERDES_CBUS_TXI_EN_PROC_RESET_Q_TXI_EN_BP                    	1
#define AR_SERDES_CBUS_TXI_EN_PROC_RESET_Q_PROC_RESET_BP                	0
#define AR_SERDES_CBUS_TXI_EN_PROC_RESET_RESERVED_7_2_QW                	0
#define AR_SERDES_CBUS_TXI_EN_PROC_RESET_Q_TXI_EN_QW                    	0
#define AR_SERDES_CBUS_TXI_EN_PROC_RESET_Q_PROC_RESET_QW                	0
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_SERDES_CBUS_ELEC_IDLE_EN_SEL DEFINES
 */
#define AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_RESERVED_7_5_MASK               	0x00000000000000e0ull
#define AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_TX_ELEC_IDLE_FPSK_MASK        	0x0000000000000010ull
#define AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_PATT_GEN_EN_FPSK_MASK         	0x0000000000000008ull
#define AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_PATT_GEN_SEL_FPSK_MASK        	0x0000000000000007ull
#define AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_RESERVED_7_5_BP                 	5
#define AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_TX_ELEC_IDLE_FPSK_BP          	4
#define AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_PATT_GEN_EN_FPSK_BP           	3
#define AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_PATT_GEN_SEL_FPSK_BP          	0
#define AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_RESERVED_7_5_QW                 	0
#define AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_TX_ELEC_IDLE_FPSK_QW          	0
#define AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_PATT_GEN_EN_FPSK_QW           	0
#define AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_PATT_GEN_SEL_FPSK_QW          	0
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */



/*
 *  AR CBUS MACROS
 */
#ifndef RD_FIELD
#define RD_FIELD(d, bp, m)	(((d)&(m))>>(bp))
#endif
#ifndef WR_FIELD
#define WR_FIELD(mmr, d, bp, m)	(mmr = (((mmr) & ~(m)) | ((((uint64_t)(d))<<(bp)) & (m))))
#endif
#define RF_AR_SERDES_CBUS_PATTERN_Q_PATTERN(mmr)                	RD_FIELD(mmr,\
									AR_SERDES_CBUS_PATTERN_Q_PATTERN_BP,\
									AR_SERDES_CBUS_PATTERN_Q_PATTERN_MASK)
#define WF_AR_SERDES_CBUS_PATTERN_Q_PATTERN(mmr,v)              	WR_FIELD(mmr,v,\
									AR_SERDES_CBUS_PATTERN_Q_PATTERN_BP,\
									AR_SERDES_CBUS_PATTERN_Q_PATTERN_MASK)
#define RF_AR_SERDES_CBUS_PATDET_Q_PATDET(mmr)                  	RD_FIELD(mmr,\
									AR_SERDES_CBUS_PATDET_Q_PATDET_BP,\
									AR_SERDES_CBUS_PATDET_Q_PATDET_MASK)
#define WF_AR_SERDES_CBUS_PATDET_Q_PATDET(mmr,v)                	WR_FIELD(mmr,v,\
									AR_SERDES_CBUS_PATDET_Q_PATDET_BP,\
									AR_SERDES_CBUS_PATDET_Q_PATDET_MASK)
#define RF_AR_SERDES_CBUS_REVPOL_REVPOL(mmr)                    	RD_FIELD(mmr,\
									AR_SERDES_CBUS_REVPOL_REVPOL_BP,\
									AR_SERDES_CBUS_REVPOL_REVPOL_MASK)
#define WF_AR_SERDES_CBUS_REVPOL_REVPOL(mmr,v)                  	WR_FIELD(mmr,v,\
									AR_SERDES_CBUS_REVPOL_REVPOL_BP,\
									AR_SERDES_CBUS_REVPOL_REVPOL_MASK)
#define RF_AR_SERDES_CBUS_TX_PAT_Q_TX_PAT(mmr)                  	RD_FIELD(mmr,\
									AR_SERDES_CBUS_TX_PAT_Q_TX_PAT_BP,\
									AR_SERDES_CBUS_TX_PAT_Q_TX_PAT_MASK)
#define WF_AR_SERDES_CBUS_TX_PAT_Q_TX_PAT(mmr,v)                	WR_FIELD(mmr,v,\
									AR_SERDES_CBUS_TX_PAT_Q_TX_PAT_BP,\
									AR_SERDES_CBUS_TX_PAT_Q_TX_PAT_MASK)
#define RF_AR_SERDES_CBUS_RX_PAT_Q_RX_PAT(mmr)                  	RD_FIELD(mmr,\
									AR_SERDES_CBUS_RX_PAT_Q_RX_PAT_BP,\
									AR_SERDES_CBUS_RX_PAT_Q_RX_PAT_MASK)
#define WF_AR_SERDES_CBUS_RX_PAT_Q_RX_PAT(mmr,v)                	WR_FIELD(mmr,v,\
									AR_SERDES_CBUS_RX_PAT_Q_RX_PAT_BP,\
									AR_SERDES_CBUS_RX_PAT_Q_RX_PAT_MASK)
#define RF_AR_SERDES_CBUS_RX_MASK_Q_RX_MASK(mmr)                	RD_FIELD(mmr,\
									AR_SERDES_CBUS_RX_MASK_Q_RX_MASK_BP,\
									AR_SERDES_CBUS_RX_MASK_Q_RX_MASK_MASK)
#define WF_AR_SERDES_CBUS_RX_MASK_Q_RX_MASK(mmr,v)              	WR_FIELD(mmr,v,\
									AR_SERDES_CBUS_RX_MASK_Q_RX_MASK_BP,\
									AR_SERDES_CBUS_RX_MASK_Q_RX_MASK_MASK)
#define RF_AR_SERDES_CBUS_ENPOLCNT_RESERVED_7_1(mmr)            	RD_FIELD(mmr,\
									AR_SERDES_CBUS_ENPOLCNT_RESERVED_7_1_BP,\
									AR_SERDES_CBUS_ENPOLCNT_RESERVED_7_1_MASK)
#define WF_AR_SERDES_CBUS_ENPOLCNT_RESERVED_7_1(mmr,v)          	WR_FIELD(mmr,v,\
									AR_SERDES_CBUS_ENPOLCNT_RESERVED_7_1_BP,\
									AR_SERDES_CBUS_ENPOLCNT_RESERVED_7_1_MASK)
#define RF_AR_SERDES_CBUS_ENPOLCNT_Q_ENPOLCNT(mmr)              	RD_FIELD(mmr,\
									AR_SERDES_CBUS_ENPOLCNT_Q_ENPOLCNT_BP,\
									AR_SERDES_CBUS_ENPOLCNT_Q_ENPOLCNT_MASK)
#define WF_AR_SERDES_CBUS_ENPOLCNT_Q_ENPOLCNT(mmr,v)            	WR_FIELD(mmr,v,\
									AR_SERDES_CBUS_ENPOLCNT_Q_ENPOLCNT_BP,\
									AR_SERDES_CBUS_ENPOLCNT_Q_ENPOLCNT_MASK)
#define RF_AR_SERDES_CBUS_TXI_EN_PROC_RESET_RESERVED_7_2(mmr)   	RD_FIELD(mmr,\
									AR_SERDES_CBUS_TXI_EN_PROC_RESET_RESERVED_7_2_BP,\
									AR_SERDES_CBUS_TXI_EN_PROC_RESET_RESERVED_7_2_MASK)
#define WF_AR_SERDES_CBUS_TXI_EN_PROC_RESET_RESERVED_7_2(mmr,v) 	WR_FIELD(mmr,v,\
									AR_SERDES_CBUS_TXI_EN_PROC_RESET_RESERVED_7_2_BP,\
									AR_SERDES_CBUS_TXI_EN_PROC_RESET_RESERVED_7_2_MASK)
#define RF_AR_SERDES_CBUS_TXI_EN_PROC_RESET_Q_TXI_EN(mmr)       	RD_FIELD(mmr,\
									AR_SERDES_CBUS_TXI_EN_PROC_RESET_Q_TXI_EN_BP,\
									AR_SERDES_CBUS_TXI_EN_PROC_RESET_Q_TXI_EN_MASK)
#define WF_AR_SERDES_CBUS_TXI_EN_PROC_RESET_Q_TXI_EN(mmr,v)     	WR_FIELD(mmr,v,\
									AR_SERDES_CBUS_TXI_EN_PROC_RESET_Q_TXI_EN_BP,\
									AR_SERDES_CBUS_TXI_EN_PROC_RESET_Q_TXI_EN_MASK)
#define RF_AR_SERDES_CBUS_TXI_EN_PROC_RESET_Q_PROC_RESET(mmr)   	RD_FIELD(mmr,\
									AR_SERDES_CBUS_TXI_EN_PROC_RESET_Q_PROC_RESET_BP,\
									AR_SERDES_CBUS_TXI_EN_PROC_RESET_Q_PROC_RESET_MASK)
#define WF_AR_SERDES_CBUS_TXI_EN_PROC_RESET_Q_PROC_RESET(mmr,v) 	WR_FIELD(mmr,v,\
									AR_SERDES_CBUS_TXI_EN_PROC_RESET_Q_PROC_RESET_BP,\
									AR_SERDES_CBUS_TXI_EN_PROC_RESET_Q_PROC_RESET_MASK)
#define RF_AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_RESERVED_7_5(mmr)    	RD_FIELD(mmr,\
									AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_RESERVED_7_5_BP,\
									AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_RESERVED_7_5_MASK)
#define WF_AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_RESERVED_7_5(mmr,v)  	WR_FIELD(mmr,v,\
									AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_RESERVED_7_5_BP,\
									AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_RESERVED_7_5_MASK)
#define RF_AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_TX_ELEC_IDLE_FPSK(mmr)	RD_FIELD(mmr,\
									AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_TX_ELEC_IDLE_FPSK_BP,\
									AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_TX_ELEC_IDLE_FPSK_MASK)
#define WF_AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_TX_ELEC_IDLE_FPSK(mmr,v)	WR_FIELD(mmr,v,\
									AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_TX_ELEC_IDLE_FPSK_BP,\
									AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_TX_ELEC_IDLE_FPSK_MASK)
#define RF_AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_PATT_GEN_EN_FPSK(mmr)	RD_FIELD(mmr,\
									AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_PATT_GEN_EN_FPSK_BP,\
									AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_PATT_GEN_EN_FPSK_MASK)
#define WF_AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_PATT_GEN_EN_FPSK(mmr,v)	WR_FIELD(mmr,v,\
									AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_PATT_GEN_EN_FPSK_BP,\
									AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_PATT_GEN_EN_FPSK_MASK)
#define RF_AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_PATT_GEN_SEL_FPSK(mmr)	RD_FIELD(mmr,\
									AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_PATT_GEN_SEL_FPSK_BP,\
									AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_PATT_GEN_SEL_FPSK_MASK)
#define WF_AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_PATT_GEN_SEL_FPSK(mmr,v)	WR_FIELD(mmr,v,\
									AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_PATT_GEN_SEL_FPSK_BP,\
									AR_SERDES_CBUS_ELEC_IDLE_EN_SEL_R_PATT_GEN_SEL_FPSK_MASK)

#endif
