/******************************************************************************
 * COPYRIGHT CRAY INC. ar_dla_mmrs_h.h
 * FILE: ar_dla_mmrs_h.h
 * Created by v2h.c on Wed Oct  8 14:39:04 2014
 ******************************************************************************/

#ifndef _AR_DLA_MMRS_H_H_
#define _AR_DLA_MMRS_H_H_

#ifdef __GNUC__
#define _unused __attribute__((unused))
#else
#define _unused
#endif

#ifndef _GENERIC_MMRD_T_
#define _GENERIC_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint64_t _mask;		/* Field bit mask */
} generic_mmrd_t;
#endif

#ifndef _ERRCAT_MMRD_T_
#define _ERRCAT_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint32_t _ec;		/* Field error category */
} errcat_mmrd_t;
#endif

#ifndef _GENERIC_MMR_T_
#define _GENERIC_MMR_T_
typedef struct {
	char* _name;		/* MMR name */
	uint64_t _addr;		/* MMR address */
	int _size;		/* Size in bytes of MMR */
	int _depth;		/* Number of MMR instances */
	const generic_mmrd_t *_info;	/* MMR detail */
} generic_mmr_t;
#endif

static const generic_mmr_t* _ar_dla_mmrs[] _unused;	/* DLA Array */

/*
 *  AR DLA MMR DETAIL DECLARATIONS
 */
static const generic_mmrd_t _ar_nic_dla_mmr_ring_0_hi_dla_detail[] = {
    { "UNUSED_145_35", AR_NIC_DLA_MMR_RING_0_HI_DLA_UNUSED_145_35_BP, AR_NIC_DLA_MMR_RING_0_HI_DLA_UNUSED_145_35_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_mmr_ring_0_mid_dla_detail[] = {
    { "UNUSED_127_98", AR_NIC_DLA_MMR_RING_0_MID_DLA_UNUSED_127_98_BP, AR_NIC_DLA_MMR_RING_0_MID_DLA_UNUSED_127_98_MASK },
    { "CNTR_RESERVED15", AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_RESERVED15_BP, AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_RESERVED15_MASK },
    { "CNTR_TARB_STALLED", AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_TARB_STALLED_BP, AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_TARB_STALLED_MASK },
    { "CNTR_FMA_PKT_ERR", AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_FMA_PKT_ERR_BP, AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_FMA_PKT_ERR_MASK },
    { "CNTR_PR_ENQ", AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_PR_ENQ_BP, AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_PR_ENQ_MASK },
    { "CNTR_HI_CD_ENQ", AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_HI_CD_ENQ_BP, AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_HI_CD_ENQ_MASK },
    { "CNTR_LO_CD_ENQ", AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_LO_CD_ENQ_BP, AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_LO_CD_ENQ_MASK },
    { "CNTR_FIFO_ENQ_PKT", AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_FIFO_ENQ_PKT_BP, AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_FIFO_ENQ_PKT_MASK },
    { "CNTR_FIFO_HDR_MBE", AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_FIFO_HDR_MBE_BP, AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_FIFO_HDR_MBE_MASK },
    { "CNTR_DATA_MBE", AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_DATA_MBE_BP, AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_DATA_MBE_MASK },
    { "CNTR_HDR_PERR", AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_HDR_PERR_BP, AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_HDR_PERR_MASK },
    { "CNTR_PR_ALLOC_FAIL", AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_PR_ALLOC_FAIL_BP, AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_PR_ALLOC_FAIL_MASK },
    { "CNTR_PR_ALLOC_PASS", AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_PR_ALLOC_PASS_BP, AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_PR_ALLOC_PASS_MASK },
    { "CNTR_HI_CD_ALLOC_FAIL", AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_HI_CD_ALLOC_FAIL_BP, AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_HI_CD_ALLOC_FAIL_MASK },
    { "CNTR_HI_CD_ALLOC_PASS", AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_HI_CD_ALLOC_PASS_BP, AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_HI_CD_ALLOC_PASS_MASK },
    { "CNTR_LO_CD_ALLOC_FAIL", AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_LO_CD_ALLOC_FAIL_BP, AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_LO_CD_ALLOC_FAIL_MASK },
    { "CNTR_LO_CD_ALLOC_PASS", AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_LO_CD_ALLOC_PASS_BP, AR_NIC_DLA_MMR_RING_0_MID_DLA_CNTR_LO_CD_ALLOC_PASS_MASK },
    { "UNUSED_81_64", AR_NIC_DLA_MMR_RING_0_MID_DLA_UNUSED_81_64_BP, AR_NIC_DLA_MMR_RING_0_MID_DLA_UNUSED_81_64_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_mmr_ring_0_lo_dla_detail[] = {
    { "UNUSED_145_35", AR_NIC_DLA_MMR_RING_0_LO_DLA_UNUSED_145_35_BP, AR_NIC_DLA_MMR_RING_0_LO_DLA_UNUSED_145_35_MASK },
    { "R_Q_DLA_PI_OS_IRQ", AR_NIC_DLA_MMR_RING_0_LO_DLA_R_Q_DLA_PI_OS_IRQ_BP, AR_NIC_DLA_MMR_RING_0_LO_DLA_R_Q_DLA_PI_OS_IRQ_MASK },
    { "R_Q_DLA_LB_HSS_IRQ", AR_NIC_DLA_MMR_RING_0_LO_DLA_R_Q_DLA_LB_HSS_IRQ_BP, AR_NIC_DLA_MMR_RING_0_LO_DLA_R_Q_DLA_LB_HSS_IRQ_MASK },
    { "R_Q_DLA_REQMON_RING_WRACK", AR_NIC_DLA_MMR_RING_0_LO_DLA_R_Q_DLA_REQMON_RING_WRACK_BP, AR_NIC_DLA_MMR_RING_0_LO_DLA_R_Q_DLA_REQMON_RING_WRACK_MASK },
    { "R_Q_DLA_REQMON_RING_15_0", AR_NIC_DLA_MMR_RING_0_LO_DLA_R_Q_DLA_REQMON_RING_15_0_BP, AR_NIC_DLA_MMR_RING_0_LO_DLA_R_Q_DLA_REQMON_RING_15_0_MASK },
    { "I_REQMON_DLA_RING_15_0", AR_NIC_DLA_MMR_RING_0_LO_DLA_I_REQMON_DLA_RING_15_0_BP, AR_NIC_DLA_MMR_RING_0_LO_DLA_I_REQMON_DLA_RING_15_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_err_flg_1_hi_dla_detail[] = {
    { "UNUSED_145_83", AR_NIC_DLA_ERR_FLG_1_HI_DLA_UNUSED_145_83_BP, AR_NIC_DLA_ERR_FLG_1_HI_DLA_UNUSED_145_83_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_err_flg_1_mid_dla_detail[] = {
    { "UNUSED_127_83", AR_NIC_DLA_ERR_FLG_1_MID_DLA_UNUSED_127_83_BP, AR_NIC_DLA_ERR_FLG_1_MID_DLA_UNUSED_127_83_MASK },
    { "FIFO_DATA1_MBE", AR_NIC_DLA_ERR_FLG_1_MID_DLA_FIFO_DATA1_MBE_BP, AR_NIC_DLA_ERR_FLG_1_MID_DLA_FIFO_DATA1_MBE_MASK },
    { "FIFO_DATA1_SBE", AR_NIC_DLA_ERR_FLG_1_MID_DLA_FIFO_DATA1_SBE_BP, AR_NIC_DLA_ERR_FLG_1_MID_DLA_FIFO_DATA1_SBE_MASK },
    { "FIFO_DATA0_MBE", AR_NIC_DLA_ERR_FLG_1_MID_DLA_FIFO_DATA0_MBE_BP, AR_NIC_DLA_ERR_FLG_1_MID_DLA_FIFO_DATA0_MBE_MASK },
    { "FIFO_DATA0_SBE", AR_NIC_DLA_ERR_FLG_1_MID_DLA_FIFO_DATA0_SBE_BP, AR_NIC_DLA_ERR_FLG_1_MID_DLA_FIFO_DATA0_SBE_MASK },
    { "ALLOC_BOTH_ERR", AR_NIC_DLA_ERR_FLG_1_MID_DLA_ALLOC_BOTH_ERR_BP, AR_NIC_DLA_ERR_FLG_1_MID_DLA_ALLOC_BOTH_ERR_MASK },
    { "FMA_PKT_ERR", AR_NIC_DLA_ERR_FLG_1_MID_DLA_FMA_PKT_ERR_BP, AR_NIC_DLA_ERR_FLG_1_MID_DLA_FMA_PKT_ERR_MASK },
    { "MARKER_RAM_MBE", AR_NIC_DLA_ERR_FLG_1_MID_DLA_MARKER_RAM_MBE_BP, AR_NIC_DLA_ERR_FLG_1_MID_DLA_MARKER_RAM_MBE_MASK },
    { "MARKER_RAM_SBE", AR_NIC_DLA_ERR_FLG_1_MID_DLA_MARKER_RAM_SBE_BP, AR_NIC_DLA_ERR_FLG_1_MID_DLA_MARKER_RAM_SBE_MASK },
    { "ALLOC_RAM_MBE", AR_NIC_DLA_ERR_FLG_1_MID_DLA_ALLOC_RAM_MBE_BP, AR_NIC_DLA_ERR_FLG_1_MID_DLA_ALLOC_RAM_MBE_MASK },
    { "ALLOC_RAM_SBE", AR_NIC_DLA_ERR_FLG_1_MID_DLA_ALLOC_RAM_SBE_BP, AR_NIC_DLA_ERR_FLG_1_MID_DLA_ALLOC_RAM_SBE_MASK },
    { "FIFO_OVERFLOW", AR_NIC_DLA_ERR_FLG_1_MID_DLA_FIFO_OVERFLOW_BP, AR_NIC_DLA_ERR_FLG_1_MID_DLA_FIFO_OVERFLOW_MASK },
    { "HDR_PERR", AR_NIC_DLA_ERR_FLG_1_MID_DLA_HDR_PERR_BP, AR_NIC_DLA_ERR_FLG_1_MID_DLA_HDR_PERR_MASK },
    { "DATA1_MBE", AR_NIC_DLA_ERR_FLG_1_MID_DLA_DATA1_MBE_BP, AR_NIC_DLA_ERR_FLG_1_MID_DLA_DATA1_MBE_MASK },
    { "DATA1_SBE", AR_NIC_DLA_ERR_FLG_1_MID_DLA_DATA1_SBE_BP, AR_NIC_DLA_ERR_FLG_1_MID_DLA_DATA1_SBE_MASK },
    { "DATA0_MBE", AR_NIC_DLA_ERR_FLG_1_MID_DLA_DATA0_MBE_BP, AR_NIC_DLA_ERR_FLG_1_MID_DLA_DATA0_MBE_MASK },
    { "DATA0_SBE", AR_NIC_DLA_ERR_FLG_1_MID_DLA_DATA0_SBE_BP, AR_NIC_DLA_ERR_FLG_1_MID_DLA_DATA0_SBE_MASK },
    { "FIFO_HDR_MBE", AR_NIC_DLA_ERR_FLG_1_MID_DLA_FIFO_HDR_MBE_BP, AR_NIC_DLA_ERR_FLG_1_MID_DLA_FIFO_HDR_MBE_MASK },
    { "FIFO_HDR_SBE", AR_NIC_DLA_ERR_FLG_1_MID_DLA_FIFO_HDR_SBE_BP, AR_NIC_DLA_ERR_FLG_1_MID_DLA_FIFO_HDR_SBE_MASK },
    { "UNUSED_64", AR_NIC_DLA_ERR_FLG_1_MID_DLA_UNUSED_64_BP, AR_NIC_DLA_ERR_FLG_1_MID_DLA_UNUSED_64_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_err_flg_1_lo_dla_detail[] = {
    { "UNUSED_63_19", AR_NIC_DLA_ERR_FLG_1_LO_DLA_UNUSED_63_19_BP, AR_NIC_DLA_ERR_FLG_1_LO_DLA_UNUSED_63_19_MASK },
    { "I_FIFO_DATA1_MBE", AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_FIFO_DATA1_MBE_BP, AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_FIFO_DATA1_MBE_MASK },
    { "I_FIFO_DATA1_SBE", AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_FIFO_DATA1_SBE_BP, AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_FIFO_DATA1_SBE_MASK },
    { "I_FIFO_DATA0_MBE", AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_FIFO_DATA0_MBE_BP, AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_FIFO_DATA0_MBE_MASK },
    { "I_FIFO_DATA0_SBE", AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_FIFO_DATA0_SBE_BP, AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_FIFO_DATA0_SBE_MASK },
    { "I_ALLOC_BOTH_ERR", AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_ALLOC_BOTH_ERR_BP, AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_ALLOC_BOTH_ERR_MASK },
    { "I_FMA_PKT_ERR", AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_FMA_PKT_ERR_BP, AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_FMA_PKT_ERR_MASK },
    { "I_MARKER_RAM_MBE", AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_MARKER_RAM_MBE_BP, AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_MARKER_RAM_MBE_MASK },
    { "I_MARKER_RAM_SBE", AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_MARKER_RAM_SBE_BP, AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_MARKER_RAM_SBE_MASK },
    { "I_ALLOC_RAM_MBE", AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_ALLOC_RAM_MBE_BP, AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_ALLOC_RAM_MBE_MASK },
    { "I_ALLOC_RAM_SBE", AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_ALLOC_RAM_SBE_BP, AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_ALLOC_RAM_SBE_MASK },
    { "I_FIFO_OVERFLOW", AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_FIFO_OVERFLOW_BP, AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_FIFO_OVERFLOW_MASK },
    { "I_HDR_PERR", AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_HDR_PERR_BP, AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_HDR_PERR_MASK },
    { "I_DATA1_MBE", AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_DATA1_MBE_BP, AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_DATA1_MBE_MASK },
    { "I_DATA1_SBE", AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_DATA1_SBE_BP, AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_DATA1_SBE_MASK },
    { "I_DATA0_MBE", AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_DATA0_MBE_BP, AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_DATA0_MBE_MASK },
    { "I_DATA0_SBE", AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_DATA0_SBE_BP, AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_DATA0_SBE_MASK },
    { "I_FIFO_HDR_MBE", AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_FIFO_HDR_MBE_BP, AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_FIFO_HDR_MBE_MASK },
    { "I_FIFO_HDR_SBE", AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_FIFO_HDR_SBE_BP, AR_NIC_DLA_ERR_FLG_1_LO_DLA_I_FIFO_HDR_SBE_MASK },
    { "UNUSED_0", AR_NIC_DLA_ERR_FLG_1_LO_DLA_UNUSED_0_BP, AR_NIC_DLA_ERR_FLG_1_LO_DLA_UNUSED_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_fma_flit_sg_5_2_hi_dla_detail[] = {
    { "R_Q_FMA_DLA_REQ_SB_SG4", AR_NIC_DLA_FMA_FLIT_SG_5_2_HI_DLA_R_Q_FMA_DLA_REQ_SB_SG4_BP, AR_NIC_DLA_FMA_FLIT_SG_5_2_HI_DLA_R_Q_FMA_DLA_REQ_SB_SG4_MASK },
    { "R_Q_FMA_DLA_REQ_FLIT_SG4", AR_NIC_DLA_FMA_FLIT_SG_5_2_HI_DLA_R_Q_FMA_DLA_REQ_FLIT_SG4_BP, AR_NIC_DLA_FMA_FLIT_SG_5_2_HI_DLA_R_Q_FMA_DLA_REQ_FLIT_SG4_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_fma_flit_sg_5_2_mid_dla_detail[] = {
    { "R_Q_FMA_DLA_REQ_FLIT_SG4", AR_NIC_DLA_FMA_FLIT_SG_5_2_MID_DLA_R_Q_FMA_DLA_REQ_FLIT_SG4_BP, AR_NIC_DLA_FMA_FLIT_SG_5_2_MID_DLA_R_Q_FMA_DLA_REQ_FLIT_SG4_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_fma_flit_sg_5_2_lo_dla_detail[] = {
    { "R_Q_FMA_DLA_REQ_FLIT_SG4", AR_NIC_DLA_FMA_FLIT_SG_5_2_LO_DLA_R_Q_FMA_DLA_REQ_FLIT_SG4_BP, AR_NIC_DLA_FMA_FLIT_SG_5_2_LO_DLA_R_Q_FMA_DLA_REQ_FLIT_SG4_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_dla_op_and_result_sg_5_3_hi_dla_detail[] = {
    { "UNUSED_145_38", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_HI_DLA_UNUSED_145_38_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_HI_DLA_UNUSED_145_38_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_dla_op_and_result_sg_5_3_mid_dla_detail[] = {
    { "UNUSED_145_38", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_MID_DLA_UNUSED_145_38_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_MID_DLA_UNUSED_145_38_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_dla_op_and_result_sg_5_3_lo_dla_detail[] = {
    { "UNUSED_145_38", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_UNUSED_145_38_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_UNUSED_145_38_MASK },
    { "Q_DESC_ALLOC_OVERFLOW_SG4", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_DESC_ALLOC_OVERFLOW_SG4_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_DESC_ALLOC_OVERFLOW_SG4_MASK },
    { "R_Q_FMA_DLA_REQ_SB_SG4", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_FMA_DLA_REQ_SB_SG4_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_FMA_DLA_REQ_SB_SG4_MASK },
    { "N1B0_34", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_N1B0_34_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_N1B0_34_MASK },
    { "Q_DESC_CD_ACTIVE_SG4", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_DESC_CD_ACTIVE_SG4_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_DESC_CD_ACTIVE_SG4_MASK },
    { "Q_DESC_PR_ACTIVE_SG4", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_DESC_PR_ACTIVE_SG4_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_DESC_PR_ACTIVE_SG4_MASK },
    { "Q_DESC_HP_ACTIVE_SG4", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_DESC_HP_ACTIVE_SG4_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_DESC_HP_ACTIVE_SG4_MASK },
    { "Q_DESC_TRANS_OVERFLOW_SG4", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_DESC_TRANS_OVERFLOW_SG4_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_DESC_TRANS_OVERFLOW_SG4_MASK },
    { "Q_TRANS_START_SG4_16", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_TRANS_START_SG4_16_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_TRANS_START_SG4_16_MASK },
    { "Q_NO_ENQUEUE_SG4_16", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_NO_ENQUEUE_SG4_16_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_NO_ENQUEUE_SG4_16_MASK },
    { "Q_DESC_DISCARD_SG4", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_DESC_DISCARD_SG4_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_DESC_DISCARD_SG4_MASK },
    { "Q_DLA_MARKER_SG4_16", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_DLA_MARKER_SG4_16_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_DLA_MARKER_SG4_16_MASK },
    { "Q_TRANS_END_SG4_16", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_TRANS_END_SG4_16_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_TRANS_END_SG4_16_MASK },
    { "Q_DEALLOCATE_SG4_16", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_DEALLOCATE_SG4_16_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_DEALLOCATE_SG4_16_MASK },
    { "Q_ALLOC_STAT_RESET_SG4_16", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_ALLOC_STAT_RESET_SG4_16_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_ALLOC_STAT_RESET_SG4_16_MASK },
    { "Q_DISCARD_RESET_SG4_16", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_DISCARD_RESET_SG4_16_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_DISCARD_RESET_SG4_16_MASK },
    { "Q_DESC_SG5", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_DESC_SG5_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_DESC_SG5_MASK },
    { "R_Q_ENQ_REQUEST_SG5_0", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_ENQ_REQUEST_SG5_0_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_ENQ_REQUEST_SG5_0_MASK },
    { "Q_FMA_DLA_REQ_COUNT_SG5", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_FMA_DLA_REQ_COUNT_SG5_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_Q_FMA_DLA_REQ_COUNT_SG5_MASK },
    { "R_Q_NO_ENQUEUE_SG5", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_NO_ENQUEUE_SG5_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_NO_ENQUEUE_SG5_MASK },
    { "R_Q_LO_CD_ENQ_SG5_0", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_LO_CD_ENQ_SG5_0_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_LO_CD_ENQ_SG5_0_MASK },
    { "R_Q_HI_CD_ENQ_SG5_0", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_HI_CD_ENQ_SG5_0_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_HI_CD_ENQ_SG5_0_MASK },
    { "R_Q_PR_ENQ_SG5_0", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_PR_ENQ_SG5_0_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_PR_ENQ_SG5_0_MASK },
    { "R_Q_LO_CD_ALLOC_PASS", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_LO_CD_ALLOC_PASS_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_LO_CD_ALLOC_PASS_MASK },
    { "R_Q_HI_CD_ALLOC_PASS", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_HI_CD_ALLOC_PASS_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_HI_CD_ALLOC_PASS_MASK },
    { "R_Q_PR_ALLOC_PASS", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_PR_ALLOC_PASS_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_PR_ALLOC_PASS_MASK },
    { "R_Q_LO_CD_ALLOC_FAIL", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_LO_CD_ALLOC_FAIL_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_LO_CD_ALLOC_FAIL_MASK },
    { "R_Q_HI_CD_ALLOC_FAIL", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_HI_CD_ALLOC_FAIL_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_HI_CD_ALLOC_FAIL_MASK },
    { "R_Q_PR_ALLOC_FAIL", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_PR_ALLOC_FAIL_BP, AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA_R_Q_PR_ALLOC_FAIL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_dla_packet_to_tarb_4_hi_dla_detail[] = {
    { "R_Q_DLA_LM_REQ_SB", AR_NIC_DLA_DLA_PACKET_TO_TARB_4_HI_DLA_R_Q_DLA_LM_REQ_SB_BP, AR_NIC_DLA_DLA_PACKET_TO_TARB_4_HI_DLA_R_Q_DLA_LM_REQ_SB_MASK },
    { "R_Q_DLA_LM_REQ_FLIT", AR_NIC_DLA_DLA_PACKET_TO_TARB_4_HI_DLA_R_Q_DLA_LM_REQ_FLIT_BP, AR_NIC_DLA_DLA_PACKET_TO_TARB_4_HI_DLA_R_Q_DLA_LM_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_dla_packet_to_tarb_4_mid_dla_detail[] = {
    { "R_Q_DLA_LM_REQ_FLIT", AR_NIC_DLA_DLA_PACKET_TO_TARB_4_MID_DLA_R_Q_DLA_LM_REQ_FLIT_BP, AR_NIC_DLA_DLA_PACKET_TO_TARB_4_MID_DLA_R_Q_DLA_LM_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_dla_packet_to_tarb_4_lo_dla_detail[] = {
    { "R_Q_DLA_LM_REQ_FLIT", AR_NIC_DLA_DLA_PACKET_TO_TARB_4_LO_DLA_R_Q_DLA_LM_REQ_FLIT_BP, AR_NIC_DLA_DLA_PACKET_TO_TARB_4_LO_DLA_R_Q_DLA_LM_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_cfg_max_detail[] = {
    { "MAX_CREDITS", AR_NIC_DLA_CFG_MAX_MAX_CREDITS_BP, AR_NIC_DLA_CFG_MAX_MAX_CREDITS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_cfg_max_lo_cd_detail[] = {
    { "MAX_LO_CD_CREDITS", AR_NIC_DLA_CFG_MAX_LO_CD_MAX_LO_CD_CREDITS_BP, AR_NIC_DLA_CFG_MAX_LO_CD_MAX_LO_CD_CREDITS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_cfg_max_hi_cd_detail[] = {
    { "MAX_HI_CD_CREDITS", AR_NIC_DLA_CFG_MAX_HI_CD_MAX_HI_CD_CREDITS_BP, AR_NIC_DLA_CFG_MAX_HI_CD_MAX_HI_CD_CREDITS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_cfg_max_pr_detail[] = {
    { "MAX_PR_CREDITS", AR_NIC_DLA_CFG_MAX_PR_MAX_PR_CREDITS_BP, AR_NIC_DLA_CFG_MAX_PR_MAX_PR_CREDITS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_cfg_max_lo_cd_pr_detail[] = {
    { "MAX_LO_CD_PR_CREDITS", AR_NIC_DLA_CFG_MAX_LO_CD_PR_MAX_LO_CD_PR_CREDITS_BP, AR_NIC_DLA_CFG_MAX_LO_CD_PR_MAX_LO_CD_PR_CREDITS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_cfg_max_lo_hi_cd_detail[] = {
    { "MAX_LO_HI_CD_CREDITS", AR_NIC_DLA_CFG_MAX_LO_HI_CD_MAX_LO_HI_CD_CREDITS_BP, AR_NIC_DLA_CFG_MAX_LO_HI_CD_MAX_LO_HI_CD_CREDITS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_cfg_max_hi_cd_pr_detail[] = {
    { "MAX_HI_CD_PR_CREDITS", AR_NIC_DLA_CFG_MAX_HI_CD_PR_MAX_HI_CD_PR_CREDITS_BP, AR_NIC_DLA_CFG_MAX_HI_CD_PR_MAX_HI_CD_PR_CREDITS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_cfg_max_cd_alloc_detail[] = {
    { "MAX_CD_ALLOC_CREDITS", AR_NIC_DLA_CFG_MAX_CD_ALLOC_MAX_CD_ALLOC_CREDITS_BP, AR_NIC_DLA_CFG_MAX_CD_ALLOC_MAX_CD_ALLOC_CREDITS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_cfg_max_pr_alloc_detail[] = {
    { "MAX_PR_ALLOC_CREDITS", AR_NIC_DLA_CFG_MAX_PR_ALLOC_MAX_PR_ALLOC_CREDITS_BP, AR_NIC_DLA_CFG_MAX_PR_ALLOC_MAX_PR_ALLOC_CREDITS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_sts_consumed_detail[] = {
    { "CONSUMED", AR_NIC_DLA_STS_CONSUMED_CONSUMED_BP, AR_NIC_DLA_STS_CONSUMED_CONSUMED_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_sts_consumed_lo_cd_detail[] = {
    { "LO_CD_CONSUMED", AR_NIC_DLA_STS_CONSUMED_LO_CD_LO_CD_CONSUMED_BP, AR_NIC_DLA_STS_CONSUMED_LO_CD_LO_CD_CONSUMED_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_sts_consumed_hi_cd_detail[] = {
    { "HI_CD_CONSUMED", AR_NIC_DLA_STS_CONSUMED_HI_CD_HI_CD_CONSUMED_BP, AR_NIC_DLA_STS_CONSUMED_HI_CD_HI_CD_CONSUMED_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_sts_consumed_pr_detail[] = {
    { "PR_CONSUMED", AR_NIC_DLA_STS_CONSUMED_PR_PR_CONSUMED_BP, AR_NIC_DLA_STS_CONSUMED_PR_PR_CONSUMED_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_sts_resvd_lo_cd_detail[] = {
    { "LO_CD_RESVD", AR_NIC_DLA_STS_RESVD_LO_CD_LO_CD_RESVD_BP, AR_NIC_DLA_STS_RESVD_LO_CD_LO_CD_RESVD_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_sts_resvd_hi_cd_detail[] = {
    { "HI_CD_RESVD", AR_NIC_DLA_STS_RESVD_HI_CD_HI_CD_RESVD_BP, AR_NIC_DLA_STS_RESVD_HI_CD_HI_CD_RESVD_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_sts_resvd_pr_detail[] = {
    { "PR_RESVD", AR_NIC_DLA_STS_RESVD_PR_PR_RESVD_BP, AR_NIC_DLA_STS_RESVD_PR_PR_RESVD_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_err_flg_detail[] = {
    { "FIFO_DATA1_MBE", AR_NIC_DLA_ERR_FLG_FIFO_DATA1_MBE_BP, AR_NIC_DLA_ERR_FLG_FIFO_DATA1_MBE_MASK },
    { "FIFO_DATA1_SBE", AR_NIC_DLA_ERR_FLG_FIFO_DATA1_SBE_BP, AR_NIC_DLA_ERR_FLG_FIFO_DATA1_SBE_MASK },
    { "FIFO_DATA0_MBE", AR_NIC_DLA_ERR_FLG_FIFO_DATA0_MBE_BP, AR_NIC_DLA_ERR_FLG_FIFO_DATA0_MBE_MASK },
    { "FIFO_DATA0_SBE", AR_NIC_DLA_ERR_FLG_FIFO_DATA0_SBE_BP, AR_NIC_DLA_ERR_FLG_FIFO_DATA0_SBE_MASK },
    { "ALLOC_BOTH_ERR", AR_NIC_DLA_ERR_FLG_ALLOC_BOTH_ERR_BP, AR_NIC_DLA_ERR_FLG_ALLOC_BOTH_ERR_MASK },
    { "FMA_PKT_ERR", AR_NIC_DLA_ERR_FLG_FMA_PKT_ERR_BP, AR_NIC_DLA_ERR_FLG_FMA_PKT_ERR_MASK },
    { "MARKER_RAM_MBE", AR_NIC_DLA_ERR_FLG_MARKER_RAM_MBE_BP, AR_NIC_DLA_ERR_FLG_MARKER_RAM_MBE_MASK },
    { "MARKER_RAM_SBE", AR_NIC_DLA_ERR_FLG_MARKER_RAM_SBE_BP, AR_NIC_DLA_ERR_FLG_MARKER_RAM_SBE_MASK },
    { "ALLOC_RAM_MBE", AR_NIC_DLA_ERR_FLG_ALLOC_RAM_MBE_BP, AR_NIC_DLA_ERR_FLG_ALLOC_RAM_MBE_MASK },
    { "ALLOC_RAM_SBE", AR_NIC_DLA_ERR_FLG_ALLOC_RAM_SBE_BP, AR_NIC_DLA_ERR_FLG_ALLOC_RAM_SBE_MASK },
    { "FIFO_OVERFLOW", AR_NIC_DLA_ERR_FLG_FIFO_OVERFLOW_BP, AR_NIC_DLA_ERR_FLG_FIFO_OVERFLOW_MASK },
    { "HDR_PERR", AR_NIC_DLA_ERR_FLG_HDR_PERR_BP, AR_NIC_DLA_ERR_FLG_HDR_PERR_MASK },
    { "DATA1_MBE", AR_NIC_DLA_ERR_FLG_DATA1_MBE_BP, AR_NIC_DLA_ERR_FLG_DATA1_MBE_MASK },
    { "DATA1_SBE", AR_NIC_DLA_ERR_FLG_DATA1_SBE_BP, AR_NIC_DLA_ERR_FLG_DATA1_SBE_MASK },
    { "DATA0_MBE", AR_NIC_DLA_ERR_FLG_DATA0_MBE_BP, AR_NIC_DLA_ERR_FLG_DATA0_MBE_MASK },
    { "DATA0_SBE", AR_NIC_DLA_ERR_FLG_DATA0_SBE_BP, AR_NIC_DLA_ERR_FLG_DATA0_SBE_MASK },
    { "FIFO_HDR_MBE", AR_NIC_DLA_ERR_FLG_FIFO_HDR_MBE_BP, AR_NIC_DLA_ERR_FLG_FIFO_HDR_MBE_MASK },
    { "FIFO_HDR_SBE", AR_NIC_DLA_ERR_FLG_FIFO_HDR_SBE_BP, AR_NIC_DLA_ERR_FLG_FIFO_HDR_SBE_MASK },
    { "DIAG_ONLY", AR_NIC_DLA_ERR_FLG_DIAG_ONLY_BP, AR_NIC_DLA_ERR_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
#ifdef EXCEPTIONS_DEFS
static const errcat_mmrd_t _ar_nic_dla_err_flg_errcat[] = {
    { "FIFO_DATA1_MBE", AR_NIC_DLA_ERR_FLG_FIFO_DATA1_MBE_BP, AR_NIC_DLA_ERR_FLG_FIFO_DATA1_MBE_EC },
    { "FIFO_DATA1_SBE", AR_NIC_DLA_ERR_FLG_FIFO_DATA1_SBE_BP, AR_NIC_DLA_ERR_FLG_FIFO_DATA1_SBE_EC },
    { "FIFO_DATA0_MBE", AR_NIC_DLA_ERR_FLG_FIFO_DATA0_MBE_BP, AR_NIC_DLA_ERR_FLG_FIFO_DATA0_MBE_EC },
    { "FIFO_DATA0_SBE", AR_NIC_DLA_ERR_FLG_FIFO_DATA0_SBE_BP, AR_NIC_DLA_ERR_FLG_FIFO_DATA0_SBE_EC },
    { "ALLOC_BOTH_ERR", AR_NIC_DLA_ERR_FLG_ALLOC_BOTH_ERR_BP, AR_NIC_DLA_ERR_FLG_ALLOC_BOTH_ERR_EC },
    { "FMA_PKT_ERR", AR_NIC_DLA_ERR_FLG_FMA_PKT_ERR_BP, AR_NIC_DLA_ERR_FLG_FMA_PKT_ERR_EC },
    { "MARKER_RAM_MBE", AR_NIC_DLA_ERR_FLG_MARKER_RAM_MBE_BP, AR_NIC_DLA_ERR_FLG_MARKER_RAM_MBE_EC },
    { "MARKER_RAM_SBE", AR_NIC_DLA_ERR_FLG_MARKER_RAM_SBE_BP, AR_NIC_DLA_ERR_FLG_MARKER_RAM_SBE_EC },
    { "ALLOC_RAM_MBE", AR_NIC_DLA_ERR_FLG_ALLOC_RAM_MBE_BP, AR_NIC_DLA_ERR_FLG_ALLOC_RAM_MBE_EC },
    { "ALLOC_RAM_SBE", AR_NIC_DLA_ERR_FLG_ALLOC_RAM_SBE_BP, AR_NIC_DLA_ERR_FLG_ALLOC_RAM_SBE_EC },
    { "FIFO_OVERFLOW", AR_NIC_DLA_ERR_FLG_FIFO_OVERFLOW_BP, AR_NIC_DLA_ERR_FLG_FIFO_OVERFLOW_EC },
    { "HDR_PERR", AR_NIC_DLA_ERR_FLG_HDR_PERR_BP, AR_NIC_DLA_ERR_FLG_HDR_PERR_EC },
    { "DATA1_MBE", AR_NIC_DLA_ERR_FLG_DATA1_MBE_BP, AR_NIC_DLA_ERR_FLG_DATA1_MBE_EC },
    { "DATA1_SBE", AR_NIC_DLA_ERR_FLG_DATA1_SBE_BP, AR_NIC_DLA_ERR_FLG_DATA1_SBE_EC },
    { "DATA0_MBE", AR_NIC_DLA_ERR_FLG_DATA0_MBE_BP, AR_NIC_DLA_ERR_FLG_DATA0_MBE_EC },
    { "DATA0_SBE", AR_NIC_DLA_ERR_FLG_DATA0_SBE_BP, AR_NIC_DLA_ERR_FLG_DATA0_SBE_EC },
    { "FIFO_HDR_MBE", AR_NIC_DLA_ERR_FLG_FIFO_HDR_MBE_BP, AR_NIC_DLA_ERR_FLG_FIFO_HDR_MBE_EC },
    { "FIFO_HDR_SBE", AR_NIC_DLA_ERR_FLG_FIFO_HDR_SBE_BP, AR_NIC_DLA_ERR_FLG_FIFO_HDR_SBE_EC },
    { "DIAG_ONLY", AR_NIC_DLA_ERR_FLG_DIAG_ONLY_BP, AR_NIC_DLA_ERR_FLG_DIAG_ONLY_EC },
    { NULL, 0, 0 }
};
#endif
static const generic_mmrd_t _ar_nic_dla_err_clr_detail[] = {
    { "FIFO_DATA1_MBE", AR_NIC_DLA_ERR_CLR_FIFO_DATA1_MBE_BP, AR_NIC_DLA_ERR_CLR_FIFO_DATA1_MBE_MASK },
    { "FIFO_DATA1_SBE", AR_NIC_DLA_ERR_CLR_FIFO_DATA1_SBE_BP, AR_NIC_DLA_ERR_CLR_FIFO_DATA1_SBE_MASK },
    { "FIFO_DATA0_MBE", AR_NIC_DLA_ERR_CLR_FIFO_DATA0_MBE_BP, AR_NIC_DLA_ERR_CLR_FIFO_DATA0_MBE_MASK },
    { "FIFO_DATA0_SBE", AR_NIC_DLA_ERR_CLR_FIFO_DATA0_SBE_BP, AR_NIC_DLA_ERR_CLR_FIFO_DATA0_SBE_MASK },
    { "ALLOC_BOTH_ERR", AR_NIC_DLA_ERR_CLR_ALLOC_BOTH_ERR_BP, AR_NIC_DLA_ERR_CLR_ALLOC_BOTH_ERR_MASK },
    { "FMA_PKT_ERR", AR_NIC_DLA_ERR_CLR_FMA_PKT_ERR_BP, AR_NIC_DLA_ERR_CLR_FMA_PKT_ERR_MASK },
    { "MARKER_RAM_MBE", AR_NIC_DLA_ERR_CLR_MARKER_RAM_MBE_BP, AR_NIC_DLA_ERR_CLR_MARKER_RAM_MBE_MASK },
    { "MARKER_RAM_SBE", AR_NIC_DLA_ERR_CLR_MARKER_RAM_SBE_BP, AR_NIC_DLA_ERR_CLR_MARKER_RAM_SBE_MASK },
    { "ALLOC_RAM_MBE", AR_NIC_DLA_ERR_CLR_ALLOC_RAM_MBE_BP, AR_NIC_DLA_ERR_CLR_ALLOC_RAM_MBE_MASK },
    { "ALLOC_RAM_SBE", AR_NIC_DLA_ERR_CLR_ALLOC_RAM_SBE_BP, AR_NIC_DLA_ERR_CLR_ALLOC_RAM_SBE_MASK },
    { "FIFO_OVERFLOW", AR_NIC_DLA_ERR_CLR_FIFO_OVERFLOW_BP, AR_NIC_DLA_ERR_CLR_FIFO_OVERFLOW_MASK },
    { "HDR_PERR", AR_NIC_DLA_ERR_CLR_HDR_PERR_BP, AR_NIC_DLA_ERR_CLR_HDR_PERR_MASK },
    { "DATA1_MBE", AR_NIC_DLA_ERR_CLR_DATA1_MBE_BP, AR_NIC_DLA_ERR_CLR_DATA1_MBE_MASK },
    { "DATA1_SBE", AR_NIC_DLA_ERR_CLR_DATA1_SBE_BP, AR_NIC_DLA_ERR_CLR_DATA1_SBE_MASK },
    { "DATA0_MBE", AR_NIC_DLA_ERR_CLR_DATA0_MBE_BP, AR_NIC_DLA_ERR_CLR_DATA0_MBE_MASK },
    { "DATA0_SBE", AR_NIC_DLA_ERR_CLR_DATA0_SBE_BP, AR_NIC_DLA_ERR_CLR_DATA0_SBE_MASK },
    { "FIFO_HDR_MBE", AR_NIC_DLA_ERR_CLR_FIFO_HDR_MBE_BP, AR_NIC_DLA_ERR_CLR_FIFO_HDR_MBE_MASK },
    { "FIFO_HDR_SBE", AR_NIC_DLA_ERR_CLR_FIFO_HDR_SBE_BP, AR_NIC_DLA_ERR_CLR_FIFO_HDR_SBE_MASK },
    { "DIAG_ONLY", AR_NIC_DLA_ERR_CLR_DIAG_ONLY_BP, AR_NIC_DLA_ERR_CLR_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_err_hss_msk_detail[] = {
    { "FIFO_DATA1_MBE", AR_NIC_DLA_ERR_HSS_MSK_FIFO_DATA1_MBE_BP, AR_NIC_DLA_ERR_HSS_MSK_FIFO_DATA1_MBE_MASK },
    { "FIFO_DATA1_SBE", AR_NIC_DLA_ERR_HSS_MSK_FIFO_DATA1_SBE_BP, AR_NIC_DLA_ERR_HSS_MSK_FIFO_DATA1_SBE_MASK },
    { "FIFO_DATA0_MBE", AR_NIC_DLA_ERR_HSS_MSK_FIFO_DATA0_MBE_BP, AR_NIC_DLA_ERR_HSS_MSK_FIFO_DATA0_MBE_MASK },
    { "FIFO_DATA0_SBE", AR_NIC_DLA_ERR_HSS_MSK_FIFO_DATA0_SBE_BP, AR_NIC_DLA_ERR_HSS_MSK_FIFO_DATA0_SBE_MASK },
    { "ALLOC_BOTH_ERR", AR_NIC_DLA_ERR_HSS_MSK_ALLOC_BOTH_ERR_BP, AR_NIC_DLA_ERR_HSS_MSK_ALLOC_BOTH_ERR_MASK },
    { "FMA_PKT_ERR", AR_NIC_DLA_ERR_HSS_MSK_FMA_PKT_ERR_BP, AR_NIC_DLA_ERR_HSS_MSK_FMA_PKT_ERR_MASK },
    { "MARKER_RAM_MBE", AR_NIC_DLA_ERR_HSS_MSK_MARKER_RAM_MBE_BP, AR_NIC_DLA_ERR_HSS_MSK_MARKER_RAM_MBE_MASK },
    { "MARKER_RAM_SBE", AR_NIC_DLA_ERR_HSS_MSK_MARKER_RAM_SBE_BP, AR_NIC_DLA_ERR_HSS_MSK_MARKER_RAM_SBE_MASK },
    { "ALLOC_RAM_MBE", AR_NIC_DLA_ERR_HSS_MSK_ALLOC_RAM_MBE_BP, AR_NIC_DLA_ERR_HSS_MSK_ALLOC_RAM_MBE_MASK },
    { "ALLOC_RAM_SBE", AR_NIC_DLA_ERR_HSS_MSK_ALLOC_RAM_SBE_BP, AR_NIC_DLA_ERR_HSS_MSK_ALLOC_RAM_SBE_MASK },
    { "FIFO_OVERFLOW", AR_NIC_DLA_ERR_HSS_MSK_FIFO_OVERFLOW_BP, AR_NIC_DLA_ERR_HSS_MSK_FIFO_OVERFLOW_MASK },
    { "HDR_PERR", AR_NIC_DLA_ERR_HSS_MSK_HDR_PERR_BP, AR_NIC_DLA_ERR_HSS_MSK_HDR_PERR_MASK },
    { "DATA1_MBE", AR_NIC_DLA_ERR_HSS_MSK_DATA1_MBE_BP, AR_NIC_DLA_ERR_HSS_MSK_DATA1_MBE_MASK },
    { "DATA1_SBE", AR_NIC_DLA_ERR_HSS_MSK_DATA1_SBE_BP, AR_NIC_DLA_ERR_HSS_MSK_DATA1_SBE_MASK },
    { "DATA0_MBE", AR_NIC_DLA_ERR_HSS_MSK_DATA0_MBE_BP, AR_NIC_DLA_ERR_HSS_MSK_DATA0_MBE_MASK },
    { "DATA0_SBE", AR_NIC_DLA_ERR_HSS_MSK_DATA0_SBE_BP, AR_NIC_DLA_ERR_HSS_MSK_DATA0_SBE_MASK },
    { "FIFO_HDR_MBE", AR_NIC_DLA_ERR_HSS_MSK_FIFO_HDR_MBE_BP, AR_NIC_DLA_ERR_HSS_MSK_FIFO_HDR_MBE_MASK },
    { "FIFO_HDR_SBE", AR_NIC_DLA_ERR_HSS_MSK_FIFO_HDR_SBE_BP, AR_NIC_DLA_ERR_HSS_MSK_FIFO_HDR_SBE_MASK },
    { "DIAG_ONLY", AR_NIC_DLA_ERR_HSS_MSK_DIAG_ONLY_BP, AR_NIC_DLA_ERR_HSS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_err_os_msk_detail[] = {
    { "FIFO_DATA1_MBE", AR_NIC_DLA_ERR_OS_MSK_FIFO_DATA1_MBE_BP, AR_NIC_DLA_ERR_OS_MSK_FIFO_DATA1_MBE_MASK },
    { "FIFO_DATA1_SBE", AR_NIC_DLA_ERR_OS_MSK_FIFO_DATA1_SBE_BP, AR_NIC_DLA_ERR_OS_MSK_FIFO_DATA1_SBE_MASK },
    { "FIFO_DATA0_MBE", AR_NIC_DLA_ERR_OS_MSK_FIFO_DATA0_MBE_BP, AR_NIC_DLA_ERR_OS_MSK_FIFO_DATA0_MBE_MASK },
    { "FIFO_DATA0_SBE", AR_NIC_DLA_ERR_OS_MSK_FIFO_DATA0_SBE_BP, AR_NIC_DLA_ERR_OS_MSK_FIFO_DATA0_SBE_MASK },
    { "ALLOC_BOTH_ERR", AR_NIC_DLA_ERR_OS_MSK_ALLOC_BOTH_ERR_BP, AR_NIC_DLA_ERR_OS_MSK_ALLOC_BOTH_ERR_MASK },
    { "FMA_PKT_ERR", AR_NIC_DLA_ERR_OS_MSK_FMA_PKT_ERR_BP, AR_NIC_DLA_ERR_OS_MSK_FMA_PKT_ERR_MASK },
    { "MARKER_RAM_MBE", AR_NIC_DLA_ERR_OS_MSK_MARKER_RAM_MBE_BP, AR_NIC_DLA_ERR_OS_MSK_MARKER_RAM_MBE_MASK },
    { "MARKER_RAM_SBE", AR_NIC_DLA_ERR_OS_MSK_MARKER_RAM_SBE_BP, AR_NIC_DLA_ERR_OS_MSK_MARKER_RAM_SBE_MASK },
    { "ALLOC_RAM_MBE", AR_NIC_DLA_ERR_OS_MSK_ALLOC_RAM_MBE_BP, AR_NIC_DLA_ERR_OS_MSK_ALLOC_RAM_MBE_MASK },
    { "ALLOC_RAM_SBE", AR_NIC_DLA_ERR_OS_MSK_ALLOC_RAM_SBE_BP, AR_NIC_DLA_ERR_OS_MSK_ALLOC_RAM_SBE_MASK },
    { "FIFO_OVERFLOW", AR_NIC_DLA_ERR_OS_MSK_FIFO_OVERFLOW_BP, AR_NIC_DLA_ERR_OS_MSK_FIFO_OVERFLOW_MASK },
    { "HDR_PERR", AR_NIC_DLA_ERR_OS_MSK_HDR_PERR_BP, AR_NIC_DLA_ERR_OS_MSK_HDR_PERR_MASK },
    { "DATA1_MBE", AR_NIC_DLA_ERR_OS_MSK_DATA1_MBE_BP, AR_NIC_DLA_ERR_OS_MSK_DATA1_MBE_MASK },
    { "DATA1_SBE", AR_NIC_DLA_ERR_OS_MSK_DATA1_SBE_BP, AR_NIC_DLA_ERR_OS_MSK_DATA1_SBE_MASK },
    { "DATA0_MBE", AR_NIC_DLA_ERR_OS_MSK_DATA0_MBE_BP, AR_NIC_DLA_ERR_OS_MSK_DATA0_MBE_MASK },
    { "DATA0_SBE", AR_NIC_DLA_ERR_OS_MSK_DATA0_SBE_BP, AR_NIC_DLA_ERR_OS_MSK_DATA0_SBE_MASK },
    { "FIFO_HDR_MBE", AR_NIC_DLA_ERR_OS_MSK_FIFO_HDR_MBE_BP, AR_NIC_DLA_ERR_OS_MSK_FIFO_HDR_MBE_MASK },
    { "FIFO_HDR_SBE", AR_NIC_DLA_ERR_OS_MSK_FIFO_HDR_SBE_BP, AR_NIC_DLA_ERR_OS_MSK_FIFO_HDR_SBE_MASK },
    { "DIAG_ONLY", AR_NIC_DLA_ERR_OS_MSK_DIAG_ONLY_BP, AR_NIC_DLA_ERR_OS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_err_first_flg_detail[] = {
    { "FIFO_DATA1_MBE", AR_NIC_DLA_ERR_FIRST_FLG_FIFO_DATA1_MBE_BP, AR_NIC_DLA_ERR_FIRST_FLG_FIFO_DATA1_MBE_MASK },
    { "FIFO_DATA1_SBE", AR_NIC_DLA_ERR_FIRST_FLG_FIFO_DATA1_SBE_BP, AR_NIC_DLA_ERR_FIRST_FLG_FIFO_DATA1_SBE_MASK },
    { "FIFO_DATA0_MBE", AR_NIC_DLA_ERR_FIRST_FLG_FIFO_DATA0_MBE_BP, AR_NIC_DLA_ERR_FIRST_FLG_FIFO_DATA0_MBE_MASK },
    { "FIFO_DATA0_SBE", AR_NIC_DLA_ERR_FIRST_FLG_FIFO_DATA0_SBE_BP, AR_NIC_DLA_ERR_FIRST_FLG_FIFO_DATA0_SBE_MASK },
    { "ALLOC_BOTH_ERR", AR_NIC_DLA_ERR_FIRST_FLG_ALLOC_BOTH_ERR_BP, AR_NIC_DLA_ERR_FIRST_FLG_ALLOC_BOTH_ERR_MASK },
    { "FMA_PKT_ERR", AR_NIC_DLA_ERR_FIRST_FLG_FMA_PKT_ERR_BP, AR_NIC_DLA_ERR_FIRST_FLG_FMA_PKT_ERR_MASK },
    { "MARKER_RAM_MBE", AR_NIC_DLA_ERR_FIRST_FLG_MARKER_RAM_MBE_BP, AR_NIC_DLA_ERR_FIRST_FLG_MARKER_RAM_MBE_MASK },
    { "MARKER_RAM_SBE", AR_NIC_DLA_ERR_FIRST_FLG_MARKER_RAM_SBE_BP, AR_NIC_DLA_ERR_FIRST_FLG_MARKER_RAM_SBE_MASK },
    { "ALLOC_RAM_MBE", AR_NIC_DLA_ERR_FIRST_FLG_ALLOC_RAM_MBE_BP, AR_NIC_DLA_ERR_FIRST_FLG_ALLOC_RAM_MBE_MASK },
    { "ALLOC_RAM_SBE", AR_NIC_DLA_ERR_FIRST_FLG_ALLOC_RAM_SBE_BP, AR_NIC_DLA_ERR_FIRST_FLG_ALLOC_RAM_SBE_MASK },
    { "FIFO_OVERFLOW", AR_NIC_DLA_ERR_FIRST_FLG_FIFO_OVERFLOW_BP, AR_NIC_DLA_ERR_FIRST_FLG_FIFO_OVERFLOW_MASK },
    { "HDR_PERR", AR_NIC_DLA_ERR_FIRST_FLG_HDR_PERR_BP, AR_NIC_DLA_ERR_FIRST_FLG_HDR_PERR_MASK },
    { "DATA1_MBE", AR_NIC_DLA_ERR_FIRST_FLG_DATA1_MBE_BP, AR_NIC_DLA_ERR_FIRST_FLG_DATA1_MBE_MASK },
    { "DATA1_SBE", AR_NIC_DLA_ERR_FIRST_FLG_DATA1_SBE_BP, AR_NIC_DLA_ERR_FIRST_FLG_DATA1_SBE_MASK },
    { "DATA0_MBE", AR_NIC_DLA_ERR_FIRST_FLG_DATA0_MBE_BP, AR_NIC_DLA_ERR_FIRST_FLG_DATA0_MBE_MASK },
    { "DATA0_SBE", AR_NIC_DLA_ERR_FIRST_FLG_DATA0_SBE_BP, AR_NIC_DLA_ERR_FIRST_FLG_DATA0_SBE_MASK },
    { "FIFO_HDR_MBE", AR_NIC_DLA_ERR_FIRST_FLG_FIFO_HDR_MBE_BP, AR_NIC_DLA_ERR_FIRST_FLG_FIFO_HDR_MBE_MASK },
    { "FIFO_HDR_SBE", AR_NIC_DLA_ERR_FIRST_FLG_FIFO_HDR_SBE_BP, AR_NIC_DLA_ERR_FIRST_FLG_FIFO_HDR_SBE_MASK },
    { "DIAG_ONLY", AR_NIC_DLA_ERR_FIRST_FLG_DIAG_ONLY_BP, AR_NIC_DLA_ERR_FIRST_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_err_info_pkt_detail[] = {
    { "PERR", AR_NIC_DLA_ERR_INFO_PKT_PERR_BP, AR_NIC_DLA_ERR_INFO_PKT_PERR_MASK },
    { "DATA1_MBE_SYND", AR_NIC_DLA_ERR_INFO_PKT_DATA1_MBE_SYND_BP, AR_NIC_DLA_ERR_INFO_PKT_DATA1_MBE_SYND_MASK },
    { "DATA1_SBE_SYND", AR_NIC_DLA_ERR_INFO_PKT_DATA1_SBE_SYND_BP, AR_NIC_DLA_ERR_INFO_PKT_DATA1_SBE_SYND_MASK },
    { "DATA0_MBE_SYND", AR_NIC_DLA_ERR_INFO_PKT_DATA0_MBE_SYND_BP, AR_NIC_DLA_ERR_INFO_PKT_DATA0_MBE_SYND_MASK },
    { "DATA0_SBE_SYND", AR_NIC_DLA_ERR_INFO_PKT_DATA0_SBE_SYND_BP, AR_NIC_DLA_ERR_INFO_PKT_DATA0_SBE_SYND_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_err_info_ram_detail[] = {
    { "MARKER_RAM_MBE_SYND", AR_NIC_DLA_ERR_INFO_RAM_MARKER_RAM_MBE_SYND_BP, AR_NIC_DLA_ERR_INFO_RAM_MARKER_RAM_MBE_SYND_MASK },
    { "MARKER_RAM_SBE_SYND", AR_NIC_DLA_ERR_INFO_RAM_MARKER_RAM_SBE_SYND_BP, AR_NIC_DLA_ERR_INFO_RAM_MARKER_RAM_SBE_SYND_MASK },
    { "ALLOC_RAM_MBE_SYND", AR_NIC_DLA_ERR_INFO_RAM_ALLOC_RAM_MBE_SYND_BP, AR_NIC_DLA_ERR_INFO_RAM_ALLOC_RAM_MBE_SYND_MASK },
    { "ALLOC_RAM_SBE_SYND", AR_NIC_DLA_ERR_INFO_RAM_ALLOC_RAM_SBE_SYND_BP, AR_NIC_DLA_ERR_INFO_RAM_ALLOC_RAM_SBE_SYND_MASK },
    { "FIFO_MBE_SYND", AR_NIC_DLA_ERR_INFO_RAM_FIFO_MBE_SYND_BP, AR_NIC_DLA_ERR_INFO_RAM_FIFO_MBE_SYND_MASK },
    { "FIFO_SBE_SYND", AR_NIC_DLA_ERR_INFO_RAM_FIFO_SBE_SYND_BP, AR_NIC_DLA_ERR_INFO_RAM_FIFO_SBE_SYND_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_dbg_errinj_ram_detail[] = {
    { "ADDRESS", AR_NIC_DLA_DBG_ERRINJ_RAM_ADDRESS_BP, AR_NIC_DLA_DBG_ERRINJ_RAM_ADDRESS_MASK },
    { "CHECKBITS_UP", AR_NIC_DLA_DBG_ERRINJ_RAM_CHECKBITS_UP_BP, AR_NIC_DLA_DBG_ERRINJ_RAM_CHECKBITS_UP_MASK },
    { "CHECKBITS_LO", AR_NIC_DLA_DBG_ERRINJ_RAM_CHECKBITS_LO_BP, AR_NIC_DLA_DBG_ERRINJ_RAM_CHECKBITS_LO_MASK },
    { "FIFO_DATA", AR_NIC_DLA_DBG_ERRINJ_RAM_FIFO_DATA_BP, AR_NIC_DLA_DBG_ERRINJ_RAM_FIFO_DATA_MASK },
    { "MARKER_RAM", AR_NIC_DLA_DBG_ERRINJ_RAM_MARKER_RAM_BP, AR_NIC_DLA_DBG_ERRINJ_RAM_MARKER_RAM_MASK },
    { "ALLOC_RAM", AR_NIC_DLA_DBG_ERRINJ_RAM_ALLOC_RAM_BP, AR_NIC_DLA_DBG_ERRINJ_RAM_ALLOC_RAM_MASK },
    { "FIFO_HDR", AR_NIC_DLA_DBG_ERRINJ_RAM_FIFO_HDR_BP, AR_NIC_DLA_DBG_ERRINJ_RAM_FIFO_HDR_MASK },
    { "TRIGGERED", AR_NIC_DLA_DBG_ERRINJ_RAM_TRIGGERED_BP, AR_NIC_DLA_DBG_ERRINJ_RAM_TRIGGERED_MASK },
    { "MODE", AR_NIC_DLA_DBG_ERRINJ_RAM_MODE_BP, AR_NIC_DLA_DBG_ERRINJ_RAM_MODE_MASK },
    { "ENABLE", AR_NIC_DLA_DBG_ERRINJ_RAM_ENABLE_BP, AR_NIC_DLA_DBG_ERRINJ_RAM_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_dbg_errinj_pkt_detail[] = {
    { "CHECKBITS_UP", AR_NIC_DLA_DBG_ERRINJ_PKT_CHECKBITS_UP_BP, AR_NIC_DLA_DBG_ERRINJ_PKT_CHECKBITS_UP_MASK },
    { "CHECKBITS_LO", AR_NIC_DLA_DBG_ERRINJ_PKT_CHECKBITS_LO_BP, AR_NIC_DLA_DBG_ERRINJ_PKT_CHECKBITS_LO_MASK },
    { "PARITY", AR_NIC_DLA_DBG_ERRINJ_PKT_PARITY_BP, AR_NIC_DLA_DBG_ERRINJ_PKT_PARITY_MASK },
    { "TAIL", AR_NIC_DLA_DBG_ERRINJ_PKT_TAIL_BP, AR_NIC_DLA_DBG_ERRINJ_PKT_TAIL_MASK },
    { "COUNT", AR_NIC_DLA_DBG_ERRINJ_PKT_COUNT_BP, AR_NIC_DLA_DBG_ERRINJ_PKT_COUNT_MASK },
    { "TRIGGERED", AR_NIC_DLA_DBG_ERRINJ_PKT_TRIGGERED_BP, AR_NIC_DLA_DBG_ERRINJ_PKT_TRIGGERED_MASK },
    { "MODE", AR_NIC_DLA_DBG_ERRINJ_PKT_MODE_BP, AR_NIC_DLA_DBG_ERRINJ_PKT_MODE_MASK },
    { "ENABLE", AR_NIC_DLA_DBG_ERRINJ_PKT_ENABLE_BP, AR_NIC_DLA_DBG_ERRINJ_PKT_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_cfg_detail[] = {
    { "MRKR_BYPASS", AR_NIC_DLA_CFG_MRKR_BYPASS_BP, AR_NIC_DLA_CFG_MRKR_BYPASS_MASK },
    { "BYPASS", AR_NIC_DLA_CFG_BYPASS_BP, AR_NIC_DLA_CFG_BYPASS_MASK },
    { "PARB_COUNT", AR_NIC_DLA_CFG_PARB_COUNT_BP, AR_NIC_DLA_CFG_PARB_COUNT_MASK },
    { "CQ_COUNT", AR_NIC_DLA_CFG_CQ_COUNT_BP, AR_NIC_DLA_CFG_CQ_COUNT_MASK },
    { "TARB_COUNT", AR_NIC_DLA_CFG_TARB_COUNT_BP, AR_NIC_DLA_CFG_TARB_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_cfg_alloc_status_adr_detail[] = {
    { "TPH", AR_NIC_DLA_CFG_ALLOC_STATUS_ADR_TPH_BP, AR_NIC_DLA_CFG_ALLOC_STATUS_ADR_TPH_MASK },
    { "TC", AR_NIC_DLA_CFG_ALLOC_STATUS_ADR_TC_BP, AR_NIC_DLA_CFG_ALLOC_STATUS_ADR_TC_MASK },
    { "STAT_ADDR", AR_NIC_DLA_CFG_ALLOC_STATUS_ADR_STAT_ADDR_BP, AR_NIC_DLA_CFG_ALLOC_STATUS_ADR_STAT_ADDR_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_cfg_alloc_status_trig_detail[] = {
    { "COUNT", AR_NIC_DLA_CFG_ALLOC_STATUS_TRIG_COUNT_BP, AR_NIC_DLA_CFG_ALLOC_STATUS_TRIG_COUNT_MASK },
    { "THRESHOLD", AR_NIC_DLA_CFG_ALLOC_STATUS_TRIG_THRESHOLD_BP, AR_NIC_DLA_CFG_ALLOC_STATUS_TRIG_THRESHOLD_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_sts_alloc_cnt_detail[] = {
    { "ALLOC_COUNT", AR_NIC_DLA_STS_ALLOC_CNT_ALLOC_COUNT_BP, AR_NIC_DLA_STS_ALLOC_CNT_ALLOC_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_sts_cqe_merge_cnt_detail[] = {
    { "MARKER", AR_NIC_DLA_STS_CQE_MERGE_CNT_MARKER_BP, AR_NIC_DLA_STS_CQE_MERGE_CNT_MARKER_MASK },
    { "ALLOC", AR_NIC_DLA_STS_CQE_MERGE_CNT_ALLOC_BP, AR_NIC_DLA_STS_CQE_MERGE_CNT_ALLOC_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_err_info_fma_pkt_detail[] = {
    { "SSID_CMD", AR_NIC_DLA_ERR_INFO_FMA_PKT_SSID_CMD_BP, AR_NIC_DLA_ERR_INFO_FMA_PKT_SSID_CMD_MASK },
    { "PTAG", AR_NIC_DLA_ERR_INFO_FMA_PKT_PTAG_BP, AR_NIC_DLA_ERR_INFO_FMA_PKT_PTAG_MASK },
    { "SSID_CH", AR_NIC_DLA_ERR_INFO_FMA_PKT_SSID_CH_BP, AR_NIC_DLA_ERR_INFO_FMA_PKT_SSID_CH_MASK },
    { "LSTATUS", AR_NIC_DLA_ERR_INFO_FMA_PKT_LSTATUS_BP, AR_NIC_DLA_ERR_INFO_FMA_PKT_LSTATUS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_clear_detail[] = {
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_dla_err_info_ram1_detail[] = {
    { "DATA1_MBE_SYND", AR_NIC_DLA_ERR_INFO_RAM1_DATA1_MBE_SYND_BP, AR_NIC_DLA_ERR_INFO_RAM1_DATA1_MBE_SYND_MASK },
    { "DATA1_SBE_SYND", AR_NIC_DLA_ERR_INFO_RAM1_DATA1_SBE_SYND_BP, AR_NIC_DLA_ERR_INFO_RAM1_DATA1_SBE_SYND_MASK },
    { "DATA0_MBE_SYND", AR_NIC_DLA_ERR_INFO_RAM1_DATA0_MBE_SYND_BP, AR_NIC_DLA_ERR_INFO_RAM1_DATA0_MBE_SYND_MASK },
    { "DATA0_SBE_SYND", AR_NIC_DLA_ERR_INFO_RAM1_DATA0_SBE_SYND_BP, AR_NIC_DLA_ERR_INFO_RAM1_DATA0_SBE_SYND_MASK },
    { NULL, 0, 0 }
};

/*
 *  AR DLA MMR DECLARATIONS
 */
static const generic_mmr_t _ar_nic_dla_mmr_ring_0_hi_dla = {
    "AR_NIC_DLA_MMR_RING_0_HI_DLA", AR_NIC_DLA_MMR_RING_0_HI_DLA, 8, 1, _ar_nic_dla_mmr_ring_0_hi_dla_detail
};
static const generic_mmr_t _ar_nic_dla_mmr_ring_0_mid_dla = {
    "AR_NIC_DLA_MMR_RING_0_MID_DLA", AR_NIC_DLA_MMR_RING_0_MID_DLA, 8, 1, _ar_nic_dla_mmr_ring_0_mid_dla_detail
};
static const generic_mmr_t _ar_nic_dla_mmr_ring_0_lo_dla = {
    "AR_NIC_DLA_MMR_RING_0_LO_DLA", AR_NIC_DLA_MMR_RING_0_LO_DLA, 8, 1, _ar_nic_dla_mmr_ring_0_lo_dla_detail
};
static const generic_mmr_t _ar_nic_dla_err_flg_1_hi_dla = {
    "AR_NIC_DLA_ERR_FLG_1_HI_DLA", AR_NIC_DLA_ERR_FLG_1_HI_DLA, 8, 1, _ar_nic_dla_err_flg_1_hi_dla_detail
};
static const generic_mmr_t _ar_nic_dla_err_flg_1_mid_dla = {
    "AR_NIC_DLA_ERR_FLG_1_MID_DLA", AR_NIC_DLA_ERR_FLG_1_MID_DLA, 8, 1, _ar_nic_dla_err_flg_1_mid_dla_detail
};
static const generic_mmr_t _ar_nic_dla_err_flg_1_lo_dla = {
    "AR_NIC_DLA_ERR_FLG_1_LO_DLA", AR_NIC_DLA_ERR_FLG_1_LO_DLA, 8, 1, _ar_nic_dla_err_flg_1_lo_dla_detail
};
static const generic_mmr_t _ar_nic_dla_fma_flit_sg_5_2_hi_dla = {
    "AR_NIC_DLA_FMA_FLIT_SG_5_2_HI_DLA", AR_NIC_DLA_FMA_FLIT_SG_5_2_HI_DLA, 8, 1, _ar_nic_dla_fma_flit_sg_5_2_hi_dla_detail
};
static const generic_mmr_t _ar_nic_dla_fma_flit_sg_5_2_mid_dla = {
    "AR_NIC_DLA_FMA_FLIT_SG_5_2_MID_DLA", AR_NIC_DLA_FMA_FLIT_SG_5_2_MID_DLA, 8, 1, _ar_nic_dla_fma_flit_sg_5_2_mid_dla_detail
};
static const generic_mmr_t _ar_nic_dla_fma_flit_sg_5_2_lo_dla = {
    "AR_NIC_DLA_FMA_FLIT_SG_5_2_LO_DLA", AR_NIC_DLA_FMA_FLIT_SG_5_2_LO_DLA, 8, 1, _ar_nic_dla_fma_flit_sg_5_2_lo_dla_detail
};
static const generic_mmr_t _ar_nic_dla_dla_op_and_result_sg_5_3_hi_dla = {
    "AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_HI_DLA", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_HI_DLA, 8, 1, _ar_nic_dla_dla_op_and_result_sg_5_3_hi_dla_detail
};
static const generic_mmr_t _ar_nic_dla_dla_op_and_result_sg_5_3_mid_dla = {
    "AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_MID_DLA", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_MID_DLA, 8, 1, _ar_nic_dla_dla_op_and_result_sg_5_3_mid_dla_detail
};
static const generic_mmr_t _ar_nic_dla_dla_op_and_result_sg_5_3_lo_dla = {
    "AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA", AR_NIC_DLA_DLA_OP_AND_RESULT_SG_5_3_LO_DLA, 8, 1, _ar_nic_dla_dla_op_and_result_sg_5_3_lo_dla_detail
};
static const generic_mmr_t _ar_nic_dla_dla_packet_to_tarb_4_hi_dla = {
    "AR_NIC_DLA_DLA_PACKET_TO_TARB_4_HI_DLA", AR_NIC_DLA_DLA_PACKET_TO_TARB_4_HI_DLA, 8, 1, _ar_nic_dla_dla_packet_to_tarb_4_hi_dla_detail
};
static const generic_mmr_t _ar_nic_dla_dla_packet_to_tarb_4_mid_dla = {
    "AR_NIC_DLA_DLA_PACKET_TO_TARB_4_MID_DLA", AR_NIC_DLA_DLA_PACKET_TO_TARB_4_MID_DLA, 8, 1, _ar_nic_dla_dla_packet_to_tarb_4_mid_dla_detail
};
static const generic_mmr_t _ar_nic_dla_dla_packet_to_tarb_4_lo_dla = {
    "AR_NIC_DLA_DLA_PACKET_TO_TARB_4_LO_DLA", AR_NIC_DLA_DLA_PACKET_TO_TARB_4_LO_DLA, 8, 1, _ar_nic_dla_dla_packet_to_tarb_4_lo_dla_detail
};
static const generic_mmr_t _ar_nic_dla_cfg_max = {
    "AR_NIC_DLA_CFG_MAX", AR_NIC_DLA_CFG_MAX, 8, 1, _ar_nic_dla_cfg_max_detail
};
static const generic_mmr_t _ar_nic_dla_cfg_max_lo_cd = {
    "AR_NIC_DLA_CFG_MAX_LO_CD", AR_NIC_DLA_CFG_MAX_LO_CD, 8, 1, _ar_nic_dla_cfg_max_lo_cd_detail
};
static const generic_mmr_t _ar_nic_dla_cfg_max_hi_cd = {
    "AR_NIC_DLA_CFG_MAX_HI_CD", AR_NIC_DLA_CFG_MAX_HI_CD, 8, 1, _ar_nic_dla_cfg_max_hi_cd_detail
};
static const generic_mmr_t _ar_nic_dla_cfg_max_pr = {
    "AR_NIC_DLA_CFG_MAX_PR", AR_NIC_DLA_CFG_MAX_PR, 8, 1, _ar_nic_dla_cfg_max_pr_detail
};
static const generic_mmr_t _ar_nic_dla_cfg_max_lo_cd_pr = {
    "AR_NIC_DLA_CFG_MAX_LO_CD_PR", AR_NIC_DLA_CFG_MAX_LO_CD_PR, 8, 1, _ar_nic_dla_cfg_max_lo_cd_pr_detail
};
static const generic_mmr_t _ar_nic_dla_cfg_max_lo_hi_cd = {
    "AR_NIC_DLA_CFG_MAX_LO_HI_CD", AR_NIC_DLA_CFG_MAX_LO_HI_CD, 8, 1, _ar_nic_dla_cfg_max_lo_hi_cd_detail
};
static const generic_mmr_t _ar_nic_dla_cfg_max_hi_cd_pr = {
    "AR_NIC_DLA_CFG_MAX_HI_CD_PR", AR_NIC_DLA_CFG_MAX_HI_CD_PR, 8, 1, _ar_nic_dla_cfg_max_hi_cd_pr_detail
};
static const generic_mmr_t _ar_nic_dla_cfg_max_cd_alloc = {
    "AR_NIC_DLA_CFG_MAX_CD_ALLOC", AR_NIC_DLA_CFG_MAX_CD_ALLOC, 8, 1, _ar_nic_dla_cfg_max_cd_alloc_detail
};
static const generic_mmr_t _ar_nic_dla_cfg_max_pr_alloc = {
    "AR_NIC_DLA_CFG_MAX_PR_ALLOC", AR_NIC_DLA_CFG_MAX_PR_ALLOC, 8, 1, _ar_nic_dla_cfg_max_pr_alloc_detail
};
static const generic_mmr_t _ar_nic_dla_sts_consumed = {
    "AR_NIC_DLA_STS_CONSUMED", AR_NIC_DLA_STS_CONSUMED, 8, 1, _ar_nic_dla_sts_consumed_detail
};
static const generic_mmr_t _ar_nic_dla_sts_consumed_lo_cd = {
    "AR_NIC_DLA_STS_CONSUMED_LO_CD", AR_NIC_DLA_STS_CONSUMED_LO_CD, 8, 1, _ar_nic_dla_sts_consumed_lo_cd_detail
};
static const generic_mmr_t _ar_nic_dla_sts_consumed_hi_cd = {
    "AR_NIC_DLA_STS_CONSUMED_HI_CD", AR_NIC_DLA_STS_CONSUMED_HI_CD, 8, 1, _ar_nic_dla_sts_consumed_hi_cd_detail
};
static const generic_mmr_t _ar_nic_dla_sts_consumed_pr = {
    "AR_NIC_DLA_STS_CONSUMED_PR", AR_NIC_DLA_STS_CONSUMED_PR, 8, 1, _ar_nic_dla_sts_consumed_pr_detail
};
static const generic_mmr_t _ar_nic_dla_sts_resvd_lo_cd = {
    "AR_NIC_DLA_STS_RESVD_LO_CD", AR_NIC_DLA_STS_RESVD_LO_CD, 8, 1, _ar_nic_dla_sts_resvd_lo_cd_detail
};
static const generic_mmr_t _ar_nic_dla_sts_resvd_hi_cd = {
    "AR_NIC_DLA_STS_RESVD_HI_CD", AR_NIC_DLA_STS_RESVD_HI_CD, 8, 1, _ar_nic_dla_sts_resvd_hi_cd_detail
};
static const generic_mmr_t _ar_nic_dla_sts_resvd_pr = {
    "AR_NIC_DLA_STS_RESVD_PR", AR_NIC_DLA_STS_RESVD_PR, 8, 1, _ar_nic_dla_sts_resvd_pr_detail
};
static const generic_mmr_t _ar_nic_dla_err_flg = {
    "AR_NIC_DLA_ERR_FLG", AR_NIC_DLA_ERR_FLG, 8, 1, _ar_nic_dla_err_flg_detail
};
static const generic_mmr_t _ar_nic_dla_err_clr = {
    "AR_NIC_DLA_ERR_CLR", AR_NIC_DLA_ERR_CLR, 8, 1, _ar_nic_dla_err_clr_detail
};
static const generic_mmr_t _ar_nic_dla_err_hss_msk = {
    "AR_NIC_DLA_ERR_HSS_MSK", AR_NIC_DLA_ERR_HSS_MSK, 8, 1, _ar_nic_dla_err_hss_msk_detail
};
static const generic_mmr_t _ar_nic_dla_err_os_msk = {
    "AR_NIC_DLA_ERR_OS_MSK", AR_NIC_DLA_ERR_OS_MSK, 8, 1, _ar_nic_dla_err_os_msk_detail
};
static const generic_mmr_t _ar_nic_dla_err_first_flg = {
    "AR_NIC_DLA_ERR_FIRST_FLG", AR_NIC_DLA_ERR_FIRST_FLG, 8, 1, _ar_nic_dla_err_first_flg_detail
};
static const generic_mmr_t _ar_nic_dla_err_info_pkt = {
    "AR_NIC_DLA_ERR_INFO_PKT", AR_NIC_DLA_ERR_INFO_PKT, 8, 1, _ar_nic_dla_err_info_pkt_detail
};
static const generic_mmr_t _ar_nic_dla_err_info_ram = {
    "AR_NIC_DLA_ERR_INFO_RAM", AR_NIC_DLA_ERR_INFO_RAM, 8, 1, _ar_nic_dla_err_info_ram_detail
};
static const generic_mmr_t _ar_nic_dla_dbg_errinj_ram = {
    "AR_NIC_DLA_DBG_ERRINJ_RAM", AR_NIC_DLA_DBG_ERRINJ_RAM, 8, 1, _ar_nic_dla_dbg_errinj_ram_detail
};
static const generic_mmr_t _ar_nic_dla_dbg_errinj_pkt = {
    "AR_NIC_DLA_DBG_ERRINJ_PKT", AR_NIC_DLA_DBG_ERRINJ_PKT, 8, 1, _ar_nic_dla_dbg_errinj_pkt_detail
};
static const generic_mmr_t _ar_nic_dla_cfg = {
    "AR_NIC_DLA_CFG", AR_NIC_DLA_CFG, 8, 1, _ar_nic_dla_cfg_detail
};
static const generic_mmr_t _ar_nic_dla_cfg_alloc_status_adr = {
    "AR_NIC_DLA_CFG_ALLOC_STATUS_ADR", AR_NIC_DLA_CFG_ALLOC_STATUS_ADR, 8, 1, _ar_nic_dla_cfg_alloc_status_adr_detail
};
static const generic_mmr_t _ar_nic_dla_cfg_alloc_status_trig = {
    "AR_NIC_DLA_CFG_ALLOC_STATUS_TRIG", AR_NIC_DLA_CFG_ALLOC_STATUS_TRIG, 8, 1, _ar_nic_dla_cfg_alloc_status_trig_detail
};
static const generic_mmr_t _ar_nic_dla_sts_alloc_cnt = {
    "AR_NIC_DLA_STS_ALLOC_CNT", AR_NIC_DLA_STS_ALLOC_CNT, 8, 1, _ar_nic_dla_sts_alloc_cnt_detail
};
static const generic_mmr_t _ar_nic_dla_sts_cqe_merge_cnt = {
    "AR_NIC_DLA_STS_CQE_MERGE_CNT", AR_NIC_DLA_STS_CQE_MERGE_CNT, 8, 1, _ar_nic_dla_sts_cqe_merge_cnt_detail
};
static const generic_mmr_t _ar_nic_dla_err_info_fma_pkt = {
    "AR_NIC_DLA_ERR_INFO_FMA_PKT", AR_NIC_DLA_ERR_INFO_FMA_PKT, 8, 1, _ar_nic_dla_err_info_fma_pkt_detail
};
static const generic_mmr_t _ar_nic_dla_clear = {
    "AR_NIC_DLA_CLEAR", AR_NIC_DLA_CLEAR, 8, 1, _ar_nic_dla_clear_detail
};
static const generic_mmr_t _ar_nic_dla_err_info_ram1 = {
    "AR_NIC_DLA_ERR_INFO_RAM1", AR_NIC_DLA_ERR_INFO_RAM1, 8, 1, _ar_nic_dla_err_info_ram1_detail
};

/*
 *  INSTALL AR DLA MMRS
 */
static const generic_mmr_t* _ar_dla_mmrs[] _unused = {
    &_ar_nic_dla_mmr_ring_0_hi_dla,
    &_ar_nic_dla_mmr_ring_0_mid_dla,
    &_ar_nic_dla_mmr_ring_0_lo_dla,
    &_ar_nic_dla_err_flg_1_hi_dla,
    &_ar_nic_dla_err_flg_1_mid_dla,
    &_ar_nic_dla_err_flg_1_lo_dla,
    &_ar_nic_dla_fma_flit_sg_5_2_hi_dla,
    &_ar_nic_dla_fma_flit_sg_5_2_mid_dla,
    &_ar_nic_dla_fma_flit_sg_5_2_lo_dla,
    &_ar_nic_dla_dla_op_and_result_sg_5_3_hi_dla,
    &_ar_nic_dla_dla_op_and_result_sg_5_3_mid_dla,
    &_ar_nic_dla_dla_op_and_result_sg_5_3_lo_dla,
    &_ar_nic_dla_dla_packet_to_tarb_4_hi_dla,
    &_ar_nic_dla_dla_packet_to_tarb_4_mid_dla,
    &_ar_nic_dla_dla_packet_to_tarb_4_lo_dla,
    &_ar_nic_dla_cfg_max,
    &_ar_nic_dla_cfg_max_lo_cd,
    &_ar_nic_dla_cfg_max_hi_cd,
    &_ar_nic_dla_cfg_max_pr,
    &_ar_nic_dla_cfg_max_lo_cd_pr,
    &_ar_nic_dla_cfg_max_lo_hi_cd,
    &_ar_nic_dla_cfg_max_hi_cd_pr,
    &_ar_nic_dla_cfg_max_cd_alloc,
    &_ar_nic_dla_cfg_max_pr_alloc,
    &_ar_nic_dla_sts_consumed,
    &_ar_nic_dla_sts_consumed_lo_cd,
    &_ar_nic_dla_sts_consumed_hi_cd,
    &_ar_nic_dla_sts_consumed_pr,
    &_ar_nic_dla_sts_resvd_lo_cd,
    &_ar_nic_dla_sts_resvd_hi_cd,
    &_ar_nic_dla_sts_resvd_pr,
    &_ar_nic_dla_err_flg,
    &_ar_nic_dla_err_clr,
    &_ar_nic_dla_err_hss_msk,
    &_ar_nic_dla_err_os_msk,
    &_ar_nic_dla_err_first_flg,
    &_ar_nic_dla_err_info_pkt,
    &_ar_nic_dla_err_info_ram,
    &_ar_nic_dla_dbg_errinj_ram,
    &_ar_nic_dla_dbg_errinj_pkt,
    &_ar_nic_dla_cfg,
    &_ar_nic_dla_cfg_alloc_status_adr,
    &_ar_nic_dla_cfg_alloc_status_trig,
    &_ar_nic_dla_sts_alloc_cnt,
    &_ar_nic_dla_sts_cqe_merge_cnt,
    &_ar_nic_dla_err_info_fma_pkt,
    &_ar_nic_dla_clear,
    &_ar_nic_dla_err_info_ram1,
    NULL
};

#endif
