/******************************************************************************
 * COPYRIGHT CRAY INC. ar_fma_descs_h.h
 * FILE: ar_fma_descs_h.h
 * Created by v2h.c on Wed Oct  8 14:38:59 2014
 ******************************************************************************/

#ifndef _AR_FMA_DESCS_H_H_
#define _AR_FMA_DESCS_H_H_

#ifndef _GENERIC_DESCD_T_
#define _GENERIC_DESCD_T_
typedef struct {
	char* _name;		/* Field's name */
	uint32_t _bpos;		/* Field's bit postion in quad word */
	uint64_t _mask;		/* Field's bit mask in quad word */
	int _index;		/* Field's quad word index */
} generic_descd_t;
#endif

#ifndef _GENERIC_DESC_T_
#define _GENERIC_DESC_T_
typedef struct {
	char* _name;		/* Descriptor name */
	uint64_t _addr;		/* Descriptor address */
	int _size;		/* Size in bytes of Descriptor */
	int _depth;		/* Number of Descriptor instances */
	const generic_descd_t *_info;	/* Descriptor detail */
} generic_desc_t;
#endif

/*
 *  AR FMA DESCRIPTOR DETAIL DECLARATIONS
 */
static const generic_descd_t _ar_nic_fma_cfg_desc_sfma_detail[] = {
    { "RESERVED_1727_1713", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_1727_1713_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_1727_1713_MASK, 26 },
    { "DLA_MARKER_DEALLOC", AR_NIC_FMA_CFG_DESC_SFMA_DLA_MARKER_DEALLOC_BP, AR_NIC_FMA_CFG_DESC_SFMA_DLA_MARKER_DEALLOC_MASK, 26 },
    { "RESERVED_1711_1696", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_1711_1696_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_1711_1696_MASK, 26 },
    { "MARKER_ID", AR_NIC_FMA_CFG_DESC_SFMA_MARKER_ID_BP, AR_NIC_FMA_CFG_DESC_SFMA_MARKER_ID_MASK, 26 },
    { "FMA_LAUNCH_OPERAND", AR_NIC_FMA_CFG_DESC_SFMA_FMA_LAUNCH_OPERAND_BP, AR_NIC_FMA_CFG_DESC_SFMA_FMA_LAUNCH_OPERAND_MASK, 25 },
    { "RESERVED_1599_1595", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_1599_1595_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_1599_1595_MASK, 24 },
    { "FMA_LAUNCH_GET", AR_NIC_FMA_CFG_DESC_SFMA_FMA_LAUNCH_GET_BP, AR_NIC_FMA_CFG_DESC_SFMA_FMA_LAUNCH_GET_MASK, 24 },
    { "FMA_LAUNCH_GLOBAL_OFFSET", AR_NIC_FMA_CFG_DESC_SFMA_FMA_LAUNCH_GLOBAL_OFFSET_BP, AR_NIC_FMA_CFG_DESC_SFMA_FMA_LAUNCH_GLOBAL_OFFSET_MASK, 24 },
    { "RESERVED_1103", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_1103_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_1103_MASK, 17 },
    { "DLA_ALLOC_CD", AR_NIC_FMA_CFG_DESC_SFMA_DLA_ALLOC_CD_BP, AR_NIC_FMA_CFG_DESC_SFMA_DLA_ALLOC_CD_MASK, 17 },
    { "DLA_ALLOC_PR", AR_NIC_FMA_CFG_DESC_SFMA_DLA_ALLOC_PR_BP, AR_NIC_FMA_CFG_DESC_SFMA_DLA_ALLOC_PR_MASK, 17 },
    { "DLA_HIGH_PRIORITY", AR_NIC_FMA_CFG_DESC_SFMA_DLA_HIGH_PRIORITY_BP, AR_NIC_FMA_CFG_DESC_SFMA_DLA_HIGH_PRIORITY_MASK, 17 },
    { "RESERVED_1099", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_1099_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_1099_MASK, 17 },
    { "DLA_CQH", AR_NIC_FMA_CFG_DESC_SFMA_DLA_CQH_BP, AR_NIC_FMA_CFG_DESC_SFMA_DLA_CQH_MASK, 17 },
    { "STATUS_DONE", AR_NIC_FMA_CFG_DESC_SFMA_STATUS_DONE_BP, AR_NIC_FMA_CFG_DESC_SFMA_STATUS_DONE_MASK, 16 },
    { "STATUS_TRANS_ACTIVE", AR_NIC_FMA_CFG_DESC_SFMA_STATUS_TRANS_ACTIVE_BP, AR_NIC_FMA_CFG_DESC_SFMA_STATUS_TRANS_ACTIVE_MASK, 16 },
    { "STATUS_LAUNCH1", AR_NIC_FMA_CFG_DESC_SFMA_STATUS_LAUNCH1_BP, AR_NIC_FMA_CFG_DESC_SFMA_STATUS_LAUNCH1_MASK, 16 },
    { "STATUS_LAUNCH0", AR_NIC_FMA_CFG_DESC_SFMA_STATUS_LAUNCH0_BP, AR_NIC_FMA_CFG_DESC_SFMA_STATUS_LAUNCH0_MASK, 16 },
    { "STATUS_PRIV_ERR", AR_NIC_FMA_CFG_DESC_SFMA_STATUS_PRIV_ERR_BP, AR_NIC_FMA_CFG_DESC_SFMA_STATUS_PRIV_ERR_MASK, 16 },
    { "STATUS_HW_ERR", AR_NIC_FMA_CFG_DESC_SFMA_STATUS_HW_ERR_BP, AR_NIC_FMA_CFG_DESC_SFMA_STATUS_HW_ERR_MASK, 16 },
    { "STATUS_SW_ERR", AR_NIC_FMA_CFG_DESC_SFMA_STATUS_SW_ERR_BP, AR_NIC_FMA_CFG_DESC_SFMA_STATUS_SW_ERR_MASK, 16 },
    { "STATUS_NPES_ERR", AR_NIC_FMA_CFG_DESC_SFMA_STATUS_NPES_ERR_BP, AR_NIC_FMA_CFG_DESC_SFMA_STATUS_NPES_ERR_MASK, 16 },
    { "STATUS_ALLOC_SEQID_ERR", AR_NIC_FMA_CFG_DESC_SFMA_STATUS_ALLOC_SEQID_ERR_BP, AR_NIC_FMA_CFG_DESC_SFMA_STATUS_ALLOC_SEQID_ERR_MASK, 16 },
    { "STATUS_SSIDS_IN_USE", AR_NIC_FMA_CFG_DESC_SFMA_STATUS_SSIDS_IN_USE_BP, AR_NIC_FMA_CFG_DESC_SFMA_STATUS_SSIDS_IN_USE_MASK, 16 },
    { "STATUS_RC", AR_NIC_FMA_CFG_DESC_SFMA_STATUS_RC_BP, AR_NIC_FMA_CFG_DESC_SFMA_STATUS_RC_MASK, 16 },
    { "STATUS_WC", AR_NIC_FMA_CFG_DESC_SFMA_STATUS_WC_BP, AR_NIC_FMA_CFG_DESC_SFMA_STATUS_WC_MASK, 16 },
    { "RESERVED_1023_960", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_1023_960_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_1023_960_MASK, 15 },
    { "RESERVED_959_896", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_959_896_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_959_896_MASK, 14 },
    { "SEQCMP_TYPE", AR_NIC_FMA_CFG_DESC_SFMA_SEQCMP_TYPE_BP, AR_NIC_FMA_CFG_DESC_SFMA_SEQCMP_TYPE_MASK, 13 },
    { "RESERVED_887_882", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_887_882_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_887_882_MASK, 13 },
    { "TRANSACTION_END", AR_NIC_FMA_CFG_DESC_SFMA_TRANSACTION_END_BP, AR_NIC_FMA_CFG_DESC_SFMA_TRANSACTION_END_MASK, 13 },
    { "SEQCMP_DLA_DEALLOC", AR_NIC_FMA_CFG_DESC_SFMA_SEQCMP_DLA_DEALLOC_BP, AR_NIC_FMA_CFG_DESC_SFMA_SEQCMP_DLA_DEALLOC_MASK, 13 },
    { "SEQCMP_SRC_CQ_DATA", AR_NIC_FMA_CFG_DESC_SFMA_SEQCMP_SRC_CQ_DATA_BP, AR_NIC_FMA_CFG_DESC_SFMA_SEQCMP_SRC_CQ_DATA_MASK, 13 },
    { "RESERVED_831_771", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_831_771_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_831_771_MASK, 12 },
    { "WR_STATUS_WHEN", AR_NIC_FMA_CFG_DESC_SFMA_WR_STATUS_WHEN_BP, AR_NIC_FMA_CFG_DESC_SFMA_WR_STATUS_WHEN_MASK, 12 },
    { "RESERVED_767_704", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_767_704_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_767_704_MASK, 11 },
    { "RESERVED_703_640", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_703_640_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_703_640_MASK, 10 },
    { "RESERVED_639_624", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_639_624_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_639_624_MASK, 9 },
    { "CQ_WRITE", AR_NIC_FMA_CFG_DESC_SFMA_CQ_WRITE_BP, AR_NIC_FMA_CFG_DESC_SFMA_CQ_WRITE_MASK, 9 },
    { "TRANSACTION_START", AR_NIC_FMA_CFG_DESC_SFMA_TRANSACTION_START_BP, AR_NIC_FMA_CFG_DESC_SFMA_TRANSACTION_START_MASK, 8 },
    { "DLA_REISSUE", AR_NIC_FMA_CFG_DESC_SFMA_DLA_REISSUE_BP, AR_NIC_FMA_CFG_DESC_SFMA_DLA_REISSUE_MASK, 8 },
    { "DISCARD_RESET", AR_NIC_FMA_CFG_DESC_SFMA_DISCARD_RESET_BP, AR_NIC_FMA_CFG_DESC_SFMA_DISCARD_RESET_MASK, 8 },
    { "ALLOC_STATUS_RESET", AR_NIC_FMA_CFG_DESC_SFMA_ALLOC_STATUS_RESET_BP, AR_NIC_FMA_CFG_DESC_SFMA_ALLOC_STATUS_RESET_MASK, 8 },
    { "RESERVED_571_558", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_571_558_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_571_558_MASK, 8 },
    { "CREDITS_REQUIRED", AR_NIC_FMA_CFG_DESC_SFMA_CREDITS_REQUIRED_BP, AR_NIC_FMA_CFG_DESC_SFMA_CREDITS_REQUIRED_MASK, 8 },
    { "BLOCK_ID", AR_NIC_FMA_CFG_DESC_SFMA_BLOCK_ID_BP, AR_NIC_FMA_CFG_DESC_SFMA_BLOCK_ID_MASK, 8 },
    { "RESERVED_523_522", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_523_522_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_523_522_MASK, 8 },
    { "STATUS_INTERVAL", AR_NIC_FMA_CFG_DESC_SFMA_STATUS_INTERVAL_BP, AR_NIC_FMA_CFG_DESC_SFMA_STATUS_INTERVAL_MASK, 8 },
    { "STATUS_WREN", AR_NIC_FMA_CFG_DESC_SFMA_STATUS_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_STATUS_WREN_MASK, 7 },
    { "DLA_MARKER_DBELL_WREN", AR_NIC_FMA_CFG_DESC_SFMA_DLA_MARKER_DBELL_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_DLA_MARKER_DBELL_WREN_MASK, 7 },
    { "FMA_LAUNCH_DBELL_WREN", AR_NIC_FMA_CFG_DESC_SFMA_FMA_LAUNCH_DBELL_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_FMA_LAUNCH_DBELL_WREN_MASK, 7 },
    { "WR_STATUS_DBELL_WREN", AR_NIC_FMA_CFG_DESC_SFMA_WR_STATUS_DBELL_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_WR_STATUS_DBELL_WREN_MASK, 7 },
    { "CE_DBELL_WREN", AR_NIC_FMA_CFG_DESC_SFMA_CE_DBELL_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_CE_DBELL_WREN_MASK, 7 },
    { "FLBTE_DBELL_WREN", AR_NIC_FMA_CFG_DESC_SFMA_FLBTE_DBELL_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_FLBTE_DBELL_WREN_MASK, 7 },
    { "CQ_WRITE_DBELL_WREN", AR_NIC_FMA_CFG_DESC_SFMA_CQ_WRITE_DBELL_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_CQ_WRITE_DBELL_WREN_MASK, 7 },
    { "SEQCMP_DBELL_WREN", AR_NIC_FMA_CFG_DESC_SFMA_SEQCMP_DBELL_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_SEQCMP_DBELL_WREN_MASK, 7 },
    { "ALLOC_SEQ_ID_DBELL_WREN", AR_NIC_FMA_CFG_DESC_SFMA_ALLOC_SEQ_ID_DBELL_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_ALLOC_SEQ_ID_DBELL_WREN_MASK, 7 },
    { "WC_WREN", AR_NIC_FMA_CFG_DESC_SFMA_WC_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_WC_WREN_MASK, 7 },
    { "DLA_ALLOC_CD_WREN", AR_NIC_FMA_CFG_DESC_SFMA_DLA_ALLOC_CD_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_DLA_ALLOC_CD_WREN_MASK, 7 },
    { "DLA_ALLOC_PR_WREN", AR_NIC_FMA_CFG_DESC_SFMA_DLA_ALLOC_PR_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_DLA_ALLOC_PR_WREN_MASK, 7 },
    { "DLA_HIGH_PRIORITY_WREN", AR_NIC_FMA_CFG_DESC_SFMA_DLA_HIGH_PRIORITY_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_DLA_HIGH_PRIORITY_WREN_MASK, 7 },
    { "DLA_CQH_WREN", AR_NIC_FMA_CFG_DESC_SFMA_DLA_CQH_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_DLA_CQH_WREN_MASK, 7 },
    { "SCRATCH_REG2_WREN", AR_NIC_FMA_CFG_DESC_SFMA_SCRATCH_REG2_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_SCRATCH_REG2_WREN_MASK, 7 },
    { "SCRATCH_REG1_WREN", AR_NIC_FMA_CFG_DESC_SFMA_SCRATCH_REG1_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_SCRATCH_REG1_WREN_MASK, 7 },
    { "SCRATCH_REG0_WREN", AR_NIC_FMA_CFG_DESC_SFMA_SCRATCH_REG0_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_SCRATCH_REG0_WREN_MASK, 7 },
    { "NTT_EN_WREN", AR_NIC_FMA_CFG_DESC_SFMA_NTT_EN_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_NTT_EN_WREN_MASK, 7 },
    { "PTAG_WREN", AR_NIC_FMA_CFG_DESC_SFMA_PTAG_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_PTAG_WREN_MASK, 7 },
    { "SRC_CQH_WREN", AR_NIC_FMA_CFG_DESC_SFMA_SRC_CQH_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_SRC_CQH_WREN_MASK, 7 },
    { "PE_BASE_WREN", AR_NIC_FMA_CFG_DESC_SFMA_PE_BASE_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_PE_BASE_WREN_MASK, 7 },
    { "NPES_WREN", AR_NIC_FMA_CFG_DESC_SFMA_NPES_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_NPES_WREN_MASK, 7 },
    { "REM_MDH_WREN", AR_NIC_FMA_CFG_DESC_SFMA_REM_MDH_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_REM_MDH_WREN_MASK, 7 },
    { "LOC_MDH_WREN", AR_NIC_FMA_CFG_DESC_SFMA_LOC_MDH_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_LOC_MDH_WREN_MASK, 7 },
    { "BTE_FENCE_WREN", AR_NIC_FMA_CFG_DESC_SFMA_BTE_FENCE_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_BTE_FENCE_WREN_MASK, 7 },
    { "PRIVILEGED_WREN", AR_NIC_FMA_CFG_DESC_SFMA_PRIVILEGED_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_PRIVILEGED_WREN_MASK, 7 },
    { "BTE_CHAN_WREN", AR_NIC_FMA_CFG_DESC_SFMA_BTE_CHAN_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_BTE_CHAN_WREN_MASK, 7 },
    { "NAT_RDCTRL_LONG_PKT_WREN", AR_NIC_FMA_CFG_DESC_SFMA_NAT_RDCTRL_LONG_PKT_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_NAT_RDCTRL_LONG_PKT_WREN_MASK, 7 },
    { "ENQ_STATUS_CQH_WREN", AR_NIC_FMA_CFG_DESC_SFMA_ENQ_STATUS_CQH_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_ENQ_STATUS_CQH_WREN_MASK, 7 },
    { "PE_MASK_FPE_WREN", AR_NIC_FMA_CFG_DESC_SFMA_PE_MASK_FPE_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_PE_MASK_FPE_WREN_MASK, 7 },
    { "OP_WREN", AR_NIC_FMA_CFG_DESC_SFMA_OP_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_OP_WREN_MASK, 7 },
    { "FMA_EN_WREN", AR_NIC_FMA_CFG_DESC_SFMA_FMA_EN_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_FMA_EN_WREN_MASK, 7 },
    { "RC_WREN", AR_NIC_FMA_CFG_DESC_SFMA_RC_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_RC_WREN_MASK, 7 },
    { "BASE_OFFSET_HIGH_WREN", AR_NIC_FMA_CFG_DESC_SFMA_BASE_OFFSET_HIGH_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_BASE_OFFSET_HIGH_WREN_MASK, 7 },
    { "BASE_OFFSET_LOW_WREN", AR_NIC_FMA_CFG_DESC_SFMA_BASE_OFFSET_LOW_WREN_BP, AR_NIC_FMA_CFG_DESC_SFMA_BASE_OFFSET_LOW_WREN_MASK, 7 },
    { "RESERVED_383_368", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_383_368_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_383_368_MASK, 5 },
    { "DEST_CQ_DATA", AR_NIC_FMA_CFG_DESC_SFMA_DEST_CQ_DATA_BP, AR_NIC_FMA_CFG_DESC_SFMA_DEST_CQ_DATA_MASK, 5 },
    { "FLAG_DATA_OFFSET", AR_NIC_FMA_CFG_DESC_SFMA_FLAG_DATA_OFFSET_BP, AR_NIC_FMA_CFG_DESC_SFMA_FLAG_DATA_OFFSET_MASK, 4 },
    { "AMO_OPRND2", AR_NIC_FMA_CFG_DESC_SFMA_AMO_OPRND2_BP, AR_NIC_FMA_CFG_DESC_SFMA_AMO_OPRND2_MASK, 4 },
    { "FLAG_DATA", AR_NIC_FMA_CFG_DESC_SFMA_FLAG_DATA_BP, AR_NIC_FMA_CFG_DESC_SFMA_FLAG_DATA_MASK, 3 },
    { "AMO_OPRND1", AR_NIC_FMA_CFG_DESC_SFMA_AMO_OPRND1_BP, AR_NIC_FMA_CFG_DESC_SFMA_AMO_OPRND1_MASK, 3 },
    { "NTT_EN", AR_NIC_FMA_CFG_DESC_SFMA_NTT_EN_BP, AR_NIC_FMA_CFG_DESC_SFMA_NTT_EN_MASK, 2 },
    { "REM_PTAG", AR_NIC_FMA_CFG_DESC_SFMA_REM_PTAG_BP, AR_NIC_FMA_CFG_DESC_SFMA_REM_PTAG_MASK, 2 },
    { "LOC_PTAG", AR_NIC_FMA_CFG_DESC_SFMA_LOC_PTAG_BP, AR_NIC_FMA_CFG_DESC_SFMA_LOC_PTAG_MASK, 2 },
    { "SRC_CQH", AR_NIC_FMA_CFG_DESC_SFMA_SRC_CQH_BP, AR_NIC_FMA_CFG_DESC_SFMA_SRC_CQH_MASK, 2 },
    { "PE_BASE", AR_NIC_FMA_CFG_DESC_SFMA_PE_BASE_BP, AR_NIC_FMA_CFG_DESC_SFMA_PE_BASE_MASK, 2 },
    { "NPES", AR_NIC_FMA_CFG_DESC_SFMA_NPES_BP, AR_NIC_FMA_CFG_DESC_SFMA_NPES_MASK, 2 },
    { "RESERVED_127", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_127_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_127_MASK, 1 },
    { "REM_MDH", AR_NIC_FMA_CFG_DESC_SFMA_REM_MDH_BP, AR_NIC_FMA_CFG_DESC_SFMA_REM_MDH_MASK, 1 },
    { "RESERVED_114", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_114_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_114_MASK, 1 },
    { "LOC_MDH", AR_NIC_FMA_CFG_DESC_SFMA_LOC_MDH_BP, AR_NIC_FMA_CFG_DESC_SFMA_LOC_MDH_MASK, 1 },
    { "RESERVED_101_100", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_101_100_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_101_100_MASK, 1 },
    { "RESERVED_99_98", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_99_98_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_99_98_MASK, 1 },
    { "RESERVED_97_92", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_97_92_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_97_92_MASK, 1 },
    { "RESERVED_91", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_91_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_91_MASK, 1 },
    { "RESERVED_90_80", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_90_80_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_90_80_MASK, 1 },
    { "RESERVED_79_76", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_79_76_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_79_76_MASK, 1 },
    { "RESERVED_75", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_75_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_75_MASK, 1 },
    { "PE_MASK_MODE", AR_NIC_FMA_CFG_DESC_SFMA_PE_MASK_MODE_BP, AR_NIC_FMA_CFG_DESC_SFMA_PE_MASK_MODE_MASK, 1 },
    { "RESERVED_71", AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_71_BP, AR_NIC_FMA_CFG_DESC_SFMA_RESERVED_71_MASK, 1 },
    { "FMA_OP", AR_NIC_FMA_CFG_DESC_SFMA_FMA_OP_BP, AR_NIC_FMA_CFG_DESC_SFMA_FMA_OP_MASK, 1 },
    { "FMA_EN", AR_NIC_FMA_CFG_DESC_SFMA_FMA_EN_BP, AR_NIC_FMA_CFG_DESC_SFMA_FMA_EN_MASK, 0 },
    { "RC", AR_NIC_FMA_CFG_DESC_SFMA_RC_BP, AR_NIC_FMA_CFG_DESC_SFMA_RC_MASK, 0 },
    { "WC", AR_NIC_FMA_CFG_DESC_SFMA_WC_BP, AR_NIC_FMA_CFG_DESC_SFMA_WC_MASK, 0 },
    { "GET_LAUNCH", AR_NIC_FMA_CFG_DESC_SFMA_GET_LAUNCH_BP, AR_NIC_FMA_CFG_DESC_SFMA_GET_LAUNCH_MASK, 0 },
    { "STATUS_WD_OFFSET", AR_NIC_FMA_CFG_DESC_SFMA_STATUS_WD_OFFSET_BP, AR_NIC_FMA_CFG_DESC_SFMA_STATUS_WD_OFFSET_MASK, 0 },
    { "BASE_OFFSET", AR_NIC_FMA_CFG_DESC_SFMA_BASE_OFFSET_BP, AR_NIC_FMA_CFG_DESC_SFMA_BASE_OFFSET_MASK, 0 },
    { "GLOBAL_OFFSET", AR_NIC_FMA_CFG_DESC_SFMA_GLOBAL_OFFSET_BP, AR_NIC_FMA_CFG_DESC_SFMA_GLOBAL_OFFSET_MASK, 0 },
    { NULL, 0, 0, 0 }
};
static const generic_descd_t _ar_nic_fma_cfg_desc_flbte_detail[] = {
    { "RESERVED_1727_1664", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_1727_1664_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_1727_1664_MASK, 26 },
    { "RESERVED_1663_1600", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_1663_1600_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_1663_1600_MASK, 25 },
    { "RESERVED_1599_1536", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_1599_1536_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_1599_1536_MASK, 24 },
    { "RESERVED_1151_1088", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_1151_1088_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_1151_1088_MASK, 17 },
    { "STATUS", AR_NIC_FMA_CFG_DESC_FLBTE_STATUS_BP, AR_NIC_FMA_CFG_DESC_FLBTE_STATUS_MASK, 16 },
    { "RESERVED_1023_960", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_1023_960_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_1023_960_MASK, 15 },
    { "RESERVED_959_896", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_959_896_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_959_896_MASK, 14 },
    { "RESERVED_895_832", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_895_832_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_895_832_MASK, 13 },
    { "RESERVED_831_771", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_831_771_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_831_771_MASK, 12 },
    { "WR_STATUS_WHEN", AR_NIC_FMA_CFG_DESC_FLBTE_WR_STATUS_WHEN_BP, AR_NIC_FMA_CFG_DESC_FLBTE_WR_STATUS_WHEN_MASK, 12 },
    { "RESERVED_767_704", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_767_704_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_767_704_MASK, 11 },
    { "FLBTE_RPT_ENQ_STATUS", AR_NIC_FMA_CFG_DESC_FLBTE_FLBTE_RPT_ENQ_STATUS_BP, AR_NIC_FMA_CFG_DESC_FLBTE_FLBTE_RPT_ENQ_STATUS_MASK, 10 },
    { "FLBTE_BTE_IMMEDIATE", AR_NIC_FMA_CFG_DESC_FLBTE_FLBTE_BTE_IMMEDIATE_BP, AR_NIC_FMA_CFG_DESC_FLBTE_FLBTE_BTE_IMMEDIATE_MASK, 10 },
    { "FLBTE_SRC_SSID_CQ_EN", AR_NIC_FMA_CFG_DESC_FLBTE_FLBTE_SRC_SSID_CQ_EN_BP, AR_NIC_FMA_CFG_DESC_FLBTE_FLBTE_SRC_SSID_CQ_EN_MASK, 10 },
    { "FLBTE_SRC_BTE_CQ_EN", AR_NIC_FMA_CFG_DESC_FLBTE_FLBTE_SRC_BTE_CQ_EN_BP, AR_NIC_FMA_CFG_DESC_FLBTE_FLBTE_SRC_BTE_CQ_EN_MASK, 10 },
    { "RESERVED_699_688", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_699_688_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_699_688_MASK, 10 },
    { "FLBTE_SRC_CQ_DATA", AR_NIC_FMA_CFG_DESC_FLBTE_FLBTE_SRC_CQ_DATA_BP, AR_NIC_FMA_CFG_DESC_FLBTE_FLBTE_SRC_CQ_DATA_MASK, 10 },
    { "RESERVED_639_576", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_639_576_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_639_576_MASK, 9 },
    { "RESERVED_575_512", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_575_512_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_575_512_MASK, 8 },
    { "PRIVILEGE_MASK", AR_NIC_FMA_CFG_DESC_FLBTE_PRIVILEGE_MASK_BP, AR_NIC_FMA_CFG_DESC_FLBTE_PRIVILEGE_MASK_MASK, 7 },
    { "DEST_USER_DATA", AR_NIC_FMA_CFG_DESC_FLBTE_DEST_USER_DATA_BP, AR_NIC_FMA_CFG_DESC_FLBTE_DEST_USER_DATA_MASK, 5 },
    { "RESERVED_319_288", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_319_288_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_319_288_MASK, 4 },
    { "XFER_LEN", AR_NIC_FMA_CFG_DESC_FLBTE_XFER_LEN_BP, AR_NIC_FMA_CFG_DESC_FLBTE_XFER_LEN_MASK, 4 },
    { "RESERVED_255_240", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_255_240_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_255_240_MASK, 3 },
    { "LOC_PHYS_ADDR", AR_NIC_FMA_CFG_DESC_FLBTE_LOC_PHYS_ADDR_BP, AR_NIC_FMA_CFG_DESC_FLBTE_LOC_PHYS_ADDR_MASK, 3 },
    { "LOC_MEM_OFFSET", AR_NIC_FMA_CFG_DESC_FLBTE_LOC_MEM_OFFSET_BP, AR_NIC_FMA_CFG_DESC_FLBTE_LOC_MEM_OFFSET_MASK, 3 },
    { "NTT_EN", AR_NIC_FMA_CFG_DESC_FLBTE_NTT_EN_BP, AR_NIC_FMA_CFG_DESC_FLBTE_NTT_EN_MASK, 2 },
    { "REM_PTAG", AR_NIC_FMA_CFG_DESC_FLBTE_REM_PTAG_BP, AR_NIC_FMA_CFG_DESC_FLBTE_REM_PTAG_MASK, 2 },
    { "LOC_PTAG", AR_NIC_FMA_CFG_DESC_FLBTE_LOC_PTAG_BP, AR_NIC_FMA_CFG_DESC_FLBTE_LOC_PTAG_MASK, 2 },
    { "SRC_CQH", AR_NIC_FMA_CFG_DESC_FLBTE_SRC_CQH_BP, AR_NIC_FMA_CFG_DESC_FLBTE_SRC_CQH_MASK, 2 },
    { "PE_BASE", AR_NIC_FMA_CFG_DESC_FLBTE_PE_BASE_BP, AR_NIC_FMA_CFG_DESC_FLBTE_PE_BASE_MASK, 2 },
    { "NPES", AR_NIC_FMA_CFG_DESC_FLBTE_NPES_BP, AR_NIC_FMA_CFG_DESC_FLBTE_NPES_MASK, 2 },
    { "RESERVED_127", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_127_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_127_MASK, 1 },
    { "REM_MDH", AR_NIC_FMA_CFG_DESC_FLBTE_REM_MDH_BP, AR_NIC_FMA_CFG_DESC_FLBTE_REM_MDH_MASK, 1 },
    { "RESERVED_114", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_114_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_114_MASK, 1 },
    { "LOC_MDH", AR_NIC_FMA_CFG_DESC_FLBTE_LOC_MDH_BP, AR_NIC_FMA_CFG_DESC_FLBTE_LOC_MDH_MASK, 1 },
    { "BTE_FENCE", AR_NIC_FMA_CFG_DESC_FLBTE_BTE_FENCE_BP, AR_NIC_FMA_CFG_DESC_FLBTE_BTE_FENCE_MASK, 1 },
    { "PRIVILEGED", AR_NIC_FMA_CFG_DESC_FLBTE_PRIVILEGED_BP, AR_NIC_FMA_CFG_DESC_FLBTE_PRIVILEGED_MASK, 1 },
    { "RESERVED_99_98", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_99_98_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_99_98_MASK, 1 },
    { "BTE_CHAN", AR_NIC_FMA_CFG_DESC_FLBTE_BTE_CHAN_BP, AR_NIC_FMA_CFG_DESC_FLBTE_BTE_CHAN_MASK, 1 },
    { "RESERVED_95", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_95_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_95_MASK, 1 },
    { "RD_NO_SNOOP", AR_NIC_FMA_CFG_DESC_FLBTE_RD_NO_SNOOP_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RD_NO_SNOOP_MASK, 1 },
    { "RD_RO", AR_NIC_FMA_CFG_DESC_FLBTE_RD_RO_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RD_RO_MASK, 1 },
    { "NAT_EN", AR_NIC_FMA_CFG_DESC_FLBTE_NAT_EN_BP, AR_NIC_FMA_CFG_DESC_FLBTE_NAT_EN_MASK, 1 },
    { "RESERVED_91", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_91_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_91_MASK, 1 },
    { "ENQ_STATUS_CQH", AR_NIC_FMA_CFG_DESC_FLBTE_ENQ_STATUS_CQH_BP, AR_NIC_FMA_CFG_DESC_FLBTE_ENQ_STATUS_CQH_MASK, 1 },
    { "RESERVED_75_72", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_75_72_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_75_72_MASK, 1 },
    { "RESERVED_71", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_71_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_71_MASK, 1 },
    { "RESERVED_70_66", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_70_66_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_70_66_MASK, 1 },
    { "BTE_OP", AR_NIC_FMA_CFG_DESC_FLBTE_BTE_OP_BP, AR_NIC_FMA_CFG_DESC_FLBTE_BTE_OP_MASK, 1 },
    { "FMA_EN", AR_NIC_FMA_CFG_DESC_FLBTE_FMA_EN_BP, AR_NIC_FMA_CFG_DESC_FLBTE_FMA_EN_MASK, 0 },
    { "RC", AR_NIC_FMA_CFG_DESC_FLBTE_RC_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RC_MASK, 0 },
    { "WC", AR_NIC_FMA_CFG_DESC_FLBTE_WC_BP, AR_NIC_FMA_CFG_DESC_FLBTE_WC_MASK, 0 },
    { "RESERVED_58", AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_58_BP, AR_NIC_FMA_CFG_DESC_FLBTE_RESERVED_58_MASK, 0 },
    { "LOGICAL_DEST", AR_NIC_FMA_CFG_DESC_FLBTE_LOGICAL_DEST_BP, AR_NIC_FMA_CFG_DESC_FLBTE_LOGICAL_DEST_MASK, 0 },
    { "REM_MEM_OFFSET", AR_NIC_FMA_CFG_DESC_FLBTE_REM_MEM_OFFSET_BP, AR_NIC_FMA_CFG_DESC_FLBTE_REM_MEM_OFFSET_MASK, 0 },
    { NULL, 0, 0, 0 }
};
static const generic_descd_t _ar_nic_fma_cfg_desc_ce_detail[] = {
    { "RESERVED_1727_1664", AR_NIC_FMA_CFG_DESC_CE_RESERVED_1727_1664_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_1727_1664_MASK, 26 },
    { "RESERVED_1663_1600", AR_NIC_FMA_CFG_DESC_CE_RESERVED_1663_1600_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_1663_1600_MASK, 25 },
    { "RESERVED_1599_1536", AR_NIC_FMA_CFG_DESC_CE_RESERVED_1599_1536_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_1599_1536_MASK, 24 },
    { "RESERVED_1151_1088", AR_NIC_FMA_CFG_DESC_CE_RESERVED_1151_1088_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_1151_1088_MASK, 17 },
    { "STATUS", AR_NIC_FMA_CFG_DESC_CE_STATUS_BP, AR_NIC_FMA_CFG_DESC_CE_STATUS_MASK, 16 },
    { "RESERVED_1023_960", AR_NIC_FMA_CFG_DESC_CE_RESERVED_1023_960_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_1023_960_MASK, 15 },
    { "RESERVED_959_896", AR_NIC_FMA_CFG_DESC_CE_RESERVED_959_896_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_959_896_MASK, 14 },
    { "SEQCMP", AR_NIC_FMA_CFG_DESC_CE_SEQCMP_BP, AR_NIC_FMA_CFG_DESC_CE_SEQCMP_MASK, 13 },
    { "RESERVED_831_771", AR_NIC_FMA_CFG_DESC_CE_RESERVED_831_771_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_831_771_MASK, 12 },
    { "WR_STATUS_WHEN", AR_NIC_FMA_CFG_DESC_CE_WR_STATUS_WHEN_BP, AR_NIC_FMA_CFG_DESC_CE_WR_STATUS_WHEN_MASK, 12 },
    { "RESERVED_767_745", AR_NIC_FMA_CFG_DESC_CE_RESERVED_767_745_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_767_745_MASK, 11 },
    { "CEDB_USE_OPRND2", AR_NIC_FMA_CFG_DESC_CE_CEDB_USE_OPRND2_BP, AR_NIC_FMA_CFG_DESC_CE_CEDB_USE_OPRND2_MASK, 11 },
    { "CEDB_REDUCTN_ID", AR_NIC_FMA_CFG_DESC_CE_CEDB_REDUCTN_ID_BP, AR_NIC_FMA_CFG_DESC_CE_CEDB_REDUCTN_ID_MASK, 11 },
    { "RESERVED_703_640", AR_NIC_FMA_CFG_DESC_CE_RESERVED_703_640_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_703_640_MASK, 10 },
    { "RESERVED_639_576", AR_NIC_FMA_CFG_DESC_CE_RESERVED_639_576_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_639_576_MASK, 9 },
    { "ALLOC_SEQID", AR_NIC_FMA_CFG_DESC_CE_ALLOC_SEQID_BP, AR_NIC_FMA_CFG_DESC_CE_ALLOC_SEQID_MASK, 8 },
    { "PRIVILEGE_MASK", AR_NIC_FMA_CFG_DESC_CE_PRIVILEGE_MASK_BP, AR_NIC_FMA_CFG_DESC_CE_PRIVILEGE_MASK_MASK, 7 },
    { "RESERVED_383_334", AR_NIC_FMA_CFG_DESC_CE_RESERVED_383_334_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_383_334_MASK, 5 },
    { "CHILD_ID", AR_NIC_FMA_CFG_DESC_CE_CHILD_ID_BP, AR_NIC_FMA_CFG_DESC_CE_CHILD_ID_MASK, 5 },
    { "RESERVED_327_326", AR_NIC_FMA_CFG_DESC_CE_RESERVED_327_326_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_327_326_MASK, 5 },
    { "CE_ID", AR_NIC_FMA_CFG_DESC_CE_CE_ID_BP, AR_NIC_FMA_CFG_DESC_CE_CE_ID_MASK, 5 },
    { "CE_OPRND2", AR_NIC_FMA_CFG_DESC_CE_CE_OPRND2_BP, AR_NIC_FMA_CFG_DESC_CE_CE_OPRND2_MASK, 4 },
    { "CE_OPRND1", AR_NIC_FMA_CFG_DESC_CE_CE_OPRND1_BP, AR_NIC_FMA_CFG_DESC_CE_CE_OPRND1_MASK, 3 },
    { "NTT_EN", AR_NIC_FMA_CFG_DESC_CE_NTT_EN_BP, AR_NIC_FMA_CFG_DESC_CE_NTT_EN_MASK, 2 },
    { "REM_PTAG", AR_NIC_FMA_CFG_DESC_CE_REM_PTAG_BP, AR_NIC_FMA_CFG_DESC_CE_REM_PTAG_MASK, 2 },
    { "RESERVED_182_164", AR_NIC_FMA_CFG_DESC_CE_RESERVED_182_164_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_182_164_MASK, 2 },
    { "PE_BASE", AR_NIC_FMA_CFG_DESC_CE_PE_BASE_BP, AR_NIC_FMA_CFG_DESC_CE_PE_BASE_MASK, 2 },
    { "NPES", AR_NIC_FMA_CFG_DESC_CE_NPES_BP, AR_NIC_FMA_CFG_DESC_CE_NPES_MASK, 2 },
    { "RESERVED_127", AR_NIC_FMA_CFG_DESC_CE_RESERVED_127_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_127_MASK, 1 },
    { "REM_MDH", AR_NIC_FMA_CFG_DESC_CE_REM_MDH_BP, AR_NIC_FMA_CFG_DESC_CE_REM_MDH_MASK, 1 },
    { "RESERVED_114", AR_NIC_FMA_CFG_DESC_CE_RESERVED_114_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_114_MASK, 1 },
    { "RESERVED_113_100", AR_NIC_FMA_CFG_DESC_CE_RESERVED_113_100_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_113_100_MASK, 1 },
    { "RESERVED_99_98", AR_NIC_FMA_CFG_DESC_CE_RESERVED_99_98_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_99_98_MASK, 1 },
    { "RESERVED_97_92", AR_NIC_FMA_CFG_DESC_CE_RESERVED_97_92_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_97_92_MASK, 1 },
    { "RESERVED_91", AR_NIC_FMA_CFG_DESC_CE_RESERVED_91_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_91_MASK, 1 },
    { "RESERVED_90_80", AR_NIC_FMA_CFG_DESC_CE_RESERVED_90_80_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_90_80_MASK, 1 },
    { "RESERVED_79_76", AR_NIC_FMA_CFG_DESC_CE_RESERVED_79_76_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_79_76_MASK, 1 },
    { "FP_EXCEPTION", AR_NIC_FMA_CFG_DESC_CE_FP_EXCEPTION_BP, AR_NIC_FMA_CFG_DESC_CE_FP_EXCEPTION_MASK, 1 },
    { "RESERVED_71", AR_NIC_FMA_CFG_DESC_CE_RESERVED_71_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_71_MASK, 1 },
    { "RESERVED_70", AR_NIC_FMA_CFG_DESC_CE_RESERVED_70_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_70_MASK, 1 },
    { "CE_OP", AR_NIC_FMA_CFG_DESC_CE_CE_OP_BP, AR_NIC_FMA_CFG_DESC_CE_CE_OP_MASK, 1 },
    { "FMA_EN", AR_NIC_FMA_CFG_DESC_CE_FMA_EN_BP, AR_NIC_FMA_CFG_DESC_CE_FMA_EN_MASK, 0 },
    { "RC", AR_NIC_FMA_CFG_DESC_CE_RC_BP, AR_NIC_FMA_CFG_DESC_CE_RC_MASK, 0 },
    { "RESERVED_59", AR_NIC_FMA_CFG_DESC_CE_RESERVED_59_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_59_MASK, 0 },
    { "RESERVED_58", AR_NIC_FMA_CFG_DESC_CE_RESERVED_58_BP, AR_NIC_FMA_CFG_DESC_CE_RESERVED_58_MASK, 0 },
    { "LOGICAL_DEST", AR_NIC_FMA_CFG_DESC_CE_LOGICAL_DEST_BP, AR_NIC_FMA_CFG_DESC_CE_LOGICAL_DEST_MASK, 0 },
    { "SCATTER_OFFSET", AR_NIC_FMA_CFG_DESC_CE_SCATTER_OFFSET_BP, AR_NIC_FMA_CFG_DESC_CE_SCATTER_OFFSET_MASK, 0 },
    { NULL, 0, 0, 0 }
};

/*
 *  AR FMA DESCRIPTOR DECLARATIONS
 */
static const generic_desc_t _ar_nic_fma_cfg_desc_sfma = {
    "AR_NIC_FMA_CFG_DESC_SFMA", AR_NIC_FMA_CFG_DESC_SFMA, AR_NIC_FMA_CFG_DESC_SFMA_DESC_INCR, AR_NIC_FMA_CFG_DESC_SFMA_N_ENTRY, _ar_nic_fma_cfg_desc_sfma_detail
};
static const generic_desc_t _ar_nic_fma_cfg_desc_flbte = {
    "AR_NIC_FMA_CFG_DESC_FLBTE", AR_NIC_FMA_CFG_DESC_FLBTE, AR_NIC_FMA_CFG_DESC_FLBTE_DESC_INCR, AR_NIC_FMA_CFG_DESC_FLBTE_N_ENTRY, _ar_nic_fma_cfg_desc_flbte_detail
};
static const generic_desc_t _ar_nic_fma_cfg_desc_ce = {
    "AR_NIC_FMA_CFG_DESC_CE", AR_NIC_FMA_CFG_DESC_CE, AR_NIC_FMA_CFG_DESC_CE_DESC_INCR, AR_NIC_FMA_CFG_DESC_CE_N_ENTRY, _ar_nic_fma_cfg_desc_ce_detail
};

/*
 *  INSTALL AR FMA DESCRIPTORS
 */
static const generic_desc_t* _ar_fma_descs[] = {
    &_ar_nic_fma_cfg_desc_sfma,
    &_ar_nic_fma_cfg_desc_flbte,
    &_ar_nic_fma_cfg_desc_ce,
    NULL
};

#endif
