/******************************************************************************
 * COPYRIGHT CRAY INC. ar_fma_enum_h.h
 * FILE: ar_fma_enum_h.h
 * Created by v2h.c on Wed Oct  8 14:38:59 2014
 ******************************************************************************/

#ifndef _AR_FMA_ENUM_H_H_
#define _AR_FMA_ENUM_H_H_

#define AR_NIC_FMA_DESC_SIZE                                        	0x1000ull
#define AR_NIC_FMA_DESC_QUANTITY                                    	0x80ull
#define AR_NIC_FMA_DESC_HIGHEST                                     	0x7full
#define WR_STATUS_CANCEL                                            	0x0ull
#define WR_STATUS_NOW                                               	0x4ull
#define WR_STATUS_WCZ                                               	0x5ull
#define WR_STATUS_RCZ                                               	0x6ull
#define WR_STATUS_WCRCZ                                             	0x7ull
#define SEQCMP_TYPE_NONE                                            	0x0ull
#define SEQCMP_TYPE_SSN                                             	0x1ull
#define SEQCMP_TYPE_DSN_NOFLAG                                      	0x4ull
#define SEQCMP_TYPE_DSN_FLAG                                        	0x8ull
#define SEQCMP_TYPE_SSN_DSN_NOFLAG                                  	0x5ull
#define SEQCMP_TYPE_SSN_DSN_FLAG                                    	0x9ull
#define PUT                                                         	0x0ull
#define PUTMSG                                                      	0x1ull
#define PUT_S                                                       	0x2ull
#define AAND_S                                                      	0x40ull
#define AAND                                                        	0x41ull
#define AOR_S                                                       	0x42ull
#define AOR                                                         	0x43ull
#define AXOR_S                                                      	0x44ull
#define AXOR                                                        	0x45ull
#define ASWAP_S                                                     	0x46ull
#define ASWAP                                                       	0x47ull
#define AAX_S                                                       	0x48ull
#define AAX                                                         	0x49ull
#define ACSWAP_S                                                    	0x4aull
#define ACSWAP                                                      	0x4bull
#define AIMIN_S                                                     	0x50ull
#define AIMIN                                                       	0x51ull
#define AIMAX_S                                                     	0x52ull
#define AIMAX                                                       	0x53ull
#define AIADD_S                                                     	0x54ull
#define AIADD                                                       	0x55ull
#define AFPMIN_S                                                    	0x58ull
#define AFPMIN                                                      	0x59ull
#define AFPMAX_S                                                    	0x5aull
#define AFPMAX                                                      	0x5bull
#define AFPADD_S                                                    	0x5cull
#define AFPADD                                                      	0x5dull
#define AAND_SC                                                     	0x60ull
#define AAND_C                                                      	0x61ull
#define AOR_SC                                                      	0x62ull
#define AOR_C                                                       	0x63ull
#define AXOR_SC                                                     	0x64ull
#define AXOR_C                                                      	0x65ull
#define ASWAP_SC                                                    	0x66ull
#define ASWAP_C                                                     	0x67ull
#define AAX_SC                                                      	0x68ull
#define AAX_C                                                       	0x69ull
#define ACSWAP_SC                                                   	0x6aull
#define ACSWAP_C                                                    	0x6bull
#define AIMIN_SC                                                    	0x70ull
#define AIMIN_C                                                     	0x71ull
#define AIMAX_SC                                                    	0x72ull
#define AIMAX_C                                                     	0x73ull
#define AIADD_SC                                                    	0x74ull
#define AIADD_C                                                     	0x75ull
#define AFPMIN_SC                                                   	0x78ull
#define AFPMIN_C                                                    	0x79ull
#define AFPMAX_SC                                                   	0x7aull
#define AFPMAX_C                                                    	0x7bull
#define AFPADD_SC                                                   	0x7cull
#define AFPADD_C                                                    	0x7dull
#define AND_S                                                       	0x0ull
#define AND                                                         	0x1ull
#define OR_S                                                        	0x2ull
#define OR                                                          	0x3ull
#define XOR_S                                                       	0x4ull
#define XOR                                                         	0x5ull
#define IMIN_LIDX_S                                                 	0x10ull
#define IMIN_LIDX                                                   	0x11ull
#define IMAX_LIDX_S                                                 	0x12ull
#define IMAX_LIDX                                                   	0x13ull
#define IADD_S                                                      	0x14ull
#define IADD                                                        	0x15ull
#define FPMIN_LIDX_S                                                	0x18ull
#define FPMIN_LIDX                                                  	0x19ull
#define FPMAX_LIDX_S                                                	0x1aull
#define FPMAX_LIDX                                                  	0x1bull
#define FPADD_S                                                     	0x1cull
#define FPADD                                                       	0x1dull
#define IMIN_GIDX_S                                                 	0x30ull
#define IMIN_GIDX                                                   	0x31ull
#define IMAX_GIDX_S                                                 	0x32ull
#define IMAX_GIDX                                                   	0x33ull
#define FPMIN_GIDX_S                                                	0x38ull
#define FPMIN_GIDX                                                  	0x39ull
#define FPMAX_GIDX_S                                                	0x3aull
#define FPMAX_GIDX                                                  	0x3bull
#define GET                                                         	0x0ull
#define AFAND_S                                                     	0x40ull
#define AFAND                                                       	0x41ull
#define AFOR_S                                                      	0x42ull
#define AFOR                                                        	0x43ull
#define AFXOR_S                                                     	0x44ull
#define AFXOR                                                       	0x45ull
#define AFSWAP                                                      	0x46ull
#define AFSWAP_S                                                    	0x47ull
#define AFAX_S                                                      	0x48ull
#define AFAX                                                        	0x49ull
#define AFCSWAP_S                                                   	0x4aull
#define AFCSWAP                                                     	0x4bull
#define AFIMIN_S                                                    	0x50ull
#define AFIMIN                                                      	0x51ull
#define AFIMAX_S                                                    	0x52ull
#define AFIMAX                                                      	0x53ull
#define AFIADD_S                                                    	0x54ull
#define AFIADD                                                      	0x55ull
#define AFFPMIN_S                                                   	0x58ull
#define AFFPMIN                                                     	0x59ull
#define AFFPMAX_S                                                   	0x5aull
#define AFFPMAX                                                     	0x5bull
#define AFFPADD_S                                                   	0x5cull
#define AFFPADD                                                     	0x5dull
#define AFAND_SC                                                    	0x60ull
#define AFAND_C                                                     	0x61ull
#define AFOR_SC                                                     	0x62ull
#define AFOR_C                                                      	0x63ull
#define AFXOR_SC                                                    	0x64ull
#define AFXOR_C                                                     	0x65ull
#define AFSWAP_C                                                    	0x66ull
#define AFSWAP_SC                                                   	0x67ull
#define AFAX_SC                                                     	0x68ull
#define AFAX_C                                                      	0x69ull
#define AFCSWAP_SC                                                  	0x6aull
#define AFCSWAP_C                                                   	0x6bull
#define AFIMIN_SC                                                   	0x70ull
#define AFIMIN_C                                                    	0x71ull
#define AFIMAX_SC                                                   	0x72ull
#define AFIMAX_C                                                    	0x73ull
#define AFIADD_SC                                                   	0x74ull
#define AFIADD_C                                                    	0x75ull
#define AFFPMIN_SC                                                  	0x78ull
#define AFFPMIN_C                                                   	0x79ull
#define AFFPMAX_SC                                                  	0x7aull
#define AFFPMAX_C                                                   	0x7bull
#define AFFPADD_SC                                                  	0x7cull
#define AFFPADD_C                                                   	0x7dull

#endif
