/******************************************************************************
 * COPYRIGHT CRAY INC. ar_fma_mmrs_h.h
 * FILE: ar_fma_mmrs_h.h
 * Created by v2h.c on Wed Oct  8 14:38:59 2014
 ******************************************************************************/

#ifndef _AR_FMA_MMRS_H_H_
#define _AR_FMA_MMRS_H_H_

#ifdef __GNUC__
#define _unused __attribute__((unused))
#else
#define _unused
#endif

#ifndef _GENERIC_MMRD_T_
#define _GENERIC_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint64_t _mask;		/* Field bit mask */
} generic_mmrd_t;
#endif

#ifndef _ERRCAT_MMRD_T_
#define _ERRCAT_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint32_t _ec;		/* Field error category */
} errcat_mmrd_t;
#endif

#ifndef _GENERIC_MMR_T_
#define _GENERIC_MMR_T_
typedef struct {
	char* _name;		/* MMR name */
	uint64_t _addr;		/* MMR address */
	int _size;		/* Size in bytes of MMR */
	int _depth;		/* Number of MMR instances */
	const generic_mmrd_t *_info;	/* MMR detail */
} generic_mmr_t;
#endif

static const generic_mmr_t* _ar_fma_mmrs[] _unused;	/* FMA Array */

/*
 *  AR FMA MMR DETAIL DECLARATIONS
 */
static const generic_mmrd_t _ar_nic_fma_mmr_ring_0_hi_fma_detail[] = {
    { "UNUSED_145_35", AR_NIC_FMA_MMR_RING_0_HI_FMA_UNUSED_145_35_BP, AR_NIC_FMA_MMR_RING_0_HI_FMA_UNUSED_145_35_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_mmr_ring_0_mid_fma_detail[] = {
    { "UNUSED_127_98", AR_NIC_FMA_MMR_RING_0_MID_FMA_UNUSED_127_98_BP, AR_NIC_FMA_MMR_RING_0_MID_FMA_UNUSED_127_98_MASK },
    { "CNTR_TDATA_SBE", AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_TDATA_SBE_BP, AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_TDATA_SBE_MASK },
    { "CNTR_INV_CMD", AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_INV_CMD_BP, AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_INV_CMD_MASK },
    { "CNTR_DESC_MBE", AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_DESC_MBE_BP, AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_DESC_MBE_MASK },
    { "CNTR_DATA_MBE", AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_DATA_MBE_BP, AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_DATA_MBE_MASK },
    { "CNTR_HDR_PERR", AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_HDR_PERR_BP, AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_HDR_PERR_MASK },
    { "CNTR_NFAMO_REQ", AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_NFAMO_REQ_BP, AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_NFAMO_REQ_MASK },
    { "CNTR_PUT_REQ", AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_PUT_REQ_BP, AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_PUT_REQ_MASK },
    { "CNTR_FAMO_REQ", AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_FAMO_REQ_BP, AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_FAMO_REQ_MASK },
    { "CNTR_GET_REQ", AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_GET_REQ_BP, AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_GET_REQ_MASK },
    { "CNTR_CQ_STALL", AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_CQ_STALL_BP, AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_CQ_STALL_MASK },
    { "CNTR_CQ", AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_CQ_BP, AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_CQ_MASK },
    { "CNTR_PI_FLIT", AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_PI_FLIT_BP, AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_PI_FLIT_MASK },
    { "CNTR_PI_PKT", AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_PI_PKT_BP, AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_PI_PKT_MASK },
    { "CNTR_TARB_STALLED", AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_TARB_STALLED_BP, AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_TARB_STALLED_MASK },
    { "CNTR_FLIT", AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_FLIT_BP, AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_FLIT_MASK },
    { "CNTR_PKT", AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_PKT_BP, AR_NIC_FMA_MMR_RING_0_MID_FMA_CNTR_PKT_MASK },
    { "UNUSED_81_64", AR_NIC_FMA_MMR_RING_0_MID_FMA_UNUSED_81_64_BP, AR_NIC_FMA_MMR_RING_0_MID_FMA_UNUSED_81_64_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_mmr_ring_0_lo_fma_detail[] = {
    { "UNUSED_145_35", AR_NIC_FMA_MMR_RING_0_LO_FMA_UNUSED_145_35_BP, AR_NIC_FMA_MMR_RING_0_LO_FMA_UNUSED_145_35_MASK },
    { "OS_INTR_REQ", AR_NIC_FMA_MMR_RING_0_LO_FMA_OS_INTR_REQ_BP, AR_NIC_FMA_MMR_RING_0_LO_FMA_OS_INTR_REQ_MASK },
    { "HSS_INTR_REQ", AR_NIC_FMA_MMR_RING_0_LO_FMA_HSS_INTR_REQ_BP, AR_NIC_FMA_MMR_RING_0_LO_FMA_HSS_INTR_REQ_MASK },
    { "MMR_WR_ACK", AR_NIC_FMA_MMR_RING_0_LO_FMA_MMR_WR_ACK_BP, AR_NIC_FMA_MMR_RING_0_LO_FMA_MMR_WR_ACK_MASK },
    { "MMR_RESP_OUT", AR_NIC_FMA_MMR_RING_0_LO_FMA_MMR_RESP_OUT_BP, AR_NIC_FMA_MMR_RING_0_LO_FMA_MMR_RESP_OUT_MASK },
    { "MMR_REQ_IN", AR_NIC_FMA_MMR_RING_0_LO_FMA_MMR_REQ_IN_BP, AR_NIC_FMA_MMR_RING_0_LO_FMA_MMR_REQ_IN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_err_flg_1_hi_fma_detail[] = {
    { "UNUSED_145_110", AR_NIC_FMA_ERR_FLG_1_HI_FMA_UNUSED_145_110_BP, AR_NIC_FMA_ERR_FLG_1_HI_FMA_UNUSED_145_110_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_err_flg_1_mid_fma_detail[] = {
    { "UNUSED_127_110", AR_NIC_FMA_ERR_FLG_1_MID_FMA_UNUSED_127_110_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_UNUSED_127_110_MASK },
    { "SW_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_SW_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_SW_ERR_MASK },
    { "PI_PKT_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_PI_PKT_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_PI_PKT_ERR_MASK },
    { "PI_BYTE_PUT_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_PI_BYTE_PUT_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_PI_BYTE_PUT_ERR_MASK },
    { "AMO_BYTE_PUT_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_AMO_BYTE_PUT_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_AMO_BYTE_PUT_ERR_MASK },
    { "GCW_MBE_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_GCW_MBE_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_GCW_MBE_ERR_MASK },
    { "PI_GET_ADDR_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_PI_GET_ADDR_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_PI_GET_ADDR_ERR_MASK },
    { "FMA_LAUNCH_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_FMA_LAUNCH_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_FMA_LAUNCH_ERR_MASK },
    { "ADDR_ALIGN_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_ADDR_ALIGN_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_ADDR_ALIGN_ERR_MASK },
    { "GET_FR_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_GET_FR_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_GET_FR_ERR_MASK },
    { "GET_LEN_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_GET_LEN_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_GET_LEN_ERR_MASK },
    { "PUT_LEN_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_PUT_LEN_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_PUT_LEN_ERR_MASK },
    { "INV_COM_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_INV_COM_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_INV_COM_ERR_MASK },
    { "NPES_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_NPES_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_NPES_ERR_MASK },
    { "PI_ADDR_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_PI_ADDR_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_PI_ADDR_ERR_MASK },
    { "PI_LEN_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_PI_LEN_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_PI_LEN_ERR_MASK },
    { "SSID_INACTIVE_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_SSID_INACTIVE_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_SSID_INACTIVE_ERR_MASK },
    { "PI_CMD_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_PI_CMD_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_PI_CMD_ERR_MASK },
    { "DB_MBE_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DB_MBE_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DB_MBE_ERR_MASK },
    { "NOPRIV_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_NOPRIV_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_NOPRIV_ERR_MASK },
    { "SSID_ALLOCID_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_SSID_ALLOCID_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_SSID_ALLOCID_ERR_MASK },
    { "DESC_ENABLE_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC_ENABLE_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC_ENABLE_ERR_MASK },
    { "PI_BUF_OVERFLOW", AR_NIC_FMA_ERR_FLG_1_MID_FMA_PI_BUF_OVERFLOW_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_PI_BUF_OVERFLOW_MASK },
    { "DESC_WR_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC_WR_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC_WR_ERR_MASK },
    { "DESC_DB_WR_ERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC_DB_WR_ERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC_DB_WR_ERR_MASK },
    { "HDR_PERR", AR_NIC_FMA_ERR_FLG_1_MID_FMA_HDR_PERR_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_HDR_PERR_MASK },
    { "DATA1IN_MBE", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DATA1IN_MBE_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DATA1IN_MBE_MASK },
    { "DATA1IN_SBE", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DATA1IN_SBE_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DATA1IN_SBE_MASK },
    { "DATA0IN_MBE", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DATA0IN_MBE_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DATA0IN_MBE_MASK },
    { "DATA0IN_SBE", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DATA0IN_SBE_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DATA0IN_SBE_MASK },
    { "DESC88_MBE", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC88_MBE_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC88_MBE_MASK },
    { "DESC88_SBE", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC88_SBE_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC88_SBE_MASK },
    { "DESC38_MBE", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC38_MBE_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC38_MBE_MASK },
    { "DESC38_SBE", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC38_SBE_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC38_SBE_MASK },
    { "DESC28_MBE", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC28_MBE_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC28_MBE_MASK },
    { "DESC28_SBE", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC28_SBE_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC28_SBE_MASK },
    { "DESC20_MBE", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC20_MBE_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC20_MBE_MASK },
    { "DESC20_SBE", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC20_SBE_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC20_SBE_MASK },
    { "DESC18_MBE", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC18_MBE_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC18_MBE_MASK },
    { "DESC18_SBE", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC18_SBE_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC18_SBE_MASK },
    { "DESC10_MBE", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC10_MBE_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC10_MBE_MASK },
    { "DESC10_SBE", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC10_SBE_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC10_SBE_MASK },
    { "DESC08_MBE", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC08_MBE_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC08_MBE_MASK },
    { "DESC08_SBE", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC08_SBE_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC08_SBE_MASK },
    { "DESC00_MBE", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC00_MBE_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC00_MBE_MASK },
    { "DESC00_SBE", AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC00_SBE_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_DESC00_SBE_MASK },
    { "UNUSED_64", AR_NIC_FMA_ERR_FLG_1_MID_FMA_UNUSED_64_BP, AR_NIC_FMA_ERR_FLG_1_MID_FMA_UNUSED_64_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_err_flg_1_lo_fma_detail[] = {
    { "UNUSED_63_46", AR_NIC_FMA_ERR_FLG_1_LO_FMA_UNUSED_63_46_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_UNUSED_63_46_MASK },
    { "I_SW_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_SW_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_SW_ERR_MASK },
    { "I_PI_PKT_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_PI_PKT_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_PI_PKT_ERR_MASK },
    { "I_PI_BYTE_PUT_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_PI_BYTE_PUT_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_PI_BYTE_PUT_ERR_MASK },
    { "I_AMO_BYTE_PUT_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_AMO_BYTE_PUT_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_AMO_BYTE_PUT_ERR_MASK },
    { "I_GCW_MBE_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_GCW_MBE_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_GCW_MBE_ERR_MASK },
    { "I_PI_GET_ADDR_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_PI_GET_ADDR_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_PI_GET_ADDR_ERR_MASK },
    { "I_FMA_LAUNCH_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_FMA_LAUNCH_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_FMA_LAUNCH_ERR_MASK },
    { "I_ADDR_ALIGN_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_ADDR_ALIGN_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_ADDR_ALIGN_ERR_MASK },
    { "I_GET_FR_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_GET_FR_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_GET_FR_ERR_MASK },
    { "I_GET_LEN_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_GET_LEN_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_GET_LEN_ERR_MASK },
    { "I_PUT_LEN_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_PUT_LEN_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_PUT_LEN_ERR_MASK },
    { "I_INV_COM_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_INV_COM_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_INV_COM_ERR_MASK },
    { "I_NPES_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_NPES_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_NPES_ERR_MASK },
    { "I_PI_ADDR_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_PI_ADDR_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_PI_ADDR_ERR_MASK },
    { "I_PI_LEN_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_PI_LEN_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_PI_LEN_ERR_MASK },
    { "I_SSID_INACTIVE_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_SSID_INACTIVE_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_SSID_INACTIVE_ERR_MASK },
    { "I_PI_CMD_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_PI_CMD_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_PI_CMD_ERR_MASK },
    { "I_DB_MBE_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DB_MBE_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DB_MBE_ERR_MASK },
    { "I_NOPRIV_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_NOPRIV_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_NOPRIV_ERR_MASK },
    { "I_SSID_ALLOCID_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_SSID_ALLOCID_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_SSID_ALLOCID_ERR_MASK },
    { "I_DESC_ENABLE_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC_ENABLE_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC_ENABLE_ERR_MASK },
    { "I_PI_BUF_OVERFLOW", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_PI_BUF_OVERFLOW_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_PI_BUF_OVERFLOW_MASK },
    { "I_DESC_WR_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC_WR_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC_WR_ERR_MASK },
    { "I_DESC_DB_WR_ERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC_DB_WR_ERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC_DB_WR_ERR_MASK },
    { "I_HDR_PERR", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_HDR_PERR_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_HDR_PERR_MASK },
    { "I_DATA1IN_MBE", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DATA1IN_MBE_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DATA1IN_MBE_MASK },
    { "I_DATA1IN_SBE", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DATA1IN_SBE_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DATA1IN_SBE_MASK },
    { "I_DATA0IN_MBE", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DATA0IN_MBE_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DATA0IN_MBE_MASK },
    { "I_DATA0IN_SBE", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DATA0IN_SBE_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DATA0IN_SBE_MASK },
    { "I_DESC88_MBE", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC88_MBE_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC88_MBE_MASK },
    { "I_DESC88_SBE", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC88_SBE_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC88_SBE_MASK },
    { "I_DESC38_MBE", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC38_MBE_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC38_MBE_MASK },
    { "I_DESC38_SBE", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC38_SBE_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC38_SBE_MASK },
    { "I_DESC28_MBE", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC28_MBE_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC28_MBE_MASK },
    { "I_DESC28_SBE", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC28_SBE_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC28_SBE_MASK },
    { "I_DESC20_MBE", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC20_MBE_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC20_MBE_MASK },
    { "I_DESC20_SBE", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC20_SBE_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC20_SBE_MASK },
    { "I_DESC18_MBE", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC18_MBE_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC18_MBE_MASK },
    { "I_DESC18_SBE", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC18_SBE_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC18_SBE_MASK },
    { "I_DESC10_MBE", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC10_MBE_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC10_MBE_MASK },
    { "I_DESC10_SBE", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC10_SBE_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC10_SBE_MASK },
    { "I_DESC08_MBE", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC08_MBE_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC08_MBE_MASK },
    { "I_DESC08_SBE", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC08_SBE_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC08_SBE_MASK },
    { "I_DESC00_MBE", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC00_MBE_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC00_MBE_MASK },
    { "I_DESC00_SBE", AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC00_SBE_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_I_DESC00_SBE_MASK },
    { "UNUSED_0", AR_NIC_FMA_ERR_FLG_1_LO_FMA_UNUSED_0_BP, AR_NIC_FMA_ERR_FLG_1_LO_FMA_UNUSED_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_pi_flit_input_stage_2_hi_fma_detail[] = {
    { "I_PI_NIC_REQ_SB", AR_NIC_FMA_PI_FLIT_INPUT_STAGE_2_HI_FMA_I_PI_NIC_REQ_SB_BP, AR_NIC_FMA_PI_FLIT_INPUT_STAGE_2_HI_FMA_I_PI_NIC_REQ_SB_MASK },
    { "I_PI_NIC_REQ_FLIT", AR_NIC_FMA_PI_FLIT_INPUT_STAGE_2_HI_FMA_I_PI_NIC_REQ_FLIT_BP, AR_NIC_FMA_PI_FLIT_INPUT_STAGE_2_HI_FMA_I_PI_NIC_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_pi_flit_input_stage_2_mid_fma_detail[] = {
    { "I_PI_NIC_REQ_FLIT", AR_NIC_FMA_PI_FLIT_INPUT_STAGE_2_MID_FMA_I_PI_NIC_REQ_FLIT_BP, AR_NIC_FMA_PI_FLIT_INPUT_STAGE_2_MID_FMA_I_PI_NIC_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_pi_flit_input_stage_2_lo_fma_detail[] = {
    { "I_PI_NIC_REQ_FLIT", AR_NIC_FMA_PI_FLIT_INPUT_STAGE_2_LO_FMA_I_PI_NIC_REQ_FLIT_BP, AR_NIC_FMA_PI_FLIT_INPUT_STAGE_2_LO_FMA_I_PI_NIC_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_pi_control_decode_desc_read_stage_4_hi_fma_detail[] = {
    { "UNUSED_145_96", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_HI_FMA_UNUSED_145_96_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_HI_FMA_UNUSED_145_96_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_pi_control_decode_desc_read_stage_4_mid_fma_detail[] = {
    { "UNUSED_145_96", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_UNUSED_145_96_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_UNUSED_145_96_MASK },
    { "R_GO_DLA_MARKER_HDR_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_GO_DLA_MARKER_HDR_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_GO_DLA_MARKER_HDR_SG3_MASK },
    { "R_WR_88_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_WR_88_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_WR_88_SG3_MASK },
    { "R_RD_88_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_RD_88_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_RD_88_SG3_MASK },
    { "R_Q_NIC_PI_REQ_ACK", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_Q_NIC_PI_REQ_ACK_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_Q_NIC_PI_REQ_ACK_MASK },
    { "R_PI_REWIND", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_PI_REWIND_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_PI_REWIND_MASK },
    { "R_PI_HOLD", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_PI_HOLD_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_PI_HOLD_MASK },
    { "R_VALID_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_VALID_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_VALID_SG3_MASK },
    { "R_HEADER_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_HEADER_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_HEADER_SG3_MASK },
    { "R_ERR_RECVD_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_ERR_RECVD_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_ERR_RECVD_SG3_MASK },
    { "R_GO_WN_HDR_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_GO_WN_HDR_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_GO_WN_HDR_SG3_MASK },
    { "R_GO_WN_DTF_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_GO_WN_DTF_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_GO_WN_DTF_SG3_MASK },
    { "R_USER_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_USER_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_USER_SG3_MASK },
    { "R_GO_CQ_WINDOW_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_GO_CQ_WINDOW_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_GO_CQ_WINDOW_SG3_MASK },
    { "R_ALLOC_SSID_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_ALLOC_SSID_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_ALLOC_SSID_SG3_MASK },
    { "R_CQWRITE_HDR_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_CQWRITE_HDR_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_CQWRITE_HDR_SG3_MASK },
    { "R_CQWRITE_DTF_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_CQWRITE_DTF_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_CQWRITE_DTF_SG3_MASK },
    { "R_GO_FLBTE_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_GO_FLBTE_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_GO_FLBTE_SG3_MASK },
    { "R_WR_STAT_WHEN_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_WR_STAT_WHEN_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_WR_STAT_WHEN_SG3_MASK },
    { "R_CE_HDR_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_CE_HDR_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_CE_HDR_SG3_MASK },
    { "R_CE_DTF_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_CE_DTF_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_CE_DTF_SG3_MASK },
    { "R_GO_SEQCMP_HDR_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_GO_SEQCMP_HDR_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_GO_SEQCMP_HDR_SG3_MASK },
    { "R_SEQCMP_DTF_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_SEQCMP_DTF_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_SEQCMP_DTF_SG3_MASK },
    { "R_GO_MMR_RD_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_GO_MMR_RD_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_GO_MMR_RD_SG3_MASK },
    { "R_GO_MMR_WR_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_GO_MMR_WR_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_GO_MMR_WR_SG3_MASK },
    { "R_FMA_LAUNCH0", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_FMA_LAUNCH0_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_FMA_LAUNCH0_MASK },
    { "R_FMA_LAUNCH1", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_FMA_LAUNCH1_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_FMA_LAUNCH1_MASK },
    { "R_GO_WR_STAT_REQ_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_GO_WR_STAT_REQ_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_GO_WR_STAT_REQ_SG3_MASK },
    { "R_SEQ_ACTIVE_READ_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_SEQ_ACTIVE_READ_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_SEQ_ACTIVE_READ_SG3_MASK },
    { "R_DESCRIPTOR_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_DESCRIPTOR_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA_R_DESCRIPTOR_SG3_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_pi_control_decode_desc_read_stage_4_lo_fma_detail[] = {
    { "R_DESCRIPTOR_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_DESCRIPTOR_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_DESCRIPTOR_SG3_MASK },
    { "R_ADDRESS_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_ADDRESS_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_ADDRESS_SG3_MASK },
    { "R_Q_DATA0_2ODD", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_Q_DATA0_2ODD_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_Q_DATA0_2ODD_MASK },
    { "R_WR_00_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_WR_00_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_WR_00_SG3_MASK },
    { "R_WR_08_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_WR_08_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_WR_08_SG3_MASK },
    { "R_WR_10_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_WR_10_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_WR_10_SG3_MASK },
    { "R_WR_18_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_WR_18_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_WR_18_SG3_MASK },
    { "R_WR_20_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_WR_20_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_WR_20_SG3_MASK },
    { "R_WR_28_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_WR_28_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_WR_28_SG3_MASK },
    { "R_WR_38_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_WR_38_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_WR_38_SG3_MASK },
    { "R_WR_80_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_WR_80_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_WR_80_SG3_MASK },
    { "R_RD_00_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_RD_00_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_RD_00_SG3_MASK },
    { "R_RD_08_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_RD_08_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_RD_08_SG3_MASK },
    { "R_RD_10_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_RD_10_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_RD_10_SG3_MASK },
    { "R_RD_18_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_RD_18_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_RD_18_SG3_MASK },
    { "R_RD_20_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_RD_20_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_RD_20_SG3_MASK },
    { "R_RD_28_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_RD_28_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_RD_28_SG3_MASK },
    { "R_RD_38_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_RD_38_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_RD_38_SG3_MASK },
    { "R_RD_80_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_RD_80_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_RD_80_SG3_MASK },
    { "R_TAIL_FLIT_SG3", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_TAIL_FLIT_SG3_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_TAIL_FLIT_SG3_MASK },
    { "R_Q_MMR_HDR_PERR", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_Q_MMR_HDR_PERR_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_Q_MMR_HDR_PERR_MASK },
    { "R_Q_MMR_HDR_COM_ERR", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_Q_MMR_HDR_COM_ERR_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_Q_MMR_HDR_COM_ERR_MASK },
    { "R_Q_MMR_HDR_ADR_ERR", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_Q_MMR_HDR_ADR_ERR_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_Q_MMR_HDR_ADR_ERR_MASK },
    { "R_Q_MMR_HDR_LEN_ERR", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_Q_MMR_HDR_LEN_ERR_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_Q_MMR_HDR_LEN_ERR_MASK },
    { "R_Q_MMR_DATA0_SBE", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_Q_MMR_DATA0_SBE_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_Q_MMR_DATA0_SBE_MASK },
    { "R_Q_MMR_DATA0_MBE", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_Q_MMR_DATA0_MBE_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_Q_MMR_DATA0_MBE_MASK },
    { "R_Q_MMR_DATA1_SBE", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_Q_MMR_DATA1_SBE_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_Q_MMR_DATA1_SBE_MASK },
    { "R_Q_MMR_DATA1_MBE", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_Q_MMR_DATA1_MBE_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_Q_MMR_DATA1_MBE_MASK },
    { "R_Q_DESC_OP_ERR", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_Q_DESC_OP_ERR_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_Q_DESC_OP_ERR_MASK },
    { "R_Q_DESC_DB_ERR", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_Q_DESC_DB_ERR_BP, AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA_R_Q_DESC_DB_ERR_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_pi_control_data_desc_read_stage_5_hi_fma_detail[] = {
    { "UNUSED_145_144", AR_NIC_FMA_PI_CONTROL_DATA_DESC_READ_STAGE_5_HI_FMA_UNUSED_145_144_BP, AR_NIC_FMA_PI_CONTROL_DATA_DESC_READ_STAGE_5_HI_FMA_UNUSED_145_144_MASK },
    { "R_ECC1_SG3", AR_NIC_FMA_PI_CONTROL_DATA_DESC_READ_STAGE_5_HI_FMA_R_ECC1_SG3_BP, AR_NIC_FMA_PI_CONTROL_DATA_DESC_READ_STAGE_5_HI_FMA_R_ECC1_SG3_MASK },
    { "R_DATA1_SG3", AR_NIC_FMA_PI_CONTROL_DATA_DESC_READ_STAGE_5_HI_FMA_R_DATA1_SG3_BP, AR_NIC_FMA_PI_CONTROL_DATA_DESC_READ_STAGE_5_HI_FMA_R_DATA1_SG3_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_pi_control_data_desc_read_stage_5_mid_fma_detail[] = {
    { "R_DATA1_SG3", AR_NIC_FMA_PI_CONTROL_DATA_DESC_READ_STAGE_5_MID_FMA_R_DATA1_SG3_BP, AR_NIC_FMA_PI_CONTROL_DATA_DESC_READ_STAGE_5_MID_FMA_R_DATA1_SG3_MASK },
    { "R_ECC0_SG3", AR_NIC_FMA_PI_CONTROL_DATA_DESC_READ_STAGE_5_MID_FMA_R_ECC0_SG3_BP, AR_NIC_FMA_PI_CONTROL_DATA_DESC_READ_STAGE_5_MID_FMA_R_ECC0_SG3_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_pi_control_data_desc_read_stage_5_lo_fma_detail[] = {
    { "R_DATA0_SG3", AR_NIC_FMA_PI_CONTROL_DATA_DESC_READ_STAGE_5_LO_FMA_R_DATA0_SG3_BP, AR_NIC_FMA_PI_CONTROL_DATA_DESC_READ_STAGE_5_LO_FMA_R_DATA0_SG3_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_packet_generation_tarb_write_stage_6_hi_fma_detail[] = {
    { "UNUSED_145_82", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_HI_FMA_UNUSED_145_82_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_HI_FMA_UNUSED_145_82_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_packet_generation_tarb_write_stage_6_mid_fma_detail[] = {
    { "UNUSED_145_82", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_UNUSED_145_82_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_UNUSED_145_82_MASK },
    { "I_DESC_SG6", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_I_DESC_SG6_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_I_DESC_SG6_MASK },
    { "R_HDR", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_R_HDR_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_R_HDR_MASK },
    { "R_LAUNCH", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_R_LAUNCH_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_R_LAUNCH_MASK },
    { "R_GET", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_R_GET_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_R_GET_MASK },
    { "R_PUT", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_R_PUT_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_R_PUT_MASK },
    { "R_AMO", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_R_AMO_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_R_AMO_MASK },
    { "R_STAT_REQ", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_R_STAT_REQ_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_R_STAT_REQ_MASK },
    { "R_AMO_2OPS", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_R_AMO_2OPS_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_R_AMO_2OPS_MASK },
    { "R_32BIT_AMO_CE", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_R_32BIT_AMO_CE_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_R_32BIT_AMO_CE_MASK },
    { "R_64BIT", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_R_64BIT_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_R_64BIT_MASK },
    { "R_REQ_COUNT", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_R_REQ_COUNT_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA_R_REQ_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_packet_generation_tarb_write_stage_6_lo_fma_detail[] = {
    { "R_REQ_COUNT", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_REQ_COUNT_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_REQ_COUNT_MASK },
    { "R_GOP0_SG6", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_GOP0_SG6_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_GOP0_SG6_MASK },
    { "R_GCW0_COUNT", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_GCW0_COUNT_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_GCW0_COUNT_MASK },
    { "R_GCW0_MBE", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_GCW0_MBE_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_GCW0_MBE_MASK },
    { "R_GCW0_COUNT_ERR", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_GCW0_COUNT_ERR_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_GCW0_COUNT_ERR_MASK },
    { "R_GOP1_SG6", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_GOP1_SG6_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_GOP1_SG6_MASK },
    { "R_GCW1_COUNT", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_GCW1_COUNT_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_GCW1_COUNT_MASK },
    { "R_GCW1_MBE", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_GCW1_MBE_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_GCW1_MBE_MASK },
    { "R_GCW1_COUNT_ERR", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_GCW1_COUNT_ERR_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_GCW1_COUNT_ERR_MASK },
    { "R_DTF", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_DTF_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_DTF_MASK },
    { "R_TAIL", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_TAIL_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_TAIL_MASK },
    { "R_CE_DTF1", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_CE_DTF1_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_CE_DTF1_MASK },
    { "R_SEND_FLAG_DATA", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_SEND_FLAG_DATA_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_SEND_FLAG_DATA_MASK },
    { "R_SEND_CE_IDX", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_SEND_CE_IDX_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_SEND_CE_IDX_MASK },
    { "R_SEND_CE_OP2", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_SEND_CE_OP2_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_SEND_CE_OP2_MASK },
    { "R_LAF1_VALID", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_LAF1_VALID_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_LAF1_VALID_MASK },
    { "R_Q_INC_RC0", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_INC_RC0_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_INC_RC0_MASK },
    { "R_Q_INC_WC0", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_INC_WC0_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_INC_WC0_MASK },
    { "R_Q_COUNT0", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_COUNT0_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_COUNT0_MASK },
    { "R_Q_INC_RC1", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_INC_RC1_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_INC_RC1_MASK },
    { "R_Q_INC_WC1", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_INC_WC1_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_INC_WC1_MASK },
    { "R_Q_SW_ERR_1", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_SW_ERR_1_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_SW_ERR_1_MASK },
    { "R_Q_NPES_ERR", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_NPES_ERR_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_NPES_ERR_MASK },
    { "R_Q_SEQID_ERR", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_SEQID_ERR_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_SEQID_ERR_MASK },
    { "R_Q_SSID_AA_ERR", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_SSID_AA_ERR_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_SSID_AA_ERR_MASK },
    { "R_Q_SSID_NA_ERR", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_SSID_NA_ERR_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_SSID_NA_ERR_MASK },
    { "R_Q_ENABLE_ERR", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_ENABLE_ERR_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_ENABLE_ERR_MASK },
    { "R_Q_FR_LEN_ERR", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_FR_LEN_ERR_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_FR_LEN_ERR_MASK },
    { "R_Q_GET_LEN_ERR", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_GET_LEN_ERR_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_GET_LEN_ERR_MASK },
    { "R_Q_PUT_LEN_ERR", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_PUT_LEN_ERR_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_PUT_LEN_ERR_MASK },
    { "R_Q_INV_COM_ERR", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_INV_COM_ERR_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_INV_COM_ERR_MASK },
    { "R_Q_ALIGN_ERR", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_ALIGN_ERR_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_ALIGN_ERR_MASK },
    { "R_Q_LAUNCH_ERR", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_LAUNCH_ERR_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_LAUNCH_ERR_MASK },
    { "R_Q_WR_STAT_WHEN", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_WR_STAT_WHEN_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_WR_STAT_WHEN_MASK },
    { "R_Q_WR_STAT_WHEN_MODE", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_WR_STAT_WHEN_MODE_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_WR_STAT_WHEN_MODE_MASK },
    { "UNUSED_1", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_UNUSED_1_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_UNUSED_1_MASK },
    { "R_Q_FMA_BTE_VALID", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_FMA_BTE_VALID_BP, AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA_R_Q_FMA_BTE_VALID_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_tarb_rd_data_stage_7_hi_fma_detail[] = {
    { "UNUSED_145_64", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_HI_FMA_UNUSED_145_64_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_HI_FMA_UNUSED_145_64_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_tarb_rd_data_stage_7_mid_fma_detail[] = {
    { "UNUSED_145_64", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_MID_FMA_UNUSED_145_64_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_MID_FMA_UNUSED_145_64_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_tarb_rd_data_stage_7_lo_fma_detail[] = {
    { "Q_GET_ACTIVE", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_GET_ACTIVE_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_GET_ACTIVE_MASK },
    { "Q_READ_PKT", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_READ_PKT_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_READ_PKT_MASK },
    { "Q_GET_LAF1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_GET_LAF1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_GET_LAF1_MASK },
    { "Q_GET_DONE", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_GET_DONE_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_GET_DONE_MASK },
    { "Q_START_PUT_AAX_MODE", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_START_PUT_AAX_MODE_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_START_PUT_AAX_MODE_MASK },
    { "Q_PUT_AMO_ACTIVE", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_PUT_AMO_ACTIVE_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_PUT_AMO_ACTIVE_MASK },
    { "Q_PUT_AMO_DONE", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_PUT_AMO_DONE_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_PUT_AMO_DONE_MASK },
    { "Q_START_PUT_AMO", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_START_PUT_AMO_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_START_PUT_AMO_MASK },
    { "Q_ADD_DATA", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_ADD_DATA_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_ADD_DATA_MASK },
    { "Q_64BIT", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_64BIT_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_64BIT_MASK },
    { "Q_2OP_PUT_AMO", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_2OP_PUT_AMO_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_2OP_PUT_AMO_MASK },
    { "Q_PUT_AMO_PTR", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_PUT_AMO_PTR_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_PUT_AMO_PTR_MASK },
    { "Q_PUT_AMO_NEXT_FLIT", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_PUT_AMO_NEXT_FLIT_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_PUT_AMO_NEXT_FLIT_MASK },
    { "Q_PEND_REQ_COUNT", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_PEND_REQ_COUNT_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_PEND_REQ_COUNT_MASK },
    { "Q_GO_READ_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_GO_READ_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_GO_READ_SG1_MASK },
    { "Q_HEADER_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_HEADER_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_HEADER_SG1_MASK },
    { "Q_LAUNCH_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_LAUNCH_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_LAUNCH_SG1_MASK },
    { "Q_START_GET", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_START_GET_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_START_GET_MASK },
    { "Q_GOP0_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_GOP0_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_GOP0_SG1_MASK },
    { "Q_CNT0_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_CNT0_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_CNT0_SG1_MASK },
    { "Q_GCW0_MBE_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_GCW0_MBE_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_GCW0_MBE_SG1_MASK },
    { "Q_GCW0_COUNT_ERR_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_GCW0_COUNT_ERR_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_GCW0_COUNT_ERR_SG1_MASK },
    { "Q_GOP1_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_GOP1_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_GOP1_SG1_MASK },
    { "Q_CNT1_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_CNT1_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_CNT1_SG1_MASK },
    { "Q_GCW1_MBE_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_GCW1_MBE_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_GCW1_MBE_SG1_MASK },
    { "Q_GCW1_COUNT_ERR_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_GCW1_COUNT_ERR_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_GCW1_COUNT_ERR_SG1_MASK },
    { "Q_TAIL_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_TAIL_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_TAIL_SG1_MASK },
    { "Q_SEND_HDR_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_SEND_HDR_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_SEND_HDR_SG1_MASK },
    { "Q_SEND_LAF_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_SEND_LAF_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_SEND_LAF_SG1_MASK },
    { "Q_SEND_LAF1_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_SEND_LAF1_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_SEND_LAF1_SG1_MASK },
    { "Q_DATA_READ_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_DATA_READ_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_DATA_READ_SG1_MASK },
    { "Q_ADD_DATA_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_ADD_DATA_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_ADD_DATA_SG1_MASK },
    { "Q_SEND_PUT_AMO_DATA_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_SEND_PUT_AMO_DATA_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_SEND_PUT_AMO_DATA_SG1_MASK },
    { "Q_SEND_GET_AMO_DATA_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_SEND_GET_AMO_DATA_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_SEND_GET_AMO_DATA_SG1_MASK },
    { "Q_PUT_AMO_PTR_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_PUT_AMO_PTR_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_PUT_AMO_PTR_SG1_MASK },
    { "Q_64BIT_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_64BIT_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_64BIT_SG1_MASK },
    { "Q_2OP_PUT_AMO_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_2OP_PUT_AMO_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_2OP_PUT_AMO_SG1_MASK },
    { "Q_2OP_GET_AMO_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_2OP_GET_AMO_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_2OP_GET_AMO_SG1_MASK },
    { "Q_64BIT_GET_AMO_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_64BIT_GET_AMO_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_64BIT_GET_AMO_SG1_MASK },
    { "Q_64BIT_PUT_AMO_SG1", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_64BIT_PUT_AMO_SG1_BP, AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA_Q_64BIT_PUT_AMO_SG1_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_err_flg_detail[] = {
    { "SW_ERR", AR_NIC_FMA_ERR_FLG_SW_ERR_BP, AR_NIC_FMA_ERR_FLG_SW_ERR_MASK },
    { "PI_PKT_ERR", AR_NIC_FMA_ERR_FLG_PI_PKT_ERR_BP, AR_NIC_FMA_ERR_FLG_PI_PKT_ERR_MASK },
    { "PI_BYTE_PUT_ERR", AR_NIC_FMA_ERR_FLG_PI_BYTE_PUT_ERR_BP, AR_NIC_FMA_ERR_FLG_PI_BYTE_PUT_ERR_MASK },
    { "AMO_BYTE_PUT_ERR", AR_NIC_FMA_ERR_FLG_AMO_BYTE_PUT_ERR_BP, AR_NIC_FMA_ERR_FLG_AMO_BYTE_PUT_ERR_MASK },
    { "GCW_MBE_ERR", AR_NIC_FMA_ERR_FLG_GCW_MBE_ERR_BP, AR_NIC_FMA_ERR_FLG_GCW_MBE_ERR_MASK },
    { "PI_GET_ADDR_ERR", AR_NIC_FMA_ERR_FLG_PI_GET_ADDR_ERR_BP, AR_NIC_FMA_ERR_FLG_PI_GET_ADDR_ERR_MASK },
    { "FMA_LAUNCH_ERR", AR_NIC_FMA_ERR_FLG_FMA_LAUNCH_ERR_BP, AR_NIC_FMA_ERR_FLG_FMA_LAUNCH_ERR_MASK },
    { "ADDR_ALIGN_ERR", AR_NIC_FMA_ERR_FLG_ADDR_ALIGN_ERR_BP, AR_NIC_FMA_ERR_FLG_ADDR_ALIGN_ERR_MASK },
    { "GET_FR_ERR", AR_NIC_FMA_ERR_FLG_GET_FR_ERR_BP, AR_NIC_FMA_ERR_FLG_GET_FR_ERR_MASK },
    { "GET_LEN_ERR", AR_NIC_FMA_ERR_FLG_GET_LEN_ERR_BP, AR_NIC_FMA_ERR_FLG_GET_LEN_ERR_MASK },
    { "PUT_LEN_ERR", AR_NIC_FMA_ERR_FLG_PUT_LEN_ERR_BP, AR_NIC_FMA_ERR_FLG_PUT_LEN_ERR_MASK },
    { "INV_COM_ERR", AR_NIC_FMA_ERR_FLG_INV_COM_ERR_BP, AR_NIC_FMA_ERR_FLG_INV_COM_ERR_MASK },
    { "NPES_ERR", AR_NIC_FMA_ERR_FLG_NPES_ERR_BP, AR_NIC_FMA_ERR_FLG_NPES_ERR_MASK },
    { "PI_ADDR_ERR", AR_NIC_FMA_ERR_FLG_PI_ADDR_ERR_BP, AR_NIC_FMA_ERR_FLG_PI_ADDR_ERR_MASK },
    { "PI_LEN_ERR", AR_NIC_FMA_ERR_FLG_PI_LEN_ERR_BP, AR_NIC_FMA_ERR_FLG_PI_LEN_ERR_MASK },
    { "SSID_INACTIVE_ERR", AR_NIC_FMA_ERR_FLG_SSID_INACTIVE_ERR_BP, AR_NIC_FMA_ERR_FLG_SSID_INACTIVE_ERR_MASK },
    { "PI_CMD_ERR", AR_NIC_FMA_ERR_FLG_PI_CMD_ERR_BP, AR_NIC_FMA_ERR_FLG_PI_CMD_ERR_MASK },
    { "DB_MBE_ERR", AR_NIC_FMA_ERR_FLG_DB_MBE_ERR_BP, AR_NIC_FMA_ERR_FLG_DB_MBE_ERR_MASK },
    { "NOPRIV_ERR", AR_NIC_FMA_ERR_FLG_NOPRIV_ERR_BP, AR_NIC_FMA_ERR_FLG_NOPRIV_ERR_MASK },
    { "SSID_ALLOCID_ERR", AR_NIC_FMA_ERR_FLG_SSID_ALLOCID_ERR_BP, AR_NIC_FMA_ERR_FLG_SSID_ALLOCID_ERR_MASK },
    { "DESC_ENABLE_ERR", AR_NIC_FMA_ERR_FLG_DESC_ENABLE_ERR_BP, AR_NIC_FMA_ERR_FLG_DESC_ENABLE_ERR_MASK },
    { "PI_BUF_OVERFLOW", AR_NIC_FMA_ERR_FLG_PI_BUF_OVERFLOW_BP, AR_NIC_FMA_ERR_FLG_PI_BUF_OVERFLOW_MASK },
    { "DESC_WR_ERR", AR_NIC_FMA_ERR_FLG_DESC_WR_ERR_BP, AR_NIC_FMA_ERR_FLG_DESC_WR_ERR_MASK },
    { "DESC_DB_WR_ERR", AR_NIC_FMA_ERR_FLG_DESC_DB_WR_ERR_BP, AR_NIC_FMA_ERR_FLG_DESC_DB_WR_ERR_MASK },
    { "HDR_PERR", AR_NIC_FMA_ERR_FLG_HDR_PERR_BP, AR_NIC_FMA_ERR_FLG_HDR_PERR_MASK },
    { "DATA1IN_MBE", AR_NIC_FMA_ERR_FLG_DATA1IN_MBE_BP, AR_NIC_FMA_ERR_FLG_DATA1IN_MBE_MASK },
    { "DATA1IN_SBE", AR_NIC_FMA_ERR_FLG_DATA1IN_SBE_BP, AR_NIC_FMA_ERR_FLG_DATA1IN_SBE_MASK },
    { "DATA0IN_MBE", AR_NIC_FMA_ERR_FLG_DATA0IN_MBE_BP, AR_NIC_FMA_ERR_FLG_DATA0IN_MBE_MASK },
    { "DATA0IN_SBE", AR_NIC_FMA_ERR_FLG_DATA0IN_SBE_BP, AR_NIC_FMA_ERR_FLG_DATA0IN_SBE_MASK },
    { "DESC88_MBE", AR_NIC_FMA_ERR_FLG_DESC88_MBE_BP, AR_NIC_FMA_ERR_FLG_DESC88_MBE_MASK },
    { "DESC88_SBE", AR_NIC_FMA_ERR_FLG_DESC88_SBE_BP, AR_NIC_FMA_ERR_FLG_DESC88_SBE_MASK },
    { "DESC38_MBE", AR_NIC_FMA_ERR_FLG_DESC38_MBE_BP, AR_NIC_FMA_ERR_FLG_DESC38_MBE_MASK },
    { "DESC38_SBE", AR_NIC_FMA_ERR_FLG_DESC38_SBE_BP, AR_NIC_FMA_ERR_FLG_DESC38_SBE_MASK },
    { "DESC28_MBE", AR_NIC_FMA_ERR_FLG_DESC28_MBE_BP, AR_NIC_FMA_ERR_FLG_DESC28_MBE_MASK },
    { "DESC28_SBE", AR_NIC_FMA_ERR_FLG_DESC28_SBE_BP, AR_NIC_FMA_ERR_FLG_DESC28_SBE_MASK },
    { "DESC20_MBE", AR_NIC_FMA_ERR_FLG_DESC20_MBE_BP, AR_NIC_FMA_ERR_FLG_DESC20_MBE_MASK },
    { "DESC20_SBE", AR_NIC_FMA_ERR_FLG_DESC20_SBE_BP, AR_NIC_FMA_ERR_FLG_DESC20_SBE_MASK },
    { "DESC18_MBE", AR_NIC_FMA_ERR_FLG_DESC18_MBE_BP, AR_NIC_FMA_ERR_FLG_DESC18_MBE_MASK },
    { "DESC18_SBE", AR_NIC_FMA_ERR_FLG_DESC18_SBE_BP, AR_NIC_FMA_ERR_FLG_DESC18_SBE_MASK },
    { "DESC10_MBE", AR_NIC_FMA_ERR_FLG_DESC10_MBE_BP, AR_NIC_FMA_ERR_FLG_DESC10_MBE_MASK },
    { "DESC10_SBE", AR_NIC_FMA_ERR_FLG_DESC10_SBE_BP, AR_NIC_FMA_ERR_FLG_DESC10_SBE_MASK },
    { "DESC08_MBE", AR_NIC_FMA_ERR_FLG_DESC08_MBE_BP, AR_NIC_FMA_ERR_FLG_DESC08_MBE_MASK },
    { "DESC08_SBE", AR_NIC_FMA_ERR_FLG_DESC08_SBE_BP, AR_NIC_FMA_ERR_FLG_DESC08_SBE_MASK },
    { "DESC00_MBE", AR_NIC_FMA_ERR_FLG_DESC00_MBE_BP, AR_NIC_FMA_ERR_FLG_DESC00_MBE_MASK },
    { "DESC00_SBE", AR_NIC_FMA_ERR_FLG_DESC00_SBE_BP, AR_NIC_FMA_ERR_FLG_DESC00_SBE_MASK },
    { "DIAG_ONLY", AR_NIC_FMA_ERR_FLG_DIAG_ONLY_BP, AR_NIC_FMA_ERR_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
#ifdef EXCEPTIONS_DEFS
static const errcat_mmrd_t _ar_nic_fma_err_flg_errcat[] = {
    { "SW_ERR", AR_NIC_FMA_ERR_FLG_SW_ERR_BP, AR_NIC_FMA_ERR_FLG_SW_ERR_EC },
    { "PI_PKT_ERR", AR_NIC_FMA_ERR_FLG_PI_PKT_ERR_BP, AR_NIC_FMA_ERR_FLG_PI_PKT_ERR_EC },
    { "PI_BYTE_PUT_ERR", AR_NIC_FMA_ERR_FLG_PI_BYTE_PUT_ERR_BP, AR_NIC_FMA_ERR_FLG_PI_BYTE_PUT_ERR_EC },
    { "AMO_BYTE_PUT_ERR", AR_NIC_FMA_ERR_FLG_AMO_BYTE_PUT_ERR_BP, AR_NIC_FMA_ERR_FLG_AMO_BYTE_PUT_ERR_EC },
    { "GCW_MBE_ERR", AR_NIC_FMA_ERR_FLG_GCW_MBE_ERR_BP, AR_NIC_FMA_ERR_FLG_GCW_MBE_ERR_EC },
    { "PI_GET_ADDR_ERR", AR_NIC_FMA_ERR_FLG_PI_GET_ADDR_ERR_BP, AR_NIC_FMA_ERR_FLG_PI_GET_ADDR_ERR_EC },
    { "FMA_LAUNCH_ERR", AR_NIC_FMA_ERR_FLG_FMA_LAUNCH_ERR_BP, AR_NIC_FMA_ERR_FLG_FMA_LAUNCH_ERR_EC },
    { "ADDR_ALIGN_ERR", AR_NIC_FMA_ERR_FLG_ADDR_ALIGN_ERR_BP, AR_NIC_FMA_ERR_FLG_ADDR_ALIGN_ERR_EC },
    { "GET_FR_ERR", AR_NIC_FMA_ERR_FLG_GET_FR_ERR_BP, AR_NIC_FMA_ERR_FLG_GET_FR_ERR_EC },
    { "GET_LEN_ERR", AR_NIC_FMA_ERR_FLG_GET_LEN_ERR_BP, AR_NIC_FMA_ERR_FLG_GET_LEN_ERR_EC },
    { "PUT_LEN_ERR", AR_NIC_FMA_ERR_FLG_PUT_LEN_ERR_BP, AR_NIC_FMA_ERR_FLG_PUT_LEN_ERR_EC },
    { "INV_COM_ERR", AR_NIC_FMA_ERR_FLG_INV_COM_ERR_BP, AR_NIC_FMA_ERR_FLG_INV_COM_ERR_EC },
    { "NPES_ERR", AR_NIC_FMA_ERR_FLG_NPES_ERR_BP, AR_NIC_FMA_ERR_FLG_NPES_ERR_EC },
    { "PI_ADDR_ERR", AR_NIC_FMA_ERR_FLG_PI_ADDR_ERR_BP, AR_NIC_FMA_ERR_FLG_PI_ADDR_ERR_EC },
    { "PI_LEN_ERR", AR_NIC_FMA_ERR_FLG_PI_LEN_ERR_BP, AR_NIC_FMA_ERR_FLG_PI_LEN_ERR_EC },
    { "SSID_INACTIVE_ERR", AR_NIC_FMA_ERR_FLG_SSID_INACTIVE_ERR_BP, AR_NIC_FMA_ERR_FLG_SSID_INACTIVE_ERR_EC },
    { "PI_CMD_ERR", AR_NIC_FMA_ERR_FLG_PI_CMD_ERR_BP, AR_NIC_FMA_ERR_FLG_PI_CMD_ERR_EC },
    { "DB_MBE_ERR", AR_NIC_FMA_ERR_FLG_DB_MBE_ERR_BP, AR_NIC_FMA_ERR_FLG_DB_MBE_ERR_EC },
    { "NOPRIV_ERR", AR_NIC_FMA_ERR_FLG_NOPRIV_ERR_BP, AR_NIC_FMA_ERR_FLG_NOPRIV_ERR_EC },
    { "SSID_ALLOCID_ERR", AR_NIC_FMA_ERR_FLG_SSID_ALLOCID_ERR_BP, AR_NIC_FMA_ERR_FLG_SSID_ALLOCID_ERR_EC },
    { "DESC_ENABLE_ERR", AR_NIC_FMA_ERR_FLG_DESC_ENABLE_ERR_BP, AR_NIC_FMA_ERR_FLG_DESC_ENABLE_ERR_EC },
    { "PI_BUF_OVERFLOW", AR_NIC_FMA_ERR_FLG_PI_BUF_OVERFLOW_BP, AR_NIC_FMA_ERR_FLG_PI_BUF_OVERFLOW_EC },
    { "DESC_WR_ERR", AR_NIC_FMA_ERR_FLG_DESC_WR_ERR_BP, AR_NIC_FMA_ERR_FLG_DESC_WR_ERR_EC },
    { "DESC_DB_WR_ERR", AR_NIC_FMA_ERR_FLG_DESC_DB_WR_ERR_BP, AR_NIC_FMA_ERR_FLG_DESC_DB_WR_ERR_EC },
    { "HDR_PERR", AR_NIC_FMA_ERR_FLG_HDR_PERR_BP, AR_NIC_FMA_ERR_FLG_HDR_PERR_EC },
    { "DATA1IN_MBE", AR_NIC_FMA_ERR_FLG_DATA1IN_MBE_BP, AR_NIC_FMA_ERR_FLG_DATA1IN_MBE_EC },
    { "DATA1IN_SBE", AR_NIC_FMA_ERR_FLG_DATA1IN_SBE_BP, AR_NIC_FMA_ERR_FLG_DATA1IN_SBE_EC },
    { "DATA0IN_MBE", AR_NIC_FMA_ERR_FLG_DATA0IN_MBE_BP, AR_NIC_FMA_ERR_FLG_DATA0IN_MBE_EC },
    { "DATA0IN_SBE", AR_NIC_FMA_ERR_FLG_DATA0IN_SBE_BP, AR_NIC_FMA_ERR_FLG_DATA0IN_SBE_EC },
    { "DESC88_MBE", AR_NIC_FMA_ERR_FLG_DESC88_MBE_BP, AR_NIC_FMA_ERR_FLG_DESC88_MBE_EC },
    { "DESC88_SBE", AR_NIC_FMA_ERR_FLG_DESC88_SBE_BP, AR_NIC_FMA_ERR_FLG_DESC88_SBE_EC },
    { "DESC38_MBE", AR_NIC_FMA_ERR_FLG_DESC38_MBE_BP, AR_NIC_FMA_ERR_FLG_DESC38_MBE_EC },
    { "DESC38_SBE", AR_NIC_FMA_ERR_FLG_DESC38_SBE_BP, AR_NIC_FMA_ERR_FLG_DESC38_SBE_EC },
    { "DESC28_MBE", AR_NIC_FMA_ERR_FLG_DESC28_MBE_BP, AR_NIC_FMA_ERR_FLG_DESC28_MBE_EC },
    { "DESC28_SBE", AR_NIC_FMA_ERR_FLG_DESC28_SBE_BP, AR_NIC_FMA_ERR_FLG_DESC28_SBE_EC },
    { "DESC20_MBE", AR_NIC_FMA_ERR_FLG_DESC20_MBE_BP, AR_NIC_FMA_ERR_FLG_DESC20_MBE_EC },
    { "DESC20_SBE", AR_NIC_FMA_ERR_FLG_DESC20_SBE_BP, AR_NIC_FMA_ERR_FLG_DESC20_SBE_EC },
    { "DESC18_MBE", AR_NIC_FMA_ERR_FLG_DESC18_MBE_BP, AR_NIC_FMA_ERR_FLG_DESC18_MBE_EC },
    { "DESC18_SBE", AR_NIC_FMA_ERR_FLG_DESC18_SBE_BP, AR_NIC_FMA_ERR_FLG_DESC18_SBE_EC },
    { "DESC10_MBE", AR_NIC_FMA_ERR_FLG_DESC10_MBE_BP, AR_NIC_FMA_ERR_FLG_DESC10_MBE_EC },
    { "DESC10_SBE", AR_NIC_FMA_ERR_FLG_DESC10_SBE_BP, AR_NIC_FMA_ERR_FLG_DESC10_SBE_EC },
    { "DESC08_MBE", AR_NIC_FMA_ERR_FLG_DESC08_MBE_BP, AR_NIC_FMA_ERR_FLG_DESC08_MBE_EC },
    { "DESC08_SBE", AR_NIC_FMA_ERR_FLG_DESC08_SBE_BP, AR_NIC_FMA_ERR_FLG_DESC08_SBE_EC },
    { "DESC00_MBE", AR_NIC_FMA_ERR_FLG_DESC00_MBE_BP, AR_NIC_FMA_ERR_FLG_DESC00_MBE_EC },
    { "DESC00_SBE", AR_NIC_FMA_ERR_FLG_DESC00_SBE_BP, AR_NIC_FMA_ERR_FLG_DESC00_SBE_EC },
    { "DIAG_ONLY", AR_NIC_FMA_ERR_FLG_DIAG_ONLY_BP, AR_NIC_FMA_ERR_FLG_DIAG_ONLY_EC },
    { NULL, 0, 0 }
};
#endif
static const generic_mmrd_t _ar_nic_fma_err_clr_detail[] = {
    { "SW_ERR", AR_NIC_FMA_ERR_CLR_SW_ERR_BP, AR_NIC_FMA_ERR_CLR_SW_ERR_MASK },
    { "PI_PKT_ERR", AR_NIC_FMA_ERR_CLR_PI_PKT_ERR_BP, AR_NIC_FMA_ERR_CLR_PI_PKT_ERR_MASK },
    { "PI_BYTE_PUT_ERR", AR_NIC_FMA_ERR_CLR_PI_BYTE_PUT_ERR_BP, AR_NIC_FMA_ERR_CLR_PI_BYTE_PUT_ERR_MASK },
    { "AMO_BYTE_PUT_ERR", AR_NIC_FMA_ERR_CLR_AMO_BYTE_PUT_ERR_BP, AR_NIC_FMA_ERR_CLR_AMO_BYTE_PUT_ERR_MASK },
    { "GCW_MBE_ERR", AR_NIC_FMA_ERR_CLR_GCW_MBE_ERR_BP, AR_NIC_FMA_ERR_CLR_GCW_MBE_ERR_MASK },
    { "PI_GET_ADDR_ERR", AR_NIC_FMA_ERR_CLR_PI_GET_ADDR_ERR_BP, AR_NIC_FMA_ERR_CLR_PI_GET_ADDR_ERR_MASK },
    { "FMA_LAUNCH_ERR", AR_NIC_FMA_ERR_CLR_FMA_LAUNCH_ERR_BP, AR_NIC_FMA_ERR_CLR_FMA_LAUNCH_ERR_MASK },
    { "ADDR_ALIGN_ERR", AR_NIC_FMA_ERR_CLR_ADDR_ALIGN_ERR_BP, AR_NIC_FMA_ERR_CLR_ADDR_ALIGN_ERR_MASK },
    { "GET_FR_ERR", AR_NIC_FMA_ERR_CLR_GET_FR_ERR_BP, AR_NIC_FMA_ERR_CLR_GET_FR_ERR_MASK },
    { "GET_LEN_ERR", AR_NIC_FMA_ERR_CLR_GET_LEN_ERR_BP, AR_NIC_FMA_ERR_CLR_GET_LEN_ERR_MASK },
    { "PUT_LEN_ERR", AR_NIC_FMA_ERR_CLR_PUT_LEN_ERR_BP, AR_NIC_FMA_ERR_CLR_PUT_LEN_ERR_MASK },
    { "INV_COM_ERR", AR_NIC_FMA_ERR_CLR_INV_COM_ERR_BP, AR_NIC_FMA_ERR_CLR_INV_COM_ERR_MASK },
    { "NPES_ERR", AR_NIC_FMA_ERR_CLR_NPES_ERR_BP, AR_NIC_FMA_ERR_CLR_NPES_ERR_MASK },
    { "PI_ADDR_ERR", AR_NIC_FMA_ERR_CLR_PI_ADDR_ERR_BP, AR_NIC_FMA_ERR_CLR_PI_ADDR_ERR_MASK },
    { "PI_LEN_ERR", AR_NIC_FMA_ERR_CLR_PI_LEN_ERR_BP, AR_NIC_FMA_ERR_CLR_PI_LEN_ERR_MASK },
    { "SSID_INACTIVE_ERR", AR_NIC_FMA_ERR_CLR_SSID_INACTIVE_ERR_BP, AR_NIC_FMA_ERR_CLR_SSID_INACTIVE_ERR_MASK },
    { "PI_CMD_ERR", AR_NIC_FMA_ERR_CLR_PI_CMD_ERR_BP, AR_NIC_FMA_ERR_CLR_PI_CMD_ERR_MASK },
    { "DB_MBE_ERR", AR_NIC_FMA_ERR_CLR_DB_MBE_ERR_BP, AR_NIC_FMA_ERR_CLR_DB_MBE_ERR_MASK },
    { "NOPRIV_ERR", AR_NIC_FMA_ERR_CLR_NOPRIV_ERR_BP, AR_NIC_FMA_ERR_CLR_NOPRIV_ERR_MASK },
    { "SSID_ALLOCID_ERR", AR_NIC_FMA_ERR_CLR_SSID_ALLOCID_ERR_BP, AR_NIC_FMA_ERR_CLR_SSID_ALLOCID_ERR_MASK },
    { "DESC_ENABLE_ERR", AR_NIC_FMA_ERR_CLR_DESC_ENABLE_ERR_BP, AR_NIC_FMA_ERR_CLR_DESC_ENABLE_ERR_MASK },
    { "PI_BUF_OVERFLOW", AR_NIC_FMA_ERR_CLR_PI_BUF_OVERFLOW_BP, AR_NIC_FMA_ERR_CLR_PI_BUF_OVERFLOW_MASK },
    { "DESC_WR_ERR", AR_NIC_FMA_ERR_CLR_DESC_WR_ERR_BP, AR_NIC_FMA_ERR_CLR_DESC_WR_ERR_MASK },
    { "DESC_DB_WR_ERR", AR_NIC_FMA_ERR_CLR_DESC_DB_WR_ERR_BP, AR_NIC_FMA_ERR_CLR_DESC_DB_WR_ERR_MASK },
    { "HDR_PERR", AR_NIC_FMA_ERR_CLR_HDR_PERR_BP, AR_NIC_FMA_ERR_CLR_HDR_PERR_MASK },
    { "DATA1IN_MBE", AR_NIC_FMA_ERR_CLR_DATA1IN_MBE_BP, AR_NIC_FMA_ERR_CLR_DATA1IN_MBE_MASK },
    { "DATA1IN_SBE", AR_NIC_FMA_ERR_CLR_DATA1IN_SBE_BP, AR_NIC_FMA_ERR_CLR_DATA1IN_SBE_MASK },
    { "DATA0IN_MBE", AR_NIC_FMA_ERR_CLR_DATA0IN_MBE_BP, AR_NIC_FMA_ERR_CLR_DATA0IN_MBE_MASK },
    { "DATA0IN_SBE", AR_NIC_FMA_ERR_CLR_DATA0IN_SBE_BP, AR_NIC_FMA_ERR_CLR_DATA0IN_SBE_MASK },
    { "DESC88_MBE", AR_NIC_FMA_ERR_CLR_DESC88_MBE_BP, AR_NIC_FMA_ERR_CLR_DESC88_MBE_MASK },
    { "DESC88_SBE", AR_NIC_FMA_ERR_CLR_DESC88_SBE_BP, AR_NIC_FMA_ERR_CLR_DESC88_SBE_MASK },
    { "DESC38_MBE", AR_NIC_FMA_ERR_CLR_DESC38_MBE_BP, AR_NIC_FMA_ERR_CLR_DESC38_MBE_MASK },
    { "DESC38_SBE", AR_NIC_FMA_ERR_CLR_DESC38_SBE_BP, AR_NIC_FMA_ERR_CLR_DESC38_SBE_MASK },
    { "DESC28_MBE", AR_NIC_FMA_ERR_CLR_DESC28_MBE_BP, AR_NIC_FMA_ERR_CLR_DESC28_MBE_MASK },
    { "DESC28_SBE", AR_NIC_FMA_ERR_CLR_DESC28_SBE_BP, AR_NIC_FMA_ERR_CLR_DESC28_SBE_MASK },
    { "DESC20_MBE", AR_NIC_FMA_ERR_CLR_DESC20_MBE_BP, AR_NIC_FMA_ERR_CLR_DESC20_MBE_MASK },
    { "DESC20_SBE", AR_NIC_FMA_ERR_CLR_DESC20_SBE_BP, AR_NIC_FMA_ERR_CLR_DESC20_SBE_MASK },
    { "DESC18_MBE", AR_NIC_FMA_ERR_CLR_DESC18_MBE_BP, AR_NIC_FMA_ERR_CLR_DESC18_MBE_MASK },
    { "DESC18_SBE", AR_NIC_FMA_ERR_CLR_DESC18_SBE_BP, AR_NIC_FMA_ERR_CLR_DESC18_SBE_MASK },
    { "DESC10_MBE", AR_NIC_FMA_ERR_CLR_DESC10_MBE_BP, AR_NIC_FMA_ERR_CLR_DESC10_MBE_MASK },
    { "DESC10_SBE", AR_NIC_FMA_ERR_CLR_DESC10_SBE_BP, AR_NIC_FMA_ERR_CLR_DESC10_SBE_MASK },
    { "DESC08_MBE", AR_NIC_FMA_ERR_CLR_DESC08_MBE_BP, AR_NIC_FMA_ERR_CLR_DESC08_MBE_MASK },
    { "DESC08_SBE", AR_NIC_FMA_ERR_CLR_DESC08_SBE_BP, AR_NIC_FMA_ERR_CLR_DESC08_SBE_MASK },
    { "DESC00_MBE", AR_NIC_FMA_ERR_CLR_DESC00_MBE_BP, AR_NIC_FMA_ERR_CLR_DESC00_MBE_MASK },
    { "DESC00_SBE", AR_NIC_FMA_ERR_CLR_DESC00_SBE_BP, AR_NIC_FMA_ERR_CLR_DESC00_SBE_MASK },
    { "DIAG_ONLY", AR_NIC_FMA_ERR_CLR_DIAG_ONLY_BP, AR_NIC_FMA_ERR_CLR_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_err_hss_msk_detail[] = {
    { "SW_ERR", AR_NIC_FMA_ERR_HSS_MSK_SW_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_SW_ERR_MASK },
    { "PI_PKT_ERR", AR_NIC_FMA_ERR_HSS_MSK_PI_PKT_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_PI_PKT_ERR_MASK },
    { "PI_BYTE_PUT_ERR", AR_NIC_FMA_ERR_HSS_MSK_PI_BYTE_PUT_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_PI_BYTE_PUT_ERR_MASK },
    { "AMO_BYTE_PUT_ERR", AR_NIC_FMA_ERR_HSS_MSK_AMO_BYTE_PUT_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_AMO_BYTE_PUT_ERR_MASK },
    { "GCW_MBE_ERR", AR_NIC_FMA_ERR_HSS_MSK_GCW_MBE_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_GCW_MBE_ERR_MASK },
    { "PI_GET_ADDR_ERR", AR_NIC_FMA_ERR_HSS_MSK_PI_GET_ADDR_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_PI_GET_ADDR_ERR_MASK },
    { "FMA_LAUNCH_ERR", AR_NIC_FMA_ERR_HSS_MSK_FMA_LAUNCH_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_FMA_LAUNCH_ERR_MASK },
    { "ADDR_ALIGN_ERR", AR_NIC_FMA_ERR_HSS_MSK_ADDR_ALIGN_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_ADDR_ALIGN_ERR_MASK },
    { "GET_FR_ERR", AR_NIC_FMA_ERR_HSS_MSK_GET_FR_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_GET_FR_ERR_MASK },
    { "GET_LEN_ERR", AR_NIC_FMA_ERR_HSS_MSK_GET_LEN_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_GET_LEN_ERR_MASK },
    { "PUT_LEN_ERR", AR_NIC_FMA_ERR_HSS_MSK_PUT_LEN_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_PUT_LEN_ERR_MASK },
    { "INV_COM_ERR", AR_NIC_FMA_ERR_HSS_MSK_INV_COM_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_INV_COM_ERR_MASK },
    { "NPES_ERR", AR_NIC_FMA_ERR_HSS_MSK_NPES_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_NPES_ERR_MASK },
    { "PI_ADDR_ERR", AR_NIC_FMA_ERR_HSS_MSK_PI_ADDR_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_PI_ADDR_ERR_MASK },
    { "PI_LEN_ERR", AR_NIC_FMA_ERR_HSS_MSK_PI_LEN_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_PI_LEN_ERR_MASK },
    { "SSID_INACTIVE_ERR", AR_NIC_FMA_ERR_HSS_MSK_SSID_INACTIVE_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_SSID_INACTIVE_ERR_MASK },
    { "PI_CMD_ERR", AR_NIC_FMA_ERR_HSS_MSK_PI_CMD_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_PI_CMD_ERR_MASK },
    { "DB_MBE_ERR", AR_NIC_FMA_ERR_HSS_MSK_DB_MBE_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_DB_MBE_ERR_MASK },
    { "NOPRIV_ERR", AR_NIC_FMA_ERR_HSS_MSK_NOPRIV_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_NOPRIV_ERR_MASK },
    { "SSID_ALLOCID_ERR", AR_NIC_FMA_ERR_HSS_MSK_SSID_ALLOCID_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_SSID_ALLOCID_ERR_MASK },
    { "DESC_ENABLE_ERR", AR_NIC_FMA_ERR_HSS_MSK_DESC_ENABLE_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_DESC_ENABLE_ERR_MASK },
    { "PI_BUF_OVERFLOW", AR_NIC_FMA_ERR_HSS_MSK_PI_BUF_OVERFLOW_BP, AR_NIC_FMA_ERR_HSS_MSK_PI_BUF_OVERFLOW_MASK },
    { "DESC_WR_ERR", AR_NIC_FMA_ERR_HSS_MSK_DESC_WR_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_DESC_WR_ERR_MASK },
    { "DESC_DB_WR_ERR", AR_NIC_FMA_ERR_HSS_MSK_DESC_DB_WR_ERR_BP, AR_NIC_FMA_ERR_HSS_MSK_DESC_DB_WR_ERR_MASK },
    { "HDR_PERR", AR_NIC_FMA_ERR_HSS_MSK_HDR_PERR_BP, AR_NIC_FMA_ERR_HSS_MSK_HDR_PERR_MASK },
    { "DATA1IN_MBE", AR_NIC_FMA_ERR_HSS_MSK_DATA1IN_MBE_BP, AR_NIC_FMA_ERR_HSS_MSK_DATA1IN_MBE_MASK },
    { "DATA1IN_SBE", AR_NIC_FMA_ERR_HSS_MSK_DATA1IN_SBE_BP, AR_NIC_FMA_ERR_HSS_MSK_DATA1IN_SBE_MASK },
    { "DATA0IN_MBE", AR_NIC_FMA_ERR_HSS_MSK_DATA0IN_MBE_BP, AR_NIC_FMA_ERR_HSS_MSK_DATA0IN_MBE_MASK },
    { "DATA0IN_SBE", AR_NIC_FMA_ERR_HSS_MSK_DATA0IN_SBE_BP, AR_NIC_FMA_ERR_HSS_MSK_DATA0IN_SBE_MASK },
    { "DESC88_MBE", AR_NIC_FMA_ERR_HSS_MSK_DESC88_MBE_BP, AR_NIC_FMA_ERR_HSS_MSK_DESC88_MBE_MASK },
    { "DESC88_SBE", AR_NIC_FMA_ERR_HSS_MSK_DESC88_SBE_BP, AR_NIC_FMA_ERR_HSS_MSK_DESC88_SBE_MASK },
    { "DESC38_MBE", AR_NIC_FMA_ERR_HSS_MSK_DESC38_MBE_BP, AR_NIC_FMA_ERR_HSS_MSK_DESC38_MBE_MASK },
    { "DESC38_SBE", AR_NIC_FMA_ERR_HSS_MSK_DESC38_SBE_BP, AR_NIC_FMA_ERR_HSS_MSK_DESC38_SBE_MASK },
    { "DESC28_MBE", AR_NIC_FMA_ERR_HSS_MSK_DESC28_MBE_BP, AR_NIC_FMA_ERR_HSS_MSK_DESC28_MBE_MASK },
    { "DESC28_SBE", AR_NIC_FMA_ERR_HSS_MSK_DESC28_SBE_BP, AR_NIC_FMA_ERR_HSS_MSK_DESC28_SBE_MASK },
    { "DESC20_MBE", AR_NIC_FMA_ERR_HSS_MSK_DESC20_MBE_BP, AR_NIC_FMA_ERR_HSS_MSK_DESC20_MBE_MASK },
    { "DESC20_SBE", AR_NIC_FMA_ERR_HSS_MSK_DESC20_SBE_BP, AR_NIC_FMA_ERR_HSS_MSK_DESC20_SBE_MASK },
    { "DESC18_MBE", AR_NIC_FMA_ERR_HSS_MSK_DESC18_MBE_BP, AR_NIC_FMA_ERR_HSS_MSK_DESC18_MBE_MASK },
    { "DESC18_SBE", AR_NIC_FMA_ERR_HSS_MSK_DESC18_SBE_BP, AR_NIC_FMA_ERR_HSS_MSK_DESC18_SBE_MASK },
    { "DESC10_MBE", AR_NIC_FMA_ERR_HSS_MSK_DESC10_MBE_BP, AR_NIC_FMA_ERR_HSS_MSK_DESC10_MBE_MASK },
    { "DESC10_SBE", AR_NIC_FMA_ERR_HSS_MSK_DESC10_SBE_BP, AR_NIC_FMA_ERR_HSS_MSK_DESC10_SBE_MASK },
    { "DESC08_MBE", AR_NIC_FMA_ERR_HSS_MSK_DESC08_MBE_BP, AR_NIC_FMA_ERR_HSS_MSK_DESC08_MBE_MASK },
    { "DESC08_SBE", AR_NIC_FMA_ERR_HSS_MSK_DESC08_SBE_BP, AR_NIC_FMA_ERR_HSS_MSK_DESC08_SBE_MASK },
    { "DESC00_MBE", AR_NIC_FMA_ERR_HSS_MSK_DESC00_MBE_BP, AR_NIC_FMA_ERR_HSS_MSK_DESC00_MBE_MASK },
    { "DESC00_SBE", AR_NIC_FMA_ERR_HSS_MSK_DESC00_SBE_BP, AR_NIC_FMA_ERR_HSS_MSK_DESC00_SBE_MASK },
    { "DIAG_ONLY", AR_NIC_FMA_ERR_HSS_MSK_DIAG_ONLY_BP, AR_NIC_FMA_ERR_HSS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_err_os_msk_detail[] = {
    { "SW_ERR", AR_NIC_FMA_ERR_OS_MSK_SW_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_SW_ERR_MASK },
    { "PI_PKT_ERR", AR_NIC_FMA_ERR_OS_MSK_PI_PKT_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_PI_PKT_ERR_MASK },
    { "PI_BYTE_PUT_ERR", AR_NIC_FMA_ERR_OS_MSK_PI_BYTE_PUT_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_PI_BYTE_PUT_ERR_MASK },
    { "AMO_BYTE_PUT_ERR", AR_NIC_FMA_ERR_OS_MSK_AMO_BYTE_PUT_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_AMO_BYTE_PUT_ERR_MASK },
    { "GCW_MBE_ERR", AR_NIC_FMA_ERR_OS_MSK_GCW_MBE_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_GCW_MBE_ERR_MASK },
    { "PI_GET_ADDR_ERR", AR_NIC_FMA_ERR_OS_MSK_PI_GET_ADDR_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_PI_GET_ADDR_ERR_MASK },
    { "FMA_LAUNCH_ERR", AR_NIC_FMA_ERR_OS_MSK_FMA_LAUNCH_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_FMA_LAUNCH_ERR_MASK },
    { "ADDR_ALIGN_ERR", AR_NIC_FMA_ERR_OS_MSK_ADDR_ALIGN_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_ADDR_ALIGN_ERR_MASK },
    { "GET_FR_ERR", AR_NIC_FMA_ERR_OS_MSK_GET_FR_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_GET_FR_ERR_MASK },
    { "GET_LEN_ERR", AR_NIC_FMA_ERR_OS_MSK_GET_LEN_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_GET_LEN_ERR_MASK },
    { "PUT_LEN_ERR", AR_NIC_FMA_ERR_OS_MSK_PUT_LEN_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_PUT_LEN_ERR_MASK },
    { "INV_COM_ERR", AR_NIC_FMA_ERR_OS_MSK_INV_COM_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_INV_COM_ERR_MASK },
    { "NPES_ERR", AR_NIC_FMA_ERR_OS_MSK_NPES_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_NPES_ERR_MASK },
    { "PI_ADDR_ERR", AR_NIC_FMA_ERR_OS_MSK_PI_ADDR_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_PI_ADDR_ERR_MASK },
    { "PI_LEN_ERR", AR_NIC_FMA_ERR_OS_MSK_PI_LEN_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_PI_LEN_ERR_MASK },
    { "SSID_INACTIVE_ERR", AR_NIC_FMA_ERR_OS_MSK_SSID_INACTIVE_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_SSID_INACTIVE_ERR_MASK },
    { "PI_CMD_ERR", AR_NIC_FMA_ERR_OS_MSK_PI_CMD_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_PI_CMD_ERR_MASK },
    { "DB_MBE_ERR", AR_NIC_FMA_ERR_OS_MSK_DB_MBE_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_DB_MBE_ERR_MASK },
    { "NOPRIV_ERR", AR_NIC_FMA_ERR_OS_MSK_NOPRIV_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_NOPRIV_ERR_MASK },
    { "SSID_ALLOCID_ERR", AR_NIC_FMA_ERR_OS_MSK_SSID_ALLOCID_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_SSID_ALLOCID_ERR_MASK },
    { "DESC_ENABLE_ERR", AR_NIC_FMA_ERR_OS_MSK_DESC_ENABLE_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_DESC_ENABLE_ERR_MASK },
    { "PI_BUF_OVERFLOW", AR_NIC_FMA_ERR_OS_MSK_PI_BUF_OVERFLOW_BP, AR_NIC_FMA_ERR_OS_MSK_PI_BUF_OVERFLOW_MASK },
    { "DESC_WR_ERR", AR_NIC_FMA_ERR_OS_MSK_DESC_WR_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_DESC_WR_ERR_MASK },
    { "DESC_DB_WR_ERR", AR_NIC_FMA_ERR_OS_MSK_DESC_DB_WR_ERR_BP, AR_NIC_FMA_ERR_OS_MSK_DESC_DB_WR_ERR_MASK },
    { "HDR_PERR", AR_NIC_FMA_ERR_OS_MSK_HDR_PERR_BP, AR_NIC_FMA_ERR_OS_MSK_HDR_PERR_MASK },
    { "DATA1IN_MBE", AR_NIC_FMA_ERR_OS_MSK_DATA1IN_MBE_BP, AR_NIC_FMA_ERR_OS_MSK_DATA1IN_MBE_MASK },
    { "DATA1IN_SBE", AR_NIC_FMA_ERR_OS_MSK_DATA1IN_SBE_BP, AR_NIC_FMA_ERR_OS_MSK_DATA1IN_SBE_MASK },
    { "DATA0IN_MBE", AR_NIC_FMA_ERR_OS_MSK_DATA0IN_MBE_BP, AR_NIC_FMA_ERR_OS_MSK_DATA0IN_MBE_MASK },
    { "DATA0IN_SBE", AR_NIC_FMA_ERR_OS_MSK_DATA0IN_SBE_BP, AR_NIC_FMA_ERR_OS_MSK_DATA0IN_SBE_MASK },
    { "DESC88_MBE", AR_NIC_FMA_ERR_OS_MSK_DESC88_MBE_BP, AR_NIC_FMA_ERR_OS_MSK_DESC88_MBE_MASK },
    { "DESC88_SBE", AR_NIC_FMA_ERR_OS_MSK_DESC88_SBE_BP, AR_NIC_FMA_ERR_OS_MSK_DESC88_SBE_MASK },
    { "DESC38_MBE", AR_NIC_FMA_ERR_OS_MSK_DESC38_MBE_BP, AR_NIC_FMA_ERR_OS_MSK_DESC38_MBE_MASK },
    { "DESC38_SBE", AR_NIC_FMA_ERR_OS_MSK_DESC38_SBE_BP, AR_NIC_FMA_ERR_OS_MSK_DESC38_SBE_MASK },
    { "DESC28_MBE", AR_NIC_FMA_ERR_OS_MSK_DESC28_MBE_BP, AR_NIC_FMA_ERR_OS_MSK_DESC28_MBE_MASK },
    { "DESC28_SBE", AR_NIC_FMA_ERR_OS_MSK_DESC28_SBE_BP, AR_NIC_FMA_ERR_OS_MSK_DESC28_SBE_MASK },
    { "DESC20_MBE", AR_NIC_FMA_ERR_OS_MSK_DESC20_MBE_BP, AR_NIC_FMA_ERR_OS_MSK_DESC20_MBE_MASK },
    { "DESC20_SBE", AR_NIC_FMA_ERR_OS_MSK_DESC20_SBE_BP, AR_NIC_FMA_ERR_OS_MSK_DESC20_SBE_MASK },
    { "DESC18_MBE", AR_NIC_FMA_ERR_OS_MSK_DESC18_MBE_BP, AR_NIC_FMA_ERR_OS_MSK_DESC18_MBE_MASK },
    { "DESC18_SBE", AR_NIC_FMA_ERR_OS_MSK_DESC18_SBE_BP, AR_NIC_FMA_ERR_OS_MSK_DESC18_SBE_MASK },
    { "DESC10_MBE", AR_NIC_FMA_ERR_OS_MSK_DESC10_MBE_BP, AR_NIC_FMA_ERR_OS_MSK_DESC10_MBE_MASK },
    { "DESC10_SBE", AR_NIC_FMA_ERR_OS_MSK_DESC10_SBE_BP, AR_NIC_FMA_ERR_OS_MSK_DESC10_SBE_MASK },
    { "DESC08_MBE", AR_NIC_FMA_ERR_OS_MSK_DESC08_MBE_BP, AR_NIC_FMA_ERR_OS_MSK_DESC08_MBE_MASK },
    { "DESC08_SBE", AR_NIC_FMA_ERR_OS_MSK_DESC08_SBE_BP, AR_NIC_FMA_ERR_OS_MSK_DESC08_SBE_MASK },
    { "DESC00_MBE", AR_NIC_FMA_ERR_OS_MSK_DESC00_MBE_BP, AR_NIC_FMA_ERR_OS_MSK_DESC00_MBE_MASK },
    { "DESC00_SBE", AR_NIC_FMA_ERR_OS_MSK_DESC00_SBE_BP, AR_NIC_FMA_ERR_OS_MSK_DESC00_SBE_MASK },
    { "DIAG_ONLY", AR_NIC_FMA_ERR_OS_MSK_DIAG_ONLY_BP, AR_NIC_FMA_ERR_OS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_err_first_flg_detail[] = {
    { "SW_ERR", AR_NIC_FMA_ERR_FIRST_FLG_SW_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_SW_ERR_MASK },
    { "PI_PKT_ERR", AR_NIC_FMA_ERR_FIRST_FLG_PI_PKT_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_PI_PKT_ERR_MASK },
    { "PI_BYTE_PUT_ERR", AR_NIC_FMA_ERR_FIRST_FLG_PI_BYTE_PUT_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_PI_BYTE_PUT_ERR_MASK },
    { "AMO_BYTE_PUT_ERR", AR_NIC_FMA_ERR_FIRST_FLG_AMO_BYTE_PUT_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_AMO_BYTE_PUT_ERR_MASK },
    { "GCW_MBE_ERR", AR_NIC_FMA_ERR_FIRST_FLG_GCW_MBE_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_GCW_MBE_ERR_MASK },
    { "PI_GET_ADDR_ERR", AR_NIC_FMA_ERR_FIRST_FLG_PI_GET_ADDR_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_PI_GET_ADDR_ERR_MASK },
    { "FMA_LAUNCH_ERR", AR_NIC_FMA_ERR_FIRST_FLG_FMA_LAUNCH_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_FMA_LAUNCH_ERR_MASK },
    { "ADDR_ALIGN_ERR", AR_NIC_FMA_ERR_FIRST_FLG_ADDR_ALIGN_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_ADDR_ALIGN_ERR_MASK },
    { "GET_FR_ERR", AR_NIC_FMA_ERR_FIRST_FLG_GET_FR_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_GET_FR_ERR_MASK },
    { "GET_LEN_ERR", AR_NIC_FMA_ERR_FIRST_FLG_GET_LEN_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_GET_LEN_ERR_MASK },
    { "PUT_LEN_ERR", AR_NIC_FMA_ERR_FIRST_FLG_PUT_LEN_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_PUT_LEN_ERR_MASK },
    { "INV_COM_ERR", AR_NIC_FMA_ERR_FIRST_FLG_INV_COM_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_INV_COM_ERR_MASK },
    { "NPES_ERR", AR_NIC_FMA_ERR_FIRST_FLG_NPES_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_NPES_ERR_MASK },
    { "PI_ADDR_ERR", AR_NIC_FMA_ERR_FIRST_FLG_PI_ADDR_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_PI_ADDR_ERR_MASK },
    { "PI_LEN_ERR", AR_NIC_FMA_ERR_FIRST_FLG_PI_LEN_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_PI_LEN_ERR_MASK },
    { "SSID_INACTIVE_ERR", AR_NIC_FMA_ERR_FIRST_FLG_SSID_INACTIVE_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_SSID_INACTIVE_ERR_MASK },
    { "PI_CMD_ERR", AR_NIC_FMA_ERR_FIRST_FLG_PI_CMD_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_PI_CMD_ERR_MASK },
    { "DB_MBE_ERR", AR_NIC_FMA_ERR_FIRST_FLG_DB_MBE_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_DB_MBE_ERR_MASK },
    { "NOPRIV_ERR", AR_NIC_FMA_ERR_FIRST_FLG_NOPRIV_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_NOPRIV_ERR_MASK },
    { "SSID_ALLOCID_ERR", AR_NIC_FMA_ERR_FIRST_FLG_SSID_ALLOCID_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_SSID_ALLOCID_ERR_MASK },
    { "DESC_ENABLE_ERR", AR_NIC_FMA_ERR_FIRST_FLG_DESC_ENABLE_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_DESC_ENABLE_ERR_MASK },
    { "PI_BUF_OVERFLOW", AR_NIC_FMA_ERR_FIRST_FLG_PI_BUF_OVERFLOW_BP, AR_NIC_FMA_ERR_FIRST_FLG_PI_BUF_OVERFLOW_MASK },
    { "DESC_WR_ERR", AR_NIC_FMA_ERR_FIRST_FLG_DESC_WR_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_DESC_WR_ERR_MASK },
    { "DESC_DB_WR_ERR", AR_NIC_FMA_ERR_FIRST_FLG_DESC_DB_WR_ERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_DESC_DB_WR_ERR_MASK },
    { "HDR_PERR", AR_NIC_FMA_ERR_FIRST_FLG_HDR_PERR_BP, AR_NIC_FMA_ERR_FIRST_FLG_HDR_PERR_MASK },
    { "DATA1IN_MBE", AR_NIC_FMA_ERR_FIRST_FLG_DATA1IN_MBE_BP, AR_NIC_FMA_ERR_FIRST_FLG_DATA1IN_MBE_MASK },
    { "DATA1IN_SBE", AR_NIC_FMA_ERR_FIRST_FLG_DATA1IN_SBE_BP, AR_NIC_FMA_ERR_FIRST_FLG_DATA1IN_SBE_MASK },
    { "DATA0IN_MBE", AR_NIC_FMA_ERR_FIRST_FLG_DATA0IN_MBE_BP, AR_NIC_FMA_ERR_FIRST_FLG_DATA0IN_MBE_MASK },
    { "DATA0IN_SBE", AR_NIC_FMA_ERR_FIRST_FLG_DATA0IN_SBE_BP, AR_NIC_FMA_ERR_FIRST_FLG_DATA0IN_SBE_MASK },
    { "DESC88_MBE", AR_NIC_FMA_ERR_FIRST_FLG_DESC88_MBE_BP, AR_NIC_FMA_ERR_FIRST_FLG_DESC88_MBE_MASK },
    { "DESC88_SBE", AR_NIC_FMA_ERR_FIRST_FLG_DESC88_SBE_BP, AR_NIC_FMA_ERR_FIRST_FLG_DESC88_SBE_MASK },
    { "DESC38_MBE", AR_NIC_FMA_ERR_FIRST_FLG_DESC38_MBE_BP, AR_NIC_FMA_ERR_FIRST_FLG_DESC38_MBE_MASK },
    { "DESC38_SBE", AR_NIC_FMA_ERR_FIRST_FLG_DESC38_SBE_BP, AR_NIC_FMA_ERR_FIRST_FLG_DESC38_SBE_MASK },
    { "DESC28_MBE", AR_NIC_FMA_ERR_FIRST_FLG_DESC28_MBE_BP, AR_NIC_FMA_ERR_FIRST_FLG_DESC28_MBE_MASK },
    { "DESC28_SBE", AR_NIC_FMA_ERR_FIRST_FLG_DESC28_SBE_BP, AR_NIC_FMA_ERR_FIRST_FLG_DESC28_SBE_MASK },
    { "DESC20_MBE", AR_NIC_FMA_ERR_FIRST_FLG_DESC20_MBE_BP, AR_NIC_FMA_ERR_FIRST_FLG_DESC20_MBE_MASK },
    { "DESC20_SBE", AR_NIC_FMA_ERR_FIRST_FLG_DESC20_SBE_BP, AR_NIC_FMA_ERR_FIRST_FLG_DESC20_SBE_MASK },
    { "DESC18_MBE", AR_NIC_FMA_ERR_FIRST_FLG_DESC18_MBE_BP, AR_NIC_FMA_ERR_FIRST_FLG_DESC18_MBE_MASK },
    { "DESC18_SBE", AR_NIC_FMA_ERR_FIRST_FLG_DESC18_SBE_BP, AR_NIC_FMA_ERR_FIRST_FLG_DESC18_SBE_MASK },
    { "DESC10_MBE", AR_NIC_FMA_ERR_FIRST_FLG_DESC10_MBE_BP, AR_NIC_FMA_ERR_FIRST_FLG_DESC10_MBE_MASK },
    { "DESC10_SBE", AR_NIC_FMA_ERR_FIRST_FLG_DESC10_SBE_BP, AR_NIC_FMA_ERR_FIRST_FLG_DESC10_SBE_MASK },
    { "DESC08_MBE", AR_NIC_FMA_ERR_FIRST_FLG_DESC08_MBE_BP, AR_NIC_FMA_ERR_FIRST_FLG_DESC08_MBE_MASK },
    { "DESC08_SBE", AR_NIC_FMA_ERR_FIRST_FLG_DESC08_SBE_BP, AR_NIC_FMA_ERR_FIRST_FLG_DESC08_SBE_MASK },
    { "DESC00_MBE", AR_NIC_FMA_ERR_FIRST_FLG_DESC00_MBE_BP, AR_NIC_FMA_ERR_FIRST_FLG_DESC00_MBE_MASK },
    { "DESC00_SBE", AR_NIC_FMA_ERR_FIRST_FLG_DESC00_SBE_BP, AR_NIC_FMA_ERR_FIRST_FLG_DESC00_SBE_MASK },
    { "DIAG_ONLY", AR_NIC_FMA_ERR_FIRST_FLG_DIAG_ONLY_BP, AR_NIC_FMA_ERR_FIRST_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_err_info_ram0_detail[] = {
    { "DESC18_MBE_SYND", AR_NIC_FMA_ERR_INFO_RAM0_DESC18_MBE_SYND_BP, AR_NIC_FMA_ERR_INFO_RAM0_DESC18_MBE_SYND_MASK },
    { "DESC18_SBE_SYND", AR_NIC_FMA_ERR_INFO_RAM0_DESC18_SBE_SYND_BP, AR_NIC_FMA_ERR_INFO_RAM0_DESC18_SBE_SYND_MASK },
    { "DESC10_MBE_SYND", AR_NIC_FMA_ERR_INFO_RAM0_DESC10_MBE_SYND_BP, AR_NIC_FMA_ERR_INFO_RAM0_DESC10_MBE_SYND_MASK },
    { "DESC10_SBE_SYND", AR_NIC_FMA_ERR_INFO_RAM0_DESC10_SBE_SYND_BP, AR_NIC_FMA_ERR_INFO_RAM0_DESC10_SBE_SYND_MASK },
    { "DESC08_MBE_SYND", AR_NIC_FMA_ERR_INFO_RAM0_DESC08_MBE_SYND_BP, AR_NIC_FMA_ERR_INFO_RAM0_DESC08_MBE_SYND_MASK },
    { "DESC08_SBE_SYND", AR_NIC_FMA_ERR_INFO_RAM0_DESC08_SBE_SYND_BP, AR_NIC_FMA_ERR_INFO_RAM0_DESC08_SBE_SYND_MASK },
    { "DESC00_MBE_SYND", AR_NIC_FMA_ERR_INFO_RAM0_DESC00_MBE_SYND_BP, AR_NIC_FMA_ERR_INFO_RAM0_DESC00_MBE_SYND_MASK },
    { "DESC00_SBE_SYND", AR_NIC_FMA_ERR_INFO_RAM0_DESC00_SBE_SYND_BP, AR_NIC_FMA_ERR_INFO_RAM0_DESC00_SBE_SYND_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_err_info_ram1_detail[] = {
    { "DESC88_MBE_SYND", AR_NIC_FMA_ERR_INFO_RAM1_DESC88_MBE_SYND_BP, AR_NIC_FMA_ERR_INFO_RAM1_DESC88_MBE_SYND_MASK },
    { "DESC88_SBE_SYND", AR_NIC_FMA_ERR_INFO_RAM1_DESC88_SBE_SYND_BP, AR_NIC_FMA_ERR_INFO_RAM1_DESC88_SBE_SYND_MASK },
    { "DESC38_MBE_SYND", AR_NIC_FMA_ERR_INFO_RAM1_DESC38_MBE_SYND_BP, AR_NIC_FMA_ERR_INFO_RAM1_DESC38_MBE_SYND_MASK },
    { "DESC38_SBE_SYND", AR_NIC_FMA_ERR_INFO_RAM1_DESC38_SBE_SYND_BP, AR_NIC_FMA_ERR_INFO_RAM1_DESC38_SBE_SYND_MASK },
    { "DESC28_MBE_SYND", AR_NIC_FMA_ERR_INFO_RAM1_DESC28_MBE_SYND_BP, AR_NIC_FMA_ERR_INFO_RAM1_DESC28_MBE_SYND_MASK },
    { "DESC28_SBE_SYND", AR_NIC_FMA_ERR_INFO_RAM1_DESC28_SBE_SYND_BP, AR_NIC_FMA_ERR_INFO_RAM1_DESC28_SBE_SYND_MASK },
    { "DESC20_MBE_SYND", AR_NIC_FMA_ERR_INFO_RAM1_DESC20_MBE_SYND_BP, AR_NIC_FMA_ERR_INFO_RAM1_DESC20_MBE_SYND_MASK },
    { "DESC20_SBE_SYND", AR_NIC_FMA_ERR_INFO_RAM1_DESC20_SBE_SYND_BP, AR_NIC_FMA_ERR_INFO_RAM1_DESC20_SBE_SYND_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_err_info_data_detail[] = {
    { "DATA1IN_MBE_SYND", AR_NIC_FMA_ERR_INFO_DATA_DATA1IN_MBE_SYND_BP, AR_NIC_FMA_ERR_INFO_DATA_DATA1IN_MBE_SYND_MASK },
    { "DATA1IN_SBE_SYND", AR_NIC_FMA_ERR_INFO_DATA_DATA1IN_SBE_SYND_BP, AR_NIC_FMA_ERR_INFO_DATA_DATA1IN_SBE_SYND_MASK },
    { "DATA0IN_MBE_SYND", AR_NIC_FMA_ERR_INFO_DATA_DATA0IN_MBE_SYND_BP, AR_NIC_FMA_ERR_INFO_DATA_DATA0IN_MBE_SYND_MASK },
    { "DATA0IN_SBE_SYND", AR_NIC_FMA_ERR_INFO_DATA_DATA0IN_SBE_SYND_BP, AR_NIC_FMA_ERR_INFO_DATA_DATA0IN_SBE_SYND_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_err_info_hdr_detail[] = {
    { "PERR3", AR_NIC_FMA_ERR_INFO_HDR_PERR3_BP, AR_NIC_FMA_ERR_INFO_HDR_PERR3_MASK },
    { "PERR2", AR_NIC_FMA_ERR_INFO_HDR_PERR2_BP, AR_NIC_FMA_ERR_INFO_HDR_PERR2_MASK },
    { "PERR1", AR_NIC_FMA_ERR_INFO_HDR_PERR1_BP, AR_NIC_FMA_ERR_INFO_HDR_PERR1_MASK },
    { "PERR0", AR_NIC_FMA_ERR_INFO_HDR_PERR0_BP, AR_NIC_FMA_ERR_INFO_HDR_PERR0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_dbg_errinj_ram_detail[] = {
    { "ADDRESS", AR_NIC_FMA_DBG_ERRINJ_RAM_ADDRESS_BP, AR_NIC_FMA_DBG_ERRINJ_RAM_ADDRESS_MASK },
    { "CHECKBYTE", AR_NIC_FMA_DBG_ERRINJ_RAM_CHECKBYTE_BP, AR_NIC_FMA_DBG_ERRINJ_RAM_CHECKBYTE_MASK },
    { "DESC88", AR_NIC_FMA_DBG_ERRINJ_RAM_DESC88_BP, AR_NIC_FMA_DBG_ERRINJ_RAM_DESC88_MASK },
    { "DESC38", AR_NIC_FMA_DBG_ERRINJ_RAM_DESC38_BP, AR_NIC_FMA_DBG_ERRINJ_RAM_DESC38_MASK },
    { "DESC28", AR_NIC_FMA_DBG_ERRINJ_RAM_DESC28_BP, AR_NIC_FMA_DBG_ERRINJ_RAM_DESC28_MASK },
    { "DESC20", AR_NIC_FMA_DBG_ERRINJ_RAM_DESC20_BP, AR_NIC_FMA_DBG_ERRINJ_RAM_DESC20_MASK },
    { "DESC18", AR_NIC_FMA_DBG_ERRINJ_RAM_DESC18_BP, AR_NIC_FMA_DBG_ERRINJ_RAM_DESC18_MASK },
    { "DESC10", AR_NIC_FMA_DBG_ERRINJ_RAM_DESC10_BP, AR_NIC_FMA_DBG_ERRINJ_RAM_DESC10_MASK },
    { "DESC08", AR_NIC_FMA_DBG_ERRINJ_RAM_DESC08_BP, AR_NIC_FMA_DBG_ERRINJ_RAM_DESC08_MASK },
    { "DESC00", AR_NIC_FMA_DBG_ERRINJ_RAM_DESC00_BP, AR_NIC_FMA_DBG_ERRINJ_RAM_DESC00_MASK },
    { "TRIGGERED", AR_NIC_FMA_DBG_ERRINJ_RAM_TRIGGERED_BP, AR_NIC_FMA_DBG_ERRINJ_RAM_TRIGGERED_MASK },
    { "MODE", AR_NIC_FMA_DBG_ERRINJ_RAM_MODE_BP, AR_NIC_FMA_DBG_ERRINJ_RAM_MODE_MASK },
    { "ENABLE", AR_NIC_FMA_DBG_ERRINJ_RAM_ENABLE_BP, AR_NIC_FMA_DBG_ERRINJ_RAM_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_dbg_errinj_pkt_detail[] = {
    { "CHECKBYTEUP", AR_NIC_FMA_DBG_ERRINJ_PKT_CHECKBYTEUP_BP, AR_NIC_FMA_DBG_ERRINJ_PKT_CHECKBYTEUP_MASK },
    { "CHECKBYTELO", AR_NIC_FMA_DBG_ERRINJ_PKT_CHECKBYTELO_BP, AR_NIC_FMA_DBG_ERRINJ_PKT_CHECKBYTELO_MASK },
    { "PARITY", AR_NIC_FMA_DBG_ERRINJ_PKT_PARITY_BP, AR_NIC_FMA_DBG_ERRINJ_PKT_PARITY_MASK },
    { "TAIL", AR_NIC_FMA_DBG_ERRINJ_PKT_TAIL_BP, AR_NIC_FMA_DBG_ERRINJ_PKT_TAIL_MASK },
    { "COUNT", AR_NIC_FMA_DBG_ERRINJ_PKT_COUNT_BP, AR_NIC_FMA_DBG_ERRINJ_PKT_COUNT_MASK },
    { "TRIGGERED", AR_NIC_FMA_DBG_ERRINJ_PKT_TRIGGERED_BP, AR_NIC_FMA_DBG_ERRINJ_PKT_TRIGGERED_MASK },
    { "MODE", AR_NIC_FMA_DBG_ERRINJ_PKT_MODE_BP, AR_NIC_FMA_DBG_ERRINJ_PKT_MODE_MASK },
    { "ENABLE", AR_NIC_FMA_DBG_ERRINJ_PKT_ENABLE_BP, AR_NIC_FMA_DBG_ERRINJ_PKT_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_cfg_credit_detail[] = {
    { "CQ_COUNT", AR_NIC_FMA_CFG_CREDIT_CQ_COUNT_BP, AR_NIC_FMA_CFG_CREDIT_CQ_COUNT_MASK },
    { "AAX_OPRND_MODE", AR_NIC_FMA_CFG_CREDIT_AAX_OPRND_MODE_BP, AR_NIC_FMA_CFG_CREDIT_AAX_OPRND_MODE_MASK },
    { "TARB_INT_COUNT", AR_NIC_FMA_CFG_CREDIT_TARB_INT_COUNT_BP, AR_NIC_FMA_CFG_CREDIT_TARB_INT_COUNT_MASK },
    { "DLA_COUNT", AR_NIC_FMA_CFG_CREDIT_DLA_COUNT_BP, AR_NIC_FMA_CFG_CREDIT_DLA_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_err_info_pi_detail[] = {
    { "LSTATUS", AR_NIC_FMA_ERR_INFO_PI_LSTATUS_BP, AR_NIC_FMA_ERR_INFO_PI_LSTATUS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_fma_err_info_sw_detail[] = {
    { "ADDRESS", AR_NIC_FMA_ERR_INFO_SW_ADDRESS_BP, AR_NIC_FMA_ERR_INFO_SW_ADDRESS_MASK },
    { NULL, 0, 0 }
};

/*
 *  AR FMA MMR DECLARATIONS
 */
static const generic_mmr_t _ar_nic_fma_mmr_ring_0_hi_fma = {
    "AR_NIC_FMA_MMR_RING_0_HI_FMA", AR_NIC_FMA_MMR_RING_0_HI_FMA, 8, 1, _ar_nic_fma_mmr_ring_0_hi_fma_detail
};
static const generic_mmr_t _ar_nic_fma_mmr_ring_0_mid_fma = {
    "AR_NIC_FMA_MMR_RING_0_MID_FMA", AR_NIC_FMA_MMR_RING_0_MID_FMA, 8, 1, _ar_nic_fma_mmr_ring_0_mid_fma_detail
};
static const generic_mmr_t _ar_nic_fma_mmr_ring_0_lo_fma = {
    "AR_NIC_FMA_MMR_RING_0_LO_FMA", AR_NIC_FMA_MMR_RING_0_LO_FMA, 8, 1, _ar_nic_fma_mmr_ring_0_lo_fma_detail
};
static const generic_mmr_t _ar_nic_fma_err_flg_1_hi_fma = {
    "AR_NIC_FMA_ERR_FLG_1_HI_FMA", AR_NIC_FMA_ERR_FLG_1_HI_FMA, 8, 1, _ar_nic_fma_err_flg_1_hi_fma_detail
};
static const generic_mmr_t _ar_nic_fma_err_flg_1_mid_fma = {
    "AR_NIC_FMA_ERR_FLG_1_MID_FMA", AR_NIC_FMA_ERR_FLG_1_MID_FMA, 8, 1, _ar_nic_fma_err_flg_1_mid_fma_detail
};
static const generic_mmr_t _ar_nic_fma_err_flg_1_lo_fma = {
    "AR_NIC_FMA_ERR_FLG_1_LO_FMA", AR_NIC_FMA_ERR_FLG_1_LO_FMA, 8, 1, _ar_nic_fma_err_flg_1_lo_fma_detail
};
static const generic_mmr_t _ar_nic_fma_pi_flit_input_stage_2_hi_fma = {
    "AR_NIC_FMA_PI_FLIT_INPUT_STAGE_2_HI_FMA", AR_NIC_FMA_PI_FLIT_INPUT_STAGE_2_HI_FMA, 8, 1, _ar_nic_fma_pi_flit_input_stage_2_hi_fma_detail
};
static const generic_mmr_t _ar_nic_fma_pi_flit_input_stage_2_mid_fma = {
    "AR_NIC_FMA_PI_FLIT_INPUT_STAGE_2_MID_FMA", AR_NIC_FMA_PI_FLIT_INPUT_STAGE_2_MID_FMA, 8, 1, _ar_nic_fma_pi_flit_input_stage_2_mid_fma_detail
};
static const generic_mmr_t _ar_nic_fma_pi_flit_input_stage_2_lo_fma = {
    "AR_NIC_FMA_PI_FLIT_INPUT_STAGE_2_LO_FMA", AR_NIC_FMA_PI_FLIT_INPUT_STAGE_2_LO_FMA, 8, 1, _ar_nic_fma_pi_flit_input_stage_2_lo_fma_detail
};
static const generic_mmr_t _ar_nic_fma_pi_control_decode_desc_read_stage_4_hi_fma = {
    "AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_HI_FMA", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_HI_FMA, 8, 1, _ar_nic_fma_pi_control_decode_desc_read_stage_4_hi_fma_detail
};
static const generic_mmr_t _ar_nic_fma_pi_control_decode_desc_read_stage_4_mid_fma = {
    "AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_MID_FMA, 8, 1, _ar_nic_fma_pi_control_decode_desc_read_stage_4_mid_fma_detail
};
static const generic_mmr_t _ar_nic_fma_pi_control_decode_desc_read_stage_4_lo_fma = {
    "AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA", AR_NIC_FMA_PI_CONTROL_DECODE_DESC_READ_STAGE_4_LO_FMA, 8, 1, _ar_nic_fma_pi_control_decode_desc_read_stage_4_lo_fma_detail
};
static const generic_mmr_t _ar_nic_fma_pi_control_data_desc_read_stage_5_hi_fma = {
    "AR_NIC_FMA_PI_CONTROL_DATA_DESC_READ_STAGE_5_HI_FMA", AR_NIC_FMA_PI_CONTROL_DATA_DESC_READ_STAGE_5_HI_FMA, 8, 1, _ar_nic_fma_pi_control_data_desc_read_stage_5_hi_fma_detail
};
static const generic_mmr_t _ar_nic_fma_pi_control_data_desc_read_stage_5_mid_fma = {
    "AR_NIC_FMA_PI_CONTROL_DATA_DESC_READ_STAGE_5_MID_FMA", AR_NIC_FMA_PI_CONTROL_DATA_DESC_READ_STAGE_5_MID_FMA, 8, 1, _ar_nic_fma_pi_control_data_desc_read_stage_5_mid_fma_detail
};
static const generic_mmr_t _ar_nic_fma_pi_control_data_desc_read_stage_5_lo_fma = {
    "AR_NIC_FMA_PI_CONTROL_DATA_DESC_READ_STAGE_5_LO_FMA", AR_NIC_FMA_PI_CONTROL_DATA_DESC_READ_STAGE_5_LO_FMA, 8, 1, _ar_nic_fma_pi_control_data_desc_read_stage_5_lo_fma_detail
};
static const generic_mmr_t _ar_nic_fma_packet_generation_tarb_write_stage_6_hi_fma = {
    "AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_HI_FMA", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_HI_FMA, 8, 1, _ar_nic_fma_packet_generation_tarb_write_stage_6_hi_fma_detail
};
static const generic_mmr_t _ar_nic_fma_packet_generation_tarb_write_stage_6_mid_fma = {
    "AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_MID_FMA, 8, 1, _ar_nic_fma_packet_generation_tarb_write_stage_6_mid_fma_detail
};
static const generic_mmr_t _ar_nic_fma_packet_generation_tarb_write_stage_6_lo_fma = {
    "AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA", AR_NIC_FMA_PACKET_GENERATION_TARB_WRITE_STAGE_6_LO_FMA, 8, 1, _ar_nic_fma_packet_generation_tarb_write_stage_6_lo_fma_detail
};
static const generic_mmr_t _ar_nic_fma_tarb_rd_data_stage_7_hi_fma = {
    "AR_NIC_FMA_TARB_RD_DATA_STAGE_7_HI_FMA", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_HI_FMA, 8, 1, _ar_nic_fma_tarb_rd_data_stage_7_hi_fma_detail
};
static const generic_mmr_t _ar_nic_fma_tarb_rd_data_stage_7_mid_fma = {
    "AR_NIC_FMA_TARB_RD_DATA_STAGE_7_MID_FMA", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_MID_FMA, 8, 1, _ar_nic_fma_tarb_rd_data_stage_7_mid_fma_detail
};
static const generic_mmr_t _ar_nic_fma_tarb_rd_data_stage_7_lo_fma = {
    "AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA", AR_NIC_FMA_TARB_RD_DATA_STAGE_7_LO_FMA, 8, 1, _ar_nic_fma_tarb_rd_data_stage_7_lo_fma_detail
};
static const generic_mmr_t _ar_nic_fma_err_flg = {
    "AR_NIC_FMA_ERR_FLG", AR_NIC_FMA_ERR_FLG, 8, 1, _ar_nic_fma_err_flg_detail
};
static const generic_mmr_t _ar_nic_fma_err_clr = {
    "AR_NIC_FMA_ERR_CLR", AR_NIC_FMA_ERR_CLR, 8, 1, _ar_nic_fma_err_clr_detail
};
static const generic_mmr_t _ar_nic_fma_err_hss_msk = {
    "AR_NIC_FMA_ERR_HSS_MSK", AR_NIC_FMA_ERR_HSS_MSK, 8, 1, _ar_nic_fma_err_hss_msk_detail
};
static const generic_mmr_t _ar_nic_fma_err_os_msk = {
    "AR_NIC_FMA_ERR_OS_MSK", AR_NIC_FMA_ERR_OS_MSK, 8, 1, _ar_nic_fma_err_os_msk_detail
};
static const generic_mmr_t _ar_nic_fma_err_first_flg = {
    "AR_NIC_FMA_ERR_FIRST_FLG", AR_NIC_FMA_ERR_FIRST_FLG, 8, 1, _ar_nic_fma_err_first_flg_detail
};
static const generic_mmr_t _ar_nic_fma_err_info_ram0 = {
    "AR_NIC_FMA_ERR_INFO_RAM0", AR_NIC_FMA_ERR_INFO_RAM0, 8, 1, _ar_nic_fma_err_info_ram0_detail
};
static const generic_mmr_t _ar_nic_fma_err_info_ram1 = {
    "AR_NIC_FMA_ERR_INFO_RAM1", AR_NIC_FMA_ERR_INFO_RAM1, 8, 1, _ar_nic_fma_err_info_ram1_detail
};
static const generic_mmr_t _ar_nic_fma_err_info_data = {
    "AR_NIC_FMA_ERR_INFO_DATA", AR_NIC_FMA_ERR_INFO_DATA, 8, 1, _ar_nic_fma_err_info_data_detail
};
static const generic_mmr_t _ar_nic_fma_err_info_hdr = {
    "AR_NIC_FMA_ERR_INFO_HDR", AR_NIC_FMA_ERR_INFO_HDR, 8, 1, _ar_nic_fma_err_info_hdr_detail
};
static const generic_mmr_t _ar_nic_fma_dbg_errinj_ram = {
    "AR_NIC_FMA_DBG_ERRINJ_RAM", AR_NIC_FMA_DBG_ERRINJ_RAM, 8, 1, _ar_nic_fma_dbg_errinj_ram_detail
};
static const generic_mmr_t _ar_nic_fma_dbg_errinj_pkt = {
    "AR_NIC_FMA_DBG_ERRINJ_PKT", AR_NIC_FMA_DBG_ERRINJ_PKT, 8, 1, _ar_nic_fma_dbg_errinj_pkt_detail
};
static const generic_mmr_t _ar_nic_fma_cfg_credit = {
    "AR_NIC_FMA_CFG_CREDIT", AR_NIC_FMA_CFG_CREDIT, 8, 1, _ar_nic_fma_cfg_credit_detail
};
static const generic_mmr_t _ar_nic_fma_err_info_pi = {
    "AR_NIC_FMA_ERR_INFO_PI", AR_NIC_FMA_ERR_INFO_PI, 8, 1, _ar_nic_fma_err_info_pi_detail
};
static const generic_mmr_t _ar_nic_fma_err_info_sw = {
    "AR_NIC_FMA_ERR_INFO_SW", AR_NIC_FMA_ERR_INFO_SW, 8, 1, _ar_nic_fma_err_info_sw_detail
};

/*
 *  INSTALL AR FMA MMRS
 */
static const generic_mmr_t* _ar_fma_mmrs[] _unused = {
    &_ar_nic_fma_mmr_ring_0_hi_fma,
    &_ar_nic_fma_mmr_ring_0_mid_fma,
    &_ar_nic_fma_mmr_ring_0_lo_fma,
    &_ar_nic_fma_err_flg_1_hi_fma,
    &_ar_nic_fma_err_flg_1_mid_fma,
    &_ar_nic_fma_err_flg_1_lo_fma,
    &_ar_nic_fma_pi_flit_input_stage_2_hi_fma,
    &_ar_nic_fma_pi_flit_input_stage_2_mid_fma,
    &_ar_nic_fma_pi_flit_input_stage_2_lo_fma,
    &_ar_nic_fma_pi_control_decode_desc_read_stage_4_hi_fma,
    &_ar_nic_fma_pi_control_decode_desc_read_stage_4_mid_fma,
    &_ar_nic_fma_pi_control_decode_desc_read_stage_4_lo_fma,
    &_ar_nic_fma_pi_control_data_desc_read_stage_5_hi_fma,
    &_ar_nic_fma_pi_control_data_desc_read_stage_5_mid_fma,
    &_ar_nic_fma_pi_control_data_desc_read_stage_5_lo_fma,
    &_ar_nic_fma_packet_generation_tarb_write_stage_6_hi_fma,
    &_ar_nic_fma_packet_generation_tarb_write_stage_6_mid_fma,
    &_ar_nic_fma_packet_generation_tarb_write_stage_6_lo_fma,
    &_ar_nic_fma_tarb_rd_data_stage_7_hi_fma,
    &_ar_nic_fma_tarb_rd_data_stage_7_mid_fma,
    &_ar_nic_fma_tarb_rd_data_stage_7_lo_fma,
    &_ar_nic_fma_err_flg,
    &_ar_nic_fma_err_clr,
    &_ar_nic_fma_err_hss_msk,
    &_ar_nic_fma_err_os_msk,
    &_ar_nic_fma_err_first_flg,
    &_ar_nic_fma_err_info_ram0,
    &_ar_nic_fma_err_info_ram1,
    &_ar_nic_fma_err_info_data,
    &_ar_nic_fma_err_info_hdr,
    &_ar_nic_fma_dbg_errinj_ram,
    &_ar_nic_fma_dbg_errinj_pkt,
    &_ar_nic_fma_cfg_credit,
    &_ar_nic_fma_err_info_pi,
    &_ar_nic_fma_err_info_sw,
    NULL
};

#endif
