/******************************************************************************
 * COPYRIGHT CRAY INC. ar_lcb_mmrs_h.h
 * FILE: ar_lcb_mmrs_h.h
 * Created by v2h.c on Wed Oct  8 14:39:04 2014
 ******************************************************************************/

#ifndef _AR_LCB_MMRS_H_H_
#define _AR_LCB_MMRS_H_H_

#ifdef __GNUC__
#define _unused __attribute__((unused))
#else
#define _unused
#endif

#ifndef _GENERIC_MMRD_T_
#define _GENERIC_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint64_t _mask;		/* Field bit mask */
} generic_mmrd_t;
#endif

#ifndef _ERRCAT_MMRD_T_
#define _ERRCAT_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint32_t _ec;		/* Field error category */
} errcat_mmrd_t;
#endif

#ifndef _GENERIC_MMR_T_
#define _GENERIC_MMR_T_
typedef struct {
	char* _name;		/* MMR name */
	uint64_t _addr;		/* MMR address */
	int _size;		/* Size in bytes of MMR */
	int _depth;		/* Number of MMR instances */
	const generic_mmrd_t *_info;	/* MMR detail */
} generic_mmr_t;
#endif

static const generic_mmr_t* _ar_lcb_mmrs[] _unused;	/* LCB Array */

/*
 *  AR LCB MMR DETAIL DECLARATIONS
 */
static const generic_mmrd_t _ar_slb_lcb_cfg_run_detail[] = {
    { "EN", AR_SLB_LCB_CFG_RUN_EN_BP, AR_SLB_LCB_CFG_RUN_EN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_cfg_mmr_reset_detail[] = {
    { "EN", AR_SLB_LCB_CFG_MMR_RESET_EN_BP, AR_SLB_LCB_CFG_MMR_RESET_EN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_cfg_tx_fifos_reset_detail[] = {
    { "ON_REINIT", AR_SLB_LCB_CFG_TX_FIFOS_RESET_ON_REINIT_BP, AR_SLB_LCB_CFG_TX_FIFOS_RESET_ON_REINIT_MASK },
    { "RADR", AR_SLB_LCB_CFG_TX_FIFOS_RESET_RADR_BP, AR_SLB_LCB_CFG_TX_FIFOS_RESET_RADR_MASK },
    { "EN", AR_SLB_LCB_CFG_TX_FIFOS_RESET_EN_BP, AR_SLB_LCB_CFG_TX_FIFOS_RESET_EN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_cfg_startup_0_detail[] = {
    { "MAX_RCV_UP_NUM", AR_SLB_LCB_CFG_STARTUP_0_MAX_RCV_UP_NUM_BP, AR_SLB_LCB_CFG_STARTUP_0_MAX_RCV_UP_NUM_MASK },
    { "MIN_RCV_UP_NUM", AR_SLB_LCB_CFG_STARTUP_0_MIN_RCV_UP_NUM_BP, AR_SLB_LCB_CFG_STARTUP_0_MIN_RCV_UP_NUM_MASK },
    { "MIN_REPLAY_TIMEOUT_SEL2", AR_SLB_LCB_CFG_STARTUP_0_MIN_REPLAY_TIMEOUT_SEL2_BP, AR_SLB_LCB_CFG_STARTUP_0_MIN_REPLAY_TIMEOUT_SEL2_MASK },
    { "MIN_REPLAY_TIMEOUT_SEL1", AR_SLB_LCB_CFG_STARTUP_0_MIN_REPLAY_TIMEOUT_SEL1_BP, AR_SLB_LCB_CFG_STARTUP_0_MIN_REPLAY_TIMEOUT_SEL1_MASK },
    { "INIT_REPLAY_TIMEOUT_SEL", AR_SLB_LCB_CFG_STARTUP_0_INIT_REPLAY_TIMEOUT_SEL_BP, AR_SLB_LCB_CFG_STARTUP_0_INIT_REPLAY_TIMEOUT_SEL_MASK },
    { "LN_ALLOWED_TIME_TO_PASS", AR_SLB_LCB_CFG_STARTUP_0_LN_ALLOWED_TIME_TO_PASS_BP, AR_SLB_LCB_CFG_STARTUP_0_LN_ALLOWED_TIME_TO_PASS_MASK },
    { "LN_TEST_REQ_MATCH_CNT", AR_SLB_LCB_CFG_STARTUP_0_LN_TEST_REQ_MATCH_CNT_BP, AR_SLB_LCB_CFG_STARTUP_0_LN_TEST_REQ_MATCH_CNT_MASK },
    { "LN_DISABLE_4_SKEW_MODE", AR_SLB_LCB_CFG_STARTUP_0_LN_DISABLE_4_SKEW_MODE_BP, AR_SLB_LCB_CFG_STARTUP_0_LN_DISABLE_4_SKEW_MODE_MASK },
    { "FORCE_LN_ENABLE", AR_SLB_LCB_CFG_STARTUP_0_FORCE_LN_ENABLE_BP, AR_SLB_LCB_CFG_STARTUP_0_FORCE_LN_ENABLE_MASK },
    { "LN_REINIT_REENABLE", AR_SLB_LCB_CFG_STARTUP_0_LN_REINIT_REENABLE_BP, AR_SLB_LCB_CFG_STARTUP_0_LN_REINIT_REENABLE_MASK },
    { "RX_LN_ALLOWED", AR_SLB_LCB_CFG_STARTUP_0_RX_LN_ALLOWED_BP, AR_SLB_LCB_CFG_STARTUP_0_RX_LN_ALLOWED_MASK },
    { "CRC_PER_LANE_MODE", AR_SLB_LCB_CFG_STARTUP_0_CRC_PER_LANE_MODE_BP, AR_SLB_LCB_CFG_STARTUP_0_CRC_PER_LANE_MODE_MASK },
    { "RX_LANE_FSS", AR_SLB_LCB_CFG_STARTUP_0_RX_LANE_FSS_BP, AR_SLB_LCB_CFG_STARTUP_0_RX_LANE_FSS_MASK },
    { "TX_LANE_FSS", AR_SLB_LCB_CFG_STARTUP_0_TX_LANE_FSS_BP, AR_SLB_LCB_CFG_STARTUP_0_TX_LANE_FSS_MASK },
    { "LOOPBACK", AR_SLB_LCB_CFG_STARTUP_0_LOOPBACK_BP, AR_SLB_LCB_CFG_STARTUP_0_LOOPBACK_MASK },
    { "RX_FIFOS_RESET_RADR", AR_SLB_LCB_CFG_STARTUP_0_RX_FIFOS_RESET_RADR_BP, AR_SLB_LCB_CFG_STARTUP_0_RX_FIFOS_RESET_RADR_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_cfg_startup_1_detail[] = {
    { "LINK_ALIVE_TIMER_MAX", AR_SLB_LCB_CFG_STARTUP_1_LINK_ALIVE_TIMER_MAX_BP, AR_SLB_LCB_CFG_STARTUP_1_LINK_ALIVE_TIMER_MAX_MASK },
    { "LTO_DEGRADE_REENABLE", AR_SLB_LCB_CFG_STARTUP_1_LTO_DEGRADE_REENABLE_BP, AR_SLB_LCB_CFG_STARTUP_1_LTO_DEGRADE_REENABLE_MASK },
    { "LTO_REINIT_REENABLE", AR_SLB_LCB_CFG_STARTUP_1_LTO_REINIT_REENABLE_BP, AR_SLB_LCB_CFG_STARTUP_1_LTO_REINIT_REENABLE_MASK },
    { "REINITS_BEFORE_LINK_LOW", AR_SLB_LCB_CFG_STARTUP_1_REINITS_BEFORE_LINK_LOW_BP, AR_SLB_LCB_CFG_STARTUP_1_REINITS_BEFORE_LINK_LOW_MASK },
    { "LINK_AUTO_RESTART_EN", AR_SLB_LCB_CFG_STARTUP_1_LINK_AUTO_RESTART_EN_BP, AR_SLB_LCB_CFG_STARTUP_1_LINK_AUTO_RESTART_EN_MASK },
    { "LINK_TIMER_DISABLE", AR_SLB_LCB_CFG_STARTUP_1_LINK_TIMER_DISABLE_BP, AR_SLB_LCB_CFG_STARTUP_1_LINK_TIMER_DISABLE_MASK },
    { "PAUSE_ON_REINIT", AR_SLB_LCB_CFG_STARTUP_1_PAUSE_ON_REINIT_BP, AR_SLB_LCB_CFG_STARTUP_1_PAUSE_ON_REINIT_MASK },
    { "USE_REPLAY_BUF_DATA", AR_SLB_LCB_CFG_STARTUP_1_USE_REPLAY_BUF_DATA_BP, AR_SLB_LCB_CFG_STARTUP_1_USE_REPLAY_BUF_DATA_MASK },
    { "TURN_ON_SIGNAL_CNT_SEL", AR_SLB_LCB_CFG_STARTUP_1_TURN_ON_SIGNAL_CNT_SEL_BP, AR_SLB_LCB_CFG_STARTUP_1_TURN_ON_SIGNAL_CNT_SEL_MASK },
    { "BACK_CH_SELECT_PRIORITY", AR_SLB_LCB_CFG_STARTUP_1_BACK_CH_SELECT_PRIORITY_BP, AR_SLB_LCB_CFG_STARTUP_1_BACK_CH_SELECT_PRIORITY_MASK },
    { "RCLK_SELECT_PRIORITY", AR_SLB_LCB_CFG_STARTUP_1_RCLK_SELECT_PRIORITY_BP, AR_SLB_LCB_CFG_STARTUP_1_RCLK_SELECT_PRIORITY_MASK },
    { "THROTTLE_TX_FLITS", AR_SLB_LCB_CFG_STARTUP_1_THROTTLE_TX_FLITS_BP, AR_SLB_LCB_CFG_STARTUP_1_THROTTLE_TX_FLITS_MASK },
    { "IGNORE_RCLK_LOSS", AR_SLB_LCB_CFG_STARTUP_1_IGNORE_RCLK_LOSS_BP, AR_SLB_LCB_CFG_STARTUP_1_IGNORE_RCLK_LOSS_MASK },
    { "IGNORE_SEQ_BAD_CRC", AR_SLB_LCB_CFG_STARTUP_1_IGNORE_SEQ_BAD_CRC_BP, AR_SLB_LCB_CFG_STARTUP_1_IGNORE_SEQ_BAD_CRC_MASK },
    { "NUM_SEQ_BAD_CRC_MAX", AR_SLB_LCB_CFG_STARTUP_1_NUM_SEQ_BAD_CRC_MAX_BP, AR_SLB_LCB_CFG_STARTUP_1_NUM_SEQ_BAD_CRC_MAX_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_sts_startup_0_detail[] = {
    { "VC_ACK_QUIET_CNTR", AR_SLB_LCB_STS_STARTUP_0_VC_ACK_QUIET_CNTR_BP, AR_SLB_LCB_STS_STARTUP_0_VC_ACK_QUIET_CNTR_MASK },
    { "PHIT_QUIET_CNTR", AR_SLB_LCB_STS_STARTUP_0_PHIT_QUIET_CNTR_BP, AR_SLB_LCB_STS_STARTUP_0_PHIT_QUIET_CNTR_MASK },
    { "ROUND_TRIP_UP_CNT", AR_SLB_LCB_STS_STARTUP_0_ROUND_TRIP_UP_CNT_BP, AR_SLB_LCB_STS_STARTUP_0_ROUND_TRIP_UP_CNT_MASK },
    { "RX_LINK3OR_PHY_LN_EN", AR_SLB_LCB_STS_STARTUP_0_RX_LINK3OR_PHY_LN_EN_BP, AR_SLB_LCB_STS_STARTUP_0_RX_LINK3OR_PHY_LN_EN_MASK },
    { "DEGRADE_LN_EN", AR_SLB_LCB_STS_STARTUP_0_DEGRADE_LN_EN_BP, AR_SLB_LCB_STS_STARTUP_0_DEGRADE_LN_EN_MASK },
    { "RX_PHY_LN_EN", AR_SLB_LCB_STS_STARTUP_0_RX_PHY_LN_EN_BP, AR_SLB_LCB_STS_STARTUP_0_RX_PHY_LN_EN_MASK },
    { "TX_PHY_LN_EN", AR_SLB_LCB_STS_STARTUP_0_TX_PHY_LN_EN_BP, AR_SLB_LCB_STS_STARTUP_0_TX_PHY_LN_EN_MASK },
    { "RX_LOGICAL_LN_EN", AR_SLB_LCB_STS_STARTUP_0_RX_LOGICAL_LN_EN_BP, AR_SLB_LCB_STS_STARTUP_0_RX_LOGICAL_LN_EN_MASK },
    { "RX_LN2_LOGICAL_ID", AR_SLB_LCB_STS_STARTUP_0_RX_LN2_LOGICAL_ID_BP, AR_SLB_LCB_STS_STARTUP_0_RX_LN2_LOGICAL_ID_MASK },
    { "RX_LN1_LOGICAL_ID", AR_SLB_LCB_STS_STARTUP_0_RX_LN1_LOGICAL_ID_BP, AR_SLB_LCB_STS_STARTUP_0_RX_LN1_LOGICAL_ID_MASK },
    { "RX_LN0_LOGICAL_ID", AR_SLB_LCB_STS_STARTUP_0_RX_LN0_LOGICAL_ID_BP, AR_SLB_LCB_STS_STARTUP_0_RX_LN0_LOGICAL_ID_MASK },
    { "RX_UP_MODE", AR_SLB_LCB_STS_STARTUP_0_RX_UP_MODE_BP, AR_SLB_LCB_STS_STARTUP_0_RX_UP_MODE_MASK },
    { "TX_UP_MODE", AR_SLB_LCB_STS_STARTUP_0_TX_UP_MODE_BP, AR_SLB_LCB_STS_STARTUP_0_TX_UP_MODE_MASK },
    { "R_Q_LCB_COL_CHAN_ALIVE", AR_SLB_LCB_STS_STARTUP_0_R_Q_LCB_COL_CHAN_ALIVE_BP, AR_SLB_LCB_STS_STARTUP_0_R_Q_LCB_COL_CHAN_ALIVE_MASK },
    { "LINK_ALIVE", AR_SLB_LCB_STS_STARTUP_0_LINK_ALIVE_BP, AR_SLB_LCB_STS_STARTUP_0_LINK_ALIVE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_sts_startup_1_detail[] = {
    { "LINK_ALIVE_TIMER_VALUE", AR_SLB_LCB_STS_STARTUP_1_LINK_ALIVE_TIMER_VALUE_BP, AR_SLB_LCB_STS_STARTUP_1_LINK_ALIVE_TIMER_VALUE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_cfg_discovery_local_detail[] = {
    { "PATTERN", AR_SLB_LCB_CFG_DISCOVERY_LOCAL_PATTERN_BP, AR_SLB_LCB_CFG_DISCOVERY_LOCAL_PATTERN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_sts_discovery_remote_detail[] = {
    { "PATTERN", AR_SLB_LCB_STS_DISCOVERY_REMOTE_PATTERN_BP, AR_SLB_LCB_STS_DISCOVERY_REMOTE_PATTERN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_cfg_scramble_seed_0_detail[] = {
    { "VAL", AR_SLB_LCB_CFG_SCRAMBLE_SEED_0_VAL_BP, AR_SLB_LCB_CFG_SCRAMBLE_SEED_0_VAL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_cfg_scramble_seed_1_detail[] = {
    { "VAL", AR_SLB_LCB_CFG_SCRAMBLE_SEED_1_VAL_BP, AR_SLB_LCB_CFG_SCRAMBLE_SEED_1_VAL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_cfg_scramble_seed_2_detail[] = {
    { "VAL", AR_SLB_LCB_CFG_SCRAMBLE_SEED_2_VAL_BP, AR_SLB_LCB_CFG_SCRAMBLE_SEED_2_VAL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_cfg_degrade_detail[] = {
    { "RESET_SETTINGS", AR_SLB_LCB_CFG_DEGRADE_RESET_SETTINGS_BP, AR_SLB_LCB_CFG_DEGRADE_RESET_SETTINGS_MASK },
    { "CURRENT_CFG_RACES_WON", AR_SLB_LCB_CFG_DEGRADE_CURRENT_CFG_RACES_WON_BP, AR_SLB_LCB_CFG_DEGRADE_CURRENT_CFG_RACES_WON_MASK },
    { "LN_12_RACES_WON", AR_SLB_LCB_CFG_DEGRADE_LN_12_RACES_WON_BP, AR_SLB_LCB_CFG_DEGRADE_LN_12_RACES_WON_MASK },
    { "LN_02_RACES_WON", AR_SLB_LCB_CFG_DEGRADE_LN_02_RACES_WON_BP, AR_SLB_LCB_CFG_DEGRADE_LN_02_RACES_WON_MASK },
    { "LN_01_RACES_WON", AR_SLB_LCB_CFG_DEGRADE_LN_01_RACES_WON_BP, AR_SLB_LCB_CFG_DEGRADE_LN_01_RACES_WON_MASK },
    { "LN_EN_ALT", AR_SLB_LCB_CFG_DEGRADE_LN_EN_ALT_BP, AR_SLB_LCB_CFG_DEGRADE_LN_EN_ALT_MASK },
    { "RACE_WINS_2TRIGGER", AR_SLB_LCB_CFG_DEGRADE_RACE_WINS_2TRIGGER_BP, AR_SLB_LCB_CFG_DEGRADE_RACE_WINS_2TRIGGER_MASK },
    { "RACE_DURATION_SEL", AR_SLB_LCB_CFG_DEGRADE_RACE_DURATION_SEL_BP, AR_SLB_LCB_CFG_DEGRADE_RACE_DURATION_SEL_MASK },
    { "NUM_DEGRADES_ALLOWED", AR_SLB_LCB_CFG_DEGRADE_NUM_DEGRADES_ALLOWED_BP, AR_SLB_LCB_CFG_DEGRADE_NUM_DEGRADES_ALLOWED_MASK },
    { "LN_X_DEGRADE_DISABLE", AR_SLB_LCB_CFG_DEGRADE_LN_X_DEGRADE_DISABLE_BP, AR_SLB_LCB_CFG_DEGRADE_LN_X_DEGRADE_DISABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_cfg_link_kill_en_detail[] = {
    { "FLOW_CTRL_BUF_MBE", AR_SLB_LCB_CFG_LINK_KILL_EN_FLOW_CTRL_BUF_MBE_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_FLOW_CTRL_BUF_MBE_MASK },
    { "FLOW_CTRL_BUF_SBE", AR_SLB_LCB_CFG_LINK_KILL_EN_FLOW_CTRL_BUF_SBE_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_FLOW_CTRL_BUF_SBE_MASK },
    { "REPLAY_BUF_MBE1", AR_SLB_LCB_CFG_LINK_KILL_EN_REPLAY_BUF_MBE1_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_REPLAY_BUF_MBE1_MASK },
    { "REPLAY_BUF_SBE1", AR_SLB_LCB_CFG_LINK_KILL_EN_REPLAY_BUF_SBE1_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_REPLAY_BUF_SBE1_MASK },
    { "REPLAY_BUF_MBE0", AR_SLB_LCB_CFG_LINK_KILL_EN_REPLAY_BUF_MBE0_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_REPLAY_BUF_MBE0_MASK },
    { "REPLAY_BUF_SBE0", AR_SLB_LCB_CFG_LINK_KILL_EN_REPLAY_BUF_SBE0_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_REPLAY_BUF_SBE0_MASK },
    { "NEG_EDGE_LINK_ALIVE", AR_SLB_LCB_CFG_LINK_KILL_EN_NEG_EDGE_LINK_ALIVE_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_NEG_EDGE_LINK_ALIVE_MASK },
    { "VC_ACK_OFLW", AR_SLB_LCB_CFG_LINK_KILL_EN_VC_ACK_OFLW_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_VC_ACK_OFLW_MASK },
    { "RCV_BUF_OFLW", AR_SLB_LCB_CFG_LINK_KILL_EN_RCV_BUF_OFLW_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_RCV_BUF_OFLW_MASK },
    { "FLOW_CTRL_BUF_OFLW", AR_SLB_LCB_CFG_LINK_KILL_EN_FLOW_CTRL_BUF_OFLW_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_FLOW_CTRL_BUF_OFLW_MASK },
    { "UNEXPECTED_REPLAY", AR_SLB_LCB_CFG_LINK_KILL_EN_UNEXPECTED_REPLAY_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_UNEXPECTED_REPLAY_MASK },
    { "RX_LESS_THAN_3_LANES", AR_SLB_LCB_CFG_LINK_KILL_EN_RX_LESS_THAN_3_LANES_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_RX_LESS_THAN_3_LANES_MASK },
    { "TX_LESS_THAN_3_LANES", AR_SLB_LCB_CFG_LINK_KILL_EN_TX_LESS_THAN_3_LANES_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_TX_LESS_THAN_3_LANES_MASK },
    { "HOLD_REINIT", AR_SLB_LCB_CFG_LINK_KILL_EN_HOLD_REINIT_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_HOLD_REINIT_MASK },
    { "OR_OF_ALL_PAUSE_MODES", AR_SLB_LCB_CFG_LINK_KILL_EN_OR_OF_ALL_PAUSE_MODES_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_OR_OF_ALL_PAUSE_MODES_MASK },
    { "MMR_FORCED_REINIT", AR_SLB_LCB_CFG_LINK_KILL_EN_MMR_FORCED_REINIT_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_MMR_FORCED_REINIT_MASK },
    { "REINIT_4_LN_DEGRADE", AR_SLB_LCB_CFG_LINK_KILL_EN_REINIT_4_LN_DEGRADE_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_REINIT_4_LN_DEGRADE_MASK },
    { "RST_4_LINK_TIMEOUT", AR_SLB_LCB_CFG_LINK_KILL_EN_RST_4_LINK_TIMEOUT_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_RST_4_LINK_TIMEOUT_MASK },
    { "RST_4_FAILED_DESKEW", AR_SLB_LCB_CFG_LINK_KILL_EN_RST_4_FAILED_DESKEW_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_RST_4_FAILED_DESKEW_MASK },
    { "REINIT_FROM_PEER", AR_SLB_LCB_CFG_LINK_KILL_EN_REINIT_FROM_PEER_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_REINIT_FROM_PEER_MASK },
    { "RCLK_STOPPED", AR_SLB_LCB_CFG_LINK_KILL_EN_RCLK_STOPPED_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_RCLK_STOPPED_MASK },
    { "SEQ_CRC_ERR", AR_SLB_LCB_CFG_LINK_KILL_EN_SEQ_CRC_ERR_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_SEQ_CRC_ERR_MASK },
    { "RST_4_LOST_TON_SIG", AR_SLB_LCB_CFG_LINK_KILL_EN_RST_4_LOST_TON_SIG_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_RST_4_LOST_TON_SIG_MASK },
    { "DIAG_ONLY", AR_SLB_LCB_CFG_LINK_KILL_EN_DIAG_ONLY_BP, AR_SLB_LCB_CFG_LINK_KILL_EN_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_err_flg_detail[] = {
    { "FLOW_CTRL_BUF_MBE", AR_SLB_LCB_ERR_FLG_FLOW_CTRL_BUF_MBE_BP, AR_SLB_LCB_ERR_FLG_FLOW_CTRL_BUF_MBE_MASK },
    { "FLOW_CTRL_BUF_SBE", AR_SLB_LCB_ERR_FLG_FLOW_CTRL_BUF_SBE_BP, AR_SLB_LCB_ERR_FLG_FLOW_CTRL_BUF_SBE_MASK },
    { "REPLAY_BUF_MBE1", AR_SLB_LCB_ERR_FLG_REPLAY_BUF_MBE1_BP, AR_SLB_LCB_ERR_FLG_REPLAY_BUF_MBE1_MASK },
    { "REPLAY_BUF_SBE1", AR_SLB_LCB_ERR_FLG_REPLAY_BUF_SBE1_BP, AR_SLB_LCB_ERR_FLG_REPLAY_BUF_SBE1_MASK },
    { "REPLAY_BUF_MBE0", AR_SLB_LCB_ERR_FLG_REPLAY_BUF_MBE0_BP, AR_SLB_LCB_ERR_FLG_REPLAY_BUF_MBE0_MASK },
    { "REPLAY_BUF_SBE0", AR_SLB_LCB_ERR_FLG_REPLAY_BUF_SBE0_BP, AR_SLB_LCB_ERR_FLG_REPLAY_BUF_SBE0_MASK },
    { "NEG_EDGE_LINK_ALIVE", AR_SLB_LCB_ERR_FLG_NEG_EDGE_LINK_ALIVE_BP, AR_SLB_LCB_ERR_FLG_NEG_EDGE_LINK_ALIVE_MASK },
    { "VC_ACK_OFLW", AR_SLB_LCB_ERR_FLG_VC_ACK_OFLW_BP, AR_SLB_LCB_ERR_FLG_VC_ACK_OFLW_MASK },
    { "RCV_BUF_OFLW", AR_SLB_LCB_ERR_FLG_RCV_BUF_OFLW_BP, AR_SLB_LCB_ERR_FLG_RCV_BUF_OFLW_MASK },
    { "FLOW_CTRL_BUF_OFLW", AR_SLB_LCB_ERR_FLG_FLOW_CTRL_BUF_OFLW_BP, AR_SLB_LCB_ERR_FLG_FLOW_CTRL_BUF_OFLW_MASK },
    { "UNEXPECTED_REPLAY", AR_SLB_LCB_ERR_FLG_UNEXPECTED_REPLAY_BP, AR_SLB_LCB_ERR_FLG_UNEXPECTED_REPLAY_MASK },
    { "RX_LESS_THAN_3_LANES", AR_SLB_LCB_ERR_FLG_RX_LESS_THAN_3_LANES_BP, AR_SLB_LCB_ERR_FLG_RX_LESS_THAN_3_LANES_MASK },
    { "TX_LESS_THAN_3_LANES", AR_SLB_LCB_ERR_FLG_TX_LESS_THAN_3_LANES_BP, AR_SLB_LCB_ERR_FLG_TX_LESS_THAN_3_LANES_MASK },
    { "HOLD_REINIT", AR_SLB_LCB_ERR_FLG_HOLD_REINIT_BP, AR_SLB_LCB_ERR_FLG_HOLD_REINIT_MASK },
    { "OR_OF_ALL_PAUSE_MODES", AR_SLB_LCB_ERR_FLG_OR_OF_ALL_PAUSE_MODES_BP, AR_SLB_LCB_ERR_FLG_OR_OF_ALL_PAUSE_MODES_MASK },
    { "MMR_FORCED_REINIT", AR_SLB_LCB_ERR_FLG_MMR_FORCED_REINIT_BP, AR_SLB_LCB_ERR_FLG_MMR_FORCED_REINIT_MASK },
    { "REINIT_4_LN_DEGRADE", AR_SLB_LCB_ERR_FLG_REINIT_4_LN_DEGRADE_BP, AR_SLB_LCB_ERR_FLG_REINIT_4_LN_DEGRADE_MASK },
    { "RST_4_LINK_TIMEOUT", AR_SLB_LCB_ERR_FLG_RST_4_LINK_TIMEOUT_BP, AR_SLB_LCB_ERR_FLG_RST_4_LINK_TIMEOUT_MASK },
    { "RST_4_FAILED_DESKEW", AR_SLB_LCB_ERR_FLG_RST_4_FAILED_DESKEW_BP, AR_SLB_LCB_ERR_FLG_RST_4_FAILED_DESKEW_MASK },
    { "REINIT_FROM_PEER", AR_SLB_LCB_ERR_FLG_REINIT_FROM_PEER_BP, AR_SLB_LCB_ERR_FLG_REINIT_FROM_PEER_MASK },
    { "RCLK_STOPPED", AR_SLB_LCB_ERR_FLG_RCLK_STOPPED_BP, AR_SLB_LCB_ERR_FLG_RCLK_STOPPED_MASK },
    { "SEQ_CRC_ERR", AR_SLB_LCB_ERR_FLG_SEQ_CRC_ERR_BP, AR_SLB_LCB_ERR_FLG_SEQ_CRC_ERR_MASK },
    { "RST_4_LOST_TON_SIG", AR_SLB_LCB_ERR_FLG_RST_4_LOST_TON_SIG_BP, AR_SLB_LCB_ERR_FLG_RST_4_LOST_TON_SIG_MASK },
    { "DIAG_ONLY", AR_SLB_LCB_ERR_FLG_DIAG_ONLY_BP, AR_SLB_LCB_ERR_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_err_clr_detail[] = {
    { "FLOW_CTRL_BUF_MBE", AR_SLB_LCB_ERR_CLR_FLOW_CTRL_BUF_MBE_BP, AR_SLB_LCB_ERR_CLR_FLOW_CTRL_BUF_MBE_MASK },
    { "FLOW_CTRL_BUF_SBE", AR_SLB_LCB_ERR_CLR_FLOW_CTRL_BUF_SBE_BP, AR_SLB_LCB_ERR_CLR_FLOW_CTRL_BUF_SBE_MASK },
    { "REPLAY_BUF_MBE1", AR_SLB_LCB_ERR_CLR_REPLAY_BUF_MBE1_BP, AR_SLB_LCB_ERR_CLR_REPLAY_BUF_MBE1_MASK },
    { "REPLAY_BUF_SBE1", AR_SLB_LCB_ERR_CLR_REPLAY_BUF_SBE1_BP, AR_SLB_LCB_ERR_CLR_REPLAY_BUF_SBE1_MASK },
    { "REPLAY_BUF_MBE0", AR_SLB_LCB_ERR_CLR_REPLAY_BUF_MBE0_BP, AR_SLB_LCB_ERR_CLR_REPLAY_BUF_MBE0_MASK },
    { "REPLAY_BUF_SBE0", AR_SLB_LCB_ERR_CLR_REPLAY_BUF_SBE0_BP, AR_SLB_LCB_ERR_CLR_REPLAY_BUF_SBE0_MASK },
    { "NEG_EDGE_LINK_ALIVE", AR_SLB_LCB_ERR_CLR_NEG_EDGE_LINK_ALIVE_BP, AR_SLB_LCB_ERR_CLR_NEG_EDGE_LINK_ALIVE_MASK },
    { "VC_ACK_OFLW", AR_SLB_LCB_ERR_CLR_VC_ACK_OFLW_BP, AR_SLB_LCB_ERR_CLR_VC_ACK_OFLW_MASK },
    { "RCV_BUF_OFLW", AR_SLB_LCB_ERR_CLR_RCV_BUF_OFLW_BP, AR_SLB_LCB_ERR_CLR_RCV_BUF_OFLW_MASK },
    { "FLOW_CTRL_BUF_OFLW", AR_SLB_LCB_ERR_CLR_FLOW_CTRL_BUF_OFLW_BP, AR_SLB_LCB_ERR_CLR_FLOW_CTRL_BUF_OFLW_MASK },
    { "UNEXPECTED_REPLAY", AR_SLB_LCB_ERR_CLR_UNEXPECTED_REPLAY_BP, AR_SLB_LCB_ERR_CLR_UNEXPECTED_REPLAY_MASK },
    { "RX_LESS_THAN_3_LANES", AR_SLB_LCB_ERR_CLR_RX_LESS_THAN_3_LANES_BP, AR_SLB_LCB_ERR_CLR_RX_LESS_THAN_3_LANES_MASK },
    { "TX_LESS_THAN_3_LANES", AR_SLB_LCB_ERR_CLR_TX_LESS_THAN_3_LANES_BP, AR_SLB_LCB_ERR_CLR_TX_LESS_THAN_3_LANES_MASK },
    { "HOLD_REINIT", AR_SLB_LCB_ERR_CLR_HOLD_REINIT_BP, AR_SLB_LCB_ERR_CLR_HOLD_REINIT_MASK },
    { "OR_OF_ALL_PAUSE_MODES", AR_SLB_LCB_ERR_CLR_OR_OF_ALL_PAUSE_MODES_BP, AR_SLB_LCB_ERR_CLR_OR_OF_ALL_PAUSE_MODES_MASK },
    { "MMR_FORCED_REINIT", AR_SLB_LCB_ERR_CLR_MMR_FORCED_REINIT_BP, AR_SLB_LCB_ERR_CLR_MMR_FORCED_REINIT_MASK },
    { "REINIT_4_LN_DEGRADE", AR_SLB_LCB_ERR_CLR_REINIT_4_LN_DEGRADE_BP, AR_SLB_LCB_ERR_CLR_REINIT_4_LN_DEGRADE_MASK },
    { "RST_4_LINK_TIMEOUT", AR_SLB_LCB_ERR_CLR_RST_4_LINK_TIMEOUT_BP, AR_SLB_LCB_ERR_CLR_RST_4_LINK_TIMEOUT_MASK },
    { "RST_4_FAILED_DESKEW", AR_SLB_LCB_ERR_CLR_RST_4_FAILED_DESKEW_BP, AR_SLB_LCB_ERR_CLR_RST_4_FAILED_DESKEW_MASK },
    { "REINIT_FROM_PEER", AR_SLB_LCB_ERR_CLR_REINIT_FROM_PEER_BP, AR_SLB_LCB_ERR_CLR_REINIT_FROM_PEER_MASK },
    { "RCLK_STOPPED", AR_SLB_LCB_ERR_CLR_RCLK_STOPPED_BP, AR_SLB_LCB_ERR_CLR_RCLK_STOPPED_MASK },
    { "SEQ_CRC_ERR", AR_SLB_LCB_ERR_CLR_SEQ_CRC_ERR_BP, AR_SLB_LCB_ERR_CLR_SEQ_CRC_ERR_MASK },
    { "RST_4_LOST_TON_SIG", AR_SLB_LCB_ERR_CLR_RST_4_LOST_TON_SIG_BP, AR_SLB_LCB_ERR_CLR_RST_4_LOST_TON_SIG_MASK },
    { "DIAG_ONLY", AR_SLB_LCB_ERR_CLR_DIAG_ONLY_BP, AR_SLB_LCB_ERR_CLR_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_err_hss_msk_detail[] = {
    { "FLOW_CTRL_BUF_MBE", AR_SLB_LCB_ERR_HSS_MSK_FLOW_CTRL_BUF_MBE_BP, AR_SLB_LCB_ERR_HSS_MSK_FLOW_CTRL_BUF_MBE_MASK },
    { "FLOW_CTRL_BUF_SBE", AR_SLB_LCB_ERR_HSS_MSK_FLOW_CTRL_BUF_SBE_BP, AR_SLB_LCB_ERR_HSS_MSK_FLOW_CTRL_BUF_SBE_MASK },
    { "REPLAY_BUF_MBE1", AR_SLB_LCB_ERR_HSS_MSK_REPLAY_BUF_MBE1_BP, AR_SLB_LCB_ERR_HSS_MSK_REPLAY_BUF_MBE1_MASK },
    { "REPLAY_BUF_SBE1", AR_SLB_LCB_ERR_HSS_MSK_REPLAY_BUF_SBE1_BP, AR_SLB_LCB_ERR_HSS_MSK_REPLAY_BUF_SBE1_MASK },
    { "REPLAY_BUF_MBE0", AR_SLB_LCB_ERR_HSS_MSK_REPLAY_BUF_MBE0_BP, AR_SLB_LCB_ERR_HSS_MSK_REPLAY_BUF_MBE0_MASK },
    { "REPLAY_BUF_SBE0", AR_SLB_LCB_ERR_HSS_MSK_REPLAY_BUF_SBE0_BP, AR_SLB_LCB_ERR_HSS_MSK_REPLAY_BUF_SBE0_MASK },
    { "NEG_EDGE_LINK_ALIVE", AR_SLB_LCB_ERR_HSS_MSK_NEG_EDGE_LINK_ALIVE_BP, AR_SLB_LCB_ERR_HSS_MSK_NEG_EDGE_LINK_ALIVE_MASK },
    { "VC_ACK_OFLW", AR_SLB_LCB_ERR_HSS_MSK_VC_ACK_OFLW_BP, AR_SLB_LCB_ERR_HSS_MSK_VC_ACK_OFLW_MASK },
    { "RCV_BUF_OFLW", AR_SLB_LCB_ERR_HSS_MSK_RCV_BUF_OFLW_BP, AR_SLB_LCB_ERR_HSS_MSK_RCV_BUF_OFLW_MASK },
    { "FLOW_CTRL_BUF_OFLW", AR_SLB_LCB_ERR_HSS_MSK_FLOW_CTRL_BUF_OFLW_BP, AR_SLB_LCB_ERR_HSS_MSK_FLOW_CTRL_BUF_OFLW_MASK },
    { "UNEXPECTED_REPLAY", AR_SLB_LCB_ERR_HSS_MSK_UNEXPECTED_REPLAY_BP, AR_SLB_LCB_ERR_HSS_MSK_UNEXPECTED_REPLAY_MASK },
    { "RX_LESS_THAN_3_LANES", AR_SLB_LCB_ERR_HSS_MSK_RX_LESS_THAN_3_LANES_BP, AR_SLB_LCB_ERR_HSS_MSK_RX_LESS_THAN_3_LANES_MASK },
    { "TX_LESS_THAN_3_LANES", AR_SLB_LCB_ERR_HSS_MSK_TX_LESS_THAN_3_LANES_BP, AR_SLB_LCB_ERR_HSS_MSK_TX_LESS_THAN_3_LANES_MASK },
    { "HOLD_REINIT", AR_SLB_LCB_ERR_HSS_MSK_HOLD_REINIT_BP, AR_SLB_LCB_ERR_HSS_MSK_HOLD_REINIT_MASK },
    { "OR_OF_ALL_PAUSE_MODES", AR_SLB_LCB_ERR_HSS_MSK_OR_OF_ALL_PAUSE_MODES_BP, AR_SLB_LCB_ERR_HSS_MSK_OR_OF_ALL_PAUSE_MODES_MASK },
    { "MMR_FORCED_REINIT", AR_SLB_LCB_ERR_HSS_MSK_MMR_FORCED_REINIT_BP, AR_SLB_LCB_ERR_HSS_MSK_MMR_FORCED_REINIT_MASK },
    { "REINIT_4_LN_DEGRADE", AR_SLB_LCB_ERR_HSS_MSK_REINIT_4_LN_DEGRADE_BP, AR_SLB_LCB_ERR_HSS_MSK_REINIT_4_LN_DEGRADE_MASK },
    { "RST_4_LINK_TIMEOUT", AR_SLB_LCB_ERR_HSS_MSK_RST_4_LINK_TIMEOUT_BP, AR_SLB_LCB_ERR_HSS_MSK_RST_4_LINK_TIMEOUT_MASK },
    { "RST_4_FAILED_DESKEW", AR_SLB_LCB_ERR_HSS_MSK_RST_4_FAILED_DESKEW_BP, AR_SLB_LCB_ERR_HSS_MSK_RST_4_FAILED_DESKEW_MASK },
    { "REINIT_FROM_PEER", AR_SLB_LCB_ERR_HSS_MSK_REINIT_FROM_PEER_BP, AR_SLB_LCB_ERR_HSS_MSK_REINIT_FROM_PEER_MASK },
    { "RCLK_STOPPED", AR_SLB_LCB_ERR_HSS_MSK_RCLK_STOPPED_BP, AR_SLB_LCB_ERR_HSS_MSK_RCLK_STOPPED_MASK },
    { "SEQ_CRC_ERR", AR_SLB_LCB_ERR_HSS_MSK_SEQ_CRC_ERR_BP, AR_SLB_LCB_ERR_HSS_MSK_SEQ_CRC_ERR_MASK },
    { "RST_4_LOST_TON_SIG", AR_SLB_LCB_ERR_HSS_MSK_RST_4_LOST_TON_SIG_BP, AR_SLB_LCB_ERR_HSS_MSK_RST_4_LOST_TON_SIG_MASK },
    { "DIAG_ONLY", AR_SLB_LCB_ERR_HSS_MSK_DIAG_ONLY_BP, AR_SLB_LCB_ERR_HSS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_err_first_flg_detail[] = {
    { "FLOW_CTRL_BUF_MBE", AR_SLB_LCB_ERR_FIRST_FLG_FLOW_CTRL_BUF_MBE_BP, AR_SLB_LCB_ERR_FIRST_FLG_FLOW_CTRL_BUF_MBE_MASK },
    { "FLOW_CTRL_BUF_SBE", AR_SLB_LCB_ERR_FIRST_FLG_FLOW_CTRL_BUF_SBE_BP, AR_SLB_LCB_ERR_FIRST_FLG_FLOW_CTRL_BUF_SBE_MASK },
    { "REPLAY_BUF_MBE1", AR_SLB_LCB_ERR_FIRST_FLG_REPLAY_BUF_MBE1_BP, AR_SLB_LCB_ERR_FIRST_FLG_REPLAY_BUF_MBE1_MASK },
    { "REPLAY_BUF_SBE1", AR_SLB_LCB_ERR_FIRST_FLG_REPLAY_BUF_SBE1_BP, AR_SLB_LCB_ERR_FIRST_FLG_REPLAY_BUF_SBE1_MASK },
    { "REPLAY_BUF_MBE0", AR_SLB_LCB_ERR_FIRST_FLG_REPLAY_BUF_MBE0_BP, AR_SLB_LCB_ERR_FIRST_FLG_REPLAY_BUF_MBE0_MASK },
    { "REPLAY_BUF_SBE0", AR_SLB_LCB_ERR_FIRST_FLG_REPLAY_BUF_SBE0_BP, AR_SLB_LCB_ERR_FIRST_FLG_REPLAY_BUF_SBE0_MASK },
    { "NEG_EDGE_LINK_ALIVE", AR_SLB_LCB_ERR_FIRST_FLG_NEG_EDGE_LINK_ALIVE_BP, AR_SLB_LCB_ERR_FIRST_FLG_NEG_EDGE_LINK_ALIVE_MASK },
    { "VC_ACK_OFLW", AR_SLB_LCB_ERR_FIRST_FLG_VC_ACK_OFLW_BP, AR_SLB_LCB_ERR_FIRST_FLG_VC_ACK_OFLW_MASK },
    { "RCV_BUF_OFLW", AR_SLB_LCB_ERR_FIRST_FLG_RCV_BUF_OFLW_BP, AR_SLB_LCB_ERR_FIRST_FLG_RCV_BUF_OFLW_MASK },
    { "FLOW_CTRL_BUF_OFLW", AR_SLB_LCB_ERR_FIRST_FLG_FLOW_CTRL_BUF_OFLW_BP, AR_SLB_LCB_ERR_FIRST_FLG_FLOW_CTRL_BUF_OFLW_MASK },
    { "UNEXPECTED_REPLAY", AR_SLB_LCB_ERR_FIRST_FLG_UNEXPECTED_REPLAY_BP, AR_SLB_LCB_ERR_FIRST_FLG_UNEXPECTED_REPLAY_MASK },
    { "RX_LESS_THAN_3_LANES", AR_SLB_LCB_ERR_FIRST_FLG_RX_LESS_THAN_3_LANES_BP, AR_SLB_LCB_ERR_FIRST_FLG_RX_LESS_THAN_3_LANES_MASK },
    { "TX_LESS_THAN_3_LANES", AR_SLB_LCB_ERR_FIRST_FLG_TX_LESS_THAN_3_LANES_BP, AR_SLB_LCB_ERR_FIRST_FLG_TX_LESS_THAN_3_LANES_MASK },
    { "HOLD_REINIT", AR_SLB_LCB_ERR_FIRST_FLG_HOLD_REINIT_BP, AR_SLB_LCB_ERR_FIRST_FLG_HOLD_REINIT_MASK },
    { "OR_OF_ALL_PAUSE_MODES", AR_SLB_LCB_ERR_FIRST_FLG_OR_OF_ALL_PAUSE_MODES_BP, AR_SLB_LCB_ERR_FIRST_FLG_OR_OF_ALL_PAUSE_MODES_MASK },
    { "MMR_FORCED_REINIT", AR_SLB_LCB_ERR_FIRST_FLG_MMR_FORCED_REINIT_BP, AR_SLB_LCB_ERR_FIRST_FLG_MMR_FORCED_REINIT_MASK },
    { "REINIT_4_LN_DEGRADE", AR_SLB_LCB_ERR_FIRST_FLG_REINIT_4_LN_DEGRADE_BP, AR_SLB_LCB_ERR_FIRST_FLG_REINIT_4_LN_DEGRADE_MASK },
    { "RST_4_LINK_TIMEOUT", AR_SLB_LCB_ERR_FIRST_FLG_RST_4_LINK_TIMEOUT_BP, AR_SLB_LCB_ERR_FIRST_FLG_RST_4_LINK_TIMEOUT_MASK },
    { "RST_4_FAILED_DESKEW", AR_SLB_LCB_ERR_FIRST_FLG_RST_4_FAILED_DESKEW_BP, AR_SLB_LCB_ERR_FIRST_FLG_RST_4_FAILED_DESKEW_MASK },
    { "REINIT_FROM_PEER", AR_SLB_LCB_ERR_FIRST_FLG_REINIT_FROM_PEER_BP, AR_SLB_LCB_ERR_FIRST_FLG_REINIT_FROM_PEER_MASK },
    { "RCLK_STOPPED", AR_SLB_LCB_ERR_FIRST_FLG_RCLK_STOPPED_BP, AR_SLB_LCB_ERR_FIRST_FLG_RCLK_STOPPED_MASK },
    { "SEQ_CRC_ERR", AR_SLB_LCB_ERR_FIRST_FLG_SEQ_CRC_ERR_BP, AR_SLB_LCB_ERR_FIRST_FLG_SEQ_CRC_ERR_MASK },
    { "RST_4_LOST_TON_SIG", AR_SLB_LCB_ERR_FIRST_FLG_RST_4_LOST_TON_SIG_BP, AR_SLB_LCB_ERR_FIRST_FLG_RST_4_LOST_TON_SIG_MASK },
    { "DIAG_ONLY", AR_SLB_LCB_ERR_FIRST_FLG_DIAG_ONLY_BP, AR_SLB_LCB_ERR_FIRST_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_dbg_good_up_cnt_detail[] = {
    { "CNT", AR_SLB_LCB_DBG_GOOD_UP_CNT_CNT_BP, AR_SLB_LCB_DBG_GOOD_UP_CNT_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_dbg_accepted_up_cnt_detail[] = {
    { "CNT", AR_SLB_LCB_DBG_ACCEPTED_UP_CNT_CNT_BP, AR_SLB_LCB_DBG_ACCEPTED_UP_CNT_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_dbg_clk_cntr_detail[] = {
    { "NEW_VALUE_WAS_STROBED", AR_SLB_LCB_DBG_CLK_CNTR_NEW_VALUE_WAS_STROBED_BP, AR_SLB_LCB_DBG_CLK_CNTR_NEW_VALUE_WAS_STROBED_MASK },
    { "STROBE_ON_LCLK_CNTR", AR_SLB_LCB_DBG_CLK_CNTR_STROBE_ON_LCLK_CNTR_BP, AR_SLB_LCB_DBG_CLK_CNTR_STROBE_ON_LCLK_CNTR_MASK },
    { "SELECT", AR_SLB_LCB_DBG_CLK_CNTR_SELECT_BP, AR_SLB_LCB_DBG_CLK_CNTR_SELECT_MASK },
    { "CNT", AR_SLB_LCB_DBG_CLK_CNTR_CNT_BP, AR_SLB_LCB_DBG_CLK_CNTR_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_cfg_perf_cntr_reset_detail[] = {
    { "HOLD_CRC_ERR_CNTRS", AR_SLB_LCB_CFG_PERF_CNTR_RESET_HOLD_CRC_ERR_CNTRS_BP, AR_SLB_LCB_CFG_PERF_CNTR_RESET_HOLD_CRC_ERR_CNTRS_MASK },
    { "CLR_CRC_ERR_CNTRS", AR_SLB_LCB_CFG_PERF_CNTR_RESET_CLR_CRC_ERR_CNTRS_BP, AR_SLB_LCB_CFG_PERF_CNTR_RESET_CLR_CRC_ERR_CNTRS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_err_info_crc_cnt_0_detail[] = {
    { "LN0_CRC_ERR_CNT", AR_SLB_LCB_ERR_INFO_CRC_CNT_0_LN0_CRC_ERR_CNT_BP, AR_SLB_LCB_ERR_INFO_CRC_CNT_0_LN0_CRC_ERR_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_err_info_crc_cnt_1_detail[] = {
    { "LN1_CRC_ERR_CNT", AR_SLB_LCB_ERR_INFO_CRC_CNT_1_LN1_CRC_ERR_CNT_BP, AR_SLB_LCB_ERR_INFO_CRC_CNT_1_LN1_CRC_ERR_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_err_info_crc_cnt_2_detail[] = {
    { "LN2_CRC_ERR_CNT", AR_SLB_LCB_ERR_INFO_CRC_CNT_2_LN2_CRC_ERR_CNT_BP, AR_SLB_LCB_ERR_INFO_CRC_CNT_2_LN2_CRC_ERR_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_err_info_crc_cnt_3_detail[] = {
    { "MULTIPLE_LN_ERR_CNT", AR_SLB_LCB_ERR_INFO_CRC_CNT_3_MULTIPLE_LN_ERR_CNT_BP, AR_SLB_LCB_ERR_INFO_CRC_CNT_3_MULTIPLE_LN_ERR_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_err_info_crc_cnt_4_detail[] = {
    { "TOTAL_CRC_ERR_CNT", AR_SLB_LCB_ERR_INFO_CRC_CNT_4_TOTAL_CRC_ERR_CNT_BP, AR_SLB_LCB_ERR_INFO_CRC_CNT_4_TOTAL_CRC_ERR_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_err_info_crc_cnt_5_detail[] = {
    { "RX_REPLAY_CNT", AR_SLB_LCB_ERR_INFO_CRC_CNT_5_RX_REPLAY_CNT_BP, AR_SLB_LCB_ERR_INFO_CRC_CNT_5_RX_REPLAY_CNT_MASK },
    { "TX_REPLAY_CNT", AR_SLB_LCB_ERR_INFO_CRC_CNT_5_TX_REPLAY_CNT_BP, AR_SLB_LCB_ERR_INFO_CRC_CNT_5_TX_REPLAY_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_err_info_misc_cnt_detail[] = {
    { "RST_FOR_FAILED_DESKEW_CNT", AR_SLB_LCB_ERR_INFO_MISC_CNT_RST_FOR_FAILED_DESKEW_CNT_BP, AR_SLB_LCB_ERR_INFO_MISC_CNT_RST_FOR_FAILED_DESKEW_CNT_MASK },
    { "REINITS_B4_LINK_LOW_CNT", AR_SLB_LCB_ERR_INFO_MISC_CNT_REINITS_B4_LINK_LOW_CNT_BP, AR_SLB_LCB_ERR_INFO_MISC_CNT_REINITS_B4_LINK_LOW_CNT_MASK },
    { "NOISY_DEGRADE_CNT", AR_SLB_LCB_ERR_INFO_MISC_CNT_NOISY_DEGRADE_CNT_BP, AR_SLB_LCB_ERR_INFO_MISC_CNT_NOISY_DEGRADE_CNT_MASK },
    { "UNEXPECTED_REPLAY_CNT", AR_SLB_LCB_ERR_INFO_MISC_CNT_UNEXPECTED_REPLAY_CNT_BP, AR_SLB_LCB_ERR_INFO_MISC_CNT_UNEXPECTED_REPLAY_CNT_MASK },
    { "REINIT_FOR_LINK_TOUT_CNT", AR_SLB_LCB_ERR_INFO_MISC_CNT_REINIT_FOR_LINK_TOUT_CNT_BP, AR_SLB_LCB_ERR_INFO_MISC_CNT_REINIT_FOR_LINK_TOUT_CNT_MASK },
    { "REINIT_FROM_PEER_CNT", AR_SLB_LCB_ERR_INFO_MISC_CNT_REINIT_FROM_PEER_CNT_BP, AR_SLB_LCB_ERR_INFO_MISC_CNT_REINIT_FROM_PEER_CNT_MASK },
    { "LOST_RCLK_REINIT_CNT2", AR_SLB_LCB_ERR_INFO_MISC_CNT_LOST_RCLK_REINIT_CNT2_BP, AR_SLB_LCB_ERR_INFO_MISC_CNT_LOST_RCLK_REINIT_CNT2_MASK },
    { "LOST_RCLK_REINIT_CNT1", AR_SLB_LCB_ERR_INFO_MISC_CNT_LOST_RCLK_REINIT_CNT1_BP, AR_SLB_LCB_ERR_INFO_MISC_CNT_LOST_RCLK_REINIT_CNT1_MASK },
    { "LOST_RCLK_REINIT_CNT0", AR_SLB_LCB_ERR_INFO_MISC_CNT_LOST_RCLK_REINIT_CNT0_BP, AR_SLB_LCB_ERR_INFO_MISC_CNT_LOST_RCLK_REINIT_CNT0_MASK },
    { "SEQ_CRC_REINIT_CNT", AR_SLB_LCB_ERR_INFO_MISC_CNT_SEQ_CRC_REINIT_CNT_BP, AR_SLB_LCB_ERR_INFO_MISC_CNT_SEQ_CRC_REINIT_CNT_MASK },
    { "RST_FOR_LOST_TOS_CNT", AR_SLB_LCB_ERR_INFO_MISC_CNT_RST_FOR_LOST_TOS_CNT_BP, AR_SLB_LCB_ERR_INFO_MISC_CNT_RST_FOR_LOST_TOS_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_err_info_ecc_cnt_0_detail[] = {
    { "FLOW_CTRL_BUF_MBE_CNT", AR_SLB_LCB_ERR_INFO_ECC_CNT_0_FLOW_CTRL_BUF_MBE_CNT_BP, AR_SLB_LCB_ERR_INFO_ECC_CNT_0_FLOW_CTRL_BUF_MBE_CNT_MASK },
    { "FLOW_CTRL_BUF_SBE_CNT", AR_SLB_LCB_ERR_INFO_ECC_CNT_0_FLOW_CTRL_BUF_SBE_CNT_BP, AR_SLB_LCB_ERR_INFO_ECC_CNT_0_FLOW_CTRL_BUF_SBE_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_err_info_ecc_cnt_1_detail[] = {
    { "REPLAY_BUF_MBE_CNT1", AR_SLB_LCB_ERR_INFO_ECC_CNT_1_REPLAY_BUF_MBE_CNT1_BP, AR_SLB_LCB_ERR_INFO_ECC_CNT_1_REPLAY_BUF_MBE_CNT1_MASK },
    { "REPLAY_BUF_SBE_CNT1", AR_SLB_LCB_ERR_INFO_ECC_CNT_1_REPLAY_BUF_SBE_CNT1_BP, AR_SLB_LCB_ERR_INFO_ECC_CNT_1_REPLAY_BUF_SBE_CNT1_MASK },
    { "REPLAY_BUF_MBE_CNT0", AR_SLB_LCB_ERR_INFO_ECC_CNT_1_REPLAY_BUF_MBE_CNT0_BP, AR_SLB_LCB_ERR_INFO_ECC_CNT_1_REPLAY_BUF_MBE_CNT0_MASK },
    { "REPLAY_BUF_SBE_CNT0", AR_SLB_LCB_ERR_INFO_ECC_CNT_1_REPLAY_BUF_SBE_CNT0_BP, AR_SLB_LCB_ERR_INFO_ECC_CNT_1_REPLAY_BUF_SBE_CNT0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_err_info_rp_buf_sbe_0_detail[] = {
    { "SYNDROME", AR_SLB_LCB_ERR_INFO_RP_BUF_SBE_0_SYNDROME_BP, AR_SLB_LCB_ERR_INFO_RP_BUF_SBE_0_SYNDROME_MASK },
    { "MMR_CREATED_SBE", AR_SLB_LCB_ERR_INFO_RP_BUF_SBE_0_MMR_CREATED_SBE_BP, AR_SLB_LCB_ERR_INFO_RP_BUF_SBE_0_MMR_CREATED_SBE_MASK },
    { "CHK", AR_SLB_LCB_ERR_INFO_RP_BUF_SBE_0_CHK_BP, AR_SLB_LCB_ERR_INFO_RP_BUF_SBE_0_CHK_MASK },
    { "DATA", AR_SLB_LCB_ERR_INFO_RP_BUF_SBE_0_DATA_BP, AR_SLB_LCB_ERR_INFO_RP_BUF_SBE_0_DATA_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_err_info_rp_buf_mbe_0_detail[] = {
    { "SYNDROME", AR_SLB_LCB_ERR_INFO_RP_BUF_MBE_0_SYNDROME_BP, AR_SLB_LCB_ERR_INFO_RP_BUF_MBE_0_SYNDROME_MASK },
    { "MMR_CREATED_MBE", AR_SLB_LCB_ERR_INFO_RP_BUF_MBE_0_MMR_CREATED_MBE_BP, AR_SLB_LCB_ERR_INFO_RP_BUF_MBE_0_MMR_CREATED_MBE_MASK },
    { "CHK", AR_SLB_LCB_ERR_INFO_RP_BUF_MBE_0_CHK_BP, AR_SLB_LCB_ERR_INFO_RP_BUF_MBE_0_CHK_MASK },
    { "DATA", AR_SLB_LCB_ERR_INFO_RP_BUF_MBE_0_DATA_BP, AR_SLB_LCB_ERR_INFO_RP_BUF_MBE_0_DATA_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_err_info_rp_buf_sbe_1_detail[] = {
    { "SIDEBAND_SBE", AR_SLB_LCB_ERR_INFO_RP_BUF_SBE_1_SIDEBAND_SBE_BP, AR_SLB_LCB_ERR_INFO_RP_BUF_SBE_1_SIDEBAND_SBE_MASK },
    { "SYNDROME", AR_SLB_LCB_ERR_INFO_RP_BUF_SBE_1_SYNDROME_BP, AR_SLB_LCB_ERR_INFO_RP_BUF_SBE_1_SYNDROME_MASK },
    { "MMR_CREATED_SBE", AR_SLB_LCB_ERR_INFO_RP_BUF_SBE_1_MMR_CREATED_SBE_BP, AR_SLB_LCB_ERR_INFO_RP_BUF_SBE_1_MMR_CREATED_SBE_MASK },
    { "CHK", AR_SLB_LCB_ERR_INFO_RP_BUF_SBE_1_CHK_BP, AR_SLB_LCB_ERR_INFO_RP_BUF_SBE_1_CHK_MASK },
    { "DATA", AR_SLB_LCB_ERR_INFO_RP_BUF_SBE_1_DATA_BP, AR_SLB_LCB_ERR_INFO_RP_BUF_SBE_1_DATA_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_err_info_rp_buf_mbe_1_detail[] = {
    { "SIDEBAND_MBE", AR_SLB_LCB_ERR_INFO_RP_BUF_MBE_1_SIDEBAND_MBE_BP, AR_SLB_LCB_ERR_INFO_RP_BUF_MBE_1_SIDEBAND_MBE_MASK },
    { "SYNDROME", AR_SLB_LCB_ERR_INFO_RP_BUF_MBE_1_SYNDROME_BP, AR_SLB_LCB_ERR_INFO_RP_BUF_MBE_1_SYNDROME_MASK },
    { "MMR_CREATED_MBE", AR_SLB_LCB_ERR_INFO_RP_BUF_MBE_1_MMR_CREATED_MBE_BP, AR_SLB_LCB_ERR_INFO_RP_BUF_MBE_1_MMR_CREATED_MBE_MASK },
    { "CHK", AR_SLB_LCB_ERR_INFO_RP_BUF_MBE_1_CHK_BP, AR_SLB_LCB_ERR_INFO_RP_BUF_MBE_1_CHK_MASK },
    { "DATA", AR_SLB_LCB_ERR_INFO_RP_BUF_MBE_1_DATA_BP, AR_SLB_LCB_ERR_INFO_RP_BUF_MBE_1_DATA_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_err_info_fl_buf_sbe_detail[] = {
    { "MMR_CREATED_SBE", AR_SLB_LCB_ERR_INFO_FL_BUF_SBE_MMR_CREATED_SBE_BP, AR_SLB_LCB_ERR_INFO_FL_BUF_SBE_MMR_CREATED_SBE_MASK },
    { "SYNDROME", AR_SLB_LCB_ERR_INFO_FL_BUF_SBE_SYNDROME_BP, AR_SLB_LCB_ERR_INFO_FL_BUF_SBE_SYNDROME_MASK },
    { "CHK", AR_SLB_LCB_ERR_INFO_FL_BUF_SBE_CHK_BP, AR_SLB_LCB_ERR_INFO_FL_BUF_SBE_CHK_MASK },
    { "DATA", AR_SLB_LCB_ERR_INFO_FL_BUF_SBE_DATA_BP, AR_SLB_LCB_ERR_INFO_FL_BUF_SBE_DATA_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_err_info_fl_buf_mbe_detail[] = {
    { "MMR_CREATED_MBE", AR_SLB_LCB_ERR_INFO_FL_BUF_MBE_MMR_CREATED_MBE_BP, AR_SLB_LCB_ERR_INFO_FL_BUF_MBE_MMR_CREATED_MBE_MASK },
    { "SYNDROME", AR_SLB_LCB_ERR_INFO_FL_BUF_MBE_SYNDROME_BP, AR_SLB_LCB_ERR_INFO_FL_BUF_MBE_SYNDROME_MASK },
    { "CHK", AR_SLB_LCB_ERR_INFO_FL_BUF_MBE_CHK_BP, AR_SLB_LCB_ERR_INFO_FL_BUF_MBE_CHK_MASK },
    { "DATA", AR_SLB_LCB_ERR_INFO_FL_BUF_MBE_DATA_BP, AR_SLB_LCB_ERR_INFO_FL_BUF_MBE_DATA_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_dbg_errinj_crc_detail[] = {
    { "CRC_ERR_PROBABILITY", AR_SLB_LCB_DBG_ERRINJ_CRC_CRC_ERR_PROBABILITY_BP, AR_SLB_LCB_DBG_ERRINJ_CRC_CRC_ERR_PROBABILITY_MASK },
    { "NUM_CRC_UP_ERRS", AR_SLB_LCB_DBG_ERRINJ_CRC_NUM_CRC_UP_ERRS_BP, AR_SLB_LCB_DBG_ERRINJ_CRC_NUM_CRC_UP_ERRS_MASK },
    { "RANDOM_XFR_ERR", AR_SLB_LCB_DBG_ERRINJ_CRC_RANDOM_XFR_ERR_BP, AR_SLB_LCB_DBG_ERRINJ_CRC_RANDOM_XFR_ERR_MASK },
    { "CRC_ERR_LN_EN", AR_SLB_LCB_DBG_ERRINJ_CRC_CRC_ERR_LN_EN_BP, AR_SLB_LCB_DBG_ERRINJ_CRC_CRC_ERR_LN_EN_MASK },
    { "CRC_ERR_XFR_EN", AR_SLB_LCB_DBG_ERRINJ_CRC_CRC_ERR_XFR_EN_BP, AR_SLB_LCB_DBG_ERRINJ_CRC_CRC_ERR_XFR_EN_MASK },
    { "CRC_ERR_BIT_EN", AR_SLB_LCB_DBG_ERRINJ_CRC_CRC_ERR_BIT_EN_BP, AR_SLB_LCB_DBG_ERRINJ_CRC_CRC_ERR_BIT_EN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_dbg_errinj_crc_seed_detail[] = {
    { "VAL", AR_SLB_LCB_DBG_ERRINJ_CRC_SEED_VAL_BP, AR_SLB_LCB_DBG_ERRINJ_CRC_SEED_VAL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_dbg_errinj_ecc_detail[] = {
    { "CLR_ECC_ERROR_CNTS", AR_SLB_LCB_DBG_ERRINJ_ECC_CLR_ECC_ERROR_CNTS_BP, AR_SLB_LCB_DBG_ERRINJ_ECC_CLR_ECC_ERROR_CNTS_MASK },
    { "ADDRESS1", AR_SLB_LCB_DBG_ERRINJ_ECC_ADDRESS1_BP, AR_SLB_LCB_DBG_ERRINJ_ECC_ADDRESS1_MASK },
    { "ADDRESS0", AR_SLB_LCB_DBG_ERRINJ_ECC_ADDRESS0_BP, AR_SLB_LCB_DBG_ERRINJ_ECC_ADDRESS0_MASK },
    { "CHECKBYTE", AR_SLB_LCB_DBG_ERRINJ_ECC_CHECKBYTE_BP, AR_SLB_LCB_DBG_ERRINJ_ECC_CHECKBYTE_MASK },
    { "RAMSELECT", AR_SLB_LCB_DBG_ERRINJ_ECC_RAMSELECT_BP, AR_SLB_LCB_DBG_ERRINJ_ECC_RAMSELECT_MASK },
    { "MODE", AR_SLB_LCB_DBG_ERRINJ_ECC_MODE_BP, AR_SLB_LCB_DBG_ERRINJ_ECC_MODE_MASK },
    { "ENABLE", AR_SLB_LCB_DBG_ERRINJ_ECC_ENABLE_BP, AR_SLB_LCB_DBG_ERRINJ_ECC_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_dbg_errinj_misc_detail[] = {
    { "FORCE_LOST_TOS", AR_SLB_LCB_DBG_ERRINJ_MISC_FORCE_LOST_TOS_BP, AR_SLB_LCB_DBG_ERRINJ_MISC_FORCE_LOST_TOS_MASK },
    { "FORCE_LOST_RCLK_REINIT", AR_SLB_LCB_DBG_ERRINJ_MISC_FORCE_LOST_RCLK_REINIT_BP, AR_SLB_LCB_DBG_ERRINJ_MISC_FORCE_LOST_RCLK_REINIT_MASK },
    { "FORCE_BAD_CRC_REINIT", AR_SLB_LCB_DBG_ERRINJ_MISC_FORCE_BAD_CRC_REINIT_BP, AR_SLB_LCB_DBG_ERRINJ_MISC_FORCE_BAD_CRC_REINIT_MASK },
    { "FORCE_REPLAY", AR_SLB_LCB_DBG_ERRINJ_MISC_FORCE_REPLAY_BP, AR_SLB_LCB_DBG_ERRINJ_MISC_FORCE_REPLAY_MASK },
    { "FORCE_REINIT", AR_SLB_LCB_DBG_ERRINJ_MISC_FORCE_REINIT_BP, AR_SLB_LCB_DBG_ERRINJ_MISC_FORCE_REINIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_dbg_init_state_0_detail[] = {
    { "FAILED_FRAMING1_CNT_LN2", AR_SLB_LCB_DBG_INIT_STATE_0_FAILED_FRAMING1_CNT_LN2_BP, AR_SLB_LCB_DBG_INIT_STATE_0_FAILED_FRAMING1_CNT_LN2_MASK },
    { "FAILED_FRAMING1_CNT_LN1", AR_SLB_LCB_DBG_INIT_STATE_0_FAILED_FRAMING1_CNT_LN1_BP, AR_SLB_LCB_DBG_INIT_STATE_0_FAILED_FRAMING1_CNT_LN1_MASK },
    { "FAILED_FRAMING1_CNT_LN0", AR_SLB_LCB_DBG_INIT_STATE_0_FAILED_FRAMING1_CNT_LN0_BP, AR_SLB_LCB_DBG_INIT_STATE_0_FAILED_FRAMING1_CNT_LN0_MASK },
    { "FRAMING1_COMPLETE", AR_SLB_LCB_DBG_INIT_STATE_0_FRAMING1_COMPLETE_BP, AR_SLB_LCB_DBG_INIT_STATE_0_FRAMING1_COMPLETE_MASK },
    { "LOGICAL_ID_COMPLETE", AR_SLB_LCB_DBG_INIT_STATE_0_LOGICAL_ID_COMPLETE_BP, AR_SLB_LCB_DBG_INIT_STATE_0_LOGICAL_ID_COMPLETE_MASK },
    { "POLARITY", AR_SLB_LCB_DBG_INIT_STATE_0_POLARITY_BP, AR_SLB_LCB_DBG_INIT_STATE_0_POLARITY_MASK },
    { "POLARITY_COMPLETE", AR_SLB_LCB_DBG_INIT_STATE_0_POLARITY_COMPLETE_BP, AR_SLB_LCB_DBG_INIT_STATE_0_POLARITY_COMPLETE_MASK },
    { "ROLL_CNT_LN2", AR_SLB_LCB_DBG_INIT_STATE_0_ROLL_CNT_LN2_BP, AR_SLB_LCB_DBG_INIT_STATE_0_ROLL_CNT_LN2_MASK },
    { "ROLL_CNT_LN1", AR_SLB_LCB_DBG_INIT_STATE_0_ROLL_CNT_LN1_BP, AR_SLB_LCB_DBG_INIT_STATE_0_ROLL_CNT_LN1_MASK },
    { "ROLL_CNT_LN0", AR_SLB_LCB_DBG_INIT_STATE_0_ROLL_CNT_LN0_BP, AR_SLB_LCB_DBG_INIT_STATE_0_ROLL_CNT_LN0_MASK },
    { "ALIGN_COMPLETE", AR_SLB_LCB_DBG_INIT_STATE_0_ALIGN_COMPLETE_BP, AR_SLB_LCB_DBG_INIT_STATE_0_ALIGN_COMPLETE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_dbg_init_state_1_detail[] = {
    { "LN_TEST_TIMER_COMPLETE", AR_SLB_LCB_DBG_INIT_STATE_1_LN_TEST_TIMER_COMPLETE_BP, AR_SLB_LCB_DBG_INIT_STATE_1_LN_TEST_TIMER_COMPLETE_MASK },
    { "LN_PASSED_TESTING", AR_SLB_LCB_DBG_INIT_STATE_1_LN_PASSED_TESTING_BP, AR_SLB_LCB_DBG_INIT_STATE_1_LN_PASSED_TESTING_MASK },
    { "PASS_CNT_LN2", AR_SLB_LCB_DBG_INIT_STATE_1_PASS_CNT_LN2_BP, AR_SLB_LCB_DBG_INIT_STATE_1_PASS_CNT_LN2_MASK },
    { "PASS_CNT_LN1", AR_SLB_LCB_DBG_INIT_STATE_1_PASS_CNT_LN1_BP, AR_SLB_LCB_DBG_INIT_STATE_1_PASS_CNT_LN1_MASK },
    { "PASS_CNT_LN0", AR_SLB_LCB_DBG_INIT_STATE_1_PASS_CNT_LN0_BP, AR_SLB_LCB_DBG_INIT_STATE_1_PASS_CNT_LN0_MASK },
    { "LN_TESTING_COMPLETE", AR_SLB_LCB_DBG_INIT_STATE_1_LN_TESTING_COMPLETE_BP, AR_SLB_LCB_DBG_INIT_STATE_1_LN_TESTING_COMPLETE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_dbg_init_state_2_detail[] = {
    { "RX_WAIT4TOS_FAIL_CNT", AR_SLB_LCB_DBG_INIT_STATE_2_RX_WAIT4TOS_FAIL_CNT_BP, AR_SLB_LCB_DBG_INIT_STATE_2_RX_WAIT4TOS_FAIL_CNT_MASK },
    { "RX_TURN_ON_SIG_CNT", AR_SLB_LCB_DBG_INIT_STATE_2_RX_TURN_ON_SIG_CNT_BP, AR_SLB_LCB_DBG_INIT_STATE_2_RX_TURN_ON_SIG_CNT_MASK },
    { "TX_TOS_3OR", AR_SLB_LCB_DBG_INIT_STATE_2_TX_TOS_3OR_BP, AR_SLB_LCB_DBG_INIT_STATE_2_TX_TOS_3OR_MASK },
    { "PEER_LANE_ENA_DETECTED", AR_SLB_LCB_DBG_INIT_STATE_2_PEER_LANE_ENA_DETECTED_BP, AR_SLB_LCB_DBG_INIT_STATE_2_PEER_LANE_ENA_DETECTED_MASK },
    { "PEER_FRAMED", AR_SLB_LCB_DBG_INIT_STATE_2_PEER_FRAMED_BP, AR_SLB_LCB_DBG_INIT_STATE_2_PEER_FRAMED_MASK },
    { "RCLK_SAMPLING_LN", AR_SLB_LCB_DBG_INIT_STATE_2_RCLK_SAMPLING_LN_BP, AR_SLB_LCB_DBG_INIT_STATE_2_RCLK_SAMPLING_LN_MASK },
    { "BACK_CHAN_REPORTING_LN", AR_SLB_LCB_DBG_INIT_STATE_2_BACK_CHAN_REPORTING_LN_BP, AR_SLB_LCB_DBG_INIT_STATE_2_BACK_CHAN_REPORTING_LN_MASK },
    { "RX_SKEW_LN_EN", AR_SLB_LCB_DBG_INIT_STATE_2_RX_SKEW_LN_EN_BP, AR_SLB_LCB_DBG_INIT_STATE_2_RX_SKEW_LN_EN_MASK },
    { "RADR_SKIP4DESKEW_CNT_LN2", AR_SLB_LCB_DBG_INIT_STATE_2_RADR_SKIP4DESKEW_CNT_LN2_BP, AR_SLB_LCB_DBG_INIT_STATE_2_RADR_SKIP4DESKEW_CNT_LN2_MASK },
    { "RADR_SKIP4DESKEW_CNT_LN1", AR_SLB_LCB_DBG_INIT_STATE_2_RADR_SKIP4DESKEW_CNT_LN1_BP, AR_SLB_LCB_DBG_INIT_STATE_2_RADR_SKIP4DESKEW_CNT_LN1_MASK },
    { "RADR_SKIP4DESKEW_CNT_LN0", AR_SLB_LCB_DBG_INIT_STATE_2_RADR_SKIP4DESKEW_CNT_LN0_BP, AR_SLB_LCB_DBG_INIT_STATE_2_RADR_SKIP4DESKEW_CNT_LN0_MASK },
    { "FAILED_TEST_CNT_LN2", AR_SLB_LCB_DBG_INIT_STATE_2_FAILED_TEST_CNT_LN2_BP, AR_SLB_LCB_DBG_INIT_STATE_2_FAILED_TEST_CNT_LN2_MASK },
    { "FAILED_TEST_CNT_LN1", AR_SLB_LCB_DBG_INIT_STATE_2_FAILED_TEST_CNT_LN1_BP, AR_SLB_LCB_DBG_INIT_STATE_2_FAILED_TEST_CNT_LN1_MASK },
    { "FAILED_TEST_CNT_LN0", AR_SLB_LCB_DBG_INIT_STATE_2_FAILED_TEST_CNT_LN0_BP, AR_SLB_LCB_DBG_INIT_STATE_2_FAILED_TEST_CNT_LN0_MASK },
    { "RX_FRAMED", AR_SLB_LCB_DBG_INIT_STATE_2_RX_FRAMED_BP, AR_SLB_LCB_DBG_INIT_STATE_2_RX_FRAMED_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_cfg_init_pause_0_detail[] = {
    { "RX_FIFO_RADR", AR_SLB_LCB_CFG_INIT_PAUSE_0_RX_FIFO_RADR_BP, AR_SLB_LCB_CFG_INIT_PAUSE_0_RX_FIFO_RADR_MASK },
    { "RX_FIFO_RD_STROBE_SELECT", AR_SLB_LCB_CFG_INIT_PAUSE_0_RX_FIFO_RD_STROBE_SELECT_BP, AR_SLB_LCB_CFG_INIT_PAUSE_0_RX_FIFO_RD_STROBE_SELECT_MASK },
    { "RX_FIFO_WR_STROBE_SELECT", AR_SLB_LCB_CFG_INIT_PAUSE_0_RX_FIFO_WR_STROBE_SELECT_BP, AR_SLB_LCB_CFG_INIT_PAUSE_0_RX_FIFO_WR_STROBE_SELECT_MASK },
    { "RX_FIFO_WADR", AR_SLB_LCB_CFG_INIT_PAUSE_0_RX_FIFO_WADR_BP, AR_SLB_LCB_CFG_INIT_PAUSE_0_RX_FIFO_WADR_MASK },
    { "TX_FIFO_RADR_TRIP", AR_SLB_LCB_CFG_INIT_PAUSE_0_TX_FIFO_RADR_TRIP_BP, AR_SLB_LCB_CFG_INIT_PAUSE_0_TX_FIFO_RADR_TRIP_MASK },
    { "TX_FIFO_RADR", AR_SLB_LCB_CFG_INIT_PAUSE_0_TX_FIFO_RADR_BP, AR_SLB_LCB_CFG_INIT_PAUSE_0_TX_FIFO_RADR_MASK },
    { "TX_FIFO_RD_STROBE_SELECT", AR_SLB_LCB_CFG_INIT_PAUSE_0_TX_FIFO_RD_STROBE_SELECT_BP, AR_SLB_LCB_CFG_INIT_PAUSE_0_TX_FIFO_RD_STROBE_SELECT_MASK },
    { "TX_FIFO_WR_STROBE_SELECT", AR_SLB_LCB_CFG_INIT_PAUSE_0_TX_FIFO_WR_STROBE_SELECT_BP, AR_SLB_LCB_CFG_INIT_PAUSE_0_TX_FIFO_WR_STROBE_SELECT_MASK },
    { "TX_FIFO_WADR_TRIP", AR_SLB_LCB_CFG_INIT_PAUSE_0_TX_FIFO_WADR_TRIP_BP, AR_SLB_LCB_CFG_INIT_PAUSE_0_TX_FIFO_WADR_TRIP_MASK },
    { "TX_FIFO_WADR", AR_SLB_LCB_CFG_INIT_PAUSE_0_TX_FIFO_WADR_BP, AR_SLB_LCB_CFG_INIT_PAUSE_0_TX_FIFO_WADR_MASK },
    { "ALT_LINK3OR_FRAME", AR_SLB_LCB_CFG_INIT_PAUSE_0_ALT_LINK3OR_FRAME_BP, AR_SLB_LCB_CFG_INIT_PAUSE_0_ALT_LINK3OR_FRAME_MASK },
    { "USE_ALT_LINK3OR_FRAME", AR_SLB_LCB_CFG_INIT_PAUSE_0_USE_ALT_LINK3OR_FRAME_BP, AR_SLB_LCB_CFG_INIT_PAUSE_0_USE_ALT_LINK3OR_FRAME_MASK },
    { "INIT_PAUSE_MODE", AR_SLB_LCB_CFG_INIT_PAUSE_0_INIT_PAUSE_MODE_BP, AR_SLB_LCB_CFG_INIT_PAUSE_0_INIT_PAUSE_MODE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_cfg_init_pause_1_detail[] = {
    { "RX_FIFOS_SKIP_RADR_INCR", AR_SLB_LCB_CFG_INIT_PAUSE_1_RX_FIFOS_SKIP_RADR_INCR_BP, AR_SLB_LCB_CFG_INIT_PAUSE_1_RX_FIFOS_SKIP_RADR_INCR_MASK },
    { "RX_FIFOS_RESET", AR_SLB_LCB_CFG_INIT_PAUSE_1_RX_FIFOS_RESET_BP, AR_SLB_LCB_CFG_INIT_PAUSE_1_RX_FIFOS_RESET_MASK },
    { "FORCE_ROLL", AR_SLB_LCB_CFG_INIT_PAUSE_1_FORCE_ROLL_BP, AR_SLB_LCB_CFG_INIT_PAUSE_1_FORCE_ROLL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_dbg_tx_fifo_wr_data_detail[] = {
    { "LN2", AR_SLB_LCB_DBG_TX_FIFO_WR_DATA_LN2_BP, AR_SLB_LCB_DBG_TX_FIFO_WR_DATA_LN2_MASK },
    { "LN1", AR_SLB_LCB_DBG_TX_FIFO_WR_DATA_LN1_BP, AR_SLB_LCB_DBG_TX_FIFO_WR_DATA_LN1_MASK },
    { "LN0", AR_SLB_LCB_DBG_TX_FIFO_WR_DATA_LN0_BP, AR_SLB_LCB_DBG_TX_FIFO_WR_DATA_LN0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_dbg_tx_fifo_rd_data_detail[] = {
    { "LN2", AR_SLB_LCB_DBG_TX_FIFO_RD_DATA_LN2_BP, AR_SLB_LCB_DBG_TX_FIFO_RD_DATA_LN2_MASK },
    { "LN1", AR_SLB_LCB_DBG_TX_FIFO_RD_DATA_LN1_BP, AR_SLB_LCB_DBG_TX_FIFO_RD_DATA_LN1_MASK },
    { "LN0", AR_SLB_LCB_DBG_TX_FIFO_RD_DATA_LN0_BP, AR_SLB_LCB_DBG_TX_FIFO_RD_DATA_LN0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_dbg_rx_fifo_wr_data_detail[] = {
    { "LN2", AR_SLB_LCB_DBG_RX_FIFO_WR_DATA_LN2_BP, AR_SLB_LCB_DBG_RX_FIFO_WR_DATA_LN2_MASK },
    { "LN1", AR_SLB_LCB_DBG_RX_FIFO_WR_DATA_LN1_BP, AR_SLB_LCB_DBG_RX_FIFO_WR_DATA_LN1_MASK },
    { "LN0", AR_SLB_LCB_DBG_RX_FIFO_WR_DATA_LN0_BP, AR_SLB_LCB_DBG_RX_FIFO_WR_DATA_LN0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_dbg_rx_fifo_rd_data_detail[] = {
    { "LN2", AR_SLB_LCB_DBG_RX_FIFO_RD_DATA_LN2_BP, AR_SLB_LCB_DBG_RX_FIFO_RD_DATA_LN2_MASK },
    { "LN1", AR_SLB_LCB_DBG_RX_FIFO_RD_DATA_LN1_BP, AR_SLB_LCB_DBG_RX_FIFO_RD_DATA_LN1_MASK },
    { "LN0", AR_SLB_LCB_DBG_RX_FIFO_RD_DATA_LN0_BP, AR_SLB_LCB_DBG_RX_FIFO_RD_DATA_LN0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_dbg_reinit_cause_detail[] = {
    { "WAS_RST_4_FAILED_DESKEW", AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_RST_4_FAILED_DESKEW_BP, AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_RST_4_FAILED_DESKEW_MASK },
    { "WAS_REINIT_FROM_PEER", AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_REINIT_FROM_PEER_BP, AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_REINIT_FROM_PEER_MASK },
    { "WAS_NULLS_NOT_REQUIRED", AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_NULLS_NOT_REQUIRED_BP, AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_NULLS_NOT_REQUIRED_MASK },
    { "WAS_REINIT_NULLS_DONE", AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_REINIT_NULLS_DONE_BP, AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_REINIT_NULLS_DONE_MASK },
    { "WAS_MMR_FORCED_REINIT", AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_MMR_FORCED_REINIT_BP, AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_MMR_FORCED_REINIT_MASK },
    { "WAS_PAUSE_MODE6", AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_PAUSE_MODE6_BP, AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_PAUSE_MODE6_MASK },
    { "WAS_RST_4_LINK_TIMEOUT", AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_RST_4_LINK_TIMEOUT_BP, AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_RST_4_LINK_TIMEOUT_MASK },
    { "WAS_RST_4_LOST_TON_SIG", AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_RST_4_LOST_TON_SIG_BP, AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_RST_4_LOST_TON_SIG_MASK },
    { "WAS_UNEXPECTED_REPLAY", AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_UNEXPECTED_REPLAY_BP, AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_UNEXPECTED_REPLAY_MASK },
    { "WAS_RCLK_STOPPED", AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_RCLK_STOPPED_BP, AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_RCLK_STOPPED_MASK },
    { "WAS_REINIT_4_LN_DEGRADE", AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_REINIT_4_LN_DEGRADE_BP, AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_REINIT_4_LN_DEGRADE_MASK },
    { "WAS_SEQ_CRC_ERR", AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_SEQ_CRC_ERR_BP, AR_SLB_LCB_DBG_REINIT_CAUSE_WAS_SEQ_CRC_ERR_MASK },
    { "CLR_LAST_REINIT_INFO", AR_SLB_LCB_DBG_REINIT_CAUSE_CLR_LAST_REINIT_INFO_BP, AR_SLB_LCB_DBG_REINIT_CAUSE_CLR_LAST_REINIT_INFO_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_dbg_replay_0_detail[] = {
    { "REPLAY_EMPTY", AR_SLB_LCB_DBG_REPLAY_0_REPLAY_EMPTY_BP, AR_SLB_LCB_DBG_REPLAY_0_REPLAY_EMPTY_MASK },
    { "POST_INIT_REPLAY_EMPTY", AR_SLB_LCB_DBG_REPLAY_0_POST_INIT_REPLAY_EMPTY_BP, AR_SLB_LCB_DBG_REPLAY_0_POST_INIT_REPLAY_EMPTY_MASK },
    { "Q_REPLAYING", AR_SLB_LCB_DBG_REPLAY_0_Q_REPLAYING_BP, AR_SLB_LCB_DBG_REPLAY_0_Q_REPLAYING_MASK },
    { "Q_FULL", AR_SLB_LCB_DBG_REPLAY_0_Q_FULL_BP, AR_SLB_LCB_DBG_REPLAY_0_Q_FULL_MASK },
    { "Q_READ_UP", AR_SLB_LCB_DBG_REPLAY_0_Q_READ_UP_BP, AR_SLB_LCB_DBG_REPLAY_0_Q_READ_UP_MASK },
    { "Q_WRITE_UP_ODD", AR_SLB_LCB_DBG_REPLAY_0_Q_WRITE_UP_ODD_BP, AR_SLB_LCB_DBG_REPLAY_0_Q_WRITE_UP_ODD_MASK },
    { "Q_WRITE_UP", AR_SLB_LCB_DBG_REPLAY_0_Q_WRITE_UP_BP, AR_SLB_LCB_DBG_REPLAY_0_Q_WRITE_UP_MASK },
    { "Q_VERIFIED_ODD_PLUS1", AR_SLB_LCB_DBG_REPLAY_0_Q_VERIFIED_ODD_PLUS1_BP, AR_SLB_LCB_DBG_REPLAY_0_Q_VERIFIED_ODD_PLUS1_MASK },
    { "Q_VERIFIED_UP_PLUS1", AR_SLB_LCB_DBG_REPLAY_0_Q_VERIFIED_UP_PLUS1_BP, AR_SLB_LCB_DBG_REPLAY_0_Q_VERIFIED_UP_PLUS1_MASK },
    { "Q_VERIFIED_UP_PREVIOUS", AR_SLB_LCB_DBG_REPLAY_0_Q_VERIFIED_UP_PREVIOUS_BP, AR_SLB_LCB_DBG_REPLAY_0_Q_VERIFIED_UP_PREVIOUS_MASK },
    { "Q_VERIFIED_UP", AR_SLB_LCB_DBG_REPLAY_0_Q_VERIFIED_UP_BP, AR_SLB_LCB_DBG_REPLAY_0_Q_VERIFIED_UP_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_dbg_replay_1_detail[] = {
    { "Q_TOSSING", AR_SLB_LCB_DBG_REPLAY_1_Q_TOSSING_BP, AR_SLB_LCB_DBG_REPLAY_1_Q_TOSSING_MASK },
    { "Q_LCL_RCV_UP_ODD", AR_SLB_LCB_DBG_REPLAY_1_Q_LCL_RCV_UP_ODD_BP, AR_SLB_LCB_DBG_REPLAY_1_Q_LCL_RCV_UP_ODD_MASK },
    { "Q_LCL_RCV_UP_NUM", AR_SLB_LCB_DBG_REPLAY_1_Q_LCL_RCV_UP_NUM_BP, AR_SLB_LCB_DBG_REPLAY_1_Q_LCL_RCV_UP_NUM_MASK },
    { "Q_MIN_TIMEOUT_PLUS_NULL_CNT", AR_SLB_LCB_DBG_REPLAY_1_Q_MIN_TIMEOUT_PLUS_NULL_CNT_BP, AR_SLB_LCB_DBG_REPLAY_1_Q_MIN_TIMEOUT_PLUS_NULL_CNT_MASK },
    { "Q_STATIC_RCV_UP_CNT", AR_SLB_LCB_DBG_REPLAY_1_Q_STATIC_RCV_UP_CNT_BP, AR_SLB_LCB_DBG_REPLAY_1_Q_STATIC_RCV_UP_CNT_MASK },
    { "Q_FIRST_ROUND_TRIP", AR_SLB_LCB_DBG_REPLAY_1_Q_FIRST_ROUND_TRIP_BP, AR_SLB_LCB_DBG_REPLAY_1_Q_FIRST_ROUND_TRIP_MASK },
    { "Q_USE_INIT_TIMEOUT", AR_SLB_LCB_DBG_REPLAY_1_Q_USE_INIT_TIMEOUT_BP, AR_SLB_LCB_DBG_REPLAY_1_Q_USE_INIT_TIMEOUT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_dbg_oflw_detail[] = {
    { "RCV_BUF_PADR_PRIOR", AR_SLB_LCB_DBG_OFLW_RCV_BUF_PADR_PRIOR_BP, AR_SLB_LCB_DBG_OFLW_RCV_BUF_PADR_PRIOR_MASK },
    { "RCV_BUF_PADR_HOLD", AR_SLB_LCB_DBG_OFLW_RCV_BUF_PADR_HOLD_BP, AR_SLB_LCB_DBG_OFLW_RCV_BUF_PADR_HOLD_MASK },
    { "RCV_BUF_RADR", AR_SLB_LCB_DBG_OFLW_RCV_BUF_RADR_BP, AR_SLB_LCB_DBG_OFLW_RCV_BUF_RADR_MASK },
    { "RCV_BUF_WADR", AR_SLB_LCB_DBG_OFLW_RCV_BUF_WADR_BP, AR_SLB_LCB_DBG_OFLW_RCV_BUF_WADR_MASK },
    { "FLOW_CTL_BUF_RADR", AR_SLB_LCB_DBG_OFLW_FLOW_CTL_BUF_RADR_BP, AR_SLB_LCB_DBG_OFLW_FLOW_CTL_BUF_RADR_MASK },
    { "FLOW_CTL_BUF_WADR_STALL", AR_SLB_LCB_DBG_OFLW_FLOW_CTL_BUF_WADR_STALL_BP, AR_SLB_LCB_DBG_OFLW_FLOW_CTL_BUF_WADR_STALL_MASK },
    { "FLOW_CTL_BUF_WADR", AR_SLB_LCB_DBG_OFLW_FLOW_CTL_BUF_WADR_BP, AR_SLB_LCB_DBG_OFLW_FLOW_CTL_BUF_WADR_MASK },
    { "FLOW_CTL_BUF_FULL", AR_SLB_LCB_DBG_OFLW_FLOW_CTL_BUF_FULL_BP, AR_SLB_LCB_DBG_OFLW_FLOW_CTL_BUF_FULL_MASK },
    { "FLOW_CTL_BUF_EMPTY", AR_SLB_LCB_DBG_OFLW_FLOW_CTL_BUF_EMPTY_BP, AR_SLB_LCB_DBG_OFLW_FLOW_CTL_BUF_EMPTY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_dbg_vc_ack_detail[] = {
    { "CNT_7", AR_SLB_LCB_DBG_VC_ACK_CNT_7_BP, AR_SLB_LCB_DBG_VC_ACK_CNT_7_MASK },
    { "CNT_6", AR_SLB_LCB_DBG_VC_ACK_CNT_6_BP, AR_SLB_LCB_DBG_VC_ACK_CNT_6_MASK },
    { "CNT_5", AR_SLB_LCB_DBG_VC_ACK_CNT_5_BP, AR_SLB_LCB_DBG_VC_ACK_CNT_5_MASK },
    { "CNT_4", AR_SLB_LCB_DBG_VC_ACK_CNT_4_BP, AR_SLB_LCB_DBG_VC_ACK_CNT_4_MASK },
    { "CNT_3", AR_SLB_LCB_DBG_VC_ACK_CNT_3_BP, AR_SLB_LCB_DBG_VC_ACK_CNT_3_MASK },
    { "CNT_2", AR_SLB_LCB_DBG_VC_ACK_CNT_2_BP, AR_SLB_LCB_DBG_VC_ACK_CNT_2_MASK },
    { "CNT_1", AR_SLB_LCB_DBG_VC_ACK_CNT_1_BP, AR_SLB_LCB_DBG_VC_ACK_CNT_1_MASK },
    { "CNT_0", AR_SLB_LCB_DBG_VC_ACK_CNT_0_BP, AR_SLB_LCB_DBG_VC_ACK_CNT_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_cfg_pause_detail[] = {
    { "DELAY_CNT", AR_SLB_LCB_CFG_PAUSE_DELAY_CNT_BP, AR_SLB_LCB_CFG_PAUSE_DELAY_CNT_MASK },
    { "CNT_CLKS", AR_SLB_LCB_CFG_PAUSE_CNT_CLKS_BP, AR_SLB_LCB_CFG_PAUSE_CNT_CLKS_MASK },
    { "UNIT48_SELECTS", AR_SLB_LCB_CFG_PAUSE_UNIT48_SELECTS_BP, AR_SLB_LCB_CFG_PAUSE_UNIT48_SELECTS_MASK },
    { "COMPARE_CNT", AR_SLB_LCB_CFG_PAUSE_COMPARE_CNT_BP, AR_SLB_LCB_CFG_PAUSE_COMPARE_CNT_MASK },
    { "COMPARE_TYPE_SELECT", AR_SLB_LCB_CFG_PAUSE_COMPARE_TYPE_SELECT_BP, AR_SLB_LCB_CFG_PAUSE_COMPARE_TYPE_SELECT_MASK },
    { "TX_TRIGGER_ENABLES", AR_SLB_LCB_CFG_PAUSE_TX_TRIGGER_ENABLES_BP, AR_SLB_LCB_CFG_PAUSE_TX_TRIGGER_ENABLES_MASK },
    { "TRIGGER_SELECTS", AR_SLB_LCB_CFG_PAUSE_TRIGGER_SELECTS_BP, AR_SLB_LCB_CFG_PAUSE_TRIGGER_SELECTS_MASK },
    { "CLR_PAUSE_MODE5", AR_SLB_LCB_CFG_PAUSE_CLR_PAUSE_MODE5_BP, AR_SLB_LCB_CFG_PAUSE_CLR_PAUSE_MODE5_MASK },
    { "CLR_PAUSE_MODE2", AR_SLB_LCB_CFG_PAUSE_CLR_PAUSE_MODE2_BP, AR_SLB_LCB_CFG_PAUSE_CLR_PAUSE_MODE2_MASK },
    { "REARM_ALL", AR_SLB_LCB_CFG_PAUSE_REARM_ALL_BP, AR_SLB_LCB_CFG_PAUSE_REARM_ALL_MASK },
    { "MODE_ENABLE", AR_SLB_LCB_CFG_PAUSE_MODE_ENABLE_BP, AR_SLB_LCB_CFG_PAUSE_MODE_ENABLE_MASK },
    { "MODE_STS", AR_SLB_LCB_CFG_PAUSE_MODE_STS_BP, AR_SLB_LCB_CFG_PAUSE_MODE_STS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_cfg_compare_value_detail[] = {
    { "FIELD", AR_SLB_LCB_CFG_COMPARE_VALUE_FIELD_BP, AR_SLB_LCB_CFG_COMPARE_VALUE_FIELD_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_cfg_compare_mask_detail[] = {
    { "FIELD", AR_SLB_LCB_CFG_COMPARE_MASK_FIELD_BP, AR_SLB_LCB_CFG_COMPARE_MASK_FIELD_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_dbg_pause_trigger_flit_detail[] = {
    { "WAS_REPLAY", AR_SLB_LCB_DBG_PAUSE_TRIGGER_FLIT_WAS_REPLAY_BP, AR_SLB_LCB_DBG_PAUSE_TRIGGER_FLIT_WAS_REPLAY_MASK },
    { "VALID", AR_SLB_LCB_DBG_PAUSE_TRIGGER_FLIT_VALID_BP, AR_SLB_LCB_DBG_PAUSE_TRIGGER_FLIT_VALID_MASK },
    { "UNIT48_CNT", AR_SLB_LCB_DBG_PAUSE_TRIGGER_FLIT_UNIT48_CNT_BP, AR_SLB_LCB_DBG_PAUSE_TRIGGER_FLIT_UNIT48_CNT_MASK },
    { "WAS_PIPE1", AR_SLB_LCB_DBG_PAUSE_TRIGGER_FLIT_WAS_PIPE1_BP, AR_SLB_LCB_DBG_PAUSE_TRIGGER_FLIT_WAS_PIPE1_MASK },
    { "VALUE", AR_SLB_LCB_DBG_PAUSE_TRIGGER_FLIT_VALUE_BP, AR_SLB_LCB_DBG_PAUSE_TRIGGER_FLIT_VALUE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_cfg_ram_read_write_detail[] = {
    { "UP_DATA_WAS_GOOD", AR_SLB_LCB_CFG_RAM_READ_WRITE_UP_DATA_WAS_GOOD_BP, AR_SLB_LCB_CFG_RAM_READ_WRITE_UP_DATA_WAS_GOOD_MASK },
    { "UP_DATA_WAS_TOSSING", AR_SLB_LCB_CFG_RAM_READ_WRITE_UP_DATA_WAS_TOSSING_BP, AR_SLB_LCB_CFG_RAM_READ_WRITE_UP_DATA_WAS_TOSSING_MASK },
    { "UP_DATA_COMPARE_RDY", AR_SLB_LCB_CFG_RAM_READ_WRITE_UP_DATA_COMPARE_RDY_BP, AR_SLB_LCB_CFG_RAM_READ_WRITE_UP_DATA_COMPARE_RDY_MASK },
    { "ARM_RAW_UP_DATA_HOLD", AR_SLB_LCB_CFG_RAM_READ_WRITE_ARM_RAW_UP_DATA_HOLD_BP, AR_SLB_LCB_CFG_RAM_READ_WRITE_ARM_RAW_UP_DATA_HOLD_MASK },
    { "REPLAY_BUF_WRITE", AR_SLB_LCB_CFG_RAM_READ_WRITE_REPLAY_BUF_WRITE_BP, AR_SLB_LCB_CFG_RAM_READ_WRITE_REPLAY_BUF_WRITE_MASK },
    { "BUFFER", AR_SLB_LCB_CFG_RAM_READ_WRITE_BUFFER_BP, AR_SLB_LCB_CFG_RAM_READ_WRITE_BUFFER_MASK },
    { "REPLAY_BUF_UP", AR_SLB_LCB_CFG_RAM_READ_WRITE_REPLAY_BUF_UP_BP, AR_SLB_LCB_CFG_RAM_READ_WRITE_REPLAY_BUF_UP_MASK },
    { "ADDRESS", AR_SLB_LCB_CFG_RAM_READ_WRITE_ADDRESS_BP, AR_SLB_LCB_CFG_RAM_READ_WRITE_ADDRESS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_cfg_ram_data_detail[] = {
    { "DATA", AR_SLB_LCB_CFG_RAM_DATA_DATA_BP, AR_SLB_LCB_CFG_RAM_DATA_DATA_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_cfg_serdes_cx_detail[] = {
    { "TX_RATE_SEL", AR_SLB_LCB_CFG_SERDES_CX_TX_RATE_SEL_BP, AR_SLB_LCB_CFG_SERDES_CX_TX_RATE_SEL_MASK },
    { "REF_SEL", AR_SLB_LCB_CFG_SERDES_CX_REF_SEL_BP, AR_SLB_LCB_CFG_SERDES_CX_REF_SEL_MASK },
    { "PLL_RECAL_EN", AR_SLB_LCB_CFG_SERDES_CX_PLL_RECAL_EN_BP, AR_SLB_LCB_CFG_SERDES_CX_PLL_RECAL_EN_MASK },
    { "NEAR_LOOPBACK_EN", AR_SLB_LCB_CFG_SERDES_CX_NEAR_LOOPBACK_EN_BP, AR_SLB_LCB_CFG_SERDES_CX_NEAR_LOOPBACK_EN_MASK },
    { "KR_TRAINING_EN", AR_SLB_LCB_CFG_SERDES_CX_KR_TRAINING_EN_BP, AR_SLB_LCB_CFG_SERDES_CX_KR_TRAINING_EN_MASK },
    { "KR_RESTART_TRAINING", AR_SLB_LCB_CFG_SERDES_CX_KR_RESTART_TRAINING_BP, AR_SLB_LCB_CFG_SERDES_CX_KR_RESTART_TRAINING_MASK },
    { "K30_7_ERR_EN", AR_SLB_LCB_CFG_SERDES_CX_K30_7_ERR_EN_BP, AR_SLB_LCB_CFG_SERDES_CX_K30_7_ERR_EN_MASK },
    { "FAR_LOOPBACK_EN", AR_SLB_LCB_CFG_SERDES_CX_FAR_LOOPBACK_EN_BP, AR_SLB_LCB_CFG_SERDES_CX_FAR_LOOPBACK_EN_MASK },
    { "CORE_TO_CNTL", AR_SLB_LCB_CFG_SERDES_CX_CORE_TO_CNTL_BP, AR_SLB_LCB_CFG_SERDES_CX_CORE_TO_CNTL_MASK },
    { "LN_RESET", AR_SLB_LCB_CFG_SERDES_CX_LN_RESET_BP, AR_SLB_LCB_CFG_SERDES_CX_LN_RESET_MASK },
    { "LSB_CONTROL", AR_SLB_LCB_CFG_SERDES_CX_LSB_CONTROL_BP, AR_SLB_LCB_CFG_SERDES_CX_LSB_CONTROL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_cfg_serdes_tx_detail[] = {
    { "EN", AR_SLB_LCB_CFG_SERDES_TX_EN_BP, AR_SLB_LCB_CFG_SERDES_TX_EN_MASK },
    { "OUTPUT_ATTENUATION", AR_SLB_LCB_CFG_SERDES_TX_OUTPUT_ATTENUATION_BP, AR_SLB_LCB_CFG_SERDES_TX_OUTPUT_ATTENUATION_MASK },
    { "OUTPUT_EN", AR_SLB_LCB_CFG_SERDES_TX_OUTPUT_EN_BP, AR_SLB_LCB_CFG_SERDES_TX_OUTPUT_EN_MASK },
    { "OUTPUT_EQ_POST", AR_SLB_LCB_CFG_SERDES_TX_OUTPUT_EQ_POST_BP, AR_SLB_LCB_CFG_SERDES_TX_OUTPUT_EQ_POST_MASK },
    { "OUTPUT_EQ_PRE", AR_SLB_LCB_CFG_SERDES_TX_OUTPUT_EQ_PRE_BP, AR_SLB_LCB_CFG_SERDES_TX_OUTPUT_EQ_PRE_MASK },
    { "OUTPUT_SLEW", AR_SLB_LCB_CFG_SERDES_TX_OUTPUT_SLEW_BP, AR_SLB_LCB_CFG_SERDES_TX_OUTPUT_SLEW_MASK },
    { "PHASE_CAL_EN", AR_SLB_LCB_CFG_SERDES_TX_PHASE_CAL_EN_BP, AR_SLB_LCB_CFG_SERDES_TX_PHASE_CAL_EN_MASK },
    { "PHASE_MASTER", AR_SLB_LCB_CFG_SERDES_TX_PHASE_MASTER_BP, AR_SLB_LCB_CFG_SERDES_TX_PHASE_MASTER_MASK },
    { "REFCLK_SYNC_MASTER", AR_SLB_LCB_CFG_SERDES_TX_REFCLK_SYNC_MASTER_BP, AR_SLB_LCB_CFG_SERDES_TX_REFCLK_SYNC_MASTER_MASK },
    { "PHASE_SLIP", AR_SLB_LCB_CFG_SERDES_TX_PHASE_SLIP_BP, AR_SLB_LCB_CFG_SERDES_TX_PHASE_SLIP_MASK },
    { "WIDTH_MODE", AR_SLB_LCB_CFG_SERDES_TX_WIDTH_MODE_BP, AR_SLB_LCB_CFG_SERDES_TX_WIDTH_MODE_MASK },
    { "OVERRIDE_EN", AR_SLB_LCB_CFG_SERDES_TX_OVERRIDE_EN_BP, AR_SLB_LCB_CFG_SERDES_TX_OVERRIDE_EN_MASK },
    { "OVERRIDE_IN", AR_SLB_LCB_CFG_SERDES_TX_OVERRIDE_IN_BP, AR_SLB_LCB_CFG_SERDES_TX_OVERRIDE_IN_MASK },
    { "ELEC_IDLE", AR_SLB_LCB_CFG_SERDES_TX_ELEC_IDLE_BP, AR_SLB_LCB_CFG_SERDES_TX_ELEC_IDLE_MASK },
    { "PATTERN_GEN_EN", AR_SLB_LCB_CFG_SERDES_TX_PATTERN_GEN_EN_BP, AR_SLB_LCB_CFG_SERDES_TX_PATTERN_GEN_EN_MASK },
    { "PATTERN_GEN_SEL_LN2", AR_SLB_LCB_CFG_SERDES_TX_PATTERN_GEN_SEL_LN2_BP, AR_SLB_LCB_CFG_SERDES_TX_PATTERN_GEN_SEL_LN2_MASK },
    { "PATTERN_GEN_SEL_LN1", AR_SLB_LCB_CFG_SERDES_TX_PATTERN_GEN_SEL_LN1_BP, AR_SLB_LCB_CFG_SERDES_TX_PATTERN_GEN_SEL_LN1_MASK },
    { "PATTERN_GEN_SEL_LN0", AR_SLB_LCB_CFG_SERDES_TX_PATTERN_GEN_SEL_LN0_BP, AR_SLB_LCB_CFG_SERDES_TX_PATTERN_GEN_SEL_LN0_MASK },
    { "POLARITY_INV_EN", AR_SLB_LCB_CFG_SERDES_TX_POLARITY_INV_EN_BP, AR_SLB_LCB_CFG_SERDES_TX_POLARITY_INV_EN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_cfg_serdes_rx_detail[] = {
    { "SIG_OK_USE_SIGNAL_STRENGTH", AR_SLB_LCB_CFG_SERDES_RX_SIG_OK_USE_SIGNAL_STRENGTH_BP, AR_SLB_LCB_CFG_SERDES_RX_SIG_OK_USE_SIGNAL_STRENGTH_MASK },
    { "SIG_OK_USE_FINE_FLOCK_COUNTER", AR_SLB_LCB_CFG_SERDES_RX_SIG_OK_USE_FINE_FLOCK_COUNTER_BP, AR_SLB_LCB_CFG_SERDES_RX_SIG_OK_USE_FINE_FLOCK_COUNTER_MASK },
    { "ACTIVE_SIG_MIN", AR_SLB_LCB_CFG_SERDES_RX_ACTIVE_SIG_MIN_BP, AR_SLB_LCB_CFG_SERDES_RX_ACTIVE_SIG_MIN_MASK },
    { "DROPOUT_CHAR_EN", AR_SLB_LCB_CFG_SERDES_RX_DROPOUT_CHAR_EN_BP, AR_SLB_LCB_CFG_SERDES_RX_DROPOUT_CHAR_EN_MASK },
    { "EN", AR_SLB_LCB_CFG_SERDES_RX_EN_BP, AR_SLB_LCB_CFG_SERDES_RX_EN_MASK },
    { "PATTERN_CMP_EN", AR_SLB_LCB_CFG_SERDES_RX_PATTERN_CMP_EN_BP, AR_SLB_LCB_CFG_SERDES_RX_PATTERN_CMP_EN_MASK },
    { "PATTERN_CMP_SEL", AR_SLB_LCB_CFG_SERDES_RX_PATTERN_CMP_SEL_BP, AR_SLB_LCB_CFG_SERDES_RX_PATTERN_CMP_SEL_MASK },
    { "POLARITY_INV_EN", AR_SLB_LCB_CFG_SERDES_RX_POLARITY_INV_EN_BP, AR_SLB_LCB_CFG_SERDES_RX_POLARITY_INV_EN_MASK },
    { "RATE_SEL", AR_SLB_LCB_CFG_SERDES_RX_RATE_SEL_BP, AR_SLB_LCB_CFG_SERDES_RX_RATE_SEL_MASK },
    { "SIG_STRENGTH_EN", AR_SLB_LCB_CFG_SERDES_RX_SIG_STRENGTH_EN_BP, AR_SLB_LCB_CFG_SERDES_RX_SIG_STRENGTH_EN_MASK },
    { "SIG_STRENGTH_STRONG_EN", AR_SLB_LCB_CFG_SERDES_RX_SIG_STRENGTH_STRONG_EN_BP, AR_SLB_LCB_CFG_SERDES_RX_SIG_STRENGTH_STRONG_EN_MASK },
    { "WIDTH_MODE", AR_SLB_LCB_CFG_SERDES_RX_WIDTH_MODE_BP, AR_SLB_LCB_CFG_SERDES_RX_WIDTH_MODE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_slb_lcb_dbg_serdes_outputs_detail[] = {
    { "TX_RDY", AR_SLB_LCB_DBG_SERDES_OUTPUTS_TX_RDY_BP, AR_SLB_LCB_DBG_SERDES_OUTPUTS_TX_RDY_MASK },
    { "TX_PHASE_OUT_LN2", AR_SLB_LCB_DBG_SERDES_OUTPUTS_TX_PHASE_OUT_LN2_BP, AR_SLB_LCB_DBG_SERDES_OUTPUTS_TX_PHASE_OUT_LN2_MASK },
    { "TX_PHASE_OUT_LN1", AR_SLB_LCB_DBG_SERDES_OUTPUTS_TX_PHASE_OUT_LN1_BP, AR_SLB_LCB_DBG_SERDES_OUTPUTS_TX_PHASE_OUT_LN1_MASK },
    { "TX_PHASE_OUT_LN0", AR_SLB_LCB_DBG_SERDES_OUTPUTS_TX_PHASE_OUT_LN0_BP, AR_SLB_LCB_DBG_SERDES_OUTPUTS_TX_PHASE_OUT_LN0_MASK },
    { "RX_PATTERN_CMP_PASS_LN2", AR_SLB_LCB_DBG_SERDES_OUTPUTS_RX_PATTERN_CMP_PASS_LN2_BP, AR_SLB_LCB_DBG_SERDES_OUTPUTS_RX_PATTERN_CMP_PASS_LN2_MASK },
    { "RX_PATTERN_CMP_PASS_LN1", AR_SLB_LCB_DBG_SERDES_OUTPUTS_RX_PATTERN_CMP_PASS_LN1_BP, AR_SLB_LCB_DBG_SERDES_OUTPUTS_RX_PATTERN_CMP_PASS_LN1_MASK },
    { "RX_PATTERN_CMP_PASS_LN0", AR_SLB_LCB_DBG_SERDES_OUTPUTS_RX_PATTERN_CMP_PASS_LN0_BP, AR_SLB_LCB_DBG_SERDES_OUTPUTS_RX_PATTERN_CMP_PASS_LN0_MASK },
    { "RX_SIGNAL_OK", AR_SLB_LCB_DBG_SERDES_OUTPUTS_RX_SIGNAL_OK_BP, AR_SLB_LCB_DBG_SERDES_OUTPUTS_RX_SIGNAL_OK_MASK },
    { "RX_SIG_STRENGTH_LN2", AR_SLB_LCB_DBG_SERDES_OUTPUTS_RX_SIG_STRENGTH_LN2_BP, AR_SLB_LCB_DBG_SERDES_OUTPUTS_RX_SIG_STRENGTH_LN2_MASK },
    { "RX_SIG_STRENGTH_LN1", AR_SLB_LCB_DBG_SERDES_OUTPUTS_RX_SIG_STRENGTH_LN1_BP, AR_SLB_LCB_DBG_SERDES_OUTPUTS_RX_SIG_STRENGTH_LN1_MASK },
    { "RX_SIG_STRENGTH_LN0", AR_SLB_LCB_DBG_SERDES_OUTPUTS_RX_SIG_STRENGTH_LN0_BP, AR_SLB_LCB_DBG_SERDES_OUTPUTS_RX_SIG_STRENGTH_LN0_MASK },
    { "RX_RDY", AR_SLB_LCB_DBG_SERDES_OUTPUTS_RX_RDY_BP, AR_SLB_LCB_DBG_SERDES_OUTPUTS_RX_RDY_MASK },
    { NULL, 0, 0 }
};

/*
 *  AR LCB MMR DECLARATIONS
 */
static const generic_mmr_t _ar_slb_lcb_cfg_run = {
    "AR_SLB_LCB_CFG_RUN", AR_SLB_LCB_CFG_RUN, 8, 1, _ar_slb_lcb_cfg_run_detail
};
static const generic_mmr_t _ar_slb_lcb_cfg_mmr_reset = {
    "AR_SLB_LCB_CFG_MMR_RESET", AR_SLB_LCB_CFG_MMR_RESET, 8, 1, _ar_slb_lcb_cfg_mmr_reset_detail
};
static const generic_mmr_t _ar_slb_lcb_cfg_tx_fifos_reset = {
    "AR_SLB_LCB_CFG_TX_FIFOS_RESET", AR_SLB_LCB_CFG_TX_FIFOS_RESET, 8, 1, _ar_slb_lcb_cfg_tx_fifos_reset_detail
};
static const generic_mmr_t _ar_slb_lcb_cfg_startup_0 = {
    "AR_SLB_LCB_CFG_STARTUP_0", AR_SLB_LCB_CFG_STARTUP_0, 8, 1, _ar_slb_lcb_cfg_startup_0_detail
};
static const generic_mmr_t _ar_slb_lcb_cfg_startup_1 = {
    "AR_SLB_LCB_CFG_STARTUP_1", AR_SLB_LCB_CFG_STARTUP_1, 8, 1, _ar_slb_lcb_cfg_startup_1_detail
};
static const generic_mmr_t _ar_slb_lcb_sts_startup_0 = {
    "AR_SLB_LCB_STS_STARTUP_0", AR_SLB_LCB_STS_STARTUP_0, 8, 1, _ar_slb_lcb_sts_startup_0_detail
};
static const generic_mmr_t _ar_slb_lcb_sts_startup_1 = {
    "AR_SLB_LCB_STS_STARTUP_1", AR_SLB_LCB_STS_STARTUP_1, 8, 1, _ar_slb_lcb_sts_startup_1_detail
};
static const generic_mmr_t _ar_slb_lcb_cfg_discovery_local = {
    "AR_SLB_LCB_CFG_DISCOVERY_LOCAL", AR_SLB_LCB_CFG_DISCOVERY_LOCAL, 8, 1, _ar_slb_lcb_cfg_discovery_local_detail
};
static const generic_mmr_t _ar_slb_lcb_sts_discovery_remote = {
    "AR_SLB_LCB_STS_DISCOVERY_REMOTE", AR_SLB_LCB_STS_DISCOVERY_REMOTE, 8, 1, _ar_slb_lcb_sts_discovery_remote_detail
};
static const generic_mmr_t _ar_slb_lcb_cfg_scramble_seed_0 = {
    "AR_SLB_LCB_CFG_SCRAMBLE_SEED_0", AR_SLB_LCB_CFG_SCRAMBLE_SEED_0, 8, 1, _ar_slb_lcb_cfg_scramble_seed_0_detail
};
static const generic_mmr_t _ar_slb_lcb_cfg_scramble_seed_1 = {
    "AR_SLB_LCB_CFG_SCRAMBLE_SEED_1", AR_SLB_LCB_CFG_SCRAMBLE_SEED_1, 8, 1, _ar_slb_lcb_cfg_scramble_seed_1_detail
};
static const generic_mmr_t _ar_slb_lcb_cfg_scramble_seed_2 = {
    "AR_SLB_LCB_CFG_SCRAMBLE_SEED_2", AR_SLB_LCB_CFG_SCRAMBLE_SEED_2, 8, 1, _ar_slb_lcb_cfg_scramble_seed_2_detail
};
static const generic_mmr_t _ar_slb_lcb_cfg_degrade = {
    "AR_SLB_LCB_CFG_DEGRADE", AR_SLB_LCB_CFG_DEGRADE, 8, 1, _ar_slb_lcb_cfg_degrade_detail
};
static const generic_mmr_t _ar_slb_lcb_cfg_link_kill_en = {
    "AR_SLB_LCB_CFG_LINK_KILL_EN", AR_SLB_LCB_CFG_LINK_KILL_EN, 8, 1, _ar_slb_lcb_cfg_link_kill_en_detail
};
static const generic_mmr_t _ar_slb_lcb_err_flg = {
    "AR_SLB_LCB_ERR_FLG", AR_SLB_LCB_ERR_FLG, 8, 1, _ar_slb_lcb_err_flg_detail
};
static const generic_mmr_t _ar_slb_lcb_err_clr = {
    "AR_SLB_LCB_ERR_CLR", AR_SLB_LCB_ERR_CLR, 8, 1, _ar_slb_lcb_err_clr_detail
};
static const generic_mmr_t _ar_slb_lcb_err_hss_msk = {
    "AR_SLB_LCB_ERR_HSS_MSK", AR_SLB_LCB_ERR_HSS_MSK, 8, 1, _ar_slb_lcb_err_hss_msk_detail
};
static const generic_mmr_t _ar_slb_lcb_err_first_flg = {
    "AR_SLB_LCB_ERR_FIRST_FLG", AR_SLB_LCB_ERR_FIRST_FLG, 8, 1, _ar_slb_lcb_err_first_flg_detail
};
static const generic_mmr_t _ar_slb_lcb_dbg_good_up_cnt = {
    "AR_SLB_LCB_DBG_GOOD_UP_CNT", AR_SLB_LCB_DBG_GOOD_UP_CNT, 8, 1, _ar_slb_lcb_dbg_good_up_cnt_detail
};
static const generic_mmr_t _ar_slb_lcb_dbg_accepted_up_cnt = {
    "AR_SLB_LCB_DBG_ACCEPTED_UP_CNT", AR_SLB_LCB_DBG_ACCEPTED_UP_CNT, 8, 1, _ar_slb_lcb_dbg_accepted_up_cnt_detail
};
static const generic_mmr_t _ar_slb_lcb_dbg_clk_cntr = {
    "AR_SLB_LCB_DBG_CLK_CNTR", AR_SLB_LCB_DBG_CLK_CNTR, 8, 1, _ar_slb_lcb_dbg_clk_cntr_detail
};
static const generic_mmr_t _ar_slb_lcb_cfg_perf_cntr_reset = {
    "AR_SLB_LCB_CFG_PERF_CNTR_RESET", AR_SLB_LCB_CFG_PERF_CNTR_RESET, 8, 1, _ar_slb_lcb_cfg_perf_cntr_reset_detail
};
static const generic_mmr_t _ar_slb_lcb_err_info_crc_cnt_0 = {
    "AR_SLB_LCB_ERR_INFO_CRC_CNT_0", AR_SLB_LCB_ERR_INFO_CRC_CNT_0, 8, 1, _ar_slb_lcb_err_info_crc_cnt_0_detail
};
static const generic_mmr_t _ar_slb_lcb_err_info_crc_cnt_1 = {
    "AR_SLB_LCB_ERR_INFO_CRC_CNT_1", AR_SLB_LCB_ERR_INFO_CRC_CNT_1, 8, 1, _ar_slb_lcb_err_info_crc_cnt_1_detail
};
static const generic_mmr_t _ar_slb_lcb_err_info_crc_cnt_2 = {
    "AR_SLB_LCB_ERR_INFO_CRC_CNT_2", AR_SLB_LCB_ERR_INFO_CRC_CNT_2, 8, 1, _ar_slb_lcb_err_info_crc_cnt_2_detail
};
static const generic_mmr_t _ar_slb_lcb_err_info_crc_cnt_3 = {
    "AR_SLB_LCB_ERR_INFO_CRC_CNT_3", AR_SLB_LCB_ERR_INFO_CRC_CNT_3, 8, 1, _ar_slb_lcb_err_info_crc_cnt_3_detail
};
static const generic_mmr_t _ar_slb_lcb_err_info_crc_cnt_4 = {
    "AR_SLB_LCB_ERR_INFO_CRC_CNT_4", AR_SLB_LCB_ERR_INFO_CRC_CNT_4, 8, 1, _ar_slb_lcb_err_info_crc_cnt_4_detail
};
static const generic_mmr_t _ar_slb_lcb_err_info_crc_cnt_5 = {
    "AR_SLB_LCB_ERR_INFO_CRC_CNT_5", AR_SLB_LCB_ERR_INFO_CRC_CNT_5, 8, 1, _ar_slb_lcb_err_info_crc_cnt_5_detail
};
static const generic_mmr_t _ar_slb_lcb_err_info_misc_cnt = {
    "AR_SLB_LCB_ERR_INFO_MISC_CNT", AR_SLB_LCB_ERR_INFO_MISC_CNT, 8, 1, _ar_slb_lcb_err_info_misc_cnt_detail
};
static const generic_mmr_t _ar_slb_lcb_err_info_ecc_cnt_0 = {
    "AR_SLB_LCB_ERR_INFO_ECC_CNT_0", AR_SLB_LCB_ERR_INFO_ECC_CNT_0, 8, 1, _ar_slb_lcb_err_info_ecc_cnt_0_detail
};
static const generic_mmr_t _ar_slb_lcb_err_info_ecc_cnt_1 = {
    "AR_SLB_LCB_ERR_INFO_ECC_CNT_1", AR_SLB_LCB_ERR_INFO_ECC_CNT_1, 8, 1, _ar_slb_lcb_err_info_ecc_cnt_1_detail
};
static const generic_mmr_t _ar_slb_lcb_err_info_rp_buf_sbe_0 = {
    "AR_SLB_LCB_ERR_INFO_RP_BUF_SBE_0", AR_SLB_LCB_ERR_INFO_RP_BUF_SBE_0, 8, 1, _ar_slb_lcb_err_info_rp_buf_sbe_0_detail
};
static const generic_mmr_t _ar_slb_lcb_err_info_rp_buf_mbe_0 = {
    "AR_SLB_LCB_ERR_INFO_RP_BUF_MBE_0", AR_SLB_LCB_ERR_INFO_RP_BUF_MBE_0, 8, 1, _ar_slb_lcb_err_info_rp_buf_mbe_0_detail
};
static const generic_mmr_t _ar_slb_lcb_err_info_rp_buf_sbe_1 = {
    "AR_SLB_LCB_ERR_INFO_RP_BUF_SBE_1", AR_SLB_LCB_ERR_INFO_RP_BUF_SBE_1, 8, 1, _ar_slb_lcb_err_info_rp_buf_sbe_1_detail
};
static const generic_mmr_t _ar_slb_lcb_err_info_rp_buf_mbe_1 = {
    "AR_SLB_LCB_ERR_INFO_RP_BUF_MBE_1", AR_SLB_LCB_ERR_INFO_RP_BUF_MBE_1, 8, 1, _ar_slb_lcb_err_info_rp_buf_mbe_1_detail
};
static const generic_mmr_t _ar_slb_lcb_err_info_fl_buf_sbe = {
    "AR_SLB_LCB_ERR_INFO_FL_BUF_SBE", AR_SLB_LCB_ERR_INFO_FL_BUF_SBE, 8, 1, _ar_slb_lcb_err_info_fl_buf_sbe_detail
};
static const generic_mmr_t _ar_slb_lcb_err_info_fl_buf_mbe = {
    "AR_SLB_LCB_ERR_INFO_FL_BUF_MBE", AR_SLB_LCB_ERR_INFO_FL_BUF_MBE, 8, 1, _ar_slb_lcb_err_info_fl_buf_mbe_detail
};
static const generic_mmr_t _ar_slb_lcb_dbg_errinj_crc = {
    "AR_SLB_LCB_DBG_ERRINJ_CRC", AR_SLB_LCB_DBG_ERRINJ_CRC, 8, 1, _ar_slb_lcb_dbg_errinj_crc_detail
};
static const generic_mmr_t _ar_slb_lcb_dbg_errinj_crc_seed = {
    "AR_SLB_LCB_DBG_ERRINJ_CRC_SEED", AR_SLB_LCB_DBG_ERRINJ_CRC_SEED, 8, 1, _ar_slb_lcb_dbg_errinj_crc_seed_detail
};
static const generic_mmr_t _ar_slb_lcb_dbg_errinj_ecc = {
    "AR_SLB_LCB_DBG_ERRINJ_ECC", AR_SLB_LCB_DBG_ERRINJ_ECC, 8, 1, _ar_slb_lcb_dbg_errinj_ecc_detail
};
static const generic_mmr_t _ar_slb_lcb_dbg_errinj_misc = {
    "AR_SLB_LCB_DBG_ERRINJ_MISC", AR_SLB_LCB_DBG_ERRINJ_MISC, 8, 1, _ar_slb_lcb_dbg_errinj_misc_detail
};
static const generic_mmr_t _ar_slb_lcb_dbg_init_state_0 = {
    "AR_SLB_LCB_DBG_INIT_STATE_0", AR_SLB_LCB_DBG_INIT_STATE_0, 8, 1, _ar_slb_lcb_dbg_init_state_0_detail
};
static const generic_mmr_t _ar_slb_lcb_dbg_init_state_1 = {
    "AR_SLB_LCB_DBG_INIT_STATE_1", AR_SLB_LCB_DBG_INIT_STATE_1, 8, 1, _ar_slb_lcb_dbg_init_state_1_detail
};
static const generic_mmr_t _ar_slb_lcb_dbg_init_state_2 = {
    "AR_SLB_LCB_DBG_INIT_STATE_2", AR_SLB_LCB_DBG_INIT_STATE_2, 8, 1, _ar_slb_lcb_dbg_init_state_2_detail
};
static const generic_mmr_t _ar_slb_lcb_cfg_init_pause_0 = {
    "AR_SLB_LCB_CFG_INIT_PAUSE_0", AR_SLB_LCB_CFG_INIT_PAUSE_0, 8, 1, _ar_slb_lcb_cfg_init_pause_0_detail
};
static const generic_mmr_t _ar_slb_lcb_cfg_init_pause_1 = {
    "AR_SLB_LCB_CFG_INIT_PAUSE_1", AR_SLB_LCB_CFG_INIT_PAUSE_1, 8, 1, _ar_slb_lcb_cfg_init_pause_1_detail
};
static const generic_mmr_t _ar_slb_lcb_dbg_tx_fifo_wr_data = {
    "AR_SLB_LCB_DBG_TX_FIFO_WR_DATA", AR_SLB_LCB_DBG_TX_FIFO_WR_DATA, 8, 1, _ar_slb_lcb_dbg_tx_fifo_wr_data_detail
};
static const generic_mmr_t _ar_slb_lcb_dbg_tx_fifo_rd_data = {
    "AR_SLB_LCB_DBG_TX_FIFO_RD_DATA", AR_SLB_LCB_DBG_TX_FIFO_RD_DATA, 8, 1, _ar_slb_lcb_dbg_tx_fifo_rd_data_detail
};
static const generic_mmr_t _ar_slb_lcb_dbg_rx_fifo_wr_data = {
    "AR_SLB_LCB_DBG_RX_FIFO_WR_DATA", AR_SLB_LCB_DBG_RX_FIFO_WR_DATA, 8, 1, _ar_slb_lcb_dbg_rx_fifo_wr_data_detail
};
static const generic_mmr_t _ar_slb_lcb_dbg_rx_fifo_rd_data = {
    "AR_SLB_LCB_DBG_RX_FIFO_RD_DATA", AR_SLB_LCB_DBG_RX_FIFO_RD_DATA, 8, 1, _ar_slb_lcb_dbg_rx_fifo_rd_data_detail
};
static const generic_mmr_t _ar_slb_lcb_dbg_reinit_cause = {
    "AR_SLB_LCB_DBG_REINIT_CAUSE", AR_SLB_LCB_DBG_REINIT_CAUSE, 8, 1, _ar_slb_lcb_dbg_reinit_cause_detail
};
static const generic_mmr_t _ar_slb_lcb_dbg_replay_0 = {
    "AR_SLB_LCB_DBG_REPLAY_0", AR_SLB_LCB_DBG_REPLAY_0, 8, 1, _ar_slb_lcb_dbg_replay_0_detail
};
static const generic_mmr_t _ar_slb_lcb_dbg_replay_1 = {
    "AR_SLB_LCB_DBG_REPLAY_1", AR_SLB_LCB_DBG_REPLAY_1, 8, 1, _ar_slb_lcb_dbg_replay_1_detail
};
static const generic_mmr_t _ar_slb_lcb_dbg_oflw = {
    "AR_SLB_LCB_DBG_OFLW", AR_SLB_LCB_DBG_OFLW, 8, 1, _ar_slb_lcb_dbg_oflw_detail
};
static const generic_mmr_t _ar_slb_lcb_dbg_vc_ack = {
    "AR_SLB_LCB_DBG_VC_ACK", AR_SLB_LCB_DBG_VC_ACK, 8, 1, _ar_slb_lcb_dbg_vc_ack_detail
};
static const generic_mmr_t _ar_slb_lcb_cfg_pause = {
    "AR_SLB_LCB_CFG_PAUSE", AR_SLB_LCB_CFG_PAUSE, 8, 1, _ar_slb_lcb_cfg_pause_detail
};
static const generic_mmr_t _ar_slb_lcb_cfg_compare_value = {
    "AR_SLB_LCB_CFG_COMPARE_VALUE", AR_SLB_LCB_CFG_COMPARE_VALUE, 8, 1, _ar_slb_lcb_cfg_compare_value_detail
};
static const generic_mmr_t _ar_slb_lcb_cfg_compare_mask = {
    "AR_SLB_LCB_CFG_COMPARE_MASK", AR_SLB_LCB_CFG_COMPARE_MASK, 8, 1, _ar_slb_lcb_cfg_compare_mask_detail
};
static const generic_mmr_t _ar_slb_lcb_dbg_pause_trigger_flit = {
    "AR_SLB_LCB_DBG_PAUSE_TRIGGER_FLIT", AR_SLB_LCB_DBG_PAUSE_TRIGGER_FLIT, 8, 1, _ar_slb_lcb_dbg_pause_trigger_flit_detail
};
static const generic_mmr_t _ar_slb_lcb_cfg_ram_read_write = {
    "AR_SLB_LCB_CFG_RAM_READ_WRITE", AR_SLB_LCB_CFG_RAM_READ_WRITE, 8, 1, _ar_slb_lcb_cfg_ram_read_write_detail
};
static const generic_mmr_t _ar_slb_lcb_cfg_ram_data = {
    "AR_SLB_LCB_CFG_RAM_DATA", AR_SLB_LCB_CFG_RAM_DATA, 8, 1, _ar_slb_lcb_cfg_ram_data_detail
};
static const generic_mmr_t _ar_slb_lcb_cfg_serdes_cx = {
    "AR_SLB_LCB_CFG_SERDES_CX", AR_SLB_LCB_CFG_SERDES_CX, 8, 1, _ar_slb_lcb_cfg_serdes_cx_detail
};
static const generic_mmr_t _ar_slb_lcb_cfg_serdes_tx = {
    "AR_SLB_LCB_CFG_SERDES_TX", AR_SLB_LCB_CFG_SERDES_TX, 8, 1, _ar_slb_lcb_cfg_serdes_tx_detail
};
static const generic_mmr_t _ar_slb_lcb_cfg_serdes_rx = {
    "AR_SLB_LCB_CFG_SERDES_RX", AR_SLB_LCB_CFG_SERDES_RX, 8, 1, _ar_slb_lcb_cfg_serdes_rx_detail
};
static const generic_mmr_t _ar_slb_lcb_dbg_serdes_outputs = {
    "AR_SLB_LCB_DBG_SERDES_OUTPUTS", AR_SLB_LCB_DBG_SERDES_OUTPUTS, 8, 1, _ar_slb_lcb_dbg_serdes_outputs_detail
};

/*
 *  INSTALL AR LCB MMRS
 */
static const generic_mmr_t* _ar_lcb_mmrs[] _unused = {
    &_ar_slb_lcb_cfg_run,
    &_ar_slb_lcb_cfg_mmr_reset,
    &_ar_slb_lcb_cfg_tx_fifos_reset,
    &_ar_slb_lcb_cfg_startup_0,
    &_ar_slb_lcb_cfg_startup_1,
    &_ar_slb_lcb_sts_startup_0,
    &_ar_slb_lcb_sts_startup_1,
    &_ar_slb_lcb_cfg_discovery_local,
    &_ar_slb_lcb_sts_discovery_remote,
    &_ar_slb_lcb_cfg_scramble_seed_0,
    &_ar_slb_lcb_cfg_scramble_seed_1,
    &_ar_slb_lcb_cfg_scramble_seed_2,
    &_ar_slb_lcb_cfg_degrade,
    &_ar_slb_lcb_cfg_link_kill_en,
    &_ar_slb_lcb_err_flg,
    &_ar_slb_lcb_err_clr,
    &_ar_slb_lcb_err_hss_msk,
    &_ar_slb_lcb_err_first_flg,
    &_ar_slb_lcb_dbg_good_up_cnt,
    &_ar_slb_lcb_dbg_accepted_up_cnt,
    &_ar_slb_lcb_dbg_clk_cntr,
    &_ar_slb_lcb_cfg_perf_cntr_reset,
    &_ar_slb_lcb_err_info_crc_cnt_0,
    &_ar_slb_lcb_err_info_crc_cnt_1,
    &_ar_slb_lcb_err_info_crc_cnt_2,
    &_ar_slb_lcb_err_info_crc_cnt_3,
    &_ar_slb_lcb_err_info_crc_cnt_4,
    &_ar_slb_lcb_err_info_crc_cnt_5,
    &_ar_slb_lcb_err_info_misc_cnt,
    &_ar_slb_lcb_err_info_ecc_cnt_0,
    &_ar_slb_lcb_err_info_ecc_cnt_1,
    &_ar_slb_lcb_err_info_rp_buf_sbe_0,
    &_ar_slb_lcb_err_info_rp_buf_mbe_0,
    &_ar_slb_lcb_err_info_rp_buf_sbe_1,
    &_ar_slb_lcb_err_info_rp_buf_mbe_1,
    &_ar_slb_lcb_err_info_fl_buf_sbe,
    &_ar_slb_lcb_err_info_fl_buf_mbe,
    &_ar_slb_lcb_dbg_errinj_crc,
    &_ar_slb_lcb_dbg_errinj_crc_seed,
    &_ar_slb_lcb_dbg_errinj_ecc,
    &_ar_slb_lcb_dbg_errinj_misc,
    &_ar_slb_lcb_dbg_init_state_0,
    &_ar_slb_lcb_dbg_init_state_1,
    &_ar_slb_lcb_dbg_init_state_2,
    &_ar_slb_lcb_cfg_init_pause_0,
    &_ar_slb_lcb_cfg_init_pause_1,
    &_ar_slb_lcb_dbg_tx_fifo_wr_data,
    &_ar_slb_lcb_dbg_tx_fifo_rd_data,
    &_ar_slb_lcb_dbg_rx_fifo_wr_data,
    &_ar_slb_lcb_dbg_rx_fifo_rd_data,
    &_ar_slb_lcb_dbg_reinit_cause,
    &_ar_slb_lcb_dbg_replay_0,
    &_ar_slb_lcb_dbg_replay_1,
    &_ar_slb_lcb_dbg_oflw,
    &_ar_slb_lcb_dbg_vc_ack,
    &_ar_slb_lcb_cfg_pause,
    &_ar_slb_lcb_cfg_compare_value,
    &_ar_slb_lcb_cfg_compare_mask,
    &_ar_slb_lcb_dbg_pause_trigger_flit,
    &_ar_slb_lcb_cfg_ram_read_write,
    &_ar_slb_lcb_cfg_ram_data,
    &_ar_slb_lcb_cfg_serdes_cx,
    &_ar_slb_lcb_cfg_serdes_tx,
    &_ar_slb_lcb_cfg_serdes_rx,
    &_ar_slb_lcb_dbg_serdes_outputs,
    NULL
};

#endif
