/******************************************************************************
 * COPYRIGHT CRAY INC. ar_nat_mmrs_h.h
 * FILE: ar_nat_mmrs_h.h
 * Created by v2h.c on Wed Oct  8 14:38:59 2014
 ******************************************************************************/

#ifndef _AR_NAT_MMRS_H_H_
#define _AR_NAT_MMRS_H_H_

#ifdef __GNUC__
#define _unused __attribute__((unused))
#else
#define _unused
#endif

#ifndef _GENERIC_MMRD_T_
#define _GENERIC_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint64_t _mask;		/* Field bit mask */
} generic_mmrd_t;
#endif

#ifndef _ERRCAT_MMRD_T_
#define _ERRCAT_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint32_t _ec;		/* Field error category */
} errcat_mmrd_t;
#endif

#ifndef _GENERIC_MMR_T_
#define _GENERIC_MMR_T_
typedef struct {
	char* _name;		/* MMR name */
	uint64_t _addr;		/* MMR address */
	int _size;		/* Size in bytes of MMR */
	int _depth;		/* Number of MMR instances */
	const generic_mmrd_t *_info;	/* MMR detail */
} generic_mmr_t;
#endif

static const generic_mmr_t* _ar_nat_mmrs[] _unused;	/* NAT Array */

/*
 *  AR NAT MMR DETAIL DECLARATIONS
 */
static const generic_mmrd_t _ar_nic_nat_nat_mmr_ring_0_hi_nat_detail[] = {
    { "UNUSED_145_35", AR_NIC_NAT_NAT_MMR_RING_0_HI_NAT_UNUSED_145_35_BP, AR_NIC_NAT_NAT_MMR_RING_0_HI_NAT_UNUSED_145_35_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_nat_mmr_ring_0_mid_nat_detail[] = {
    { "UNUSED_127_98", AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_UNUSED_127_98_BP, AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_UNUSED_127_98_MASK },
    { "CNTR_PTT_MBE", AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_PTT_MBE_BP, AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_PTT_MBE_MASK },
    { "CNTR_PTT_SBE", AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_PTT_SBE_BP, AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_PTT_SBE_MASK },
    { "CNTR_MDDT1_MBE", AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_MDDT1_MBE_BP, AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_MDDT1_MBE_MASK },
    { "CNTR_MDDT1_SBE", AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_MDDT1_SBE_BP, AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_MDDT1_SBE_MASK },
    { "CNTR_MDDT0_MBE", AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_MDDT0_MBE_BP, AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_MDDT0_MBE_MASK },
    { "CNTR_MDDT0_SBE", AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_MDDT0_SBE_BP, AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_MDDT0_SBE_MASK },
    { "CNTR_PIPELINE_STALLED", AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_PIPELINE_STALLED_BP, AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_PIPELINE_STALLED_MASK },
    { "CNTR_BTE_BLOCKED", AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_BTE_BLOCKED_BP, AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_BTE_BLOCKED_MASK },
    { "CNTR_BTE_STALLED", AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_BTE_STALLED_BP, AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_BTE_STALLED_MASK },
    { "CNTR_BTE_TRANSLATIONS", AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_BTE_TRANSLATIONS_BP, AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_BTE_TRANSLATIONS_MASK },
    { "CNTR_CQ_BLOCKED", AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_CQ_BLOCKED_BP, AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_CQ_BLOCKED_MASK },
    { "CNTR_CQ_STALLED", AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_CQ_STALLED_BP, AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_CQ_STALLED_MASK },
    { "CNTR_CQ_TRANSLATIONS", AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_CQ_TRANSLATIONS_BP, AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_CQ_TRANSLATIONS_MASK },
    { "CNTR_RAT_BLOCKED", AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_RAT_BLOCKED_BP, AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_RAT_BLOCKED_MASK },
    { "CNTR_RAT_STALLED", AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_RAT_STALLED_BP, AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_RAT_STALLED_MASK },
    { "CNTR_RAT_TRANSLATIONS", AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_RAT_TRANSLATIONS_BP, AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_CNTR_RAT_TRANSLATIONS_MASK },
    { "UNUSED_81_64", AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_UNUSED_81_64_BP, AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT_UNUSED_81_64_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_nat_mmr_ring_0_lo_nat_detail[] = {
    { "UNUSED_145_35", AR_NIC_NAT_NAT_MMR_RING_0_LO_NAT_UNUSED_145_35_BP, AR_NIC_NAT_NAT_MMR_RING_0_LO_NAT_UNUSED_145_35_MASK },
    { "R_Q_NAT_PI_OS_IRQ", AR_NIC_NAT_NAT_MMR_RING_0_LO_NAT_R_Q_NAT_PI_OS_IRQ_BP, AR_NIC_NAT_NAT_MMR_RING_0_LO_NAT_R_Q_NAT_PI_OS_IRQ_MASK },
    { "R_Q_NAT_LB_HSS_IRQ", AR_NIC_NAT_NAT_MMR_RING_0_LO_NAT_R_Q_NAT_LB_HSS_IRQ_BP, AR_NIC_NAT_NAT_MMR_RING_0_LO_NAT_R_Q_NAT_LB_HSS_IRQ_MASK },
    { "R_Q_NAT_NETMON_RING_WRACK", AR_NIC_NAT_NAT_MMR_RING_0_LO_NAT_R_Q_NAT_NETMON_RING_WRACK_BP, AR_NIC_NAT_NAT_MMR_RING_0_LO_NAT_R_Q_NAT_NETMON_RING_WRACK_MASK },
    { "R_Q_NAT_NETMON_RING_15_0", AR_NIC_NAT_NAT_MMR_RING_0_LO_NAT_R_Q_NAT_NETMON_RING_15_0_BP, AR_NIC_NAT_NAT_MMR_RING_0_LO_NAT_R_Q_NAT_NETMON_RING_15_0_MASK },
    { "I_NETMON_NAT_RING_15_0", AR_NIC_NAT_NAT_MMR_RING_0_LO_NAT_I_NETMON_NAT_RING_15_0_BP, AR_NIC_NAT_NAT_MMR_RING_0_LO_NAT_I_NETMON_NAT_RING_15_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_err_flg_1_hi_nat_detail[] = {
    { "UNUSED_145_128", AR_NIC_NAT_ERR_FLG_1_HI_NAT_UNUSED_145_128_BP, AR_NIC_NAT_ERR_FLG_1_HI_NAT_UNUSED_145_128_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_err_flg_1_mid_nat_detail[] = {
    { "UNUSED_127_83", AR_NIC_NAT_ERR_FLG_1_MID_NAT_UNUSED_127_83_BP, AR_NIC_NAT_ERR_FLG_1_MID_NAT_UNUSED_127_83_MASK },
    { "PTT_SBE", AR_NIC_NAT_ERR_FLG_1_MID_NAT_PTT_SBE_BP, AR_NIC_NAT_ERR_FLG_1_MID_NAT_PTT_SBE_MASK },
    { "MDDT_SBE1", AR_NIC_NAT_ERR_FLG_1_MID_NAT_MDDT_SBE1_BP, AR_NIC_NAT_ERR_FLG_1_MID_NAT_MDDT_SBE1_MASK },
    { "MDDT_SBE0", AR_NIC_NAT_ERR_FLG_1_MID_NAT_MDDT_SBE0_BP, AR_NIC_NAT_ERR_FLG_1_MID_NAT_MDDT_SBE0_MASK },
    { "PTT_MBE", AR_NIC_NAT_ERR_FLG_1_MID_NAT_PTT_MBE_BP, AR_NIC_NAT_ERR_FLG_1_MID_NAT_PTT_MBE_MASK },
    { "MDDT_MBE1", AR_NIC_NAT_ERR_FLG_1_MID_NAT_MDDT_MBE1_BP, AR_NIC_NAT_ERR_FLG_1_MID_NAT_MDDT_MBE1_MASK },
    { "MDDT_MBE0", AR_NIC_NAT_ERR_FLG_1_MID_NAT_MDDT_MBE0_BP, AR_NIC_NAT_ERR_FLG_1_MID_NAT_MDDT_MBE0_MASK },
    { "MALFORMED_MDD", AR_NIC_NAT_ERR_FLG_1_MID_NAT_MALFORMED_MDD_BP, AR_NIC_NAT_ERR_FLG_1_MID_NAT_MALFORMED_MDD_MASK },
    { "VMDHCAM_MULTIHIT", AR_NIC_NAT_ERR_FLG_1_MID_NAT_VMDHCAM_MULTIHIT_BP, AR_NIC_NAT_ERR_FLG_1_MID_NAT_VMDHCAM_MULTIHIT_MASK },
    { "IOMMU_FIFO_UFLW", AR_NIC_NAT_ERR_FLG_1_MID_NAT_IOMMU_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FLG_1_MID_NAT_IOMMU_FIFO_UFLW_MASK },
    { "BYPASS_FIFO_UFLW", AR_NIC_NAT_ERR_FLG_1_MID_NAT_BYPASS_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FLG_1_MID_NAT_BYPASS_FIFO_UFLW_MASK },
    { "BTE_FIFO_UFLW", AR_NIC_NAT_ERR_FLG_1_MID_NAT_BTE_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FLG_1_MID_NAT_BTE_FIFO_UFLW_MASK },
    { "CQ_FIFO_UFLW", AR_NIC_NAT_ERR_FLG_1_MID_NAT_CQ_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FLG_1_MID_NAT_CQ_FIFO_UFLW_MASK },
    { "RAT_FIFO_UFLW", AR_NIC_NAT_ERR_FLG_1_MID_NAT_RAT_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FLG_1_MID_NAT_RAT_FIFO_UFLW_MASK },
    { "IOMMU_FIFO_OFLW", AR_NIC_NAT_ERR_FLG_1_MID_NAT_IOMMU_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FLG_1_MID_NAT_IOMMU_FIFO_OFLW_MASK },
    { "BYPASS_FIFO_OFLW", AR_NIC_NAT_ERR_FLG_1_MID_NAT_BYPASS_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FLG_1_MID_NAT_BYPASS_FIFO_OFLW_MASK },
    { "BTE_FIFO_OFLW", AR_NIC_NAT_ERR_FLG_1_MID_NAT_BTE_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FLG_1_MID_NAT_BTE_FIFO_OFLW_MASK },
    { "CQ_FIFO_OFLW", AR_NIC_NAT_ERR_FLG_1_MID_NAT_CQ_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FLG_1_MID_NAT_CQ_FIFO_OFLW_MASK },
    { "RAT_FIFO_OFLW", AR_NIC_NAT_ERR_FLG_1_MID_NAT_RAT_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FLG_1_MID_NAT_RAT_FIFO_OFLW_MASK },
    { "DIAG_ONLY", AR_NIC_NAT_ERR_FLG_1_MID_NAT_DIAG_ONLY_BP, AR_NIC_NAT_ERR_FLG_1_MID_NAT_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_err_flg_1_lo_nat_detail[] = {
    { "UNUSED_63_19", AR_NIC_NAT_ERR_FLG_1_LO_NAT_UNUSED_63_19_BP, AR_NIC_NAT_ERR_FLG_1_LO_NAT_UNUSED_63_19_MASK },
    { "I_PTT_SBE", AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_PTT_SBE_BP, AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_PTT_SBE_MASK },
    { "I_MDDT_SBE1", AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_MDDT_SBE1_BP, AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_MDDT_SBE1_MASK },
    { "I_MDDT_SBE0", AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_MDDT_SBE0_BP, AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_MDDT_SBE0_MASK },
    { "I_PTT_MBE", AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_PTT_MBE_BP, AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_PTT_MBE_MASK },
    { "I_MDDT_MBE1", AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_MDDT_MBE1_BP, AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_MDDT_MBE1_MASK },
    { "I_MDDT_MBE0", AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_MDDT_MBE0_BP, AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_MDDT_MBE0_MASK },
    { "I_MALFORMED_MDD", AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_MALFORMED_MDD_BP, AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_MALFORMED_MDD_MASK },
    { "I_VMDHCAM_MULTIHIT", AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_VMDHCAM_MULTIHIT_BP, AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_VMDHCAM_MULTIHIT_MASK },
    { "I_IOMMU_FIFO_UFLW", AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_IOMMU_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_IOMMU_FIFO_UFLW_MASK },
    { "I_BYPASS_FIFO_UFLW", AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_BYPASS_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_BYPASS_FIFO_UFLW_MASK },
    { "I_BTE_FIFO_UFLW", AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_BTE_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_BTE_FIFO_UFLW_MASK },
    { "I_CQ_FIFO_UFLW", AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_CQ_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_CQ_FIFO_UFLW_MASK },
    { "I_RAT_FIFO_UFLW", AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_RAT_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_RAT_FIFO_UFLW_MASK },
    { "I_IOMMU_FIFO_OFLW", AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_IOMMU_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_IOMMU_FIFO_OFLW_MASK },
    { "I_BYPASS_FIFO_OFLW", AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_BYPASS_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_BYPASS_FIFO_OFLW_MASK },
    { "I_BTE_FIFO_OFLW", AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_BTE_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_BTE_FIFO_OFLW_MASK },
    { "I_CQ_FIFO_OFLW", AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_CQ_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_CQ_FIFO_OFLW_MASK },
    { "I_RAT_FIFO_OFLW", AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_RAT_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FLG_1_LO_NAT_I_RAT_FIFO_OFLW_MASK },
    { "UNUSED_0", AR_NIC_NAT_ERR_FLG_1_LO_NAT_UNUSED_0_BP, AR_NIC_NAT_ERR_FLG_1_LO_NAT_UNUSED_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_nat_rat_req_rsp_2_hi_nat_detail[] = {
    { "UNUSED_145_141", AR_NIC_NAT_NAT_RAT_REQ_RSP_2_HI_NAT_UNUSED_145_141_BP, AR_NIC_NAT_NAT_RAT_REQ_RSP_2_HI_NAT_UNUSED_145_141_MASK },
    { "R_Q_NAT_RAT_TID", AR_NIC_NAT_NAT_RAT_REQ_RSP_2_HI_NAT_R_Q_NAT_RAT_TID_BP, AR_NIC_NAT_NAT_RAT_REQ_RSP_2_HI_NAT_R_Q_NAT_RAT_TID_MASK },
    { "R_Q_NAT_RAT_CQH", AR_NIC_NAT_NAT_RAT_REQ_RSP_2_HI_NAT_R_Q_NAT_RAT_CQH_BP, AR_NIC_NAT_NAT_RAT_REQ_RSP_2_HI_NAT_R_Q_NAT_RAT_CQH_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_nat_rat_req_rsp_2_mid_nat_detail[] = {
    { "R_Q_NAT_RAT_CQH", AR_NIC_NAT_NAT_RAT_REQ_RSP_2_MID_NAT_R_Q_NAT_RAT_CQH_BP, AR_NIC_NAT_NAT_RAT_REQ_RSP_2_MID_NAT_R_Q_NAT_RAT_CQH_MASK },
    { "R_Q_NAT_RAT_PI_CFG", AR_NIC_NAT_NAT_RAT_REQ_RSP_2_MID_NAT_R_Q_NAT_RAT_PI_CFG_BP, AR_NIC_NAT_NAT_RAT_REQ_RSP_2_MID_NAT_R_Q_NAT_RAT_PI_CFG_MASK },
    { "R_Q_NAT_RAT_TC", AR_NIC_NAT_NAT_RAT_REQ_RSP_2_MID_NAT_R_Q_NAT_RAT_TC_BP, AR_NIC_NAT_NAT_RAT_REQ_RSP_2_MID_NAT_R_Q_NAT_RAT_TC_MASK },
    { "R_Q_NAT_RAT_ADDR", AR_NIC_NAT_NAT_RAT_REQ_RSP_2_MID_NAT_R_Q_NAT_RAT_ADDR_BP, AR_NIC_NAT_NAT_RAT_REQ_RSP_2_MID_NAT_R_Q_NAT_RAT_ADDR_MASK },
    { "R_Q_NAT_RAT_ERRORS", AR_NIC_NAT_NAT_RAT_REQ_RSP_2_MID_NAT_R_Q_NAT_RAT_ERRORS_BP, AR_NIC_NAT_NAT_RAT_REQ_RSP_2_MID_NAT_R_Q_NAT_RAT_ERRORS_MASK },
    { "R_Q_NAT_RAT_VALID", AR_NIC_NAT_NAT_RAT_REQ_RSP_2_MID_NAT_R_Q_NAT_RAT_VALID_BP, AR_NIC_NAT_NAT_RAT_REQ_RSP_2_MID_NAT_R_Q_NAT_RAT_VALID_MASK },
    { "I_RAT_NAT_TID", AR_NIC_NAT_NAT_RAT_REQ_RSP_2_MID_NAT_I_RAT_NAT_TID_BP, AR_NIC_NAT_NAT_RAT_REQ_RSP_2_MID_NAT_I_RAT_NAT_TID_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_nat_rat_req_rsp_2_lo_nat_detail[] = {
    { "I_RAT_NAT_TID", AR_NIC_NAT_NAT_RAT_REQ_RSP_2_LO_NAT_I_RAT_NAT_TID_BP, AR_NIC_NAT_NAT_RAT_REQ_RSP_2_LO_NAT_I_RAT_NAT_TID_MASK },
    { "I_RAT_NAT_MDH", AR_NIC_NAT_NAT_RAT_REQ_RSP_2_LO_NAT_I_RAT_NAT_MDH_BP, AR_NIC_NAT_NAT_RAT_REQ_RSP_2_LO_NAT_I_RAT_NAT_MDH_MASK },
    { "I_RAT_NAT_PROT", AR_NIC_NAT_NAT_RAT_REQ_RSP_2_LO_NAT_I_RAT_NAT_PROT_BP, AR_NIC_NAT_NAT_RAT_REQ_RSP_2_LO_NAT_I_RAT_NAT_PROT_MASK },
    { "I_RAT_NAT_PROT_TYPE", AR_NIC_NAT_NAT_RAT_REQ_RSP_2_LO_NAT_I_RAT_NAT_PROT_TYPE_BP, AR_NIC_NAT_NAT_RAT_REQ_RSP_2_LO_NAT_I_RAT_NAT_PROT_TYPE_MASK },
    { "I_RAT_NAT_ADDR", AR_NIC_NAT_NAT_RAT_REQ_RSP_2_LO_NAT_I_RAT_NAT_ADDR_BP, AR_NIC_NAT_NAT_RAT_REQ_RSP_2_LO_NAT_I_RAT_NAT_ADDR_MASK },
    { "I_RAT_NAT_READ_CMD", AR_NIC_NAT_NAT_RAT_REQ_RSP_2_LO_NAT_I_RAT_NAT_READ_CMD_BP, AR_NIC_NAT_NAT_RAT_REQ_RSP_2_LO_NAT_I_RAT_NAT_READ_CMD_MASK },
    { "I_RAT_NAT_WRITE_CMD", AR_NIC_NAT_NAT_RAT_REQ_RSP_2_LO_NAT_I_RAT_NAT_WRITE_CMD_BP, AR_NIC_NAT_NAT_RAT_REQ_RSP_2_LO_NAT_I_RAT_NAT_WRITE_CMD_MASK },
    { "I_RAT_NAT_BYPASS_IOMMU", AR_NIC_NAT_NAT_RAT_REQ_RSP_2_LO_NAT_I_RAT_NAT_BYPASS_IOMMU_BP, AR_NIC_NAT_NAT_RAT_REQ_RSP_2_LO_NAT_I_RAT_NAT_BYPASS_IOMMU_MASK },
    { "I_RAT_NAT_VALID", AR_NIC_NAT_NAT_RAT_REQ_RSP_2_LO_NAT_I_RAT_NAT_VALID_BP, AR_NIC_NAT_NAT_RAT_REQ_RSP_2_LO_NAT_I_RAT_NAT_VALID_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_nat_cq_req_rsp_3_hi_nat_detail[] = {
    { "UNUSED_145_112", AR_NIC_NAT_NAT_CQ_REQ_RSP_3_HI_NAT_UNUSED_145_112_BP, AR_NIC_NAT_NAT_CQ_REQ_RSP_3_HI_NAT_UNUSED_145_112_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_nat_cq_req_rsp_3_mid_nat_detail[] = {
    { "UNUSED_145_112", AR_NIC_NAT_NAT_CQ_REQ_RSP_3_MID_NAT_UNUSED_145_112_BP, AR_NIC_NAT_NAT_CQ_REQ_RSP_3_MID_NAT_UNUSED_145_112_MASK },
    { "R_Q_NAT_CQ_TID", AR_NIC_NAT_NAT_CQ_REQ_RSP_3_MID_NAT_R_Q_NAT_CQ_TID_BP, AR_NIC_NAT_NAT_CQ_REQ_RSP_3_MID_NAT_R_Q_NAT_CQ_TID_MASK },
    { "R_Q_NAT_CQ_TPH", AR_NIC_NAT_NAT_CQ_REQ_RSP_3_MID_NAT_R_Q_NAT_CQ_TPH_BP, AR_NIC_NAT_NAT_CQ_REQ_RSP_3_MID_NAT_R_Q_NAT_CQ_TPH_MASK },
    { "R_Q_NAT_CQ_TC", AR_NIC_NAT_NAT_CQ_REQ_RSP_3_MID_NAT_R_Q_NAT_CQ_TC_BP, AR_NIC_NAT_NAT_CQ_REQ_RSP_3_MID_NAT_R_Q_NAT_CQ_TC_MASK },
    { "R_Q_NAT_CQ_ADDR", AR_NIC_NAT_NAT_CQ_REQ_RSP_3_MID_NAT_R_Q_NAT_CQ_ADDR_BP, AR_NIC_NAT_NAT_CQ_REQ_RSP_3_MID_NAT_R_Q_NAT_CQ_ADDR_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_nat_cq_req_rsp_3_lo_nat_detail[] = {
    { "R_Q_NAT_CQ_ADDR", AR_NIC_NAT_NAT_CQ_REQ_RSP_3_LO_NAT_R_Q_NAT_CQ_ADDR_BP, AR_NIC_NAT_NAT_CQ_REQ_RSP_3_LO_NAT_R_Q_NAT_CQ_ADDR_MASK },
    { "R_Q_NAT_CQ_ERRORS", AR_NIC_NAT_NAT_CQ_REQ_RSP_3_LO_NAT_R_Q_NAT_CQ_ERRORS_BP, AR_NIC_NAT_NAT_CQ_REQ_RSP_3_LO_NAT_R_Q_NAT_CQ_ERRORS_MASK },
    { "R_Q_NAT_CQ_VALID", AR_NIC_NAT_NAT_CQ_REQ_RSP_3_LO_NAT_R_Q_NAT_CQ_VALID_BP, AR_NIC_NAT_NAT_CQ_REQ_RSP_3_LO_NAT_R_Q_NAT_CQ_VALID_MASK },
    { "UNUSED_56", AR_NIC_NAT_NAT_CQ_REQ_RSP_3_LO_NAT_UNUSED_56_BP, AR_NIC_NAT_NAT_CQ_REQ_RSP_3_LO_NAT_UNUSED_56_MASK },
    { "I_CQ_NAT_TID", AR_NIC_NAT_NAT_CQ_REQ_RSP_3_LO_NAT_I_CQ_NAT_TID_BP, AR_NIC_NAT_NAT_CQ_REQ_RSP_3_LO_NAT_I_CQ_NAT_TID_MASK },
    { "I_CQ_NAT_MDD_EN", AR_NIC_NAT_NAT_CQ_REQ_RSP_3_LO_NAT_I_CQ_NAT_MDD_EN_BP, AR_NIC_NAT_NAT_CQ_REQ_RSP_3_LO_NAT_I_CQ_NAT_MDD_EN_MASK },
    { "I_CQ_NAT_TFIELDS", AR_NIC_NAT_NAT_CQ_REQ_RSP_3_LO_NAT_I_CQ_NAT_TFIELDS_BP, AR_NIC_NAT_NAT_CQ_REQ_RSP_3_LO_NAT_I_CQ_NAT_TFIELDS_MASK },
    { "I_CQ_NAT_VALID", AR_NIC_NAT_NAT_CQ_REQ_RSP_3_LO_NAT_I_CQ_NAT_VALID_BP, AR_NIC_NAT_NAT_CQ_REQ_RSP_3_LO_NAT_I_CQ_NAT_VALID_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_nat_bte_req_rsp_4_hi_nat_detail[] = {
    { "UNUSED_145_110", AR_NIC_NAT_NAT_BTE_REQ_RSP_4_HI_NAT_UNUSED_145_110_BP, AR_NIC_NAT_NAT_BTE_REQ_RSP_4_HI_NAT_UNUSED_145_110_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_nat_bte_req_rsp_4_mid_nat_detail[] = {
    { "UNUSED_145_110", AR_NIC_NAT_NAT_BTE_REQ_RSP_4_MID_NAT_UNUSED_145_110_BP, AR_NIC_NAT_NAT_BTE_REQ_RSP_4_MID_NAT_UNUSED_145_110_MASK },
    { "R_Q_NAT_BTE_TID", AR_NIC_NAT_NAT_BTE_REQ_RSP_4_MID_NAT_R_Q_NAT_BTE_TID_BP, AR_NIC_NAT_NAT_BTE_REQ_RSP_4_MID_NAT_R_Q_NAT_BTE_TID_MASK },
    { "R_Q_NAT_BTE_PI_CFG", AR_NIC_NAT_NAT_BTE_REQ_RSP_4_MID_NAT_R_Q_NAT_BTE_PI_CFG_BP, AR_NIC_NAT_NAT_BTE_REQ_RSP_4_MID_NAT_R_Q_NAT_BTE_PI_CFG_MASK },
    { "R_Q_NAT_BTE_TC", AR_NIC_NAT_NAT_BTE_REQ_RSP_4_MID_NAT_R_Q_NAT_BTE_TC_BP, AR_NIC_NAT_NAT_BTE_REQ_RSP_4_MID_NAT_R_Q_NAT_BTE_TC_MASK },
    { "R_Q_NAT_BTE_ADDR", AR_NIC_NAT_NAT_BTE_REQ_RSP_4_MID_NAT_R_Q_NAT_BTE_ADDR_BP, AR_NIC_NAT_NAT_BTE_REQ_RSP_4_MID_NAT_R_Q_NAT_BTE_ADDR_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_nat_bte_req_rsp_4_lo_nat_detail[] = {
    { "R_Q_NAT_BTE_ADDR", AR_NIC_NAT_NAT_BTE_REQ_RSP_4_LO_NAT_R_Q_NAT_BTE_ADDR_BP, AR_NIC_NAT_NAT_BTE_REQ_RSP_4_LO_NAT_R_Q_NAT_BTE_ADDR_MASK },
    { "R_Q_NAT_BTE_ERRORS", AR_NIC_NAT_NAT_BTE_REQ_RSP_4_LO_NAT_R_Q_NAT_BTE_ERRORS_BP, AR_NIC_NAT_NAT_BTE_REQ_RSP_4_LO_NAT_R_Q_NAT_BTE_ERRORS_MASK },
    { "R_Q_NAT_BTE_VALID", AR_NIC_NAT_NAT_BTE_REQ_RSP_4_LO_NAT_R_Q_NAT_BTE_VALID_BP, AR_NIC_NAT_NAT_BTE_REQ_RSP_4_LO_NAT_R_Q_NAT_BTE_VALID_MASK },
    { "I_BTE_NAT_TID", AR_NIC_NAT_NAT_BTE_REQ_RSP_4_LO_NAT_I_BTE_NAT_TID_BP, AR_NIC_NAT_NAT_BTE_REQ_RSP_4_LO_NAT_I_BTE_NAT_TID_MASK },
    { "I_BTE_NAT_MDH", AR_NIC_NAT_NAT_BTE_REQ_RSP_4_LO_NAT_I_BTE_NAT_MDH_BP, AR_NIC_NAT_NAT_BTE_REQ_RSP_4_LO_NAT_I_BTE_NAT_MDH_MASK },
    { "I_BTE_NAT_PTAG", AR_NIC_NAT_NAT_BTE_REQ_RSP_4_LO_NAT_I_BTE_NAT_PTAG_BP, AR_NIC_NAT_NAT_BTE_REQ_RSP_4_LO_NAT_I_BTE_NAT_PTAG_MASK },
    { "I_BTE_NAT_ADDR", AR_NIC_NAT_NAT_BTE_REQ_RSP_4_LO_NAT_I_BTE_NAT_ADDR_BP, AR_NIC_NAT_NAT_BTE_REQ_RSP_4_LO_NAT_I_BTE_NAT_ADDR_MASK },
    { "I_BTE_NAT_VALID", AR_NIC_NAT_NAT_BTE_REQ_RSP_4_LO_NAT_I_BTE_NAT_VALID_BP, AR_NIC_NAT_NAT_BTE_REQ_RSP_4_LO_NAT_I_BTE_NAT_VALID_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_nat_power_down_ff_hi_nat_detail[] = {
    { "POWER_DOWN", AR_NIC_NAT_NAT_POWER_DOWN_FF_HI_NAT_POWER_DOWN_BP, AR_NIC_NAT_NAT_POWER_DOWN_FF_HI_NAT_POWER_DOWN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_nat_power_down_ff_mid_nat_detail[] = {
    { "POWER_DOWN", AR_NIC_NAT_NAT_POWER_DOWN_FF_MID_NAT_POWER_DOWN_BP, AR_NIC_NAT_NAT_POWER_DOWN_FF_MID_NAT_POWER_DOWN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_nat_power_down_ff_lo_nat_detail[] = {
    { "POWER_DOWN", AR_NIC_NAT_NAT_POWER_DOWN_FF_LO_NAT_POWER_DOWN_BP, AR_NIC_NAT_NAT_POWER_DOWN_FF_LO_NAT_POWER_DOWN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_cfg_tbl_vmdhcam_detail[] = {
    { "PTAG", AR_NIC_NAT_CFG_TBL_VMDHCAM_PTAG_BP, AR_NIC_NAT_CFG_TBL_VMDHCAM_PTAG_MASK },
    { "PKEY", AR_NIC_NAT_CFG_TBL_VMDHCAM_PKEY_BP, AR_NIC_NAT_CFG_TBL_VMDHCAM_PKEY_MASK },
    { "EN", AR_NIC_NAT_CFG_TBL_VMDHCAM_EN_BP, AR_NIC_NAT_CFG_TBL_VMDHCAM_EN_MASK },
    { "MDH_BASE", AR_NIC_NAT_CFG_TBL_VMDHCAM_MDH_BASE_BP, AR_NIC_NAT_CFG_TBL_VMDHCAM_MDH_BASE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_cfg_params_detail[] = {
    { "BYPASS_CRDTS_MAX", AR_NIC_NAT_CFG_PARAMS_BYPASS_CRDTS_MAX_BP, AR_NIC_NAT_CFG_PARAMS_BYPASS_CRDTS_MAX_MASK },
    { "IOMMU_CRDTS_MAX", AR_NIC_NAT_CFG_PARAMS_IOMMU_CRDTS_MAX_BP, AR_NIC_NAT_CFG_PARAMS_IOMMU_CRDTS_MAX_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_err_flg_detail[] = {
    { "PTT_SBE", AR_NIC_NAT_ERR_FLG_PTT_SBE_BP, AR_NIC_NAT_ERR_FLG_PTT_SBE_MASK },
    { "MDDT_SBE1", AR_NIC_NAT_ERR_FLG_MDDT_SBE1_BP, AR_NIC_NAT_ERR_FLG_MDDT_SBE1_MASK },
    { "MDDT_SBE0", AR_NIC_NAT_ERR_FLG_MDDT_SBE0_BP, AR_NIC_NAT_ERR_FLG_MDDT_SBE0_MASK },
    { "PTT_MBE", AR_NIC_NAT_ERR_FLG_PTT_MBE_BP, AR_NIC_NAT_ERR_FLG_PTT_MBE_MASK },
    { "MDDT_MBE1", AR_NIC_NAT_ERR_FLG_MDDT_MBE1_BP, AR_NIC_NAT_ERR_FLG_MDDT_MBE1_MASK },
    { "MDDT_MBE0", AR_NIC_NAT_ERR_FLG_MDDT_MBE0_BP, AR_NIC_NAT_ERR_FLG_MDDT_MBE0_MASK },
    { "MALFORMED_MDD", AR_NIC_NAT_ERR_FLG_MALFORMED_MDD_BP, AR_NIC_NAT_ERR_FLG_MALFORMED_MDD_MASK },
    { "VMDHCAM_MULTIHIT", AR_NIC_NAT_ERR_FLG_VMDHCAM_MULTIHIT_BP, AR_NIC_NAT_ERR_FLG_VMDHCAM_MULTIHIT_MASK },
    { "IOMMU_FIFO_UFLW", AR_NIC_NAT_ERR_FLG_IOMMU_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FLG_IOMMU_FIFO_UFLW_MASK },
    { "BYPASS_FIFO_UFLW", AR_NIC_NAT_ERR_FLG_BYPASS_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FLG_BYPASS_FIFO_UFLW_MASK },
    { "BTE_FIFO_UFLW", AR_NIC_NAT_ERR_FLG_BTE_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FLG_BTE_FIFO_UFLW_MASK },
    { "CQ_FIFO_UFLW", AR_NIC_NAT_ERR_FLG_CQ_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FLG_CQ_FIFO_UFLW_MASK },
    { "RAT_FIFO_UFLW", AR_NIC_NAT_ERR_FLG_RAT_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FLG_RAT_FIFO_UFLW_MASK },
    { "IOMMU_FIFO_OFLW", AR_NIC_NAT_ERR_FLG_IOMMU_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FLG_IOMMU_FIFO_OFLW_MASK },
    { "BYPASS_FIFO_OFLW", AR_NIC_NAT_ERR_FLG_BYPASS_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FLG_BYPASS_FIFO_OFLW_MASK },
    { "BTE_FIFO_OFLW", AR_NIC_NAT_ERR_FLG_BTE_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FLG_BTE_FIFO_OFLW_MASK },
    { "CQ_FIFO_OFLW", AR_NIC_NAT_ERR_FLG_CQ_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FLG_CQ_FIFO_OFLW_MASK },
    { "RAT_FIFO_OFLW", AR_NIC_NAT_ERR_FLG_RAT_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FLG_RAT_FIFO_OFLW_MASK },
    { "DIAG_ONLY", AR_NIC_NAT_ERR_FLG_DIAG_ONLY_BP, AR_NIC_NAT_ERR_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
#ifdef EXCEPTIONS_DEFS
static const errcat_mmrd_t _ar_nic_nat_err_flg_errcat[] = {
    { "PTT_SBE", AR_NIC_NAT_ERR_FLG_PTT_SBE_BP, AR_NIC_NAT_ERR_FLG_PTT_SBE_EC },
    { "MDDT_SBE1", AR_NIC_NAT_ERR_FLG_MDDT_SBE1_BP, AR_NIC_NAT_ERR_FLG_MDDT_SBE1_EC },
    { "MDDT_SBE0", AR_NIC_NAT_ERR_FLG_MDDT_SBE0_BP, AR_NIC_NAT_ERR_FLG_MDDT_SBE0_EC },
    { "PTT_MBE", AR_NIC_NAT_ERR_FLG_PTT_MBE_BP, AR_NIC_NAT_ERR_FLG_PTT_MBE_EC },
    { "MDDT_MBE1", AR_NIC_NAT_ERR_FLG_MDDT_MBE1_BP, AR_NIC_NAT_ERR_FLG_MDDT_MBE1_EC },
    { "MDDT_MBE0", AR_NIC_NAT_ERR_FLG_MDDT_MBE0_BP, AR_NIC_NAT_ERR_FLG_MDDT_MBE0_EC },
    { "MALFORMED_MDD", AR_NIC_NAT_ERR_FLG_MALFORMED_MDD_BP, AR_NIC_NAT_ERR_FLG_MALFORMED_MDD_EC },
    { "VMDHCAM_MULTIHIT", AR_NIC_NAT_ERR_FLG_VMDHCAM_MULTIHIT_BP, AR_NIC_NAT_ERR_FLG_VMDHCAM_MULTIHIT_EC },
    { "IOMMU_FIFO_UFLW", AR_NIC_NAT_ERR_FLG_IOMMU_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FLG_IOMMU_FIFO_UFLW_EC },
    { "BYPASS_FIFO_UFLW", AR_NIC_NAT_ERR_FLG_BYPASS_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FLG_BYPASS_FIFO_UFLW_EC },
    { "BTE_FIFO_UFLW", AR_NIC_NAT_ERR_FLG_BTE_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FLG_BTE_FIFO_UFLW_EC },
    { "CQ_FIFO_UFLW", AR_NIC_NAT_ERR_FLG_CQ_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FLG_CQ_FIFO_UFLW_EC },
    { "RAT_FIFO_UFLW", AR_NIC_NAT_ERR_FLG_RAT_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FLG_RAT_FIFO_UFLW_EC },
    { "IOMMU_FIFO_OFLW", AR_NIC_NAT_ERR_FLG_IOMMU_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FLG_IOMMU_FIFO_OFLW_EC },
    { "BYPASS_FIFO_OFLW", AR_NIC_NAT_ERR_FLG_BYPASS_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FLG_BYPASS_FIFO_OFLW_EC },
    { "BTE_FIFO_OFLW", AR_NIC_NAT_ERR_FLG_BTE_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FLG_BTE_FIFO_OFLW_EC },
    { "CQ_FIFO_OFLW", AR_NIC_NAT_ERR_FLG_CQ_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FLG_CQ_FIFO_OFLW_EC },
    { "RAT_FIFO_OFLW", AR_NIC_NAT_ERR_FLG_RAT_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FLG_RAT_FIFO_OFLW_EC },
    { "DIAG_ONLY", AR_NIC_NAT_ERR_FLG_DIAG_ONLY_BP, AR_NIC_NAT_ERR_FLG_DIAG_ONLY_EC },
    { NULL, 0, 0 }
};
#endif
static const generic_mmrd_t _ar_nic_nat_err_clr_detail[] = {
    { "PTT_SBE", AR_NIC_NAT_ERR_CLR_PTT_SBE_BP, AR_NIC_NAT_ERR_CLR_PTT_SBE_MASK },
    { "MDDT_SBE1", AR_NIC_NAT_ERR_CLR_MDDT_SBE1_BP, AR_NIC_NAT_ERR_CLR_MDDT_SBE1_MASK },
    { "MDDT_SBE0", AR_NIC_NAT_ERR_CLR_MDDT_SBE0_BP, AR_NIC_NAT_ERR_CLR_MDDT_SBE0_MASK },
    { "PTT_MBE", AR_NIC_NAT_ERR_CLR_PTT_MBE_BP, AR_NIC_NAT_ERR_CLR_PTT_MBE_MASK },
    { "MDDT_MBE1", AR_NIC_NAT_ERR_CLR_MDDT_MBE1_BP, AR_NIC_NAT_ERR_CLR_MDDT_MBE1_MASK },
    { "MDDT_MBE0", AR_NIC_NAT_ERR_CLR_MDDT_MBE0_BP, AR_NIC_NAT_ERR_CLR_MDDT_MBE0_MASK },
    { "MALFORMED_MDD", AR_NIC_NAT_ERR_CLR_MALFORMED_MDD_BP, AR_NIC_NAT_ERR_CLR_MALFORMED_MDD_MASK },
    { "VMDHCAM_MULTIHIT", AR_NIC_NAT_ERR_CLR_VMDHCAM_MULTIHIT_BP, AR_NIC_NAT_ERR_CLR_VMDHCAM_MULTIHIT_MASK },
    { "IOMMU_FIFO_UFLW", AR_NIC_NAT_ERR_CLR_IOMMU_FIFO_UFLW_BP, AR_NIC_NAT_ERR_CLR_IOMMU_FIFO_UFLW_MASK },
    { "BYPASS_FIFO_UFLW", AR_NIC_NAT_ERR_CLR_BYPASS_FIFO_UFLW_BP, AR_NIC_NAT_ERR_CLR_BYPASS_FIFO_UFLW_MASK },
    { "BTE_FIFO_UFLW", AR_NIC_NAT_ERR_CLR_BTE_FIFO_UFLW_BP, AR_NIC_NAT_ERR_CLR_BTE_FIFO_UFLW_MASK },
    { "CQ_FIFO_UFLW", AR_NIC_NAT_ERR_CLR_CQ_FIFO_UFLW_BP, AR_NIC_NAT_ERR_CLR_CQ_FIFO_UFLW_MASK },
    { "RAT_FIFO_UFLW", AR_NIC_NAT_ERR_CLR_RAT_FIFO_UFLW_BP, AR_NIC_NAT_ERR_CLR_RAT_FIFO_UFLW_MASK },
    { "IOMMU_FIFO_OFLW", AR_NIC_NAT_ERR_CLR_IOMMU_FIFO_OFLW_BP, AR_NIC_NAT_ERR_CLR_IOMMU_FIFO_OFLW_MASK },
    { "BYPASS_FIFO_OFLW", AR_NIC_NAT_ERR_CLR_BYPASS_FIFO_OFLW_BP, AR_NIC_NAT_ERR_CLR_BYPASS_FIFO_OFLW_MASK },
    { "BTE_FIFO_OFLW", AR_NIC_NAT_ERR_CLR_BTE_FIFO_OFLW_BP, AR_NIC_NAT_ERR_CLR_BTE_FIFO_OFLW_MASK },
    { "CQ_FIFO_OFLW", AR_NIC_NAT_ERR_CLR_CQ_FIFO_OFLW_BP, AR_NIC_NAT_ERR_CLR_CQ_FIFO_OFLW_MASK },
    { "RAT_FIFO_OFLW", AR_NIC_NAT_ERR_CLR_RAT_FIFO_OFLW_BP, AR_NIC_NAT_ERR_CLR_RAT_FIFO_OFLW_MASK },
    { "DIAG_ONLY", AR_NIC_NAT_ERR_CLR_DIAG_ONLY_BP, AR_NIC_NAT_ERR_CLR_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_err_hss_msk_detail[] = {
    { "PTT_SBE", AR_NIC_NAT_ERR_HSS_MSK_PTT_SBE_BP, AR_NIC_NAT_ERR_HSS_MSK_PTT_SBE_MASK },
    { "MDDT_SBE1", AR_NIC_NAT_ERR_HSS_MSK_MDDT_SBE1_BP, AR_NIC_NAT_ERR_HSS_MSK_MDDT_SBE1_MASK },
    { "MDDT_SBE0", AR_NIC_NAT_ERR_HSS_MSK_MDDT_SBE0_BP, AR_NIC_NAT_ERR_HSS_MSK_MDDT_SBE0_MASK },
    { "PTT_MBE", AR_NIC_NAT_ERR_HSS_MSK_PTT_MBE_BP, AR_NIC_NAT_ERR_HSS_MSK_PTT_MBE_MASK },
    { "MDDT_MBE1", AR_NIC_NAT_ERR_HSS_MSK_MDDT_MBE1_BP, AR_NIC_NAT_ERR_HSS_MSK_MDDT_MBE1_MASK },
    { "MDDT_MBE0", AR_NIC_NAT_ERR_HSS_MSK_MDDT_MBE0_BP, AR_NIC_NAT_ERR_HSS_MSK_MDDT_MBE0_MASK },
    { "MALFORMED_MDD", AR_NIC_NAT_ERR_HSS_MSK_MALFORMED_MDD_BP, AR_NIC_NAT_ERR_HSS_MSK_MALFORMED_MDD_MASK },
    { "VMDHCAM_MULTIHIT", AR_NIC_NAT_ERR_HSS_MSK_VMDHCAM_MULTIHIT_BP, AR_NIC_NAT_ERR_HSS_MSK_VMDHCAM_MULTIHIT_MASK },
    { "IOMMU_FIFO_UFLW", AR_NIC_NAT_ERR_HSS_MSK_IOMMU_FIFO_UFLW_BP, AR_NIC_NAT_ERR_HSS_MSK_IOMMU_FIFO_UFLW_MASK },
    { "BYPASS_FIFO_UFLW", AR_NIC_NAT_ERR_HSS_MSK_BYPASS_FIFO_UFLW_BP, AR_NIC_NAT_ERR_HSS_MSK_BYPASS_FIFO_UFLW_MASK },
    { "BTE_FIFO_UFLW", AR_NIC_NAT_ERR_HSS_MSK_BTE_FIFO_UFLW_BP, AR_NIC_NAT_ERR_HSS_MSK_BTE_FIFO_UFLW_MASK },
    { "CQ_FIFO_UFLW", AR_NIC_NAT_ERR_HSS_MSK_CQ_FIFO_UFLW_BP, AR_NIC_NAT_ERR_HSS_MSK_CQ_FIFO_UFLW_MASK },
    { "RAT_FIFO_UFLW", AR_NIC_NAT_ERR_HSS_MSK_RAT_FIFO_UFLW_BP, AR_NIC_NAT_ERR_HSS_MSK_RAT_FIFO_UFLW_MASK },
    { "IOMMU_FIFO_OFLW", AR_NIC_NAT_ERR_HSS_MSK_IOMMU_FIFO_OFLW_BP, AR_NIC_NAT_ERR_HSS_MSK_IOMMU_FIFO_OFLW_MASK },
    { "BYPASS_FIFO_OFLW", AR_NIC_NAT_ERR_HSS_MSK_BYPASS_FIFO_OFLW_BP, AR_NIC_NAT_ERR_HSS_MSK_BYPASS_FIFO_OFLW_MASK },
    { "BTE_FIFO_OFLW", AR_NIC_NAT_ERR_HSS_MSK_BTE_FIFO_OFLW_BP, AR_NIC_NAT_ERR_HSS_MSK_BTE_FIFO_OFLW_MASK },
    { "CQ_FIFO_OFLW", AR_NIC_NAT_ERR_HSS_MSK_CQ_FIFO_OFLW_BP, AR_NIC_NAT_ERR_HSS_MSK_CQ_FIFO_OFLW_MASK },
    { "RAT_FIFO_OFLW", AR_NIC_NAT_ERR_HSS_MSK_RAT_FIFO_OFLW_BP, AR_NIC_NAT_ERR_HSS_MSK_RAT_FIFO_OFLW_MASK },
    { "DIAG_ONLY", AR_NIC_NAT_ERR_HSS_MSK_DIAG_ONLY_BP, AR_NIC_NAT_ERR_HSS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_err_os_msk_detail[] = {
    { "PTT_SBE", AR_NIC_NAT_ERR_OS_MSK_PTT_SBE_BP, AR_NIC_NAT_ERR_OS_MSK_PTT_SBE_MASK },
    { "MDDT_SBE1", AR_NIC_NAT_ERR_OS_MSK_MDDT_SBE1_BP, AR_NIC_NAT_ERR_OS_MSK_MDDT_SBE1_MASK },
    { "MDDT_SBE0", AR_NIC_NAT_ERR_OS_MSK_MDDT_SBE0_BP, AR_NIC_NAT_ERR_OS_MSK_MDDT_SBE0_MASK },
    { "PTT_MBE", AR_NIC_NAT_ERR_OS_MSK_PTT_MBE_BP, AR_NIC_NAT_ERR_OS_MSK_PTT_MBE_MASK },
    { "MDDT_MBE1", AR_NIC_NAT_ERR_OS_MSK_MDDT_MBE1_BP, AR_NIC_NAT_ERR_OS_MSK_MDDT_MBE1_MASK },
    { "MDDT_MBE0", AR_NIC_NAT_ERR_OS_MSK_MDDT_MBE0_BP, AR_NIC_NAT_ERR_OS_MSK_MDDT_MBE0_MASK },
    { "MALFORMED_MDD", AR_NIC_NAT_ERR_OS_MSK_MALFORMED_MDD_BP, AR_NIC_NAT_ERR_OS_MSK_MALFORMED_MDD_MASK },
    { "VMDHCAM_MULTIHIT", AR_NIC_NAT_ERR_OS_MSK_VMDHCAM_MULTIHIT_BP, AR_NIC_NAT_ERR_OS_MSK_VMDHCAM_MULTIHIT_MASK },
    { "IOMMU_FIFO_UFLW", AR_NIC_NAT_ERR_OS_MSK_IOMMU_FIFO_UFLW_BP, AR_NIC_NAT_ERR_OS_MSK_IOMMU_FIFO_UFLW_MASK },
    { "BYPASS_FIFO_UFLW", AR_NIC_NAT_ERR_OS_MSK_BYPASS_FIFO_UFLW_BP, AR_NIC_NAT_ERR_OS_MSK_BYPASS_FIFO_UFLW_MASK },
    { "BTE_FIFO_UFLW", AR_NIC_NAT_ERR_OS_MSK_BTE_FIFO_UFLW_BP, AR_NIC_NAT_ERR_OS_MSK_BTE_FIFO_UFLW_MASK },
    { "CQ_FIFO_UFLW", AR_NIC_NAT_ERR_OS_MSK_CQ_FIFO_UFLW_BP, AR_NIC_NAT_ERR_OS_MSK_CQ_FIFO_UFLW_MASK },
    { "RAT_FIFO_UFLW", AR_NIC_NAT_ERR_OS_MSK_RAT_FIFO_UFLW_BP, AR_NIC_NAT_ERR_OS_MSK_RAT_FIFO_UFLW_MASK },
    { "IOMMU_FIFO_OFLW", AR_NIC_NAT_ERR_OS_MSK_IOMMU_FIFO_OFLW_BP, AR_NIC_NAT_ERR_OS_MSK_IOMMU_FIFO_OFLW_MASK },
    { "BYPASS_FIFO_OFLW", AR_NIC_NAT_ERR_OS_MSK_BYPASS_FIFO_OFLW_BP, AR_NIC_NAT_ERR_OS_MSK_BYPASS_FIFO_OFLW_MASK },
    { "BTE_FIFO_OFLW", AR_NIC_NAT_ERR_OS_MSK_BTE_FIFO_OFLW_BP, AR_NIC_NAT_ERR_OS_MSK_BTE_FIFO_OFLW_MASK },
    { "CQ_FIFO_OFLW", AR_NIC_NAT_ERR_OS_MSK_CQ_FIFO_OFLW_BP, AR_NIC_NAT_ERR_OS_MSK_CQ_FIFO_OFLW_MASK },
    { "RAT_FIFO_OFLW", AR_NIC_NAT_ERR_OS_MSK_RAT_FIFO_OFLW_BP, AR_NIC_NAT_ERR_OS_MSK_RAT_FIFO_OFLW_MASK },
    { "DIAG_ONLY", AR_NIC_NAT_ERR_OS_MSK_DIAG_ONLY_BP, AR_NIC_NAT_ERR_OS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_err_first_flg_detail[] = {
    { "PTT_SBE", AR_NIC_NAT_ERR_FIRST_FLG_PTT_SBE_BP, AR_NIC_NAT_ERR_FIRST_FLG_PTT_SBE_MASK },
    { "MDDT_SBE1", AR_NIC_NAT_ERR_FIRST_FLG_MDDT_SBE1_BP, AR_NIC_NAT_ERR_FIRST_FLG_MDDT_SBE1_MASK },
    { "MDDT_SBE0", AR_NIC_NAT_ERR_FIRST_FLG_MDDT_SBE0_BP, AR_NIC_NAT_ERR_FIRST_FLG_MDDT_SBE0_MASK },
    { "PTT_MBE", AR_NIC_NAT_ERR_FIRST_FLG_PTT_MBE_BP, AR_NIC_NAT_ERR_FIRST_FLG_PTT_MBE_MASK },
    { "MDDT_MBE1", AR_NIC_NAT_ERR_FIRST_FLG_MDDT_MBE1_BP, AR_NIC_NAT_ERR_FIRST_FLG_MDDT_MBE1_MASK },
    { "MDDT_MBE0", AR_NIC_NAT_ERR_FIRST_FLG_MDDT_MBE0_BP, AR_NIC_NAT_ERR_FIRST_FLG_MDDT_MBE0_MASK },
    { "MALFORMED_MDD", AR_NIC_NAT_ERR_FIRST_FLG_MALFORMED_MDD_BP, AR_NIC_NAT_ERR_FIRST_FLG_MALFORMED_MDD_MASK },
    { "VMDHCAM_MULTIHIT", AR_NIC_NAT_ERR_FIRST_FLG_VMDHCAM_MULTIHIT_BP, AR_NIC_NAT_ERR_FIRST_FLG_VMDHCAM_MULTIHIT_MASK },
    { "IOMMU_FIFO_UFLW", AR_NIC_NAT_ERR_FIRST_FLG_IOMMU_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FIRST_FLG_IOMMU_FIFO_UFLW_MASK },
    { "BYPASS_FIFO_UFLW", AR_NIC_NAT_ERR_FIRST_FLG_BYPASS_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FIRST_FLG_BYPASS_FIFO_UFLW_MASK },
    { "BTE_FIFO_UFLW", AR_NIC_NAT_ERR_FIRST_FLG_BTE_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FIRST_FLG_BTE_FIFO_UFLW_MASK },
    { "CQ_FIFO_UFLW", AR_NIC_NAT_ERR_FIRST_FLG_CQ_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FIRST_FLG_CQ_FIFO_UFLW_MASK },
    { "RAT_FIFO_UFLW", AR_NIC_NAT_ERR_FIRST_FLG_RAT_FIFO_UFLW_BP, AR_NIC_NAT_ERR_FIRST_FLG_RAT_FIFO_UFLW_MASK },
    { "IOMMU_FIFO_OFLW", AR_NIC_NAT_ERR_FIRST_FLG_IOMMU_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FIRST_FLG_IOMMU_FIFO_OFLW_MASK },
    { "BYPASS_FIFO_OFLW", AR_NIC_NAT_ERR_FIRST_FLG_BYPASS_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FIRST_FLG_BYPASS_FIFO_OFLW_MASK },
    { "BTE_FIFO_OFLW", AR_NIC_NAT_ERR_FIRST_FLG_BTE_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FIRST_FLG_BTE_FIFO_OFLW_MASK },
    { "CQ_FIFO_OFLW", AR_NIC_NAT_ERR_FIRST_FLG_CQ_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FIRST_FLG_CQ_FIFO_OFLW_MASK },
    { "RAT_FIFO_OFLW", AR_NIC_NAT_ERR_FIRST_FLG_RAT_FIFO_OFLW_BP, AR_NIC_NAT_ERR_FIRST_FLG_RAT_FIFO_OFLW_MASK },
    { "DIAG_ONLY", AR_NIC_NAT_ERR_FIRST_FLG_DIAG_ONLY_BP, AR_NIC_NAT_ERR_FIRST_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_err_info_mddt0_detail[] = {
    { "MBE_ADDRESS", AR_NIC_NAT_ERR_INFO_MDDT0_MBE_ADDRESS_BP, AR_NIC_NAT_ERR_INFO_MDDT0_MBE_ADDRESS_MASK },
    { "MBE_SYNDROME", AR_NIC_NAT_ERR_INFO_MDDT0_MBE_SYNDROME_BP, AR_NIC_NAT_ERR_INFO_MDDT0_MBE_SYNDROME_MASK },
    { "SBE_ADDRESS", AR_NIC_NAT_ERR_INFO_MDDT0_SBE_ADDRESS_BP, AR_NIC_NAT_ERR_INFO_MDDT0_SBE_ADDRESS_MASK },
    { "SBE_SYNDROME", AR_NIC_NAT_ERR_INFO_MDDT0_SBE_SYNDROME_BP, AR_NIC_NAT_ERR_INFO_MDDT0_SBE_SYNDROME_MASK },
    { "MMR_CREATED_ERROR", AR_NIC_NAT_ERR_INFO_MDDT0_MMR_CREATED_ERROR_BP, AR_NIC_NAT_ERR_INFO_MDDT0_MMR_CREATED_ERROR_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_err_info_mddt1_detail[] = {
    { "MBE_ADDRESS", AR_NIC_NAT_ERR_INFO_MDDT1_MBE_ADDRESS_BP, AR_NIC_NAT_ERR_INFO_MDDT1_MBE_ADDRESS_MASK },
    { "MBE_SYNDROME", AR_NIC_NAT_ERR_INFO_MDDT1_MBE_SYNDROME_BP, AR_NIC_NAT_ERR_INFO_MDDT1_MBE_SYNDROME_MASK },
    { "SBE_ADDRESS", AR_NIC_NAT_ERR_INFO_MDDT1_SBE_ADDRESS_BP, AR_NIC_NAT_ERR_INFO_MDDT1_SBE_ADDRESS_MASK },
    { "SBE_SYNDROME", AR_NIC_NAT_ERR_INFO_MDDT1_SBE_SYNDROME_BP, AR_NIC_NAT_ERR_INFO_MDDT1_SBE_SYNDROME_MASK },
    { "MMR_CREATED_ERROR", AR_NIC_NAT_ERR_INFO_MDDT1_MMR_CREATED_ERROR_BP, AR_NIC_NAT_ERR_INFO_MDDT1_MMR_CREATED_ERROR_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_err_info_ptt_detail[] = {
    { "MBE_ADDRESS", AR_NIC_NAT_ERR_INFO_PTT_MBE_ADDRESS_BP, AR_NIC_NAT_ERR_INFO_PTT_MBE_ADDRESS_MASK },
    { "MBE_SYNDROME", AR_NIC_NAT_ERR_INFO_PTT_MBE_SYNDROME_BP, AR_NIC_NAT_ERR_INFO_PTT_MBE_SYNDROME_MASK },
    { "SBE_ADDRESS", AR_NIC_NAT_ERR_INFO_PTT_SBE_ADDRESS_BP, AR_NIC_NAT_ERR_INFO_PTT_SBE_ADDRESS_MASK },
    { "SBE_SYNDROME", AR_NIC_NAT_ERR_INFO_PTT_SBE_SYNDROME_BP, AR_NIC_NAT_ERR_INFO_PTT_SBE_SYNDROME_MASK },
    { "MMR_CREATED_ERROR", AR_NIC_NAT_ERR_INFO_PTT_MMR_CREATED_ERROR_BP, AR_NIC_NAT_ERR_INFO_PTT_MMR_CREATED_ERROR_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_err_info_malformed_mdd_detail[] = {
    { "MDH", AR_NIC_NAT_ERR_INFO_MALFORMED_MDD_MDH_BP, AR_NIC_NAT_ERR_INFO_MALFORMED_MDD_MDH_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_dbg_errinj_detail[] = {
    { "ADDRESS", AR_NIC_NAT_DBG_ERRINJ_ADDRESS_BP, AR_NIC_NAT_DBG_ERRINJ_ADDRESS_MASK },
    { "CHECKBYTE", AR_NIC_NAT_DBG_ERRINJ_CHECKBYTE_BP, AR_NIC_NAT_DBG_ERRINJ_CHECKBYTE_MASK },
    { "RAMSELECT", AR_NIC_NAT_DBG_ERRINJ_RAMSELECT_BP, AR_NIC_NAT_DBG_ERRINJ_RAMSELECT_MASK },
    { "TRIGGERED", AR_NIC_NAT_DBG_ERRINJ_TRIGGERED_BP, AR_NIC_NAT_DBG_ERRINJ_TRIGGERED_MASK },
    { "MODE", AR_NIC_NAT_DBG_ERRINJ_MODE_BP, AR_NIC_NAT_DBG_ERRINJ_MODE_MASK },
    { "ENABLE", AR_NIC_NAT_DBG_ERRINJ_ENABLE_BP, AR_NIC_NAT_DBG_ERRINJ_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_dbg_crdts_detail[] = {
    { "IOMMU_CRDTS", AR_NIC_NAT_DBG_CRDTS_IOMMU_CRDTS_BP, AR_NIC_NAT_DBG_CRDTS_IOMMU_CRDTS_MASK },
    { "BYPASS_CRDTS", AR_NIC_NAT_DBG_CRDTS_BYPASS_CRDTS_BP, AR_NIC_NAT_DBG_CRDTS_BYPASS_CRDTS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_nat_dbg_trans_errs_detail[] = {
    { "ERR15", AR_NIC_NAT_DBG_TRANS_ERRS_ERR15_BP, AR_NIC_NAT_DBG_TRANS_ERRS_ERR15_MASK },
    { "ERR14", AR_NIC_NAT_DBG_TRANS_ERRS_ERR14_BP, AR_NIC_NAT_DBG_TRANS_ERRS_ERR14_MASK },
    { "ERR13", AR_NIC_NAT_DBG_TRANS_ERRS_ERR13_BP, AR_NIC_NAT_DBG_TRANS_ERRS_ERR13_MASK },
    { "ERR12", AR_NIC_NAT_DBG_TRANS_ERRS_ERR12_BP, AR_NIC_NAT_DBG_TRANS_ERRS_ERR12_MASK },
    { "ERR11", AR_NIC_NAT_DBG_TRANS_ERRS_ERR11_BP, AR_NIC_NAT_DBG_TRANS_ERRS_ERR11_MASK },
    { "ERR10", AR_NIC_NAT_DBG_TRANS_ERRS_ERR10_BP, AR_NIC_NAT_DBG_TRANS_ERRS_ERR10_MASK },
    { "ERR9", AR_NIC_NAT_DBG_TRANS_ERRS_ERR9_BP, AR_NIC_NAT_DBG_TRANS_ERRS_ERR9_MASK },
    { "ERR8", AR_NIC_NAT_DBG_TRANS_ERRS_ERR8_BP, AR_NIC_NAT_DBG_TRANS_ERRS_ERR8_MASK },
    { "ERR7", AR_NIC_NAT_DBG_TRANS_ERRS_ERR7_BP, AR_NIC_NAT_DBG_TRANS_ERRS_ERR7_MASK },
    { "ERR6", AR_NIC_NAT_DBG_TRANS_ERRS_ERR6_BP, AR_NIC_NAT_DBG_TRANS_ERRS_ERR6_MASK },
    { "ERR5", AR_NIC_NAT_DBG_TRANS_ERRS_ERR5_BP, AR_NIC_NAT_DBG_TRANS_ERRS_ERR5_MASK },
    { "ERR4", AR_NIC_NAT_DBG_TRANS_ERRS_ERR4_BP, AR_NIC_NAT_DBG_TRANS_ERRS_ERR4_MASK },
    { "ERR3", AR_NIC_NAT_DBG_TRANS_ERRS_ERR3_BP, AR_NIC_NAT_DBG_TRANS_ERRS_ERR3_MASK },
    { "ERR2", AR_NIC_NAT_DBG_TRANS_ERRS_ERR2_BP, AR_NIC_NAT_DBG_TRANS_ERRS_ERR2_MASK },
    { "ERR1", AR_NIC_NAT_DBG_TRANS_ERRS_ERR1_BP, AR_NIC_NAT_DBG_TRANS_ERRS_ERR1_MASK },
    { "ERR0", AR_NIC_NAT_DBG_TRANS_ERRS_ERR0_BP, AR_NIC_NAT_DBG_TRANS_ERRS_ERR0_MASK },
    { NULL, 0, 0 }
};

/*
 *  AR NAT MMR DECLARATIONS
 */
static const generic_mmr_t _ar_nic_nat_nat_mmr_ring_0_hi_nat = {
    "AR_NIC_NAT_NAT_MMR_RING_0_HI_NAT", AR_NIC_NAT_NAT_MMR_RING_0_HI_NAT, 8, 1, _ar_nic_nat_nat_mmr_ring_0_hi_nat_detail
};
static const generic_mmr_t _ar_nic_nat_nat_mmr_ring_0_mid_nat = {
    "AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT", AR_NIC_NAT_NAT_MMR_RING_0_MID_NAT, 8, 1, _ar_nic_nat_nat_mmr_ring_0_mid_nat_detail
};
static const generic_mmr_t _ar_nic_nat_nat_mmr_ring_0_lo_nat = {
    "AR_NIC_NAT_NAT_MMR_RING_0_LO_NAT", AR_NIC_NAT_NAT_MMR_RING_0_LO_NAT, 8, 1, _ar_nic_nat_nat_mmr_ring_0_lo_nat_detail
};
static const generic_mmr_t _ar_nic_nat_err_flg_1_hi_nat = {
    "AR_NIC_NAT_ERR_FLG_1_HI_NAT", AR_NIC_NAT_ERR_FLG_1_HI_NAT, 8, 1, _ar_nic_nat_err_flg_1_hi_nat_detail
};
static const generic_mmr_t _ar_nic_nat_err_flg_1_mid_nat = {
    "AR_NIC_NAT_ERR_FLG_1_MID_NAT", AR_NIC_NAT_ERR_FLG_1_MID_NAT, 8, 1, _ar_nic_nat_err_flg_1_mid_nat_detail
};
static const generic_mmr_t _ar_nic_nat_err_flg_1_lo_nat = {
    "AR_NIC_NAT_ERR_FLG_1_LO_NAT", AR_NIC_NAT_ERR_FLG_1_LO_NAT, 8, 1, _ar_nic_nat_err_flg_1_lo_nat_detail
};
static const generic_mmr_t _ar_nic_nat_nat_rat_req_rsp_2_hi_nat = {
    "AR_NIC_NAT_NAT_RAT_REQ_RSP_2_HI_NAT", AR_NIC_NAT_NAT_RAT_REQ_RSP_2_HI_NAT, 8, 1, _ar_nic_nat_nat_rat_req_rsp_2_hi_nat_detail
};
static const generic_mmr_t _ar_nic_nat_nat_rat_req_rsp_2_mid_nat = {
    "AR_NIC_NAT_NAT_RAT_REQ_RSP_2_MID_NAT", AR_NIC_NAT_NAT_RAT_REQ_RSP_2_MID_NAT, 8, 1, _ar_nic_nat_nat_rat_req_rsp_2_mid_nat_detail
};
static const generic_mmr_t _ar_nic_nat_nat_rat_req_rsp_2_lo_nat = {
    "AR_NIC_NAT_NAT_RAT_REQ_RSP_2_LO_NAT", AR_NIC_NAT_NAT_RAT_REQ_RSP_2_LO_NAT, 8, 1, _ar_nic_nat_nat_rat_req_rsp_2_lo_nat_detail
};
static const generic_mmr_t _ar_nic_nat_nat_cq_req_rsp_3_hi_nat = {
    "AR_NIC_NAT_NAT_CQ_REQ_RSP_3_HI_NAT", AR_NIC_NAT_NAT_CQ_REQ_RSP_3_HI_NAT, 8, 1, _ar_nic_nat_nat_cq_req_rsp_3_hi_nat_detail
};
static const generic_mmr_t _ar_nic_nat_nat_cq_req_rsp_3_mid_nat = {
    "AR_NIC_NAT_NAT_CQ_REQ_RSP_3_MID_NAT", AR_NIC_NAT_NAT_CQ_REQ_RSP_3_MID_NAT, 8, 1, _ar_nic_nat_nat_cq_req_rsp_3_mid_nat_detail
};
static const generic_mmr_t _ar_nic_nat_nat_cq_req_rsp_3_lo_nat = {
    "AR_NIC_NAT_NAT_CQ_REQ_RSP_3_LO_NAT", AR_NIC_NAT_NAT_CQ_REQ_RSP_3_LO_NAT, 8, 1, _ar_nic_nat_nat_cq_req_rsp_3_lo_nat_detail
};
static const generic_mmr_t _ar_nic_nat_nat_bte_req_rsp_4_hi_nat = {
    "AR_NIC_NAT_NAT_BTE_REQ_RSP_4_HI_NAT", AR_NIC_NAT_NAT_BTE_REQ_RSP_4_HI_NAT, 8, 1, _ar_nic_nat_nat_bte_req_rsp_4_hi_nat_detail
};
static const generic_mmr_t _ar_nic_nat_nat_bte_req_rsp_4_mid_nat = {
    "AR_NIC_NAT_NAT_BTE_REQ_RSP_4_MID_NAT", AR_NIC_NAT_NAT_BTE_REQ_RSP_4_MID_NAT, 8, 1, _ar_nic_nat_nat_bte_req_rsp_4_mid_nat_detail
};
static const generic_mmr_t _ar_nic_nat_nat_bte_req_rsp_4_lo_nat = {
    "AR_NIC_NAT_NAT_BTE_REQ_RSP_4_LO_NAT", AR_NIC_NAT_NAT_BTE_REQ_RSP_4_LO_NAT, 8, 1, _ar_nic_nat_nat_bte_req_rsp_4_lo_nat_detail
};
static const generic_mmr_t _ar_nic_nat_nat_power_down_ff_hi_nat = {
    "AR_NIC_NAT_NAT_POWER_DOWN_FF_HI_NAT", AR_NIC_NAT_NAT_POWER_DOWN_FF_HI_NAT, 8, 1, _ar_nic_nat_nat_power_down_ff_hi_nat_detail
};
static const generic_mmr_t _ar_nic_nat_nat_power_down_ff_mid_nat = {
    "AR_NIC_NAT_NAT_POWER_DOWN_FF_MID_NAT", AR_NIC_NAT_NAT_POWER_DOWN_FF_MID_NAT, 8, 1, _ar_nic_nat_nat_power_down_ff_mid_nat_detail
};
static const generic_mmr_t _ar_nic_nat_nat_power_down_ff_lo_nat = {
    "AR_NIC_NAT_NAT_POWER_DOWN_FF_LO_NAT", AR_NIC_NAT_NAT_POWER_DOWN_FF_LO_NAT, 8, 1, _ar_nic_nat_nat_power_down_ff_lo_nat_detail
};
static const generic_mmr_t _ar_nic_nat_cfg_tbl_vmdhcam_0 = {
    "AR_NIC_NAT_CFG_TBL_VMDHCAM_0", AR_NIC_NAT_CFG_TBL_VMDHCAM + 0x0ull, 8, 1, _ar_nic_nat_cfg_tbl_vmdhcam_detail
};
static const generic_mmr_t _ar_nic_nat_cfg_tbl_vmdhcam_1 = {
    "AR_NIC_NAT_CFG_TBL_VMDHCAM_1", AR_NIC_NAT_CFG_TBL_VMDHCAM + 0x8ull, 8, 1, _ar_nic_nat_cfg_tbl_vmdhcam_detail
};
static const generic_mmr_t _ar_nic_nat_cfg_tbl_vmdhcam_2 = {
    "AR_NIC_NAT_CFG_TBL_VMDHCAM_2", AR_NIC_NAT_CFG_TBL_VMDHCAM + 0x10ull, 8, 1, _ar_nic_nat_cfg_tbl_vmdhcam_detail
};
static const generic_mmr_t _ar_nic_nat_cfg_tbl_vmdhcam_3 = {
    "AR_NIC_NAT_CFG_TBL_VMDHCAM_3", AR_NIC_NAT_CFG_TBL_VMDHCAM + 0x18ull, 8, 1, _ar_nic_nat_cfg_tbl_vmdhcam_detail
};
static const generic_mmr_t _ar_nic_nat_cfg_params = {
    "AR_NIC_NAT_CFG_PARAMS", AR_NIC_NAT_CFG_PARAMS, 8, 1, _ar_nic_nat_cfg_params_detail
};
static const generic_mmr_t _ar_nic_nat_err_flg = {
    "AR_NIC_NAT_ERR_FLG", AR_NIC_NAT_ERR_FLG, 8, 1, _ar_nic_nat_err_flg_detail
};
static const generic_mmr_t _ar_nic_nat_err_clr = {
    "AR_NIC_NAT_ERR_CLR", AR_NIC_NAT_ERR_CLR, 8, 1, _ar_nic_nat_err_clr_detail
};
static const generic_mmr_t _ar_nic_nat_err_hss_msk = {
    "AR_NIC_NAT_ERR_HSS_MSK", AR_NIC_NAT_ERR_HSS_MSK, 8, 1, _ar_nic_nat_err_hss_msk_detail
};
static const generic_mmr_t _ar_nic_nat_err_os_msk = {
    "AR_NIC_NAT_ERR_OS_MSK", AR_NIC_NAT_ERR_OS_MSK, 8, 1, _ar_nic_nat_err_os_msk_detail
};
static const generic_mmr_t _ar_nic_nat_err_first_flg = {
    "AR_NIC_NAT_ERR_FIRST_FLG", AR_NIC_NAT_ERR_FIRST_FLG, 8, 1, _ar_nic_nat_err_first_flg_detail
};
static const generic_mmr_t _ar_nic_nat_err_info_mddt0 = {
    "AR_NIC_NAT_ERR_INFO_MDDT0", AR_NIC_NAT_ERR_INFO_MDDT0, 8, 1, _ar_nic_nat_err_info_mddt0_detail
};
static const generic_mmr_t _ar_nic_nat_err_info_mddt1 = {
    "AR_NIC_NAT_ERR_INFO_MDDT1", AR_NIC_NAT_ERR_INFO_MDDT1, 8, 1, _ar_nic_nat_err_info_mddt1_detail
};
static const generic_mmr_t _ar_nic_nat_err_info_ptt = {
    "AR_NIC_NAT_ERR_INFO_PTT", AR_NIC_NAT_ERR_INFO_PTT, 8, 1, _ar_nic_nat_err_info_ptt_detail
};
static const generic_mmr_t _ar_nic_nat_err_info_malformed_mdd = {
    "AR_NIC_NAT_ERR_INFO_MALFORMED_MDD", AR_NIC_NAT_ERR_INFO_MALFORMED_MDD, 8, 1, _ar_nic_nat_err_info_malformed_mdd_detail
};
static const generic_mmr_t _ar_nic_nat_dbg_errinj = {
    "AR_NIC_NAT_DBG_ERRINJ", AR_NIC_NAT_DBG_ERRINJ, 8, 1, _ar_nic_nat_dbg_errinj_detail
};
static const generic_mmr_t _ar_nic_nat_dbg_crdts = {
    "AR_NIC_NAT_DBG_CRDTS", AR_NIC_NAT_DBG_CRDTS, 8, 1, _ar_nic_nat_dbg_crdts_detail
};
static const generic_mmr_t _ar_nic_nat_dbg_trans_errs = {
    "AR_NIC_NAT_DBG_TRANS_ERRS", AR_NIC_NAT_DBG_TRANS_ERRS, 8, 1, _ar_nic_nat_dbg_trans_errs_detail
};

/*
 *  INSTALL AR NAT MMRS
 */
static const generic_mmr_t* _ar_nat_mmrs[] _unused = {
    &_ar_nic_nat_nat_mmr_ring_0_hi_nat,
    &_ar_nic_nat_nat_mmr_ring_0_mid_nat,
    &_ar_nic_nat_nat_mmr_ring_0_lo_nat,
    &_ar_nic_nat_err_flg_1_hi_nat,
    &_ar_nic_nat_err_flg_1_mid_nat,
    &_ar_nic_nat_err_flg_1_lo_nat,
    &_ar_nic_nat_nat_rat_req_rsp_2_hi_nat,
    &_ar_nic_nat_nat_rat_req_rsp_2_mid_nat,
    &_ar_nic_nat_nat_rat_req_rsp_2_lo_nat,
    &_ar_nic_nat_nat_cq_req_rsp_3_hi_nat,
    &_ar_nic_nat_nat_cq_req_rsp_3_mid_nat,
    &_ar_nic_nat_nat_cq_req_rsp_3_lo_nat,
    &_ar_nic_nat_nat_bte_req_rsp_4_hi_nat,
    &_ar_nic_nat_nat_bte_req_rsp_4_mid_nat,
    &_ar_nic_nat_nat_bte_req_rsp_4_lo_nat,
    &_ar_nic_nat_nat_power_down_ff_hi_nat,
    &_ar_nic_nat_nat_power_down_ff_mid_nat,
    &_ar_nic_nat_nat_power_down_ff_lo_nat,
    &_ar_nic_nat_cfg_tbl_vmdhcam_0,
    &_ar_nic_nat_cfg_tbl_vmdhcam_1,
    &_ar_nic_nat_cfg_tbl_vmdhcam_2,
    &_ar_nic_nat_cfg_tbl_vmdhcam_3,
    &_ar_nic_nat_cfg_params,
    &_ar_nic_nat_err_flg,
    &_ar_nic_nat_err_clr,
    &_ar_nic_nat_err_hss_msk,
    &_ar_nic_nat_err_os_msk,
    &_ar_nic_nat_err_first_flg,
    &_ar_nic_nat_err_info_mddt0,
    &_ar_nic_nat_err_info_mddt1,
    &_ar_nic_nat_err_info_ptt,
    &_ar_nic_nat_err_info_malformed_mdd,
    &_ar_nic_nat_dbg_errinj,
    &_ar_nic_nat_dbg_crdts,
    &_ar_nic_nat_dbg_trans_errs,
    NULL
};

#endif
