/******************************************************************************
 * COPYRIGHT CRAY INC. ar_rat_mmrs_h.h
 * FILE: ar_rat_mmrs_h.h
 * Created by v2h.c on Wed Oct  8 14:39:03 2014
 ******************************************************************************/

#ifndef _AR_RAT_MMRS_H_H_
#define _AR_RAT_MMRS_H_H_

#ifdef __GNUC__
#define _unused __attribute__((unused))
#else
#define _unused
#endif

#ifndef _GENERIC_MMRD_T_
#define _GENERIC_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint64_t _mask;		/* Field bit mask */
} generic_mmrd_t;
#endif

#ifndef _ERRCAT_MMRD_T_
#define _ERRCAT_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint32_t _ec;		/* Field error category */
} errcat_mmrd_t;
#endif

#ifndef _GENERIC_MMR_T_
#define _GENERIC_MMR_T_
typedef struct {
	char* _name;		/* MMR name */
	uint64_t _addr;		/* MMR address */
	int _size;		/* Size in bytes of MMR */
	int _depth;		/* Number of MMR instances */
	const generic_mmrd_t *_info;	/* MMR detail */
} generic_mmr_t;
#endif

static const generic_mmr_t* _ar_rat_mmrs[] _unused;	/* RAT Array */

/*
 *  AR RAT MMR DETAIL DECLARATIONS
 */
static const generic_mmrd_t _ar_nic_rat_cfg_link_active_detail[] = {
    { "SIGNAL", AR_NIC_RAT_CFG_LINK_ACTIVE_SIGNAL_BP, AR_NIC_RAT_CFG_LINK_ACTIVE_SIGNAL_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_mmr_ring_0_hi_rat_detail[] = {
    { "UNUSED_145_109", AR_NIC_RAT_RAT_MMR_RING_0_HI_RAT_UNUSED_145_109_BP, AR_NIC_RAT_RAT_MMR_RING_0_HI_RAT_UNUSED_145_109_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_mmr_ring_0_mid_rat_detail[] = {
    { "UNUSED_127_109", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_UNUSED_127_109_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_UNUSED_127_109_MASK },
    { "CNTR_RSP_FLIT", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_RSP_FLIT_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_RSP_FLIT_MASK },
    { "CNTR_REQ_FLIT", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_REQ_FLIT_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_REQ_FLIT_MASK },
    { "CNTR_RSP_INV_CMD", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_RSP_INV_CMD_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_RSP_INV_CMD_MASK },
    { "CNTR_RSP_MALFORMED", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_RSP_MALFORMED_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_RSP_MALFORMED_MASK },
    { "CNTR_REQ_INV_CMD", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_REQ_INV_CMD_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_REQ_INV_CMD_MASK },
    { "CNTR_REQ_MALFORMED", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_REQ_MALFORMED_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_REQ_MALFORMED_MASK },
    { "CNTR_IOMMU_PAYLD_ERR", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_IOMMU_PAYLD_ERR_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_IOMMU_PAYLD_ERR_MASK },
    { "CNTR_IOMMU_DROP_INPUT", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_IOMMU_DROP_INPUT_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_IOMMU_DROP_INPUT_MASK },
    { "CNTR_IOMMU_PARITY_INPUT", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_IOMMU_PARITY_INPUT_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_IOMMU_PARITY_INPUT_MASK },
    { "CNTR_RSP_PAYLD_ERR", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_RSP_PAYLD_ERR_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_RSP_PAYLD_ERR_MASK },
    { "CNTR_RSP_XLAT_ERR", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_RSP_XLAT_ERR_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_RSP_XLAT_ERR_MASK },
    { "CNTR_REQ_PAYLD_ERR", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_REQ_PAYLD_ERR_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_REQ_PAYLD_ERR_MASK },
    { "CNTR_REQ_XLAT_ERR", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_REQ_XLAT_ERR_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_REQ_XLAT_ERR_MASK },
    { "CNTR_RSP_PARITY_OUTPUT", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_RSP_PARITY_OUTPUT_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_RSP_PARITY_OUTPUT_MASK },
    { "CNTR_REQ_PARITY_OUTPUT", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_REQ_PARITY_OUTPUT_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_REQ_PARITY_OUTPUT_MASK },
    { "CNTR_RSP_PARITY_INPUT", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_RSP_PARITY_INPUT_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_RSP_PARITY_INPUT_MASK },
    { "CNTR_REQ_PARITY_INPUT", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_REQ_PARITY_INPUT_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_REQ_PARITY_INPUT_MASK },
    { "CNTR_RSP_STALLED", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_RSP_STALLED_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_RSP_STALLED_MASK },
    { "CNTR_ORB_FLITS", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_ORB_FLITS_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_ORB_FLITS_MASK },
    { "CNTR_ORB_PKTS", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_ORB_PKTS_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_ORB_PKTS_MASK },
    { "CNTR_REQ_STALLED", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_REQ_STALLED_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_REQ_STALLED_MASK },
    { "CNTR_IOMMU_BLOCKED", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_IOMMU_BLOCKED_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_IOMMU_BLOCKED_MASK },
    { "CNTR_IOMMU_FLITS", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_IOMMU_FLITS_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_IOMMU_FLITS_MASK },
    { "CNTR_IOMMU_PKTS", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_IOMMU_PKTS_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_IOMMU_PKTS_MASK },
    { "CNTR_NL_BLOCKED", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_NL_BLOCKED_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_NL_BLOCKED_MASK },
    { "CNTR_NL_FLITS", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_NL_FLITS_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_NL_FLITS_MASK },
    { "CNTR_NL_PKTS", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_NL_PKTS_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_CNTR_NL_PKTS_MASK },
    { "UNUSED_81_49", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_UNUSED_81_49_BP, AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT_UNUSED_81_49_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_mmr_ring_0_lo_rat_detail[] = {
    { "UNUSED_81_49", AR_NIC_RAT_RAT_MMR_RING_0_LO_RAT_UNUSED_81_49_BP, AR_NIC_RAT_RAT_MMR_RING_0_LO_RAT_UNUSED_81_49_MASK },
    { "DBG_RSP_OLDEST_ADDR", AR_NIC_RAT_RAT_MMR_RING_0_LO_RAT_DBG_RSP_OLDEST_ADDR_BP, AR_NIC_RAT_RAT_MMR_RING_0_LO_RAT_DBG_RSP_OLDEST_ADDR_MASK },
    { "DBG_RSP_OLDEST_STALL", AR_NIC_RAT_RAT_MMR_RING_0_LO_RAT_DBG_RSP_OLDEST_STALL_BP, AR_NIC_RAT_RAT_MMR_RING_0_LO_RAT_DBG_RSP_OLDEST_STALL_MASK },
    { "DBG_REQ_OLDEST_ADDR", AR_NIC_RAT_RAT_MMR_RING_0_LO_RAT_DBG_REQ_OLDEST_ADDR_BP, AR_NIC_RAT_RAT_MMR_RING_0_LO_RAT_DBG_REQ_OLDEST_ADDR_MASK },
    { "DBG_REQ_OLDEST_STALL", AR_NIC_RAT_RAT_MMR_RING_0_LO_RAT_DBG_REQ_OLDEST_STALL_BP, AR_NIC_RAT_RAT_MMR_RING_0_LO_RAT_DBG_REQ_OLDEST_STALL_MASK },
    { "R_Q_RAT_PI_OS_IRQ", AR_NIC_RAT_RAT_MMR_RING_0_LO_RAT_R_Q_RAT_PI_OS_IRQ_BP, AR_NIC_RAT_RAT_MMR_RING_0_LO_RAT_R_Q_RAT_PI_OS_IRQ_MASK },
    { "R_Q_RAT_LB_HSS_IRQ", AR_NIC_RAT_RAT_MMR_RING_0_LO_RAT_R_Q_RAT_LB_HSS_IRQ_BP, AR_NIC_RAT_RAT_MMR_RING_0_LO_RAT_R_Q_RAT_LB_HSS_IRQ_MASK },
    { "R_Q_RAT_NETMON_RING_WRACK", AR_NIC_RAT_RAT_MMR_RING_0_LO_RAT_R_Q_RAT_NETMON_RING_WRACK_BP, AR_NIC_RAT_RAT_MMR_RING_0_LO_RAT_R_Q_RAT_NETMON_RING_WRACK_MASK },
    { "R_Q_RAT_NETMON_RING_15_0", AR_NIC_RAT_RAT_MMR_RING_0_LO_RAT_R_Q_RAT_NETMON_RING_15_0_BP, AR_NIC_RAT_RAT_MMR_RING_0_LO_RAT_R_Q_RAT_NETMON_RING_15_0_MASK },
    { "I_NETMON_RAT_RING_15_0", AR_NIC_RAT_RAT_MMR_RING_0_LO_RAT_I_NETMON_RAT_RING_15_0_BP, AR_NIC_RAT_RAT_MMR_RING_0_LO_RAT_I_NETMON_RAT_RING_15_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_err_flg_1_hi_rat_detail[] = {
    { "UNUSED_145_128", AR_NIC_RAT_ERR_FLG_1_HI_RAT_UNUSED_145_128_BP, AR_NIC_RAT_ERR_FLG_1_HI_RAT_UNUSED_145_128_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_err_flg_1_mid_rat_detail[] = {
    { "UNUSED_127_83", AR_NIC_RAT_ERR_FLG_1_MID_RAT_UNUSED_127_83_BP, AR_NIC_RAT_ERR_FLG_1_MID_RAT_UNUSED_127_83_MASK },
    { "RSP_TIMEOUT", AR_NIC_RAT_ERR_FLG_1_MID_RAT_RSP_TIMEOUT_BP, AR_NIC_RAT_ERR_FLG_1_MID_RAT_RSP_TIMEOUT_MASK },
    { "REQ_TIMEOUT", AR_NIC_RAT_ERR_FLG_1_MID_RAT_REQ_TIMEOUT_BP, AR_NIC_RAT_ERR_FLG_1_MID_RAT_REQ_TIMEOUT_MASK },
    { "IOMMU_PAYLD", AR_NIC_RAT_ERR_FLG_1_MID_RAT_IOMMU_PAYLD_BP, AR_NIC_RAT_ERR_FLG_1_MID_RAT_IOMMU_PAYLD_MASK },
    { "IOMMU_DROP", AR_NIC_RAT_ERR_FLG_1_MID_RAT_IOMMU_DROP_BP, AR_NIC_RAT_ERR_FLG_1_MID_RAT_IOMMU_DROP_MASK },
    { "PARITY_IOMMU_INPUT", AR_NIC_RAT_ERR_FLG_1_MID_RAT_PARITY_IOMMU_INPUT_BP, AR_NIC_RAT_ERR_FLG_1_MID_RAT_PARITY_IOMMU_INPUT_MASK },
    { "PARITY_RSP_TRANS", AR_NIC_RAT_ERR_FLG_1_MID_RAT_PARITY_RSP_TRANS_BP, AR_NIC_RAT_ERR_FLG_1_MID_RAT_PARITY_RSP_TRANS_MASK },
    { "PARITY_REQ_TRANS", AR_NIC_RAT_ERR_FLG_1_MID_RAT_PARITY_REQ_TRANS_BP, AR_NIC_RAT_ERR_FLG_1_MID_RAT_PARITY_REQ_TRANS_MASK },
    { "PARITY_RSP_OUTPUT", AR_NIC_RAT_ERR_FLG_1_MID_RAT_PARITY_RSP_OUTPUT_BP, AR_NIC_RAT_ERR_FLG_1_MID_RAT_PARITY_RSP_OUTPUT_MASK },
    { "PARITY_REQ_OUTPUT", AR_NIC_RAT_ERR_FLG_1_MID_RAT_PARITY_REQ_OUTPUT_BP, AR_NIC_RAT_ERR_FLG_1_MID_RAT_PARITY_REQ_OUTPUT_MASK },
    { "PARITY_RSP_INPUT", AR_NIC_RAT_ERR_FLG_1_MID_RAT_PARITY_RSP_INPUT_BP, AR_NIC_RAT_ERR_FLG_1_MID_RAT_PARITY_RSP_INPUT_MASK },
    { "PARITY_REQ_INPUT", AR_NIC_RAT_ERR_FLG_1_MID_RAT_PARITY_REQ_INPUT_BP, AR_NIC_RAT_ERR_FLG_1_MID_RAT_PARITY_REQ_INPUT_MASK },
    { "UFLW_RSP", AR_NIC_RAT_ERR_FLG_1_MID_RAT_UFLW_RSP_BP, AR_NIC_RAT_ERR_FLG_1_MID_RAT_UFLW_RSP_MASK },
    { "UFLW_IOMMU", AR_NIC_RAT_ERR_FLG_1_MID_RAT_UFLW_IOMMU_BP, AR_NIC_RAT_ERR_FLG_1_MID_RAT_UFLW_IOMMU_MASK },
    { "UFLW_REQ", AR_NIC_RAT_ERR_FLG_1_MID_RAT_UFLW_REQ_BP, AR_NIC_RAT_ERR_FLG_1_MID_RAT_UFLW_REQ_MASK },
    { "OFLW_XARB", AR_NIC_RAT_ERR_FLG_1_MID_RAT_OFLW_XARB_BP, AR_NIC_RAT_ERR_FLG_1_MID_RAT_OFLW_XARB_MASK },
    { "OFLW_RSP", AR_NIC_RAT_ERR_FLG_1_MID_RAT_OFLW_RSP_BP, AR_NIC_RAT_ERR_FLG_1_MID_RAT_OFLW_RSP_MASK },
    { "OFLW_IOMMU", AR_NIC_RAT_ERR_FLG_1_MID_RAT_OFLW_IOMMU_BP, AR_NIC_RAT_ERR_FLG_1_MID_RAT_OFLW_IOMMU_MASK },
    { "OFLW_REQ", AR_NIC_RAT_ERR_FLG_1_MID_RAT_OFLW_REQ_BP, AR_NIC_RAT_ERR_FLG_1_MID_RAT_OFLW_REQ_MASK },
    { "DIAG_ONLY", AR_NIC_RAT_ERR_FLG_1_MID_RAT_DIAG_ONLY_BP, AR_NIC_RAT_ERR_FLG_1_MID_RAT_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_err_flg_1_lo_rat_detail[] = {
    { "UNUSED_63_19", AR_NIC_RAT_ERR_FLG_1_LO_RAT_UNUSED_63_19_BP, AR_NIC_RAT_ERR_FLG_1_LO_RAT_UNUSED_63_19_MASK },
    { "I_RSP_TIMEOUT", AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_RSP_TIMEOUT_BP, AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_RSP_TIMEOUT_MASK },
    { "I_REQ_TIMEOUT", AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_REQ_TIMEOUT_BP, AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_REQ_TIMEOUT_MASK },
    { "I_IOMMU_PAYLD", AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_IOMMU_PAYLD_BP, AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_IOMMU_PAYLD_MASK },
    { "I_IOMMU_DROP", AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_IOMMU_DROP_BP, AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_IOMMU_DROP_MASK },
    { "I_PARITY_IOMMU_INPUT", AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_PARITY_IOMMU_INPUT_BP, AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_PARITY_IOMMU_INPUT_MASK },
    { "I_PARITY_RSP_TRANS", AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_PARITY_RSP_TRANS_BP, AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_PARITY_RSP_TRANS_MASK },
    { "I_PARITY_REQ_TRANS", AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_PARITY_REQ_TRANS_BP, AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_PARITY_REQ_TRANS_MASK },
    { "I_PARITY_RSP_OUTPUT", AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_PARITY_RSP_OUTPUT_BP, AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_PARITY_RSP_OUTPUT_MASK },
    { "I_PARITY_REQ_OUTPUT", AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_PARITY_REQ_OUTPUT_BP, AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_PARITY_REQ_OUTPUT_MASK },
    { "I_PARITY_RSP_INPUT", AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_PARITY_RSP_INPUT_BP, AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_PARITY_RSP_INPUT_MASK },
    { "I_PARITY_REQ_INPUT", AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_PARITY_REQ_INPUT_BP, AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_PARITY_REQ_INPUT_MASK },
    { "I_UFLW_RSP", AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_UFLW_RSP_BP, AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_UFLW_RSP_MASK },
    { "I_UFLW_IOMMU", AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_UFLW_IOMMU_BP, AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_UFLW_IOMMU_MASK },
    { "I_UFLW_REQ", AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_UFLW_REQ_BP, AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_UFLW_REQ_MASK },
    { "I_OFLW_XARB", AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_OFLW_XARB_BP, AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_OFLW_XARB_MASK },
    { "I_OFLW_RSP", AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_OFLW_RSP_BP, AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_OFLW_RSP_MASK },
    { "I_OFLW_IOMMU", AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_OFLW_IOMMU_BP, AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_OFLW_IOMMU_MASK },
    { "I_OFLW_REQ", AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_OFLW_REQ_BP, AR_NIC_RAT_ERR_FLG_1_LO_RAT_I_OFLW_REQ_MASK },
    { "UNUSED_0", AR_NIC_RAT_ERR_FLG_1_LO_RAT_UNUSED_0_BP, AR_NIC_RAT_ERR_FLG_1_LO_RAT_UNUSED_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_wc_rsp_flit_2_hi_rat_detail[] = {
    { "R_Q_RAT_WC_RSP_SB", AR_NIC_RAT_RAT_WC_RSP_FLIT_2_HI_RAT_R_Q_RAT_WC_RSP_SB_BP, AR_NIC_RAT_RAT_WC_RSP_FLIT_2_HI_RAT_R_Q_RAT_WC_RSP_SB_MASK },
    { "R_Q_RAT_WC_RSP_FLIT", AR_NIC_RAT_RAT_WC_RSP_FLIT_2_HI_RAT_R_Q_RAT_WC_RSP_FLIT_BP, AR_NIC_RAT_RAT_WC_RSP_FLIT_2_HI_RAT_R_Q_RAT_WC_RSP_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_wc_rsp_flit_2_mid_rat_detail[] = {
    { "R_Q_RAT_WC_RSP_FLIT", AR_NIC_RAT_RAT_WC_RSP_FLIT_2_MID_RAT_R_Q_RAT_WC_RSP_FLIT_BP, AR_NIC_RAT_RAT_WC_RSP_FLIT_2_MID_RAT_R_Q_RAT_WC_RSP_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_wc_rsp_flit_2_lo_rat_detail[] = {
    { "R_Q_RAT_WC_RSP_FLIT", AR_NIC_RAT_RAT_WC_RSP_FLIT_2_LO_RAT_R_Q_RAT_WC_RSP_FLIT_BP, AR_NIC_RAT_RAT_WC_RSP_FLIT_2_LO_RAT_R_Q_RAT_WC_RSP_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_rmt_req_flit_3_hi_rat_detail[] = {
    { "R_Q_RAT_RMT_REQ_SB", AR_NIC_RAT_RAT_RMT_REQ_FLIT_3_HI_RAT_R_Q_RAT_RMT_REQ_SB_BP, AR_NIC_RAT_RAT_RMT_REQ_FLIT_3_HI_RAT_R_Q_RAT_RMT_REQ_SB_MASK },
    { "R_Q_RAT_RMT_REQ_FLIT", AR_NIC_RAT_RAT_RMT_REQ_FLIT_3_HI_RAT_R_Q_RAT_RMT_REQ_FLIT_BP, AR_NIC_RAT_RAT_RMT_REQ_FLIT_3_HI_RAT_R_Q_RAT_RMT_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_rmt_req_flit_3_mid_rat_detail[] = {
    { "R_Q_RAT_RMT_REQ_FLIT", AR_NIC_RAT_RAT_RMT_REQ_FLIT_3_MID_RAT_R_Q_RAT_RMT_REQ_FLIT_BP, AR_NIC_RAT_RAT_RMT_REQ_FLIT_3_MID_RAT_R_Q_RAT_RMT_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_rmt_req_flit_3_lo_rat_detail[] = {
    { "R_Q_RAT_RMT_REQ_FLIT", AR_NIC_RAT_RAT_RMT_REQ_FLIT_3_LO_RAT_R_Q_RAT_RMT_REQ_FLIT_BP, AR_NIC_RAT_RAT_RMT_REQ_FLIT_3_LO_RAT_R_Q_RAT_RMT_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_ce_req_flit_4_hi_rat_detail[] = {
    { "R_Q_RAT_CE_REQ_SB", AR_NIC_RAT_RAT_CE_REQ_FLIT_4_HI_RAT_R_Q_RAT_CE_REQ_SB_BP, AR_NIC_RAT_RAT_CE_REQ_FLIT_4_HI_RAT_R_Q_RAT_CE_REQ_SB_MASK },
    { "R_Q_RAT_CE_REQ_FLIT", AR_NIC_RAT_RAT_CE_REQ_FLIT_4_HI_RAT_R_Q_RAT_CE_REQ_FLIT_BP, AR_NIC_RAT_RAT_CE_REQ_FLIT_4_HI_RAT_R_Q_RAT_CE_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_ce_req_flit_4_mid_rat_detail[] = {
    { "R_Q_RAT_CE_REQ_FLIT", AR_NIC_RAT_RAT_CE_REQ_FLIT_4_MID_RAT_R_Q_RAT_CE_REQ_FLIT_BP, AR_NIC_RAT_RAT_CE_REQ_FLIT_4_MID_RAT_R_Q_RAT_CE_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_ce_req_flit_4_lo_rat_detail[] = {
    { "R_Q_RAT_CE_REQ_FLIT", AR_NIC_RAT_RAT_CE_REQ_FLIT_4_LO_RAT_R_Q_RAT_CE_REQ_FLIT_BP, AR_NIC_RAT_RAT_CE_REQ_FLIT_4_LO_RAT_R_Q_RAT_CE_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_nl_nic_req_flit_5_hi_rat_detail[] = {
    { "Q_NL_NIC_REQ_SB", AR_NIC_RAT_NL_NIC_REQ_FLIT_5_HI_RAT_Q_NL_NIC_REQ_SB_BP, AR_NIC_RAT_NL_NIC_REQ_FLIT_5_HI_RAT_Q_NL_NIC_REQ_SB_MASK },
    { "Q_NL_NIC_REQ_FLIT", AR_NIC_RAT_NL_NIC_REQ_FLIT_5_HI_RAT_Q_NL_NIC_REQ_FLIT_BP, AR_NIC_RAT_NL_NIC_REQ_FLIT_5_HI_RAT_Q_NL_NIC_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_nl_nic_req_flit_5_mid_rat_detail[] = {
    { "Q_NL_NIC_REQ_FLIT", AR_NIC_RAT_NL_NIC_REQ_FLIT_5_MID_RAT_Q_NL_NIC_REQ_FLIT_BP, AR_NIC_RAT_NL_NIC_REQ_FLIT_5_MID_RAT_Q_NL_NIC_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_nl_nic_req_flit_5_lo_rat_detail[] = {
    { "Q_NL_NIC_REQ_FLIT", AR_NIC_RAT_NL_NIC_REQ_FLIT_5_LO_RAT_Q_NL_NIC_REQ_FLIT_BP, AR_NIC_RAT_NL_NIC_REQ_FLIT_5_LO_RAT_Q_NL_NIC_REQ_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_rdy_vecs_6_hi_rat_detail[] = {
    { "UNUSED_145_128", AR_NIC_RAT_RAT_RDY_VECS_6_HI_RAT_UNUSED_145_128_BP, AR_NIC_RAT_RAT_RDY_VECS_6_HI_RAT_UNUSED_145_128_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_rdy_vecs_6_mid_rat_detail[] = {
    { "RDY_PKT_VEC", AR_NIC_RAT_RAT_RDY_VECS_6_MID_RAT_RDY_PKT_VEC_BP, AR_NIC_RAT_RAT_RDY_VECS_6_MID_RAT_RDY_PKT_VEC_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_rdy_vecs_6_lo_rat_detail[] = {
    { "RDY_NAT_VEC", AR_NIC_RAT_RAT_RDY_VECS_6_LO_RAT_RDY_NAT_VEC_BP, AR_NIC_RAT_RAT_RDY_VECS_6_LO_RAT_RDY_NAT_VEC_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_free_vld_vecs_7_hi_rat_detail[] = {
    { "UNUSED_145_128", AR_NIC_RAT_RAT_FREE_VLD_VECS_7_HI_RAT_UNUSED_145_128_BP, AR_NIC_RAT_RAT_FREE_VLD_VECS_7_HI_RAT_UNUSED_145_128_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_free_vld_vecs_7_mid_rat_detail[] = {
    { "VLD_VEC", AR_NIC_RAT_RAT_FREE_VLD_VECS_7_MID_RAT_VLD_VEC_BP, AR_NIC_RAT_RAT_FREE_VLD_VECS_7_MID_RAT_VLD_VEC_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_free_vld_vecs_7_lo_rat_detail[] = {
    { "FREE_VEC", AR_NIC_RAT_RAT_FREE_VLD_VECS_7_LO_RAT_FREE_VEC_BP, AR_NIC_RAT_RAT_FREE_VLD_VECS_7_LO_RAT_FREE_VEC_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_vbuf_class_vecs_8_hi_rat_detail[] = {
    { "UNUSED_145_128", AR_NIC_RAT_RAT_VBUF_CLASS_VECS_8_HI_RAT_UNUSED_145_128_BP, AR_NIC_RAT_RAT_VBUF_CLASS_VECS_8_HI_RAT_UNUSED_145_128_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_vbuf_class_vecs_8_mid_rat_detail[] = {
    { "CLASS_VEC", AR_NIC_RAT_RAT_VBUF_CLASS_VECS_8_MID_RAT_CLASS_VEC_BP, AR_NIC_RAT_RAT_VBUF_CLASS_VECS_8_MID_RAT_CLASS_VEC_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_vbuf_class_vecs_8_lo_rat_detail[] = {
    { "VBUF_VEC", AR_NIC_RAT_RAT_VBUF_CLASS_VECS_8_LO_RAT_VBUF_VEC_BP, AR_NIC_RAT_RAT_VBUF_CLASS_VECS_8_LO_RAT_VBUF_VEC_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_buffer_state_9_hi_rat_detail[] = {
    { "UNUSED_145_98", AR_NIC_RAT_RAT_BUFFER_STATE_9_HI_RAT_UNUSED_145_98_BP, AR_NIC_RAT_RAT_BUFFER_STATE_9_HI_RAT_UNUSED_145_98_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_buffer_state_9_mid_rat_detail[] = {
    { "UNUSED_145_98", AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_UNUSED_145_98_BP, AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_UNUSED_145_98_MASK },
    { "REQ_RD_STALL", AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_REQ_RD_STALL_BP, AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_REQ_RD_STALL_MASK },
    { "REQ_RD_VLD", AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_REQ_RD_VLD_BP, AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_REQ_RD_VLD_MASK },
    { "REQ_RD_ADDR", AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_REQ_RD_ADDR_BP, AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_REQ_RD_ADDR_MASK },
    { "RSP_RD_STALL", AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_RSP_RD_STALL_BP, AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_RSP_RD_STALL_MASK },
    { "RSP_RD_VLD", AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_RSP_RD_VLD_BP, AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_RSP_RD_VLD_MASK },
    { "RSP_RD_ADDR", AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_RSP_RD_ADDR_BP, AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_RSP_RD_ADDR_MASK },
    { "REQ_WR_STALL", AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_REQ_WR_STALL_BP, AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_REQ_WR_STALL_MASK },
    { "REQ_WR_VLD", AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_REQ_WR_VLD_BP, AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_REQ_WR_VLD_MASK },
    { "REQ_WR_VBUF", AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_REQ_WR_VBUF_BP, AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_REQ_WR_VBUF_MASK },
    { "REQ_WR_ADDR", AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_REQ_WR_ADDR_BP, AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_REQ_WR_ADDR_MASK },
    { "RSP_WR_STALL", AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_RSP_WR_STALL_BP, AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_RSP_WR_STALL_MASK },
    { "RSP_WR_VLD", AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_RSP_WR_VLD_BP, AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_RSP_WR_VLD_MASK },
    { "RSP_WR_VBUF", AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_RSP_WR_VBUF_BP, AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_RSP_WR_VBUF_MASK },
    { "RSP_WR_ADDR", AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_RSP_WR_ADDR_BP, AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT_RSP_WR_ADDR_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_buffer_state_9_lo_rat_detail[] = {
    { "ORD_VEC", AR_NIC_RAT_RAT_BUFFER_STATE_9_LO_RAT_ORD_VEC_BP, AR_NIC_RAT_RAT_BUFFER_STATE_9_LO_RAT_ORD_VEC_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_power_down_ff_hi_rat_detail[] = {
    { "POWER_DOWN", AR_NIC_RAT_RAT_POWER_DOWN_FF_HI_RAT_POWER_DOWN_BP, AR_NIC_RAT_RAT_POWER_DOWN_FF_HI_RAT_POWER_DOWN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_power_down_ff_mid_rat_detail[] = {
    { "POWER_DOWN", AR_NIC_RAT_RAT_POWER_DOWN_FF_MID_RAT_POWER_DOWN_BP, AR_NIC_RAT_RAT_POWER_DOWN_FF_MID_RAT_POWER_DOWN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_rat_power_down_ff_lo_rat_detail[] = {
    { "POWER_DOWN", AR_NIC_RAT_RAT_POWER_DOWN_FF_LO_RAT_POWER_DOWN_BP, AR_NIC_RAT_RAT_POWER_DOWN_FF_LO_RAT_POWER_DOWN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_cfg_params_detail[] = {
    { "FORCE_AMO_RR", AR_NIC_RAT_CFG_PARAMS_FORCE_AMO_RR_BP, AR_NIC_RAT_CFG_PARAMS_FORCE_AMO_RR_MASK },
    { "SF_IOMMU", AR_NIC_RAT_CFG_PARAMS_SF_IOMMU_BP, AR_NIC_RAT_CFG_PARAMS_SF_IOMMU_MASK },
    { "SF_ORB", AR_NIC_RAT_CFG_PARAMS_SF_ORB_BP, AR_NIC_RAT_CFG_PARAMS_SF_ORB_MASK },
    { "SF_NL", AR_NIC_RAT_CFG_PARAMS_SF_NL_BP, AR_NIC_RAT_CFG_PARAMS_SF_NL_MASK },
    { "RO_HASHED", AR_NIC_RAT_CFG_PARAMS_RO_HASHED_BP, AR_NIC_RAT_CFG_PARAMS_RO_HASHED_MASK },
    { "RSP_MAX", AR_NIC_RAT_CFG_PARAMS_RSP_MAX_BP, AR_NIC_RAT_CFG_PARAMS_RSP_MAX_MASK },
    { "REQ_MAX", AR_NIC_RAT_CFG_PARAMS_REQ_MAX_BP, AR_NIC_RAT_CFG_PARAMS_REQ_MAX_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_cfg_crdts_detail[] = {
    { "MAX_PKT_SIZE", AR_NIC_RAT_CFG_CRDTS_MAX_PKT_SIZE_BP, AR_NIC_RAT_CFG_CRDTS_MAX_PKT_SIZE_MASK },
    { "WC_CRDTS", AR_NIC_RAT_CFG_CRDTS_WC_CRDTS_BP, AR_NIC_RAT_CFG_CRDTS_WC_CRDTS_MASK },
    { "CE_CRDTS", AR_NIC_RAT_CFG_CRDTS_CE_CRDTS_BP, AR_NIC_RAT_CFG_CRDTS_CE_CRDTS_MASK },
    { "RMT_CRDTS", AR_NIC_RAT_CFG_CRDTS_RMT_CRDTS_BP, AR_NIC_RAT_CFG_CRDTS_RMT_CRDTS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_cfg_timeout_req_detail[] = {
    { "MAX_DURATION", AR_NIC_RAT_CFG_TIMEOUT_REQ_MAX_DURATION_BP, AR_NIC_RAT_CFG_TIMEOUT_REQ_MAX_DURATION_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_cfg_timeout_rsp_detail[] = {
    { "MAX_DURATION", AR_NIC_RAT_CFG_TIMEOUT_RSP_MAX_DURATION_BP, AR_NIC_RAT_CFG_TIMEOUT_RSP_MAX_DURATION_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_err_flg_detail[] = {
    { "RSP_TIMEOUT", AR_NIC_RAT_ERR_FLG_RSP_TIMEOUT_BP, AR_NIC_RAT_ERR_FLG_RSP_TIMEOUT_MASK },
    { "REQ_TIMEOUT", AR_NIC_RAT_ERR_FLG_REQ_TIMEOUT_BP, AR_NIC_RAT_ERR_FLG_REQ_TIMEOUT_MASK },
    { "IOMMU_PAYLD", AR_NIC_RAT_ERR_FLG_IOMMU_PAYLD_BP, AR_NIC_RAT_ERR_FLG_IOMMU_PAYLD_MASK },
    { "IOMMU_DROP", AR_NIC_RAT_ERR_FLG_IOMMU_DROP_BP, AR_NIC_RAT_ERR_FLG_IOMMU_DROP_MASK },
    { "PARITY_IOMMU_INPUT", AR_NIC_RAT_ERR_FLG_PARITY_IOMMU_INPUT_BP, AR_NIC_RAT_ERR_FLG_PARITY_IOMMU_INPUT_MASK },
    { "PARITY_RSP_TRANS", AR_NIC_RAT_ERR_FLG_PARITY_RSP_TRANS_BP, AR_NIC_RAT_ERR_FLG_PARITY_RSP_TRANS_MASK },
    { "PARITY_REQ_TRANS", AR_NIC_RAT_ERR_FLG_PARITY_REQ_TRANS_BP, AR_NIC_RAT_ERR_FLG_PARITY_REQ_TRANS_MASK },
    { "PARITY_RSP_OUTPUT", AR_NIC_RAT_ERR_FLG_PARITY_RSP_OUTPUT_BP, AR_NIC_RAT_ERR_FLG_PARITY_RSP_OUTPUT_MASK },
    { "PARITY_REQ_OUTPUT", AR_NIC_RAT_ERR_FLG_PARITY_REQ_OUTPUT_BP, AR_NIC_RAT_ERR_FLG_PARITY_REQ_OUTPUT_MASK },
    { "PARITY_RSP_INPUT", AR_NIC_RAT_ERR_FLG_PARITY_RSP_INPUT_BP, AR_NIC_RAT_ERR_FLG_PARITY_RSP_INPUT_MASK },
    { "PARITY_REQ_INPUT", AR_NIC_RAT_ERR_FLG_PARITY_REQ_INPUT_BP, AR_NIC_RAT_ERR_FLG_PARITY_REQ_INPUT_MASK },
    { "UFLW_RSP", AR_NIC_RAT_ERR_FLG_UFLW_RSP_BP, AR_NIC_RAT_ERR_FLG_UFLW_RSP_MASK },
    { "UFLW_IOMMU", AR_NIC_RAT_ERR_FLG_UFLW_IOMMU_BP, AR_NIC_RAT_ERR_FLG_UFLW_IOMMU_MASK },
    { "UFLW_REQ", AR_NIC_RAT_ERR_FLG_UFLW_REQ_BP, AR_NIC_RAT_ERR_FLG_UFLW_REQ_MASK },
    { "OFLW_XARB", AR_NIC_RAT_ERR_FLG_OFLW_XARB_BP, AR_NIC_RAT_ERR_FLG_OFLW_XARB_MASK },
    { "OFLW_RSP", AR_NIC_RAT_ERR_FLG_OFLW_RSP_BP, AR_NIC_RAT_ERR_FLG_OFLW_RSP_MASK },
    { "OFLW_IOMMU", AR_NIC_RAT_ERR_FLG_OFLW_IOMMU_BP, AR_NIC_RAT_ERR_FLG_OFLW_IOMMU_MASK },
    { "OFLW_REQ", AR_NIC_RAT_ERR_FLG_OFLW_REQ_BP, AR_NIC_RAT_ERR_FLG_OFLW_REQ_MASK },
    { "DIAG_ONLY", AR_NIC_RAT_ERR_FLG_DIAG_ONLY_BP, AR_NIC_RAT_ERR_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
#ifdef EXCEPTIONS_DEFS
static const errcat_mmrd_t _ar_nic_rat_err_flg_errcat[] = {
    { "RSP_TIMEOUT", AR_NIC_RAT_ERR_FLG_RSP_TIMEOUT_BP, AR_NIC_RAT_ERR_FLG_RSP_TIMEOUT_EC },
    { "REQ_TIMEOUT", AR_NIC_RAT_ERR_FLG_REQ_TIMEOUT_BP, AR_NIC_RAT_ERR_FLG_REQ_TIMEOUT_EC },
    { "IOMMU_PAYLD", AR_NIC_RAT_ERR_FLG_IOMMU_PAYLD_BP, AR_NIC_RAT_ERR_FLG_IOMMU_PAYLD_EC },
    { "IOMMU_DROP", AR_NIC_RAT_ERR_FLG_IOMMU_DROP_BP, AR_NIC_RAT_ERR_FLG_IOMMU_DROP_EC },
    { "PARITY_IOMMU_INPUT", AR_NIC_RAT_ERR_FLG_PARITY_IOMMU_INPUT_BP, AR_NIC_RAT_ERR_FLG_PARITY_IOMMU_INPUT_EC },
    { "PARITY_RSP_TRANS", AR_NIC_RAT_ERR_FLG_PARITY_RSP_TRANS_BP, AR_NIC_RAT_ERR_FLG_PARITY_RSP_TRANS_EC },
    { "PARITY_REQ_TRANS", AR_NIC_RAT_ERR_FLG_PARITY_REQ_TRANS_BP, AR_NIC_RAT_ERR_FLG_PARITY_REQ_TRANS_EC },
    { "PARITY_RSP_OUTPUT", AR_NIC_RAT_ERR_FLG_PARITY_RSP_OUTPUT_BP, AR_NIC_RAT_ERR_FLG_PARITY_RSP_OUTPUT_EC },
    { "PARITY_REQ_OUTPUT", AR_NIC_RAT_ERR_FLG_PARITY_REQ_OUTPUT_BP, AR_NIC_RAT_ERR_FLG_PARITY_REQ_OUTPUT_EC },
    { "PARITY_RSP_INPUT", AR_NIC_RAT_ERR_FLG_PARITY_RSP_INPUT_BP, AR_NIC_RAT_ERR_FLG_PARITY_RSP_INPUT_EC },
    { "PARITY_REQ_INPUT", AR_NIC_RAT_ERR_FLG_PARITY_REQ_INPUT_BP, AR_NIC_RAT_ERR_FLG_PARITY_REQ_INPUT_EC },
    { "UFLW_RSP", AR_NIC_RAT_ERR_FLG_UFLW_RSP_BP, AR_NIC_RAT_ERR_FLG_UFLW_RSP_EC },
    { "UFLW_IOMMU", AR_NIC_RAT_ERR_FLG_UFLW_IOMMU_BP, AR_NIC_RAT_ERR_FLG_UFLW_IOMMU_EC },
    { "UFLW_REQ", AR_NIC_RAT_ERR_FLG_UFLW_REQ_BP, AR_NIC_RAT_ERR_FLG_UFLW_REQ_EC },
    { "OFLW_XARB", AR_NIC_RAT_ERR_FLG_OFLW_XARB_BP, AR_NIC_RAT_ERR_FLG_OFLW_XARB_EC },
    { "OFLW_RSP", AR_NIC_RAT_ERR_FLG_OFLW_RSP_BP, AR_NIC_RAT_ERR_FLG_OFLW_RSP_EC },
    { "OFLW_IOMMU", AR_NIC_RAT_ERR_FLG_OFLW_IOMMU_BP, AR_NIC_RAT_ERR_FLG_OFLW_IOMMU_EC },
    { "OFLW_REQ", AR_NIC_RAT_ERR_FLG_OFLW_REQ_BP, AR_NIC_RAT_ERR_FLG_OFLW_REQ_EC },
    { "DIAG_ONLY", AR_NIC_RAT_ERR_FLG_DIAG_ONLY_BP, AR_NIC_RAT_ERR_FLG_DIAG_ONLY_EC },
    { NULL, 0, 0 }
};
#endif
static const generic_mmrd_t _ar_nic_rat_err_clr_detail[] = {
    { "RSP_TIMEOUT", AR_NIC_RAT_ERR_CLR_RSP_TIMEOUT_BP, AR_NIC_RAT_ERR_CLR_RSP_TIMEOUT_MASK },
    { "REQ_TIMEOUT", AR_NIC_RAT_ERR_CLR_REQ_TIMEOUT_BP, AR_NIC_RAT_ERR_CLR_REQ_TIMEOUT_MASK },
    { "IOMMU_PAYLD", AR_NIC_RAT_ERR_CLR_IOMMU_PAYLD_BP, AR_NIC_RAT_ERR_CLR_IOMMU_PAYLD_MASK },
    { "IOMMU_DROP", AR_NIC_RAT_ERR_CLR_IOMMU_DROP_BP, AR_NIC_RAT_ERR_CLR_IOMMU_DROP_MASK },
    { "PARITY_IOMMU_INPUT", AR_NIC_RAT_ERR_CLR_PARITY_IOMMU_INPUT_BP, AR_NIC_RAT_ERR_CLR_PARITY_IOMMU_INPUT_MASK },
    { "PARITY_RSP_TRANS", AR_NIC_RAT_ERR_CLR_PARITY_RSP_TRANS_BP, AR_NIC_RAT_ERR_CLR_PARITY_RSP_TRANS_MASK },
    { "PARITY_REQ_TRANS", AR_NIC_RAT_ERR_CLR_PARITY_REQ_TRANS_BP, AR_NIC_RAT_ERR_CLR_PARITY_REQ_TRANS_MASK },
    { "PARITY_RSP_OUTPUT", AR_NIC_RAT_ERR_CLR_PARITY_RSP_OUTPUT_BP, AR_NIC_RAT_ERR_CLR_PARITY_RSP_OUTPUT_MASK },
    { "PARITY_REQ_OUTPUT", AR_NIC_RAT_ERR_CLR_PARITY_REQ_OUTPUT_BP, AR_NIC_RAT_ERR_CLR_PARITY_REQ_OUTPUT_MASK },
    { "PARITY_RSP_INPUT", AR_NIC_RAT_ERR_CLR_PARITY_RSP_INPUT_BP, AR_NIC_RAT_ERR_CLR_PARITY_RSP_INPUT_MASK },
    { "PARITY_REQ_INPUT", AR_NIC_RAT_ERR_CLR_PARITY_REQ_INPUT_BP, AR_NIC_RAT_ERR_CLR_PARITY_REQ_INPUT_MASK },
    { "UFLW_RSP", AR_NIC_RAT_ERR_CLR_UFLW_RSP_BP, AR_NIC_RAT_ERR_CLR_UFLW_RSP_MASK },
    { "UFLW_IOMMU", AR_NIC_RAT_ERR_CLR_UFLW_IOMMU_BP, AR_NIC_RAT_ERR_CLR_UFLW_IOMMU_MASK },
    { "UFLW_REQ", AR_NIC_RAT_ERR_CLR_UFLW_REQ_BP, AR_NIC_RAT_ERR_CLR_UFLW_REQ_MASK },
    { "OFLW_XARB", AR_NIC_RAT_ERR_CLR_OFLW_XARB_BP, AR_NIC_RAT_ERR_CLR_OFLW_XARB_MASK },
    { "OFLW_RSP", AR_NIC_RAT_ERR_CLR_OFLW_RSP_BP, AR_NIC_RAT_ERR_CLR_OFLW_RSP_MASK },
    { "OFLW_IOMMU", AR_NIC_RAT_ERR_CLR_OFLW_IOMMU_BP, AR_NIC_RAT_ERR_CLR_OFLW_IOMMU_MASK },
    { "OFLW_REQ", AR_NIC_RAT_ERR_CLR_OFLW_REQ_BP, AR_NIC_RAT_ERR_CLR_OFLW_REQ_MASK },
    { "DIAG_ONLY", AR_NIC_RAT_ERR_CLR_DIAG_ONLY_BP, AR_NIC_RAT_ERR_CLR_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_err_hss_msk_detail[] = {
    { "RSP_TIMEOUT", AR_NIC_RAT_ERR_HSS_MSK_RSP_TIMEOUT_BP, AR_NIC_RAT_ERR_HSS_MSK_RSP_TIMEOUT_MASK },
    { "REQ_TIMEOUT", AR_NIC_RAT_ERR_HSS_MSK_REQ_TIMEOUT_BP, AR_NIC_RAT_ERR_HSS_MSK_REQ_TIMEOUT_MASK },
    { "IOMMU_PAYLD", AR_NIC_RAT_ERR_HSS_MSK_IOMMU_PAYLD_BP, AR_NIC_RAT_ERR_HSS_MSK_IOMMU_PAYLD_MASK },
    { "IOMMU_DROP", AR_NIC_RAT_ERR_HSS_MSK_IOMMU_DROP_BP, AR_NIC_RAT_ERR_HSS_MSK_IOMMU_DROP_MASK },
    { "PARITY_IOMMU_INPUT", AR_NIC_RAT_ERR_HSS_MSK_PARITY_IOMMU_INPUT_BP, AR_NIC_RAT_ERR_HSS_MSK_PARITY_IOMMU_INPUT_MASK },
    { "PARITY_RSP_TRANS", AR_NIC_RAT_ERR_HSS_MSK_PARITY_RSP_TRANS_BP, AR_NIC_RAT_ERR_HSS_MSK_PARITY_RSP_TRANS_MASK },
    { "PARITY_REQ_TRANS", AR_NIC_RAT_ERR_HSS_MSK_PARITY_REQ_TRANS_BP, AR_NIC_RAT_ERR_HSS_MSK_PARITY_REQ_TRANS_MASK },
    { "PARITY_RSP_OUTPUT", AR_NIC_RAT_ERR_HSS_MSK_PARITY_RSP_OUTPUT_BP, AR_NIC_RAT_ERR_HSS_MSK_PARITY_RSP_OUTPUT_MASK },
    { "PARITY_REQ_OUTPUT", AR_NIC_RAT_ERR_HSS_MSK_PARITY_REQ_OUTPUT_BP, AR_NIC_RAT_ERR_HSS_MSK_PARITY_REQ_OUTPUT_MASK },
    { "PARITY_RSP_INPUT", AR_NIC_RAT_ERR_HSS_MSK_PARITY_RSP_INPUT_BP, AR_NIC_RAT_ERR_HSS_MSK_PARITY_RSP_INPUT_MASK },
    { "PARITY_REQ_INPUT", AR_NIC_RAT_ERR_HSS_MSK_PARITY_REQ_INPUT_BP, AR_NIC_RAT_ERR_HSS_MSK_PARITY_REQ_INPUT_MASK },
    { "UFLW_RSP", AR_NIC_RAT_ERR_HSS_MSK_UFLW_RSP_BP, AR_NIC_RAT_ERR_HSS_MSK_UFLW_RSP_MASK },
    { "UFLW_IOMMU", AR_NIC_RAT_ERR_HSS_MSK_UFLW_IOMMU_BP, AR_NIC_RAT_ERR_HSS_MSK_UFLW_IOMMU_MASK },
    { "UFLW_REQ", AR_NIC_RAT_ERR_HSS_MSK_UFLW_REQ_BP, AR_NIC_RAT_ERR_HSS_MSK_UFLW_REQ_MASK },
    { "OFLW_XARB", AR_NIC_RAT_ERR_HSS_MSK_OFLW_XARB_BP, AR_NIC_RAT_ERR_HSS_MSK_OFLW_XARB_MASK },
    { "OFLW_RSP", AR_NIC_RAT_ERR_HSS_MSK_OFLW_RSP_BP, AR_NIC_RAT_ERR_HSS_MSK_OFLW_RSP_MASK },
    { "OFLW_IOMMU", AR_NIC_RAT_ERR_HSS_MSK_OFLW_IOMMU_BP, AR_NIC_RAT_ERR_HSS_MSK_OFLW_IOMMU_MASK },
    { "OFLW_REQ", AR_NIC_RAT_ERR_HSS_MSK_OFLW_REQ_BP, AR_NIC_RAT_ERR_HSS_MSK_OFLW_REQ_MASK },
    { "DIAG_ONLY", AR_NIC_RAT_ERR_HSS_MSK_DIAG_ONLY_BP, AR_NIC_RAT_ERR_HSS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_err_os_msk_detail[] = {
    { "RSP_TIMEOUT", AR_NIC_RAT_ERR_OS_MSK_RSP_TIMEOUT_BP, AR_NIC_RAT_ERR_OS_MSK_RSP_TIMEOUT_MASK },
    { "REQ_TIMEOUT", AR_NIC_RAT_ERR_OS_MSK_REQ_TIMEOUT_BP, AR_NIC_RAT_ERR_OS_MSK_REQ_TIMEOUT_MASK },
    { "IOMMU_PAYLD", AR_NIC_RAT_ERR_OS_MSK_IOMMU_PAYLD_BP, AR_NIC_RAT_ERR_OS_MSK_IOMMU_PAYLD_MASK },
    { "IOMMU_DROP", AR_NIC_RAT_ERR_OS_MSK_IOMMU_DROP_BP, AR_NIC_RAT_ERR_OS_MSK_IOMMU_DROP_MASK },
    { "PARITY_IOMMU_INPUT", AR_NIC_RAT_ERR_OS_MSK_PARITY_IOMMU_INPUT_BP, AR_NIC_RAT_ERR_OS_MSK_PARITY_IOMMU_INPUT_MASK },
    { "PARITY_RSP_TRANS", AR_NIC_RAT_ERR_OS_MSK_PARITY_RSP_TRANS_BP, AR_NIC_RAT_ERR_OS_MSK_PARITY_RSP_TRANS_MASK },
    { "PARITY_REQ_TRANS", AR_NIC_RAT_ERR_OS_MSK_PARITY_REQ_TRANS_BP, AR_NIC_RAT_ERR_OS_MSK_PARITY_REQ_TRANS_MASK },
    { "PARITY_RSP_OUTPUT", AR_NIC_RAT_ERR_OS_MSK_PARITY_RSP_OUTPUT_BP, AR_NIC_RAT_ERR_OS_MSK_PARITY_RSP_OUTPUT_MASK },
    { "PARITY_REQ_OUTPUT", AR_NIC_RAT_ERR_OS_MSK_PARITY_REQ_OUTPUT_BP, AR_NIC_RAT_ERR_OS_MSK_PARITY_REQ_OUTPUT_MASK },
    { "PARITY_RSP_INPUT", AR_NIC_RAT_ERR_OS_MSK_PARITY_RSP_INPUT_BP, AR_NIC_RAT_ERR_OS_MSK_PARITY_RSP_INPUT_MASK },
    { "PARITY_REQ_INPUT", AR_NIC_RAT_ERR_OS_MSK_PARITY_REQ_INPUT_BP, AR_NIC_RAT_ERR_OS_MSK_PARITY_REQ_INPUT_MASK },
    { "UFLW_RSP", AR_NIC_RAT_ERR_OS_MSK_UFLW_RSP_BP, AR_NIC_RAT_ERR_OS_MSK_UFLW_RSP_MASK },
    { "UFLW_IOMMU", AR_NIC_RAT_ERR_OS_MSK_UFLW_IOMMU_BP, AR_NIC_RAT_ERR_OS_MSK_UFLW_IOMMU_MASK },
    { "UFLW_REQ", AR_NIC_RAT_ERR_OS_MSK_UFLW_REQ_BP, AR_NIC_RAT_ERR_OS_MSK_UFLW_REQ_MASK },
    { "OFLW_XARB", AR_NIC_RAT_ERR_OS_MSK_OFLW_XARB_BP, AR_NIC_RAT_ERR_OS_MSK_OFLW_XARB_MASK },
    { "OFLW_RSP", AR_NIC_RAT_ERR_OS_MSK_OFLW_RSP_BP, AR_NIC_RAT_ERR_OS_MSK_OFLW_RSP_MASK },
    { "OFLW_IOMMU", AR_NIC_RAT_ERR_OS_MSK_OFLW_IOMMU_BP, AR_NIC_RAT_ERR_OS_MSK_OFLW_IOMMU_MASK },
    { "OFLW_REQ", AR_NIC_RAT_ERR_OS_MSK_OFLW_REQ_BP, AR_NIC_RAT_ERR_OS_MSK_OFLW_REQ_MASK },
    { "DIAG_ONLY", AR_NIC_RAT_ERR_OS_MSK_DIAG_ONLY_BP, AR_NIC_RAT_ERR_OS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_err_first_flg_detail[] = {
    { "RSP_TIMEOUT", AR_NIC_RAT_ERR_FIRST_FLG_RSP_TIMEOUT_BP, AR_NIC_RAT_ERR_FIRST_FLG_RSP_TIMEOUT_MASK },
    { "REQ_TIMEOUT", AR_NIC_RAT_ERR_FIRST_FLG_REQ_TIMEOUT_BP, AR_NIC_RAT_ERR_FIRST_FLG_REQ_TIMEOUT_MASK },
    { "IOMMU_PAYLD", AR_NIC_RAT_ERR_FIRST_FLG_IOMMU_PAYLD_BP, AR_NIC_RAT_ERR_FIRST_FLG_IOMMU_PAYLD_MASK },
    { "IOMMU_DROP", AR_NIC_RAT_ERR_FIRST_FLG_IOMMU_DROP_BP, AR_NIC_RAT_ERR_FIRST_FLG_IOMMU_DROP_MASK },
    { "PARITY_IOMMU_INPUT", AR_NIC_RAT_ERR_FIRST_FLG_PARITY_IOMMU_INPUT_BP, AR_NIC_RAT_ERR_FIRST_FLG_PARITY_IOMMU_INPUT_MASK },
    { "PARITY_RSP_TRANS", AR_NIC_RAT_ERR_FIRST_FLG_PARITY_RSP_TRANS_BP, AR_NIC_RAT_ERR_FIRST_FLG_PARITY_RSP_TRANS_MASK },
    { "PARITY_REQ_TRANS", AR_NIC_RAT_ERR_FIRST_FLG_PARITY_REQ_TRANS_BP, AR_NIC_RAT_ERR_FIRST_FLG_PARITY_REQ_TRANS_MASK },
    { "PARITY_RSP_OUTPUT", AR_NIC_RAT_ERR_FIRST_FLG_PARITY_RSP_OUTPUT_BP, AR_NIC_RAT_ERR_FIRST_FLG_PARITY_RSP_OUTPUT_MASK },
    { "PARITY_REQ_OUTPUT", AR_NIC_RAT_ERR_FIRST_FLG_PARITY_REQ_OUTPUT_BP, AR_NIC_RAT_ERR_FIRST_FLG_PARITY_REQ_OUTPUT_MASK },
    { "PARITY_RSP_INPUT", AR_NIC_RAT_ERR_FIRST_FLG_PARITY_RSP_INPUT_BP, AR_NIC_RAT_ERR_FIRST_FLG_PARITY_RSP_INPUT_MASK },
    { "PARITY_REQ_INPUT", AR_NIC_RAT_ERR_FIRST_FLG_PARITY_REQ_INPUT_BP, AR_NIC_RAT_ERR_FIRST_FLG_PARITY_REQ_INPUT_MASK },
    { "UFLW_RSP", AR_NIC_RAT_ERR_FIRST_FLG_UFLW_RSP_BP, AR_NIC_RAT_ERR_FIRST_FLG_UFLW_RSP_MASK },
    { "UFLW_IOMMU", AR_NIC_RAT_ERR_FIRST_FLG_UFLW_IOMMU_BP, AR_NIC_RAT_ERR_FIRST_FLG_UFLW_IOMMU_MASK },
    { "UFLW_REQ", AR_NIC_RAT_ERR_FIRST_FLG_UFLW_REQ_BP, AR_NIC_RAT_ERR_FIRST_FLG_UFLW_REQ_MASK },
    { "OFLW_XARB", AR_NIC_RAT_ERR_FIRST_FLG_OFLW_XARB_BP, AR_NIC_RAT_ERR_FIRST_FLG_OFLW_XARB_MASK },
    { "OFLW_RSP", AR_NIC_RAT_ERR_FIRST_FLG_OFLW_RSP_BP, AR_NIC_RAT_ERR_FIRST_FLG_OFLW_RSP_MASK },
    { "OFLW_IOMMU", AR_NIC_RAT_ERR_FIRST_FLG_OFLW_IOMMU_BP, AR_NIC_RAT_ERR_FIRST_FLG_OFLW_IOMMU_MASK },
    { "OFLW_REQ", AR_NIC_RAT_ERR_FIRST_FLG_OFLW_REQ_BP, AR_NIC_RAT_ERR_FIRST_FLG_OFLW_REQ_MASK },
    { "DIAG_ONLY", AR_NIC_RAT_ERR_FIRST_FLG_DIAG_ONLY_BP, AR_NIC_RAT_ERR_FIRST_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_dbg_crdts_detail[] = {
    { "WC_CRDTS", AR_NIC_RAT_DBG_CRDTS_WC_CRDTS_BP, AR_NIC_RAT_DBG_CRDTS_WC_CRDTS_MASK },
    { "CE_CRDTS", AR_NIC_RAT_DBG_CRDTS_CE_CRDTS_BP, AR_NIC_RAT_DBG_CRDTS_CE_CRDTS_MASK },
    { "RMT_CRDTS", AR_NIC_RAT_DBG_CRDTS_RMT_CRDTS_BP, AR_NIC_RAT_DBG_CRDTS_RMT_CRDTS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_dbg_buf_state_detail[] = {
    { "REQ_CNTR", AR_NIC_RAT_DBG_BUF_STATE_REQ_CNTR_BP, AR_NIC_RAT_DBG_BUF_STATE_REQ_CNTR_MASK },
    { "RSP_CNTR", AR_NIC_RAT_DBG_BUF_STATE_RSP_CNTR_BP, AR_NIC_RAT_DBG_BUF_STATE_RSP_CNTR_MASK },
    { "BUF_CNTR", AR_NIC_RAT_DBG_BUF_STATE_BUF_CNTR_BP, AR_NIC_RAT_DBG_BUF_STATE_BUF_CNTR_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_dbg_errinj_bus_detail[] = {
    { "TRIGGERED_RSP", AR_NIC_RAT_DBG_ERRINJ_BUS_TRIGGERED_RSP_BP, AR_NIC_RAT_DBG_ERRINJ_BUS_TRIGGERED_RSP_MASK },
    { "TRIGGERED_IOMMU", AR_NIC_RAT_DBG_ERRINJ_BUS_TRIGGERED_IOMMU_BP, AR_NIC_RAT_DBG_ERRINJ_BUS_TRIGGERED_IOMMU_MASK },
    { "TRIGGERED_REQ", AR_NIC_RAT_DBG_ERRINJ_BUS_TRIGGERED_REQ_BP, AR_NIC_RAT_DBG_ERRINJ_BUS_TRIGGERED_REQ_MASK },
    { "PARITY", AR_NIC_RAT_DBG_ERRINJ_BUS_PARITY_BP, AR_NIC_RAT_DBG_ERRINJ_BUS_PARITY_MASK },
    { "ECC1", AR_NIC_RAT_DBG_ERRINJ_BUS_ECC1_BP, AR_NIC_RAT_DBG_ERRINJ_BUS_ECC1_MASK },
    { "ECC0", AR_NIC_RAT_DBG_ERRINJ_BUS_ECC0_BP, AR_NIC_RAT_DBG_ERRINJ_BUS_ECC0_MASK },
    { "TAIL", AR_NIC_RAT_DBG_ERRINJ_BUS_TAIL_BP, AR_NIC_RAT_DBG_ERRINJ_BUS_TAIL_MASK },
    { "COUNT", AR_NIC_RAT_DBG_ERRINJ_BUS_COUNT_BP, AR_NIC_RAT_DBG_ERRINJ_BUS_COUNT_MASK },
    { "MODE", AR_NIC_RAT_DBG_ERRINJ_BUS_MODE_BP, AR_NIC_RAT_DBG_ERRINJ_BUS_MODE_MASK },
    { "RSP_EN", AR_NIC_RAT_DBG_ERRINJ_BUS_RSP_EN_BP, AR_NIC_RAT_DBG_ERRINJ_BUS_RSP_EN_MASK },
    { "IOMMU_EN", AR_NIC_RAT_DBG_ERRINJ_BUS_IOMMU_EN_BP, AR_NIC_RAT_DBG_ERRINJ_BUS_IOMMU_EN_MASK },
    { "REQ_EN", AR_NIC_RAT_DBG_ERRINJ_BUS_REQ_EN_BP, AR_NIC_RAT_DBG_ERRINJ_BUS_REQ_EN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_dbg_errinj_buf_detail[] = {
    { "RSP_TRIGGERED", AR_NIC_RAT_DBG_ERRINJ_BUF_RSP_TRIGGERED_BP, AR_NIC_RAT_DBG_ERRINJ_BUF_RSP_TRIGGERED_MASK },
    { "REQ_TRIGGERED", AR_NIC_RAT_DBG_ERRINJ_BUF_REQ_TRIGGERED_BP, AR_NIC_RAT_DBG_ERRINJ_BUF_REQ_TRIGGERED_MASK },
    { "HEADER_PARITY", AR_NIC_RAT_DBG_ERRINJ_BUF_HEADER_PARITY_BP, AR_NIC_RAT_DBG_ERRINJ_BUF_HEADER_PARITY_MASK },
    { "TRANSLATION_PARITY", AR_NIC_RAT_DBG_ERRINJ_BUF_TRANSLATION_PARITY_BP, AR_NIC_RAT_DBG_ERRINJ_BUF_TRANSLATION_PARITY_MASK },
    { "MODE", AR_NIC_RAT_DBG_ERRINJ_BUF_MODE_BP, AR_NIC_RAT_DBG_ERRINJ_BUF_MODE_MASK },
    { "RSP_EN", AR_NIC_RAT_DBG_ERRINJ_BUF_RSP_EN_BP, AR_NIC_RAT_DBG_ERRINJ_BUF_RSP_EN_MASK },
    { "REQ_EN", AR_NIC_RAT_DBG_ERRINJ_BUF_REQ_EN_BP, AR_NIC_RAT_DBG_ERRINJ_BUF_REQ_EN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_prf_req_val0_detail[] = {
    { "FLIT_63_0", AR_NIC_RAT_PRF_REQ_VAL0_FLIT_63_0_BP, AR_NIC_RAT_PRF_REQ_VAL0_FLIT_63_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_prf_req_val1_detail[] = {
    { "FLIT_127_64", AR_NIC_RAT_PRF_REQ_VAL1_FLIT_127_64_BP, AR_NIC_RAT_PRF_REQ_VAL1_FLIT_127_64_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_prf_req_val2_detail[] = {
    { "IOMMU_EN", AR_NIC_RAT_PRF_REQ_VAL2_IOMMU_EN_BP, AR_NIC_RAT_PRF_REQ_VAL2_IOMMU_EN_MASK },
    { "NL_EN", AR_NIC_RAT_PRF_REQ_VAL2_NL_EN_BP, AR_NIC_RAT_PRF_REQ_VAL2_NL_EN_MASK },
    { "HDR", AR_NIC_RAT_PRF_REQ_VAL2_HDR_BP, AR_NIC_RAT_PRF_REQ_VAL2_HDR_MASK },
    { "TAIL", AR_NIC_RAT_PRF_REQ_VAL2_TAIL_BP, AR_NIC_RAT_PRF_REQ_VAL2_TAIL_MASK },
    { "FLIT_143_128", AR_NIC_RAT_PRF_REQ_VAL2_FLIT_143_128_BP, AR_NIC_RAT_PRF_REQ_VAL2_FLIT_143_128_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_prf_req_mask0_detail[] = {
    { "FLIT_63_0", AR_NIC_RAT_PRF_REQ_MASK0_FLIT_63_0_BP, AR_NIC_RAT_PRF_REQ_MASK0_FLIT_63_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_prf_req_mask1_detail[] = {
    { "FLIT_127_64", AR_NIC_RAT_PRF_REQ_MASK1_FLIT_127_64_BP, AR_NIC_RAT_PRF_REQ_MASK1_FLIT_127_64_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_prf_req_mask2_detail[] = {
    { "HDR", AR_NIC_RAT_PRF_REQ_MASK2_HDR_BP, AR_NIC_RAT_PRF_REQ_MASK2_HDR_MASK },
    { "TAIL", AR_NIC_RAT_PRF_REQ_MASK2_TAIL_BP, AR_NIC_RAT_PRF_REQ_MASK2_TAIL_MASK },
    { "FLIT_143_128", AR_NIC_RAT_PRF_REQ_MASK2_FLIT_143_128_BP, AR_NIC_RAT_PRF_REQ_MASK2_FLIT_143_128_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_prf_rsp_val0_detail[] = {
    { "FLIT_63_0", AR_NIC_RAT_PRF_RSP_VAL0_FLIT_63_0_BP, AR_NIC_RAT_PRF_RSP_VAL0_FLIT_63_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_prf_rsp_val1_detail[] = {
    { "FLIT_127_64", AR_NIC_RAT_PRF_RSP_VAL1_FLIT_127_64_BP, AR_NIC_RAT_PRF_RSP_VAL1_FLIT_127_64_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_prf_rsp_val2_detail[] = {
    { "EN", AR_NIC_RAT_PRF_RSP_VAL2_EN_BP, AR_NIC_RAT_PRF_RSP_VAL2_EN_MASK },
    { "HDR", AR_NIC_RAT_PRF_RSP_VAL2_HDR_BP, AR_NIC_RAT_PRF_RSP_VAL2_HDR_MASK },
    { "TAIL", AR_NIC_RAT_PRF_RSP_VAL2_TAIL_BP, AR_NIC_RAT_PRF_RSP_VAL2_TAIL_MASK },
    { "FLIT_143_128", AR_NIC_RAT_PRF_RSP_VAL2_FLIT_143_128_BP, AR_NIC_RAT_PRF_RSP_VAL2_FLIT_143_128_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_prf_rsp_mask0_detail[] = {
    { "FLIT_63_0", AR_NIC_RAT_PRF_RSP_MASK0_FLIT_63_0_BP, AR_NIC_RAT_PRF_RSP_MASK0_FLIT_63_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_prf_rsp_mask1_detail[] = {
    { "FLIT_127_64", AR_NIC_RAT_PRF_RSP_MASK1_FLIT_127_64_BP, AR_NIC_RAT_PRF_RSP_MASK1_FLIT_127_64_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_prf_rsp_mask2_detail[] = {
    { "HDR", AR_NIC_RAT_PRF_RSP_MASK2_HDR_BP, AR_NIC_RAT_PRF_RSP_MASK2_HDR_MASK },
    { "TAIL", AR_NIC_RAT_PRF_RSP_MASK2_TAIL_BP, AR_NIC_RAT_PRF_RSP_MASK2_TAIL_MASK },
    { "FLIT_143_128", AR_NIC_RAT_PRF_RSP_MASK2_FLIT_143_128_BP, AR_NIC_RAT_PRF_RSP_MASK2_FLIT_143_128_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_prf_en_detail[] = {
    { "PRF_RSP_DURATION_EN", AR_NIC_RAT_PRF_EN_PRF_RSP_DURATION_EN_BP, AR_NIC_RAT_PRF_EN_PRF_RSP_DURATION_EN_MASK },
    { "PRF_REQ_DURATION_EN", AR_NIC_RAT_PRF_EN_PRF_REQ_DURATION_EN_BP, AR_NIC_RAT_PRF_EN_PRF_REQ_DURATION_EN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_prf_req_stall_duration_detail[] = {
    { "VALUE", AR_NIC_RAT_PRF_REQ_STALL_DURATION_VALUE_BP, AR_NIC_RAT_PRF_REQ_STALL_DURATION_VALUE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_prf_rsp_stall_duration_detail[] = {
    { "VALUE", AR_NIC_RAT_PRF_RSP_STALL_DURATION_VALUE_BP, AR_NIC_RAT_PRF_RSP_STALL_DURATION_VALUE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_rat_prf_req_bytes_rcvd_detail[] = {
    { "BYTES", AR_NIC_RAT_PRF_REQ_BYTES_RCVD_BYTES_BP, AR_NIC_RAT_PRF_REQ_BYTES_RCVD_BYTES_MASK },
    { NULL, 0, 0 }
};

/*
 *  AR RAT MMR DECLARATIONS
 */
static const generic_mmr_t _ar_nic_rat_cfg_link_active = {
    "AR_NIC_RAT_CFG_LINK_ACTIVE", AR_NIC_RAT_CFG_LINK_ACTIVE, 8, 1, _ar_nic_rat_cfg_link_active_detail
};
static const generic_mmr_t _ar_nic_rat_rat_mmr_ring_0_hi_rat = {
    "AR_NIC_RAT_RAT_MMR_RING_0_HI_RAT", AR_NIC_RAT_RAT_MMR_RING_0_HI_RAT, 8, 1, _ar_nic_rat_rat_mmr_ring_0_hi_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_mmr_ring_0_mid_rat = {
    "AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT", AR_NIC_RAT_RAT_MMR_RING_0_MID_RAT, 8, 1, _ar_nic_rat_rat_mmr_ring_0_mid_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_mmr_ring_0_lo_rat = {
    "AR_NIC_RAT_RAT_MMR_RING_0_LO_RAT", AR_NIC_RAT_RAT_MMR_RING_0_LO_RAT, 8, 1, _ar_nic_rat_rat_mmr_ring_0_lo_rat_detail
};
static const generic_mmr_t _ar_nic_rat_err_flg_1_hi_rat = {
    "AR_NIC_RAT_ERR_FLG_1_HI_RAT", AR_NIC_RAT_ERR_FLG_1_HI_RAT, 8, 1, _ar_nic_rat_err_flg_1_hi_rat_detail
};
static const generic_mmr_t _ar_nic_rat_err_flg_1_mid_rat = {
    "AR_NIC_RAT_ERR_FLG_1_MID_RAT", AR_NIC_RAT_ERR_FLG_1_MID_RAT, 8, 1, _ar_nic_rat_err_flg_1_mid_rat_detail
};
static const generic_mmr_t _ar_nic_rat_err_flg_1_lo_rat = {
    "AR_NIC_RAT_ERR_FLG_1_LO_RAT", AR_NIC_RAT_ERR_FLG_1_LO_RAT, 8, 1, _ar_nic_rat_err_flg_1_lo_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_wc_rsp_flit_2_hi_rat = {
    "AR_NIC_RAT_RAT_WC_RSP_FLIT_2_HI_RAT", AR_NIC_RAT_RAT_WC_RSP_FLIT_2_HI_RAT, 8, 1, _ar_nic_rat_rat_wc_rsp_flit_2_hi_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_wc_rsp_flit_2_mid_rat = {
    "AR_NIC_RAT_RAT_WC_RSP_FLIT_2_MID_RAT", AR_NIC_RAT_RAT_WC_RSP_FLIT_2_MID_RAT, 8, 1, _ar_nic_rat_rat_wc_rsp_flit_2_mid_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_wc_rsp_flit_2_lo_rat = {
    "AR_NIC_RAT_RAT_WC_RSP_FLIT_2_LO_RAT", AR_NIC_RAT_RAT_WC_RSP_FLIT_2_LO_RAT, 8, 1, _ar_nic_rat_rat_wc_rsp_flit_2_lo_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_rmt_req_flit_3_hi_rat = {
    "AR_NIC_RAT_RAT_RMT_REQ_FLIT_3_HI_RAT", AR_NIC_RAT_RAT_RMT_REQ_FLIT_3_HI_RAT, 8, 1, _ar_nic_rat_rat_rmt_req_flit_3_hi_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_rmt_req_flit_3_mid_rat = {
    "AR_NIC_RAT_RAT_RMT_REQ_FLIT_3_MID_RAT", AR_NIC_RAT_RAT_RMT_REQ_FLIT_3_MID_RAT, 8, 1, _ar_nic_rat_rat_rmt_req_flit_3_mid_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_rmt_req_flit_3_lo_rat = {
    "AR_NIC_RAT_RAT_RMT_REQ_FLIT_3_LO_RAT", AR_NIC_RAT_RAT_RMT_REQ_FLIT_3_LO_RAT, 8, 1, _ar_nic_rat_rat_rmt_req_flit_3_lo_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_ce_req_flit_4_hi_rat = {
    "AR_NIC_RAT_RAT_CE_REQ_FLIT_4_HI_RAT", AR_NIC_RAT_RAT_CE_REQ_FLIT_4_HI_RAT, 8, 1, _ar_nic_rat_rat_ce_req_flit_4_hi_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_ce_req_flit_4_mid_rat = {
    "AR_NIC_RAT_RAT_CE_REQ_FLIT_4_MID_RAT", AR_NIC_RAT_RAT_CE_REQ_FLIT_4_MID_RAT, 8, 1, _ar_nic_rat_rat_ce_req_flit_4_mid_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_ce_req_flit_4_lo_rat = {
    "AR_NIC_RAT_RAT_CE_REQ_FLIT_4_LO_RAT", AR_NIC_RAT_RAT_CE_REQ_FLIT_4_LO_RAT, 8, 1, _ar_nic_rat_rat_ce_req_flit_4_lo_rat_detail
};
static const generic_mmr_t _ar_nic_rat_nl_nic_req_flit_5_hi_rat = {
    "AR_NIC_RAT_NL_NIC_REQ_FLIT_5_HI_RAT", AR_NIC_RAT_NL_NIC_REQ_FLIT_5_HI_RAT, 8, 1, _ar_nic_rat_nl_nic_req_flit_5_hi_rat_detail
};
static const generic_mmr_t _ar_nic_rat_nl_nic_req_flit_5_mid_rat = {
    "AR_NIC_RAT_NL_NIC_REQ_FLIT_5_MID_RAT", AR_NIC_RAT_NL_NIC_REQ_FLIT_5_MID_RAT, 8, 1, _ar_nic_rat_nl_nic_req_flit_5_mid_rat_detail
};
static const generic_mmr_t _ar_nic_rat_nl_nic_req_flit_5_lo_rat = {
    "AR_NIC_RAT_NL_NIC_REQ_FLIT_5_LO_RAT", AR_NIC_RAT_NL_NIC_REQ_FLIT_5_LO_RAT, 8, 1, _ar_nic_rat_nl_nic_req_flit_5_lo_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_rdy_vecs_6_hi_rat = {
    "AR_NIC_RAT_RAT_RDY_VECS_6_HI_RAT", AR_NIC_RAT_RAT_RDY_VECS_6_HI_RAT, 8, 1, _ar_nic_rat_rat_rdy_vecs_6_hi_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_rdy_vecs_6_mid_rat = {
    "AR_NIC_RAT_RAT_RDY_VECS_6_MID_RAT", AR_NIC_RAT_RAT_RDY_VECS_6_MID_RAT, 8, 1, _ar_nic_rat_rat_rdy_vecs_6_mid_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_rdy_vecs_6_lo_rat = {
    "AR_NIC_RAT_RAT_RDY_VECS_6_LO_RAT", AR_NIC_RAT_RAT_RDY_VECS_6_LO_RAT, 8, 1, _ar_nic_rat_rat_rdy_vecs_6_lo_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_free_vld_vecs_7_hi_rat = {
    "AR_NIC_RAT_RAT_FREE_VLD_VECS_7_HI_RAT", AR_NIC_RAT_RAT_FREE_VLD_VECS_7_HI_RAT, 8, 1, _ar_nic_rat_rat_free_vld_vecs_7_hi_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_free_vld_vecs_7_mid_rat = {
    "AR_NIC_RAT_RAT_FREE_VLD_VECS_7_MID_RAT", AR_NIC_RAT_RAT_FREE_VLD_VECS_7_MID_RAT, 8, 1, _ar_nic_rat_rat_free_vld_vecs_7_mid_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_free_vld_vecs_7_lo_rat = {
    "AR_NIC_RAT_RAT_FREE_VLD_VECS_7_LO_RAT", AR_NIC_RAT_RAT_FREE_VLD_VECS_7_LO_RAT, 8, 1, _ar_nic_rat_rat_free_vld_vecs_7_lo_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_vbuf_class_vecs_8_hi_rat = {
    "AR_NIC_RAT_RAT_VBUF_CLASS_VECS_8_HI_RAT", AR_NIC_RAT_RAT_VBUF_CLASS_VECS_8_HI_RAT, 8, 1, _ar_nic_rat_rat_vbuf_class_vecs_8_hi_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_vbuf_class_vecs_8_mid_rat = {
    "AR_NIC_RAT_RAT_VBUF_CLASS_VECS_8_MID_RAT", AR_NIC_RAT_RAT_VBUF_CLASS_VECS_8_MID_RAT, 8, 1, _ar_nic_rat_rat_vbuf_class_vecs_8_mid_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_vbuf_class_vecs_8_lo_rat = {
    "AR_NIC_RAT_RAT_VBUF_CLASS_VECS_8_LO_RAT", AR_NIC_RAT_RAT_VBUF_CLASS_VECS_8_LO_RAT, 8, 1, _ar_nic_rat_rat_vbuf_class_vecs_8_lo_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_buffer_state_9_hi_rat = {
    "AR_NIC_RAT_RAT_BUFFER_STATE_9_HI_RAT", AR_NIC_RAT_RAT_BUFFER_STATE_9_HI_RAT, 8, 1, _ar_nic_rat_rat_buffer_state_9_hi_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_buffer_state_9_mid_rat = {
    "AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT", AR_NIC_RAT_RAT_BUFFER_STATE_9_MID_RAT, 8, 1, _ar_nic_rat_rat_buffer_state_9_mid_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_buffer_state_9_lo_rat = {
    "AR_NIC_RAT_RAT_BUFFER_STATE_9_LO_RAT", AR_NIC_RAT_RAT_BUFFER_STATE_9_LO_RAT, 8, 1, _ar_nic_rat_rat_buffer_state_9_lo_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_power_down_ff_hi_rat = {
    "AR_NIC_RAT_RAT_POWER_DOWN_FF_HI_RAT", AR_NIC_RAT_RAT_POWER_DOWN_FF_HI_RAT, 8, 1, _ar_nic_rat_rat_power_down_ff_hi_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_power_down_ff_mid_rat = {
    "AR_NIC_RAT_RAT_POWER_DOWN_FF_MID_RAT", AR_NIC_RAT_RAT_POWER_DOWN_FF_MID_RAT, 8, 1, _ar_nic_rat_rat_power_down_ff_mid_rat_detail
};
static const generic_mmr_t _ar_nic_rat_rat_power_down_ff_lo_rat = {
    "AR_NIC_RAT_RAT_POWER_DOWN_FF_LO_RAT", AR_NIC_RAT_RAT_POWER_DOWN_FF_LO_RAT, 8, 1, _ar_nic_rat_rat_power_down_ff_lo_rat_detail
};
static const generic_mmr_t _ar_nic_rat_cfg_params = {
    "AR_NIC_RAT_CFG_PARAMS", AR_NIC_RAT_CFG_PARAMS, 8, 1, _ar_nic_rat_cfg_params_detail
};
static const generic_mmr_t _ar_nic_rat_cfg_crdts = {
    "AR_NIC_RAT_CFG_CRDTS", AR_NIC_RAT_CFG_CRDTS, 8, 1, _ar_nic_rat_cfg_crdts_detail
};
static const generic_mmr_t _ar_nic_rat_cfg_timeout_req = {
    "AR_NIC_RAT_CFG_TIMEOUT_REQ", AR_NIC_RAT_CFG_TIMEOUT_REQ, 8, 1, _ar_nic_rat_cfg_timeout_req_detail
};
static const generic_mmr_t _ar_nic_rat_cfg_timeout_rsp = {
    "AR_NIC_RAT_CFG_TIMEOUT_RSP", AR_NIC_RAT_CFG_TIMEOUT_RSP, 8, 1, _ar_nic_rat_cfg_timeout_rsp_detail
};
static const generic_mmr_t _ar_nic_rat_err_flg = {
    "AR_NIC_RAT_ERR_FLG", AR_NIC_RAT_ERR_FLG, 8, 1, _ar_nic_rat_err_flg_detail
};
static const generic_mmr_t _ar_nic_rat_err_clr = {
    "AR_NIC_RAT_ERR_CLR", AR_NIC_RAT_ERR_CLR, 8, 1, _ar_nic_rat_err_clr_detail
};
static const generic_mmr_t _ar_nic_rat_err_hss_msk = {
    "AR_NIC_RAT_ERR_HSS_MSK", AR_NIC_RAT_ERR_HSS_MSK, 8, 1, _ar_nic_rat_err_hss_msk_detail
};
static const generic_mmr_t _ar_nic_rat_err_os_msk = {
    "AR_NIC_RAT_ERR_OS_MSK", AR_NIC_RAT_ERR_OS_MSK, 8, 1, _ar_nic_rat_err_os_msk_detail
};
static const generic_mmr_t _ar_nic_rat_err_first_flg = {
    "AR_NIC_RAT_ERR_FIRST_FLG", AR_NIC_RAT_ERR_FIRST_FLG, 8, 1, _ar_nic_rat_err_first_flg_detail
};
static const generic_mmr_t _ar_nic_rat_dbg_crdts = {
    "AR_NIC_RAT_DBG_CRDTS", AR_NIC_RAT_DBG_CRDTS, 8, 1, _ar_nic_rat_dbg_crdts_detail
};
static const generic_mmr_t _ar_nic_rat_dbg_buf_state = {
    "AR_NIC_RAT_DBG_BUF_STATE", AR_NIC_RAT_DBG_BUF_STATE, 8, 1, _ar_nic_rat_dbg_buf_state_detail
};
static const generic_mmr_t _ar_nic_rat_dbg_errinj_bus = {
    "AR_NIC_RAT_DBG_ERRINJ_BUS", AR_NIC_RAT_DBG_ERRINJ_BUS, 8, 1, _ar_nic_rat_dbg_errinj_bus_detail
};
static const generic_mmr_t _ar_nic_rat_dbg_errinj_buf = {
    "AR_NIC_RAT_DBG_ERRINJ_BUF", AR_NIC_RAT_DBG_ERRINJ_BUF, 8, 1, _ar_nic_rat_dbg_errinj_buf_detail
};
static const generic_mmr_t _ar_nic_rat_prf_req_val0 = {
    "AR_NIC_RAT_PRF_REQ_VAL0", AR_NIC_RAT_PRF_REQ_VAL0, 8, 1, _ar_nic_rat_prf_req_val0_detail
};
static const generic_mmr_t _ar_nic_rat_prf_req_val1 = {
    "AR_NIC_RAT_PRF_REQ_VAL1", AR_NIC_RAT_PRF_REQ_VAL1, 8, 1, _ar_nic_rat_prf_req_val1_detail
};
static const generic_mmr_t _ar_nic_rat_prf_req_val2 = {
    "AR_NIC_RAT_PRF_REQ_VAL2", AR_NIC_RAT_PRF_REQ_VAL2, 8, 1, _ar_nic_rat_prf_req_val2_detail
};
static const generic_mmr_t _ar_nic_rat_prf_req_mask0 = {
    "AR_NIC_RAT_PRF_REQ_MASK0", AR_NIC_RAT_PRF_REQ_MASK0, 8, 1, _ar_nic_rat_prf_req_mask0_detail
};
static const generic_mmr_t _ar_nic_rat_prf_req_mask1 = {
    "AR_NIC_RAT_PRF_REQ_MASK1", AR_NIC_RAT_PRF_REQ_MASK1, 8, 1, _ar_nic_rat_prf_req_mask1_detail
};
static const generic_mmr_t _ar_nic_rat_prf_req_mask2 = {
    "AR_NIC_RAT_PRF_REQ_MASK2", AR_NIC_RAT_PRF_REQ_MASK2, 8, 1, _ar_nic_rat_prf_req_mask2_detail
};
static const generic_mmr_t _ar_nic_rat_prf_rsp_val0 = {
    "AR_NIC_RAT_PRF_RSP_VAL0", AR_NIC_RAT_PRF_RSP_VAL0, 8, 1, _ar_nic_rat_prf_rsp_val0_detail
};
static const generic_mmr_t _ar_nic_rat_prf_rsp_val1 = {
    "AR_NIC_RAT_PRF_RSP_VAL1", AR_NIC_RAT_PRF_RSP_VAL1, 8, 1, _ar_nic_rat_prf_rsp_val1_detail
};
static const generic_mmr_t _ar_nic_rat_prf_rsp_val2 = {
    "AR_NIC_RAT_PRF_RSP_VAL2", AR_NIC_RAT_PRF_RSP_VAL2, 8, 1, _ar_nic_rat_prf_rsp_val2_detail
};
static const generic_mmr_t _ar_nic_rat_prf_rsp_mask0 = {
    "AR_NIC_RAT_PRF_RSP_MASK0", AR_NIC_RAT_PRF_RSP_MASK0, 8, 1, _ar_nic_rat_prf_rsp_mask0_detail
};
static const generic_mmr_t _ar_nic_rat_prf_rsp_mask1 = {
    "AR_NIC_RAT_PRF_RSP_MASK1", AR_NIC_RAT_PRF_RSP_MASK1, 8, 1, _ar_nic_rat_prf_rsp_mask1_detail
};
static const generic_mmr_t _ar_nic_rat_prf_rsp_mask2 = {
    "AR_NIC_RAT_PRF_RSP_MASK2", AR_NIC_RAT_PRF_RSP_MASK2, 8, 1, _ar_nic_rat_prf_rsp_mask2_detail
};
static const generic_mmr_t _ar_nic_rat_prf_en = {
    "AR_NIC_RAT_PRF_EN", AR_NIC_RAT_PRF_EN, 8, 1, _ar_nic_rat_prf_en_detail
};
static const generic_mmr_t _ar_nic_rat_prf_req_stall_duration = {
    "AR_NIC_RAT_PRF_REQ_STALL_DURATION", AR_NIC_RAT_PRF_REQ_STALL_DURATION, 8, 1, _ar_nic_rat_prf_req_stall_duration_detail
};
static const generic_mmr_t _ar_nic_rat_prf_rsp_stall_duration = {
    "AR_NIC_RAT_PRF_RSP_STALL_DURATION", AR_NIC_RAT_PRF_RSP_STALL_DURATION, 8, 1, _ar_nic_rat_prf_rsp_stall_duration_detail
};
static const generic_mmr_t _ar_nic_rat_prf_req_bytes_rcvd = {
    "AR_NIC_RAT_PRF_REQ_BYTES_RCVD", AR_NIC_RAT_PRF_REQ_BYTES_RCVD, 8, 1, _ar_nic_rat_prf_req_bytes_rcvd_detail
};

/*
 *  INSTALL AR RAT MMRS
 */
static const generic_mmr_t* _ar_rat_mmrs[] _unused = {
    &_ar_nic_rat_cfg_link_active,
    &_ar_nic_rat_rat_mmr_ring_0_hi_rat,
    &_ar_nic_rat_rat_mmr_ring_0_mid_rat,
    &_ar_nic_rat_rat_mmr_ring_0_lo_rat,
    &_ar_nic_rat_err_flg_1_hi_rat,
    &_ar_nic_rat_err_flg_1_mid_rat,
    &_ar_nic_rat_err_flg_1_lo_rat,
    &_ar_nic_rat_rat_wc_rsp_flit_2_hi_rat,
    &_ar_nic_rat_rat_wc_rsp_flit_2_mid_rat,
    &_ar_nic_rat_rat_wc_rsp_flit_2_lo_rat,
    &_ar_nic_rat_rat_rmt_req_flit_3_hi_rat,
    &_ar_nic_rat_rat_rmt_req_flit_3_mid_rat,
    &_ar_nic_rat_rat_rmt_req_flit_3_lo_rat,
    &_ar_nic_rat_rat_ce_req_flit_4_hi_rat,
    &_ar_nic_rat_rat_ce_req_flit_4_mid_rat,
    &_ar_nic_rat_rat_ce_req_flit_4_lo_rat,
    &_ar_nic_rat_nl_nic_req_flit_5_hi_rat,
    &_ar_nic_rat_nl_nic_req_flit_5_mid_rat,
    &_ar_nic_rat_nl_nic_req_flit_5_lo_rat,
    &_ar_nic_rat_rat_rdy_vecs_6_hi_rat,
    &_ar_nic_rat_rat_rdy_vecs_6_mid_rat,
    &_ar_nic_rat_rat_rdy_vecs_6_lo_rat,
    &_ar_nic_rat_rat_free_vld_vecs_7_hi_rat,
    &_ar_nic_rat_rat_free_vld_vecs_7_mid_rat,
    &_ar_nic_rat_rat_free_vld_vecs_7_lo_rat,
    &_ar_nic_rat_rat_vbuf_class_vecs_8_hi_rat,
    &_ar_nic_rat_rat_vbuf_class_vecs_8_mid_rat,
    &_ar_nic_rat_rat_vbuf_class_vecs_8_lo_rat,
    &_ar_nic_rat_rat_buffer_state_9_hi_rat,
    &_ar_nic_rat_rat_buffer_state_9_mid_rat,
    &_ar_nic_rat_rat_buffer_state_9_lo_rat,
    &_ar_nic_rat_rat_power_down_ff_hi_rat,
    &_ar_nic_rat_rat_power_down_ff_mid_rat,
    &_ar_nic_rat_rat_power_down_ff_lo_rat,
    &_ar_nic_rat_cfg_params,
    &_ar_nic_rat_cfg_crdts,
    &_ar_nic_rat_cfg_timeout_req,
    &_ar_nic_rat_cfg_timeout_rsp,
    &_ar_nic_rat_err_flg,
    &_ar_nic_rat_err_clr,
    &_ar_nic_rat_err_hss_msk,
    &_ar_nic_rat_err_os_msk,
    &_ar_nic_rat_err_first_flg,
    &_ar_nic_rat_dbg_crdts,
    &_ar_nic_rat_dbg_buf_state,
    &_ar_nic_rat_dbg_errinj_bus,
    &_ar_nic_rat_dbg_errinj_buf,
    &_ar_nic_rat_prf_req_val0,
    &_ar_nic_rat_prf_req_val1,
    &_ar_nic_rat_prf_req_val2,
    &_ar_nic_rat_prf_req_mask0,
    &_ar_nic_rat_prf_req_mask1,
    &_ar_nic_rat_prf_req_mask2,
    &_ar_nic_rat_prf_rsp_val0,
    &_ar_nic_rat_prf_rsp_val1,
    &_ar_nic_rat_prf_rsp_val2,
    &_ar_nic_rat_prf_rsp_mask0,
    &_ar_nic_rat_prf_rsp_mask1,
    &_ar_nic_rat_prf_rsp_mask2,
    &_ar_nic_rat_prf_en,
    &_ar_nic_rat_prf_req_stall_duration,
    &_ar_nic_rat_prf_rsp_stall_duration,
    &_ar_nic_rat_prf_req_bytes_rcvd,
    NULL
};

#endif
