/******************************************************************************
 * COPYRIGHT CRAY INC. ar_tarb_defs.h
 * FILE: ar_tarb_defs.h
 * Created by v2h.c on Wed Oct  8 14:39:03 2014
 ******************************************************************************/

#ifndef _AR_TARB_DEFS_H_
#define _AR_TARB_DEFS_H_

#define AR_TARB_N_MMRS                                         	21
#define AR_TARB_N_DESCS                                        	0

/*
 *  AR TARB MMR TABLE ADDRESS DEFINES
 */

/*
 *  AR TARB MMR ADDRESS DEFINES
 */
#define AR_NIC_TARB_CFG_PARAMS                                 	(AR_TARB_BASE+0x0000000000ull)
#define AR_NIC_TARB_CFG_PARAMS_SIZE                            	0x0000000008ull
#define AR_NIC_TARB_CFG_PARAMS_LIMIT                           	AR_NIC_TARB_CFG_PARAMS+AR_NIC_TARB_CFG_PARAMS_SIZE-1
#define AR_NIC_TARB_TARB_MMR_RING_0_HI_TARB                    	(AR_TARB_BASE+0x0000000000ull)
#define AR_NIC_TARB_TARB_MMR_RING_0_HI_TARB_SIZE               	0x0000000018ull
#define AR_NIC_TARB_TARB_MMR_RING_0_HI_TARB_LIMIT              	AR_NIC_TARB_TARB_MMR_RING_0_HI_TARB+AR_NIC_TARB_TARB_MMR_RING_0_HI_TARB_SIZE-1
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB                   	(AR_TARB_BASE+0x0000000000ull)
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_SIZE              	0x0000000010ull
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_LIMIT             	AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB+AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_SIZE-1
#define AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB                    	(AR_TARB_BASE+0x0000000000ull)
#define AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_SIZE               	0x0000000008ull
#define AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_LIMIT              	AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB+AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_SIZE-1
#define AR_NIC_TARB_ERR_FLG_1_HI_TARB                          	(AR_TARB_BASE+0x0000000000ull)
#define AR_NIC_TARB_ERR_FLG_1_HI_TARB_SIZE                     	0x0000000018ull
#define AR_NIC_TARB_ERR_FLG_1_HI_TARB_LIMIT                    	AR_NIC_TARB_ERR_FLG_1_HI_TARB+AR_NIC_TARB_ERR_FLG_1_HI_TARB_SIZE-1
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB                         	(AR_TARB_BASE+0x0000000000ull)
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_SIZE                    	0x0000000010ull
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_LIMIT                   	AR_NIC_TARB_ERR_FLG_1_MID_TARB+AR_NIC_TARB_ERR_FLG_1_MID_TARB_SIZE-1
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB                          	(AR_TARB_BASE+0x0000000000ull)
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_SIZE                     	0x0000000008ull
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_LIMIT                    	AR_NIC_TARB_ERR_FLG_1_LO_TARB+AR_NIC_TARB_ERR_FLG_1_LO_TARB_SIZE-1
#define AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB               	(AR_TARB_BASE+0x0000000000ull)
#define AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB_SIZE          	0x0000000018ull
#define AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB_LIMIT         	AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB+AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB_SIZE-1
#define AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_MID_TARB              	(AR_TARB_BASE+0x0000000000ull)
#define AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_MID_TARB_SIZE         	0x0000000010ull
#define AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_MID_TARB_LIMIT        	AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_MID_TARB+AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_MID_TARB_SIZE-1
#define AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_LO_TARB               	(AR_TARB_BASE+0x0000000000ull)
#define AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_LO_TARB_SIZE          	0x0000000008ull
#define AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_LO_TARB_LIMIT         	AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_LO_TARB+AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_LO_TARB_SIZE-1
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_HI_TARB         	(AR_TARB_BASE+0x0000000000ull)
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_HI_TARB_SIZE    	0x0000000018ull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_HI_TARB_LIMIT   	AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_HI_TARB+AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_HI_TARB_SIZE-1
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_MID_TARB        	(AR_TARB_BASE+0x0000000000ull)
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_MID_TARB_SIZE   	0x0000000010ull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_MID_TARB_LIMIT  	AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_MID_TARB+AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_MID_TARB_SIZE-1
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB         	(AR_TARB_BASE+0x0000000000ull)
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_SIZE    	0x0000000008ull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_LIMIT   	AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB+AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_SIZE-1
#define AR_NIC_TARB_CFG_QOS_RATE                               	(AR_TARB_BASE+0x0000000008ull)
#define AR_NIC_TARB_CFG_QOS_RATE_SIZE                          	0x0000000008ull
#define AR_NIC_TARB_CFG_QOS_RATE_LIMIT                         	AR_NIC_TARB_CFG_QOS_RATE+AR_NIC_TARB_CFG_QOS_RATE_SIZE-1
#define AR_NIC_TARB_CFG_QOS_SIZE                               	(AR_TARB_BASE+0x0000000010ull)
#define AR_NIC_TARB_CFG_QOS_SIZE_SIZE                          	0x0000000008ull
#define AR_NIC_TARB_CFG_QOS_SIZE_LIMIT                         	AR_NIC_TARB_CFG_QOS_SIZE+AR_NIC_TARB_CFG_QOS_SIZE_SIZE-1
#define AR_NIC_TARB_DBG_CREDIT                                 	(AR_TARB_BASE+0x0000000080ull)
#define AR_NIC_TARB_DBG_CREDIT_SIZE                            	0x0000000008ull
#define AR_NIC_TARB_DBG_CREDIT_LIMIT                           	AR_NIC_TARB_DBG_CREDIT+AR_NIC_TARB_DBG_CREDIT_SIZE-1
#define AR_NIC_TARB_ERR_FLG                                    	(AR_TARB_BASE+0x0000000100ull)
#define AR_NIC_TARB_ERR_FLG_SIZE                               	0x0000000008ull
#define AR_NIC_TARB_ERR_FLG_LIMIT                              	AR_NIC_TARB_ERR_FLG+AR_NIC_TARB_ERR_FLG_SIZE-1
#define AR_NIC_TARB_ERR_CLR                                    	(AR_TARB_BASE+0x0000000108ull)
#define AR_NIC_TARB_ERR_CLR_SIZE                               	0x0000000008ull
#define AR_NIC_TARB_ERR_CLR_LIMIT                              	AR_NIC_TARB_ERR_CLR+AR_NIC_TARB_ERR_CLR_SIZE-1
#define AR_NIC_TARB_ERR_HSS_MSK                                	(AR_TARB_BASE+0x0000000110ull)
#define AR_NIC_TARB_ERR_HSS_MSK_SIZE                           	0x0000000008ull
#define AR_NIC_TARB_ERR_HSS_MSK_LIMIT                          	AR_NIC_TARB_ERR_HSS_MSK+AR_NIC_TARB_ERR_HSS_MSK_SIZE-1
#define AR_NIC_TARB_ERR_OS_MSK                                 	(AR_TARB_BASE+0x0000000118ull)
#define AR_NIC_TARB_ERR_OS_MSK_SIZE                            	0x0000000008ull
#define AR_NIC_TARB_ERR_OS_MSK_LIMIT                           	AR_NIC_TARB_ERR_OS_MSK+AR_NIC_TARB_ERR_OS_MSK_SIZE-1
#define AR_NIC_TARB_ERR_FIRST_FLG                              	(AR_TARB_BASE+0x0000000120ull)
#define AR_NIC_TARB_ERR_FIRST_FLG_SIZE                         	0x0000000008ull
#define AR_NIC_TARB_ERR_FIRST_FLG_LIMIT                        	AR_NIC_TARB_ERR_FIRST_FLG+AR_NIC_TARB_ERR_FIRST_FLG_SIZE-1

/*
 *  AR_NIC_TARB_CFG_PARAMS DEFINES
 */
#define AR_NIC_TARB_CFG_PARAMS_MAX_PKT_SIZE_MASK                        	0x000000000000f000ull
#define AR_NIC_TARB_CFG_PARAMS_SF_DLA_MASK                              	0x0000000000000400ull
#define AR_NIC_TARB_CFG_PARAMS_SF_BTE_MASK                              	0x0000000000000200ull
#define AR_NIC_TARB_CFG_PARAMS_SF_CE_MASK                               	0x0000000000000100ull
#define AR_NIC_TARB_CFG_PARAMS_SSID_CREDIT_MAX_MASK                     	0x00000000000000ffull
#define AR_NIC_TARB_CFG_PARAMS_MAX_PKT_SIZE_BP                          	12
#define AR_NIC_TARB_CFG_PARAMS_SF_DLA_BP                                	10
#define AR_NIC_TARB_CFG_PARAMS_SF_BTE_BP                                	9
#define AR_NIC_TARB_CFG_PARAMS_SF_CE_BP                                 	8
#define AR_NIC_TARB_CFG_PARAMS_SSID_CREDIT_MAX_BP                       	0
#define AR_NIC_TARB_CFG_PARAMS_MAX_PKT_SIZE_QW                          	0
#define AR_NIC_TARB_CFG_PARAMS_SF_DLA_QW                                	0
#define AR_NIC_TARB_CFG_PARAMS_SF_BTE_QW                                	0
#define AR_NIC_TARB_CFG_PARAMS_SF_CE_QW                                 	0
#define AR_NIC_TARB_CFG_PARAMS_SSID_CREDIT_MAX_QW                       	0
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_NIC_TARB_TARB_MMR_RING_0_HI_TARB DEFINES
 */
#define AR_NIC_TARB_TARB_MMR_RING_0_HI_TARB_UNUSED_145_35_MASK          	0x000000000003ffffull
#define AR_NIC_TARB_TARB_MMR_RING_0_HI_TARB_UNUSED_145_35_BP            	0
#define AR_NIC_TARB_TARB_MMR_RING_0_HI_TARB_UNUSED_145_35_QW            	2
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB DEFINES
 */
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_UNUSED_127_94_MASK         	0xffffffffc0000000ull
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_STALLED_MASK     	0x0000000020000000ull
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_PKTS_MASK        	0x0000000010000000ull
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_FLITS_MASK       	0x0000000008000000ull
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_BLOCKED_MASK      	0x0000000004000000ull
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_PKTS_MASK         	0x0000000002000000ull
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_FLITS_MASK        	0x0000000001000000ull
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_BLOCKED_MASK      	0x0000000000800000ull
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_PKTS_MASK         	0x0000000000400000ull
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_FLITS_MASK        	0x0000000000200000ull
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_BLOCKED_MASK       	0x0000000000100000ull
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_PKTS_MASK          	0x0000000000080000ull
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_FLITS_MASK         	0x0000000000040000ull
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_UNUSED_81_64_MASK          	0x000000000003ffffull
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_UNUSED_127_94_BP           	30
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_STALLED_BP       	29
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_PKTS_BP          	28
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_FLITS_BP         	27
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_BLOCKED_BP        	26
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_PKTS_BP           	25
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_FLITS_BP          	24
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_BLOCKED_BP        	23
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_PKTS_BP           	22
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_FLITS_BP          	21
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_BLOCKED_BP         	20
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_PKTS_BP            	19
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_FLITS_BP           	18
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_UNUSED_81_64_BP            	0
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_UNUSED_127_94_QW           	1
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_STALLED_QW       	1
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_PKTS_QW          	1
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_FLITS_QW         	1
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_BLOCKED_QW        	1
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_PKTS_QW           	1
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_FLITS_QW          	1
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_BLOCKED_QW        	1
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_PKTS_QW           	1
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_FLITS_QW          	1
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_BLOCKED_QW         	1
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_PKTS_QW            	1
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_FLITS_QW           	1
#define AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_UNUSED_81_64_QW            	1
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB DEFINES
 */
#define AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_UNUSED_145_35_MASK          	0xfffffff800000000ull
#define AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_PI_OS_IRQ_MASK     	0x0000000400000000ull
#define AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_LB_HSS_IRQ_MASK    	0x0000000200000000ull
#define AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_NETMON_RING_WRACK_MASK	0x0000000100000000ull
#define AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_NETMON_RING_15_0_MASK	0x00000000ffff0000ull
#define AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_I_NETMON_TARB_RING_15_0_MASK	0x000000000000ffffull
#define AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_UNUSED_145_35_BP            	35
#define AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_PI_OS_IRQ_BP       	34
#define AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_LB_HSS_IRQ_BP      	33
#define AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_NETMON_RING_WRACK_BP	32
#define AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_NETMON_RING_15_0_BP	16
#define AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_I_NETMON_TARB_RING_15_0_BP  	0
#define AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_UNUSED_145_35_QW            	0
#define AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_PI_OS_IRQ_QW       	0
#define AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_LB_HSS_IRQ_QW      	0
#define AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_NETMON_RING_WRACK_QW	0
#define AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_NETMON_RING_15_0_QW	0
#define AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_I_NETMON_TARB_RING_15_0_QW  	0
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_NIC_TARB_ERR_FLG_1_HI_TARB DEFINES
 */
#define AR_NIC_TARB_ERR_FLG_1_HI_TARB_UNUSED_145_71_MASK                	0x000000000003ffffull
#define AR_NIC_TARB_ERR_FLG_1_HI_TARB_UNUSED_145_71_BP                  	0
#define AR_NIC_TARB_ERR_FLG_1_HI_TARB_UNUSED_145_71_QW                  	2
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_NIC_TARB_ERR_FLG_1_MID_TARB DEFINES
 */
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_UNUSED_127_71_MASK               	0xffffffffffffff80ull
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_DLA_UNDERFLOW_MASK               	0x0000000000000040ull
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_BTE_UNDERFLOW_MASK               	0x0000000000000020ull
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_CE_UNDERFLOW_MASK                	0x0000000000000010ull
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_DLA_OVERFLOW_MASK                	0x0000000000000008ull
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_BTE_OVERFLOW_MASK                	0x0000000000000004ull
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_CE_OVERFLOW_MASK                 	0x0000000000000002ull
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_DIAG_ONLY_MASK                   	0x0000000000000001ull
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_UNUSED_127_71_BP                 	7
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_DLA_UNDERFLOW_BP                 	6
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_BTE_UNDERFLOW_BP                 	5
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_CE_UNDERFLOW_BP                  	4
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_DLA_OVERFLOW_BP                  	3
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_BTE_OVERFLOW_BP                  	2
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_CE_OVERFLOW_BP                   	1
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_DIAG_ONLY_BP                     	0
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_UNUSED_127_71_QW                 	1
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_DLA_UNDERFLOW_QW                 	1
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_BTE_UNDERFLOW_QW                 	1
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_CE_UNDERFLOW_QW                  	1
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_DLA_OVERFLOW_QW                  	1
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_BTE_OVERFLOW_QW                  	1
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_CE_OVERFLOW_QW                   	1
#define AR_NIC_TARB_ERR_FLG_1_MID_TARB_DIAG_ONLY_QW                     	1
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_NIC_TARB_ERR_FLG_1_LO_TARB DEFINES
 */
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_UNUSED_63_7_MASK                  	0xffffffffffffff80ull
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_DLA_UNDERFLOW_MASK              	0x0000000000000040ull
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_BTE_UNDERFLOW_MASK              	0x0000000000000020ull
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_CE_UNDERFLOW_MASK               	0x0000000000000010ull
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_DLA_OVERFLOW_MASK               	0x0000000000000008ull
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_BTE_OVERFLOW_MASK               	0x0000000000000004ull
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_CE_OVERFLOW_MASK                	0x0000000000000002ull
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_UNUSED_0_MASK                     	0x0000000000000001ull
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_UNUSED_63_7_BP                    	7
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_DLA_UNDERFLOW_BP                	6
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_BTE_UNDERFLOW_BP                	5
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_CE_UNDERFLOW_BP                 	4
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_DLA_OVERFLOW_BP                 	3
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_BTE_OVERFLOW_BP                 	2
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_CE_OVERFLOW_BP                  	1
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_UNUSED_0_BP                       	0
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_UNUSED_63_7_QW                    	0
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_DLA_UNDERFLOW_QW                	0
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_BTE_UNDERFLOW_QW                	0
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_CE_UNDERFLOW_QW                 	0
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_DLA_OVERFLOW_QW                 	0
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_BTE_OVERFLOW_QW                 	0
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_CE_OVERFLOW_QW                  	0
#define AR_NIC_TARB_ERR_FLG_1_LO_TARB_UNUSED_0_QW                       	0
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB DEFINES
 */
#define AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB_TARB_SSID_REQ_SB_MASK  	0x0000000000030000ull
#define AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB_TARB_SSID_REQ_FLIT_MASK	0x000000000000ffffull
#define AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB_TARB_SSID_REQ_SB_BP    	16
#define AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB_TARB_SSID_REQ_FLIT_BP  	0
#define AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB_TARB_SSID_REQ_SB_QW    	2
#define AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB_TARB_SSID_REQ_FLIT_QW  	2
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_MID_TARB DEFINES
 */
#define AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_MID_TARB_TARB_SSID_REQ_FLIT_MASK	0xffffffffffffffffull
#define AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_MID_TARB_TARB_SSID_REQ_FLIT_BP 	0
#define AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_MID_TARB_TARB_SSID_REQ_FLIT_QW 	1
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_LO_TARB DEFINES
 */
#define AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_LO_TARB_TARB_SSID_REQ_FLIT_MASK	0xffffffffffffffffull
#define AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_LO_TARB_TARB_SSID_REQ_FLIT_BP  	0
#define AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_LO_TARB_TARB_SSID_REQ_FLIT_QW  	0
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_HI_TARB DEFINES
 */
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_HI_TARB_UNUSED_145_37_MASK	0x000000000003ffffull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_HI_TARB_UNUSED_145_37_BP 	0
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_HI_TARB_UNUSED_145_37_QW 	2
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_MID_TARB DEFINES
 */
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_MID_TARB_UNUSED_145_37_MASK	0xffffffffffffffffull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_MID_TARB_UNUSED_145_37_BP	0
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_MID_TARB_UNUSED_145_37_QW	1
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB DEFINES
 */
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_UNUSED_145_37_MASK	0xffffffe000000000ull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_I_SSID_TARB_REQ_ACK_MASK	0x0000001000000000ull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_35_33_MASK	0x0000000e00000000ull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_DLA_REQ_ACK_MASK	0x0000000100000000ull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_31_29_MASK	0x00000000e0000000ull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_BTE_REQ_ACK_MASK	0x0000000010000000ull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_27_25_MASK	0x000000000e000000ull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_CE_REQ_ACK_MASK	0x0000000001000000ull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_TARB_CRDTS_MASK  	0x0000000000ff0000ull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_TARB_CRDTS_EMPTY_MASK	0x0000000000008000ull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_I_DLA_TARB_DL_REC_MASK	0x0000000000004000ull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_QOS_VLD_MASK     	0x0000000000002000ull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_HOLD_MASK    	0x0000000000001000ull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_11_MASK 	0x0000000000000800ull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_ACK_MASK     	0x0000000000000700ull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_7_MASK  	0x0000000000000080ull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_GNT_MASK     	0x0000000000000070ull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_3_MASK  	0x0000000000000008ull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_REQ_MASK     	0x0000000000000007ull
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_UNUSED_145_37_BP 	37
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_I_SSID_TARB_REQ_ACK_BP	36
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_35_33_BP	33
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_DLA_REQ_ACK_BP	32
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_31_29_BP	29
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_BTE_REQ_ACK_BP	28
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_27_25_BP	25
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_CE_REQ_ACK_BP	24
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_TARB_CRDTS_BP    	16
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_TARB_CRDTS_EMPTY_BP	15
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_I_DLA_TARB_DL_REC_BP	14
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_QOS_VLD_BP       	13
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_HOLD_BP      	12
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_11_BP   	11
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_ACK_BP       	8
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_7_BP    	7
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_GNT_BP       	4
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_3_BP    	3
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_REQ_BP       	0
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_UNUSED_145_37_QW 	0
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_I_SSID_TARB_REQ_ACK_QW	0
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_35_33_QW	0
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_DLA_REQ_ACK_QW	0
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_31_29_QW	0
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_BTE_REQ_ACK_QW	0
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_27_25_QW	0
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_CE_REQ_ACK_QW	0
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_TARB_CRDTS_QW    	0
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_TARB_CRDTS_EMPTY_QW	0
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_I_DLA_TARB_DL_REC_QW	0
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_QOS_VLD_QW       	0
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_HOLD_QW      	0
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_11_QW   	0
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_ACK_QW       	0
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_7_QW    	0
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_GNT_QW       	0
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_3_QW    	0
#define AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_REQ_QW       	0
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_NIC_TARB_CFG_QOS_RATE DEFINES
 */
#define AR_NIC_TARB_CFG_QOS_RATE_B2_RATE_MASK                           	0xffffffff00000000ull
#define AR_NIC_TARB_CFG_QOS_RATE_B1_RATE_MASK                           	0x00000000ffffffffull
#define AR_NIC_TARB_CFG_QOS_RATE_B2_RATE_BP                             	32
#define AR_NIC_TARB_CFG_QOS_RATE_B1_RATE_BP                             	0
#define AR_NIC_TARB_CFG_QOS_RATE_B2_RATE_QW                             	0
#define AR_NIC_TARB_CFG_QOS_RATE_B1_RATE_QW                             	0
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_NIC_TARB_CFG_QOS_SIZE DEFINES
 */
#define AR_NIC_TARB_CFG_QOS_SIZE_B2_SIZE_MASK                           	0x0000ffff00000000ull
#define AR_NIC_TARB_CFG_QOS_SIZE_B1_SIZE_MASK                           	0x00000000ffffffffull
#define AR_NIC_TARB_CFG_QOS_SIZE_B2_SIZE_BP                             	32
#define AR_NIC_TARB_CFG_QOS_SIZE_B1_SIZE_BP                             	0
#define AR_NIC_TARB_CFG_QOS_SIZE_B2_SIZE_QW                             	0
#define AR_NIC_TARB_CFG_QOS_SIZE_B1_SIZE_QW                             	0
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_NIC_TARB_DBG_CREDIT DEFINES
 */
#define AR_NIC_TARB_DBG_CREDIT_SSID_CREDIT_CNT_MASK                     	0x00000000000000ffull
#define AR_NIC_TARB_DBG_CREDIT_SSID_CREDIT_CNT_BP                       	0
#define AR_NIC_TARB_DBG_CREDIT_SSID_CREDIT_CNT_QW                       	0
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_NIC_TARB_ERR_FLG DEFINES
 */
#define AR_NIC_TARB_ERR_FLG_DLA_UNDERFLOW_MASK                          	0x0000000000000040ull
#define AR_NIC_TARB_ERR_FLG_BTE_UNDERFLOW_MASK                          	0x0000000000000020ull
#define AR_NIC_TARB_ERR_FLG_CE_UNDERFLOW_MASK                           	0x0000000000000010ull
#define AR_NIC_TARB_ERR_FLG_DLA_OVERFLOW_MASK                           	0x0000000000000008ull
#define AR_NIC_TARB_ERR_FLG_BTE_OVERFLOW_MASK                           	0x0000000000000004ull
#define AR_NIC_TARB_ERR_FLG_CE_OVERFLOW_MASK                            	0x0000000000000002ull
#define AR_NIC_TARB_ERR_FLG_DIAG_ONLY_MASK                              	0x0000000000000001ull
#define AR_NIC_TARB_ERR_FLG_DLA_UNDERFLOW_BP                            	6
#define AR_NIC_TARB_ERR_FLG_BTE_UNDERFLOW_BP                            	5
#define AR_NIC_TARB_ERR_FLG_CE_UNDERFLOW_BP                             	4
#define AR_NIC_TARB_ERR_FLG_DLA_OVERFLOW_BP                             	3
#define AR_NIC_TARB_ERR_FLG_BTE_OVERFLOW_BP                             	2
#define AR_NIC_TARB_ERR_FLG_CE_OVERFLOW_BP                              	1
#define AR_NIC_TARB_ERR_FLG_DIAG_ONLY_BP                                	0
#define AR_NIC_TARB_ERR_FLG_DLA_UNDERFLOW_QW                            	0
#define AR_NIC_TARB_ERR_FLG_BTE_UNDERFLOW_QW                            	0
#define AR_NIC_TARB_ERR_FLG_CE_UNDERFLOW_QW                             	0
#define AR_NIC_TARB_ERR_FLG_DLA_OVERFLOW_QW                             	0
#define AR_NIC_TARB_ERR_FLG_BTE_OVERFLOW_QW                             	0
#define AR_NIC_TARB_ERR_FLG_CE_OVERFLOW_QW                              	0
#define AR_NIC_TARB_ERR_FLG_DIAG_ONLY_QW                                	0
#ifdef EXCEPTIONS_DEFS
#define AR_NIC_TARB_ERR_FLG_DLA_UNDERFLOW_EC                            	A_EC_CRIT
#define AR_NIC_TARB_ERR_FLG_BTE_UNDERFLOW_EC                            	A_EC_CRIT
#define AR_NIC_TARB_ERR_FLG_CE_UNDERFLOW_EC                             	A_EC_CRIT
#define AR_NIC_TARB_ERR_FLG_DLA_OVERFLOW_EC                             	A_EC_CRIT
#define AR_NIC_TARB_ERR_FLG_BTE_OVERFLOW_EC                             	A_EC_CRIT
#define AR_NIC_TARB_ERR_FLG_CE_OVERFLOW_EC                              	A_EC_CRIT
#define AR_NIC_TARB_ERR_FLG_DIAG_ONLY_EC                                	A_EC_DIAG
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_NIC_TARB_ERR_CLR DEFINES
 */
#define AR_NIC_TARB_ERR_CLR_DLA_UNDERFLOW_MASK                          	0x0000000000000040ull
#define AR_NIC_TARB_ERR_CLR_BTE_UNDERFLOW_MASK                          	0x0000000000000020ull
#define AR_NIC_TARB_ERR_CLR_CE_UNDERFLOW_MASK                           	0x0000000000000010ull
#define AR_NIC_TARB_ERR_CLR_DLA_OVERFLOW_MASK                           	0x0000000000000008ull
#define AR_NIC_TARB_ERR_CLR_BTE_OVERFLOW_MASK                           	0x0000000000000004ull
#define AR_NIC_TARB_ERR_CLR_CE_OVERFLOW_MASK                            	0x0000000000000002ull
#define AR_NIC_TARB_ERR_CLR_DIAG_ONLY_MASK                              	0x0000000000000001ull
#define AR_NIC_TARB_ERR_CLR_DLA_UNDERFLOW_BP                            	6
#define AR_NIC_TARB_ERR_CLR_BTE_UNDERFLOW_BP                            	5
#define AR_NIC_TARB_ERR_CLR_CE_UNDERFLOW_BP                             	4
#define AR_NIC_TARB_ERR_CLR_DLA_OVERFLOW_BP                             	3
#define AR_NIC_TARB_ERR_CLR_BTE_OVERFLOW_BP                             	2
#define AR_NIC_TARB_ERR_CLR_CE_OVERFLOW_BP                              	1
#define AR_NIC_TARB_ERR_CLR_DIAG_ONLY_BP                                	0
#define AR_NIC_TARB_ERR_CLR_DLA_UNDERFLOW_QW                            	0
#define AR_NIC_TARB_ERR_CLR_BTE_UNDERFLOW_QW                            	0
#define AR_NIC_TARB_ERR_CLR_CE_UNDERFLOW_QW                             	0
#define AR_NIC_TARB_ERR_CLR_DLA_OVERFLOW_QW                             	0
#define AR_NIC_TARB_ERR_CLR_BTE_OVERFLOW_QW                             	0
#define AR_NIC_TARB_ERR_CLR_CE_OVERFLOW_QW                              	0
#define AR_NIC_TARB_ERR_CLR_DIAG_ONLY_QW                                	0
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_NIC_TARB_ERR_HSS_MSK DEFINES
 */
#define AR_NIC_TARB_ERR_HSS_MSK_DLA_UNDERFLOW_MASK                      	0x0000000000000040ull
#define AR_NIC_TARB_ERR_HSS_MSK_BTE_UNDERFLOW_MASK                      	0x0000000000000020ull
#define AR_NIC_TARB_ERR_HSS_MSK_CE_UNDERFLOW_MASK                       	0x0000000000000010ull
#define AR_NIC_TARB_ERR_HSS_MSK_DLA_OVERFLOW_MASK                       	0x0000000000000008ull
#define AR_NIC_TARB_ERR_HSS_MSK_BTE_OVERFLOW_MASK                       	0x0000000000000004ull
#define AR_NIC_TARB_ERR_HSS_MSK_CE_OVERFLOW_MASK                        	0x0000000000000002ull
#define AR_NIC_TARB_ERR_HSS_MSK_DIAG_ONLY_MASK                          	0x0000000000000001ull
#define AR_NIC_TARB_ERR_HSS_MSK_DLA_UNDERFLOW_BP                        	6
#define AR_NIC_TARB_ERR_HSS_MSK_BTE_UNDERFLOW_BP                        	5
#define AR_NIC_TARB_ERR_HSS_MSK_CE_UNDERFLOW_BP                         	4
#define AR_NIC_TARB_ERR_HSS_MSK_DLA_OVERFLOW_BP                         	3
#define AR_NIC_TARB_ERR_HSS_MSK_BTE_OVERFLOW_BP                         	2
#define AR_NIC_TARB_ERR_HSS_MSK_CE_OVERFLOW_BP                          	1
#define AR_NIC_TARB_ERR_HSS_MSK_DIAG_ONLY_BP                            	0
#define AR_NIC_TARB_ERR_HSS_MSK_DLA_UNDERFLOW_QW                        	0
#define AR_NIC_TARB_ERR_HSS_MSK_BTE_UNDERFLOW_QW                        	0
#define AR_NIC_TARB_ERR_HSS_MSK_CE_UNDERFLOW_QW                         	0
#define AR_NIC_TARB_ERR_HSS_MSK_DLA_OVERFLOW_QW                         	0
#define AR_NIC_TARB_ERR_HSS_MSK_BTE_OVERFLOW_QW                         	0
#define AR_NIC_TARB_ERR_HSS_MSK_CE_OVERFLOW_QW                          	0
#define AR_NIC_TARB_ERR_HSS_MSK_DIAG_ONLY_QW                            	0
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_NIC_TARB_ERR_OS_MSK DEFINES
 */
#define AR_NIC_TARB_ERR_OS_MSK_DLA_UNDERFLOW_MASK                       	0x0000000000000040ull
#define AR_NIC_TARB_ERR_OS_MSK_BTE_UNDERFLOW_MASK                       	0x0000000000000020ull
#define AR_NIC_TARB_ERR_OS_MSK_CE_UNDERFLOW_MASK                        	0x0000000000000010ull
#define AR_NIC_TARB_ERR_OS_MSK_DLA_OVERFLOW_MASK                        	0x0000000000000008ull
#define AR_NIC_TARB_ERR_OS_MSK_BTE_OVERFLOW_MASK                        	0x0000000000000004ull
#define AR_NIC_TARB_ERR_OS_MSK_CE_OVERFLOW_MASK                         	0x0000000000000002ull
#define AR_NIC_TARB_ERR_OS_MSK_DIAG_ONLY_MASK                           	0x0000000000000001ull
#define AR_NIC_TARB_ERR_OS_MSK_DLA_UNDERFLOW_BP                         	6
#define AR_NIC_TARB_ERR_OS_MSK_BTE_UNDERFLOW_BP                         	5
#define AR_NIC_TARB_ERR_OS_MSK_CE_UNDERFLOW_BP                          	4
#define AR_NIC_TARB_ERR_OS_MSK_DLA_OVERFLOW_BP                          	3
#define AR_NIC_TARB_ERR_OS_MSK_BTE_OVERFLOW_BP                          	2
#define AR_NIC_TARB_ERR_OS_MSK_CE_OVERFLOW_BP                           	1
#define AR_NIC_TARB_ERR_OS_MSK_DIAG_ONLY_BP                             	0
#define AR_NIC_TARB_ERR_OS_MSK_DLA_UNDERFLOW_QW                         	0
#define AR_NIC_TARB_ERR_OS_MSK_BTE_UNDERFLOW_QW                         	0
#define AR_NIC_TARB_ERR_OS_MSK_CE_UNDERFLOW_QW                          	0
#define AR_NIC_TARB_ERR_OS_MSK_DLA_OVERFLOW_QW                          	0
#define AR_NIC_TARB_ERR_OS_MSK_BTE_OVERFLOW_QW                          	0
#define AR_NIC_TARB_ERR_OS_MSK_CE_OVERFLOW_QW                           	0
#define AR_NIC_TARB_ERR_OS_MSK_DIAG_ONLY_QW                             	0
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */


/*
 *  AR_NIC_TARB_ERR_FIRST_FLG DEFINES
 */
#define AR_NIC_TARB_ERR_FIRST_FLG_DLA_UNDERFLOW_MASK                    	0x0000000000000040ull
#define AR_NIC_TARB_ERR_FIRST_FLG_BTE_UNDERFLOW_MASK                    	0x0000000000000020ull
#define AR_NIC_TARB_ERR_FIRST_FLG_CE_UNDERFLOW_MASK                     	0x0000000000000010ull
#define AR_NIC_TARB_ERR_FIRST_FLG_DLA_OVERFLOW_MASK                     	0x0000000000000008ull
#define AR_NIC_TARB_ERR_FIRST_FLG_BTE_OVERFLOW_MASK                     	0x0000000000000004ull
#define AR_NIC_TARB_ERR_FIRST_FLG_CE_OVERFLOW_MASK                      	0x0000000000000002ull
#define AR_NIC_TARB_ERR_FIRST_FLG_DIAG_ONLY_MASK                        	0x0000000000000001ull
#define AR_NIC_TARB_ERR_FIRST_FLG_DLA_UNDERFLOW_BP                      	6
#define AR_NIC_TARB_ERR_FIRST_FLG_BTE_UNDERFLOW_BP                      	5
#define AR_NIC_TARB_ERR_FIRST_FLG_CE_UNDERFLOW_BP                       	4
#define AR_NIC_TARB_ERR_FIRST_FLG_DLA_OVERFLOW_BP                       	3
#define AR_NIC_TARB_ERR_FIRST_FLG_BTE_OVERFLOW_BP                       	2
#define AR_NIC_TARB_ERR_FIRST_FLG_CE_OVERFLOW_BP                        	1
#define AR_NIC_TARB_ERR_FIRST_FLG_DIAG_ONLY_BP                          	0
#define AR_NIC_TARB_ERR_FIRST_FLG_DLA_UNDERFLOW_QW                      	0
#define AR_NIC_TARB_ERR_FIRST_FLG_BTE_UNDERFLOW_QW                      	0
#define AR_NIC_TARB_ERR_FIRST_FLG_CE_UNDERFLOW_QW                       	0
#define AR_NIC_TARB_ERR_FIRST_FLG_DLA_OVERFLOW_QW                       	0
#define AR_NIC_TARB_ERR_FIRST_FLG_BTE_OVERFLOW_QW                       	0
#define AR_NIC_TARB_ERR_FIRST_FLG_CE_OVERFLOW_QW                        	0
#define AR_NIC_TARB_ERR_FIRST_FLG_DIAG_ONLY_QW                          	0
#ifdef EXCEPTIONS_DEFS
#endif /* EXCEPTIONS_DEFS */



/*
 *  AR TARB MACROS
 */
#ifndef RD_FIELD
#define RD_FIELD(d, bp, m)	(((d)&(m))>>(bp))
#endif
#ifndef WR_FIELD
#define WR_FIELD(mmr, d, bp, m)	(mmr = (((mmr) & ~(m)) | ((((uint64_t)(d))<<(bp)) & (m))))
#endif
#define RF_AR_NIC_TARB_CFG_PARAMS_MAX_PKT_SIZE(mmr)             	RD_FIELD(mmr,\
									AR_NIC_TARB_CFG_PARAMS_MAX_PKT_SIZE_BP,\
									AR_NIC_TARB_CFG_PARAMS_MAX_PKT_SIZE_MASK)
#define WF_AR_NIC_TARB_CFG_PARAMS_MAX_PKT_SIZE(mmr,v)           	WR_FIELD(mmr,v,\
									AR_NIC_TARB_CFG_PARAMS_MAX_PKT_SIZE_BP,\
									AR_NIC_TARB_CFG_PARAMS_MAX_PKT_SIZE_MASK)
#define RF_AR_NIC_TARB_CFG_PARAMS_SF_DLA(mmr)                   	RD_FIELD(mmr,\
									AR_NIC_TARB_CFG_PARAMS_SF_DLA_BP,\
									AR_NIC_TARB_CFG_PARAMS_SF_DLA_MASK)
#define WF_AR_NIC_TARB_CFG_PARAMS_SF_DLA(mmr,v)                 	WR_FIELD(mmr,v,\
									AR_NIC_TARB_CFG_PARAMS_SF_DLA_BP,\
									AR_NIC_TARB_CFG_PARAMS_SF_DLA_MASK)
#define RF_AR_NIC_TARB_CFG_PARAMS_SF_BTE(mmr)                   	RD_FIELD(mmr,\
									AR_NIC_TARB_CFG_PARAMS_SF_BTE_BP,\
									AR_NIC_TARB_CFG_PARAMS_SF_BTE_MASK)
#define WF_AR_NIC_TARB_CFG_PARAMS_SF_BTE(mmr,v)                 	WR_FIELD(mmr,v,\
									AR_NIC_TARB_CFG_PARAMS_SF_BTE_BP,\
									AR_NIC_TARB_CFG_PARAMS_SF_BTE_MASK)
#define RF_AR_NIC_TARB_CFG_PARAMS_SF_CE(mmr)                    	RD_FIELD(mmr,\
									AR_NIC_TARB_CFG_PARAMS_SF_CE_BP,\
									AR_NIC_TARB_CFG_PARAMS_SF_CE_MASK)
#define WF_AR_NIC_TARB_CFG_PARAMS_SF_CE(mmr,v)                  	WR_FIELD(mmr,v,\
									AR_NIC_TARB_CFG_PARAMS_SF_CE_BP,\
									AR_NIC_TARB_CFG_PARAMS_SF_CE_MASK)
#define RF_AR_NIC_TARB_CFG_PARAMS_SSID_CREDIT_MAX(mmr)          	RD_FIELD(mmr,\
									AR_NIC_TARB_CFG_PARAMS_SSID_CREDIT_MAX_BP,\
									AR_NIC_TARB_CFG_PARAMS_SSID_CREDIT_MAX_MASK)
#define WF_AR_NIC_TARB_CFG_PARAMS_SSID_CREDIT_MAX(mmr,v)        	WR_FIELD(mmr,v,\
									AR_NIC_TARB_CFG_PARAMS_SSID_CREDIT_MAX_BP,\
									AR_NIC_TARB_CFG_PARAMS_SSID_CREDIT_MAX_MASK)
#define RF_AR_NIC_TARB_TARB_MMR_RING_0_HI_TARB_UNUSED_145_35(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_MMR_RING_0_HI_TARB_UNUSED_145_35_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_HI_TARB_UNUSED_145_35_MASK)
#define WF_AR_NIC_TARB_TARB_MMR_RING_0_HI_TARB_UNUSED_145_35(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_MMR_RING_0_HI_TARB_UNUSED_145_35_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_HI_TARB_UNUSED_145_35_MASK)
#define RF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_UNUSED_127_94(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_UNUSED_127_94_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_UNUSED_127_94_MASK)
#define WF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_UNUSED_127_94(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_UNUSED_127_94_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_UNUSED_127_94_MASK)
#define RF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_STALLED(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_STALLED_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_STALLED_MASK)
#define WF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_STALLED(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_STALLED_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_STALLED_MASK)
#define RF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_PKTS(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_PKTS_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_PKTS_MASK)
#define WF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_PKTS(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_PKTS_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_PKTS_MASK)
#define RF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_FLITS(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_FLITS_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_FLITS_MASK)
#define WF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_FLITS(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_FLITS_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_SSID_FLITS_MASK)
#define RF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_BLOCKED(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_BLOCKED_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_BLOCKED_MASK)
#define WF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_BLOCKED(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_BLOCKED_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_BLOCKED_MASK)
#define RF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_PKTS(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_PKTS_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_PKTS_MASK)
#define WF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_PKTS(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_PKTS_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_PKTS_MASK)
#define RF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_FLITS(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_FLITS_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_FLITS_MASK)
#define WF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_FLITS(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_FLITS_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_DLA_FLITS_MASK)
#define RF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_BLOCKED(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_BLOCKED_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_BLOCKED_MASK)
#define WF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_BLOCKED(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_BLOCKED_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_BLOCKED_MASK)
#define RF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_PKTS(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_PKTS_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_PKTS_MASK)
#define WF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_PKTS(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_PKTS_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_PKTS_MASK)
#define RF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_FLITS(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_FLITS_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_FLITS_MASK)
#define WF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_FLITS(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_FLITS_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_BTE_FLITS_MASK)
#define RF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_BLOCKED(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_BLOCKED_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_BLOCKED_MASK)
#define WF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_BLOCKED(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_BLOCKED_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_BLOCKED_MASK)
#define RF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_PKTS(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_PKTS_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_PKTS_MASK)
#define WF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_PKTS(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_PKTS_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_PKTS_MASK)
#define RF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_FLITS(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_FLITS_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_FLITS_MASK)
#define WF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_FLITS(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_FLITS_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_CNTR_CE_FLITS_MASK)
#define RF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_UNUSED_81_64(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_UNUSED_81_64_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_UNUSED_81_64_MASK)
#define WF_AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_UNUSED_81_64(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_UNUSED_81_64_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_MID_TARB_UNUSED_81_64_MASK)
#define RF_AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_UNUSED_145_35(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_UNUSED_145_35_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_UNUSED_145_35_MASK)
#define WF_AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_UNUSED_145_35(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_UNUSED_145_35_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_UNUSED_145_35_MASK)
#define RF_AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_PI_OS_IRQ(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_PI_OS_IRQ_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_PI_OS_IRQ_MASK)
#define WF_AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_PI_OS_IRQ(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_PI_OS_IRQ_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_PI_OS_IRQ_MASK)
#define RF_AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_LB_HSS_IRQ(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_LB_HSS_IRQ_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_LB_HSS_IRQ_MASK)
#define WF_AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_LB_HSS_IRQ(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_LB_HSS_IRQ_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_LB_HSS_IRQ_MASK)
#define RF_AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_NETMON_RING_WRACK(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_NETMON_RING_WRACK_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_NETMON_RING_WRACK_MASK)
#define WF_AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_NETMON_RING_WRACK(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_NETMON_RING_WRACK_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_NETMON_RING_WRACK_MASK)
#define RF_AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_NETMON_RING_15_0(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_NETMON_RING_15_0_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_NETMON_RING_15_0_MASK)
#define WF_AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_NETMON_RING_15_0(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_NETMON_RING_15_0_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_R_Q_TARB_NETMON_RING_15_0_MASK)
#define RF_AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_I_NETMON_TARB_RING_15_0(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_I_NETMON_TARB_RING_15_0_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_I_NETMON_TARB_RING_15_0_MASK)
#define WF_AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_I_NETMON_TARB_RING_15_0(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_I_NETMON_TARB_RING_15_0_BP,\
									AR_NIC_TARB_TARB_MMR_RING_0_LO_TARB_I_NETMON_TARB_RING_15_0_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_1_HI_TARB_UNUSED_145_71(mmr)     	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_1_HI_TARB_UNUSED_145_71_BP,\
									AR_NIC_TARB_ERR_FLG_1_HI_TARB_UNUSED_145_71_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_1_HI_TARB_UNUSED_145_71(mmr,v)   	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_1_HI_TARB_UNUSED_145_71_BP,\
									AR_NIC_TARB_ERR_FLG_1_HI_TARB_UNUSED_145_71_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_1_MID_TARB_UNUSED_127_71(mmr)    	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_UNUSED_127_71_BP,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_UNUSED_127_71_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_1_MID_TARB_UNUSED_127_71(mmr,v)  	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_UNUSED_127_71_BP,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_UNUSED_127_71_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_1_MID_TARB_DLA_UNDERFLOW(mmr)    	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_DLA_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_DLA_UNDERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_1_MID_TARB_DLA_UNDERFLOW(mmr,v)  	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_DLA_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_DLA_UNDERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_1_MID_TARB_BTE_UNDERFLOW(mmr)    	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_BTE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_BTE_UNDERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_1_MID_TARB_BTE_UNDERFLOW(mmr,v)  	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_BTE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_BTE_UNDERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_1_MID_TARB_CE_UNDERFLOW(mmr)     	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_CE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_CE_UNDERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_1_MID_TARB_CE_UNDERFLOW(mmr,v)   	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_CE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_CE_UNDERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_1_MID_TARB_DLA_OVERFLOW(mmr)     	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_DLA_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_DLA_OVERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_1_MID_TARB_DLA_OVERFLOW(mmr,v)   	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_DLA_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_DLA_OVERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_1_MID_TARB_BTE_OVERFLOW(mmr)     	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_BTE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_BTE_OVERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_1_MID_TARB_BTE_OVERFLOW(mmr,v)   	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_BTE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_BTE_OVERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_1_MID_TARB_CE_OVERFLOW(mmr)      	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_CE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_CE_OVERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_1_MID_TARB_CE_OVERFLOW(mmr,v)    	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_CE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_CE_OVERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_1_MID_TARB_DIAG_ONLY(mmr)        	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_DIAG_ONLY_BP,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_DIAG_ONLY_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_1_MID_TARB_DIAG_ONLY(mmr,v)      	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_DIAG_ONLY_BP,\
									AR_NIC_TARB_ERR_FLG_1_MID_TARB_DIAG_ONLY_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_1_LO_TARB_UNUSED_63_7(mmr)       	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_UNUSED_63_7_BP,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_UNUSED_63_7_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_1_LO_TARB_UNUSED_63_7(mmr,v)     	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_UNUSED_63_7_BP,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_UNUSED_63_7_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_DLA_UNDERFLOW(mmr)   	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_DLA_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_DLA_UNDERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_DLA_UNDERFLOW(mmr,v) 	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_DLA_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_DLA_UNDERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_BTE_UNDERFLOW(mmr)   	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_BTE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_BTE_UNDERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_BTE_UNDERFLOW(mmr,v) 	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_BTE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_BTE_UNDERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_CE_UNDERFLOW(mmr)    	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_CE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_CE_UNDERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_CE_UNDERFLOW(mmr,v)  	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_CE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_CE_UNDERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_DLA_OVERFLOW(mmr)    	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_DLA_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_DLA_OVERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_DLA_OVERFLOW(mmr,v)  	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_DLA_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_DLA_OVERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_BTE_OVERFLOW(mmr)    	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_BTE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_BTE_OVERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_BTE_OVERFLOW(mmr,v)  	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_BTE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_BTE_OVERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_CE_OVERFLOW(mmr)     	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_CE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_CE_OVERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_CE_OVERFLOW(mmr,v)   	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_CE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_I_CE_OVERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_1_LO_TARB_UNUSED_0(mmr)          	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_UNUSED_0_BP,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_UNUSED_0_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_1_LO_TARB_UNUSED_0(mmr,v)        	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_UNUSED_0_BP,\
									AR_NIC_TARB_ERR_FLG_1_LO_TARB_UNUSED_0_MASK)
#define RF_AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB_TARB_SSID_REQ_SB(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB_TARB_SSID_REQ_SB_BP,\
									AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB_TARB_SSID_REQ_SB_MASK)
#define WF_AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB_TARB_SSID_REQ_SB(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB_TARB_SSID_REQ_SB_BP,\
									AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB_TARB_SSID_REQ_SB_MASK)
#define RF_AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB_TARB_SSID_REQ_FLIT(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB_TARB_SSID_REQ_FLIT_BP,\
									AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB_TARB_SSID_REQ_FLIT_MASK)
#define WF_AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB_TARB_SSID_REQ_FLIT(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB_TARB_SSID_REQ_FLIT_BP,\
									AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_HI_TARB_TARB_SSID_REQ_FLIT_MASK)
#define RF_AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_MID_TARB_TARB_SSID_REQ_FLIT(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_MID_TARB_TARB_SSID_REQ_FLIT_BP,\
									AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_MID_TARB_TARB_SSID_REQ_FLIT_MASK)
#define WF_AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_MID_TARB_TARB_SSID_REQ_FLIT(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_MID_TARB_TARB_SSID_REQ_FLIT_BP,\
									AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_MID_TARB_TARB_SSID_REQ_FLIT_MASK)
#define RF_AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_LO_TARB_TARB_SSID_REQ_FLIT(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_LO_TARB_TARB_SSID_REQ_FLIT_BP,\
									AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_LO_TARB_TARB_SSID_REQ_FLIT_MASK)
#define WF_AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_LO_TARB_TARB_SSID_REQ_FLIT(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_LO_TARB_TARB_SSID_REQ_FLIT_BP,\
									AR_NIC_TARB_TARB_SSID_REQ_FLIT_2_LO_TARB_TARB_SSID_REQ_FLIT_MASK)
#define RF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_HI_TARB_UNUSED_145_37(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_HI_TARB_UNUSED_145_37_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_HI_TARB_UNUSED_145_37_MASK)
#define WF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_HI_TARB_UNUSED_145_37(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_HI_TARB_UNUSED_145_37_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_HI_TARB_UNUSED_145_37_MASK)
#define RF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_MID_TARB_UNUSED_145_37(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_MID_TARB_UNUSED_145_37_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_MID_TARB_UNUSED_145_37_MASK)
#define WF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_MID_TARB_UNUSED_145_37(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_MID_TARB_UNUSED_145_37_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_MID_TARB_UNUSED_145_37_MASK)
#define RF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_UNUSED_145_37(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_UNUSED_145_37_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_UNUSED_145_37_MASK)
#define WF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_UNUSED_145_37(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_UNUSED_145_37_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_UNUSED_145_37_MASK)
#define RF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_I_SSID_TARB_REQ_ACK(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_I_SSID_TARB_REQ_ACK_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_I_SSID_TARB_REQ_ACK_MASK)
#define WF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_I_SSID_TARB_REQ_ACK(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_I_SSID_TARB_REQ_ACK_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_I_SSID_TARB_REQ_ACK_MASK)
#define RF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_35_33(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_35_33_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_35_33_MASK)
#define WF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_35_33(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_35_33_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_35_33_MASK)
#define RF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_DLA_REQ_ACK(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_DLA_REQ_ACK_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_DLA_REQ_ACK_MASK)
#define WF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_DLA_REQ_ACK(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_DLA_REQ_ACK_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_DLA_REQ_ACK_MASK)
#define RF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_31_29(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_31_29_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_31_29_MASK)
#define WF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_31_29(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_31_29_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_31_29_MASK)
#define RF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_BTE_REQ_ACK(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_BTE_REQ_ACK_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_BTE_REQ_ACK_MASK)
#define WF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_BTE_REQ_ACK(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_BTE_REQ_ACK_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_BTE_REQ_ACK_MASK)
#define RF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_27_25(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_27_25_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_27_25_MASK)
#define WF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_27_25(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_27_25_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_27_25_MASK)
#define RF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_CE_REQ_ACK(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_CE_REQ_ACK_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_CE_REQ_ACK_MASK)
#define WF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_CE_REQ_ACK(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_CE_REQ_ACK_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_R_Q_TARB_CE_REQ_ACK_MASK)
#define RF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_TARB_CRDTS(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_TARB_CRDTS_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_TARB_CRDTS_MASK)
#define WF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_TARB_CRDTS(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_TARB_CRDTS_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_TARB_CRDTS_MASK)
#define RF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_TARB_CRDTS_EMPTY(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_TARB_CRDTS_EMPTY_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_TARB_CRDTS_EMPTY_MASK)
#define WF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_TARB_CRDTS_EMPTY(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_TARB_CRDTS_EMPTY_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_TARB_CRDTS_EMPTY_MASK)
#define RF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_I_DLA_TARB_DL_REC(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_I_DLA_TARB_DL_REC_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_I_DLA_TARB_DL_REC_MASK)
#define WF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_I_DLA_TARB_DL_REC(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_I_DLA_TARB_DL_REC_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_I_DLA_TARB_DL_REC_MASK)
#define RF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_QOS_VLD(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_QOS_VLD_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_QOS_VLD_MASK)
#define WF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_QOS_VLD(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_QOS_VLD_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_QOS_VLD_MASK)
#define RF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_HOLD(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_HOLD_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_HOLD_MASK)
#define WF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_HOLD(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_HOLD_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_HOLD_MASK)
#define RF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_11(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_11_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_11_MASK)
#define WF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_11(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_11_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_11_MASK)
#define RF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_ACK(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_ACK_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_ACK_MASK)
#define WF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_ACK(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_ACK_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_ACK_MASK)
#define RF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_7(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_7_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_7_MASK)
#define WF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_7(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_7_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_7_MASK)
#define RF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_GNT(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_GNT_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_GNT_MASK)
#define WF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_GNT(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_GNT_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_GNT_MASK)
#define RF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_3(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_3_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_3_MASK)
#define WF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_3(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_3_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_RESERVED_3_MASK)
#define RF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_REQ(mmr)	RD_FIELD(mmr,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_REQ_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_REQ_MASK)
#define WF_AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_REQ(mmr,v)	WR_FIELD(mmr,v,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_REQ_BP,\
									AR_NIC_TARB_TARB_ARB_CRDT_ACK_FIELDS_3_LO_TARB_ARB_REQ_MASK)
#define RF_AR_NIC_TARB_CFG_QOS_RATE_B2_RATE(mmr)                	RD_FIELD(mmr,\
									AR_NIC_TARB_CFG_QOS_RATE_B2_RATE_BP,\
									AR_NIC_TARB_CFG_QOS_RATE_B2_RATE_MASK)
#define WF_AR_NIC_TARB_CFG_QOS_RATE_B2_RATE(mmr,v)              	WR_FIELD(mmr,v,\
									AR_NIC_TARB_CFG_QOS_RATE_B2_RATE_BP,\
									AR_NIC_TARB_CFG_QOS_RATE_B2_RATE_MASK)
#define RF_AR_NIC_TARB_CFG_QOS_RATE_B1_RATE(mmr)                	RD_FIELD(mmr,\
									AR_NIC_TARB_CFG_QOS_RATE_B1_RATE_BP,\
									AR_NIC_TARB_CFG_QOS_RATE_B1_RATE_MASK)
#define WF_AR_NIC_TARB_CFG_QOS_RATE_B1_RATE(mmr,v)              	WR_FIELD(mmr,v,\
									AR_NIC_TARB_CFG_QOS_RATE_B1_RATE_BP,\
									AR_NIC_TARB_CFG_QOS_RATE_B1_RATE_MASK)
#define RF_AR_NIC_TARB_CFG_QOS_SIZE_B2_SIZE(mmr)                	RD_FIELD(mmr,\
									AR_NIC_TARB_CFG_QOS_SIZE_B2_SIZE_BP,\
									AR_NIC_TARB_CFG_QOS_SIZE_B2_SIZE_MASK)
#define WF_AR_NIC_TARB_CFG_QOS_SIZE_B2_SIZE(mmr,v)              	WR_FIELD(mmr,v,\
									AR_NIC_TARB_CFG_QOS_SIZE_B2_SIZE_BP,\
									AR_NIC_TARB_CFG_QOS_SIZE_B2_SIZE_MASK)
#define RF_AR_NIC_TARB_CFG_QOS_SIZE_B1_SIZE(mmr)                	RD_FIELD(mmr,\
									AR_NIC_TARB_CFG_QOS_SIZE_B1_SIZE_BP,\
									AR_NIC_TARB_CFG_QOS_SIZE_B1_SIZE_MASK)
#define WF_AR_NIC_TARB_CFG_QOS_SIZE_B1_SIZE(mmr,v)              	WR_FIELD(mmr,v,\
									AR_NIC_TARB_CFG_QOS_SIZE_B1_SIZE_BP,\
									AR_NIC_TARB_CFG_QOS_SIZE_B1_SIZE_MASK)
#define RF_AR_NIC_TARB_DBG_CREDIT_SSID_CREDIT_CNT(mmr)          	RD_FIELD(mmr,\
									AR_NIC_TARB_DBG_CREDIT_SSID_CREDIT_CNT_BP,\
									AR_NIC_TARB_DBG_CREDIT_SSID_CREDIT_CNT_MASK)
#define WF_AR_NIC_TARB_DBG_CREDIT_SSID_CREDIT_CNT(mmr,v)        	WR_FIELD(mmr,v,\
									AR_NIC_TARB_DBG_CREDIT_SSID_CREDIT_CNT_BP,\
									AR_NIC_TARB_DBG_CREDIT_SSID_CREDIT_CNT_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_DLA_UNDERFLOW(mmr)               	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_DLA_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_DLA_UNDERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_DLA_UNDERFLOW(mmr,v)             	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_DLA_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_DLA_UNDERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_BTE_UNDERFLOW(mmr)               	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_BTE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_BTE_UNDERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_BTE_UNDERFLOW(mmr,v)             	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_BTE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_BTE_UNDERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_CE_UNDERFLOW(mmr)                	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_CE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_CE_UNDERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_CE_UNDERFLOW(mmr,v)              	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_CE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_CE_UNDERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_DLA_OVERFLOW(mmr)                	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_DLA_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_DLA_OVERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_DLA_OVERFLOW(mmr,v)              	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_DLA_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_DLA_OVERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_BTE_OVERFLOW(mmr)                	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_BTE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_BTE_OVERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_BTE_OVERFLOW(mmr,v)              	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_BTE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_BTE_OVERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_CE_OVERFLOW(mmr)                 	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_CE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_CE_OVERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_CE_OVERFLOW(mmr,v)               	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_CE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FLG_CE_OVERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FLG_DIAG_ONLY(mmr)                   	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FLG_DIAG_ONLY_BP,\
									AR_NIC_TARB_ERR_FLG_DIAG_ONLY_MASK)
#define WF_AR_NIC_TARB_ERR_FLG_DIAG_ONLY(mmr,v)                 	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FLG_DIAG_ONLY_BP,\
									AR_NIC_TARB_ERR_FLG_DIAG_ONLY_MASK)
#define RF_AR_NIC_TARB_ERR_CLR_DLA_UNDERFLOW(mmr)               	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_CLR_DLA_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_CLR_DLA_UNDERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_CLR_DLA_UNDERFLOW(mmr,v)             	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_CLR_DLA_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_CLR_DLA_UNDERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_CLR_BTE_UNDERFLOW(mmr)               	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_CLR_BTE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_CLR_BTE_UNDERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_CLR_BTE_UNDERFLOW(mmr,v)             	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_CLR_BTE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_CLR_BTE_UNDERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_CLR_CE_UNDERFLOW(mmr)                	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_CLR_CE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_CLR_CE_UNDERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_CLR_CE_UNDERFLOW(mmr,v)              	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_CLR_CE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_CLR_CE_UNDERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_CLR_DLA_OVERFLOW(mmr)                	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_CLR_DLA_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_CLR_DLA_OVERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_CLR_DLA_OVERFLOW(mmr,v)              	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_CLR_DLA_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_CLR_DLA_OVERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_CLR_BTE_OVERFLOW(mmr)                	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_CLR_BTE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_CLR_BTE_OVERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_CLR_BTE_OVERFLOW(mmr,v)              	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_CLR_BTE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_CLR_BTE_OVERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_CLR_CE_OVERFLOW(mmr)                 	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_CLR_CE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_CLR_CE_OVERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_CLR_CE_OVERFLOW(mmr,v)               	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_CLR_CE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_CLR_CE_OVERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_CLR_DIAG_ONLY(mmr)                   	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_CLR_DIAG_ONLY_BP,\
									AR_NIC_TARB_ERR_CLR_DIAG_ONLY_MASK)
#define WF_AR_NIC_TARB_ERR_CLR_DIAG_ONLY(mmr,v)                 	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_CLR_DIAG_ONLY_BP,\
									AR_NIC_TARB_ERR_CLR_DIAG_ONLY_MASK)
#define RF_AR_NIC_TARB_ERR_HSS_MSK_DLA_UNDERFLOW(mmr)           	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_HSS_MSK_DLA_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_HSS_MSK_DLA_UNDERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_HSS_MSK_DLA_UNDERFLOW(mmr,v)         	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_HSS_MSK_DLA_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_HSS_MSK_DLA_UNDERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_HSS_MSK_BTE_UNDERFLOW(mmr)           	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_HSS_MSK_BTE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_HSS_MSK_BTE_UNDERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_HSS_MSK_BTE_UNDERFLOW(mmr,v)         	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_HSS_MSK_BTE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_HSS_MSK_BTE_UNDERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_HSS_MSK_CE_UNDERFLOW(mmr)            	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_HSS_MSK_CE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_HSS_MSK_CE_UNDERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_HSS_MSK_CE_UNDERFLOW(mmr,v)          	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_HSS_MSK_CE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_HSS_MSK_CE_UNDERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_HSS_MSK_DLA_OVERFLOW(mmr)            	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_HSS_MSK_DLA_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_HSS_MSK_DLA_OVERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_HSS_MSK_DLA_OVERFLOW(mmr,v)          	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_HSS_MSK_DLA_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_HSS_MSK_DLA_OVERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_HSS_MSK_BTE_OVERFLOW(mmr)            	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_HSS_MSK_BTE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_HSS_MSK_BTE_OVERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_HSS_MSK_BTE_OVERFLOW(mmr,v)          	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_HSS_MSK_BTE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_HSS_MSK_BTE_OVERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_HSS_MSK_CE_OVERFLOW(mmr)             	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_HSS_MSK_CE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_HSS_MSK_CE_OVERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_HSS_MSK_CE_OVERFLOW(mmr,v)           	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_HSS_MSK_CE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_HSS_MSK_CE_OVERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_HSS_MSK_DIAG_ONLY(mmr)               	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_HSS_MSK_DIAG_ONLY_BP,\
									AR_NIC_TARB_ERR_HSS_MSK_DIAG_ONLY_MASK)
#define WF_AR_NIC_TARB_ERR_HSS_MSK_DIAG_ONLY(mmr,v)             	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_HSS_MSK_DIAG_ONLY_BP,\
									AR_NIC_TARB_ERR_HSS_MSK_DIAG_ONLY_MASK)
#define RF_AR_NIC_TARB_ERR_OS_MSK_DLA_UNDERFLOW(mmr)            	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_OS_MSK_DLA_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_OS_MSK_DLA_UNDERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_OS_MSK_DLA_UNDERFLOW(mmr,v)          	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_OS_MSK_DLA_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_OS_MSK_DLA_UNDERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_OS_MSK_BTE_UNDERFLOW(mmr)            	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_OS_MSK_BTE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_OS_MSK_BTE_UNDERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_OS_MSK_BTE_UNDERFLOW(mmr,v)          	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_OS_MSK_BTE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_OS_MSK_BTE_UNDERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_OS_MSK_CE_UNDERFLOW(mmr)             	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_OS_MSK_CE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_OS_MSK_CE_UNDERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_OS_MSK_CE_UNDERFLOW(mmr,v)           	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_OS_MSK_CE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_OS_MSK_CE_UNDERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_OS_MSK_DLA_OVERFLOW(mmr)             	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_OS_MSK_DLA_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_OS_MSK_DLA_OVERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_OS_MSK_DLA_OVERFLOW(mmr,v)           	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_OS_MSK_DLA_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_OS_MSK_DLA_OVERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_OS_MSK_BTE_OVERFLOW(mmr)             	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_OS_MSK_BTE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_OS_MSK_BTE_OVERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_OS_MSK_BTE_OVERFLOW(mmr,v)           	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_OS_MSK_BTE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_OS_MSK_BTE_OVERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_OS_MSK_CE_OVERFLOW(mmr)              	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_OS_MSK_CE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_OS_MSK_CE_OVERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_OS_MSK_CE_OVERFLOW(mmr,v)            	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_OS_MSK_CE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_OS_MSK_CE_OVERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_OS_MSK_DIAG_ONLY(mmr)                	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_OS_MSK_DIAG_ONLY_BP,\
									AR_NIC_TARB_ERR_OS_MSK_DIAG_ONLY_MASK)
#define WF_AR_NIC_TARB_ERR_OS_MSK_DIAG_ONLY(mmr,v)              	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_OS_MSK_DIAG_ONLY_BP,\
									AR_NIC_TARB_ERR_OS_MSK_DIAG_ONLY_MASK)
#define RF_AR_NIC_TARB_ERR_FIRST_FLG_DLA_UNDERFLOW(mmr)         	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FIRST_FLG_DLA_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FIRST_FLG_DLA_UNDERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FIRST_FLG_DLA_UNDERFLOW(mmr,v)       	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FIRST_FLG_DLA_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FIRST_FLG_DLA_UNDERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FIRST_FLG_BTE_UNDERFLOW(mmr)         	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FIRST_FLG_BTE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FIRST_FLG_BTE_UNDERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FIRST_FLG_BTE_UNDERFLOW(mmr,v)       	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FIRST_FLG_BTE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FIRST_FLG_BTE_UNDERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FIRST_FLG_CE_UNDERFLOW(mmr)          	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FIRST_FLG_CE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FIRST_FLG_CE_UNDERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FIRST_FLG_CE_UNDERFLOW(mmr,v)        	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FIRST_FLG_CE_UNDERFLOW_BP,\
									AR_NIC_TARB_ERR_FIRST_FLG_CE_UNDERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FIRST_FLG_DLA_OVERFLOW(mmr)          	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FIRST_FLG_DLA_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FIRST_FLG_DLA_OVERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FIRST_FLG_DLA_OVERFLOW(mmr,v)        	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FIRST_FLG_DLA_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FIRST_FLG_DLA_OVERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FIRST_FLG_BTE_OVERFLOW(mmr)          	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FIRST_FLG_BTE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FIRST_FLG_BTE_OVERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FIRST_FLG_BTE_OVERFLOW(mmr,v)        	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FIRST_FLG_BTE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FIRST_FLG_BTE_OVERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FIRST_FLG_CE_OVERFLOW(mmr)           	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FIRST_FLG_CE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FIRST_FLG_CE_OVERFLOW_MASK)
#define WF_AR_NIC_TARB_ERR_FIRST_FLG_CE_OVERFLOW(mmr,v)         	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FIRST_FLG_CE_OVERFLOW_BP,\
									AR_NIC_TARB_ERR_FIRST_FLG_CE_OVERFLOW_MASK)
#define RF_AR_NIC_TARB_ERR_FIRST_FLG_DIAG_ONLY(mmr)             	RD_FIELD(mmr,\
									AR_NIC_TARB_ERR_FIRST_FLG_DIAG_ONLY_BP,\
									AR_NIC_TARB_ERR_FIRST_FLG_DIAG_ONLY_MASK)
#define WF_AR_NIC_TARB_ERR_FIRST_FLG_DIAG_ONLY(mmr,v)           	WR_FIELD(mmr,v,\
									AR_NIC_TARB_ERR_FIRST_FLG_DIAG_ONLY_BP,\
									AR_NIC_TARB_ERR_FIRST_FLG_DIAG_ONLY_MASK)

#endif
