/******************************************************************************
 * COPYRIGHT CRAY INC. ar_wc_mmrs_h.h
 * FILE: ar_wc_mmrs_h.h
 * Created by v2h.c on Wed Oct  8 14:39:04 2014
 ******************************************************************************/

#ifndef _AR_WC_MMRS_H_H_
#define _AR_WC_MMRS_H_H_

#ifdef __GNUC__
#define _unused __attribute__((unused))
#else
#define _unused
#endif

#ifndef _GENERIC_MMRD_T_
#define _GENERIC_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint64_t _mask;		/* Field bit mask */
} generic_mmrd_t;
#endif

#ifndef _ERRCAT_MMRD_T_
#define _ERRCAT_MMRD_T_
typedef struct {
	char* _name;		/* Field name */
	uint32_t _bpos;		/* Field bit postion */
	uint32_t _ec;		/* Field error category */
} errcat_mmrd_t;
#endif

#ifndef _GENERIC_MMR_T_
#define _GENERIC_MMR_T_
typedef struct {
	char* _name;		/* MMR name */
	uint64_t _addr;		/* MMR address */
	int _size;		/* Size in bytes of MMR */
	int _depth;		/* Number of MMR instances */
	const generic_mmrd_t *_info;	/* MMR detail */
} generic_mmr_t;
#endif

static const generic_mmr_t* _ar_wc_mmrs[] _unused;	/* WC Array */

/*
 *  AR WC MMR DETAIL DECLARATIONS
 */
static const generic_mmrd_t _ar_nic_wc_cfg_params_detail[] = {
    { "BUF_SCRUB_RATE", AR_NIC_WC_CFG_PARAMS_BUF_SCRUB_RATE_BP, AR_NIC_WC_CFG_PARAMS_BUF_SCRUB_RATE_MASK },
    { "REQ_WAIT_CNT", AR_NIC_WC_CFG_PARAMS_REQ_WAIT_CNT_BP, AR_NIC_WC_CFG_PARAMS_REQ_WAIT_CNT_MASK },
    { "ENABLE", AR_NIC_WC_CFG_PARAMS_ENABLE_BP, AR_NIC_WC_CFG_PARAMS_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_mmr_ring_0_hi_wc_detail[] = {
    { "UNUSED_145_35", AR_NIC_WC_WC_MMR_RING_0_HI_WC_UNUSED_145_35_BP, AR_NIC_WC_WC_MMR_RING_0_HI_WC_UNUSED_145_35_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_mmr_ring_0_mid_wc_detail[] = {
    { "UNUSED_127_98", AR_NIC_WC_WC_MMR_RING_0_MID_WC_UNUSED_127_98_BP, AR_NIC_WC_WC_MMR_RING_0_MID_WC_UNUSED_127_98_MASK },
    { "CNTR_BUFFER_TIMEOUT", AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_BUFFER_TIMEOUT_BP, AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_BUFFER_TIMEOUT_MASK },
    { "CNTR_RSPIN1_HDR_PBE", AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_RSPIN1_HDR_PBE_BP, AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_RSPIN1_HDR_PBE_MASK },
    { "CNTR_RSPIN0_HDR_PBE", AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_RSPIN0_HDR_PBE_BP, AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_RSPIN0_HDR_PBE_MASK },
    { "CNTR_NTWK_RSP_HDR_PBE", AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_NTWK_RSP_HDR_PBE_BP, AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_NTWK_RSP_HDR_PBE_MASK },
    { "CNTR_TAG_PBE", AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_TAG_PBE_BP, AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_TAG_PBE_MASK },
    { "CNTR_RESERVED10", AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_RESERVED10_BP, AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_RESERVED10_MASK },
    { "CNTR_BUF1_EVICTION", AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_BUF1_EVICTION_BP, AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_BUF1_EVICTION_MASK },
    { "CNTR_BUF1_COMBINE", AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_BUF1_COMBINE_BP, AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_BUF1_COMBINE_MASK },
    { "CNTR_BUF1_ALLOCATION", AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_BUF1_ALLOCATION_BP, AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_BUF1_ALLOCATION_MASK },
    { "CNTR_BUF0_EVICTION", AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_BUF0_EVICTION_BP, AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_BUF0_EVICTION_MASK },
    { "CNTR_BUF0_COMBINE", AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_BUF0_COMBINE_BP, AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_BUF0_COMBINE_MASK },
    { "CNTR_BUF0_ALLOCATION", AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_BUF0_ALLOCATION_BP, AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_BUF0_ALLOCATION_MASK },
    { "CNTR_WC_OUT", AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_WC_OUT_BP, AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_WC_OUT_MASK },
    { "CNTR_WC_IN", AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_WC_IN_BP, AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_WC_IN_MASK },
    { "CNTR_PARB_PUT", AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_PARB_PUT_BP, AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_PARB_PUT_MASK },
    { "CNTR_RAT_GETRESP", AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_RAT_GETRESP_BP, AR_NIC_WC_WC_MMR_RING_0_MID_WC_CNTR_RAT_GETRESP_MASK },
    { "UNUSED_81_64", AR_NIC_WC_WC_MMR_RING_0_MID_WC_UNUSED_81_64_BP, AR_NIC_WC_WC_MMR_RING_0_MID_WC_UNUSED_81_64_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_mmr_ring_0_lo_wc_detail[] = {
    { "UNUSED_145_35", AR_NIC_WC_WC_MMR_RING_0_LO_WC_UNUSED_145_35_BP, AR_NIC_WC_WC_MMR_RING_0_LO_WC_UNUSED_145_35_MASK },
    { "WC_PI_OS_IRQ", AR_NIC_WC_WC_MMR_RING_0_LO_WC_WC_PI_OS_IRQ_BP, AR_NIC_WC_WC_MMR_RING_0_LO_WC_WC_PI_OS_IRQ_MASK },
    { "WC_LB_HSS_IRQ", AR_NIC_WC_WC_MMR_RING_0_LO_WC_WC_LB_HSS_IRQ_BP, AR_NIC_WC_WC_MMR_RING_0_LO_WC_WC_LB_HSS_IRQ_MASK },
    { "R_Q_WC_NETMON_RING_WRACK", AR_NIC_WC_WC_MMR_RING_0_LO_WC_R_Q_WC_NETMON_RING_WRACK_BP, AR_NIC_WC_WC_MMR_RING_0_LO_WC_R_Q_WC_NETMON_RING_WRACK_MASK },
    { "R_Q_WC_NETMON_RING", AR_NIC_WC_WC_MMR_RING_0_LO_WC_R_Q_WC_NETMON_RING_BP, AR_NIC_WC_WC_MMR_RING_0_LO_WC_R_Q_WC_NETMON_RING_MASK },
    { "Q_NETMON_WC_RING", AR_NIC_WC_WC_MMR_RING_0_LO_WC_Q_NETMON_WC_RING_BP, AR_NIC_WC_WC_MMR_RING_0_LO_WC_Q_NETMON_WC_RING_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_err_flg_1_hi_wc_detail[] = {
    { "UNUSED_145_128", AR_NIC_WC_ERR_FLG_1_HI_WC_UNUSED_145_128_BP, AR_NIC_WC_ERR_FLG_1_HI_WC_UNUSED_145_128_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_err_flg_1_mid_wc_detail[] = {
    { "UNUSED_127_92", AR_NIC_WC_ERR_FLG_1_MID_WC_UNUSED_127_92_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_UNUSED_127_92_MASK },
    { "BUFFER_TIMEOUT", AR_NIC_WC_ERR_FLG_1_MID_WC_BUFFER_TIMEOUT_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_BUFFER_TIMEOUT_MASK },
    { "FLUSH_RSP_FIFO_UFLW", AR_NIC_WC_ERR_FLG_1_MID_WC_FLUSH_RSP_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_FLUSH_RSP_FIFO_UFLW_MASK },
    { "FLUSH_RSP_FIFO_OFLW", AR_NIC_WC_ERR_FLG_1_MID_WC_FLUSH_RSP_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_FLUSH_RSP_FIFO_OFLW_MASK },
    { "FLUSH_REQ_FIFO_UFLW", AR_NIC_WC_ERR_FLG_1_MID_WC_FLUSH_REQ_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_FLUSH_REQ_FIFO_UFLW_MASK },
    { "FLUSH_REQ_FIFO_OFLW", AR_NIC_WC_ERR_FLG_1_MID_WC_FLUSH_REQ_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_FLUSH_REQ_FIFO_OFLW_MASK },
    { "RSPOUT1_FIFO_UFLW", AR_NIC_WC_ERR_FLG_1_MID_WC_RSPOUT1_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_RSPOUT1_FIFO_UFLW_MASK },
    { "RSPOUT1_FIFO_OFLW", AR_NIC_WC_ERR_FLG_1_MID_WC_RSPOUT1_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_RSPOUT1_FIFO_OFLW_MASK },
    { "RSPOUT0_FIFO_UFLW", AR_NIC_WC_ERR_FLG_1_MID_WC_RSPOUT0_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_RSPOUT0_FIFO_UFLW_MASK },
    { "RSPOUT0_FIFO_OFLW", AR_NIC_WC_ERR_FLG_1_MID_WC_RSPOUT0_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_RSPOUT0_FIFO_OFLW_MASK },
    { "RSPIN1_FIFO_UFLW", AR_NIC_WC_ERR_FLG_1_MID_WC_RSPIN1_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_RSPIN1_FIFO_UFLW_MASK },
    { "RSPIN1_FIFO_OFLW", AR_NIC_WC_ERR_FLG_1_MID_WC_RSPIN1_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_RSPIN1_FIFO_OFLW_MASK },
    { "RSPIN0_FIFO_UFLW", AR_NIC_WC_ERR_FLG_1_MID_WC_RSPIN0_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_RSPIN0_FIFO_UFLW_MASK },
    { "RSPIN0_FIFO_OFLW", AR_NIC_WC_ERR_FLG_1_MID_WC_RSPIN0_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_RSPIN0_FIFO_OFLW_MASK },
    { "NTWK_RSP_FIFO_UFLW", AR_NIC_WC_ERR_FLG_1_MID_WC_NTWK_RSP_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_NTWK_RSP_FIFO_UFLW_MASK },
    { "NTWK_RSP_FIFO_OFLW", AR_NIC_WC_ERR_FLG_1_MID_WC_NTWK_RSP_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_NTWK_RSP_FIFO_OFLW_MASK },
    { "TAG_PBE", AR_NIC_WC_ERR_FLG_1_MID_WC_TAG_PBE_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_TAG_PBE_MASK },
    { "RSPIN1_HDR_PBE", AR_NIC_WC_ERR_FLG_1_MID_WC_RSPIN1_HDR_PBE_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_RSPIN1_HDR_PBE_MASK },
    { "RSPIN0_HDR_PBE", AR_NIC_WC_ERR_FLG_1_MID_WC_RSPIN0_HDR_PBE_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_RSPIN0_HDR_PBE_MASK },
    { "NTWK_RSP_HDR_PBE", AR_NIC_WC_ERR_FLG_1_MID_WC_NTWK_RSP_HDR_PBE_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_NTWK_RSP_HDR_PBE_MASK },
    { "BUF1_MBE", AR_NIC_WC_ERR_FLG_1_MID_WC_BUF1_MBE_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_BUF1_MBE_MASK },
    { "BUF1_SBE", AR_NIC_WC_ERR_FLG_1_MID_WC_BUF1_SBE_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_BUF1_SBE_MASK },
    { "BUF0_MBE", AR_NIC_WC_ERR_FLG_1_MID_WC_BUF0_MBE_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_BUF0_MBE_MASK },
    { "BUF0_SBE", AR_NIC_WC_ERR_FLG_1_MID_WC_BUF0_SBE_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_BUF0_SBE_MASK },
    { "RSPIN1_DAT_MBE", AR_NIC_WC_ERR_FLG_1_MID_WC_RSPIN1_DAT_MBE_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_RSPIN1_DAT_MBE_MASK },
    { "RSPIN1_DAT_SBE", AR_NIC_WC_ERR_FLG_1_MID_WC_RSPIN1_DAT_SBE_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_RSPIN1_DAT_SBE_MASK },
    { "RSPIN0_DAT_MBE", AR_NIC_WC_ERR_FLG_1_MID_WC_RSPIN0_DAT_MBE_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_RSPIN0_DAT_MBE_MASK },
    { "RSPIN0_DAT_SBE", AR_NIC_WC_ERR_FLG_1_MID_WC_RSPIN0_DAT_SBE_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_RSPIN0_DAT_SBE_MASK },
    { "DIAG_ONLY", AR_NIC_WC_ERR_FLG_1_MID_WC_DIAG_ONLY_BP, AR_NIC_WC_ERR_FLG_1_MID_WC_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_err_flg_1_lo_wc_detail[] = {
    { "UNUSED_63_28", AR_NIC_WC_ERR_FLG_1_LO_WC_UNUSED_63_28_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_UNUSED_63_28_MASK },
    { "I_BUFFER_TIMEOUT", AR_NIC_WC_ERR_FLG_1_LO_WC_I_BUFFER_TIMEOUT_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_BUFFER_TIMEOUT_MASK },
    { "I_FLUSH_RSP_FIFO_UFLW", AR_NIC_WC_ERR_FLG_1_LO_WC_I_FLUSH_RSP_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_FLUSH_RSP_FIFO_UFLW_MASK },
    { "I_FLUSH_RSP_FIFO_OFLW", AR_NIC_WC_ERR_FLG_1_LO_WC_I_FLUSH_RSP_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_FLUSH_RSP_FIFO_OFLW_MASK },
    { "I_FLUSH_REQ_FIFO_UFLW", AR_NIC_WC_ERR_FLG_1_LO_WC_I_FLUSH_REQ_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_FLUSH_REQ_FIFO_UFLW_MASK },
    { "I_FLUSH_REQ_FIFO_OFLW", AR_NIC_WC_ERR_FLG_1_LO_WC_I_FLUSH_REQ_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_FLUSH_REQ_FIFO_OFLW_MASK },
    { "I_RSPOUT1_FIFO_UFLW", AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPOUT1_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPOUT1_FIFO_UFLW_MASK },
    { "I_RSPOUT1_FIFO_OFLW", AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPOUT1_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPOUT1_FIFO_OFLW_MASK },
    { "I_RSPOUT0_FIFO_UFLW", AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPOUT0_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPOUT0_FIFO_UFLW_MASK },
    { "I_RSPOUT0_FIFO_OFLW", AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPOUT0_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPOUT0_FIFO_OFLW_MASK },
    { "I_RSPIN1_FIFO_UFLW", AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPIN1_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPIN1_FIFO_UFLW_MASK },
    { "I_RSPIN1_FIFO_OFLW", AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPIN1_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPIN1_FIFO_OFLW_MASK },
    { "I_RSPIN0_FIFO_UFLW", AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPIN0_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPIN0_FIFO_UFLW_MASK },
    { "I_RSPIN0_FIFO_OFLW", AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPIN0_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPIN0_FIFO_OFLW_MASK },
    { "I_NTWK_RSP_FIFO_UFLW", AR_NIC_WC_ERR_FLG_1_LO_WC_I_NTWK_RSP_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_NTWK_RSP_FIFO_UFLW_MASK },
    { "I_NTWK_RSP_FIFO_OFLW", AR_NIC_WC_ERR_FLG_1_LO_WC_I_NTWK_RSP_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_NTWK_RSP_FIFO_OFLW_MASK },
    { "I_TAG_PBE", AR_NIC_WC_ERR_FLG_1_LO_WC_I_TAG_PBE_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_TAG_PBE_MASK },
    { "I_RSPIN1_HDR_PBE", AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPIN1_HDR_PBE_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPIN1_HDR_PBE_MASK },
    { "I_RSPIN0_HDR_PBE", AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPIN0_HDR_PBE_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPIN0_HDR_PBE_MASK },
    { "I_NTWK_RSP_HDR_PBE", AR_NIC_WC_ERR_FLG_1_LO_WC_I_NTWK_RSP_HDR_PBE_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_NTWK_RSP_HDR_PBE_MASK },
    { "I_BUF1_MBE", AR_NIC_WC_ERR_FLG_1_LO_WC_I_BUF1_MBE_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_BUF1_MBE_MASK },
    { "I_BUF1_SBE", AR_NIC_WC_ERR_FLG_1_LO_WC_I_BUF1_SBE_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_BUF1_SBE_MASK },
    { "I_BUF0_MBE", AR_NIC_WC_ERR_FLG_1_LO_WC_I_BUF0_MBE_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_BUF0_MBE_MASK },
    { "I_BUF0_SBE", AR_NIC_WC_ERR_FLG_1_LO_WC_I_BUF0_SBE_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_BUF0_SBE_MASK },
    { "I_RSPIN1_DAT_MBE", AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPIN1_DAT_MBE_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPIN1_DAT_MBE_MASK },
    { "I_RSPIN1_DAT_SBE", AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPIN1_DAT_SBE_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPIN1_DAT_SBE_MASK },
    { "I_RSPIN0_DAT_MBE", AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPIN0_DAT_MBE_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPIN0_DAT_MBE_MASK },
    { "I_RSPIN0_DAT_SBE", AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPIN0_DAT_SBE_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_I_RSPIN0_DAT_SBE_MASK },
    { "UNUSED_0", AR_NIC_WC_ERR_FLG_1_LO_WC_UNUSED_0_BP, AR_NIC_WC_ERR_FLG_1_LO_WC_UNUSED_0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_parb_flit_2_hi_wc_detail[] = {
    { "Q_LM_PARB_SB", AR_NIC_WC_WC_PARB_FLIT_2_HI_WC_Q_LM_PARB_SB_BP, AR_NIC_WC_WC_PARB_FLIT_2_HI_WC_Q_LM_PARB_SB_MASK },
    { "Q_LM_PARB_FLIT", AR_NIC_WC_WC_PARB_FLIT_2_HI_WC_Q_LM_PARB_FLIT_BP, AR_NIC_WC_WC_PARB_FLIT_2_HI_WC_Q_LM_PARB_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_parb_flit_2_mid_wc_detail[] = {
    { "Q_LM_PARB_FLIT", AR_NIC_WC_WC_PARB_FLIT_2_MID_WC_Q_LM_PARB_FLIT_BP, AR_NIC_WC_WC_PARB_FLIT_2_MID_WC_Q_LM_PARB_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_parb_flit_2_lo_wc_detail[] = {
    { "Q_LM_PARB_FLIT", AR_NIC_WC_WC_PARB_FLIT_2_LO_WC_Q_LM_PARB_FLIT_BP, AR_NIC_WC_WC_PARB_FLIT_2_LO_WC_Q_LM_PARB_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_ssid_rsp_flit_3_hi_wc_detail[] = {
    { "Q_LM_NTWK_RSP_SB", AR_NIC_WC_WC_SSID_RSP_FLIT_3_HI_WC_Q_LM_NTWK_RSP_SB_BP, AR_NIC_WC_WC_SSID_RSP_FLIT_3_HI_WC_Q_LM_NTWK_RSP_SB_MASK },
    { "Q_LM_NTWK_RSP_FLIT", AR_NIC_WC_WC_SSID_RSP_FLIT_3_HI_WC_Q_LM_NTWK_RSP_FLIT_BP, AR_NIC_WC_WC_SSID_RSP_FLIT_3_HI_WC_Q_LM_NTWK_RSP_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_ssid_rsp_flit_3_mid_wc_detail[] = {
    { "Q_LM_NTWK_RSP_FLIT", AR_NIC_WC_WC_SSID_RSP_FLIT_3_MID_WC_Q_LM_NTWK_RSP_FLIT_BP, AR_NIC_WC_WC_SSID_RSP_FLIT_3_MID_WC_Q_LM_NTWK_RSP_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_ssid_rsp_flit_3_lo_wc_detail[] = {
    { "Q_LM_NTWK_RSP_FLIT", AR_NIC_WC_WC_SSID_RSP_FLIT_3_LO_WC_Q_LM_NTWK_RSP_FLIT_BP, AR_NIC_WC_WC_SSID_RSP_FLIT_3_LO_WC_Q_LM_NTWK_RSP_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_top_misc_4_hi_wc_detail[] = {
    { "UNUSED_145_120", AR_NIC_WC_WC_TOP_MISC_4_HI_WC_UNUSED_145_120_BP, AR_NIC_WC_WC_TOP_MISC_4_HI_WC_UNUSED_145_120_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_top_misc_4_mid_wc_detail[] = {
    { "UNUSED_145_120", AR_NIC_WC_WC_TOP_MISC_4_MID_WC_UNUSED_145_120_BP, AR_NIC_WC_WC_TOP_MISC_4_MID_WC_UNUSED_145_120_MASK },
    { "Q_ARB_TAG_ERR", AR_NIC_WC_WC_TOP_MISC_4_MID_WC_Q_ARB_TAG_ERR_BP, AR_NIC_WC_WC_TOP_MISC_4_MID_WC_Q_ARB_TAG_ERR_MASK },
    { "Q_ARB_REQ", AR_NIC_WC_WC_TOP_MISC_4_MID_WC_Q_ARB_REQ_BP, AR_NIC_WC_WC_TOP_MISC_4_MID_WC_Q_ARB_REQ_MASK },
    { "Q_ARB_GNT", AR_NIC_WC_WC_TOP_MISC_4_MID_WC_Q_ARB_GNT_BP, AR_NIC_WC_WC_TOP_MISC_4_MID_WC_Q_ARB_GNT_MASK },
    { "UNUSED_112_110", AR_NIC_WC_WC_TOP_MISC_4_MID_WC_UNUSED_112_110_BP, AR_NIC_WC_WC_TOP_MISC_4_MID_WC_UNUSED_112_110_MASK },
    { "Q_ARB_ERR", AR_NIC_WC_WC_TOP_MISC_4_MID_WC_Q_ARB_ERR_BP, AR_NIC_WC_WC_TOP_MISC_4_MID_WC_Q_ARB_ERR_MASK },
    { "Q_NTWK_RSP_HEAD", AR_NIC_WC_WC_TOP_MISC_4_MID_WC_Q_NTWK_RSP_HEAD_BP, AR_NIC_WC_WC_TOP_MISC_4_MID_WC_Q_NTWK_RSP_HEAD_MASK },
    { "Q_NTWK_RSP_GO_DATA", AR_NIC_WC_WC_TOP_MISC_4_MID_WC_Q_NTWK_RSP_GO_DATA_BP, AR_NIC_WC_WC_TOP_MISC_4_MID_WC_Q_NTWK_RSP_GO_DATA_MASK },
    { "Q_NTWK_RSP_GO", AR_NIC_WC_WC_TOP_MISC_4_MID_WC_Q_NTWK_RSP_GO_BP, AR_NIC_WC_WC_TOP_MISC_4_MID_WC_Q_NTWK_RSP_GO_MASK },
    { "Q_NTWK_RSP_BUF0", AR_NIC_WC_WC_TOP_MISC_4_MID_WC_Q_NTWK_RSP_BUF0_BP, AR_NIC_WC_WC_TOP_MISC_4_MID_WC_Q_NTWK_RSP_BUF0_MASK },
    { "Q_NTWK_RSP_BUF1", AR_NIC_WC_WC_TOP_MISC_4_MID_WC_Q_NTWK_RSP_BUF1_BP, AR_NIC_WC_WC_TOP_MISC_4_MID_WC_Q_NTWK_RSP_BUF1_MASK },
    { "Q_NTWK_RSP_GETRESP", AR_NIC_WC_WC_TOP_MISC_4_MID_WC_Q_NTWK_RSP_GETRESP_BP, AR_NIC_WC_WC_TOP_MISC_4_MID_WC_Q_NTWK_RSP_GETRESP_MASK },
    { "Q_NTWK_RSP_BUF", AR_NIC_WC_WC_TOP_MISC_4_MID_WC_Q_NTWK_RSP_BUF_BP, AR_NIC_WC_WC_TOP_MISC_4_MID_WC_Q_NTWK_RSP_BUF_MASK },
    { "RSPOUT1_COUNT", AR_NIC_WC_WC_TOP_MISC_4_MID_WC_RSPOUT1_COUNT_BP, AR_NIC_WC_WC_TOP_MISC_4_MID_WC_RSPOUT1_COUNT_MASK },
    { "RSPOUT0_COUNT", AR_NIC_WC_WC_TOP_MISC_4_MID_WC_RSPOUT0_COUNT_BP, AR_NIC_WC_WC_TOP_MISC_4_MID_WC_RSPOUT0_COUNT_MASK },
    { "PARB_REQ_COUNT", AR_NIC_WC_WC_TOP_MISC_4_MID_WC_PARB_REQ_COUNT_BP, AR_NIC_WC_WC_TOP_MISC_4_MID_WC_PARB_REQ_COUNT_MASK },
    { "SSID_RSP_COUNT", AR_NIC_WC_WC_TOP_MISC_4_MID_WC_SSID_RSP_COUNT_BP, AR_NIC_WC_WC_TOP_MISC_4_MID_WC_SSID_RSP_COUNT_MASK },
    { "SSID_FL_RSP_COUNT", AR_NIC_WC_WC_TOP_MISC_4_MID_WC_SSID_FL_RSP_COUNT_BP, AR_NIC_WC_WC_TOP_MISC_4_MID_WC_SSID_FL_RSP_COUNT_MASK },
    { "BUF1_REQ_COUNT", AR_NIC_WC_WC_TOP_MISC_4_MID_WC_BUF1_REQ_COUNT_BP, AR_NIC_WC_WC_TOP_MISC_4_MID_WC_BUF1_REQ_COUNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_top_misc_4_lo_wc_detail[] = {
    { "BUF1_REQ_COUNT", AR_NIC_WC_WC_TOP_MISC_4_LO_WC_BUF1_REQ_COUNT_BP, AR_NIC_WC_WC_TOP_MISC_4_LO_WC_BUF1_REQ_COUNT_MASK },
    { "BUF0_REQ_COUNT", AR_NIC_WC_WC_TOP_MISC_4_LO_WC_BUF0_REQ_COUNT_BP, AR_NIC_WC_WC_TOP_MISC_4_LO_WC_BUF0_REQ_COUNT_MASK },
    { "FLUSH_RSP_COUNT", AR_NIC_WC_WC_TOP_MISC_4_LO_WC_FLUSH_RSP_COUNT_BP, AR_NIC_WC_WC_TOP_MISC_4_LO_WC_FLUSH_RSP_COUNT_MASK },
    { "Q_LM_COMP_WAIT_SG1_DONE", AR_NIC_WC_WC_TOP_MISC_4_LO_WC_Q_LM_COMP_WAIT_SG1_DONE_BP, AR_NIC_WC_WC_TOP_MISC_4_LO_WC_Q_LM_COMP_WAIT_SG1_DONE_MASK },
    { "Q_COMP_WAIT_SG1", AR_NIC_WC_WC_TOP_MISC_4_LO_WC_Q_COMP_WAIT_SG1_BP, AR_NIC_WC_WC_TOP_MISC_4_LO_WC_Q_COMP_WAIT_SG1_MASK },
    { "Q_COMP_WAIT_SG0_DONE", AR_NIC_WC_WC_TOP_MISC_4_LO_WC_Q_COMP_WAIT_SG0_DONE_BP, AR_NIC_WC_WC_TOP_MISC_4_LO_WC_Q_COMP_WAIT_SG0_DONE_MASK },
    { "Q_COMP_WAIT_SG0", AR_NIC_WC_WC_TOP_MISC_4_LO_WC_Q_COMP_WAIT_SG0_BP, AR_NIC_WC_WC_TOP_MISC_4_LO_WC_Q_COMP_WAIT_SG0_MASK },
    { "Q_IOMMU_WC_COMP_WAIT_REQ", AR_NIC_WC_WC_TOP_MISC_4_LO_WC_Q_IOMMU_WC_COMP_WAIT_REQ_BP, AR_NIC_WC_WC_TOP_MISC_4_LO_WC_Q_IOMMU_WC_COMP_WAIT_REQ_MASK },
    { "NXT_FLUSH_RSP_OUT", AR_NIC_WC_WC_TOP_MISC_4_LO_WC_NXT_FLUSH_RSP_OUT_BP, AR_NIC_WC_WC_TOP_MISC_4_LO_WC_NXT_FLUSH_RSP_OUT_MASK },
    { "FLUSH_RSP_FIFO_RDATA", AR_NIC_WC_WC_TOP_MISC_4_LO_WC_FLUSH_RSP_FIFO_RDATA_BP, AR_NIC_WC_WC_TOP_MISC_4_LO_WC_FLUSH_RSP_FIFO_RDATA_MASK },
    { "Q_FLUSH_RSP_CMPLT_PEND", AR_NIC_WC_WC_TOP_MISC_4_LO_WC_Q_FLUSH_RSP_CMPLT_PEND_BP, AR_NIC_WC_WC_TOP_MISC_4_LO_WC_Q_FLUSH_RSP_CMPLT_PEND_MASK },
    { "GO_FLUSH_RSP_OUT", AR_NIC_WC_WC_TOP_MISC_4_LO_WC_GO_FLUSH_RSP_OUT_BP, AR_NIC_WC_WC_TOP_MISC_4_LO_WC_GO_FLUSH_RSP_OUT_MASK },
    { "Q_LM_FLUSH_RSP_OUT_VLD", AR_NIC_WC_WC_TOP_MISC_4_LO_WC_Q_LM_FLUSH_RSP_OUT_VLD_BP, AR_NIC_WC_WC_TOP_MISC_4_LO_WC_Q_LM_FLUSH_RSP_OUT_VLD_MASK },
    { "Q_LM_FLUSH_RSP_OUT_CMPLT", AR_NIC_WC_WC_TOP_MISC_4_LO_WC_Q_LM_FLUSH_RSP_OUT_CMPLT_BP, AR_NIC_WC_WC_TOP_MISC_4_LO_WC_Q_LM_FLUSH_RSP_OUT_CMPLT_MASK },
    { "Q_LM_FLUSH_RSP_OUT_SSID", AR_NIC_WC_WC_TOP_MISC_4_LO_WC_Q_LM_FLUSH_RSP_OUT_SSID_BP, AR_NIC_WC_WC_TOP_MISC_4_LO_WC_Q_LM_FLUSH_RSP_OUT_SSID_MASK },
    { "Q_LM_FLUSH_RSP_OUT_STATUS", AR_NIC_WC_WC_TOP_MISC_4_LO_WC_Q_LM_FLUSH_RSP_OUT_STATUS_BP, AR_NIC_WC_WC_TOP_MISC_4_LO_WC_Q_LM_FLUSH_RSP_OUT_STATUS_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_flush_misc_5_hi_wc_detail[] = {
    { "UNUSED_145_122", AR_NIC_WC_WC_FLUSH_MISC_5_HI_WC_UNUSED_145_122_BP, AR_NIC_WC_WC_FLUSH_MISC_5_HI_WC_UNUSED_145_122_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_flush_misc_5_mid_wc_detail[] = {
    { "UNUSED_145_122", AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC_UNUSED_145_122_BP, AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC_UNUSED_145_122_MASK },
    { "R_Q_OVFLOW", AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC_R_Q_OVFLOW_BP, AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC_R_Q_OVFLOW_MASK },
    { "R_Q_UNFLOW", AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC_R_Q_UNFLOW_BP, AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC_R_Q_UNFLOW_MASK },
    { "Q_WADDR", AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC_Q_WADDR_BP, AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC_Q_WADDR_MASK },
    { "Q_FLUSH_REQ_VLD", AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC_Q_FLUSH_REQ_VLD_BP, AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC_Q_FLUSH_REQ_VLD_MASK },
    { "Q_FLUSH_REQ_SSID", AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC_Q_FLUSH_REQ_SSID_BP, AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC_Q_FLUSH_REQ_SSID_MASK },
    { "R_FLUSH_RSP_VLD", AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC_R_FLUSH_RSP_VLD_BP, AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC_R_FLUSH_RSP_VLD_MASK },
    { "R_FLUSH_RSP_SSID", AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC_R_FLUSH_RSP_SSID_BP, AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC_R_FLUSH_RSP_SSID_MASK },
    { "FLUSH_DONE", AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC_FLUSH_DONE_BP, AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC_FLUSH_DONE_MASK },
    { "Q_VLD", AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC_Q_VLD_BP, AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC_Q_VLD_MASK },
    { "R_FLUSH_SSID7", AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC_R_FLUSH_SSID7_BP, AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC_R_FLUSH_SSID7_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_flush_misc_5_lo_wc_detail[] = {
    { "R_FLUSH_SSID7", AR_NIC_WC_WC_FLUSH_MISC_5_LO_WC_R_FLUSH_SSID7_BP, AR_NIC_WC_WC_FLUSH_MISC_5_LO_WC_R_FLUSH_SSID7_MASK },
    { "R_FLUSH_SSID6", AR_NIC_WC_WC_FLUSH_MISC_5_LO_WC_R_FLUSH_SSID6_BP, AR_NIC_WC_WC_FLUSH_MISC_5_LO_WC_R_FLUSH_SSID6_MASK },
    { "R_FLUSH_SSID5", AR_NIC_WC_WC_FLUSH_MISC_5_LO_WC_R_FLUSH_SSID5_BP, AR_NIC_WC_WC_FLUSH_MISC_5_LO_WC_R_FLUSH_SSID5_MASK },
    { "R_FLUSH_SSID4", AR_NIC_WC_WC_FLUSH_MISC_5_LO_WC_R_FLUSH_SSID4_BP, AR_NIC_WC_WC_FLUSH_MISC_5_LO_WC_R_FLUSH_SSID4_MASK },
    { "R_FLUSH_SSID3", AR_NIC_WC_WC_FLUSH_MISC_5_LO_WC_R_FLUSH_SSID3_BP, AR_NIC_WC_WC_FLUSH_MISC_5_LO_WC_R_FLUSH_SSID3_MASK },
    { "R_FLUSH_SSID2", AR_NIC_WC_WC_FLUSH_MISC_5_LO_WC_R_FLUSH_SSID2_BP, AR_NIC_WC_WC_FLUSH_MISC_5_LO_WC_R_FLUSH_SSID2_MASK },
    { "R_FLUSH_SSID1", AR_NIC_WC_WC_FLUSH_MISC_5_LO_WC_R_FLUSH_SSID1_BP, AR_NIC_WC_WC_FLUSH_MISC_5_LO_WC_R_FLUSH_SSID1_MASK },
    { "R_FLUSH_SSID0", AR_NIC_WC_WC_FLUSH_MISC_5_LO_WC_R_FLUSH_SSID0_BP, AR_NIC_WC_WC_FLUSH_MISC_5_LO_WC_R_FLUSH_SSID0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf0_rspin_flit_6_hi_wc_detail[] = {
    { "RSPIN_TAIL", AR_NIC_WC_WC_BUF0_RSPIN_FLIT_6_HI_WC_RSPIN_TAIL_BP, AR_NIC_WC_WC_BUF0_RSPIN_FLIT_6_HI_WC_RSPIN_TAIL_MASK },
    { "RSPIN_VLD", AR_NIC_WC_WC_BUF0_RSPIN_FLIT_6_HI_WC_RSPIN_VLD_BP, AR_NIC_WC_WC_BUF0_RSPIN_FLIT_6_HI_WC_RSPIN_VLD_MASK },
    { "RSPIN_FLIT", AR_NIC_WC_WC_BUF0_RSPIN_FLIT_6_HI_WC_RSPIN_FLIT_BP, AR_NIC_WC_WC_BUF0_RSPIN_FLIT_6_HI_WC_RSPIN_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf0_rspin_flit_6_mid_wc_detail[] = {
    { "RSPIN_FLIT", AR_NIC_WC_WC_BUF0_RSPIN_FLIT_6_MID_WC_RSPIN_FLIT_BP, AR_NIC_WC_WC_BUF0_RSPIN_FLIT_6_MID_WC_RSPIN_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf0_rspin_flit_6_lo_wc_detail[] = {
    { "RSPIN_FLIT", AR_NIC_WC_WC_BUF0_RSPIN_FLIT_6_LO_WC_RSPIN_FLIT_BP, AR_NIC_WC_WC_BUF0_RSPIN_FLIT_6_LO_WC_RSPIN_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf0_lm_data1_7_hi_wc_detail[] = {
    { "UNUSED_145_135", AR_NIC_WC_WC_BUF0_LM_DATA1_7_HI_WC_UNUSED_145_135_BP, AR_NIC_WC_WC_BUF0_LM_DATA1_7_HI_WC_UNUSED_145_135_MASK },
    { "NO_MATCH_SG0", AR_NIC_WC_WC_BUF0_LM_DATA1_7_HI_WC_NO_MATCH_SG0_BP, AR_NIC_WC_WC_BUF0_LM_DATA1_7_HI_WC_NO_MATCH_SG0_MASK },
    { "Q_RSPIN_GO_DATA_SG0", AR_NIC_WC_WC_BUF0_LM_DATA1_7_HI_WC_Q_RSPIN_GO_DATA_SG0_BP, AR_NIC_WC_WC_BUF0_LM_DATA1_7_HI_WC_Q_RSPIN_GO_DATA_SG0_MASK },
    { "Q_RSPIN_GO_VLD_HD_SG0", AR_NIC_WC_WC_BUF0_LM_DATA1_7_HI_WC_Q_RSPIN_GO_VLD_HD_SG0_BP, AR_NIC_WC_WC_BUF0_LM_DATA1_7_HI_WC_Q_RSPIN_GO_VLD_HD_SG0_MASK },
    { "Q_RSPIN_COLOR_SG0", AR_NIC_WC_WC_BUF0_LM_DATA1_7_HI_WC_Q_RSPIN_COLOR_SG0_BP, AR_NIC_WC_WC_BUF0_LM_DATA1_7_HI_WC_Q_RSPIN_COLOR_SG0_MASK },
    { "Q_RSPIN_SSID_SG0", AR_NIC_WC_WC_BUF0_LM_DATA1_7_HI_WC_Q_RSPIN_SSID_SG0_BP, AR_NIC_WC_WC_BUF0_LM_DATA1_7_HI_WC_Q_RSPIN_SSID_SG0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf0_lm_data1_7_mid_wc_detail[] = {
    { "Q_RSPIN_SSID_SG0", AR_NIC_WC_WC_BUF0_LM_DATA1_7_MID_WC_Q_RSPIN_SSID_SG0_BP, AR_NIC_WC_WC_BUF0_LM_DATA1_7_MID_WC_Q_RSPIN_SSID_SG0_MASK },
    { "Q_RSPIN_MASK_SG0", AR_NIC_WC_WC_BUF0_LM_DATA1_7_MID_WC_Q_RSPIN_MASK_SG0_BP, AR_NIC_WC_WC_BUF0_LM_DATA1_7_MID_WC_Q_RSPIN_MASK_SG0_MASK },
    { "Q_RSPIN_ADDR_SG0", AR_NIC_WC_WC_BUF0_LM_DATA1_7_MID_WC_Q_RSPIN_ADDR_SG0_BP, AR_NIC_WC_WC_BUF0_LM_DATA1_7_MID_WC_Q_RSPIN_ADDR_SG0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf0_lm_data1_7_lo_wc_detail[] = {
    { "COMBINE_SG0", AR_NIC_WC_WC_BUF0_LM_DATA1_7_LO_WC_COMBINE_SG0_BP, AR_NIC_WC_WC_BUF0_LM_DATA1_7_LO_WC_COMBINE_SG0_MASK },
    { "ALLOCATE_SG0", AR_NIC_WC_WC_BUF0_LM_DATA1_7_LO_WC_ALLOCATE_SG0_BP, AR_NIC_WC_WC_BUF0_LM_DATA1_7_LO_WC_ALLOCATE_SG0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf0_lm_data2_8_hi_wc_detail[] = {
    { "UNUSED_145_143", AR_NIC_WC_WC_BUF0_LM_DATA2_8_HI_WC_UNUSED_145_143_BP, AR_NIC_WC_WC_BUF0_LM_DATA2_8_HI_WC_UNUSED_145_143_MASK },
    { "Q_GO_ARB_SG0", AR_NIC_WC_WC_BUF0_LM_DATA2_8_HI_WC_Q_GO_ARB_SG0_BP, AR_NIC_WC_WC_BUF0_LM_DATA2_8_HI_WC_Q_GO_ARB_SG0_MASK },
    { "Q_PKT_BSY_SG0", AR_NIC_WC_WC_BUF0_LM_DATA2_8_HI_WC_Q_PKT_BSY_SG0_BP, AR_NIC_WC_WC_BUF0_LM_DATA2_8_HI_WC_Q_PKT_BSY_SG0_MASK },
    { "Q_PKT_ADDR_SG0", AR_NIC_WC_WC_BUF0_LM_DATA2_8_HI_WC_Q_PKT_ADDR_SG0_BP, AR_NIC_WC_WC_BUF0_LM_DATA2_8_HI_WC_Q_PKT_ADDR_SG0_MASK },
    { "Q_PKT_LENGTH_SG0", AR_NIC_WC_WC_BUF0_LM_DATA2_8_HI_WC_Q_PKT_LENGTH_SG0_BP, AR_NIC_WC_WC_BUF0_LM_DATA2_8_HI_WC_Q_PKT_LENGTH_SG0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf0_lm_data2_8_mid_wc_detail[] = {
    { "ARB_FLUSH_REQ_PEND_X_1", AR_NIC_WC_WC_BUF0_LM_DATA2_8_MID_WC_ARB_FLUSH_REQ_PEND_X_1_BP, AR_NIC_WC_WC_BUF0_LM_DATA2_8_MID_WC_ARB_FLUSH_REQ_PEND_X_1_MASK },
    { "ARB_FLUSH_REQ_X_1", AR_NIC_WC_WC_BUF0_LM_DATA2_8_MID_WC_ARB_FLUSH_REQ_X_1_BP, AR_NIC_WC_WC_BUF0_LM_DATA2_8_MID_WC_ARB_FLUSH_REQ_X_1_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf0_lm_data2_8_lo_wc_detail[] = {
    { "ARB_REQ", AR_NIC_WC_WC_BUF0_LM_DATA2_8_LO_WC_ARB_REQ_BP, AR_NIC_WC_WC_BUF0_LM_DATA2_8_LO_WC_ARB_REQ_MASK },
    { "ARB_REQ_PEND", AR_NIC_WC_WC_BUF0_LM_DATA2_8_LO_WC_ARB_REQ_PEND_BP, AR_NIC_WC_WC_BUF0_LM_DATA2_8_LO_WC_ARB_REQ_PEND_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf0_lm_data3_9_hi_wc_detail[] = {
    { "UNUSED_145_130", AR_NIC_WC_WC_BUF0_LM_DATA3_9_HI_WC_UNUSED_145_130_BP, AR_NIC_WC_WC_BUF0_LM_DATA3_9_HI_WC_UNUSED_145_130_MASK },
    { "R_Q_BUFFER_TIMEOUT", AR_NIC_WC_WC_BUF0_LM_DATA3_9_HI_WC_R_Q_BUFFER_TIMEOUT_BP, AR_NIC_WC_WC_BUF0_LM_DATA3_9_HI_WC_R_Q_BUFFER_TIMEOUT_MASK },
    { "Q_GO_EVICT_SG0", AR_NIC_WC_WC_BUF0_LM_DATA3_9_HI_WC_Q_GO_EVICT_SG0_BP, AR_NIC_WC_WC_BUF0_LM_DATA3_9_HI_WC_Q_GO_EVICT_SG0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf0_lm_data3_9_mid_wc_detail[] = {
    { "BUFFER_TIMEOUT", AR_NIC_WC_WC_BUF0_LM_DATA3_9_MID_WC_BUFFER_TIMEOUT_BP, AR_NIC_WC_WC_BUF0_LM_DATA3_9_MID_WC_BUFFER_TIMEOUT_MASK },
    { "EVICT", AR_NIC_WC_WC_BUF0_LM_DATA3_9_MID_WC_EVICT_BP, AR_NIC_WC_WC_BUF0_LM_DATA3_9_MID_WC_EVICT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf0_lm_data3_9_lo_wc_detail[] = {
    { "BUFFER_AVAIL", AR_NIC_WC_WC_BUF0_LM_DATA3_9_LO_WC_BUFFER_AVAIL_BP, AR_NIC_WC_WC_BUF0_LM_DATA3_9_LO_WC_BUFFER_AVAIL_MASK },
    { "BUFFER_VALID", AR_NIC_WC_WC_BUF0_LM_DATA3_9_LO_WC_BUFFER_VALID_BP, AR_NIC_WC_WC_BUF0_LM_DATA3_9_LO_WC_BUFFER_VALID_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf0_rspout_flit_a_hi_wc_detail[] = {
    { "I_RSPOUT_RD", AR_NIC_WC_WC_BUF0_RSPOUT_FLIT_A_HI_WC_I_RSPOUT_RD_BP, AR_NIC_WC_WC_BUF0_RSPOUT_FLIT_A_HI_WC_I_RSPOUT_RD_MASK },
    { "R_RSPOUT_ERR", AR_NIC_WC_WC_BUF0_RSPOUT_FLIT_A_HI_WC_R_RSPOUT_ERR_BP, AR_NIC_WC_WC_BUF0_RSPOUT_FLIT_A_HI_WC_R_RSPOUT_ERR_MASK },
    { "R_RSPOUT_TAIL", AR_NIC_WC_WC_BUF0_RSPOUT_FLIT_A_HI_WC_R_RSPOUT_TAIL_BP, AR_NIC_WC_WC_BUF0_RSPOUT_FLIT_A_HI_WC_R_RSPOUT_TAIL_MASK },
    { "RSPOUT_FIFO_FLIT", AR_NIC_WC_WC_BUF0_RSPOUT_FLIT_A_HI_WC_RSPOUT_FIFO_FLIT_BP, AR_NIC_WC_WC_BUF0_RSPOUT_FLIT_A_HI_WC_RSPOUT_FIFO_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf0_rspout_flit_a_mid_wc_detail[] = {
    { "RSPOUT_FIFO_FLIT", AR_NIC_WC_WC_BUF0_RSPOUT_FLIT_A_MID_WC_RSPOUT_FIFO_FLIT_BP, AR_NIC_WC_WC_BUF0_RSPOUT_FLIT_A_MID_WC_RSPOUT_FIFO_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf0_rspout_flit_a_lo_wc_detail[] = {
    { "RSPOUT_FIFO_FLIT", AR_NIC_WC_WC_BUF0_RSPOUT_FLIT_A_LO_WC_RSPOUT_FIFO_FLIT_BP, AR_NIC_WC_WC_BUF0_RSPOUT_FLIT_A_LO_WC_RSPOUT_FIFO_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf1_rspin_flit_b_hi_wc_detail[] = {
    { "RSPIN_TAIL", AR_NIC_WC_WC_BUF1_RSPIN_FLIT_B_HI_WC_RSPIN_TAIL_BP, AR_NIC_WC_WC_BUF1_RSPIN_FLIT_B_HI_WC_RSPIN_TAIL_MASK },
    { "RSPIN_VLD", AR_NIC_WC_WC_BUF1_RSPIN_FLIT_B_HI_WC_RSPIN_VLD_BP, AR_NIC_WC_WC_BUF1_RSPIN_FLIT_B_HI_WC_RSPIN_VLD_MASK },
    { "RSPIN_FLIT", AR_NIC_WC_WC_BUF1_RSPIN_FLIT_B_HI_WC_RSPIN_FLIT_BP, AR_NIC_WC_WC_BUF1_RSPIN_FLIT_B_HI_WC_RSPIN_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf1_rspin_flit_b_mid_wc_detail[] = {
    { "RSPIN_FLIT", AR_NIC_WC_WC_BUF1_RSPIN_FLIT_B_MID_WC_RSPIN_FLIT_BP, AR_NIC_WC_WC_BUF1_RSPIN_FLIT_B_MID_WC_RSPIN_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf1_rspin_flit_b_lo_wc_detail[] = {
    { "RSPIN_FLIT", AR_NIC_WC_WC_BUF1_RSPIN_FLIT_B_LO_WC_RSPIN_FLIT_BP, AR_NIC_WC_WC_BUF1_RSPIN_FLIT_B_LO_WC_RSPIN_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf1_lm_data1_c_hi_wc_detail[] = {
    { "UNUSED_145_135", AR_NIC_WC_WC_BUF1_LM_DATA1_C_HI_WC_UNUSED_145_135_BP, AR_NIC_WC_WC_BUF1_LM_DATA1_C_HI_WC_UNUSED_145_135_MASK },
    { "NO_MATCH_SG0", AR_NIC_WC_WC_BUF1_LM_DATA1_C_HI_WC_NO_MATCH_SG0_BP, AR_NIC_WC_WC_BUF1_LM_DATA1_C_HI_WC_NO_MATCH_SG0_MASK },
    { "Q_RSPIN_GO_DATA_SG0", AR_NIC_WC_WC_BUF1_LM_DATA1_C_HI_WC_Q_RSPIN_GO_DATA_SG0_BP, AR_NIC_WC_WC_BUF1_LM_DATA1_C_HI_WC_Q_RSPIN_GO_DATA_SG0_MASK },
    { "Q_RSPIN_GO_VLD_HD_SG0", AR_NIC_WC_WC_BUF1_LM_DATA1_C_HI_WC_Q_RSPIN_GO_VLD_HD_SG0_BP, AR_NIC_WC_WC_BUF1_LM_DATA1_C_HI_WC_Q_RSPIN_GO_VLD_HD_SG0_MASK },
    { "Q_RSPIN_COLOR_SG0", AR_NIC_WC_WC_BUF1_LM_DATA1_C_HI_WC_Q_RSPIN_COLOR_SG0_BP, AR_NIC_WC_WC_BUF1_LM_DATA1_C_HI_WC_Q_RSPIN_COLOR_SG0_MASK },
    { "Q_RSPIN_SSID_SG0", AR_NIC_WC_WC_BUF1_LM_DATA1_C_HI_WC_Q_RSPIN_SSID_SG0_BP, AR_NIC_WC_WC_BUF1_LM_DATA1_C_HI_WC_Q_RSPIN_SSID_SG0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf1_lm_data1_c_mid_wc_detail[] = {
    { "Q_RSPIN_SSID_SG0", AR_NIC_WC_WC_BUF1_LM_DATA1_C_MID_WC_Q_RSPIN_SSID_SG0_BP, AR_NIC_WC_WC_BUF1_LM_DATA1_C_MID_WC_Q_RSPIN_SSID_SG0_MASK },
    { "Q_RSPIN_MASK_SG0", AR_NIC_WC_WC_BUF1_LM_DATA1_C_MID_WC_Q_RSPIN_MASK_SG0_BP, AR_NIC_WC_WC_BUF1_LM_DATA1_C_MID_WC_Q_RSPIN_MASK_SG0_MASK },
    { "Q_RSPIN_ADDR_SG0", AR_NIC_WC_WC_BUF1_LM_DATA1_C_MID_WC_Q_RSPIN_ADDR_SG0_BP, AR_NIC_WC_WC_BUF1_LM_DATA1_C_MID_WC_Q_RSPIN_ADDR_SG0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf1_lm_data1_c_lo_wc_detail[] = {
    { "COMBINE_SG0", AR_NIC_WC_WC_BUF1_LM_DATA1_C_LO_WC_COMBINE_SG0_BP, AR_NIC_WC_WC_BUF1_LM_DATA1_C_LO_WC_COMBINE_SG0_MASK },
    { "ALLOCATE_SG0", AR_NIC_WC_WC_BUF1_LM_DATA1_C_LO_WC_ALLOCATE_SG0_BP, AR_NIC_WC_WC_BUF1_LM_DATA1_C_LO_WC_ALLOCATE_SG0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf1_lm_data2_d_hi_wc_detail[] = {
    { "UNUSED_145_143", AR_NIC_WC_WC_BUF1_LM_DATA2_D_HI_WC_UNUSED_145_143_BP, AR_NIC_WC_WC_BUF1_LM_DATA2_D_HI_WC_UNUSED_145_143_MASK },
    { "Q_GO_ARB_SG0", AR_NIC_WC_WC_BUF1_LM_DATA2_D_HI_WC_Q_GO_ARB_SG0_BP, AR_NIC_WC_WC_BUF1_LM_DATA2_D_HI_WC_Q_GO_ARB_SG0_MASK },
    { "Q_PKT_BSY_SG0", AR_NIC_WC_WC_BUF1_LM_DATA2_D_HI_WC_Q_PKT_BSY_SG0_BP, AR_NIC_WC_WC_BUF1_LM_DATA2_D_HI_WC_Q_PKT_BSY_SG0_MASK },
    { "Q_PKT_ADDR_SG0", AR_NIC_WC_WC_BUF1_LM_DATA2_D_HI_WC_Q_PKT_ADDR_SG0_BP, AR_NIC_WC_WC_BUF1_LM_DATA2_D_HI_WC_Q_PKT_ADDR_SG0_MASK },
    { "Q_PKT_LENGTH_SG0", AR_NIC_WC_WC_BUF1_LM_DATA2_D_HI_WC_Q_PKT_LENGTH_SG0_BP, AR_NIC_WC_WC_BUF1_LM_DATA2_D_HI_WC_Q_PKT_LENGTH_SG0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf1_lm_data2_d_mid_wc_detail[] = {
    { "ARB_FLUSH_REQ_PEND_X_1", AR_NIC_WC_WC_BUF1_LM_DATA2_D_MID_WC_ARB_FLUSH_REQ_PEND_X_1_BP, AR_NIC_WC_WC_BUF1_LM_DATA2_D_MID_WC_ARB_FLUSH_REQ_PEND_X_1_MASK },
    { "ARB_FLUSH_REQ_X_1", AR_NIC_WC_WC_BUF1_LM_DATA2_D_MID_WC_ARB_FLUSH_REQ_X_1_BP, AR_NIC_WC_WC_BUF1_LM_DATA2_D_MID_WC_ARB_FLUSH_REQ_X_1_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf1_lm_data2_d_lo_wc_detail[] = {
    { "ARB_REQ", AR_NIC_WC_WC_BUF1_LM_DATA2_D_LO_WC_ARB_REQ_BP, AR_NIC_WC_WC_BUF1_LM_DATA2_D_LO_WC_ARB_REQ_MASK },
    { "ARB_REQ_PEND", AR_NIC_WC_WC_BUF1_LM_DATA2_D_LO_WC_ARB_REQ_PEND_BP, AR_NIC_WC_WC_BUF1_LM_DATA2_D_LO_WC_ARB_REQ_PEND_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf1_lm_data3_e_hi_wc_detail[] = {
    { "UNUSED_145_130", AR_NIC_WC_WC_BUF1_LM_DATA3_E_HI_WC_UNUSED_145_130_BP, AR_NIC_WC_WC_BUF1_LM_DATA3_E_HI_WC_UNUSED_145_130_MASK },
    { "R_Q_BUFFER_TIMEOUT", AR_NIC_WC_WC_BUF1_LM_DATA3_E_HI_WC_R_Q_BUFFER_TIMEOUT_BP, AR_NIC_WC_WC_BUF1_LM_DATA3_E_HI_WC_R_Q_BUFFER_TIMEOUT_MASK },
    { "Q_GO_EVICT_SG0", AR_NIC_WC_WC_BUF1_LM_DATA3_E_HI_WC_Q_GO_EVICT_SG0_BP, AR_NIC_WC_WC_BUF1_LM_DATA3_E_HI_WC_Q_GO_EVICT_SG0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf1_lm_data3_e_mid_wc_detail[] = {
    { "BUFFER_TIMEOUT", AR_NIC_WC_WC_BUF1_LM_DATA3_E_MID_WC_BUFFER_TIMEOUT_BP, AR_NIC_WC_WC_BUF1_LM_DATA3_E_MID_WC_BUFFER_TIMEOUT_MASK },
    { "EVICT", AR_NIC_WC_WC_BUF1_LM_DATA3_E_MID_WC_EVICT_BP, AR_NIC_WC_WC_BUF1_LM_DATA3_E_MID_WC_EVICT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf1_lm_data3_e_lo_wc_detail[] = {
    { "BUFFER_AVAIL", AR_NIC_WC_WC_BUF1_LM_DATA3_E_LO_WC_BUFFER_AVAIL_BP, AR_NIC_WC_WC_BUF1_LM_DATA3_E_LO_WC_BUFFER_AVAIL_MASK },
    { "BUFFER_VALID", AR_NIC_WC_WC_BUF1_LM_DATA3_E_LO_WC_BUFFER_VALID_BP, AR_NIC_WC_WC_BUF1_LM_DATA3_E_LO_WC_BUFFER_VALID_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf1_rspout_flit_f_hi_wc_detail[] = {
    { "I_RSPOUT_RD", AR_NIC_WC_WC_BUF1_RSPOUT_FLIT_F_HI_WC_I_RSPOUT_RD_BP, AR_NIC_WC_WC_BUF1_RSPOUT_FLIT_F_HI_WC_I_RSPOUT_RD_MASK },
    { "R_RSPOUT_ERR", AR_NIC_WC_WC_BUF1_RSPOUT_FLIT_F_HI_WC_R_RSPOUT_ERR_BP, AR_NIC_WC_WC_BUF1_RSPOUT_FLIT_F_HI_WC_R_RSPOUT_ERR_MASK },
    { "R_RSPOUT_TAIL", AR_NIC_WC_WC_BUF1_RSPOUT_FLIT_F_HI_WC_R_RSPOUT_TAIL_BP, AR_NIC_WC_WC_BUF1_RSPOUT_FLIT_F_HI_WC_R_RSPOUT_TAIL_MASK },
    { "RSPOUT_FIFO_FLIT", AR_NIC_WC_WC_BUF1_RSPOUT_FLIT_F_HI_WC_RSPOUT_FIFO_FLIT_BP, AR_NIC_WC_WC_BUF1_RSPOUT_FLIT_F_HI_WC_RSPOUT_FIFO_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf1_rspout_flit_f_mid_wc_detail[] = {
    { "RSPOUT_FIFO_FLIT", AR_NIC_WC_WC_BUF1_RSPOUT_FLIT_F_MID_WC_RSPOUT_FIFO_FLIT_BP, AR_NIC_WC_WC_BUF1_RSPOUT_FLIT_F_MID_WC_RSPOUT_FIFO_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_wc_buf1_rspout_flit_f_lo_wc_detail[] = {
    { "RSPOUT_FIFO_FLIT", AR_NIC_WC_WC_BUF1_RSPOUT_FLIT_F_LO_WC_RSPOUT_FIFO_FLIT_BP, AR_NIC_WC_WC_BUF1_RSPOUT_FLIT_F_LO_WC_RSPOUT_FIFO_FLIT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_mux_sel_ff_hi_wc_detail[] = {
    { "POWER_DOWN", AR_NIC_WC_MUX_SEL_FF_HI_WC_POWER_DOWN_BP, AR_NIC_WC_MUX_SEL_FF_HI_WC_POWER_DOWN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_mux_sel_ff_mid_wc_detail[] = {
    { "POWER_DOWN", AR_NIC_WC_MUX_SEL_FF_MID_WC_POWER_DOWN_BP, AR_NIC_WC_MUX_SEL_FF_MID_WC_POWER_DOWN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_mux_sel_ff_lo_wc_detail[] = {
    { "POWER_DOWN", AR_NIC_WC_MUX_SEL_FF_LO_WC_POWER_DOWN_BP, AR_NIC_WC_MUX_SEL_FF_LO_WC_POWER_DOWN_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_cfg_crdts_detail[] = {
    { "FLRSP_FIFO_MAX_CRDT", AR_NIC_WC_CFG_CRDTS_FLRSP_FIFO_MAX_CRDT_BP, AR_NIC_WC_CFG_CRDTS_FLRSP_FIFO_MAX_CRDT_MASK },
    { "RSPOUT_FIFO_MAX_CRDT", AR_NIC_WC_CFG_CRDTS_RSPOUT_FIFO_MAX_CRDT_BP, AR_NIC_WC_CFG_CRDTS_RSPOUT_FIFO_MAX_CRDT_MASK },
    { "RSPIN_FIFO_MAX_CRDT", AR_NIC_WC_CFG_CRDTS_RSPIN_FIFO_MAX_CRDT_BP, AR_NIC_WC_CFG_CRDTS_RSPIN_FIFO_MAX_CRDT_MASK },
    { "SSID_FL_RSP_MAX_CRDT", AR_NIC_WC_CFG_CRDTS_SSID_FL_RSP_MAX_CRDT_BP, AR_NIC_WC_CFG_CRDTS_SSID_FL_RSP_MAX_CRDT_MASK },
    { "SSID_RSP_MAX_CRDT", AR_NIC_WC_CFG_CRDTS_SSID_RSP_MAX_CRDT_BP, AR_NIC_WC_CFG_CRDTS_SSID_RSP_MAX_CRDT_MASK },
    { "PARB_MAX_CRDT", AR_NIC_WC_CFG_CRDTS_PARB_MAX_CRDT_BP, AR_NIC_WC_CFG_CRDTS_PARB_MAX_CRDT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_dbg_errinj_mem_detail[] = {
    { "ADDRESS", AR_NIC_WC_DBG_ERRINJ_MEM_ADDRESS_BP, AR_NIC_WC_DBG_ERRINJ_MEM_ADDRESS_MASK },
    { "PARITY", AR_NIC_WC_DBG_ERRINJ_MEM_PARITY_BP, AR_NIC_WC_DBG_ERRINJ_MEM_PARITY_MASK },
    { "POISON", AR_NIC_WC_DBG_ERRINJ_MEM_POISON_BP, AR_NIC_WC_DBG_ERRINJ_MEM_POISON_MASK },
    { "CHECKBITS", AR_NIC_WC_DBG_ERRINJ_MEM_CHECKBITS_BP, AR_NIC_WC_DBG_ERRINJ_MEM_CHECKBITS_MASK },
    { "RAMSELECT", AR_NIC_WC_DBG_ERRINJ_MEM_RAMSELECT_BP, AR_NIC_WC_DBG_ERRINJ_MEM_RAMSELECT_MASK },
    { "TRIGGERED", AR_NIC_WC_DBG_ERRINJ_MEM_TRIGGERED_BP, AR_NIC_WC_DBG_ERRINJ_MEM_TRIGGERED_MASK },
    { "MODE", AR_NIC_WC_DBG_ERRINJ_MEM_MODE_BP, AR_NIC_WC_DBG_ERRINJ_MEM_MODE_MASK },
    { "ENABLE", AR_NIC_WC_DBG_ERRINJ_MEM_ENABLE_BP, AR_NIC_WC_DBG_ERRINJ_MEM_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_dbg_errinj_bus_detail[] = {
    { "RSPIN_FIFO_1", AR_NIC_WC_DBG_ERRINJ_BUS_RSPIN_FIFO_1_BP, AR_NIC_WC_DBG_ERRINJ_BUS_RSPIN_FIFO_1_MASK },
    { "RSPIN_FIFO_0", AR_NIC_WC_DBG_ERRINJ_BUS_RSPIN_FIFO_0_BP, AR_NIC_WC_DBG_ERRINJ_BUS_RSPIN_FIFO_0_MASK },
    { "NTWK_RSP_FIFO", AR_NIC_WC_DBG_ERRINJ_BUS_NTWK_RSP_FIFO_BP, AR_NIC_WC_DBG_ERRINJ_BUS_NTWK_RSP_FIFO_MASK },
    { "CHECKBITS_UP", AR_NIC_WC_DBG_ERRINJ_BUS_CHECKBITS_UP_BP, AR_NIC_WC_DBG_ERRINJ_BUS_CHECKBITS_UP_MASK },
    { "CHECKBITS_LO", AR_NIC_WC_DBG_ERRINJ_BUS_CHECKBITS_LO_BP, AR_NIC_WC_DBG_ERRINJ_BUS_CHECKBITS_LO_MASK },
    { "PARITY", AR_NIC_WC_DBG_ERRINJ_BUS_PARITY_BP, AR_NIC_WC_DBG_ERRINJ_BUS_PARITY_MASK },
    { "COUNT", AR_NIC_WC_DBG_ERRINJ_BUS_COUNT_BP, AR_NIC_WC_DBG_ERRINJ_BUS_COUNT_MASK },
    { "TRIGGERED", AR_NIC_WC_DBG_ERRINJ_BUS_TRIGGERED_BP, AR_NIC_WC_DBG_ERRINJ_BUS_TRIGGERED_MASK },
    { "MODE", AR_NIC_WC_DBG_ERRINJ_BUS_MODE_BP, AR_NIC_WC_DBG_ERRINJ_BUS_MODE_MASK },
    { "ENABLE", AR_NIC_WC_DBG_ERRINJ_BUS_ENABLE_BP, AR_NIC_WC_DBG_ERRINJ_BUS_ENABLE_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_dbg_buf_inval_detail[] = {
    { "FLUSH", AR_NIC_WC_DBG_BUF_INVAL_FLUSH_BP, AR_NIC_WC_DBG_BUF_INVAL_FLUSH_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_sts_buf_avail_detail[] = {
    { "BUF1", AR_NIC_WC_STS_BUF_AVAIL_BUF1_BP, AR_NIC_WC_STS_BUF_AVAIL_BUF1_MASK },
    { "BUF0", AR_NIC_WC_STS_BUF_AVAIL_BUF0_BP, AR_NIC_WC_STS_BUF_AVAIL_BUF0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_sts_buf_vld_detail[] = {
    { "BUF1", AR_NIC_WC_STS_BUF_VLD_BUF1_BP, AR_NIC_WC_STS_BUF_VLD_BUF1_MASK },
    { "BUF0", AR_NIC_WC_STS_BUF_VLD_BUF0_BP, AR_NIC_WC_STS_BUF_VLD_BUF0_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_err_flg_detail[] = {
    { "BUFFER_TIMEOUT", AR_NIC_WC_ERR_FLG_BUFFER_TIMEOUT_BP, AR_NIC_WC_ERR_FLG_BUFFER_TIMEOUT_MASK },
    { "FLUSH_RSP_FIFO_UFLW", AR_NIC_WC_ERR_FLG_FLUSH_RSP_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_FLUSH_RSP_FIFO_UFLW_MASK },
    { "FLUSH_RSP_FIFO_OFLW", AR_NIC_WC_ERR_FLG_FLUSH_RSP_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_FLUSH_RSP_FIFO_OFLW_MASK },
    { "FLUSH_REQ_FIFO_UFLW", AR_NIC_WC_ERR_FLG_FLUSH_REQ_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_FLUSH_REQ_FIFO_UFLW_MASK },
    { "FLUSH_REQ_FIFO_OFLW", AR_NIC_WC_ERR_FLG_FLUSH_REQ_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_FLUSH_REQ_FIFO_OFLW_MASK },
    { "RSPOUT1_FIFO_UFLW", AR_NIC_WC_ERR_FLG_RSPOUT1_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_RSPOUT1_FIFO_UFLW_MASK },
    { "RSPOUT1_FIFO_OFLW", AR_NIC_WC_ERR_FLG_RSPOUT1_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_RSPOUT1_FIFO_OFLW_MASK },
    { "RSPOUT0_FIFO_UFLW", AR_NIC_WC_ERR_FLG_RSPOUT0_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_RSPOUT0_FIFO_UFLW_MASK },
    { "RSPOUT0_FIFO_OFLW", AR_NIC_WC_ERR_FLG_RSPOUT0_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_RSPOUT0_FIFO_OFLW_MASK },
    { "RSPIN1_FIFO_UFLW", AR_NIC_WC_ERR_FLG_RSPIN1_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_RSPIN1_FIFO_UFLW_MASK },
    { "RSPIN1_FIFO_OFLW", AR_NIC_WC_ERR_FLG_RSPIN1_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_RSPIN1_FIFO_OFLW_MASK },
    { "RSPIN0_FIFO_UFLW", AR_NIC_WC_ERR_FLG_RSPIN0_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_RSPIN0_FIFO_UFLW_MASK },
    { "RSPIN0_FIFO_OFLW", AR_NIC_WC_ERR_FLG_RSPIN0_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_RSPIN0_FIFO_OFLW_MASK },
    { "NTWK_RSP_FIFO_UFLW", AR_NIC_WC_ERR_FLG_NTWK_RSP_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_NTWK_RSP_FIFO_UFLW_MASK },
    { "NTWK_RSP_FIFO_OFLW", AR_NIC_WC_ERR_FLG_NTWK_RSP_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_NTWK_RSP_FIFO_OFLW_MASK },
    { "TAG_PBE", AR_NIC_WC_ERR_FLG_TAG_PBE_BP, AR_NIC_WC_ERR_FLG_TAG_PBE_MASK },
    { "RSPIN1_HDR_PBE", AR_NIC_WC_ERR_FLG_RSPIN1_HDR_PBE_BP, AR_NIC_WC_ERR_FLG_RSPIN1_HDR_PBE_MASK },
    { "RSPIN0_HDR_PBE", AR_NIC_WC_ERR_FLG_RSPIN0_HDR_PBE_BP, AR_NIC_WC_ERR_FLG_RSPIN0_HDR_PBE_MASK },
    { "NTWK_RSP_HDR_PBE", AR_NIC_WC_ERR_FLG_NTWK_RSP_HDR_PBE_BP, AR_NIC_WC_ERR_FLG_NTWK_RSP_HDR_PBE_MASK },
    { "BUF1_MBE", AR_NIC_WC_ERR_FLG_BUF1_MBE_BP, AR_NIC_WC_ERR_FLG_BUF1_MBE_MASK },
    { "BUF1_SBE", AR_NIC_WC_ERR_FLG_BUF1_SBE_BP, AR_NIC_WC_ERR_FLG_BUF1_SBE_MASK },
    { "BUF0_MBE", AR_NIC_WC_ERR_FLG_BUF0_MBE_BP, AR_NIC_WC_ERR_FLG_BUF0_MBE_MASK },
    { "BUF0_SBE", AR_NIC_WC_ERR_FLG_BUF0_SBE_BP, AR_NIC_WC_ERR_FLG_BUF0_SBE_MASK },
    { "RSPIN1_DAT_MBE", AR_NIC_WC_ERR_FLG_RSPIN1_DAT_MBE_BP, AR_NIC_WC_ERR_FLG_RSPIN1_DAT_MBE_MASK },
    { "RSPIN1_DAT_SBE", AR_NIC_WC_ERR_FLG_RSPIN1_DAT_SBE_BP, AR_NIC_WC_ERR_FLG_RSPIN1_DAT_SBE_MASK },
    { "RSPIN0_DAT_MBE", AR_NIC_WC_ERR_FLG_RSPIN0_DAT_MBE_BP, AR_NIC_WC_ERR_FLG_RSPIN0_DAT_MBE_MASK },
    { "RSPIN0_DAT_SBE", AR_NIC_WC_ERR_FLG_RSPIN0_DAT_SBE_BP, AR_NIC_WC_ERR_FLG_RSPIN0_DAT_SBE_MASK },
    { "DIAG_ONLY", AR_NIC_WC_ERR_FLG_DIAG_ONLY_BP, AR_NIC_WC_ERR_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
#ifdef EXCEPTIONS_DEFS
static const errcat_mmrd_t _ar_nic_wc_err_flg_errcat[] = {
    { "BUFFER_TIMEOUT", AR_NIC_WC_ERR_FLG_BUFFER_TIMEOUT_BP, AR_NIC_WC_ERR_FLG_BUFFER_TIMEOUT_EC },
    { "FLUSH_RSP_FIFO_UFLW", AR_NIC_WC_ERR_FLG_FLUSH_RSP_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_FLUSH_RSP_FIFO_UFLW_EC },
    { "FLUSH_RSP_FIFO_OFLW", AR_NIC_WC_ERR_FLG_FLUSH_RSP_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_FLUSH_RSP_FIFO_OFLW_EC },
    { "FLUSH_REQ_FIFO_UFLW", AR_NIC_WC_ERR_FLG_FLUSH_REQ_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_FLUSH_REQ_FIFO_UFLW_EC },
    { "FLUSH_REQ_FIFO_OFLW", AR_NIC_WC_ERR_FLG_FLUSH_REQ_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_FLUSH_REQ_FIFO_OFLW_EC },
    { "RSPOUT1_FIFO_UFLW", AR_NIC_WC_ERR_FLG_RSPOUT1_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_RSPOUT1_FIFO_UFLW_EC },
    { "RSPOUT1_FIFO_OFLW", AR_NIC_WC_ERR_FLG_RSPOUT1_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_RSPOUT1_FIFO_OFLW_EC },
    { "RSPOUT0_FIFO_UFLW", AR_NIC_WC_ERR_FLG_RSPOUT0_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_RSPOUT0_FIFO_UFLW_EC },
    { "RSPOUT0_FIFO_OFLW", AR_NIC_WC_ERR_FLG_RSPOUT0_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_RSPOUT0_FIFO_OFLW_EC },
    { "RSPIN1_FIFO_UFLW", AR_NIC_WC_ERR_FLG_RSPIN1_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_RSPIN1_FIFO_UFLW_EC },
    { "RSPIN1_FIFO_OFLW", AR_NIC_WC_ERR_FLG_RSPIN1_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_RSPIN1_FIFO_OFLW_EC },
    { "RSPIN0_FIFO_UFLW", AR_NIC_WC_ERR_FLG_RSPIN0_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_RSPIN0_FIFO_UFLW_EC },
    { "RSPIN0_FIFO_OFLW", AR_NIC_WC_ERR_FLG_RSPIN0_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_RSPIN0_FIFO_OFLW_EC },
    { "NTWK_RSP_FIFO_UFLW", AR_NIC_WC_ERR_FLG_NTWK_RSP_FIFO_UFLW_BP, AR_NIC_WC_ERR_FLG_NTWK_RSP_FIFO_UFLW_EC },
    { "NTWK_RSP_FIFO_OFLW", AR_NIC_WC_ERR_FLG_NTWK_RSP_FIFO_OFLW_BP, AR_NIC_WC_ERR_FLG_NTWK_RSP_FIFO_OFLW_EC },
    { "TAG_PBE", AR_NIC_WC_ERR_FLG_TAG_PBE_BP, AR_NIC_WC_ERR_FLG_TAG_PBE_EC },
    { "RSPIN1_HDR_PBE", AR_NIC_WC_ERR_FLG_RSPIN1_HDR_PBE_BP, AR_NIC_WC_ERR_FLG_RSPIN1_HDR_PBE_EC },
    { "RSPIN0_HDR_PBE", AR_NIC_WC_ERR_FLG_RSPIN0_HDR_PBE_BP, AR_NIC_WC_ERR_FLG_RSPIN0_HDR_PBE_EC },
    { "NTWK_RSP_HDR_PBE", AR_NIC_WC_ERR_FLG_NTWK_RSP_HDR_PBE_BP, AR_NIC_WC_ERR_FLG_NTWK_RSP_HDR_PBE_EC },
    { "BUF1_MBE", AR_NIC_WC_ERR_FLG_BUF1_MBE_BP, AR_NIC_WC_ERR_FLG_BUF1_MBE_EC },
    { "BUF1_SBE", AR_NIC_WC_ERR_FLG_BUF1_SBE_BP, AR_NIC_WC_ERR_FLG_BUF1_SBE_EC },
    { "BUF0_MBE", AR_NIC_WC_ERR_FLG_BUF0_MBE_BP, AR_NIC_WC_ERR_FLG_BUF0_MBE_EC },
    { "BUF0_SBE", AR_NIC_WC_ERR_FLG_BUF0_SBE_BP, AR_NIC_WC_ERR_FLG_BUF0_SBE_EC },
    { "RSPIN1_DAT_MBE", AR_NIC_WC_ERR_FLG_RSPIN1_DAT_MBE_BP, AR_NIC_WC_ERR_FLG_RSPIN1_DAT_MBE_EC },
    { "RSPIN1_DAT_SBE", AR_NIC_WC_ERR_FLG_RSPIN1_DAT_SBE_BP, AR_NIC_WC_ERR_FLG_RSPIN1_DAT_SBE_EC },
    { "RSPIN0_DAT_MBE", AR_NIC_WC_ERR_FLG_RSPIN0_DAT_MBE_BP, AR_NIC_WC_ERR_FLG_RSPIN0_DAT_MBE_EC },
    { "RSPIN0_DAT_SBE", AR_NIC_WC_ERR_FLG_RSPIN0_DAT_SBE_BP, AR_NIC_WC_ERR_FLG_RSPIN0_DAT_SBE_EC },
    { "DIAG_ONLY", AR_NIC_WC_ERR_FLG_DIAG_ONLY_BP, AR_NIC_WC_ERR_FLG_DIAG_ONLY_EC },
    { NULL, 0, 0 }
};
#endif
static const generic_mmrd_t _ar_nic_wc_err_clr_detail[] = {
    { "BUFFER_TIMEOUT", AR_NIC_WC_ERR_CLR_BUFFER_TIMEOUT_BP, AR_NIC_WC_ERR_CLR_BUFFER_TIMEOUT_MASK },
    { "FLUSH_RSP_FIFO_UFLW", AR_NIC_WC_ERR_CLR_FLUSH_RSP_FIFO_UFLW_BP, AR_NIC_WC_ERR_CLR_FLUSH_RSP_FIFO_UFLW_MASK },
    { "FLUSH_RSP_FIFO_OFLW", AR_NIC_WC_ERR_CLR_FLUSH_RSP_FIFO_OFLW_BP, AR_NIC_WC_ERR_CLR_FLUSH_RSP_FIFO_OFLW_MASK },
    { "FLUSH_REQ_FIFO_UFLW", AR_NIC_WC_ERR_CLR_FLUSH_REQ_FIFO_UFLW_BP, AR_NIC_WC_ERR_CLR_FLUSH_REQ_FIFO_UFLW_MASK },
    { "FLUSH_REQ_FIFO_OFLW", AR_NIC_WC_ERR_CLR_FLUSH_REQ_FIFO_OFLW_BP, AR_NIC_WC_ERR_CLR_FLUSH_REQ_FIFO_OFLW_MASK },
    { "RSPOUT1_FIFO_UFLW", AR_NIC_WC_ERR_CLR_RSPOUT1_FIFO_UFLW_BP, AR_NIC_WC_ERR_CLR_RSPOUT1_FIFO_UFLW_MASK },
    { "RSPOUT1_FIFO_OFLW", AR_NIC_WC_ERR_CLR_RSPOUT1_FIFO_OFLW_BP, AR_NIC_WC_ERR_CLR_RSPOUT1_FIFO_OFLW_MASK },
    { "RSPOUT0_FIFO_UFLW", AR_NIC_WC_ERR_CLR_RSPOUT0_FIFO_UFLW_BP, AR_NIC_WC_ERR_CLR_RSPOUT0_FIFO_UFLW_MASK },
    { "RSPOUT0_FIFO_OFLW", AR_NIC_WC_ERR_CLR_RSPOUT0_FIFO_OFLW_BP, AR_NIC_WC_ERR_CLR_RSPOUT0_FIFO_OFLW_MASK },
    { "RSPIN1_FIFO_UFLW", AR_NIC_WC_ERR_CLR_RSPIN1_FIFO_UFLW_BP, AR_NIC_WC_ERR_CLR_RSPIN1_FIFO_UFLW_MASK },
    { "RSPIN1_FIFO_OFLW", AR_NIC_WC_ERR_CLR_RSPIN1_FIFO_OFLW_BP, AR_NIC_WC_ERR_CLR_RSPIN1_FIFO_OFLW_MASK },
    { "RSPIN0_FIFO_UFLW", AR_NIC_WC_ERR_CLR_RSPIN0_FIFO_UFLW_BP, AR_NIC_WC_ERR_CLR_RSPIN0_FIFO_UFLW_MASK },
    { "RSPIN0_FIFO_OFLW", AR_NIC_WC_ERR_CLR_RSPIN0_FIFO_OFLW_BP, AR_NIC_WC_ERR_CLR_RSPIN0_FIFO_OFLW_MASK },
    { "NTWK_RSP_FIFO_UFLW", AR_NIC_WC_ERR_CLR_NTWK_RSP_FIFO_UFLW_BP, AR_NIC_WC_ERR_CLR_NTWK_RSP_FIFO_UFLW_MASK },
    { "NTWK_RSP_FIFO_OFLW", AR_NIC_WC_ERR_CLR_NTWK_RSP_FIFO_OFLW_BP, AR_NIC_WC_ERR_CLR_NTWK_RSP_FIFO_OFLW_MASK },
    { "TAG_PBE", AR_NIC_WC_ERR_CLR_TAG_PBE_BP, AR_NIC_WC_ERR_CLR_TAG_PBE_MASK },
    { "RSPIN1_HDR_PBE", AR_NIC_WC_ERR_CLR_RSPIN1_HDR_PBE_BP, AR_NIC_WC_ERR_CLR_RSPIN1_HDR_PBE_MASK },
    { "RSPIN0_HDR_PBE", AR_NIC_WC_ERR_CLR_RSPIN0_HDR_PBE_BP, AR_NIC_WC_ERR_CLR_RSPIN0_HDR_PBE_MASK },
    { "NTWK_RSP_HDR_PBE", AR_NIC_WC_ERR_CLR_NTWK_RSP_HDR_PBE_BP, AR_NIC_WC_ERR_CLR_NTWK_RSP_HDR_PBE_MASK },
    { "BUF1_MBE", AR_NIC_WC_ERR_CLR_BUF1_MBE_BP, AR_NIC_WC_ERR_CLR_BUF1_MBE_MASK },
    { "BUF1_SBE", AR_NIC_WC_ERR_CLR_BUF1_SBE_BP, AR_NIC_WC_ERR_CLR_BUF1_SBE_MASK },
    { "BUF0_MBE", AR_NIC_WC_ERR_CLR_BUF0_MBE_BP, AR_NIC_WC_ERR_CLR_BUF0_MBE_MASK },
    { "BUF0_SBE", AR_NIC_WC_ERR_CLR_BUF0_SBE_BP, AR_NIC_WC_ERR_CLR_BUF0_SBE_MASK },
    { "RSPIN1_DAT_MBE", AR_NIC_WC_ERR_CLR_RSPIN1_DAT_MBE_BP, AR_NIC_WC_ERR_CLR_RSPIN1_DAT_MBE_MASK },
    { "RSPIN1_DAT_SBE", AR_NIC_WC_ERR_CLR_RSPIN1_DAT_SBE_BP, AR_NIC_WC_ERR_CLR_RSPIN1_DAT_SBE_MASK },
    { "RSPIN0_DAT_MBE", AR_NIC_WC_ERR_CLR_RSPIN0_DAT_MBE_BP, AR_NIC_WC_ERR_CLR_RSPIN0_DAT_MBE_MASK },
    { "RSPIN0_DAT_SBE", AR_NIC_WC_ERR_CLR_RSPIN0_DAT_SBE_BP, AR_NIC_WC_ERR_CLR_RSPIN0_DAT_SBE_MASK },
    { "DIAG_ONLY", AR_NIC_WC_ERR_CLR_DIAG_ONLY_BP, AR_NIC_WC_ERR_CLR_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_err_hss_msk_detail[] = {
    { "BUFFER_TIMEOUT", AR_NIC_WC_ERR_HSS_MSK_BUFFER_TIMEOUT_BP, AR_NIC_WC_ERR_HSS_MSK_BUFFER_TIMEOUT_MASK },
    { "FLUSH_RSP_FIFO_UFLW", AR_NIC_WC_ERR_HSS_MSK_FLUSH_RSP_FIFO_UFLW_BP, AR_NIC_WC_ERR_HSS_MSK_FLUSH_RSP_FIFO_UFLW_MASK },
    { "FLUSH_RSP_FIFO_OFLW", AR_NIC_WC_ERR_HSS_MSK_FLUSH_RSP_FIFO_OFLW_BP, AR_NIC_WC_ERR_HSS_MSK_FLUSH_RSP_FIFO_OFLW_MASK },
    { "FLUSH_REQ_FIFO_UFLW", AR_NIC_WC_ERR_HSS_MSK_FLUSH_REQ_FIFO_UFLW_BP, AR_NIC_WC_ERR_HSS_MSK_FLUSH_REQ_FIFO_UFLW_MASK },
    { "FLUSH_REQ_FIFO_OFLW", AR_NIC_WC_ERR_HSS_MSK_FLUSH_REQ_FIFO_OFLW_BP, AR_NIC_WC_ERR_HSS_MSK_FLUSH_REQ_FIFO_OFLW_MASK },
    { "RSPOUT1_FIFO_UFLW", AR_NIC_WC_ERR_HSS_MSK_RSPOUT1_FIFO_UFLW_BP, AR_NIC_WC_ERR_HSS_MSK_RSPOUT1_FIFO_UFLW_MASK },
    { "RSPOUT1_FIFO_OFLW", AR_NIC_WC_ERR_HSS_MSK_RSPOUT1_FIFO_OFLW_BP, AR_NIC_WC_ERR_HSS_MSK_RSPOUT1_FIFO_OFLW_MASK },
    { "RSPOUT0_FIFO_UFLW", AR_NIC_WC_ERR_HSS_MSK_RSPOUT0_FIFO_UFLW_BP, AR_NIC_WC_ERR_HSS_MSK_RSPOUT0_FIFO_UFLW_MASK },
    { "RSPOUT0_FIFO_OFLW", AR_NIC_WC_ERR_HSS_MSK_RSPOUT0_FIFO_OFLW_BP, AR_NIC_WC_ERR_HSS_MSK_RSPOUT0_FIFO_OFLW_MASK },
    { "RSPIN1_FIFO_UFLW", AR_NIC_WC_ERR_HSS_MSK_RSPIN1_FIFO_UFLW_BP, AR_NIC_WC_ERR_HSS_MSK_RSPIN1_FIFO_UFLW_MASK },
    { "RSPIN1_FIFO_OFLW", AR_NIC_WC_ERR_HSS_MSK_RSPIN1_FIFO_OFLW_BP, AR_NIC_WC_ERR_HSS_MSK_RSPIN1_FIFO_OFLW_MASK },
    { "RSPIN0_FIFO_UFLW", AR_NIC_WC_ERR_HSS_MSK_RSPIN0_FIFO_UFLW_BP, AR_NIC_WC_ERR_HSS_MSK_RSPIN0_FIFO_UFLW_MASK },
    { "RSPIN0_FIFO_OFLW", AR_NIC_WC_ERR_HSS_MSK_RSPIN0_FIFO_OFLW_BP, AR_NIC_WC_ERR_HSS_MSK_RSPIN0_FIFO_OFLW_MASK },
    { "NTWK_RSP_FIFO_UFLW", AR_NIC_WC_ERR_HSS_MSK_NTWK_RSP_FIFO_UFLW_BP, AR_NIC_WC_ERR_HSS_MSK_NTWK_RSP_FIFO_UFLW_MASK },
    { "NTWK_RSP_FIFO_OFLW", AR_NIC_WC_ERR_HSS_MSK_NTWK_RSP_FIFO_OFLW_BP, AR_NIC_WC_ERR_HSS_MSK_NTWK_RSP_FIFO_OFLW_MASK },
    { "TAG_PBE", AR_NIC_WC_ERR_HSS_MSK_TAG_PBE_BP, AR_NIC_WC_ERR_HSS_MSK_TAG_PBE_MASK },
    { "RSPIN1_HDR_PBE", AR_NIC_WC_ERR_HSS_MSK_RSPIN1_HDR_PBE_BP, AR_NIC_WC_ERR_HSS_MSK_RSPIN1_HDR_PBE_MASK },
    { "RSPIN0_HDR_PBE", AR_NIC_WC_ERR_HSS_MSK_RSPIN0_HDR_PBE_BP, AR_NIC_WC_ERR_HSS_MSK_RSPIN0_HDR_PBE_MASK },
    { "NTWK_RSP_HDR_PBE", AR_NIC_WC_ERR_HSS_MSK_NTWK_RSP_HDR_PBE_BP, AR_NIC_WC_ERR_HSS_MSK_NTWK_RSP_HDR_PBE_MASK },
    { "BUF1_MBE", AR_NIC_WC_ERR_HSS_MSK_BUF1_MBE_BP, AR_NIC_WC_ERR_HSS_MSK_BUF1_MBE_MASK },
    { "BUF1_SBE", AR_NIC_WC_ERR_HSS_MSK_BUF1_SBE_BP, AR_NIC_WC_ERR_HSS_MSK_BUF1_SBE_MASK },
    { "BUF0_MBE", AR_NIC_WC_ERR_HSS_MSK_BUF0_MBE_BP, AR_NIC_WC_ERR_HSS_MSK_BUF0_MBE_MASK },
    { "BUF0_SBE", AR_NIC_WC_ERR_HSS_MSK_BUF0_SBE_BP, AR_NIC_WC_ERR_HSS_MSK_BUF0_SBE_MASK },
    { "RSPIN1_DAT_MBE", AR_NIC_WC_ERR_HSS_MSK_RSPIN1_DAT_MBE_BP, AR_NIC_WC_ERR_HSS_MSK_RSPIN1_DAT_MBE_MASK },
    { "RSPIN1_DAT_SBE", AR_NIC_WC_ERR_HSS_MSK_RSPIN1_DAT_SBE_BP, AR_NIC_WC_ERR_HSS_MSK_RSPIN1_DAT_SBE_MASK },
    { "RSPIN0_DAT_MBE", AR_NIC_WC_ERR_HSS_MSK_RSPIN0_DAT_MBE_BP, AR_NIC_WC_ERR_HSS_MSK_RSPIN0_DAT_MBE_MASK },
    { "RSPIN0_DAT_SBE", AR_NIC_WC_ERR_HSS_MSK_RSPIN0_DAT_SBE_BP, AR_NIC_WC_ERR_HSS_MSK_RSPIN0_DAT_SBE_MASK },
    { "DIAG_ONLY", AR_NIC_WC_ERR_HSS_MSK_DIAG_ONLY_BP, AR_NIC_WC_ERR_HSS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_err_os_msk_detail[] = {
    { "BUFFER_TIMEOUT", AR_NIC_WC_ERR_OS_MSK_BUFFER_TIMEOUT_BP, AR_NIC_WC_ERR_OS_MSK_BUFFER_TIMEOUT_MASK },
    { "FLUSH_RSP_FIFO_UFLW", AR_NIC_WC_ERR_OS_MSK_FLUSH_RSP_FIFO_UFLW_BP, AR_NIC_WC_ERR_OS_MSK_FLUSH_RSP_FIFO_UFLW_MASK },
    { "FLUSH_RSP_FIFO_OFLW", AR_NIC_WC_ERR_OS_MSK_FLUSH_RSP_FIFO_OFLW_BP, AR_NIC_WC_ERR_OS_MSK_FLUSH_RSP_FIFO_OFLW_MASK },
    { "FLUSH_REQ_FIFO_UFLW", AR_NIC_WC_ERR_OS_MSK_FLUSH_REQ_FIFO_UFLW_BP, AR_NIC_WC_ERR_OS_MSK_FLUSH_REQ_FIFO_UFLW_MASK },
    { "FLUSH_REQ_FIFO_OFLW", AR_NIC_WC_ERR_OS_MSK_FLUSH_REQ_FIFO_OFLW_BP, AR_NIC_WC_ERR_OS_MSK_FLUSH_REQ_FIFO_OFLW_MASK },
    { "RSPOUT1_FIFO_UFLW", AR_NIC_WC_ERR_OS_MSK_RSPOUT1_FIFO_UFLW_BP, AR_NIC_WC_ERR_OS_MSK_RSPOUT1_FIFO_UFLW_MASK },
    { "RSPOUT1_FIFO_OFLW", AR_NIC_WC_ERR_OS_MSK_RSPOUT1_FIFO_OFLW_BP, AR_NIC_WC_ERR_OS_MSK_RSPOUT1_FIFO_OFLW_MASK },
    { "RSPOUT0_FIFO_UFLW", AR_NIC_WC_ERR_OS_MSK_RSPOUT0_FIFO_UFLW_BP, AR_NIC_WC_ERR_OS_MSK_RSPOUT0_FIFO_UFLW_MASK },
    { "RSPOUT0_FIFO_OFLW", AR_NIC_WC_ERR_OS_MSK_RSPOUT0_FIFO_OFLW_BP, AR_NIC_WC_ERR_OS_MSK_RSPOUT0_FIFO_OFLW_MASK },
    { "RSPIN1_FIFO_UFLW", AR_NIC_WC_ERR_OS_MSK_RSPIN1_FIFO_UFLW_BP, AR_NIC_WC_ERR_OS_MSK_RSPIN1_FIFO_UFLW_MASK },
    { "RSPIN1_FIFO_OFLW", AR_NIC_WC_ERR_OS_MSK_RSPIN1_FIFO_OFLW_BP, AR_NIC_WC_ERR_OS_MSK_RSPIN1_FIFO_OFLW_MASK },
    { "RSPIN0_FIFO_UFLW", AR_NIC_WC_ERR_OS_MSK_RSPIN0_FIFO_UFLW_BP, AR_NIC_WC_ERR_OS_MSK_RSPIN0_FIFO_UFLW_MASK },
    { "RSPIN0_FIFO_OFLW", AR_NIC_WC_ERR_OS_MSK_RSPIN0_FIFO_OFLW_BP, AR_NIC_WC_ERR_OS_MSK_RSPIN0_FIFO_OFLW_MASK },
    { "NTWK_RSP_FIFO_UFLW", AR_NIC_WC_ERR_OS_MSK_NTWK_RSP_FIFO_UFLW_BP, AR_NIC_WC_ERR_OS_MSK_NTWK_RSP_FIFO_UFLW_MASK },
    { "NTWK_RSP_FIFO_OFLW", AR_NIC_WC_ERR_OS_MSK_NTWK_RSP_FIFO_OFLW_BP, AR_NIC_WC_ERR_OS_MSK_NTWK_RSP_FIFO_OFLW_MASK },
    { "TAG_PBE", AR_NIC_WC_ERR_OS_MSK_TAG_PBE_BP, AR_NIC_WC_ERR_OS_MSK_TAG_PBE_MASK },
    { "RSPIN1_HDR_PBE", AR_NIC_WC_ERR_OS_MSK_RSPIN1_HDR_PBE_BP, AR_NIC_WC_ERR_OS_MSK_RSPIN1_HDR_PBE_MASK },
    { "RSPIN0_HDR_PBE", AR_NIC_WC_ERR_OS_MSK_RSPIN0_HDR_PBE_BP, AR_NIC_WC_ERR_OS_MSK_RSPIN0_HDR_PBE_MASK },
    { "NTWK_RSP_HDR_PBE", AR_NIC_WC_ERR_OS_MSK_NTWK_RSP_HDR_PBE_BP, AR_NIC_WC_ERR_OS_MSK_NTWK_RSP_HDR_PBE_MASK },
    { "BUF1_MBE", AR_NIC_WC_ERR_OS_MSK_BUF1_MBE_BP, AR_NIC_WC_ERR_OS_MSK_BUF1_MBE_MASK },
    { "BUF1_SBE", AR_NIC_WC_ERR_OS_MSK_BUF1_SBE_BP, AR_NIC_WC_ERR_OS_MSK_BUF1_SBE_MASK },
    { "BUF0_MBE", AR_NIC_WC_ERR_OS_MSK_BUF0_MBE_BP, AR_NIC_WC_ERR_OS_MSK_BUF0_MBE_MASK },
    { "BUF0_SBE", AR_NIC_WC_ERR_OS_MSK_BUF0_SBE_BP, AR_NIC_WC_ERR_OS_MSK_BUF0_SBE_MASK },
    { "RSPIN1_DAT_MBE", AR_NIC_WC_ERR_OS_MSK_RSPIN1_DAT_MBE_BP, AR_NIC_WC_ERR_OS_MSK_RSPIN1_DAT_MBE_MASK },
    { "RSPIN1_DAT_SBE", AR_NIC_WC_ERR_OS_MSK_RSPIN1_DAT_SBE_BP, AR_NIC_WC_ERR_OS_MSK_RSPIN1_DAT_SBE_MASK },
    { "RSPIN0_DAT_MBE", AR_NIC_WC_ERR_OS_MSK_RSPIN0_DAT_MBE_BP, AR_NIC_WC_ERR_OS_MSK_RSPIN0_DAT_MBE_MASK },
    { "RSPIN0_DAT_SBE", AR_NIC_WC_ERR_OS_MSK_RSPIN0_DAT_SBE_BP, AR_NIC_WC_ERR_OS_MSK_RSPIN0_DAT_SBE_MASK },
    { "DIAG_ONLY", AR_NIC_WC_ERR_OS_MSK_DIAG_ONLY_BP, AR_NIC_WC_ERR_OS_MSK_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_err_first_flg_detail[] = {
    { "BUFFER_TIMEOUT", AR_NIC_WC_ERR_FIRST_FLG_BUFFER_TIMEOUT_BP, AR_NIC_WC_ERR_FIRST_FLG_BUFFER_TIMEOUT_MASK },
    { "FLUSH_RSP_FIFO_UFLW", AR_NIC_WC_ERR_FIRST_FLG_FLUSH_RSP_FIFO_UFLW_BP, AR_NIC_WC_ERR_FIRST_FLG_FLUSH_RSP_FIFO_UFLW_MASK },
    { "FLUSH_RSP_FIFO_OFLW", AR_NIC_WC_ERR_FIRST_FLG_FLUSH_RSP_FIFO_OFLW_BP, AR_NIC_WC_ERR_FIRST_FLG_FLUSH_RSP_FIFO_OFLW_MASK },
    { "FLUSH_REQ_FIFO_UFLW", AR_NIC_WC_ERR_FIRST_FLG_FLUSH_REQ_FIFO_UFLW_BP, AR_NIC_WC_ERR_FIRST_FLG_FLUSH_REQ_FIFO_UFLW_MASK },
    { "FLUSH_REQ_FIFO_OFLW", AR_NIC_WC_ERR_FIRST_FLG_FLUSH_REQ_FIFO_OFLW_BP, AR_NIC_WC_ERR_FIRST_FLG_FLUSH_REQ_FIFO_OFLW_MASK },
    { "RSPOUT1_FIFO_UFLW", AR_NIC_WC_ERR_FIRST_FLG_RSPOUT1_FIFO_UFLW_BP, AR_NIC_WC_ERR_FIRST_FLG_RSPOUT1_FIFO_UFLW_MASK },
    { "RSPOUT1_FIFO_OFLW", AR_NIC_WC_ERR_FIRST_FLG_RSPOUT1_FIFO_OFLW_BP, AR_NIC_WC_ERR_FIRST_FLG_RSPOUT1_FIFO_OFLW_MASK },
    { "RSPOUT0_FIFO_UFLW", AR_NIC_WC_ERR_FIRST_FLG_RSPOUT0_FIFO_UFLW_BP, AR_NIC_WC_ERR_FIRST_FLG_RSPOUT0_FIFO_UFLW_MASK },
    { "RSPOUT0_FIFO_OFLW", AR_NIC_WC_ERR_FIRST_FLG_RSPOUT0_FIFO_OFLW_BP, AR_NIC_WC_ERR_FIRST_FLG_RSPOUT0_FIFO_OFLW_MASK },
    { "RSPIN1_FIFO_UFLW", AR_NIC_WC_ERR_FIRST_FLG_RSPIN1_FIFO_UFLW_BP, AR_NIC_WC_ERR_FIRST_FLG_RSPIN1_FIFO_UFLW_MASK },
    { "RSPIN1_FIFO_OFLW", AR_NIC_WC_ERR_FIRST_FLG_RSPIN1_FIFO_OFLW_BP, AR_NIC_WC_ERR_FIRST_FLG_RSPIN1_FIFO_OFLW_MASK },
    { "RSPIN0_FIFO_UFLW", AR_NIC_WC_ERR_FIRST_FLG_RSPIN0_FIFO_UFLW_BP, AR_NIC_WC_ERR_FIRST_FLG_RSPIN0_FIFO_UFLW_MASK },
    { "RSPIN0_FIFO_OFLW", AR_NIC_WC_ERR_FIRST_FLG_RSPIN0_FIFO_OFLW_BP, AR_NIC_WC_ERR_FIRST_FLG_RSPIN0_FIFO_OFLW_MASK },
    { "NTWK_RSP_FIFO_UFLW", AR_NIC_WC_ERR_FIRST_FLG_NTWK_RSP_FIFO_UFLW_BP, AR_NIC_WC_ERR_FIRST_FLG_NTWK_RSP_FIFO_UFLW_MASK },
    { "NTWK_RSP_FIFO_OFLW", AR_NIC_WC_ERR_FIRST_FLG_NTWK_RSP_FIFO_OFLW_BP, AR_NIC_WC_ERR_FIRST_FLG_NTWK_RSP_FIFO_OFLW_MASK },
    { "TAG_PBE", AR_NIC_WC_ERR_FIRST_FLG_TAG_PBE_BP, AR_NIC_WC_ERR_FIRST_FLG_TAG_PBE_MASK },
    { "RSPIN1_HDR_PBE", AR_NIC_WC_ERR_FIRST_FLG_RSPIN1_HDR_PBE_BP, AR_NIC_WC_ERR_FIRST_FLG_RSPIN1_HDR_PBE_MASK },
    { "RSPIN0_HDR_PBE", AR_NIC_WC_ERR_FIRST_FLG_RSPIN0_HDR_PBE_BP, AR_NIC_WC_ERR_FIRST_FLG_RSPIN0_HDR_PBE_MASK },
    { "NTWK_RSP_HDR_PBE", AR_NIC_WC_ERR_FIRST_FLG_NTWK_RSP_HDR_PBE_BP, AR_NIC_WC_ERR_FIRST_FLG_NTWK_RSP_HDR_PBE_MASK },
    { "BUF1_MBE", AR_NIC_WC_ERR_FIRST_FLG_BUF1_MBE_BP, AR_NIC_WC_ERR_FIRST_FLG_BUF1_MBE_MASK },
    { "BUF1_SBE", AR_NIC_WC_ERR_FIRST_FLG_BUF1_SBE_BP, AR_NIC_WC_ERR_FIRST_FLG_BUF1_SBE_MASK },
    { "BUF0_MBE", AR_NIC_WC_ERR_FIRST_FLG_BUF0_MBE_BP, AR_NIC_WC_ERR_FIRST_FLG_BUF0_MBE_MASK },
    { "BUF0_SBE", AR_NIC_WC_ERR_FIRST_FLG_BUF0_SBE_BP, AR_NIC_WC_ERR_FIRST_FLG_BUF0_SBE_MASK },
    { "RSPIN1_DAT_MBE", AR_NIC_WC_ERR_FIRST_FLG_RSPIN1_DAT_MBE_BP, AR_NIC_WC_ERR_FIRST_FLG_RSPIN1_DAT_MBE_MASK },
    { "RSPIN1_DAT_SBE", AR_NIC_WC_ERR_FIRST_FLG_RSPIN1_DAT_SBE_BP, AR_NIC_WC_ERR_FIRST_FLG_RSPIN1_DAT_SBE_MASK },
    { "RSPIN0_DAT_MBE", AR_NIC_WC_ERR_FIRST_FLG_RSPIN0_DAT_MBE_BP, AR_NIC_WC_ERR_FIRST_FLG_RSPIN0_DAT_MBE_MASK },
    { "RSPIN0_DAT_SBE", AR_NIC_WC_ERR_FIRST_FLG_RSPIN0_DAT_SBE_BP, AR_NIC_WC_ERR_FIRST_FLG_RSPIN0_DAT_SBE_MASK },
    { "DIAG_ONLY", AR_NIC_WC_ERR_FIRST_FLG_DIAG_ONLY_BP, AR_NIC_WC_ERR_FIRST_FLG_DIAG_ONLY_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_err_info_buf0_detail[] = {
    { "MBE_SSID", AR_NIC_WC_ERR_INFO_BUF0_MBE_SSID_BP, AR_NIC_WC_ERR_INFO_BUF0_MBE_SSID_MASK },
    { "MBE_ADDRESS", AR_NIC_WC_ERR_INFO_BUF0_MBE_ADDRESS_BP, AR_NIC_WC_ERR_INFO_BUF0_MBE_ADDRESS_MASK },
    { "MBE_PART", AR_NIC_WC_ERR_INFO_BUF0_MBE_PART_BP, AR_NIC_WC_ERR_INFO_BUF0_MBE_PART_MASK },
    { "MBE_SYNDROME", AR_NIC_WC_ERR_INFO_BUF0_MBE_SYNDROME_BP, AR_NIC_WC_ERR_INFO_BUF0_MBE_SYNDROME_MASK },
    { "SBE_ADDRESS", AR_NIC_WC_ERR_INFO_BUF0_SBE_ADDRESS_BP, AR_NIC_WC_ERR_INFO_BUF0_SBE_ADDRESS_MASK },
    { "SBE_PART", AR_NIC_WC_ERR_INFO_BUF0_SBE_PART_BP, AR_NIC_WC_ERR_INFO_BUF0_SBE_PART_MASK },
    { "SBE_SYNDROME", AR_NIC_WC_ERR_INFO_BUF0_SBE_SYNDROME_BP, AR_NIC_WC_ERR_INFO_BUF0_SBE_SYNDROME_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_err_info_buf1_detail[] = {
    { "MBE_SSID", AR_NIC_WC_ERR_INFO_BUF1_MBE_SSID_BP, AR_NIC_WC_ERR_INFO_BUF1_MBE_SSID_MASK },
    { "MBE_ADDRESS", AR_NIC_WC_ERR_INFO_BUF1_MBE_ADDRESS_BP, AR_NIC_WC_ERR_INFO_BUF1_MBE_ADDRESS_MASK },
    { "MBE_PART", AR_NIC_WC_ERR_INFO_BUF1_MBE_PART_BP, AR_NIC_WC_ERR_INFO_BUF1_MBE_PART_MASK },
    { "MBE_SYNDROME", AR_NIC_WC_ERR_INFO_BUF1_MBE_SYNDROME_BP, AR_NIC_WC_ERR_INFO_BUF1_MBE_SYNDROME_MASK },
    { "SBE_ADDRESS", AR_NIC_WC_ERR_INFO_BUF1_SBE_ADDRESS_BP, AR_NIC_WC_ERR_INFO_BUF1_SBE_ADDRESS_MASK },
    { "SBE_PART", AR_NIC_WC_ERR_INFO_BUF1_SBE_PART_BP, AR_NIC_WC_ERR_INFO_BUF1_SBE_PART_MASK },
    { "SBE_SYNDROME", AR_NIC_WC_ERR_INFO_BUF1_SBE_SYNDROME_BP, AR_NIC_WC_ERR_INFO_BUF1_SBE_SYNDROME_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_err_info_rspin0_detail[] = {
    { "MBE_UPPER", AR_NIC_WC_ERR_INFO_RSPIN0_MBE_UPPER_BP, AR_NIC_WC_ERR_INFO_RSPIN0_MBE_UPPER_MASK },
    { "MBE_SYNDROME", AR_NIC_WC_ERR_INFO_RSPIN0_MBE_SYNDROME_BP, AR_NIC_WC_ERR_INFO_RSPIN0_MBE_SYNDROME_MASK },
    { "SBE_UPPER", AR_NIC_WC_ERR_INFO_RSPIN0_SBE_UPPER_BP, AR_NIC_WC_ERR_INFO_RSPIN0_SBE_UPPER_MASK },
    { "SBE_SYNDROME", AR_NIC_WC_ERR_INFO_RSPIN0_SBE_SYNDROME_BP, AR_NIC_WC_ERR_INFO_RSPIN0_SBE_SYNDROME_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_err_info_rspin1_detail[] = {
    { "MBE_UPPER", AR_NIC_WC_ERR_INFO_RSPIN1_MBE_UPPER_BP, AR_NIC_WC_ERR_INFO_RSPIN1_MBE_UPPER_MASK },
    { "MBE_SYNDROME", AR_NIC_WC_ERR_INFO_RSPIN1_MBE_SYNDROME_BP, AR_NIC_WC_ERR_INFO_RSPIN1_MBE_SYNDROME_MASK },
    { "SBE_UPPER", AR_NIC_WC_ERR_INFO_RSPIN1_SBE_UPPER_BP, AR_NIC_WC_ERR_INFO_RSPIN1_SBE_UPPER_MASK },
    { "SBE_SYNDROME", AR_NIC_WC_ERR_INFO_RSPIN1_SBE_SYNDROME_BP, AR_NIC_WC_ERR_INFO_RSPIN1_SBE_SYNDROME_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_err_info_cnt_sbe_buf0_detail[] = {
    { "CNT", AR_NIC_WC_ERR_INFO_CNT_SBE_BUF0_CNT_BP, AR_NIC_WC_ERR_INFO_CNT_SBE_BUF0_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_err_info_cnt_mbe_buf0_detail[] = {
    { "CNT", AR_NIC_WC_ERR_INFO_CNT_MBE_BUF0_CNT_BP, AR_NIC_WC_ERR_INFO_CNT_MBE_BUF0_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_err_info_cnt_sbe_buf1_detail[] = {
    { "CNT", AR_NIC_WC_ERR_INFO_CNT_SBE_BUF1_CNT_BP, AR_NIC_WC_ERR_INFO_CNT_SBE_BUF1_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_err_info_cnt_mbe_buf1_detail[] = {
    { "CNT", AR_NIC_WC_ERR_INFO_CNT_MBE_BUF1_CNT_BP, AR_NIC_WC_ERR_INFO_CNT_MBE_BUF1_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_err_info_cnt_sbe_rspin0_detail[] = {
    { "CNT", AR_NIC_WC_ERR_INFO_CNT_SBE_RSPIN0_CNT_BP, AR_NIC_WC_ERR_INFO_CNT_SBE_RSPIN0_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_err_info_cnt_mbe_rspin0_detail[] = {
    { "CNT", AR_NIC_WC_ERR_INFO_CNT_MBE_RSPIN0_CNT_BP, AR_NIC_WC_ERR_INFO_CNT_MBE_RSPIN0_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_err_info_cnt_sbe_rspin1_detail[] = {
    { "CNT", AR_NIC_WC_ERR_INFO_CNT_SBE_RSPIN1_CNT_BP, AR_NIC_WC_ERR_INFO_CNT_SBE_RSPIN1_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_err_info_cnt_mbe_rspin1_detail[] = {
    { "CNT", AR_NIC_WC_ERR_INFO_CNT_MBE_RSPIN1_CNT_BP, AR_NIC_WC_ERR_INFO_CNT_MBE_RSPIN1_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_prf_rsp_bytes_rcvd_detail[] = {
    { "CNT", AR_NIC_WC_PRF_RSP_BYTES_RCVD_CNT_BP, AR_NIC_WC_PRF_RSP_BYTES_RCVD_CNT_MASK },
    { NULL, 0, 0 }
};
static const generic_mmrd_t _ar_nic_wc_prf_bufs_vld_detail[] = {
    { "CNT", AR_NIC_WC_PRF_BUFS_VLD_CNT_BP, AR_NIC_WC_PRF_BUFS_VLD_CNT_MASK },
    { NULL, 0, 0 }
};

/*
 *  AR WC MMR DECLARATIONS
 */
static const generic_mmr_t _ar_nic_wc_cfg_params = {
    "AR_NIC_WC_CFG_PARAMS", AR_NIC_WC_CFG_PARAMS, 8, 1, _ar_nic_wc_cfg_params_detail
};
static const generic_mmr_t _ar_nic_wc_wc_mmr_ring_0_hi_wc = {
    "AR_NIC_WC_WC_MMR_RING_0_HI_WC", AR_NIC_WC_WC_MMR_RING_0_HI_WC, 8, 1, _ar_nic_wc_wc_mmr_ring_0_hi_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_mmr_ring_0_mid_wc = {
    "AR_NIC_WC_WC_MMR_RING_0_MID_WC", AR_NIC_WC_WC_MMR_RING_0_MID_WC, 8, 1, _ar_nic_wc_wc_mmr_ring_0_mid_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_mmr_ring_0_lo_wc = {
    "AR_NIC_WC_WC_MMR_RING_0_LO_WC", AR_NIC_WC_WC_MMR_RING_0_LO_WC, 8, 1, _ar_nic_wc_wc_mmr_ring_0_lo_wc_detail
};
static const generic_mmr_t _ar_nic_wc_err_flg_1_hi_wc = {
    "AR_NIC_WC_ERR_FLG_1_HI_WC", AR_NIC_WC_ERR_FLG_1_HI_WC, 8, 1, _ar_nic_wc_err_flg_1_hi_wc_detail
};
static const generic_mmr_t _ar_nic_wc_err_flg_1_mid_wc = {
    "AR_NIC_WC_ERR_FLG_1_MID_WC", AR_NIC_WC_ERR_FLG_1_MID_WC, 8, 1, _ar_nic_wc_err_flg_1_mid_wc_detail
};
static const generic_mmr_t _ar_nic_wc_err_flg_1_lo_wc = {
    "AR_NIC_WC_ERR_FLG_1_LO_WC", AR_NIC_WC_ERR_FLG_1_LO_WC, 8, 1, _ar_nic_wc_err_flg_1_lo_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_parb_flit_2_hi_wc = {
    "AR_NIC_WC_WC_PARB_FLIT_2_HI_WC", AR_NIC_WC_WC_PARB_FLIT_2_HI_WC, 8, 1, _ar_nic_wc_wc_parb_flit_2_hi_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_parb_flit_2_mid_wc = {
    "AR_NIC_WC_WC_PARB_FLIT_2_MID_WC", AR_NIC_WC_WC_PARB_FLIT_2_MID_WC, 8, 1, _ar_nic_wc_wc_parb_flit_2_mid_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_parb_flit_2_lo_wc = {
    "AR_NIC_WC_WC_PARB_FLIT_2_LO_WC", AR_NIC_WC_WC_PARB_FLIT_2_LO_WC, 8, 1, _ar_nic_wc_wc_parb_flit_2_lo_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_ssid_rsp_flit_3_hi_wc = {
    "AR_NIC_WC_WC_SSID_RSP_FLIT_3_HI_WC", AR_NIC_WC_WC_SSID_RSP_FLIT_3_HI_WC, 8, 1, _ar_nic_wc_wc_ssid_rsp_flit_3_hi_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_ssid_rsp_flit_3_mid_wc = {
    "AR_NIC_WC_WC_SSID_RSP_FLIT_3_MID_WC", AR_NIC_WC_WC_SSID_RSP_FLIT_3_MID_WC, 8, 1, _ar_nic_wc_wc_ssid_rsp_flit_3_mid_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_ssid_rsp_flit_3_lo_wc = {
    "AR_NIC_WC_WC_SSID_RSP_FLIT_3_LO_WC", AR_NIC_WC_WC_SSID_RSP_FLIT_3_LO_WC, 8, 1, _ar_nic_wc_wc_ssid_rsp_flit_3_lo_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_top_misc_4_hi_wc = {
    "AR_NIC_WC_WC_TOP_MISC_4_HI_WC", AR_NIC_WC_WC_TOP_MISC_4_HI_WC, 8, 1, _ar_nic_wc_wc_top_misc_4_hi_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_top_misc_4_mid_wc = {
    "AR_NIC_WC_WC_TOP_MISC_4_MID_WC", AR_NIC_WC_WC_TOP_MISC_4_MID_WC, 8, 1, _ar_nic_wc_wc_top_misc_4_mid_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_top_misc_4_lo_wc = {
    "AR_NIC_WC_WC_TOP_MISC_4_LO_WC", AR_NIC_WC_WC_TOP_MISC_4_LO_WC, 8, 1, _ar_nic_wc_wc_top_misc_4_lo_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_flush_misc_5_hi_wc = {
    "AR_NIC_WC_WC_FLUSH_MISC_5_HI_WC", AR_NIC_WC_WC_FLUSH_MISC_5_HI_WC, 8, 1, _ar_nic_wc_wc_flush_misc_5_hi_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_flush_misc_5_mid_wc = {
    "AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC", AR_NIC_WC_WC_FLUSH_MISC_5_MID_WC, 8, 1, _ar_nic_wc_wc_flush_misc_5_mid_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_flush_misc_5_lo_wc = {
    "AR_NIC_WC_WC_FLUSH_MISC_5_LO_WC", AR_NIC_WC_WC_FLUSH_MISC_5_LO_WC, 8, 1, _ar_nic_wc_wc_flush_misc_5_lo_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf0_rspin_flit_6_hi_wc = {
    "AR_NIC_WC_WC_BUF0_RSPIN_FLIT_6_HI_WC", AR_NIC_WC_WC_BUF0_RSPIN_FLIT_6_HI_WC, 8, 1, _ar_nic_wc_wc_buf0_rspin_flit_6_hi_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf0_rspin_flit_6_mid_wc = {
    "AR_NIC_WC_WC_BUF0_RSPIN_FLIT_6_MID_WC", AR_NIC_WC_WC_BUF0_RSPIN_FLIT_6_MID_WC, 8, 1, _ar_nic_wc_wc_buf0_rspin_flit_6_mid_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf0_rspin_flit_6_lo_wc = {
    "AR_NIC_WC_WC_BUF0_RSPIN_FLIT_6_LO_WC", AR_NIC_WC_WC_BUF0_RSPIN_FLIT_6_LO_WC, 8, 1, _ar_nic_wc_wc_buf0_rspin_flit_6_lo_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf0_lm_data1_7_hi_wc = {
    "AR_NIC_WC_WC_BUF0_LM_DATA1_7_HI_WC", AR_NIC_WC_WC_BUF0_LM_DATA1_7_HI_WC, 8, 1, _ar_nic_wc_wc_buf0_lm_data1_7_hi_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf0_lm_data1_7_mid_wc = {
    "AR_NIC_WC_WC_BUF0_LM_DATA1_7_MID_WC", AR_NIC_WC_WC_BUF0_LM_DATA1_7_MID_WC, 8, 1, _ar_nic_wc_wc_buf0_lm_data1_7_mid_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf0_lm_data1_7_lo_wc = {
    "AR_NIC_WC_WC_BUF0_LM_DATA1_7_LO_WC", AR_NIC_WC_WC_BUF0_LM_DATA1_7_LO_WC, 8, 1, _ar_nic_wc_wc_buf0_lm_data1_7_lo_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf0_lm_data2_8_hi_wc = {
    "AR_NIC_WC_WC_BUF0_LM_DATA2_8_HI_WC", AR_NIC_WC_WC_BUF0_LM_DATA2_8_HI_WC, 8, 1, _ar_nic_wc_wc_buf0_lm_data2_8_hi_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf0_lm_data2_8_mid_wc = {
    "AR_NIC_WC_WC_BUF0_LM_DATA2_8_MID_WC", AR_NIC_WC_WC_BUF0_LM_DATA2_8_MID_WC, 8, 1, _ar_nic_wc_wc_buf0_lm_data2_8_mid_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf0_lm_data2_8_lo_wc = {
    "AR_NIC_WC_WC_BUF0_LM_DATA2_8_LO_WC", AR_NIC_WC_WC_BUF0_LM_DATA2_8_LO_WC, 8, 1, _ar_nic_wc_wc_buf0_lm_data2_8_lo_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf0_lm_data3_9_hi_wc = {
    "AR_NIC_WC_WC_BUF0_LM_DATA3_9_HI_WC", AR_NIC_WC_WC_BUF0_LM_DATA3_9_HI_WC, 8, 1, _ar_nic_wc_wc_buf0_lm_data3_9_hi_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf0_lm_data3_9_mid_wc = {
    "AR_NIC_WC_WC_BUF0_LM_DATA3_9_MID_WC", AR_NIC_WC_WC_BUF0_LM_DATA3_9_MID_WC, 8, 1, _ar_nic_wc_wc_buf0_lm_data3_9_mid_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf0_lm_data3_9_lo_wc = {
    "AR_NIC_WC_WC_BUF0_LM_DATA3_9_LO_WC", AR_NIC_WC_WC_BUF0_LM_DATA3_9_LO_WC, 8, 1, _ar_nic_wc_wc_buf0_lm_data3_9_lo_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf0_rspout_flit_a_hi_wc = {
    "AR_NIC_WC_WC_BUF0_RSPOUT_FLIT_A_HI_WC", AR_NIC_WC_WC_BUF0_RSPOUT_FLIT_A_HI_WC, 8, 1, _ar_nic_wc_wc_buf0_rspout_flit_a_hi_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf0_rspout_flit_a_mid_wc = {
    "AR_NIC_WC_WC_BUF0_RSPOUT_FLIT_A_MID_WC", AR_NIC_WC_WC_BUF0_RSPOUT_FLIT_A_MID_WC, 8, 1, _ar_nic_wc_wc_buf0_rspout_flit_a_mid_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf0_rspout_flit_a_lo_wc = {
    "AR_NIC_WC_WC_BUF0_RSPOUT_FLIT_A_LO_WC", AR_NIC_WC_WC_BUF0_RSPOUT_FLIT_A_LO_WC, 8, 1, _ar_nic_wc_wc_buf0_rspout_flit_a_lo_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf1_rspin_flit_b_hi_wc = {
    "AR_NIC_WC_WC_BUF1_RSPIN_FLIT_B_HI_WC", AR_NIC_WC_WC_BUF1_RSPIN_FLIT_B_HI_WC, 8, 1, _ar_nic_wc_wc_buf1_rspin_flit_b_hi_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf1_rspin_flit_b_mid_wc = {
    "AR_NIC_WC_WC_BUF1_RSPIN_FLIT_B_MID_WC", AR_NIC_WC_WC_BUF1_RSPIN_FLIT_B_MID_WC, 8, 1, _ar_nic_wc_wc_buf1_rspin_flit_b_mid_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf1_rspin_flit_b_lo_wc = {
    "AR_NIC_WC_WC_BUF1_RSPIN_FLIT_B_LO_WC", AR_NIC_WC_WC_BUF1_RSPIN_FLIT_B_LO_WC, 8, 1, _ar_nic_wc_wc_buf1_rspin_flit_b_lo_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf1_lm_data1_c_hi_wc = {
    "AR_NIC_WC_WC_BUF1_LM_DATA1_C_HI_WC", AR_NIC_WC_WC_BUF1_LM_DATA1_C_HI_WC, 8, 1, _ar_nic_wc_wc_buf1_lm_data1_c_hi_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf1_lm_data1_c_mid_wc = {
    "AR_NIC_WC_WC_BUF1_LM_DATA1_C_MID_WC", AR_NIC_WC_WC_BUF1_LM_DATA1_C_MID_WC, 8, 1, _ar_nic_wc_wc_buf1_lm_data1_c_mid_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf1_lm_data1_c_lo_wc = {
    "AR_NIC_WC_WC_BUF1_LM_DATA1_C_LO_WC", AR_NIC_WC_WC_BUF1_LM_DATA1_C_LO_WC, 8, 1, _ar_nic_wc_wc_buf1_lm_data1_c_lo_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf1_lm_data2_d_hi_wc = {
    "AR_NIC_WC_WC_BUF1_LM_DATA2_D_HI_WC", AR_NIC_WC_WC_BUF1_LM_DATA2_D_HI_WC, 8, 1, _ar_nic_wc_wc_buf1_lm_data2_d_hi_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf1_lm_data2_d_mid_wc = {
    "AR_NIC_WC_WC_BUF1_LM_DATA2_D_MID_WC", AR_NIC_WC_WC_BUF1_LM_DATA2_D_MID_WC, 8, 1, _ar_nic_wc_wc_buf1_lm_data2_d_mid_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf1_lm_data2_d_lo_wc = {
    "AR_NIC_WC_WC_BUF1_LM_DATA2_D_LO_WC", AR_NIC_WC_WC_BUF1_LM_DATA2_D_LO_WC, 8, 1, _ar_nic_wc_wc_buf1_lm_data2_d_lo_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf1_lm_data3_e_hi_wc = {
    "AR_NIC_WC_WC_BUF1_LM_DATA3_E_HI_WC", AR_NIC_WC_WC_BUF1_LM_DATA3_E_HI_WC, 8, 1, _ar_nic_wc_wc_buf1_lm_data3_e_hi_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf1_lm_data3_e_mid_wc = {
    "AR_NIC_WC_WC_BUF1_LM_DATA3_E_MID_WC", AR_NIC_WC_WC_BUF1_LM_DATA3_E_MID_WC, 8, 1, _ar_nic_wc_wc_buf1_lm_data3_e_mid_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf1_lm_data3_e_lo_wc = {
    "AR_NIC_WC_WC_BUF1_LM_DATA3_E_LO_WC", AR_NIC_WC_WC_BUF1_LM_DATA3_E_LO_WC, 8, 1, _ar_nic_wc_wc_buf1_lm_data3_e_lo_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf1_rspout_flit_f_hi_wc = {
    "AR_NIC_WC_WC_BUF1_RSPOUT_FLIT_F_HI_WC", AR_NIC_WC_WC_BUF1_RSPOUT_FLIT_F_HI_WC, 8, 1, _ar_nic_wc_wc_buf1_rspout_flit_f_hi_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf1_rspout_flit_f_mid_wc = {
    "AR_NIC_WC_WC_BUF1_RSPOUT_FLIT_F_MID_WC", AR_NIC_WC_WC_BUF1_RSPOUT_FLIT_F_MID_WC, 8, 1, _ar_nic_wc_wc_buf1_rspout_flit_f_mid_wc_detail
};
static const generic_mmr_t _ar_nic_wc_wc_buf1_rspout_flit_f_lo_wc = {
    "AR_NIC_WC_WC_BUF1_RSPOUT_FLIT_F_LO_WC", AR_NIC_WC_WC_BUF1_RSPOUT_FLIT_F_LO_WC, 8, 1, _ar_nic_wc_wc_buf1_rspout_flit_f_lo_wc_detail
};
static const generic_mmr_t _ar_nic_wc_mux_sel_ff_hi_wc = {
    "AR_NIC_WC_MUX_SEL_FF_HI_WC", AR_NIC_WC_MUX_SEL_FF_HI_WC, 8, 1, _ar_nic_wc_mux_sel_ff_hi_wc_detail
};
static const generic_mmr_t _ar_nic_wc_mux_sel_ff_mid_wc = {
    "AR_NIC_WC_MUX_SEL_FF_MID_WC", AR_NIC_WC_MUX_SEL_FF_MID_WC, 8, 1, _ar_nic_wc_mux_sel_ff_mid_wc_detail
};
static const generic_mmr_t _ar_nic_wc_mux_sel_ff_lo_wc = {
    "AR_NIC_WC_MUX_SEL_FF_LO_WC", AR_NIC_WC_MUX_SEL_FF_LO_WC, 8, 1, _ar_nic_wc_mux_sel_ff_lo_wc_detail
};
static const generic_mmr_t _ar_nic_wc_cfg_crdts = {
    "AR_NIC_WC_CFG_CRDTS", AR_NIC_WC_CFG_CRDTS, 8, 1, _ar_nic_wc_cfg_crdts_detail
};
static const generic_mmr_t _ar_nic_wc_dbg_errinj_mem = {
    "AR_NIC_WC_DBG_ERRINJ_MEM", AR_NIC_WC_DBG_ERRINJ_MEM, 8, 1, _ar_nic_wc_dbg_errinj_mem_detail
};
static const generic_mmr_t _ar_nic_wc_dbg_errinj_bus = {
    "AR_NIC_WC_DBG_ERRINJ_BUS", AR_NIC_WC_DBG_ERRINJ_BUS, 8, 1, _ar_nic_wc_dbg_errinj_bus_detail
};
static const generic_mmr_t _ar_nic_wc_dbg_buf_inval = {
    "AR_NIC_WC_DBG_BUF_INVAL", AR_NIC_WC_DBG_BUF_INVAL, 8, 1, _ar_nic_wc_dbg_buf_inval_detail
};
static const generic_mmr_t _ar_nic_wc_sts_buf_avail = {
    "AR_NIC_WC_STS_BUF_AVAIL", AR_NIC_WC_STS_BUF_AVAIL, 8, 1, _ar_nic_wc_sts_buf_avail_detail
};
static const generic_mmr_t _ar_nic_wc_sts_buf_vld = {
    "AR_NIC_WC_STS_BUF_VLD", AR_NIC_WC_STS_BUF_VLD, 8, 1, _ar_nic_wc_sts_buf_vld_detail
};
static const generic_mmr_t _ar_nic_wc_err_flg = {
    "AR_NIC_WC_ERR_FLG", AR_NIC_WC_ERR_FLG, 8, 1, _ar_nic_wc_err_flg_detail
};
static const generic_mmr_t _ar_nic_wc_err_clr = {
    "AR_NIC_WC_ERR_CLR", AR_NIC_WC_ERR_CLR, 8, 1, _ar_nic_wc_err_clr_detail
};
static const generic_mmr_t _ar_nic_wc_err_hss_msk = {
    "AR_NIC_WC_ERR_HSS_MSK", AR_NIC_WC_ERR_HSS_MSK, 8, 1, _ar_nic_wc_err_hss_msk_detail
};
static const generic_mmr_t _ar_nic_wc_err_os_msk = {
    "AR_NIC_WC_ERR_OS_MSK", AR_NIC_WC_ERR_OS_MSK, 8, 1, _ar_nic_wc_err_os_msk_detail
};
static const generic_mmr_t _ar_nic_wc_err_first_flg = {
    "AR_NIC_WC_ERR_FIRST_FLG", AR_NIC_WC_ERR_FIRST_FLG, 8, 1, _ar_nic_wc_err_first_flg_detail
};
static const generic_mmr_t _ar_nic_wc_err_info_buf0 = {
    "AR_NIC_WC_ERR_INFO_BUF0", AR_NIC_WC_ERR_INFO_BUF0, 8, 1, _ar_nic_wc_err_info_buf0_detail
};
static const generic_mmr_t _ar_nic_wc_err_info_buf1 = {
    "AR_NIC_WC_ERR_INFO_BUF1", AR_NIC_WC_ERR_INFO_BUF1, 8, 1, _ar_nic_wc_err_info_buf1_detail
};
static const generic_mmr_t _ar_nic_wc_err_info_rspin0 = {
    "AR_NIC_WC_ERR_INFO_RSPIN0", AR_NIC_WC_ERR_INFO_RSPIN0, 8, 1, _ar_nic_wc_err_info_rspin0_detail
};
static const generic_mmr_t _ar_nic_wc_err_info_rspin1 = {
    "AR_NIC_WC_ERR_INFO_RSPIN1", AR_NIC_WC_ERR_INFO_RSPIN1, 8, 1, _ar_nic_wc_err_info_rspin1_detail
};
static const generic_mmr_t _ar_nic_wc_err_info_cnt_sbe_buf0 = {
    "AR_NIC_WC_ERR_INFO_CNT_SBE_BUF0", AR_NIC_WC_ERR_INFO_CNT_SBE_BUF0, 8, 1, _ar_nic_wc_err_info_cnt_sbe_buf0_detail
};
static const generic_mmr_t _ar_nic_wc_err_info_cnt_mbe_buf0 = {
    "AR_NIC_WC_ERR_INFO_CNT_MBE_BUF0", AR_NIC_WC_ERR_INFO_CNT_MBE_BUF0, 8, 1, _ar_nic_wc_err_info_cnt_mbe_buf0_detail
};
static const generic_mmr_t _ar_nic_wc_err_info_cnt_sbe_buf1 = {
    "AR_NIC_WC_ERR_INFO_CNT_SBE_BUF1", AR_NIC_WC_ERR_INFO_CNT_SBE_BUF1, 8, 1, _ar_nic_wc_err_info_cnt_sbe_buf1_detail
};
static const generic_mmr_t _ar_nic_wc_err_info_cnt_mbe_buf1 = {
    "AR_NIC_WC_ERR_INFO_CNT_MBE_BUF1", AR_NIC_WC_ERR_INFO_CNT_MBE_BUF1, 8, 1, _ar_nic_wc_err_info_cnt_mbe_buf1_detail
};
static const generic_mmr_t _ar_nic_wc_err_info_cnt_sbe_rspin0 = {
    "AR_NIC_WC_ERR_INFO_CNT_SBE_RSPIN0", AR_NIC_WC_ERR_INFO_CNT_SBE_RSPIN0, 8, 1, _ar_nic_wc_err_info_cnt_sbe_rspin0_detail
};
static const generic_mmr_t _ar_nic_wc_err_info_cnt_mbe_rspin0 = {
    "AR_NIC_WC_ERR_INFO_CNT_MBE_RSPIN0", AR_NIC_WC_ERR_INFO_CNT_MBE_RSPIN0, 8, 1, _ar_nic_wc_err_info_cnt_mbe_rspin0_detail
};
static const generic_mmr_t _ar_nic_wc_err_info_cnt_sbe_rspin1 = {
    "AR_NIC_WC_ERR_INFO_CNT_SBE_RSPIN1", AR_NIC_WC_ERR_INFO_CNT_SBE_RSPIN1, 8, 1, _ar_nic_wc_err_info_cnt_sbe_rspin1_detail
};
static const generic_mmr_t _ar_nic_wc_err_info_cnt_mbe_rspin1 = {
    "AR_NIC_WC_ERR_INFO_CNT_MBE_RSPIN1", AR_NIC_WC_ERR_INFO_CNT_MBE_RSPIN1, 8, 1, _ar_nic_wc_err_info_cnt_mbe_rspin1_detail
};
static const generic_mmr_t _ar_nic_wc_prf_rsp_bytes_rcvd = {
    "AR_NIC_WC_PRF_RSP_BYTES_RCVD", AR_NIC_WC_PRF_RSP_BYTES_RCVD, 8, 1, _ar_nic_wc_prf_rsp_bytes_rcvd_detail
};
static const generic_mmr_t _ar_nic_wc_prf_bufs_vld = {
    "AR_NIC_WC_PRF_BUFS_VLD", AR_NIC_WC_PRF_BUFS_VLD, 8, 1, _ar_nic_wc_prf_bufs_vld_detail
};

/*
 *  INSTALL AR WC MMRS
 */
static const generic_mmr_t* _ar_wc_mmrs[] _unused = {
    &_ar_nic_wc_cfg_params,
    &_ar_nic_wc_wc_mmr_ring_0_hi_wc,
    &_ar_nic_wc_wc_mmr_ring_0_mid_wc,
    &_ar_nic_wc_wc_mmr_ring_0_lo_wc,
    &_ar_nic_wc_err_flg_1_hi_wc,
    &_ar_nic_wc_err_flg_1_mid_wc,
    &_ar_nic_wc_err_flg_1_lo_wc,
    &_ar_nic_wc_wc_parb_flit_2_hi_wc,
    &_ar_nic_wc_wc_parb_flit_2_mid_wc,
    &_ar_nic_wc_wc_parb_flit_2_lo_wc,
    &_ar_nic_wc_wc_ssid_rsp_flit_3_hi_wc,
    &_ar_nic_wc_wc_ssid_rsp_flit_3_mid_wc,
    &_ar_nic_wc_wc_ssid_rsp_flit_3_lo_wc,
    &_ar_nic_wc_wc_top_misc_4_hi_wc,
    &_ar_nic_wc_wc_top_misc_4_mid_wc,
    &_ar_nic_wc_wc_top_misc_4_lo_wc,
    &_ar_nic_wc_wc_flush_misc_5_hi_wc,
    &_ar_nic_wc_wc_flush_misc_5_mid_wc,
    &_ar_nic_wc_wc_flush_misc_5_lo_wc,
    &_ar_nic_wc_wc_buf0_rspin_flit_6_hi_wc,
    &_ar_nic_wc_wc_buf0_rspin_flit_6_mid_wc,
    &_ar_nic_wc_wc_buf0_rspin_flit_6_lo_wc,
    &_ar_nic_wc_wc_buf0_lm_data1_7_hi_wc,
    &_ar_nic_wc_wc_buf0_lm_data1_7_mid_wc,
    &_ar_nic_wc_wc_buf0_lm_data1_7_lo_wc,
    &_ar_nic_wc_wc_buf0_lm_data2_8_hi_wc,
    &_ar_nic_wc_wc_buf0_lm_data2_8_mid_wc,
    &_ar_nic_wc_wc_buf0_lm_data2_8_lo_wc,
    &_ar_nic_wc_wc_buf0_lm_data3_9_hi_wc,
    &_ar_nic_wc_wc_buf0_lm_data3_9_mid_wc,
    &_ar_nic_wc_wc_buf0_lm_data3_9_lo_wc,
    &_ar_nic_wc_wc_buf0_rspout_flit_a_hi_wc,
    &_ar_nic_wc_wc_buf0_rspout_flit_a_mid_wc,
    &_ar_nic_wc_wc_buf0_rspout_flit_a_lo_wc,
    &_ar_nic_wc_wc_buf1_rspin_flit_b_hi_wc,
    &_ar_nic_wc_wc_buf1_rspin_flit_b_mid_wc,
    &_ar_nic_wc_wc_buf1_rspin_flit_b_lo_wc,
    &_ar_nic_wc_wc_buf1_lm_data1_c_hi_wc,
    &_ar_nic_wc_wc_buf1_lm_data1_c_mid_wc,
    &_ar_nic_wc_wc_buf1_lm_data1_c_lo_wc,
    &_ar_nic_wc_wc_buf1_lm_data2_d_hi_wc,
    &_ar_nic_wc_wc_buf1_lm_data2_d_mid_wc,
    &_ar_nic_wc_wc_buf1_lm_data2_d_lo_wc,
    &_ar_nic_wc_wc_buf1_lm_data3_e_hi_wc,
    &_ar_nic_wc_wc_buf1_lm_data3_e_mid_wc,
    &_ar_nic_wc_wc_buf1_lm_data3_e_lo_wc,
    &_ar_nic_wc_wc_buf1_rspout_flit_f_hi_wc,
    &_ar_nic_wc_wc_buf1_rspout_flit_f_mid_wc,
    &_ar_nic_wc_wc_buf1_rspout_flit_f_lo_wc,
    &_ar_nic_wc_mux_sel_ff_hi_wc,
    &_ar_nic_wc_mux_sel_ff_mid_wc,
    &_ar_nic_wc_mux_sel_ff_lo_wc,
    &_ar_nic_wc_cfg_crdts,
    &_ar_nic_wc_dbg_errinj_mem,
    &_ar_nic_wc_dbg_errinj_bus,
    &_ar_nic_wc_dbg_buf_inval,
    &_ar_nic_wc_sts_buf_avail,
    &_ar_nic_wc_sts_buf_vld,
    &_ar_nic_wc_err_flg,
    &_ar_nic_wc_err_clr,
    &_ar_nic_wc_err_hss_msk,
    &_ar_nic_wc_err_os_msk,
    &_ar_nic_wc_err_first_flg,
    &_ar_nic_wc_err_info_buf0,
    &_ar_nic_wc_err_info_buf1,
    &_ar_nic_wc_err_info_rspin0,
    &_ar_nic_wc_err_info_rspin1,
    &_ar_nic_wc_err_info_cnt_sbe_buf0,
    &_ar_nic_wc_err_info_cnt_mbe_buf0,
    &_ar_nic_wc_err_info_cnt_sbe_buf1,
    &_ar_nic_wc_err_info_cnt_mbe_buf1,
    &_ar_nic_wc_err_info_cnt_sbe_rspin0,
    &_ar_nic_wc_err_info_cnt_mbe_rspin0,
    &_ar_nic_wc_err_info_cnt_sbe_rspin1,
    &_ar_nic_wc_err_info_cnt_mbe_rspin1,
    &_ar_nic_wc_prf_rsp_bytes_rcvd,
    &_ar_nic_wc_prf_bufs_vld,
    NULL
};

#endif
