/*
 * Transaction Management Defines.
 * Copyright 2012 Cray Inc. All Rights Reserved.
 */
#ifndef TRANSACTIONMGT_DEFS			// Check to see if these defines are already called
#define TRANSACTIONMGT_DEFS	 1		// Make sure they are not called again
	#define   TRANSACTIONMGT_BASE_ADDR                                    	0x0000000	// Base Loop Address for MMR Verilog
	#define   A_NIC_RXDESC_ERRLOC_NONE                                    	0       	// This value is not used.
	#define   A_NIC_RXDESC_ERRLOC_SREQ                                    	1       	// If an error is reported in the RX_STATUS field of the CPU RX descriptor, that error was detected while processing one of the transaction's request packets at the source endpoint.
	#define   A_NIC_RXDESC_ERRLOC_DREQ                                    	2       	// If an error is reported in the RX_STATUS field of the CPU RX descriptor, that error was detected while processing one of the transaction's request packets at the destination endpoint.
	#define   A_NIC_RXDESC_ERRLOC_SRSP                                    	3       	// If an error is reported in the RX_STATUS field of the CPU RX descriptor, that error was detected while processing one of the transaction's response packets at the source endpoint.
	#define   A_IOMMU_EC_RESERVED_0                                       	0    	
	#define   A_IOMMU_EC_INVALID_TRANSLATION_CONTEXT                      	1    	
	#define   A_IOMMU_EC_IO_PAGE_FAULT                                    	2    	
	#define   A_IOMMU_EC_PAGE_TAB_HARDWARE_ERROR                          	3    	
	#define   A_IOMMU_EC_ILLEGAL_COMMAND_ERROR                            	0x4    	
	#define   A_IOMMU_EC_RESERVED_5                                       	5    	
	#define   A_IOMMU_EC_RESERVED_6                                       	6    	
	#define   A_IOMMU_EC_RESERVED_7                                       	7    	
	#define   A_IOMMU_EC_RESERVED_8                                       	8    	
	#define   A_IOMMU_EC_RESERVED_9                                       	9    	
	#define   A_IOMMU_EC_RESERVED_10                                      	10   	
	#define   A_IOMMU_EC_RESERVED_11                                      	11   	
	#define   A_IOMMU_EC_RESERVED_12                                      	12   	
	#define   A_IOMMU_EC_RESERVED_13                                      	13   	
	#define   A_IOMMU_EC_RESERVED_14                                      	14   	
	#define   A_IOMMU_EC_RESERVED_15                                      	15   	
	#define   A_RC_NON_MIN_HASHED                                         	0    	// Routing is non-minimal. The route used to reach the destination may not be the most direct.
	#define   A_RC_MIN_HASHED                                             	1    	// Routing is minimal. The route used to reach the destination is chosen from the set of routes that are the most direct (use the least number of hops).
	#define   A_RC_MIN_NON_HASHED                                         	3    	// Routing is minimal.
	#define   A_RC_ADAPTIVE_0                                             	4    	// Routing is adaptive. The route taken by a given packet, to reach its destination, depends on the level of congestion present in the network.
	#define   A_RC_ADAPTIVE_1                                             	5    	// See A_RC_ADAPTIVE_0.
	#define   A_RC_ADAPTIVE_2                                             	6    	// See A_RC_ADAPTIVE_0.
	#define   A_RC_ADAPTIVE_3                                             	7    	// See A_RC_ADAPTIVE_0.
	#define   A_NIC_CQE_SRC_NONE                                          	0       	// Empty CQ entry.
	#define   A_NIC_CQE_SRC_BTE                                           	1       	// The CQE was generated by the BTE block.
	#define   A_NIC_CQE_SRC_SSID                                          	2       	// The CQE was generated by the SSID block.
	#define   A_NIC_CQE_SRC_RMT                                           	3       	// The CQE was generated by the RMT block.
	#define   A_NIC_CQE_SRC_DLA                                           	4       	// The CQE was generated by the DLA block.
	#define   A_NIC_CQE_INFO_TX_DONE                                      	0       	// The CQE was generated by BTE to report the completion of processing of a TX descriptor.
	#define   A_NIC_CQE_INFO_TX_DONE_NO_SSID                              	1       	// The CQE was generated by BTE to report the completion of processing of a BTE TX descriptor.
	#define   A_NIC_CQE_INFO_ENQ_STATUS                                   	2       	// The CQE was generated by BTE to report the enqueue status of an FMA launched BTE transaction. (Section 1.3.5.4)
	#define   A_NIC_CQE_INFO_CQWRITE                                      	0       	// The CQE was generated using the FMA CQ_WRITE doorbell mechanism. (Section 6.2.1.3.1 on page 325)
	#define   A_NIC_CQE_INFO_CPLTN_SREQ                                   	1       	// The CQE reports the completion of a transaction and either the transaction was error free (CQE Status = STATUS_OK) or the error that occurred was detected while processing one of the transaction's request packets at the source endpoint.
	#define   A_NIC_CQE_INFO_CPLTN_DREQ                                   	2       	// The CQE reports the completion of a transaction and an error was detected while processing one of the transaction's request packets at the destination endpoint.
	#define   A_NIC_CQE_INFO_CPLTN_SRSP                                   	3       	// The CQE reports the completion of a transaction and an error was detected while processing one of the transaction's response packets at the source endpoint.
	#define   A_NIC_CQE_INFO_ALLOC_STATUS                                 	0       	// The CQE was generated by DLA and reports the status of a FIFO space allocation request.
	#define   A_NIC_CQE_INFO_DLA_MARKER                                   	1       	// The CQE was generated by DLA and reports a Marker notification.
// Register defines from table # 7 of transactionmgt.xml - A_NIC_DLA_ALLOC_STATUS_CQE
	#define   A_NIC_DLA_ALLOC_STATUS_CQE_UNUSED_47_44_WIDTH               	4       	
	#define   A_NIC_DLA_ALLOC_STATUS_CQE_UNUSED_47_44_MSB                 	47      	
	#define   A_NIC_DLA_ALLOC_STATUS_CQE_UNUSED_47_44_LSB                 	44      	
	#define   A_NIC_DLA_ALLOC_STATUS_CQE_UNSUCCESSFUL_ALLOC_CNT_WIDTH     	20      	
	#define   A_NIC_DLA_ALLOC_STATUS_CQE_UNSUCCESSFUL_ALLOC_CNT_MSB       	43      	
	#define   A_NIC_DLA_ALLOC_STATUS_CQE_UNSUCCESSFUL_ALLOC_CNT_LSB       	24      	
	#define   A_NIC_DLA_ALLOC_STATUS_CQE_UNUSED_23_20_WIDTH               	4       	
	#define   A_NIC_DLA_ALLOC_STATUS_CQE_UNUSED_23_20_MSB                 	23      	
	#define   A_NIC_DLA_ALLOC_STATUS_CQE_UNUSED_23_20_LSB                 	20      	
	#define   A_NIC_DLA_ALLOC_STATUS_CQE_LAST_BLOCK_ID_WIDTH              	20      	
	#define   A_NIC_DLA_ALLOC_STATUS_CQE_LAST_BLOCK_ID_MSB                	19      	
	#define   A_NIC_DLA_ALLOC_STATUS_CQE_LAST_BLOCK_ID_LSB                	0       	
// Register defines from table # 8 of transactionmgt.xml - A_NIC_DLA_MARKER_CQE
	#define   A_NIC_DLA_MARKER_CQE_UNUSED_47_32_WIDTH                     	16      	
	#define   A_NIC_DLA_MARKER_CQE_UNUSED_47_32_MSB                       	47      	
	#define   A_NIC_DLA_MARKER_CQE_UNUSED_47_32_LSB                       	32      	
	#define   A_NIC_DLA_MARKER_CQE_MARKER_ID_WIDTH                        	32      	
	#define   A_NIC_DLA_MARKER_CQE_MARKER_ID_MSB                          	31      	
	#define   A_NIC_DLA_MARKER_CQE_MARKER_ID_LSB                          	0       	
// Register defines from table # 10 of transactionmgt.xml - A_NIC_DLA_FIFO_FILL_LEVEL
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_63_WIDTH                   	1       	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_63_MSB                     	63      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_63_LSB                     	63      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_CONSUMED_WIDTH                    	15      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_CONSUMED_MSB                      	62      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_CONSUMED_LSB                      	48      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_47_WIDTH                   	1       	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_47_MSB                     	47      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_47_LSB                     	47      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_PR_CONSUMED_WIDTH                 	15      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_PR_CONSUMED_MSB                   	46      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_PR_CONSUMED_LSB                   	32      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_31_WIDTH                   	1       	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_31_MSB                     	31      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_31_LSB                     	31      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_HI_CD_CONSUMED_WIDTH              	15      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_HI_CD_CONSUMED_MSB                	30      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_HI_CD_CONSUMED_LSB                	16      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_15_WIDTH                   	1       	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_15_MSB                     	15      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_15_LSB                     	15      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_LO_CD_CONSUMED_WIDTH              	15      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_LO_CD_CONSUMED_MSB                	14      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_LO_CD_CONSUMED_LSB                	0       	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_127_120_WIDTH              	8       	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_127_120_MSB                	127     	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_127_120_LSB                	120     	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_127_120_MSB_NBO            	63      	// MSB with no byte offset
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_127_120_LSB_NBO            	56      	// LSB with no byte offset
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_ALLOC_COUNT_WIDTH                 	8       	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_ALLOC_COUNT_MSB                   	119     	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_ALLOC_COUNT_LSB                   	112     	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_ALLOC_COUNT_MSB_NBO               	55      	// MSB with no byte offset
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_ALLOC_COUNT_LSB_NBO               	48      	// LSB with no byte offset
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_111_WIDTH                  	1       	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_111_MSB                    	111     	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_111_LSB                    	111     	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_111_MSB_NBO                	47      	// MSB with no byte offset
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_111_LSB_NBO                	47      	// LSB with no byte offset
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_PR_RESVD_WIDTH                    	15      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_PR_RESVD_MSB                      	110     	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_PR_RESVD_LSB                      	96      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_PR_RESVD_MSB_NBO                  	46      	// MSB with no byte offset
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_PR_RESVD_LSB_NBO                  	32      	// LSB with no byte offset
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_95_WIDTH                   	1       	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_95_MSB                     	95      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_95_LSB                     	95      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_95_MSB_NBO                 	31      	// MSB with no byte offset
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_95_LSB_NBO                 	31      	// LSB with no byte offset
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_HI_CD_RESVD_WIDTH                 	15      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_HI_CD_RESVD_MSB                   	94      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_HI_CD_RESVD_LSB                   	80      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_HI_CD_RESVD_MSB_NBO               	30      	// MSB with no byte offset
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_HI_CD_RESVD_LSB_NBO               	16      	// LSB with no byte offset
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_79_WIDTH                   	1       	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_79_MSB                     	79      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_79_LSB                     	79      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_79_MSB_NBO                 	15      	// MSB with no byte offset
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_UNUSED_79_LSB_NBO                 	15      	// LSB with no byte offset
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_LO_CD_RESVD_WIDTH                 	15      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_LO_CD_RESVD_MSB                   	78      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_LO_CD_RESVD_LSB                   	64      	
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_LO_CD_RESVD_MSB_NBO               	14      	// MSB with no byte offset
	#define   A_NIC_DLA_FIFO_FILL_LEVEL_LO_CD_RESVD_LSB_NBO               	0       	// LSB with no byte offset
// Register defines from table # 16 of transactionmgt.xml - A_NIC_FLBTE_CQE
	#define   A_NIC_FLBTE_CQE_UNUSED_47_42_WIDTH                          	6       	
	#define   A_NIC_FLBTE_CQE_UNUSED_47_42_MSB                            	47      	
	#define   A_NIC_FLBTE_CQE_UNUSED_47_42_LSB                            	42      	
	#define   A_NIC_FLBTE_CQE_INSUFFICIENT_PRIV_WIDTH                     	1       	
	#define   A_NIC_FLBTE_CQE_INSUFFICIENT_PRIV_MSB                       	41      	
	#define   A_NIC_FLBTE_CQE_INSUFFICIENT_PRIV_LSB                       	41      	
	#define   A_NIC_FLBTE_CQE_BTE_UNAVAILABLE_WIDTH                       	1       	
	#define   A_NIC_FLBTE_CQE_BTE_UNAVAILABLE_MSB                         	40      	
	#define   A_NIC_FLBTE_CQE_BTE_UNAVAILABLE_LSB                         	40      	
	#define   A_NIC_FLBTE_CQE_FAILED_ENQUEUE_CNT_WIDTH                    	20      	
	#define   A_NIC_FLBTE_CQE_FAILED_ENQUEUE_CNT_MSB                      	39      	
	#define   A_NIC_FLBTE_CQE_FAILED_ENQUEUE_CNT_LSB                      	20      	
	#define   A_NIC_FLBTE_CQE_REQ_ID_WIDTH                                	20      	
	#define   A_NIC_FLBTE_CQE_REQ_ID_MSB                                  	19      	
	#define   A_NIC_FLBTE_CQE_REQ_ID_LSB                                  	0       	
// Register defines from table # 18 of transactionmgt.xml - A_NIC_RX_DESC
	#define   A_NIC_RX_DESC_IRQ_EN_WIDTH                                  	1       	
	#define   A_NIC_RX_DESC_IRQ_EN_MSB                                    	63      	
	#define   A_NIC_RX_DESC_IRQ_EN_LSB                                    	63      	
	#define   A_NIC_RX_DESC_DELAYED_IRQ_EN_WIDTH                          	1       	
	#define   A_NIC_RX_DESC_DELAYED_IRQ_EN_MSB                            	62      	
	#define   A_NIC_RX_DESC_DELAYED_IRQ_EN_LSB                            	62      	
	#define   A_NIC_RX_DESC_UNUSED_61_51_WIDTH                            	11      	
	#define   A_NIC_RX_DESC_UNUSED_61_51_MSB                              	61      	
	#define   A_NIC_RX_DESC_UNUSED_61_51_LSB                              	51      	
	#define   A_NIC_RX_DESC_PI_HINTS_2_0_WIDTH                            	3       	
	#define   A_NIC_RX_DESC_PI_HINTS_2_0_MSB                              	50      	
	#define   A_NIC_RX_DESC_PI_HINTS_2_0_LSB                              	48      	
	#define   A_NIC_RX_DESC_BASE_ADDR_47_6_WIDTH                          	42      	
	#define   A_NIC_RX_DESC_BASE_ADDR_47_6_MSB                            	47      	
	#define   A_NIC_RX_DESC_BASE_ADDR_47_6_LSB                            	6       	
	#define   A_NIC_RX_DESC_UNUSED_5_0_WIDTH                              	6       	
	#define   A_NIC_RX_DESC_UNUSED_5_0_MSB                                	5       	
	#define   A_NIC_RX_DESC_UNUSED_5_0_LSB                                	0       	
	#define   A_NIC_RX_DESC_DATA_LEN_WIDTH                                	32      	
	#define   A_NIC_RX_DESC_DATA_LEN_MSB                                  	127     	
	#define   A_NIC_RX_DESC_DATA_LEN_LSB                                  	96      	
	#define   A_NIC_RX_DESC_DATA_LEN_MSB_NBO                              	63      	// MSB with no byte offset
	#define   A_NIC_RX_DESC_DATA_LEN_LSB_NBO                              	32      	// LSB with no byte offset
	#define   A_NIC_RX_DESC_UNUSED_95_75_WIDTH                            	21      	
	#define   A_NIC_RX_DESC_UNUSED_95_75_MSB                              	95      	
	#define   A_NIC_RX_DESC_UNUSED_95_75_LSB                              	75      	
	#define   A_NIC_RX_DESC_UNUSED_95_75_MSB_NBO                          	31      	// MSB with no byte offset
	#define   A_NIC_RX_DESC_UNUSED_95_75_LSB_NBO                          	11      	// LSB with no byte offset
	#define   A_NIC_RX_DESC_RX_STATUS_WIDTH                               	6       	
	#define   A_NIC_RX_DESC_RX_STATUS_MSB                                 	74      	
	#define   A_NIC_RX_DESC_RX_STATUS_LSB                                 	69      	
	#define   A_NIC_RX_DESC_RX_STATUS_MSB_NBO                             	10      	// MSB with no byte offset
	#define   A_NIC_RX_DESC_RX_STATUS_LSB_NBO                             	5       	// LSB with no byte offset
	#define   A_NIC_RX_DESC_UNUSED_68_WIDTH                               	1       	
	#define   A_NIC_RX_DESC_UNUSED_68_MSB                                 	68      	
	#define   A_NIC_RX_DESC_UNUSED_68_LSB                                 	68      	
	#define   A_NIC_RX_DESC_UNUSED_68_MSB_NBO                             	4       	// MSB with no byte offset
	#define   A_NIC_RX_DESC_UNUSED_68_LSB_NBO                             	4       	// LSB with no byte offset
	#define   A_NIC_RX_DESC_RX_ERR_LOC_WIDTH                              	2       	
	#define   A_NIC_RX_DESC_RX_ERR_LOC_MSB                                	67      	
	#define   A_NIC_RX_DESC_RX_ERR_LOC_LSB                                	66      	
	#define   A_NIC_RX_DESC_RX_ERR_LOC_MSB_NBO                            	3       	// MSB with no byte offset
	#define   A_NIC_RX_DESC_RX_ERR_LOC_LSB_NBO                            	2       	// LSB with no byte offset
	#define   A_NIC_RX_DESC_USER_DATA_AVAIL_WIDTH                         	1       	
	#define   A_NIC_RX_DESC_USER_DATA_AVAIL_MSB                           	65      	
	#define   A_NIC_RX_DESC_USER_DATA_AVAIL_LSB                           	65      	
	#define   A_NIC_RX_DESC_USER_DATA_AVAIL_MSB_NBO                       	1       	// MSB with no byte offset
	#define   A_NIC_RX_DESC_USER_DATA_AVAIL_LSB_NBO                       	1       	// LSB with no byte offset
	#define   A_NIC_RX_DESC_DMA_COMPLETE_WIDTH                            	1       	
	#define   A_NIC_RX_DESC_DMA_COMPLETE_MSB                              	64      	
	#define   A_NIC_RX_DESC_DMA_COMPLETE_LSB                              	64      	
	#define   A_NIC_RX_DESC_DMA_COMPLETE_MSB_NBO                          	0       	// MSB with no byte offset
	#define   A_NIC_RX_DESC_DMA_COMPLETE_LSB_NBO                          	0       	// LSB with no byte offset
	#define   A_NIC_RX_DESC_USER_DATA_WIDTH                               	64      	
	#define   A_NIC_RX_DESC_USER_DATA_MSB                                 	191     	
	#define   A_NIC_RX_DESC_USER_DATA_LSB                                 	128     	
	#define   A_NIC_RX_DESC_USER_DATA_MSB_NBO                             	63      	// MSB with no byte offset
	#define   A_NIC_RX_DESC_USER_DATA_LSB_NBO                             	0       	// LSB with no byte offset
// Register defines from table # 26 of transactionmgt.xml - A_NIC_CE_RESULT
	#define   A_NIC_CE_RESULT_DONE_WIDTH                                  	1       	
	#define   A_NIC_CE_RESULT_DONE_MSB                                    	63      	
	#define   A_NIC_CE_RESULT_DONE_LSB                                    	63      	
	#define   A_NIC_CE_RESULT_UNUSED_62_WIDTH                             	1       	
	#define   A_NIC_CE_RESULT_UNUSED_62_MSB                               	62      	
	#define   A_NIC_CE_RESULT_UNUSED_62_LSB                               	62      	
	#define   A_NIC_CE_RESULT_STATUS_WIDTH                                	6       	
	#define   A_NIC_CE_RESULT_STATUS_MSB                                  	61      	
	#define   A_NIC_CE_RESULT_STATUS_LSB                                  	56      	
	#define   A_NIC_CE_RESULT_FP_EXCEPTION_WIDTH                          	4       	
	#define   A_NIC_CE_RESULT_FP_EXCEPTION_MSB                            	55      	
	#define   A_NIC_CE_RESULT_FP_EXCEPTION_LSB                            	52      	
	#define   A_NIC_CE_RESULT_UNUSED_51_40_WIDTH                          	12      	
	#define   A_NIC_CE_RESULT_UNUSED_51_40_MSB                            	51      	
	#define   A_NIC_CE_RESULT_UNUSED_51_40_LSB                            	40      	
	#define   A_NIC_CE_RESULT_REDUCTN_ID_WIDTH                            	40      	
	#define   A_NIC_CE_RESULT_REDUCTN_ID_MSB                              	39      	
	#define   A_NIC_CE_RESULT_REDUCTN_ID_LSB                              	0       	
	#define   A_NIC_CE_RESULT_RESULTANT1_WIDTH                            	64      	
	#define   A_NIC_CE_RESULT_RESULTANT1_MSB                              	127     	
	#define   A_NIC_CE_RESULT_RESULTANT1_LSB                              	64      	
	#define   A_NIC_CE_RESULT_RESULTANT1_MSB_NBO                          	63      	// MSB with no byte offset
	#define   A_NIC_CE_RESULT_RESULTANT1_LSB_NBO                          	0       	// LSB with no byte offset
	#define   A_NIC_CE_RESULT_RESULTANT2_WIDTH                            	64      	
	#define   A_NIC_CE_RESULT_RESULTANT2_MSB                              	191     	
	#define   A_NIC_CE_RESULT_RESULTANT2_LSB                              	128     	
	#define   A_NIC_CE_RESULT_RESULTANT2_MSB_NBO                          	63      	// MSB with no byte offset
	#define   A_NIC_CE_RESULT_RESULTANT2_LSB_NBO                          	0       	// LSB with no byte offset
// Register defines from table # 27 of transactionmgt.xml - A_NIC_CE_CQE
	#define   A_NIC_CE_CQE_TRANS_TYPE_WIDTH                               	1       	
	#define   A_NIC_CE_CQE_TRANS_TYPE_MSB                                 	47      	
	#define   A_NIC_CE_CQE_TRANS_TYPE_LSB                                 	47      	
	#define   A_NIC_CE_CQE_RESERVED_46_WIDTH                              	1       	
	#define   A_NIC_CE_CQE_RESERVED_46_MSB                                	46      	
	#define   A_NIC_CE_CQE_RESERVED_46_LSB                                	46      	
	#define   A_NIC_CE_CQE_CE_ID_WIDTH                                    	6       	
	#define   A_NIC_CE_CQE_CE_ID_MSB                                      	45      	
	#define   A_NIC_CE_CQE_CE_ID_LSB                                      	40      	
	#define   A_NIC_CE_CQE_REDUCTN_ID_WIDTH                               	40      	
	#define   A_NIC_CE_CQE_REDUCTN_ID_MSB                                 	39      	
	#define   A_NIC_CE_CQE_REDUCTN_ID_LSB                                 	0       	
// Register defines from table # 29 of transactionmgt.xml - A_NIC_PTE_V1
	#define   A_NIC_PTE_V1_RESERVED_63_WIDTH                              	1       	
	#define   A_NIC_PTE_V1_RESERVED_63_MSB                                	63      	
	#define   A_NIC_PTE_V1_RESERVED_63_LSB                                	63      	
	#define   A_NIC_PTE_V1_IW_WIDTH                                       	1       	
	#define   A_NIC_PTE_V1_IW_MSB                                         	62      	
	#define   A_NIC_PTE_V1_IW_LSB                                         	62      	
	#define   A_NIC_PTE_V1_IR_WIDTH                                       	1       	
	#define   A_NIC_PTE_V1_IR_MSB                                         	61      	
	#define   A_NIC_PTE_V1_IR_LSB                                         	61      	
	#define   A_NIC_PTE_V1_RESERVED_60_WIDTH                              	1       	
	#define   A_NIC_PTE_V1_RESERVED_60_MSB                                	60      	
	#define   A_NIC_PTE_V1_RESERVED_60_LSB                                	60      	
	#define   A_NIC_PTE_V1_IGNORED_59_WIDTH                               	1       	
	#define   A_NIC_PTE_V1_IGNORED_59_MSB                                 	59      	
	#define   A_NIC_PTE_V1_IGNORED_59_LSB                                 	59      	
	#define   A_NIC_PTE_V1_RESERVED_58_52_WIDTH                           	7       	
	#define   A_NIC_PTE_V1_RESERVED_58_52_MSB                             	58      	
	#define   A_NIC_PTE_V1_RESERVED_58_52_LSB                             	52      	
	#define   A_NIC_PTE_V1_ADDR_WIDTH                                     	40      	
	#define   A_NIC_PTE_V1_ADDR_MSB                                       	51      	
	#define   A_NIC_PTE_V1_ADDR_LSB                                       	12      	
	#define   A_NIC_PTE_V1_RESERVED_11_1_WIDTH                            	11      	
	#define   A_NIC_PTE_V1_RESERVED_11_1_MSB                              	11      	
	#define   A_NIC_PTE_V1_RESERVED_11_1_LSB                              	1       	
	#define   A_NIC_PTE_V1_P_WIDTH                                        	1       	
	#define   A_NIC_PTE_V1_P_MSB                                          	0       	
	#define   A_NIC_PTE_V1_P_LSB                                          	0       	
// Register defines from table # 30 of transactionmgt.xml - A_NIC_PTE_V2
	#define   A_NIC_PTE_V2_IGNORED_63_WIDTH                               	1       	
	#define   A_NIC_PTE_V2_IGNORED_63_MSB                                 	63      	
	#define   A_NIC_PTE_V2_IGNORED_63_LSB                                 	63      	
	#define   A_NIC_PTE_V2_RESERVED_62_WIDTH                              	1       	
	#define   A_NIC_PTE_V2_RESERVED_62_MSB                                	62      	
	#define   A_NIC_PTE_V2_RESERVED_62_LSB                                	62      	
	#define   A_NIC_PTE_V2_ADDR_WIDTH                                     	50      	
	#define   A_NIC_PTE_V2_ADDR_MSB                                       	61      	
	#define   A_NIC_PTE_V2_ADDR_LSB                                       	12      	
	#define   A_NIC_PTE_V2_RESERVED_11_WIDTH                              	1       	
	#define   A_NIC_PTE_V2_RESERVED_11_MSB                                	11      	
	#define   A_NIC_PTE_V2_RESERVED_11_LSB                                	11      	
	#define   A_NIC_PTE_V2_IGNORED_10_8_WIDTH                             	3       	
	#define   A_NIC_PTE_V2_IGNORED_10_8_MSB                               	10      	
	#define   A_NIC_PTE_V2_IGNORED_10_8_LSB                               	8       	
	#define   A_NIC_PTE_V2_RESERVED_7_WIDTH                               	1       	
	#define   A_NIC_PTE_V2_RESERVED_7_MSB                                 	7       	
	#define   A_NIC_PTE_V2_RESERVED_7_LSB                                 	7       	
	#define   A_NIC_PTE_V2_IGNORED_6_2_WIDTH                              	5       	
	#define   A_NIC_PTE_V2_IGNORED_6_2_MSB                                	6       	
	#define   A_NIC_PTE_V2_IGNORED_6_2_LSB                                	2       	
	#define   A_NIC_PTE_V2_WRITE_WIDTH                                    	1       	
	#define   A_NIC_PTE_V2_WRITE_MSB                                      	1       	
	#define   A_NIC_PTE_V2_WRITE_LSB                                      	1       	
	#define   A_NIC_PTE_V2_READ_WIDTH                                     	1       	
	#define   A_NIC_PTE_V2_READ_MSB                                       	0       	
	#define   A_NIC_PTE_V2_READ_LSB                                       	0       	
// Register defines from table # 32 of transactionmgt.xml - A_NIC_MMU_ELOG
	#define   A_NIC_MMU_ELOG_EVENT_CODE_WIDTH                             	4       	
	#define   A_NIC_MMU_ELOG_EVENT_CODE_MSB                               	63      	
	#define   A_NIC_MMU_ELOG_EVENT_CODE_LSB                               	60      	
	#define   A_NIC_MMU_ELOG_ERROR_CODE_WIDTH                             	4       	
	#define   A_NIC_MMU_ELOG_ERROR_CODE_MSB                               	59      	
	#define   A_NIC_MMU_ELOG_ERROR_CODE_LSB                               	56      	
	#define   A_NIC_MMU_ELOG_RSVD_55_50_WIDTH                             	6       	
	#define   A_NIC_MMU_ELOG_RSVD_55_50_MSB                               	55      	
	#define   A_NIC_MMU_ELOG_RSVD_55_50_LSB                               	50      	
	#define   A_NIC_MMU_ELOG_WT_WIDTH                                     	1       	
	#define   A_NIC_MMU_ELOG_WT_MSB                                       	49      	
	#define   A_NIC_MMU_ELOG_WT_LSB                                       	49      	
	#define   A_NIC_MMU_ELOG_RD_WIDTH                                     	1       	
	#define   A_NIC_MMU_ELOG_RD_MSB                                       	48      	
	#define   A_NIC_MMU_ELOG_RD_LSB                                       	48      	
	#define   A_NIC_MMU_ELOG_RSVD_47_34_WIDTH                             	14      	
	#define   A_NIC_MMU_ELOG_RSVD_47_34_MSB                               	47      	
	#define   A_NIC_MMU_ELOG_RSVD_47_34_LSB                               	34      	
	#define   A_NIC_MMU_ELOG_SRC_WIDTH                                    	2       	
	#define   A_NIC_MMU_ELOG_SRC_MSB                                      	33      	
	#define   A_NIC_MMU_ELOG_SRC_LSB                                      	32      	
	#define   A_NIC_MMU_ELOG_RSVD_31_4_WIDTH                              	28      	
	#define   A_NIC_MMU_ELOG_RSVD_31_4_MSB                                	31      	
	#define   A_NIC_MMU_ELOG_RSVD_31_4_LSB                                	4       	
	#define   A_NIC_MMU_ELOG_TC_WIDTH                                     	4       	
	#define   A_NIC_MMU_ELOG_TC_MSB                                       	3       	
	#define   A_NIC_MMU_ELOG_TC_LSB                                       	0       	
	#define   A_NIC_MMU_ELOG_RSVD_63_48_WIDTH                             	16      	
	#define   A_NIC_MMU_ELOG_RSVD_63_48_MSB                               	127     	
	#define   A_NIC_MMU_ELOG_RSVD_63_48_LSB                               	112     	
	#define   A_NIC_MMU_ELOG_RSVD_63_48_MSB_NBO                           	63      	// MSB with no byte offset
	#define   A_NIC_MMU_ELOG_RSVD_63_48_LSB_NBO                           	48      	// LSB with no byte offset
	#define   A_NIC_MMU_ELOG_ADDRESS_WIDTH                                	48      	
	#define   A_NIC_MMU_ELOG_ADDRESS_MSB                                  	111     	
	#define   A_NIC_MMU_ELOG_ADDRESS_LSB                                  	64      	
	#define   A_NIC_MMU_ELOG_ADDRESS_MSB_NBO                              	47      	// MSB with no byte offset
	#define   A_NIC_MMU_ELOG_ADDRESS_LSB_NBO                              	0       	// LSB with no byte offset
	#define   A_NIC_MMU_ELOG_ILL_CMD_OP0_50_0_WIDTH                       	51      	
	#define   A_NIC_MMU_ELOG_ILL_CMD_OP0_50_0_MSB                         	50      	
	#define   A_NIC_MMU_ELOG_ILL_CMD_OP0_50_0_LSB                         	0       	
	#define   A_NIC_MMU_ELOG_ILL_CMD_INDEX_WIDTH                          	5       	
	#define   A_NIC_MMU_ELOG_ILL_CMD_INDEX_MSB                            	55      	
	#define   A_NIC_MMU_ELOG_ILL_CMD_INDEX_LSB                            	51      	
	#define   A_NIC_MMU_ELOG_ILL_CMD_OPCODE_WIDTH                         	4       	
	#define   A_NIC_MMU_ELOG_ILL_CMD_OPCODE_MSB                           	59      	
	#define   A_NIC_MMU_ELOG_ILL_CMD_OPCODE_LSB                           	56      	
	#define   A_NIC_MMU_ELOG_ILL_CMD_OP1_WIDTH                            	64      	
	#define   A_NIC_MMU_ELOG_ILL_CMD_OP1_MSB                              	127     	
	#define   A_NIC_MMU_ELOG_ILL_CMD_OP1_LSB                              	64      	
	#define   A_NIC_MMU_ELOG_ILL_CMD_OP1_MSB_NBO                          	63      	// MSB with no byte offset
	#define   A_NIC_MMU_ELOG_ILL_CMD_OP1_LSB_NBO                          	0       	// LSB with no byte offset
// Register defines from table # 36 of transactionmgt.xml - A_NIC_CQ_USER_WIN
	#define   A_NIC_CQ_USER_WIN_IRQ_MASK_WIDTH                            	1       	
	#define   A_NIC_CQ_USER_WIN_IRQ_MASK_MSB                              	63      	
	#define   A_NIC_CQ_USER_WIN_IRQ_MASK_LSB                              	63      	
	#define   A_NIC_CQ_USER_WIN_UNUSED_62_29_WIDTH                        	34      	
	#define   A_NIC_CQ_USER_WIN_UNUSED_62_29_MSB                          	62      	
	#define   A_NIC_CQ_USER_WIN_UNUSED_62_29_LSB                          	29      	
	#define   A_NIC_CQ_USER_WIN_RD_IDX_WIDTH                              	29      	
	#define   A_NIC_CQ_USER_WIN_RD_IDX_MSB                                	28      	
	#define   A_NIC_CQ_USER_WIN_RD_IDX_LSB                                	0       	
// Register defines from table # 37 of transactionmgt.xml - A_NIC_CQE
	#define   A_NIC_CQE_FULL_WIDTH                                        	1       	
	#define   A_NIC_CQE_FULL_MSB                                          	63      	
	#define   A_NIC_CQE_FULL_LSB                                          	63      	
	#define   A_NIC_CQE_SOURCE_WIDTH                                      	3       	
	#define   A_NIC_CQE_SOURCE_MSB                                        	62      	
	#define   A_NIC_CQE_SOURCE_LSB                                        	60      	
	#define   A_NIC_CQE_RESERVED_59_58_WIDTH                              	2       	
	#define   A_NIC_CQE_RESERVED_59_58_MSB                                	59      	
	#define   A_NIC_CQE_RESERVED_59_58_LSB                                	58      	
	#define   A_NIC_CQE_INFO_WIDTH                                        	2       	
	#define   A_NIC_CQE_INFO_MSB                                          	57      	
	#define   A_NIC_CQE_INFO_LSB                                          	56      	
	#define   A_NIC_CQE_REM_OVERRUN_WIDTH                                 	1       	
	#define   A_NIC_CQE_REM_OVERRUN_MSB                                   	55      	
	#define   A_NIC_CQE_REM_OVERRUN_LSB                                   	55      	
	#define   A_NIC_CQE_RESERVED_54_WIDTH                                 	1       	
	#define   A_NIC_CQE_RESERVED_54_MSB                                   	54      	
	#define   A_NIC_CQE_RESERVED_54_LSB                                   	54      	
	#define   A_NIC_CQE_STATUS_WIDTH                                      	6       	
	#define   A_NIC_CQE_STATUS_MSB                                        	53      	
	#define   A_NIC_CQE_STATUS_LSB                                        	48      	
	#define   A_NIC_CQE_SW_DATA_WIDTH                                     	48      	
	#define   A_NIC_CQE_SW_DATA_MSB                                       	47      	
	#define   A_NIC_CQE_SW_DATA_LSB                                       	0       	

#define A_NIC_DLA_ALLOC_STATUS_CQE_UNUSED_47_44_MASK ( ( (ULL) 1 << A_NIC_DLA_ALLOC_STATUS_CQE_UNUSED_47_44_WIDTH ) - 1 ) \
  << A_NIC_DLA_ALLOC_STATUS_CQE_UNUSED_47_44_LSB
#define A_NIC_DLA_ALLOC_STATUS_CQE_UNSUCCESSFUL_ALLOC_CNT_MASK ( ( (ULL) 1 << A_NIC_DLA_ALLOC_STATUS_CQE_UNSUCCESSFUL_ALLOC_CNT_WIDTH ) - 1 ) \
  << A_NIC_DLA_ALLOC_STATUS_CQE_UNSUCCESSFUL_ALLOC_CNT_LSB
#define A_NIC_DLA_ALLOC_STATUS_CQE_UNUSED_23_20_MASK ( ( (ULL) 1 << A_NIC_DLA_ALLOC_STATUS_CQE_UNUSED_23_20_WIDTH ) - 1 ) \
  << A_NIC_DLA_ALLOC_STATUS_CQE_UNUSED_23_20_LSB
#define A_NIC_DLA_ALLOC_STATUS_CQE_LAST_BLOCK_ID_MASK ( ( (ULL) 1 << A_NIC_DLA_ALLOC_STATUS_CQE_LAST_BLOCK_ID_WIDTH ) - 1 ) \
  << A_NIC_DLA_ALLOC_STATUS_CQE_LAST_BLOCK_ID_LSB

#define A_NIC_DLA_MARKER_CQE_UNUSED_47_32_MASK ( ( (ULL) 1 << A_NIC_DLA_MARKER_CQE_UNUSED_47_32_WIDTH ) - 1 ) \
  << A_NIC_DLA_MARKER_CQE_UNUSED_47_32_LSB
#define A_NIC_DLA_MARKER_CQE_MARKER_ID_MASK ( ( (ULL) 1 << A_NIC_DLA_MARKER_CQE_MARKER_ID_WIDTH ) - 1 ) \
  << A_NIC_DLA_MARKER_CQE_MARKER_ID_LSB

#define A_NIC_FLBTE_CQE_UNUSED_47_42_MASK ( ( (ULL) 1 << A_NIC_FLBTE_CQE_UNUSED_47_42_WIDTH ) - 1 ) \
  << A_NIC_FLBTE_CQE_UNUSED_47_42_LSB
#define A_NIC_FLBTE_CQE_INSUFFICIENT_PRIV_MASK ( ( (ULL) 1 << A_NIC_FLBTE_CQE_INSUFFICIENT_PRIV_WIDTH ) - 1 ) \
  << A_NIC_FLBTE_CQE_INSUFFICIENT_PRIV_LSB
#define A_NIC_FLBTE_CQE_BTE_UNAVAILABLE_MASK ( ( (ULL) 1 << A_NIC_FLBTE_CQE_BTE_UNAVAILABLE_WIDTH ) - 1 ) \
  << A_NIC_FLBTE_CQE_BTE_UNAVAILABLE_LSB
#define A_NIC_FLBTE_CQE_FAILED_ENQUEUE_CNT_MASK ( ( (ULL) 1 << A_NIC_FLBTE_CQE_FAILED_ENQUEUE_CNT_WIDTH ) - 1 ) \
  << A_NIC_FLBTE_CQE_FAILED_ENQUEUE_CNT_LSB
#define A_NIC_FLBTE_CQE_REQ_ID_WIDTH_MASK ( ( (ULL) 1 << A_NIC_FLBTE_CQE_REQ_ID_WIDTH ) - 1 ) \
  << A_NIC_FLBTE_CQE_REQ_ID_LSB

#define A_NIC_CE_CQE_TRANS_TYPE_MASK ( ( (ULL) 1 << A_NIC_CE_CQE_TRANS_TYPE_WIDTH ) - 1 ) \
  << A_NIC_CE_CQE_TRANS_TYPE_LSB
#define A_NIC_CE_CQE_RESERVED_46_MASK ( ( (ULL) 1 << A_NIC_CE_CQE_RESERVED_46_WIDTH ) - 1 ) \
  << A_NIC_CE_CQE_RESERVED_46_LSB
#define A_NIC_CE_CQE_CE_ID_MASK ( ( (ULL) 1 << A_NIC_CE_CQE_CE_ID_WIDTH ) - 1 ) \
  << A_NIC_CE_CQE_CE_ID_LSB
#define A_NIC_CE_CQE_REDUCTN_ID_MASK ( ( (ULL) 1 << A_NIC_CE_CQE_REDUCTN_ID_WIDTH ) - 1 ) \
  << A_NIC_CE_CQE_REDUCTN_ID_LSB

#define RF_AR_NIC_DLA_ALLOC_STATUS_CQE_UNUSED_47_44(mmr)		FIELD(mmr,		\
									A_NIC_DLA_ALLOC_STATUS_CQE_UNUSED_47_44_LSB, \
									A_NIC_DLA_ALLOC_STATUS_CQE_UNUSED_47_44_MASK)
#define RF_AR_NIC_DLA_ALLOC_STATUS_CQE_UNSUCCESSFUL_ALLOC_CNT(mmr)	FIELD(mmr,		\
									A_NIC_DLA_ALLOC_STATUS_CQE_UNSUCCESSFUL_ALLOC_CNT_LSB, \
									A_NIC_DLA_ALLOC_STATUS_CQE_UNSUCCESSFUL_ALLOC_CNT_MASK)
#define RF_AR_NIC_DLA_ALLOC_STATUS_CQE_UNUSED_23_20(mmr)	        FIELD(mmr,		\
									A_NIC_DLA_ALLOC_STATUS_CQE_UNUSED_23_20_LSB, \
									A_NIC_DLA_ALLOC_STATUS_CQE_UNUSED_23_20_MASK)
#define RF_AR_NIC_DLA_ALLOC_STATUS_CQE_LAST_BLOCK_ID(mmr)	        FIELD(mmr,		\
									A_NIC_DLA_ALLOC_STATUS_CQE_LAST_BLOCK_ID_LSB, \
									A_NIC_DLA_ALLOC_STATUS_CQE_LAST_BLOCK_ID_MASK)

#define RF_AR_NIC_DLA_MARKER_CQE_UNUSED_47_32(mmr)	                FIELD(mmr,		\
									A_NIC_DLA_MARKER_CQE_UNUSED_47_32_LSB, \
									A_NIC_DLA_MARKER_CQE_UNUSED_47_32_MASK)
#define RF_AR_NIC_DLA_MARKER_CQE_MARKER_ID(mmr)	                        FIELD(mmr,		\
									A_NIC_DLA_MARKER_CQE_MARKER_ID_LSB, \
									A_NIC_DLA_MARKER_CQE_MARKER_ID_MASK)

#define RF_AR_NIC_FLBTE_CQE_UNUSED_47_42(mmr)	                        FIELD(mmr,		\
									A_NIC_FLBTE_CQE_UNUSED_47_42_LSB, \
									A_NIC_FLBTE_CQE_UNUSED_47_42_MASK)
/* #define RF_AR_NIC_FLBTE_CQE_INSUFFICIENT_PRIV(mmr)	                FIELD(mmr,		\ */
/* 									A_NIC_FLBTE_CQE_INSUFFICIENT_PRIV_LSB, \ */
/* 									A_NIC_FLBTE_CQE_INSUFFICIENT_PRIV_MASK) */
/* #define RF_AR_NIC_FLBTE_CQE_BTE_UNAVAILABLE(mmr)	                FIELD(mmr,		\ */
/* 									A_NIC_FLBTE_CQE_BTE_UNAVAILABLE_LSB, \ */
/* 									A_NIC_FLBTE_CQE_BTE_UNAVAILABLE_MASK) */
/* #define RF_AR_NIC_FLBTE_CQE_FAILED_ENQUEUE_CNT(mmr)	                FIELD(mmr,		\ */
/* 									A_NIC_FLBTE_CQE_FAILED_ENQUEUE_CNT_LSB, \ */
/* 									A_NIC_FLBTE_CQE_FAILED_ENQUEUE_CNT_MASK) */
#define RF_AR_NIC_FLBTE_CQE_REQ_ID_WIDTH(mmr)	                        FIELD(mmr,		\
									A_NIC_FLBTE_CQE_REQ_ID_LSB, \
									A_NIC_FLBTE_CQE_REQ_ID_WIDTH_MASK)

#define RF_AR_NIC_CE_CQE_TRANS_TYPE(mmr)	                        FIELD(mmr,		\
									A_NIC_CE_CQE_TRANS_TYPE_LSB, \
									A_NIC_CE_CQE_TRANS_TYPE_MASK)
#define RF_AR_NIC_CE_CQE_RESERVED_46(mmr)	                        FIELD(mmr,		\
									A_NIC_CE_CQE_RESERVED_46_LSB, \
									A_NIC_CE_CQE_RESERVED_46_MASK)
#define RF_AR_NIC_CE_CQE_CE_ID(mmr)	                                FIELD(mmr,		\
									A_NIC_CE_CQE_CE_ID_LSB, \
									A_NIC_CE_CQE_CE_ID_MASK)
#define RF_AR_NIC_CE_CQE_REDUCTN_ID(mmr)	                        FIELD(mmr,		\
									A_NIC_CE_CQE_REDUCTN_ID_LSB, \
									A_NIC_CE_CQE_REDUCTN_ID_MASK)

#endif 			// TRANSACTIONMGT_DEFS

